artsy/force

src/Components/Artwork/Details.tsx

Addresses [CX-3077]
Adjust Demand Icon spacing.
[CX-3077]: https://artsyproduct.atlassian.net/browse/CX-3077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Adjust Demand Icon spacing 

---

src/Components/Authentication/Validators.tsx

This PR solves [CX02622]
https://user-images.githubusercontent.com/11945712/201912102-7ba116e7-9697-452f-8715-05d4dddf1629.mov

fix: disable spaces as full name

---

src/Components/FlashBanner/EmailConfirmationCTA.tsx
src/Components/FlashBanner/EmailConfirmationLinkExpired.tsx
src/Components/FlashBanner/__tests__/FlashBanner.jest.tsx
src/Components/FlashBanner/index.tsx
src/__generated__/FlashBannerQuery.graphql.ts
src/__generated__/FlashBanner_Test_Query.graphql.ts
src/__generated__/FlashBanner_me.graphql.ts

Thanks to @dimatretyak for catching this.
Previously there was a `isServer` check that was preventing this code from executing. But _that_ was causing server/client mismatch rendering errors. So when that was fixed, this broke.
😵‍💫

fix(flashbanner): removes use of window (!)

---

cypress/e2e/shows.cy.ts

Temporarily pends spec to unblock CI

chore: pends shows spec

---

src/Components/NavBar/NavBarLoggedInActions.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotificationsIndicator.tsx
src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenuNotificationsIndicator.jest.tsx
src/Components/NavBar/helpers.ts
src/Components/NavBar/useIndicators.ts

Review app: [indicators](https://indicators.artsy.net/)

feat: removed the use of `isServer`

---

src/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
src/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
src/Components/ArtworkFilter/Utils/usePrepareFiltersForPills.ts

This PR solves [FX-4444]
| <img width="1919" alt="before" src="https://user-images.githubusercontent.com/3513494/202166589-1d79a409-1a27-4bd4-ae54-a1c4b1eef53c.png"> | <img width="1919" alt="after" src="https://user-images.githubusercontent.com/3513494/202166626-a6e76209-7237-44de-bb4e-39359cb11fdf.png"> | 
[FX-4444]: https://artsyproduct.atlassian.net/browse/FX-4444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-4444): update copy from "Artists I Follow" to "Artists You Follow"

---

src/client.tsx

Reverts artsy/force#11366
Opening this to get a passing build, I think it might be related to some Integrity issues, (but there seems to be other transient stuff going on, so hard to say atm).

Revert "chore(client): Cleanup client entrypoint"

---

src/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
src/Apps/Artist/Routes/Overview/Components/ArtistFeaturedWorksRail.tsx
src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistFeaturedWorksRail.jest.tsx
src/Apps/Artist/Routes/Overview/__tests__/ArtistOverviewRoute.jest.tsx
src/System/i18n/locales/en-US/translation.json
src/__generated__/ArtistFeaturedWorksRailQuery.graphql.ts
src/__generated__/ArtistFeaturedWorksRail_Test_Query.graphql.ts
src/__generated__/ArtistFeaturedWorksRail_artist.graphql.ts

This PR solves [GRO-1387]
We received user feedback that strongly indicated using the word Notable in this title was misleading our users. In order to clarify our intent with this rail, and reestablish good faith, we are renaming this rail 'Featured Works'.
This PR updates copy and filenames to reflect the change, and implements i18n for this rail.
[GRO-1387]: https://artsyproduct.atlassian.net/browse/GRO-1387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(GRO-1378): Rename Notable Works Rail

---

src/client.tsx

Reverts artsy/force#11367
The analytics issue was unrelated to this PR! So we're reverting the revert

Revert "Revert "chore(client): Cleanup client entrypoint""

---

src/Apps/Order/Components/ShippingArtaSummaryItem.tsx
src/Apps/Order/Routes/Review/index.tsx

This PR solves [TX-864]
This PR places shipping-related information together on the review page of the checkout flow. 
[TX-864]: https://artsyproduct.atlassian.net/browse/TX-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

perf(TX-864): place ship to and shipping together on review page

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
src/Components/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx

This PR solves [FX-4436]
| <img width="475" alt="before" src="https://user-images.githubusercontent.com/3513494/202186299-8e488bd5-1f82-4928-8527-721299d7d982.png"> | <img width="475" alt="after" src="https://user-images.githubusercontent.com/3513494/202186336-a3b648f3-badf-4038-9523-92a14361788e.png"> | 
[FX-4436]: https://artsyproduct.atlassian.net/browse/FX-4436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-4436): update names for some ways to buy filters

---

src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx
src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
src/Apps/Settings/Routes/Insights/InsightsRoute.tsx

This PR solves [CX-3125]
Remove upload artwork on small screens
| --- | --- |
| <img width="395" alt="Screenshot 2022-11-15 at 17 50 48" src="https://user-images.githubusercontent.com/11945712/201978705-675bb536-5a88-47fe-a210-63b48938001a.png"> | <img width="397" alt="Screenshot 2022-11-15 at 17 47 14" src="https://user-images.githubusercontent.com/11945712/201978729-9136a2cc-083f-4058-8eab-8e2ff1ff7689.png"> |
[CX-3125]: https://artsyproduct.atlassian.net/browse/CX-3125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove upload artwork on small screens

---

src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/Components/PhoneNumberInput/PhoneNumberInput.tsx
src/Components/PhoneNumberInput/__tests__/PhoneNumberInput.jest.tsx

This PR introduces debouncing to the phone number validation.

feat: Debounce phone number validation call

---

src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx

fix: change copy on the confirmation page

---

src/Apps/Partner/Components/PartnerShows/ShowBanner.tsx
src/__generated__/ShowBanner_Test_Query.graphql.ts
src/__generated__/ShowBanner_show.graphql.ts
src/__generated__/ShowBannersRailRendererQuery.graphql.ts
src/__generated__/partnerRoutes_ShowsQuery.graphql.ts

This PR solves [PX-5202](https://artsyproduct.atlassian.net/browse/PX-5202)
Per conversation with @dzucconi, these dimensions are wrong and should be 910 x 480, which is the the maximum dimensions the image can be displayed in this context.

bugfix(PX-5202): change show cover images to correct dimension to fix blurriness

---

src/Components/Inquiry/Views/InquiryBasicInfo.tsx
src/Components/Inquiry/__tests__/Views/InquiryBasicInfo.jest.tsx
src/__generated__/InquiryBasicInfoQuery.graphql.ts
src/__generated__/InquiryBasicInfo_Test_Query.graphql.ts
src/__generated__/InquiryBasicInfo_me.graphql.ts

This PR solves [CX-3131]
This PR updates the basic information form in the Inquiry Flow and replaces the Phone number field with Other Relative Positions
|--|--|
| ![image](https://user-images.githubusercontent.com/20655703/203377336-3444675b-b8c5-44d0-b171-1419022a8681.png) | ![image](https://user-images.githubusercontent.com/20655703/203377344-91792d47-513d-4787-b80d-9782a7fbfcb9.png) |
[CX-3131]: https://artsyproduct.atlassian.net/browse/CX-3131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3131): Replace Phone number with Other Relative Positions in Inquiry Flow

---

src/Apps/Authentication/Utils/__tests__/helpers.jest.ts
src/Apps/Authentication/Utils/helpers.ts

Missed a parens 🎨  🖌️ — added some specs.

fix(auth): correctly triggers onboarding

---

src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
src/Apps/Order/Utils/shippingUtils.ts

This PR solves [TX-907]
Fixes the problem with not being able to an address after setting an address on Order in the checkout flow.

fix: user can edit address

---

src/Apps/Order/Components/SavedAddresses.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Utils/shippingUtils.ts
src/Components/Address/ShippingAddressForm.tsx
src/Components/AddressForm.tsx

feat: getting things

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWAHowItWorksModal.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWAHowItWorksModal.jest.tsx
src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx

This PR solves [CX-3162]
Change email address from sell@artsymail.com to sell@artsy.net
[CX-3162]: https://artsyproduct.atlassian.net/browse/CX-3162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3162): change email address from sell@artsymail.com to sell@artsy.net

---

src/Components/Inquiry/Views/InquiryConfirmation.tsx

This PR updates the confirmation view design in the inquiry flow
| -- | -- |
| ![image](https://user-images.githubusercontent.com/20655703/203990027-64574a6c-dc49-4b41-a53d-00c27ea9da59.png) | ![image](https://user-images.githubusercontent.com/20655703/203989861-fa90ccb2-54bb-4614-b98a-2d89bcd44213.png) |

fix: Update confirmation view design

---

src/Components/Inquiry/Inquiry.tsx

This PR solves [CX-3192]
This PR updates the logic on the inquiry flow to show the confirmation message after skipping the Basic Info view
[CX-3192]: https://artsyproduct.atlassian.net/browse/CX-3192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3192): Update UX on Basic Info view on Inquiry flow

---

cypress/e2e/myCollection.cy.ts

I can't be sure _why_ this is suddenly failing but this update does get the tests back in working order.

Update failing mycollection cypress test

---

cypress/e2e/myCollection.cy.ts
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarClassification.jest.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarMetadata.jest.tsx
src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2Details.jest.tsx
src/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
src/Apps/Artwork/Components/TrustSignals/__tests__/AuthenticityCertificate.jest.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebar.jest.tsx
src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarClassification.ts
src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarMetadata.ts
src/Apps/__tests__/Fixtures/Artworks.ts
src/System/i18n/locales/en-US/translation.json

Old copy: This work includes a Certificate of Authenticity
New copy: Includes a Certificate of Authenticity
Jira: [FX-4324](https://artsyproduct.atlassian.net/browse/FX-4324)

feat(artwork): update certificate of authenticity copy

---

src/Apps/CollectorProfile/Components/CollectorProfileHeader/CollectorProfileHeader.tsx

This PR updates the Spacer props in the collector profile header to follow the new Palette upgrade

fix: update Spacer props

---

src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

I did the thing.
https://artsyproduct.atlassian.net/browse/GRO-1422

feat: Update info on specialist page GRO-1422

---

src/Components/Cells/CellPartnerArtist.tsx

Minor fix for artists that don't have artworks.

fix(cellpartnerartist): guard for artists without artworks

---

src/Apps/Settings/Routes/MyCollection/Components/MyCollectionEmptyState.tsx

This PR solves [CX-3184
Add tracking event for the "Upload artwork" button
As agreed with Audrey here: https://artsyproduct.atlassian.net/browse/CX-3184?focusedCommentId=53380

feat: add tracking to my collection landing page logged out

---

src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileAboutYou.tsx
src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
src/Apps/Settings/Routes/EditSettings/Components/__tests__/SettingsEditSettingsInformation.jest.tsx
src/Apps/Settings/Routes/EditSettings/Components/useUpdateSettingsInformation.ts
src/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
src/__generated__/SettingsEditProfileRoute_me.graphql.ts
src/__generated__/SettingsEditSettingsInformation_Test_Query.graphql.ts
src/__generated__/SettingsEditSettingsInformation_me.graphql.ts
src/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
src/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
src/__generated__/useUpdateSettingsInformationMutation.graphql.ts

This PR solves [CX-3178]
"Full Name" field was removed and replaced with "Price Range" field + moved components to the Account tab
| Web | mWeb |
| --- | --- |
| <img width="1192" alt="image" src="https://user-images.githubusercontent.com/36167539/206210078-c6d6ae68-0f1e-42f1-b3b2-5405c94bbe23.png"> |  <img width="481" alt="image" src="https://user-images.githubusercontent.com/36167539/206210195-c515323b-73c0-4651-b52d-0d84230e401e.png"> |
[CX-3178]: https://artsyproduct.atlassian.net/browse/CX-3178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3178): update account page

---

docs/best_practices.md

docs: fix typo

---

docs/best_practices.md

docs: links

---

src/Apps/Settings/SettingsApp.tsx
src/Components/TopContextBar.tsx

This PR solves [CX-3224]
| Web | mWeb |
| --- | --- |
| <img width="922" alt="image" src="https://user-images.githubusercontent.com/36167539/206251487-197064db-9872-45b9-8238-f2e358d4103a.png"> | <img width="568" alt="image" src="https://user-images.githubusercontent.com/36167539/206251812-b7f50b1c-f502-4f59-b68e-5bc3919724d7.png"> |
[CX-3224]: https://artsyproduct.atlassian.net/browse/CX-3224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3224): update settings header

---

src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/NotificationsListPlaceholder.tsx

This PR solves [FX-4468]
Let me know if I should spin up a review app for you!
[FX-4468]: https://artsyproduct.atlassian.net/browse/FX-4468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4468): Add skeleton loader for activity panel

---

package.json
src/Utils/resizer.ts
yarn.lock

chore(deps): bumps @artsy/img

---

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.jest.tsx
src/__generated__/ArtistAuctionResultsQuery.graphql.ts
src/__generated__/ArtistAuctionResults_artist.graphql.ts

This PR solves [DO-558]
[DO-558]: https://artsyproduct.atlassian.net/browse/DO-558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DO-558): add upcoming auctions filter

---

src/Apps/CollectorProfile/Components/CollectorProfileHeader/Components/CollectorProfileHeaderInfo.tsx

This PR solves [CX-3173]
This PR updates the design of the collector profile header on mWeb
|--|--|
| ![image](https://user-images.githubusercontent.com/20655703/207039253-e55629b2-eab8-43bf-b275-95555156bbd9.png) | ![image](https://user-images.githubusercontent.com/20655703/207039011-0b0ae628-b4dc-4617-b197-8733067fe6ed.png) |
[CX-3173]: https://artsyproduct.atlassian.net/browse/CX-3173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3173): Update collector profile info fields

---

src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotifications.tsx
src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
src/__generated__/NavBarMobileMenuNotificationsQuery.graphql.ts
src/__generated__/NavBarMobileMenuNotifications_me.graphql.ts

This PR solves [FX-4478]
Move activity panel menu item together with inbox up, so that users find them easily.
|---|---|
| ![Screenshot 2022-12-12 at 11 41 31](https://user-images.githubusercontent.com/3934579/207025532-42eb648b-8a81-42b9-aac8-b471f2eb8d6c.png)  | ![Screenshot 2022-12-12 at 11 41 18](https://user-images.githubusercontent.com/3934579/207025554-7d7bb1dc-66dd-4d8a-b51b-1d4e24edf4ee.png)  |
[FX-4478]: https://artsyproduct.atlassian.net/browse/FX-4478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4478): Re-position elements in the menu (mWeb)

---

src/Apps/Home/Components/HomeTrendingArtistsRail.tsx
src/__generated__/HomeTrendingArtistsRailQuery.graphql.ts
src/__generated__/HomeTrendingArtistsRail_Test_Query.graphql.ts
src/__generated__/HomeTrendingArtistsRail_viewer.graphql.ts

Another sibling PR to https://github.com/artsy/metaphysics/pull/4605 and https://github.com/artsy/eigen/pull/7839 this one just updates Force and is independent of the merging of the other ones.
https://artsyproduct.atlassian.net/browse/GRO-1381

feat: Use curated trending artists for home page GRO-1381

---

scripts/start.sh

Just pulling this off my working branch. Does fix the backgrounded process issue.

chore: fixes start up script to use concurrently

---

src/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx

Reverts back to snowflake header per: https://artsy.slack.com/archives/C01B2P6LJUU/p1670937681864789

fix(sell): reverts full bleed header consistency pass

---

src/Apps/CollectorProfile/CollectorProfileApp.tsx
src/Apps/CollectorProfile/collectorProfileRoutes.tsx
src/Server/middleware/hardcodedRedirects.ts

This PR solves [CX-3236]
Renamed the route from '/collection' to '/my-collection' 
[CX-3236]: https://artsyproduct.atlassian.net/browse/CX-3236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3236): change route 'collector-profile/collection' to 'collector-profile/my-collection'

---

src/Components/AuthDialog/AuthDialog.tsx
src/Utils/auth.ts

Bunch of stuff was addressed in Palette here: https://github.com/artsy/palette/pull/1236, which is already in `main`

fix(authdialog): addresses q/a items

---

src/Apps/ArtQuiz/Components/ArtQuizResultsTabs.tsx
src/System/i18n/locales/en-US/translation.json

Doesn't do anything yet; just wiring this up since we don't need a full modal dialog anymore.

feat(artquiz): adds toast email confirmation

---

.secrets.baseline
src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx

Fix the back button on the edit artwork page to behave correctly.

fix: Edit artwork form back button

---

src/Components/Artwork/Details.tsx

This PR solves [FX-4086]
Review app: [auction-labels](https://auction-labels.artsy.net/)
Auction demo: [dima-test-auction-3](https://auction-labels.artsy.net/auction/dima-test-auction-3)
| <img width="341" alt="before" src="https://user-images.githubusercontent.com/3513494/207610609-4515ec4d-d869-4b98-ac2a-739349247b35.png"> | <img width="341" alt="after" src="https://user-images.githubusercontent.com/3513494/207610650-e844fa2c-c0fa-4f9f-be26-2faa43c84564.png"> | 
[FX-4086]: https://artsyproduct.atlassian.net/browse/FX-4086?atlOrigin=eyJpIjoiNWRkNTljNzY …

chore(FX-4086): improvements for lot number and lot close labels

---

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.jest.tsx
src/__generated__/ArtistAuctionResultsQuery.graphql.ts
src/__generated__/ArtistAuctionResults_artist.graphql.ts

chore(DO-558): revert add upcoming auctions filter

---

src/System/i18n/locales/en-US/translation.json

Closes [GRO-1359](https://artsyproduct.atlassian.net/browse/GRO-1359)

fix(art-quiz): updates copy

---

src/Apps/ArtQuiz/ArtQuizApp.tsx
src/Apps/ArtQuiz/Components/ArtQuizLikedArtworks.tsx
src/Apps/ArtQuiz/Components/ArtQuizRecommendedArtists.tsx
src/Apps/ArtQuiz/Components/ArtQuizResultsEmpty.tsx
src/Apps/ArtQuiz/Components/ArtQuizTrendingArtists.tsx
src/Apps/ArtQuiz/Components/ArtQuizTrendingCollection.tsx
src/Apps/ArtQuiz/Components/ArtQuizTrendingCollections.tsx
src/Apps/ArtQuiz/Routes/ArtQuizResults.tsx
src/Apps/ArtQuiz/__tests__/ArtQuizResults.jest.tsx
src/Apps/ArtQuiz/artQuizRoutes.tsx
src/System/i18n/locales/en-US/translation.json
src/__generated__/ArtQuizLikedArtworksQuery.graphql.ts
src/__generated__/ArtQuizLikedArtworks_me.graphql.ts
src/__generated__/ArtQuizRecommendedArtistsQuery.graphql.ts
src/__generated__/ArtQuizRecommendedArtists_me.graphql.ts
src/__generated__/ArtQuizResults_Test_Query.graphql.ts
src/__generated__/ArtQuizResults_me.graphql.ts
src/__generated__/ArtQuizTrendingArtistsQuery.graphql.ts
src/__generated__/ArtQuizTrendingArtists_viewer.graphql.ts
src/__generated__/ArtQuizTrendingCollection_collection.graphql.ts
src/__generated__/ArtQuizTrendingCollectionsQuery.graphql.ts
src/__generated__/ArtQuizTrendingCollections_viewer.graphql.ts
src/__generated__/artQuizRoutes_ArtQuizResultsQuery.graphql.ts

Closes [GRO-1470](https://artsyproduct.atlassian.net/browse/GRO-1470)

feat(GRO-1470): art quiz results empty state

---

src/Apps/ArtQuiz/Components/ArtQuizLikedArtworks.tsx
src/Apps/ArtQuiz/Components/ArtQuizResultsRecommendedArtworks.tsx
src/Apps/ArtQuiz/Components/ArtQuizResultsTabs.tsx
src/Apps/ArtQuiz/__tests__/ArtQuizResults.jest.tsx
src/System/i18n/locales/en-US/translation.json
src/__generated__/ArtQuizLikedArtworksQuery.graphql.ts
src/__generated__/ArtQuizLikedArtworks_me.graphql.ts
src/__generated__/ArtQuizResultsRecommendedArtworksQuery.graphql.ts
src/__generated__/ArtQuizResultsRecommendedArtworks_me.graphql.ts

Closes [GRO-1260](https://artsyproduct.atlassian.net/browse/GRO-1260)
Just roughs this in there so we can see how these results feel and tweak from there.

feat(art-quiz): implements recommended artworks tab

---

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtworkStep.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormContext.tsx
src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx

This PR solves [CX-3215]
Implements the new My Collection artwork upload flow with three different steps (select artist, select artwork, main form). This PR only introduces the logic for the steps. The steps will be implemented later.
[CX-3215]: https://artsyproduct.atlassian.net/browse/CX-3215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: My Collection artwork upload steps

---

src/Apps/Consign/Routes/MarketingLanding/Components/CtaBanner.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/CtaSection.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/CtaBanner.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/CtaSection.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Header.jest.tsx

This PR fixes an issue with submissions missing the email address
**Context:** https://artsy.slack.com/archives/C03N12SR0RK/p1671226743277469

fix: broken submissions link

---

src/Apps/Partners/Components/PartnersLocationAutocomplete.tsx
src/Apps/Shows/Routes/ShowsAllCities.tsx
src/__generated__/PartnersLocationAutocompleteQuery.graphql.ts
src/__generated__/PartnersLocationAutocomplete_Test_Query.graphql.ts
src/__generated__/PartnersLocationAutocomplete_viewer.graphql.ts
src/__generated__/ShowsAllCities_viewer.graphql.ts
src/__generated__/showsRoutes_ShowsAllCitiesQuery.graphql.ts

Closes: [GRO-720](https://artsyproduct.atlassian.net/browse/GRO-720)

fix: differentiates city by displaying regions

---

package.json
src/Utils/resizer.ts
yarn.lock

See also: https://github.com/artsy/metaphysics/pull/4632/

fix(img): adds positron config

---

package.json
yarn.lock

chore(deps): bumps img

---

src/__generated__/useDislikeArtworkMutation.graphql.ts

fix: runs relay

---

src/Apps/ArtQuiz/ArtQuizApp.tsx
src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
src/__generated__/ArtQuizArtworks_me.graphql.ts
src/__generated__/artQuizRoutes_ArtworksQuery.graphql.ts

I wanted to just get this back to a working state while I take a look at the `AppShell` today. I'm thinking a smarter direction would be to just support the notion of "layouts" and have a few available, instead of a concoction of boolean flags like `hideNav`, `hideFooter` etc. Would be easier to understand and maintain. But in the meantime...

fix(art-quiz): temporarily fixes height

---

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormHeader.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx

Remove skip button from MyC artist upload step.

fix: Remove skip button from MyC artist upload step

---

src/Apps/CollectorProfile/collectorProfileRoutes.tsx
src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts

Address the following bug: 
https://www.notion.so/artsy/Upload-Artwork-from-MC-gives-me-an-error-82bce64f1eb448e8ac7aa2940595cf92

fix: add artwork button

---

src/Apps/CollectorProfile/Utils/ValidationSchemas.ts

This PR solves [CX-3279]
Adit validation schema 
[CX-3279]: https://artsyproduct.atlassian.net/browse/CX-3279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3279): trim the name

---

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx

Increase MyC upload flow artist step font size.

fix: Increase MyC upload flow artist step font size

---

src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsOverview.jest.tsx
src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
src/Apps/Settings/SettingsApp.tsx
src/Components/NavBar/Menus/NavBarUserMenu.tsx
src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx
src/Components/NavBar/NavBar.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotifications.tsx

This PR solves [CX-3225]
Updated the navigation menu
| Web | mWeb | mWeb expanded |
| --- | --- | --- | 
| <img width="404" alt="image" src="https://user-images.githubusercontent.com/36167539/209346195-104bebf6-9b6e-4a70-b1d8-220adb91548c.png"> | <img width="408" alt="image" src="https://user-images.githubusercontent.com/36167539/209346149-54680737-cbd7-40b6-8705-63e6d7ef999a.png"> |<img width="404" alt="image" src="https://user-images.githubusercontent.com/36167539/209346068-2554062b-6658-4ba7-9731-706dc30e4e40.png"> |
[CX-3225]: https://artsyproduct.atlassian.net/browse/CX-3225?atlOrigin=eyJpIjoiNWRkNTlj …

feat(CX-3225): update the navigation menu Web and  mWeb

---

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx

Adjusting My Collection artwork form spacing between inputs after breaking it in https://github.com/artsy/force/pull/11629

fix: Adjust My Collection form spacing between inputs

---

src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts

chore: runs relay

---

src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileSubMenu.tsx

This PR solves [CX-3283]
Added "Log Out" button to the mWeb menu
[CX-3283]: https://artsyproduct.atlassian.net/browse/CX-3283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3283): add log out button to mWeb menu

---

src/Apps/CollectorProfile/Components/CollectorProfileHeader/CollectorProfileHeader.tsx
src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileImage/Components/LocalImagePreview.tsx
src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileImage/SettingsEditProfileImage.tsx

This PR solves [CX-3277]
This PR displays the local image in the collector profile when available
[CX-3277]: https://artsyproduct.atlassian.net/browse/CX-3277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3277): Add local image in Collector Profile

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
src/Apps/Consign/Routes/SubmissionFlow/Utils/acceptableCategoriesForSubmission.ts
src/__generated__/ArtworkDetails_SubmissionFlowPrepopulatedTest_Query.graphql.ts
src/__generated__/ArtworkDetails_SubmissionFlowTest_Query.graphql.ts
src/__generated__/ArtworkDetails_myCollectionArtwork.graphql.ts
src/__generated__/ArtworkDetails_submission.graphql.ts
src/__generated__/consignFromCollectorProfileMyCollectionRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
src/__generated__/consignFromCollectorProfileMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
src/__generated__/consignFromCollectorProfileMyCollectionRoutes_myCollectionArtworkQuery.graphql.ts
src/__generated__/consignFromCollectorProfileMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
src/__generated__/consignFromMyCollectionRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
src/__generated__/consignFromMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
src/__generated__/consignFromMyCollectionRoutes_myCollectionArtworkQuery.graphql.ts
src/__generated__/consignFromMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
src/__generated__/consignRoutes_artworkDetailsQuery.graphql.ts
src/__generated__/consignRoutes_contactInformationQuery.graphql.ts
src/__generated__/consignRoutes_uploadPhotosQuery.graphql.ts
src/__generated__/redirects_submission.graphql.ts

This PR solves [CX-3157]
- Adds the Category Field to SWA form
[CX-3157]: https://artsyproduct.atlassian.net/browse/CX-3157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3157): Force - Add Medium to SWA Form

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtworkStep.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArworkSearch.tsx
src/__generated__/MyCollectionArworkSearchQuery.graphql.ts

Adjusting a few My Collection artwork form details to fix bugs.

fix: Adjust My Collection artwork form details

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

This PR solves [CX-3271]
- This PR removes the zip code field from the SWA submission form
[CX-3271]: https://artsyproduct.atlassian.net/browse/CX-3271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3271): Remove zip code from swa form

---

.secrets.baseline
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormContext.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArworkSearch.tsx
src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
src/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts
src/__generated__/MyCollectionArtworkFormArtistStep_me.graphql.ts
src/__generated__/MyCollectionCreateArtworkTest_Query.graphql.ts
src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts
src/__generated__/myCollectionRoutes_MyCollectionArtworkUploadQuery.graphql.ts

This PR solves [CX-3211]
Skip artwork step if artist has no artworks in My Collection upload flow.
[CX-3211]: https://artsyproduct.atlassian.net/browse/CX-3211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Skip artwork step if artist has no artworks

---

src/Components/AuthDialog/Utils/formatErrorMessage.ts
src/Components/AuthDialog/Views/AuthDialogForgotPassword.tsx
src/Components/AuthDialog/Views/AuthDialogLogin.tsx
src/Components/AuthDialog/Views/AuthDialogSignUp.tsx

Good morning 2023.
Running down the rollout of this new auth dialog component this week. This PR just improves some of our existing error messages that we display to the user. These are distinct from the inline validation errors that happen on a per-field basis.

feat(authdialog): improves error message handling

---

src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
src/Components/NavBar/menuData.ts

Reopening from upstream - replaces #11668.
https://artsyproduct.atlassian.net/browse/GRO-1462

chore: Minor navbar copy changes GRO-1462

---

src/Apps/Artist/Components/ArtistInsights/ArtistInsightBadges.tsx

Sibling of https://github.com/artsy/metaphysics/pull/4666 and just updates the placeholder.
https://artsyproduct.atlassian.net/browse/GRO-1440

chore: Minor artist insights copy changes GRO-1440

---

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtworkStep.tsx

Reset My Collection form when going back from artwork step.

fix: Reset My Collection form when going back from artwork step

---

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx

Reset My Collection form correctly when skipping artist step.

fix: Reset My Collection form correctly when skipping artist step

---

.vscode/launch.json

This PR enables debugging the active file on VSCode
https://user-images.githubusercontent.com/11945712/210609197-ca927acf-f387-4a3e-ab77-01b6751931b0.mov

feat: support debugging active file

---

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArworkSearch.tsx
src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
src/Components/Artwork/GridItem.tsx
src/Components/Artwork/Metadata.tsx
src/Components/Artwork/__tests__/GridItem.jest.tsx
src/Components/Artwork/__tests__/Metadata.jest.tsx
src/__generated__/MyCollectionArtworkFormArtistStep_me.graphql.ts
src/__generated__/MyCollectionCreateArtworkTest_Query.graphql.ts
src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts
src/__generated__/myCollectionRoutes_MyCollectionArtworkUploadQuery.graphql.ts

Addresses [CX-3308]
Add onClick correctly to MyC form artwork grid items
[CX-3308]: https://artsyproduct.atlassian.net/browse/CX-3308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Adjust onClick behaviour in MyC form artwork grid

---

src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
src/__generated__/MyCollectionArtworkFormArtistStep_me.graphql.ts
src/__generated__/MyCollectionCreateArtworkTest_Query.graphql.ts
src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts
src/__generated__/myCollectionRoutes_MyCollectionArtworkUploadQuery.graphql.ts

This PR solves [CX-3308]
Scroll to top when entering next step in My Collection upload flow.
[CX-3308]: https://artsyproduct.atlassian.net/browse/CX-3308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Scroll to top when entering next step in My Collection upload flow

---

package.json
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtworkStep.tsx
src/Apps/MyCollection/Routes/Hooks/useMyCollectionTracking.tsx
yarn.lock

Addresses [CX-3317]
My Collection uploading flow tracking.
[CX-3317]: https://artsyproduct.atlassian.net/browse/CX-3317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: My Collection uploading flow tracking

---

src/Components/NavBar/NavBar.tsx

This PR solves [CX-3289]
This PR adds the experience of expanding the search bar when it is focused on Mobile view
https://user-images.githubusercontent.com/20655703/211069455-5cdf246a-52a6-4148-b099-0116971ef01b.mov
https://user-images.githubusercontent.com/20655703/211069501-c2b5ab74-5e19-4943-b3f0-ff1142cdc357.mov
[CX-3289]: https://artsyproduct.atlassian.net/browse/CX-3289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3289): Expand the search bar on focus on mWeb

---

src/Apps/CollectorProfile/Components/CollectorProfileHeader/CollectorProfileHeader.tsx
src/Apps/CollectorProfile/Components/CollectorProfileHeader/__tests__/CollectorProfileHeader.jest.tsx
src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
src/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
src/Apps/Settings/SettingsApp.tsx
src/Components/NavBar/Menus/NavBarUserMenu.tsx
src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
src/__generated__/SettingsEditProfileRoute_me.graphql.ts
src/__generated__/SettingsEditSettingsRoute_me.graphql.ts
src/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
src/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts

This PR solves [CX-3318]
This PR updates the URLs of the Edit Settings and Edit Profile tabs
[CX-3318]: https://artsyproduct.atlassian.net/browse/CX-3318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3318): Update Edit Profile and Edit Settings URLs

---

src/Apps/Debug/DebugAuth.tsx
src/Apps/Debug/debugRoutes.tsx
src/Components/AuthDialog/AuthDialog.tsx
src/Components/AuthDialog/AuthDialogContext.tsx
src/Components/AuthDialog/Hooks/__tests__/useAfterAuthenticationRedirectUrl.jest.ts
src/Components/AuthDialog/Hooks/useAfterAuthenticationRedirect.ts
src/Components/AuthDialog/Hooks/useAfterAuthenticationRedirectUrl.ts
src/Components/AuthDialog/Hooks/useAuthDialogTracking.ts
src/Components/AuthDialog/Hooks/useElligibleForOnboarding.ts
src/Components/AuthDialog/Views/AuthDialogForgotPassword.tsx
src/Components/AuthDialog/Views/AuthDialogLogin.tsx
src/Components/AuthDialog/Views/AuthDialogSignUp.tsx
src/Components/AuthDialog/Views/__tests__/AuthDialogForgotPassword.jest.tsx
src/Components/AuthDialog/useAuthDialog.tsx
src/Components/NavBar/NavBar.tsx
src/Components/NavBar/NavBarLoggedOutActions.tsx
src/System/Router/Boot.tsx
src/System/Router/__tests__/buildClientApp.jest.tsx

This looks ready to go — passing against the existing Integrity specs, but will wait until Monday morning to merge and begin rollout. Shoutout Integrity for catching a missing bit of tracking.

feat(authdialog): feature flag rollout

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArworkSearch.tsx

Addresses [CX-3308]
My Collection upload flow artist not found message.
[CX-3308]: https://artsyproduct.atlassian.net/browse/CX-3308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: My Collection upload flow artist not found message

---

src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/FeaturedCollectionRailEntity.tsx
src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.jest.tsx
src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
src/__generated__/FeaturedCollectionRailEntity_member.graphql.ts
src/__generated__/FeaturedCollectionsRails_collectionGroup.graphql.ts
src/__generated__/collectRoutes_CollectionQuery.graphql.ts

An image was missing and the fragment type was set to `any`, so this page was 500ing. I extracted the fragment and cleaned up the component.

fix(collection): fixes null check for missing images

---

src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
src/Apps/Settings/Routes/MyCollection/Components/MyCollectionBenefits.tsx
src/Components/StepsWithImage.tsx

This PR solves [CX-3320]
- UI Updates to SWA submission confirmation page
[CX-3320]: https://artsyproduct.atlassian.net/browse/CX-3320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3320): SWA Confirmation Page Update

---

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/HideUpcomingFilter.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
src/Apps/Artist/Utils/allowedAuctionResultFilters.ts
src/__generated__/ArtistAuctionResultsQuery.graphql.ts
src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
src/__generated__/ArtistAuctionResults_artist.graphql.ts
src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts

Addresses [CX-3221]
Add "hide upcoming auction results" filter.
[CX-3221]: https://artsyproduct.atlassian.net/browse/CX-3221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add hide upcoming auction results filter

---

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
src/__generated__/ArtistAuctionResultsQuery.graphql.ts
src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
src/__generated__/ArtistAuctionResults_artist.graphql.ts
src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts

Addresses [CX-3281]
Add number of auction results to the section.
| web | mWeb |
| --- | --- |
|![Screenshot 2023-01-12 at 14 26 14](https://user-images.githubusercontent.com/4691889/212078797-2e3d5086-2b20-4d0c-9f60-f275a9777d45.png) | ![Screenshot 2023-01-12 at 14 26 49](https://user-images.githubusercontent.com/4691889/212078849-eecb87aa-0ed7-4207-997a-c25fa5514cac.png)|
[CX-3281]: https://artsyproduct.atlassian.net/browse/CX-3281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add number of auction results to section

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
src/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx
src/Apps/Auction/Components/AuctionArtworkFilter.tsx
src/Apps/Collect/Routes/Collect/index.tsx
src/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
src/Apps/Example/Routes/ArtworkFilter/ExampleArtworkFilterRoute.tsx
src/Apps/Fair/Routes/FairArtworks.tsx
src/Apps/Gene/Components/GeneArtworkFilter.tsx
src/Apps/Partner/Routes/Works/index.tsx
src/Apps/Partner/Routes/__tests__/Works.jest.tsx
src/Apps/Partner/partnerRoutes.tsx
src/Apps/Search/Routes/SearchResultsArtworks.tsx
src/Apps/Show/Components/ShowArtworks.tsx
src/Apps/Tag/Components/TagArtworkFilter.tsx

Review app: [updated-sort-options](http://updated-sort-options.artsy.net/)
This PR solves [FX-4541]
* [Artist](https://updated-sort-options.artsy.net/artist/anish-kapoor/works-for-sale)
* [Collect](https://updated-sort-options.artsy.net/collect)
* [Collection](https://updated-sort-options.artsy.net/collection/painting)
* [Fair](https://updated-sort-options.artsy.net/fair/middle-eastern-galleries-now/artworks)
* [Gene](https://updated-sort-options.artsy.net/gene/east-village-art)
* [Show](https://updated-sort-options.artsy.net/show/dab-art-art-in-the-time-of-corona)
* [Tag](https://updated-sort-options.artsy.net/tag/horse)
* [Search Results](https://updated-sort-options.artsy.net/search?term=sculpture)
* …

chore: update sort options

---

.circleci/config.yml

Fixes an issue where review apps were no longer building. More info in [this slack convo](https://artsy.slack.com/archives/CA8SANW3W/p1673545688780529).

fix(review-app): Fix ref to artsy docker instance

---

src/Apps/Consign/Routes/ConsignmentInquiry/Components/ConsignmentInquiryForm.tsx
src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiry.tsx
src/Apps/Consign/Routes/ConsignmentInquiry/__tests__/ConsignmentInquiry.jest.tsx
src/Apps/Consign/Routes/ConsignmentInquiry/utils/validation.ts

This PR solves [CX-3300]
- Remove Phone input validation from Consignment Inquiry form 
https://user-images.githubusercontent.com/18648835/211615497-ede13b0b-70fd-437e-a16f-7f17687de804.mov
[CX-3300]: https://artsyproduct.atlassian.net/browse/CX-3300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix(CX-3300): Remove Phone validation in Consignment Inquiry

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
src/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx
src/Apps/Auction/Components/AuctionArtworkFilter.tsx
src/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
src/Apps/Example/Routes/ArtworkFilter/ExampleArtworkFilterRoute.tsx
src/Apps/Fair/Routes/FairArtworks.tsx
src/Apps/Gene/Components/GeneArtworkFilter.tsx
src/Apps/Partner/Routes/Works/index.tsx
src/Apps/Search/Routes/SearchResultsArtworks.tsx
src/Apps/Show/Components/ShowArtworks.tsx
src/Apps/Tag/Components/TagArtworkFilter.tsx

This PR solves [FX-4541]
[FX-4541]: https://artsyproduct.atlassian.net/browse/FX-4541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FX-4541): incorrect price sort options order

---

scripts/uploadToS3.js

Solves an issue we saw through the CircleCI incident, where an error in the upload process failed to stop a deploy from going out.

fix(ci): Exit if error on S3 asset upload during deploy

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilter.jest.tsx
src/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx
src/Apps/Collect/Routes/Collect/index.tsx
src/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
src/Apps/Example/Routes/ArtworkFilter/ExampleArtworkFilterRoute.tsx
src/Apps/Fair/Routes/FairArtworks.tsx
src/Apps/Gene/Components/GeneArtworkFilter.tsx
src/Apps/Partner/Routes/Works/index.tsx
src/Apps/Partner/Routes/__tests__/Works.jest.tsx
src/Apps/Search/Routes/SearchResultsArtworks.tsx
src/Apps/Show/Components/ShowArtworks.tsx
src/Apps/Tag/Components/TagArtworkFilter.tsx

This PR solves [FX-4540]
Review app: [rename-default-sort](https://rename-default-sort-option.artsy.net)
* [Artist](https://rename-default-sort-option.artsy.net/artist/anish-kapoor/works-for-sale)
* [Artist Series](https://rename-default-sort-option.artsy.net/artist-series/andy-warhol-marilyn-monroe)
* [Collect](https://rename-default-sort-option.artsy.net/collect)
* [Collection](https://rename-default-sort-option.artsy.net/collection/painting)
* [Fair](https://rename-default-sort-option.artsy.net/fair/middle-eastern-galleries-now/artworks)
* [Gene](https://rename-default-sort-option.artsy.net/gene/east-village-art)
* [Show](https://rename-default-sort-option.artsy.net/show/dab-art-art-in-the-time-of-corona)
* …

chore(FX-4540): rename "Default" sort option to "Recommended"

---

.secrets.baseline
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormMain.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx

https://user-images.githubusercontent.com/36167539/212967771-556dd904-38d1-499b-8f37-68dd1e35d84f.mov

fix: fix navigation after artwork deletion

---

src/Components/Footer/Footer.tsx
src/Server/middleware/hardcodedRedirects.ts

[GRO-1471]
Removing art-appraisal from the footer -- will wait for the auctions team to confirm whether they want to remove the art-appraisal view altogether.
[GRO-1471]: https://artsyproduct.atlassian.net/browse/GRO-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: rm art appraisal from footer

---

src/Apps/Auction/Components/Form/IdentityVerificationWarning.tsx
src/Apps/Auction/Routes/AuctionConfirmRegistrationRoute.tsx
src/Apps/Auction/Routes/__tests__/AuctionConfirmRegistrationRoute.jest.tsx

This PR solves [TX-1001]
This PR updates confirm registration form(allows to enter phone number) to fix registration to the auctions with required identity verification when user has already saved credit card.
Steps to reproduce this bug:
- Register a new user
- Add credit card at the [Saved Payment Details page](https://staging.artsy.net/settings/payments)
- Check that mobile number is empty at the [Edit Settings](https://staging.artsy.net/settings/edit-settings)
- Open auction with required identity verification
- Press `Register to Bid` button
- Try to fill the form
**Updated confirm registration forms**
<details><summary>Auction with required identity verification and empty phone number</summary>
</details>
<details><summary>Auction without required …

fix: update confirm registration form

---

src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
src/Components/NavBar/menuData.ts

Minor PR to update some items in the nav bar - looks like this:
https://artsyproduct.atlassian.net/browse/GRO-1521

chore: Nav item updates for collections GRO-1521

---

src/Components/AuthDialog/Utils/formatErrorMessage.ts

Minor thing I noticed in our Slack — when staging went down this was the error.

chore(authdialog): adds an additional error case

---

src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
src/Apps/MyCollection/Routes/PriceEstimate/__tests__/PriceEstimateContactInformation.jest.tsx
src/__generated__/ContactInformationForm_me.graphql.ts
src/__generated__/ContactInformation_SubmissionFlowTest_Query.graphql.ts
src/__generated__/ContactInformation_me.graphql.ts
src/__generated__/PriceEstimateContactInformation_ArtworkFlowTest_Query.graphql.ts
src/__generated__/PriceEstimateContactInformation_me.graphql.ts
src/__generated__/collectorProfileRoutes_priceEstimateContactInformationQuery.graphql.ts
src/__generated__/consignFromCollectorProfileMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
src/__generated__/consignFromCollectorProfileMyCollectionRoutes_contactInformationMeQuery.graphql.ts
src/__generated__/consignFromMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
src/__generated__/consignFromMyCollectionRoutes_contactInformationMeQuery.graphql.ts
src/__generated__/consignRoutes_contactInformationQuery.graphql.ts
src/__generated__/myCollectionRoutes_priceEstimateContactInformationQuery.graphql.ts

This PR solves [CX-3353]
- This PR fixes other places where we populate phone input with user's phone number
[CX-3353]: https://artsyproduct.atlassian.net/browse/CX-3353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix(CX-3353): Fix Wrong Phone Input Autopopulation

---

src/Apps/Consign/Routes/SubmissionFlow/SubmissionLayout.tsx
src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx

This PR solves [CX-3320]
- This PR addresses the issues raised following QA. QA Notes in the comment of the linked Jira ticket.
[CX-3320]: https://artsyproduct.atlassian.net/browse/CX-3320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix(CX-3320): SWA Confirmation Page fixes

---

src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx

This PR solves [CX-3320]
[CX-3320]: https://artsyproduct.atlassian.net/browse/CX-3320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat(CX-3320): Add spacing

---

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResultItem.jest.tsx

This PR updates the logic of the Awaiting Results condition for the auction results 

fix(auction-results): Update Auction Results awaiting results logic

---

src/Apps/MyCollection/Routes/EditArtwork/MyCollectionEditArtwork.tsx
src/Utils/localImageHelpers.ts

Addresses [CX-3337]
Adjust local image logic.
[CX-3337]: https://artsyproduct.atlassian.net/browse/CX-3337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Adjust local image logic

---

src/Apps/Order/Components/BuyerGuarantee.tsx
src/Apps/Order/Components/ConditionsOfSaleDisclaimer.tsx
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/Review/index.tsx
src/Apps/Order/Routes/__tests__/Review.jest.tsx

This PR solves [TX-1026]
This PR updates the text copy for displaying Artsy private sale conditions link, and updates the sidebar styles according to designs. 
[TX-1026]: https://artsyproduct.atlassian.net/browse/TX-1026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TX-1026): Update sale conditions copy and arrange sidebar styles

---

src/Components/NavBar/menuData.ts

Just a minor update per the brand team.
https://artsyproduct.atlassian.net/browse/GRO-1534

chore: Move some nav items GRO-1534

---

src/Apps/ArtQuiz/Components/ArtQuizResultsTabs.tsx
src/Apps/ArtQuiz/__tests__/ArtQuizResults.jest.tsx
src/System/i18n/locales/en-US/translation.json

This PR solves [GRO-1531]
Swap out copy in translations.json
[GRO-1531]: https://artsyproduct.atlassian.net/browse/GRO-1531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(art-quiz): update results page copy

---

scripts/jest.sh

Seeing if this reduces the amount of timeouts we're seeing.

ci: reduces max workers to 2

---

src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx

Once again but this time with feeling! https://github.com/artsy/force/pull/11850

Update tests to match new nav item order

---

package.json
src/System/__tests__/useFeatureFlag.jest.tsx
yarn.lock

This PR fixes CI breaking because of a tracking schema update. The event wasn't being used anywhere else, so I updated it to match the one on app.

fix: update experiment viewed tracking event

---

src/Components/AuthDialog/Views/AuthDialogForgotPassword.tsx
src/Components/AuthDialog/Views/AuthDialogLogin.tsx

Minor change to support a few assertions about the server-side rendered pages in Integrity.

fix(auth): adds data-attrs for integrity

---

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormContext.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx

Addresses [CX-3392]
Add index to local images to avoid assigning the wrong images.
[CX-3392]: https://artsyproduct.atlassian.net/browse/CX-3392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add index to local images

---

src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/FourUpImageLayout.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/SavesItem.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/StackedImageLayout.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/FourUpImageLayout.jest.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/SavesItem.jest.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/StackedImageLayout.jest.tsx
src/Apps/CollectorProfile/Routes/Saves2/Utils/__tests__/prepareImageURLs.jest.ts
src/Apps/CollectorProfile/Routes/Saves2/Utils/prepareImageURLs.ts
src/Apps/CollectorProfile/collectorProfileRoutes.tsx
src/__generated__/CollectorProfileSaves2Route_me.graphql.ts
src/__generated__/SavesItem_item.graphql.ts
src/__generated__/SavesItem_test_Query.graphql.ts
src/__generated__/collectorProfileRoutes_Saves2Query.graphql.ts

This PR solves [FX-4526]
Review app: [saves-and-wishlist](https://saves-and-wishlist.artsy.net/collector-profile/saves2)
* [Desktop view](https://www.figma.com/file/wSV2KNz97Tyj8HkH2ZYAkB/Save-%2B-Wishlist?node-id=308%3A216953&t=rOlJYAozFRqXRwb9-0)
* [mWeb view](https://www.figma.com/file/wSV2KNz97Tyj8HkH2ZYAkB/Save-%2B-Wishlist?node-id=466%3A144453&t=rOlJYAozFRqXRwb9-0)
https://user-images.githubusercontent.com/3513494/215774846-21576c87-1000-4b7a-847a-cc87c98e2d44.mp4
[FX-4526]: https://artsyproduct.atlassian.net/browse/FX-4526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

feat(FX-4526): Create component for Saves and Wishlist rail

---

cypress/e2e/alerts.cy.ts
cypress/e2e/consign.cy.ts
cypress/e2e/notifications.cy.ts
cypress/e2e/partnerProfile.cy.js
cypress/e2e/userPayments.cy.js
cypress/e2e/userShipping.cy.js
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx

Unblocks Force CI — see [Slack thread](https://artsy.slack.com/archives/CP9P4KR35/p1675767396072529)
We may need a better long-term solution for smoke tests that exercise features that are under an Unleash flag.
For now, we pend one such spec in 414f25f676ed590addea3a99e31ac0657724a7d9 but should un-pend as soon as it's no longer under a flag cc @dariakoko 
cc @rquartararo @AlicanAkyuz

fix: smoke tests

---

src/Apps/Order/Routes/Payment/PaymentContent.tsx
src/Apps/Order/Routes/__tests__/Payment.jest.tsx

This PR solves [TX-1033]
This PR adds a title to the wire transfer details when it's the only payment method available. 
[TX-1033]: https://artsyproduct.atlassian.net/browse/TX-1033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TX-1033): add conditional title for wire transfer

---

src/Apps/ArtQuiz/Hooks/__mocks__/useDislikeArtwork.ts
src/Apps/ArtQuiz/Hooks/__mocks__/useSaveArtwork.ts
src/Apps/ArtQuiz/Hooks/__mocks__/useUpdateQuiz.ts
src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
src/Apps/ArtQuiz/__tests__/ArtQuizArtworks.jest.tsx
src/System/i18n/locales/en-US/translation.json
src/__generated__/ArtQuizArtworks_Test_Query.graphql.ts
src/__generated__/ArtQuizArtworks_me.graphql.ts
src/__generated__/artQuizRoutes_ArtworksQuery.graphql.ts

The type of this PR is: **style**
This PR solves [GRO-1539]
A small change requested by Lois.
[GRO-1539]: https://artsyproduct.atlassian.net/browse/GRO-1539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

style(art-quiz): translate and add newline to tooltip text

---

src/Apps/Jobs/Components/JobLink.tsx
src/Apps/Jobs/Components/JobsFilter.tsx

fix(jobs): removes redundant location for leadgen category

---

scripts/smoke_test.sh

Cherry picking @dimatretyak's change

chore: restore smoke scripts

---

src/Apps/Authentication/Legacy/Server/__tests__/checkForRedirect.jest.ts
src/Apps/Authentication/Legacy/Server/checkForRedirect.ts
src/Components/AuthDialog/Components/AuthDialogSocial.tsx
src/Utils/__tests__/sanitizeRedirect.jest.ts

Closes [GRO-1301](https://artsyproduct.atlassian.net/browse/GRO-1301)
[GRO-1301]: https://artsyproduct.atlassian.net/browse/GRO-1301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(GRO-1301): Fixes redirect for social sign ups

---

src/Apps/ArtQuiz/artQuizRoutes.tsx
src/__generated__/artQuizRoutes_ArtworksQuery.graphql.ts

Hotfix to pre-create user collections before a new user hits the art quiz.

fix(art-quiz): preload collections

---

src/Utils/localImageHelpers.ts

Adjust cleanLocalImages logic.

fix: Adjust cleanLocalImages logic

---

src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/Components/PhotoUpload/Components/PhotoThumbnail.tsx
src/Components/PhotoUpload/Utils/fileUtils.ts

Addresses [CX-3384]
Hide size for automatically added photos in MyC form.
[CX-3384]: https://artsyproduct.atlassian.net/browse/CX-3384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Hide size for automatically added photos in MyC form

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FAQSWA.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Reviews.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/FAQSWA.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Footer.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
src/Components/HeroCarousel/HeroCarousel.story.tsx
src/Components/HeroCarousel/HeroCarousel.tsx
src/Components/HeroCarousel/HeroCarouselLarge.tsx
src/Components/HeroCarousel/HeroCarouselSmall.tsx

This PR solves [CX-3370]
https://user-images.githubusercontent.com/36167539/218133773-117bb2f4-88ff-4388-bb42-57b30287dd86.mov
[CX-3370]: https://artsyproduct.atlassian.net/browse/CX-3370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat(CX-3370): redesign the swa landing page part 6

---

src/Apps/ArtQuiz/Components/ArtQuizResultsLoader.tsx
src/Apps/ArtQuiz/Routes/ArtQuizWelcome.tsx
src/Components/Onboarding/Components/OnboardingModal.tsx
src/Components/Onboarding/Hooks/useOnboarding.tsx
src/Components/Onboarding/Views/OnboardingWelcome.tsx
src/Components/SplitLayout.tsx

Closes [GRO-1555](https://artsyproduct.atlassian.net/browse/GRO-1555)
[GRO-1555]: https://artsyproduct.atlassian.net/browse/GRO-1555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(onboarding): fixes responsive styling

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/CollectorsOverview.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx

This PR solves [CX-3368]
https://user-images.githubusercontent.com/36167539/218520350-df921bdb-8a76-4672-92f9-0e56421b15df.mov
[CX-3368]: https://artsyproduct.atlassian.net/browse/CX-3368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat(CX-3368): redesign the swa landing page part 4

---

src/Apps/Order/Routes/__tests__/Status.jest.tsx
src/Apps/Order/Utils/getStatusCopy.tsx

This PR solves [TX-1067]
This PR updates wire transfer instructions with the new copies. 
[TX-1067]: https://artsyproduct.atlassian.net/browse/TX-1067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TX-1067): Wire instructions update

---

src/Apps/Artist/Routes/AuctionResults/Components/MarketStatsPlaceholder.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/MarketStats.jest.tsx
src/Utils/__tests__/formatLargeNumber.jest.ts
src/Utils/formatLargeNumber.ts

This PR solves the capitalising issue
[Convo](https://artsy.slack.com/archives/C01CAM2QS3U/p1676474089447359)
[List](https://docs.google.com/document/d/1inhRPjJmK1AJg-XYS8CC74y6t6a8KrDx32MdxJwWFG8/edit#bookmark=id.tnamqxk3v7az)

fix: capitalize K on sale price

---

.secrets.baseline
src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
src/Apps/ViewingRoom/Routes/Works/__tests__/ViewingRoomWorksRoute.jest.tsx
src/__generated__/ViewingRoomArtworkDetails_artwork.graphql.ts
src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
src/__generated__/viewingRoomRoutes_ViewingRoomWorksRouteQuery.graphql.ts

This PR solves: [PX-5416]
Essentially this PR just ensures that the artist name is clickable and will take you to the artist page. It uses the `Details.tsx` component to accomplish this per ticket specification. 
[PX-5416]: https://artsyproduct.atlassian.net/browse/PX-5416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore:add artist link to viewing room

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FAQSWA.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FooterBanner.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviouslySoldOnArtsyRail.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpeakToTheTeam.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/TextAndImageLayout.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx

Addressed QA comments
Can be tested here: https://swa-lp-redesign.artsy.net/sell

fix(CX-3360): swa final adjustments

---

src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal.tsx

This PR solves [FX-4551]
Just a tiny refactoring based on @dimatretyak's suggestions
[FX-4551]: https://artsyproduct.atlassian.net/browse/FX-4551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Small refactoring of create collection modal

---

src/Apps/Order/Components/BuyerGuarantee.tsx
src/Apps/Order/Components/ConditionsOfSaleDisclaimer.tsx
src/Apps/Order/Components/__tests__/BuyerGuarantee.jest.tsx
src/Apps/Order/Routes/__tests__/Review.jest.tsx

This PR solves [TX-1065]
The PR updates the copy of Additional Conditions of Sale for the private sales.
[TX-1065]: https://artsyproduct.atlassian.net/browse/TX-1065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update the copy of Additional Conditions of Sale for the private sales

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
src/Components/FollowButton/FollowArtistButton.tsx
src/Components/FollowButton/__tests__/FollowArtistButton.jest.tsx
src/Components/NavBar/Menus/NavBarUserMenu.tsx
src/Components/NavBar/NavBarLoggedInActions.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFindFollows.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowsHighlight.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingPopover.tsx
src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingContext.jest.tsx
src/System/Router/Boot.tsx
src/__generated__/FollowArtistButtonMutation.graphql.ts
src/__generated__/FollowArtistButtonQuery.graphql.ts
src/__generated__/FollowArtistButton_Test_Query.graphql.ts
src/__generated__/FollowArtistButton_me.graphql.ts
src/__generated__/ProgressiveOnboardingFollowArtistQuery.graphql.ts
src/__generated__/ProgressiveOnboardingFollowArtist_me.graphql.ts

Closes [GRO-1558](https://artsyproduct.atlassian.net/browse/GRO-1558)
Nothing particularly notable/novel needed here. There's a context store that wraps local storage and the individual tips are wrapper components that we just place individually around our target nodes.
[GRO-1558]: https://artsyproduct.atlassian.net/browse/GRO-1558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(GRO-1558): progressive onboarding for artist follows

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx

Change specialty for one specialist - requested by Pierluca

fix(CX-3360): change specialty for one specialist

---

src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFindFollows.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSaves.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowsHighlight.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingHighlight.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingPopover.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingSavesHighlight.tsx
src/Components/ProgressiveOnboarding/useProgressiveOnboardingTracking.tsx

Closes [GRO-1586](https://artsyproduct.atlassian.net/browse/GRO-1586)
Adds analytics impression tracking and tightens up some of the display/dismissal logic.
[GRO-1586]: https://artsyproduct.atlassian.net/browse/GRO-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(progressive-onboarding): adds tracking; updates dismissal logic

---

src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/DeleteSavesModal.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditSavesModal.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useUpdateCollection.ts
src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/SavesContextualMenu.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/DeleteSavesModal.jest.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/EditSavesModal.jest.tsx
src/Components/ContextualMenu/ContextualMenu.tsx
src/System/i18n/locales/en-US/translation.json
src/__generated__/useUpdateCollectionMutation.graphql.ts

This PR solves [FX-4552]
Review app: https://edit-wishlist.artsy.net/collector-profile/saves2
Fleshes out the Artwork List area's contextual menu by implementing the "Edit list" functionality
https://user-images.githubusercontent.com/140521/222452515-c5889bc9-8a71-4005-9706-b25db64037a9.mov
https://user-images.githubusercontent.com/140521/222452528-e0e56968-5f94-4c5d-8f33-af0e5348c373.mov
[FX-4552]: https://artsyproduct.atlassian.net/browse/FX-4552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(artwork lists): add the edit action

---

package.json
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FooterBanner.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpeakToTheTeam.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Footer.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HowItWorksSteps.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/MeetTheSpecialists.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SpeakToTheTeam.jest.tsx
yarn.lock

Adjust tracking events
Make the contact specialist button smaller
Remove margin from the banner

Fix(CX-3360): design and tracking adjustments

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/__tests__/MyCollectionArtwork.jest.tsx
src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightCard.tsx
src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightPromoCard.tsx
src/Apps/Settings/Routes/MyCollection/Components/EmptyMyCollectionPage.tsx

This PR solves [CX-3417]
Remove cx released ffs
[CX-3417]: https://artsyproduct.atlassian.net/browse/CX-3417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove cx released ffs

---

src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkModal.tsx
src/Components/Artwork/ManageArtworkForSaves.tsx
src/Components/Artwork/SaveButton/SaveArtworkToListsButton.tsx
src/Components/Artwork/SaveButton/__tests__/SaveArtworkToListsButton.jest.tsx
src/System/i18n/locales/en-US/translation.json
src/__generated__/SelectListsForArtworkModalQuery.graphql.ts
src/__generated__/SelectListsForArtworkModal_Test_Query.graphql.ts
src/__generated__/SelectListsForArtworkModal_me.graphql.ts

This PR solves [FX-4592]
Review app: [display-toasts](https://display-toasts.artsy.net/)
https://user-images.githubusercontent.com/3513494/223429773-3ed9f971-ee78-4560-b9dd-acfb55c2c462.mp4
https://user-images.githubusercontent.com/3513494/223429893-3076c09a-3cde-4b95-b2b9-680a8269deb7.mp4
[FX-4592]: https://artsyproduct.atlassian.net/browse/FX-4592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4592): display toasts for Saves

---

.secrets.baseline
src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
src/Components/Artwork/Details.tsx
src/Components/Artwork/__tests__/Details.jest.tsx

This PR solves [CX-3417]
Remove uploading flow-related feature flags
Remove upcoming auction results feature flag
[CX-3417]: https://artsyproduct.atlassian.net/browse/CX-3417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove more cx ffs

---

src/Components/RecentlyViewed/RecentlyViewed.tsx

Reverts artsy/force#12065
We can merge this once https://github.com/artsy/metaphysics/pull/4870 is deployed.

Revert "fix: compacts artworks displayed in shelf"

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/CollectorsOverview.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Highlights.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Footer.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HowItWorksSteps.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
src/__generated__/InsightsAuctionResults_me.graphql.ts
src/__generated__/collectorProfileRoutes_InsightsRouteQuery.graphql.ts
src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts

This PR solves [CX-3526]
Added new copies, adjusted images in carousels (we checked the changes on the QA call)
[CX-3526]: https://artsyproduct.atlassian.net/browse/CX-3526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3526): add new copies, adjust images in carousels

---

src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx

This PR solves [CX-3530]
To test: https://swa-lp-redesign.artsy.net/sell
[CX-3530]: https://artsyproduct.atlassian.net/browse/CX-3530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(CX-3530): hide parts of the page

---

docs/creating_review_app.md

While triggering a review app noticed this new cloudflare feature that is SO useful IMO (screenshots on [slack thread](https://artsy.slack.com/archives/C2TQ4PT8R/p1678878896538269))
We are now able to add a descriptive comment about the review-app that we deploy and also tags that do not affect anything DNS related it is for our own reference.
Updated the docs to reflect that.
Happy to hear your thoughts on this :star-struck:
[slack thread](https://artsy.slack.com/archives/C2TQ4PT8R/p1678878896538269)

docs: update create review app.md

---

scripts/setup.sh

This PR brings back brew section from setup script. I've accidentally removed it in https://github.com/artsy/force/pull/12082

chore: Bring back brew section from setup script

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx

fix: replace the image

---

src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
src/__generated__/CollectorProfileSaves2Route_Test_Query.graphql.ts
src/__generated__/CollectorProfileSaves2Route_me.graphql.ts
src/__generated__/collectorProfileRoutes_Saves2Query.graphql.ts

https://user-images.githubusercontent.com/3513494/225695020-021f1fbc-92e9-4d20-9807-c2beffc823e5.mp4
https://user-images.githubusercontent.com/3513494/225695126-4e77698a-e7d1-4245-b268-a98aaadcb1b0.mp4

chore: specify `sort` arg for other collections

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FAQSWA.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FooterBanner.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/FAQSWA.jest.tsx

fix(CX-3360): address design issues

---

src/Components/Search/SearchBar.tsx
src/Components/Search/Suggestions/SuggestionItem.tsx
src/Components/Search/Suggestions/SuggestionItemPreview.tsx
src/Components/Search/__tests__/SearchBar.jest.tsx
src/__generated__/SearchBarRefetchQuery.graphql.ts
src/__generated__/SearchBarSuggestQuery.graphql.ts
src/__generated__/SearchBarTestQuery.graphql.ts
src/__generated__/SearchBar_viewer.graphql.ts

This PR solves [FX-4652]
|Before|After|
|---|---|
|<img width="602" alt="image" src="https://user-images.githubusercontent.com/17421923/225934000-a5faf908-ba95-4f02-a81c-6be664688840.png">|<img width="691" alt="image" src="https://user-images.githubusercontent.com/17421923/225933836-dd50c096-e84f-4a61-859d-03da8b8880ae.png">|
[FX-4652]: https://artsyproduct.atlassian.net/browse/FX-4652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Image icon in search result

---

src/Apps/ArtQuiz/Components/ArtQuizResultsLoader.tsx
src/Apps/ArtQuiz/__tests__/ArtQuizResults.jest.tsx
src/Components/Onboarding/Views/OnboardingQuestionThree.tsx
src/Components/Onboarding/config.ts
src/System/i18n/locales/en-US/translation.json

This is the mostly static part of the changes we're making to the art quiz. Note that some of these changes were in the i18n file, huzzah! But for others I had to go elsewhere - should I be extracting them to that file? 🤔 
<details>
<summary>a few screenshots for proof</summary>
</details>
https://artsyproduct.atlassian.net/browse/GRO-1608

chore: Art quiz copy updates GRO-1608

---

src/Apps/Order/OrderApp.tsx

This PR solves [TX-1072]
This PR fixes unsubscribe logic of the navigation listener.
https://user-images.githubusercontent.com/79979820/227218545-cf51923b-d33e-498e-a8b9-dd248d165e1e.mp4
[TX-1072]: https://artsyproduct.atlassian.net/browse/TX-1072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove second popup appearing on artwork page after leaving checkout

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
src/Apps/Components/constants.ts
src/Components/NavBar/NavBar.tsx
src/Components/NavBar/NavBarLoggedInActions.tsx
src/Components/NavBar/__tests__/NavBar.jest.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertCreate.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFind.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertReady.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertSelectFilter.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingCounts.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFindFollows.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFindSaves.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowsHighlight.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingPopover.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingSavesHighlight.tsx
src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingAlerts.jest.tsx
src/Components/SavedSearchAlert/Components/ActiveFilterPillsAndCreateAlert.tsx
src/Components/SavedSearchAlert/Mutations/createSavedSearchAlert.ts
src/__generated__/ProgressiveOnboardingCountsQuery.graphql.ts
src/__generated__/ProgressiveOnboardingCounts_me.graphql.ts
src/__generated__/createSavedSearchAlertMutation.graphql.ts

Closes [GRO-1602](https://artsyproduct.atlassian.net/browse/GRO-1602)
[GRO-1602]: https://artsyproduct.atlassian.net/browse/GRO-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://user-images.githubusercontent.com/112297/227029456-4afe12f9-cb0c-410d-9753-935bcb3d2b7f.mov

feat(GRO-1602): Progressive onboarding for alerts

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx

Update SWA landing page images

chore: update swa landing page images

---

src/Apps/ArtQuiz/artQuizRoutes.tsx

This wasn't building previously because it was a PR from my fork. Rebased and re-opening.

chore(feature-flags): removes art-quiz flag

---

src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

Just a minor update to a headshot.
https://artsyproduct.atlassian.net/browse/GRO-1633

chore: Update a headshot GRO-1633

---

src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYouWhenFromMyCollection.tsx
src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYouWhenFromMyCollection.jest.tsx

This PR solves [CX-3525]
cc @MrSltun 
[CX-3525]: https://artsyproduct.atlassian.net/browse/CX-3525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update copy on SWA confirmation pages

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx

This PR solves [CX-3581]
The background color on the screen recording is set to blue and red to show that the image is aligned correctly
https://user-images.githubusercontent.com/36167539/228297121-be46efd4-6cb4-415c-8ed4-a9f7af63aa99.mov
[CX-3581]: https://artsyproduct.atlassian.net/browse/CX-3581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3581): swa adjust alignment

---

src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListArtworksGrid.tsx

The type of this PR is: **Refactor**, **Feat**
Pass context owner type in the parent component

refactor: pass context owner in the parent component

---

src/Apps/Marketing/Components/MarketingAlternatingStack.tsx
src/Apps/Marketing/Components/MarketingCollectionCell.tsx
src/Apps/Marketing/Components/MarketingFeaturedArtworksRail.tsx
src/Apps/Marketing/Components/MarketingHeader.tsx
src/Apps/Marketing/Components/MarketingQuizCTA.tsx
src/Apps/Marketing/Components/MarketingTrendingArtistsRail.tsx
src/Apps/Marketing/Routes/MarketingFindArtYouWantRoute.tsx
src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx
src/Apps/Marketing/marketingRoutes.tsx
src/__generated__/MarketingFeaturedArtworksRailQuery.graphql.ts
src/__generated__/MarketingFeaturedArtworksRail_viewer.graphql.ts
src/__generated__/MarketingTrendingArtistsRailQuery.graphql.ts
src/__generated__/MarketingTrendingArtistsRail_viewer.graphql.ts
src/routes.tsx

Re: [GRO-1639](https://artsyproduct.atlassian.net/browse/GRO-1639), [GRO-1640](https://artsyproduct.atlassian.net/browse/GRO-1640)
Not much to these. I'll do another pass once we have final assets, refining some of the responsive details, etc.
[GRO-1639]: https://artsyproduct.atlassian.net/browse/GRO-1639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1640]: https://artsyproduct.atlassian.net/browse/GRO-1640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(GRO-1637): roughs in brand campaign routes

---

src/Apps/Search/Components/SendFeedback.tsx
src/Apps/Search/Components/__tests__/SendFeedback.jest.tsx

This PR solves [FX-4698]
Review app: [send-search-feedback](http://send-search-feedback.artsy.net/)
https://user-images.githubusercontent.com/3513494/229781526-2a4a48c7-79e5-4d88-ae06-366f78032692.mp4
https://user-images.githubusercontent.com/3513494/229781895-5e58364f-97ee-42de-a3da-f5ff2cf9d829.mp4
[FX-4698]: https://artsyproduct.atlassian.net/browse/FX-4698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FX-4698): search feedback

---

src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListEmptyState.tsx

This PR solves [FX-4716]
| <img width="375" alt="before" src="https://user-images.githubusercontent.com/3513494/230135307-de859965-a596-4e35-8f90-b74402834469.png"> | <img width="375" alt="after" src="https://user-images.githubusercontent.com/3513494/230135342-6d95519e-467d-4bc5-bd62-0d3f7c16a80b.png"> |
[FX-4716]: https://artsyproduct.atlassian.net/browse/FX-4716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FX-4716): update empty-state to match designs

---

src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx

I had a session with Dasha and Pierluca to review these together and have them approve the changes. 
cc @dariakoko

chore: update copy to follow new designs

---

src/Components/DownloadAppBadges/DownloadAppBadge.tsx
src/Components/DownloadAppBadges/DownloadAppBadges.tsx
src/Components/Footer/Footer.tsx
src/Components/Footer/FooterDownloadAppBanner.tsx
src/Components/Footer/FooterDownloadAppBanner2.tsx

Closes [GRO-1638](https://artsyproduct.atlassian.net/browse/GRO-1638)
Enabled on staging via the [`grow_universal-footer`](https://unleash.artsy.net/projects/default/features/grow_universal-footer) feature flag.
[GRO-1638]: https://artsyproduct.atlassian.net/browse/GRO-1638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(GRO-1638): New footer

---

src/Apps/Marketing/Components/MarketingQuizCTA.tsx
src/Components/Footer/FooterDownloadAppBanner.tsx
src/Components/Footer/__tests__/Footer.jest.tsx

Closes: [GRO-1640](https://artsyproduct.atlassian.net/browse/GRO-1640), [GRO-1639](https://artsyproduct.atlassian.net/browse/GRO-1639)
[GRO-1640]: https://artsyproduct.atlassian.net/browse/GRO-1640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1639]: https://artsyproduct.atlassian.net/browse/GRO-1639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(GRO-1639,GRO-1640): Minor tweaks

---

src/Apps/Order/Routes/__tests__/Status.jest.tsx
src/Apps/Order/Utils/getStatusCopy.tsx

This PR solves [TX-1114]
This PR updates wire transfer bank info and notes. 
[TX-1114]: https://artsyproduct.atlassian.net/browse/TX-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(TX-1114): update wire transfer bank details

---

src/Components/Footer/Footer.tsx

Brought back Talk to a Specialist link

fix: bring back the link

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Footer.jest.tsx
src/Apps/Settings/Routes/MyCollection/Components/MyCollectionEmptyState.tsx

This PR solves [CX-3606] [CX-3607]
Copy update to My Collection empty state
Copy update to the Sell With Artsy page
[CX-3606]: https://artsyproduct.atlassian.net/browse/CX-3606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-3607]: https://artsyproduct.atlassian.net/browse/CX-3607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update copies

---

src/Apps/CollectorProfile/CollectorProfileApp.tsx

This PR solves [CX-3619]
Adjust font size for Tabs in Collector Profile mweb to xs 
https://user-images.githubusercontent.com/36167539/231989099-af248376-c24c-4c43-ba51-b951080fd3f3.mov
[CX-3619]: https://artsyproduct.atlassian.net/browse/CX-3619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-3619): change tabs text size

---

src/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx
src/Apps/Auctions/Components/__tests__/WorksByArtistsYouFollowRail.jest.tsx
src/Components/Artwork/ShelfArtwork.tsx

This PR solves [CX-3620]
| --- | --- |
| <img width="1038" alt="image" src="https://user-images.githubusercontent.com/36167539/232068343-f7531053-31c1-4931-81e8-615cc7aaf037.png"> | <img width="1030" alt="image" src="https://user-images.githubusercontent.com/36167539/232068177-485e5d36-7257-454d-9d20-d5c8988d8b05.png"> |
[CX-3620]: https://artsyproduct.atlassian.net/browse/CX-3620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3620): change the design of the auction lots rail

---

src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useCreateCollection.ts
src/__generated__/useCreateCollectionMutation.graphql.ts

https://user-images.githubusercontent.com/3513494/232044687-77dfaa06-6e29-45e3-81e8-c9b48e184ea5.mp4
https://user-images.githubusercontent.com/3513494/232044758-4bfd600e-d483-4dd9-827a-063a1f9b7e0e.mp4

fix: correctly display artworks count for recently created artwork list

---

src/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx
src/Apps/Auctions/Components/__tests__/WorksByArtistsYouFollowRail.jest.tsx
src/Components/Artwork/ShelfArtwork.tsx

Reverts artsy/force#12249
Reverting because of design inconsistency

Revert "feat(CX-3620): change the design of the auction lots rail"

---

src/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx
src/Apps/Auctions/Components/__tests__/WorksByArtistsYouFollowRail.jest.tsx

This PR solves [CX-3620]
[CX-3620]: https://artsyproduct.atlassian.net/browse/CX-3620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-3620): auction lots for you ending soon rail ux chanes

---

src/Apps/Home/Components/HomeContentCards/HomeContentCards.tsx

I've been working with Braze support over the last week trying to figure out why Content Cards aren't showing up as we'd expect. They have asked for more logging so that they can continue troubleshooting so I'm just following what they asked for here. I'll remove this once their investigation is complete.

Add more braze logging

---

src/Apps/ArtQuiz/artQuizRoutes.tsx
src/Apps/Marketing/Components/MarketingFeaturedArtworksRail.tsx
src/Apps/Marketing/Components/MarketingHeader.tsx
src/Apps/Marketing/Components/MarketingQuizCTA.tsx
src/Apps/Marketing/Routes/MarketingFindArtYouLoveRoute.tsx
src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx
src/Apps/Marketing/marketingRoutes.tsx
src/Components/DownloadAppBadges/DownloadAppBadge.tsx
src/Components/Footer/FooterDownloadAppBanner2.tsx

Closes [GRO-1659](https://artsyproduct.atlassian.net/browse/GRO-1659)
[GRO-1659]: https://artsyproduct.atlassian.net/browse/GRO-1659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(GRO-1659): Brand campaign Q/A

---

src/Components/Artwork/__tests__/ManageArtworkForSaves.jest.tsx
src/System/i18n/locales/en-US/translation.json

This PR solves [FX-4732], [FX-4742]
| <img width="673" alt="before" src="https://user-images.githubusercontent.com/3513494/232527616-db3cca10-0d71-4032-8f36-c7062e382706.png"> | <img width="673" alt="after" src="https://user-images.githubusercontent.com/3513494/232527693-332f8b9b-6d3f-4349-91da-cc29354197e5.png"> | 
[FX-4732]: https://artsyproduct.atlassian.net/browse/FX-4732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FX-4742]: https://artsyproduct.atlassian.net/browse/FX-4742?atlOrigin=eyJpIjoiNWRkNTlj …

chore(FX-4732): Change message when creating a list

---

src/Apps/Marketing/Components/MarketingQuizCTA.tsx
src/Apps/Marketing/Routes/MarketingFindArtYouLoveRoute.tsx
src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx

fix(marketing): updates assets

---

src/Components/NavBar/NavBar.tsx
src/Components/Search/NewSearch/NewSearchBar.tsx
src/Components/Search/NewSearch/NewSearchBarInputContainer.tsx
src/Components/Search/NewSearch/NewSearchBarSuggestion.tsx

This PR solves [FX-4651]
This PR resolves the followings :
- Add fx-force-search-dropdown-improvements feature flag in [Unleash](https://unleash.artsy.net/features)
- Add a new search dropdown component that will not display anything when feature flag is enabled.
- Add `AutocompleteInput` from palette as a new Search input container
[FX-4651]: https://artsyproduct.atlassian.net/browse/FX-4651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: new search boilerplate with feature flag enabled. 

---

src/System/Relay/createRelaySSREnvironment.ts

Companion PR to https://github.com/artsy/exchange/pull/1612, see there for context.
Jira ticket: https://artsyproduct.atlassian.net/browse/PRO-102

feat[PRO-102]: pass session ID with headers to MP

---

src/Apps/Home/Components/HomeNewWorksForYouRail.tsx
src/Apps/NewForYou/newForYouRoutes.tsx
src/__generated__/HomeNewWorksForYouRailQuery.graphql.ts

This PR solves [CX-3541]
Use version C for new works for you rail
If we decide to roll this on email as well, we will adjust C to be also the default on MP
https://user-images.githubusercontent.com/11945712/228198337-f277fbc1-cdc3-4842-8faa-3b6401d299f2.mov
[CX-3541]: https://artsyproduct.atlassian.net/browse/CX-3541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: use version C for new works for you rail

---

src/Components/NavBar/Menus/NavBarUserMenu.tsx
src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx

This surfaces the alerts in the dropdown to allow us to guide through progressive onboarding.

feat: alerts option in user dropdown

---

src/Apps/Article/Components/ArticleAd/ArticleAd.tsx

fix(article): disables lazyloading on ads

---

src/Apps/Marketing/Routes/MarketingFindArtYouLoveRoute.tsx
src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx
src/Components/Footer/FooterDownloadAppBanner2.tsx

Closes [GRO-1673](https://artsyproduct.atlassian.net/browse/GRO-1673)
[GRO-1673]: https://artsyproduct.atlassian.net/browse/GRO-1673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(GRO-1673): remaining q/a items

---

scripts/smoke_test.sh

This PR refactors the changes introduced in https://github.com/artsy/force/pull/12311 and https://github.com/artsy/force/pull/12317
Based on some debugging in CI container it was assumed that the above changes would be enough however it turned out to not be so. This morning [CI experienced a failure](https://app.circleci.com/pipelines/github/artsy/force/47868/workflows/740acc97-a1ac-43cc-94d5-255701a31c88/jobs/359708?invite=true#step-101-18)  after the cypress install timed out and the binary was not installed.
This follows up with another improvement to this workaround. Increasing the timeout to 60 and also implementing a retry.
I re-ran acceptance tests 8 times in CI with this change and on the [8th run the install step timed out, retried, and …

refactor: increase cypress install timeout to 60s, add retry

---

src/Components/ArtworkFilter/index.tsx
src/Components/NavBar/NavBar.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertSelectFilter.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingFollows.jest.tsx

Notably, this adds the `Alerts` option to the mobile dropdown.

fix(progressive-onboarding): addresses remaining q/a items

---

src/Components/SalesforceWrapper.tsx

This PR solves [NX-3530]
Integration and smoke tests failing for `window` being undefined on the server.
[NX-3530]: https://artsyproduct.atlassian.net/browse/NX-3530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(NX-3530): window is undefined on ssr

---

src/Components/SalesforceWrapper.tsx

This PR solves [NX-3530]
[NX-3530]: https://artsyproduct.atlassian.net/browse/NX-3530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: move usage of window to the useEffect

---

src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx

Reverts artsy/force#12331
I tested this change on staging, and expected to see an event being fired in the console. Instead, I found the following error message, and thought it merited some more investigation:

Revert "feat(PRO-107): add tracking to settings IDV clicks"

---

src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx

Revert "Revert "feat(PRO-107): add tracking to settings IDV clicks""

---

src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGallery.tsx
src/Apps/Artist/Routes/AuctionResults/Components/ImageWithFallback.tsx
src/Apps/Artist/Routes/AuctionResults/Components/KeywordFilter.tsx
src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResultImage.tsx
src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResultPrice.tsx
src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsWatchLotButton.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/SaveUtilButton.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/UtilButton.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.jest.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActionsSaveButtonV2.jest.tsx
src/Apps/Artwork/Components/PricingContextModal.tsx
src/Apps/Artwork/Components/__tests__/PricingContext.jest.tsx
src/Apps/Artwork/Components/__tests__/PricingContextModal.jest.tsx
src/Apps/Auction/Components/AuctionDetails/LiveAuctionToolTip.tsx
src/Apps/Authentication/Routes/AuthenticationResetPasswordRoute.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/SelectArtworkItem.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/Images/ArtworkListNoImage.tsx
src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiryContainer.tsx
src/Apps/Consign/Routes/SubmissionFlow/SubmissionLayout.tsx
src/Apps/Conversation/Components/DetailsSidebar.tsx
src/Apps/Conversation/Components/Message.tsx
src/Apps/Conversation/Components/OrderUpdate.tsx
src/Apps/Conversation/Components/ReviewOfferCTA.tsx
src/Apps/Conversation/Components/UnreadMessagesToast.tsx

chore: replaces icons

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx

Addresses [CX-3689]
Hide install app on meet your new art advisor LP campaign.
[CX-3689]: https://artsyproduct.atlassian.net/browse/CX-3689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Hide install app on meet your new art advisor LP campaign

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx

[Slack Thread](https://artsy.slack.com/archives/C01B2P6LJUU/p1683640022407649)
Adjust SWA Meet the Specialist section pill styling.

fix: Adjust pill styling in SWA "Meet the Specialist" section 

---

src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx

Closes [GRO-1654](https://artsyproduct.atlassian.net/browse/GRO-1654)
[GRO-1654]: https://artsyproduct.atlassian.net/browse/GRO-1654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: removes follow/saves flag

---

.eslintrc.js

Enable tslint react/jsx-key rule.

chore: Enable tslint react/jsx-key rule

---

src/Apps/About/AboutApp.tsx
src/Apps/About/AboutArtworksRail.tsx
src/Components/NavBar/NavBar.tsx
src/System/i18n/locales/en-US/translation.json
src/__generated__/AboutArtworksRailQuery.graphql.ts
src/__generated__/AboutArtworksRail_marketingCollection.graphql.ts

Closes [GRO-1713](https://artsyproduct.atlassian.net/browse/GRO-1713)
We had a link on the about page which I've pointed to `meet-your-new-art-advisor`.
Also noticed and fixed a rail on that page which was no longer working.
[GRO-1713]: https://artsyproduct.atlassian.net/browse/GRO-1713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(GRO-1713): Remove download link

---

src/Components/Search/NewSearch/SuggestionItem/QuickNavigation.tsx
src/Components/Search/NewSearch/SuggestionItem/QuickNavigationItem.tsx

Co-authored-by: @dimatretyak 
This PR solves [FX-4655]
@dimatretyak I've PRd your suggested fix / refactoring. Thanks a lot for looking into it!
[FX-4655]: https://artsyproduct.atlassian.net/browse/FX-4655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FX-4655): fixes new search bar quicklink navigation

---

src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx

This PR solves https://artsy.slack.com/archives/C01B2P6LJUU/p1684137964892049
The testimonials were released by mistake on both App and Web. Reverting them here until we get them.

fix: hide testimonials in SWA LP

---

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx

The type of this PR is: **REFACTOR**
This is just a cleanup after #12405 

refactor: clean up legacy empty auction handling

---

src/Apps/PriceDatabase/Components/PriceDatabaseArtistAutosuggest.tsx
src/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
src/Apps/PriceDatabase/Components/PriceDatabaseSearch.tsx
src/Apps/PriceDatabase/PriceDatabase.tsx
src/__generated__/PriceDatabaseArtistAutosuggestQuery.graphql.ts

I saw this mentioned a few times in Slack so just figured I'd do a quick fix while I was working with autocompletes. I am not entirely sure if this has been in this state for a while. Code gets a lot simpler. It could still use a debounce and "no results" state but it at least works now.
The page has some layout issues but it'd be nice to find a Figma spec for it before adjusting.
cc @artsy/collector-experience

fix(price-database): implements a working autocomplete

---

src/Components/Search/NewSearch/NewSearchBarFooter.tsx
src/Components/Search/NewSearch/NewSearchBarInput.tsx

This PR solves [FX-4788]
**Before**
https://github.com/artsy/force/assets/17421923/ce969265-88aa-4e9c-8c85-c330db58facd
**After**
https://github.com/artsy/force/assets/17421923/cba2e119-e51b-466d-942a-496db4068fdb
[FX-4788]: https://artsyproduct.atlassian.net/browse/FX-4788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: dropdown closes clicking on footer

---

src/Components/Inquiry/Hooks/useInquiryContext.tsx
src/Components/Inquiry/Views/InquiryInquiry.tsx
src/Components/Inquiry/__tests__/Views/InquirySpecialist.jest.tsx

This PR solves [NX-3543](https://artsyproduct.atlassian.net/browse/NX-3543)
Automate and randomize messages displayed in the Contact Gallery modal.
Contact Gallery modal:
Collector Conversations:
CMS Conversations:
[NX-3543]: https://artsyproduct.atlassian.net/browse/NX-3543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3543): automated inquiry messages for contact gallery modal

---

src/Apps/Order/Components/CheckoutAddress.tsx
src/Apps/Order/Components/__tests__/CheckoutAddress.jest.tsx

This PR solves [TX-1200] and [TX-1201]
This PR implements the address verification modals.
[TX-1200]: https://artsyproduct.atlassian.net/browse/TX-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TX-1201]: https://artsyproduct.atlassian.net/browse/TX-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TX-1200): Address verification modals

---

src/Components/Search/NewSearch/Mobile/Overlay.tsx
src/Components/Search/NewSearch/NewSearchBarFooter.tsx
src/Components/Search/NewSearch/NewSearchBarInput.tsx
src/Components/Search/NewSearch/SuggestionItem/NewSuggestionItem.tsx
src/Components/Search/NewSearch/constants.ts

This PR solves [FX-4780]
Tasks
[FX-4780]: https://artsyproduct.atlassian.net/browse/FX-4780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: analytic events for new search bar container

---

cypress/e2e/artist.cy.js

This is to unblock CI and trigger a new release

chore(GRO-1671): skip artist acceptance test to unblock CI

---

src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
src/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx

Minor typo to adjust the copy to the [designs](https://www.figma.com/file/O8VPQKz1syMas0qeuqqyCZ/ARTA-Shipping-in-CMS-update-Q2?type=design&node-id=440-374&t=rceKyM2Fb2yZ80ob-0)

fix: use lowercase o in only

---

src/Utils/Hooks/useSizeAndPosition.ts

Revert "fix(usesizeandposition): ensures that if node is added after hook is set up; we still get geometry"

---

src/Components/CreditCardInput/CreditCardInput.tsx

This PR solves [CX-3767]
This PR separates the CVC and Expiration from Credit Card Number on small devices
| Before                                                                                                                                              | After                                                                                                                                               |
|-----------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="479" alt="Screenshot 2023-06-05 at 15 46 …

fix: separate CVC and Expiration from Credit Card Number on small devices

---

src/Apps/Order/Components/OfferNote.tsx
src/Apps/Order/Components/PriceOptions.tsx
src/Apps/Order/Components/__tests__/OfferNote.jest.tsx
src/Apps/Order/Components/__tests__/PriceOptions.jest.tsx

This PR solves [TX-1154]
This PR updates the price options and offer notes to help guide users when selecting the offer option at checkout.
[TX-1154]: https://artsyproduct.atlassian.net/browse/TX-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TX-1154): update price options and offer note 

---

src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListContent.tsx
src/Apps/CollectorProfile/Routes/Saves2/Utils/useArtworkListVisibility.tsx

https://github.com/artsy/force/pull/12502#discussion_r1224644134
This adds the revert that was missing from this^ earlier PR.

chore(artwork lists): make artwork list scrolling less strict

---

src/Apps/Contact/ContactApp.tsx

Just a couple minor updates - looks like this:
https://artsyproduct.atlassian.net/browse/GRO-1627

chore: Update editorial contact section GRO-1627

---

src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

Minor updates to specialist page.
https://artsyproduct.atlassian.net/browse/GRO-1757

chore: Update specialist info GRO-1757

---

src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListArtworksGrid.tsx

#trivial Removes a small typo I introduced while addressing PR feedback for #12502

fix(artwork lists): small typo

---

src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditArtworkListModal.tsx
src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useCreateCollection.ts
src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/Mutations/useUpdateArtworkList.ts
src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx
src/__generated__/useCreateCollectionMutation.graphql.ts
src/__generated__/useUpdateArtworkListMutation.graphql.ts

[Jira ticket](https://artsyproduct.atlassian.net/browse/FX-4730)
This PR solves [FX-4730]
- Aligns error message handling between Create / Edit flows
- Uses correct metaphysics field for displaying error message
https://github.com/artsy/force/assets/3934579/8729f9a1-c0f4-4d29-8331-6a1101595573
[FX-4730]: https://artsyproduct.atlassian.net/browse/FX-4730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FX-4730): fixes incorrect validation message when creating / updating artwork lists

---

src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx
src/__generated__/SettingsEditProfileFields_Test_Query.graphql.ts
src/__generated__/SettingsEditProfileFields_me.graphql.ts
src/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts

This PR solves [PRO-158]
[PRO-158]: https://artsyproduct.atlassian.net/browse/PRO-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(PRO-158): store user ID on self-initiated IDV

---

src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

Just updating the list of people on the meet the specialist page.

chore: Update list of people on meet the specialist page

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx

This PR updates the list of specialists to match the new org changes.

chore: update list of specialists

---

src/Apps/Order/OrderApp.tsx
src/Apps/Order/__tests__/OrderApp.jest.tsx
src/Components/SalesforceWrapper.tsx

Avoid hitting errors when the expected settings are not present. For ref, see:
https://artsy.slack.com/archives/C9RK0BLEP/p1687972679348039?thread_ts=1687970942.807569&cid=C9RK0BLEP

fix: Make SalesforceWrapper safer

---

src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
src/System/i18n/locales/en-US/translation.json

More updates to Meet the Specialist page including consolidating a couple sections down into one called "Collector Sales".
https://artsyproduct.atlassian.net/browse/GRO-1771

chore: More updates to meet the specialist page GRO-1771

---

src/Apps/Artist/Routes/Shows/Components/ArtistShowsGroup.tsx

OOPS!
https://artsyproduct.atlassian.net/browse/DIA-61

fix: Update section headers on Artist Shows page DIA-61

---

src/Components/Search/NewSearch/NewSearchBarFooter.tsx
src/Components/Search/NewSearch/NewSearchBarInput.tsx

This PR solves [ONYX-147]
https://github.com/artsy/force/assets/3934579/be85378c-6d55-494b-911e-d995a79b37c7
[ONYX-147]: https://artsyproduct.atlassian.net/browse/ONYX-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(onyx-147): fix impossible to navigate to a See full results option using keyboard arrows

---

src/Apps/Search/SearchApp.tsx
src/Components/Search/NewSearch/NewSearchBar.tsx
src/Components/Search/NewSearch/NewSearchBarInput.tsx

This PR solves [ONYX-145]
https://github.com/artsy/force/assets/3934579/83a5e67c-f937-47ed-a2ea-9d194159be08
[ONYX-145]: https://artsyproduct.atlassian.net/browse/ONYX-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(onyx-145): update the search input field when scrolling through options using keyboard arrows

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/CollectorsOverview.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/Footer.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Footer.jest.tsx

This PR solves [ONYX-117]
Updated copy on the SWA landing page
[ONYX-117]: https://artsyproduct.atlassian.net/browse/ONYX-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-117): SWA LP copy update

---

src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/AuctionResult.tsx

Closes [DIA-74](https://artsyproduct.atlassian.net/browse/DIA-74)
Some initial [discussion here](https://github.com/artsy/force/pull/12653).
Which prompted [more discussion here](https://artsy.slack.com/archives/C9XJKPY9W/p1690831439802239).
[DIA-74]: https://artsyproduct.atlassian.net/browse/DIA-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(artist): specifically links to artist auction results index and labels link

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
src/__generated__/ArtistApp_Test_Query.graphql.ts
src/__generated__/ArtistHeader2_artist.graphql.ts
src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts

This PR solves [DIA-66]
It adds Represented By Gallery to Artist Page Header. 
[DIA-66]: https://artsyproduct.atlassian.net/browse/DIA-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add verified representatives to Artist header

---

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlertButton.tsx

The type of this PR is: Fix 
This PR solves [ONYX-128](https://artsyproduct.atlassian.net/browse/ONYX-128)
Update Create Alert buttons to have the `BellStrokeIcon`. 
Add grid for title and button layout.
[ONYX-128]: https://artsyproduct.atlassian.net/browse/ONYX-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-128): update Create Alert button with icon and add grid layout

---

src/Apps/Artist/ArtistApp.tsx

This is some minor work to prep for both the new header and new filters that I think is deployable currently.

feat(artist): updates to new tab style

---

src/Apps/Order/Components/AddressVerificationFlow.tsx
src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx

This PR solves [EMI-1392]
The goal of this PR is to do an audit of the mocked tracking calls in the tests and fix any errors in expected values, mocks or empty fields in the `AddressVerificationFlow` spec. 
[EMI-1392]: https://artsyproduct.atlassian.net/browse/EMI-1392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-1392): address verification flow tracking spec audit

---

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultsRoute.tsx
src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/CurrencyFilter.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/PriceRangeFilter.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
src/Apps/Artist/Utils/allowedAuctionResultFilters.ts
src/__generated__/ArtistAuctionResultsQuery.graphql.ts
src/__generated__/ArtistAuctionResultsRoute_artist.graphql.ts
src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
src/__generated__/ArtistAuctionResults_artist.graphql.ts
src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts

This PR solves DIA-30
Adds currency filter to PriceDB filters.
[Metaphysics PR](https://github.com/artsy/metaphysics/pull/5196)

feat: add currency filter for PriceDB

---

src/Apps/Artist/ArtistApp.tsx
src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
src/Components/ArtworkFilter/ArtworkFilterDrawer.tsx
src/Components/ArtworkFilter/ArtworkFilterMobileOverlay.tsx
src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
src/Components/ArtworkFilter/__tests__/ArtworkFilterMobileOverlay.jest.tsx
src/Components/ArtworkFilter/index.tsx

Closes [DIA-15](https://artsyproduct.atlassian.net/browse/DIA-15)
This brings the mobile version of the filters up to date with the design spec and guards using the feature flag.
[DIA-15]: https://artsyproduct.atlassian.net/browse/DIA-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(filters): mobile filter updates

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlertButton.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertCreateSimple.tsx

Closes [DIA-20](https://artsyproduct.atlassian.net/browse/DIA-20)
[DIA-20]: https://artsyproduct.atlassian.net/browse/DIA-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(progressive-onboarding): adds popover for create alert artwork sidebar

---

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/KeywordFilter.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionResultsControls.tsx

This PR solves [DIA-27]
Move Keyword Search to filters place.
[DIA-27]: https://artsyproduct.atlassian.net/browse/DIA-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: move keyword search to filters area

---

src/Apps/Order/Routes/Payment/PaymentContent.tsx
src/Apps/Order/Routes/__tests__/Payment.jest.tsx

https://artsyproduct.atlassian.net/browse/EMI-1282
This PR solves [EMI-1282]
**Before**
**After**
[EMI-1282]: https://artsyproduct.atlassian.net/browse/EMI-1282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1282): update PaymentContent copy

---

package.json
yarn.lock

Lets keep our deps up to date! This PR bumps `body-parser`. No reported breaking changes in the [releases](https://github.com/expressjs/body-parser/releases). Mainly dep updates.

chore: bump body-parser

---

src/System/Router/RouterLink.tsx
src/System/Router/__tests__/RouterLink.jest.tsx
src/Utils/__tests__/sanitizeURL.jest.ts
src/Utils/sanitizeURL.ts

Closes [DIA-102](https://artsyproduct.atlassian.net/browse/DIA-102)
[DIA-102]: https://artsyproduct.atlassian.net/browse/DIA-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: prevents malicious hrefs

---

src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
src/Components/NavBar/menuData.ts

This PR solves [DIA-64]
Updates in curated collections in nav
[DIA-64]: https://artsyproduct.atlassian.net/browse/DIA-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(DIA-64): Update curated collections in nav

---

src/Components/NavBar/menuData.ts

This PR solves a small copy mistake from [DIA-64]
[DIA-64]: https://artsyproduct.atlassian.net/browse/DIA-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-64): Incorrect copy

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
src/__generated__/ArtistApp_Test_Query.graphql.ts
src/__generated__/ArtistHeader2_artist.graphql.ts
src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts

Removing code that touches this schema so we can deploy

fix(artist): removes verified reps for time being

---

src/Components/NavBar/menuData.ts

This PR solves a route typo from [DIA-64]
[DIA-64]: https://artsyproduct.atlassian.net/browse/DIA-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-64): Fixes incorrect nav route

---

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx

This PR solves [ONYX-270](https://artsyproduct.atlassian.net/browse/ONYX-270)
Update responsive margins and fontsize, remove empty Columns for mobile.
Create Alert CTA has a fixed width on all viewports except mobile.
https://github.com/artsy/force/assets/17580625/218d9dbd-7b2d-494d-ae35-6c0c1dd3db7f
[ONYX-270]: https://artsyproduct.atlassian.net/browse/ONYX-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-270): update responsive spacing and fontsize

---

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx

This PR solves [ONYX-270](https://artsyproduct.atlassian.net/browse/ONYX-270)
Adds hight and overflow to the skeleton to match the component.
[ONYX-270]: https://artsyproduct.atlassian.net/browse/ONYX-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-270): update skeleton with height and overflow

---

src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx

This PR solves [EMI-1437](https://artsyproduct.atlassian.net/browse/EMI-1437)
This fixes the broken help article link.
[EMI-1437]: https://artsyproduct.atlassian.net/browse/EMI-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix broken help article link

---

src/Apps/Order/Routes/Payment/PaymentContent.tsx
src/Apps/Order/Routes/__tests__/Payment.jest.tsx

This PR solves [EMI-1417]
Due to the longer timeline for SEPA payments, we should have clear messaging in the checkout flow that sets proper shipping expectation.
**Current messaging**
“Payment processing will take 4-7 business days once the gallery accepts the order.”
**Updated messaging**
Once your order is accepted, please allow 7-10 business days for processing your payment. After processing, your order will be prepared for pickup or packed and shipped, depending on your chosen delivery type.
[EMI-1417]: https://artsyproduct.atlassian.net/browse/EMI-1417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

chore(EMI-1417): update payment processing copy for SEPA

---

src/Apps/Order/Components/AddressVerificationFlow.tsx
src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx
src/__generated__/AddressVerificationFlowQuery.graphql.ts
src/__generated__/AddressVerificationFlow_Test_Query.graphql.ts
src/__generated__/AddressVerificationFlow_verifyAddress.graphql.ts

This PR solves [EMI-1308]
After merging https://github.com/artsy/metaphysics/pull/5250/files I did a QA on staging and didn't see the new exposed field there (see screenshot below), this is adding the missing generated files changes that are needed for it to work.
[EMI-1308]: https://artsyproduct.atlassian.net/browse/EMI-1308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-1308): run yarn relay-compiler

---

src/Components/Address/AddressForm.tsx
src/Components/Address/__tests__/AddressForm.jest.tsx
src/Components/Address/__tests__/useAddressAutocomplete.jest.ts
src/Components/Address/useAddressAutocomplete.ts

This PR solves [EMI-1458]
[EMI-1458]: https://artsyproduct.atlassian.net/browse/EMI-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-1458): change min chars on address input to 3 or more

---

src/Apps/Order/Routes/NewPayment/index.tsx

This PR adds event tracking to the "new payment" route which users visit when fixing a failed payment for an order.
The goal of this work is to better understand what dead-ends users encounter when re-submitting orders after fixing failed payments. We currently know that it is possible for this to fail if the seller's stripe account is deactivated before the buyer gets a chance to fix a failed payment. There may be other cases we are missing.

feat: add tracking events to errors in new payment route

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
src/Apps/Partner/Components/NavigationTabs/index.tsx
src/Apps/Partner/Components/PartnerHeader/index.tsx
src/Apps/Partner/Components/__tests__/PartnerHeader.jest.tsx
src/Utils/__tests__/formatFollowerCount.jest.ts
src/Utils/formatFollowerCount.ts
src/__generated__/PartnerApp_Test_Query.graphql.ts
src/__generated__/PartnerHeader_Test_Query.graphql.ts
src/__generated__/PartnerHeader_partner.graphql.ts
src/__generated__/partnerRoutes_PartnerQuery.graphql.ts

This PR solves [DIA-130]
Revert of original revert https://github.com/artsy/force/pull/12881 😅 
[DIA-130]: https://artsyproduct.atlassian.net/browse/DIA-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add follower count for galleries

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx

Closes [DIA-166](https://artsyproduct.atlassian.net/browse/DIA-166)
[DIA-166]: https://artsyproduct.atlassian.net/browse/DIA-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(artist): implements design q/a

---

package.json
src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
yarn.lock

Closes [DIA-112](https://artsyproduct.atlassian.net/browse/DIA-112)
[DIA-112]: https://artsyproduct.atlassian.net/browse/DIA-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dia-112): verified representation click tracking

---

src/Components/Address/__tests__/useAddressAutocomplete.jest.ts
src/Components/Address/useAddressAutocomplete.ts

This PR limits address autocomplete suggestions to 5, completing [EMI-1468].
1-line change, plus breaking up some tests.
[EMI-1468]: https://artsyproduct.atlassian.net/browse/EMI-1468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: EMI-1468 Limit address completion suggestions to 5

---

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/ArtworkAuctionCreateAlertHeader.jest.tsx

This PR solves [ONYX-313](https://artsyproduct.atlassian.net/browse/ONYX-313)
Remove feature flag `onyx_auction-header-alert-cta` for the released feature `Auction Header Alert CTA`
[ONYX-313]: https://artsyproduct.atlassian.net/browse/ONYX-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-313): remove featureflag onyx_auction-header-alert-cta

---

src/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlights.tsx
src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistCareerHighlights.jest.tsx

fix(artist): subtracts out highlights that exist within header

---

src/Components/Search/NewSearch/SearchBarInput.tsx

This is just one of those things I keep trying to do and being vaguely frustrated when it doesn't work. I'm a little unclear on the origin of this keyboard shortcut but it is pervasive at this point.

feat(search): focus search input on forward slash

---

cypress/e2e/feature.cy.ts

Looks like the previous feature is now unpublished.

chore: fix /feature/slug e2e cypress test

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx

Addresses [ONYX-79]
Meet the Specialist image issue.
| --- | --- |
|![Screenshot 2023-09-25 at 13 10 56](https://github.com/artsy/force/assets/4691889/d04e70c3-cbe9-493a-8b57-0040087016f8) |![Screenshot 2023-09-25 at 13 10 47](https://github.com/artsy/force/assets/4691889/ec1323cb-b09a-4bc1-b6fd-5da256d2f66a) |
[ONYX-79]: https://artsyproduct.atlassian.net/browse/ONYX-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Meet the Specialist image issue

---

src/Apps/Contact/ContactApp.tsx
src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

Just some minor copy changes for the contact and specialist pages.
https://artsyproduct.atlassian.net/browse/DIA-155
https://artsyproduct.atlassian.net/browse/DIA-164

chore: Copy updates on contact and specialist pages DIA-155

---

src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx

Add `name=priceRange` to Price Range select input on Edit Profile page so we can more easily query for it within Integrity (cypress) specs.

chore(integrity): add name to Edit Profile > Price Range select input

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
src/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlight.tsx
src/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlights.tsx
src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistCareerHighlights.jest.tsx
src/__generated__/ArtistCareerHighlight_insight.graphql.ts
src/__generated__/ArtistCareerHighlightsQuery.graphql.ts
src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
src/__generated__/ArtistCareerHighlights_artist.graphql.ts

Closes [DIA-176](https://artsyproduct.atlassian.net/browse/DIA-176)
[DIA-176]: https://artsyproduct.atlassian.net/browse/DIA-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DIA-176): Mobile web artist header

---

src/Apps/Artist/ArtistApp.tsx
src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
src/Apps/Artist/Routes/Overview/Components/ArtistEditorialNewsGrid.tsx

Just switches mobile to use the `FullBleedHeader` component.

fix(artist): header image consistency

---

src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx

This PR solves [EMI-1455] https://artsyproduct.atlassian.net/browse/EMI-1455
Adjust link to refer to the collector help centre article, instead of the partner one.
[EMI-1455]: https://artsyproduct.atlassian.net/browse/EMI-1455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-1455): taxes link in checkout

---

src/Apps/Order/Routes/Payment/PaymentContent.tsx

This PR solves [EMI-1346]
https://artsyproduct.atlassian.net/browse/EMI-1346
Use proper mailto: for the orders email in checkout
[EMI-1346]: https://artsyproduct.atlassian.net/browse/EMI-1346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use proper mailto: in wire transfer checkout

---

scripts/setup.sh

This updates our `setup.sh` script to also install watchman, which is needed for relay.

feat(setup): Add watchman to brew install

---

src/Apps/Search/Routes/SearchResultsArtworks.tsx

Fixes typo mentioned [here](https://github.com/artsy/force/pull/12941#pullrequestreview-1644589457).

fix: fixes typo

---

src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
src/Apps/Settings/Routes/EditSettings/Components/useUpdateSettingsInformation.ts
src/__generated__/SettingsEditSettingsInformation_Test_Query.graphql.ts
src/__generated__/SettingsEditSettingsInformation_me.graphql.ts
src/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
src/__generated__/useUpdateSettingsInformationMutation.graphql.ts

All works nicely! It correctly sends back (and persists on the backend) the more structured phone number + region code.

fix: update settings page to send phone country code in order to persist the structured data

---

src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx

chore: scroll advisory opportunity section into view in create alert modal

---

package.json
yarn.lock

Revert "chore(deps): update dep typescript from 4.7.4 to v5"

---

src/Apps/Order/Routes/Payment/PaymentContent.tsx

This PR solves [EMI-1379]
The PR updates the `Bank transfer` text to `ACH bank transfer`.
[EMI-1379]: https://artsyproduct.atlassian.net/browse/EMI-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update the text

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx
src/Apps/Partner/Components/PartnerHeader/index.tsx
src/Components/FollowButton/Button.tsx
src/Components/FollowButton/FollowArtistButton.tsx
src/Components/FollowButton/FollowGeneButton.tsx
src/Components/FollowButton/FollowProfileButton.tsx

Closes [DIA-184](https://artsyproduct.atlassian.net/browse/DIA-184)
Adds inline counts to the buttons on mobile
| Artist | Profile |
| --- | --- |
| ![localhost_5050_partner_white-cube(iPhone XR) (1)](https://github.com/artsy/force/assets/112297/6b20972c-23d6-41cf-9b24-331cf3a41544) | ![localhost_5050_partner_white-cube(iPhone XR)](https://github.com/artsy/force/assets/112297/cae4481c-92b5-4bf5-9efa-f4bb0db7003a) |
[DIA-184]: https://artsyproduct.atlassian.net/browse/DIA-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DIA-184): inline follow counts on mobile

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/Components/ArtworkFilter/ArtworkFilters/AttributionClassFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick/FilterQuick.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick/__tests__/FilterQuick.jest.tsx
src/Components/ArtworkFilter/index.tsx
src/Components/SavedSearchAlert/Utils/extractPills.ts

Closes [DIA-218](https://artsyproduct.atlassian.net/browse/DIA-218)
Closes [DIA-219](https://artsyproduct.atlassian.net/browse/DIA-219)
Just adds these two simple multi-select filters.
https://github.com/artsy/force/assets/112297/672e707c-8bda-4e69-9048-a96e14fa1907
[DIA-218]: https://artsyproduct.atlassian.net/browse/DIA-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DIA-219]: https://artsyproduct.atlassian.net/browse/DIA-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(filters): adds rarity and medium quick filters

---

data/schema.graphql
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/Components/SavedSearchAlert/Components/DetailsInput.tsx
src/Components/SavedSearchAlert/Components/PriceRangeFilter.tsx
src/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButtonContainer.tsx
src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
src/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
src/Components/SavedSearchAlert/types.ts
src/__generated__/SavedSearchAlertEditFormQuery.graphql.ts
src/__generated__/SavedSearchAlertEditForm_Test_Query.graphql.ts
src/__generated__/SavedSearchAlertEditForm_me.graphql.ts
src/__generated__/createSavedSearchAlertMutation.graphql.ts
src/__generated__/useEditSavedSearchAlertMutation.graphql.ts

This PR solves [ONYX-433]
> [!WARNING]
> Do not merge until https://github.com/artsy/metaphysics/pull/5355 is deployed to prod
- Added new "details" text input to create / update alerts UI.
- Fold price range component on mWeb
- Fixed uneven margins around pills
| Desktop | mWeb |
|---|---|
| ![Screenshot 2023-10-19 at 11 20 42](https://github.com/artsy/force/assets/3934579/0ead2c3e-0157-4148-aac3-12c8dcea7c08) | ![Screenshot 2023-10-19 at 11 21 12](https://github.com/artsy/force/assets/3934579/52cdc4e4-3d57-4663-aeac-304b274de5c7) |
[ONYX-433]: https://artsyproduct.atlassian.net/browse/ONYX-433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-433): add details text input to create / update alerts UI

---

src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/PriceRangeFilter.tsx
src/Components/ArtworkFilter/ArtworkFilterSort.tsx
src/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick/FilterQuick.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick/PriceRangeFilterQuick.tsx
src/Components/ArtworkFilter/index.tsx

Closes [DIA-220](https://artsyproduct.atlassian.net/browse/DIA-220)
Extracts out most of the logic for the existing price range filter into a hook + uses it for the quick filter.
https://github.com/artsy/force/assets/112297/905a8993-8c68-41d3-94e8-9c250f031edc
[DIA-220]: https://artsyproduct.atlassian.net/browse/DIA-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dia-220): implements price range quick filter

---

src/Components/SavedSearchAlert/Components/DetailsInput.tsx

This PR solves [onyx-433]
Change the text area placeholder copy on create / update alerts form.
Per [this request](https://artsy.slack.com/archives/C05EQL4R5N0/p1698073299830419?thread_ts=1698065852.642879&cid=C05EQL4R5N0).

feat(onyx-433): create / edit alert modal copy update

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormDesktop.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormMobile.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx

This PR solves [ONYX-271]
Removed `onyx_force-fallback-to-generated-alert-names` feature flag related logic 
[ONYX-271]: https://artsyproduct.atlassian.net/browse/ONYX-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ONYX-271): cleanup ff related code

---

src/Apps/Order/Components/AddressVerificationFlow.tsx
src/Apps/Order/Components/ShippingQuotes.tsx
src/Apps/Order/Routes/Shipping2/AddressModal.jest.tsx
src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
src/Apps/Order/Routes/Shipping2/SavedAddresses2.jest.tsx
src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
src/Apps/Order/Routes/Shipping2/Shipping2.jest.tsx
src/Apps/Order/Routes/Shipping2/ShippingContext.ts
src/Apps/Order/Routes/Shipping2/index.tsx
src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
src/Components/CountrySelect.tsx

This PR continues the shipping route refactor by fixing most address verification specs. It does _not_ include the saved addresses specs because they are complicated by other factors around testing shipping quotes, but the functionality should be there.

Refactor [EMI-1513]: Shipping2 address verification

---

src/Components/Alert/Components/Filters/__tests__/Medium.jest.tsx

- Context: https://github.com/artsy/force/pull/13106#discussion_r1386487311
Remove filter context from alert medium filter test.

chore: Remove filter context from alert medium filter test

---

src/Components/CreditCardInput/CreditCardInput.tsx

This PR solves [ONYX-522]
Add some selectors in order update the specs that started failing in Integrity after the credit card form changed.
Integrity PR to come shortly…
[ONYX-522]: https://artsyproduct.atlassian.net/browse/ONYX-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: add new selectors for Integrity to fix CC issue

---

src/Components/NavBar/Menus/NavBarSubMenu.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileSubMenu.tsx
src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
src/Components/NavBar/menuData.ts

Re: [DIA-191](https://artsyproduct.atlassian.net/browse/DIA-191)
This updates the nav items and makes some slight alterations to the structuring. Notably missing here is the updated artists list which I'll tackle in a follow up PR.
https://github.com/artsy/force/assets/112297/8deec8fe-a44c-4250-ac5d-cea1579a7f43
[DIA-191]: https://artsyproduct.atlassian.net/browse/DIA-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(nav): updates nav items

---

src/Components/Alert/Components/Steps/Filters.tsx

Current: Price Range > Rarity > Medium
Desired: Medium > Rarity > Price Range
Related Eigen (app) PR: https://github.com/artsy/eigen/pull/9555
cc/ @dariakoko @tam-kis @olerichter00 

feat(alerts): reorder filters in new create alert modal

---

src/Components/Alert/Components/Steps/Details.tsx

Email Alerts > Email
Mobile Alerts > Push Notifications

feat(alerts): copy update for details screen

---

src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
src/Utils/__tests__/isArtsyEmail.jest.ts
src/Utils/isArtsyEmail.ts

This PR solves [PHIRE-443]
Add a `Sup` next to the "App Authenticator" option to indicate it is the preferred method for 2fa. 🔒 [Slack discussion](https://artsy.slack.com/archives/C03N12SR0RK/p1699632665246949?thread_ts=1699631939.121759&cid=C03N12SR0RK).
[PHIRE-443]: https://artsyproduct.atlassian.net/browse/PHIRE-443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: mark App Authenticator as preferred 2fa method

---

src/Apps/Article/Components/ArticleBody.tsx
src/Components/Sticky/Sticky.tsx

Closes [DIA-194](https://artsyproduct.atlassian.net/browse/DIA-194)
This PR implements a sticky sidebar that releases when at the boundary of the article. Previously we weren't updating the sticky context when something was unstuck.
[DIA-194]: https://artsyproduct.atlassian.net/browse/DIA-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dia-194): sticky article sidebar

---

package.json
src/Components/Alert/Hooks/useAlert.tsx
yarn.lock

This PR bumbs the `Cohesion`. version to use `createAlert` as `AuthContextModule`.

chore: Cohesion createAlert AuthContextModule type

---

src/Components/Alert/Components/CriteriaPills.tsx
src/Components/Alert/Components/Filters/Medium.tsx
src/Components/Alert/Components/Filters/QuickMultipleSelectAlertFilter.tsx
src/Components/Alert/Components/Modal.tsx
src/Components/Alert/Components/Steps.tsx
src/Components/Alert/Components/Steps/Details.tsx
src/Components/Alert/Components/Steps/Filters.tsx

This PR solves [ONYX-529](https://artsyproduct.atlassian.net/browse/ONYX-529)
Update UI for new Alert Modal: limit number of pills, add sticky header and Set Filter button on the Filters modal.
Added animation but this is still being discussed and yet to be refined.
https://github.com/artsy/force/assets/17580625/c87d6256-72a4-49fa-ab3d-5c5c2f26656e
[ONYX-529]: https://artsyproduct.atlassian.net/browse/ONYX-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-529): alert modal UI updates

---

src/Components/Alert/Components/Filters/Price.tsx
src/Components/Alert/Components/Filters/__tests__/Price.jest.tsx
src/Components/Alert/Components/Steps/Filters.tsx
src/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
src/__generated__/PriceAggregationsQuery.graphql.ts
src/__generated__/Price_aggregations.graphql.ts
src/__generated__/Price_artworksConnection.graphql.ts

This PR solves [ONYX-525]
This PR adds the Alert filter price histogram.
[ONYX-525]: https://artsyproduct.atlassian.net/browse/ONYX-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Alert filter price histogram

---

src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/SelectArtworkListsModal.tsx
src/__generated__/SelectArtworkListsModalQuery.graphql.ts
src/__generated__/SelectArtworkListsModal_Test_Query.graphql.ts
src/__generated__/SelectArtworkListsModal_me.graphql.ts

Addresses [ONYX-120]
Sort artwork lists by updated at desc.
[ONYX-120]: https://artsyproduct.atlassian.net/browse/ONYX-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Sort artwork lists by updated at desc

---

src/Components/Alert/AlertContext.ts
src/Components/Alert/AlertProvider.tsx
src/Components/Alert/Components/Filters/Size.tsx
src/Components/Alert/Components/Filters/__tests__/Size.jest.tsx
src/Components/Alert/Components/Steps/Filters.tsx
src/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter.jest.tsx
src/Components/SavedSearchAlert/Utils/extractPills.ts
src/Utils/__tests__/customSizeUtils.jest.ts
src/Utils/customRangeUtils.ts
src/Utils/customSizeUtils.ts

This PR solves [ONYX-472]
Add size filter to alert filters screen.
- [Review app](https://alerts-size-filter.artsy.net/)
https://github.com/artsy/force/assets/3934579/48445303-a5ba-4ad8-8011-9cf8883167b5
[ONYX-472]: https://artsyproduct.atlassian.net/browse/ONYX-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-472): add size filter to alert filters

---

src/Components/ArtworkFilter/index.tsx

This reverts commit 9f2dc1267b95c34fd3f955aa6ecf4482f795387a.
Re: https://artsy.slack.com/archives/C03N12SR0RK/p1701216437888209
Will follow up with correct fix.

Revert "feat(filters): jump to top on filter apply"

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx

This PR adjusts the sellers' bio and photo.

fix: adjust sellers bio and photo

---

src/Apps/Conversations/components/ConversationCTA/ConversationReviewOfferCTA.tsx
src/Apps/Conversations/components/Details/OrderInformation/__tests__/OrderState.jest.tsx
src/Apps/Conversations/components/Details/OrderState/ConversationStatusWithCounter.tsx

This updates the convos message status copy a bit to be more reflective of the collector -> buyer dynamic

chore(convos): Update copy

---

src/Apps/Conversations/ConversationApp.tsx
src/Apps/Conversations/components/ConversationZeroState.tsx
src/Apps/Conversations/conversationsRoutes.tsx
src/__generated__/conversationsRoutes_DetailQuery.graphql.ts

feat(convos): Add ZeroState

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx

Simply moves the Artist Series filter into the agreed upon position (after medium/rarity/price).

feat: move artist series filter into correct position

---

src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
src/Apps/Order/Routes/Shipping2/Mutations/useDeleteSavedAddress.ts
src/Apps/Order/Routes/Shipping2/Mutations/useSelectShippingQuote.ts
src/Apps/Order/Routes/Shipping2/Mutations/useUpdateSavedAddress.ts
src/Apps/Order/Routes/Shipping2/Mutations/useUpdateUserDefaultAddress.ts
src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
src/Apps/Order/Routes/Shipping2/index.tsx
src/__generated__/useCreateSavedAddressMutation.graphql.ts
src/__generated__/useDeleteSavedAddressMutation.graphql.ts
src/__generated__/useSelectShippingQuoteMutation.graphql.ts
src/__generated__/useUpdateSavedAddressMutation.graphql.ts
src/__generated__/useUpdateUserDefaultAddressMutation.graphql.ts

Follow-up to #13231 - #minor fix to re-generate some relay types affected by that change.

fix: generate and fix types

---

src/Components/Alert/Components/Filters/QuickMultipleSelectAlertFilter.tsx
src/Components/Alert/Components/Form/SuggestedFilters.tsx
src/Components/Alert/Components/Form/__tests__/SuggestedFilters.jest.tsx
src/Components/Alert/Components/Steps/Details.tsx
src/Components/Alert/Helpers/handleFieldsWithMultipleValues.ts
src/Components/Alert/Helpers/isValueSelected.tsx
src/Components/Alert/Hooks/__tests__/AlertProvider.jest.tsx
src/DevTools/setupTestWrapper.tsx
src/__generated__/SuggestedFiltersFetchQuery.graphql.ts

This PR solves [ONYX-385]
This PR adds suggested filters to the saved search flow.
https://github.com/artsy/force/assets/11945712/42dedc91-9541-44ee-8b0e-87560cb1a8a4
[ONYX-385]: https://artsyproduct.atlassian.net/browse/ONYX-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-385): Saved searches suggested filters

---

src/Apps/Order/Routes/NewPayment/index.tsx

It fixes the SCA flow in the Fix Failed Payment flow by handling the post-SCA mutation to Exchange inline (rather than calling `onContinue` a second time).
This was needed because the second call to `onContinue` did not have access to the same state and ref values that the first call had, so SCA was never completing.

fix: failed payment SCA (EMI-1214)

---

src/Components/Alert/Components/Form/SuggestedFilters.tsx
src/Components/Alert/Components/Form/__tests__/SuggestedFilters.jest.tsx
src/Components/Alert/Components/Steps/Details.tsx

[ONYX-580]
This PR updates the copy on create alert flow
[ONYX-580]: https://artsyproduct.atlassian.net/browse/ONYX-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-580): update create alert copy

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
src/Components/Alert/AlertContext.ts
src/Components/Alert/AlertProvider.tsx
src/Components/Alert/Components/NotificationPreferences.tsx
src/__generated__/NewSavedSearchAlertEditFormQuery.graphql.ts
src/__generated__/NewSavedSearchAlertEditForm_searchCriteria.graphql.ts

This PR is against another feature branch with feedback on #13206.

review: feedback on #13206

---

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx

This PR solves [ONYX-554]
Render old / new alert button / form conditionally.
Demo:
https://github.com/artsy/force/assets/3934579/4709262a-f598-441d-9696-2740f434749d
[ONYX-554]: https://artsyproduct.atlassian.net/browse/ONYX-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-554): Include new modal design to closed lot alert header via feature flag

---

src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx

This PR solves [ONYX-595]
This PR fixes an issue affecting the UX while saving alerts.
https://github.com/artsy/force/assets/11945712/79248ce4-c3fc-4397-b7e1-a741d992015e
[ONYX-595]: https://artsyproduct.atlassian.net/browse/ONYX-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: get alerts list to update properly

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormPlaceholder.tsx
src/Components/Alert/Components/CriteriaPills.tsx
src/Components/Alert/Components/Form/SuggestedFilters.tsx
src/Components/Alert/Components/Form/__tests__/SuggestedFilters.jest.tsx

This PR solves [ONYX-601]
This PR fixed placeholder on the Edit Alert form
| Form | Placeholder |
| --- | --- |
| <img width="1391" alt="image" src="https://github.com/artsy/force/assets/36167539/f914c15d-5829-4fcd-9774-9894319be382"> | <img width="1396" alt="image" src="https://github.com/artsy/force/assets/36167539/821b1b04-aa5f-47c8-953c-3bf31c045c50"> |
[ONYX-601]: https://artsyproduct.atlassian.net/browse/ONYX-601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-601): fix placeholder on the edit alert form

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
src/Components/Alert/Components/Steps/Filters.tsx

This PR solves [ONYX-591](https://artsyproduct.atlassian.net/browse/ONYX-591)
Remove Separators from Edit form and adjust spacing to Create Alert modal.
Reduce spacing between Filters and SetFilters button.
[ONYX-591]: https://artsyproduct.atlassian.net/browse/ONYX-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-591): remove separators and update spacing

---

src/Apps/Order/Routes/Shipping2/AddressModal2.tsx
src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
src/Apps/Order/Routes/Shipping2/FulfillmentDetailsForm.tsx
src/Apps/Order/Routes/Shipping2/Utils/ShippingContext/ShippingContext.tsx
src/Apps/Order/Routes/Shipping2/__tests__/AddressModal2.jest.tsx
src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
src/Apps/Order/Routes/Shipping2/index.tsx

It is a rebase of #13260. 
Completes [EMI-1613]
This PR continues the Shipping route refactoring project by putting loading state in the route around places we call mutations. There is also a minor fix for automatically selecting shipping quotes when they change.
[EMI-1613]: https://artsyproduct.atlassian.net/browse/EMI-1613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: Shipping2 loading state

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx

This PR solves [ONYX-596](https://artsyproduct.atlassian.net/browse/ONYX-596)
Add animation to Details in the Edit Alert form,
https://github.com/artsy/force/assets/17580625/033fa7cc-f6e8-47f1-8eb4-5912e2ee2234
[ONYX-596]: https://artsyproduct.atlassian.net/browse/ONYX-596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-596): add animation to Details in Edit Alert form

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertDeleteModal.tsx

Add testid to the delete alert button

chore: add testid to the delete alert button

---

src/Apps/Order/Routes/Shipping2/__tests__/FulfillmentDetailsForm.jest.tsx
src/Apps/Order/Routes/Shipping2/__tests__/SavedAddresses2.jest.tsx

A few test fixes for #13297 - mostly updating spec setup for the new organization.

fix SavedAddresses2 specs

---

src/Apps/Partner/Components/Overview/SubscriberBanner.tsx
src/__generated__/SubscriberBanner_partner.graphql.ts
src/__generated__/partnerRoutes_OverviewQuery.graphql.ts

This PR solves [DIA-347]
Updates copy for all churned partners and fairs.
[DIA-347]: https://artsyproduct.atlassian.net/browse/DIA-347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DIA-347]: https://artsyproduct.atlassian.net/browse/DIA-347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update copy for subscribe banner

---

src/Apps/ViewingRoom/Components/ViewingRoomContentNotAccessible.tsx

This PR solves [DIA-355](https://artsyproduct.atlassian.net/browse/DIA-355)
Changing the Viewing Room button copy from `Visit Gallery` to `View Works`
[DIA-355]: https://artsyproduct.atlassian.net/browse/DIA-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: change Viewing Room button copy

---

package.json
yarn.lock

Revert "chore(deps): update dep @artsy/palette from 37.2.2 to v37.3.0"

---

src/Apps/Notifications/NotificationApp.tsx
src/Apps/Notifications/notificationsRoutes.ts
src/Components/Notifications/Notification.tsx
src/Components/Notifications/__tests__/Notification.jest.tsx
src/__generated__/NotificationApp_me.graphql.ts
src/__generated__/Notification_me.graphql.ts
src/__generated__/Notification_test_Query.graphql.ts
src/__generated__/notificationsRoutesNotificationQuery.graphql.ts

Addresses [ONYX-622]
This PR adds a route and app and query for the new Notification page. The implementation of the content of the page is not part of this PR.
I extracted most of the code from this prototype PR: https://github.com/artsy/force/pull/13165
[ONYX-622]: https://artsyproduct.atlassian.net/browse/ONYX-622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: New Notification route

---

src/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButtonContainer.tsx
src/Components/SavedSearchAlert/SavedSearchAlertContext.tsx
src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
src/Components/SavedSearchAlert/types.ts

Rename saved search alert to alert in comments.

chore: Rename saved search alert to alert in comments

---

src/Apps/Artwork/ArtworkApp.tsx

This PR solves [EMI-1595]
Change copy
[EMI-1595]: https://artsyproduct.atlassian.net/browse/EMI-1595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-1595): change unavailable copy

---

src/Apps/Notifications/NotificationsApp.tsx

Use borderColor instead of hex value.

chore: Use borderColor instead of hex value

---

src/System/Router/ErrorBoundary.tsx

@joeyAghion [noticed](https://artsy.slack.com/archives/CP9P4KR35/p1705618588927709?thread_ts=1705595615.137369&cid=CP9P4KR35) our `ErrorBoundary` was... erroring.
It's due to found's `HttpError` class, not extending `Error`. So there's no message. While I'm in here I just made it so that our client-side routing errors will behave in the same manner as a server-side one, in terms of what they display.

fix(errorboundary): fixes client-side routing-error error

---

src/Components/Notifications/Notifications.tsx
src/Components/Notifications/NotificationsEmptyStateByType.tsx
src/Components/Notifications/NotificationsHeader.tsx
src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/NotificationsPills.tsx
src/Components/Notifications/NotificationsWrapper.tsx
src/Components/Notifications/__tests__/Notifications.jest.tsx
src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
src/Components/Notifications/types.ts
src/Components/Notifications/useNotificationsContext.tsx

This PR solves [ONYX-627](https://artsyproduct.atlassian.net/browse/ONYX-627)
Refactor and replace existing NotificationsTabs with Pills.
Separate Notifications header and pills components.
Dropdown:
https://github.com/artsy/force/assets/17580625/3879ee8b-9b13-4978-846c-1bde392d9278
Activity Panel:
https://github.com/artsy/force/assets/17580625/653d1673-ffbc-403d-a367-100e65b2bb97
No alerts, empty state:
https://github.com/artsy/force/assets/17580625/eef6f0b8-f2f3-4c6c-97dc-9dd763bfdac9
[ONYX-627]: https://artsyproduct.atlassian.net/browse/ONYX-627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

feat(ONYX-627): activity list pills

---

src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx

These tests are flaky and not needed right now.
#minor

chore: pend shipping2 tests

---

src/Apps/Notifications/NotificationsApp.tsx
src/Components/Notifications/NotificationItem.tsx
src/Components/Notifications/NotificationTypeLabel.tsx
src/Components/Notifications/NotificationsHeader.tsx
src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/NotificationsListPlaceholder.tsx
src/Components/Notifications/__tests__/NotificationItem.jest.tsx
src/Components/Notifications/util.ts
src/__generated__/NotificationItem_item.graphql.ts
src/__generated__/NotificationItem_test_Query.graphql.ts
src/__generated__/NotificationsListNextQuery.graphql.ts
src/__generated__/NotificationsListQuery.graphql.ts
src/__generated__/NotificationsList_test_Query.graphql.ts

Addresses [ONYX-657]
This PR updates the design of the Activity list items.
| --- | --- |
|<img width="379" alt="Screenshot 2024-01-25 at 16 55 31" src="https://github.com/artsy/force/assets/4691889/c3472cc6-02c1-4289-b5d1-6b3a286c937f"> | <img width="383" alt="Screenshot 2024-01-25 at 16 54 37" src="https://github.com/artsy/force/assets/4691889/b142ecfb-319f-4e08-a0ee-0ced04a15860">|
[ONYX-657]: https://artsyproduct.atlassian.net/browse/ONYX-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Activity list item design update

---

src/Apps/CollectorProfile/Routes/Saves/Components/Actions/ArtworkListContextualMenu.tsx
src/Components/ContextualMenu/ContextualMenu.tsx
src/Components/Notifications/MarkAllAsReadPanel.tsx
src/Components/Notifications/NotificationsContextualMenu.tsx
src/Components/Notifications/NotificationsHeader.tsx
src/Components/Notifications/NotificationsWrapper.tsx
src/Components/Notifications/__tests__/Notifications.jest.tsx

This PR solves [ONYX-628](https://artsyproduct.atlassian.net/browse/ONYX-628)
Update ContextualMenu with z-index and placement - necessary for adding it to dropdowns.
Add NotificationsContextualMenu to the Notifications.
https://github.com/artsy/force/assets/17580625/f6658168-fbd1-4e5f-a85c-27820d1fba6d
https://github.com/artsy/force/assets/17580625/678dcf33-8111-4bfc-a884-05989e17a306
[ONYX-628]: https://artsyproduct.atlassian.net/browse/ONYX-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-628): add and update ContextualMenu

---

src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGallery.tsx
src/Apps/Order/Routes/__tests__/Shipping.jest.tsx

I somehow missed left this in when doing the dark mode mega-PR.

fix(article): removes debug code

---

src/Components/Notifications/util.ts

- Countdown timer should display days + hours (currently displays only days)
- Adds pluralisation logic for days, hours, minutes, seconds
- [Slack thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1706565019774699)

fix: fixes partner offer notification timer

---

src/Components/Notifications/__tests__/util.jest.ts
src/Components/Notifications/util.ts

This PR solves [Onyx-724]
Do not show partner offers with unpublished artwork

fix(onyx-724): hide partner show notifications with unpublished artwork

---

src/Apps/Partner/Components/PartnerHeader/index.tsx

This PR solves [DIA-447]
Before
After 
[DIA-447]: https://artsyproduct.atlassian.net/browse/DIA-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove followers count on mobile view

---

src/Apps/Artwork/Components/ArtworkErrorApp/ArtworkErrorApp.tsx
src/Apps/Artwork/artworkRoutes.tsx
src/System/useFeatureFlag.tsx

Oh, and also the correct feature flag enabled check! This was erroneously on in production.

fix: update artwork custom error page copy

---

src/Apps/Fairs/Routes/FairsIndex.tsx
src/Apps/Fairs/Routes/__tests__/FairsIndex.jest.tsx
src/Apps/Home/Components/HomeCurrentFairs.tsx
src/Apps/Home/__tests__/HomeCurrentFairs.jest.tsx
src/Components/NavBar/NavBar.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
src/Components/NavBar/__tests__/NavBarTracking.jest.tsx
src/System/i18n/locales/en-US/translation.json

This PR solves [DIA-442]
Changing copy from Fairs to Fairs & Events per this [document](https://docs.google.com/document/d/1T6a5X79rwevDyenqBB2EALtAyYkjLDzs0x7ZFG3ZetE/edit)
[DIA-442]: https://artsyproduct.atlassian.net/browse/DIA-442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore(copy): Fairs -> Fairs & Events

---

src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/NotificationsWrapper.tsx

This PR solves [ONYX-688]
This pull request removes the "Show More" button from the notification list and includes some design fixes:
-  Removes the bottom border of the notification list.
-  Adjusts the maximum height of the notification list to prevent over-scrolling.
[ONYX-688]: https://artsyproduct.atlassian.net/browse/ONYX-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Remove notification list Show More button and design fixes

---

src/Apps/Order/Components/PartnerOfferTimerItem.tsx

Don't include seconds, adjust copy around expiration
https://artsyproduct.atlassian.net/browse/EMI-1687
https://artsyproduct.atlassian.net/browse/EMI-1673

fix: adjust checkout timer copy

---

src/Components/NavBar/menuData.ts

This PR solves [DIA-357]
Changing the list of trending artists and hard coding for now.
Next: look at creating a set in Forque to manage this data vs hard coding it.
[DIA-357]: https://artsyproduct.atlassian.net/browse/DIA-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore(copy): Change trending artists in nav bar

---

src/Apps/Artwork/ArtworkApp.tsx

This PR solves [EMI-1700]
Copy change
[EMI-1700]: https://artsyproduct.atlassian.net/browse/EMI-1700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-1700): offer expired banner copy change

---

src/Components/Artwork/GridItem.tsx

Let's remove the flag as it all seems to be working quite well!

chore: remove blurhash feature flag usage

---

src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/__tests__/NotificationsList.jest.tsx
src/__generated__/NotificationsListNextQuery.graphql.ts
src/__generated__/NotificationsList_viewer.graphql.ts

Pagination doesn't work - for some reason Force always sends the same `cursor`. I can't figure why this happens, but it was probably introduced in [this PR](https://github.com/artsy/force/pull/13485), when switching to `usePaginationFragment` hook.

fix: fixes broken pagination for activity panel

---

src/Components/Notifications/NotificationItem.tsx
src/Components/Notifications/NotificationTypeLabel.tsx

Addresses [ONYX-768]
This PR fixes the partner offer notification item design.
| --- | --- |
|<img width="381" alt="Screenshot 2024-02-21 at 10 01 13" src="https://github.com/artsy/force/assets/4691889/e7380ea7-e3c5-4c4d-9d9e-a7781cccf963"> |<img width="373" alt="Screenshot 2024-02-21 at 10 00 04" src="https://github.com/artsy/force/assets/4691889/a514c31d-96df-4260-9562-2a4fab5e9610"> |
[ONYX-768]: https://artsyproduct.atlassian.net/browse/ONYX-768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Partner offer notification item design

---

src/Components/Notifications/Mutations/markAllNotificationsAsRead.ts
src/Components/Notifications/Mutations/markNotificationAsRead.ts
src/Components/Notifications/Mutations/markNotificationsAsSeen.ts
src/__generated__/markAllNotificationsAsReadMutation.graphql.ts
src/__generated__/markNotificationAsReadMutation.graphql.ts
src/__generated__/markNotificationsAsSeenMutation.graphql.ts

Addresses [ONYX-750]
Correctly update unreadNotificationsCount when reading notification.
[ONYX-750]: https://artsyproduct.atlassian.net/browse/ONYX-750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Correctly update unreadNotificationsCount when reading notification

---

src/Components/Notifications/NotificationsPills.tsx

https://www.notion.so/artsy/Inconsistency-in-filter-pills-between-web-Following-and-app-Follows-5161c13888284a70b7b020a008de7ab5?pvs=4
Rename Follows notification filter pill.

fix: Rename Follows notification filter pill

---

package.json
src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
src/Components/ArticleShare.tsx
src/Components/Footer/Footer.tsx
yarn.lock

Closes [DIA-413](https://artsyproduct.atlassian.net/browse/DIA-413)
Also updates in the share menu. Changes URLs to what they redirect to, where relevant.
[DIA-413]: https://artsyproduct.atlassian.net/browse/DIA-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dia-413): update twitter icon to x in footer

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
src/Components/Alert/AlertContext.ts
src/Components/Alert/AlertProvider.tsx

- [Spotted by Integrity](https://artsy.slack.com/archives/C067SRUKSNM/p1709212046275799)
Fixes infinite loading of "Save artwork" button on the alert edit page.

fix: fix infinite loading state of submit button on edit alert

---

src/Apps/Artwork/ArtworkApp.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPrivateArtwork.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutWork.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkCondition.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkDetails.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkExhibitionHistory.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkProvenance.tsx
src/__generated__/ArtworkApp_artwork.graphql.ts
src/__generated__/ArtworkSidebarPrivateArtwork_artwork.graphql.ts
src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
src/__generated__/ArtworkSidebar_artwork.graphql.ts
src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
src/__generated__/PrivateArtworkAboutWork_artwork.graphql.ts
src/__generated__/PrivateArtworkCondition_artwork.graphql.ts
src/__generated__/PrivateArtworkDetails_artwork.graphql.ts
src/__generated__/PrivateArtworkExhibitionHistory_artwork.graphql.ts
src/__generated__/PrivateArtworkProvenance_artwork.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

⚠️ Guarded behind `amber_artwork_visibility_unlisted` 
1st PR of a few. This stubs out some simple no-design components and relay data stubs, getting in the app structure. 
Next PR will include design. 

feat(private-artworks): Stub out components and relay 

---

src/Components/Notifications/NotificationsPills.tsx
src/__generated__/NotificationsPillsQuery.graphql.ts

This PR resolves [ONYX-757](https://artsyproduct.atlassian.net/browse/ONYX-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Use totalCount for offer notifications because the workaround is not needed in production.
[ONYX-757]: https://artsyproduct.atlassian.net/browse/ONYX-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Use totalCount for offer notifications

---

src/Components/Notifications/__tests__/Notifications.jest.tsx

Fix Activity panel filter pills test.

chore: Fix Activity panel filter pills test

---

src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx

This PR solves [ONYX-826]
Select another alert after deletion
| --- | --- |
| <video src="https://github.com/artsy/force/assets/36167539/050e4f72-142e-4e4f-8bca-e90078bca32d"> | <video src="https://github.com/artsy/force/assets/36167539/9d1c72aa-ce83-4ddc-9d5d-2ff8d377c662"> |
[ONYX-826]: https://artsyproduct.atlassian.net/browse/ONYX-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-826): fix performance after alert deletion

---

src/Apps/Show/Components/ShowHeader.tsx

fix(show): hyphenates titles if need be

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPrivateArtwork.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPrivateArtwork.jest.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutWork.tsx
src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkAboutArtist.jest.tsx
src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkAboutWork.jest.tsx
src/__generated__/ArtworkSidebarPrivateArtworkQuery.graphql.ts
src/__generated__/ArtworkSidebarPrivateArtwork_artwork.graphql.ts
src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
src/__generated__/PrivateArtworkAboutWorkQuery.graphql.ts
src/__generated__/PrivateArtworkAboutWork_artwork.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

This PR solves [AMBER-535]
Renders the "About The Artist" and "About This Work" sections of the private artworks page. 
[AMBER-535]: https://artsyproduct.atlassian.net/browse/AMBER-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AMBER-535]: https://artsyproduct.atlassian.net/browse/AMBER-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore (Amber-535): Private Artwork Page "About Artist" and "About Artwork" sections 

---

src/Apps/CollectorProfile/Routes/Saves/Components/Actions/Mutations/useCreateCollection.ts
src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListContent.tsx
src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListItem.tsx
src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/SelectArtworkListItem.tsx
src/Apps/CollectorProfile/Routes/Saves/Components/__tests__/ArtworkListContent.jest.tsx
src/Apps/CollectorProfile/Routes/Saves/Components/__tests__/ArtworkListItem.jest.tsx
src/__generated__/useCreateCollectionMutation.graphql.ts

This should complete https://artsyproduct.atlassian.net/browse/EMI-1761
Had several of hours of waiting in between the trains and tracked down this error. Super minor at the end but took a bit of figuring out how this page set up :)
Also noticed that 'lock icon' is right aligned in the card in designs. So adjusted that as well.

fix: properly display privacy status after list creation

---

src/Apps/Auction/Components/Form/ConditionsOfSaleCheckbox.tsx
src/Apps/Auction/Components/Form/__tests__/ConditionsOfSaleCheckbox.jest.tsx

This PR updates the copy on the checkbox at the bottom of the auction registration modal.
|--------|------|
| <img width="549" alt="Screenshot 2024-03-26 at 6 47 00 AM" src="https://github.com/artsy/force/assets/44589599/7c853d5b-942a-4d8b-bc0f-0cf1cbd36d0e"> | <img width="554" alt="Screenshot 2024-03-26 at 6 45 46 AM" src="https://github.com/artsy/force/assets/44589599/ba5f6937-85c7-426e-a0cc-8e13bafe3fc8"> |

chore: update conditions of sale checkbox (DIA-538)

---

src/Components/TermsUpdateDialog.tsx
src/System/Router/Boot.tsx
src/tests.ts

Closes [DIA-174](https://artsyproduct.atlassian.net/browse/DIA-174)
[DIA-174]: https://artsyproduct.atlassian.net/browse/DIA-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adds terms update dialog

---

src/Components/NavBar/menuData.ts

This PR solves [GRO-563]
Curator's Picks -> Curators' Picks
**Under Artists**
**Under Artworks**  
[GRO-563]: https://artsyproduct.atlassian.net/browse/GRO-563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: changing navbar copy

---

src/System/Router/Boot.tsx

fix: disables terms dialog for time being

---

src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsAddDialog.tsx
src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsAddResult.tsx
src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
src/Apps/CollectorProfile/Routes/Artists/CollectorProfileArtistsRoute.tsx
src/Apps/CollectorProfile/Routes/Artists/__tests__/CollectorProfileArtistsRoute.jest.tsx
src/__generated__/CollectorProfileArtistsAddDialogCreateUserInterestsMutation.graphql.ts
src/__generated__/CollectorProfileArtistsAddDialogQuery.graphql.ts
src/__generated__/CollectorProfileArtistsAddResult_artist.graphql.ts
src/__generated__/CollectorProfileArtistsListArtistsQuery.graphql.ts

Closes [DIA-478](https://artsyproduct.atlassian.net/browse/DIA-478)
https://github.com/artsy/force/assets/112297/dac45f00-be30-4c4f-81e4-f1ecddf97f79
[DIA-478]: https://artsyproduct.atlassian.net/browse/DIA-478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(collectorprofile): implements add artist to collection

---

src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtist.tsx
src/__generated__/CollectorProfileArtistsAddDialogCreateUserInterestsMutation.graphql.ts
src/__generated__/CollectorProfileArtistsListArtistUpdateMutation.graphql.ts
src/__generated__/CollectorProfileArtistsListArtist_userInterestEdge.graphql.ts
src/__generated__/CollectorProfileArtistsListArtistsQuery.graphql.ts

Closes [DIA-479](https://artsyproduct.atlassian.net/browse/DIA-479)
https://github.com/artsy/force/assets/112297/1045a630-3716-459f-8e09-d10b2c780756
[DIA-479]: https://artsyproduct.atlassian.net/browse/DIA-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(collectorprofile): implements artist private toggle

---

docs/adding_a_segment_destination.md
src/Server/config.ts
src/Server/setup_sharify.ts
src/Typings/global.d.ts
src/Typings/sharify.d.ts

This PR supports [PHIRE-84]
Remove legacy OneTrust references.
[PHIRE-84]: https://artsyproduct.atlassian.net/browse/PHIRE-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: delete more onetrust references

---

src/Components/TermsUpdateDialog.tsx

Closes [DIA-585](https://artsyproduct.atlassian.net/browse/DIA-585)
[DIA-585]: https://artsyproduct.atlassian.net/browse/DIA-585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(terms): suppress terms dialog when within eigen

---

src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
src/Apps/CollectorProfile/Routes/Artists/__tests__/CollectorProfileArtistsRoute.jest.tsx
src/Components/Pagination/index.tsx
src/__generated__/CollectorProfileArtistsListArtistsQuery.graphql.ts

Closes [DIA-477](https://artsyproduct.atlassian.net/browse/DIA-477)
[DIA-477]: https://artsyproduct.atlassian.net/browse/DIA-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dia-477): user sees artists as paginated list on web

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx
src/__generated__/ArtworkAppTestQuery.graphql.ts
src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
src/__generated__/ArtworkSidebarCommercialButtons_artwork.graphql.ts
src/__generated__/ArtworkSidebarCommercialButtons_me.graphql.ts
src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

This PR solves [EMI-1782]
Display partner offer note in artwork listing
[EMI-1782]: https://artsyproduct.atlassian.net/browse/EMI-1782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1782): display partner offer note in artwork listing

---

src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtist.tsx
src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtistDialog.tsx
src/Apps/CollectorProfile/Routes/Artists/CollectorProfileArtistsRoute.tsx
src/__generated__/CollectorProfileArtistsAddDialogCreateUserInterestsMutation.graphql.ts
src/__generated__/CollectorProfileArtistsDeleteDialogMutation.graphql.ts
src/__generated__/CollectorProfileArtistsListArtistDialogUpdateMutation.graphql.ts
src/__generated__/CollectorProfileArtistsListArtistDialog_userInterestEdge.graphql.ts
src/__generated__/CollectorProfileArtistsListArtistsQuery.graphql.ts

Closes [DIA-589](https://artsyproduct.atlassian.net/browse/DIA-589)
There wasn't a mock up for this so I just adapted what we do in app.
https://github.com/artsy/force/assets/112297/1ae984ed-8282-44fe-b2bb-53c6aea32e65

feat(dia-589): collector profile artists mobile layout

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
src/Components/Notifications/PartnerOfferArtwork.tsx
src/__generated__/ArtworkAppTestQuery.graphql.ts
src/__generated__/ArtworkSidebarCommercialButtons_Test_Query.graphql.ts
src/__generated__/ArtworkSidebarCommercialButtons_artwork.graphql.ts
src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
src/__generated__/NotificationQuery.graphql.ts
src/__generated__/PartnerOfferArtwork_artwork.graphql.ts
src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

Use higher quality image for partner icon + add a border around it according to [designs](https://www.figma.com/file/RHkhhJJwixhFPltqhH9ZkW/v1.5-Saves-Partner-Offers?node-id=4381%3A13647&mode=dev)

fix: improve partner icon quality, border

---

src/Components/TermsUpdateDialog.tsx

Closes [DIA-598](https://artsyproduct.atlassian.net/browse/DIA-598)
[DIA-598]: https://artsyproduct.atlassian.net/browse/DIA-598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(terms): makes minor updates

---

src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtist.tsx
src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListHeader.tsx
src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsSearchResults.tsx
src/Apps/CollectorProfile/Routes/Artists/CollectorProfileArtistsRoute.tsx
src/__generated__/CollectorProfileArtistsSearchResultsQuery.graphql.ts

Closes [DIA-569](https://artsyproduct.atlassian.net/browse/DIA-569)
So this more or less works but obviously it's non ideal. When you start the search we just fetch the first 100 and filter from that, because we don't support search on this collection of items.
https://github.com/artsy/force/assets/112297/fb750200-0404-491c-a402-2d428c1f2bd3
[DIA-569]: https://artsyproduct.atlassian.net/browse/DIA-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(collector-profile): implements "search"

---

src/Apps/Components/AppShell.tsx
src/Utils/Hooks/useDarkModeToggle.ts

This adds hotkey support (cmd+i / ctrl + i) to toggle dark mode. Very helpful during development! 

feat(darkmode): Add cmd+i hotkey toggle

---

src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx

Closes [DIA-601](https://artsyproduct.atlassian.net/browse/DIA-601)
Adds a simple empty state, in line with others around the site.
[DIA-601]: https://artsyproduct.atlassian.net/browse/DIA-601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(collector-profile): adds simple empty state

---

src/Components/Notifications/__tests__/PartnerShowOpenedNotification.jest.tsx

https://github.com/artsy/force/pull/13749#discussion_r1572294252
This fixes the Partner show notification test.

chore: Fix Partner show notification test

---

src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
src/__generated__/ArtworkAppTestQuery.graphql.ts
src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

Ensures thats that we render html for the partner artist bio: 

fix(private-artworks): Ensure private artist bio is html

---

src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkAboutArtist.jest.tsx
src/__generated__/ArtworkAppTestQuery.graphql.ts
src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

Only show artsy bio, and make sure to still show rest of artist section if bio is disabled.

fix(private-artworks): Defer to artsy bio

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/MeetTheSpecialists.jest.tsx

This PR solves [ONYX-927]
Removed old specialists from the SWA flow and reordered the list
Changes requested by Sales team
[ONYX-927]: https://artsyproduct.atlassian.net/browse/ONYX-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove old secialists and reorder the list

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx

This PR solves [ONYX-936]
Remove filters from the specialists list on the /sell page
[Slack thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1714080170749499)
[ONYX-936]: https://artsyproduct.atlassian.net/browse/ONYX-936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ONYX-936): remove filters from the list of specialist on the sell page

---

src/Apps/ArtAdvisor/03-Instruction-Experiments/App.tsx
src/Apps/ArtAdvisor/ArtAdvisorApp.tsx

These frontend changes (from aea0a58689299e8d63d63d827e94dd3bc130b729 onward) were made in order to support the first review app / demo for the AI squad.
These commits are now pulled out of #13835 and into this PR, to separate the backend changes from the frontend ones.

feat: update frontend for review app/demo

---

src/Apps/SaleAgreements/Components/SaleAgreementsList.tsx

The type of this PR is: refactor
This PR updates the `SaleAgreements` app to order conditions of sale by the `sale` name.

refactor: sort conditions of sale by sale name

---

.secrets.baseline

Upgrade detect-secrets baseline to new version.

chore: bump detect-secrets baseline version

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/Apps/Consign/Routes/SubmissionFlow/Mutations/UpdateConsignSubmissionMutation.ts
src/Apps/Consign/Routes/SubmissionFlow/Utils/createOrUpdateConsignSubmission.ts
src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

The type of this PR is:  Feat
This PR solves [ONYX-906](https://artsyproduct.atlassian.net/browse/ONYX-906)
Update required fields for the `ArtworkDetailsForm` and add tracking for `width` and `height`
Optional width and height, `isSellFlowRequiredField` feature flag enabled:
https://github.com/artsy/force/assets/17580625/927362e1-4ffb-41a2-ba31-cbf8cfe063e7
Required width and height, `isSellFlowRequiredField` feature flag disabled:
https://github.com/artsy/force/assets/17580625/a8251a0f-350f-4fe5-8a83-07b4c2e2c221
[ONYX-906]: https://artsyproduct.atlassian.net/browse/ONYX-906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

feat(ONYX-906): update required fields on sell flow

---

src/Components/NavBar/menuData.ts

This PR solves [DIA-613]
This PR changes the featured artists in the navbar for May
[DIA-613]: https://artsyproduct.atlassian.net/browse/DIA-613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: change featured artists in navbar

---

src/Components/NavBar/menuData.ts

fix: fix url for duplicate artist

---

hokusai/production.yml
hokusai/staging.yml

The type of this PR is: **Revert**
Revert https://github.com/artsy/force/pull/13827 due to [problem with creating review apps](https://artsy.slack.com/archives/CP9P4KR35/p1715170793873049).

feat: revert external secret changes due to problem with review app

---

src/Apps/Home/Components/HomeFeaturedEventsRail.tsx
src/__generated__/HomeApp_Test_Query.graphql.ts
src/__generated__/HomeFeaturedEventsRail_orderedSet.graphql.ts
src/__generated__/homeRoutes_HomeQuery.graphql.ts

This was just something I noticed while testing that bugged me. I don't believe there is a ticket for it.
| --- | --- |
| <img src="https://capture.static.damonzucconi.com/Screen-Shot-2024-05-09-09-41-57.25-1T2n9ZZ6IzeT3s70GENUMOVK49d4gRwZWotnTRWjr6ZSy7lyXmIbadrfQU5BfRbcgCDyrE43atzzugHpEYmpB8jxC0tD8zthq8UG.png"> | <img src="https://capture.static.damonzucconi.com/Screen-Shot-2024-05-09-09-45-45.26-wQOMMVvJ7itsD77Ti2mdjNibsYNuXnZLFx6PP7yCkik4BHvFa2zMVx9daKnZ1AoC2CmOspgdWJa4RyIVmJrRJSgMtKalgYfR7dUn.png"> |

fix(homepage): fixes homepage featured events thumbnails

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx

Rename ~**Log in to submit an artwork for sell**~ to **Log in to submit an artwork for sale**

fix: update auth modal copy on SWA flow

---

src/Apps/Fair/Routes/FairOverview.tsx

Closes [DIA-597](https://artsyproduct.atlassian.net/browse/DIA-597)
[DIA-597]: https://artsyproduct.atlassian.net/browse/DIA-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(fair): fixes scroll to on load from trapping

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
src/Components/ArtworkGrid/ArtworkGrid.tsx
src/DevTools/MockBoot.tsx
src/DevTools/__tests__/renderUntil.jest.tsx
src/System/Router/Boot.tsx
src/Utils/Responsive/DeprecatedResponsive.tsx
src/Utils/Responsive/index.tsx

Revert "fix(DIA-648): unifies breakpoints across Force"

---

src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
src/Apps/Consign/consignRoutes.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtworkAboutTab.tsx

This PR is related to [ONYX-902](https://artsyproduct.atlassian.net/browse/ONYX-902)
Removes `contact-information` from routes, updates redirection to submission flow and `artwork-details`
Desktop:
https://github.com/artsy/force/assets/17580625/51e9c534-351c-407b-a9b7-58390502b51a
Mobile:
https://github.com/artsy/force/assets/17580625/555baf24-1a1c-4fa1-992a-df7f89d687c3
Desktop Thank You redirection:
https://github.com/artsy/force/assets/17580625/e98b4350-700e-46c5-9a77-dd1a28b30568
[ONYX-902]: https://artsyproduct.atlassian.net/browse/ONYX-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …

fix(ONYX-902): update routes for submission flow

---

.eslintrc.js
package.json
yarn.lock

chore: enables lint rule for nested components

---

src/Apps/Artwork/Components/ArtworkPageBanner.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
src/Components/Notifications/PartnerOfferArtwork.tsx
src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx

Small cleanup here. Will remove the flag once this goes out.

chore: remove references to emerald_partner-offers-to-artwork-page feature flag as it's fully released now

---

src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
src/Apps/Artwork/Components/ArtworkSidebar/PrivateArtworkAdditionalInfo.tsx

Demonstrates how to refactor things to share code. Click through each commit to see the process.

refactor(private-artworks): Share additional info code

---

src/Apps/Preferences/__tests__/PreferencesApp.jest.tsx
src/__generated__/PreferencesAppTestQuery.graphql.ts

This PR solves [EMI-1691]
This PR refactors and updates the tests for the Preference App
[EMI-1691]: https://artsyproduct.atlassian.net/browse/EMI-1691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-1691): Refactor Preference App tests

---

src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Components/DevDebug.tsx
src/Apps/Sell/Components/SubmissionHeader.tsx
src/Apps/Sell/Components/SubmissionLayout.tsx
src/Apps/Sell/Routes/NewRoute.tsx
src/Apps/Sell/SellFlowContext.tsx
src/__generated__/PreferencesAppTestQuery.graphql.ts

This PR includes a few small design updates and refactorings for the new Sell flow:
* Disable dev mode by default (can be enabled by setting `devMode` to `true` in the submission context)
* Update layout to match the design
* Small changes to the artist screen and navigation
The design is still WIP, but these changes should move everything in the right direction and make it easier to work on the different steps independently :)

feat: Some small design updates for the new Submission flow

---

src/System/Router/PageLoadingBar.tsx
src/System/Router/RenderStatus.tsx

With SSR, we need to be sure to not show the loader on mount.

fix(nav-loader): tiny tweaks

---

src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
src/Components/Inquiry/Views/InquiryInquiry.tsx

This PR solves [DIA-402]
This PR updates the text copy as specified in the ticket.
Before: 
After: 
[DIA-402]: https://artsyproduct.atlassian.net/browse/DIA-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update text for the inquiry flow

---

src/Components/Inquiry/Views/InquiryInquiry.tsx

This PR solves [DIA-725]
[DIA-725]: https://artsyproduct.atlassian.net/browse/DIA-725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add missing info icon to inquiry modal copy

---

package.json
src/Components/NavBar/Menus/NavBarSubMenu.tsx
src/Components/NavBar/NavBar.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
src/Components/NavBar/menuData.ts
yarn.lock

Closes [DIA-651](https://artsyproduct.atlassian.net/browse/DIA-651) + [DIA-720](https://artsyproduct.atlassian.net/browse/DIA-720)
[DIA-651]: https://artsyproduct.atlassian.net/browse/DIA-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DIA-720]: https://artsyproduct.atlassian.net/browse/DIA-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(nav): updates menus

---

src/Components/Inquiry/Views/InquiryInquiry.tsx

fix: update the settings link color

---

src/Apps/Sell/Routes/TitleRoute.tsx
src/Apps/Sell/Routes/__tests__/TitleRoute.jest.tsx
src/Components/EntityHeaders/EntityHeaderArtist.tsx
src/__generated__/TitleRoute_Test_Query.graphql.ts
src/__generated__/TitleRoute_submission.graphql.ts
src/__generated__/sellRoutes_TitleRouteQuery.graphql.ts

This PR solves [ONYX-1015](https://artsyproduct.atlassian.net/browse/ONYX-1015)
Add Artwork Title step in new submission flow.
https://github.com/artsy/force/assets/17580625/8e58a7f9-3c93-4687-83cf-e4d668fc14c2
[ONYX-1015]: https://artsyproduct.atlassian.net/browse/ONYX-1015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-1015): add Artwork Title step

---

src/Apps/Partner/Components/PartnerHeader/index.tsx

Closes [DIA-678](https://artsyproduct.atlassian.net/browse/DIA-678)
[DIA-678]: https://artsyproduct.atlassian.net/browse/DIA-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(partner): corrects follow button alignment

---

src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Routes/ArtistRoute.tsx
src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
src/Apps/Sell/SellFlowContext.tsx

This PR solves [ONYX-1072]
This improves the new Sell flow bottom navigation:
-  Saving the submission when clicking on "Back."
-  Better error handling.
-  Prevent form from navigating to the previous or next step when updating the submission fails.
[ONYX-1072]: https://artsyproduct.atlassian.net/browse/ONYX-1072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Improve new Sell flow bottom navigation

---

src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Routes/ArtistRoute.tsx
src/Apps/Sell/SellFlowContext.tsx

Resolves [Slack Thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1718379105202439)
This replaces `console.error` with `logger` everywhere in the new Sell flow.

chore: Use logger everywhere in the new Sell flow

---

src/System/Components/PageLoadingBar.tsx

I am so neurotic about this loading bar! This fades things in slightly faster.

chore(loading-bar): Less fade

---

src/Apps/Auction/Components/AuctionDetails/AuctionInfoSidebar.tsx

This PR solves [PROJECT-718]
This PR adds a new element to the auction sidebar and spaces the boxes more:

chore(DIA-718): add elements to auction sidebar 

---

src/Components/CompleteProfile/CompleteProfileInformationDialog.tsx
src/__generated__/CompleteProfileInformationDialogQuery.graphql.ts

Closes [DIA-714](https://artsyproduct.atlassian.net/browse/DIA-714)
First we build the two dialogs. Then we integrate them into the various flows. Here's the first dialog.
[DIA-714]: https://artsyproduct.atlassian.net/browse/DIA-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(completeprofile): adds profile information dialog

---

src/Apps/Sell/Components/SubmissionLayout.tsx
src/Apps/Sell/Routes/IntroRoute.tsx
src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx

This PR solves [ONYX-1013](https://artsyproduct.atlassian.net/browse/ONYX-1013)
This adds the intro page for the new sell flow.
| | |
| --- | --- |
|![Screenshot 2024-06-20 at 14 51 44](https://github.com/artsy/force/assets/4691889/de418b6e-9de2-4384-b893-01343478d623) | ![Screenshot 2024-06-20 at 14 51 51](https://github.com/artsy/force/assets/4691889/1005e8cb-6109-40f3-bd56-e304b46f58cd)|
[ONYX-1013]: https://artsyproduct.atlassian.net/browse/ONYX-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-1013): add start submission page

---

src/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethods.tsx
src/Apps/Settings/Routes/__tests__/SettingsPaymentsRoute.jest.tsx

Makes ability to manage payment methods more strict based on [discussion here](https://artsy.slack.com/archives/CA8SANW3W/p1718713045925899).
https://artsyproduct.atlassian.net/browse/PHIRE-1013

feat: offer card registration only to those with saved payment methods (PHIRE-1013)

---

src/Apps/Sell/Components/SubmissionStepTitle.tsx
src/Apps/Sell/Routes/ArtistNotEligibleRoute.tsx
src/Apps/Sell/Routes/ArtistRoute.tsx
src/Apps/Sell/Routes/DetailsRoute.tsx
src/Apps/Sell/Routes/DimensionsRoute.tsx
src/Apps/Sell/Routes/PhotosRoute.tsx
src/Apps/Sell/Routes/PurchaseHistoryRoute.tsx
src/Apps/Sell/Routes/TitleRoute.tsx

Adjust title sizes on the submission screens

fix: adjust title sizes on the submission screens

---

src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
src/Components/Inquiry/Views/InquiryInquiry.tsx

Now that we launched, we can remove the usage here in Force.

feat: retire diamond_collector-summary Unleash flag

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/Components/Alert/Components/Steps/Details.tsx
src/Components/Alert/Components/Steps/Filters.tsx
src/Components/FadeInBox.tsx

Add FadeInBox to standardize fade in animation for `isMounted` on Force
https://github.com/artsy/force/assets/17580625/3a721638-0fe4-47cf-be53-3119fa90ff7c

feat(fadeinbox): animation standardization fadein isMounted

---

src/Apps/Sell/Components/SubmissionHeader.tsx
src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx

This PR solves [ONYX-1077](https://artsyproduct.atlassian.net/browse/ONYX-1077)
Refactor original navigation and add navigation changes for mobile web.
mWeb:
https://github.com/artsy/force/assets/17580625/c91bd23b-4835-4819-8563-ac266032a0e4
Web:
https://github.com/artsy/force/assets/17580625/b2899d93-a0c1-4b0b-9823-ab9a89bcbd71
[ONYX-1077]: https://artsyproduct.atlassian.net/browse/ONYX-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-1077): add mWeb navigation

---

src/Components/Inquiry/Views/InquiryInquiry.tsx

chore: remove extra paranthesis in inquiry modal copy

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx

This PR solves https://github.com/artsy/force/pull/13998#discussion_r1651089688
Do not set SOURCE when submitting an artwork from My Collection

chore: Do not set SOURCE when submitting an artwork from My Collection

---

src/Apps/Sell/Components/SubmissionLayout.tsx
src/Apps/Sell/Routes/IntroRoute.tsx

This PR solves [ONYX-1013](https://artsyproduct.atlassian.net/browse/ONYX-1013)
Update and crop images, refactor spacing and update for mWeb.
[ONYX-1013]: https://artsyproduct.atlassian.net/browse/ONYX-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-1013): update images and styling

---

hokusai/production.yml
hokusai/staging.yml

Revert https://github.com/artsy/force/pull/13942 due to [broken review app creation](https://app.circleci.com/pipelines/github/artsy/force/61832/workflows/7f442926-ac41-48ab-a763-7e5d8bf98697).

fix: vault integration breaks review app

---

src/Apps/Sell/Hooks/useFocusInput.ts
src/Apps/Sell/Routes/ArtistRoute.tsx
src/Apps/Sell/Routes/DetailsRoute.tsx
src/Apps/Sell/Routes/DimensionsRoute.tsx
src/Apps/Sell/Routes/PurchaseHistoryRoute.tsx
src/Apps/Sell/Routes/TitleRoute.tsx

Focus on the first input when entering new Sell flow steps whenever the first field is an `Input` component.

feat: Focus first input when entering new Sell flow steps

---

src/Apps/Sell/Components/SubmissionLayout.tsx

* Context: https://github.com/artsy/force/pull/14077#discussion_r1652642379
This reverts a Submission layout update that causes issues on the Title step.

fix: Revert Submission layout update

---

src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Form.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/types.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts

This PR:
- Requires a user to be logged in to use the curated discovery app. 
- creates a `weaviate` from the `gravity` user, if one doesn't already exist
- Adds backend support for user related actions
https://github.com/artsy/force/assets/38149304/7dd6ed82-be82-4e7b-a946-ed68f1a72581

feat: get or create weaviate user for curated discovery

---

src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/StatePreview.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts

Builds on https://github.com/artsy/force/pull/14053 to add price filtering ability to the artworks semantic search:
https://github.com/artsy/force/assets/140521/b493a222-a5be-4b1f-b308-ce52e6b53984

feat: add price filtering to 07 artworks rail

---

src/Apps/Sell/Components/ArtistNotEligibleText.tsx
src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Components/SubmissionHeader.tsx
src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
src/Apps/Sell/Hooks/useSubmissionTracking.ts
src/Apps/Sell/Hooks/useSubmitArtworkTracking.ts
src/Apps/Sell/Routes/ArtistRoute.tsx
src/Apps/Sell/Routes/IntroRoute.tsx
src/Apps/Sell/Routes/NewFromMyCollectionRoute.tsx
src/Apps/Sell/Routes/ThankYouRoute.tsx
src/Apps/Sell/Routes/__tests__/ArtistNotEligibleRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx
src/Apps/Sell/SellFlowContext.tsx
src/__generated__/ThankYouRoute_Test_Query.graphql.ts
src/__generated__/ThankYouRoute_submission.graphql.ts

Addresses [ONYX-1022]
This PR adds tracking for the new Sell flow.
**Events:**
```
action: "tappedNewSubmission",
context_module: "sell",
context_owner_type: "submitArtworkStepStart",
action: "tappedSubmissionBack",
context_module: "sell",
context_owner_type: null,
submission_id: "123",
submission_step: "title",
action: "tappedSubmissionSaveExit",
context_module: "sell",
context_owner_type: null,
submission_id: "123",
submission_step: "title",
action: "consignmentSubmitted",
context_module: "sell",
context_owner_type: "submitArtworkStepCompleteYourSubmission",
fieldsProvided: [],
submission_id: '<mock-value-for-field-"externalId">',
action: "tappedSubmitAnotherWork",
context_module: "sell",
context_owner_type: "submitArtworkStepCompleteYourSubmission",
submission_id: …
```

chore: New sell flow tracking

---

src/Apps/Sell/Components/ArtistNotEligibleText.tsx

Open Sell flow advisor and faq links in new tab.

fix: Open Sell flow advisor and faq links in new tab

---

src/Apps/ArtAdvisor/ArtAdvisorApp.tsx

Small PR updating the curated discovery app description with authenticated user requirement. (This is mainly to get a new commit in and trigger a deploy process when `ai-squad` is merged into `review-app-ai-squad`).

chore: update curated discovery description with user requirement

---

hokusai/production.yml
hokusai/staging.yml

Per [this comment](https://artsy.slack.com/archives/C06SSV1K10D/p1719518446758289?thread_ts=1719497520.526979&cid=C06SSV1K10D), cherry-picks the Vault fix to try and un-bork the `review-app-ai-squad` deployment
cc @mc-jones

fix: ai-squad review app

---

src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx

This PR solves [EMI-1936]
**Before**
**After**
[EMI-1936]: https://artsyproduct.atlassian.net/browse/EMI-1936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-1936): remove extra space in the shipping form

---

src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/types.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts

New PR doing the same as #14097, just to the correct base branch: `ai-squad`.

Mc jones/feat rank artworks

---

src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Budget.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Form.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Goals.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Interests.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArticlesRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Links.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/StatePreview.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts

Grab-bag of UX fixes for the 07 demo, including:
- un-blah-ing the page title
- following the results mockup more closely
- improving the budget field behavior, and make it optional
- preventing incomplete form submissions which lead to errors or empty rails

fix: various UX tweaks for 07 demo

---

package.json
yarn.lock

Add `dedent` as a top level dependency in `ai-squad` branch.

chore: add dedent

---

src/Apps/ArtAdvisor/07-Curated-Discovery/App.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Form.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Interests.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArticlesRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/llm/extractInterestsIntent.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts

Adds LLM-parsed free text for collecting interests into the mix:
https://github.com/artsy/force/assets/140521/1588fd44-5389-4eed-b2f0-c2b5d2d3bab1

feat: parse interests free text into concepts array

---

src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Form.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Article.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArticlesRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Header.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollection.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/types.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts

A few pure refactors to deal with some inconsistencies and unwieldy code that had crept in recently — components and methods that want to be extracted as well as some type consolidation.

refactor: 07 components and types

---

src/Apps/ArtAdvisor/07-Curated-Discovery/App.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Form.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Interests.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Article.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArticlesRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Header.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollection.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/llm/extractInterestsIntent.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/types.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts

With free text interests and some pure refactors

chore(ai): deploy review app

---

src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Article.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArticlesRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollection.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/types.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts

The type of this PR is: **Style**
A few opinionated style tweaks to get this looking closer to our design patterns.
- A fuller artwork tombstone, styled conventionally
- Like/dislike buttons positioned conventionally
- Conventionally styled RouterLinks throughout
- Skeletons adjusted to minimize layout shifts

feat: minor styling changes to 07 

---

src/Apps/Sell/Routes/PhoneNumberRoute.tsx
src/Apps/Sell/Routes/ThankYouRoute.tsx

https://www.notion.so/artsy/Sub-copy-below-title-should-be-16px-bed396eae99a435e9a3bdf1b8307e2a6?pvs=4
Adjust Sell flow thank you step font size.

fix: Adjust Sell flow thank you step font size

---

src/Apps/Consign/Routes/MarketingLanding/Components/SellMeta.tsx
src/Apps/Sell/Routes/IntroRoute.tsx
src/Apps/Sell/Routes/NewRoute.tsx
src/Apps/Sell/Routes/SubmissionRoute.tsx
src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/NewRoute.jest.tsx

Addresses [ONYX-1078]
New Sell flow meta tags.
[ONYX-1078]: https://artsyproduct.atlassian.net/browse/ONYX-1078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: New Sell flow meta tags

---

src/Apps/Sell/Components/SubmissionLayout.tsx
src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
src/Apps/Sell/Routes/ArtistRoute.tsx
src/Apps/Sell/Routes/DimensionsRoute.tsx
src/Apps/Sell/Routes/PhotosRoute.tsx
src/Apps/Sell/Routes/__tests__/PhotosRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/TitleRoute.jest.tsx
src/Apps/Sell/SellFlowContext.tsx

New Sell flow design adjustments and fixes.

fix: New Sell flow design adjustments and fixes

---

src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx

This PR solves [ONYX-1037]
Show the first alert's details only when the screen size is greater than sm
https://github.com/artsy/force/assets/36167539/3b27dcb2-557c-4390-a5f9-d19e48ae4183
[ONYX-1037]: https://artsyproduct.atlassian.net/browse/ONYX-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-1037): change isMobile efinition

---

src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Article.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollection.tsx

chore: deploy ai review app

---

src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
src/Apps/Sell/Routes/__tests__/PhotosRoute.jest.tsx
src/Components/PhotoUpload/Utils/fileUtils.ts

Add HEIC to Sell flow error message and update "Add photos" button copy.

fix: Update Sell flow photo step copy

---

src/Apps/Sell/Routes/PhotosRoute.tsx

Adjust Tips for taking photos font size.

fix: Adjust Tips for taking photos font size

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx

Point all Start Selling buttons to new Sell flow.

fix: Point all Start Selling buttons to new Sell flow

---

src/Apps/Sell/Components/SubmissionProgressBar.tsx

fix: align check icon

---

src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Components/SubmissionLayout.tsx

The type of this PR is: **Chore*
Ddd border to bottom form navigation

chore: add border to bottom form navigation

---

src/Apps/Sell/Components/BottomFormNavigation.tsx

Adjust Sell flow bottom navigation.

fix: Adjust Sell flow bottom navigation

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviousSubmission.tsx
src/Apps/Sell/Components/SubmissionHeader.tsx
src/__generated__/PreviousSubmissionQuery.graphql.ts

Finish previous submission adjustments.

fix: Finish previous submission adjustments

---

src/Apps/Sell/Utils/previousSubmissionUtils.ts

This PR solves https://github.com/artsy/force/pull/14108#discussion_r1663996003
This PR adds Yup validation to validate "previous submission" localStorage data.

fix: Add Yup validation to Previous submission localStorage data

---

src/Apps/Sell/SellFlowContext.tsx

Guard Sell flow step navigation.

fix: Guard Sell flow step navigation

---

src/Components/NavBar/menuData.ts

This PR solves [DIA-747]
Changing the artists in the nav bar:
[DIA-747]: https://artsyproduct.atlassian.net/browse/DIA-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(DIA-747): updates artists in navbar

---

src/Apps/Sell/Components/ImagePreviewItem.tsx

Sell flow image preview onError logic.

fix: Sell flow image preview onError logic

---

src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.jest.tsx
src/System/i18n/locales/en-US/translation.json

Context https://artsy.slack.com/archives/C03N12SR0RK/p1720634176078359?thread_ts=1710279395.397359&cid=C03N12SR0RK
Updates copy of:
`"Be covered by the Artsy Guarantee when you checkout with Artsy"`
to be 
`"Be covered by the Artsy Guarantee when you check out with Artsy"`
|Before|After|
|---|---|
|![b4](https://github.com/artsy/force/assets/21178754/fb7d7257-137f-416a-8daf-6204bb75914c)|![aft](https://github.com/artsy/force/assets/21178754/86227b1e-d5ed-41b9-84f6-b205eca69868)|

chore(copy): update checkout - to check out

---

src/Apps/ArtAdvisor/08-Art-Quiz/server.ts
src/Apps/ArtAdvisor/08-Art-Quiz/types.ts
src/Apps/ArtAdvisor/08-Art-Quiz/weaviate-db.ts
src/Apps/ArtAdvisor/ArtAdvisorServerRoutes.ts
src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
src/Apps/ArtQuiz/__tests__/ArtQuizArtworks.jest.tsx
src/__generated__/ArtQuizArtworks_Test_Query.graphql.ts
src/__generated__/ArtQuizArtworks_me.graphql.ts
src/__generated__/artQuizRoutes_ArtworksQuery.graphql.ts

This PR adds a `08-Art-Quiz` experiment to the `ArtAdvisor` app for a quick poc to provide real-time recommendations for the onboarding art quiz.

feat: real-time art quiz recs

---

src/Apps/Sell/Mutations/useUpdateMyCollectionArtwork.tsx
src/Apps/Sell/Routes/AdditionalRoutes/FrameRoute.tsx
src/Apps/Sell/Routes/__tests__/FrameRoute.jest.tsx
src/Apps/Sell/SellFlowContext.tsx
src/__generated__/FrameRoute_Test_Query.graphql.ts
src/__generated__/FrameRoute_submission.graphql.ts
src/__generated__/sellRoutes_FrameRouteQuery.graphql.ts
src/__generated__/useUpdateMyCollectionArtworkMutation.graphql.ts

This PR solves [ONYX-1112]
Adds Frame step:
[ONYX-1112]: https://artsyproduct.atlassian.net/browse/ONYX-1112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-1112): sell frame step

---

src/Apps/Sell/Routes/ThankYouRoute.tsx
src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx

This PR solves [ONYX-1128]
Update Thank You step according to the design
| Any other state | Submitted state |
| --- | --- |
| <img width="1102" alt="image" src="https://github.com/user-attachments/assets/aaca43a5-3e26-4bfc-975e-b00cb3347175"> | <img width="1104" alt="image" src="https://github.com/user-attachments/assets/ae966545-28cd-4b61-996b-cb6bf35866d9"> |
[ONYX-1128]: https://artsyproduct.atlassian.net/browse/ONYX-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ONYX-1128): update thank you step

---

src/System/Components/PageLoadingBar.tsx

Follow up from PR review which removes an unnecessary prop.

fix(loading-bar): remove unnecessary prop

---

src/__generated__/sellRoutes_ThankYouRouteQuery.graphql.ts

Somehow this was excluded from #14187.

chore: update relay generated files

---

src/Components/__stories__/AppDownloadBanner.story.tsx

Fixes the build by removing the dev dep in this story.

fix: removes import

---

src/Apps/Home/Components/HomeCurrentFairs.tsx
src/__generated__/HomeCurrentFairsQuery.graphql.ts
src/__generated__/HomeCurrentFairs_Test_Query.graphql.ts
src/__generated__/HomeCurrentFairs_viewer.graphql.ts

For whatever reason this would sometimes prefer the smallest version. This specifies the correct order of versions.

fix(homepage): prefers larger version for rails

---

src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
src/Apps/Sell/Components/DocumentPreviewItem.tsx
src/Apps/Sell/Components/DocumentPreviewsGrid.tsx
src/Apps/Sell/Components/ImagePreviewItem.tsx
src/Apps/Sell/Components/SubmissionLayout.tsx
src/Apps/Sell/Components/UploadDocumentsForm.tsx
src/Apps/Sell/Components/UploadPhotosForm.tsx
src/Apps/Sell/Routes/AdditionalRoutes/AdditionalDocumentsRoute.tsx
src/Apps/Sell/Routes/PhotosRoute.tsx
src/Apps/Sell/Routes/__tests__/AdditionalDocumentsRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/PhotosRoute.jest.tsx
src/Apps/Sell/Utils/uploadUtils.ts
src/Components/FileUpload/FileDropzone.tsx
src/Components/FileUpload/types.ts
src/Components/FileUpload/utils/concatDropzoneErrors.ts
src/Components/FileUpload/utils/getErrorMessage.ts
src/Components/FileUpload/utils/validateTotalMaxSize.ts
src/Components/PhotoUpload/Components/PhotoDropzone.tsx
src/Components/PhotoUpload/Utils/fileUtils.ts
src/__generated__/AdditionalDocumentsRoute_Test_Query.graphql.ts
src/__generated__/AdditionalDocumentsRoute_submission.graphql.ts
src/__generated__/sellRoutes_AdditionalDocumentsRouteQuery.graphql.ts

This PR solves [ONYX-1113]
Made some assumptions how thumbnails should look like and behave, once it's on staging I'll ask Barney what needs to be changed.
[ONYX-1113]: https://artsyproduct.atlassian.net/browse/ONYX-1113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-1113): sell flow - additional documents step

---

package.json
src/Components/AppDownloadBanner.tsx
src/Components/AppDownloadFooter.tsx
yarn.lock

This PR solves [DIA-730]
Adds tracking for app upsell.
[DIA-730]: https://artsyproduct.atlassian.net/browse/DIA-730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add tracking for app upsell

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx

This fixes the My Collection submission status header spacing on mWeb.

fix: My Collection submission status header spacing on mWeb

---

src/Apps/Sell/Components/SubmissionHeader.tsx

Resolves https://www.notion.so/artsy/When-submitting-a-MyC-artwork-should-Save-Exit-navigate-back-to-the-artwork-Currently-it-opens--ebdf272100c94666ba75b1c943097327?pvs=4
Link to My Collection artwork page when exiting Sell flow.

fix: Link to My Collection artwork page when exiting Sell flow

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx

Add missing My Collection submission status tracking.

fix: Add missing My Collection submission status tracking

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
src/Apps/Sell/Routes/AdditionalRoutes/ShippingLocationRoute.tsx

Do not display Input error messages in the Sell flow.

fix: Do not display Input error messages in the Sell flow

---

src/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetails.tsx
src/Apps/Partner/Components/PartnerArtists/PartnerArtistDetailsList/PartnerArtistDetailsList.tsx
src/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtists.tsx
src/__generated__/PartnerArtistDetailsListRendererQuery.graphql.ts
src/__generated__/PartnerArtistDetailsList_partner.graphql.ts

Addresses issue noticed [in slack](https://artsy.slack.com/archives/C03N12SR0RK/p1723140546223969?thread_ts=1723127436.495189&cid=C03N12SR0RK). 
Increases the refetch on infinite scroll to 10. 
https://github.com/user-attachments/assets/bdce2875-73a3-45b6-9d59-4a620dec7dd4

chore(partner-artists): Increase fetch to 10 on scroll

---

src/Server/middleware/__tests__/graphqlProxyMiddleware.jest.ts
src/Server/middleware/graphqlProxyMiddleware.ts

Staging smoke tests caught a gap in some coverage, thanks to some bad staging data. 
Queries to `pablo-picasso` / `artist/id` were intermittently failing from Metaphysics (see offending query below), and per the GraphQL spec returning an `errors` object. Since the response was successful, it was cached.
While the general spec guidance is that graphql requests should always 200, and upon seeing `errors` in the response client UI should handle said errors gracefully, we still shouldn't cache so as to give upstream a chance to resolve the errors at some future point. Then future requests from clients have the opportunity to cache correctly. 
@joeyAghion - going to merge this to get it to staging, since the artist/id query is currently unstable, and dont want …

chore(cache): Make saves and lookups safer

---

src/Apps/Show/Components/ShowContextCard.tsx

A [#product-bugs-and-feedback issue ](https://artsy.slack.com/archives/C03N12SR0RK/p1723214440888709) yielded an unrelated issue where where past closed shows that are disassociated with a partner were erroring out due to missing partner. This fixes that

fix: broken partner shows

---

src/Components/NavBar/menuData.ts

This PR solves [DIA-779]
This PR updates the monthly artists in the nav bar per this [document](https://docs.google.com/document/d/1YymWqOBN6_-Gn1-3FXmvDf-9lmNYS6E26FtxB5mO3MI/edit).
[DIA-779]: https://artsyproduct.atlassian.net/browse/DIA-779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(DIA-779): monthly artists name update in navbar

---

src/Apps/Sell/Hooks/useSubmissionTracking.ts

Simplify submission tracking getOwnerType function

chore: Simplify submission tracking getOwnerType function

---

yarn.lock

Bumps `@babel/traverse` to version > `7.25`

chore: bump @babel/traverse

---

src/Server/middleware/__tests__/bootstrapSharifyAndContextLocalsMiddleware.jest.ts
src/Server/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts

Closes [DIA-792](https://artsyproduct.atlassian.net/browse/DIA-792)
Using this we should be able to determine the actual impact of 3rd parties on web vitals.
[DIA-792]: https://artsyproduct.atlassian.net/browse/DIA-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: allows for disabling 3rd party code via query string

---

src/Apps/Sell/Components/BottomFormNavigation.tsx

Resolves [Slack Thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1724145714222689?thread_ts=1723734957.955569&cid=C05EQL4R5N0)
Decrease Sell flow bottom navigation transparency.

feat: Decrease Sell flow bottom navigation transparency

---

src/Components/Notifications/Notifications.tsx

This PR solves [ONYX-1223]
Did this ever work? It seems like it couldn't, if the context wasn't wrapped. In any case, wraps the notifications menu with the provider which fixes everything:
https://github.com/user-attachments/assets/d7821b69-b349-4dca-bd5a-6e766e46e3fd
[ONYX-1223]: https://artsyproduct.atlassian.net/browse/ONYX-1223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(notifications): Fix notifications menu pills

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HowItWorksSteps.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HowItWorksSteps.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SWAFooter.jest.tsx
src/Apps/Consign/Routes/MarketingLanding/Utils/marketingLandingTracking.ts
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSubmitForSale.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSubmitForSale.jest.tsx

Resolves [ONYX-1074](https://artsyproduct.atlassian.net/browse/ONYX-1074)
This removes code related to the old Sell flow and the feature flag `onyx_new_submission_flow`.
[ONYX-1074]: https://artsyproduct.atlassian.net/browse/ONYX-1074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Remove old Sell flow (part 1)

---

src/Apps/Sell/SellFlowContext.tsx

Follow-up fix for https://github.com/artsy/force/pull/14396
This PR uppercases the test submission state to match the submission state format.

fix: Uppercase test submission state

---

src/Apps/Partner/Components/Overview/AboutPartner.tsx
src/Apps/Partner/Components/__tests__/Overview/AboutPartner.jest.tsx
src/__generated__/AboutPartner_Test_Query.graphql.ts
src/__generated__/AboutPartner_partner.graphql.ts
src/__generated__/partnerRoutes_OverviewQuery.graphql.ts

Address https://artsyproduct.atlassian.net/browse/EMI-2034
With my hour long light availability that is about the size of PR I can manage here :(

chore: remove VAT number from Partner info display

---

src/Apps/ArtAdvisor/ArtAdvisorApp.tsx

Trivial change to trigger the review-app ci flow.

chore: trivial change to trigger review app deploy

---

src/System/Relay/middleware/cacheHeaderMiddleware.ts

Untested! But saw the conversation in Slack.

feat: propagate client-side-cached-but-not-server custom 0 TTL to CDN

---

src/Apps/Sell/SellFlowContext.tsx

Jira: [ONYX-1132](https://artsyproduct.atlassian.net/browse/ONYX-1132) 🔒

fix: add missing source/userAgent attributes for non-MyC submissions

---

src/Apps/Artwork/Components/ArtworkDetails/ConditionInfoModal.tsx
src/Apps/Sell/Routes/AdditionalRoutes/ConditionRoute.tsx
src/Apps/Sell/Utils/conditionOptions.tsx

- Rephrase step description. Prefer "work" to "piece"
- Order condition option from Excellent > Fair
- Simplify and avoid duplication in modal copy

feat: some minor copy edits to the SWA Condition step

---

src/Apps/Collect/Routes/Collect/index.tsx
src/Apps/Collect/Routes/Collections/index.tsx

This PR solves [DIA-839]
Noticed that the /collect meta tag image was broken, and noticed we weren't using our latest patterns. This should fix things.
[DIA-839]: https://artsyproduct.atlassian.net/browse/DIA-839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(collect): Fix collect metatags

---

src/Components/AuthDialog/Hooks/useAuthDialogTracking.ts

Just memoizes the tracking functions, the `track` was causing a diff in the effect. The way we're doing impression tracking here isn't amazing, but this works for now.

fix(auth): fixes double firing of impression

---

src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetails.tsx
src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
src/Apps/Order/Routes/Shipping2/Components/__tests__/FulfillmentDetailsForm.jest.tsx
src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
src/Apps/Order/Routes/Shipping2/index.tsx
src/DevTools/setupTestWrapper.tsx

This PR solves [EMI-1527]
This PR adds tests and missing tracking behavior to match what we have in the legacy shipping route. No user-facing behavior changes.
[EMI-1527]: https://artsyproduct.atlassian.net/browse/EMI-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-1527): Add tests and confirm tracking behavior

---

src/Apps/serverCacheTTLs.tsx
src/System/Relay/middleware/__tests__/cacheHeaderMiddleware.jest.ts
src/System/Relay/middleware/cacheHeaderMiddleware.ts

This updates our relayCacheHeaderMiddleware with the ability to add custom expiration times.

feat(cache): Add route-level cache TTL config

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarLinks.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarLinks.jest.tsx
src/Apps/Auction/Components/Form/ConditionsOfSaleCheckbox.tsx
src/Apps/Auction/Components/Form/IdentityVerificationWarning.tsx
src/Apps/Auction/Components/Form/__tests__/ConditionsOfSaleCheckbox.jest.tsx
src/Apps/Auction/Components/Form/__tests__/IdentityVerificationWarning.jest.tsx
src/Apps/Auction/Routes/AuctionConfirmRegistrationRoute.tsx
src/Apps/Auction/Routes/__tests__/AuctionConfirmRegistrationRoute.jest.tsx
src/Apps/Order/Components/ConditionsOfSaleDisclaimer.tsx
src/Apps/Order/Routes/__tests__/Accept.jest.tsx
src/Apps/Order/Routes/__tests__/Counter.jest.tsx
src/Apps/Order/Routes/__tests__/Reject.jest.tsx
src/Apps/Order/Routes/__tests__/Review.jest.tsx
src/Components/Footer/Footer.tsx
src/Components/Footer/__tests__/Footer.jest.tsx
src/Components/Inquiry/Views/InquirySignUp.tsx
src/Components/Inquiry/__tests__/Views/InquirySignUp.jest.tsx

Closes [DIA-816](https://artsyproduct.atlassian.net/browse/DIA-816)
Lot of code for this simple flag — surprised we weren't able just to make this change?
[DIA-816]: https://artsyproduct.atlassian.net/browse/DIA-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: removes the diamond new terms and conditions flag

---

src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
src/__generated__/RelatedCollectionsRailQuery.graphql.ts

The linked collections field appears to be busted. Just going to remove, as showing related collections at the very bottom of the screen -- if there are related collections -- seems harmless enough.

fix(collection/id): fix weird schema error

---

src/System/Components/RouterLink.tsx

- Gated behind `diamond_prefetch-on-enter` FF
This adds support for prefetching links on viewport enter. Right now this only applies to links wrapped in RouterLink. 
**Conditions**:
- `diamond_prefetch-on-enter` flag is enabled
- Link is in viewport 
- User is **not logged in** (part of the aim is to generate more cache hit coverage) 
**Behavior**: 
- Once intersection observer executes, its detached, and we don't attempt to prefetch again (via `once` prop on hook)
As discussed below, with logged in users + lazy-loaded artwork grids, things don't feel quite right. Pages transition instantly, yet there's still always this glaring fetch of the grid on key pages. 
For logged out, there's enough cache entries (and soon to be more) to where this doesn't matter as much, but when logged in, …

feat(performance): Add experimental support for "prefetch on viewport enter" 

---

src/Components/Notifications/NotificationItem.tsx
src/Components/Notifications/__tests__/NotificationItem.jest.tsx
src/__generated__/NotificationItem_notification.graphql.ts
src/__generated__/NotificationItem_test_Query.graphql.ts
src/__generated__/NotificationsListNextQuery.graphql.ts
src/__generated__/NotificationsListQuery.graphql.ts
src/__generated__/NotificationsList_test_Query.graphql.ts

Should respect image ratio better than relying on the default image URL.
**Current: Left, Proposed: Right**

feat: request resized preview images for activity panel notification item

---

yarn.lock

Not expecting much in the way of changes since it looks like this was actually updated 2 months ago. Though the way this was resolving in the lockfile was a little weird? Anyway we were getting a warning on boot to update this, so.

chore: updates browserlist

---

.circleci/config.yml
Dockerfile

Ensure we're pushing the staging image first.

fix(ci): Push staging image before deploy

---

.circleci/config.yml

Deploys to staging working. Does some last cleanup before I fix smoke tests and review apps

ci(circle): cleanup main config

---

src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetails.tsx

This PR solves [EMI-2110] where a user in the refactored shipping route would have to click [save & continue] 2 times to procede.
[EMI-2110]: https://artsyproduct.atlassian.net/browse/EMI-2110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2110): click 1x to proceed with pickup

---

.circleci/config.yml

Last part of the CI refactor. Bring back review app creation support.

ci(config): re-add review app

---

src/System/Hooks/__tests__/usePrefetchRoute.jest.tsx
src/System/Relay/isRequestCacheable.ts
src/System/Relay/middleware/__tests__/cacheHeaderMiddleware.jest.ts
src/System/Relay/middleware/cacheHeaderMiddleware.ts

Adds a couple tests for the new metadata cache TTL functionality added here: https://github.com/artsy/force/pull/14567

chore(cache): Add a few tests

---

src/Components/Notifications/NotificationItem.tsx

Follow-up to address [this comment][] in a previous PR.
cc/ @mzikherman 
[this comment]: https://github.com/artsy/force/pull/14528/files#r1769075579

feat(activity): update preferred source image versions for thumbnails

---

src/Apps/Auction/AuctionApp.tsx
src/Apps/Auction/Components/AuctionBuyNowRail.tsx
src/Apps/Auction/Components/__tests__/AuctionBuyNowRail.jest.tsx
src/Apps/Auction/__tests__/AuctionApp.jest.tsx

This PR solves [DIA-907]
This PR changes the copy on auction page and auction page rail.
[Slack comm](https://artsy.slack.com/archives/C05EEBNEF71/p1727356551259459)
[DIA-907]: https://artsyproduct.atlassian.net/browse/DIA-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update copy on auction page and rail

---

src/Components/NavBar/NavBarLoggedInActions.tsx

Fixes the responsiveness of the user menu in nav bar by not waiting for fetch to complete.

fix(navbar): restore responsiveness

---

src/Apps/Artwork/Components/ArtworkLightbox.tsx
src/Apps/Artwork/Components/ArtworkLightboxPlaceholder.tsx
src/System/Router/renderServerApp.tsx
src/Typings/global.d.ts
src/html.ejs

Cherry picking what should be a straightforward change from https://github.com/artsy/force/pull/14609 to see if I can deploy a review app. Though this should be mergeable without.
https://web.dev/articles/fetch-priority

feat: improve lcp on artwork page

---

src/System/Utils/setupSentryClient.ts
src/instrument.ts

Our sentry quota has been filled, so lets drop this down. We have a lot of existing data to go on for now.

chore(sentry): Drop our sample rate down

---

src/System/Utils/setupSentryClient.ts
src/instrument.ts

chore(sentry): drop our sample rate down further

---

src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx

One of the minor visual things uncovered while testing.
https://www.notion.so/artsy/Order-History-QA-10dcab0764a08007b2efe2d07008d41b

fix: minor update to accommodate for smaller screen

---

Dockerfile

https://github.com/artsy/force/pull/14612 had wrong entrypoint.

fix: path in entrypoint

---

src/Apps/Invoice/Routes/InvoicePaymentRoute.tsx

chore: add line break after payment amount in InvoicePaymentRoute

---

src/Apps/Invoice/Hooks/__tests__/useCreateTokenAndSubmit.jest.ts
src/Apps/Invoice/InvoiceApp.tsx
src/Apps/Invoice/Routes/InvoiceDetailRoute.tsx
src/Apps/Invoice/Routes/InvoicePaymentRoute.tsx
src/Apps/Invoice/Routes/__tests__/InvoiceDetailRoute.jest.tsx
src/Apps/Invoice/Routes/__tests__/InvoicePaymentRoute.jest.tsx
src/Apps/Invoice/__tests__/InvoiceApp.jest.tsx
src/Apps/Invoice/invoiceRoutes.tsx
src/__generated__/InvoiceApp_Test_Query.graphql.ts
src/__generated__/InvoiceDetailRoute_Test_Query.graphql.ts
src/__generated__/InvoicePaymentRoute_Test_Query.graphql.ts

Adding a bunch of tests in advance of setting up the redirect in prod!

test: add tests for InvoiceApp

---

src/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlight.tsx
src/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlights.tsx
src/__generated__/ArtistCareerHighlightsQuery.graphql.ts
src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
src/__generated__/ArtistCareerHighlights_artist.graphql.ts

This PR solves [PBRW-107]
This PR adds safeguards for insights, addressing the issue described in the ticket and discussed in this [Slack thread](https://artsy.slack.com/archives/C05EEBNEF71/p1729601303168049).
[PBRW-107]: https://artsyproduct.atlassian.net/browse/PBRW-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add safeguards for rendering the insights

---

src/System/Components/RouterLink.tsx

This might be more futureproof.

fix: use isPropValid when considering forwarding props

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
src/Apps/Artwork/Components/ArtworkLightbox.tsx
src/Apps/Artwork/Components/ArtworkLightboxPlaceholder.tsx
src/Components/CookieConsentManager/CookieConsentManager.tsx

This implements a few things we brainstormed on in our meeting. If **googlebot**
- Don't lazy load artist image 
- Don't load the cookie consent
- Don't lazyload artwork image
- Don't blur placeholder image

chore(performance): Experiment with improving LCP and CLS by guarding against bots

---

src/Apps/Gene/Components/GeneArtworkFilter.tsx
src/Apps/Gene/Routes/GeneShow.tsx
src/Apps/Gene/Routes/__tests__/GeneShow.jest.tsx
src/Apps/Gene/geneRoutes.tsx
src/__generated__/GeneArtworkFilterRefetchQuery.graphql.ts
src/__generated__/GeneShow_Test_Query.graphql.ts
src/__generated__/GeneShow_gene.graphql.ts
src/__generated__/geneRoutes_GeneShowQuery.graphql.ts

Pretty straightforward, just use a query renderer.

feat: defer artworks grid on Gene pages

---

src/Apps/ArtistSeries/ArtistSeriesApp.tsx
src/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx
src/Apps/ArtistSeries/__tests__/ArtistSeriesArtworksFilter.jest.tsx
src/Apps/ArtistSeries/artistSeriesRoutes.tsx
src/__generated__/ArtistSeriesApp_artistSeries.graphql.ts
src/__generated__/ArtistSeriesArtworksFilterRefetchQuery.graphql.ts
src/__generated__/ArtistSeriesArtworksFilter_Query.graphql.ts
src/__generated__/ArtistSeriesArtworksFilter_artistSeries.graphql.ts
src/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts

Another one! Straightforward, query renderer, plus had to move the 'aggregations' part into the filter component as well.

feat: defer artwork grid on ArtistSeries page

---

src/Apps/Show/Components/ShowArtworks.tsx
src/Apps/Show/ShowApp.tsx
src/Apps/Show/__tests__/ShowApp.jest.tsx
src/Apps/Show/__tests__/ShowArtworks.jest.tsx
src/Apps/Show/showRoutes.tsx
src/__generated__/ShowApp_Test_Query.graphql.ts
src/__generated__/ShowApp_show.graphql.ts
src/__generated__/ShowArtworksFilterQuery.graphql.ts
src/__generated__/ShowArtworksFilterRefetchQuery.graphql.ts
src/__generated__/ShowArtworks_show.graphql.ts
src/__generated__/showRoutes_ShowQuery.graphql.ts

feat: defer artwork grid on Show page

---

src/Apps/Auction/AuctionApp.tsx
src/Apps/Auction/Components/AuctionArtworkFilter.tsx
src/Apps/Auction/Components/__tests__/AuctionArtworkFilter.jest.tsx
src/Apps/Auction/__tests__/AuctionApp.jest.tsx
src/Apps/Auction/auctionRoutes.tsx
src/__generated__/AuctionAppTestQuery.graphql.ts
src/__generated__/AuctionApp_viewer.graphql.ts
src/__generated__/AuctionArtworkFilterRefetchQuery.graphql.ts
src/__generated__/AuctionArtworkFilterTestQuery.graphql.ts
src/__generated__/auctionRoutes_TopLevelQuery.graphql.ts

feat: defer artwork grid on Auction page

---

src/Apps/Partner/Routes/Works/index.tsx
src/Apps/Partner/partnerRoutes.tsx
src/__generated__/WorksFilterQuery.graphql.ts
src/__generated__/WorksFilterRefetchQuery.graphql.ts
src/__generated__/partnerRoutes_WorksQuery.graphql.ts

Similar to deferring the grid on fair.

feat: defer artworks grid on Partner works route

---

src/Apps/Invoice/Components/AddressForm.tsx
src/Apps/Invoice/Components/InvoiceLineItems.tsx
src/Apps/Invoice/Components/InvoicePaymentForm.tsx
src/Apps/Invoice/InvoiceApp.tsx
src/Apps/Invoice/Routes/InvoiceDetailRoute.tsx
src/Apps/Invoice/Routes/InvoicePaymentRoute.tsx
src/Apps/Invoice/Routes/__tests__/InvoiceDetailRoute.jest.tsx
src/Apps/Invoice/Routes/__tests__/InvoicePaymentRoute.jest.tsx
src/Apps/Invoice/__tests__/InvoiceApp.jest.tsx
src/Apps/Invoice/invoiceRoutes.tsx

This adds a bit of polish and visual simplification to the ui, and matches some other patterns seen elsewhere: 

chore(invoice): Clean up layout

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
src/Apps/Artwork/Components/ArtworkLightbox.tsx
src/Apps/Artwork/Components/ArtworkLightboxPlaceholder.tsx
src/Components/CookieConsentManager/CookieConsentManager.tsx

Removes the bot bits on here: https://github.com/artsy/force/pull/14708 and sets lazyload explicitly to `false` to improve LCP.

chore(performance): Attempt to improve LCP by disabling lazyload on Artwork/Artist

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx

Adding some comments to fix [a PR comment](https://github.com/artsy/force/pull/14705#discussion_r1815252355) from [a previous PR](https://github.com/artsy/force/pull/14705)

chore: adding comment to give context on hard coded values

---

package.json
src/middleware.ts
yarn.lock

Removes deep link dependency now that we are serving this file via cloudflare, see here: https://github.com/artsy/artsy-eigen-web-association/pull/58

chore: remove deep link dep

---

src/Apps/Fair/Routes/FairArtworks.tsx
src/__generated__/FairArtworksFilterQuery.graphql.ts

This wasn't being threaded through properly, and so the initial request was fine, but refetches threw a Relay error.

fix: thread through aggregation properly in deferred fair artworks grid

---

src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx

This PR addresses the visual part discovered here [PROJECT-XX]
Think it't good to fix this spacing on a small screens but the app should probably not redirect here. Will confirm with Cami and update the app if we want to redirect to app order history there.

chore: super minor update to mobile version style

---

src/Components/FullBleedHeader/FullBleedHeaderPicture.tsx

Follows up https://github.com/artsy/force/pull/14743 by loading the main artist image for the mobile layout immediately.

feat: don't lazy-load main artist image (LCP)

---

src/Apps/Artists/Components/ArtistsCarouselCell.tsx
src/Apps/Artists/Routes/ArtistsIndex.tsx
src/Apps/Fairs/Components/FairsFairBanner.tsx
src/Apps/Fairs/Routes/FairsIndex.tsx
src/Apps/Partners/Components/PartnersFeaturedCarousel.tsx
src/Apps/Partners/Components/PartnersFeaturedCarouselCell.tsx
src/Apps/Sell/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
src/Components/Cells/CellArtist.tsx

Attempts to reduce LCP score by no longer lazy loading above the fold (main) images on:
- /artists
- /fairs
- /partners
- /sell

chore(lcp): Attempt to improve LCP on top level pages 

---

src/Apps/Articles/Components/ArticlesIndexArticle.tsx
src/Apps/Articles/Components/ArticlesIndexArticles.tsx

Improve LCP by not lazy-loading the first, above the fold image. 

fix(lcp): Improve LCP on /articles

---

src/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
src/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts
src/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts

Improves LCP on /artist-series by not lazy loading the main above the fold image.

fix(lcp): Improve LCP on /artist-series

---

src/Apps/Articles/Components/ArticlesIndexArticle.tsx
src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
src/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
src/Apps/Artists/Components/ArtistsCarouselCell.tsx
src/Apps/Fair/Components/FairHeader/FairHeaderImage.tsx
src/Apps/Fairs/Components/FairsFairBanner.tsx
src/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
src/Apps/Partners/Components/PartnersFeaturedCarouselCell.tsx
src/Apps/Sell/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
src/Components/Cells/CellArtist.tsx
src/Components/CollectionsHubsNav.tsx
src/Components/FullBleedHeader/FullBleedHeaderPicture.tsx

Prioritizes above the fold images with `fetchPriority='high'`.

chore(lcp): Add fetchPriority=high to main images 

---

package.json
src/html.ejs
webpack/envs/clientDevelopmentConfig.js
webpack/envs/clientProductionConfig.js
webpack/sharedPlugins.js
yarn.lock

Reopens revert of artsy/force#14789. 
Running prod locally works just fine, so need to merge and see what staging looks like.

feat(performance): Add PreloadWebpackPlugin for preloading initial JS chunks and simplify html pipeline - take 2

---

package.json
src/html.ejs
webpack/envs/clientDevelopmentConfig.js
webpack/envs/clientProductionConfig.js
webpack/sharedPlugins.js
yarn.lock

feat(performance): Add PreloadWebpackPlugin for preloading initial JS chunks and simplify html pipeline - Take 3

---

webpack/envs/clientProductionConfig.js

Quick follow-up to https://github.com/artsy/force/pull/14793, which fixes the commented-out html minification.

fix(html): Re-enable html minification

---

src/Components/Onboarding/Components/OnboardingFollows.tsx
src/Components/Onboarding/Components/OnboardingMarketingCollection.tsx
src/Components/Onboarding/Components/OnboardingSteps.tsx
src/Components/Onboarding/config.ts

Closes [DIA-776](https://artsyproduct.atlassian.net/browse/DIA-776)
Previously, completion tracking was incomplete. Now it's integrated directly into the workflow, with tracking occurring at the final step.
[DIA-776]: https://artsyproduct.atlassian.net/browse/DIA-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: properly tracks completion, and avoids early closure

---

hokusai/production.yml
hokusai/staging.yml

This PR solves [PHIRE-1315]
Load-secrets script now lives in [Fortress repo](https://github.com/artsy/fortress).
[PHIRE-1315]: https://artsyproduct.atlassian.net/browse/PHIRE-1315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: switch initContainer to Fortress repo

---

src/Server/middleware/hardcodedRedirects.ts

Reverts artsy/force#14852
Too many redirects issue in /user routes
https://artsy.slack.com/archives/C05EEBNEF71/p1731920485790039?thread_ts=1731701728.948379&cid=C05EEBNEF71

Revert "chore: permanent redirects edit and additions"

---

src/Apps/Order/Routes/NewPayment/index.tsx
src/Apps/Order/Routes/Respond/index.tsx
src/Components/__stories__/CountdownTimer.story.tsx

Adresses [EMI-2186](https://artsyproduct.atlassian.net/browse/EMI-2186)
[EMI-2186]: https://artsyproduct.atlassian.net/browse/EMI-2186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update note for counteroffer step

---

src/Apps/Artwork/ArtworkApp.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
src/Apps/Artwork/__tests__/ArtworkApp.jest.tsx
src/Apps/Artwork/artworkRoutes.tsx
src/System/Router/Utils/serverAppContext.ts
src/System/Router/__tests__/serverRouter.jest.enzyme.tsx
src/__generated__/ArtworkAppTestQuery.graphql.ts
src/__generated__/ArtworkApp_artwork.graphql.ts
src/__generated__/ArtworkApp_artworkResult.graphql.ts
src/__generated__/ArtworkApp_me.graphql.ts
src/__generated__/ArtworkSidebarQuery.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

This is a large component which is actually below the fold in our (current) mobile layout for the artwork page.
So, let's conditionally fetch that fragment (on desktop) vs. using a query renderer (on mobile).

feat: use a query renderer for artwork page sidebar on mobile

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx

This looks fine to me? (but so did the non-placeholder version).

chore: add placeholder for artwork sidebar query renderer

---

data/schema.graphql

chore: Sync schema

---

src/Components/MagnifyImage.tsx

Perf on this has become janky over the past few months. This fixes that: 
https://github.com/user-attachments/assets/6449cbcf-8ac6-47fb-9062-cb48ab037984

fix(artwork-brick): Fix artwork hover zoom performance

---

src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
src/__generated__/ArtworkAppTestQuery.graphql.ts
src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

Fixes issue where there was a store mismatch between data which is used to initially render the page and the data fetched (and updated in the store). Specifically, related to follower count. 
See this [slack thread](https://artsy.slack.com/archives/C05EEBNEF71/p1732301220557309) for more info.

fix(artist): Fix missing artist follower count

---

src/Apps/ViewingRoom/viewingRoomRoutes.tsx
src/Apps/WorksForYou/worksForYouRoutes.tsx

A couple of routes weren't saved before committing https://github.com/artsy/force/pull/14918 -- this updates that.

chore(preloading): add a couple missing routes

---

src/client.tsx

Starting to implement suggestions from [this blog post](https://kurtextrem.de/posts/improve-inp-react), and in particular [concurrent hydration](https://kurtextrem.de/posts/improve-inp-react#concurrent-hydration-with-).

chore(performance): Optimize rehydration

---

src/Apps/Components/AppShell.tsx
src/client.tsx

Test if this fixes some integrity issues we might be running into with wrapping `hydrateRoot` around a startTransition.

fix(ready-event): Test moving Integrity ready flag

---

src/Apps/Components/AppShell.tsx
src/client.tsx

Integrity didn't like the rehydration optimization in https://github.com/artsy/force/pull/14940, so going to revert for now and spin up a local integrity to diagnose (later). Seemed like a harmless quick win, but will need to investigate why things are failing.

fix(integrity): undo changes

---

src/Components/NavBar/Menus/NavBarNotifications.tsx

Reverts artsy/force#14947 because it does not fix the bug and does not seem to be related.

Revert "fix: Revert lazy loading notifications dropdown"

---

src/Apps/Artist/ArtistApp.tsx
src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx

This fixes a few things on mobile, notably 
- The incorrect assignment of fetchPriority on the top artist image (need to apply it to the link tag, too)
- Removes double image fetching by wrapping mobile/desktop in hard application boundaries (vs using fresnel)
- Lowers the quality on mobile to match artwork. With srcset its hardly noticeable, yet we save kb. 

fix(artist): Fix LCP and fetchPriority assignment

---

src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx
src/Apps/Marketing/Routes/MarketingFindArtYouLoveRoute.tsx

This PR solves [ONYX-1434]
[As requested](https://artsy.slack.com/archives/C07PRTJSD6G/p1733334824005519), changing the title from "Curators’ Picks: Emerging" to "Curators’ Picks"
[ONYX-1434]: https://artsyproduct.atlassian.net/browse/ONYX-1434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ONYX-1434): change Curators’ Picks title

---

package.json
src/Apps/Order/Routes/Shipping/Components/__tests__/SavedAddresses.jest.tsx
src/dev.ts
yarn.lock

Notice hot module reloading was behaving slowly and looking closer, realized that I accidentally mounted the RSBuild middleware after express-reloadable, which was blocking the HMR update event being sent to the browser. This fixes that and now changes to code are instant again. 

fix(hot-reloading): improve perf

---

src/Apps/Order/Routes/Shipping/Components/AddressModal.tsx
src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Routes/AdditionalRoutes/FrameRoute.tsx
src/Apps/Sell/Routes/DetailsRoute.tsx
src/Apps/Sell/Routes/PhoneNumberRoute.tsx
src/Apps/Sell/SellFlowContext.tsx

This PR solves [ONYX-1435]
Fix phone number validation on the SWA submission flow
**Logged out user:**
https://github.com/user-attachments/assets/f219c4c7-c6f8-477a-802f-59dca3486190
**Logged in user:**
https://github.com/user-attachments/assets/2ba15220-1f15-438e-8709-a4b6c27f0a04
[ONYX-1435]: https://artsyproduct.atlassian.net/browse/ONYX-1435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(ONYX-1435): fix phone number validation on SWA submission flow

---

package.json
src/Apps/Artwork/Components/__tests__/PricingContext.jest.enzyme.tsx
yarn.lock

This PR solves [DIA-1032]
Related: https://github.com/artsy/palette/pull/1414
Fixes broken chart init. 
[DIA-1032]: https://artsyproduct.atlassian.net/browse/DIA-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(palette-charts): Bump 39.1.1 (fix bar chart)

---

src/Server/startServer.ts

Not sure about this one! Things work fine locally, so not too sure why they don't when deployed to staging / prod. Lets see if this has an impact. 
[PBRW-260]: https://artsyproduct.atlassian.net/browse/PBRW-260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(404): Attempt to fix 404

---

docs/creating_review_app.md

Updates docs around review app creation. 
**TLDR**:
- `git checkout -b review-app-hello-world` 
- Add some commits 
- Push branch to GitHub
- Visit `https://hello-world.artsy.net` 

docs(review-app): Update docs

---

src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx

Follow up on changes for https://artsyproduct.atlassian.net/browse/EMI-2204
This might be reviewed after we pair with Viviana on update display of the orders but for now I believe it represents the most accurate the action collector needs to take.

feat: for now bundle incomplete offer partner reply into Counteroffer Received state

---

cypress/e2e/auction.cy.ts

Add smoke test asserting that query params still render the grid.

test(auction): Add smoke test around auction/id and query params

---

src/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx

Addresses [ONYX-646]
Allow creating alerts with multiple artists from Artist series page.
[ONYX-646]: https://artsyproduct.atlassian.net/browse/ONYX-646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Allow creating alerts with multiple artists from Artist series page

---

package.json
src/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
src/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitLoggedOut.tsx
src/Apps/Home/Components/HomeHeroUnits/HomeHeroUnits.tsx
src/Apps/Marketing/Components/MarketingHeader.tsx
src/Apps/Marketing/Components/MarketingHeaderSpitTest.tsx
src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx
yarn.lock

Reverts artsy/force#14987
Re-enables: https://github.com/artsy/force/pull/14985
Adds tracking

chore: Revert "chore: Revert "feat: adds download app split test for logged out hero units""

---

src/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitLoggedOut.tsx

fix(home): adds experiment tracking

---

src/Components/CollectorProfile/CollectorProfileArtistsAdd.tsx

This PR solves  [ONYX-400]
* Related Eigen PR: https://github.com/artsy/eigen/pull/11252
Automatically opt into sharing collected artists with galleries.
[ONYX-400]: https://artsyproduct.atlassian.net/browse/ONYX-400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Automatically opt into sharing collected artists with galleries

---

.vscode/settings.json

Adds some missing VSCode config

fix(formatter): fix vscode config

---

src/Apps/Jobs/JobsApp.tsx

feat(jobs): adds talent pool link

---

src/Apps/Debug/debugRoutes.tsx

Re: https://github.com/artsy/force/pull/15028#discussion_r1892707702

fix(debug): uses getcomponent

---

CONTRIBUTING.md
scripts/setup.sh

Updated our README and setup script with the latest.

docs(setup): Update setup readme docs and setup.sh script

---

src/dev.ts

Logic for the --open command could lose the condition.

fix(dev): Simplify up logic

---

.vscode/settings.json

Small fix to improve perf of the linter/formatter.

fix: Formatting perf

---

docs/best_practices.md
package.json

Updates our docs on Relay to match current best practices.

docs(best-practices): Update docs on Relay

---

src/Apps/Artwork/Components/ArtworkPageBanner.tsx

Removes expired partner offers FF, simplifying the logic

chore: remove expired partner offers ff

---

src/Apps/Auctions/AuctionsApp.tsx

fix(auctions): updates link to help page

---

src/Apps/Auctions/__tests__/AuctionsApp.jest.enzyme.tsx

The type of this PR is: **test**
Noticing the `main` branch is failing. This fixes the test from https://github.com/artsy/force/pull/15057.

test: fix help article link

---

src/Apps/Artist/Components/ArtistMeta/ArtistMeta.tsx
src/Apps/Artist/Components/ArtistMeta/__tests__/ArtistMeta.jest.tsx
src/Apps/Artist/Components/ArtistMeta/__tests__/useCanonicalHref.jest.tsx
src/Apps/Artist/Components/ArtistMeta/useCanonicalHref.ts
src/Apps/Sitemaps/sitemapsServerApp.tsx
src/__generated__/ArtistApp_Test_Query.graphql.ts
src/__generated__/ArtistMeta_Test_Query.graphql.ts
src/__generated__/ArtistMeta_artist.graphql.ts
src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
src/__generated__/artistRoutes_ArtistSubAppQuery.graphql.ts
src/__generated__/sitemapsServerAppQuery.graphql.ts

Closing https://github.com/artsy/force/pull/15082 in favor of this; since these need to be together.
This enables a small SEO experiment where we will index some medium specific filter views for a selection of 100 artists.

feat(artist): enables 100 artist seo experiment

---

src/Apps/Jobs/Components/JobsFilter.tsx
src/__generated__/JobsFilter_viewer.graphql.ts
src/__generated__/jobsRoutes_JobsQuery.graphql.ts

fix(jobs): switches to grouping by team instead of dept

---

src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx

Whoops! Noticed this in #product-bugs

fix: remove errand right parens in artist works route

---

src/Components/NavBar/NavBar.tsx

Fixes issue where Buy link vanishes at `md` breakpoints. 
https://github.com/user-attachments/assets/2e5cb3c6-854f-460c-9deb-4dbbde7c485a

fix(nav): always persist Buy link

---

src/Apps/Artwork/Components/PricingContext.tsx
src/__generated__/PricingContextQuery.graphql.ts

Getting back into the swing of things and noticed I updated but never committed this small change to cache the pricing context (chart) query.

chore: cache pricing context query

---

src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryFigure.tsx
src/Apps/Article/Components/ArticleZoomGallery/__tests__/ArticleZoomGallery.jest.tsx
src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
src/Apps/Fair/Components/FairHeader/FairHeaderImage.tsx
src/Components/HeaderIcon.tsx

I'm trying to get back into Force after a while away and this warning appears locally:
```
Warning: Invalid DOM property `imagesrcset`. Did you mean `imageSrcSet`?
at link
```

fix: use valid DOM property

---

src/Components/ArtsyShippingEstimate.tsx

This is additional minor tweaks to the Arta widget styles.
I'll merge this as those are minor.

chore: some more style tweaks

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarLinks.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarLinks.jest.tsx
src/Apps/Auction/Components/AuctionDetails/AuctionInfoSidebar.tsx

| <img width="1901" alt="Screenshot 2025-02-10 at 14 18 19" src="https://github.com/user-attachments/assets/fa7e3256-fa6a-4f41-bb5e-6d00216b744a" /> | <img width="1899" alt="Screenshot 2025-02-10 at 14 15 56" src="https://github.com/user-attachments/assets/b2b956ba-4efe-4ae6-bcfb-b3390782f116" /> |
| <img width="1904" alt="Screenshot 2025-02-10 at 14 18 13" src="https://github.com/user-attachments/assets/18b73d4c-01dc-45e6-a897-59f47038e528" /> | <img width="1903" alt="Screenshot 2025-02-10 at 14 16 26" src="https://github.com/user-attachments/assets/a449b574-fc8a-48a1-944f-0119b41cff55" /> | 
This PR solves [ONYX-1531] [ONYX-1524] (sorry I only saw that you also have started working on this after pushing this PR …

chore: remove sell mentions

---

src/Components/Footer/FooterDownloadAppBanner.tsx

This PR solves [ONYX-1534]
Swaps in a new banner, without the Sell CTA
| <img src="https://files.artsy.net/images/universal-footer_april-14_cropped.jpg" /> | <img src="https://files.artsy.net/images/artsy-universal-footer-2025.png" /> | 
[ONYX-1534]: https://artsyproduct.atlassian.net/browse/ONYX-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(swa): swap footer banner image

---

src/Components/Footer/Footer.tsx
src/Components/Footer/__tests__/Footer.jest.enzyme.tsx

fix: updates footer link copy

---

README.md

chore: remove dead links from readme

---

src/Components/Notifications/NotificationItem.tsx
src/__generated__/NotificationItem_notification.graphql.ts
src/__generated__/NotificationItem_test_Query.graphql.ts
src/__generated__/NotificationsListNextQuery.graphql.ts
src/__generated__/NotificationsListQuery.graphql.ts
src/__generated__/NotificationsList_test_Query.graphql.ts

So this should be the only real stumbling block in the way of https://github.com/artsy/palette/pull/1423
And this seems like something that we should actually correct, of course. I'm tempted to also make width and height required params in the type signature on image, but I'll probably do that separately.

fix(notifications): adds missing geometry

---

src/Apps/Home/Components/HomeFeaturedMarketNews.tsx

Re: https://artsy.slack.com/archives/C07PRTJSD6G/p1740669615506399
It seems that we would get a lot of mileage out of at least publishing a canary that requires an height and then using that to validate that all of our images are correct.

fix(homepage): fixes image collapse

---

src/Components/NavBar/__tests__/NavBarSubMenu.jest.enzyme.tsx
src/Components/NavBar/menuData.ts

This PR solves [DIA-1084] and [DIA-1159]
We've made changes to the links in the nav bar, updating the price ranges and replacing collections with size and color filters. 
[DIA-1084]: https://artsyproduct.atlassian.net/browse/DIA-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DIA-1159]: https://artsyproduct.atlassian.net/browse/DIA-1159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-1084): Updates to nav bar links 

---

package.json
yarn.lock

Manually update cohesion because [dependabot cannot do it](https://artsy.slack.com/archives/C02BC3HEJ/p1741952742113239?thread_ts=1741943554.390519&cid=C02BC3HEJ) because of `^`.

chore: update cohesion

---

docs/adding_new_app.md
docs/caching.md
src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
src/Apps/Artist/artistRoutes.tsx
src/Components/NavBar/NavBar.tsx
src/Components/NavBar/NavBarDropdownPanel.tsx
src/System/Components/RouterLink.tsx
src/System/Hooks/__tests__/usePrefetchRoute.jest.tsx
src/System/Hooks/usePrefetchRoute.tsx
src/System/Router/Route.tsx

Reverts artsy/force#15324
Reopening this as a review app.

Revert "feat(performance): Add support for prefetching route sub queries via `prefetchSubQueries` on hover"

---

docs/best_practices.md

Adds link to vault for managing secrets

docs(vault): Update best_practices.md

---

package.json
src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
src/Apps/Order/Hooks/useOrderTracking.tsx
yarn.lock

Updates express checkout tracking with new field name

chore: update express checkout tracking

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
src/Apps/Order/Components/ExpressCheckout/Mutations/useSubmitOrderMutation.ts
src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
src/Apps/Order/Components/ExpressCheckout/index.tsx
src/__generated__/useSubmitOrderMutation.graphql.ts

This PR solves [EMI-2304]
Depends on https://github.com/artsy/metaphysics/pull/6565.
This is the UI counterpart of the [API work](https://github.com/artsy/exchange/pull/2470) to support submitting an Apple Pay order.
[EMI-2304]: https://artsyproduct.atlassian.net/browse/EMI-2304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: submit apple pay order on confirm

---

src/Components/NavBar/menuData.ts

Just wanted to get this out of the way while I work on fixing the underlying issue.

fix(nav): removes colors

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx

This PR solves [EMI-2393]
[EMI-2393]: https://artsyproduct.atlassian.net/browse/EMI-2393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2393): add ToS line below Apple Pay CTA

---

src/Components/DeepZoom/DeepZoom.tsx

You might have thought, when you click to zoom an artwork on Artsy and you saw the spinner, that meant that something was loading. But no, you would be mistaken.
Prior to React 18, this had access to the ref by the time that effect ran. Once we upgraded to React 18 there's a stricter distinction between render and commit phases. At that point we noticed that it was no longer working and the ref was added to the dependency array (despite the fact that you very much do not/should not add refs to dependency arrays). But it worked now.
Best I can tell is that React 18's new concurrency model may be prioritizing other operations before getting back to our component's initialization. Either way using a callback ref works better since it'll execute as soon as the element is available. …

fix(artwork): eliminates delay when opening zoom view

---

src/Apps/Checkout/ApplePay.tsx
src/Apps/Checkout/checkoutRoutes.tsx
src/__generated__/ApplePay_order.graphql.ts
src/__generated__/checkoutRoutes_ApplePayQuery.graphql.ts

This PR solves [EMI-2375]
[EMI-2375]: https://artsyproduct.atlassian.net/browse/EMI-2375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2375): testing Apple Pay in checkout app

---

src/Apps/SaleAgreements/Routes/SaleAgreementRoute.tsx
src/Apps/SaleAgreements/SaleAgreementsApp.tsx
src/Apps/SaleAgreements/__tests__/SaleAgreementRoute.jest.tsx
src/Apps/SaleAgreements/__tests__/SaleAgreementsApp.jest.tsx

This PR removes the `sapphire_supplemental-cos` feature flag, which is no longer needed.

chore: remove sapphire_supplemental-cos flag

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx

This PR solves [EMI-2387]
I took the liberty to unify the cases since there's no current logic between those. I've tested locally and it's working fine.
[EMI-2387]: https://artsyproduct.atlassian.net/browse/EMI-2387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2387): update express checkout shipping display names

---

src/Components/NavBar/NavBar.tsx

This PR solves [DIA-1290]
Updated the url for Collecting 101 to match editorial changes. 
[DIA-1290]: https://artsyproduct.atlassian.net/browse/DIA-1290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-1290): updated Collecting 101 url

---

package.json
src/Apps/Order/Components/ApplePayDetails.tsx
src/Apps/Order/Components/CreditCardDetails.tsx
yarn.lock

This PR solves part of [EMI-2412]
This PR adds the Apple Pay icon to the order history page
It also updates the size of icons from `24x24` to `26x26` to match
| Icon | Before | After |
|---|---|---|
| Apple Pay | <img width="284" alt="image" src="https://github.com/user-attachments/assets/f9865cd2-f6a6-445c-b149-2df03232bcf0" /> | ![image](https://github.com/user-attachments/assets/7b5633a6-dd07-4f3c-b5ac-fa72b335f52e) |
| Visa | <img width="284" alt="image" src="https://github.com/user-attachments/assets/2784bb92-4b4e-42dc-beb5-43443d6b4c35" /> | ![image](https://github.com/user-attachments/assets/6309efb8-27b2-48e6-a177-37063ff3836b) |
| MasterCard | <img width="284" alt="image" src="https://github.com/user-attachments/assets/7acf0fc3-b95b-4a1f-a077-c3a3c …

feat(EMI-2412): Add Apple Pay icon to order history

---

src/Components/Search/Mobile/Overlay.tsx
src/Components/Search/SearchBarInput.tsx

This PR solves [ONYX-1561]
This PR fixes the broken debouncing behavior on the search input.
|  | Desktop | Mobile |
|--------|--------|--------|
| Before | <video src="https://github.com/user-attachments/assets/3570d744-ab29-47b1-8b26-a90f4914f6af" /> | this wasn't broken |
| After | <video src="https://github.com/user-attachments/assets/df8564ba-f1f8-4a5e-bad3-c281c954c6e4" /> | <video src="https://github.com/user-attachments/assets/28a54cf4-aeb8-4d71-8e5a-c0ab9993ca22" /> | 
[ONYX-1561]: https://artsyproduct.atlassian.net/browse/ONYX-1561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: broken search input debouncing

---

src/Apps/Order/__tests__/OrderApp.jest.enzyme.tsx
src/Apps/Order/orderRoutes.tsx
src/Apps/Order/redirects.tsx
src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
src/Apps/Order2/Routes/Details/Order2DetailsRoute.tsx
src/Apps/Order2/order2Routes.tsx
src/__generated__/order2Routes_CheckoutQuery.graphql.ts
src/__generated__/order2Routes_DetailsQuery.graphql.ts

Reverts artsy/force#15481 because we need to set up routing in eigen first. 
#minor

Revert "chore(EMI-2364): Redirects for new order checkout/details routes"

---

src/Components/ArtsyShippingEstimate.tsx
src/Components/__tests__/ArtsyShippingEstimate.jest.tsx

This PR solves [EMI-2443]
Pass state to Arta widget if we have it
[EMI-2443]: https://artsyproduct.atlassian.net/browse/EMI-2443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2443): consider the state for arta shipping widget

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx

This PR solves [EMI-2431]
`google_pay` is passed to submitOrderMutation on the client 
[EMI-2431]: https://artsyproduct.atlassian.net/browse/EMI-2431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2431): google pay

---

src/Apps/Order2/Order2App.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsPage.tsx
src/Apps/Order2/Routes/Details/Order2DetailsRoute.tsx
src/Apps/Order2/order2Routes.tsx

Was going to wait for this Pr first https://github.com/artsy/force/pull/15481 but it actually minimal overlap - and looks better:)

chore: updating static code for details page to add help and update colors.

---

src/Components/Onboarding/Components/OnboardingFigure.tsx

This PR solves [DIA-1232]
I've removed lazy loading for the onboarding quiz to address a bug with image rendering
Before:
After:
[DIA-1232]: https://artsyproduct.atlassian.net/browse/DIA-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-1232): removing lazy load for image rendering

---

docs/using_unleash.md
package.json
src/Apps/Example/exampleRoutes.tsx
src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
src/Apps/Order/__tests__/OrderApp.jest.enzyme.tsx
src/Apps/Order/orderRoutes.tsx
src/Apps/Order/redirects.tsx
src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
src/Apps/Order2/Routes/Details/Order2DetailsRoute.tsx
src/Apps/Order2/order2Routes.tsx
src/System/Contexts/SystemContext.tsx
src/System/Router/__tests__/clientRouter.jest.tsx
src/__generated__/order2Routes_CheckoutQuery.graphql.ts
src/__generated__/order2Routes_DetailsQuery.graphql.ts
src/client.tsx
src/server.ts
yarn.lock

This PR solves [EMI-2364] and [EMI-2380]
This PR re-implements the reverted #15481 with an update to the system context to make it pass the correct context values to unleash when checking on the server.
[EMI-2364]: https://artsyproduct.atlassian.net/browse/EMI-2364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMI-2380]: https://artsyproduct.atlassian.net/browse/EMI-2380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2364): new checkout and order details page redirects

---

src/Apps/About/AboutApp.tsx
src/Apps/Components/constants.ts
src/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx

This PR adds proposed JSON-LD schema to the about page, with one object describing our applications and the other describing our organization. I've edited the proposal for accuracy and expanded it a bit.
We should probably decide on the description, keywords, and whether there's any information we don't want here.
The only slightly weird thing is that we'd have to keep the aggregate ratings up to date, so those will require an update every so often.
I also fixed a bug in the hero URL that was causing the mobile version of the image to not load.
```json
{
"@context": "https://schema.org",
"@type": "WebApplication",
"name": "Artsy",
"url": "https://www.artsy.net",
"applicationCategory": ["LifestyleApplication", "ShoppingApplication"],
"operatingSystem": "Web",
"browserRequirements": …
```

feat(dia-1298): adds JSON-LD to about page

---

src/Apps/Components/Layouts/LayoutLogoOnly.tsx
src/Apps/Components/Layouts/LayoutLogoOnlyFullBleed.tsx
src/Apps/Components/Layouts/index.tsx
src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
src/Apps/Order2/order2Routes.tsx
src/Components/Address/AddressFormFields.tsx

The type of this PR is: **Style**
This PR solves [EMI-2382].
Data is almost entirely static - I created an object for a few properties to track where they came from in our legacy checkout flow.
There is a slight change to the `LayoutLogoOnly` component to enable a full-bleed version that removes the horizontal padding on the page.
[EMI-2382]: https://artsyproduct.atlassian.net/browse/EMI-2382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

style(EMI-2382): Static checkout flow, mobile

---

src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx

Update failing express checkout spec after https://github.com/artsy/force/pull/15502 got merged.

fix: update ExpressCheckoutUI specs

---

src/Apps/About/AboutApp.tsx

Just a minor change flagged in [Google's Rich Results Test](https://search.google.com/test/rich-results/result/r%2Fsoftware-apps?id=o0UhtqCav86Z0os7CygGfg).

feat(about): adds operating system field for android app

---

src/Apps/Article/ArticleApp.tsx
src/Apps/Article/Components/ArticleStructuredData.tsx
src/__generated__/ArticleApp_article.graphql.ts
src/__generated__/ArticleStructuredData_article.graphql.ts
src/__generated__/articleRoutes_ArticleQuery.graphql.ts

Adds structured data for articles. Following guidelines here: https://developers.google.com/search/docs/appearance/structured-data/article

feat(about): adds structured data schema for article

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx

Looks like this got accidentally added from an AI autocomplete ✨

fix(artwork): removes target blank

---

src/Apps/SaleAgreements/Routes/SaleAgreementRoute.tsx
src/Apps/SaleAgreements/SaleAgreementsApp.tsx

Adds missing title tags. Minor item flagged in the action board.

feat: adds missing title tags

---

src/System/Relay/createRelaySSREnvironment.ts

Send x-xapp-token downstream when executing relay middleware

feat: include artsy xapp token when sending headers downstream

---

src/Apps/About/AboutApp.tsx
src/Apps/Components/constants.ts
src/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
src/Apps/Sitemaps/sitemapsServerApp.tsx
src/Apps/Sitemaps/templates/llms.ts
src/Components/Footer/Footer.tsx
src/Utils/factsAndFigures.ts

Obviously, I think this could use some editing, but this just opens a draft and gets things set up. I also need to figure out who maintains the "Stats and Facts" document as it is out of date. I did use the values it specifies for now.
See https://llmstxt.org/ for the spec and https://llmstxt.site/ for some examples. I'd be interested in seeing more examples for normal ecommerce sites. Most of these lean towards technical products. Here's an ecomm example: https://cdn.shopify.com/s/files/1/0650/1158/1085/files/llms.txt?v=1743756682
Below is the draft of the text as rendered Markdown.
-------
> Artsy is the world’s largest online art marketplace. Browse over 1,000,000 artworks by iconic and emerging artists from 3,000+ galleries and top auction houses.
- …

feat(dia-1311): create and implement llms.txt

---

src/Apps/Order2/Routes/Details/Components/Order2DetailsMessage.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsOrderSummary.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsPaymentInfo.tsx

Thanks for noticing and for the suggestion @MrSltun . I forgot about this `flexShrink` trick option.

chore: adjusting Artwork title text to have proper truncation

---

src/Apps/Components/Layouts/LayoutLogoOnlyFullBleed.tsx
src/Apps/Order2/Order2App.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentStep.tsx
src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx

Paired with @oxaudo 
This PR solves [EMI-2472].
This PR adds the 2-column desktop layout with other responsive tweaks to the layout component used in checkout and order details. 
<details><summary>Demo</summary>
<p>
</p>
</details> 
[EMI-2472]: https://artsyproduct.atlassian.net/browse/EMI-2472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2472): New checkout desktop layout

---

data/schema.graphql
src/Apps/Order2/Routes/Details/Components/Order2DetailsFulfillmentInfo.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsPage.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsPaymentInfo.tsx
src/Apps/Order2/Routes/Details/Components/__tests__/Order2DetailsFulfillmentInfo.jest.tsx
src/__generated__/Order2DetailsFulfillmentInfo_TestQuery.graphql.ts
src/__generated__/Order2DetailsFulfillmentInfo_order.graphql.ts
src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
src/__generated__/Order2DetailsPage_order.graphql.ts
src/__generated__/order2Routes_DetailsQuery.graphql.ts

feat: implement fulfillment details on Order details page

---

src/Apps/Order2/Components/Order2PricingBreakdown.tsx
src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2PickupForm.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsHelpLinks.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsOrderSummary.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsPage.tsx
src/__generated__/Order2DetailsOrderSummary_order.graphql.ts
src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
src/__generated__/order2Routes_DetailsQuery.graphql.ts

This moves us to the right direction. Will probably need to adjust more stuff but good to start testing.

chore: start responsive adjustment for details page

---

src/Apps/Order2/Routes/Details/Components/Order2DetailsHelpLinks.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsPage.tsx
src/Apps/Order2/Routes/Details/Components/__tests__/Order2DetailsHelpLinks.jest.tsx
src/__generated__/Order2DetailsHelpLinks_Test_Query.graphql.ts
src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
src/__generated__/Order2DetailsPage_order.graphql.ts
src/__generated__/order2Routes_DetailsQuery.graphql.ts

This PR solves [EMI-2445]
This PR adds functionality to the links in the new Order Details screen
It also adds tests for `Order2DetailsHelpLinks`
<video src="https://github.com/user-attachments/assets/97372bf0-fba4-48b2-b7e6-3059c1f25b33" />
[EMI-2445]: https://artsyproduct.atlassian.net/browse/EMI-2445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2445): Add help links section functionality

---

src/Apps/Partner/Components/PartnerMeta/PartnerMetaStructuredData.tsx
src/__generated__/PartnerApp_Test_Query.graphql.ts
src/__generated__/PartnerMetaStructuredData_partner.graphql.ts
src/__generated__/partnerRoutes_PartnerQuery.graphql.ts

This populates the `member` field with represented artists.
I initially considered making this a separate PR because I wasn't sure how performant this fetch would be for a feature that's invisible in the UI. Limiting it to representation seems to make it not too bad in practice. We can always revisit this, but for now, this seems reasonable.
----
```json
{
"@context": "https://schema.org",
"@type": "ArtGallery",
"@id": "http://localhost:5050/partner/paula-cooper-gallery",
"name": "Paula Cooper Gallery",
"url": "http://localhost:5050/partner/paula-cooper-gallery",
"description": "Paula Cooper Gallery, the first art gallery in SoHo, opened in 1968. For over fifty years, the gallery’s artistic agenda has remained focused on, though not limited to, conceptual and minimal art.",
"image": { …
```

feat(partner): adds represented artists to json ld schema

---

src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx

This PR solves [EMI-2553]
Disables Apple and Google Pay in the payment element
[EMI-2553]: https://artsyproduct.atlassian.net/browse/EMI-2553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2553): disable wallet payment methods in the payment element

---

src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/Order2ExpressCheckoutUI.tsx
src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx
src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx

This PR relates to [EMI-2542]
This PR contains #minor copy updates.
[EMI-2542]: https://artsyproduct.atlassian.net/browse/EMI-2542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2542): copy updates

---

src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
src/Apps/Order2/Routes/Checkout/Components/DeliveryOptionsStep/Order2DeliveryOptionsStep.tsx

This PR solves [EMI-2549]
Followup of https://github.com/artsy/force/pull/15675 to address additional comments that were made after the code was merged.
Thanks @damassi for the review.
[EMI-2549]: https://artsyproduct.atlassian.net/browse/EMI-2549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2549): followup from code review

---

src/Apps/Order2/Routes/Details/Components/Order2DetailsFulfillmentInfo.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsHeader.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsMessage.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsOrderSummary.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsPaymentInfo.tsx

This PR solves [EMI-2564]
A pass at adjusting font sizes and spacing
[EMI-2564]: https://artsyproduct.atlassian.net/browse/EMI-2564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2564): order details style check

---

src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx
src/Components/Onboarding/Views/OnboardingCuratedArtworks.tsx

This is a follow-up to #15710 that makes an even smaller copy change.

fix(DIA-1364): curators picks subtitle once more

---

src/Apps/Order/Routes/Shipping/Components/ShippingQuotes.tsx

This PR solves [EMI-2586]
Change copy to adapt to new Arta standard shuttle premium option
https://www.figma.com/design/kaBdUapJIWs9YL9ATlPDzw/Checkout-Redesign?node-id=1476-6253&p=f&m=dev
[EMI-2586]: https://artsyproduct.atlassian.net/browse/EMI-2586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2586): change white glove copy

---

src/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
src/Apps/Order/Utils/__tests__/offerUtils.jest.ts
src/Apps/Order/Utils/offerUtils.ts

This PR solves [EMI-2588]
Remove offer guidance copy
[EMI-2588]: https://artsyproduct.atlassian.net/browse/EMI-2588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2588): remove offer guidance copy

---

src/Apps/Components/Layouts/LayoutLogoOnlyFullBleed.tsx
src/Apps/Order2/Routes/Checkout/Components/DeliveryOptionsStep/Order2DeliveryOptionsStep.tsx
src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/Order2ExpressCheckout.tsx
src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/Order2ExpressCheckoutUI.tsx
src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2FulfillmentDetailsCompletedView.tsx
src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2FulfillmentDetailsStep.tsx
src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2PickupForm.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2HelpLinks.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentCompletedView.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentStep.tsx
src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx

This PR solves [EMI-2575]
Layout and copy changes to checkout redesign
https://github.com/user-attachments/assets/e02cfbe8-8d2c-47ae-973a-e4c27f10755c
https://github.com/user-attachments/assets/92321ad8-1d2c-4405-8ad1-67050b735d85
[EMI-2575]: https://artsyproduct.atlassian.net/browse/EMI-2575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2575): Layout and copy changes to checkout redesign

---

src/Apps/Order/Utils/__tests__/orderUtils.jest.ts
src/Apps/Order/Utils/orderUtils.ts

This PR solves [EMI-2590]
Update the payment step of the legacy flow to not auto-select the first payment method, and instead, ask users to explicitly select one when there are multiple options.
https://github.com/user-attachments/assets/7a9f5ea7-ccd5-4e39-928a-7d5d2b4e79dd
[EMI-2590]: https://artsyproduct.atlassian.net/browse/EMI-2590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2590): no default payment method

---

src/Apps/Order/Routes/Shipping/Components/FulfillmentDetailsForm.tsx
src/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethodForm.tsx
src/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx
src/Components/Address/AddressAutocompleteInput.tsx
src/Components/Address/AddressForm.tsx

Current checkout
https://github.com/user-attachments/assets/c5b32e94-1d5d-4373-86b3-8b2efa357003
New checkout
https://github.com/user-attachments/assets/80155313-8aa1-4fca-9e87-3b8c0077837d

chore(EMI-2573): update address autocomplete placeholder copy

---

src/Apps/About2/Components/AboutWhatWeDo.tsx

feat(about2): adds what we do section

---

src/Apps/About2/Components/AboutPress.tsx

Just fixes up the layout on mobile for the press section

fix(about2): fixes mobile layout for press

---

src/Apps/About2/Components/AboutJoin.tsx

feat(about2): adds join as partner section

---

src/Apps/About2/About2App.tsx
src/Apps/About2/Components/AboutNav.tsx
src/Apps/About2/Components/AboutSection.tsx
src/Utils/Hooks/useIntersectionObserver.ts

Improves section highlighting and adds nav on mobile
https://github.com/user-attachments/assets/a5ab5f6f-266a-4cfe-90d3-10a747154963

feat(dia-1389): add mobile version of bottom section nav

---

src/Apps/Auction/Components/AuctionDetails/AuctionInfoSidebar.tsx
src/Apps/Auction/Components/AuctionDetails/__tests__/AuctionInfoSidebar.jest.enzyme.tsx

This PR solves [EMI-2636]
Removes the feature flag check and add some specs.
https://artsyproduct.atlassian.net/browse/EMI-2636
[EMI-2636]: https://artsyproduct.atlassian.net/browse/EMI-2636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2636): remove emerald_hackathon-sale-total-raised feature flag

---

package.json
src/Apps/About2/Components/AboutDownload.tsx
src/Apps/About2/Components/AboutHeader.tsx
src/Apps/About2/Components/AboutJoin.tsx
src/Apps/About2/Components/AboutNav.tsx
src/Apps/About2/Components/AboutPress.tsx
yarn.lock

Adds tracking. Snuck in the last Q/A items as well.

feat(dia-1400): about page tracking; remaining q/a items

---

src/Components/Footer/Footer.tsx

Corrects the order of these links

fix(footer): reorders social links

---

src/Apps/Authentication/__tests__/authenticationRoutes.jest.tsx
src/Apps/Components/AppShell.tsx
src/Utils/Hooks/useAuthIntent/index.tsx

Adds tracking for follows that execute after a login/sign up.

feat: adds tracking to follows after auth

---

src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx

fix: order redirect

---

src/Apps/Home/Components/HomeArtworkRecommendationsRail.tsx

Removing `onyx_artwork_recommendations_rail_on_web` feature flag introduced in https://github.com/artsy/force/pull/15837

chore: remove onyx_artwork_recommendations_rail_on_web feature flag

---

src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/__tests__/Order2PaymentForm.jest.tsx
src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx

This PR solves [EMI-2695]
[EMI-2695]: https://artsyproduct.atlassian.net/browse/EMI-2695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2695): rename 'Save and Continue' to 'Continue to Review'

---

src/Apps/Articles/AuthorApp.tsx
src/Apps/Articles/Components/AuthorArticlesGrid.tsx
src/__generated__/AuthorApp_author.graphql.ts
src/__generated__/AuthorArticlesGridPaginationQuery.graphql.ts
src/__generated__/AuthorArticlesGridQuery.graphql.ts
src/__generated__/AuthorArticlesGrid_query.graphql.ts
src/__generated__/articlesRoutes_AuthorQuery.graphql.ts

This adds 'Show More'-style pagination to the author articles grid.

feat(dia-1419): articles by author pagination

---

.circleci/config.yml

Fixes env not being set correctly for the live smoke tests.

fix(e2): env for live smoke tests

---

src/Utils/Hooks/useLoadScript.ts

revert: add error tracking to useLoadScript for debugging "Load failed" errors

---

src/System/Utils/setupSentryClient.ts

revert: temporarily disable Sentry denyUrls to debug "Load failed" errors

---

src/System/Utils/setupGlobalErrorHandlers.ts

After deploying #15957, #15958 and #15963 to debug "Load failed" errors, we discovered:
- "TypeError: Load failed" errors are still occurring
- Our targeted error handlers aren't catching them
- The errors show `mechanism: onunhandledrejection` but bypass our network-related filters
This PR implements a temporary debugging enhancement that:
- Catches ALL unhandled promise rejections (not just network-related ones)
- Captures comprehensive error context including error type, constructor, stack trace, and serialized object data
Transform vague errors like:
```
TypeError: Load failed
mechanism: onunhandledrejection
(no context)
```
Into detailed errors with full context:
```
source: "all_unhandled_rejections"
reasonMessage: "TypeError: Load failed at XMLHttpRequest..."
stack: [complete stack …
```

chore: catch all unhandled promise rejections to debug "TypeError: Load failed" errors

---

src/System/Utils/setupGlobalErrorHandlers.ts

revert: catch all unhandled promise rejections to debug "TypeError: Load failed" errors

---

src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx

This PR solves [EMI-2774]
This fixes the saved SEPA flow.
https://github.com/user-attachments/assets/7c901945-df92-406a-9118-88208c7f186c
[EMI-2774]: https://artsyproduct.atlassian.net/browse/EMI-2774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2774): use correct SEPA type

---

.gitignore

fix: change .gitignore to track claude.local.md

---

src/Apps/About2/Components/AboutOurTeam.tsx

|-|-|
| <img width="2434" height="3202" alt="www artsy net_about2" src="https://github.com/user-attachments/assets/17ed5263-cfca-4a7d-912f-353b9765e8bc" /> | <img width="2434" height="3100" alt="localhost_4000_about2" src="https://github.com/user-attachments/assets/21e61234-90c4-4812-bb68-3d0d3815d8ee" /> |
| <img width="1050" height="5772" alt="www artsy net_about2(iPhone 12 Pro)" src="https://github.com/user-attachments/assets/1d76023b-0f82-44f8-8692-b219ca9a1c56" /> | <img width="1050" height="5190" alt="mobile" src="https://github.com/user-attachments/assets/9fe9c98f-db67-4adb-b745-30e80377b5e9" /> |
cc: @artsy/diamond-devs

chore(DIAM-4): update Our Team section on About page

---

src/Apps/About2/Components/AboutOurTeam.tsx

| Mobile | Desktop|
|-|-|
| <img width="1050" height="5190" alt="localhost_4000_about2(iPhone 12 Pro)" src="https://github.com/user-attachments/assets/60977f9f-2847-44ad-a7bc-8ba633ba4239" /> | <img width="2514" height="3060" alt="localhost_4000_about2" src="https://github.com/user-attachments/assets/a54f7bd4-0ab2-4483-a1c2-6c4aad6e88b4" /> |
cc: @artsy/diamond-devs

fix(DIAM-4): tweak Our Team section on About page

---

src/Apps/Article/Components/ArticleBody.tsx
src/Apps/Article/Components/ArticleHero.tsx
src/Apps/Article/Components/__tests__/ArticleBody.jest.tsx
src/Components/CommaList.tsx
src/__generated__/ArticleBody_article.graphql.ts
src/__generated__/ArticleBody_test_Query.graphql.ts
src/__generated__/ArticleHeroStoryQuery.graphql.ts
src/__generated__/ArticleHero_article.graphql.ts
src/__generated__/ArticleInfiniteScrollQuery.graphql.ts
src/__generated__/NewsIndexArticlesQuery.graphql.ts
src/__generated__/articleRoutes_ArticleQuery.graphql.ts
src/__generated__/articlesRoutes_NewsQuery.graphql.ts

This launches the author pages by linking the author names.

feat(diam-50): link to new author pages

---

.circleci/config.yml

Follow up to https://github.com/artsy/force/pull/16150/files#r2363573722.

fix(diff): Use merge-base to find lock changes

---

package.json
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutWork.tsx
yarn.lock

Had to manually update due to a small breaking change. See: https://github.com/artsy/palette/pull/1473

chore(deps): upgrades palette
