artsy/force

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksModal.tsx
src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksModalHeader.tsx
src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksModal.jest.tsx
src/System/i18n/locales/en-US/translation.json

The type of this PR is: FIX
This PR solves [ONYX-274](https://artsyproduct.atlassian.net/browse/ONYX-274)
Update copy and add artistName to the Suggested Artworks modal title.
[ONYX-274]: https://artsyproduct.atlassian.net/browse/ONYX-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-274): update copy for title and sugested artworks modal

---

src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx

Addresses [ONYX-283]
This fixes the scroll bug in the Saved Search Alert edit form. There are two nested scroll views. The issue is that the user cannot scroll to the end of the form component when focusing on the form scroll view.
[ONYX-283]: https://artsyproduct.atlassian.net/browse/ONYX-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Alert edit form scroll bug

---

src/Apps/Artist/Utils/allowedAuctionResultFilters.ts

I noticed when including `saleEndYear` and `saleStartYear` as url params, that we were sending  to Metaphysics string as parameter from these variables.
This PR remove the argument support

fix: remove sale year params

---

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx

Follow-up to #12817 ([ONYX-278](https://artsyproduct.atlassian.net/browse/ONYX-278))
Adds a contextModule analytics attribute to the ShelfArtwork component used in the new closed lot create alert header.
cc/ @tam-kis 
[ONYX-278]: https://artsyproduct.atlassian.net/browse/ONYX-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(analytics): add contextModule to ShelfArtwork used in closed lot header

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx

This PR adds missing padding to Alert list header on mobile.
| --- | --- |
|<img width="479" alt="Screenshot 2023-08-31 at 16 20 39" src="https://github.com/artsy/force/assets/4691889/d46077c7-c72a-44e0-a6b2-228385cf9b24"> | <img width="477" alt="Screenshot 2023-08-31 at 16 20 20" src="https://github.com/artsy/force/assets/4691889/82c7f235-e072-4e6c-a3bf-751ac83988c4">|
Add padding to Alert list header on mobile.

fix: Add padding to Alert list header on mobile

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx

Addresses [ONYX-281]
Prevent Alert list item name text overflow.
| --- | --- |
| <img width="396" alt="Screenshot 2023-09-01 at 10 05 55" src="https://github.com/artsy/force/assets/4691889/83d7ea69-5878-4be4-9edc-0f6d1353297c">| <img width="393" alt="Screenshot 2023-09-01 at 10 04 09" src="https://github.com/artsy/force/assets/4691889/6d3fe10f-1a68-4131-84d4-e6715449ad7d">|
[ONYX-281]: https://artsyproduct.atlassian.net/browse/ONYX-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Prevent Alert list item name text overflow

---

src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/SaleEndYearFilter.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.jest.tsx

I noticed in the [datadog](https://app.datadoghq.com/apm/services/force/operations/express.request/resources?env=production&graphType=flamegraph&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Aavg%29%2CtopN%3Aall%2CselectedResourceID%3A109c96c4c4c2f7%29%2Cversion%3A%210%29&shouldShowLegend=true&sort=time&spanID=8951849862372371502&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&timeHint=1693570959744&topGraphs=late …

chore: do not render sale end year filter when no options available

---

src/Apps/Artist/Routes/AuctionResults/SingleAuctionResultPage/__tests__/AuctionResult.jest.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResultItem.jest.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkAuctionRegistrationPanel.jest.tsx
src/Apps/CollectorProfile/Components/CollectorProfileHeader/Components/__tests__/CollectorProfileHeaderAvatar.jest.tsx
src/Apps/CollectorProfile/Components/CollectorProfileHeader/Components/__tests__/CollectorProfileHeaderInfo.jest.tsx
src/Apps/CollectorProfile/Components/CollectorProfileHeader/__tests__/CollectorProfileHeader.jest.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/__tests__/MyCollectionArtworkImageBrowser.jest.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebar.jest.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkArtistMarket.jest.tsx
src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx
src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/__tests__/CareerHighlightModalStep.jest.tsx
src/Apps/Settings/Routes/Insights/Components/CareerHighlights/__tests__/InsightsCareerHighlightRail.jest.tsx
src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsMedianSalePrice.jest.tsx
src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsOverview.jest.tsx
src/Components/Artwork/__tests__/GridItem.jest.tsx
src/Components/Artwork/__tests__/Metadata.jest.tsx
src/Components/SavedSearchAlert/Components/__tests__/ConfirmationStepFooter.jest.tsx
src/DevTools/setupTestWrapper.tsx

This PR solves [EMI-1413](https://artsyproduct.atlassian.net/browse/EMI-1413)
Inspired by @erikdstock's [spike](https://github.com/artsy/force/compare/erik.SPIKE-shipping-react-testing-library-spike), I realized a need, while working on [EMI-1413](https://artsyproduct.atlassian.net/browse/EMI-1413), to support passing in a relay environment to the [`renderWithRelay`](https://github.com/artsy/force/blob/68a4a6139e1e666818b6581b29e4abdd8ffb6ffb/src/DevTools/setupTestWrapper.tsx#L86-L90) helper, to avoid handling multiple relay environments in tests. The existing [`manualEnvControl`](https://github.com/artsy/force/blob/68a4a6139e1e666818b6581b29e4abdd8ffb6ffb/src/DevTools/setupTestWrapper.tsx#L88) boolean is not able to support this.
This PR replaces the …

refactor: support passing in a relay env to `renderWithRelay` test helper

---

src/Server/__tests__/getContextPage.jest.ts
src/Server/getContextPage.ts
src/System/Analytics/AnalyticsContext.tsx
src/System/useFeatureFlag.tsx

Paired on this with @TMcMeans, if we've missed some critical consideration or otherwise don't want to merge that it's totally ok.
Following up on [https://github.com/artsy/force/pull/12776](https://github.com/artsy/force/pull/12776/files#diff-91d000540513622973ef9d699e2cfd5ae4444c21ef601128c970314655d42f5eR113-R117), which fixed and refactored a lot of our analytics context, this PR:
- migrates the `OwnerType orders was not part of @artsy/cohesion's schema` messaging to our `useMemo` hook where it is set
- removes references to a deprecated method that did an earlier version of the same thing
- fixes a bug in our alerting code which was testing the keys rather than the values of the OwnerType enum.

Migrate alerting for missing OwnerTypes into refactored AnalyticsContext

---

src/Components/Address/__tests__/useAddressAutocomplete.jest.ts
src/Components/Address/useAddressAutocomplete.ts

This PR solves [EMI-1448]
The goal of this PR is to wrap up the tests for the autocomplete hook. I have one test that is currently skipped while there is still conversation with design on debouncing/throttling calls to the Smarty API while the user key inputs. 
[EMI-1448]: https://artsyproduct.atlassian.net/browse/EMI-1448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-1448): wrap up tests for address autocomplete hook

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateArtworkAlert.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCreateArtworkAlert.jest.tsx

This PR solves [ONYX-275]
Prevents the creation of alerts from artwork pages when the artwork has no associated artists.
Auction artworks were [already doing](https://github.com/artsy/force/blob/156b302c328600c704360e4998168c1a72186d44/src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBiddingClosedMessage.tsx#L24) the right thing. So this addresses the non-auction case, which solves this issue for other susceptible works, such as museums‘ permanent collection artworks —
|Before|After|
|---|---|
|<img width="1392" alt="before" src="https://github.com/artsy/force/assets/140521/71d37862-40ca-4c49-a4d9-6f9505de47bb">|<img width="1392" alt="after" src="https://github.com/artsy/force/assets/140521/40ee5b2c-eabd-4202-90e1-a6caaa1cc4d2">|
[GRO-434]: …

fix(alerts): prevent artwork alert creation when there are no artists

---

src/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistList.tsx

Fixes an issue a partner noticed around how we were organizing the partner artists page. Before we were dynamically sorting, but now we're ensuring that Represented Artists is always at the top

fix(partner): Ensure represented artists are always aat the top

---

src/Apps/Order/Components/PriceOptions.tsx

This PR solves [EMI-1342]
This PR fixes the double-jumping that happens in the offer screen in Safari iOS (tested with Safari mobile view and it works fine)
|---|---|
| <video src="https://github.com/artsy/force/assets/20655703/552c60aa-7492-41c4-8e1d-0b17dd56b089" /> | <video src="https://github.com/artsy/force/assets/20655703/3a6a69e8-8edd-4d1a-a416-2f3e4d7c6532" />	 | 
[EMI-1342]: https://artsyproduct.atlassian.net/browse/EMI-1342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-1342): jumping issue on iPhones in Offer page

---

src/Apps/Order/Routes/Review/index.tsx

Our tracking data shows that users are seeing the generic "Something went wrong..." error message while attempting to submit orders. We have been able to map some occurrences of these to errors raised in Exchange, but there is still a fair number of occurrences that do not correspond to any logged errors in Exchange.
This PR aims to give us some more breadcrumbs when investigating these occurrences by logging the error that causes them inside the tracking event. Previously we had hoped that an error code would be available, but these have mostly been blank.

chore: add deadend breadcrumbs to review route

---

src/Apps/Order/Routes/Accept/index.tsx
src/__generated__/AcceptOfferMutation.graphql.ts

This PR solves [EMI-151]
This is part 1 of handling Stripe's 3DS flow consistently. For more context, please see https://artsyproduct.atlassian.net/browse/EMI-151
[Part two](https://github.com/artsy/exchange/pull/1787) will allow us to remove the unnecessary code in a followup PR.
Relates to https://github.com/artsy/force/pull/12744
[EMI-151]: https://artsyproduct.atlassian.net/browse/EMI-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-151): handle 3DS flow consistently

---

package.json
src/Components/Address/__tests__/useAddressAutocomplete.jest.ts
src/Components/Address/useAddressAutocomplete.ts

This PR solves [EMI-1459]
The goal of this PR is to change the usage of debounce to implementing Lodash's throttle function in the `useAddressAutocomplete` hook to stagger multiple query requests to the Smarty API on user key press.
Note: Thoroughly testing the throttle's behavior was challenging. Although Lodash's throttle can use `setTimeout`, it also employs timestamps for finer control over function execution. This makes it less straightforward to mock using Jest's timer mocks, which are primarily designed to work with `setInterval()` and `setTimeout()`.
[EMI-1459]: …

fix(EMI-1459) use throttle instead of debounce for address autocomplete

---

src/Apps/Order/Routes/Payment/index.tsx

This PR is related to #12870.
Our tracking data shows that users are seeing the generic "Something went wrong..." error message while attempting to submit the Payment step. We have been able to map some occurrences of these to errors raised in Exchange, but there is still a fair number of occurrences that do not correspond to any logged errors in Exchange.
This PR aims to give us some more breadcrumbs when investigating these occurrences by logging the error that causes them inside the tracking event. Previously we had hoped that an error code would be available, but these have mostly been blank.

chore: add deadend breadcrumbs to payment route

---

src/Apps/Search/Components/ZeroState.tsx

Fixes "No results found for" message on the search page. Before it had an extra space between search term's quotation marks.
|---|---|
| ![Screenshot 2023-09-18 at 13 11 09](https://github.com/artsy/force/assets/3934579/01d443d1-3058-4b97-980f-45a768d76db7) | ![Screenshot 2023-09-18 at 13 11 16](https://github.com/artsy/force/assets/3934579/e5ad9b68-8046-401a-852a-620e37ea7d67) |

fix: fixes no results message on search page

---

src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
src/Components/__tests__/Utils/addressForm.ts

This PR solves [EMI-1413](https://artsyproduct.atlassian.net/browse/EMI-1413)
Following https://github.com/artsy/force/pull/12867, this promotes the `fillAddressFormTL` helper because the Enzyme ``fillAddressForm` helper is now unused.
[EMI-1413]: https://artsyproduct.atlassian.net/browse/EMI-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: promote `fillAddressFormTL` helper

---

src/Apps/NewWorksFromGalleriesYouFollow/NewWorksFromGalleriesYouFollowApp.tsx

Jira Ticket: [ONYX-45]
More Context: https://artsy.slack.com/archives/C05EQL4R5N0/p1694165141999769?thread_ts=1694095496.316869&cid=C05EQL4R5N0
This PR adjusts the artwork grid details for "New Works from Galleries You Follow" to match other artwork grids. I accidentally copy-pasted the props from the My Collection artwork grid, which doesn't display all the details.
| --- | --- |
|<img width="893" alt="Screenshot 2023-09-13 at 11 46 55" src="https://github.com/artsy/force/assets/4691889/20e5d597-c2ca-4ce2-9885-bcd9ae37dbd2"> |<img width="897" alt="Screenshot 2023-09-13 at 11 46 47" src="https://github.com/artsy/force/assets/4691889/e8af72d8-c356-4784-8efe-be14458790fc"> |
[ONYX-45]: https://artsyproduct.atlassian.net/browse/ONYX-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …

fix: Adjust `New Works from Galleries you follow` artwork grid details

---

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultsRoute.tsx
src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
src/__generated__/ArtistAuctionResultsQuery.graphql.ts
src/__generated__/ArtistAuctionResultsRoute_artist.graphql.ts
src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts
src/__generated__/ArtistAuctionResults_artist.graphql.ts
src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts

This PR solves [DIA-106]
This PR uses new `LOTS_BY_CREATED_YEAR` aggregation from diffusion (filters endpoint).
[DIA-106]: https://artsyproduct.atlassian.net/browse/DIA-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: use aggregation for lots by year created filter

---

src/Apps/Order/Routes/__tests__/Shipping.jest.tsx

Reported on [Slack](https://artsy.slack.com/archives/C2TQ4PT8R/p1695298550790839), shipping tests sometimes time out on CI (> 5 seconds). [Previous attempt](https://github.com/artsy/force/pull/12867/commits/a5782ec99010954c22cfc6d2b5abeff0632e601e) to improve the performance is not sufficient.
To unblock the `main` branch/deployment, this tentatively increases the timeout _only_ for that particular file while I look into more performance improvements.

test: set a longer timeout for shipping tests tentatively

---

src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
src/Components/Address/AddressForm.tsx
src/Components/Address/__tests__/useAddressAutocomplete.jest.ts
src/Components/Address/useAddressAutocomplete.ts
src/Components/__tests__/Utils/addressForm.ts

This PR resolves [EMI-1457] by adding a brief loading state to the autocomplete input. While loading (and server-side) the address form renders the input, but disabled, then swaps it out if autocomplete is not available. This has the effect of making the 🔎  disappear, a small papercut and possible followup in palette.
[EMI-1457]: https://artsyproduct.atlassian.net/browse/EMI-1457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: EMI-1457 - show autocomplete input by default so hidden element styles are applied properly

---

src/Apps/Order/Components/AddressVerificationFlow.tsx

This PR solves [EMI-1425]
This PR adds `addressVerificationModal` as data-test to address verification modal so it can be picked up by Integrity
[EMI-1425]: https://artsyproduct.atlassian.net/browse/EMI-1425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1425): Add `addressVerificationModal` to address verification modal

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx

This PR updates the cocktail of booleans that we use to show and hide things in the new ArtistHeader component. I added a new boolean that indicates whether we have a third column - could be because we have gallery reps or could be because we have insights or both!
Then I just updated a few call sites to use that instead. I checked with a couple artists to verify that rendering works as expected:
<details><summary>screenshots</summary>
</details> 
https://artsyproduct.atlassian.net/browse/DIA-173

fix: Show artist gallery reps even without insights DIA-173

---

src/Components/Address/__tests__/useAddressAutocomplete.jest.ts
src/Components/Address/useAddressAutocomplete.ts

The type of this PR is: **FEAT**
This PR solves [EMI-1464]
[EMI-1405]: https://artsyproduct.atlassian.net/browse/EMI-1405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMI-1464]: https://artsyproduct.atlassian.net/browse/EMI-1464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1464): fill/clear all inputs when selecting new address

---

src/Components/Address/AddressForm.tsx

This PR solves [EMI-1478]
The goal of this PR is to disable flipping so that autocomplete suggestions should always appear below the input. I've tested this on mobile web and it seems to work as intended so far. 
Description in the QA doc [here](https://www.notion.so/artsy/In-the-app-the-address-results-appears-above-address-field-making-it-hard-to-read-and-disappears-if-9d61d732e97644f99594310c67d82a1d?pvs=4) and discussion about the 1-line fix [here](https://artsy.slack.com/archives/C2TQ4PT8R/p1695038670638129?thread_ts=1694615187.242149&cid=C2TQ4PT8R).
[EMI-1478]: …

fix(EMI-1478): disable flip on autocomplete input

---

src/Apps/Order/Routes/__tests__/Shipping.jest.tsx

In https://github.com/artsy/force/pull/12898#discussion_r1330888144, we suspected the mock was not cleared properly which caused the leaky tests issue. This PR verified it and fixed it by resetting the particular mocked commit mutation.
cc @artsy/emerald-devs

Fix leaky tests

---

src/Components/Search/NewSearch/constants.ts

This PR solves [ONYX-359]
The ‘Sale' pill is called ‘Auction’ in the app. In this PR we align the naming between the app and web.
[ONYX-359]: https://artsyproduct.atlassian.net/browse/ONYX-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(onyx-359): Rename the 'Sale' pill to 'Auction'

---

src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
src/__generated__/SettingsEditSettingsInformation_Test_Query.graphql.ts
src/__generated__/SettingsEditSettingsInformation_me.graphql.ts
src/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
src/__generated__/useUpdateSettingsInformationMutation.graphql.ts

Doesn't yet persist the country code selected but it does use it for async client-side validation.
Note that I'm planning a follow-up iteration of this which would also pass a `phoneNumberCountryCode` value to the backend for more robust validation ([Gravity PR](https://github.com/artsy/gravity/pull/16875) / 🔒 )
https://github.com/artsy/force/assets/123595/4619d656-e270-457b-ab94-e7a029df0dda
**No number persisted yet, form is still valid**
---
**Form becomes invalid if invalid number is entered or user tries to submit a form with an invalid number previously persisted**
---
**Client-side validation detects country code / regional number mismatches**

feat: add structured phone input to User > Account Settings

---

src/Apps/Search/Routes/SearchResultsArtworks.tsx

This PR solves [ONYX-396]
Steps to reproduce:
- Type "kaws" in search input, press enter
- Type "warhol" in search input, press enter
- Under artworks grid, click on the "next" link
Outcome before this fix:
- Kaws's artworks are displayed in the grid
Expected outcome:
- Warhol's artworks should be displayed
[ONYX-396]: https://artsyproduct.atlassian.net/browse/ONYX-396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(onyx-396): fixes search pagination issue when previous search results appear

---

src/Components/Address/AddressForm.tsx
src/Components/Address/__tests__/AddressForm.jest.tsx

This PR clears the line 1 input and resets suggestions when clearing the autocomplete. I added a test for it, but then marked it with `it.skip` because I could not get the behavior to work in the test. I'll try a bit more, but it does work in manual testing:
Fixes [EMI-1469]
<details><summary>Demo</summary>
</details> 
[EMI-1469]: https://artsyproduct.atlassian.net/browse/EMI-1469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix [EMI-1469]: clear addressLine1 when clearing autocomplete

---

src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx

Small follow-up to #12933 
We don't require a phone number when a user updates their account information so we shouldn't use this required indicator. Mistakenly added in [force#12933][].
[force#12933]: https://github.com/artsy/force/pull/12933
| <img width="978" alt="Screenshot 2023-09-26 at 17 33 13" src="https://github.com/artsy/force/assets/123595/dc02b95a-8a8f-4d5e-80b3-35c63d1a5bb7"> | <img width="965" alt="Screenshot 2023-09-26 at 17 34 22" src="https://github.com/artsy/force/assets/123595/868b2dad-b05b-43bb-b90e-c5addc070002"> |

feat: remove required asterisk from account settings phone input

---

src/Apps/Shows/Routes/ShowsCity.tsx

This PR extracts a couple locals to help us control when we show various elements of the city page for shows. The city slug does double-duty here and can be the string `online` - when this is the case we want to suppress the first part of the page.
<details><summary>screenshots</summary>
</details> 
https://artsyproduct.atlassian.net/browse/DIA-98

chore: Suppress opening section for online show page DIA-98

---

src/Apps/Order/Routes/__tests__/Shipping.jest.tsx

This PR solves [EMI-1413](https://artsyproduct.atlassian.net/browse/EMI-1413)
This adds tests to the shipping step for address verification flow. They might feel more like integration tests but given the number of regressions we saw in developing address verification, we think it's still important to cover the major flows.
The expanded test cases are:
```
Shipping
with partner shipping
with no saved address
address verification
with US enabled and international disabled
✓ uses recommended address
✓ goes back and edits address after verification
with Artsy shipping
with no saved address
address verification
with US enabled and international disabled
✓ uses recommended address
✓ goes back and edits address after verification
```
cc @artsy/emerald-devs …

Add address verification tests

---

scripts/start.sh

This (attempts) to fix our pipeline to prevent relay errors from slipping in by checking for errors in commands and then exiting. If relay isn't working, we should immediately fail so that devs can fix their relay command. 
Not sure if this is the best fix, but lets give it a shot and see if it doesn't create more problems.

fix(start): Add --kill-all to exit when something errors out

---

src/Apps/Articles/ArticlesApp.tsx
src/Apps/Articles/Components/ArticlesIndexNews.tsx
src/__generated__/ArticlesApp_viewer.graphql.ts
src/__generated__/ArticlesIndexNews_viewer.graphql.ts
src/__generated__/articlesRoutes_ArticlesQuery.graphql.ts

Closes [DIA-136](https://artsyproduct.atlassian.net/browse/DIA-136)
News is back and this brings back the news module on the articles index page.
The layout here is the one that Ryan tweaked [in this thread.](https://artsy.slack.com/archives/C05EEBNEF71/p1695816773386229)
[DIA-136]: https://artsyproduct.atlassian.net/browse/DIA-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
-----

feat(articles): adds news module to top of page

---

src/Apps/Articles/ArticlesApp.tsx
src/Apps/Articles/Components/ArticlesIndexArticle.tsx

This adds some additional markup to differentiate links to main articles with links to news articles. There is an Integrity spec which tries to load an article with an ad on it. News doesn't contain ads so this is now failing since the first links are news articles.
Added h1, h2, h3 tags while I'm at it.

feat(articles): adds h-tags and testid

---

src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx

This PR adds an invisible change to the artist page by adding a couple meta tags. It uses a feature I setup in Unleash so that we could do a dry run of testing for the horizontal filters. The idea is to let this sit on production for a bit and then we can verify that the data we want to analyze is flowing through the data pipeline as expected.
/cc @artsy/diamond-devs @leodmz

feat: Dry run of testing horizontal filters

---

src/Components/Address/AddressForm.tsx
src/Components/Address/__tests__/AddressForm.jest.tsx
src/Components/Address/__tests__/useAddressAutocomplete.jest.ts
src/Components/Address/useAddressAutocomplete.ts

This PR makes the secondary suggestion feature of our autocomplete hook disabled by default. The reasoning here is that we need a strategy for handling apartment/unit/suite information in a [more specific way than "address line 1/2"](https://www.smarty.com/articles/address-line-2-meaning), and until then this experience will give a bad UX when automatically filling suggestions.
Change
The change is to disable this functionality in the hook unless it receives a specific parameter. We can turn this back on and refine it later.
User facing changes unless the secondary suggestions are explicitly enabled:
- No more `(3 entries)` when an address has sub-entries.
- Secondary information that doesn't rest in a nested entries like above is stripped out. This way we won't autofill that input (they …

feat [EMI-1480]: disable autocomplete secondary suggestions by default

---

src/Components/Address/AddressForm.tsx

This PR completes [EMI-1494] by disabling address autocomplete on the billing page. This is a minor launch-blocker that we will revisit in EMI-1485 (linked to that ticket with some investigation details there)
#minor 
[EMI-1494]: https://artsyproduct.atlassian.net/browse/EMI-1494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore [EMI-1494]: disable autocomplete on billing page

---

src/Apps/Components/Layouts/index.tsx
src/System/Router/RenderStatus.tsx
src/System/Router/buildClientApp.tsx
src/System/Router/loadingIndicatorMiddleware.ts
src/System/SystemContext.tsx

This addresses a long-standing and difficult to fix issue involving very unacceptable UX layout jank when transitioning between routes that have different route layouts. 
**The problem:**
- User navigates to an artwork page, with a default layout
- User clicks "Make Offer", which transitions to the Order app, with a `LogoOnly` layout
- Immediately upon click, the page layout changes and the logo-only appears, but the main content stays because the page is still fetching the query
- When fetch is done, main content updates to the latest
I've attempted to fix this about 20 times! But ran into it yet again today while working on migrating convos work from V2 over to force and thought I'd give it another shot. 
**The solution**
- Globally export the …

fix(router): Ensure page transitions execute only when page is fully done loading 

---

src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetailsAdditionalInfo.jest.tsx

From Sam: “can you please add a tracking event to the "Read more" of the various sections on the lot page? It's a very helpful signal to be able to reach back out to the collectors for Matchmaking and these tracking events are currently missing from the page (see thread linked in [#data-team](https://artsy.slack.com/archives/C0KEQD4B0)).I'm hoping that it's a fairly easy change. Please confirm when you'll be able to slot that in.“
https://artsy.slack.com/archives/C05F8TNKGAV/p1695067295001329 
Original thread: https://artsy.slack.com/archives/C0KEQD4B0/p1695063167749489
[AMBER-227]: https://artsyproduct.atlassian.net/browse/AMBER-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

tracks clicks to read more link

---

src/tests.ts

This updates our RTL testing lib to hide HTML test output on failed tests by default. Reasoning: 
- HTML output is almost always truncated except for in the shortest of components. This makes things not too helpful
- It makes tracking down tests in large files difficult, because the terminal is getting spammed with unhelpful output
- It severely hampers CI output for failed tests. Not only is the CI window frequently truncated entirely (due to output being exceeded), but again, it makes figuring out which tests are failing ever more difficult 
With this disabled, we still get nice RTL hints for failures which _are_ useful. We also get proper stack traces. AND we get our quick-look overviews back, which were hidden due to all of the RTL output. 
If we want …

chore(tests): Hide RTL html output on failed tests by default

---

src/Components/SavedSearchAlert/useUserPhoneNumber.tsx
src/__generated__/useUserPhoneNumberQuery.graphql.ts

Turns out that there is a parsed phone display field without the country code! So we can try to display that, with a fallback to the original number if it's not a valid number to start with.

fix: display formatted phone w/o country code if possible for adv oppty

---

.env.example
package.json
src/tests.ts

Welcome to the bike shed  🚲 🏠  🎨🖌️  
Follow-up to https://github.com/artsy/force/pull/12984 which kicked off a discussion about the detailed output of React Testing Library.
This PR:
- retains the quieter output configured above^ when running in CI
- allows developers to opt-in to this behavior locally via env var, rather than making it the default
- adds `yarn jest:terse` so you don't have to remember the env var
See [this comment thread](https://github.com/artsy/force/pull/12984#discussion_r1346424738), and particularly the output [examples here](https://github.com/artsy/force/pull/12984#discussion_r1346458121) to see my reasoning for this change.

feat(devx): allow configurability of RTL output level

---

src/Apps/Order/Routes/Review/index.tsx
src/Apps/Order/Routes/__tests__/Review.jest.tsx

This PR solves [EMI-1335]
Add a more meaningful error message when buyers are trying to submit an order with a deactivated credit card.
Before
After
[EMI-1335]: https://artsyproduct.atlassian.net/browse/EMI-1335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1335): add error msg for credit_card_deactivated

---

src/Components/Address/AddressForm.tsx

The type of this PR is: Fix.
This PR is a followup to #12978 which had an error in its control flow logic. I failed to write a failing test for it which might be fixable if we add a queryable parameter to palette's autocomplete input. (Fixes [EMI-1494])
It also fixes the flash of magnifying glass while the input is loading in cases where it is disabled (Fixes [EMI-1504])
Updated view showing the autocomplete input is not rendered on the credit card form.
<details><summary>Fix for flash of autocomplete 🔍 before it is disabled.</summary>
</details> 
#minor
[EMI-1494]: https://artsyproduct.atlassian.net/browse/EMI-1494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMI-1504]: https://artsyproduct.atlassian.net/browse/EMI-1504?atlOrigin=eyJpIjoiNW …

fix: Disable autocomplete on billing page.

---

src/Components/SavedSearchAlert/Components/SavedSearchAlertPills.tsx

A simple thing but: making some updates to the `Pill` components for consistency. `selected` isn't a distinct state but can stack with the other states. In the case of the `filter` variant; the idle state and selected state are the same. Idle should lack the `x` icon and it will be removed. This is the one case in which it's needed.

fix(filter): includes selected prop

---

src/Components/CookieConsentManager/useConsentRequired.ts
src/System/Relay/createRelaySSREnvironment.ts
src/Utils/getTimeZone.jest.ts
src/Utils/getTimeZone.ts

This PR fixes an issue where multiple users in Seoul where not able to access artsy.net due to Timezone being returned as `undefined`. This seems to be a fresh issue affecting some chrome versions and I expect it to be solved in few weeks. 
Review app link: fix-broken-artsy-app-in-seoul.artsy.net

fix: get timezone from luxon when Intl timezone is undefined [WIP]

---

src/Apps/Order/Components/OfferInput.tsx
src/Apps/Order/Components/__tests__/OfferInput.jest.tsx

This PR solves https://artsyproduct.atlassian.net/browse/EMI-1378
- Use thousand separator for the offer input
Extra: Use numeric input mode to trigger number keyboard in mobile, instead of the full qwerty keyboard
https://github.com/artsy/force/assets/7518671/bb962fc2-f167-40bf-b194-8c22b9c9c5af

feat(EMI-1378): use thousand separator for offer input

---

src/Apps/Order/Components/OfferInput.tsx
src/Apps/Order/Routes/Offer/index.tsx
src/Apps/Order/Routes/Respond/index.tsx

Solves https://artsy.slack.com/archives/C03GX7A4KV0/p1697034020143039
Since we're using the value of the OfferInput to properly format and display, we need to make sure that is being passed on by the parent component. This worked for the normal offer flow but it wasn't being set on the rest use cases for that component.
https://github.com/artsy/force/assets/7518671/d4a4b465-4eca-4696-ab94-50dba6c2462c

fix: offer input value

---

src/Components/AuthDialog/Views/AuthDialogLogin.tsx
src/Components/Inquiry/Views/InquiryLogin.tsx

While working on #13011 I noticed we could use the numeric input mode for the auth code, to make the authentication flow easier on mobile web by triggering the numeric keyboard on that input

feat: numeric input mode for auth code

---

src/Components/TransitionPanel.tsx
src/Components/__stories__/TransitionPanel.story.tsx

https://github.com/artsy/force/assets/112297/394dba7d-0514-4d95-835b-7e5b570ff303
The transition animation isn't the hard part here, rather it's maintaining a natural 'order' to the panels. If you're navigating to a new panel from the home, it should be oriented on the right, if you're navigating back then it should be oriented on the left. I support N panels here in the event we need more and they will appear on the left or right depending on their ordering within the provider. You also need to be able to trigger navigation from inside panels so that's where the context provider comes in.
We don't animate changes in modal size. Theoretically we could but this adds a lot more complexity. We may not be adjusting size at all, it turns out. I suspect this will appear a lot less strange when …

feat: implements a transitioning panel

---

src/Components/ArtworkFilter/ArtworkFilterActiveFilters.tsx
src/Components/ArtworkFilter/index.tsx

Re: [DIA-216](https://artsyproduct.atlassian.net/browse/DIA-216)
Closes: [DIA-223](https://artsyproduct.atlassian.net/browse/DIA-223)
This PR restructures our existing layout to match the new mock ups; then adds the new `Clear all` button.
https://github.com/artsy/force/assets/112297/8b256a23-72db-4ea3-a7c5-07876aaf6787
[DIA-216]: https://artsyproduct.atlassian.net/browse/DIA-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DIA-223]: https://artsyproduct.atlassian.net/browse/DIA-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DIA-216,DIA-223): Re-structure existing layout; adds clear all button

---

src/Components/NumericInput.tsx

Closes [DIA-217](https://artsyproduct.atlassian.net/browse/DIA-217)
The bug is that when the price range filter was placed in a `Drawer` component, the `Range` handles would be off/visually missing. I determined that this would only happen when the two `LabeledInput` components were also present. What appears to be happening is that it's something to do with [how we apply padding to prevent overlapping with the label](https://github.com/artsy/palette/blob/382d9289ed1c1ce63f9b535f76673bb38ecf90c5/packages/palette/src/elements/LabeledInput/LabeledInput.tsx#L32), when present within the `Drawer`. Best I can tell it's just an _extremely_ obscure browser rendering bug — but it's not entirely clear to me exactly what's happening.
We can simply fix the issue by just disabling the padding on …

fix(filters): fixes issue with range + labeled input interaction

---

src/Components/ProgressiveOnboarding/withProgressiveOnboardingCounts.tsx

Closes [DIA-234](https://artsyproduct.atlassian.net/browse/DIA-234)
See: https://github.com/artsy/force/blob/cda34a6da2f0e37a190a86be1cc679dfdfb1b55f/src/System/Relay/SystemQueryRenderer.tsx#L77-L78
The query for counts for progressive onboarding is a HOC, which makes this kind of annoying. However, all of these components are above the fold already anyway making `lazyLoad` pointless. So I'm simply removing it, which then fixes the layout shift problem.
[DIA-234]: https://artsyproduct.atlassian.net/browse/DIA-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(progressive-onboarding): removes lazyload to prevent layout shift

---

src/Components/ArtworkFilter/ArtworkFilters/__tests__/KeywordFilter.jest.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter.jest.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/Utils.tsx

Decided to split this from https://github.com/artsy/force/pull/13041#discussion_r1366195014 so that I can get this on `main` and then include it in that PR.
This takes some patterns for working with artwork filters in a react-testing-library friendly way and extracts them into shared helpers.
This was [introduced](https://github.com/artsy/force/pull/7629#discussion_r639742956) in the original RTL spike for the `SizeFilter` spec, [copied over](https://github.com/artsy/force/pull/10379) to the `KeywordFilter` spec and now will be [used](https://github.com/artsy/force/pull/13041/commits/686e2e5ed163b117f6ab35f015c250e604d50f3b) for the `ArtistSeriesFilter` spec as well.
Seems like a good time to extract and document this shareable code.

test: extract shared RTL patterns for artwork filter specs

---

.eslintrc.js
src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilters.jest.tsx
src/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
src/Apps/Artist/artistRoutes.tsx
src/Components/ArtworkFilter/ArtworkFilterContext.tsx
src/Components/ArtworkFilter/ArtworkFilters/ArtistSeriesFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtistSeriesFilter.jest.tsx
src/Components/ArtworkFilter/Utils/__tests__/countChangedFilters.jest.ts
src/Components/ArtworkFilter/Utils/__tests__/getSelectedFiltersCounts.jest.ts
src/Components/ArtworkFilter/Utils/__tests__/urlBuilder.jest.tsx
src/Components/ArtworkFilter/Utils/allowedFilters.ts
src/Components/ArtworkFilter/Utils/isDefaultFilter.tsx
src/Components/SavedSearchAlert/constants.ts

This PR solves [ONYX-442]
Implements a new Artist Series filter and places it behind an Unleash flag (`onyx_enable-artist-series-filter`)
There is also a review app, which does _not_ require anyone to have the flag enabled: https://artist-series-filter.artsy.net/
It's been a while since we added a new facet to the artwork grid. So I came to this like a 👶🏽 and was a little flummoxed by all the wiring that needed to happen. But it appears to work!
https://github.com/artsy/force/assets/140521/f6718503-0994-405b-b0fa-428e35ca2575
[ONYX-442]: https://artsyproduct.atlassian.net/browse/ONYX-442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(artist series filter): add to artist page's artwork grid

---

src/Apps/Search/Components/SendFeedback.tsx
src/__generated__/SendFeedbackSearchResultsMutation.graphql.ts

[FF]
This PR solves https://artsyproduct.atlassian.net/browse/PHIRE-212
We recently added [throttling to the feedback endpoint](https://github.com/artsy/gravity/pull/16958) in order to [resolve a security submission](https://artsyproduct.atlassian.net/browse/PHIRE-212). While testing end to end I noticed that the client was returning a generic message however the server was returning a more descriptive message. This fixes the mutation to extract the returned fields and display the appropriate message.
Before
After

fix: feedback mutation

---

src/Components/CookieConsentManager/CookieConsentManager.tsx

This PR solves [EMI-1336]
Cookie consent banner shows up when opening the checkout flow in the app. Introducing a `isEigen` check to avoid showing it in those scenarios.
Note: I found an Eigen check [in the past implementation](https://github.com/artsy/force/pull/12280/files#diff-62f5fc92583c63dc0ef6698014cb81e6d7db0a22c0bf70bd599482fd876785deL7)
[EMI-1336]: https://artsyproduct.atlassian.net/browse/EMI-1336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-1336): don't show cookie banner for Eigen

---

src/Apps/Collect/collectRoutes.tsx

This PR updates the list of featured categories on the /collect page. It does NOT fix the order of them - that is a change I will make in Gravity. Looks like this:
Note that some of those thumbnails are empty just because staging data doesn't match production.
https://artsyproduct.atlassian.net/browse/DIA-188

chore: Update list of featured categories DIA-188

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
src/Apps/Artist/Routes/WorksForSale/Components/ArtistWorksForSaleEmpty.tsx
src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx
src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/ArtworkAuctionCreateAlertTooltip.jest.tsx
src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksModal.jest.tsx
src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksModalGrid.jest.tsx
src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksShelf.jest.tsx
src/Apps/Artwork/Components/ArtworkCreateAlertButton.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateArtworkAlert.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/Components/SavedSearchAlert/Components/__tests__/ConfirmationModalHeader.jest.tsx
src/Components/SavedSearchAlert/Components/__tests__/SavedSearchCreateAlertButtonContainer.jest.tsx
src/Components/SavedSearchAlert/Utils/__tests__/savedSearchCriteria.jest.ts
src/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
src/Components/SavedSearchAlert/types.ts

This PR related to [ONYX-271].
Follow-up to [#13059][].
As of [#12751][], we no longer rely on an explicitly passed value for an alert's default name, also rendered as a placeholder on the text input. Instead, we query Metaphysics for a default/generated name based on the working alert criteria, which we also show in the input placeholder but no longer persist with the alert. This default/generated name is also used after the alert has been created and stays in sync with any changes to the criteria.
The previous cleanup PR ([#13059][]) removed the feature flag branching logic and this PR follow-ups and removes the `placeholder` attribute from the `SavedSearchEntity` type and any instances of a placeholder passed in elsewhere.
[#13059]: …

chore: cleanup unused default alert placeholder value

---

src/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
src/Components/ArtworkFilter/index.tsx
src/Components/ArtworkFilter/useRevisedArtworkFilters.ts
src/System/useFeatureFlag.tsx

Closes [DIA-226](https://artsyproduct.atlassian.net/browse/DIA-226)
[Variants in Unleash](https://unleash.artsy.net/projects/default/features/diamond_revised-artwork-filters/variants) on this flag are set up as follows:
Production will just need to be enabled to begin running the rollout. How long are we keeping these at 50/50?
[DIA-226]: https://artsyproduct.atlassian.net/browse/DIA-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dia-226): filter experiment set up

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarTitleInfo.tsx

Fixes a bug that was [noted in the bugs and feedback channel](https://artsy.slack.com/archives/C03N12SR0RK/p1698683435339269). 
The issue arose because we were using `!`, which assumes that the code there is always safe. We should never use `!` (we can use `?` instead); but even so, best to guard and exit early.  As a general rule, UI not appearing is (data is null) is better than a crash.

fix(my-collection): Remove non-null assertion crasher

---

.eslintrc.js

Thank you @gkartalis for the suggestion to add this to our `estlint` 🙏 Looking at our eslint file, found that it was disabled, probably due to some migration at some point. Turned it back on!

feat(eslint): Enable no-non-null-assertion rule

---

.eslintrc.js

This relaxes the rule in our tests, since its often helpful to assert in relay test setup (which will never be null).

chore(eslint): relax non-null assertions in tests

---

src/Components/ArtworkFilter/ArtworkFilterDrawer.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick/FilterQuick.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick/PriceRangeFilterQuick.tsx
src/Components/ArtworkFilter/index.tsx

Re: [DIA-295](https://artsyproduct.atlassian.net/browse/DIA-295)
[Q/A board](https://www.notion.so/artsy/14381bc3646e40a6a92ac9b1a0776960?v=6c29026ec39b41b6941567d3a688c589)
This tackles all the issues sans 2:
* When I check “artists you follow,” “Andy Warhol” appears as a filter pill
* This has been in production since perhaps when this feature was introduced.
* Bug with the two instances of the price range filter keeping in sync
* Going to PR that one separately because I do not understand why it's doing what it was doing in the first place.
[DIA-295]: https://artsyproduct.atlassian.net/browse/DIA-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(dia-295): filter q/a

---

src/Apps/Order/Routes/Shipping2/FulfillmentDetails.tsx
src/Apps/Order/Routes/Shipping2/SavedAddresses2.jest.tsx
src/Apps/Order/Routes/Shipping2/SavedAddresses2.tsx
src/Apps/Order/Routes/Shipping2/index.tsx
src/Apps/Order/Utils/useOrderTracking.tsx

This PR solves [EMI-1512]
@erikdstock assigning you as I will be out on Monday. 
This adds a tracking helper for the checkout flow, starting with the new shipping route. We will be adding order tracking calls for all other routes to the helper in follow-up tickets. 
[EMI-1512]: https://artsyproduct.atlassian.net/browse/EMI-1512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1512): add order tracking helper for new shipping route

---

src/Apps/Artist/Routes/Articles/ArtistArticlesRoute.tsx
src/__generated__/ArtistArticlesRouteQuery.graphql.ts
src/__generated__/ArtistArticlesRoute_Test_Query.graphql.ts
src/__generated__/ArtistArticlesRoute_artist.graphql.ts
src/__generated__/artistRoutes_ArticlesQuery.graphql.ts

Prior to his PR we excluded news from the articles being shown on the About tab for an Artist. This removes that exclusion with the intention of showing those news items.
There's more to it though - in addition to removing this filter we _also_ have some examples where we aren't connecting an article with artists. That's not a code question though that's more of an operational question and we'll pursue it with our editorial friends to see what's intentional and what's a mistake.
https://artsyproduct.atlassian.net/browse/DIA-291

feat: Include news in artist articles section DIA-291

---

src/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx

Closes [DIA-306](https://artsyproduct.atlassian.net/browse/DIA-306)
Some really odd behavior in Safari with flex gaps. It winds up being much simpler to use a `Join` here because it requires less knowledge of the child components — If any of them return an empty div or parallel divs for instance, it won't matter since `Spacers` on the `y` axis are margins that collapse.
[DIA-306]: https://artsyproduct.atlassian.net/browse/DIA-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(artist): corrects spacing in safari

---

src/Apps/Artist/Routes/Articles/ArtistArticlesRoute.tsx
src/Apps/Artist/Routes/Overview/Components/ArtistEditorialNewsGrid.tsx
src/Components/ArtistCurrentArticlesRail.tsx
src/__generated__/ArtistArticlesRouteQuery.graphql.ts
src/__generated__/ArtistArticlesRoute_Test_Query.graphql.ts
src/__generated__/ArtistArticlesRoute_artist.graphql.ts
src/__generated__/ArtistCurrentArticlesRailQuery.graphql.ts
src/__generated__/ArtistCurrentArticlesRail_Test_Query.graphql.ts
src/__generated__/ArtistCurrentArticlesRail_artist.graphql.ts
src/__generated__/ArtistEditorialNewsGridQuery.graphql.ts
src/__generated__/ArtistEditorialNewsGrid_Test_Query.graphql.ts
src/__generated__/ArtistEditorialNewsGrid_artist.graphql.ts
src/__generated__/artistRoutes_ArticlesQuery.graphql.ts

Over on https://github.com/artsy/force/pull/13091 I missed places where we were sending this flag and then @dzucconi had the idea that I should just reverse the default and remove this flag altogether.
https://artsyproduct.atlassian.net/browse/DIA-291

feat: Include news in artist overview tab DIA-291

---

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx

Relates to this PR: https://github.com/artsy/force/pull/13092
Removes the [new Alert modal](src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx) from the Auctions closed lot header due to an issue with rendering the modal. This issue will be addressed separately to unblock the current deploy block on Force.
After removing the new alert modal, in this PR:
https://github.com/artsy/force/assets/17580625/f9a59cdf-f4ac-4c25-8448-2d3d24c5998f
With the new alert modal, with modal rendering bug:
https://github.com/artsy/force/assets/17580625/490534b5-0f19-4049-a8b2-9668c1f75d61
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

fix(ONYX-386): remove new artwork alert modal from auctions header

---

src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/PriceRangeFilter.tsx
src/Components/Alert/Components/Form/PriceRange.tsx
src/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick/PriceRangeFilterQuick.tsx
src/Components/PriceRange/PriceRange.tsx
src/Components/SavedSearchAlert/Components/PriceRangeFilter.tsx

Closes [DIA-309](https://artsyproduct.atlassian.net/browse/DIA-309)
The problem we were seeing was that, if you updated the price range within the quick filter dropdown, then opened up the all filters drawer, that price range filter wasn't in sync with the state.
This is because the price range component keeps local state and only sets it based on initial props, not responding to any props updates. We can't make it a controlled component because the artwork filter context is naive, firing off API requests on every change, the slider dragging is chatty, and I have no desire to touch the filter code.
So, this PR:
* Adds an `onDebouncedUpdate` internally to the slider so that we can just use it since that's generally what you want with this type of input
* Responds to external updates to the …

fix(pricerange): respond to external value changes; adds debounced callback

---

src/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
src/Apps/Artist/Routes/Overview/__tests__/ArtistOverviewRoute.jest.tsx
src/__generated__/ArtistOverviewRoute_Test_Query.graphql.ts
src/__generated__/ArtistOverviewRoute_artist.graphql.ts
src/__generated__/artistRoutes_OverviewQuery.graphql.ts

Closes [DIA-311](https://artsyproduct.atlassian.net/browse/DIA-311)
Few issues uncovered here:
* One of the conditions for rendering the empty state was checking for featured artworks, which was removed, so if an artist had any artworks but nothing else, the page would appear empty
* We did not ever wrap any of these sub-components in the empty check which is two problems: unsure what to remove if the sub-components change and we were fetching for _all_ of those sub-components, even when we knew they weren't there. That lead to an inaccurate skeleton state for the page and extraneous requests to Metaphysics.
* The last two components on the page didn't have conditions factored into the empty state, so on artists where we might have related artists + related categories, we wouldn't display …

fix(artist): corrects empty condition; guards on extraneous fetches of subcomponents

---

src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.jest.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx
src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingSaves.jest.tsx

This PR solves [DIA-204]
Removed the logged-in user conditional for the "Save" artwork tooltip, so now it's also visible for logged-out users.
[DIA-204]: https://artsyproduct.atlassian.net/browse/DIA-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(DIA-204): Display save tooltip regardless of logged in status

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
src/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
src/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/ShowMore.tsx
src/Components/ArtworkFilter/ArtworkFilters/index.tsx
src/Components/ArtworkFilter/index.tsx
src/Components/SavedSearchAlert/Utils/extractPills.ts
src/Components/SavedSearchAlert/constants.ts
src/Components/SavedSearchAlert/useActiveFilterPills.ts

Closes [DIA-308](https://artsyproduct.atlassian.net/browse/DIA-308)
Q/A of the filters revealed a very confusing behavior: Checking the "Artists You Follow" checkbox would display one or two artist filter pills. Turns out this is because: we fetch [the first 99 artists you follow](https://github.com/artsy/force/blob/2cc6cd481f3e9838c1c953062facec815bd20b8c/src/Components/ArtworkFilter/Utils/fetchFollowedArtists.ts#L37) — if you follow more than that, sorry. We then just cross reference those with whatever happens to land in the artist aggregations. If you tried to edit this selection it would switch out of this mode, but the counts would be completely wrong because you'd still be sending artist IDs which were then un-toggleable. This is not a useful UX.
This PR changes that behavior to …

fix(DIA-308): implements less confusing "artists you follow" filter behavior

---

src/Apps/Article/Components/ArticleChannelRelatedArticles.tsx
src/__generated__/ArticleChannelRelatedArticlesQuery.graphql.ts
src/__generated__/ArticleChannelRelatedArticles_article.graphql.ts

Closes [DIA-294](https://artsyproduct.atlassian.net/browse/DIA-294)
This component displays articles from the same 'channel.' It's less confusing to use the channel name here over the article byeline.
[DIA-294]: https://artsyproduct.atlassian.net/browse/DIA-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(article): uses channel name; falls back to byline

---

src/Components/Alert/Components/Filters/BaseAlertFilter.tsx
src/Components/Alert/Components/Filters/Medium.tsx
src/Components/Alert/Components/Filters/QuickMultipleSelectAlertFilter.tsx
src/Components/Alert/Components/Filters/Rarity.tsx
src/Components/Alert/Components/Filters/ShowMore.tsx
src/Components/Alert/Components/Filters/__tests__/Medium.jest.tsx
src/Components/Alert/Components/Steps/Filters.tsx

Addresses [ONYX-480]
This PR adds the Medium filter to the new Alert Filter modal.
It also moves the filter logic, which we would probably need to duplicate between the different filters, into a base filter component.
[ONYX-480]: https://artsyproduct.atlassian.net/browse/ONYX-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add Medium Alert Filter

---

src/DevTools/setupTestWrapper.tsx

Following Eigen, this allows for better mutation testing support from directly within our common testing patterns. 
```tsx
it("follows the artist", () => {
const { mockResolveLastOperation } = renderWithRelay({ Artist: () => artist })
fireEvent.press(screen.getByText("Follow"))
mockResolveLastOperation({
Artist: () => ({
isFollowed: true,
}),
})
expect(screen.getByText("Following")).toBeOnTheScreen()
})
it("unfollows the artist", () => {
const { mockResolveLastOperation } = renderWithRelay({
Artist: () => ({
isFollowed: true,
}),
})
fireEvent.press(screen.getByText("Following"))
const { operationName, operationVariables } = mockResolveLastOperation({ 
Artist: () => ({ 
isFollowed: false 
}) 
})
expect(screen.getByText("Follow")).toBeOnTheScreen() …
```

feat(relay-test-utils): Add support for mutations

---

package.json
scripts/setup.sh

As per https://github.com/artsy/README/pull/530, this updates setup to pull shared configuration from its new, simpler location.

chore: simplify S3 path for shared configuration

---

src/Components/Alert/Components/Filters/Color.tsx
src/Components/Alert/Components/Filters/WaysToBuy.tsx
src/Components/Alert/Components/Filters/__tests__/Color.jest.tsx
src/Components/Alert/Components/Filters/__tests__/WaysToBuy.jest.tsx
src/Components/Alert/Components/Steps/Filters.tsx

This PR solves [ONYX-479](https://artsyproduct.atlassian.net/browse/ONYX-479)
Adds Colors and Ways To Buy filters.
https://github.com/artsy/force/assets/17580625/8cd6b0b7-7103-482e-8aeb-d22d1768fbd9
[ONYX-479]: https://artsyproduct.atlassian.net/browse/ONYX-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-479): add color and ways to buy filters

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistWorksForSaleEmpty.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlert.tsx
src/Components/Alert/Hooks/useAlert.tsx
src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx
src/Utils/Hooks/useAuthIntent/index.tsx

Note: this an PR against another feature branch (https://github.com/artsy/force/pull/13129), not main.
Try to handle as much as we can within the hook itself, without relying on passed arguments.

chore(alerts): remove passing of authDialogOptions options to useAlert

---

src/Components/Alert/Components/Modal.tsx
src/Components/Alert/Components/Steps/Details.tsx
src/Components/Alert/Components/Steps/Filters.tsx

cc/ @dariakoko @tam-kis 
- Filters step expands in size a bit from Details
- Remove horizontal scrolling transition (felt a bit buggy on mWeb)
- Adjust padding between Details sections
- "Save alert" > "Create alert"
https://github.com/artsy/force/assets/123595/d3ed0253-5c92-4f16-9c07-830c30d222ec

feat(alerts): small style updates to the new create alert modal

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistWorksForSaleEmpty.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBiddingClosedMessage.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlert.tsx
src/Components/Alert/Components/CreateAlertButton.tsx
src/Components/Alert/Hooks/useAlertContext.tsx
src/Components/Alert/Hooks/useAlertTracking.ts
src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx

This PR solves [ONYX-388](https://artsyproduct.atlassian.net/browse/ONYX-388)
- createdAlert: ToggledSavedSearch
- deletedAlert: DeletedSavedSearch
- clickedCreateAlert: ClickedCreateAlert
Note: this does not yet include analytics events for the new filters flow. That will be covered in a subsequent PR after attribute have been added to artsy/cohesion.
[ONYX-388]: https://artsyproduct.atlassian.net/browse/ONYX-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(analytics): add analytics events to new create alert modal

---

package.json
webpack/envs/clientDevelopmentConfig.js
yarn.lock

This removes the type-checker from our webpack pipeline. We check in a few different ways and this one is particularly noisy.

chore(webpack): Remove fork-ts-checker webpack plugin

---

src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx

The type of this PR is: refactor
This PR updates the wording used next to the App Authenticator 2fa options. It changes "Preferred" to "Recommended" as requested by design in this Slack 🔒 [thread](https://artsy.slack.com/archives/C02BGC5PW/p1699892493938409)

refactor: use recommended instead of preferred for App Auth 2fa

---

src/Apps/Consign/Routes/SubmissionFlow/Utils/redirects.ts
src/Apps/Consign/consignRoutes.tsx

Noticed that the Sell button on /sell page was doing hard jumps between pages, circumventing our SPA router and impacting performance. This was due to the button pointing to a URL which on the server then performs a server-side redirect. Instead, just add a proper route that matches `/sell/submission`. This is to preserve the SEO of having a canonical `sell/submission` link, vs updating the button to point directly at `sell/submission/contact-info`. 
Additionally, this fixes the back button that goes back to contact info, as it currently force redirects you to artwork details, which is confusing. I'm not sure entirely of the history behind this code, but a back button shouldn't ever be subject to redirect rules that prevent one from going back!

fix(sell): fix hard jump between sell and sell/submission, and fix broken back button to /contact-info

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
src/__generated__/SavedSearchAlertListItem_item.graphql.ts
src/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
src/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
src/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
src/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts

This PR solves [ONYX-531]
Alerts that contained artist series criteria were rendering incorrectly in the alerts management area, because stitching 😣 
(Same idea as https://github.com/artsy/eigen/pull/9572)
[ONYX-531]: https://artsyproduct.atlassian.net/browse/ONYX-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(alerts): ensure artist series in previews/pills when managing alerts

---

src/Components/Search/Mobile/SearchResultsList.tsx
src/Components/Search/SearchBarInput.tsx
src/__generated__/MobileSearchBarSuggestQuery.graphql.ts
src/__generated__/OverlayRefetchQuery.graphql.ts
src/__generated__/SearchBarInputRefetchQuery.graphql.ts
src/__generated__/SearchBarInputSuggestQuery.graphql.ts
src/__generated__/SearchBarInput_viewer.graphql.ts
src/__generated__/SearchResultsListPaginationQuery.graphql.ts
src/__generated__/SearchResultsList_viewer.graphql.ts

Closes [DIA-192](https://artsyproduct.atlassian.net/browse/DIA-192)
| --- | --- |
| <img src="https://static.damonzucconi.com/_capture/VHFhOBEodNu5PjElvFf1cspAEwhpQsiVcwZfmZUWzb4zdcafZzS8QusOWtrPH7sXCPtfD0KIIUwTDOPjEzL37RTuaTGHfFAk0NZV.png"> | <img src="https://static.damonzucconi.com/_capture/Rnih1twd72eipTqx0OAKIjKd0SNinjz2IgICTgEizMRvYhJT4iQzSi45s5jKHPfMvN7crjOvmyqb2NaU4V8TOyHeQufiFg5GXlyL.png"> |
So this winds up being the minimal change we can make here. Swapping out the `imageUrl` field for just the artist type winds up being really painful in Metaphysics and of very limited utility. I'm just going to follow up with some deprecations and call this one. We will have to address Eigen separately.
The search could/should be simplified a lot by just switching to use …

fix(search): uses cover artworks for avatar images on artists

---

src/Apps/Search/Components/NavigationTabs.tsx

Noticed the vertical padding was very crammed, this increases it from .5 to 1.
Before: 
https://github.com/artsy/force/assets/236943/132ca184-8a8d-4f22-9543-2808bdc63f1f
After:

chore(search): Increase padding around pills

---

package.json
src/Components/Alert/Components/Steps/Details.tsx
src/Components/Alert/Hooks/useAlertTracking.ts
src/Components/SavedSearchAlert/ConfirmationArtworksGrid.tsx
yarn.lock

This PR solves [ONYX-512]
Added tracking for alerts filters flow
- Add Filters button
- Click on the artwork on the confirmation screen
[ONYX-512]: https://artsyproduct.atlassian.net/browse/ONYX-512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat(ONYX-512): add tracking for alerts filters

---

src/Components/Sticky/Sticky.tsx
src/Components/Sticky/StickyProvider.tsx
src/Components/Sticky/__tests__/StickyProvider.jest.tsx

Some work towards supporting sticky horizontal filters.
This took a moment to wrap my head around — we always want to register all Stickies on initialization, but we need to filter out any that may be "released" due to intercepting a bottom boundary, when getting the top offset.
I'm unable to merge sticky wrapped around the filters though because the drawer isn't actually implemented in a modal fashion (with portal).

fix(sticky): supports proper stacking and release

---

src/Components/Alert/Components/Modal.tsx

[ONYX-533](https://artsyproduct.atlassian.net/browse/ONYX-533)
This PR fixes Alert filter modal overflow background which is broken since [this](https://github.com/artsy/force/pull/13156/files#diff-e2d6453b65cffc01bdde27c288e20b8bfaa3dc5395e48579c9520c066f1eef04L46) change ([PR](https://github.com/artsy/force/pull/13156)).
| --- | --- |
| <img width="396" alt="Screenshot 2023-11-20 at 15 25 15" src="https://github.com/artsy/force/assets/4691889/4b07f8fe-e85f-43f8-96d7-9dc52f6a37d6">| <img width="389" alt="Screenshot 2023-11-20 at 15 25 43" src="https://github.com/artsy/force/assets/4691889/556fab6d-2783-4472-b2cf-9f44876f7d05">|
[ONYX-533]: https://artsyproduct.atlassian.net/browse/ONYX-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …

fix: Alert filter modal overflow background

---

src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
src/Utils/Hooks/useAuthIntent/index.tsx

This PR solves [DIA-327]
This PR syncs the action of saving an Artwork to the progressive onboarding and contains a small fix to show the Follow Artist popover when logged out correctly.
[DIA-327]: https://artsyproduct.atlassian.net/browse/DIA-327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(progressive-onboarding): sync saving artwork logged out

---

src/Components/Alert/AlertProvider.tsx

Guard the after auth intent handling behind the same feature flag so we don't accidentally dispatch both the old and new alert modals.
| Before (double dispatch) | After |
| <video src="https://github.com/artsy/force/assets/123595/939e4a75-a5f0-4df5-b7c5-4c37b0852693" /> | <video src="https://github.com/artsy/force/assets/123595/7bcf08ef-30d3-4ddd-bb42-4e82a51e1cd7" /> |

chore: guard after auth behavior behind same feature flag

---

src/DevTools/README.md
src/DevTools/renderRelayTree.tsx
src/DevTools/setupTestWrapper.tsx

Mark deprecated testing utilities and point to updated docs.
The `@deprecated` comment adds some visual discouragement and a hover note in VSCode. The `[!WARNING]` tag adds a colored alert section in GitHub-flavored Markdown ([documented here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts)).

docs: mark deprecated testing utilities and point to updated docs

---

.eslintrc.js

With latest relay, the graphql import needs to come from `react-relay`, not `relay-runtime` for typescript to be satisfied. This also applies to a few other things (like `commitMutation`, etc). However, using those things directly only apply to legacy patterns given our current set of tools, so should be fine.

chore(eslint): Add rule guarding against relay-runtime `graphql` import

---

src/Apps/Order/Routes/Shipping2/AddressModal2.jest.tsx

#minor
This PR should fix some recent flakiness in CI due to long-running test failures. Investigation  🔒[here](https://artsy.slack.com/archives/CP9P4KR35/p1701184330992859). In short, tests seem to get backed up on their first `await` after a previous test, which may have queued up some promises that weren't resolved before the test passed and exited. Unmounting the enzyme wrapper after each test helps somewhat. I also increased the timeout on tests for this file.
- remove waitFor; use flushPromiseQueue (I had tried `waitFor()` as an experiment to make our tests more semantic and less reliant on knowing the internals of the component they are testing, but I don't think it is good to mix with enzyme tests)
- unmount wrapper after each test (~40% reduction in total time)
- increase jest …

fix: long-running tests causing flaky CI failures

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
src/Components/SavedSearchAlert/types.ts
src/__generated__/SavedSearchAlertEditFormQuery.graphql.ts
src/__generated__/SavedSearchAlertEditForm_Test_Query.graphql.ts
src/__generated__/SavedSearchAlertEditForm_me.graphql.ts

Pills were not displayed on edit alert pages before.
Here is a video which demonstrated the whole user flow working:
https://github.com/artsy/force/assets/3934579/8c9a1956-104b-4091-9bce-5556b975de35

fix: Fix for artist series pills not being displayed on the edit alerts page

---

src/Components/ArtworkFilter/index.tsx

One of the problems that surfaced with the old sidebar filters was that inputs might be multi-step — meaning the page would scroll after applying some state, and maybe you want to refine the state (price filter, for example). Because the sidebar isn't sticky, this would be disruptive. So we only scroll on the new filters.

fix(filters): scroll to top if in experiment branch

---

src/Apps/Order/Routes/Shipping2/FulfillmentDetailsForm.tsx
src/Apps/Order/Routes/Shipping2/__tests__/FulfillmentDetailsForm.jest.tsx
src/Components/Address/AddressAutocompleteInput.tsx
src/Components/Address/__tests__/AddressAutocompleteInput.jest.tsx
src/Components/Address/useAddressAutocomplete.ts

Closes [EMI-1447]
Related to #12971 
This PR brings address autocomplete functionality to the new shipping route, refactoring the [existing autocomplete functionality](https://github.com/artsy/force/blob/337575304df1b338c1463795ac13041d563cc4e5/src/Components/Address/AddressForm.tsx#L238-L240) into a single component along the way.
TODOs:
Since the autocomplete input and its fallback are straightforward but bulky, I decided to pull its functionality into a component that can render either an autocomplete or fallback input and handle most tracking. As a result, tracking helpers are exported form the component file, and the `useAddressAutocomplete()` hook has been deprecated (its logic now living in the hook. I have also removed the secondary address …

Feat: Address autocomplete input for new shipping route

---

src/Apps/Auction/auctionRoutes.tsx
src/Apps/Settings/settingsRoutes.tsx
src/Components/FollowButton/FollowArtistButton.tsx
src/Components/FollowButton/FollowGeneButton.tsx
src/Components/FollowButton/FollowProfileButton.tsx
src/System/Relay/createRelaySSREnvironment.ts

Have been puzzling for a while why the logged out experience on Artsy.net is so much faster than the logged-in experience and finally figured out why: we were clearing the cache every time a mutation occurred, which was generally triggered by [viewing an artwork](https://github.com/artsy/force/blob/58f8a45ad69c3f69f59ca2291a3dc5f24218de1a/src/Apps/Artwork/useRecordArtworkView.ts#L36). If not logged in, we short circuit the mutation, and the cache remains. 
As [we typically attach `force: true`](https://github.com/artsy/force/blob/58f8a45ad69c3f69f59ca2291a3dc5f24218de1a/src/Apps/Artwork/artworkRoutes.tsx#L34-L36) to our relay queries for areas that _must_ remain fresh, and when we perform mutations for various sections of the UI we typically refresh the …

fix(system): Dont clear relay cache after mutations -> speed up logged in experience

---

src/Apps/Auction/auctionRoutes.tsx
src/Apps/Settings/settingsRoutes.tsx
src/Components/FollowButton/FollowArtistButton.tsx
src/Components/FollowButton/FollowGeneButton.tsx
src/Components/FollowButton/FollowProfileButton.tsx
src/System/Relay/createRelaySSREnvironment.ts

Reverts artsy/force#13211
Noticed an issue where `cacheConfig: { force: true }` no longer seems to work when attached to individual routes (eg, after visiting an artwork page it remains cached, when it should never cache, due to force: true being present on the route). Might be something with a recent relay upgrade? But in any case, we need a way to force certain routes to always be fresh, and short of that we'll have to shortcircuit it as we have been (unknowingly).

Revert "fix(system): Dont clear relay cache after mutations -> speed up logged in experience"

---

src/Components/Alert/Components/Filters/Price.tsx
src/__generated__/PriceAggregationsQuery.graphql.ts

Addresses [ONYX-525]
- Resolves https://github.com/artsy/force/pull/13158#discussion_r1399214348
- 🔴  Blocked by https://github.com/artsy/gravity/pull/17110
With this change, we will be able to show the price histogram for all artists that the alert is created with.
[ONYX-525]: https://artsyproduct.atlassian.net/browse/ONYX-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Allow multiple artist IDs for Alert price histogram

---

src/Apps/Article/Components/ArticleVisibilityMetadata.tsx
src/Apps/Artwork/ArtworkApp.tsx
src/Apps/Collect/Routes/Collect/index.tsx
src/Apps/Search/Routes/SearchResultsArtists.tsx
src/Apps/Search/Routes/SearchResultsEntity.tsx
src/Apps/Shows/Routes/ShowsCity.tsx
src/System/Router/useRouter.tsx

We've occasionally needed to perform a silent URL update instead of performing a full navigation event via our routing layer. This commit adds two new functions, `silentPush` and `silentReplace`, to consolidate our pattern for doing so in one place.
Follow-up on this [review comment](https://github.com/artsy/force/pull/13215#discussion_r1410897022).

chore: add silentPush and silentReplace to useRouter hook

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormDesktop.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
src/Apps/Settings/settingsRoutes.tsx
src/__generated__/SavedSearchAlertsApp_Alert_Query.graphql.ts
src/__generated__/settingsRoutes_SavedSearchAlertsAppEditQuery.graphql.ts

This PR solves [ONYX-548](https://artsyproduct.atlassian.net/browse/ONYX-548)
Allow explicit routing to `/settings/alerts/:id/edit`.
Supports routing to alerts not fetched within the list panel by fetching the alert data separately in a useEffect hook.
https://github.com/artsy/force/assets/123595/7c3f6b59-123d-4c59-a405-b27eb5b353e2
[ONYX-548]: https://artsyproduct.atlassian.net/browse/ONYX-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: allow routing to edit panel of alerts app

---

src/Components/ArtworkFilter/ArtworkFiltersQuick.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick/ArtistSeriesFilterQuick.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick/__tests__/ArtistSeriesFilterQuick.jest.tsx

This PR solves [ONYX-567]
Per discussion with @jpoczik — this adds the new Artist Series filter as one of the preferred quick filters in the sticky horizontal filters section above artwork grids.
https://github.com/artsy/force/assets/140521/c6558c2a-939a-467c-841c-7fe095e40b87
This new filter will appear if and only if:
- The feature flag is enabled
- Artist Series aggregations are present (which will only be true on artist pages currently)
|Artist series are present|Artist series are absent|Non-artist page|
|---|---|---|
|![presen](https://github.com/artsy/force/assets/140521/f28163a7-b970-466d-ba69-cccce45abce7)|![absen](https://github.com/artsy/force/assets/140521/597fcdc4-0b54-43dd-a46b-20c7f283a259)|![nonen](https://github.com/artsy/force/assets/140521 …

feat: add artist series horizontal filter

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
src/Components/Alert/Components/Steps/Confirmation.tsx

Addresses [ONYX-551]
Reload artist page correctly when navigating from same artist page.
From the Alert modal confirmation footer we are linking to the same artist page but with different filters (passed as query params in the URL) [here](https://github.com/artsy/force/blob/9f1078cdfebf737af3a0d2b173cd77ccf43f890b/src/Components/SavedSearchAlert/Components/ConfirmationStepFooter.tsx#L34).
The issue at the moment is that the filter context doesn't get remounted and therefore doesn't get updated (because the internal filter state doesn't get reinitialized) when navigating to the same artist page. By adding a key to the filter context component, we ensure that the component remounts whenever the URL changes. This way, the filters are set correctly on the page.
The artwork grid already gets …

feat: Reload artist page correctly when navigating from same artist page

---

src/Apps/Preferences/PreferencesApp.tsx

We should not reset the email preferences after submitting because the update in Gravity [runs in a background job](https://github.com/artsy/gravity/blob/35fd62b809c3e40fb09c7a948fd56aa9b8022a43/app/api/v1/notification_preferences_endpoint.rb#L30), and the preferences won't be updated immediately.
Even reading the return data from the mutation will return the previously set preferences. It takes a few seconds until the backend returns the updated preferences.
This PR doesn't fix the underlying issue but at least it fixes the form by not resetting the value.
https://github.com/artsy/force/assets/4691889/ec2454d6-c4b3-445b-8f0e-657b0a5043dd

fix: Do not reset email preferences after submitting

---

src/Components/Alert/Components/Form/SuggestedFilters.tsx

This PR solves [this request](https://www.notion.so/artsy/More-Filters-CTA-should-be-black-34bf69c3d3f04bde897d03eae5860d68?pvs=4) from design
Update more filters button color

fix: update more filters button color

---

src/Apps/Authentication/Components/AuthenticationInlineDialog.tsx
src/Server/passport/lib/app/lifecycle.ts
src/Server/passport/test/app/lifecycle.jest.js

Closes [DIA-333](https://artsyproduct.atlassian.net/browse/DIA-333)
Cleaned up https://github.com/artsy/force/pull/13236 and removed the email insertion. Using Sharify here was actually a problem and this winds up being simpler.
---------
We were just rendering error toasts with the error message returned from the server. This is potentially a problem because you could send a login link with a custom (potentially malicious) error message. The utility of this would be limited though since you couldn't inject any code or links but 🤷 .
This switches to using error codes.
[DIA-333]: https://artsyproduct.atlassian.net/browse/DIA-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dia-333): prevent insertion of arbitrary error messages

---

src/Apps/Order/Components/ArtworkSummaryItem.tsx

This PR solves EMI-1592
When the order is a partner offer without a list price, the price label should be `List price` and the value for the price should be `Not publicly listed` now. 

feat(EMI-1592): show the list price for a partner offer

---

src/Apps/Partner/Routes/Overview/index.tsx
src/__generated__/Overview_partner.graphql.ts
src/__generated__/partnerRoutes_OverviewQuery.graphql.ts

This PR solves [DIA-346]
It removes the sections for the churned profiles.
Before:
After:
[DIA-346]: https://artsyproduct.atlassian.net/browse/DIA-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove sections for churned profiles

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx

This PR solves [ONYX-591](https://artsyproduct.atlassian.net/browse/ONYX-591)
Update copy for criteria pills title in the edit alert form
[ONYX-591]: https://artsyproduct.atlassian.net/browse/ONYX-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-591): update copy for criteria pills in edit alert form

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
src/__generated__/NewSavedSearchAlertEditFormQuery.graphql.ts
src/__generated__/NewSavedSearchAlertEditForm_searchCriteria.graphql.ts

This PR solves [ONYX-599]
From the QA session for the new edit form — quick easy fix to ensure that artist series criteria, when present, are displayed and actionable.
https://github.com/artsy/force/assets/140521/e4801e19-82cf-4707-9d9f-a25901d0a185
[ONYX-599]: https://artsyproduct.atlassian.net/browse/ONYX-599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(alerts): ensure artist series is editable in new form

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/NewSavedSearchAlertEditForm.tsx
src/Components/Alert/Components/Steps/Filters.tsx

This PR solves [ONYX-598]
[Notion ticket](https://www.notion.so/artsy/The-filters-do-not-resize-well-on-medium-size-screens-e-g-ipad-bb5d3dd0b328487eb50826d9bf97a240?pvs=4)
The size of the details and filters form did not change when resizing the screen. This PR fixes it
**Before**
https://www.notion.so/artsy/New-Edit-Alert-Form-web-QA-Session-ce3682253e194683b9417437560a0647?p=bb5d3dd0b328487eb50826d9bf97a240&pm=s 
**After**
https://github.com/artsy/force/assets/36167539/a06549a7-1906-4eb3-810f-e5917e6f7fb5
[ONYX-598]: https://artsyproduct.atlassian.net/browse/ONYX-598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

fix(ONYX-598): fix resizing of the edit alert form and filters

---

src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx

This PR solves [EMI-1593]
> [!Note]
> This change is behind the feature flag `emerald_partner-offers-from-saves`
This PR updates the content of the Progressive Onboarding tooltip content for the Partner Offer
|---|---|
| ![image](https://github.com/artsy/force/assets/20655703/3d7a7942-94ff-4cfd-996d-f32a6f859ef6) | ![image](https://github.com/artsy/force/assets/20655703/be5d2746-5429-4328-bdee-1770529c52b3) |
[EMI-1593]: https://artsyproduct.atlassian.net/browse/EMI-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1593): update saves tooltip content for PartnerOffer

---

src/Apps/Search/Routes/SearchResultsEntity.tsx
src/Components/ArtworkFilter/index.tsx

This PR solves [ONYX-560]
When searching by a number (2019, for example) and then clicking on the "Next" link (or a number in pagination list), Force sends 2019 as a number, but Metaphysics expects a string. MP fails on such requests -> pagination doesn't work.
I'm opening a PR with a "naive" fix - explicitly convert keyword to a string, but I am wondering if we will forget to add such conversion somewhere and stumble upon the same issue.
|---|---|
| <video src="https://github.com/artsy/force/assets/3934579/2611e50e-fa98-4e61-ac1a-ec6a094219de" /> | <video src="https://github.com/artsy/force/assets/3934579/b61f20c8-e220-48fd-8694-b4ab30823e46" /> |
[ONYX-560]: https://artsyproduct.atlassian.net/browse/ONYX-560?atlOrigin=eyJpIjoiNWRkNTljNzY …

fix(onyx-560): Searching for a number results in errors that break pagination

---

src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActionsSaveButton.jest.tsx
src/Components/Artwork/SaveButton/__tests__/SaveArtworkToListsButton.jest.tsx
src/Components/Artwork/useArtworkLists.ts
src/System/i18n/locales/en-US/translation.json

This PR solves [EMI-1594]
> [!Note]
> This change is behind the feature flag `emerald_partner-offers-from-saves`
This PR updates the Save artwork toast and adds a description for the Partner Offer
|---|---|
| ![image](https://github.com/artsy/force/assets/20655703/0edcae92-0459-4e80-bbf9-4137dc76fa06) | ![image](https://github.com/artsy/force/assets/20655703/dc08ef0a-a836-4c10-b810-076cc6fb61d1) |  
[EMI-1594]: https://artsyproduct.atlassian.net/browse/EMI-1594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1594): Update Save Artwork toast

---

src/Apps/Partner/Routes/Overview/index.tsx
src/__generated__/Overview_partner.graphql.ts
src/__generated__/partnerRoutes_OverviewQuery.graphql.ts

This PR solves [DIA-347]
It displays nearby galleries rail and about section for churned profiles according to [this ticket](https://artsyproduct.atlassian.net/browse/DIA-347).
[DIA-347]: https://artsyproduct.atlassian.net/browse/DIA-347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: display nearby galleries rail and about section for churned profiles

---

src/Components/Alert/Components/Form/SuggestedFilters.tsx
src/Components/Alert/Components/Form/__tests__/SuggestedFilters.jest.tsx

Solves this QA item: https://www.notion.so/artsy/I-ve-found-a-case-where-one-suggested-filter-is-clicked-but-isn-t-added-a4f52b3dbe7c4f0ba13e65cb85856e31
Now that Artist Series suggestions have landed in Metaphysics we need to make sure Force can accept them.

feat(alerts): allow artist series suggestion to be accepted

---

src/Components/Alert/Components/CriteriaPills.tsx

This PR solves [ONYX-606](https://artsyproduct.atlassian.net/browse/ONYX-606)
Add underline to ShowMore on filter pills.
[ONYX-606]: https://artsyproduct.atlassian.net/browse/ONYX-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-606): add underline to showmore on filter pills

---

src/Components/Alert/Components/Filters/__tests__/NotificationPreferences.jest.tsx
src/Components/Alert/Components/NotificationPreferences.tsx

Always enable email notifications when creating alerts. Previously, it was disabled if the user had unsubscribed from Custom Alerts emails.
Addresses [ONYX-607](https://artsyproduct.atlassian.net/browse/ONYX-607)
[ONYX-607]: https://artsyproduct.atlassian.net/browse/ONYX-607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Always enable email notifications when creating alerts

---

src/Components/Search/SearchBarInput.tsx

This PR solves [ONYX-560]
Another bug related to search by a number: when searching by a number, search input becomes unresponsive. This happens because `SearchBarInputSuggestQuery` fails because it sends term as a number, but schema expects a string.
[ONYX-560]: https://artsyproduct.atlassian.net/browse/ONYX-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(onyx-560): fixes broken search page when searching by a number

---

src/Apps/Artwork/ArtworkApp.tsx
src/Components/Alert/Components/Form/SuggestedFilters.tsx
src/__generated__/SuggestedFiltersFetchQuery.graphql.ts

This PR solves [ONYX-563]
Now that we suggest artist series criteria in the Create Alert UI, we want to make sure they are as relevant as possible.
This means that when we are creating an alert from an artwork, we want the artist series suggestion to be based on the artist series  which _that_ artwork belongs to (if any).
(This is made possible by https://github.com/artsy/metaphysics/pull/5471)
|Before|After|
|---|---|
|![artist](https://github.com/artsy/force/assets/140521/791bfe39-97ea-468d-ba4d-163c88270bfb)|![artwork](https://github.com/artsy/force/assets/140521/2b287d14-0813-456a-934e-b594f3d2f9ba)|
[ONYX-563]: https://artsyproduct.atlassian.net/browse/ONYX-563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

feat(alerts): source artist series suggestions from artwork

---

src/Apps/Show/Components/ShowInstallShots.tsx
src/__generated__/ShowApp_Test_Query.graphql.ts
src/__generated__/ShowInstallShots_Test_Query.graphql.ts
src/__generated__/ShowInstallShots_show.graphql.ts
src/__generated__/showRoutes_ShowQuery.graphql.ts

In response to [this complaint](https://artsy.slack.com/archives/C03N12SR0RK/p1702895145151689) we learned that shows’ install shots are another case where our `quality: 50` setting bites us.
(Which makes sense since [white- or light-colored walls](https://observablehq.com/@anandaroop/artwork-color-casts) predominate in these photos.)
So this adds another targeted fix — very similar to https://github.com/artsy/force/pull/12913 — this time focusing on install shots.
The effect is subtle, but hopefully this gif (artifacts notwithstanding) makes the change clearer:

fix(images): increase quality of install shots

---

src/Apps/Settings/SettingsApp.tsx
src/Components/NavBar/Menus/NavBarUserMenu.tsx
src/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx

This PR solves [ONYX-564]
This is the only place I could find where alerts are still called "saved alerts"
[ONYX-564]: https://artsyproduct.atlassian.net/browse/ONYX-564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: rename Saved Alerts to Alerts in settings

---

src/Components/Alert/Components/Filters/ArtistSeries.tsx
src/Components/Alert/Components/Filters/QuickMultipleSelectAlertFilter.story.tsx
src/Components/Alert/Components/Filters/QuickMultipleSelectAlertFilter.tsx
src/Components/Alert/Components/Filters/__tests__/ArtistSeries.jest.tsx
src/Components/Alert/Components/Filters/__tests__/QuickMultipleSelectAlertFilter.jest.tsx
src/Components/Alert/Components/Steps/Filters.tsx
src/__generated__/ArtistSeriesOptionsQuery.graphql.ts

This PR solves [ONYX-610]
Allows selection of arbitrary artist series belonging to the current artist.
Introduces a slightly new UX for doing so (long lists of options that can optionally be collapsed)
https://github.com/artsy/force/assets/140521/f936df74-a78d-439f-804d-546439422c9e
[ONYX-610]: https://artsyproduct.atlassian.net/browse/ONYX-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(alerts): allow selection of artist series from "more filters" UI

---

src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx
src/Apps/Order/Routes/__tests__/Shipping.jest.tsx

We noticed that Force's test suite was failing after some dependency updates were auto-merged. We believe that the following updates could have changed something that caused these tests to fail:
- https://github.com/artsy/force/pull/13360
- https://github.com/artsy/force/pull/13363
The existing tests were failing because the "Offer" stepper button in the checkout flow was wrapped inside another button, like this:
```
<button>
<div>
<button>
Offer
</button>
</div>
<button>
```
And the testing library was recognizing this as two buttons with the same text, so the tests were asserting the existence of 2 buttons. Whatever caused these tests to fail was a blessing in disguise because this allows the test to assert the existence of 1 button.

fix: failing test after palette upgrade

---

docs/unleash_a-b_testing.md
src/System/__tests__/useFeatureFlag.jest.tsx
src/System/useFeatureFlag.tsx

The type of this PR is: refactor
This PR solves [PHIRE-533]
This PR refactors the `useFeatureFlag` hook to no longer throttle segment events when `trackFeatureView` is called.  
Currently, we throttle the number of segment events to one event per user, per variant view (i.e., if a user sees an experiment multiple times, only the first view sends a segment event), using `localStorage` to track if an experiment was viewed or not. This implementation makes it difficult to analyze and accurately report on the outcome of our experiments and creates extra work for the data team. This was discussed in more detail in this [Slack thread](https://artsy.slack.com/archives/C0KEQD4B0/p1702548231405999) and the recommendation was made to change the implementation.
With these changes, we will send a …

refactor: do not throttle experiment_viewed tracking events

---

src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListsHeader.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveTitle.tsx
src/Components/ProgressiveOnboarding/progressiveOnboardingAlerts.tsx
src/System/i18n/locales/en-US/translation.json

This PR solves [EMI-1595]
Inform users about the Partner Offer new project by showing a toast on the saves page.
I found it hard to follow the designs perfectly. Tried having the ProgressiveOnborading only on the specific link but it generated issues in the responsive view, as it created a div that I couldn't wrap around and instead the text was displayed as 2 columns like so
[EMI-1595]: https://artsyproduct.atlassian.net/browse/EMI-1595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1595): add text and tooltip to saves list header

---

src/Components/ErrorPage.tsx

Really small change to fix a type check error I came across while looking at the ErrorPage component. Implemented the co-pilot suggested fix to resolve:

fix: Typescript type checking error in ErrorPage component

---

src/Components/Search/SearchBarInput.tsx

When I press (long click) on search results in the dropdown - redirect doesn't happen. This PR fixes the issue.
|---|---|
| <video src="https://github.com/artsy/force/assets/3934579/a627fea6-4641-4563-a211-e3269af39e3e" /> | <video src="https://github.com/artsy/force/assets/3934579/e00cde18-3383-4aae-9aed-7046ccb3b9af" /> |

fix: fix long press on search dropdown items

---

src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx

This follows up [a few failed attempts](https://github.com/artsy/force/pull/13405) to solve the alerts-related artist page scroll bug [ticketed here](https://artsyproduct.atlassian.net/browse/ONYX-665).
At this point we are getting rid of the bug by actually _disabling_ the automatic `jumpTo` behavior completely. (It seems to interact poorly with the new filter UI which was released in https://github.com/artsy/force/pull/13329)
I'll leave the bug ticket open, in case anyone wants to take another swing at this. For context, the discussion took place in [this thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1706034210971619).

fix(artist): disable artist page jumpTo when coming from alert context

---

src/Apps/Artwork/Components/ArtworkDefinitionList.tsx
src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
src/Apps/Artwork/Components/ArtworkDetails/ConditionInfoModal.tsx
src/Apps/Auction/Routes/Bid/Components/ConditionInfoModal.tsx

This PR solves [AMBER-376]
Bidders can now see a breakdown of what different condition levels mean and make an informed decision when bidding on an artwork by clicking "Condition" which opens a modal. 
[This design/copy might change? TBD. WIP.]
[AMBER-376]: https://artsyproduct.atlassian.net/browse/AMBER-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: (AMBER-367) Added modal for condition information in auction lots. 

---

src/Components/Inquiry/Views/InquirySpecialist.tsx
src/Components/Inquiry/config.ts

This PR solves [EMI-1640]
This PR updates the Ask Specialist inquiry modal config to fix showing the Error status in the button.
~~We also updated the waiting period from `0.5s` to `1.5s` so users don't feel surprised when the modal suddenly disappears~~
We also added a toast when the message gets sent.
The fix here was to remove the `isLoggedOut` check from the `AskSpecialist` config for two reasons:
- We simplified the workflow a while ago in #11399. In the previous workflow, we used to have a confirmation modal at the end of the steps, so if the user was already logged in, it would skip the `isLoggedOut` check and move on to the confirmation modal.
- We don't have an Ask Specialist inquiry flow anymore, and if the user was logged in, the `isLoggedOut` …

fix(EMI-1640): Update ask specialist workflow engine config

---

src/Apps/Notifications/NotificationsApp.tsx
src/Components/Notifications/AlertNotification.tsx
src/Components/Notifications/ArtworkPublishedNotification.tsx
src/Components/Notifications/Notification.tsx
src/Components/Notifications/NotificationArtwork.tsx
src/Components/Notifications/NotificationArtworkList.tsx
src/Components/Notifications/__tests__/Notification.jest.tsx
src/__generated__/AlertNotification_notification.graphql.ts
src/__generated__/ArtworkPublishedNotification_notification.graphql.ts
src/__generated__/NotificationArtworkList_artworksConnection.graphql.ts
src/__generated__/NotificationArtwork_artwork.graphql.ts
src/__generated__/NotificationQuery.graphql.ts

Addresses [ONYX-625] & [ONYX-626]
- [Figma Design](https://www.figma.com/file/PO3rjpDV29YOFR8kLI4InJ/Activity-Panel-%26-Alerts-Management?type=design&node-id=652-3067&mode=design&t=H6HRDnH8XJe5dsI0-0)
This PR implement notification pages for Alert and Follow notifications
**To Do:**
- The label is still missing but will be displayed correctly after merging https://github.com/artsy/force/pull/13419
| Follow | Alert |
| --- | --- |
|<img width="1182" alt="Screenshot 2024-01-25 at 17 06 12" src="https://github.com/artsy/force/assets/4691889/ab19d64a-bc74-45e1-bfb1-f6787f582467"> |<img width="1199" alt="Screenshot 2024-01-25 at 17 06 25" src="https://github.com/artsy/force/assets/4691889/aeff720b-5fdb-4c28-96e6-b822d6e304c4"> |
[ONYX-626]: …

feat: Implement notification pages for Alert and Follow notifications

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
src/Components/__tests__/LocationAutocompleteInput.jest.tsx

Fixes [this failing test](https://app.circleci.com/pipelines/github/artsy/force/57761/workflows/a595a2db-bb43-4c09-b279-8e6aec8af35d/jobs/432033) cause by [this palette update](https://github.com/artsy/palette/pull/1361).
Not sure why `.simulate("mouseenter").simulate("mousedown").simulate("mouseup")` is not the same as `.simulate("click")` though 🤷

fix: fixes failing LocationAutocompleteInput spec

---

src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/useNotificationsContext.tsx

When navigating to `/notifications` the first notification in the list should open, but for some reason, it is not happening. This fix solves the issue. With this change also the URL is correctly replaced with `/notification/${firstNotificationID}`.
| --- | --- |
|<img width="1042" alt="Screenshot 2024-01-26 at 16 15 42" src="https://github.com/artsy/force/assets/4691889/57a0767c-bfc7-4f30-98b9-fe31ee151b90"> |<img width="1040" alt="Screenshot 2024-01-26 at 16 15 53" src="https://github.com/artsy/force/assets/4691889/b1c83bd2-e695-4af5-a942-ba6acc8bd33d"> |

fix: Open first notification correctly

---

src/Components/Notifications/NotificationsWrapper.tsx

This PR fixes the scrolling behavior of the Activity list in the split view, which was broken after updating the design of the activity list (https://github.com/artsy/force/issues/13392).
Basically, it wasn't possible to scroll the list independently.

fix: Notification list scroll behaviour

---

src/Components/Notifications/NotificationsList.tsx

Fixes unwanted redirect for mWeb, when user opens `/notifications` page and gets redirected to a top notification page right away. See before and after (notice that only mWeb was broken, I've attached desktop video just to demo that it works after changes)
Before:
|---|---|
| <video src="https://github.com/artsy/force/assets/3934579/62abe90f-8df5-4688-baa8-b883901f0223" /> | <video src="https://github.com/artsy/force/assets/3934579/175c5369-6a73-4788-b6d9-6e95ba09dcd1" /> |
After:
|---|---|
| <video src="https://github.com/artsy/force/assets/3934579/7e3326fe-4a88-458e-a132-48cb838aad72" /> | <video src="https://github.com/artsy/force/assets/3934579/e05fd6d1-2486-4d2c-af3c-0961e74107e8" /> |

fix: fixes unwanted redirect to a notification page from notifications list

---

cypress/e2e/artwork.cy.js
src/Apps/Artwork/ArtworkApp.tsx
src/Apps/Artwork/Components/ArtworkErrorApp/ArtworkErrorApp.tsx
src/Apps/Artwork/Components/ArtworkErrorApp/ArtworkErrorAppOtherWorks.tsx
src/Apps/Artwork/Components/ArtworkErrorApp/ArtworkErrorAppRelatedWorks.tsx
src/Apps/Artwork/artworkRoutes.tsx
src/Components/ErrorPage.tsx
src/Server/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts
src/System/Router/renderServerApp.tsx
src/Typings/sharify.d.ts
src/__generated__/ArtworkApp_artworkResult.graphql.ts
src/__generated__/ArtworkErrorAppOtherWorksQuery.graphql.ts
src/__generated__/ArtworkErrorAppOtherWorks_artwork.graphql.ts
src/__generated__/ArtworkErrorAppRelatedWorksQuery.graphql.ts
src/__generated__/ArtworkErrorAppRelatedWorks_artwork.graphql.ts
src/__generated__/ArtworkErrorApp_artworkError.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

This adds support a custom artwork error page with some related content. It still returns the right status code for the response (typically a 404). This is behind a feature flag so that in production, the behavior is unaffected. As such, we can iteratively merge and keep building this out.
It doesn't look 'amazing', but I'm hoping we can pretty it up as we work on this more!
It uses the new `artworkOrResult` pattern + schema to be able to perform some of this error-checking, as well as resolving the data we'd like to start out with for a custom error page. Overall it wound up being the standard Relay machinations and components.
Before this, propagating the right status code from the Relay/React app (`found`-router plus our framework) was fairly simple - there'd be a `throw new …

feat: custom artwork error page behind unleash flag

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/TextAndImageLayout.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/WaysWeSell.tsx

Closes [DIA-438](https://artsyproduct.atlassian.net/browse/DIA-438)
OK so this _was_ dark mode related, but not in the way I thought.
These backgrounds were previously defined with: `background="black"` — `black` is of course a valid HTML color, not a themed value. I replaced it with `black100` but, surprisingly, `background` is not theme-aware. We typically use the prop `bg`, which is.
Additionally I fixed these images which were causing a content shift on page load. I do note that the assets we use are inadequately sized as well: we need much larger images to pull resizes from.
[DIA-438]: https://artsyproduct.atlassian.net/browse/DIA-438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(consign): fixes inverted contrast; image placeholders

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilters.jest.tsx
src/Components/ArtworkFilter/ArtworkFilters/AvailabilityFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/AvailabilityFilter.jest.tsx

This PR solves [Hack13 - available filter](https://www.notion.so/artsy/Add-Sold-and-Available-filters-for-works-on-Artsy-net-so-it-makes-it-easier-to-send-inventories--167eb801582247acbee50db536bcba82) / [ONYX-698]
Review app example: https://availability-filter.artsy.net/artist/mike-gough
Adds a filter using our customary ux patterns that allows a collector to filter down to for-sale works only.
Quirky behavior at the moment:
- toggling it on shows `forsale: true` works only ✅ 
- toggling it off shows `forsale: false` works only, rather than _all_ works 🤔 
Notice how the count here goes from 46 (**all**) → 16 (**for-sale**) → 30 (**not-for-sale**) → 46 (back to **all**, by tweaking the url) →
https://github.com/artsy/force/assets/140521/08414b79-fb3d-43a6- …

feat: adds an availability filter for use on artwork grids

---

src/Apps/CollectorProfile/Routes/Saves/Components/Actions/Mutations/useCreateCollection.ts
src/Apps/CollectorProfile/Routes/Saves/Components/Actions/Mutations/useDeleteArtworkList.ts

This PR fixes a [bug reported in 🔒 slack](https://artsy.slack.com/archives/C02JHHHKP5K/p1707317247273669?thread_ts=1707317112.824079&cid=C02JHHHKP5K) where the artwork list list does not get updated after creating or deleting an artwork list. Looks like a tiny oversight after a migration on this page was completed.

fix: wrong relay connection key used to refresh artwork lists

---

src/Apps/Artwork/Components/ArtworkErrorApp/ArtworkErrorApp.tsx

@abhitip pointed out that our regular pageview tracking wasn't in effect for the artwork error app.
Looking into it, and this is b/c artwork pageview tracking is actually excluded in `trackingMiddleware`, otherwise we'd get that for free. That configuration is [here](https://github.com/artsy/force/blob/0c96a2f8313fcdb057604a29d4df803a3634d73c/src/System/Router/buildClientApp.tsx#L78).
So, this adds the same kind of raw pageview tracking (via `useEffect` with a good ol' `[]` dep. array), and `window.analytics`, as the `ArtworkApp` does [here](https://github.com/artsy/force/blob/0c96a2f8313fcdb057604a29d4df803a3634d73c/src/Apps/Artwork/ArtworkApp.tsx#L175).
Overall this is a bit messy and less than ideal, but is a consequence of the need to do custom analytics hooks on the artwork page (and …

feat: add pageview tracking to artwork error pages

---

src/Components/Notifications/ArticleFeaturedArtistNotification.tsx

Addresses [ONYX-754]
Removing the editorial notification page artist name line breaks that don't look so good.
| --- | --- |
|<img width="396" alt="Screenshot 2024-02-13 at 14 22 12" src="https://github.com/artsy/force/assets/4691889/1e68c4c6-f0dc-4844-8ecd-df878fb222e7"> |<img width="389" alt="Screenshot 2024-02-13 at 14 20 40" src="https://github.com/artsy/force/assets/4691889/732a031c-e12c-43f7-8f93-8955fe4b4519"> |
[ONYX-754]: https://artsyproduct.atlassian.net/browse/ONYX-754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Editorial notification artist line breaks

---

src/Apps/Notifications/NotificationsApp.tsx
src/Components/Notifications/Notifications.tsx
src/Components/Notifications/NotificationsEmptyStateByType.tsx
src/Components/Notifications/NotificationsHeader.tsx
src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/NotificationsPills.tsx
src/Components/Notifications/__tests__/Notifications.jest.tsx
src/Components/Notifications/__tests__/NotificationsList.jest.tsx
src/Components/Notifications/types.ts
src/__generated__/NotificationsListPaginationQuery.graphql.ts
src/__generated__/NotificationsList_viewer.graphql.ts
src/__generated__/NotificationsPillsQuery.graphql.ts

This PR solves [ONYX-695](https://artsyproduct.atlassian.net/browse/ONYX-695)
This pull request does the following:
-  Adds a new "Offers" filter pill to the Activity panel
-  Implements logic to conditionally render the Activity panel filter pills based on whether the user has activities of this type.
-  Adjusts the minimum width of the Activity panel to display all filter pills in a single row.
-  Refactors the notification/activity list to address a pagination bug using Relay hooks (instead of QueryRenderer).
-  Uses a separate feature flag, [onyx_activity_panel_filter_pills](https://unleash.artsy.net/projects/default/features/onyx_new_notification_page), to enable independent release of the Activity pills (Staging: enabled; Production: disabled)
We are …

feat(ONYX-695): add offers filter

---

src/Components/Notifications/NotificationsContextualMenu.tsx
src/Components/Notifications/NotificationsEmptyStateByType.tsx
src/Components/Notifications/NotificationsPills.tsx
src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx

This PR solves [ONYX-742](https://artsyproduct.atlassian.net/browse/ONYX-742)
Update Notifications empty state design, added links "Artists" and "Galleries" that lead to their pages.
https://github.com/artsy/force/assets/17580625/5badc5dd-2329-44f8-8d04-ccf05784ed1f
https://github.com/artsy/force/assets/17580625/0b3a7ad3-bee5-4ff2-88b8-89e9cddd18ee
[ONYX-742]: https://artsyproduct.atlassian.net/browse/ONYX-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-742): notifications empty state redesign

---

src/Components/Notifications/MarkAllAsReadPanel.tsx

Use the new `onyx_activity_panel_filter_pills` feature flag for the "Mark All as Read" panel to avoid this issue.

fix: Use onyx_activity_panel_filter_pills for mark all as read panel

---

src/Components/Notifications/AlertNotification.tsx

Addresses [ONYX-759]
Adjust Alerts notification page header on mWeb.
| --- | --- |
|<img width="467" alt="Screenshot 2024-02-15 at 08 32 58" src="https://github.com/artsy/force/assets/4691889/cefa9193-1a32-485d-a90d-488cbbb0c4fe"> | <img width="464" alt="Screenshot 2024-02-15 at 08 33 07" src="https://github.com/artsy/force/assets/4691889/136ac352-617a-4e18-bf0a-b6bf546d4b05">|
[ONYX-759]: https://artsyproduct.atlassian.net/browse/ONYX-759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Adjust Alerts notification page header on mWeb

---

src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/__tests__/NotificationsList.jest.tsx
src/Components/Notifications/__tests__/util.jest.ts
src/Components/Notifications/util.ts
src/__generated__/NotificationsListNextQuery.graphql.ts
src/__generated__/NotificationsListQuery.graphql.ts
src/__generated__/NotificationsList_test_Query.graphql.ts
src/__generated__/NotificationsList_viewer.graphql.ts

This PR solves [ONYX-751]
Hides notifications which do not have published viewing rooms / article within them.
[ONYX-751]: https://artsyproduct.atlassian.net/browse/ONYX-751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(onyx-751): hide unpublished viewing room / activity panel notifications from activity panel

---

package.json
scripts/check-dead-code.sh
src/DevTools/mockReactI18n.tsx
src/Server/asyncLocalWrapper/browser.ts
src/Server/asyncLocalWrapper/server.ts
src/Server/ip.ts
src/Server/userPerformanceMetrics.ts
webpack/sharedConfig.js

Dead-code analyis was added to Force in https://github.com/artsy/force/pull/11984, built on top of [`ts-prune`](https://github.com/nadeesha/ts-prune). 
That project has been archived and now recommends that its users adopt [Knip](https://knip.dev).
This PR changes the existing script to use Knip instead.
It also adds a `production` option that can used to do a deeper clean in  "[production mode](https://knip.dev/features/production-mode)" — i.e. will flag files that _are_ used, if they are _only_ used in tests.
Example:
```sh
yarn dead-code
yarn dead-code:production
```
- I've only enable the unused file reporting (`--include files`), but Knip can report many other types of unused things, such as binaries or `package.json` dependencies. Definitely worth …

feat: update dead-code analysis

---

src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx
src/Components/ProgressiveOnboarding/ProgressiveOnboardingPopover.tsx

This PR changes:
1. The horizontal position of the artist follows popover when the artist has no:
- Cover artwork
- Biography blurb
- Verified representatives
- Insights
1. The placement of the arrow on the artist follows popover
(1) was needed because the popover was appearing to the far right of the follows button:
The solution was to fit the container that the popover is attached to to fit its content. However, (2) was needed because the popover was smooshed against the edge of the screen when there was no cover artwork:
Here is the final result for artists with/without a cover artwork:

fix: wandering artist follows popover (DIA-471)

---

src/Components/Notifications/AlertNotification.tsx

Addresses [ONYX-777]
This PR adjusts the notification page Edit Alert font size.
| | |
| --- | --- |
|<img width="796" alt="Screenshot 2024-02-22 at 16 06 43" src="https://github.com/artsy/force/assets/4691889/de95be50-067f-464d-b6fd-0646fb21b78d"> |<img width="801" alt="Screenshot 2024-02-22 at 16 06 48" src="https://github.com/artsy/force/assets/4691889/d6bb065c-9d4b-4861-a864-6c791d3492ea"> |
[ONYX-777]: https://artsyproduct.atlassian.net/browse/ONYX-777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Adjust notification page Edit Alert font size

---

src/Apps/Show/Components/ShowInfoLocation.tsx

Addresses an issue noted in #product-bugs-and-feedback around duplicate addresses showing up. Fixed it by removing reference to the summary, in favor of the better-formatted version:
Before:
After:

fix(shows): Fix display of address

---

src/Components/Notifications/Notification.tsx
src/Components/Notifications/NotificationsWrapper.tsx

https://www.notion.so/artsy/mWeb-The-image-placeholder-on-the-notification-page-e-g-alert-and-follow-is-to-wide-and-doesn-t--e9c00ff9529b425382956838e401427c?pvs=4
https://www.notion.so/artsy/All-lines-should-be-same-light-grey-in-the-build-the-top-one-is-darker-80559cfdbef64d22a74b481d04580669?pvs=4
This PR fixes the Activity panel max height and placeholder image width for mobile web and the line color below the Activity panel header.
| --- | --- |
|<img width="376" alt="Screenshot 2024-02-26 at 16 47 16" src="https://github.com/artsy/force/assets/4691889/c2057663-1996-4b90-a7e5-99d3128d3f3d"> |<img width="379" alt="Screenshot 2024-02-26 at 16 47 09" src="https://github.com/artsy/force/assets/4691889/0af5beae-30c4-4ff2-8a01-5abe54ddd50c"> |
| --- | --- |
|<img …

fix: Adjust Activity panel max height and placeholder image width for mWeb

---

src/Components/Notifications/Notification.tsx

https://www.notion.so/artsy/Navigating-to-a-missing-unknown-notification-throws-a-500-internal-error-Maybe-we-redirect-to--adcf2e8c8868423591987955477fa511?pvs=4
Add error boundary around notification pane in Activity panel to display the list if loading the notification fails (e.g. if the id is wrong).
| --- | --- |
|<img width="1492" alt="Screenshot 2024-02-27 at 16 20 06" src="https://github.com/artsy/force/assets/4691889/5d77c687-6f23-420d-a436-f533f678db94"> | <img width="1490" alt="Screenshot 2024-02-27 at 16 19 55" src="https://github.com/artsy/force/assets/4691889/2e648447-b31f-4dc4-9b6a-07b8c46e7c63">|

fix: Add error boundary around notification pane in Activity panel

---

src/Apps/Artist/Components/ArtistMeta/ArtistMeta.tsx
src/Apps/Artist/Components/ArtistMeta/__tests__/ArtistMeta.jest.tsx
src/Apps/Artist/Components/ArtistMeta/__tests__/helpers.jest.ts
src/Apps/Artist/Components/ArtistMeta/helpers.ts
src/__generated__/ArtistApp_Test_Query.graphql.ts
src/__generated__/ArtistMeta_Test_Query.graphql.ts
src/__generated__/ArtistMeta_artist.graphql.ts
src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
src/__generated__/artistRoutes_ArtistSubAppQuery.graphql.ts

This PR solves [this bug report](https://artsy.slack.com/archives/C03N12SR0RK/p1709222809114789)
It was reported [here](https://artsy.slack.com/archives/C03N12SR0RK/p1709222809114789) that when people share a link for an artist we do not display the artist cover image as thumbnail meta when sharing the link via social.
This pr changes this behavior to use the coverArtwork for each artist let me know your thoughts on this.

fix: artist cover image meta

---

src/Components/Notifications/NotificationsEmptyStateByType.tsx
src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/NotificationsPills.tsx
src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
src/Components/Notifications/types.ts

Context: https://github.com/artsy/force/pull/13532#discussion_r1506307872
Rename "following" notification type to "follows".

chore: Rename "following" notification type to "follows"

---

src/Components/NavBar/NavBar.tsx

Fixes an long-standing issue where top-nav clicks don't close the drop down, leading to some page confusion. Discussed with Jimi [in here](https://artsy.slack.com/archives/C9XJKPY9W/p1709241670001359). 
https://github.com/artsy/force/assets/236943/cdc8d5f4-aee4-432c-9ce1-65165f92fb47

fix(nav-menu): Close artist and artworks dropdowns on nav item click

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx

Closes [DIA-456](https://artsyproduct.atlassian.net/browse/DIA-456)
Re: https://github.com/artsy/force/pull/13214 — this bug needs to be fixed rather than papered over by constantly remounting the filter whenever the route changes.
It's actually pretty concerning that one can't drive the filters with a simple route change. One would think that would be the primary way we'd change filter state...
[DIA-456]: https://artsyproduct.atlassian.net/browse/DIA-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: avoids remounting

---

src/Components/NavBar/menuData.ts

This PR solves an inconsistency in the NavBar menu Categories list where item _Emerging Art_ [links to a gene](https://github.com/artsy/force/blob/83e5cf4561d21a2653621aaeb497abf628ed8092/src/Components/NavBar/menuData.ts#L178-L180) while the rest of the items in the list link to a collection. This corrects that inconsistency so that all list items link to collections.
Update the Categories menu Emerging Art item to link to [emerging-art _collection_](https://staging.artsy.net/collection/emerging-art).

fix: NavBar categories menu links to emerging-art collection

---

package.json
yarn.lock

The type of this PR is: **Build**
Bumps `passport-facebook` to latest version due to #inc-195 
> [!IMPORTANT]  
> This PR is not urgent we can merge later

build(deps): bump passport-facebook from 2.1.1 to 3.0.0

---

src/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx
src/Apps/WorksForYou/WorksForYouApp.tsx
src/Apps/WorksForYou/worksForYouRoutes.tsx

Closes [DIA-380](https://artsyproduct.atlassian.net/browse/DIA-380)
[DIA-380]: https://artsyproduct.atlassian.net/browse/DIA-380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(works-for-you): includes login prompt when logged out

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx

This PR solves [ONYX-827]
Adds a space between the superscript count and its preceding word, as we do elsewhere.
[ONYX-827]: https://artsyproduct.atlassian.net/browse/ONYX-827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: spacing on new alert counts

---

src/Apps/Notifications/NotificationsApp.tsx
src/Components/Notifications/Notification.tsx
src/Components/Notifications/NotificationErrorMessage.tsx

Addresses [ONYX-769]
Show authentication dialog on the Notifications app (`/notifications` or `/notification/123`) when the user is not logged in.
<p>
| --- | --- |
|<img width="1800" alt="Screenshot 2024-03-06 at 13 25 36" src="https://github.com/artsy/force/assets/4691889/e6c94275-6803-4a0c-8f93-d3cd10853c35"> | <img width="1800" alt="Screenshot 2024-03-06 at 13 25 15" src="https://github.com/artsy/force/assets/4691889/5b04d501-e366-41f9-99df-492d4e7d97f6">|
</p>
</details> 
[ONYX-769]: https://artsyproduct.atlassian.net/browse/ONYX-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Show authentication dialog on the Notifications app when not logged in

---

src/Components/AuthDialog/Views/AuthDialogForgotPassword.tsx
src/Components/AuthDialog/Views/__tests__/AuthDialogForgotPassword.jest.tsx

The type of this PR is: refactor
This PR solves [PHIRE-681]
This PR refactors the copy a user sees when triggering a password reset email. The new copy includes a gentle reminder that they should only expect an email if we have an artsy account associated with the email they have input. 
👉 **Please feel free to suggest copy edits**
Old: 
New:
[PHIRE-681]: https://artsyproduct.atlassian.net/browse/PHIRE-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: password reset copy

---

src/Apps/Artwork/Components/ArtworkChatBubble.tsx
src/__generated__/ArtworkChatBubble_artwork.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

[AMBER-504]
The current implementation is not working on the auction page because it needs different handling for the price thresold.
The chat bubble for artworks is based on the listed price. This works for BNMO artworks, but it doesn't work for Auction artworks. For Auction artworks we want to consider the starting bid value instead of listed price.
[AMBER-504]: https://artsyproduct.atlassian.net/browse/AMBER-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(AMBER-504): Fix Salesforce Chat Bubble for auctions

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx

Noticed a typo in the text surrounding a MyCollection work's submission status. Once fixed, the linter demanded that I address a few `Forbidden non-null assertion`s, which I _hope_ I did correctly.

fix: my-collection submission status typo

---

src/Apps/Partner/Routes/Artists/ArtistsRoute.tsx

Fixes issue noted [here](https://artsy.slack.com/archives/C05F8TNKGAV/p1710452735521909) where adding `jumpTo` to the dependencies array seems to "capture" the behavior and always scroll. Seems like `jumpTo` is rerendering in a weird way. 
Will file ticket on Diamond board, cc @dzucconi

fix(partner): Fix scrollTo on partner/artist section

---

src/Apps/AppPreferences/__tests__/appPreferencesServerRoutes.jest.ts
src/Apps/AppPreferences/appPreferencesMiddleware.ts
src/Apps/AppPreferences/appPreferencesServerRoutes.ts
src/Apps/AppPreferences/useAppPreferences.tsx
src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsThemeSelect.tsx
src/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
src/System/Router/Boot.tsx
src/System/Router/buildServerApp.tsx
src/Typings/sharify.d.ts
src/middleware.ts
src/server.ts

Re: [DIA-415](https://artsyproduct.atlassian.net/browse/DIA-415)
The idea here is that we set preferences in a server side cookie, then parse and cast using a Yup schema and load it into sharify. A context provider pulls it out of sharify and into state for the client. You can then update both the client-side state and the cookie simultaneously. This provides a stable value for the server-side render + client-side mount.
The toggle for dark mode is located on the account settings page and hidden behind the feature flag `diamond_dark-mode`.
[DIA-415]: https://artsyproduct.atlassian.net/browse/DIA-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Implement app preferences + theme select

---

.circleci/config.yml

Related:
- https://github.com/artsy/volt/pull/7443
This updates our CI config to take advantage of our slack-orb context for the SLACK_ACCESS_TOKEN key, vs a per-repo env config.

ci(slack): Update slack notification to use circle context

---

.circleci/config.yml

This fixes our circle ci config to not clobber the preexisting `hokusai` context and instead updates our staging / deploy yaml fragments to support multiple contexts

ci(slack): Update circle config to use slack context - Try 2

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormPlaceholder.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertsArtworks.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
src/Apps/Settings/settingsRoutes.tsx

Addresses [ONYX-823]
This PR updates the Alerts screen page layout to use a split view with independent scrollable views. We already use this layout for https://www.artsy.net/notifications and https://www.artsy.net/user/conversation. 
Using the split view instead of a sticky right panel resolves a couple of scrolling issues that we experienced (for example [ONYX-823] & https://github.com/artsy/force/pull/13599).
- The split screen isn't usable with a browser window hight below 500px. Should we fix it?
- Should we make the whole row in the list on the left clickable?
- Should we adjust the ratio between list and detail view to match the 1:3 ratio from `/notifications`?
https://github.com/artsy/force/assets/4691889/ecde8919-2574-4484-bc5f-857b6bbaeb94
[ONYX-823]: …

fix: Update Alerts screen page to use split view

---

src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListContent.tsx
src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListForm/ArtworkListForm.tsx
src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListItem.tsx
src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/SelectArtworkListItem.tsx
src/Apps/CollectorProfile/Routes/Saves/Components/__tests__/ArtworkListContent.jest.tsx
src/System/i18n/locales/en-US/translation.json

This PR solves [EMI-1773]
- Update the "Create a new list" description copy
- Replace the lock icon for a hide icon
- Update the list header to remove the list privacy (Shared or Private) and move the icon to the title itself
- Add tooltips for both icons
- Replace the lock icon in the SelectArtworkListItem modal
This will have merge conflicts with https://github.com/artsy/force/pull/13641, so we should merge that first.
[EMI-1773]: https://artsyproduct.atlassian.net/browse/EMI-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1773): update copy for saves page tooltips and modals

---

src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtist.tsx
src/Apps/CollectorProfile/Routes/Artists/CollectorProfileArtistsRoute.tsx
src/Apps/CollectorProfile/Routes/Artists/__tests__/CollectorProfileArtistsRoute.jest.tsx
src/Apps/CollectorProfile/collectorProfileRoutes.tsx
src/__generated__/CollectorProfileArtistsListArtist_userInterestEdge.graphql.ts
src/__generated__/CollectorProfileArtistsListQuery.graphql.ts

Closes [DIA-535](https://artsyproduct.atlassian.net/browse/DIA-535)
[DIA-535]: https://artsyproduct.atlassian.net/browse/DIA-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(collectorprofile): roughs in artists page

---

src/Components/Footer/Footer.tsx
src/Components/Footer/__tests__/Footer.jest.tsx

This PR reshuffles the footer links behind a feature flag. In addition to a new ordering, the following changes have been made:
1. "Terms of Use" becomes "Terms and Conditions"
2. "Conditions of Sale" becomes "Auction Supplement" and has a new URL
3. "ACA Seller Conditions" is removed
This PR also sneaks in a refactor of the footer link layout. Thanks to @araujobarret, we were able to remove the margin properties (which can cause layout problems when the parent component is updated in Palette) and space out each footer link using a [Flex gap](https://developer.mozilla.org/en-US/docs/Web/CSS/gap).
One side-effect of this change is that the footer links have a vertical gap on mobile web (see screenshots below). We decided that this was a good thing because it now gives users more space to …

feat: update footer links (DIA-123)

---

src/Components/Alert/AlertProvider.tsx
src/Components/ArtworkFilter/ArtworkFilterContext.tsx
src/Components/ArtworkFilter/ArtworkFilters/AvailabilityFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/AvailabilityFilter.jest.tsx
src/Components/ArtworkFilter/Utils/__tests__/countChangedFilters.jest.ts
src/Components/ArtworkFilter/Utils/countChangedFilters.ts
src/Components/SavedSearchAlert/Utils/__tests__/extractPills.jest.ts
src/Components/SavedSearchAlert/Utils/extractPills.ts
src/Components/SavedSearchAlert/constants.ts
src/Components/SavedSearchAlert/types.ts

This PR solves [ONYX-702] and [ONYX-703]
This wraps up the Hackathon request that got stalled for a bit on the filter param logic (KS'd [here](https://www.notion.so/artsy/Boolean-filters-on-the-artwork-grid-0ccf4af13df54712b7c88b0480d377f8) and addressed in https://github.com/artsy/gravity/pull/17446)
Now that the for-sale toggle is filtering results correctly, we want to ensure the rest of the search UI works accordingly as well.
- A **pill** corresponding to the for-sale filter selection should be displayed, and allow for dismissal
- The **count** of active filters should account for the for-sale filter
Addressing the counts also turned up some gaps in the mWeb behavior, which should be addressed now.
Remains staging-only behind [an Unleash …

feat: enable pills and counts for the availability filter

---

src/Apps/Order/Components/ConditionsOfSaleDisclaimer.tsx
src/Apps/Order/Routes/__tests__/Accept.jest.tsx
src/Apps/Order/Routes/__tests__/Counter.jest.tsx
src/Apps/Order/Routes/__tests__/Reject.jest.tsx
src/Apps/Order/Routes/__tests__/Review.jest.tsx

This PR updates the conditions of sale copy that can be seen at the bottom of the submit-button on the last step of the checkout flow.
| Surface | Screenshot |
|---------|------------|
| Review order | <img width="1502" alt="Screenshot 2024-03-28 at 1 14 16 PM" src="https://github.com/artsy/force/assets/44589599/682163a0-866e-4faf-a5d9-abf45eaaef48"> |
| Review offer | <img width="1251" alt="Screenshot 2024-03-28 at 1 15 48 PM" src="https://github.com/artsy/force/assets/44589599/827df33e-4658-4253-9e2a-d3f1ab4868d8"> |
| Counter counteroffer |  <img width="1502" alt="Screenshot 2024-03-28 at 1 18 44 PM" src="https://github.com/artsy/force/assets/44589599/cf4314ee-53e4-4b36-a618-d7ee7e0f8b7b"> |
| Accept counteroffer | <img width="1493" alt="Screenshot 2024-03-28 at 1 19 21 PM" …

feat: update checkout conditions of sale copy (DIA-539)

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx

Aligns links evenly depending on different artwork count:
|---|---|
| <img width="300px" alt="Screenshot 2024-04-02 at 15 41 28" src="https://github.com/artsy/force/assets/3934579/b47f699c-1c4d-4cd2-8e45-525470fc5171"> | <img width="300px" alt="Screenshot 2024-04-02 at 15 41 39" src="https://github.com/artsy/force/assets/3934579/69d8d74c-9b64-4768-bd53-d326c4385bfe"> |

fix: fixes View Artworks link alignment on Your Alerts page

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx

As discussed in Onyx KS, this is a quick change to move the Availability filter closer to Ways to Buy, since these facets are kind of related thematically.

feat: move availability filter to correct position

---

src/Components/PhoneNumberInput/PhoneNumberInput.tsx

We have a real [PhoneNumberInput](https://palette-storybook.artsy.net/?path=/story/components-phoneinput--default) now — which is not used on settings. I don't have a moment to fix that, but I am getting sick of opening settings and seeing a broken looking input. So this PR just fixes that.

fix(phonenumberinput): includes gap

---

src/Components/AuthDialog/Components/AuthDialogSignUpPlaceholder.tsx
src/Components/AuthDialog/Views/AuthDialogSignUp.tsx
src/Components/AuthDialog/Views/__tests__/AuthDialogSignUp.jest.tsx
src/Components/Inquiry/Views/InquirySignUp.tsx
src/Components/Inquiry/__tests__/Views/InquirySignUp.jest.tsx

This PR updates the disclaimer at the bottom of the signup dialog behind a feature flag. In addition to the default signup dialog, there is a skeleton loader for that dialog, as well as a signup dialog in the inquiry flow that needs to be updated.
|-------|------|
| <img width="1436" alt="before_auth_signup" src="https://github.com/artsy/force/assets/44589599/35a680a1-c81a-4d70-bb7f-155a99a1448e"> | <img width="1436" alt="after_auth_signup" src="https://github.com/artsy/force/assets/44589599/1eb44634-de6e-4825-b5f2-5c3ece2973ff"> |
| <img width="1436" alt="before_inquiry_signup" src="https://github.com/artsy/force/assets/44589599/e08e62b5-63cc-4cb6-84e7-e13a7d428134"> | <img width="1436" alt="after_inquiry_signup" …

feat: new disclaimer in signup dialog (DIA-533)

---

src/Components/TermsUpdateDialog.tsx
src/Typings/sharify.d.ts

If running as part of an Integrity spec, do not show the terms update dialog. Turns out it's tricky to globally accept within Integrity.

fix(termsupdate): ignores integrity

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
src/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts

> [!IMPORTANT]  
> As a reminder, **any** time we present a list of artists from which a user will select, we should also display disambiguating info: nationality, birth date, death date.
This PR solves [ONYX-438]
(Counterpart to https://github.com/artsy/eigen/pull/10018)
This adds disambiguating information to the artist selection UI that is used in both My Collection and Sell with Artsy, for similar reasons as stated in the Eigen PR — to minimize the risk of misattributed works and duplicated artist data.
Before and after…
---
Before and after…
[ONYX-438]: https://artsyproduct.atlassian.net/browse/ONYX-438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(MyC, SwA): present disambiguating info when selecting an artist

---

src/Apps/Auction/Components/Form/ConditionsOfSaleCheckbox.tsx
src/Apps/Auction/Components/Form/__tests__/ConditionsOfSaleCheckbox.jest.tsx
src/Apps/Order/Components/ConditionsOfSaleDisclaimer.tsx
src/Apps/Order/Routes/__tests__/Accept.jest.tsx
src/Apps/Order/Routes/__tests__/Counter.jest.tsx
src/Apps/Order/Routes/__tests__/Reject.jest.tsx
src/Apps/Order/Routes/__tests__/Review.jest.tsx
src/Components/AuthDialog/Views/__tests__/AuthDialogSignUp.jest.tsx
src/Components/Footer/Footer.tsx
src/Components/Footer/__tests__/Footer.jest.tsx
src/Components/Inquiry/__tests__/Views/InquirySignUp.jest.tsx

This PR addresses:
- https://artsyproduct.atlassian.net/browse/DIA-549
- https://artsyproduct.atlassian.net/browse/DIA-550
This PR changes:
1. Linking "General Terms and Conditions of Sale" to `/terms`
2. Linking "Auctions Supplement" to `/supplemental-cos`
3. Standardizing how tests are written

fix: a cornucopia of terms and conditions changes

---

cypress.config.ts
src/Components/TermsUpdateDialog.tsx
src/System/Router/Boot.tsx

Similar to the Integrity user-agent check, do something similar for smoke tests (to opt those out of this dialog).

chore: reenable terms dialog w/ opt-out for smoke test

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

Fixes https://artsyproduct.atlassian.net/browse/ONYX-870
This adds in our 'standard' form best practices -> using the `required` label, and also informative validation errors (to be displayed after a user has interacted with a field, and then focused away w/ the field still being invalid).
Winds up looking something like -
I think this is an improvement of the current experience, where it's more subtle that all fields are required, _and_ there were no validation errors being displayed (besides the auto-completes which have their own).

chore: add required label and field errors to consignment artwork-details

---

src/Components/Notifications/PartnerOfferArtwork.tsx
src/Components/Notifications/PartnerOfferCreatedNotification.tsx

Adjusting for scenarios where partner offer is not available, according to the original design handoff https://www.figma.com/file/PO3rjpDV29YOFR8kLI4InJ/Activity-Panel-%26-Alerts-Management?type=design&node-id=1001-21830&mode=design&t=tuZwYYFoPc7jjniE-0

fix: conditionally display subtitle in notification panel partner offers

---

src/Apps/Conversations/components/Details/ConversationArtwork.tsx
src/Apps/Conversations/components/Sidebar/ConversationsSidebarItem.tsx
src/__generated__/ConversationArtwork_conversation.graphql.ts
src/__generated__/ConversationDetailsTestQuery.graphql.ts
src/__generated__/ConversationsSidebar2PaginationQuery.graphql.ts
src/__generated__/ConversationsSidebarItemTestQuery.graphql.ts
src/__generated__/ConversationsSidebarItem_conversation.graphql.ts
src/__generated__/ConversationsSidebarPaginationQuery.graphql.ts
src/__generated__/ConversationsSidebarTestQuery.graphql.ts
src/__generated__/conversationsRoutes_DetailQuery.graphql.ts

This PR solves [AMBER-548]
Adding the `Exclusive Access` text to unlisted artworks being talked about in converations. This terminology is the collector facing way of showing this information, whereas partner facing is `Private`.
Before:
After:
[AMBER-548]: https://artsyproduct.atlassian.net/browse/AMBER-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-548 - adding exclusive access text to artwork

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilters.jest.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick/ArtistSeriesFilterQuick.tsx
src/Components/ArtworkFilter/ArtworkFiltersQuick/__tests__/ArtistSeriesFilterQuick.jest.tsx

This PR solves [ONYX-800]
Feature has been fully launched for while, time to clean up the flag 🧹 
TODO
[ONYX-800]: https://artsyproduct.atlassian.net/browse/ONYX-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(artist series filter): retire Unleash feature flag

---

src/Components/Inquiry/Hooks/useInquiryContext.tsx
src/Components/Inquiry/Views/InquiryInquiry.tsx
src/Components/Inquiry/__tests__/Views/InquirySpecialist.jest.tsx

This PR solves [AMBER-522]
The rotating messages are being removed as part of the work to update these messages for Private Artworks. These were adding additional overhead without bringing any value. Some more conversations can be found attached to the ticket including some data to back this decision.
[AMBER-522]: https://artsyproduct.atlassian.net/browse/AMBER-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Before:
After:

Chore/amber 522/remove rotating conversation messages

---

src/Apps/Auctions/Components/CuritorialRailsTabBar.tsx
src/Apps/Auctions/Components/__tests__/CuritorialRailsTabBar.jest.tsx

This PR solves [ONYX-804](https://artsyproduct.atlassian.net/browse/ONYX-804)
Add "Lots for You" tab to Auctions page:
https://github.com/artsy/force/assets/17580625/a3e180c9-5d2a-42d5-8087-6ceb20d94a84
[ONYX-804]: https://artsyproduct.atlassian.net/browse/ONYX-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-804): add Lots for You tab on Auction page

---

src/Components/Artwork/Details.tsx

This PR partially solves [AMBER-550]
The previous PR for 550: https://github.com/artsy/force/pull/13685 introduced a visual bug for Partner Offers. This PR solves that bug by removing the `minHeight` which will cause a currently unseen issue with partner artworks.
Reverting the offending PR would be the best choice, but the revert is not very clean due to the number of files changed so this is the next best option. We can fix forward on the private artworks rail issue.
Before (Rail looking good, but Partner Offers not looking good):
After (Rail not looking good, but Partner Offers fixed):
[AMBER-550]: …

fix: remove minHeight so that Partner Offers are fixed

---

src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/Apps/Consign/Routes/SubmissionFlow/Utils/formHelpers.ts
src/__generated__/ContactInformation_SubmissionFlowTest_Query.graphql.ts
src/__generated__/ContactInformation_submission.graphql.ts
src/__generated__/consignFromCollectorProfileMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
src/__generated__/consignFromMyCollectionRoutes_contactInformationArtworkOwnerQuery.graphql.ts
src/__generated__/consignRoutes_contactInformationQuery.graphql.ts

Addresses [ONYX-821]
Correctly initializing the SWA form contact info on back press. This was not happening before at this step. It is likely that it was never set up because this is the first step of the form without loading an already existing submission.
[ONYX-821]: https://artsyproduct.atlassian.net/browse/ONYX-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Correctly initializing SWA form contact info on back press

---

src/Components/Notifications/NotificationItem.tsx
src/Components/Notifications/PartnerOfferArtwork.tsx
src/Components/Notifications/PartnerOfferCreatedNotification.tsx
src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx
src/__generated__/NotificationQuery.graphql.ts
src/__generated__/PartnerOfferArtwork_artwork.graphql.ts
src/__generated__/PartnerOfferCreatedNotification_test_Query.graphql.ts

This PR solves [EMI-1799]
Show the note for partner offers on Activity Panel. Adjust `Limited-Time Offer` label to match [designs](https://www.figma.com/file/RHkhhJJwixhFPltqhH9ZkW/v1.5-Saves-Partner-Offers?node-id=4381%3A13607&mode=dev).
[EMI-1799]: https://artsyproduct.atlassian.net/browse/EMI-1799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1799): partner offer note redesign in notification panel

---

src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsDeleteDialog.tsx
src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsList.tsx
src/Apps/CollectorProfile/Components/CollectorProfileArtists/CollectorProfileArtistsListArtist.tsx
src/__generated__/CollectorProfileArtistsDeleteDialogMutation.graphql.ts

Closes [DIA-570](https://artsyproduct.atlassian.net/browse/DIA-570)
This feature raised this issue: https://artsyproduct.atlassian.net/browse/DIA-590 — sort of annoying to remove a thing from a paginated list and then update the list once it's removed.
I feel like the natural way to do this would be to 'fade' out the item and _not_ refetch anything, but then navigating to the next page is going to be broken as it'll skip one item because of how it's paginated.
I feel like the only way to do this given our current API would be to force navigation to the first page while refetching the list.
For now it's just refreshing the page.
https://github.com/artsy/force/assets/112297/2750fba0-d36f-4c4c-8a9f-1e32d92c527e
[DIA-570]: https://artsyproduct.atlassian.net/browse/DIA-570?atlOrigin=eyJpIjoiNWR …

feat(dia-570): user can remove artist

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx

I tried to refactor the logic how we determine what buttons to display in which state - hopefully that is more readable now.
Here is the current look. 
The question I have here if we need to update partner section to display this 'contact gallery' button if purchase button bumped out the 'contact gallery' from main buttons?

feat(EMI-1800): update display to only have 2 active action buttons at a time

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarLinks.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarLinks.jest.tsx
src/System/i18n/locales/en-US/translation.json

This PR updates the disclaimer that appears at the bottom of an artwork page if that artwork is in an active auction.
|--------|------|
| <img width="1436" alt="Screenshot 2024-04-12 at 10 02 18 AM" src="https://github.com/artsy/force/assets/44589599/a40bc108-5835-46d9-8790-4bb77c1294a0"> | <img width="1436" alt="Screenshot 2024-04-12 at 10 12 20 AM" src="https://github.com/artsy/force/assets/44589599/bce85084-1579-42a3-9b2b-4613e451e8ab"> |

chore: update auction artwork disclaimer (DIA-552)

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx

Believe it should be good to rely on offer 'isActive' as it seems to be updated properly when the works become unavailable.

fix [EMI-1820]: do not add purchase button for inactive offers

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
src/Components/Notifications/NotificationItem.tsx
src/Components/Notifications/PartnerOfferCreatedNotification.tsx

Add border radius to limited-time offer to match [designs](https://www.figma.com/file/RHkhhJJwixhFPltqhH9ZkW/v1.5-Saves-Partner-Offers?node-id=4381%3A13945&mode=dev)

fix: add border radius to limited-time offer

---

src/Server/middleware/hardcodedRedirects.ts

This PR adds a permanent redirect from /conditions-of-sale to /supplemental-cos. This PR has a "Do not merge" label because the redirect destination has not yet been created. It is planned to be ready to launch by April 17, 2024.

feat: redirect conditions of sale

---

src/Components/Alert/Components/CriteriaPills.tsx

This PR solves [ONYX-561](https://artsyproduct.atlassian.net/browse/ONYX-561)
Allow conditional editing of alert artist criteria when an alert is associated with more than one artist.
https://github.com/artsy/force/assets/123595/6bced048-9c9a-4f54-b4a5-2df68f730222
[ONYX-561]: https://artsyproduct.atlassian.net/browse/ONYX-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: allow conditional editing of alert artist criteria

---

src/Apps/Auctions/Components/CuritorialRailsTabBar.tsx
src/Apps/Auctions/Components/__tests__/CuritorialRailsTabBar.jest.tsx
src/__generated__/AuctionsApp_Test_Query.graphql.ts
src/__generated__/CuritorialRailsTabBar_Test_Query.graphql.ts
src/__generated__/CuritorialRailsTabBar_viewer.graphql.ts
src/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts

This PR solves [ONYX-905](https://artsyproduct.atlassian.net/browse/ONYX-905)
Removes "Works for You" rail on Auction page and keeping only "Lots for You".
https://github.com/artsy/force/assets/17580625/fbb8f68b-b499-4366-a282-8ef03577c0db
[ONYX-905]: https://artsyproduct.atlassian.net/browse/ONYX-905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-905): remove works for you on auction page

---

src/Components/TermsUpdateDialog.tsx

Pretty simple fix - we want to suppress the terms update dialog for logged-out users.

chore: dont show terms update when user logged out

---

src/Apps/Collect/Routes/Collection/Components/Header/index.tsx

This makes the merchandisableArtists field safer, by falling back to an empty array if null. 
(From [this thread](https://artsy.slack.com/archives/C03N12SR0RK/p1713543478775019))

fix(collection): make field safer

---

src/Components/Footer/FooterDownloadAppBanner.tsx
src/Components/Footer/__tests__/Footer.jest.tsx

@joeyAghion reported in [this slack thread](https://artsy.slack.com/archives/C05F8TNKGAV/p1713558385846229) that the error rate was jumping. Turns out this relay request will 500 when not on an artwork page. 
This PR adds logic to early exit from the `useEffect` that makes the relay request, only on non-artwork pages.

fix: early exit from useEffect that checks for Private Artwork

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx

This PR ensures that we do not double render edition set information for private artworks.
<details><summary>screenshots below!</summary>
</details> 
My approach was to start by extracting a boolean for whether the work is editioned and also extracting the edition set info into it's own component. These moves seemed helpful so that we could operate at the same level of abstraction - one component for editioned works, another for non-editioned works. Boolean flag to render one or the other.
Then the actual fix was to wrap that with a check for the flag to show price info. When false bail on the rendering whether editioned or not.
https://artsyproduct.atlassian.net/browse/AMBER-629
/cc @artsy/amber-devs

fix: Suppress duplicate edition set info on private artwork pages AMBER-629

---

src/Apps/Artwork/ArtworkApp.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkDetails.tsx
src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkMetadata.tsx

This PR solves [AMBER-625]
In this PR I moved the location of the artist bio on mobile web to match the comps, and also made some small style adjustments.
https://github.com/artsy/force/assets/5643895/b0d4b454-9eec-4e6c-bf25-d5d21c408d93
[AMBER-625]: https://artsyproduct.atlassian.net/browse/AMBER-625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(AMBER-625): Move About the Artist section on mobile web and adjust margins and font size

---

src/Apps/Artwork/ArtworkApp.tsx

This PR solves [AMBER-640]
As per [this discussion](https://artsy.slack.com/archives/C05F8TNKGAV/p1713885480541039), the submitted order modal is not rendering for private works. We should show this for all works.
_Modal rendering over PA page:_ 
[AMBER-640]: https://artsyproduct.atlassian.net/browse/AMBER-640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(AMBER-342): show submitted order modal for private artworks

---

src/Apps/Collect/Routes/Collection/Components/Header/index.tsx

Addresses https://artsy.slack.com/archives/C03N12SR0RK/p1713983397739069?thread_ts=1713543478.775019&cid=C03N12SR0RK. 
Seems like somewhere there's a network race condition where artworks could come back null. Not sure why, but this makes things even safer for the time being.

fix(collections): Make even safer

---

src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
src/Apps/Artwork/Components/PrivateArtwork/__tests__/PrivateArtworkAboutArtist.jest.tsx

This hides the private artwork partner bio unless `displayArtistBio` is true. 

fix(artwork): only show partner bio if enabled

---

package.json
src/Apps/ArtAdvisor/01-Spike/App.tsx
src/Apps/ArtAdvisor/02-Markdown/App.tsx
src/Apps/ArtAdvisor/ArtAdvisorApp.tsx
src/Apps/ArtAdvisor/ArtAdvisorRoutes.tsx
yarn.lock

Two things:
- Sets up a folder structure similar to the one in artsy/quantum for adding numbered experiments (and moves the initial spike into experiment no. 1)
- Adds experiment no. 2 which demonstrates a few UI niceties to help makes this a little more presentable and chatgpt-esque for internal testing

feat: set up experiments directory for art advisory

---

src/Apps/Admin/NavigateToRoute.tsx
src/Apps/Admin/adminRoutes.tsx

Inspired by a slack thread around needing to see request info for routes that we can only access via a direct link (and thus are SSR'd, and hard to get relay logging info), this adds a new admin app / route `/admin/navigate-to-route` which allows us to quickly jump anywhere on the site:

feat(admin): Add admin/navigate-to-route route

---

src/Apps/Artwork/ArtworkApp.tsx

The type of this PR is:  CHORE
Adds an artworks visibility level to Artwork Pageview tracking:

chore: Adds visibility level to artwork pageview track events

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx

This PR solves [EMI-1841]
If a Partner Offer is not available anymore, it's details should be hidden in the artwork page.
https://github.com/artsy/force/assets/554507/422d392d-2ca5-47c6-b55c-488084999ce8
[EMI-1841]: https://artsyproduct.atlassian.net/browse/EMI-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-1841): hide partner offer details if not available anymore

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormPlaceholder.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertsArtworks.tsx
src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx

Closes [DIA-611](https://artsyproduct.atlassian.net/browse/DIA-611)
Cherry-picking this as it's not directly related to the work I'm doing.
As part of https://github.com/artsy/force/pull/13820 the situation with the alerts UI got worse due to there being even more vertical space occupied. This just removes all fixed pane and just has things sit on the page naturally. Clicking items scrolls to the top. It isn't ideal (this sidebar layout should only be used with fullscreen UIs, IMO), but it's actually usable.
https://github.com/artsy/force/assets/112297/5d64727b-0d9b-460f-88e7-bd7cf8065d83
[DIA-611]: https://artsyproduct.atlassian.net/browse/DIA-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(alerts): makes ui usable on all screens

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx

Fixes [EMI-1806]- or improves it at least.
_See linked ticket for bug_
This PR improves some visual bugs with the partner offer countdown timer by removing a component that is defined in the body of another component. As a result of doing this the `useTimer()` hook was repeatedly re-rendering, causing the internal hook to sync with our official server time to continually cancel itself out.
However, I think there may be something more to improve here. I wasn't able to eliminate 100% of the visual tics and there is still some flickering in the first instant the component loads. This might deserve more investigation.
[EMI-1806]: https://artsyproduct.atlassian.net/browse/EMI-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

fix: EMI-1806 partner offer timer re-mounts over and over

---

src/Components/AuthDialog/Components/AuthDialogSocial.tsx

This PR adds a note that social login [does not work ](https://artsy.slack.com/archives/C06SSV1K10D/p1714662670281049?thread_ts=1714662167.086639&cid=C06SSV1K10D)in this review app and disables the buttons. I figured it is better to be explicit and keep them in the UI but add a note, rather than just removing them. If we decide we want to support social login, we can dig into the root issue. 

chore: disable social login

---

hokusai/production.yml
hokusai/staging.yml

This PR supports [PHIRE-813]
Let pods [load key/value pairs from Hashicorp Vault](https://www.notion.so/artsy/Integrate-Kubernetes-with-Vault-922ee8d71ac04507a5ad38b9003ca014?pvs=4#8b5a7b5dbcb244c698535841dd1f7107). We will migrate secret configs from ConfigMap to Vault.
[PHIRE-813]: https://artsyproduct.atlassian.net/browse/PHIRE-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: pull secrets from vault

---

src/Apps/ViewingRoom/Components/ViewingRoomsFeaturedRail.tsx
src/Apps/ViewingRoom/__tests__/ViewingRoomsApp.jest.tsx
src/Utils/Hooks/useStableShuffle.ts

Fixes https://artsyproduct.atlassian.net/browse/DIA-371
Some related updates to get rid of `!` usage and relative vs absolute paths for imports (plus a Palette update that allows `image={undefined}` in the `Card` component).

chore: randomize featured viewing rooms banner order

---

src/Apps/Home/Components/HomeFeaturedMarketNews.tsx

Fixes https://artsyproduct.atlassian.net/browse/DIA-620 , bumps font size down a tad for mobile (still seems big enough to me, the `["lg", "xl"]` variant on `Text` appears throughout the codebase so seems to be a reasonable pattern).

chore: bump font size down on editorial titles for homepage on mobile

---

src/Components/Cells/CellShow.tsx

Fixes https://artsyproduct.atlassian.net/browse/DIA-617
We have reference shows (not _really_, but shows with only unpublished artworks count as reference shows), that can be rendered using this component, and those are not linkable (`href: null`).
When passing `href=null` to our link component, it renders a cursor indicating this is clickable (even though it isn't).
I thought about making that change in `RouterLink` (suppressing that cursor pointer if `!href`), but that felt a touch global, so just made this update in this component.
Another option might be to skip rendering a wrapping link entirely (either here _or_ in `RouterLink`) if `href == null`, but also a bit of a global change that I'm not insanely confident on.

chore: suppress cursor pointer when a ref show rendered via CellShow

---

src/Apps/Partner/Components/PartnerShows/ShowBanner.tsx
src/Apps/Partner/Components/__tests__/PartnerShows/ShowBanner.jest.tsx

This PR solves [AMBER-583]
Addressing partner feedback/bug, now we check to make sure that `href` is not null before rendering the View More button.
[AMBER-583]: https://artsyproduct.atlassian.net/browse/AMBER-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix (Amber-583): "View More" button no longer renders on partner shows if there is no href 

---

cypress/e2e/institutions.cy.ts
src/Apps/Partners/Routes/InstitutionsRoute.tsx

The type of this PR is: tiny **Feat**
See discussion: [Slack thread](https://artsy.slack.com/archives/C03N12SR0RK/p1715174220151949)
"Browse Institutions" → "Browse Museums and Institutions" to better parallel the global nav as well as the content of the page.

feat: update Institutions page title

---

src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/__tests__/SelectArtworkListsModal.jest.tsx
src/Apps/CollectorProfile/Routes/Saves/Components/SelectArtworkListsModal/useSelectArtworkLists.ts
src/Components/Artwork/SaveButton/SaveArtworkToListsButton.tsx
src/Components/Artwork/SaveButton/useSaveArtwork.ts
src/Components/Artwork/SaveButton/useSaveArtworkToLists.ts

This PR solves [EMI-1791]
This PR fixes a case in saving artworks when a collector does the following:
1. Saves an artwork to a custom list
2. Saves the same artwork to default using the Select List modal
3. Clicking the saves button on the Artwork Page
The previous steps results in un-saving the artwork from the default saves list without showing the modal
This PR also re-enables some tests and removes non-null assersions
|---|---|
| <video src="https://github.com/artsy/force/assets/20655703/eac090d2-e101-4d18-9ae5-fefdf917be3c" /> | <video src="https://github.com/artsy/force/assets/20655703/756c78a7-eeb1-4e10-b483-0e063d55702e" /> |
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWR …

fix(EMI-1791): Fix unsaving artwork in multiple lists bug

---

package.json
src/Apps/Home/Components/HomeNewWorksForYouRail.tsx
src/Apps/Home/Components/HomeRecentlyViewedRail.tsx
src/Apps/Home/Components/HomeWorksByArtistsYouFollowRail.tsx
yarn.lock

This PR solves [DIA-640]
[Blocked by Cohesion PR](https://github.com/artsy/cohesion/pull/501) 
This PR adds save artwork ability to HomeWorksForYou rails under tab bar.
[DIA-640]: https://artsyproduct.atlassian.net/browse/DIA-640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add save ability to home works tab bar

---

src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
src/__generated__/ArtworkAppTestQuery.graphql.ts
src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

This PR solves [AMBER-687]
The private artwork page was previously not able to deal with artworks that had multiple artworks. This has now been updated as part of this PR.
Screenshots
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
[AMBER-687]: https://artsyproduct.atlassian.net/browse/AMBER-687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-687 - private artwork multiple artists

---

src/Apps/Settings/Routes/MyCollection/Components/MyCollectionArtworkGrid.tsx
src/Components/ArtworkGrid/ArtworkGrid.tsx
src/__generated__/MyCollectionArtworkGrid_artworks.graphql.ts
src/__generated__/MyCollectionRouteQuery.graphql.ts
src/__generated__/collectorProfileRoutes_MyCollectionRouteQuery.graphql.ts

- Change tooltip copy
- If artwork was already submitted - do not display tooltip on top of it (thanks @dariakoko for noticing this bug)
|---|---|
| <img width="1510" alt="Screenshot 2024-05-15 at 09 06 48" src="https://github.com/artsy/force/assets/3934579/5dfe0d00-5c63-4753-ad23-dd3ba5aa80c8"> | <img width="1511" alt="Screenshot 2024-05-15 at 09 06 57" src="https://github.com/artsy/force/assets/3934579/e8b2295a-6e00-485a-9d45-825aa5df4a11"> |

feat: change SWA tooltip copy and do not show tooltip for submitted artworks

---

src/Apps/Home/Components/HomeAuctionLotsForYouRail.tsx
src/Apps/Home/Components/HomeAuctionLotsRail.tsx

This PR solves [ONYX-969](https://artsyproduct.atlassian.net/browse/ONYX-969)
Adds save artwork button on HomeAuctionLotsForYouRail and HomeAuctionLotsRail (Curators picks)
Related to this[ Cohesion PR](https://github.com/artsy/cohesion/pull/502).
Home page:
https://github.com/artsy/force/assets/17580625/a2d59e55-15c5-4753-9a78-7ec81227d306
Auctions page:
https://github.com/artsy/force/assets/17580625/77a23d24-8e9d-4879-be92-55bdf665ead7
Logged out:
https://github.com/artsy/force/assets/17580625/d86a3fb2-cc10-4bb3-af06-1152b522bf28
[ONYX-969]: https://artsyproduct.atlassian.net/browse/ONYX-969?atlOrigin=eyJpIjo …

fix(ONYX-969): add save artwork button to rails

---

src/Apps/Order/Components/OfferInput.tsx

I tried just removing this separator as the other option the ticket suggests but those big numbers where cents are not allowed felt strange to me. Also it's kinda nice when it's matching the display above.
Regex for the win!

chore(EMI-1864): replace localization with blant conversion to comma separated numbers to match display

---

src/Server/middleware/hardcodedRedirects.ts

Redirects from pages like `https://www.artsy.net/settings/alerts/c99019b3-029c-433f-8a55-7117bd397598/edit` (come from email) are broken.
[Slack thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1716387774309809)

fix: fixes alerts redirects

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx
src/Apps/Order/Routes/Payment/PaymentContent.tsx
src/Components/BankDebitForm/BankDebitProvider.tsx
src/Components/CreditCardInput/CreditCardInput.tsx
src/Components/Notifications/PartnerOfferArtwork.tsx

Should probably rename the `THEME` constant to discourage use.

fix(dia-580): fixes theme usage throughout

---

src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
src/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileFields.jest.tsx

Addresses [ONYX-985]
This fixes the profile settings location input. 
When entering an arbitrary string in the location input, users can save the profile, but the location does not get updated. This corrects the input by updating the location correctly for arbitrary strings.
The app already accepts arbitrary strings as location and works as expected.
[ONYX-985]: https://artsyproduct.atlassian.net/browse/ONYX-985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Edit profile settings location input arbitrary string support

---

src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx

This PR solves [AMBER-699]
@lidimayra noticed that link hovers were vanishing on the black background, so this fixes that by removing the hover. 
[AMBER-699]: https://artsyproduct.atlassian.net/browse/AMBER-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(private-artworks): fix link hover

---

src/Apps/Partner/Routes/Shows/index.tsx

This PR solves [AMBER-678]
Partner Shows are displaying as Current events on partner profile overview page but not in Events tab under Current Events
Partner: Galerie Max Hetzler
[Events page](https://www.artsy.net/partner/galerie-max-hetzler/shows)
[Profile overview page](https://www.artsy.net/partner/galerie-max-hetzler)
Slack thread: https://artsy.slack.com/archives/C03N12SR0RK/p1715016600143109
So basically we show a banner for the first featured show but only if `isFeatured` is true, and its false for that show. So its technically not broken but I think if the first featured show has `isFeatured` set to false we should show that show in the regular show rail, so that's what I did.
__Before:__
__After:__
[GRO-434]: …

fix(AMBER-678): Shows display on partner profile overview page but not in Events tab

---

src/Apps/Auction/Components/AuctionDetails/AuctionInfoSidebar.tsx
src/Apps/Auction/Components/AuctionDetails/__tests__/AuctionInfoSidebar.jest.tsx

Remove contact phone number from auctions pages
| BEFORE | AFTER |
|---------|--------|
| <img width="1430" alt="Screenshot 2024-05-28 at 5 45 27 AM" src="https://github.com/artsy/force/assets/44589599/9c6c790a-5f3a-4130-8124-b8902fbc40e3"> | <img width="1447" alt="Screenshot 2024-05-28 at 5 45 04 AM" src="https://github.com/artsy/force/assets/44589599/246a94d6-f8f9-42a8-bd09-71106f5ad76b"> |

fix: remove auctions phone number (DIA-660)

---

.secrets.baseline
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
src/Apps/MyCollection/Routes/EditArtwork/MyCollectionEditArtwork.tsx
src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkFormHelpers.ts
src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkModel.ts
src/Apps/MyCollection/Routes/EditArtwork/Utils/useCreateOrUpdateArtwork.ts
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebar.jest.tsx
src/Components/LocationAutocompleteInput.tsx
src/Components/__tests__/LocationAutocompleteInput.jest.tsx
src/__generated__/MyCollectionArtworkSidebarMetadata_artwork.graphql.ts
src/__generated__/MyCollectionArtworkSidebarTestQuery.graphql.ts
src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
src/__generated__/MyCollectionEditArtworkTest_Query.graphql.ts
src/__generated__/MyCollectionEditArtwork_artwork.graphql.ts
src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
src/__generated__/collectorProfileRoutes_MyCollectionArtworkFormQuery.graphql.ts
src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
src/__generated__/myCollectionRoutes_MyCollectionArtworkFormQuery.graphql.ts

🔴 Do not merge before https://github.com/artsy/gravity/pull/17722 has run
This PR solves [ONYX-860]
- Eigen PR: https://github.com/artsy/eigen/pull/10245
- Gravity PR: https://github.com/artsy/gravity/pull/17680
- 
This PR adds autocomplete capability to the My Collection artwork form location input.
I couldn't get the auto-suggestions dropdown to work locally, so the screenshot doesn't show the dropdown.
[ONYX-860]: https://artsyproduct.atlassian.net/browse/ONYX-860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: My Collection form location autocomplete

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx

Noticed this flashing alert button on the artwork page:
https://github.com/artsy/force/assets/112297/4d4f32bd-5da1-4059-a270-216ba6f7934a
------
This was primarily due to the alert button component being declared _inside_ of another component's body. Just _never do this_. I wish there was a linting rule for this sort of thing because it's happened a number of times.
Initially I thought it was due to the timer hook being used to just determine if a date was in the past, which is related, but in fact _any_ timer/polling on the page would cause this thing to re-render. I fixed that anyway because it was unnecessary.

fix(artwork): fixes re-rendering alert button

---

src/Apps/Shows/Components/ShowsCurrentShows.tsx
src/__generated__/ShowsCurrentShowsQuery.graphql.ts
src/__generated__/ShowsCurrentShows_viewer.graphql.ts

[Context here](https://artsy.slack.com/archives/C03N12SR0RK/p1715174220151949)
Some partners may abuse the notion of 'online shows' in order to put together loose collections of 'inventory', then manually alter the start dates so that they are constantly bumped to the top of the index.
Including 'online shows' here was initially a response to the pandemic and has outlived its usefulness.

fix(shows): makes shows index useful again

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
src/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx

[Slack thread](https://artsy.slack.com/archives/C05EQL4R5N0/p1717421505002459)
Should fix broken sticky with CTA on /sell page on mWeb.
I cannot reproduce the issue on my laptop - still looking for how to do it (going to create review app soon in any case). In the meantime I borrowed the code from the "cookie content" sticky. I think it should work.

fix: Start Selling sticky hidden on mWeb

---

src/Apps/AppPreferences/useAppPreferences.tsx
src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsThemeSelect.tsx
src/Components/Footer/Footer.tsx
src/Utils/Hooks/useDarkModeToggle.ts
src/__generated__/PreferencesAppTestQuery.graphql.ts

Closes [DIA-664](https://artsyproduct.atlassian.net/browse/DIA-664)
With this we can enable the feature flag. I'll leave the flag in place for a week then PR it's removal.
This PR fixes a small bug where we would block updates to preferences until the previous one completed. Instead now we maintain a queue of operations and apply them in order, while optimistically updating them in local state. (Read: It's fun to flip the theme back and forth rapidly).
And some minor rework of the theme selector design.
In the footer:
In account settings:
[DIA-664]: https://artsyproduct.atlassian.net/browse/DIA-664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-664): Cleans up theme selection

---

src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
src/Apps/Order/Routes/Shipping2/Components/__tests__/FulfillmentDetailsForm.jest.tsx
src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx

This PR solves [EMI-1671]
This PR removes the name field from the pickup form in the refactored shipping route. It also fixes a (skipped) test that depends on filling in [jsdom's missing srcroll-into-view helper](https://stackoverflow.com/questions/53271193/typeerror-scrollintoview-is-not-a-function) on an HTML element.
[EMI-1671]: https://artsyproduct.atlassian.net/browse/EMI-1671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore(EMI-1671): remove name from pickup form

---

src/Apps/Artwork/Components/__tests__/ArtworkPageBanner.jest.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Routes/ArtistRoute.tsx
src/Apps/Sell/Routes/NewRoute.tsx
src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/NewRoute.jest.tsx
src/Apps/Sell/SellFlowContext.tsx
src/Apps/Sell/sellRoutes.tsx
src/__generated__/ArtistRoute_Test_Query.graphql.ts
src/__generated__/ArtistRoute_submission.graphql.ts
src/__generated__/sellRoutes_ArtistRouteQuery.graphql.ts

Addresses [ONYX-1014]
This implements the "Artist step for the new submission flow. 
- `/sell2/submissions/new`
- renders the artist step without initializing the form
- `/sell2/submissions/:id/artist`
- renders the artist step and initializes the form
[ONYX-1014]: https://artsyproduct.atlassian.net/browse/ONYX-1014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: New submission flow artist step

---

src/Apps/Sell/Routes/DetailsRoute.tsx
src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
src/__generated__/ArtistRoute_Test_Query.graphql.ts
src/__generated__/DetailsRoute_Test_Query.graphql.ts

Addresses [ONYX-1017]
This implements the **Details step** for the new submission flow.
| desktop | mWeb |
| --- | --- |
|<img width="1395" alt="Screenshot 2024-06-13 at 11 19 11" src="https://github.com/artsy/force/assets/4691889/553f4d6c-f588-4382-927a-5a56f37592f7"> | <img width="395" alt="Screenshot 2024-06-13 at 11 19 35" src="https://github.com/artsy/force/assets/4691889/de2f4f08-6a8f-47e1-8dd1-69cd6463ea4d">|
[ONYX-1017]: https://artsyproduct.atlassian.net/browse/ONYX-1017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: New submission flow details step

---

.vscode/settings.json
package.json
src/Apps/ArtAdvisor/05-Near-Object-Rail/App.tsx
src/Apps/ArtAdvisor/05-Near-Object-Rail/components/Artwork.tsx
src/Apps/ArtAdvisor/05-Near-Object-Rail/helpers/weaviate.tsx
src/Apps/ArtAdvisor/05-Near-Object-Rail/server.ts
src/Apps/ArtAdvisor/ArtAdvisorApp.tsx
src/Apps/ArtAdvisor/ArtAdvisorRoutes.tsx
src/Apps/ArtAdvisor/ArtAdvisorServerRoutes.ts
yarn.lock

This PR adds and experiment to evaluate using a `nearObject` [search](https://weaviate.io/developers/weaviate/api/graphql/search-operators#nearobject) to populate and update an artwork rail based on user interactions. Specifically, "liking" or "disliking" an artwork. 
https://github.com/artsy/force/assets/38149304/9efb31ee-95e4-4fc7-ac59-15f7c7cbbe38
- This experiment has generated a few open questions that we would need to address before introducing this approach into a product. I believe they are best demonstrated through the code, so I have highlighted them in PR comments. 
- There are some UI rough edges that we would want to address, but my focus on this experiment was fleshing out the `nearObject` based rail concept.

feat: add 05-near-object-rail experiment

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
src/__generated__/ArtworkDetails_SubmissionFlowPrepopulatedTest_Query.graphql.ts
src/__generated__/ArtworkDetails_myCollectionArtwork.graphql.ts
src/__generated__/consignRoutes_artworkDetailsWithArtworkIdQuery.graphql.ts
src/__generated__/consignRoutes_myCollectionArtworkQuery.graphql.ts

Addresses [ONYX-1059]
With this update, we correctly carry over the (new) auto-completed collector location when submitting a MyC artwork.
| | |
| --- | --- |
|<img width="1425" alt="Screenshot 2024-06-13 at 09 22 36" src="https://github.com/artsy/force/assets/4691889/60a6641d-5f88-45c7-873d-c4356ba0ce75"> |<img width="1426" alt="Screenshot 2024-06-13 at 09 22 19" src="https://github.com/artsy/force/assets/4691889/d83cb703-e672-4eab-b11d-829aa3890740"> |
[ONYX-1059]: https://artsyproduct.atlassian.net/browse/ONYX-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Carry over auto-completed location when submitting a MyC artwork

---

src/Apps/Sell/Routes/DimensionsRoute.tsx
src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
src/__generated__/DimensionsRoute_Test_Query.graphql.ts

This PR solves [ONYX-1019]
Implement artwork dimensions step for the new submission flow
| Web | mWeb |
| --- | --- |
| <img width="1444" alt="image" src="https://github.com/artsy/force/assets/36167539/b9e99317-799a-4ee0-9dbb-93ae3340620a"> | <img width="415" alt="image" src="https://github.com/artsy/force/assets/36167539/3328260a-edee-4b55-8cbf-8d8f0290bc1e"> |
[ONYX-1019]: https://artsyproduct.atlassian.net/browse/ONYX-1019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-1019): add artwork dimensions step

---

src/Apps/Components/__tests__/AppShell.jest.tsx
src/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
src/Components/Footer/Footer.tsx
src/Components/Footer/__tests__/Footer.jest.tsx

Closes [DIA-684](https://artsyproduct.atlassian.net/browse/DIA-684)
Removes dark mode feature flag. Also adjusts the footer theme selector to wrap better.
[DIA-684]: https://artsyproduct.atlassian.net/browse/DIA-684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Once deployed we'll archive the flag completely.

chore: removes dark mode feature flag

---

.circleci/config.yml

Storybooks is useful for local dev, but we don't need to deploy it (and also no reason to occupy CI runtime).

chore(storybooks): Remove CI deploys

---

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
src/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts

This updates the new Sell flow's `ArtistAutocomplete` component to use `Artist#coverArtwork` instead of `Artist#image`. 
`coverImage` seems to be the new thing (https://github.com/artsy/force/pull/13004) and with this change the artist image is consistent with [EntityHeaderArtistFragmentContainer](https://github.com/artsy/force/blob/8a4d1ac03f7b59512442ce7fc068fdc4dbc45124/src/Components/EntityHeaders/EntityHeaderArtist.tsx#L107) which we display in following steps.
**Before**
| | |
| --- | --- |
| <img width="832" alt="Screenshot 2024-06-14 at 17 23 39" src="https://github.com/artsy/force/assets/4691889/0d94eb26-4354-4293-857a-02d29eea3518">|<img width="905" alt="Screenshot 2024-06-14 at 17 24 06" src="https://github.com/artsy/force/assets/4691889/4fe7908e-bad3-48f3-8775-9aebbd19f044"> | …

fix: Update Sell flow `ArtistAutocomplete` `Artist#image` to `Artist#coverArtwork`

---

.env.oss
.secrets.baseline
src/Apps/ArtAdvisor/06-Discovery-Neartext/App.tsx
src/Apps/ArtAdvisor/06-Discovery-Neartext/components/Artwork.tsx
src/Apps/ArtAdvisor/06-Discovery-Neartext/components/Concepts.tsx
src/Apps/ArtAdvisor/06-Discovery-Neartext/server.ts
src/Apps/ArtAdvisor/06-Discovery-Neartext/types.ts
src/Apps/ArtAdvisor/06-Discovery-Neartext/weaviate-db.ts
src/Apps/ArtAdvisor/ArtAdvisorApp.tsx
src/Apps/ArtAdvisor/ArtAdvisorRoutes.tsx
src/Apps/ArtAdvisor/ArtAdvisorServerRoutes.ts

Adds an experiment to source artwork discovery recommendations for a user based on:
- a list of plaintext "concepts" that describes the user
- a list of liked artworks
- a list of disliked artworks
The concepts act as a semantic search over the Weaviate `DiscoveryArtworks` collection (a few hundred artworks from our curated collections, as of this writing)
The dis/likes serve to refine the results based on explicit user signals.
https://github.com/artsy/force/assets/140521/e6aa165f-ee64-4ebc-92ed-4e6dcf390438

feat: add 06 neartext experiment

---

src/Components/Artwork/Details.tsx
src/Components/Artwork/__tests__/Details.jest.tsx

This PR solves [AMBER-724]
As part of the changes made in https://github.com/artsy/gravity/pull/17819 we now have a new `sale_message` which will be displayed on the Artworks page. We do not want this, however, to appear in the artwork grid. This change ensures it will not be shown.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
[AMBER-724]: https://artsyproduct.atlassian.net/browse/AMBER-724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AMBER-724 - hide inquire on artworks grid

---

src/Apps/Components/AppShell.tsx
src/Apps/Components/constants.ts
src/System/Components/PageLoadingBar.tsx
src/System/Router/RenderStates.tsx
src/Typings/found.d.ts

After updating the page loader, it really brought to light a lot of our slow loading pages, particularly around collections (which was kinda masked before). This improves the loader a bit by never really stopping -- there's always motion -- as well as animating out from where it was currently at. This was possible by leveraging the `match.elements == undefined` recent discovery which means the page is loading, and moving the bar into the appshell, vs being depending on the weird found router render states.
https://github.com/artsy/force/assets/236943/f9a27c53-7af1-4f3a-bf38-49808fca1178

chore(page-loader): Improve it a bit more

---

src/System/Components/PageLoadingBar.tsx

One more small improvement - quickly fades the bar in on show so that the initial appearance isn't so abrupt. 
https://github.com/artsy/force/assets/236943/fc821d3d-98c0-4d9e-92e1-4e13f3532d0f

chore(loading-bar): fade in top bar

---

src/Apps/Auction/Components/AuctionDetails/AuctionInfoSidebar.tsx
src/Apps/Auction/Components/AuctionDetails/__tests__/AuctionInfoSidebar.jest.tsx

This PR solves [DIA-718]
Changing/adding elements to the auctions sidebar:
* How to bid on artsy? -> How to bid on artsy
* New "More information" section
[DIA-718]: https://artsyproduct.atlassian.net/browse/DIA-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: copy changes for auction pages

---

src/Apps/Sell/Components/ArtistNotEligibleText.tsx
src/Apps/Sell/Routes/ArtistNotEligibleRoute.tsx
src/Apps/Sell/Routes/ArtistRoute.tsx
src/Apps/Sell/Routes/__tests__/ArtistNotEligibleRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
src/Apps/Sell/sellRoutes.tsx
src/__generated__/ArtistNotEligibleRoute_Test_Query.graphql.ts
src/__generated__/ArtistNotEligibleRoute_artist.graphql.ts
src/__generated__/sellRoutes_ArtistNotEligibleRouteQuery.graphql.ts

Addresses [ONYX-1068]
This implements the  "artist not eligible" experience for the new Sell flow.
If the selected artist isn't the target supplier, the user gets sent to this screen.
| | |
| --- | --- |
|<img width="1329" alt="Screenshot 2024-06-20 at 10 29 05" src="https://github.com/artsy/force/assets/4691889/922b4795-1cef-4bc3-8af2-781bca407344"> |<img width="397" alt="Screenshot 2024-06-20 at 10 33 46" src="https://github.com/artsy/force/assets/4691889/a7f8fc55-b18d-46af-9641-f936e2f9a95e"> |
[ONYX-1068]: https://artsyproduct.atlassian.net/browse/ONYX-1068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: New sell flow "artist not eligible" experience

---

src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
src/Apps/Order/Routes/Shipping2/Components/__tests__/AddressModal2.jest.tsx
src/Apps/Order/Routes/Shipping2/Utils/shippingUtils.ts

This PR completes [EMI-1941] by giving us identical address validation shapes in both of the refactored shipping route's address forms.
#minor
[EMI-1941]: https://artsyproduct.atlassian.net/browse/EMI-1941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: address form validation inconsistencies

---

.vscode/settings.json
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollection.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts

This PR wires up the marketing collections rail to the `07-Curated-Discovery` result page, taking input from the form page. Similar to #14044, this isn't the final representation of the collections rail, but stubs it out and allows us to keep iterating and avoid duplicative work.
I've punted on UI polish considerations.
---
https://github.com/artsy/force/assets/38149304/1452330a-d51e-4ab9-88f5-dde44bcb1751

feat: wire up marketing collections rail to 07-Curated-Discovery

---

src/Apps/Artwork/Components/ArtworkPageBanner.tsx

This PR solves [EMI-1924]
An alternative to #14058 where we only check that the user is logged in to avoid backend + app changes that need to be coordinated
[EMI-1924]: https://artsyproduct.atlassian.net/browse/EMI-1924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-1924): user logged in to show expired banner

---

package.json
src/Apps/ArtAdvisor/07-Curated-Discovery/App.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Budget.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Form.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Links.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/llm/extractBudgetIntent.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
yarn.lock

Completes the budget inference step that was stubbed in #14044 
The LLM logic was developed over in https://github.com/artsy/quantum/pull/30 and is re-used in slightly modified form here.
Upon submitting messy free text such as “**idk maybe 5k by the end of the year**” the intent will be parsed as shown in the global state object here:
```js
{
"currentStep": "result",
"goal": "Decorate my home",
// 👇🏽 messy input
"budget": "idk maybe 5k by the end of the year",   
// 👇🏽 extracted intent
"budgetIntent": {                
"budget": {
"currency": "USD",
"min": 0,
"max": 5000
},
"timeFrame": {
"number": 6,
"unit": "month"
}
},
"interests": [
"Prints"
],
"interestsFreeText": ""
}
```
https://github.com/artsy/force/assets/140521/bd9a9d5a-1644-4420-9983-64cedc343cbd

feat: extract budget intent via LLM

---

src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx

We had a report that /alerts page was returning 500 for some users
After pairing with @anandaroop, this is happening when an artist associated with some Saved alerts gets deleted
Thinking of ways to be a little more defensive on the client side so instead users can access their alerts instead of returning a 500 page exception
An artist for one of my saved alerts was deleted
After some console logging, the `node` itself is coming back as `null` if artist cannot be found, so we have an array of search criteria with null as the last value
Early Return if the node is `null`, that way users can at least view the page
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

Fix: return if artist associated with saved alert cannot be found

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx

Resolves [ONYX-1058](https://artsyproduct.atlassian.net/browse/ONYX-1058)
Make the "Start Selling" button ready for the new sales flow (behind a feature flag).
[ONYX-1058]: https://artsyproduct.atlassian.net/browse/ONYX-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Make "Start Selling" button ready for new sell flow

---

src/Apps/Sell/Components/SubmissionLayout.tsx

Use [`100dvh` instead of `100dv`](https://developer.mozilla.org/en-US/docs/Web/CSS/length) in the Sell flow layout to correctly set height on mobile .
| --- | --- |
|![IMG_E02836EC05E3-1](https://github.com/artsy/force/assets/4691889/4f0498fe-f3b8-44d6-85ec-7e2f620fb5d9) |<img width="461" alt="Screenshot 2024-06-25 at 12 07 25" src="https://github.com/artsy/force/assets/4691889/f393f092-4c08-4da5-b088-8d77b8849a03"> |

fix: Use dvh for Sell flow layout to correctly set height on mobile

---

src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Routes/ArtistRoute.tsx
src/Apps/Sell/Routes/__tests__/ArtistNotEligibleRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/NewRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/TitleRoute.jest.tsx

Addresses [ONYX-1058]
This change will require login in the new Sell flow. Creating a new submission by selecting an artist will open the auth modal and clicking "Next" in the flow will open the auth modal as well (even if it might not be needed, I thought this would be good to have).
[ONYX-1058]: https://artsyproduct.atlassian.net/browse/ONYX-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: require login in new Sell flow

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx

Correctly link to the Sell Flow **intro** page when clicking "Start Selling" on the `/sell` page.

fix: Correctly link to Sell flow intro page

---

.vscode/settings.json
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Article.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArticlesRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/MarketingCollectionsRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts

This PR follows #14050 and uses it as a template to wire up the articles rail.
- As part of this work, I ingested just under `9,000` articles into a new `weaviate` collection called `DiscoveryArticles` using the `quantum` [scripts](https://github.com/artsy/quantum/tree/main/src/06-positron-rag). I also expanded the script to also return the `imageUrl` (PR forthcoming). 
- In the current implementation of the `DiscoveryArticles` collection, we include "news" articles. And in testing this PR I noticed they tend to be a lot of the top results. It seems like we will want to exclude news articles (an article from 2012 about that years gallery shows probably doesn't have a ton of discovery value). This  should be possible by updating the `articlesConnection` [MP …

feat: add 07 curated discovery articles rail

---

src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Result.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts

Brings over a simple Artworks rail from 06 into 07.
Deliberately pared down and simplified to match the existing Collections rails so that we can incrementally, in future PRs:
- add the price filtering (once we've re-ingested [with better data](https://artsy.slack.com/archives/C06SSV1K10D/p1719323396490219))
- add liking/disliking back in
- do a design pass over all the rails
For now, pretty straighforward:
https://github.com/artsy/force/assets/140521/5976765e-03e4-4af3-8d01-6ac173dbcebc

feat: add rudimentary 07 artworks rail

---

src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomSubsections.tsx
src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorksArtwork.tsx
src/Apps/ViewingRoom/Routes/Works/ViewingRoomWorksRoute.tsx
src/__generated__/ViewingRoomStatementRoute_Test_Query.graphql.ts
src/__generated__/ViewingRoomWorksArtwork_artwork.graphql.ts
src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
src/__generated__/ViewingRoomWorksRoute_viewingRoom.graphql.ts
src/__generated__/viewingRoomRoutes_ViewingRoomStatementRouteQuery.graphql.ts
src/__generated__/viewingRoomRoutes_ViewingRoomWorksRouteQuery.graphql.ts

One more targeted fix (following https://github.com/artsy/force/pull/13308) for a surface that highlights both artworks and install shots — Viewing Rooms
Effect is (as usual) subtle, but often [noticed by partners](https://artsy.slack.com/archives/C045UP78DG8/p1719426228258459?thread_ts=1694371647.491209&cid=C045UP78DG8):

fix(images): increase quality of viewing rooms

---

src/Components/Notifications/NotificationItem.tsx
src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/__tests__/NotificationItem.jest.tsx

This PR solves [ONYX-944]
When tapping on an Activity Panel notification containing one artwork (or show/etc), we want to redirect the user directly to the artwork page rather than the notifications app with the notification selected in the preview pane. The only exception I made is Partner offer notification, because it always has 1 object.
|---|---|
| <video src="https://github.com/artsy/force/assets/3934579/92854e7b-2994-434c-ad51-f75416149688" /> |  <video src="https://github.com/artsy/force/assets/3934579/a9ce17ad-bf03-4209-b8d7-7d8e99b17a11" /> |
[ONYX-944]: https://artsyproduct.atlassian.net/browse/ONYX-944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-944): activity panel navigates directly to entity page whenonly one entity in notification row

---

src/Components/Artwork/Details.tsx
src/Components/Artwork/__tests__/Details.jest.tsx

This PR solves [AMBER-769]
We initially defined the sale message shouldn't be displayed in case of "Inquire about availability" (see https://github.com/artsy/force/pull/14002). This caused weirdness on the grid compared to other artworks. We're undoing this.
[AMBER-769]: https://artsyproduct.atlassian.net/browse/AMBER-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(AMBER-769): Do not hide the sale message on the grid

---

src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/Artwork.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Result/ArtworksRail.tsx
src/Apps/ArtAdvisor/07-Curated-Discovery/server.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/types.ts
src/Apps/ArtAdvisor/07-Curated-Discovery/weaviate-db.ts

This PR updates the `07-curated-discovery` app with functionality to allow a user to like or dislike artworks so that we may refine what is shown to them in the `ArtworksRail`. It largely ports over the implementation from #13992, with some exceptions, which are noted in the comments.
Follow-ups:
- UI shifting on refetch
- Handling different artwork sizes
https://github.com/artsy/force/assets/38149304/a3eba88b-4107-4369-b7bc-5dd9c7581e5e

feat: add artwork like and dislike functionality

---

src/Components/PhotoUpload/Components/PhotoDropzone.tsx
src/Components/PhotoUpload/__tests__/PhotoDropzone.jest.tsx

https://www.notion.so/artsy/It-doesn-t-support-upload-of-heic-photos-I-understand-we-brought-this-in-elsewhere-c55ae750075f40869d9505ab6701792f?pvs=4
Add HEIC support to Sell flow.

fix: Add HEIC support to Sell flow

---

src/Apps/Sell/Components/ImagePreviewItem.tsx

https://www.notion.so/artsy/Images-skewed-when-uploaded-dada7142bf2343e498cd6d5dc6973550?pvs=4
Add `objectFit: contain` to Sell flow photo preview.
| --- | --- |
|<img width="745" alt="Screenshot 2024-07-01 at 10 36 37" src="https://github.com/artsy/force/assets/4691889/8a8f4475-158c-4eae-a2b9-20b8900b0948"> | <img width="755" alt="Screenshot 2024-07-01 at 10 34 31" src="https://github.com/artsy/force/assets/4691889/e7095749-d97a-4cba-8353-9a9e077f9e78">|

fix: Add `objectFit: contain` to Sell flow photo preview.

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx

This PR addresses [ONYX-1089](https://artsyproduct.atlassian.net/browse/ONYX-1089)
Instead of forcing a user to login or sign up directly on the /sell landing page, we'd like to allow the user to start and progress through the submission and only force an authenticated state at the end, right before the submission graduates from draft > submitted. At that point in the flow we want to make sure we have an Artsy user account to link the submission to but we're okay with letting visitor / unauthenticated users start and experience the submission flow before the final step.
| Title | Video |
| Current (Visitor) | <video src="https://github.com/artsy/force/assets/123595/dd0d1364-f50d-4c5c-a0a4-4833d9b07717" /> |
| New (Vistor) | <video …

feat: defer forced login / sign up to end of SWA submission flow

---

src/Apps/Consign/Routes/SubmissionFlow/Utils/redirects.ts

These server-side validations aren't necessary and there's some missing mapping causing the whole page to 404 when refreshing a draft.

fix: remove validation redirects in existing submission flow

---

src/Apps/Sell/Routes/__tests__/TitleRoute.jest.tsx
src/Apps/Sell/SellFlowContext.tsx

Resolves https://www.notion.so/artsy/I-know-that-it-is-intentional-but-why-there-is-no-Back-button-on-Title-step-8d161a74f52a4b12aade2c12fd83b729?pvs=4
Bring Back button back to Sell flow title step.

fix: Bring Back button back to Sell flow title step

---

src/Components/Artwork/Details.tsx
src/Components/Artwork/__tests__/Details.jest.tsx

Relates to https://github.com/artsy/gravity/pull/17866
This PR solves [AMBER-769]
This is now coming straight from Gravity, so we don't need additional logic in the clients anymore
[AMBER-769]: https://artsyproduct.atlassian.net/browse/AMBER-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
@artsy/amber-devs

chore(AMBER-769): Remove logic to display hardcoded message for "Bidding closed"

---

src/Apps/Sell/Routes/TitleRoute.tsx

Resolves https://www.notion.so/artsy/Odd-behavior-when-clicking-on-Artist-component-on-title-page-get-taken-directly-to-thank-you-page-b6a9bace58e24fcb9f616cfecabde6f5?pvs=4
This PR makes the artist on the Sell flow "Title" step non-clickable.

fix: Make artist on Sell flow "Title" step non-clickable

---

src/Apps/Sell/Components/SubmissionLayout.tsx

Allow scrolling from any part of the add photos page
https://github.com/artsy/force/assets/36167539/e5bf3338-9c57-4531-a491-ce4c857631ec

fix: allow scrolling from any part of the add photos page

---

src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/SellFlowContext.tsx

Resolves https://www.notion.so/artsy/Had-to-press-several-times-on-Submit-CTA-on-the-phone-input-screen-before-it-navigated-to-the-Than-b28e105c16534075a33ffaaef68181a3?pvs=4
This correctly disables the "Submit" button in the Sell flow until the submission is updated. Before, it was possible to click the button multiple times.

fix: Sell flow submit button

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SWAFooter.jest.tsx

Follow-up to [artsy/force#14049][].
[artsy/force#14049]: https://github.com/artsy/force/pull/14049
The login/signup prompt within the SWA flow is no deferred to right before a user is able to submit a draft. This earlier prompt is no longer necessary.

feat: defer SWA login/signup prompt in SWAFooter/SWAStickyFooter

---

src/Apps/Sell/Routes/PurchaseHistoryRoute.tsx

Resolves https://www.notion.so/artsy/Purchase-History-the-space-between-the-title-and-the-text-input-is-too-small-68b989c14dc242f9b2e6fc206301c1b3?pvs=4
Add space above Sell flow purchase history select. The other steps don't need extra space, it's just that the Select component is missing the top padding.
| --- | --- |
|<img width="810" alt="Screenshot 2024-07-03 at 12 10 18" src="https://github.com/artsy/force/assets/4691889/d084a4c8-0bd9-4b80-b0d2-345704899572"> | <img width="687" alt="Screenshot 2024-07-03 at 12 08 59" src="https://github.com/artsy/force/assets/4691889/3d57f964-343c-47dc-937d-bda1ef024cf1">|

fix: Add space above Sell flow purchase history select

---

src/Apps/Sell/Routes/PhoneNumberRoute.tsx
src/Apps/Sell/SellFlowContext.tsx
src/Components/PhoneNumberInput/validatePhoneNumber.ts

Resolves https://www.notion.so/artsy/Phone-number-can-take-letters-without-any-invalidation-message-e358107930ac4df680b78869210b86d3?pvs=4
This adds phone number validation to the Sell flow. The validation only results in a warning, and it will still be possible to submit with an invalid number.

feat: Add phone number validation to Sell flow

---

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx
src/Apps/Sell/Components/UploadMoreMessage.tsx
src/Apps/Sell/Components/UploadPhotosForm.tsx
src/Components/PhotoUpload/Components/PhotoDropzone.tsx
src/Components/PhotoUpload/__tests__/PhotoDropzone.jest.tsx

As discussed with Barney and Ole, adjust the add photos page to make the uploaded images more visible when working with smaller screens
| iPhone SE | iPhone 12 Pro | iPad Pro |
| --- | --- | --- |
| <img width="374" alt="image" src="https://github.com/artsy/force/assets/36167539/5dd08310-31ce-457a-b6e6-32c38ccc6743"> | <img width="388" alt="image" src="https://github.com/artsy/force/assets/36167539/12ef4f48-4381-4803-94f3-4dd8c8f26a7a"> | <img width="511" alt="image" src="https://github.com/artsy/force/assets/36167539/80170941-c8a4-4d83-ab8a-c0030c73993c"> |
Also, adjust the photos drop component on the artwork add/edit page
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …

fix: adjust add photos page

---

src/Apps/Sell/Components/SubmissionLayout.tsx

Follow-Up for https://github.com/artsy/force/pull/14141
With this change, the Sell flow layout centers the content on large screens and keeps the larger scroll area introduced in https://github.com/artsy/force/pull/14141.
| --- | --- |
|![Screenshot 2024-07-04 at 11 28 53](https://github.com/artsy/force/assets/4691889/ce4b0101-cc27-4ec6-adc3-6b646ab7ea7e) |![Screenshot 2024-07-04 at 11 29 03](https://github.com/artsy/force/assets/4691889/e64f896e-0a61-4a45-914a-a59791d81467) |

fix: Center Sell flow layout on large screens

---

src/Apps/Sell/Routes/PurchaseHistoryRoute.tsx
src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
src/Apps/Sell/Utils/formUtils.ts

Addresses this [Notion ticket](https://www.notion.so/artsy/Is-this-the-correct-default-state-of-the-drop-down-Or-should-it-have-Purchase-information-inside--80be530b056b4bf5a5111b8cb2e99aef?pvs=4)
Add Select option to the Select component values to display empty value correctly

fix: add Select option to the Select component values

---

src/Apps/Sell/Components/ImagePreviewsGrid.tsx

Solves https://www.notion.so/artsy/Photo-upload-given-that-on-small-screens-the-whole-grid-of-uploaded-photos-is-not-visible-does-it-828252b08d5049cbad9ae71b734a2ccb?pvs=4
Display preview images in reverse order in the Sell flow to ensure that the most recent photos are always visible. This is helpful when many photos are uploaded and not all preview images fit on the screen.

fix: Display preview images in reverse order in Sell flow

---

src/Apps/Sell/Components/ImagePreviewItem.tsx

Solves https://www.notion.so/artsy/Mweb-Photo-Upload-The-X-button-to-delete-a-photo-is-invisible-when-the-uploaded-image-is-black-871fc50a3e3c42309e2144d3131e3178?pvs=4
This adds a white background color to the "Delete photo" x button to make ensure it's visible on dark images.
| --- | --- |
|<img width="623" alt="Screenshot 2024-07-04 at 19 22 55" src="https://github.com/artsy/force/assets/4691889/b5106263-34fd-4c3a-b24f-fc450a04087f"> |<img width="619" alt="Screenshot 2024-07-04 at 19 22 20" src="https://github.com/artsy/force/assets/4691889/0cb587ee-7e51-4321-9dae-dc093248d242"> |

fix: Add background color to delete photo button on Sell flow

---

src/Apps/Sell/Components/UploadMoreMessage.tsx

Adding a fading animation to the Sell flow "Photo" step message to make it appear a bit smoother when removing an image.

fix: Add fading animation to Sell flow photo step message

---

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilters.jest.tsx
src/Apps/ArtistSeries/__tests__/ArtistSeriesArtworksFilter.jest.tsx
src/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx
src/Apps/Collect/Routes/Collection/Components/__tests__/CollectionArtworksFilter.jest.tsx
src/Apps/Fair/Routes/FairArtworks.tsx
src/Apps/Gene/Components/__tests__/GeneArtworkFilter.jest.tsx
src/Apps/Partner/Routes/__tests__/Works.jest.tsx
src/Apps/Search/Components/SearchResultsArtworksFilters.tsx
src/Apps/Show/__tests__/ShowArtworks.jest.tsx
src/Apps/Tag/Components/__tests__/TagArtworkFilter.jest.tsx
src/Components/ArtworkFilter/ArtworkFilters/AvailabilityFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/AvailabilityFilter.jest.tsx
src/Components/ArtworkFilter/ArtworkFilters/index.tsx

This PR solves [ONYX-887]
This PR implements the recommendations in [ONYX-887][] and rolls out the availability filter to the following artwork grids:
- Standard artwork grids (Artist series, Artworks (/collect), Gene, Show, Tag)
- Fair
- Marketing Collection
- Search Results
This repurposes the existing `onyx_availability-filter` Unleash feature flag so before deploy we should switch that to staging only so we can poke around other grids before a user-facing release on production.
[ONYX-887]: https://artsyproduct.atlassian.net/browse/ONYX-887

feat: add availability filter to other artwork grids

---

src/Apps/Sell/Components/SubmissionHeader.tsx

This PR solves https://www.notion.so/artsy/Position-of-Save-Exit-is-not-right-aligned-with-the-rest-of-the-content-0ee4259ccf544af98a62bf693c198bad?pvs=4
Align Sell flow exit button on mobile.
| --- | --- |
|<img width="412" alt="Screenshot 2024-07-08 at 10 06 21" src="https://github.com/artsy/force/assets/4691889/d3e418ec-84b6-4ed2-8ba5-222b41e1544a"> | <img width="416" alt="Screenshot 2024-07-08 at 10 04 42" src="https://github.com/artsy/force/assets/4691889/2c36d898-78df-44d8-be2c-3a57698b448e">|

fix: Align Sell flow exit button on mobile

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/HeaderSWA.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviousSubmission.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAFooter.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SWAStickyFooter.tsx
src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HeaderSWA.jest.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWASection.jest.tsx
src/Apps/Sell/Components/StepsNavigation.tsx
src/Apps/Sell/Routes/ArtistNotEligibleRoute.tsx
src/Apps/Sell/Routes/ArtistRoute.tsx
src/Apps/Sell/Routes/IntroRoute.tsx
src/Apps/Sell/Routes/ThankYouRoute.tsx
src/Apps/Sell/Routes/__tests__/ArtistNotEligibleRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/PhoneNumberRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/PhotosRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx
src/Apps/Sell/SellFlowContext.tsx
src/Apps/Sell/sellRoutes.tsx

Solves https://artsyproduct.atlassian.net/browse/ONYX-1106
This updates all the routes for the new Sell flow from `/sell2` to `/sell`. We want to do this before the release to ensure screen tracking works as expected.
There is already a ticket for cleaning up the old `/sell` routes ([ONYX-1074](https://artsyproduct.atlassian.net/browse/ONYX-1074)).
[ONYX-1074]: https://artsyproduct.atlassian.net/browse/ONYX-1074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Replace new Sell flow routes: `/sell2` - `/sell`

---

src/Apps/ArtAdvisor/07-Curated-Discovery/Components/Form/Interests.tsx

Per [this comment](https://artsy.slack.com/archives/C06SSV1K10D/p1720551004527469?thread_ts=1720550997.373359&cid=C06SSV1K10D), this just slims down and slightly rationalizes the list of interests. 
Nothing gospel here, just an incremental improvement before the next demo.

feat(ai): simplify the list of interests

---

src/Apps/Partner/Components/Overview/ArticlesRail.tsx
src/__generated__/ArticlesRail_partner.graphql.ts
src/__generated__/partnerRoutes_OverviewQuery.graphql.ts

This PR solves the issue reported [here](https://artsy.slack.com/archives/C03N12SR0RK/p1720172832143009)
Articles displayed on the partner profile page are not sorted, which means they use the [upstream default](https://github.com/artsy/positron/blob/9ea829fefe6bb1118131c0fc3ff429e357507afe/src/api/apps/articles/model/retrieve.js#L189-L191) of sorting by _last updated_ date, instead of the _publication_ date.
The updated date often matches the published date — but not always, as the report shows. We should instead by explicitly requesting these articles in order of publish date.
Note that we already do this everywhere else we request articles — the current case must have just been an oversight 🙈

fix(partner): explicitly request articles sorted by pub date

---

src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Components/StepsNavigation.tsx
src/Apps/Sell/Components/SubmissionHeader.tsx
src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
src/Apps/Sell/Routes/SubmissionRoute.tsx
src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/PhoneNumberRoute.jest.tsx
src/Apps/Sell/SellFlowContext.tsx

Request from @daytavares  
Currently, we send the submission's `externalID` when tracking Sell flow events. Instead, we need to use the internal submission ID.

chore: Use submission's `internalID` for Sell flow tracking

---

src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
src/Apps/Sell/Routes/ThankYouRoute.tsx
src/Apps/Sell/Routes/__tests__/AdditionalDocumentsRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/ArtistRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/ConditionRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/DetailsRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/DimensionsRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/FrameRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/IntroRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/NewRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/PhoneNumberRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/PhotosRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/PurchaseHistoryRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/ShippingLocationRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx
src/Apps/Sell/Routes/__tests__/TitleRoute.jest.tsx
src/Apps/Sell/SellFlowContext.tsx
src/__generated__/ThankYouRoute_Test_Query.graphql.ts
src/__generated__/ThankYouRoute_submission.graphql.ts
src/__generated__/sellRoutes_ThankYouRouteQuery.graphql.ts

With this change, we link directly to the MyC artwork page instead of the MyC artwork grid on the Sell flow "Thank You" step.

feat: Navigate to MyC artwork page on Sell flow thank you step

---

src/Apps/Order/Components/ArtworkSummaryItem.tsx
src/Apps/Order/Utils/currencyUtils.ts

This should resolve [EMI-1843](https://artsyproduct.atlassian.net/browse/EMI-1843)
The solution here is pretty ugly but I think we need to maintain this custom function here as we can not use just streight 'saleMessage' for the artwork from the server. Sometimes this list price is not really the list price but rather 'last negotiated price' (there is a separate ticket to figure out proper display name here). But for now just modify this value client side to account for possible 'Under ' prefix there.
Before: 
After:
Also in the process I encountered a strange crash with works with very high value. Seems like in this case for whatever reason the server does not give us partner information(?!) - did not track the cause but made UI a bit more bullet proof if that is the case.
[EMI-1843]: …

fix: make manual prepending of US account for possibility of 'under' in price

---

src/Apps/ArtAdvisor/08-Art-Quiz/server.ts

This PR patches #14194 to correctly handle disliked artworks. We are currently persisting all choices as "liked" so this will correct the bug and should improve the recommendation results.

fix: handle disliked artworks correctly

---

src/Components/Notifications/__tests__/NotificationsList.jest.tsx
src/Components/Notifications/__tests__/util.jest.ts
src/Components/Notifications/util.ts

This PR solves https://artsy.slack.com/archives/C05EQL4R5N0/p1721034091096429
We should filter out `null` notifications in the Activity panel. This PR fixes the types of `shouldDisplayNotification` and adds a check that filters out `null` notifications to avoid the following error:

fix: Filter out null notifications in Activity panel        

---

src/System/Components/PageLoadingBar.tsx

Somewhat endless faffing on this one. This animates things in from the left a bit, so that the fade in doesn't feel so abrupt.

chore(loading-bar): Less fade

---

src/System/Components/PageLoadingBar.tsx

Noticed that the loading bar was a bit shaky on safari, so moved the css animations to the GPU via `transform`.

fix(loading-bar): Improve perf for safari

---

src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Components/SubmissionHeader.tsx
src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx
src/Apps/Sell/Mutations/useAssociateSubmission.tsx
src/Apps/Sell/Routes/ArtistRoute.tsx
src/Apps/Sell/Routes/PhoneNumberRoute.tsx
src/Apps/Sell/Routes/__tests__/PhoneNumberRoute.jest.tsx
src/Apps/Sell/SellFlowContext.tsx
src/Apps/Sell/sellRoutes.tsx
src/Utils/Hooks/useAuthIntent/__tests__/useAuthIntent.jest.ts
src/Utils/Hooks/useAuthIntent/index.tsx
src/__generated__/sellRoutes_ArtistRouteQuery.graphql.ts
src/__generated__/sellRoutes_DetailsRouteQuery.graphql.ts
src/__generated__/sellRoutes_DimensionsRouteQuery.graphql.ts
src/__generated__/sellRoutes_PhoneNumberRouteQuery.graphql.ts
src/__generated__/sellRoutes_PhotosRouteQuery.graphql.ts
src/__generated__/sellRoutes_PurchaseHistoryRouteQuery.graphql.ts
src/__generated__/sellRoutes_SubmissionRouteQuery.graphql.ts
src/__generated__/sellRoutes_ThankYouRouteQuery.graphql.ts
src/__generated__/sellRoutes_TitleRouteQuery.graphql.ts
src/__generated__/useAssociateSubmissionMutation.graphql.ts

Defer auth prompt to either "Save and Exit" or "Submit Artwork".
| Name | Video |
| Before | <video src="https://github.com/user-attachments/assets/7b28c20e-5eaa-4b1e-90d5-8c8114d107e6" /> |
| After (Save & Exit) | <video src="https://github.com/user-attachments/assets/e5aac9a9-5598-438d-b1b9-a34f44d6e259" /> |
| After (Submit) | <video src="https://github.com/user-attachments/assets/35b6ca48-6dae-4298-bd12-5e974ed1c1e0" /> |

chore: defer auth prompt in redesigned submission flow

---

src/Server/middleware/__tests__/graphqlProxyMiddleware.jest.ts
src/Server/middleware/graphqlProxyMiddleware.ts

Fixes an issue observed in staging (from https://github.com/artsy/force/pull/14247) around uncompressed responses from MP not being persisted to redis. Handles that case.

fix(caching): Handle uncompressed cases from MP

---

src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetails.tsx
src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetailsForm.tsx
src/Apps/Order/Routes/Shipping2/Components/__tests__/FulfillmentDetailsForm.jest.tsx
src/Apps/Order/Routes/Shipping2/Utils/shippingUtils.ts
src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx

This PR solves [EMI-1957]
This PR fixes a bug where you cannot switch from pickup back to shipping if the order loads with a saved pickup fulfillment. The issue was that we were resetting the form to its initial values when changing from pickup to shipping, but those initial values were for a pickup fulfillment if that was what was saved to the order.
Added tests as todos, but existing tests passed.
[EMI-1957]: https://artsyproduct.atlassian.net/browse/EMI-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: switching from saved pickup back to shipping

---

package.json

Per [this comment](https://github.com/artsy/force/pull/14254#discussion_r1696845308), this removes the cache invalidation on deploy in favor of adding our release number to the cache key.

ci(deploys): dont bust cache on deploy

---

src/Apps/Sell/Routes/__tests__/ConditionRoute.jest.tsx
src/Apps/Sell/SellFlowContext.tsx

Addresses [ONYX-1146]
- Related Eigen PR: https://github.com/artsy/eigen/pull/10512
We want to set the submission state to "RESUBMITTED" when completing the Tier 2 submission flow (similar to when the user completes the Tier 1 flow and we set the state to "SUBMITTED").
[ONYX-1146]: https://artsyproduct.atlassian.net/browse/ONYX-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Set submission state when completing tier 2 flow

---

hokusai/production.yml
hokusai/staging.yml

https://github.com/artsy/substance/pull/395 makes k8s-internal clients hit Force directly, bypassing Cloudflare. Force sees this traffic coming from k8s IPs.
Ingress allow-list currently allows Cloudflare IPs only. This PR adds k8s IPs.

feat: in addition to cloudflare IPs, allow k8s internal IPs

---

src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Routes/AdditionalRoutes/ConditionRoute.tsx

This PR solves https://www.notion.so/artsy/Condition-Definition-link-on-the-field-should-match-the-design-system-spacing-see-image-f641d103ac3b430cb48dbf2ed415b9cd?pvs=4
This PR fixes the Sell flow Condition step link styling.
| --- | --- |
|<img width="871" alt="Screenshot 2024-08-01 at 11 23 54" src="https://github.com/user-attachments/assets/1a314332-1090-48bf-9557-24db88a99a73"> |<img width="777" alt="Screenshot 2024-08-01 at 11 22 58" src="https://github.com/user-attachments/assets/ad9e684f-74b3-4683-945d-b2d7c674f6b2">| 

fix: Sell flow Condition step link styling

---

src/Apps/Sell/Routes/ArtistNotEligibleRoute.tsx
src/Apps/Sell/Routes/__tests__/ArtistNotEligibleRoute.jest.tsx
src/Apps/Sell/sellRoutes.tsx

This PR solves [ONYX-1145](https://artsyproduct.atlassian.net/browse/ONYX-1145)
- feat: prompt for authentication for SWA > Add to MyC
After selecting an artist ineligible for submission, we suggest that the user
can add the artwork to My Collection instead. Since those surfaces require
authentication, trigger the auth modal in response to that button click.
- feat: redirect to login page if navigating to authenticated SWA route
Applies some server-side redirects if we're navigating to /sell route known to
require authentication.
[ONYX-1145]: https://artsyproduct.atlassian.net/browse/ONYX-1145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://github.com/user-attachments/assets/0b93cc04-a472-4219-b2e9-4eece4 …

feat: prompt for authentication for SWA > Add to MyC

---

src/Apps/Sell/Routes/AdditionalRoutes/AdditionalDocumentsRoute.tsx
src/Apps/Sell/Routes/__tests__/AdditionalDocumentsRoute.jest.tsx

Resolves https://www.notion.so/artsy/A-user-should-be-able-to-move-past-Additional-Documents-without-uploading-a-document-28d98971106f465cb59dd1339c0ca6bd?pvs=4
Make additional documents optional in Sell flow and change title to match other steps.

fix: Make additional documents optional in Sell flow

---

src/Apps/Sell/Components/SubmissionHeader.tsx
src/Apps/Sell/Routes/SubmissionRoute.tsx
src/__generated__/AdditionalDocumentsRoute_Test_Query.graphql.ts
src/__generated__/ArtistRoute_Test_Query.graphql.ts
src/__generated__/ConditionRoute_Test_Query.graphql.ts
src/__generated__/DetailsRoute_Test_Query.graphql.ts
src/__generated__/DimensionsRoute_Test_Query.graphql.ts
src/__generated__/FrameRoute_Test_Query.graphql.ts
src/__generated__/PhoneNumberRoute_Test_Query.graphql.ts
src/__generated__/PhotosRoute_Test_Query.graphql.ts
src/__generated__/PurchaseHistoryRoute_Test_Query.graphql.ts
src/__generated__/ShippingLocationRoute_Test_Query.graphql.ts
src/__generated__/SubmissionRoute_submission.graphql.ts
src/__generated__/ThankYouRoute_Test_Query.graphql.ts
src/__generated__/TitleRoute_Test_Query.graphql.ts
src/__generated__/sellRoutes_SubmissionRouteQuery.graphql.ts

Resolves https://www.notion.so/artsy/When-submitting-a-MyC-artwork-should-Save-Exit-navigate-back-to-the-artwork-Currently-it-opens--ebdf272100c94666ba75b1c943097327?pvs=4
Navigate to My Collection artwork page on the "Save & Exit" when associated My Collection artwork is present.

fix: Navigate to My Collection artwork page on the Sell flow "Save & Exit"

---

docs/caching.md
src/Apps/Artist/artistRoutes.tsx
src/Apps/ArtistSeries/artistSeriesRoutes.tsx
src/Apps/Artists/artistsRoutes.tsx
src/Apps/Auction/auctionRoutes.tsx
src/Apps/Categories/categoriesRoutes.tsx
src/Apps/Collect/collectRoutes.tsx
src/Apps/Gene/geneRoutes.tsx
src/Apps/Partners/partnersRoutes.ts
src/Apps/Sale/saleRoutes.tsx
src/Apps/serverCacheTTLs.tsx

In an effort to improve our cache hit rate, this bumps our server-side TTLs for a number of routes via a new `Apps/serverCacheTTLs.tsx` index file. Most of these choices I believe are uncontroversial but let me know if anything should be tweaked, or if I missed a route that should be bumped up more appropriately!

chore(cache): Update TTLs / docs

---

src/Apps/Auction/Components/AuctionArtworkFilter.tsx
src/Apps/Auction/Components/__tests__/AuctionArtworkFilter.jest.tsx
src/Components/ArtworkFilter/ArtworkFilters/Utils/useFilterSelectResults.ts

This PR was inspired by this hackathon 14 project [suggestion](https://www.notion.so/artsy/Add-shoppable-curated-collections-like-gems-on-paper-or-small-and-special-and-better-filter-op-710f2df614484eae90fc57fecabcef9c?pvs=4) to include more filter options for auction artworks, which has significantly less than our other artwork surfaces. After spiking on this work, it seems like we can extend the auction artwork filter options with pre-existing filters (size, materials, time period and colors) with very few code changes. 
**In fact, there are so few code changes required, I'm wondering if we have limited the filter options intentionally? Any insight on this would be appreciated. If not, this seems like an easy win.**
| auctions | fairs |
| ------------- | …

feat: expand auction artworks filter options

---

src/Server/middleware/__tests__/graphqlProxyMiddleware.jest.ts
src/Server/middleware/graphqlProxyMiddleware.ts
src/System/Relay/createRelaySSREnvironment.ts
src/System/Relay/middleware/cacheLoggerMiddleware.ts

This adds a tiny log on the client for debugging cache hits. Maybe we can also do something with this flag analytics-wise / in volley? We can remove this once things stabilize:

feat(cache): Add cache logger middleware

---

src/Utils/Hooks/useAuthValidation.ts

We should never cache the auth validation query since that manages invalid token behavior.

fix(caching): Dont cache auth check

---

src/System/Relay/getMetaphysicsEndpoint.ts
src/middleware.ts

- Closes https://github.com/artsy/force/pull/14292
When logged in, we directly hit metaphysics, vs going through the proxy. This helps address the issue described in https://github.com/artsy/force/pull/14292, but in a simpler and less trap-like way.

fix(proxy): Only use the proxy if logged out

---

src/Server/middleware/__tests__/graphqlProxyMiddleware.jest.ts
src/Server/middleware/graphqlProxyMiddleware.ts

Ran into an issue with https://github.com/artsy/force/pull/14306 due to the proxy middleware being above passport, which injects `req.user` (ie, logged-in) into the req/res cycle. With the middleware above it, we lost access to this property, which then led to erroneous cache behavior. 
This fixes things by instead checking for our x-access-token header, which is present regardless of passport. 
https://github.com/user-attachments/assets/f0e95e0a-e9ef-4781-a80f-1b3af9fd2b02

fix(proxy): Use X-Access-Token for checking logged-in

---

cypress/e2e/artist.cy.ts

Points our artist smoke test at an artist with less data to get around staging artist/id problem and reenable deploys. Will switch this back to a bigger-name artist once staging is deployed with https://github.com/artsy/force/pull/14318

chore(smoke-tests): point at artist with less data

---

cypress/e2e/artist.cy.ts

Now that staging is deployed with the new `errors` check for the cache, undo the temporary smoke test change so that we can diagnose whats going on with metaphysics staging, under a completely-filled-out artist/id page.
The issue is intermittent on staging; will try to get this merged so as to best reflect the current state of things.

chore(smoke-tests): undo temp change

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkHeader.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkHeader.jest.tsx
src/__generated__/MyCollectionArtworkHeaderTestQuery.graphql.ts
src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts

This PR solves [Notion card](https://www.notion.so/artsy/app-web-The-edit-artwork-CTA-needs-to-be-removed-for-any-myC-artworks-that-are-submitted-for-sale-da171fb6b103459aaa1d6ac91c1fa0e8?pvs=4): remove the edit artwork CTA for any myC artworks that is submitted for sale

fix: hide edit button if submission

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
src/Apps/Sell/SellFlowContext.tsx

Resolves https://www.notion.so/artsy/Web-We-should-not-allow-the-user-to-edit-artwork-s-Artist-and-title-13745a26be404bd5b9c0f5755dd31693?pvs=4
With this change, we link to the Title step instead of the Artist step when editing a submission. This approach discourages users from updating the artist of an already existing submission.

fix: Do not link to artist step when editing submissions

---

src/Server/passport/lib/app/lifecycle.ts
src/Server/passport/test/app/lifecycle.jest.js

Looking through our datadog logs noticed that a lot of 500ish errors come from `sign_in` / `sign_up`. Digging in, noticed that we're sending 500s for 400-ish errors. This fixes that. 
Let me know if we should have more fine-grained status codes here.

fix(auth): Signin / Signup no longer 500 -> 4x

---

src/Apps/Sell/Components/SubmissionHeader.tsx

Resolves https://www.notion.so/artsy/Web-User-can-just-quit-the-flow-without-a-warning-should-we-add-an-alert-65052f96a3114861bd8da809d036ac24?pvs=4
Make the Artsy logo unclickable in the Sell flow header.

fix: Make Artsy logo unclickable in Sell flow header

---

src/Apps/Sell/Routes/ThankYouRoute.tsx
src/Apps/Sell/Routes/__tests__/ThankYouRoute.jest.tsx

Resolves https://www.notion.so/artsy/Web-Fulfil-or-Fulfill-f36f9af164cb4f59956b325a52a74511?pvs=4
`fulfil` -> `fulfill`.

fix: `fulfil` -> `fulfill`

---

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/PreviousSubmission.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
src/Apps/Sell/SellFlowContext.tsx

With this change, we also display the previous submission on the Sell page when it is in the `APPROVED` state. With this change, I consider `draft` and `approved` submissions as non-completed submissions (`PRE_SUBMITTED_STEPS`) that require additional information.

fix: Display previous submission on Sell page when in APPROVED state

---

src/Server/middleware/__tests__/graphqlProxyMiddleware.jest.ts
src/Server/middleware/graphqlProxyMiddleware.ts

Currently, a graphql response can be cached by one release, and served by a later release. That's fine, and even intentional, as long as the query hasn't changed. If the query has changed, cached responses to the old query should be invalidated. This PR adds a `digest` property to the cache key that's computed over the query itself. When a query changes, the digest will change and requests will be cache misses until the updated query's responses are cached.
Those old responses will be evicted by redis in the usual course of things. This also allows review apps to employ slightly different queries with the same identifier. Their responses will be cached in isolation.
Example verbose logging output:
```
[1] [graphqlProxyMiddleware # writeCache] 
[1] …
```

fix: ensure cached graphql responses are invalidated upon query changes

---

src/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethods.tsx
src/Apps/Settings/Routes/__tests__/SettingsPaymentsRoute.jest.tsx

Reverts https://github.com/artsy/force/pull/14046, now that other safeguards have proven effective. This also fixes a typo in the original copy.
Follow-up to: https://artsyproduct.atlassian.net/browse/PHIRE-1013

fix: allow all accounts to add cards (reverts #14046)

---

src/Apps/Sell/Components/BottomFormNavigation.tsx
src/Apps/Sell/Components/SubmissionLayout.tsx

Addresses [ONYX-1196]
This change makes the bottom navigation of the Sell flow transparent, allowing the content below the fold to be visible to users.
[ONYX-1196]: https://artsyproduct.atlassian.net/browse/ONYX-1196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Make Sell flow bottom navigation transparent

---

.circleci/config.yml
.gitignore
Dockerfile
package.json
relativeci.config.js
webpack/envs/clientProductionConfig.js
yarn.lock

Closes [DIA-793](https://artsyproduct.atlassian.net/browse/DIA-793)
We need to generate size diffs for bundle reports on pull requests. Testing out [relative-ci.com](https://relative-ci.com/) — free for open source.
[DIA-793]: https://artsyproduct.atlassian.net/browse/DIA-793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: adds relative-ci agent

---

src/Components/Onboarding/Components/OnboardingDialog.tsx
src/Components/Onboarding/Hooks/useOnboarding.tsx

Closes [DIA-796](https://artsyproduct.atlassian.net/browse/DIA-796)
Similar to https://github.com/artsy/force/pull/14351 — just separating out a large network of imports that isn't needed on every page. Here we obviously only need the onboarding experience once on sign up.
[DIA-796]: https://artsyproduct.atlassian.net/browse/DIA-796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: separates out and lazy loads onboarding code

---

src/Apps/Conversations/components/ConversationLayout.tsx
src/Apps/Sell/Routes/IntroRoute.tsx

This PR solves [ONYX-1197](https://artsyproduct.atlassian.net/browse/ONYX-1197)
Make sure the Sell Flow intro page CTAs are visible on all window sizes by setting a maximum height to the container.
| --- | --- |
|<img width="1135" alt="Screenshot 2024-08-20 at 11 14 45" src="https://github.com/user-attachments/assets/6a3ab275-ccdd-47bd-9447-d6e1850ff9e3"> | <img width="1135" alt="Screenshot 2024-08-20 at 11 14 33" src="https://github.com/user-attachments/assets/9c3d38f7-0a7e-45f4-84b4-2b7386de83ab">|
[ONYX-1197]: https://artsyproduct.atlassian.net/browse/ONYX-1197?atlOrigin=eyJpIjoiNWRkNT …

fix(ONYX-1197): Make sure Sell flow intro page CTAs are visible on all window sizes

---

package.json
yarn.lock

This PR removes `eslint-plugin-graphql`, which appears [unused](https://github.com/artsy/force/blob/main/.eslintrc.js#L4-L11), and bumps `ws` to >= `7.5.10` in order to resolve a [security vulnerability](https://github.com/artsy/force/security/dependabot/170).

chore: remove eslint-plugin-graphql

---

src/Components/Artwork/Details.tsx

This fixes the artist line overflow for the art cards. 
BEFORE
AFTER

fix: details artist line overflow

---

src/Apps/Order/Routes/Shipping2/Components/FulfillmentDetails.tsx

Believe this fixes: [EMI-1939](https://artsyproduct.atlassian.net/browse/EMI-1939)
If I understand the current flow correctly - the only way we can end up on a shipping step with the shipping details already saved on the order is if the page is reloaded with address already saved on order but this address is not saved as a default user addresses. In this case we should fall back to checking 'saveAddress' on the form to be true as if the user clicks 'save and continue' we want the address to be preserved in settings.
I might be missing some cases here but I believe that is a legit change here.
[EMI-1939]: https://artsyproduct.atlassian.net/browse/EMI-1939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: if form ends up on the shipping step with details saved the address should save by default

---

src/Apps/Search/Routes/SearchResultsArtists.tsx
src/__generated__/SearchResultsArtistsQuery.graphql.ts
src/__generated__/SearchResultsArtists_viewer.graphql.ts
src/__generated__/searchRoutes_SearchResultsArtistsQuery.graphql.ts

Noticed that we weren't using the artists cover image, via this [bug report](https://artsy.slack.com/archives/C03N12SR0RK/p1724348520629639). 
Now, coverImage, then fallback, then none. 

fix(search): Use coverImage first, then fallback

---

src/Components/Artwork/Details.tsx

The type of this PR is: FIX
By trying to fix the overflow issue I messed up the partner offer signal. Looks like it was a regression with the partner offer implementation after all. I'm going to revert my change and then push up another PR to with the overflow. Sorry y'all
<!-- If applicable, write the Jira ticket number in square brackets e.g. `[GRO-434]`
The Jira integration will turn it into a clickable link for you. --
By trying to fix the overflow issue I messed up the partner offer signal. Looks like it was a regression with the partner offer implementation after all. I'm going to revert my change and then push up another PR to with the overflow. 
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

fix: revert artwork details overflow fix

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASubmissionStatus.tsx
src/Apps/Sell/SellFlowContext.tsx

This PR solves [ONYX-1154](https://artsyproduct.atlassian.net/browse/ONYX-1154)
* [Slack Thread with discussion](https://artsy.slack.com/archives/C05EQL4R5N0/p1723540029364359?thread_ts=1723539761.516339&cid=C05EQL4R5N0)
With this PR, we allow overriding the submission state in the Sell flow to be able to access the post-approval Sell flow without having to approve a submission in Convection. This is for testing purposes only and allows us to test the new flow without admin access in Convection, which could create security issues.
[ONYX-1154]: https://artsyproduct.atlassian.net/browse/ONYX-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore: add sell flow test submission state query param for Integrity tests

---

src/Apps/Order/Routes/Shipping2/Components/AddressModal2.tsx
src/Apps/Order/Routes/Shipping2/Components/SavedAddresses2.tsx
src/Apps/Order/Routes/Shipping2/Components/__tests__/AddressModal2.jest.tsx

This PR solves [EMI-1935]
This PR accomplishes a but where the address modal does not show a country on render for two reasons [[slack](https://artsy.slack.com/archives/C2TQ4PT8R/p1724882978745289) 🔒]
- For new addresses, we need to get the default country from the order's possible locations. We start with the location of the artwork.
- For updating addresses, the value actually was already there, but not rendered correctly. This is fixed by not rendering the modal until the address modal actually has something to do and real initial values are ready.
[EMI-1935]: https://artsyproduct.atlassian.net/browse/EMI-1935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-1935): Prefill address modal country and make sure it is visible

---

src/System/Relay/createRelaySSREnvironment.ts
src/System/Relay/middleware/cacheHeaderMiddleware.ts

In preparation for experimenting with a CDN in front of Metaphysics (which would eventually supplant Force's proxy + cache setup) - this adds 'standard' caching headers when we want to skip the cache.
We've experimented with proving out that our CDN _will_ respect this standard header.
So, effectively mimicking Force's determination on whether the cache should be skipped for a particular query - logged in (which the CDN will also skip via existence of the access token header - but might as well include that check) - as well as queries that have been set to skip the cache via config.
In practice - there's not a _ton_ of places that skip the cache b/c of `cacheConfig` while logged out:
- auth query in https://github.com/artsy/force/blob/c6bcf0255d4f6a1c733903580f881a8aea3fd6dd/src/Utils/Hook …

chore: set Cache-Control: no-cache header appropriately on proxied MP req

---

src/Apps/Order/Routes/Shipping2/Components/SavedAddresses2.tsx
src/Apps/Order/Routes/Shipping2/__tests__/Shipping2.jest.tsx

This is a second case I found that should fix https://artsyproduct.atlassian.net/browse/EMI-1939
It's a bit roundabout way to fix it but I believe it's a proper condition to call this `useEffect` regardless of this bug even. But looks like it works here because when the last address deleted on the page the length of addresses change and the previous case that I fixed (default to save address when address is present on the order but there is no addresses in context - default to save address).
It's all a bit confusing but seems to work. Also not sure how to test any of this stuff cause the setup is pretty complicated. But maybe can tested with integration run after.

chore: second part of defaulting to save address.

---

src/Components/Inquiry/Views/InquiryArtistsInCollection.tsx
src/Components/Inquiry/Views/InquiryBasicInfo.tsx
src/Components/Inquiry/__tests__/Views/InquiryBasicInfo.jest.tsx

This PR updates the post-inquiry prompts to fire a mutation that will update the "last update prompt at" timestamp when the prompt is displayed. Updating this timestamp will prevent the user from being prompted to update their profile for 30 days if they don't complete the prompt.

feat: update "last update prompt at" timestamp when user sees post-inquiry prompts

---

package.json
yarn.lock

This PR bumps `@babel/plugin-transform-runtime` to `7.23.2` to address security vulnerability `CVE-2023-45133`. [Dependabot](https://github.com/artsy/force/security/dependabot/161).

chore: bump @babel/plugin-transform-runtime to 7.23.2

---

src/System/Relay/middleware/searchBarImmediateResolveMiddleware.ts

This is silly, but we have precedence for it - apparently this component has fired 'empty' queries for a while?!
At some point, the name of the query changed - so this simple thing fixes it.
I tried to put the query name in a constant for a single source of truth, but you can't do string interpolation within the `graphql` tags [here](https://github.com/artsy/force/blob/db4e4a8c6a800e3f081530f3f9b1a80ce1a498ca/src/Components/Search/SearchBarInput.tsx#L336).
Of course a question about _why_ the component behaves like this is valid - but this is a complicated custom input component that's owned by Onyx, so any larger tweak should sit with them. Since there's already precedent to suppress the query and it just had the wrong name, making that small change.
Confirmed locally this query no …

chore: immediately resolve empty search bar queries

---

src/System/Relay/middleware/searchBarImmediateResolveMiddleware.ts

Reverts artsy/force#14445
This fixes the issue (intercepts the empty query), but the shape of the resolved data is probably not 100% accurate leading to some Relay warnings.
The component should be patched by https://artsyproduct.atlassian.net/browse/ONYX-1281

Revert "chore: immediately resolve empty search bar queries"

---

src/Apps/Auctions/Routes/CurrentAuctions.tsx
src/Apps/Auctions/Routes/PastAuctions.tsx
src/Apps/Auctions/Routes/UpcomingAuctions.tsx
src/__generated__/CurrentAuctionsQuery.graphql.ts
src/__generated__/CurrentAuctions_Test_Query.graphql.ts
src/__generated__/CurrentAuctions_viewer.graphql.ts
src/__generated__/PastAuctionsQuery.graphql.ts
src/__generated__/PastAuctions_Test_Query.graphql.ts
src/__generated__/PastAuctions_viewer.graphql.ts
src/__generated__/UpcomingAuctionsQuery.graphql.ts
src/__generated__/UpcomingAuctions_Test_Query.graphql.ts
src/__generated__/UpcomingAuctions_viewer.graphql.ts
src/__generated__/auctionsRoutes_Current_AuctionsQuery.graphql.ts
src/__generated__/auctionsRoutes_Past_AuctionsQuery.graphql.ts
src/__generated__/auctionsRoutes_Upcoming_AuctionsQuery.graphql.ts

Also switches the other rails to be a query renderer just in case, on /auctions.
Locally the page is really fast now!

chore: remove unneeded fragment since a QueryRenderer is being used

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarShippingInformation.tsx
src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx

Similar to https://github.com/artsy/metaphysics/pull/5995, the "learn more" link in the shipping and taxes section of the artwork page is broken. The team has merged some articles and this updates the link accordingly.
See [Slack](https://artsy.slack.com/archives/C03N12SR0RK/p1726063808864249?thread_ts=1725961290.888429&cid=C03N12SR0RK) for context.

fix: update help article link for taxes

---

src/Components/AuthDialog/Views/AuthDialogWelcome.tsx

I had misunderstood what this analytics property was doing. Intent is set on the _initial_ click that opens the dialog. It's not what action you ultimately wind up taking in the dialog.

fix(auth): removes dynamic setting of intent

---

src/Components/AuthDialog/Hooks/useCountryCode.ts

Not sure if I did this correctly, but it seems to work in my local testing.
According to [relay docs](https://relay.dev/docs/guided-tour/reusing-cached-data/fetch-policies/), `store-or-network` is the default fetch policy, so hopefully we don't need that. With or without it, this query to geocode an IP address to a country gets a `force: true`, which ends up sending the `Cache-Control: no-cache` header. Setting `force: false` has the effect of removing that header and allowing the result (a single country) to be cached. I think that's OK, as IP<>country mappings don't change that often.

fix: allow caching of IP geocoding queries (DIA-844)

---

pull_request_template.md

This specific Jira ticket (an epic) has become linked to many pull requests because it's referenced in the example reference:
https://artsyproduct.atlassian.net/browse/GRO-434
This commit updates the example reference to one that's simply instructional and will not trigger the actual linking logic.

docs: update example Jira reference in PR template

---

src/Apps/Home/Components/HomeCurrentFairs.tsx

This PR adds an elipses to overflowing text on the home screen view of current fairs to address an issue where the fair name is one very long string without whitespace.

fix:add elipses for long fair names

---

src/Apps/Collect/Routes/Collect/index.tsx
src/Apps/Collect/Routes/Collection/index.tsx
src/Components/ArtworkGrid/ArtworkGrid.tsx

Fixes issue where clicking an artwork grid item on collection/id would lead to a page flash rerender. This fixes that by leveraging found's StaticContainer, which will only rerender when there are route elements to display (which isn't true if a route is transitioning).

fix(collection/id): fix weird grid flash

---

src/Server/passport/lib/app/__tests__/analytics.jest.ts
src/Server/passport/lib/app/__tests__/lifecycle.jest.ts
src/Server/passport/lib/app/__tests__/locals.jest.ts
src/Server/passport/lib/app/__tests__/token_login.jest.js
src/Server/passport/lib/app/lifecycle.ts
src/Server/passport/lib/passport/__tests__/callbacks.jest.js
src/Server/passport/lib/passport/__tests__/serializers.jest.js

Closes [DIA-864](https://artsyproduct.atlassian.net/browse/DIA-864)
Ultimately there were two issues here:
When you tried to link the account, there was only one error that was explicitly handled for 3rd-party auth errors when logged in: `"Provider account previously linked to Artsy. Redirect back to settings page"`
As a result, when we encountered any other kind of error it would fall into the UNKNOWN error condition which would redirect to the login page. If you were logged out this would have popped up a toast that just said "Bad Request". But since you're logged in it would then throw away the query param and redirect to the homepage.
So this just sets the correct redirect path regardless now.
In addition we were swallowing this error message, which is a useful one. So now we dig into …

fix(DIA-864): correct redirect/pass along error message

---

src/Apps/ViewingRoom/ViewingRoomApp.tsx
src/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
src/Utils/user.ts

@mzikherman noticed that we're duplicating some auth checks in force for VRs, which is creating a lot of friction around previewing VR states. So lets fix that!

fix(viewing-rooms): Fix preview state

---

src/Apps/ViewingRoom/Components/ViewingRoomsFeaturedRail.tsx
src/Apps/ViewingRoom/ViewingRoomsApp.tsx
src/Apps/ViewingRoom/__tests__/ViewingRoomsApp.jest.tsx
src/Apps/ViewingRoom/viewingRoomRoutes.tsx
src/__generated__/ViewingRoomsApp_Test_Query.graphql.ts
src/__generated__/ViewingRoomsApp_featuredViewingRooms.graphql.ts
src/__generated__/ViewingRoomsFeaturedRail_featuredViewingRooms.graphql.ts
src/__generated__/viewingRoomRoutes_ViewingRoomsAppQuery.graphql.ts

This PR solves [ONYX-1307]
I want to remove viewingRooms (which is deprecated) query from gravity to simplify un-stitching
[ONYX-1307]: https://artsyproduct.atlassian.net/browse/ONYX-1307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(onyx-1307): use viewingRoomsConnection instead of deprecated viewingRooms query

---

src/Apps/Auction/Components/__tests__/AuctionArtworkFilter.jest.tsx
src/Apps/Auction/Components/getArtworkFilterInputArgs.ts
src/Apps/Collect/Routes/Collection/Components/__tests__/CollectionArtworksFilter.jest.tsx
src/Apps/Collect/collectRoutes.tsx
src/Apps/Fair/fairRoutes.tsx
src/Apps/Gene/geneRoutes.tsx
src/Apps/Partner/partnerRoutes.tsx
src/Apps/Sale/Components/getArtworkFilterInputArgs.ts
src/Apps/Search/searchRoutes.tsx
src/Apps/Show/__tests__/ShowArtworks.jest.tsx
src/Apps/Show/showRoutes.tsx
src/Apps/Tag/tagRoutes.tsx
src/Components/ArtworkFilter/ArtworkFilterContext.tsx
src/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtistsFilter.jest.tsx
src/System/Relay/createRelaySSREnvironment.ts
src/System/Relay/isRequestCacheable.ts
src/System/Relay/middleware/cacheHeaderMiddleware.ts

In order to be able to properly cache grid/filter queries - we needed to figure something out with the personalized 'followed artists' information.
One thing was easy - when your filter query _includes_ that option, naturally we don't want to cache. That was added in 97cb651f2a861b786c216ec14c9ea1996252b6ae.
The other thing was a bit tricky and required a judgement call. We fetch a `FOLLOWED_ARTISTS` aggregation up front as part of the initial filter call. This means that request _must_ skip all cache - both our CDN _and_ any data loader caching in MP. That request has to hit ElasticSearch.
And for what purpose? It purely returns a count....which decides whether a checkbox is enabled or disabled.
I think it's not worth it. Let's just enable/disable the checkbox based on logged in. I went …

feat: removes personalized FOLLOWED_ARTISTS aggregation, prep for @cacheable

---

.circleci/config.yml

Oops, we're still running the world. Constrain things on release to just test and type-check

ci(circle): Only run required

---

.circleci/config.yml

Since we cache docker build pushes, its safe to run on merges to main just in case a dev quick-merges a PR before its done. Then it will rebuild and send out ensuring some resiliency.

ci(kick): Kick the staging push 

---

src/Apps/Order/Routes/Shipping2/Components/ShippingQuotes2.tsx

The type of this PR is: **fix** #minor
This PR is related to [EMI-1516]. A data-testid attribute is sent to the wrong element, causing tests to fail.
[EMI-1516]: https://artsyproduct.atlassian.net/browse/EMI-1516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: move data-testid to correct container

---

src/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
src/Apps/Artwork/artworkRoutes.tsx
src/System/Hooks/useFeatureFlag.tsx
src/Utils/getFeatureFlag.ts
src/Utils/warnInDevelopment.ts

I noticed this looking at the load flame graph. Importing `getFeatureFlag` would also bring with it all of `SystemContext`. I pulled that function out into its own file to prevent that, but might as well remove these flags anyway.

chore: removes feature flags

---

.circleci/config.yml
src/Utils/__tests__/url.jest.ts

Fixes missing Jest error output from https://github.com/artsy/force/pull/14553, and also ensures that all required steps run before pushing a staging image.

ci(test): fix jest error output

---

src/Components/Artwork/SaveButton/SaveButton.tsx

Recent integrity failures [uncovered](https://app.circleci.com/pipelines/github/artsy/integrity/25325/workflows/e6106519-afae-4dca-b27d-8a9baae2d526/jobs/124720/steps) a small issue with saves buttons. If user opens a page and clicks on a save page icon too fast (before query renderer is finished loading the data) - user gets redirected to an artwork page. Apparently this happens when there is a Clickable without onClick handler. When click happens - closest parent's onClick gets executed (sorry for confusing explanation). This PR should fix it - instead of redirecting a user to a separate page, nothing should happen.

fix: do not redirect to an artwork page when clicking on a save button and save button is not loaded yet

---

src/Components/Artwork/SaveButton/SaveArtworkToListsButton.tsx
src/Components/Artwork/SaveButton/SaveButton.tsx

Just adding some `data-test-id`s which hopefully will help to fix [failing integrity specs](https://app.circleci.com/pipelines/github/artsy/integrity/25325/workflows/e6106519-afae-4dca-b27d-8a9baae2d526/jobs/124720/steps). Save buttons became query renderers recently and apparently integrity presses on them too fast - query renderers are still loading data. I plan to use `saveButtonPlaceholder` test id with `waitUntil` to confirm that query renderer is finished loading data and only after then press on save buttons.

chore: add data-test-id to save button placeholders for integrity

---

src/System/Components/RouterLink.tsx

As discussed, we can try this experiment only for logged-in users.

feat: switch prefetch-on-enter to only be enabled for logged-in

---

src/System/Hooks/usePrefetchRoute.tsx
src/System/Relay/middleware/cacheHeaderMiddleware.ts

Noticing this, when we prefetch, we need to inject the custom TTL (if any).
Then, in middleware, if we're in the pre-fetch context we propagate that TTL (even if there was none set). Without any `max-age` we'd default to the worker 1 hour.

fix: use TTL of prefetched route, rather than current route, for setting max-age

---

src/Apps/CollectorProfile/Routes/Saves/CollectorProfileSavesRoute.tsx
src/Apps/CollectorProfile/Routes/Saves/Components/ArtworkListItemsList.tsx
src/__generated__/ArtworkListItemsListQuery.graphql.ts

When user creates a saves list (from `/favorites/saves`) - page fails with 500 error. Honestly idk what happens exactly, but the error suggest to wrap the section in Suspense. For that I had to extract the whole saves lists rail into a query renderer component.
|---|---|
| <video src="https://github.com/user-attachments/assets/c1b5b56b-0d2e-43bb-9dc8-8b4042d79a90" /> | <video src="https://github.com/user-attachments/assets/166aa1dd-b451-48ff-92fb-52c23380d102" /> |

fix: fix 500 when creating artworks list (saves)

---

src/System/Relay/middleware/cacheHeaderMiddleware.ts

When you're on a page with a `serverCacheTTL` of 0 (like the auction page) - you don't want to consider that when determining whether to skip the CDN for prefetched routes (you'd want to consider the prefetched route's `serverCacheTTL`).

fix: use TTL of prefetched route to determine if CDN should be skipped (when set to 0)

---

src/System/Relay/middleware/__tests__/cacheHeaderMiddleware.jest.ts
src/System/Relay/middleware/cacheHeaderMiddleware.ts

Little cleanup now that the caching behavior in Force that used this is gone. We're actually setting these headers and sending them off on MP/CDN requests (not that it matters there, just we don't need to).

chore: remove unused x-relay cache headers

---

src/Apps/Order/Components/CreditCardPicker.tsx
src/Apps/Order/Components/__tests__/CreditCardPicker.jest.tsx
src/Utils/createStripeWrapper.tsx
src/__generated__/CreditCardPickerTestQuery.graphql.ts
src/__generated__/CreditCardPicker_order.graphql.ts
src/__generated__/NewPaymentTestQuery.graphql.ts
src/__generated__/PaymentTestQuery.graphql.ts
src/__generated__/orderRoutes_NewPaymentQuery.graphql.ts
src/__generated__/orderRoutes_PaymentQuery.graphql.ts

This PR solves [EMI-1948](https://artsyproduct.atlassian.net/browse/EMI-1948).
In BNMO checkout where we know the merchant of record, we want to pass `onBehalfOf` parameter to Stripe `Elements` so the card elements UI can determine displaying the card network selection dropdown (or not).
Adding a credit card for completing an order can be done in 2 places:
- Checking out before submitting an order
- Fixing a failed payment
Screen recording for both scenarios:
<details><summary>Checking out before submitting an order</summary>
<p>
</p>
</details> 
<details><summary>Fixing a failed payment</summary>
<p>
</p>
</details> 
[EMI-1948]: https://artsyproduct.atlassian.net/browse/EMI-1948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …

feat: support card network selection for new cards in BNMO checkout

---

src/Components/AuthDialog/AuthDialogContext.tsx
src/Components/AuthDialog/Views/AuthDialogWelcome.tsx

Apparently `fetchQuery` does not reject on GraphQL errors, only actual network errors. So:
* reCAPTCHA might fail; in which case it would reject/throw and you'd get the fallback
* If it does give you a token, _we_ might reject based on the score, in which case it would _not_ reject/throw, instead we'd assume that your account did not exist, not triggering the fallback.
There literally is no way to access the errors field when using `fetchQuery`, as far as I can tell. So we just have to assume that the absence of a response at all is failing.
I've also switched the fallback state to default to the login, since that seems to be what's desirable most of the time.
* `verifyUser: null` = failed reCAPTCHA, fallback to login
* `verifyUser: { exists: true }` = go to login
* `verifyUser: { exists: …

fix(auth): adjusts re-captcha fallback behavior

---

src/Apps/Conversations/components/ConversationHeader.tsx
src/Apps/Conversations/components/Details/OrderInformation/ReviewOrderButton.tsx
src/Apps/Conversations/components/Sidebar/ConversationsSidebarItem.tsx
src/Apps/Conversations/components/__tests__/ConversationHeader.jest.tsx
src/Components/NavBar/Menus/NavBarUserMenu.tsx
src/Components/NavBar/NavBarLoggedInActions.tsx
src/System/Components/RouterLink.tsx

Adds the ability to toggle off link prefetching via `prefetchEnabled` prop on RouterLink, and disables for admin items. Also guards against erronious queries to the user menu. Not sure if that fixes anything related to [this reported issue](https://artsy.slack.com/archives/C03N12SR0RK/p1727365743754609) as I cannot reproduce, but lets just be safe.

feat(router-link): Add enablePrefetch flag to link

---

src/Components/ArtworkFilter/ArtworkFiltersQuick/FeaturedKeywordsFilterQuick.tsx

Chatting with Ryan today, we puzzled over how to visually distinguish featured keywords, which operate almost as toggles, from the quick filter menus that expand. He's refining a few alternatives, but in the meantime we thought they should _at least_ be separated somehow. In this PR, I borrow the separator used on artists' artwork grids:
Looks like:
Q: should this separator and its spacing be elevated to Palette?

feat: separate quick filter menus from featured keywords

---

README.md
scripts/build_review_app.sh
scripts/update_review_app.sh

This PR solves [PHIIRE-1236]
`scripts/update_review_app.sh` calls `hokusai review_app setup` only to create Yaml. Now there's a [hokusai review_app create-yaml](https://github.com/artsy/hokusai/pull/428) command. Let's switch to that.
`hokusai review_app env copy` command is [deprecated](https://github.com/artsy/hokusai/pull/426). Remove.

feat: update review app scripts

---

src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx

This PR solves [EMI-2113]
This allows the order history page to display "Payment failed" and links to add a new payment to the order history page when `displayState` is `PAYMENT_FAILED`. 
https://github.com/user-attachments/assets/68aeb9d3-41da-478a-a31e-b0f4e858b664
[EMI-2113]: https://artsyproduct.atlassian.net/browse/EMI-2113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2113): add payment failed status and link to order history

---

src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx

Minor follow up for this one: https://artsyproduct.atlassian.net/browse/EMI-2113
Here how it looks with the icon:

chore: add icon to failed payment display on order history

---

src/Apps/Article/articleRoutes.tsx
src/Apps/Articles/articlesRoutes.tsx
src/Apps/serverCacheTTLs.tsx

Reported by Casey - the 60 minute default TTL at the CDN was asked to be removed in order to keep articles timely as news is published. My sense is most of the time it would have been _fine_ to enforce the TTL, but article pages don't appear to have any glaring performance issues according to DataDog, so this is fine.
Also, this would have been the behavior prior to these more recent caching experiments.

feat: remove caching from article(s), opt-out of CDN

---

data/schema.graphql
src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
src/Apps/Collect/Routes/Collection/index.tsx
src/__generated__/Collection_collection.graphql.ts
src/__generated__/Header_collection.graphql.ts
src/__generated__/collectRoutes_CollectionQuery.graphql.ts

Closes [DIA-753](https://artsyproduct.atlassian.net/browse/DIA-753)
Depends on https://github.com/artsy/metaphysics/pull/6077
Once deployed we can circle back and make the change on the `description` field. The default format is just Markdown syntax not HTML.
[DIA-753]: https://artsyproduct.atlassian.net/browse/DIA-753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dia-753): update meta descriptions to remove markdown syntax

---

src/Apps/Order/__tests__/OrderApp.jest.tsx
src/Apps/Order/redirects.tsx

This PR solves [EMI-2123]
We have a redirect rule which is incompatible with the new PAYMENT_FAILED display state. I don't think it is needed for this route but wouldn't mind a second set of eyes. Might need tests.
[EMI-2123]: https://artsyproduct.atlassian.net/browse/EMI-2123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2123): dont redirect for displayState != submitted on payment failed route

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCollectorSignal.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarDetails.jest.tsx

This PR solves [EMI-2134]
Numeric and date ranges should always be punctuated with an en dash. 
(See [our guidelines](https://docs.google.com/document/d/1NoBSYM-EBA4b6rdux-8CQJWneXcglISHzZNvSkKFDh0/edit#bookmark=id.yw4t3wp6qe04) or [this reference](https://www.thepunctuationguide.com/en-dash.html))
| ![before](https://github.com/user-attachments/assets/176e4272-2ac8-470e-93a0-9d98b3cc3414) | ![after](https://github.com/user-attachments/assets/4ea52502-26f3-47ac-b5e5-5e4c1904c22c) |
[EMI-2134]: https://artsyproduct.atlassian.net/browse/EMI-2134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: en dash in date range for collector signals

---

src/Components/Artwork/Details/BidTimerLine.tsx
src/Components/Artwork/Details/__tests__/BidTimerLine.jest.tsx

This PR solves [EMI-2022]
See [Slack](https://artsy.slack.com/archives/C02JHHHKP5K/p1727989265612639?thread_ts=1727370726.687139&cid=C02JHHHKP5K) for context.
We currently don't show seconds in the time left to bid for auction artworks. When it's less than 1 minute, it displays "0m left to bid". This updates the logic to show seconds.
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After: not extended timer</summary>
<p>
</p>
</details> 
<details><summary>After: extended timer</summary>
<p>
</p>
</details> 
[EMI-2022]: https://artsyproduct.atlassian.net/browse/EMI-2022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: show seconds left to bid in auction signals

---

src/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx

Noticed this bug on staging and production
If I am viewing my saved alerts and then go to log out from the menu bar, I receive a `Internal Server error 500`
Though, I am technically signed out, seeing the 500 seems to be a bit of a dead end as a user
Also to note, this only happens on desktop sized screens! Mobile correctly shows the sign in page
This is happening because I'm not logged out and `me` == null when trying to load in the alerts page
Example of the error in Sentry and Force:
- https://artsynet.sentry.io/issues/5900188608/?project=159064&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1
---
I've adjusted the code to handle the case when `me` is `null` (aka logged out user), so they can see something like this and not a 500 …

fix: Adds handling in case of `me` being null

---

src/Apps/Order/Dialogs.tsx
src/Apps/Order/Routes/Accept/index.tsx

We noticed that in the 'update payment' flow if the new payment is failing as well we are displaying really confusing CTA. The easy solution was to at least remove extra CTA button that does not seem to add anything.
Before:
After:

chore(EMI-2132): remove secondary button from payment failed dialog

---

src/System/Components/RouterLink.tsx

This adds a new feature flag `diamond_prefetch-on-enter-logged-out` which we can use to toggle on/off support for prefetch on enter.

feat(prefetch): Add feature-flag support for prefetch-on-enter for logged out 

---

src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx

The type of this PR is: Fix or small user experience improvement
This PR solves [PBRW-86](https://artsyproduct.atlassian.net/browse/PBRW-86)
Got a report in #product-bugs about a gallery not being able to click artist name on the Private Artworks Exclusive access page and see more artist details. This is a small change that mimics the behavior of our publicly published artwork pages
Seems pretty low risk, eh?
[PBRW-86]: https://artsyproduct.atlassian.net/browse/PBRW-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Make artist name clickable on Private artworks pages

---

Dockerfile
hokusai/production.yml
hokusai/staging.yml
scripts/load_secrets_and_run.sh

This PR solves [PHIRE-1095]
This PR introduces:
- Kubernetes initContainer which takes care of fetching vars from [Vault](https://www.notion.so/artsy/Hashicorp-Vault-developer-instructions-77d94af51f714d51bb44049f4f2027bc) and writing them to a file.
- Kubernetes serviceAccount which the initContainer uses to authenticate to Vault.
- A script that loads the vars from file into container ENV.
This is a big change. Please create a deploy block, and QA.
Before merging:
After merging:
[PHIRE-1095]: https://artsyproduct.atlassian.net/browse/PHIRE-1095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: pods to load vars from vault [Do-Not-Merge]

---

src/Apps/Fair/Components/FairOverview/FairFollowedArtists.tsx
src/Apps/Fair/Routes/FairOverview.tsx
src/__generated__/FairFollowedArtistsQuery.graphql.ts

Fallout! I didn't realize the overview page included a section for works by artists you follow. Because this was `@cacheable` - we wouldn't include access tokens - and so we wouldn't render this section anymore. It would just silently not show up on the fair page anymore.
I was clued in to it by noticing the [fair overview query in DataDog](https://app.datadoghq.com/apm/services/metaphysics.graphql/operations/graphql.execute/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%2195%2CtopN%3A%215%29%2Cversion%3A%210%29&env=production&fromUser=false&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apod …

fix: defer FairFollowedArtistsQuery so fair overview can be @cacheable

---

src/Apps/Order/Routes/Payment/PaymentContent.tsx
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/__tests__/Payment.jest.tsx
src/__generated__/PaymentTestQuery.graphql.ts
src/__generated__/Payment_me.graphql.ts
src/__generated__/orderRoutes_PaymentQuery.graphql.ts

This PR solves [EMI-2047]
Part of the co-badged card compliance requirements, we want to display language about managing card networks when the user has saved cards.
<details><summary>Screenshot: when there is a saved card</summary>
<p>
</p>
</details> 
<details><summary>Screenshot: when there is no saved card</summary>
<p>
</p>
</details> 
[EMI-2047]: https://artsyproduct.atlassian.net/browse/EMI-2047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: show co-badged card language when there is a saved card

---

src/Apps/Invoice/Components/AddressForm.tsx
src/Apps/Invoice/Components/AddressFormWithCreditCard.tsx
src/Apps/Invoice/Components/InvoiceLineItems.tsx
src/Apps/Invoice/Components/InvoicePaymentForm.tsx
src/Apps/Invoice/Components/InvoicePayments.tsx
src/Apps/Invoice/Hooks/useCreateTokenAndSubmit.ts
src/Apps/Invoice/Hooks/useFormContext.ts
src/Apps/Invoice/Hooks/useMakeInvoicePayment.ts
src/Apps/Invoice/InvoiceApp.tsx
src/Apps/Invoice/Routes/InvoiceDetailRoute.tsx
src/Apps/Invoice/Routes/InvoicePaymentRoute.tsx
src/Apps/Invoice/invoiceRoutes.tsx
src/__generated__/InvoiceApp_invoice.graphql.ts
src/__generated__/InvoiceDetailRoute_invoice.graphql.ts
src/__generated__/InvoiceLineItems_invoice.graphql.ts
src/__generated__/InvoicePaymentRoute_invoice.graphql.ts
src/__generated__/InvoicePayments_invoice.graphql.ts
src/__generated__/invoiceRoutes_InvoiceDetailQuery.graphql.ts
src/__generated__/invoiceRoutes_InvoicePaymentQuery.graphql.ts
src/__generated__/invoiceRoutes_InvoiceQuery.graphql.ts
src/__generated__/useMakeInvoicePaymentMutation.graphql.ts
src/routes.tsx

This adds a new app with a couple of new routes - retrieving an invoice/displaying it, as well as making a payment. These are under the `/invoice/:token` and `/invoice/:token/payment` routes, as part of a new `Invoice` app.
It's quite basic, and mostly replicates almost 1-1 (using Palette's design system) the UI and functionality present in https://github.com/artsy/charge. It uses a schema that was added in https://github.com/artsy/metaphysics/pull/6137 to support invoice/payments.
The idea is that we can simply retire Charge and its associated code, in favor of this page. In order to do that, we need to set up a redirect from Charge-style routes to these routes. Since Charge is deployed on its own subdomain - I'm not 100% sure the best place for the redirect (somewhere in our nginx …

feat: add InvoiceApp to retrieve an invoice by token, and allow a payment

---

package.json
yarn.lock

This PR solves [EMI-2063]
Noticing the credit card icons are rendered black after the @artsy/icons version bump. Going to revert back for now and investigate further.
[EMI-2063]: https://artsyproduct.atlassian.net/browse/EMI-2063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
cc @artsy/emerald-devs

feat: downgrade @artsy/icons

---

src/System/Components/RouterLink.tsx

Fixes integration tests, which currently fail in multiple suites expecting `data-testid` attributes. A search indicates that `data-test` is another attribute specified throughout the codebase, and probably gets removed before generating the DOM.

fix: pass through data-test* properties

---

scripts/build_review_app.sh

While creating a review app for [signals work](https://artsy.slack.com/archives/C02JHHHKP5K/p1729195691286149?thread_ts=1729195668.187189&cid=C02JHHHKP5K), the review app creation failed for the following reason. It looks the script might have incorrectly replaced [a wrong line](https://github.com/artsy/force/blob/25e34cd25ecbccb442f90b9f07da5cb907e3044c/hokusai/staging.yml#L35) that's for the new vault. This updates the script to be more specific.

chore: update review app script

---

.circleci/config.yml

Noticed that slack deploy failure alerts stopped working with the latest CI refactor. Not sure why! So hard code the value in here and see if it works.

ci(slack): fix slack notifications

---

src/System/Components/RouterLink.tsx

Apparently more fallout from the [Styled Components upgrade](https://github.com/artsy/force/pull/14678), and the need to explicitly allowlist some [more](https://github.com/artsy/force/pull/14686) props
(Surfaced by some [failing specs](https://artsy.slack.com/archives/C05EQL4R5N0/p1729619815219029) for logged-out MyC users in Integrity)

fix(router link): allow onclick prop explicitly

---

package.json
yarn.lock

This follows up https://github.com/artsy/force/pull/14481 to remove the `http-proxy-middleware` lib. I believe it's now unused.

chore: remove http-proxy-middleware

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
src/Apps/ArtistSeries/ArtistSeriesApp.tsx
src/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx
src/Apps/Artwork/Components/ArtworkLightbox.tsx
src/Apps/Auction/Components/AuctionArtworkFilter.tsx
src/Apps/Collect/Routes/Collect/index.tsx
src/Apps/Collect/Routes/Collection/Components/Header/CollectionFeaturedArtists.tsx
src/Apps/Collect/Routes/Collection/index.tsx
src/Apps/Gene/Components/GeneArtworkFilter.tsx
src/Apps/Show/Components/ShowArtworks.tsx
src/Apps/Tag/Components/TagArtworkFilter.tsx
src/Components/ArtworkGrid/LazyArtworkGrid.tsx

Need to make sure we don't rerender lazy grids if a user has clicked on a route (triggering state update in router via url bar update). So adds a new (maybe too generic) `LazyArtworkGrid` component that we can wrap things in.

fix(artwork-grids): Ensure we dont rerender on route changes

---

src/Apps/Order/Components/CreditCardDetails.tsx
src/Components/BrandCreditCardIcon.tsx

This PR solves [EMI-2063](https://artsyproduct.atlassian.net/browse/EMI-2063)
Now that we've updated the credit card icons and added a few more, including CB card that's required in the compliance project, in artsy/icons, let's display them.
[EMI-2063]: https://artsyproduct.atlassian.net/browse/EMI-2063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: display new credit card brand icons

---

src/Apps/Fair/Routes/FairArtworks.tsx
src/Apps/Fair/fairRoutes.tsx
src/__generated__/FairArtworksFilterQuery.graphql.ts
src/__generated__/FairArtworksFilterRefetchQuery.graphql.ts

This one was easy - the entire route was already _just_ the artworks filter!

feat: defer artworks grid on Fair artworks route

---

src/Apps/MyCollection/Routes/EditArtwork/Components/ArtworkFormExitConfirmationDialog.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormHeader.tsx
src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormMain.tsx
src/Apps/Sell/Components/SubmissionHeader.tsx
src/Apps/Sell/Components/__tests__/SubmissionLayout.jest.tsx

Addresses [ONYX-1266]
With this change, we will allow logged-out users to exit the Sell flow by clicking on the Artsy logo in the header. 
The current problem is that clicking on "Save & Exit" opens the "Sign up" modal for logged-out users and does not allow to (simply) exit the Sell flow.
Clicking on the Artsy logo in the header will now open a dialog to exit the flow without signing up and navigate the user to the "/sell" page.
[ONYX-1266]: https://artsyproduct.atlassian.net/browse/ONYX-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Allow logged out users to exit Sell flow by clicking on Artsy logo

---

src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx

Adding tracking call for when 'update payment' button is clicked on order history.
Should finish this one: [EMI-2130](https://artsyproduct.atlassian.net/browse/EMI-2130)
Not sure if there is a better way to do it as because it's a hook React wanted me to move it inside function declaration. 
[EMI-2130]: https://artsyproduct.atlassian.net/browse/EMI-2130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add tracking to update payment method

---

src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx

[AMBER-1099](https://artsyproduct.atlassian.net/browse/AMBER-1099)
Steps to reproduce:
Issues relating to the viewing room William Kentridge : Studio Life Gravures Viewing Room.
Parter: Jillian Ross Print
When looking at this viewing room and then artwork within it 'The Old Gods Have Retired':
1. The formatting of the text 'About the artwork' does not have any line breaks in the preview. Creates a long passage of text which is difficult to read.
2. The video is not showing in the Viewing room 
Artwork listing in CMS here <https://cms.artsy.net/artworks/66fda41ced5b2f0e49ec965f/edit>
Viewing room preview here <https://www.artsy.net/viewing-room/jillian-ross-print-william-kentridge-studio-life-gravures/artworks>
URL Affected: https://www.artsy.net/viewing-room/jillian-ross-print-william-kent …

fix(AMBER-1099): [Viewing Room] Jillian Ross Viewing Room Bug/Formatting

---

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx

Fixes cutoff on closed auction artworks. 
@dblandin - i can't find the ticket for this, but its on y'alls board somewhere.  
Before:
After: 

fix(artwork): Fix cutoff on closed auction artworks

---

package.json
yarn.lock

This PR bumps `package.json` version of `artsy-xapp` to use version `2.0.0`. The new versions uses native `node-fetch` instead of `superagent`. See https://github.com/artsy/artsy-xapp/pull/11 for details.

chore: use artsy-xapp 2.0.0

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx

This is not the prettiest PR, and its not as nice as things are currently (with the fixed scrolling backdrop, etc), but given our LCP scores, its likely worth it. 
Simplifies the artist header image on mobile by skipping out on FullBleedHeader (and all of its nice features) in favor of a ResponsiveBox + Image 
Still looks the same: 
But (local) lighthouse LCP performance score has significantly improved:
Before:
After:

fix(artist): Attempt to improve LCP

---

src/Components/CollectionsHubsNav.tsx

Noticed we were still lazy-loading the top collection hub images, impacting LCP. This fixes that. 

fix(lcp): Improve LCP on /collect

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
src/Apps/Fair/Components/FairHeader/FairHeaderImage.tsx

Similar to recent [work done on /artist/id](https://github.com/artsy/force/pull/14769), this improves LCP on fair/id by eliminating the fullbleed header and using a simple cropped image.

fix(lcp): Improve LCP on mobile fair page 

---

src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActionsSaveButton.jest.tsx

Replacing `isSaved` / `isSavedToList` by `isSavedToAnyList` winds up feeling unusual on the artwork page when the artwork is in an auction _and_ is saved to a custom list (which is allowed on rails).
This is b/c the artwork page 'Watch Lot' functionality only adds/removes from the default list - there's no entry point to list selection if the artwork is saved to custom lists.
I'm not quite sure why we wouldn't do that - in general we should only make exceptions in truly exceptional cases. Not finding much explanation in the previous PR (+ JIRA ticket) - https://github.com/artsy/force/pull/12605
I think we can relax this.
https://github.com/user-attachments/assets/da74e7db-4067-4183-9795-bf6e5010612a

feat: allow list management entry point to occur on artwork page for auction artworks

---

package.json
src/html.ejs
webpack/envs/clientDevelopmentConfig.js
webpack/envs/clientProductionConfig.js
webpack/sharedPlugins.js
yarn.lock

This PR solves [DIA-969]
This adds support for preload hints around initial JS chunks that are shipped down to the page via https://github.com/vuejs/preload-webpack-plugin. 
Idea first came from reading [this blogpost](https://mmazzarolo.com/blog/2024-08-13-async-chunk-preloading-on-load) and dug around a bit and realized that webpack can do this all for us. 
Example output:
Also refactored / simplified our html setup by not manually defining JS chunk output in our html template, and instead let HTMLWebpackPlugin do the work it was originally designed to do 🤷 
[DIA-969]: https://artsyproduct.atlassian.net/browse/DIA-969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(performance): Add PreloadWebpackPlugin for preloading initial JS chunks and simplify html pipeline

---

package.json
src/html.ejs
webpack/envs/clientDevelopmentConfig.js
webpack/envs/clientProductionConfig.js
webpack/sharedPlugins.js
yarn.lock

Reverts artsy/force#14787 in response to lots of asset-loading failures in staging and integration tests.

Revert "feat(performance): Add PreloadWebpackPlugin for preloading initial JS chunks and simplify html pipeline"

---

package.json
src/Apps/Authentication/Middleware/redirectPostAuth.ts
src/Server/middleware/__tests__/hardcodedRedirects.jest.ts
src/Server/middleware/linkHeadersMiddleware.ts
src/middleware.ts
yarn.lock

This PR adds `Link` headers corresponding to the `preconnect` and `preload` declarations already made [at the top of our HTML template](https://github.com/artsy/force/blob/7fc5ed5cb75c865cc0b146072e26258e2772d10c/src/html.ejs#L9-L17).
Once these are part of Force's response, we should be able to toggle on [Cloudflare's intelligent "early hints" handling](https://developers.cloudflare.com/cache/advanced-configuration/early-hints/). Supposedly, `103` responses will automatically be streamed to compatible clients before the server's response is available.
[This thread](https://webmasters.stackexchange.com/questions/89466/when-should-i-use-the-crossorigin-attribute-on-a-preconnect-link) was helpful in understanding the appropriate `crossorigin` settings.
(Very open to feedback about how to …

feat: add Link headers corresponding to preconnect and preload instructions (DIA-967)

---

package.json
src/html.ejs
webpack/envs/clientDevelopmentConfig.js
webpack/envs/clientProductionConfig.js
webpack/sharedPlugins.js
yarn.lock

Opening a review app for preloading JS chunks: https://github.com/artsy/force/pull/14787 (PR merged and reverted).
The issue is we were double embedding our script tags for some reason. Removed the second call, and all good.

feat(performance): Add PreloadWebpackPlugin for preloading initial JS chunks -- Review App 

---

src/Apps/Fair/Routes/FairOverview.tsx
src/__generated__/FairOverview_Test_Query.graphql.ts
src/__generated__/FairOverview_fair.graphql.ts
src/__generated__/fairRoutes_FairOverviewQuery.graphql.ts

This query has a very high error rate...b/c it includes a fragment that errors when the user is logged out! There's no effect in the UI as the relevant component doesn't show up.
However, this entire fragment had been moved into a query renderer (guarded behind a logged-in user: https://github.com/artsy/force/blob/bc35b7ffe4dfd469495f36cff343e5cf67c653dd/src/Apps/Fair/Routes/FairOverview.tsx#L51), so this is a case of overfetching - we can safely just remove the whole fragment.

fix: remove a fragment thats been deferred from Fair overview

---

package.json
src/Server/__tests__/getWebpackEarlyHints.jest.ts
src/Server/getWebpackEarlyHints.ts
src/Server/middleware/linkHeadersMiddleware.ts
src/System/Router/renderServerApp.tsx
src/dev.js
src/html.ejs
webpack/plugins/EarlyHintsPlugin.js
webpack/sharedPlugins.js
yarn.lock

This PR solves [DIA-972]
Building on work completed in: 
- https://github.com/artsy/force/pull/14794 
This adds a new Webpack plugin for generating a list of "initial" webpack chunks for `early-hints` (`initial` being, those assets that are required on every page to run the site). On the express side we read the list and then expand the headers that are being passed down via the new `linkHeadersMiddleware`. With this now in place we can take further advantage of the new `<link rel="preload" as="script">` tags that we're now writing to our html template on build. 
**Screenshots:**
1. Can now see that we've got a high fetch priority on our main scripts: 
2. And here are the script link headers as passed over from the server: …

feat(early-hints): Add support for emitting webpack .js early hint headers and passing via linkHeadersMiddleware

---

src/Server/__tests__/getWebpackEarlyHints.jest.ts
src/Server/getWebpackEarlyHints.ts

Fixes CORS config after lots of faffing, but eventually got to a good localhost workflow:
- install nginx via homebrew
- point nginx server at localhost but mapped to artsy domain (I used [nginx.artys.net](http://nginx.artys.net/))
- `yarn build:client:prod`
- WEBPACK_FAST_PROD_BUILD=true yarn build:server:prod` (speed things up, if making changes)
- `yarn start:prod:debug`
The final incantation was:
- crossorigin on Link header CDN preconnect 
- no crossorigin on Link header preload
- no crossorigin on `<link>` tag preload 
Screenshot of local resources loading correctly (high priority, via `<link>` preload, using CDN): 

fix(early-hints): Fix cors configuration around preloading js assets 

---

src/Apps/Favorites/favoritesRoutes.tsx
src/Server/middleware/userRequiredMiddleware.ts

Addresses [ONYX-1248]
Require logged-in user for `/favorites/alerts/$id/edit` route instead of redirecting to `/`.
[ONYX-1248]: https://artsyproduct.atlassian.net/browse/ONYX-1248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Require logged in user for  all`/favorites/alerts/` sub route

---

src/Apps/Search/Routes/SearchResultsArtworks.tsx

Addresses [ONYX-861]
* Related fix: https://github.com/artsy/force/pull/13567
* PR that introduced the remount issue: https://github.com/artsy/force/pull/12941
With this fix, we avoid the remount on the Search page when clicking on a search item that was caused by the updated `key` prop.
[ONYX-861]: https://artsyproduct.atlassian.net/browse/ONYX-861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Avoid remount on Search page

---

src/Apps/Article/Components/ArticleHero.tsx

In certain cases and viewport widths, the left column extends beyond the right column's height due to longer headline text. The solution is to change the `height` property to `min-height` to accommodate this, while also addressing Firefox-specific image height rendering behavior.

fix: header image in writer feature layout not formatting properly

---

src/Apps/Order/Routes/Shipping/Components/AddressModal.tsx
src/Apps/Order/Routes/Shipping/Components/FulfillmentDetailsForm.tsx
src/Apps/Order/Routes/Shipping/Utils/shippingUtils.ts

Paired with @starsirius 
This PR solves [EMI-2157]
It's possible for a user to have a saved address that doesn't pass our existing validation methods. In particular we have seen this on phone numbers with spaces or parens. As an immediate fix, we are improving error handling on saved addresses by:
- relaxing phone validation
- showing a message if saved address has errors
- touching saved address error fields in the edit modal on load.
[EMI-2157]: https://artsyproduct.atlassian.net/browse/EMI-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2157): Checkout dead ends due to invisible saved address errors

---

src/Components/Notifications/NotificationArtwork.tsx

Somehow, prefetching the `artworkRoutes_ArtworkQuery` query seems to cause this error on the Notification page. It looks like prefetching the query causes the removal of the data in the Relay store (maybe by overriding or [garbage collecting](https://relay.dev/docs/guided-tour/accessing-data-without-react/retaining-queries/) the data 🤔).
**Internal error after a few milliseconds:**
**Artwork is visible and disappears after a few milliseconds with this error:**

fix: Disable prefetching artworks on the Notification page

---

src/Components/ArtworkFilter/ArtworkFilters/AvailabilityFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/AvailabilityFilter.jest.tsx

Addresses [ONYX-699]
Currently, unchecking the "Only works for sale" filter on the artwork grid does not remove the filter; instead, it filters for artworks that are not for sale.
With this change, the filter will be **removed** correctly when unchecked.
----
In https://github.com/artsy/force/pull/14817, I'm making sure the filter does not appear in the URL as `for_sale=`.
[ONYX-699]: https://artsyproduct.atlassian.net/browse/ONYX-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Correctly unset availability filter

---

src/Components/ArtworkFilter/Utils/urlBuilder.tsx

Addresses [ONYX-699]
- Related PR: https://github.com/artsy/force/pull/14816
Currently, we add filters with `null` values ([examples](https://github.com/artsy/force/blob/main/src/Components/ArtworkFilter/ArtworkFilterContext.tsx#L544)) to the URL as `?filterName=`. I suppose we can remove these values from the URL without any issues, which would result in a cleaner URL.
With this change, all filters with `null` values will be omitted when constructing the URL from the filters.
**Example:**
`/artist/gerhard-richter?for_sale=` -> `/gerhard-richter`
[ONYX-699]: https://artsyproduct.atlassian.net/browse/ONYX-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Remove filters with `null` values from the URL

---

src/Apps/Artists/Routes/ArtistsIndex.tsx

Noticed that we were incorrectly prioritizing highPriority LCP images on mobile on /artists, and not lazyloading where we should. This fixes that. 
Before:
After: 

fix(artists): Fix LCP images

---

src/Apps/Article/Components/ArticleMetaTags.tsx
src/Components/MetaTags.tsx

Closes: [DIA-758](https://artsyproduct.atlassian.net/browse/DIA-758)
The `MetaTags` component has been updated to accept a `socialTitle` override, allowing different titles for OpenGraph and Twitter meta tags to properly display article titles. However, we've observed that Google may be disregarding the page title tag in favor of the H1 tag content. This behavior isn't something we can directly control, but I'll investigate other instances to confirm this pattern.
[DIA-758]: https://artsyproduct.atlassian.net/browse/DIA-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: ensures social title is correct

---

src/Components/AuthDialog/Views/AuthDialogLogin.tsx
src/Components/Inquiry/Views/InquiryLogin.tsx

This PR partially solves [DIA-982] by removing the `inputMode="numeric"` property of the authentication code field so that mobile web users can enter a recovery code (which includes alphabet characters) if they need to.
Currently this field only allowed numeric input, so mobile users could only use a 0-9 keyboard. Now they will see the default text keyboard, which means they need to switch to numeric mode for OTPs, but also allows for recovery codes to be entered.
[DIA-982]: https://artsyproduct.atlassian.net/browse/DIA-982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-982): allow recovery codes to be entered on mobile

---

package.json
webpack/bundleSplitting.js
yarn.lock

Based on Chrome's coverage tooling, @dzucconi and I identified that the `artsy-framework` bundle was a little too liberal in the modules it included. Because that bundle is `preload`ed, that meant that _all_ of the referenced code was being loaded on all pages, and with a high priority.
* `@artsy/to-title-case` appears unused, so we removed it.
* `@artsy/icons` is designed for icons to be imported individually, and [occasionally](https://github.com/artsy/icons/pull/54) gains a bloated image, so is excluded.
* Modules like `@artsy/xapp` and `/multienv` should only be required server-side.
* Other libs like `@artsy/commerce_helpers`, `/dismissible`, `/express-reloadable`, `/palette-charts`, and `react-html-parser` should only be needed in a few places, so load them there.
* Q: What about …

chore: avoid loading extensive @artsy libraries until necessary

---

src/Apps/Articles/Components/ArticlesIndexArticle.tsx

Noticed that now that we've removed lazy loading on LCP images, we need a key to (instantly) refresh things, otherwise on SPA transition to another article the image from the previous article will remain for a moment while the other one loads in the background. 

fix(article): Add missing image key

---

src/Apps/Search/SearchApp.tsx

Resolves [ONYX-1384](https://artsyproduct.atlassian.net/browse/ONYX-1384)
Entering a new search term on the search page does not always update the text on the page. This PR fixes the issue.
**Steps to reproduce:**
Type "richter" in search input, press enter
Type "warhol" in search input, press enter
Type "richter" in search input, press enter
Outcome before this fix:
`... results for "warhol"` is still displayed
Expected outcome:
`... results for "richter"` should be displayed
https://github.com/user-attachments/assets/d1bb780c-1b1a-4c4a-92d3-4dcc363e8025
[ONYX-1384]: https://artsyproduct.atlassian.net/browse/ONYX-1384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update the term on the search page correctly

---

src/Components/CookieConsentManager/__tests__/useConsentRequired.jest.ts
src/Components/CookieConsentManager/useConsentRequired.ts

This change is straightforward - it disables the cookie consent banner specifically for Googlebot requests. We've observed the consent banner appearing in web.measure snapshots during Lighthouse testing, so this should impact LCP. Should result in improved page performance in certain scenarios. It also just makes sense.
@joeyAghion I've assigned you, feel free to merge; as I'm uncertain how this plays with the other changes we're doing.

feat: removes cookie consent banner for googlebot

---

src/Apps/Sell/Routes/ConsignmentInquiry/ConsignmentInquiryConfirmation.tsx
src/Apps/Sell/sellRoutes.tsx

This PR solves [ONYX-1401]
- The consignment inquiry flow was added in https://github.com/artsy/force/pull/11578
- Then those routes were re-organized in https://github.com/artsy/force/pull/14419
This resulted in some extraneous nesting that broke the inquiry email flow:
[ONYX-1401]: https://artsyproduct.atlassian.net/browse/ONYX-1401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(consignment inquiry): correct routing for email form

---

package.json
src/Apps/Auction/Components/Form/AddressForm.tsx
src/Apps/Auction/Components/Form/__tests__/AddressForm.jest.enzyme.tsx
src/Apps/Order/Routes/Shipping/Components/FulfillmentDetailsForm.tsx
src/Apps/Order/Routes/Shipping/Components/__tests__/FulfillmentDetailsForm.jest.tsx
src/Components/Address/AddressAutocompleteInput.tsx
src/Components/Address/__tests__/AddressAutocompleteInput.jest.tsx
yarn.lock

The type of this PR is: **FEAT**
This PR solves [EMI-2159] and relates to [EMI-2196]
This PR adds autocomplete for US addresses on auction registration and makes minor changes to the registration form layout to follow our latest specs for address forms.
It also simplifies the autocomplete input with the tradeoff of eliminating tracking for when a user edits an input on an autocompleted address.
[EMI-2159]: https://artsyproduct.atlassian.net/browse/EMI-2159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EMI-2196]: https://artsyproduct.atlassian.net/browse/EMI-2196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2159): Auction registration address autocomplete

---

src/Apps/Artwork/artworkRoutes.tsx
src/System/Router/Utils/serverAppContext.ts
src/System/Router/__tests__/serverRouter.jest.enzyme.tsx

This was coming up with `loadSidebar: true` on the client, since `context.isMobile` was undefined.
Rather than use context for these, seems like we should just use `getENV` as that works as expected everywhere.

fix: use getENV instead of server side context to check IS_MOBILE

---

src/Utils/Hooks/useClientQuery.ts

Resolves [Slack Bug Thread](https://artsy.slack.com/archives/C07PRTJSD6G/p1727723121828589)
To prevent runtime issues from queries being garbage collected by Relay, I think it would be a good idea to [retain](https://relay.dev/docs/guided-tour/accessing-data-without-react/retaining-queries/) all queries fetched with `useClientQuery`.
This fix should resolve the [garbage collection issue](https://artsy.slack.com/archives/C07PRTJSD6G/p1727723121828589). 
I am also open to removing `useClientQuery` entirely in favor of `useLazyLoadQuery`. While `useClientQuery` has a great interface (no `Suspense` 🥳 ), it may be better to only use Relay's standard ways for data fetching (`QueryRenderer`, `fetchQuery` only for callbacks, and `useLazyLoadQueries`).

fix: Retain useClientQuery queries

---

src/Components/DeepZoom/DeepZoom.tsx

Noticed that deepzoom was no longer working, but passing the ref into the dependency array fixed it. Some change between React 17 and 18? Not too sure. 
(My internet is slow, just heads up): 
https://github.com/user-attachments/assets/fed6732b-ecde-487f-9c7c-d6911b79ae34

fix(artwork): Fix deepzoom

---

src/Components/AppDownloadFooter.tsx

The implementation issue stems from enabling page caching, which prevents page pre-fetching in numerous scenarios. Previously, route change completion was only being detected on routes where the loading bar appeared at the top of the screen. In this case, route completion status isn't relevant - we simply need to detect and display based on the number of routes, which is what this implementation now does.
There are two other call sites using this hook that require investigation to determine if additional refactoring opportunities exist.

fix: ensures download banner is shown for all users

---

src/Utils/Hooks/useRouteComplete.ts

This simplifies the hook by removing the state management which fixes the problem we were having of it not firing on cached pages. Thanks to @damassi for noting we could directly check match elements. I'm preserving this implementation to maintain compatibility for existing consumers and it's a more clear semantically.

fix: fixes and simplifies route complete hook

---

src/Apps/Artwork/Components/PrivateArtwork/PrivateArtworkAboutArtist.tsx
src/__generated__/ArtworkAppTestQuery.graphql.ts
src/__generated__/PrivateArtworkAboutArtistQuery.graphql.ts
src/__generated__/PrivateArtworkAboutArtist_artwork.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

This is a 2nd attempt at avoiding API requests for artists on every artwork page query, like https://github.com/artsy/force/pull/14858 (which needed the follow-up fix in https://github.com/artsy/force/pull/14900). Now that https://github.com/artsy/gravity/pull/18377 is in place, artists' `follow_count` should always be available.
While I was in there, I removed queries for `counts.artists`, `counts.forSaleArtwork`, and a 2nd `name` which didn't seem to be used.
If this approach is acceptable, we should just wait until the Gravity change is released and its cache is cleared.

chore(perf): avoid loading artworks' associated artists unnecessarily

---

src/Components/DeepZoom/DeepZoom.tsx

I can't actually tell if something changed since upgrading to React 18 or I'm just noticing it now but the black screen while the deep zoom view loads seemed excessive. I've implemented a loading indicator to provide better user feedback during this delay, ensuring users see something on screen rather than empty space.
https://github.com/user-attachments/assets/00122232-66ce-4a56-8d91-4303f435b290

fix(artwork): adds loading indicator to zoom view

---

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx

Addresses [ONYX-894]
Related Cohesion PR: https://github.com/artsy/cohesion/pull/540
This PR adds tracking to [Alert list](https://staging.artsy.net/favorites/alerts/180931/edit) actions ("View Artworks" & "Edit").
[ONYX-894]: https://artsyproduct.atlassian.net/browse/ONYX-894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Add tracking to Alert list actions

---

.circleci/config.yml

Noticed that bundle stats stopped running on main after https://github.com/artsy/force/pull/14540; this fixes that. 
@artsy/diamond-devs

fix(bundle-stats): Run on main

---

webpack/bundleSplitting.js

Generating this new (~8kb) chunk was an optimization for streaming, but since streaming is currently off we don't need it. Diagnosing whether this might be whats leading to a large increase in transferred js (according to [calibre](https://capture.static.damonzucconi.com/Screen-Shot-2024-12-02-07-52-28.76-9IbI4OkfirSSgc8Kg5ytyYUpgBCVvTOERBQmBL3GQo0rtJoIzsdHXcxD4kOfpLPYnUzpiRj9LYRTfV2KZTgJRR00cTKbZwfObuAY.png)) but not too sure. It could also be React 18 or Relay 18.  

chore(bootstrap): remove client entrypoint streaming bundle

---

src/Apps/Order/Routes/Shipping/Components/__tests__/SavedAddresses.jest.tsx
src/Components/Address/__tests__/utils.ts

This PR relates to [EMI-1685]
**Note: after enabling the test it immediately failed due to a timeout. I therefore increased the timeout to make the test pass. Open to feedback on the approach, and we could check out the intermediate commit if we want to try more improvements.**
This PR makes refinements to some of our test helpers and re-enables a test that has been skipped. The test has been ported from enzyme and hopefully performance will be better now.
The intermediate commit 330b3539251c69f9090124ac4d99a233127845ce shows two different implementations of the once-problematic test for comparison. In short the improvements in this PR don't make a meaningful difference in runtime. Repeated runs in that commit show roughly the same …

perf(EMI-1685): re-enable slow test

---

src/Components/NavBar/Menus/NavBarNotifications.tsx

- [Related Slack Thread](https://artsy.slack.com/archives/C07PRTJSD6G/p1727723121828589)
This reverts lazy loading notifications dropdown (https://github.com/artsy/force/pull/14490) to find out if this causes the bug described in the Slack thread. I cannot reproduce the bug locally and it only happens in Chrome.

fix: Revert lazy loading notifications dropdown

---

src/Components/Address/AddressAutocompleteInput.tsx
src/Components/Address/__tests__/AddressAutocompleteInput.jest.tsx

The type of this PR is: **refactor**
This PR solves is related to [EMI-1934]. Currently it's just a refactor and not a solution.
This PR refactors the address autocomplete component to make use of `useReducer()` rather than separate `useState()` + `useEffect()` calls. I also tried to move some code out of the component itself.
[EMI-1934]: https://artsyproduct.atlassian.net/browse/EMI-1934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(EMI-1934): autocomplete input, now using useReducer

---

data/schema.graphql
src/Apps/Jobs/Components/JobsFilter.tsx
src/__generated__/JobsFilter_viewer.graphql.ts
src/__generated__/jobsRoutes_JobsQuery.graphql.ts

This change removes the dependency on querying jobs through departments, as this functionality won't be available when we switch to the Ashby API. Instead, we're implementing manual grouping that will be compatible with the new API's capabilities. This approach allows us to seamlessly swap the underlying API while maintaining the page's existing functionality. I'll follow up with the corresponding changes in Metaphysics and merge once we're ready to transition to the new service.

chore(jobs): removes dependency on department nested jobs field

---

src/Apps/Order/Routes/Shipping/Components/FulfillmentDetailsForm.tsx
src/Components/Address/AddressAutocompleteInput.tsx
src/Components/Address/AddressFormFields.tsx

Paired with @dzucconi on diagnosis
This PR Resolves [EMI-1934] by removing the `onBlur` prop from our address autocomplete input. It also fixes what is probably a minor bug due to a missing onClear() prop.
This PR fixes an issue where keyboard navigation does not work on the first down-arrow press. We traced this issue to the incoming `onBlur={handleBlur}` prop we pass in from the formik context - it is triggered on the first down arrow press, but the first enter press does not trigger the `onSelect` prop. After the second down arrow press a subsequent enter press does trigger the correct behavior, but for the still-selected first option. A third down arrow press highlights the second option. To put it another way, the first down arrow press triggers that …

fix(EMI-1934): address autocomplete keyboard navigation issue

---

.circleci/config.yml
src/dev.ts

Now that it doesn't take a painful minute to actually serve the app in a browser window, during development automatically open the browser when the server is done booting.

feat(dx): Open browser on yarn start during dev

---

data/schema.graphql
src/Apps/Artwork/Utils/createCollectUrl.tsx
src/Apps/MyCollection/Routes/EditArtwork/Utils/categoryOptions.ts
src/Components/Alert/Components/Filters/__tests__/Medium.jest.enzyme.tsx
src/Components/ArtworkFilter/ArtworkFilters/MediumFilter.tsx

This PR solves [AMBER-1121]
Here I'm including 'Digital Art' in the list of medium filters in the artwork grid so it can be used in front-end marketplace searches, allowing collectors to search specifically for digital artworks. (Partners can also now set 'Digital Art' as the medium in the artwork form in CMS.)
[AMBER-1121]: https://artsyproduct.atlassian.net/browse/AMBER-1121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: including digital art in artwork grid filters 

---

src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
src/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
src/Apps/Artist/artistRoutes.tsx
src/Apps/Auction/__tests__/AuctionApp.jest.enzyme.tsx
src/System/Components/RouterLink.tsx
src/System/Components/__tests__/RouterLink.jest.tsx
src/System/Hooks/__tests__/usePrefetchRoute.jest.tsx
src/System/Hooks/usePrefetchRoute.tsx
src/__generated__/ArtistWorksForSaleRoute_artist.graphql.ts
src/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts

The **goal** here is to not lazy load the artist page works grid when pre-fetching. Might as well take advantage of a background pre-fetch and fetch what we can, thus reducing waiting when the user actually clicks on an artist page link. **Note - this will definitely increase throughput to ElasticSearch which backs the artist page grid! I think this is ok as we're not pre-fetching artists with high volume like we do artworks**.
The way this was accomplished was - add the filter fragment to the route query (behind an `@include`), and then in the containing React component - be able to conditionally render the filter query renderer or the fragment container.
The 'trick' was how to propagate/get that behavior correct when in a pre-fetching context.
**For the query pre-fetch and `@include`** …

feat: dont lazy load artist artworks grid when prefetched

---

cypress/e2e/404.cy.ts
src/Server/startServer.ts
src/server.ts

Fixes missing 404 pages. Not sure why this works fine locally, but when deployed to prod we needed to move the error handler to server.ts. 
Got to the bottom of this (production) issue by rapidly pushing to a review app branch. With latest infra updates it worked fast and well. 
Also added a smoke test!

fix(404): fix missing 404 pages

---

src/Server/middleware/linkHeadersMiddleware.ts
src/html.ts

Fixes `crossorigin` mode of image host in `<link>` preconnect tags and `Link` headers. Ultimately, this will also fix them in Cloudflare's `103` (early hints) responses. This was flagged by a recent page-speed report.

fix: specify correct non-crossorigin mode on image host preconnect hints

---

cypress/e2e/collection.cy.js
src/Apps/Collect/Server/__tests__/redirectCollectionToArtistSeries.jest.ts
src/Apps/Collect/Server/redirectCollectionToArtistSeries.ts
src/Apps/Collect/collectRoutes.tsx
src/server.ts

This PR solves [ONYX-1445]
See [thread](https://artsy.slack.com/archives/C05EEBNEF71/p1733943061015619?thread_ts=1733940262.518139&cid=C05EEBNEF71) for context.
At [multiple](https://github.com/artsy/force/pull/6177) [various](https://github.com/artsy/force/pull/6509) [points](https://github.com/artsy/force/pull/12687) we've migrated artist series-esque `MarketingCollections` to "true" `ArtistSeries`.
We therefore added some redirect mappings for those collections. 
But that mapping file itself was unbeknownst to us adding >100k to the bundle size.
This refactors the redirection strategy to happen purely server-side at the Express layer rather than in the React SSR layer, in order to avoid this bundle bloat!
[ONYX-1445]: …

refactor(collections): modify redirects to be purely server-side

---

src/Components/NavBar/menuData.ts

Noticed this doesn't play nicely with something in our pre-fetching/client-side navigation setup!

fix: remove unnecessary metric query param from hard-coded NAV items

---

cypress/e2e/auction.cy.ts
src/Apps/Auction/Components/AuctionArtworkFilter.tsx
src/Components/Rail/RailHeader.tsx

For some reason the `returnTo` query param is polluting the query that gets dispatched to render the auction/id artwork grid. So disabling that less urgent feature in our artwork rails for now while we figure out a) what it does; and b) how to fix / diagnose the underlying issue. 
Also updated auction smoke test to check for artwork grid existence.  

fix(auctions): Disable returnTo query param in rail titles

---

src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.jest.enzyme.tsx
src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionsRail.jest.enzyme.tsx
src/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
src/Components/Rail/RailHeader.tsx
src/System/Components/RouterLink.tsx

Un-applies https://github.com/artsy/force/pull/14984 and then fixes the underlying issue, which originated in https://github.com/artsy/force/pull/14962. We weren't passing query params across the route in the way that was required.
(Though one would assume passing a string with query params would be sufficient, as a pathname. But no -- pathname is pathname, and query is query, and search is search. When expanding the location (`to`) it expects a full location descriptor which encodes all the props.) 
https://github.com/user-attachments/assets/0cde56a8-3101-4025-b797-45ccefb11810

fix(router): Fix query param issue

---

src/html.ts

With the original ordering, I was not able to get analytics working locally. `window.analytics` would be `undefined`, and the Segment script tags aren't even included in the DOM, nor is the lib being loaded from the Segment CDN.
This ordering seems to work(?).
Seems sus to me, but...

fix: reorder some script tags to fix some weirdness around Segment analytics not loading

---

src/Apps/Settings/settingsRoutes.tsx
src/Server/middleware/userRequiredMiddleware.ts

Adds settings routes and follows route to user required middleware, removing the legacy redirect implementation.

fix: consistent login redirects for settings/favorites

---

src/Apps/Artwork/Components/SubmittedOrderModal/SubmittedOrderModal.tsx
src/Apps/Artwork/Components/SubmittedOrderModal/__tests__/SubmittedOrderModal.jest.tsx
src/__generated__/SubmittedOrderModalQuery.graphql.ts
src/__generated__/SubmittedOrderModal_Test_Query.graphql.ts
src/__generated__/SubmittedOrderModal_submittedOrder.graphql.ts

re: https://artsyproduct.atlassian.net/browse/EMI-2239
I'm actually not 100% sure why the default selecting first conversation is not working in this case. My guess is that the conversation is created async and maybe somehow not refreshed in the original conversations used when navigating. But this explicit conversation reference seems to work and is logical - so going with this.

fix: navigate to newly created conversation after offer submit

---

.gitignore
src/Apps/Artwork/ArtworkApp.tsx

This just removes the extraneous tracking, which I assume was added for some legitimate reason at some point but no longer does anything other than track additionally. This covers all of the scenarios that @mzikherman laid out:
* client-side navigation from a non-artwork page to an artwork page
* client-side navigation from one artwork page to another
* initial SSR navigation to an artwork page

fix(dia-1031): fixes double firing pageview on artwork pages on web

---

.vscode/settings.json

This seems to behave well locally where I still have prettier installed. Was seeing prettier doing some formatting (which `biome` undoes in pre-commit hook from command line) on save still.

fix: specify biome explicitly for typescript

---

src/Components/SalesforceWrapper.tsx

This PR solves [AMBER-1209]
Similar to https://github.com/artsy/volt/pull/8211, but now for collectors
We must not display the SF chat bubble on the mobile version. We handled this during the migration from Zendesk to SF, but our css rule specifies a class that's defined on SF stylesheet, which became outdated after the recent upgrade.
Changes in this PR point update the class name to meet the current definition.
[AMBER-1209]: https://artsyproduct.atlassian.net/browse/AMBER-1209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(AMBER-1209): Update the class name on css to match the component

---

src/Server/bootstrapSharify.ts

Lil update to sharify to [allow the inspect images link to work](https://artsy.slack.com/archives/C045UP78DG8/p1734719548758179?thread_ts=1732742421.746579&cid=C045UP78DG8) when you get to an artwork page via client-side nav.

fix: allow forque link to be exposed to client-side nav'd pages

---

package.json
scripts/start.sh
src/dev.ts
yarn.lock

After some trial, this removes the default open browser on start behavior in favor of a simple cli argument:
- `yarn start --open` -- Falls back to default localhost:PORT url 
- `yarn start --open=http://foo.bar` -- pass in a specific url

feat(start): Add --open cli argument

---

src/Apps/Conversations/components/ConversationCTA/ConversationReviewOfferCTA.tsx
src/Apps/Conversations/components/ConversationCTA/__tests__/ConversationCTA.jest.tsx
src/Apps/Conversations/components/ConversationCTA/__tests__/ConversationReviewOfferCTA.jest.tsx
src/Apps/Conversations/components/Details/OrderInformation/ReviewOrderButton.tsx

This PR solves [https://artsyproduct.atlassian.net/browse/EMI-2218]
This is just removing the modal and opening the appropriate order in the new tab regardless of the state of the order. We currently have this modal opened for multiple states (counteroffer received in different variations, order approved, order payment failing, etc). So I applied this 'open in the new window' across the board. 
Need to discuss with Cami and Vivi what is the appropriate flow we want at the end but for now confirmed with Cami that it's good enough of a change. For now don't want to merge this immediately as we want to have a bit of time to test it before putting it out (mainly make sure there is no major objections to this flow).
So if all looks well - we should merge it when more people from the team is …

chore:  open action prompt in a new window instead of the modal for order actions in conversations

---

src/Components/HeroCarousel/HeroCarousel.tsx

When adding the logged-out hero unit, we inadvertently create a child element in the logged-in state that evaluates to false. While this element isn't rendered, it still gets included in the count, affecting the number of entries in the navigation. The fix is to filter children before passing them to the carousel component.

fix(home): ensures we count cells correctly when logged in

---

src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
src/Apps/Artist/artistRoutes.tsx
src/__generated__/ArtistWorksForSaleRoute_artist.graphql.ts
src/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts

This PR solves [ONYX-1475]
When prefetching an artists's artwork grid content, we are correctly requesting the prepared variables, but  we are not passing the prepared `input` into the fragments as needed. Thus the `{ input : { sort: … } }` argument is missing, which explains the recent reports of unsorted artworks in the grid.
The nature of this bug meant that it was apparent only when client-side navigating to a prefetched artist page (e.g. from an artwork page by clicking on the artist's name).  A direct navigation or hard-refresh would not have repro'd the bug. 
[ONYX-1475]: https://artsyproduct.atlassian.net/browse/ONYX-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: include initial input/sort when prefetching artist artworks

---

src/Apps/Order/redirects.tsx

This PR solves [EMI-2213]
Adding a redirect for the payment failed scenario, so the user is presented with the payment/new route instead of an infinite loop
https://github.com/user-attachments/assets/6ff9bf7d-a210-4b27-86e3-14e0dd307278
[EMI-2213]: https://artsyproduct.atlassian.net/browse/EMI-2213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2213): failed payment redirect

---

scripts/create-review-app-subdomain.js

[Cloudflare docs](https://developers.cloudflare.com/api/resources/dns/subresources/records/methods/create/) indicate that an array of tags (`:`-delimited strings) can be set when creating DNS records. Let's add a tag on any records created automatically by this script to support review apps. That should make it possible to clean up these records later on without too much risk of breaking production.
Caveat: I haven't run this script but errors should surface upon the next review app creation.

chore: tag review app CNAME records accordingly, to make automatic clean-up safe (later)

---

src/Components/ArtworkGrid/ArtworkGrid.tsx

Pretty simple! The auctions team would like the auction page grid layout to have 4 artwork columns instead of 3 (which confusingly means changing this span number from a 4 to a 3).

feat: move to 4 artworks wide for auction pages

---

src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryFigure.tsx
src/Apps/Artwork/Components/ArtworkLightboxPlaceholder.tsx
src/Apps/Fair/Components/FairHeader/FairHeaderImage.tsx
src/Components/HeaderIcon.tsx

Documentation [indicates](https://www.debugbear.com/blog/fetchpriority-attribute) that `<link rel="preload" as="image" ...` elements can support a `fetchpriority` attribute. I'd have thought preloading was enough for the browser to fetch at a high priority, but let's see if adding this reduces warnings or helps LCP further. At the moment, the browser calculates a "low" priority for the artwork placeholder image despite the many signals to the contrary.

chore: add high fetch priority to preload links when applicable

---

src/Apps/Auction/Components/__tests__/AuctionArtworkFilter.jest.enzyme.tsx
src/Apps/Auction/Components/getArtworkFilterInputArgs.ts

Since moving to a 4 artwork column wide form on the auction page, requesting 39 (not evenly divisible) leaves an incomplete row, so let's move to 40.

chore: move to page size of 40 for auction page (4 column wide)

---

src/Components/Artwork/Details/Details.tsx
src/Components/ArtworkGrid/ArtworkGrid.tsx

This PR solves [EMI-2256] (https://artsyproduct.atlassian.net/browse/EMI-2256)
This seems to be too easy of a fix but seems to work for me on all the screens that I was checking. The thing I'm not sure about if we need to make this line conditional. Like is there rails that would never include this 5th line?
Also remember @starsirius that you said that you've hardcoded the hight in some rail and wonder if we should clean that up and see if things are still working.
[EMI-2256]: https://artsyproduct.atlassian.net/browse/EMI-2256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add additional line to the artwork metadata placeholder

---

src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
src/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
src/Apps/Artist/artistRoutes.tsx
src/__generated__/ArtistWorksForSaleRoute_artist.graphql.ts
src/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts

As a UX optimization - we would load the works grid on an artist route while in a prefetching context, versus the standard behavior of lazily loading the grid only after a user landed on an artist route.
This had the affect of increasing ElasticSearch traffic, resulting in some latency/alerts. Since this UX optimization isn't strictly _necessary_, was just a nice discretionary thing - let's revert. We typically wouldn't want to accept a trade-off of an optional improvement that has a negative affect on ElasticSearch.

chore: revert prefetching artist works over lazily loading

---

src/Apps/Components/INPOptimizer.tsx
src/Apps/Components/Layouts/index.tsx
src/Apps/Components/__tests__/INPOptimizer.jest.tsx
src/Components/Artwork/Details/PrimaryLabelLine.tsx
src/Components/RouteTabs.tsx

This PR solves [DIA-1049]
This adds a new optimization strategy around INP via an `INPOptimizer` component. 
**Feature Flag:**
- `diamond_experimental-inp-optimization` 
**Impact Areas:**
- Only on **mobile**!
- `/artwork/:id`
- `/artist/:id` 
**Review App:**
- https://inp-test-2.artsy.net/
If ☝️ is successful in google search console and we see big drops we can expand this site-wide. 
**Issue**: 
We get subpar INP scores on artwork / artist due to the overhead involved in clicking on a link, then transitioning via our router to a new fully rendered page. There's an unavoidable overhead baked into using it. 
**The Fix**: 
The fix is straightforward. Instead of transiting from fully-rendered page to fully-rendered page, we instead transition to a blank page …

feat(performance): Add INP optimization strategy for mobile web

---

src/Apps/Home/Components/HomeFeaturedMarketNews.tsx
src/Components/AppDownloadBanner.tsx
src/Components/AppDownloadFooter.tsx
src/Components/NavBar/useNavBarHeight.ts

This implementation disables the top download banner specifically on the homepage, which adjusts the global nav height accordingly. The footer banner is also disabled on the homepage only. The system treats homepage visits as standard route changes—the banner will hide when arriving on the homepage if previously displayed, then reappear when navigating away via route change.

fix(dia-1058): avoid extraneous app download ctas on homepage

---

src/Apps/Artist/Routes/CV/ArtistCVRoute.tsx
src/Apps/Artist/Routes/CV/Components/ArtistCVGroup.tsx
src/__generated__/NotificationQuery.graphql.ts
src/__generated__/NotificationViewingRoom_viewingRoom.graphql.ts
src/__generated__/PartnerViewingRoomsGrid_Test_Query.graphql.ts
src/__generated__/PartnerViewingRoomsGrid_ViewingRoomsQuery.graphql.ts
src/__generated__/ShowApp_Test_Query.graphql.ts
src/__generated__/ShowViewingRoom_Test_Query.graphql.ts
src/__generated__/ShowViewingRoom_show.graphql.ts
src/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts
src/__generated__/ViewingRoomApp_DraftTest_Query.graphql.ts
src/__generated__/ViewingRoomApp_LoggedOutTest_Query.graphql.ts
src/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts
src/__generated__/ViewingRoomApp_ScheduledTest_Query.graphql.ts
src/__generated__/ViewingRoomCard_Test_Query.graphql.ts
src/__generated__/ViewingRoomCard_viewingRoom.graphql.ts
src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
src/__generated__/ViewingRoomMeta_viewingRoom.graphql.ts
src/__generated__/ViewingRoomPublishedNotification_test_Query.graphql.ts
src/__generated__/ViewingRoomsApp_Test_Query.graphql.ts
src/__generated__/ViewingRoomsFeaturedRail_featuredViewingRooms.graphql.ts
src/__generated__/ViewingRoomsLatestGrid_ViewingRoomsAppQuery.graphql.ts
src/__generated__/ViewingRoomsLatestGrid_viewingRooms.graphql.ts
src/__generated__/partnerRoutes_ViewingRoomsQuery.graphql.ts
src/__generated__/showRoutes_ShowQuery.graphql.ts
src/__generated__/viewingRoomRoutes_ViewingRoomQuery.graphql.ts
src/__generated__/viewingRoomRoutes_ViewingRoomsAppQuery.graphql.ts

This PR implements semantic heading structure on artist CV pages by adding the h1 tag and marking up subheaders with h2 tags.

fix(dia-1090): adds h1 tag to artist CV pages

---

src/Components/ArtsyShippingEstimate.tsx
src/Components/__tests__/ArtsyShippingEstimate.jest.tsx
src/__generated__/ArtsyShippingEstimate_Test_Query.graphql.ts

Resolves [EMI-2277]
This PR adds some tests for the shipping widget. Due to the way we load it from a script tag the tests are a little strange; maybe there is a better way. We have the library in our dev dependencies for example, but i'm just mocking out the entire lib with `jest.fn()`s.
We can add more tests or things for the specific complex estimate params creation as we go - wanted to get a solid base to work off.
It also corrects two minor bugs not visible outside staging.
[EMI-2277]: https://artsyproduct.atlassian.net/browse/EMI-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2277): add tests for shipping estimate widget

---

src/Components/ArtsyShippingEstimate.tsx

We do have limited options in what we can currently edit/modify.
For example there does not seem to be a clear way to space things within the modal. We can def contact arta and see if they can add configurable paddings/margins to the widget components but not sure it's worth it at this point. Maybe it looks good enough for now?
I tried to get it as close to the design as currently possible without too much trouble and will ask bunch of questions in slack. Will do a follow up after but think we can merge it as an improvement so people can play with more refined version on staging/prod.

chore: attempt to style Arta widget

---

src/Apps/Show/Components/ShowMeta.tsx

Updates the meta description format for show pages to use more conversational language. This change addresses an issue where some meta descriptions are not appearing in search engine results pages (SERP). While Google's handling of meta descriptions can be unpredictable - sometimes modifying or excluding them without clear reasoning - this update to a more conversational format may improve their likelihood of being displayed.
> Google will sometimes use the [<meta name="description"> tag](https://developers.google.com/search/docs/crawling-indexing/special-tags) from a page to generate a snippet in search results, if we think it gives users a more accurate description than would be possible purely from the on-page content. A meta description tag generally informs and interests users with a …

fix(show): updates meta description format

---

src/Components/ArtsyShippingEstimate.tsx

This PR solves [EMI-2276]
depends on https://github.com/artsy/cohesion/pull/555
This PR implements tracking for the shipping estimate test. We track both opening the widget and viewing an estimate, including the min/max values, origin/destination strings and currency. Because the widget doesn't have an api for the estimate event, the view event is triggered using a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) which watches the dom for changes.
Tests: I don't think this is worth testing due to the amount of mocking that would be required to manipulate the dom. I think we should manually test instead.
[EMI-2276]: https://artsyproduct.atlassian.net/browse/EMI-2276?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

chore(EMI-2276): Tracking for shipping estimate widget

---

src/Components/ArtsyShippingEstimate.tsx

Followup to #15151 
This PR updates our shipping estimate widget events to use real cohesion events.
#minor

fix(EMI-2276): use new cohesion events for tracking

---

src/Components/ArtsyShippingEstimate.tsx

chore: update the test for disqualified message for Arta estimate widget

---

src/Components/ArtworkFilter/ArtworkFilters/FramedFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/SignedFilter.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/FramedFilter.jest.tsx
src/Components/ArtworkFilter/ArtworkFilters/__tests__/SignedFilter.jest.tsx

This PR solves https://www.notion.so/artsy/Position-name-and-copy-of-framed-filter-differs-between-app-and-web-18ccab0764a0809b8440f23dad62f25f?pvs=4
align copy with app

chore: align framed and signed copy with app

---

src/Apps/Fair/Routes/FairArtworks.tsx

This PR solves: https://www.notion.so/artsy/web-Signed-Framed-filters-missing-on-fairs-artwork-grids-intentional-18ccab0764a0804c9562f3fa2a6a95c9?pvs=4
This PR adds framed and signed filters to the fairs screen
https://github.com/user-attachments/assets/7a20ae1e-c454-4edf-bcbb-77c7259dd880

chore: add framed and signed filters to fairs

---

src/Apps/Article/Components/ArticleVisibilityMetadata.tsx

The infinite scrolling feature updates the title and URL when encountering new articles during page scroll. While this worked for subsequent articles, the initial article's behavior would strip the query string parameters. This fix preserves any existing query string in the URL, resolving the tracking issue.

fix(article): preserves query string if present

---

cypress/e2e/home.cy.ts
src/Apps/Home/Components/HomeMeta.tsx
src/Components/MetaTags.tsx
src/Components/NavBar/NavBar.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.enzyme.tsx
src/Components/__tests__/MetaTags.jest.enzyme.tsx
src/Server/middleware/hardcodedRedirects.ts
src/routes.tsx

This PR solves [ONYX-1519] and [ONYX-1536]
First of several PRs to retire consignments from web
Can track progress at review app: https://swa.artsy.net/
This one:
[ONYX-1519]: https://artsyproduct.atlassian.net/browse/ONYX-1519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ONYX-1536]: https://artsyproduct.atlassian.net/browse/ONYX-1536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove /sell page

---

scripts/clean.sh

#minor
This PR updates the `yarn clean` script to empty the rspack cache. I also made the echoed output a little more verbose.

chore: update `yarn clean` script to clean rspack cache

---

src/Apps/Components/Layouts/LayoutLogoOnly.tsx
src/Components/NavBar/NavBarPrimaryLogo.tsx

This PR updates the Artsy Logo `to` prop when the client is Eigen to disable navigating to the homepage in the Order App

fix: Disable Artsy logo link for Eigen

---

src/Apps/CollectorProfile/Components/CollectorProfileHeader/CollectorProfileHeader.tsx
src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx

Added responsive props to the button and fixed a subtle layout bug where an unsized tooltip was causing horizontal page overflow. The overflow wasn't noticeable until a dialog was opened, which would appear off-center due to the incorrect page width. While tooltips should ideally have a default content width, this change addresses the immediate layout issue.

fix(my-collection): corrects layout for mobile

---

src/Apps/About/AboutApp.tsx

This PR solves [ONYX-1532]
This PR remove sell art from `/about`
[ONYX-1532]: https://artsyproduct.atlassian.net/browse/ONYX-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: sell art from /about

---

src/Components/ArtworkFilter/ArtworkFilters/FilterExpandable.tsx
src/Components/ArtworkFilter/ArtworkFilters/SignedFilter.tsx

**Context:** https://www.notion.so/artsy/mWeb-last-filter-group-signed-remains-hidden-when-expanded-18ccab0764a080c3afa6cb099e8b3f1c?pvs=4
This PR fixes the issue of the hidden last item on the filters.
https://github.com/user-attachments/assets/4447184e-43e5-415d-9114-3a6fe8646485

fix: expand scrollview on signed press

---

src/Components/ArtsyShippingEstimate.tsx

#minor
This PR calls `event.stopPropagation()` to prevent a click on the estimate widget link from opening the shipping details collapse element.

fix: stop propagation of estimate widget open clicks

---

package.json
src/Components/ArtsyShippingEstimate.tsx
yarn.lock

This PR solves [EMI-2291]
This PR updates how we do shipping estimate tracking to handle single values without a range as well as cases where no estimate is available.
<details><summary>Example of 3 consecutive estimates (not available, available with geolocated city, available with postal code input only):
</summary>
<p>
</p>
</details> 
[EMI-2291]: https://artsyproduct.atlassian.net/browse/EMI-2291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2291): update estimate widget tracking

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.jest.tsx
src/Components/ArtsyShippingEstimate.tsx
src/Components/__tests__/ArtsyShippingEstimate.jest.tsx

This PR solves [EMI-2293]
This PR updates our conditional widget rendering code to use experimental groups instead of a release feature flag and adds tracking to do it.
[EMI-2293]: https://artsyproduct.atlassian.net/browse/EMI-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2293): use experimental groups instead of release feature flag for estimate widget

---

src/Apps/Artwork/Components/ArtworkTopContextBar/ArtworkTopContextBar.tsx
src/Apps/Artwork/Components/ArtworkTopContextBar/__tests__/ArtworkTopContextBar.jest.enzyme.tsx
src/__generated__/ArtworkAppTestQuery.graphql.ts
src/__generated__/ArtworkTopContextBar_Test_Query.graphql.ts
src/__generated__/ArtworkTopContextBar_artwork.graphql.ts
src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts

In this update, I've removed the context bar functionality except where needed for auctions. The navigation is simplified to a single return link to the parent artist page. Additionally, I've implemented structured data markup to explicitly define the artist-artwork relationship for SEO purposes.

feat(artist): updates breadcrumbs to always show artist except for auctions

---

src/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitLoggedOut.tsx

This PR removes the hero unit A/B test, implementing the experiment branch as the standard version. After deployment, I'll clean up by removing the feature flag (`diamond_hero-app-download`).

chore(home): closes out hero unit a/b test in favor of experiment branch

---

src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworksHeader.tsx
src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx

The share lists feature has been enabled in production since the hackathon and has been successfully launched. We can proceed with removing the feature flag.

chore: removes share lists feature flag

---

src/Apps/Marketing/Components/MarketingHeaderPrimary.tsx
src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx

This PR addresses an overlooked page from the initial removal, closing out the remaining code in favor of the experiment branch.

chore: closes out remaining test code for app download header

---

src/Apps/Artwork/ArtworkApp.tsx
src/Apps/Artwork/Components/ArtworkDetails/index.tsx

This PR solves [PBRW-479]
First reported in the [bugs channel](https://artsy.slack.com/archives/C07PRTJSD6G/p1739468756482839), was noticed that on certain artworks there's a strange flashing behavior. 
Its hard to repo, but for now lets disable lazy loading (when scrolling into view) on that component. Its already lazy loaded via a QueryRenderer, so in a sense it just makes the page feel more stable (as an improvement). 
[PBRW-479]: https://artsyproduct.atlassian.net/browse/PBRW-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(artwork): Attempt to fix mysterious flashing details

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkHeader.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkHeader.jest.tsx
src/__generated__/MyCollectionArtworkHeaderTestQuery.graphql.ts
src/__generated__/MyCollectionArtworkHeader_artwork.graphql.ts
src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts
src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts

This PR solves [ONYX-1547]
Restores the **Edit Artwork Details** button for MyC artworks.
Previously this was deliberately suppressed for consigned works. But since consignment is on hold now, we now want to "unlock" these works for editing and deletion.
| ![Screenshot 2025-02-14 at 11 31 31 AM](https://github.com/user-attachments/assets/411db583-a329-43c7-b280-92a66cfef859) | ![Screenshot 2025-02-14 at 11 31 32 AM](https://github.com/user-attachments/assets/55b06353-e1cc-4bdb-ab2f-dddcabe1291c) | 
[ONYX-1547]: https://artsyproduct.atlassian.net/browse/ONYX-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(my collection): re-enable artwork editing regardless of submission status

---

docs/unleash_a-b_testing.md
src/Components/ArtsyShippingEstimate.tsx

followup to [EMI-2293]
This PR updates our shipping estimate widget `useEffect(trackExperimentViewed` call to have an explicit empty dependency array. It also update the docs to include this array.
[EMI-2293]: https://artsyproduct.atlassian.net/browse/EMI-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2293): update hook deps and docs

---

src/Apps/Order/Routes/Payment/ExpressCheckoutPrototype/ExpressCheckout.tsx
src/Apps/Order/Routes/Payment/ExpressCheckoutPrototype/ExpressCheckoutProvider.tsx
src/Apps/Order/Routes/Payment/PaymentContent.tsx
src/Apps/Order/Routes/Shipping/index.tsx
src/__generated__/ExpressCheckoutProvider_order.graphql.ts
src/__generated__/ShippingTestQuery.graphql.ts
src/__generated__/Shipping_order.graphql.ts
src/__generated__/orderRoutes_ShippingQuery.graphql.ts
src/__generated__/useSaveFulfillmentDetailsMutation.graphql.ts
src/__generated__/useSelectShippingQuoteMutation.graphql.ts

This PR solves [EMI-2294]
This PR:
- Moves the express checkout element to the shipping route page
- Does not display header of spacers unless their are available payment methods
- Styles to button to match designs 
https://github.com/user-attachments/assets/ca9a0977-eb73-41a1-aacf-a6880169bfb7
https://github.com/user-attachments/assets/a02a1b96-16e1-422f-8a6c-8426b00c39bc
[EMI-2294]: https://artsyproduct.atlassian.net/browse/EMI-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2294): move and style express checkout element

---

src/Apps/Auction/Components/AuctionActiveBids.tsx
src/Apps/Auction/Components/__tests__/AuctionActiveBids.jest.enzyme.tsx
src/Apps/Auctions/Components/MyBids/MyBidsBidItem.tsx
src/Apps/Settings/Routes/Auctions/Components/SettingsAuctionsLotStanding.tsx
src/Apps/Settings/Routes/Auctions/Components/UserActiveBids.tsx
src/Apps/Settings/Routes/Auctions/Components/UserBidHistory.tsx
src/Apps/Settings/settingsRoutes.tsx
src/__generated__/MyBidsBidItem_Test_Query.graphql.ts
src/__generated__/MyBidsBidItem_saleArtwork.graphql.ts
src/__generated__/MyBidsQuery.graphql.ts
src/__generated__/MyBids_Test_Query.graphql.ts
src/__generated__/SettingsAuctionsLotStanding_lotStanding.graphql.ts
src/__generated__/SettingsAuctionsRouteQuery_Test_Query.graphql.ts
src/__generated__/UserActiveBids_Test_Query.graphql.ts
src/__generated__/UserBidHistory_Test_Query.graphql.ts
src/__generated__/settingsRoutes_SettingsAuctionsRouteQuery.graphql.ts

Address EMI-2234
This solution is not ideal but as we currently don't have a good way to pull updated current bid info from live auction - add 'live bidding' instead of displaying bid status in relevant screens similar to how we display it on Artwork screen:
|Before|After|
|---|---|
|My Bids screen||
|![Screenshot 2025-02-19 at 4 33 54 PM](https://github.com/user-attachments/assets/d765790d-fc59-4fbc-9545-453e47ac22fd)|![Screenshot 2025-02-19 at 4 35 26 PM](https://github.com/user-attachments/assets/15001cf6-dbdd-455c-8c86-108a38e794fd)
|Auction screen| |
|![Screenshot 2025-02-19 at 4 32 00 PM](https://github.com/user-attachments/assets/5a8e76cd-ee30-4497-92d9-dfe39397d2cd)|![Screenshot 2025-02-19 at 4 31 29 PM](https://github.com/user-attachments/assets/a692b02e-0587-458b-9d20-cf72ee7ec3a …

feat: update myBids screens to respect sale isLiveOpen attribute

---

src/Apps/ViewingRoom/Routes/Works/ViewingRoomWorksRoute.tsx

Small bug from the image component rewrite. I still feel like we should require width and height. I think there is no valid argument against that, and if you want to use a custom image then you should just use a simple `img` tag.

fix(viewing-rooms): corrects image dimensions

---

hokusai/staging.yml

CPU usage in staging force has climbed dramatically since the end of January. This seems to be causing some stability issues. I tried temporarily horizontally scaling to 10 pods and it just continued to use all available cpu. I want to test vertical scaling. [Datadog metrics](https://app.datadoghq.com/dashboard/2n5-6tr-ypp/kubernetes-deployments?fromUser=true&refresh_mode=sliding&tpl_var_deployment%5B0%5D=force-web-spotty&tpl_var_env%5B0%5D=staging&tpl_var_hpa%5B0%5D=force-web-spotty&from_ts=1740777157702&to_ts=1740778957702&live=true) for cpu usage. This is not a long term solution. We need to hunt down the cause of the bump.

chore: bump pod cpu request from 100m to 500m

---

src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx

This PR solves [DIA-1100]
Quick copy change: 
remove “by rising talents” so that the text says: 
"The best works on Artsy, all available now."
[DIA-1100]: https://artsyproduct.atlassian.net/browse/DIA-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIA-1100): Update copy on curators picks rail on homepage

---

src/Components/Alert/AlertProvider.tsx
src/Components/SavedSearchAlert/constants.ts
src/Components/SavedSearchAlert/useActiveFilterPills.ts

This PR solves [ONYX-1576]
The new framed and signed filters from the recent Hackathon have not been released due to incompatibility with our alerts UX.
After some [discussion](https://artsy.slack.com/archives/C05EQL4R5N0/p1741273678919609) we decided that it is acceptable to release these filters _without_ alert support until/unless we have more confidence in them as alert criteria.
This PR simply removes `framed` and `signed` from the allowlist for _alert_ criteria. (They remain in the allowlist for _filter_ criteria.)
| ![broke](https://github.com/user-attachments/assets/c98cca16-4a45-44b4-9a84-86c48aebee69) | ![fixed](https://github.com/user-attachments/assets/f2d3b612-c813-48a7-8cfc-521c9d9ae7bd) | 
[ONYX-1576]: …

fix(filters): allow "framed" and "signed" as filter criteria, but not alert criteria

---

src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx

This PR solves [ONYX-1569]
Simply puts the MyC sharing widget behind a flag again (this time managed by Onyx: `onyx_shareable-my-collection`) while we sort out the details of this feature.
The flag is disabled in production, and enabled in dev/staging by opting in user IDs.
[See ticket](https://artsyproduct.atlassian.net/browse/ONYX-1569) for some relevant stats related to usage of this feature so far.
| Before <br/>(or with user id explicitly opted in) | After |
| ![before or opt](https://github.com/user-attachments/assets/cfd0b570-b147-4a3d-9aae-1481e79f5f71) | ![after](https://github.com/user-attachments/assets/02c70fe0-c5af-4870-b3e0-3b153504a853) | 
[ONYX-1569]: https://artsyproduct.atlassian.net/browse/ONYX-1569?atlOrigin=eyJpIjoi …

chore(MyC): put sharing widget behind a feature flag

---

src/Apps/Artwork/Components/ArtworkLightbox.tsx

When inserting images into the gallery, we determine the container size by finding the maximum height across all images then create a static container height. This prevents UI shifting during carousel navigation. However, when images are missing geometry data, we encounter an issue where the container sizing becomes incorrect. Since these images default to a 1:1 aspect ratio instead of their correct aspect ratio, they stretch to fill the container, resulting in distorted images and a broken UI.
While there's no elegant solution really, this is a practical fix for these edge cases.

fix(artwork): improves fallback when images are missing geometry

---

src/Apps/Checkout/Components/PaymentForm.tsx
src/Apps/Checkout/Components/PaymentForm/index.tsx
src/Apps/Checkout/Routes/CheckoutOverviewRoute.tsx

This PR solves [EMI-2308]
This maps to [step 1](https://www.notion.so/artsy/Stripe-Payment-Element-189cab0764a080cebe0bcb2fea09295f?pvs=4#191cab0764a0808f91b1e5009dc51919) of the payment flow in the tech plan. The [design](https://www.figma.com/design/kaBdUapJIWs9YL9ATlPDzw/Checkout-Redesign?node-id=1304-27470&t=bNrEN8Xc3hA5IRFB-4) is not fully done yet, but we can start developing the payment flow and come back to polish the visual when ready.
The idea is to have a functional payment element under the new `/checkout` route with the `onBehalfOf` param working as intended, which can be seen in the video below.
https://github.com/user-attachments/assets/31291cef-e75c-4c54-b9ac-57caab052f3d
[EMI-2308]: …

feat(EMI-2308): render Payment Element UI and enable dynamic payment methods for connected accounts

---

src/Apps/Order/Routes/Payment/PaymentContext/OrderPaymentContext.tsx
src/Apps/Order/Routes/Payment/PaymentContext/orderPaymentReducer.ts
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Order/Routes/__tests__/Payment.jest.enzyme.tsx

Following the pattern introduced for shipping screen https://github.com/artsy/force/pull/15282 adding loading state for the payment route as well.
Seems to fix the flicker and double render on reload.

fix: add loading state for payment route of order app so that the screen does not flicker on load

---

src/Apps/Auction/Components/AuctionArtworkFilter.tsx
src/Apps/Show/Components/ShowArtworks.tsx
src/Apps/Show/__tests__/ShowArtworks.jest.enzyme.tsx
src/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
src/Components/ArtworkFilter/index.tsx
src/Components/ArtworkGrid/ArtworkGrid.tsx

This PR enables flat grid layouts for artwork displays on show pages so that the curated sort is intuitively reflected. The artwork grid implementation has been refactored to decouple the layout logic from auction-specific checks, making it more flexible for use across different contexts and collection types.

feat:(dia-1117): update grid on gallery curated sort for gallery shows

---

src/Components/ShareCollectionDialog.tsx

Makes the change [discussed here](https://github.com/artsy/force/pull/15110/files#r1994348426), in order to prevent unintended sharing with partners of the user's saved artwork lists.
This PR solves [ONYX-1612]
[ONYX-1612]: https://artsyproduct.atlassian.net/browse/ONYX-1612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: unlink partner sharing from public list sharing

---

src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworksHeader.tsx
src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
src/Apps/User/Routes/UserCollectionRoute.tsx
src/Components/ShareCollectionDialog.tsx

This PR solves [ONYX-1570]
Tracking events for the “Share” Saves Collection feature:
- Click Share Button – When a user clicks the “Share” button.
- Copy URL – When a user clicks the “Copy URL” button.
- Open in New Tab – When a user clicks the “Open in New Tab” button.
- Shared Page View – When someone opens a shared saves page.
[ONYX-1570]: https://artsyproduct.atlassian.net/browse/ONYX-1570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onyx-1570): tracking share saves

---

package.json
yarn.lock

@dzucconi  caught an SSR error with the latest `@artsy/dismissible` changes. Fixed [there](https://github.com/artsy/dismissible/pull/9) and bumping here.

chore(dismissible): Make SSR safe @latest

---

src/Components/Notifications/NotificationItem.tsx
src/__generated__/NotificationItem_notification.graphql.ts
src/__generated__/NotificationItem_test_Query.graphql.ts
src/__generated__/NotificationsListNextQuery.graphql.ts
src/__generated__/NotificationsListQuery.graphql.ts
src/__generated__/NotificationsList_test_Query.graphql.ts

Previously, images would occasionally break the notifications dropdown layout, causing overflow issues and an unwanted horizontal scroll bar. I've implemented our horizontal overflow component with a gradient fade-out, which maintains the layout while still allowing users to peek at overflowing content via scroll if needed.
Additionally, I've integrated blur hashes for these images - an ideal use case for that feature as the component is client-side and contains images which are much less likely to be cached.
| --- | --- |

fix(dia-1219): notifications item may overflow

---

src/Components/Artwork/Details/SaleMessage.tsx
src/Components/Notifications/PartnerOfferArtwork.tsx
src/Components/Notifications/PartnerOfferCreatedNotification.tsx
src/Components/Notifications/__tests__/PartnerOfferCreatedNotification.jest.tsx

Another even simpler way to deal with issue in https://artsyproduct.atlassian.net/browse/EMI-2311
My proposal here is to render Metadata for the artwork as is, including pricing line that accounts for partner offer. And then the additional line that notification adds will only render price without discount.
This is alternative of a solution explored here: https://github.com/artsy/force/pull/15293
And the current view:
And updated view proposed on this pr:

fix(EMI-2311): another attempt to deal with empty line in partner offer notification

---

docs/adding_new_app.md
docs/caching.md
src/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
src/Apps/Artist/artistRoutes.tsx
src/Components/NavBar/NavBar.tsx
src/Components/NavBar/NavBarDropdownPanel.tsx
src/System/Components/RouterLink.tsx
src/System/Hooks/__tests__/usePrefetchRoute.jest.tsx
src/System/Hooks/usePrefetchRoute.tsx
src/System/Router/Route.tsx

This builds in support for declaratively prefetching route dependencies, when a user hovers over a RouterLink that matches the path. Currently only enabled on artist! But lets evaluate. 
Guarded behind feature flag: 
- `diamond_prefetch-subqueries`
See:
- [Previous implementation](https://github.com/artsy/force/pull/15090) that we needed to back out of due to ES issues, hopefully remedied by only triggering via hover
New API: 
```tsx
const myRoute = [
{
path: '/foo/:id',
Component: FooApp,
query: ...,
// Automatically receives forwarded arguments from `prepareVariables` or  `params` 
prefetchSubQueries: [
SomeArtworkGridQuery
] 
}
]
```
Opening PR for discussion, since this has the potential to impact some system dynamics by fetching grids up front, when …

feat(performance): Add support for prefetching route sub queries via `prefetchSubQueries` on hover

---

src/Apps/Artwork/Components/ArtworkLightbox.tsx

I think we could probably remove this feature flag completely, but we might as well just see this through into production.

fix(artwork): switches to use correct feature flag

---

src/Apps/CollectorProfile/Routes/Saves/Components/SavesArtworksHeader.tsx
src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
src/Apps/User/Components/UserCollectionArtworks.tsx
src/Components/ShareCollectionDialog.tsx
src/Components/__tests__/ShareCollectionDialog.jest.tsx
src/__generated__/MyCollectionRouteQuery.graphql.ts
src/__generated__/MyCollectionRoute_me.graphql.ts
src/__generated__/SavesArtworksHeaderQuery.graphql.ts
src/__generated__/ShareCollectionDialogMutation.graphql.ts
src/__generated__/collectorProfileRoutes_MyCollectionRouteQuery.graphql.ts

This PR solves [ONYX-1627]
Updates the recent Hackathon project for sharing artwork lists. 
Highlights:
- Changes the UX to a toggle (rather than sharing upon mount) so that **un-sharing is permitted**. This is analogous to the existing toggle for sharing lists for partner offers.
- Ensures that the collection **slug is available in the url**, even on the initial share
- Updates copy to be consistent with the public-facing **language** for existing feature ("list" instead of "collection")
- Adds **test coverage** (based on somewhat iffy Claude results which I had to touch up)
Not in scope:
- Trying to reconcile the copy or the UX between this feature and the Partner Offer sharing. Punting on that based on today's office hours discussion.
cc @mzikherman …

feat(collection sharing): update UI and allow un-sharing

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx

#minor
This PR solves [EMI-2351]
For some reason we aren't setting postal code when the user selects a shipping address in express checkout. This PR fixes it.
[EMI-2351]: https://artsyproduct.atlassian.net/browse/EMI-2351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2351): Add postal code to payload when selecting apple pay shipping address

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
src/Apps/Order/Hooks/useOrderTracking.tsx

The type of this PR is: **Chore*
This PR solves [EMI-2366]
This adds the `ExpressCheckoutViewed` event for express checkout as well as moves all express checkout tracking to `useOrderTracking`. 
[EMI-2366]: https://artsyproduct.atlassian.net/browse/EMI-2366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2366): track express checkout viewed

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
src/Apps/Order/Components/ExpressCheckout/index.tsx

This PR makes 2 optimizations to the express checkout flow:
- Don't fully reset the order on load - pass the initial line items total and rely on subsequent events like shipping address and shipping rate selection to update totals including line items.
- show pickup last in the shipping rates list.

chore: Show pickup last, do less work to reset order on load

---

src/Apps/Artwork/Components/ArtworkTopContextBar/ArtworkTopContextBarSale.tsx
src/Apps/Artwork/Components/ArtworkTopContextBar/__tests__/ArtworkTopContextBarSale.jest.tsx

Corrects the layout of the auction artwork dynamic breadcrumb when there is a countdown.

fix(artwork): fixes layout for auction artwork breadcrumb

---

src/Components/ArtsyShippingEstimate.tsx

As we are not even loading this widget if artwork is not eligible the changes here are very scoped!

chore(EMI-2340): remove emerald_shipping-estimate-widget flag for arta widget estimate

---

src/Components/NavBar/NavBar.tsx

This PR solves [DIA-1246]
Added two new links to the nav: 
- Artsy for Galleries in the top navigation
- Collecting 101 in the bottom navigation 
Museums and Fairs & Events are both hidden at max-width: 900px so Collecting 101 stays visible for smaller screens.
Before:
After:
[DIA-1246]: https://artsyproduct.atlassian.net/browse/DIA-1246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(DIA-1246): Artsy for Galleries and Collecting 101 pages 

---

src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckout.jest.tsx
src/Apps/Order/Components/ExpressCheckout/index.tsx
src/__generated__/ExpressCheckout_Test_Query.graphql.ts
src/__generated__/ExpressCheckout_order.graphql.ts

This PR solves [EMI-2377]
Now that the seller info is [available from MP](https://github.com/artsy/metaphysics/pull/6581), we can configure the Stripe Elements provider with the proper `onBehalfOf` parameter.
Note that when the partner's stripe account id is missing in exceptional cases, depending on the value, the behavior would be different. I'll create a separate ticket to follow up and avoid silent failures or incorrect transactions. More details inline.
[EMI-2377]: https://artsyproduct.atlassian.net/browse/EMI-2377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: configure Apple Pay `onBehalfOf` the partner

---

src/System/Components/RouterLink.tsx
src/System/Hooks/usePrefetchRoute.tsx

This PR (partially) solves [DIA-1224]
Removing some old feature flags that are no longer needed:
- diamond_prefetch-on-enter
- diamond_prefetch-on-enter-logged-out
- diamond_prefetch-hover
[DIA-1224]: https://artsyproduct.atlassian.net/browse/DIA-1224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(DIA-1224): Removing feature flags 

---

src/Components/PriceRange/Histogram.tsx

This PR solves [ONYX-1512]
Fixes a small visual regression that crept in sometime over the past few years:
While it's relatively minor visually it does have an impact on the interaction between slider and histogram, since the slider range handles were no longer toggling the bars directly above them, but rather bars that were slightly off to the side.
This restores the original alignment.
| <img src="https://github.com/user-attachments/assets/103a281c-64cd-4804-92e4-8b2e585d7f59" /> | <img src="https://github.com/user-attachments/assets/e106a47e-e570-434c-bce1-6428622793f5" /> | 
[ONYX-1512]: https://artsyproduct.atlassian.net/browse/ONYX-1512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …

fix(price filter): alignment of histogram and sliders

---

src/Apps/Order/Components/ApplePayDetails.tsx
src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx

This PR removes the Apple Pay Mark icon
| | Desktop | mWeb |
|---|---|---|
| Before | ![image](https://github.com/user-attachments/assets/649af3d6-92bd-473a-93c5-b03c1120fbca) | ![image](https://github.com/user-attachments/assets/55a4797d-840c-4880-b744-f72b3567c214) |
| After | ![image](https://github.com/user-attachments/assets/05eb2af5-2e56-4d7e-9f35-2bdd205c64b6) | ![image](https://github.com/user-attachments/assets/7f2495b1-e555-4980-89b3-ceb2717a24da) |

fix: remove Apple Pay Mark Icon

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx

Just pushing a new url into the router seems to do the trick. There is a loading bar and redirect happens. It takes several seconds but looks ok to me.
Let me know if you think there is a better way to approach it.

feat(EMI-2383): redirect to Status screen after applePay successful submission

---

src/Apps/Checkout/ApplePay.tsx

The type of this PR is: **refactor**
This new `useFeatureFlag` snuck in right before I merged #15263 . This updates the import to use the native unleash `useFlag` function.

refactor: use unleash useFlag for apple pay flag

---

src/Apps/Partner/PartnerApp.tsx

Fixes a weird padding issue noticed on the works screen - the alignment didn't work because of the sticky filter in grid combined with the sticky tab bar, so this just makes it even.

fix: padding on partner works screen

---

src/Apps/Order/Components/BuyerGuarantee.tsx
src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
src/Apps/Order/Components/__tests__/BuyerGuarantee.jest.tsx

This PR solves [EMI-2410]
[EMI-2410]: https://artsyproduct.atlassian.net/browse/EMI-2410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2410): remove dot from checkout links

---

src/Apps/Order/Routes/Shipping/Components/FulfillmentDetailsForm.tsx

Attempting to fix: EMI-2376
After some digging and pointers from @erikdstock seems like the issue is that submit form is called before `formik.setValues` finished executing. And seems like `setValues doesn't return a promise, awaiting it doesn't ensure the values are updated.` - so trying to use `useEffect` with a dependency on `formikContext.values` instead when address is saved. 
Seems to fix this concrete error but not sure it does not break something else :( Did some local testing and seems fine though....

fix: submit form after formik values are saved

---

src/Apps/Order/__tests__/OrderApp.jest.enzyme.tsx
src/Apps/Order/orderRoutes.tsx
src/Apps/Order/redirects.tsx
src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
src/Apps/Order2/Routes/Details/Order2DetailsRoute.tsx
src/Apps/Order2/order2Routes.tsx
src/__generated__/order2Routes_CheckoutQuery.graphql.ts
src/__generated__/order2Routes_DetailsQuery.graphql.ts

_Draft: Rebase after #15480 is merged: changes start with https://github.com/artsy/force/pull/15481_
This PR solves [EMI-2364] and [EMI-2380]
This PR is one of the first uses of force's new server-side unleash feature flag checks. In short, for legacy checkout flow routes we redirect to `orders2/:id/checkout` and for the legacy status page we redirect to `orders2/:id/details`. Likewise from those routes we use the same criteria to direct you to the legacy pages.
The criteria for both is the same right now: A BUY order with the appropriate feature flag enabled.
Paired with @damassi and @oxaudo 
CC @artsy/emerald-devs 
[EMI-2364]: https://artsyproduct.atlassian.net/browse/EMI-2364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …

chore(EMI-2364): Redirects for new order checkout/details routes

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx

This PR solves [EMI-2447]
To allow Apple Pay or Google Pay to appear when they’re not set up, set [paymentMethods.applePay](https://docs.stripe.com/js/elements_object/create_express_checkout_element#express_checkout_element_create-options-paymentMethods-applePay) or [paymentMethods.googlePay](https://docs.stripe.com/js/elements_object/create_express_checkout_element#express_checkout_element_create-options-paymentMethods-applePay) to always. This still won’t force them to appear on unsupported platforms, or when the payment is in an unsupported currency.
[EMI-2447]: https://artsyproduct.atlassian.net/browse/EMI-2447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2447): always show express checkout

---

src/Apps/Order/Components/GooglePayDetails.tsx
src/Apps/Order/Components/PaymentMethodSummaryItem.tsx
src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx

This PR solves [EMI-2432]
This PR adds Google Pay as a payment method in the order history and order details page
| View | Desktop | mWeb |
|---|---|---|
| Order History | ![image](https://github.com/user-attachments/assets/bb4cf649-fc64-4458-b4e6-ae43f2ee491f) | ![image](https://github.com/user-attachments/assets/4f3c03bd-d865-407f-9cc9-0b852ac6af4d) |
| Order Details | ![image](https://github.com/user-attachments/assets/21529705-51f5-4e51-808e-6caca513f2e8) | ![image](https://github.com/user-attachments/assets/83355bb9-8dc2-4478-b4ba-7ae1137a00ce) |
[EMI-2432]: https://artsyproduct.atlassian.net/browse/EMI-2432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2432): Add Google Pay icon to order history

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
src/Apps/Artist/Components/ArtistHeader/ArtistHeaderImage.tsx
src/__generated__/ArtistApp_Test_Query.graphql.ts
src/__generated__/ArtistHeader_artist.graphql.ts
src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts

Belated follow-up on the recent [accessibility mob](https://artsy.slack.com/archives/C2TQ4PT8R/p1745246843599959)
This simply adds an `alt` attribute for the artist page cover image.
Amazingly TIL about the `artwork.imageTitle` attribute that's been around for years and was [concocted for this purpose](https://github.com/artsy/metaphysics/pull/523/files). I wonder if we use that everywhere we should.
There were some other findings in that session but they will have to be dealt with in Palette.

fix(a11y): add alt text to artist cover image

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
src/Apps/Order/Components/ExpressCheckout/Mutations/useUpdateOrderShippingAddressMutation.ts
src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
src/__generated__/useUpdateOrderShippingAddressMutation.graphql.ts

This PR solves [EMI-2399]
Followup from https://github.com/artsy/metaphysics/pull/6682 and https://github.com/artsy/exchange/pull/2535
The main idea here is to use a more specific endpoint to update the Order shipping address values instead of the general `PUT /api/me/orders/:id`, since updating shipping address values will require an Order totals re-calculation and we want to avoid that in the more general purpose update.
[EMI-2399]: https://artsyproduct.atlassian.net/browse/EMI-2399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2399): decouple address and payment method updates from express checkout orders

---

src/Apps/Artist/Routes/Overview/Components/ArtistEditorialNewsGrid.tsx

When `lazyLoad` is enabled the wrapper component needs a width/height. IMO width/height should be required on the component type but this is merely my opinion. Doing that with a canary would at least expose remaining bugs.
https://artsyproduct.atlassian.net/browse/DIA-1316

fix(artist): fixes image collapse

---

src/Apps/Order2/Routes/Checkout/Components/Order2CollapsibleOrderSummary.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2PricingBreakdown.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
src/Apps/Order2/Routes/Checkout/Components/__tests__/Order2PricingBreakdown.jest.tsx
src/__generated__/Order2CollapsibleOrderSummary_order.graphql.ts
src/__generated__/Order2PricingBreakdownTestQuery.graphql.ts
src/__generated__/Order2PricingBreakdown_order.graphql.ts
src/__generated__/Order2ReviewStep_order.graphql.ts
src/__generated__/order2Routes_CheckoutQuery.graphql.ts

This PR improves the collapsible order summary and order review components in the new checkout flow with pricing breakdown data from metaphysics.
Completes [EMI-2466]
✅ Depends on artsy/metaphysics#6714 for new order pricing breakdown schema
Graphql Enum typenames are used to render the render the ordered lines with appropriate formatting. No user-facing changes except that we will get more specific names for shipping/pickup values than just "Shipping" once a user has selected an option.
[EMI-2466]: https://artsyproduct.atlassian.net/browse/EMI-2466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: load order summary lines from MP

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx

This PR solves [EMI-2451]
We only want to set shipping address when it’s really a shipping order
[EMI-2451]: https://artsyproduct.atlassian.net/browse/EMI-2451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2451): do not send address for pickup mode

---

src/Apps/Order2/Routes/Checkout/Components/Order2DeliveryForm.tsx
src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
src/__generated__/order2Routes_CheckoutQuery.graphql.ts

This PR solves [EMI-2452]
- Implement the ship/pickup switcher if the order has pickup available (checking `fulfillmentOptions` for a pickup option).
- Need to check if it's simple to persist input values when switching tabs - not included in this PR
[EMI-2452]: https://artsyproduct.atlassian.net/browse/EMI-2452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2452): conditionally render pickup if available

---

src/Apps/Order/Components/ExpressCheckout/ExpressCheckoutUI.tsx
src/Apps/Order/Components/ExpressCheckout/__tests__/ExpressCheckoutUI.jest.tsx
src/Apps/Order/Components/ExpressCheckout/index.tsx
src/Apps/Order/Components/ProcessingPaymentSpinner.tsx
src/Apps/Order/Components/SubmittingOrderSpinner.tsx
src/Apps/Order/Routes/Shipping/index.tsx

This PR solves [EMI-2450]
This PR adds a spinner for order submission through the express checkout
| Apple Pay | Google Pay |
|---|---|
| <video src="https://github.com/user-attachments/assets/517d0e07-799e-440b-a022-71b713408e67" /> | <video src="https://github.com/user-attachments/assets/c7b4d32f-5b92-4a66-a4be-96c22ee83d2f" /> |
[EMI-2450]: https://artsyproduct.atlassian.net/browse/EMI-2450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2450): Add loading screen for express checkout submissions

---

src/Apps/Order/__tests__/OrderApp.jest.enzyme.tsx
src/Apps/Order/redirects.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsHeader.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsMessage.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsPage.tsx
src/Apps/Order2/Routes/Details/Components/__tests__/Order2DetailsPage.jest.tsx
src/__generated__/Order2DetailsHeader_order.graphql.ts
src/__generated__/Order2DetailsMessage_order.graphql.ts
src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
src/__generated__/Order2DetailsPage_order.graphql.ts
src/__generated__/order2Routes_DetailsQuery.graphql.ts

This is mainly to bring the strings that we've created in MP for this summary.
I'm also relaxing the requirement for redirect to happen only for BuyNow orders as we would need to test the messaging for offers as well (the plan is to release those together).

feat: continue implementation for Summary component on order details page

---

src/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
src/Apps/InstitutionPartnerships/Components/InstitutionPartnershipsHero.tsx

Noticed that content was sitting behind an overlay gradient in a few places. These headers were never really designed to have significant content in them. In the case of https://www.artsy.net/institution-partnerships the "Apply to Join" link wasn't even clickable. I think that also might be linking to a dead page (raised in Slack).

fix: fixes content from sitting behind gradient overlay

---

src/Apps/Order2/Routes/Details/Components/Order2DetailsMessage2.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsPage.tsx
src/__generated__/Order2DetailsMessage2_order.graphql.ts
src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
src/__generated__/Order2DetailsPage_order.graphql.ts
src/__generated__/order2Routes_DetailsQuery.graphql.ts

This is an alternative approach to DetailsMessage where content is rendered completely on the client based on specific `message_type` that is coming from the server.
Once we settle on the approach - we'll need to DRY this code a bit and add some specs. But want to confirm what is the way to go forward first.

chore: alternative approach to rendering messages on order details page

---

src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2DeliveryForm.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2FulfillmentDetailsCompletedView.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2FulfillmentDetailsStep.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2FulfillmentDetailsStep/Order2PickupForm.tsx
src/Apps/Order2/Routes/Checkout/Mutations/useSetOrderFulfillmentOptionMutation.ts
src/Apps/Order2/Routes/Checkout/Mutations/useSetOrderPickupDetailsMutation.ts
src/Apps/Order2/Routes/Checkout/Order2CheckoutRoute.tsx
src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
src/__generated__/Order2CheckoutRoute_viewer.graphql.ts
src/__generated__/Order2FulfillmentDetailsStep_order.graphql.ts
src/__generated__/Order2PickupForm_order.graphql.ts
src/__generated__/order2Routes_CheckoutQuery.graphql.ts
src/__generated__/useSetOrderFulfillmentOptionMutation.graphql.ts
src/__generated__/useSetOrderPickupDetailsMutation.graphql.ts

This PR solves [EMI-2469]
This PR allows a user to set a pickup fulfillment type and save the details (their phone number) to the order.
**Implementation details**
- We save the phone number country code value (like `us` or `de` in lower case) to the `order.buyer_phone_number_country_code`. Historically we haven't saved these very often. It's possible that express checkout does it (or does it but differently), and it's possible we want to save something else like the `+1` number. However, this is what we save to users in gravity.
- I implemented a bare minimum checkout state management system - when fulfillment details get set, transition to the completed view of the step. When clicking edit on that view, transition back to the active version of the step. …

feat(EMI-2469): Set pickup fulfillment type and details on new checkout flow

---

src/Apps/Order2/Routes/Details/Components/Order2DetailsMessage.tsx
src/Apps/Order2/Routes/Details/Components/WireTransferInfo.tsx
src/Apps/Order2/Routes/Details/Components/__tests__/Order2DetailsMessage.jest.tsx
src/__generated__/Order2DetailsMessage_Test_Query.graphql.ts
src/__generated__/Order2DetailsMessage_order.graphql.ts
src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
src/__generated__/order2Routes_DetailsQuery.graphql.ts

Finally! It's the last part of [EMI-2436](https://artsyproduct.atlassian.net/browse/EMI-2436)
Here we are adding wire details selection based on order currency. I refactored this Wire details info into separate component and think it's a bit easier to see the variations in this format. But that brings a question - is that intentional that both EUR and GBP bank address is in London [cami-w](https://github.com/cami-w)?
Also removing a link for 'contact gallery' for now. As we've discussed it'll be a follow up to link this properly based on presense of existing conversation.
Here is the look for USD:
[EMI-2436]: https://artsyproduct.atlassian.net/browse/EMI-2436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Final wire details for the message section.

---

src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/Order2ExpressCheckout.tsx
src/Apps/Order2/Routes/Checkout/Components/ExpressCheckout/Order2ExpressCheckoutUI.tsx
src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2FulfillmentDetailsCompletedView.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentCompletedView.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentStep.tsx

The type of this PR is: **Style**
#minor
This PR updates the checkout app to follow naming conventions for React FCs and their prop types as well as calling a single fragment `FRAGMENT` rather than `{OBJECT_NAME}_FRAGMENT`.
See https://github.com/artsy/force/pull/15632#discussion_r2112883352

style: checkout app naming conventions

---

src/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx

This PR solves [ONYX-1748]
When discussing the process of evaluating NWFY recs, we noted that masonry layouts can make it difficult to understand the ordering of artworks.
Because ordering of artworks will be an important part of the next round of recs work (i.e. a/b test of re-ranking based on price affinity) I make a small change here to allow NWFY works to be presented in strict gridded order instead of masonry.
With this change, toggling between masonry and strict grids is accomplished with a simple query param:
- <code>/new-for-you?version=A</code>
-vs-
- <code>/new-for-you?version=A<b>&layout=grid</b></code>
Hopefully that smooths the qualitative QA step.
(We could also consider making the strict grid the default, so that users coming from the email …

feat: allow NWFY works to be strictly gridded for easier evaluation

---

src/Apps/Article/Components/ArticleHTML.tsx

The type of this PR is: **FIX/CHORE**
This PR is a follow up of [DIA-1310] (see first pr here: https://github.com/artsy/force/pull/15647)
After adding the additional Follow button intended only for single entity h2 headers in Editorial (artist or partner name only), I noticed a visual bug where the cta was also appearing in cases where there were headers that include multiple artist or partner links on a single line (group shows), which should not receive a CTA.
Now we are only displaying this cta if:
- the h2 heading contains only 1 artist name or partner link, and the heading itself is just the artist/partner name
- if there is an h3 subheading, it contains no other links (descriptive text is ok)
- if there are any multi-entity headers, or non-artist/partner entities, we suppress the …

fix: Accounting for additional elements and entity links in Article headers for Follow CTA

---

src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx

This PR solves [PBRW-836]
This PR makes two changes:
- Update the link of my collection to match the new one on Eigen
- Hide the link on Android until `react-native-webview` successfully intercepts js.
_This is the new link working on Eigen_
https://github.com/user-attachments/assets/488c202a-33fd-41c4-be03-ffd08b687009
[PBRW-836]: https://artsyproduct.atlassian.net/browse/PBRW-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update my profile link to match new link on Eigen

---

src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentStep.tsx
src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx

This PR solves [EMI-2556]
This has a few changes on how we handle the payment section, more specifically:
- Added a condition to check which payment method is chosen and proceed accordingly;
- Added a `IsPaymentMethodSelected` logic to handle the scenario where the page is loaded and no payment method is selected;
- Added a subtitleErrorMessage logic to handle the scenario above;
- Let Stripe handle it's errors on the element itself;
- Added an error "box" at the bottom of the section to handle all other errors;
- Clear error messages when changing the payment method;
[EMI-2556]: https://artsyproduct.atlassian.net/browse/EMI-2556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2556): stripe error handling and display

---

src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
src/Components/ArtworkFilter/ArtworkFilterContext.tsx

Simple fix: we were pushing changes to the URL bar on mutation of the filter params. This just happened to run on initial mount as well and it doesn't need to.

fix(filters): avoids url changes on initial mount for default params

---

src/Apps/Order2/Routes/Details/Components/Order2DetailsFulfillmentInfo.tsx
src/Apps/Order2/Routes/Details/Components/Order2DetailsMessage.tsx
src/Apps/Order2/Routes/Details/Components/__tests__/Order2DetailsMessage.jest.tsx
src/__generated__/Order2DetailsMessage_Test_Query.graphql.ts
src/__generated__/Order2DetailsMessage_order.graphql.ts
src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
src/__generated__/order2Routes_DetailsQuery.graphql.ts

The linking will only work for Arta shipped orders for now as those will have link stored. The regular orders will not for now. We will have a separate follow up ticket if we want to try and generate links for partner shipped orders as well.

feat: add display for tracking info in the order details message for orders in shipped state

---

src/Apps/Partner/Components/PartnerMeta/index.tsx

> To help consolidate SEO value to our main artist pages and avoid dilution of page rank across duplicate or near-duplicate pages, we should add a canonical tag to all partner artist pages that points to the main /artist/ page.

fix(partner): points to the artist as the true canonical

---

src/Apps/Show/Components/ShowMeta.tsx

We disable `displayable` on some shows like older fair booths from non-partners (I think?), but we don’t 404 them instead displaying the copy: `This fair booth is currently unavailable.`. But we also disable links to them by nulling out the `href`. As a result they erroneously specify `https://www.artsy.net/` as the canonical. This just fallsback to the current path instead.

fix(show): includes a fallback href for canonical

---

src/Apps/Artist/artistRoutes.tsx
src/Apps/ArtistSeries/artistSeriesRoutes.tsx
src/Apps/Artists/artistsRoutes.tsx
src/Apps/Categories/categoriesRoutes.tsx
src/Apps/Collect/collectRoutes.tsx
src/Apps/Gene/geneRoutes.tsx
src/Apps/serverCacheTTLs.tsx

This PR solves [PBRW-875]
This updates our serverCacheTTL settings by removing specific entries, in favor of default 1hr cache times. We haven't seen much impact here given our traffic patterns; however, bug reports do come in from confused partners. 
[PBRW-875]: https://artsyproduct.atlassian.net/browse/PBRW-875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(cache): Drop page cache times down to default 1hr

---

src/Apps/Order2/Routes/Details/Components/Order2DetailsOrderSummary.tsx
src/Apps/Order2/Routes/Details/Components/__tests__/Order2DetailsOrderSummary.jest.tsx
src/__generated__/Order2DetailsOrderSummary_Test_Query.graphql.ts
src/__generated__/Order2DetailsOrderSummary_order.graphql.ts
src/__generated__/Order2DetailsPage_Test_Query.graphql.ts
src/__generated__/order2Routes_DetailsQuery.graphql.ts

This PR solves [EMI-2563]
Add Partner name to Details page Artwork summary
[EMI-2563]: https://artsyproduct.atlassian.net/browse/EMI-2563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2563): show partner name in details

---

src/Components/ArtistRail.tsx
src/Components/CategoryRail.tsx
src/__generated__/ArtistRail_artist.graphql.ts
src/__generated__/CategoryRail_category.graphql.ts
src/__generated__/SettingsSavesArtistsQuery.graphql.ts
src/__generated__/SettingsSavesArtists_test_Query.graphql.ts
src/__generated__/SettingsSavesCategoriesQuery.graphql.ts
src/__generated__/SettingsSavesCategories_test_Query.graphql.ts

This PR solves [ONYX-1751]
Our follow rails were not specifying an order for the artworks they were displaying, thus often displaying many sold or unavailable works.
This PR ensures that…
- **Followed Artists** and **Followed Categories** rails use the ES-backed filter artworks endpoint
- and they explicitly specify `-decayed_merch` as their sort, so that the rail downranks sold works (and matches the corresponding artwork grid the user will see if they click through)
Now users are much more likely to see for-sale works in these rails:
| Rail | Before | After |
|--------|--------|--------|
| Artists |<img width="300" alt="artworks" src="https://github.com/user-attachments/assets/80ca0504-42af-48c2-9ed5-a12ee8635494" /> |<img width="300" alt="filter" …

fix: order of artworks in follow rails

---

src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentCompletedView.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentStep.tsx

This PR solves [EMI-2535]
https://github.com/user-attachments/assets/05a861e8-b10c-42f8-a457-0f236b78ca51
[EMI-2535]: https://artsyproduct.atlassian.net/browse/EMI-2535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2535): buyer can see unsaved card when editing payment

---

src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx
src/Components/Onboarding/Views/OnboardingCuratedArtworks.tsx

This PR updates copy used in the curator's picks rail and onboarding screen. It comes from user feedback.

feat(DIA-1364): update curator's picks subtitle

---

src/Apps/About2/About2App.tsx
src/Apps/About2/Components/About2Header.tsx
src/Apps/About2/Components/About2Hero.tsx
src/Apps/About2/Components/About2Nav.tsx
src/Apps/About2/Components/About2Stats.tsx
src/Apps/About2/Components/About2StructuredData.tsx
src/Apps/About2/about2Routes.tsx
src/routes.tsx

Going to split off 2 more tickets here:
1. Will handle the scrollspy nav as it's own thing
2. We'll replace image placeholders once everything is final. Prepping assets is a bit arduous so it doesn't make sense to do yet. (cc @JanaeHijaz)

feat(dia-1367): build the scaffolding for the new about page

---

src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx

This PR solves [EMI-2592]
This is working nicely, but I am not sure if re-using the order modal is the direction we wanna go, so I would appreciate any input from more experienced React people.
Once we have a decision, I can write the specs.
https://github.com/user-attachments/assets/e943260c-5a35-4836-984a-3a7f2ad37e37
[EMI-2592]: https://artsyproduct.atlassian.net/browse/EMI-2592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2592): handle order submission errors

---

src/Apps/Order2/Routes/Details/Components/Order2DetailsHeader.tsx

We can probably figure out how to modify it's usage in Integrity - but seems like an ok edition for now.

chore: add data-test attribute to order# on new details page as it is used for integrity specs

---

src/Apps/Artwork/Components/ArtworkTopContextBar/ArtworkTopContextBarShow.tsx
src/Apps/Artwork/Components/ArtworkTopContextBar/__tests__/ArtworkTopContextBarShow.jest.tsx

[Reported here](https://artsy.slack.com/archives/C07PRTJSD6G/p1750848836071779) on Slack
Small fix to account for the [all possible values](https://github.com/artsy/gravity/blob/cb9e09fb769b4af045b3b1421a64786ffce131a2/app/models/domain/partner_show.rb#L449-L458) of `show.status`
Here is a show which currently has a status of `upcoming`:
| <img width="1474" alt="Screenshot 2025-06-25 at 3 43 23 PM" src="https://github.com/user-attachments/assets/ddd78fb1-8698-4659-a2f5-4548438c2252" /> | <img width="1474" alt="Screenshot 2025-06-25 at 3 44 09 PM" src="https://github.com/user-attachments/assets/60e6e2d3-1391-4353-8fb2-e4c8405e2e4c" /> |

fix: dynamic breadcrumb for upcoming shows

---

src/Apps/About2/Components/AboutPress.tsx
src/Apps/About2/Components/AboutPressShelf.tsx
src/Apps/About2/Components/__tests__/AboutPressShelf.jest.tsx
src/__generated__/AboutPressShelfQuery.graphql.ts

Adds the press section, which fetches the `in-the-media` Markdown page, and parses it into cards.

feat(about2): implements press section

---

src/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
src/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx
src/__generated__/ArtistApp_Test_Query.graphql.ts
src/__generated__/ArtistHeader_Test_Query.graphql.ts
src/__generated__/ArtistHeader_artist.graphql.ts
src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts

This PR updates the artist page to display whatever bio Metaphysics serves it - regardless of whether it was written by Artsy, the partner, or (hypothetically) an LLM.
See artsy/metaphysics#6860 for more information.
|-------|------|
| <img width="1840" alt="BEFORE" src="https://github.com/user-attachments/assets/aacbae9f-c037-44d2-be7e-699cc6a47fa6" /> | <img width="1840" alt="AFTER" src="https://github.com/user-attachments/assets/92b68a55-5546-4be3-bb7e-316cdc96215a" /> |

feat(DIA-1308): allow partner bios on artist page

---

src/Apps/Feature/Components/FeatureFeaturedLink.tsx

This PR solves [DIA-1336]
The existing image element was wrapped in a link, and if no link was present, the defaulted title would've been linked. but in the case where the image is present, the title and other elements were't getting wrapped. 
Alternately, I could have wrapped each of these elements individually with a router link instead of using the `Figure` to wrap them all like I did here. But I noticed we just wrap other elements like this elsewhere: 
https://github.com/artsy/force/blob/0047c96671d1edb6e24100a063aeb533fba2ba39/src/Apps/Articles/Components/ArticlesIndexArticle.tsx#L28-L45
ps: I was 🤏 this close to having my first ticket number be `1337`.
[DIA-1336]: https://artsyproduct.atlassian.net/browse/DIA-1336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …

fix(feature): makes featured title/sub/text clickable

---

src/Apps/Order2/Routes/Checkout/Components/Order2CollapsibleOrderSummary.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
src/__generated__/Order2CheckoutRouteTestQuery.graphql.ts
src/__generated__/Order2ReviewStep_order.graphql.ts
src/__generated__/order2Routes_CheckoutQuery.graphql.ts
src/__generated__/useSetOrderFulfillmentOptionMutation.graphql.ts
src/__generated__/useSetOrderPickupDetailsMutation.graphql.ts

Resolves [EMI-2595]
This PR adds missing artwork metadata to the review step of the checkout flow that was previously placeholder text. I tried to follow the logic used in the details page [here](https://github.com/artsy/force/blob/13f2e95861ec6accc4a8d9c85c7bbfc6157c3592/src/Apps/Order2/Routes/Details/Components/Order2DetailsOrderSummary.tsx#L30-L41).
[EMI-2595]: https://artsyproduct.atlassian.net/browse/EMI-2595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2595): add proper artwork metadata to review step

---

src/Apps/Order2/Layouts/LayoutCheckout.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2CheckoutLoadingSkeleton.tsx
src/Apps/Order2/Routes/Checkout/Order2CheckoutApp.tsx

This is updating Checkout layout with the changes that we've made for Details page yesterday.
This looks ok as far as I can tell but there is still one small visual issue here. 
On a smaller screen with 2 column layout right column is not given the proper `40px` margin on the right. The content is resized properly but the margin is not appearing.  I suspect it's something with the fact that the position is `fixed for it`. Suspect we might need to have some placeholder dummy element to give it a proper sizing but unfortunately do not have time to play with it right now.
@rquartararo and @erikdstock - tagging you here and you can decide if you want to use this just for reference or merge it and do the fixes based on this code.

chore: adjustment to the layout for checkout page

---

src/Apps/Artwork/Components/ArtworkLightbox.tsx

This PR enables generated caption only for default images.

fix: use caption only for default artwork image

---

src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx

This PR solves [EMI-2537]
> [!warning]
> This PR requires artsy/metaphysics#6902 to be merged first
This PR allows saving a credit card when submitting an order
| One Time Use | Save Credit Card |
|---|---|
| <video src="https://github.com/user-attachments/assets/8a601d12-81fa-4853-b577-53a631e163b7" /> | <video src="https://github.com/user-attachments/assets/75a49d2e-f9dd-4849-991c-79a8fce2e8b4" /> |
[EMI-2537]: https://artsyproduct.atlassian.net/browse/EMI-2537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2537): Allow saving credit card when submitting an order

---

src/Apps/Artwork/Components/ArtistInfo.tsx
src/Components/ArtistBio.tsx
src/Components/__tests__/ArtistBio.jest.enzyme.tsx
src/__generated__/ArtistBioTestQuery.graphql.ts
src/__generated__/ArtistBio_bio.graphql.ts
src/__generated__/ArtistInfoQuery.graphql.ts
src/__generated__/ArtistInfo_Test_Query.graphql.ts
src/__generated__/ArtistInfo_artist.graphql.ts

This PR fixes a bug where the credit for an artist bio was appearing as ugly HTML. This is the result of me changing the `biographyBlurb.credit` field to follow the same formatting as the `biographyBlurb.text` field so that we could embed a link to the partner page in it. 
|--------|------|
| <img width="1113" height="489" alt="Screenshot 2025-07-10 at 2 43 51 PM" src="https://github.com/user-attachments/assets/a34e5c6d-2689-4991-8bfa-3d740b5bf52f" /> | <img width="1109" height="507" alt="Screenshot 2025-07-10 at 2 44 04 PM" src="https://github.com/user-attachments/assets/edb84fd1-ba83-46bb-aaae-e0b0bd166103" /> |
cc: @artsy/diamond-devs

fix(DIA-1407): artist bio credit on artwork pages

---

src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx
src/Apps/Order2/Routes/Checkout/Components/Order2ReviewStep.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentCompletedView.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentStep.tsx
src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
src/__generated__/Order2PaymentFormSavedCreditCardsQuery.graphql.ts

This PR solves [EMI-2539]
https://github.com/user-attachments/assets/6b788b89-967c-41a0-bdfe-c364a58e7245
- When a buyer has saved credit cards, the payment step includes saved payments at the top.
- The saved payments should be expanded by default.
- The saved credit cards are sorted by creation time in descending order.
- The first saved payment method should be selected.
- The buyer can submit the order with the selected credit card as the payment method.
https://artsyproduct.atlassian.net/browse/EMI-2539
[EMI-2539]: https://artsyproduct.atlassian.net/browse/EMI-2539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2539): Buyer can pay with a saved credit card

---

src/Apps/Order/Components/ExpressCheckout/Util/mutationHandling.ts
src/Apps/Order2/Routes/Checkout/Components/CheckoutErrorBanner.tsx
src/Apps/Order2/Routes/Checkout/Components/DeliveryOptionsStep/utils.ts
src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2DeliveryForm.tsx
src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/__tests__/handleError.jest.ts
src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/handleError.tsx
src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/utils.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx
src/DevTools/mockStripe.ts

This PR solves [EMI-2503]
This PR adds error handling to our fulfillment details step. It also gives us a clickable support email link in our error banners.
Best reviewed with [whitespace off](https://github.com/artsy/force/pull/15873/files?diff=split&w=1) because i adjusted some test indentation.
[EMI-2503]: https://artsyproduct.atlassian.net/browse/EMI-2503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2503): Fulfillment details step error handling

---

src/Apps/Home/Components/HomeRecommendedArtistsRail.tsx

Going to remove `onyx_artist_recommendations_rail_on_web` (introduced in https://github.com/artsy/force/pull/15872). There is no really a need for it + for some reason unleash rollout out this feature only for ~70% of users (even thought 100% is specified) - can't figure out why

chore: cleanup onyx_artist_recommendations_rail_on_web feature flag

---

src/Apps/Order2/Routes/Checkout/Components/PaymentStep/Order2PaymentForm.tsx
src/Apps/Order2/Routes/Checkout/Components/PaymentStep/__tests__/Order2PaymentForm.jest.tsx
src/Apps/Order2/Routes/Checkout/Hooks/useCheckoutTracking.ts

This PR solves [EMI-2669]
This PR adds tracking for clicking and viewing saved payment methods. I'd like to double check that I'm doing it right since it seems like every `click` should be followed by a `viewed`.
[EMI-2669]: https://artsyproduct.atlassian.net/browse/EMI-2669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(EMI-2669): track saved payment method interactions

---

src/Utils/Hooks/useLoadScript.ts

We're seeing "TypeError: Load failed" errors in Sentry but lack context about which external scripts are failing to load.
Added `script.onerror` handler to `useLoadScript` hook that captures:
- Which script failed (scriptId)
- What URL failed to load (src)
- Tagged as "script_load_failure" for easy Sentry filtering
Dynamically loads external JavaScript scripts at runtime, including:
1. Google ReCAPTCHA: https://www.google.com/recaptcha/api.js (line 22-24)
2. Salesforce scripts: Various Salesforce integration scripts
3. Google Maps: Location/shipping estimation scripts
4. ArtsyShippingEstimate: Shipping calculation scripts
- No functional changes - scripts that fail will still fail
- Better observability into external script loading issues (ReCAPTCHA, Salesforce, etc.)
- Tagged Sentry …

chore: add error tracking to useLoadScript for debugging "Load failed" errors

---

src/System/Utils/setupSentryClient.ts

We're seeing frequent "TypeError: Load failed" errors in Sentry but lack visibility into which third-party services might be causing them. Our current Sentry configuration blocks errors related to external services (Braze, Google Tag Manager, DoubleClick, etc.) via the `denyUrls` filter.
Temporarily disable the `denyUrls` configuration in Sentry client setup to allow third-party service errors (occurring on our domain) to reach Sentry.
I will monitor Sentry for 24 hours to collect data and then revert this change.
- Script loading failures when artsy.net tries to load external services
- SDK initialization errors from third-party services on our pages
- Network errors from external service calls
- Which specific services correlate with "Load failed" error patterns
- **No functional …

chore: temporarily disable Sentry denyUrls to debug "Load failed" errors

---

src/Apps/Artists/Components/ArtistsCarouselCell.tsx

This PR fixes an annoying issue where the Featured Artist rail links to production, even when you are running Force on localhost or staging.
| localhost | staging |
|-|-|
| <img width="1560" height="1039" alt="localhost" src="https://github.com/user-attachments/assets/11647ec6-e7e0-42e2-934e-eae1d19d01ec" /> | <img width="1560" height="1039" alt="staging" src="https://github.com/user-attachments/assets/ec405e3a-3c65-41d2-a066-af763218b003" /> |
This is especially annoying when building and testing features locally because developers will click into an artist page without knowing that they've been taken to production, where they will not be able to see any changes that they made locally.
The solution was to use the [getInternalHref](https://github.com/artsy/force/blob/12fbf3088b69d332d89f2d …

fix: featured artists rail linking to production instead of current env

---

src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx

This PR solves [EMI-2727](https://artsyproduct.atlassian.net/browse/EMI-2727)
- Add "Complete your profile and make a great impression" before existing text on web collector settings page to match app language.
- Replace custom implementation with the palette Message component.
| <img width="1934" height="216" alt="Screenshot 2025-08-13 at 10 48 28 (1)" src="https://github.com/user-attachments/assets/b048fde2-bc8b-4cb0-b00e-97072547fc67" /> | <img width="1518" height="270" alt="Screenshot 2025-08-13 at 11 01 56" src="https://github.com/user-attachments/assets/787c5d0d-79dd-437d-a378-7aed816fa0cb" /> |
[EMI-2727]: https://artsyproduct.atlassian.net/browse/EMI-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …

chore: Use Message component with title for info box in Settings → Edit Profile

---

src/Apps/Fair/Components/FairHeader/FairHeader.tsx
src/Apps/Fair/Components/FairOverview/FairAbout.tsx
src/Apps/Fair/Components/__tests__/FairHeader.jest.tsx
src/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx
src/__generated__/FairAbout_fair.graphql.ts
src/__generated__/FairApp_Test_Query.graphql.ts
src/__generated__/FairHeaderTestQuery.graphql.ts
src/__generated__/FairHeader_fair.graphql.ts
src/__generated__/FairOverviewTestQuery.graphql.ts
src/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
src/__generated__/fairRoutes_FairQuery.graphql.ts

Part of a set of requests from Marketing to tweak the design of the fair experience to support the use of these surfaces for a persistent "online shop", sourcing works directly from various gallery partners.
- Hide "[open] - [close]" dates in header, replace with subheader copy.
- Hide "Closes in" timer.
- Left-align "about" content.
Long-term, we intend to plan out the introduction of a separate "Shop" concept, which can borrow from some fair behavior (like sourcing directly from partners via CMS) but shed some of the time-specific requirements fairs currently have.
Jira: [ONYX-1872](https://artsyproduct.atlassian.net/browse/ONYX-1872) 🔒 
|Platform | Before | After |
|--------|--------|--------|
|Desktop Web| <img width="1400" alt="Screenshot 2025-08-14 …

feat: alter fair experience for The Artsy Edition Shop

---

src/Apps/Articles/AuthorsApp.tsx
src/Apps/Articles/Components/ArticlesAuthors.tsx
src/Apps/Articles/articlesRoutes.tsx
src/Apps/Artists/Routes/ArtistsByLetter.tsx
src/__generated__/ArticlesAuthorsQuery.graphql.ts

Adds a simple authors index page to assist in crawling.

feat(dia-1453): adds an authors index page

---

src/Apps/Order2/Routes/Checkout/Components/FulfillmentDetailsStep/Order2PickupForm.tsx
src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
src/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx
src/Components/Address/AddressFormFields.tsx
src/Components/Address/utils/utils.ts

follow-up on: #16050 
The Settings' Phone Input shouldn't be required, so I created richRequiredPhoneValidators extensions of richPhoneValidators.

fix: some phone numbers inputs  are not required

---

src/Apps/Artist/Components/ArtistMeta/__tests__/ArtistMeta.jest.tsx
src/Apps/Artist/Components/ArtistMeta/__tests__/useCanonicalHref.jest.tsx
src/Apps/Artist/Components/ArtistMeta/useCanonicalHref.ts

This PR adds page (and only page) params to the canonical link of the paginated artist page, with the caveat that it will only work with direct page access to paginated pages.
This means that if a user (or crawler) directly accesses https://www.artsy.net/artists/andy-warhol?page=2, the canonical link will correctly include `page=2`. However, if a user navigates to the second page by clicking a pagination link, the canonical link not be updated to include `page=2`.
This happens because we synthetically update the URL in the browser's address bar and history when a user clicks a pagination link to make it look like the user is on a new page, but in reality they are on the same route as far as React Router is concerned.
Instead of solving that problem, I want to see if this simple solution …

chore: paginate artist page canonical link

---

src/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx

The type of this PR is: Refactor
This PR solves [EMI-2792](https://artsyproduct.atlassian.net/browse/EMI-2792)
Refactoring [Settings > Shipping (Add / Edit Addresses)](https://staging.artsy.net/settings/shipping) form so it uses the same address component we already use in for the checkout (both old and new), invoice, and auctions. This space in settings is the last place with a custom implementation.
| <img width="750" height="710" alt="Screenshot 2025-08-28 at 09 12 31" src="https://github.com/user-attachments/assets/7f80af54-b4b0-4b4d-8010-37eba5178d7a" /> | <img width="753" height="668" alt="Screenshot 2025-08-28 at 09 29 05" src="https://github.com/user-attachments/assets/5b5fe2d0-6380-4a25-984a-8f725b948a3a" /> | …

refactor: using the address component in settings

---

CLAUDE.md
src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.jest.tsx
src/__generated__/ArtworkImageBrowserTestQuery.graphql.ts

This PR solves [AMBER-1966]
The artwork page was always showing the first image instead of the one marked with `isDefault: true` (which corresponds to the primary image set in CMS).
The `useCursor` hook was initializing with `index: 0` instead of using the calculated `defaultIndex` from the `isDefault` field.
Example of an artwork with a primary image defined in CMS:
**Before:** How this artwork looks in artsy.net currently:
**After:** How the same artwork looks like after the changes on this PR:
[AMBER-1966]: https://artsyproduct.atlassian.net/browse/AMBER-1966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(AMBER-1966): Respect primary image setting on the artwork page

---

src/Apps/Order2/Routes/Checkout/CheckoutContext/Order2CheckoutContext.tsx

This PR solves [EMI-2802]
https://github.com/user-attachments/assets/b5915c71-1b99-42b5-83b5-a8013921e3d8
The checkout loading manager was waiting for Express Checkout to load even when it should be hidden (like on the review step), causing an infinite loading state. Updated the loading condition to consider Express Checkout "loaded" when we're in post-payment states where it shouldn't be shown anyway.
This resolves the hanging issue that occurred after clicking "Continue to Review" with SEPA or ACH payment methods.
[EMI-2802]: https://artsyproduct.atlassian.net/browse/EMI-2802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(EMI-2802): Fix SEPA/ACH checkout hanging on loading skeleton

---

src/Apps/Articles/AuthorApp.tsx

Adds a link back to the index. Fixes the double h1 — the authors name should be the h1.

fix(author): adds breadcrumb; fixes h1

---

src/Apps/Conversations/components/Message/ConversationMessages.tsx

Noticed that on first load of the conversations page, the conversation that opens doesn't scroll to the last message. Subsequent conversations scroll fine so it's seems to be a matter of DOM rendering and execution timing.
Adding a timeout solves the issue, not sure if there's a more elegant way of achieving the same result.
Before:
https://github.com/user-attachments/assets/7dd347b8-2bcf-4470-aadd-713c6681a10d
After:
https://github.com/user-attachments/assets/25b2a243-d12c-4d5b-810d-baf9ef49a262

fix: scroll messages on first load

---

src/Apps/Order2/Routes/Checkout/__tests__/Order2CheckoutRoute.jest.tsx

Reported on [Slack](https://artsy.slack.com/archives/C02JHHHKP5K/p1757432618619149). The Order2CheckoutRoute tests are flaky on CI due to timeout. This bumps up the timeout tentatively for now and we'll ticket and improve the tests separately.
cc @artsy/emerald-devs

test: bump up timeout tentatively until implementing proper improvements

---

src/Apps/Conversations/components/Details/ConversationArtwork.tsx
src/Apps/Conversations/components/Details/__tests__/ConversationDetails.jest.tsx

This PR solves [EMI-2785]
Artwork clickable instead of a button, following CMS changes
[EMI-2785]: https://artsyproduct.atlassian.net/browse/EMI-2785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2785): artwork clickable

---

src/Apps/Conversations/components/Message/ConversationMessage.tsx
src/Apps/Conversations/components/Message/ConversationMessageImage.tsx
src/Apps/Conversations/components/Message/ConversationMessages.tsx

After revisiting #16122, noticed that the scrolling to bottom is not working properly if there are attachments. Here I'm suggesting a working solution, waiting for the image to load to scroll.
Before:
https://github.com/user-attachments/assets/45052c05-f576-41fa-b9c9-f79e2a066a79
After:
https://github.com/user-attachments/assets/befc5e61-6651-4734-93a9-7c0103ed7bef

fix: scroll to bottom with attachments

---

.yarnrc.yml

Related:
- https://github.com/artsy/force/pull/16141
The [current npm supply chain attack](https://www.stepsecurity.io/blog/ctrl-tinycolor-and-40-npm-packages-compromised) relies on executing a postInstall script to exfiltrate data. Yarn has the [ability to disable this behavior](https://v3.yarnpkg.com/configuration/yarnrc) via `enableScripts: false`. 
In the past it was common to use this, but in 2025 the need to build, etc, npm package scripts is much less given latest tools. If we run into issues however we should assess.

chore(security): Disable postinstall scripts from 3rd party libs on yarn install

---

src/Apps/Order2/Routes/Checkout/Components/DeliveryOptionsStep/Order2DeliveryOptionsForm.tsx
src/Apps/Order2/Routes/Checkout/Components/DeliveryOptionsStep/__tests__/Order2DeliveryOptionsForm.jest.tsx
src/Apps/Order2/Routes/Checkout/Components/DeliveryOptionsStep/utils.ts
src/__generated__/Order2DeliveryOptionsFormTestQuery.graphql.ts

This PR solves [EMI-2830]
This PR displays the Artsy Shipping Options for the new checkout. Note: we can not continue the checkout with Artsy shipping yet, I will make a separate PR for this in Exchange. 
[EMI-2830]: https://artsyproduct.atlassian.net/browse/EMI-2830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(EMI-2830): display order2 artsy shipping options

---

src/Apps/About/AboutApp.tsx
src/Apps/About/Components/AboutStructuredData.tsx
src/Apps/Home/Components/HomeStructuredData.tsx
src/Apps/Home/HomeApp.tsx

This PR solves [DIAM-103]
Description
When we visit / and /about we no longer see structure data for the Artsy organization. Jeff at Botify believes we used to have it on the old About page and homepage. So we may be able to look in git history to find it.
Action Performed:
Visit both 
Search the HTML source for relevant schema
Expected Result:
should have schema
Actual Result:
didn’t
Additional Info
https://docs.google.com/document/d/1vnSF7UcvLYzGvseZcb10eY3OwIsauwaxsadrBkhA2iw/edit?tab=t.p020j1sr9pjy
__After:__
https://github.com/user-attachments/assets/817bfa90-fbea-4014-864a-f66e400022c4
You can find some examples of organizational schema in https://docs.google.com/document/d/1qU0hbCpQrTKk3s4ZdgCQg653E_pe_tsxoNRcIU21OKY/edit?tab=t.0 embedded within …

fix(DIAM-103): Missing schema on the About Us page

---

src/Components/ArtworkFilter/ImmersiveView.tsx
src/Components/ArtworkFilter/__tests__/ImmersiveView.jest.tsx

This PR solves some old QA cards [here](https://www.notion.so/artsy/web-Immersive-artwork-view-23ecab0764a080789532dffa22cc2f1a?p=242cab0764a080398a48d5bc8577b59c&pm=s) and [here](https://www.notion.so/artsy/web-Immersive-artwork-view-23ecab0764a080789532dffa22cc2f1a?p=23ecab0764a080689e36f08f04375d35&pm=s).
- Constrains image width to `85vw`
- Removes **Previous** button when you are on the very first artwork within a paginated collection (page 1, work 1)
[This grid](https://staging.artsy.net/artist/barbara-blondeau) demonstrates both:
https://github.com/user-attachments/assets/e45a3ddc-0fba-4f09-91c2-1ff079e95371

fix(immersive): minor QA items
