artsy/force

- README.md
I am not sure what this list should be today, happy to amend.
> @craigspaeth => Removed dzucconi. [ci skip]

- apps/order/stylesheets/index.styl
- components/credit_card/client/error_handling_form.coffee
- components/form/index.coffee
- components/form/serializer.coffee
- components/form/test/serializer.coffee
- models/order.coffee
- npm-shrinkwrap.json
- package.json
- test/models/order.coffee
> @craigspaeth - Filter HTML in forms before submitting

- apps/artwork/client/bootstrap.coffee
- apps/artwork/client/index.coffee
- apps/artwork/components/skrillex/index.coffee
Still trying to come up with new hackathon stuff :(
> @broskoski => Add back skrillex easter egg

- apps/artwork/client/bootstrap.coffee
- apps/artwork/client/index.coffee
- apps/artwork/components/doge/index.coffee
- apps/artwork/components/doge/index.jade
- apps/artwork/components/doge/index.styl
- apps/artwork/components/doge/query.coffee
- apps/artwork/stylesheets/index.styl
> @broskoski => Add back doge mode easter egg

- CONTRIBUTING.md
- README.md
> @orta => Updated README and added CONTRIBUTING

- apps/artwork/components/artists/index.styl
- apps/artwork/components/artists/query.coffee
- apps/artwork/components/artists/templates/articles.jade
This makes sure the articles in the artist module on the artwork page are linkable.
> @kanaabe: add link to articles

- components/commercial_filter/views/headline/index.jade
closes: https://github.com/artsy/force/issues/27
> @broskoski: minor copy change to /collect header

- components/related_links/types/gene_genes.coffee
> @xtina-starr - Adapts related links view to use new endpoint

- components/auction_artwork_brick/index.styl
- components/auction_artwork_brick/templates/bid_status.jade
closes: https://github.com/artsy/force-private/issues/5310
> @broskoski: minor changes to auction related works module

- apps/artist/templates/meta.jade
- apps/artist/view_helpers.coffee
> @broskoski: [SEO] update auctions result page title tag

- apps/home_2/client/setup_home_page_modules.coffee
- apps/home_2/queries/initial.coffee
- apps/home_2/queries/module.coffee
- components/artwork_metadata_stub/queries/contact.coffee
Re: https://github.com/artsy/metaphysics/pull/388
🎩
> @craigspaeth - Updated queries to get random related artist on home

- apps/gene/routes.coffee
- apps/gene/test/routes.coffee
I'll trade ya! Re: https://artsy.slack.com/archives/web/p1471979802000878
cc @cavvia
> @kanaabe - Fix gene page for genes with artworks or artist in the slug

- models/mixins/meta_overrides.coffee
[Monthly Request](https://trello.com/c/fszVJO9M/329-update-seo-metadescriptions-for-art-fairs-monthly-request) to update metadescriptions for Art Fairs
> [SEO] undate metadescriptions for Art Fairs

- apps/home_2/routes.coffee
Looks like this got left out in the move 😢
> @broskoski - Reimplement sitelinks search box markup in homepage split test

- apps/artwork/components/related_artworks/index.jade
Fixes scroll bug at the bottom of artwork page
> @broskoski: use proper class to fix scroll bug

- Dangerfile
Nothing too aggressive WRT the checks, in theory this should fail as I don't have an `@` in the title.
> @xtina-starr => Initial Danger set of warnings

- apps/artist/templates/meta.jade
- apps/artist/test/view_helpers.coffee
And sneaks some specs in for the auctionResultsPageTitle method.
> @broskoski: fixes logic to deindex select artist pages

- apps/article/routes.coffee
- apps/partner/client/articles.coffee
- apps/partner/client/router.coffee
- apps/partner/index.coffee
- apps/partner/test/client/articles.coffee
- assets/partner.styl
- models/article.coffee
- Adds a redirect for partner-written articles
- Adds embedded articles to `partner` subapp
Closes https://github.com/artsy/force/issues/86
> @1aurabrown => Partner redirect

- analytics/bidding.js
cc @devangt 
As per request, this submits the price to criteo in dollars instead of cents!
> @craigspaeth => make price in dollars for criteo track

- apps/artwork/client/index.coffee
- apps/artwork/components/related_artworks/index.jade
- apps/artwork/components/related_artworks/query.coffee
- apps/artwork/components/related_artworks/view.coffee
Re: https://github.com/artsy/metaphysics/pull/396
> @mzikherman - Adds collaborative filter lab test to related works section

- apps/artwork/client/footer.jade
- apps/artwork/client/index.coffee
- apps/artwork/components/artists/index.styl
- apps/artwork/components/artists/query.coffee
- apps/artwork/components/related_artists/artists.jade
- apps/artwork/components/related_artists/index.coffee
- apps/artwork/components/related_artists/index.jade
- apps/artwork/components/related_artists/index.styl
- apps/artwork/components/related_artists/test/artists_fixture.coffee
- apps/artwork/components/related_artists/test/client.coffee
- apps/artwork/components/related_artists/test/template.coffee
- apps/artwork/stylesheets/index.styl
https://github.com/artsy/force/issues/74
> @broskoski: add related artists rail

- apps/artwork/components/artists/templates/exhibition.jade
Fixes https://github.com/artsy/force/issues/121
> @xtina-starr  => Handle shows without names gracefully in artist exhibition history

- components/commercial_filter/filters/price/price_filter_view.coffee
- components/slider/index.coffee
Closes https://github.com/artsy/force/issues/76
> @broskoski => Allow for more nuanced sliding behavior for price filtering in /collect

- apps/artwork/components/artists/helpers.coffee
- apps/artwork/components/artists/templates/exhibition.jade
- apps/artwork/components/artists/templates/highlights.jade
Fixes minor QA item (sort exhibition sequence) mentioned in https://github.com/artsy/force/issues/61#issuecomment-245282292.
> @broskoski: sort exhibition sequence from newest to oldest

- apps/articles/client/team_channel.coffee
- apps/articles/stylesheets/team_channel.styl
- apps/articles/templates/team_channel.jade
- apps/articles/test/client/team_channel.coffee
- components/articles_grid/stylesheets/index.styl
Closes https://github.com/artsy/force/issues/116
Full width (looks the same):
Medium width:
Mobile width:
> @broskoski => Responsive content differentiation pages

- apps/artwork/components/related_artists/index.jade
- apps/artwork/components/related_artists/test/template.coffee
Fixes https://github.com/artsy/force/issues/145
> @kanaabe => Be defensive about artworks without artists

- components/artwork_brick_rail/index.styl
Closes #148 
(see surfboard image)
> @eessex - Set min-width for artwork item inside rail

- apps/show/helpers/view_helpers.coffee
- apps/show/routes.coffee
- apps/show/templates/meta.jade
- apps/show/test/helpers/view_helpers.coffee
Closes https://github.com/artsy/force/issues/124
Metaphysics dependency: https://github.com/artsy/metaphysics/pull/411
Spoke with Sara and decided to change definition of some tags. I will add more details inline. Thanks for helping with the integration.
> @kanaabe Add Sailthru meta tags on the show page

- apps/partnerships/stylesheets/marketo.styl
> @xtina-starr Revert "@craigspaeth change marketo embedded form styling for last row 3 fields"

- apps/categories2/stylesheets/index.styl
My bad, turns out it was important to not have that invalid stylus line b/c it will break the asset build process on CI.
> @craigspaeth (cc @anandaroop): Comment out empty selector

- apps/artwork/components/auction_artworks/helpers.coffee
- apps/artwork/components/auction_artworks/index.jade
- apps/artwork/components/auction_artworks/index.styl
- components/artwork_brick/index.styl
- components/artwork_brick/templates/auction_image.jade
- components/artwork_metadata_stub/templates/contact.jade
- components/auction_artwork_brick/index.jade
closes https://github.com/artsy/force/issues/72
> @broskoski: Artwork Brick Adjustment for Auctioned Works

- analytics/article_impressions.js
- analytics/articles.js
Closes #143 
Distinguish visible and non-visible links inside read-more.
Add support for related articles component for impressions and clicks.
> @kanaabe => Article Analytics hooks

- apps/artwork/components/commercial/index.jade
Closes https://github.com/artsy/force/issues/171
> @broskoski - Remove questions about non-buyable works

- apps/partnerships/index.coffee
- apps/partnerships/routes.coffee
Solves https://github.com/artsy/force/issues/181
> @nicholassewitz: Add random A/B redirect b/t Marketo page vs. usual marketing page

- apps/artist/queries/cv.coffee
Removes this unneeded part of the query that was happening to error out.
> @mzikherman - Remove related image from cv query (closes #178)

- apps/artwork/components/commercial/templates/inquire.jade
- apps/artwork/components/commercial/test/template.coffee
- apps/artwork/components/commercial/test/view.coffee
> @briansw - More typo corrections

- apps/article/templates/meta.jade
This adds an Open Graph tag for description using our newly added description field. 
Convo: https://artsy.slack.com/archives/publishing-support/p1474491889000099
> @eessex => Adds open graph description tag #minor

- components/multi_page/config.coffee
Adds explore page to collector FAQ
> @broskoski - Adds exploring on artsy to collector-faq

- assets/shows.styl
- components/contact/show_inquiry_modal.coffee
- components/contact/view.coffee
- components/inquiry_questionnaire/templates/basic_info.jade
- components/inquiry_questionnaire/views/test_account.coffee
- components/inquiry_questionnaire/views/test_inquiry.coffee
- components/modalize/stylesheets/index.styl
- components/modalize/view.coffee
Close #191 
Leaving the last two things for later (as they were pre-existing and unrelated to this test).
> @mzikherman - Inquiry test QA

- apps/rss/templates/instant_articles.jade
- apps/rss/templates/news.jade
- apps/rss/test/instant_articles.coffee
- apps/rss/test/news.coffee
Google News and IA should use the new description fields.
> @eessex => Adds description to RSS feeds

- apps/articles/stylesheets/team_channel.styl
- components/channel_nav/index.styl
- lib/middleware/redirect_mobile.coffee
Fixes a couple padding issues and adds /artsy-partner-updates to the responsive pages
> @eessex => Minor channel page updates

- analytics/article_impressions.js
- analytics/articles.js
Closes https://github.com/artsy/force/issues/209
Fix reversed impression/context type for TOC.
Update "related_article" to match microgravity.
> @kanaabe => Article update analytics

- apps/home/components/artists_to_follow/stylesheets/index.styl
- apps/home/components/artists_to_follow/view.coffee
> @mzikherman - Artists to follow QA

- apps/artwork/components/partner_artworks/query.coffee
see https://github.com/artsy/force-private/issues/5068#issuecomment-237919777
> @broskoski: don't include not-for-sale-artworks in partner artworks section of artwork page

- components/contact/show_inquiry_modal.coffee
- components/inquiry_questionnaire/index.coffee
- components/inquiry_questionnaire/views/basic_info.coffee
- components/inquiry_questionnaire/views/test_account.coffee
- models/logged_out_user.coffee
> @mzikherman - forced login split test QA

- components/split_test/running_tests.coffee
> @craigspaeth - Launch forced login split test

- components/inquiry_questionnaire/views/test_account.coffee
- components/inquiry_questionnaire/views/test_inquiry.coffee
> @craigspaeth - Mobile inquiry form does not have a modal

- apps/artist/components/current_show_auction/query.coffee
- apps/artist/queries/cv.coffee
- apps/artist/queries/related_show_image.coffee
- apps/artist/queries/show_fragment.coffee
- apps/artist/queries/shows.coffee
- apps/artwork/components/artists/query.coffee
Updates `exhibition_highlights` and `partner_shows` stuff from the Artist schema. I sort of naively grepp'ed for them...I _think_ these are all.
> @alloy => Switch to use new Metaphysics Show schema

- apps/artwork/components/artists/query.coffee
- components/show_cell/helpers.coffee
Updates display to use new field.
> @mzikherman => Switch to use new city field to support ref shows on artwork page

- apps/artist/queries/cv.coffee
- apps/artist/queries/show_fragment.coffee
- lib/global_client_setup.coffee
Now that the bulk of the wiring up work was done in Gravity/Galaxy/Metaphysics, exposing ref shows on the artist page is a breeze.
> @craigspaeth => Support reference shows on the artist page

- apps/articles/routes.coffee
- apps/articles/stylesheets/section.styl
- apps/articles/templates/articles.jade
- apps/articles/test/routes.coffee
- models/article.coffee
- A couple places we weren't using server-side caching (i'll keep an eye out for stale content complaints from editorial)
- Remove extra Section fetch on /articles (and remove the "featured section" html+css altogether)
> @craigspaeth => Article caching and Magazine router cleanup

- components/article/stylesheets/index.styl
- components/article/templates/callout.jade
closes https://github.com/artsy/force/issues/260
Updated styling for callout articles and pull-quotes.
> @xtina-starr => Callouts inline

- apps/home/components/followed_artists/search_artists_view.coffee
Closes: https://github.com/artsy/force/issues/208
> @mzikherman : track artist follow from search artist component on homepage

- components/inquiry_questionnaire/test/views/test_inquiry.coffee
- components/inquiry_questionnaire/views/test_inquiry.coffee
We were getting errors for users placed in the forced_login bucket who were already logged in. This is due to us delaying the inquiry save until after the user gets through...however for logged in users the inquiry should be saved immediately.
cc @joeyAghion
> @craigspaeth - hotfix for forced login inquiry

- apps/artwork/test/routes.coffee
- models/additional_image.coffee
- models/artwork.coffee
Requires the 'larger' version to be there for download
> @craigspaeth => Be more defensive in artwork download route

- components/email/client/editorial_signup.coffee
Default CTA display to modal popup on fullscreen articles.
> @craigspaeth => CTA bug on fullscreen articles

- components/article/client/view.coffee
- components/article/stylesheets/index.styl
Closes https://github.com/artsy/force/issues/273
Removed fillwidth plugin from sections with a single artwork.
> @xtina-starr => Make single artworks fullwidth

- components/article/stylesheets/index.styl
Resize and center pull quotes in articles.
> @xtina-starrr => Pull quote styles

- components/article/client/view.coffee
- components/article/stylesheets/index.styl
- Add class distinction to a single vertical artwork
- Make max-height css apply only to single vertical artworks
> @kanaabe => Artwork heights

- components/artwork_filter_2/index.styl
see https://github.com/artsy/force/issues/285
> @xtina-starr margin between filters and results

- apps/home/routes.coffee
- apps/home/test/routes.coffee
This is more of a stopgap solution. This "cheats" the metaphysics promise by always resolving no matter what. 
Obviously we should think of a better way to move forward with the partial errors, maybe we can use this PR to discuss alternatives.
cc @craigspaeth @alloy
> @xtina-starr - render the homepage regardless, even if we fail to fetch the rails

- components/article/templates/index.jade
Update GI CTA to display when GI channel is present
> @kanaabe => GI CTA bug

- apps/fairs/helpers/view_helpers.coffee
Closes: https://github.com/artsy/force/issues/293
> @craigspaeth: Increase limit on Upcoming Fairs

- components/email/client/editorial_signup.coffee
Fixes the modal appearance for fullscreen articles
> @eessex => Fullscreen signup modal fix #minor

- apps/home/client/index.coffee
- apps/home/templates/rails.jade
> @briansw - Launch artists to follow rail

- apps/articles/routes.coffee
- components/email/client/editorial_signup.coffee
- components/email/test/editorial_signup.coffee
cc @robertlenne thanks for catching!
> @eessex => Hides magazine modal for logged in users

- components/article/client/view.coffee
- components/article/stylesheets/fullscreen_article.styl
- components/article/stylesheets/image_set.styl
- components/article/stylesheets/index.styl
- components/article/templates/index.jade
- components/article/templates/mixins.jade
- components/article/test/view.coffee
- components/email/stylesheets/editorial_signup.styl
This PR addresses changes in:
https://github.com/artsy/force/issues/238
closes https://github.com/artsy/force/issues/237
The image-set preview is not touched here -- @owendodd requested an update to display as it does in microgravity, will address this in a separate issue. 
Also sorry about the long commit list - had some issues with rebasing failing!
> @kanaabe => Responsive articles component

- analytics/article_impressions.js
Bug fix, analytics now fire for image-sets
> @kanaabe => Article analytics: Imageset

- components/article/client/view.coffee
- components/article/templates/mixins.jade
- components/article/test/view.coffee
Embedded content can apply 'mobile height' field from Writer.
> @kanaabe => Add mobile heights to embeds

- apps/artist/templates/meta.jade
- apps/artist/test/view_helpers.coffee
- apps/artist/view_helpers.coffee
This is just some leftover pertaining to [this](https://github.com/artsy/force/pull/183).
> @broskoski: remove remaining auction title tag tests

- apps/artwork/components/artists/index.styl
cc @briansw 
Closes https://github.com/artsy/force/issues/319
> @mzikherman => Restore lost padding #minor

- apps/artist/client/views/overview.coffee
- apps/artist/queries/show_fragment.coffee
- apps/artist/templates/sections/cv_item.jade
- apps/artwork/components/artists/templates/exhibition.jade
cc @briansw 
Dont wrap ref shows in anchor tags, and group them into 'Group/Solo' properly (on Artist pages, artwork pages were already working).
> @mzikherman => Minor ref show QA

- components/article/client/view.coffee
Apply max width to container instead of the image
> @kanaabe => Image caption bug

- analytics/articles.js
- components/email/client/editorial_signup.coffee
- components/email/test/editorial_signup.coffee
- components/split_test/README.md
Just met with Ani to confirm setup on this -- the updates from yesterday were incorrect, I've removed those and replaced it with the missing piece (calling splitTest.view() on the client side)
> @kanaabe => Ab analytics

- analytics/articles.js
Bug fix, modal was not closing because of undefined var.
> @kanaabe => modal closes

- apps/article/stylesheets/index.styl
> @kanaabe => Read-next responsive

- test/models/search_result.coffee
Just double checking Force is modelling articles correctly when they are present in search results.
> @mzikherman : basic tests for articles in search bar results #minor

- apps/partner/client/articles.coffee
- apps/partner/test/client/articles.coffee
- apps/partner2/client/articles.coffee
- apps/partner2/test/client/articles.coffee
I _think_ it should be ok to run this after the embedded article is loaded. Can't really do this from the server-side since the article is fetched later, but since it's a script I think the delay doesn't matter.
> @craigspaeth => Adds json-ld to partner articles (for Parsely)

- components/article/stylesheets/index.styl
- components/article/templates/callout.jade
Update to new callout styles, accounts for imageless articles.
> @xtinastarr=> New callouts, imageless

- components/main_layout/footer/index.styl
- components/main_layout/footer/mobile_footer_menu.jade
- components/main_layout/footer/template.jade
- components/main_layout/footer/view.coffee
Closes https://github.com/artsy/force/issues/242
Main layout footer changes to mobile version at 600px, has anonymous and logged in states.
> @kanaabe => Responsive main layout footer

- components/article/client/view.coffee
- components/article/stylesheets/index.styl
Closes https://github.com/artsy/force/issues/240
Readmore rebuilds crop height and goes to mobile styles on resize.
> @kanaabe => Responsive scrollheights

- apps/artwork/components/commercial/templates/inquire.jade
> @mzikherman - Updates fair tooltip messaging

- components/article/client/fullscreen.coffee
- components/article/client/super_article.coffee
- components/article/stylesheets/fullscreen_article.styl
- components/article/stylesheets/index.styl
- components/article/stylesheets/super_article.styl
- components/article/templates/mixins.jade
- components/article/templates/super_article_footer.jade
- components/article/templates/super_article_sticky_header.jade
- components/article/test/super_article.coffee
- components/channel_nav/test/view.coffee
- components/main_layout/stylesheets/body.styl
Closes https://github.com/artsy/force/issues/336 https://github.com/artsy/force/issues/337
PR-ing for now, need to do a round of cleanup and then I'll let you know when it's ready for review!
Header desktop:
Header mobile:
Footer desktop:
Footer mobile:
> @eessex => Super Article redesign (nav, footer, responsive)

- components/artwork_filter_2/index.styl
cc @briansw this was causing the large headings on the new filter on the artist page.
> @anyone => Define constant before it gets used

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/eoy.styl
- apps/editorial_features/components/eoy/index.jade
- apps/editorial_features/components/eoy/super_article.styl
- apps/editorial_features/index.coffee
- apps/editorial_features/routes.coffee
- apps/editorial_features/test/routes.coffee
- assets/editorial_features.styl
- components/article/client/super_article.coffee
- components/article/stylesheets/super_article.styl
- config.coffee
- lib/setup_sharify.coffee
Great time pairing on this!! I added a test and a stylesheet for EOY-specific stuff.
Just note that we should put EOY_2016_ARTICLE variable in Heroku --- probably only for staging right now. It's currently living as a private var since we don't have the article in place but I'm open to changing that as we get the articles published.
> @eessex => EOY Nav and Footer

- components/json_page/index.coffee
- components/json_page/test/index.coffee
Re: https://artsy.slack.com/archives/web/p1479207968001516
I'm guessing the request timed out (hence no response object), but that would be pretty hard to replicate / prove.
> @craigspaeth - Be defensive about checking for error on response object

- apps/artwork/stylesheets/index.styl
> @OLI9292  - Adjust z-index for artwork metadata div (closes #361)

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- apps/editorial_features/components/eoy/stylesheets/index.styl
- apps/editorial_features/components/eoy/templates/body.jade
Intro and first few sections are animated
Videos have play controls
Added image carousels
> @kanaabe => EOY animations + additions

- config.coffee
- lib/middleware/block_ip.coffee
- lib/setup.coffee
> @alloy - Add middleware to block ip addresses

- apps/show/components/artwork_columns_metaphysics/view.coffee
- apps/show/components/artwork_item_metaphysics/templates/variable_width_image.jade
- apps/show/routes.coffee
fixes https://github.com/artsy/force/issues/157
I was testing this out using this show: https://artsy.net/show/charles-nodrum-gallery-john-aslanidis
before and after (click to expand to see pixelation)
----------------------------------------
> @craigspaeth : used cropped or resized image if available. use larger image version on show artwork columns

- apps/partner2/components/fixed_cells_count_carousel/shows.jade
fixes https://github.com/artsy/force/issues/165
> @craigspaeth: use larger image for show carousel on partner profile

- apps/show/components/artwork_columns_metaphysics/view.coffee
- apps/show/components/artwork_item_metaphysics/templates/variable_width_image.jade
- apps/show/routes.coffee
> Revert "@craigspaeth : used cropped or resized image if available. use larger image version on show artwork columns"

- apps/articles/index.coffee
- apps/articles/routes.coffee
- lib/middleware/redirect_mobile.coffee
Instead of using the already existing editorial-signup/form, just create a custom one to handle the `source` attribution (could _not_ get this working regularly). Also update the redirect links.
> @mzikherman => Separate form and fix redirect mg url

- test/helpers/integration.coffee
> @craigspaeth fix promise being returned

- analytics/account_creation.js
- analytics/inquiry_questionnaire.js
- assets/analytics.coffee
- components/marketing_signup_modal/index.coffee
- components/marketing_signup_modal/index.jade
- npm-shrinkwrap.json
- package.json
This does a couple things:
* Get client-side + server-side tracking in sync
* Add a "full name" field above email
* Refresh the page after the thank you message on desktop to show logged in
Most importantly we needed to get client-side and server-side tracking in sync and both sending along the `user_id` and `acquisition_initiative`. The other two are should-have UX items.
cc @anipetrov
> @broskoski: Signup Modal QA

- apps/partner/templates/_artists_grid.jade
- apps/partner2/components/artists_grid/index.jade
- apps/partner2/components/artists_grid/view.coffee
Fixes https://github.com/artsy/force/issues/316
> Don't show non-rep'ed artists when they set to no display

- components/fair_layout/templates/index.jade
> @xtina-starr - Adds missing bodyClass to fair layout

- components/artwork_brick/index.styl
- components/artwork_item/stylesheets/index.styl
Updates the placeholder color to the lighter gray color
> @briansw - Update artwork placeholder color

- models/search_result.coffee
- test/models/search_result.coffee
- Adds support for city searches in search results, in order to expose [landing pages like this](https://www.artsy.net/shows/new-york-ny-usa).
> @starsirius : add support for cities in search results

- components/auction_reminders/blacklist.coffee
- components/auction_reminders/test/blacklist.coffee
> @eessex => Blacklist EOY in auction reminders

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- apps/editorial_features/components/eoy/stylesheets/index.styl
- apps/editorial_features/components/eoy/stylesheets/scroller.styl
- apps/editorial_features/components/eoy/stylesheets/super_article.styl
- apps/editorial_features/components/eoy/templates/body.jade
- apps/editorial_features/components/eoy/templates/index.jade
- add mobile styles to feature animation, body and menu
- Update body animations so all sections display
> @kanaabe => EOY responsive styles

- .env.oss
> @alloy - Add API_URL to .env.oss

- apps/fairs/test/template.coffee
- components/marketing_signup_modal/index.coffee
- components/marketing_signup_modal/index.jade
- components/marketing_signup_modal/index.styl
- components/modalize/view.coffee
Wraps up checklist from https://github.com/artsy/force/issues/365#issuecomment-262343858
> @alloy: QA work for marketing modal

- apps/search/routes.coffee
- Adds cities to search results page
Missed this when pushing out the city work so they are only showing in the auto-suggest right now.
> @starsirius : add cities to search result page

- apps/article/templates/meta.jade
- apps/editorial_features/components/eoy/templates/head.jade
- apps/editorial_features/components/eoy/templates/index.jade
- apps/rss/templates/instant_articles.jade
Closes https://github.com/artsy/force/issues/467
> @eessex => Meta Tag Updates for Distribution Channels

- apps/artwork/components/artists/helpers.coffee
- apps/artwork/components/artists/index.coffee
- apps/artwork/components/artists/templates/biography.jade
- apps/artwork/components/artists/test/templates/index.coffee
> @mzikherman - Check for biography blurb text for artwork artists module

- components/artist_cell/fixture.coffee
- components/artist_cell/index.jade
- components/artist_cell/query.coffee
Closes https://github.com/artsy/force/issues/22
and re: https://github.com/artsy/gravity/pull/10626
Feel free to merge whenever, but this will actually start working on the `related_artists` page when that Gravity PR gets deployed.
> @mzikherman - Use formatted_nationality_and_birthday

- lib/middleware/redirect_mobile.coffee
> @eessex => Don't redirect mobile on eoy-2016

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- Updates video waypoints to apply to all videos
- adds styles for video in section #2
- open the scroller on initialize
> @kanaabe => EOY bug fixes

- apps/article/routes.coffee
- apps/article/templates/article.jade
- components/article/client/super_article.coffee
- components/article/stylesheets/eoy_2016_sub_articles.styl
- components/article/stylesheets/index.styl
- models/article.coffee
- test/models/article.coffee
Closes https://github.com/artsy/force/issues/381
[do not merge] because we don't have an ID for the super article yet and it would consequently change the 2015 layout.
Screenshots: 
Image/header combo
Mobile: 
@owendodd lmk what you're thinking about mobile. i mimicked the stuff we're doing for landing pages for now.
> @eessex => EOY super-sub article styling

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- apps/editorial_features/components/eoy/stylesheets/scroller.styl
- apps/editorial_features/components/eoy/templates/body.jade
- apps/editorial_features/components/eoy/templates/index.jade
- apps/editorial_features/components/eoy/templates/scroller.jade
Moment titles in header scroller are now link anchors to their corresponding body section.
> @kanaabe => EOY link anchors

- components/article/stylesheets/eoy_2016_sub_articles.styl
- components/article/templates/index.jade
- config.coffee
- lib/middleware/redirect_mobile.coffee
- models/article.coffee
- A few style updates for sub articles
- EOY sub slugs
- Draft access for sub articles
> @eessex => [EOY] Sub Article Draft Access + Styling

- apps/editorial_features/components/eoy/stylesheets/body.styl
Adds mobile styles for final sections
> @kanaabe => EOY is responsive

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/templates/body.jade
- apps/editorial_features/test/components/eoy/client.coffee
I'll comment below on a couple questions I had!
> @eessex => [EOY] Tests

- apps/editorial_features/components/eoy/stylesheets/body.styl
- apps/editorial_features/components/eoy/templates/body.jade
> @kanaabe => EOY update section order

- apps/artwork/components/commercial/bootstrap.coffee
- apps/artwork/components/commercial/view.coffee
- apps/artwork_purchase/templates/summary.jade
- apps/artwork_purchase/test/templates.coffee
closes https://github.com/artsy/collector-experience/issues/64
closes https://github.com/artsy/collector-experience/issues/68
> @craigspaeth: more qa fixes

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- Animation of vertical lines overshoots container by 400px
- Video controls are sized to the video dimensions, update on resize
> @kanaabe => EOY: video, vertical lines

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- apps/editorial_features/components/eoy/stylesheets/scroller.styl
- Add animated delay to text-anchor scrolling
- Adjust fade-in boundary for screens under 550px
- Fade in sections once
- Update h2's to use breakpoints rather than scaling by page width
> @kanaabe => [EOY] QA

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- apps/editorial_features/components/eoy/stylesheets/scroller.styl
- apps/editorial_features/components/eoy/templates/body.jade
- add missing image and caption
- move video click event after body has loaded
- change intro font size in mobile
> @kanaabe => EOY fixes

- apps/editorial_features/components/eoy/stylesheets/body.styl
- apps/editorial_features/components/eoy/templates/body.jade
- apps/editorial_features/components/eoy/templates/carousel.jade
- apps/editorial_features/components/eoy/templates/index.jade
- components/article/stylesheets/image_set.styl
- components/article/templates/image_set.jade
Adds captions for the final images, video caption, and fixes some sizing on image sets
> @eessex => [EOY] Final captions

- analytics/articles.js
- analytics/before_ready.js
- analytics/editorial_features.js
- apps/articles/index.coffee
- apps/articles/routes.coffee
- apps/editorial_features/index.coffee
- components/article/client/super_article.coffee
- components/auction_reminders/blacklist.coffee
- components/recently_viewed_artworks/exclude_list.coffee
- lib/middleware/redirect_mobile.coffee
- lib/routers/hardcoded_redirects.coffee
- lib/setup.coffee
Removes all /eoy-2016 references
Removes all splash page + signup code
Makes /2016-year-in-art live and for public
> @eessex => [EOY] Make EOY Live

- apps/editorial_features/components/eoy/stylesheets/index.styl
- apps/editorial_features/components/eoy/stylesheets/scroller.styl
- lib/routers/hardcoded_redirects.coffee
- npm-shrinkwrap.json
- Full opacity for mobile headers
- Cells with no margin on carousel
- Fix UBS logo + back to mag button
- Update redirect url
> @eessex => [EOY] QA Few mobile items

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- apps/editorial_features/components/eoy/stylesheets/index.styl
- apps/editorial_features/components/eoy/stylesheets/scroller.styl
- apps/editorial_features/components/eoy/templates/carousel.jade
- Smaller intro text
- Update logo size for ubs
- Smaller space between scrolling on header
- Mobile tweak for header height
- Corrects captions on carousel
> @kanaabe => [EOY] Mobile QA

- apps/editorial_features/components/eoy/templates/body.jade
- apps/editorial_features/components/eoy/templates/head.jade
- apps/editorial_features/routes.coffee
- components/main_layout/templates/blank.jade
Caption issue, Parsely bucketing, Viewport
> @craigspaeth => [EOY] Caption issue, Parsely bucketing, Viewport

- apps/eoy_2016/fixtures/data.json
- apps/eoy_2016/index.coffee
- apps/eoy_2016/routes.coffee
- apps/eoy_2016/templates/index.jade
- assets/eoy_2016.styl
- components/eoy_artist_list/_artist_item.jade
- components/eoy_artist_list/artist_item.styl
- components/eoy_artist_list/index.jade
- components/eoy_artist_list/index.styl
- lib/setup.coffee
Did a little bit more than the basics here but this sets up the basic structure for:
- JSON page route (which will serve as a way to easily develop the component, gives admins a way to edit the content, and will serve data to both MG and the artist page banner check thing)
- Artist list component (which will appear on the homepage and artist index page)
> @alloy - [EOY] basic structure for eoy artist list component

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- apps/editorial_features/components/eoy/stylesheets/index.styl
- apps/editorial_features/components/eoy/stylesheets/scroller.styl
- apps/editorial_features/components/eoy/templates/body.jade
- apps/editorial_features/components/eoy/templates/scroller.jade
- apps/editorial_features/test/components/eoy/client.coffee
- Social buttons in header and body
- Adjust scroller height to new header size
- make 'back to magazine' link normal font-weight
> @kanaabe => [EOY] Social / QA

- assets/eoy_2016.coffee
- components/eoy_artist_list/_artist_item.jade
- components/eoy_artist_list/artist_item.styl
- components/eoy_artist_list/index.coffee
- components/eoy_artist_list/index.styl
Closes #543 
Closes #542 
Closes #541
> @alloy - Add follow button to artist item in EOY list

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- Extend event target to button class
- playVideo reassigns target if button clicked
- a few small fixes to social
> @kanaabe => [EOY] video play button

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- Page auto scrolls down and stops once it has passed into body
> @kanaabe => [EOY] Auto scrolling

- apps/partner2/client/overview_layout_factory.coffee
- apps/partner2/test/client/overview_layout_factory.coffee
Only show the artists component when `profile_artists_layout` is true.
> Hide artists component when not enabled

- analytics/artwork.js
- analytics/artwork_purchase.js
- apps/artwork/components/commercial/templates/acquire.jade
- apps/artwork/components/commercial/templates/index.jade
- apps/artwork/components/commercial/templates/purchase_flow_inquiry_buttons.jade
- apps/artwork/components/commercial/view.coffee
- apps/artwork/routes.coffee
- apps/artwork/templates/index.jade
- apps/artwork_purchase/client/index.coffee
- apps/artwork_purchase/client/purchase_form.coffee
- apps/artwork_purchase/client/purchase_signup_form.coffee
- apps/artwork_purchase/helpers.coffee
- apps/artwork_purchase/routes.coffee
- apps/artwork_purchase/templates/success.jade
- apps/artwork_purchase/test/routes.coffee
- assets/analytics.coffee
made a new branch
closes https://github.com/artsy/force/issues/463
closes https://github.com/artsy/force/issues/536
> @craigspaeth Analytics

- apps/artists/client/index.coffee
- apps/artists/routes.coffee
- apps/artists/templates/index.jade
- apps/eoy_2016/routes.coffee
- apps/home/client/index.coffee
- apps/home/routes.coffee
- apps/home/templates/index.jade
- assets/artists.styl
- assets/home.styl
- components/eoy_artist_list/_artist_item.jade
- components/eoy_artist_list/artist_item.styl
- components/eoy_artist_list/index.jade
- components/eoy_artist_list/index.styl
- components/eoy_artist_list/server.coffee
You can also use this server component to pull data for the individual artists page.
> @alloy - Add EOY artist list to home and artists page for admins only

- apps/partner2/stylesheets/overview.styl
Fixes https://github.com/artsy/force/issues/522
> Show partner2 news in horizontal list

- apps/artwork/components/commercial/query.coffee
- apps/artwork/components/commercial/templates/editions.jade
closes: https://github.com/artsy/collector-experience/issues/66
> @mzikherman: add 'Sold' flag to edition sets that are sold

- apps/partner/client/filter_settings.coffee
- apps/partner2/client/filter_settings.coffee
Former comments were misleading.
> Updates comments for accuracy

- components/eoy_artist_list/artist_item.styl
> @alloy - [EOY] Fix layout weirdness on wide screens

- apps/artwork_purchase/client/purchase_signup_form.coffee
fixes https://github.com/artsy/force/issues/593
> @craigspaeth bubble up error from user lookup

- components/article/client/view.coffee
- components/article/stylesheets/image_set.styl
Closes #571 
Closes https://github.com/artsy/microgravity/issues/80
(Also updated the image to use an https link)
> @kanaabe - Scope image slideshow modal changes to class

- components/marketing_signup_modal/index.coffee
- components/marketing_signup_modal/index.jade
- components/marketing_signup_modal/index.styl
> @mzikherman - Trigger login instead of signup on marketing modal

- apps/article/stylesheets/index.styl
- apps/article/stylesheets/promoted_content.styl
- apps/article/templates/promoted_content.jade
- apps/article/test/client/index.coffee
- components/article/stylesheets/index.styl
- components/articles_grid/stylesheets/index.styl
- lib/middleware/redirect_mobile.coffee
Closes https://github.com/artsy/force/issues/243
> @eessex => Responsive Promoted Content and Footer Articles

- apps/artwork/components/commercial/view.coffee
- components/inquiry_questionnaire/map/decisions.coffee
- components/inquiry_questionnaire/map/steps.coffee
fixes https://github.com/artsy/force/issues/598
also fixes a bug i saw while fixing the first where a logged out user with an account was getting sent directly to the password entry step, skipping over the inquiry step where you can modify your message.
> @broskoski fix some bugs with inquiry modal

- components/marketing_signup_modal/index.coffee
- components/marketing_signup_modal/index.styl
> @alloy - Fix signup modal for responsive pages (like articles)

- analytics/eoy_2016.js
- apps/home/templates/index.jade
- assets/analytics.coffee
- components/eoy_artist_list/_artist_item.jade
Closes https://github.com/artsy/force/issues/568
Follow button already has analytics on it, this adds the other two events.
> @alloy - [EOY] Analytics

- apps/artwork/components/commercial/templates/acquire.jade
- apps/artwork/components/commercial/templates/index.jade
- apps/artwork/components/commercial/view.coffee
- apps/artwork/routes.coffee
- apps/artwork/templates/index.jade
- apps/artwork_purchase/routes.coffee
- apps/artwork_purchase/test/routes.coffee
just wanna get a green light from @tayapage6 and @briansw and give @anipetrov an opportunity to check out the added analytics events since my last pr was merged
> @alloy [HOLD] launch purchase flow test on production

- apps/artwork_purchase/client/purchase_form.coffee
Rename purchase to purchase_request for https://github.com/artsy/gravity/pull/10671
> @joeyAghion => Rename purchase to purchase_request

- apps/artwork_purchase/helpers.coffee
> @alloy => Fixing typo in purchase receipt

- apps/home/components/followed_artist_context/query.coffee
- apps/home/queries/module.coffee
- apps/home/view_helpers.coffee
Don't merge until https://github.com/artsy/metaphysics/pull/510 is!
> @alloy - Update homepage queries to handle followed_artist module #dontmerge

- apps/press/templates/index.jade
Simple request from [Anna](https://team.artsy.net/anna.carey).
> @1aurabrown: Swap links order in press page

- apps/collect/client.coffee
- components/commercial_filter/views/popular_artists/index.jade
- components/commercial_filter/views/popular_artists/index.styl
- components/commercial_filter/views/popular_artists/popular_artists_view.coffee
These were the last pieces (as I remember) for launching this out of labs, finally. (https://github.com/artsy/collector-experience/issues/76)
- Only shows widget on first page
- Adds chevron and truncates long names
So I think this can be launched? cc @briansw @tayapage6  let's get this out!
> @alloy => Popular artists QA

- components/artist_page_cta/index.styl
- components/artist_page_cta/overlay.jade
- components/artist_page_cta/template.jade
- components/artist_page_cta/view.coffee
Not really functional yet, just scaffolding...
The 'smooth' animation is sorta hard to see in the GIF
> @alloy => Add 'sign up' button and initial full screen overlay

- apps/home/client/setup_home_page_modules.coffee
- apps/home/components/related_artists_context/annotation.jade
- apps/home/components/related_artists_context/query.coffee
- components/artwork_brick_rail/index.styl
- components/artwork_brick_rail/templates/index.jade
- components/artwork_brick_rail/view.coffee
> @mzikherman - Extract annotation into its own template, add link to based on text

- apps/artwork/components/additional_info/index.coffee
- apps/artwork/components/additional_info/templates/about_the_work.jade
> Adds read more cap to 'about more' artwork descriptions

- components/commercial_filter/views/popular_artists/index.styl
> @alloy => Add color transition and change font size of chevron for popular artists

- components/slider/nouislider-base.styl
- components/slider/nouislider-override.styl
Closes #629 
Looks like the slide plugin got updated and the markup is slightly different now.
> @mzikherman - Fix styling on sliders for /collect

- apps/article/client/index.coffee
- components/article/stylesheets/editorial_signup.styl
- components/article/stylesheets/index.styl
- components/articles_grid/stylesheets/index.styl
- components/channel_nav/index.styl
Closes https://github.com/artsy/force/issues/628
- Changes max width for article-grid and team-nav components to 1600px
- Restore responsive grid to article-grid
- GI signup is responsive
- Minor breakpoints/margin changes for consistency
> @kanaabe => Responsive Team Nav

- components/json_page/seed.coffee
- components/json_page/update.coffee
Working through merging codebases and one of the trickier things will be joining the S3 buckets between Force & Microgravity. This is a small thing to consolidate how we point to those buckets using the `APPLICATION_NAME` config variable.
>  @xtina-starr: Move JSON page bucket to config var

- analytics/collect.js
- components/commercial_filter/views/popular_artists/index.jade
Closes https://github.com/artsy/collector-experience/issues/83
> @1aurabrown => Add click tracking for popular artists

- components/article/templates/mixins.jade
- components/article/test/templates.coffee
- components/article/test/view.coffee
- Article artworks print names from 'artists' array by default and fallback to 'artist'
- Tests updated to use 'artists' array
> @kanaabe => Article artworks use 'artists' array

- components/commercial_filter/views/popular_artists/index.styl
- components/commercial_filter/views/popular_artists/popular_artists_view.coffee
Closes https://github.com/artsy/collector-experience/issues/82
commit msgs tell the story
> @xtina-starr => Minor popular artists QA

- components/article/client/view.coffee
- components/article/stylesheets/index.styl
- components/article/templates/mixins.jade
- components/article/test/view.coffee
- Adds support for positron's image 'layout' field 
- Resizes images if they exceed 90vh, regardless of orientation
- Redo image-size check on window resize
> @kanaabe => Image heights

- apps/partnerships/client/view.coffee
- apps/partnerships/templates/nav.jade
Fixes the [broken **apply** link](https://artsy.slack.com/archives/help/p1483641955000360) on the [/institution-partnerships](https://www.artsy.net/institution-partnerships) page
> @starsirius => Fix institutions apply link

- apps/articles/stylesheets/team_channel.styl
Header was causing a width scrollbar to appear in staging, this fixes it from overflowing.
> @kannabe => Team Channel QA

- apps/artist/client/index.coffee
- apps/artist/routes.coffee
- apps/artist/templates/payoff.jade
- apps/home/components/followed_artists/templates/index.jade
- apps/home/components/followed_artists/templates/result.jade
- apps/home/components/followed_artists/view.coffee
- components/artist_page_cta/index.styl
- components/artist_page_cta/query.coffee
- components/artist_page_cta/templates/register.jade
- components/artist_page_cta/view.coffee
Implements the 'payoff' screen for the new artist page CTA.
Up next:
- analytics and some QA work(!)
- launch AB test
> @xtina-starr => Artist page CTA payoff screen

- components/artist_page_cta/index.styl
Closes #657 
Got it to look as close as possible to the screenshot.
> Make caret on new Artist Page white/transparent

- apps/artist/client/cta.coffee
- apps/artist/routes.coffee
- apps/artist/test/routes.coffee
- components/artist_page_cta/view.coffee
- config.coffee
This launches the full screen CTA once you scroll 2 viewport's worth (and once you dismiss it it doesn't automatically get triggered.
Additionally, I added a special query param, `show_artist_cta_code` that if present, will show the CTA (so we can QA it). I've already set this ENV var on Heroku.
> @xtina-starr => Launch overlay when you scroll, and show CTA when special query param is set

- Makefile
- npm-shrinkwrap.json
- package.json
To avoid relying on S3 on bootup, [more details here](https://github.com/artsy/bucket-assets/pull/48).
> @broskoski: Update bucket-assets to pull from environment

- components/main_layout/stylesheets/navigation.styl
fixes https://github.com/artsy/force/issues/29
brian said not to change the icon itself, so it's just a change of colors for the following state
> @craigspaeth update follow entity button

- apps/artist/client/cta.coffee
closes: https://github.com/artsy/force/issues/656
This uses the referrer to determine if a user is coming from an external source and displays low-key cta to logged out users.
> @mzikherman: display low-key cta bar to logged out users from external source

- apps/home/client/index.coffee
- apps/home/routes.coffee
- apps/home/templates/index.jade
- assets/home.styl
fixes part 1 of https://github.com/artsy/collector-experience/issues/80
I saw that this issue exists but that EOY is still on the homepage.
> @mzikherman remove EOY from homepage

- components/artist_page_cta/view.coffee
whoops changed this at the last sec!
> @mzikherman => Correct var name for launching overlay from scroll

- apps/partner2/index.coffee
- apps/partner2/routes.coffee
- apps/partner2/test/index.coffee
New institutions profiles are ready for prime time!
Closes https://github.com/artsy/force/issues/685
> Launches upgraded institutions profiles

- components/main_layout/stylesheets/buttons.styl
- components/stylus_lib/colors.json
- npm-shrinkwrap.json
Re: https://github.com/artsy/artsy-ezel-components/pull/13
New purple is the biggest difference...
> @mzikherman - Update colors to match the ones on Elan

- apps/rss/index.coffee
- apps/rss/routes.coffee
- apps/rss/templates/article.jade
- apps/rss/test/news.coffee
- Change `PAGE_SIZE` to 50. 100 is just taking too long
- Remove meta tag (it's not valid to use meta tags in `content:encoded`)
- Remove extra wrapping p tag 
- Multi artist support
> @eessex => RSS Multiple Artists, make validators happy

- components/article/stylesheets/index.styl
- Image captions match styling of artwork captions
> @kanaabe => Article image captions

- components/main_layout/stylesheets/navigation.styl
fixes https://github.com/artsy/force/issues/703
> @craigspaeth fix entity follow button color and spacing

- apps/search/collections/global_search_results.coffee
- components/search_bar/collections/search.coffee
The artist's gallerist confirms that they are fine with being restored to search results.
> @gnilekaw => undo a custom search result exclusion

- components/email/client/editorial_signup.coffee
- components/email/stylesheets/editorial_signup.styl
- components/email/templates/editorial_cta_banner.jade
- components/email/test/editorial_signup.coffee
- components/split_test/running_tests.coffee
- Show new modal on article and magazine pages
- Remove old banner
- New modal CTA is responsive
> @kanaabe => Responsive cta modal

- components/article/stylesheets/editorial_signup.styl
- config.coffee
- lib/middleware/redirect_mobile.coffee
This can be merged after we handle the signup modals which we'll get results for tomorrow! Just wanted to get this ready and mergeable.
> @eessex => Stop redirect to MG on articles

- apps/auction/stylesheets/index.styl
- apps/auction/stylesheets/my_active_bids.styl
- apps/auction2/client.js
- apps/auction2/routes.js
- apps/auction2/stylesheets/index.styl
- apps/auction2/stylesheets/my_active_bids.styl
- apps/auction2/templates/index.jade
- apps/auction2/templates/my_active_bids.jade
- apps/auction2/templates/registration_component.jade
- apps/auction2/test/my_active_bids.js
- apps/auction2/test/templates.js
- assets/auction2.js
- assets/auction2.styl
- components/my_active_bids/query.coffee
- lib/setup.coffee
This PR adds the "My Active Bids" section to the auction2 page, based on the new designs.
> @craigspaeth => Auction2 "My active bids"

- components/article/stylesheets/index.styl
- components/email/stylesheets/editorial_signup.styl
Closes https://github.com/artsy/force/issues/709
On a side note, working with that article component stylesheet is really starting to become a pain. I may set aside some time for refactoring/cleaning up.
> @eessex => Mobile articles QA

- models/search_result.coffee
- test/models/search_result.coffee
> Show Institution label for institutions

- apps/artwork/components/images/query.coffee
- apps/artwork/components/images/templates/image.jade
(This depends on https://github.com/artsy/metaphysics/pull/523, don't merge until that one is!)
Re: https://github.com/artsy/collector-experience/issues/62
> @sweir27 - Add a title attribute to the artwork image tag #hold 

- analytics/partner.js
- apps/partner2/templates/contact_info.jade
Updated property names for contact gallery via email link and website link per https://github.com/artsy/force/pull/713#issuecomment-273289920
> @broskoski: use correct property names

- components/artist_page_cta/index.styl
- components/artist_page_cta/templates/overlay.jade
- components/artist_page_cta/view.coffee
Closes some more of the checked-off items
> @xtina-starr => Grabbag of some other visual QA

- assets/misc.coffee
For this one weird route we support in our user settings app https://artsy.net/profile/edit
> @craigspaeth: Load user asset package on /profile/ routes as well

- apps/artist/client/views/header.coffee
- apps/artist/routes.coffee
- apps/artist/templates/payoff.jade
- components/artist_page_cta/index.styl
- components/artist_page_cta/templates/register_footer.jade
- components/artist_page_cta/view.coffee
- components/follow_button/test/view.coffee
- components/follow_button/view.coffee
- components/main_layout/header/view.coffee
Some more visual QA, and a couple of functional ones, I'll make a couple of comments inline
> @xtina-starr => Some moar CTA QA

- apps/artwork_purchase/index.styl
fixes https://github.com/artsy/force/issues/710
> @briansw fix border color on artwork purchase

- components/artist_page_cta/index.styl
- components/artist_page_cta/templates/overlay.jade
- components/artist_page_cta/view.coffee
- config.coffee
center the content on the overlay and fade out the dropshadow with the content on the dropdown
https://github.com/artsy/force/issues/688
> @mzikherman updates to overlay

- apps/auction2/components/auction_grid/index.js
- apps/auction2/components/auction_grid/index.styl
- apps/auction2/components/auction_grid_artwork/index.js
- apps/auction2/components/auction_grid_artwork/index.styl
- apps/auction2/components/bid_status/index.js
- apps/auction2/components/bid_status/index.styl
> @craigspaeth => namespacing auction2 page

- apps/home/client/hero_unit_view.coffee
- lib/global_client_setup.coffee
- npm-shrinkwrap.json
- package.json
Closes #440 
Preeeety simple. The one simple trick was finding a nice mobile event library that actually worked.
> @mzikherman - Add swipe events for homepage banner

- components/artist_page_cta/index.styl
- components/artist_page_cta/templates/overlay.jade
- components/artist_page_cta/view.coffee
Closes https://github.com/artsy/force/issues/753
Closes https://github.com/artsy/force/issues/758
The latter is a blocker for release, and the former (IMO) also felt kinda grimy.
> @broskoski => Essential artist CTA QA

- components/artist_page_cta/index.styl
- components/artist_page_cta/templates/index.jade
- components/artist_page_cta/templates/overlay.jade
- components/artist_page_cta/view.coffee
- config.coffee
> @mzikherman fix transition when overlay is is invoked or dismissed

- apps/artist/client/cta.coffee
- components/artist_page_cta/index.styl
- components/artist_page_cta/templates/overlay.jade
- components/artist_page_cta/view.coffee
- components/auction_reminders/blacklist.coffee
Closes https://github.com/artsy/force/issues/759
Closes https://github.com/artsy/force/issues/754
Closes https://github.com/artsy/force/issues/750
Here's the mailcheck hint:
> @alloy=> Some more minor QA

- npm-shrinkwrap.json
- package.json
See https://github.com/artsy/artsy-passport/pull/98
> @craigspaeth- Bump artsy passport again

- components/article/client/view.coffee
- components/article/templates/callout.jade
- components/article/templates/mixins.jade
- components/article/test/view.coffee
Yesterday I moved callout article fetching to server-side and introduced a bug with infinite scroll articles that have callouts. If it's an infinite scroll article with a callout, we will render it client-side with this PR.
> @craigspaeth => Callout Fix on Infinite Scroll

- components/artist_page_cta/index.styl
- components/artist_page_cta/templates/row.jade
Fixes https://github.com/artsy/force/issues/783
> @briansw => Better refactor of pseudo feed on artist CTA

- apps/auction/templates/registration_component.jade
- apps/auction2/templates/registration_component.jade
> @sweir27 => email to specialist@ instead of inquiries@ on auction reg page

- components/artwork_metadata_stub/index.styl
- components/artwork_metadata_stub/queries/contact.coffee
- components/artwork_metadata_stub/templates/contact.jade
closes https://github.com/artsy/force/issues/729
> @mzikherman update artwork brick for auction data

- components/auction_lots/templates/artist.jade
closes https://github.com/artsy/force/issues/788
> @briansw update auction copy

- components/commercial_filter/models/params.coffee
OOPS did not mean to leave this in the `defaults`!
> @broskoski => dont aggregate by artist by default

- components/inquiry_questionnaire/error.coffee
- config.coffee
- lib/global_client_setup.coffee
- lib/setup_sharify.coffee
- npm-shrinkwrap.json
- package.json
cc @joeyAghion 
Re #801 
This will send client-side errors (and specific errors from the inquiry page) to our trial Raygun service. I tested it out, already looks useful. Log in via Heroku.
> @mzikherman - Client side error

- README.md
While looking through our projects, I noticed many of these were out of date and there were inconsistencies so I reached out to Yayoi and asked her to help me come up with an exemplar that I could copy/paste around. I'm going to get this commit in, confirm that I got it right and then update other repos.
It would also be cool if Danger could let us know when dates need to be updated, but that's something Future Jon can figure out when he's got a minute.
> Update copyright line

- components/artist_page_cta/index.styl
fixes https://github.com/artsy/force/issues/751
-----
------
> make artist cta responsive

- LICENSE
- README.md
Ok, last PR on license/copyright stuff today, promise! Turns out the copyright line belongs in the LICENSE file and that should be the single source of truth for this info.
> Update LICENSE file

- apps/article/templates/amp_mixins.jade
- assets/amp.styl
Instead of including it as an asset package, just transform the stylus sheet directly.
> @craigspaeth => Get AMP assets working

- apps/article/routes.coffee
- apps/article/templates/amp_mixins.jade
- models/article.coffee
Closes https://github.com/artsy/force/issues/829
> @eessex => Adds AMP-specific JSONLD

- apps/home/client/setup_home_page_modules.coffee
- apps/home/components/follow_button/index.coffee
> @mzikherman - Setup follow button for homepage followed artist rail

- apps/personalize/templates/favorites.jade
Closes https://github.com/artsy/force/issues/835
> @xtina-starr => Add &nbsp; to favorites page on onboarding

- components/artist_page_cta/view.coffee
closes: https://github.com/artsy/force/issues/841
> @mzikherman: dismiss Artist CTA modal with esc key

- apps/notifications/stylesheets/index.styl
fixes https://github.com/artsy/force/issues/823
> @kanaabe remove min width on columns in saved artwork view

- apps/fair/client/index.coffee
- components/marketing_signup_modal/index.coffee
- components/marketing_signup_modal/index.styl
Fixes responsive layout issues in https://github.com/artsy/collector-experience/issues/148
Some tweaks to accomplish the three responsive styles outlined in https://cloud.githubusercontent.com/assets/1022172/22787136/42f6904c-eea9-11e6-8482-406488163e9b.jpg
> some qa items for marketing modal

- apps/artwork/components/banner/index.jade
> @mzikherman => only show countdown for fairs

- Dangerfile
- components/main_layout/header/view.coffee
Closes https://github.com/artsy/force/issues/859
> @xtina-starr => Only show full page banner on signup click, and not login

- components/marketing_signup_modal/index.styl
this way the photo credit is always shown
> @xtina-starr pin modal image to bottom left

- components/cta_bar/view.coffee
- components/marketing_signup_modal/index.coffee
fixes https://github.com/artsy/force/issues/878
> @craigspaeth redirect after flash

- apps/auction2/reducers.js
- npm-shrinkwrap.json
- package.json
Last one had some weird npm errors 😬
> @damassi => remove updeep for now

- package.json
- yarn.lock
Circle was having a problem building JS assets otherwise. Mgith want to move this to github.com/artsy/ezel-assets,
> Add babel runtime

- package.json
- yarn.lock
To leverage Circle's parallelization.
> Update ezel assets

- CONTRIBUTING.md
- desktop/lib/setup.coffee
- mobile/apps/articles/test/client/articles.coffee
- mobile/lib/setup.coffee
Solves https://github.com/artsy/force/issues/906
> Update cookie session settings.

- desktop/lib/setup.coffee
- mobile/lib/setup.coffee
As mentioned in cookie-session docs.
> Add trust proxy setting

- Dangerfile
- circle.yml
Grabbing the old Dangerfile and attempting to set it back up.
> @orta: Add Danger back

- desktop/apps/artist/client/cta.coffee
- desktop/apps/artist/routes.coffee
- desktop/components/follow_button/view.coffee
- desktop/components/main_layout/header/view.coffee
- desktop/components/split_test/running_tests.coffee
Woo!
Closes https://github.com/artsy/collector-experience/issues/149
> @broskoski => Resolve artist page CTA AB test in favor of new full-screen CTA

- Dangerfile
For future developers trying to simulate Danger locally, note that you must first `git fetch` the artsy remote or risk `Commit ... doesn't exist` errors.
Example invocation:
DANGER_GITHUB_API_TOKEN=... danger pr https://github.com/artsy/force/pull/915
> @mzikherman: Fix Dangerfile PR link and add PR authors' names (fixes #922)

- desktop/apps/artsy_primer/client.js
- desktop/apps/artsy_primer/server.js
- desktop/assets/misc.coffee
I forgot to add some dependencies of the article view for primer articles like this one https://www.artsy.net/artsy-primer/sarah-gottesman-artwork-recommendations-carolyn-brehm
> @eessex: Add view helpers and client-side article view.

- desktop/apps/artwork/components/partner_stub/index.jade
Here comes my first PR! I'm sure there's something I did wrong, but let me know if there is anything I should fix!
closes #810.
> Add a border between artwork metadata and partner stub when it's not for sale

- desktop/apps/consignments/templates/landing.jade
- desktop/apps/consignments/templates/meta.jade
#minor PR to add a bunch of the standard `meta` tags to the consign page.
> @craigspaeth => adds meta tag to consign page

- mobile/apps/artist/routes.coffee
- mobile/apps/artist/test/routes.coffee
Intermittent failure on this test because we weren't actually hooking into the promise chain and trying to beat it with defers.
> @damassi: Fix race condition in test

- desktop/components/zig_zag_banner/index.styl
> @briansw => Fixes ribbon moving entire sidebar over

- desktop/components/json_page/index.coffee
- desktop/components/json_page/seed.coffee
- desktop/components/json_page/test/index.coffee
- desktop/components/json_page/update.coffee
- desktop/config.coffee
- desktop/lib/setup_sharify.coffee
- mobile/config.coffee
- mobile/lib/setup_sharify.coffee
Solves https://github.com/artsy/force/issues/965
I [noted a more future-facing idea](https://github.com/artsy/post_mortems/issues/11#issuecomment-283414357) about not having to use S3 for these (maybe using Positron curations), but for now this will let people edit these pages again.
> @kanaabe: Point to JSON page component to S3 bucket and not application name

- desktop/components/artist_page_cta/index.styl
- desktop/components/artist_page_cta/templates/index.jade
Closes https://github.com/artsy/force/issues/973
Closes https://github.com/artsy/force/issues/972
> @sweir27 => Tiny artist page CTA tweakz

- desktop/apps/sitemaps/templates/misc.jade
https://www.artsy.net/sitemap-misc.xml
> Fix: invalid URL in sitemap.

- mobile/apps/artwork/components/meta_data/templates/inquiry.jade
- mobile/apps/artwork/components/meta_data/test/template.coffee
> @mzikherman - Check for inquireability on contact button

- desktop/apps/home/client/setup_home_page_modules.coffee
- desktop/apps/home/components/follow_button/index.coffee
> @sweir27 - Fix generic gene follow button on homepage

- desktop/apps/sitemaps/index.coffee
- desktop/apps/sitemaps/routes.coffee
- desktop/apps/sitemaps/templates/fairs.jade
- desktop/apps/sitemaps/templates/features.jade
- desktop/apps/sitemaps/templates/genes.jade
- desktop/apps/sitemaps/templates/partners.jade
- desktop/apps/sitemaps/templates/profiles.jade
- desktop/apps/sitemaps/templates/shows.jade
- desktop/apps/sitemaps/test/routes.coffee
- desktop/apps/sitemaps/test/templates.coffee
Closes https://github.com/artsy/force/issues/997
- Better coverage on sitemap tests
- Move news sitemap to root, as per @joeyAghion's suggestion
> @mzikherman => Sitemap tests + news sitemap to root

- desktop/apps/artsy_primer/personalize/client/index.coffee
- desktop/apps/artsy_primer/personalize/stylesheets/categories.styl
- desktop/apps/artsy_primer/personalize/stylesheets/favorites.styl
- desktop/apps/artsy_primer/personalize/stylesheets/index.styl
- desktop/apps/artsy_primer/personalize/stylesheets/next_step.styl
- desktop/apps/artsy_primer/personalize/stylesheets/price_range.styl
- desktop/apps/artsy_primer/personalize/stylesheets/suggestible.styl
- desktop/apps/artsy_primer/personalize/stylesheets/thank_you.styl
- desktop/apps/artsy_primer/stylesheets/index.styl
- desktop/apps/auth/index.styl
- desktop/lib/middleware/redirect_mobile.coffee
- desktop/lib/setup.coffee
This adds mobile responsive breakpoints to the Artsy Primer personalize flow to get a quick mobile friendly version working. These aren't 100% to David's specs b/c some of the UI is trickier to morph into what he designed, so I made some off-the-cuff compromises to get something nice looking out the door sooner. I'll follow up in an email with more details about handing off this project to Collector Experience Team.
> @broskoski: Mobile breakpoints for Artsy Primer personalize flow

- desktop/apps/buy_art/stylesheets/index.styl
- desktop/apps/buy_art/templates/landing.jade
- Center icon image in mobile for benefits section.
- Add signup links to buttons.
> @yuki24: Fix icon links

- desktop/apps/auction2/components/auction_grid_artwork/index.styl
Minor thing I forgot to add in the last PR.
> @sweir27 => Don't expand images :grimacing:

- desktop/apps/auth/index.styl
- desktop/apps/auth/templates/log_in.jade
- desktop/apps/auth/templates/sign_up.jade
- desktop/assets/auth.coffee
- desktop/assets/auth.styl
- desktop/assets/misc.coffee
I actually introduced this! And not the primer thing...
> @joeyAghion => Fix CSS regression

- desktop/analytics/account_creation.js
- desktop/analytics/collect_art.js
- desktop/apps/auth/index.styl
- desktop/apps/auth/templates/sign_up.jade
- desktop/apps/collect_art/templates/landing.jade
- desktop/assets/analytics.coffee
- desktop/components/auction_reminders/blacklist.coffee
closes: #1020
This is a continuation of #1028 and all the issues that @briansw pointed out have been addressed.
> Tweak collect art signup page

- desktop/apps/artwork/client/index.coffee
Fixes a client-side preventing the below-the-fold JS from working.
> @mzikherman => Fix for below the fold crash on non-auction works

- desktop/apps/collect_art/stylesheets/index.styl
> [Collector Marketing] Make the button color transition duration consistent

- desktop/apps/auth/index.coffee
- desktop/apps/collect_art/index.coffee
This reverts commit c6cf872c6a31db8fcae7da694c6a01e71dc34ed6 to launch the Collector Marketing Landing Page.
> Revert "Hide collector marketing pages for now"

- desktop/apps/auth/templates/log_in.jade
- desktop/apps/auth/templates/sign_up.jade
- desktop/apps/collect_art/stylesheets/index.styl
- desktop/apps/collect_art/templates/landing.jade
- desktop/apps/collect_art/templates/meta.jade
closes https://github.com/artsy/force/issues/1050
This addresses the background image issue that came up in safari, firefox, and IE.
**Before**
**After**
> Collector marketing safari

- desktop/analytics/collect_art.js
- desktop/apps/collect_art/templates/landing.jade
Per @anipetrov's [comment](https://github.com/artsy/force/issues/1020#issuecomment-288106282) on the QA issue for the Collector Marketing Landing Page, this updates the analytic tracking properties for the sign up buttons.
> [Collector Marketing] update analytic tracking properties

- README.md
> @xtina-starr: Clarify how to deploy

- desktop/apps/artsy_primer/personalize/client/views/favorites.coffee
- desktop/apps/artsy_primer/personalize/client/views/next_step.coffee
- desktop/apps/artsy_primer/personalize/client/views/price_range.coffee
- desktop/apps/artsy_primer/personalize/templates/price_range.jade
Closes a few of the issues outlined here: https://github.com/artsy/force/issues/978
Two things:
1. Separates the `onFavorited` callback into three separate methods, in order to control the order in which they appear in the favorites window.
2. Actually sets the `notes` field on the user.
Thank you for your time.
> @mzikherman - Some Artsy Primer QA

- desktop/apps/partnerships/stylesheets/marketo.styl
quick fix to marketo form styling
> @cfinsess quick fix to marketo form styling

- desktop/components/main_layout/templates/index.jade
- desktop/components/main_layout/test/templates.coffee
Something @joeyAghion pointed out in #web the other day: https://artsy.slack.com/archives/web/p1489725867036265
We just need to make sure `lab_features` exists on `CURRENT_USER`.
> @broskoski => Add existy check on main_layout html

- desktop/apps/partnerships/stylesheets/marketo.styl
@mzikherman make apply button centered
> @mzikherman make apply button centered

- desktop/apps/artsy_primer/personalize/client/index.coffee
- desktop/apps/artsy_primer/personalize/test/client/index.coffee
- desktop/apps/artsy_primer/routes.js
- desktop/apps/artsy_primer/server.js
- desktop/components/flash/index.coffee
> @mzikherman - Handles setting sailthru variables for artsy-primer

- desktop/analytics/partner_application.js
- desktop/apps/partnerships/client/view.coffee
fix to https://github.com/artsy/force/pull/1079
> @kanaabe minor fix to analyticshook

- desktop/apps/artsy_primer/stylesheets/index.styl
- desktop/apps/artsy_primer/templates/article.jade
- desktop/apps/artsy_primer/templates/header.jade
> @mzikherman - More minor Artsy Primer QA

- desktop/apps/article/stylesheets/index.styl
Closes https://github.com/artsy/positron/issues/985
> @anyone => limit read-next width to 1100px

- desktop/apps/auction2/stylesheets/my_active_bids.styl
- desktop/components/add_to_calendar/index.styl
minor minor css things for the acution2 page
> @sweir27 => little fix for my active bids

- desktop/apps/partnerships/client/view.coffee
> @kanaabe take out leftover analytics require

- desktop/apps/artsy_primer/routes.js
Closes #1105 
`moment().format()` returns a date like: `"2017-03-28T10:51:49-04:00"`
@sperle does that work for you?
> @mzikherman - Use moment to format date, instead of new Date

- desktop/apps/artsy_primer/routes.js
> @craigspaeth - force user to be logged in when viewing artsy primer articles

- desktop/components/article/client/view.coffee
- desktop/components/article/stylesheets/content.styl
- desktop/components/article/stylesheets/index.styl
- desktop/components/article/stylesheets/video.styl
Closes https://github.com/artsy/force/issues/1106
> @eessex => Separate video styles and fix mobile video overflow

- desktop/apps/artsy_primer/personalize/client/views/next_step.coffee
- desktop/apps/artsy_primer/personalize/stylesheets/categories.styl
- desktop/apps/artsy_primer/personalize/stylesheets/index.styl
- desktop/apps/artsy_primer/personalize/stylesheets/next_step.styl
- desktop/apps/artsy_primer/personalize/stylesheets/suggestible.styl
- desktop/components/auth_modal/templates/_login_footer.jade
- desktop/components/auth_modal/templates/_signup_footer.jade
- mobile/apps/auth/index.coffee
Incidentally closes https://github.com/artsy/collector-experience/issues/193
> @alloy - More artsy primer QA

- desktop/apps/sitemaps/index.coffee
- desktop/apps/sitemaps/routes.coffee
- desktop/apps/sitemaps/test/routes.coffee
Corresponds to https://github.com/artsy/cinder/pull/121.
> Use cinder-generated partner sitemaps.

- desktop/apps/sitemaps/index.coffee
- desktop/apps/sitemaps/routes.coffee
- desktop/apps/sitemaps/test/routes.coffee
Part of https://github.com/artsy/cinder/issues/86.
https://s3.amazonaws.com/artsy-sitemaps/sitemap-shows.xml
...
https://s3.amazonaws.com/artsy-sitemaps/sitemap-shows-2016.xml
https://s3.amazonaws.com/artsy-sitemaps/sitemap-shows-2017.xml
> Replaces show sitemaps with cinder output.

- yarn.lock
Woot, just upgrade artsy-eigen-web-association
> @alloy => Upgrade artsy-eigen-web-association

- lib/memory_profiler.js
> [memory] Ignore initial heap growth, which is just startup growth.

- desktop/apps/auction2/client/index.js
> @damassi => stupid typo

- desktop/apps/sitemaps/index.coffee
- desktop/apps/sitemaps/routes.coffee
- desktop/apps/sitemaps/test/routes.coffee
Companion for https://github.com/artsy/cinder/pull/151. This is part of an image indexing experiment https://github.com/artsy/barium-ion/issues/1.
> @alloy => Serve artist images sitemaps.

- desktop/apps/artwork/README.md
Not much to see here, will self merge.
> [Dev] Minor typo fix

- mobile/apps/artwork/client/index.coffee
- mobile/apps/auth/templates/call_to_action.jade
- mobile/apps/auth/test/templates.coffee
- mobile/assets/mobile_all.coffee
At least one of these I traced to a commit around the merger, so I think this is just fallout.
Fixes https://github.com/artsy/collector-experience/issues/194
> @broskoski => Mobile signups + artwork page bug

- desktop/apps/pro_buyer/pages/landing/client/view.coffee
- desktop/assets/misc.coffee
Fixes https://github.com/artsy/collector-experience/issues/216
> @broskoski => Fix professional buyer asset package

- desktop/apps/categories2/components/AppContainer.js
- desktop/apps/categories2/components/Content.js
- desktop/apps/categories2/components/GeneFamilies.js
- desktop/apps/categories2/components/Intro.js
- desktop/apps/categories2/components/Sidebar.js
- desktop/apps/categories2/components/__snapshots__/AppContainer.spec.js.snap
- desktop/apps/categories2/data/data.json
These are the results of "mobbing" with @anandaroop and @oxaudo. We have some new fake data and beautiful orange and pink divs. One thing Roop and I discussed was how to pass messages from the sidebar to the content pane. In the past I've used React Router for this. Roop mentioned Waypoints might possibly be relevant also.
> Add stub data and skeleton components

- package.json
Fixes https://github.com/artsy/ezel-assets/issues/25.
> @craigspaeth => Add NODE_ENV=production to deloy-assets task

- index.js
Per your comment here: https://github.com/artsy/force/pull/1177#issuecomment-291881669
> @craigspaeth => use bluebird for performance

- desktop/apps/collect/templates/meta.jade
- desktop/apps/collect/test/meta.coffee
The Browse title is probably the least desirable SEO-wise, renamed to Collect.
Closes https://github.com/artsy/force/issues/1182.
cc: @christine-artsy
> Renamed browse page.

- .vscode/extensions.json
This looks like it covers the majority of the needed extensions to work productively in Force.
> [Dev] Add recommended extensions for Force

- desktop/apps/collect_art/stylesheets/index.styl
fixes #1215.
The container div for the icon was covering the button so I changed the style to only apply `transform rotate(90deg)` to the icon itself.
> Fixed an issue where Users can't click on the middle part of the 'SIGN UP' button on "/collect-art"

- desktop/apps/fair/components/booths/index.styl
- desktop/apps/fair/components/booths/section.jade
- desktop/apps/fair/components/booths/view.coffee
- desktop/apps/fair/components/browse/template.jade
- desktop/apps/fair/templates/overview_top.jade
closes: https://github.com/artsy/collector-experience/issues/190
> @yuki24: remove exhibitor count

- desktop/apps/loyalty/index.js
- package.json
- yarn.lock
Updated reaction-force and remounts the loyalty program app
> Upgrades reaction-force and remounts the loyalty app

- package.json
- yarn.lock
Hoping this will result in better restarting behavior than the App crashed screens Heroku puts up.
> @damassi: Added forever to start script

- desktop/apps/article/templates/article.jade
- desktop/apps/article/test/templates.coffee
RE: https://artsy.slack.com/archives/C083S2Y57/p1492191534419513
> @kanaabe: Added noindex meta tags to articles tagged with  noindex

- desktop/apps/artist/client/views/articles.coffee
- desktop/apps/artist/client/views/artworks.coffee
- desktop/apps/artist/client/views/auction_results.coffee
- desktop/apps/artist/client/views/cv.coffee
- desktop/apps/artist/client/views/header.coffee
- desktop/apps/artist/client/views/related_artists.coffee
- desktop/apps/artist/client/views/shows.coffee
I don't know what I am doing so please tell me if this is a bad idea.
This fixes a cosmetic problem related to https://github.com/artsy/force/issues/1060. If you go to an empty page like https://www.artsy.net/artist/munan-ovrelid/related-artists we will no longer show an empty title.
> @alloy => Fix: hide rails when empty.

- desktop/models/user.coffee
Follow-up to https://github.com/artsy/force/pull/1255.
> @craigspaeth => Remove Sentry user context reporting 

- desktop/apps/categories2/components/AppContainer.js
- desktop/apps/categories2/components/FamilyList.js
- desktop/apps/categories2/components/__snapshots__/AppContainer.spec.js.snap
- desktop/apps/categories2/lib/helpers.js
This is not really for merging, but I was trying to play with the scroll. Found one blog post online with the example of smooth scroll without jQuery and basically copied it here. We can play with it on Tuesday @anandaroop, @gnilekaw and decide what our approach should be.
> testing the scroll on categories2 page

- package.json
- yarn.lock
> Revert "Upgrade reaction-force"

- desktop/apps/editorial_features/components/venice_2017/client/video.coffee
- desktop/apps/editorial_features/components/venice_2017/stylesheets/index.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/video.styl
- desktop/apps/editorial_features/components/venice_2017/templates/body.jade
- desktop/apps/editorial_features/components/venice_2017/templates/cover.jade
- desktop/apps/editorial_features/components/venice_2017/templates/index.jade
- desktop/apps/editorial_features/routes.coffee
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
- desktop/apps/editorial_features/test/routes.coffee
- desktop/config.coffee
Also for posterity, we're using a custom build of [Google VR View](https://github.com/googlevr/vrview) that lives [here](https://github.com/kanaabe/vrview).
> @eessex => [Venice] Responsive player and cover

- desktop/apps/editorial_features/components/venice_2017/templates/index.jade
- desktop/apps/editorial_features/index.coffee
- desktop/apps/editorial_features/routes.coffee
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
- desktop/apps/editorial_features/test/routes.coffee
Video index checks curation to find a matching section, otherwise returns the first section
> @kanaabe => [Venice] Routes use slug

- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/components/venice_2017/stylesheets/index.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/video.styl
- desktop/apps/editorial_features/components/venice_2017/templates/carousel.jade
- desktop/apps/editorial_features/components/venice_2017/templates/video.jade
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
- Adds subscribe prompt and editorial signup form
- Adds overlay styles for unpublished sections
- Removes 360 icon for unpublished sections
> @kanaabe => [Venice] Unpublished video covers

- desktop/models/search_result.coffee
- desktop/test/models/search_result.coffee
This is a requirement for https://github.com/artsy/gravity/pull/10989
> @sweir27 : support for static internal pages in search

- desktop/analytics/editorial_features.js
- desktop/apps/editorial_features/components/venice_2017/client/video.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
- package.json
Track call names are subject to change. Naming updates will be posted here: https://github.com/artsy/force/issues/1305
Thanks for pairing with me on this! Afterwards I just added tests and cleaned up a bit.
> @eessex => [Venice] Analytics

- desktop/apps/editorial_features/components/venice_2017/stylesheets/index.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/video.styl
Covers a few items in https://github.com/artsy/force/issues/1237
> @eessex => [Venice] Style QA

- desktop/apps/editorial_features/components/venice_2017/stylesheets/body.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/index.styl
- desktop/apps/editorial_features/components/venice_2017/templates/body.jade
- desktop/apps/editorial_features/components/venice_2017/templates/index.jade
- desktop/apps/editorial_features/components/venice_2017/templates/nav.jade
- desktop/apps/editorial_features/components/venice_2017/templates/video_description.jade
Couldn't figure out pushing to your PR -- here are a few more items on that list.
> @kanaabe => Venice style QA

- CONTRIBUTING.md
Per https://github.com/artsy/force/pull/1311#issuecomment-297557984, this PR adds a little note about how to run Force in different NODE_ENVs:
```sh
yarn assets && NODE_ENV=x yarn start
```
> @craigspaeth => Update CONTRIBUTING.md 

- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/components/venice_2017/client/video.coffee
- desktop/apps/editorial_features/components/venice_2017/stylesheets/body.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/index.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/video.styl
- desktop/apps/editorial_features/components/venice_2017/templates/carousel.jade
- desktop/apps/editorial_features/components/venice_2017/templates/mixins.jade
- desktop/apps/editorial_features/components/venice_2017/templates/video_completed.jade
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
> @kanaabe => [Venice] Completed video cover

- desktop/apps/auction/client/commercial_filter.js
I could also remove for staging, but it might be helpful for debugging there.
> @damassi => only load redux logger in dev and staging

- desktop/apps/about/routes.coffee
- desktop/apps/about/test/routes.coffee
Closes https://github.com/artsy/force/issues/1098
> @kanaabe => Redirect /about to /collect-art for mobile visitors

- desktop/analytics/editorial_features.js
- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/components/venice_2017/templates/carousel.jade
- desktop/apps/editorial_features/components/venice_2017/templates/mixins.jade
Adds events for 
- Share buttons
- Sign up for editorial
- Artist follow
Removes extra fields from video/partner link events
> @kanaabe => [Venice] Analytics updates

- mobile/models/featured_link.coffee
- mobile/test/models/featured_link.coffee
@sweir27
This fixes the image size issue in the file you pointed us to. Thanks! @acjay and I did this for auctions knowledge hour.
> default image size in mobile feature page

- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
Creates separate follow buttons for carousel and body, eliminates bugginess
> @kanaabe => [Venice] Follow buttons

- desktop/apps/galleries_institutions/routes.coffee
- desktop/apps/galleries_institutions/test/routes.coffee
This test was occasionally failing on Circle because of a race condition using `_.defer`. I refactored it to use native promises in the routes and tests to ensure async things resolve in the correct order without guessing.
> @anandaroop: Fixed intermittent failing galleries/institutions test

- desktop/apps/artwork/components/partner_stub/index.jade
This was just reported in Slack as semi urgent, so once green I will selfie-merge this...
> @anandaroop => Fix typo in "inquire via phone"

- desktop/analytics/editorial_features.js
- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/components/venice_2017/client/video.coffee
- desktop/apps/editorial_features/components/venice_2017/stylesheets/body.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/carousel.styl
- desktop/apps/editorial_features/components/venice_2017/templates/body.jade
- desktop/apps/editorial_features/components/venice_2017/templates/mixins.jade
- desktop/apps/editorial_features/index.coffee
- desktop/apps/editorial_features/routes.coffee
- desktop/apps/editorial_features/test/routes.coffee
I didn't have any problems with the proxy being outside of the route function so I think we're ok! Good catch 👍 
The rest of the stuff is analytics + copy + a small window resize bug.
> @craigspaeth => [Venice] Last analytics and follow button copy

- desktop/apps/editorial_features/routes.coffee
Fixes a "too many redirects" bug I just introduced.
> @kanaabe => [Venice] Fixes redirect issue

- desktop/apps/editorial_features/index.coffee
Removes the admin flag to make this baby come alive. We're still waiting on the video assets and external feedback, so 🙏  don't merge yet!
> @eessex => [Venice] Live (do not merge)

- desktop/assets/categories.coffee
Looks like me trying to get around importing the reaction-force node_module in a normal way is indeed breaking the page. Will revert that for now and think of an alternative approach.
> @craigspaeth - Go back to original version of tag page

- desktop/analytics/before_ready.js
- desktop/analytics/editorial_features.js
- desktop/apps/editorial_features/components/venice_2017/templates/head.jade
- desktop/apps/editorial_features/components/venice_2017/templates/index.jade
- desktop/apps/editorial_features/components/venice_2017/templates/video_description.jade
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
Adds dynamic metadata on each of the Venice pages and adds ST, Parsely tracking. Also a tiny fix for `context_label` in the play button.
> @craigspaeth => Metadata updates, ST, parsely tracking

- desktop/apps/editorial_features/components/venice_2017/templates/head.jade
- desktop/apps/editorial_features/components/venice_2017/templates/mixins.jade
- desktop/apps/editorial_features/components/venice_2017/templates/video_completed.jade
- desktop/apps/editorial_features/components/venice_2017/templates/video_description.jade
- desktop/apps/editorial_features/routes.coffee
- desktop/apps/editorial_features/test/routes.coffee
Some QA.. JSONLD needs to be present for Parsely tracking to actually work, also requests from Mark for social sharing.
> @craigspaeth => [Venice] jsonld, social sharing copy

- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/components/venice_2017/templates/body.jade
- desktop/apps/editorial_features/components/venice_2017/templates/video_description.jade
- desktop/apps/editorial_features/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
- desktop/apps/editorial_features/test/routes.coffee
Adds markdown rendering to descriptions in venice feature
> @craigspaeth => [Venice] Render markdown

- desktop/components/error_handler/index.jade
- desktop/components/error_handler/test/template.coffee
- lib/middleware/error_handler.coffee
- lib/setup.js
- test/lib/middleware/error_handler.coffee
cc @joeyAghion 
This moves the error handler into a proper middleware with tests...thanks for the nudge!
> @craigspaeth => Move error handling to middleware

- package.json
- yarn.lock
Updates the version to get the new name.
> @anipetrov => Update loyalty app for new analytics name for property

- desktop/components/email/stylesheets/editorial_signup.styl
Closes https://github.com/artsy/force/issues/1354
> @craigspaeth => Editorial CTA mobile bug

- desktop/apps/partnerships/templates/auction_sections.jade
- desktop/apps/partnerships/templates/common_section_mixins.jade
Solving half of https://github.com/artsy/force/issues/1406
> @cfinsness: Added Terms of Use to partnership forms

- desktop/apps/home/components/followed_artists/view.coffee
> @broskoski => Proper binding for homepage method

- desktop/apps/personalize/routes.coffee
- desktop/apps/personalize/test/routes.coffee
- package.json
- yarn.lock
Closing https://github.com/artsy/force/issues/1407 and https://github.com/artsy/force/issues/1390
> @broskoski: Upgraded Artsy Passport

- desktop/apps/tag/client.js
- package.json
- yarn.lock
Closes https://github.com/artsy/reaction-force/issues/153
Was actually bad logic that caused the code not to work on when the user is logged out, not a weird rewire thing!
> @alloy - Fix /tag page on logged out and upgrade reaction-force

- scripts/assets.sh
Looks like uglifify (introduced in https://github.com/artsy/force/pull/1402 ) is breaking code in production. I think @sweir27 ran into this as well, let's remove it for now!
> @joeyAghion - Remove uglifyify

- desktop/apps/partnerships/stylesheets/index.styl
- desktop/apps/partnerships/templates/auction_sections.jade
- desktop/apps/partnerships/templates/common_section_mixins.jade
Closes https://github.com/artsy/force/issues/1406
As we discussed, it would be better to allow the terms of use to be implemented in Marketo.
> @cfinsness: Removed TOS so we can make it in Marketo

- desktop/apps/artist/test/view_helpers.coffee
- desktop/apps/artist/view_helpers.coffee
- yarn.lock
> [Artist/JSONLD] Artwork may not have an image.

- desktop/apps/editorial_features/routes.coffee
- desktop/apps/editorial_features/test/routes.coffee
- Resolves pending Venice tests and adds assertion for JSONld
- Current user was removed from before block -- rendering is tested client-side
> @kanaabe => Venice route tests

- desktop/components/main_layout/templates/scripts.jade
Script written by consultants to help tracking in Marketo. The code generates field values pulled in by Marketo.
> Add Marketo Tracking Script

- desktop/analytics/bidding.js
- desktop/apps/artwork/components/auction/helpers.coffee
- desktop/apps/artwork/components/auction/templates/bid.jade
- desktop/apps/artwork/components/auction/test/view.coffee
Fixes a form redirect issue that creeped in when we revised language status language during PR review in https://github.com/artsy/force/pull/1417.
> @sweir27 => [BUGFIX] Bid button form action URL 

- desktop/analytics/account_creation.js
The current analytics code has some duplications and they should be consolidated. I also noticed that this file gets transpiled, so we can refactor further with ES6.
> Refactor analytics

- desktop/components/main_layout/templates/head.jade
Enable Asynchronous Munchkin Script for embedded Marketo Munchkin tracking.
> Enable Asynchronous Munchkin Script

- desktop/components/auction_reminders/index.coffee
Fixes: https://sentry.io/artsynet/force-staging/issues/276106542/
> @erikdstock => BUGFIX: Notification check fail is sale null

- desktop/models/article.coffee
- desktop/test/models/article.coffee
Adds vertical and tracking tags to article keywords when distributing to Parsley.
> @kanaabe => Verticals and tracking for Parsley 

- desktop/components/main_layout/templates/scripts.jade
Per our offline emails, this should do the trick.
> @nicholassewitz => Silence Marketo logs

- desktop/analytics/account_creation.js
- desktop/apps/artwork/components/inquire_via_phone/index.coffee
- desktop/apps/artwork/components/partner_stub/index.coffee
- desktop/components/auth_modal/templates/signup.jade
- desktop/components/auth_modal/view.coffee
This PR sets up analytics for the Inquire via Phone modal with the context value of `show phone number`.
> Track account creation on Inquire via Phone modal

- desktop/apps/artist/components/current_item/index.jade
- desktop/apps/artist/components/current_item/index.styl
- desktop/apps/artist/components/current_venice_feature/index.coffee
- desktop/apps/artist/routes.coffee
- desktop/apps/artist/test/components/current_venice_feature/index.coffee
- scripts/mocha.sh
- scripts/test.sh
Closes https://github.com/artsy/collector-experience/issues/242
> [Artist] Show Venice Biennale banner if a participant.

- mobile/apps/fair_organizer/client/fair_organizer.coffee
- mobile/apps/fair_organizer/routes.coffee
- mobile/apps/fair_organizer/test/templates/articles.coffee
- mobile/apps/fair_organizer/test/templates/template.coffee
- mobile/components/article_figure/mixin.jade
- mobile/test/helpers/fixtures.coffee
Closes https://github.com/artsy/force/issues/1389
Closes https://github.com/artsy/force/issues/1440
- Adds authors and contributing authors to article template
- Fetches articles with 'fair_ids[]' instead of author_id
- Replaces html rather than appending article template (stops repeating articles)
> @kanaabe => Mobile fair authors / article loading bugs

- desktop/components/article/templates/mixins.jade
- desktop/components/article/templates/super_article_sticky_header.jade
- desktop/components/article/test/templates.coffee
- desktop/models/article.coffee
Closes https://github.com/artsy/force/issues/1445
- Updates menu classes on superSubArticles when fullscreen header is present
- Prints partner logos and share info in fullscreen header if it is a superSubArticle
> SuperSubArticle header

- desktop/apps/consignments2/routes.js
- desktop/apps/consignments2/stylesheets/landing/desktop.styl
- desktop/apps/consignments2/templates/landing.jade
- desktop/apps/consignments2/test/fixture.json
Mostly just static page stuff + a new `fixture` structure for this JSON page (will have to update the file in the production s3 bucket as part of this being deployed).
Still have to look into the FAQ and make this view (and the submission flow) responsive.
A rough scrolling view (correct images still have to be uploaded):
> @craigspaeth => Consign2 landing page

- desktop/apps/artwork/components/auction/helpers.coffee
- desktop/apps/artwork/components/auction/index.styl
- desktop/apps/artwork/components/auction/query.coffee
- desktop/apps/artwork/components/auction/templates/bid.jade
- desktop/apps/artwork/components/auction/test/view.coffee
This PR adds a path I missed in https://github.com/artsy/force/pull/1417, `Registration Closed`.
> @erikdstock => [BUGFIX] Add 'Registration Closed' path

- desktop/apps/artwork/components/auction/helpers.coffee
- desktop/apps/artwork/components/auction/query.coffee
- desktop/apps/artwork/components/auction/test/view.coffee
Follow up to https://github.com/artsy/metaphysics/pull/643 and https://github.com/artsy/force/pull/1469.
> @sweir27 => Update artwork/auction with is_registration_closed

- desktop/analytics/editorial_features.js
Closes Sentry ticket: https://sentry.io/artsynet/force-staging/issues/279999851/
> @damassi => Fixes js in venice analytics

- desktop/apps/consignments2/stylesheets/landing/desktop.styl
> @sweir27 => fix styles

- desktop/apps/article/client/index.coffee
- desktop/apps/article/queries/partner.coffee
- desktop/apps/article/queries/sale.coffee
- desktop/apps/article/stylesheets/promoted_content.styl
- desktop/apps/article/test/client/index.coffee
Closes https://github.com/artsy/force/issues/1292
Uses metaphysics queries to get partner and sale info on promoted articles.
> @kanaabe => New fetches for promoted banner

- desktop/components/json_page/client/editor.coffee
#trivial 
Leftover from: https://github.com/artsy/force/pull/1483
> @mzikherman => Fix typo in comment

- desktop/apps/artists/templates/index.jade
- desktop/apps/style_guide/templates/navigation.jade
Per request from @anna.carey in #web (https://artsy.slack.com/archives/C0350895E/p14962536219627450) this PR updates the little 40k label to 50k on https://www.artsy.net/artists:
> @anyone => Update 40k artist label to 50k

- desktop/components/main_layout/stylesheets/body_with_header_split_test.styl
Closes: https://github.com/artsy/collector-experience/issues/313
Ensures search header changes are global, persist on scroll, and include hover state.
> @mzikherman: Search Header QA

- mobile/components/marketing_signup_modal/index.styl
> @yuki24: remove the gap beneath the text

- desktop/apps/partnerships/index.coffee
- desktop/apps/partnerships/templates/nav.jade
Re: https://artsy.slack.com/archives/C0350895E/p1496782562219985
> @kanaabe: Fixed the links in the nav of partnerships pages

- desktop/apps/consignments2/components/thank_you/index.styl
- desktop/apps/consignments2/components/upload_photo/index.js
- desktop/apps/consignments2/stylesheets/landing/desktop.styl
- desktop/apps/consignments2/stylesheets/landing/mobile.styl
#minor updates to the consignments flow to support safari mobile web.
> @sweir27 => update styles for safari mobile

- desktop/apps/gene/index.styl
- package.json
- yarn.lock
Closes https://github.com/artsy/force/issues/1519
> Gene page QA

- desktop/components/marketing_signup_modal/index.styl
Changing the color of the photo credit text #minor
> @xtina-starr: change photo credit text to #666

- desktop/components/main_layout/header/view.coffee
- desktop/components/split_test/running_tests.coffee
- lib/middleware/locals.coffee
Part of https://github.com/artsy/collector-experience/issues/251
I'm still waiting on approval from Ani regarding analytics, but I wanted to go head and submit a PR to ensure that I was launching the test correctly.
> @mzikherman: launch header search a/b test

- desktop/components/main_layout/stylesheets/body_with_header_split_test.styl
> @yuki24: [Header Search] restore notification bell/styles

- desktop/apps/artwork/components/additional_info/index.styl
Fixes https://github.com/artsy/force/issues/1210
Closes https://github.com/artsy/auctions/issues/498
> @sweir27 => [BUGFIX] Paragraph spacing in artwork description

- desktop/apps/auction/routes.js
- desktop/components/main_layout/templates/index.jade
- desktop/components/main_layout/templates/layout/index.jade
- desktop/components/react/main_layout/index.js
- desktop/components/react/main_layout/layout.jsx
- desktop/components/react/main_layout/test/layout_test.js
- desktop/components/react/main_layout/utils/get_layout.js
- desktop/components/react/main_layout/utils/make_layout.js
- desktop/components/react/main_layout/utils/make_template_component.js
- desktop/components/react/main_layout/utils/test/get_layout_test.js
- desktop/components/react/main_layout/utils/test/make_layout_test.js
- desktop/components/react/main_layout/utils/test/make_template_component_test.js
- desktop/components/react/utils/template_renderer.js
- desktop/components/react/utils/test/template_renderer_test.js
Addresses some additional post-merge feedback from https://github.com/artsy/force/pull/1537
> @acjay => Address feedback

- desktop/apps/auction/routes.js
For some reason this is leading to leaky sd info. Not sure why
> Revert React template rendering

- desktop/apps/auction/client/reducers.js
- desktop/apps/auction/components/sidebar/index.js
Now that [this PR](https://github.com/artsy/gravity/pull/11107) has been merged/deployed, we can go ahead and remove this hack!
I tested locally pointing to production gravity and it looks 👌 .
> @craigspaeth => revert hack for creative time

- desktop/apps/consignments2/client/steps_config.js
- desktop/apps/consignments2/stylesheets/index.styl
- desktop/apps/consignments2/test/components.js
This PR:
- updates the footer to stick to the bottom of the screen, but fall below the content
- removes the notification icon from the header in the desktop layout
- removes the search bar/button from the header in mobile layout
+1 to the idea that when we redo the nav we should do it in react!
> @craigspaeth => fixing header and footer to meet specs

- desktop/components/article/client/fullscreen.coffee
- desktop/components/article/stylesheets/content.styl
- desktop/components/article/stylesheets/fullscreen_article.styl
- desktop/components/article/stylesheets/super_article.styl
- desktop/components/article/templates/mixins.jade
- desktop/components/article/test/templates.coffee
Closes https://github.com/artsy/force/issues/1530
> @eessex => Fullscreen updates

- desktop/apps/consignments2/index.js
> @sweir27 => remove extra adminonly check

- desktop/apps/consignments2/components/step_marker/index.styl
- desktop/apps/consignments2/components/thank_you/index.styl
> @sweir27 => fix little styles on consign

- desktop/apps/editorial_features/test/routes.coffee
Been seeing this Venice route test fail often. Pend the test for now so we're not blocking people!
> @eessex => Stub Venice test

- desktop/apps/artwork/components/auction_artworks/query.coffee
Whoopsie, thank you for spotting!
> @damassi => Update metaphysics root query name to match recent update

- desktop/components/article/stylesheets/fullscreen_article.styl
https://github.com/artsy/force/issues/1585
> @eessex => Share padding/hover update for bombay

- desktop/components/commercial_filter/stylesheets/index.styl
Oops! Quick css fix for a breaking column.
> BUGFIX: Auction/:id filter width

- mobile/components/artwork_columns/artwork.jade
> @damassi => be forgiving when there is no image

- circle.yml
> Test git push -f sync

- circle.yml
> Undo -f sync fix

- mobile/apps/artist/routes.coffee
- mobile/apps/artist/test/routes.coffee
- mobile/components/artist_app_banner/index.coffee
Closes: https://github.com/artsy/collector-experience/issues/192
In order to get the Adjust tracking link rendering this empty page
to showing this instead
> Changes artist app banner link to direct app store

- desktop/apps/gallery_partnerships2/client/index.coffee
- desktop/apps/gallery_partnerships2/index.coffee
- desktop/apps/gallery_partnerships2/routes.coffee
- desktop/apps/gallery_partnerships2/stylesheets/grid_styles.styl
- desktop/apps/gallery_partnerships2/stylesheets/index.styl
- desktop/apps/gallery_partnerships2/stylesheets/mobile.styl
- desktop/apps/gallery_partnerships2/templates/index.jade
- desktop/apps/gallery_partnerships2/templates/meta.jade
- desktop/apps/gallery_partnerships2/test/fixture.json
- desktop/assets/gallery_partnerships2.coffee
- desktop/assets/gallery_partnerships2.styl
- desktop/components/auction_reminders/blacklist.coffee
- desktop/components/merry_go_round/view.coffee
- desktop/index.js
> New gallery partnerships app

- desktop/analytics/gallery_partnerships.js
- desktop/apps/gallery_partnerships2/client/index.coffee
- desktop/apps/gallery_partnerships2/stylesheets/index.styl
- desktop/apps/gallery_partnerships2/templates/index.jade
- desktop/apps/gallery_partnerships2/test/fixture.json
- desktop/assets/analytics.coffee
- desktop/components/merry_go_round/README.md
This work ensures the video autoplays inline on iOS, adds analytic events for the buttons on this page, makes the requested copy changes, and fixes some styling issues in IE and other browsers.
> Remaining items for gallery partnerships page

- desktop/apps/home/stylesheets/hero_units.styl
- desktop/apps/home/templates/index.jade
- desktop/components/split_test/running_tests.coffee
- lib/middleware/locals.coffee
> Deploy the no-hero layout and add the ability to switch to it using query parameter

- desktop/apps/home/stylesheets/hero_units.styl
- desktop/components/main_layout/stylesheets/body.styl
fixes https://github.com/artsy/collector-experience/issues/400#issuecomment-314283295
> eliminated unneccesary styles for the header search and restore the 'browse artworks' module

- desktop/components/main_layout/stylesheets/body.styl
- desktop/components/split_test/running_tests.coffee
- lib/middleware/locals.coffee
last items for https://github.com/artsy/collector-experience/issues/400
> Home page ab test

- desktop/apps/home/client/index.coffee
I forgot to add the setup for tracking the experiment.
> @craigspaeth: set up tracking experiment

- desktop/apps/article2/__tests__/routes.test.js
- desktop/apps/article2/queries/article.js
- desktop/apps/article2/routes.js
This lets us render article2 via a slug
Related to: https://github.com/artsy/positron/pull/1166
> @craigspaeth => Update article2 query for fetching with slugs

- desktop/apps/artwork/components/auction/index.styl
- desktop/apps/artwork/components/auction/templates/bid.jade
- desktop/apps/artwork/components/auction/test/view.coffee
(Missed a label from https://github.com/artsy/force/pull/1631)
> BUGFIX: Add missing info tip

- package.json
- yarn.lock
This fixes a style issue in Force.
> Upgrade to reaction 0.1.48 that ships with a style fix

- yarn.lock
I just followed [the suggestion here](https://github.com/yarnpkg/yarn/issues/1625#issuecomment-314615392). I'm not sure if it fixes the issue, but I think it's worth giving it a try.
> Fix deployment failure due to "An unexpected error occurred: "Invalid protocol: git:"."

- desktop/analytics/article_impressions.js
- desktop/analytics/articles.js
- desktop/components/article/stylesheets/content.styl
- desktop/components/article/stylesheets/image.styl
- desktop/components/article/templates/mixins.jade
- desktop/components/article/test/templates.coffee
- mobile/analytics/article_impressions.js
- Adds new paragraph spacing (related to draft updates)
- Removes classes for TOC
> @kanaabe => Text spacing updates, remove TOC

- desktop/apps/contact/test/fixture.json
- desktop/components/feedback_modal/templates/press.jade
- desktop/components/feedback_modal/tests/index.coffee
- mobile/apps/contact/fixtures/contact.json
- mobile/apps/contact/templates/template.jade
Requested on #help — simply updating `storyideas@` &rarr; `pitches@`
Also I fixed some malformed `mailto` urls I found in the mobile version of the page.
> @anyone: Update the email address for story ideas / pitches

- desktop/components/article/stylesheets/content.styl
Changes text spacing to .75em rather than 1em
> @kanaabe => bump text spacing down

- desktop/apps/gallery_partnerships2/client/index.coffee
- desktop/apps/gallery_partnerships2/stylesheets/index.styl
- desktop/apps/gallery_partnerships2/templates/index.jade
Addresses QA items for GP signup page mentioned in https://github.com/artsy/collector-experience/issues/94#issuecomment-315907166
> @yuki24: fix qa items

- desktop/apps/home/browse_categories.coffee
As discussed in Slack, the correct link is actually https://www.artsy.net/collect?medium=film-slash-video.
> @anyone: Fix broken link

- desktop/apps/auction2/components/artwork_browser/header/HeaderMobile.styl
- desktop/apps/auction2/components/layout/auction_info/AuctionInfoMobile.js
(Forgot a commit before merging; please move along :)
> Add missing commit

- desktop/apps/home/client/index.coffee
- desktop/apps/home/stylesheets/hero_units.styl
- desktop/apps/home/templates/index.jade
- desktop/components/split_test/running_tests.coffee
Closes: https://github.com/artsy/collector-experience/issues/421
It closes the home page personalization a/b test. This should be merge by **EOD July 25th**.
> @yuki24: closes home page a/b test

- .env.oss
- desktop/components/main_layout/templates/index.jade
- desktop/config.coffee
- lib/setup_sharify.js
Additionally, this url has been pushed into Heroku's `force-staging` and `force-production` config.
> @kanaabe => Move webfont url into WEBFONT_URL

- desktop/components/marketing_signup_modal/index.coffee
- desktop/components/marketing_signup_modal/index.styl
- desktop/config.coffee
- mobile/components/marketing_signup_modal/index.styl
- mobile/components/marketing_signup_modal/middleware.coffee
- mobile/config.coffee
Closes: https://github.com/artsy/collector-experience/issues/425
**note**: I need to the environment variables for both staging and production. I can do that shortly after this gets merged.
Desktop: 
Mobile:
> @mzikherman: update marketing signup modals for seattle art fair

- desktop/apps/auction2/components/artwork_browser/main/ArtworkDisplay.js
- desktop/apps/auction2/components/artwork_browser/main/ArtworkDisplay.styl
- desktop/apps/auction2/components/artwork_browser/main/LoadingSpinner.js
- desktop/apps/auction2/components/artwork_browser/main/LoadingSpinner.styl
- desktop/apps/auction2/components/artwork_browser/main/__tests__/ArtworkDisplay.test.js
- desktop/apps/auction2/components/layout/Banner.js
- desktop/apps/auction2/components/layout/Banner.styl
- desktop/apps/auction2/components/layout/auction_info/AuctionInfoDesktop.js
- desktop/apps/auction2/stylesheets/index.styl
- desktop/components/add_to_calendar/react.js
Lots of little bug fixes related to the main `<Banner />` component, but also added in a full-screen preloader mask for when toggling between different filter-states on mobile.
> @sweir27 => Auctions2 polish

- desktop/apps/auction2/components/artwork_browser/main/ArtworkDisplay.js
> @damassi => Cleanup

- desktop/apps/gallery_partnerships2/stylesheets/index.styl
This addresses https://github.com/artsy/collector-experience/issues/94#issuecomment-318091619.
> Address two QA items for the new gallery partnerships page

- desktop/analytics/articles.js
- desktop/components/main_layout/templates/index.jade
cc @anipetrov for naming
Closes https://github.com/artsy/publishing/issues/35
> @craigspaeth => Adds tracking to footer markdown links

- desktop/apps/gallery_partnerships2/client/index.coffee
- desktop/apps/gallery_partnerships2/stylesheets/index.styl
- desktop/apps/gallery_partnerships2/templates/index.jade
Addresses https://github.com/artsy/collector-experience/issues/94#issuecomment-318200869
> Another QA for the gallery partnerships page

- desktop/apps/gallery_partnerships2/templates/index.jade
This PR changes the language for the Terms of Use as requested [here](https://github.com/artsy/collector-experience/issues/94#issuecomment-318519188).
> Change the language to 'by submitting...'

- desktop/components/main_layout/templates/head.jade
- desktop/components/main_layout/templates/index.jade
This addresses the font issue we just discussed on slack.
> Fix the font-loading issue on responsive mobile pages

- desktop/apps/partnerships/client/router.coffee
- desktop/apps/partnerships/templates/mobile/section0.jade
- desktop/apps/partnerships/templates/mobile/section1.jade
- desktop/apps/partnerships/templates/mobile/section2.jade
- desktop/apps/partnerships/templates/mobile/section3.jade
- desktop/apps/partnerships/templates/mobile/section4.jade
- desktop/apps/partnerships/templates/mobile/section5.jade
This PR fixes an issue where the far-right "Apply" button does not jump down to bottom of page.
> @craigspaeth => [BUGFIX] Apply button does not jump to "Apply"

- desktop/apps/gallery_partnerships2/templates/index.jade
Address: https://github.com/artsy/collector-experience/issues/94#issuecomment-319407547
> @yuki24: update copy for gallery partnership plans

- package.json
- yarn.lock
> @damassi => Bump reaction to latest

- desktop/apps/gallery_partnerships2/templates/index.jade
This PR is the second half of this change https://github.com/artsy/force/pull/1687
> @xtina-starr: update gallery partnership plans for mobile

- desktop/apps/gallery_partnerships/templates/meta.jade
This PR updates the page title and meta description as requested here: https://github.com/artsy/collector-experience/issues/448
cc @NicoletteChao @christine-artsy @remyferber
> Update title tag and meta description to drive up click-through rate

- desktop/apps/auction/server.js
Forgot to remove `adminOnly` from routes
> [BUGFIX] Remove adminOnly routes

- desktop/apps/auction/client.js
- desktop/apps/home/client/hero_unit_view.coffee
- desktop/components/react/responsive_window/index.js
- desktop/components/react/utils/renderReactLayout.js
I had left off an init method which was prompting unrelated assets to load. Additionally fixes a hero banner issue.
> @sweir27 => Fix auction asset loading

- desktop/components/auction_reminders/blacklist.coffee
closes https://github.com/artsy/collector-experience/issues/463
> Gallery Partnerships marketing page shouldn't show auction pop ups

- desktop/analytics/bidding.js
Fixes https://github.com/artsy/auctions/issues/582
> @mikehrom => [BUGFIX] Update auction analytics code 

- desktop/apps/home/queries/initial.coffee
Related PR in Metaphysics: https://github.com/artsy/metaphysics/pull/710
> use same order as app for homepage artwork_modules

- desktop/apps/auction/routes.js
Follow up to https://github.com/artsy/metaphysics/pull/713: Don't fall over when a fetch fails.
> @sweir27 => Guard against Article fetch errors

- desktop/apps/article/templates/article.jade
- desktop/apps/article2/templates/article.jade
- desktop/components/main_layout/header/templates/large_screen_header.jade
- desktop/components/main_layout/header/templates/small_screen_header.jade
- desktop/components/main_layout/templates/head.jade
- desktop/components/main_layout/templates/index.jade
A few more minor tweaks for screen readers.
> @craigspaeth => More accessibility tweaks

- package.json
- yarn.lock
> @damassi => Try to upgrade uglify

- desktop/apps/auctions2/components/Layout.js
- desktop/apps/auctions2/components/auctions_block/AuctionsBlock.js
- desktop/apps/auctions2/components/auctions_block/AuctionsBlock.styl
- desktop/apps/auctions2/components/auctions_block/AuctionsItem.js
- Adds responsive/mobile layout to auction-blocks component
- Fixes some key/propTypes errors
> @sweir27 => Auction blocks responsive styles

- circle.yml
- package.json
Lets see if we can leverage some of the recent performance improvements in Node.
> @kanaabe => Bump Node to 8.4.0

- desktop/components/main_layout/templates/head.jade
While we figure out this CloudFront caching issue.
> Force wefont cache reset 

- desktop/components/fair_layout/templates/index.jade
Fix sub-layout icons in `/fair`.
> Update fair page

- desktop/apps/fair/test/templates.coffee
> Fix Fair Icons 

- desktop/apps/article2/components/App.js
- desktop/apps/article2/components/InfiniteScrollArticle.js
- desktop/apps/article2/components/__tests__/InfiniteScrollArticle.test.js
- desktop/apps/article2/queries/article.js
- desktop/apps/article2/queries/articles.js
- desktop/apps/article2/queries/relatedArticles.js
- package.json
- yarn.lock
Uses the latest reaction with some QA items + adds in the RelatedArticlesCanvas component.
> @craigspaeth => Bump reaction and use new RelatedArticles queries

- package.json
- yarn.lock
This includes @alloy's PR to fix rails with multiple fillwidths. ie, the Russia gene page.
>  @joeyAghion => Bump reaction version

- mobile/analytics/bidding.js
Fixes https://sentry.io/artsynet/force-staging/issues/351662274/
> @kanaabe => [BUGFIX] Update analytics code for older browsers

- desktop/components/article/templates/super_article_footer.jade
- desktop/components/article/templates/super_article_sticky_header.jade
- desktop/components/article/test/templates.coffee
- desktop/test/helpers/fixtures.coffee
Follow up to https://github.com/artsy/positron/pull/1293
Closes https://github.com/artsy/publishing/issues/51, https://github.com/artsy/positron/issues/1288
> @eessex => Super Article footer title support

- desktop/apps/article2/__tests__/routes.test.js
- desktop/apps/article2/components/App.js
- desktop/apps/article2/components/InfiniteScrollArticle.js
- desktop/apps/article2/components/__tests__/InfiniteScrollArticle.test.js
- desktop/apps/article2/index.js
- desktop/apps/article2/queries/articleBody.js
- desktop/apps/article2/routes.js
- desktop/test/helpers/fixtures.coffee
- package.json
- yarn.lock
- Checks if user is signed up for editorial emails 
- Adds a signup route that sends a welcome email
> @eessex => Include Email Signup and Read More from Reaction

- desktop/apps/artist/client/views/cv.coffee
Fixes missing CV's. Artists have CV's, but can be lacking some other metadata.
> @mzikherman => Dont hide CV section just b/c theres no hometown/location data

- desktop/apps/artist/client/views/cv.coffee
- yarn.lock
> Deploy a lil' CV update

- desktop/apps/article2/components/App.js
- desktop/apps/article2/components/EditButton.js
- desktop/apps/article2/components/__tests__/EditButton.test.js
- desktop/apps/article2/index.js
- desktop/apps/article2/queries/channelMember.js
- desktop/config.coffee
Checks a logged-in user's channel membership to determine if we should render an Edit button client-side.
> @craigspaeth => Edit button on article2

- desktop/apps/auction/components/layout/active_bids/ActiveBidItem.styl
Fixes https://github.com/artsy/auctions/issues/660
> @sweir27 => [Bugfix]: Increase margin between active bid items

- package.json
- yarn.lock
https://artsy.slack.com/archives/C2TQ4PT8R/p1506968028000195
> [package] Update Reaction to 0.6.3 with gene artworks fix.

- desktop/apps/article2/__tests__/routes.test.js
- desktop/apps/article2/components/App.js
- desktop/apps/article2/components/__tests__/App.test.js
- desktop/apps/article2/components/__tests__/EditButton.test.js
- desktop/apps/article2/components/__tests__/InfiniteScrollArticle.test.js
- desktop/apps/article2/queries/articleBody.js
- desktop/apps/article2/queries/superArticle.js
- desktop/apps/article2/routes.js
- desktop/assets/article2.styl
- desktop/components/article/client/super_article.coffee
- desktop/components/article/templates/super_article_sticky_header.jade
- package.json
- yarn.lock
Bumps reaction and adds super article support
> @eessex => Super Article integration

- desktop/apps/marketing_signup_modals/stylesheets/index.styl
- desktop/apps/marketing_signup_modals/templates/index.jade
- desktop/apps/marketing_signup_modals/test/fixture.json
- desktop/components/marketing_signup_modal/index.coffee
- desktop/components/marketing_signup_modal/index.jade
This adds some of the remaining items for the marketing modal admin ui. Specifically it implements using the text color and delay duration.
> @craigspaeth: [Marketing Modals] adds the ability to configure hex color and duration

- desktop/apps/article2/__tests__/routes.test.js
- desktop/apps/article2/components/InfiniteScrollArticle.js
- desktop/apps/article2/components/__tests__/App.test.js
- desktop/apps/article2/components/__tests__/EditButton.test.js
- desktop/apps/article2/components/__tests__/InfiniteScrollArticle.test.js
- package.json
- scripts/mocha.sh
- yarn.lock
Pushes articles to `window.history` and updates the tab title (document.title) in the browser as you scroll along.
> [Publishing] @craigspaeth => Article2 Infinite scroll browser navigation

- desktop/apps/categories3/components/App.js
- desktop/apps/categories3/components/FeaturedGene.js
- desktop/apps/categories3/components/FeaturedGenes.js
- desktop/apps/categories3/components/Gene.js
- desktop/apps/categories3/components/GeneFamily.js
- desktop/apps/categories3/components/GeneFamilyNav.js
- desktop/apps/categories3/components/TAGPContent.js
- desktop/apps/categories3/components/__tests__/GeneFamily.test.js
- desktop/apps/categories3/queries/featuredGenes.js
- desktop/apps/categories3/queries/geneFamilies.js
- desktop/apps/categories3/utils.js
QA laundry list for the new TAGP page at /categories3
> Categories3 QA 

- desktop/apps/article2/components/App.js
- desktop/apps/article2/queries/superArticle.js
Closes https://github.com/artsy/publishing/issues/82
> @eessex => Fixes white spacing on Super Article header 

- desktop/apps/article2/components/App.js
- desktop/apps/article2/components/InfiniteScrollArticle.js
- desktop/apps/article2/components/__tests__/App.test.js
- desktop/apps/article2/components/__tests__/InfiniteScrollArticle.test.js
- desktop/apps/article2/queries/article.js
- desktop/apps/article2/queries/articles.js
- desktop/apps/article2/queries/display.js
- desktop/apps/article2/routes.js
- package.json
- yarn.lock
Closes https://github.com/artsy/publishing/issues/92
Pending https://github.com/artsy/positron/pull/1334 deploy
> @craigspaeth => Update reaction and make Display fetch

- desktop/apps/articles/routes.coffee
- desktop/apps/articles/test/routes.coffee
Closes https://github.com/artsy/publishing/issues/89
> @eessex => Fixes Team Channel landing page query param bug

- CONTRIBUTING.md
- desktop/apps/article2/components/App.js
- desktop/apps/article2/components/EditButton.js
- desktop/apps/article2/components/InfiniteScrollArticle.js
- desktop/apps/article2/components/__tests__/App.test.js
- desktop/apps/article2/components/__tests__/EditButton.test.js
- desktop/apps/article2/components/__tests__/InfiniteScrollArticle.test.js
- desktop/apps/article2/queries/articles.js
Updates https://github.com/artsy/publishing/issues/91 along with some light cleanup.
> @eessex => [Bugfix] Missing sidebar in <Article />

- desktop/apps/categories/client.js
> @craigspaeth => Wrap client.js in fn

- desktop/apps/gene/client.js
- desktop/lib/global_client_setup.coffee
Thanks for this suggestion! (cc @joeyAghion)
> @craigspaeth => set request id header in global ajax settings for client-side backbone fetches

- package.json
Per #front-end discussion. (Also, don't think we need to force NPM version either.)
> @yuki24 => Unlock npm and yarn versions

- desktop/analytics/impressions.js
- mobile/analytics/impressions.js
- mobile/assets/mobile_analytics.coffee
😞  until we find a good way to send ids instead of slugs. [Related](https://github.com/artsy/fulcrum/pull/724)
> @wrgoldstein: Revert Fixed impression tracking

- package.json
- yarn.lock
> @kanaabe => Bump reaction version

- package.json
> Revert "@yuki24 => Unlock npm and yarn versions"

- desktop/apps/article2/queries/article.js
- desktop/apps/article2/routes.js
- desktop/lib/positronql.coffee
Thx for noticing this!
Closes https://github.com/artsy/publishing/issues/111
> @eessex => Be able to view article2 drafts

- desktop/apps/article2/client/__tests__/classic.test.js
- desktop/apps/article2/client/article.js
- desktop/apps/article2/client/classic.js
- desktop/apps/article2/stylesheets/classic.styl
- desktop/assets/article2.coffee
- desktop/assets/article2.styl
Adds client file for "classic" views -- not sure how I missed this before but we are missing client-side JS for all non-editorial channels atm.
> @damassi => Client-side backbone views for "classic" layouts

- desktop/apps/article2/components/App.js
- desktop/apps/article2/components/InfiniteScrollArticle.js
- desktop/apps/article2/routes.js
- package.json
- yarn.lock
This is to support better SSR rendering, so that layouts don't shift once the client mounts.
> @kanaabe => Pass isMobile over to Reaction

- desktop/apps/article2/components/InfiniteScrollArticle.js
- yarn.lock
Addresses issues located here https://github.com/artsy/publishing/issues/113
> @damassi => Update margins

- desktop/apps/article2/components/InfiniteScrollArticle.js
> @damassi => Update infinite scroll offset

- package.json
> @damassi => Bump Reaction

- desktop/apps/article2/components/App.js
- desktop/apps/article2/components/InfiniteScrollArticle.js
- desktop/apps/article2/components/__tests__/App.test.js
- desktop/apps/article2/components/__tests__/InfiniteScrollArticle.test.js
Only super/sub-super articles have static footers.
> @eessex => Infinite scroll on features

- desktop/apps/article/index.coffee
- desktop/apps/article/routes.coffee
- desktop/apps/article2/__tests__/routes.test.js
- desktop/apps/article2/components/App.js
- desktop/apps/article2/index.js
- desktop/apps/article2/routes.js
- package.json
- yarn.lock
Makes use of express `next` to move admins to the article2 subapp and render new layouts for them. 
Holding since we're not quite ready on the communication/backfill side yet to merge this. Should be end of this week!
> @craigspaeth => Release article2 to admin

- desktop/apps/article/routes.coffee
- desktop/apps/article2/__tests__/routes.test.js
- desktop/apps/article2/index.js
- desktop/apps/article2/routes.js
- desktop/assets/article2.coffee
- desktop/components/auction_reminders/blacklist.coffee
Left out one ref -- this fixes the asset file for initializing client-side js
> @kanaabe => Fixes client-side admin article2

- desktop/apps/miami_fair_week/components/MiamiFairWeekPage.js
QA fixes to https://github.com/artsy/collector-experience/issues/609#issuecomment-338811236
> Style updates for miami fair week

- desktop/apps/article2/__tests__/routes.test.js
- desktop/apps/article2/routes.js
- desktop/apps/article2/stylesheets/classic.styl
Adds support for articles that are ghosted -- this is a simple existy check on `channels` which not all articles are required to have.
> @eessex => Ghost article support

- desktop/apps/miami_fair_week/components/MiamiFairWeekPage.js
This updates the styles for the introduction on https://staging.artsy.net/miami-fair-week:
> Update the styles for intro text in the Miami Fair Week

- desktop/apps/miami_fair_week/index.js
Yuki can't type 'edit' properly
> Yuki can't type 'edit' properly

- desktop/apps/article2/components/App.js
- desktop/apps/article2/components/FollowButton.js
- desktop/apps/article2/components/InfiniteScrollArticle.js
- desktop/apps/article2/components/__tests__/App.test.js
- desktop/apps/article2/components/__tests__/InfiniteScrollArticle.test.js
Not super excited about using jquery, but it seemed the only way to get this working with our text components. 
- Sets up user's followed artists in App and InfiniteScrollArticle
- Sets up FollowButtons when component mounts and sync's with users follows
> @kanaabe => Artist follows

- package.json
- yarn.lock
> @eessex => Bump reaction

- desktop/apps/article2/components/InfiniteScrollArticle.js
> @damassi => Fix spacing

- package.json
- yarn.lock
> @kanaabe => Bump reaction

- package.json
Bumps reaction for latest publishing release. cc @kanaabe
> @damassi => Bump reaction 0.10.2

- desktop/apps/article2/queries/articleBody.js
- package.json
- yarn.lock
Time to use the freshly backfilled authors!
> @kanaabe => Update query and bump reaction

- desktop/components/auction_reminders/blacklist.coffee
forgot to update this path when doing https://github.com/artsy/force/pull/1899.
> Disable auction reminders on the Artsy inMiami page

- desktop/apps/artsy_in_miami/index.js
Merge this PR once the page is ready.
> Roll out the marketing page for the Miami Art Week

- desktop/assets/analytics.coffee
Addresses https://waffle.io/artsy/publishing/cards/59f94a1dbe2199001a384bbc
> @craigspaeth => Be defensive about window.PARSELY

- package.json
> Bump reaction 0.11.3

- package.json
- yarn.lock
> @damassi => Bump reaction 0.11.4

- desktop/apps/article/index.js
> @damassi => Remove admin only

- package.json
- yarn.lock
Adds header and breakpoint fixes
> @craigspaeth => Update reaction version

- desktop/apps/artwork/components/commercial/index.styl
closes https://github.com/artsy/force/issues/1910
Now looks like:
> @damassi => fix display of multiple consignable artists

- package.json
- yarn.lock
> Bump reaction 0.11.7

- package.json
- yarn.lock
> @damassi => Bump reaction 0.11.8

- package.json
- yarn.lock
> @damassi => Bump reaction 0.11.9

- package.json
- yarn.lock
> Bump reaction 0.11.11

- desktop/components/main_layout/templates/react_index.jade
Adds the json-ld template to the page if the value is passed along.
> @damassi => Adds json-ld to react_index.jade

- desktop/apps/article/components/App.js
- desktop/apps/article/queries/display.js
Follow up to https://github.com/artsy/positron/pull/1404
> @kanaabe => Update query to support cover_image_url

- desktop/apps/article/components/App.js
- package.json
- yarn.lock
Related: https://github.com/artsy/reaction/pull/369
> @kanaabe => Patch cover image url

- package.json
- yarn.lock
> Bump reaction 0.11.13

- package.json
- yarn.lock
Pulls in: https://github.com/artsy/reaction/pull/372
> @damassi => Bump reaction 0.11.14

- package.json
- yarn.lock
Bump Reaction 0.12.0 - cc @craigspaeth
> Bump Reaction 0.12.0

- package.json
- yarn.lock
Related to module not found error on Gucci microsite
> @kanaabe => Use same flexboxgrid as reaction

- desktop/apps/editorial_features/components/gucci/templates/__tests__/head.test.js
- desktop/apps/editorial_features/components/gucci/templates/head.jade
- desktop/apps/editorial_features/components/gucci/templates/index.jade
- desktop/apps/editorial_features/routes.coffee
Addresses https://waffle.io/artsy/publishing/cards/5a032dec1b23d70089e701fd
> @eessex => Gucci metadata

- circle.yml
Per offline convo with @craigspaeth, temporarily add `--force` to push to staging
> @damassi => Fix staging

- circle.yml
- package.json
- yarn.lock
Bumps reaction with latest
- https://github.com/artsy/reaction/pull/378
- https://github.com/artsy/reaction/pull/377
> Bump reaction-0.12.1

- circle.yml
@craigspaeth - not sure whats up... seems to need `--force` even though it (should) be in sync.
> Fix staging (again)

- desktop/apps/editorial_features/components/gucci/client.js
- desktop/apps/editorial_features/components/gucci/components/App.jsx
- desktop/apps/editorial_features/components/gucci/components/nav/__tests__/header.test.js
- desktop/apps/editorial_features/components/gucci/components/nav/fixed_header.jsx
- desktop/apps/editorial_features/components/gucci/components/nav/header.jsx
- desktop/apps/editorial_features/components/gucci/components/nav/sections_nav.jsx
- desktop/apps/editorial_features/components/gucci/components/section/section.jsx
- desktop/apps/editorial_features/components/gucci/components/section/section_text.jsx
- desktop/apps/editorial_features/components/gucci/components/series/series_footer.jsx
- desktop/apps/editorial_features/components/gucci/components/series/series_header.jsx
- Adds isMobile to App component, and resets isMobile if window size changes
- Uses isMobile (over `display: none`) for elements that are rendered based on screen size
- Adds hamburger menu icon to Header
> @kanaabe => Gucci mobile nav

- desktop/apps/editorial_features/components/gucci/components/nav/fixed_header.jsx
- desktop/apps/editorial_features/components/gucci/components/nav/header.jsx
- desktop/apps/editorial_features/components/gucci/components/nav/sections_nav.jsx
- desktop/apps/editorial_features/components/gucci/components/partner/partner_block.jsx
- desktop/apps/editorial_features/components/gucci/components/section/section_text.jsx
- desktop/apps/editorial_features/components/gucci/components/section/section_video.jsx
- desktop/apps/editorial_features/components/gucci/templates/head.jade
- Animates menu dropdown
- Adds link to unica font 
- Adds video name as trackingData to Video component
- Removes debounce on scroll because it makes animation buggy
- Removes manually set font weights
> @kanaabe => Gucci QA

- desktop/apps/article/queries/relatedArticles.js
Related to https://github.com/artsy/publishing/issues/218
> @kanaabe => published_at date in relatedArticlesCanvas query

- desktop/apps/article/queries/relatedArticles.js
- desktop/components/article/stylesheets/super_article.styl
Adds padding to superarticle footer, closes https://github.com/artsy/publishing/issues/191
> @kanaabe => [Minor] Superarticle margins

- desktop/apps/editorial_features/components/gucci/components/App.jsx
- desktop/apps/editorial_features/components/gucci/components/series/series_footer.jsx
- package.json
- yarn.lock
> @eessex => Bump reaction, minor Gucci QA

- desktop/apps/editorial_features/components/gucci/components/section/section_video.jsx
> [Trivial] Fix font wieght

- desktop/analytics/editorial_features.js
- desktop/apps/editorial_features/components/gucci/components/nav/header.jsx
- desktop/apps/editorial_features/components/gucci/components/section/section_text.jsx
- desktop/apps/editorial_features/components/gucci/components/section/section_video.jsx
- package.json
- yarn.lock
- Updates tracking args
- Bumps Reaction
- Adds custom size to Reaction PartnerInline imgs
> Gucci Final QA

- desktop/apps/editorial_features/index.coffee
Removes admin flags to publish Gucci project to public
> @kanaabe => [HOLD] Publish Gucci

- desktop/apps/editorial_features/components/gucci/templates/index.jade
- desktop/apps/editorial_features/routes.coffee
- desktop/apps/editorial_features/test/routes.coffee
- desktop/components/main_layout/templates/scripts.jade
Includes json-ld on the page and allows Parsely to start tracking the page
> @eessex => Adds json-ld and Parsely to Gucci feature

- desktop/apps/editorial_features/routes.coffee
- desktop/components/main_layout/templates/scripts.jade
> @kanaabe => Includes sailthru and fixes regex #minor

- desktop/apps/home/stylesheets/hero_units.styl
> Fix button text color in the hero units on the top page

- desktop/apps/article/templates/classic_meta.jade
- desktop/apps/article/templates/meta.jade
- desktop/apps/editorial_features/components/eoy/templates/head.jade
- desktop/apps/editorial_features/components/gucci/templates/head.jade
- desktop/apps/editorial_features/components/venice_2017/templates/head.jade
Related Convo: https://artsy.slack.com/archives/C04GGGDCM/p1510761504000906
> @craigspaeth => Updates Sailthru image sizes

- package.json
- yarn.lock
Minor publishing updates-
- Video cover image cursor is pointer
- Drop-caps on feature article are css only
- Basic header titles have max-width
> Bump Reaction

- desktop/apps/auctions/routes.coffee
- desktop/apps/auctions/test/routes.coffee
Increase the (unfortunate, but soon to be fixed) hard limit on the number returned.
> @damassi => [Auctions] Bump /auctions fetch from 30 to 40

- desktop/apps/article/components/App.js
- desktop/apps/article/components/__tests__/App.test.js
- desktop/apps/article/routes.js
- desktop/assets/article.styl
- desktop/components/email/client/editorial_signup.coffee
- desktop/components/email/templates/editorial_cta_banner.jade
- desktop/components/email/test/editorial_signup.coffee
Addresses: https://github.com/artsy/publishing/issues/261
> @eessex => Adds email modal back to editorial articles

- desktop/apps/article/__tests__/routes.test.js
- desktop/apps/rss/templates/article.jade
- desktop/apps/rss/test/news.coffee
- desktop/models/article.coffee
- desktop/test/models/article.coffee
- Updates RSS to include media
- Only allow `standard` and `feature` layouts for Google AMP
> @eessex => Handle AMP and RSS feeds for new layouts

- package.json
- yarn.lock
This hopefully fixes the deploys!
> @mzikherman => Use proper released version of Reaction

- desktop/apps/article/queries/articleBody.js
Looks for series header and fetches url for bg image
> @kanaabe => Series queries for bg url

- desktop/apps/article/components/App.js
- desktop/apps/article/queries/articleBody.js
- package.json
- yarn.lock
Queries the `sponsor` and `seriesArticle`.
> @eessex => Add sponsor + series to query + bump reaction

- desktop/apps/gene/aggregations.coffee
- desktop/apps/gene/client.js
- desktop/apps/gene/routes.coffee
- desktop/apps/gene/templates/filter.jade
- desktop/apps/gene/test/routes.coffee
- desktop/apps/tag/aggregations.coffee
- desktop/apps/tag/client.js
- desktop/apps/tag/index.styl
- desktop/apps/tag/routes.coffee
- desktop/apps/tag/test/routes.coffee
Removes the now redundant server-side fetches (and a bit of cleanup).
> @alloy => Remove unneeded server-side fetches, and remove `assign`

- desktop/apps/article/queries/articleBody.js
- package.json
> @kanaabe => Bump reaction again + adds in the title and slug for SeriesArticle

- yarn.lock
Oops! Forgot to update the lockfile for Reaction bump. 😞
> @kanaabe => Update lock file

- package.json
- yarn.lock
Brings in changes for increasing max-widths on SeriesTitle logos and fixes clicking on Nav ☠️
> @kanaabe => One more Reaction bump for tonight

- package.json
- yarn.lock
> Bump reaction to 0.16.12

- package.json
- yarn.lock
Pulls in latest IE fixes for BMW
> Bump reaction to 0.17.2

- desktop/apps/artwork/components/artists/helpers.coffee
- desktop/apps/artwork/components/artists/index.coffee
- desktop/apps/artwork/components/artists/index.jade
- desktop/apps/artwork/components/artists/market_insights.js
- desktop/apps/artwork/components/artists/query.coffee
- desktop/apps/artwork/components/artists/templates/biography.jade
- desktop/apps/artwork/components/meta/index.jade
- desktop/apps/artwork/routes.coffee
- desktop/assets/artists_artworks.coffee
- package.json
- yarn.lock
Looks like (zoomed out, pointing to staging):
I need to actually publish Reaction `master`, and import that here, but otherwise basically good to go!
> @alloy => Market Insights on Artwork page for Admins

- desktop/apps/article/__tests__/routes.test.js
- desktop/apps/article/routes.js
- desktop/components/email/stylesheets/editorial_signup.styl
- desktop/components/email/templates/editorial_cta_banner.jade
Addresses https://github.com/artsy/publishing/issues/273
> @eessex => Email Modal Updates

- package.json
- yarn.lock
> @mzikherman => Bump reaction for market insights QA

- desktop/apps/artwork/routes.coffee
- package.json
- yarn.lock
> @mzikherman => Some auction related market insights fixes + bump Reaction

- package.json
- yarn.lock
> @mzikherman => Bump reaction for a new help tooltip

- desktop/components/partner_buttons/show_buttons.coffee
Fixes https://github.com/artsy/collector-experience/issues/350 and https://github.com/artsy/collector-experience/issues/349
Pretty simple, it just wasn't correctly handling the case of the user being logged out.
> @yuki24 => Fix following profile on fair and shows feed for logged out users

- desktop/apps/show/client/index.coffee
- desktop/apps/show/components/follow_profile/index.coffee
Fixes https://github.com/artsy/collector-experience/issues/348
> @yuki24 => Fix profile follows on the show page

- package.json
- yarn.lock
> @mzikherman => Reaction bump for gene/tag QA issues

- package.json
- yarn.lock
> @mzikherman => one more lil reaction bump for always showing 'for sale' toggle

- desktop/components/zig_zag_banner/index.styl
- package.json
- yarn.lock
> @mzikherman => Bump reaction, last bits of market insights QA

- desktop/components/bordered_pulldown/index.styl
- desktop/components/bordered_pulldown/mixin.jade
- desktop/components/commercial_filter/filters/keyword/keyword_filter_view.coffee
- desktop/components/commercial_filter/views/sort/index.jade
- desktop/components/commercial_filter/views/sort/sort_view.coffee
cc @cavvia last update to disable sort.
> @mzikherman => Disable sorting when a keyword search is applied

- package.json
- yarn.lock
Changes since 18.8.8 include...
- Draft class updates (not visible in Force)
- New Auctions RailSlider (@damassi this is also not visible, right?)
- Updated artwork captions
> @mzikherman => Upgrade Reaction to 0.18.11

- desktop/analytics/collect.js
- desktop/components/commercial_filter/filters/keyword/keyword_filter_view.coffee
This might be sufficient for tracking keywords? It just uses Segment/is analogous to the main nav bar search term tracking.
> @cavvia => Track keywords searched on /collect

- package.json
Try 1: https://github.com/artsy/force/pull/2099
Try 2: Update the node version in package.json
> Clear Heroku node_modules cache try 2 

- package.json
> Revert "Clear Heroku node_modules cache try 2 "

- scripts/deploy.sh
Reverts previous test, attempts: https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache
> Heroku node_modules cache bust attempt 4

- desktop/components/main_layout/templates/scripts.jade
- desktop/lib/global_client_setup.coffee
- lib/global_modules.js
- mobile/components/layout/bootstrap.coffee
- mobile/components/layout/templates/scaffold.jade
- webpack.config.js
Fixes sequence of https://sentry.io/artsynet/force-staging/issues/439401207/activity/ errors related to missing global jQuery variables. 
Thanks @starsirius for the approach 👍
> @kanaabe => [Webpack] Consolidate global module dependencies 

- desktop/apps/articles/client/magazine.coffee
- desktop/components/email/client/editorial_signup.coffee
- Update copy
- Ensure /magazine gets the split_test tracking call
> @yuki24 => [QA] Editorial Signup AB

- desktop/apps/auction/components/artwork_browser/main/artwork/MasonryArtwork.js
- desktop/apps/auction/components/artwork_browser/main/artwork/__tests__/MasonryArtwork.test.js
- desktop/apps/auction/components/layout/auction_info/AuctionInfo.styl
Quick CSS follow-up to https://github.com/artsy/force/pull/2072
(Popup cover wasn't 100% width / height)
> @damassi => CSS fix 

- package.json
- yarn.lock
Bumping up the version of reaction to apply the latest UI tweaks for onboarding.
> bump up the version of reaction

- package.json
- yarn.lock
> @damassi => [Toolchain] Bump express-reloadable 1.2.2

- desktop/apps/auction/components/layout/Banner.js
- desktop/apps/auction/components/layout/__tests__/Banner.test.js
This PR fixes the bug identified here: https://github.com/artsy/force/pull/2123/files#r165689201
> @damassi => Fix auction banner when live sale hasn't started

- package.json
- yarn.lock
This includes UI fixes for the new onboarding flow.
> Upgrade to latest reaction 0.18.18

- desktop/apps/auction/components/artwork_browser/__tests__/ArtworkBrowser.test.js
- desktop/apps/auction/components/artwork_browser/sidebar/RangeSlider.js
- desktop/apps/auction/components/artwork_browser/sidebar/__tests__/Sidebar.test.js
Fixes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=BNS&modal=detail&selectedIssue=BNS-11
> @sweir27 => [Bugfix] Remove lot mention 

- package.json
- yarn.lock
We can probably hold on merging this until we bump reaction and include that in this PR --
> @damassi => Upgrade styled-components to 3.1.5

- desktop/apps/artist/routes.coffee
- desktop/apps/personalize/components/App.js
- desktop/apps/personalize/routes.js
- desktop/components/artist_page_cta/view.coffee
This is a work in progress that addresses [AR-83](https://artsyproduct.atlassian.net/browse/AR-83) and sends users that from google down the full onboarding flow. This takes care of the new onboarding flow but the old flow is not implemented yet.
> @yuki24: ensure artist cta sends users to onboarding and redirect back to artist page

- desktop/components/artist_page_cta/view.coffee
This addresses @mzikherman [comment](https://github.com/artsy/force/pull/2130#discussion_r166418648) and uses the correct query param.
> @kana: fix redirectTo param in artist cta view

- package.json
- yarn.lock
This includes the PRs below:
* https://github.com/artsy/reaction/pull/510
* https://github.com/artsy/reaction/pull/511
* https://github.com/artsy/reaction/pull/512
> Upgrade to the latest reaction

- desktop/apps/personalize/components/App.js
- desktop/apps/personalize/index.coffee
- desktop/apps/personalize/routes.js
- package.json
- yarn.lock
~~Need to wait on https://github.com/artsy/reaction/pull/511~~
> @xtina-starr => [Onboarding] Passes forceStep to Wizard from slug

- desktop/apps/armory_week/components/ArmoryWeekPage.js
- desktop/components/auction_reminders/blacklist.coffee
finishes https://artsyproduct.atlassian.net/browse/AR-101 and https://artsyproduct.atlassian.net/browse/AR-108.
> Replace hard coded url in the armory show page and hide auction reminders

- desktop/apps/armory_week/components/Cta.js
This is just a follow-up PR on https://github.com/artsy/force/pull/2150/files#r167294119
> Replace a hard-coded color value

- desktop/apps/armory_week/components/BannerPopUp.js
- desktop/apps/armory_week/index.js
finishes https://artsyproduct.atlassian.net/browse/AR-124
* The modal doesn't show up automatically because you'll have to be logged in as an admin to see the page but the modal only shows up automatically only when the user is **not** logged in
* We'll have to edit and update two different JSON pages, but given that this is the fastest way that gets us to where we want to get, I think that's a fair trade-off
> Re-use the marketing modal on the armory week marketing page

- desktop/apps/artwork/client/index.coffee
- desktop/apps/artwork/components/artists/helpers.coffee
- desktop/apps/artwork/components/artists/index.jade
- desktop/apps/artwork/components/artists/templates/biography.jade
- desktop/apps/artwork/components/meta/index.jade
- desktop/assets/artists_artworks.coffee
- desktop/components/split_test/running_tests.coffee
Apparently the test finished relatively flat (50/50) in its results...which is a win for us! Score! We'll take it.
> @cavvia => Resolve AB test for market insights and roll it out to everbody

- package.json
- yarn.lock
This includes fixes for the UI elements in the new onboarding.
> Upgrade to latest reaction

- desktop/apps/personalize/meta.jade
- desktop/apps/personalize/routes.js
This just adds a metadata title to the new onboarding page. I followed the pattern in the [stitch docs](https://github.com/artsy/stitch#expressjs-and-pug).
> @yuki24: adds metadata title to new onboarding

- desktop/analytics/collect.js
- desktop/apps/collect/client.coffee
- desktop/components/commercial_filter/views/pillbox/index.styl
- desktop/components/main_layout/templates/index.jade
- desktop/components/split_test/running_tests.coffee
cc @cavvia who is OOO
This removes the lab feature guard and launches the AB test, w/ a couple minor analytics updates.
> @joeyAghion => Launch keyword search on /collect AB test

- package.json
Lets see if this busts the cache; we can push another removing it after
> Force new antigravity version

- desktop/apps/article/components/InfiniteScrollArticle.js
- desktop/apps/article/queries/articles.js
Missed a few imports when un-`default`-ing from https://github.com/artsy/force/pull/2158/files#diff-aeefbe99d0daf781758ca007af213729 :)
> @damassi => Fix infinite scroll on articles

- desktop/apps/armory_week/components/ArmoryWeekPage.js
> Fix margins on mobile armory week page

- desktop/apps/personalize/client/onboarding.js
- desktop/apps/personalize/components/RoutesWithProgressBar.js
- package.json
- test.config.js
- webpack.config.js
- yarn.lock
Reverts artsy/force#2178
This has caused CI builds to fail. I'm sending this PR in case we can't wait for me to fix the build failure.
> Revert "Upgrade to reaction 0.23.4"

- scripts/deploy.sh
> @damassi => Fix deploy asset path

- .vscode/tasks.json
- package.json
- src/desktop/apps/artwork/components/auction/view.coffee
- src/desktop/components/auth_modal/templates/signup.jade
- src/desktop/components/auth_modal/view.coffee
- src/desktop/models/logged_out_user.coffee
- src/desktop/test/models/logged_out_user.coffee
- yarn.lock
related to https://github.com/artsy/artsy-passport/pull/118
This PR adds a signupIntent option to AuthModalView which gets passed through to social oauth links or the LoggedOutUser object for artsy-passport.
> @mzikherman => handle signupIntent for AuthModalView

- src/desktop/components/auth_modal/view.coffee
Nice sleuthing!
Basically, when we updated the modal redirect flow to work on signup/register, we didn't notice a bug (which previously would have been hard to catch since the redirects weren't working most of the time).
The `redirectTo` param is important to the template- this is what controls where you get redirected after signing up. It is different based on the mode: `signup/register` leads you to `/personalize`, whereas login leads you back to where you started.
However, we were never actually recomputing this when we changed modes, so if you initiated a modal in 'register' mode (by clicking 'Follow' and being signed out), your `redirectTo` would be `/personalize`. Then, when you switched into 'login' mode...your `redirectTo` _stayed_ as `/personalize`.
The fix is to not only …
> @erikdstock => Fix for auth modal not updating redirect when switching modes

- src/desktop/apps/personalize/client/onboarding.js
finishes https://artsyproduct.atlassian.net/browse/AR-212
This PR adds a callback that scrolls to the top of the page on a route update. There will be a conflict when we merge this PR or https://github.com/artsy/force/pull/2210, so I would wait until the other one is merged since the footprint of this PR is smaller and easier to resolve.
> [Onboarding] User should be taken to the top scroll position after clicking NEXT

- package.json
- src/desktop/analytics/articles.js
- src/desktop/apps/personalize/client/index.coffee
- src/desktop/apps/personalize/client/onboarding.js
- src/desktop/assets/analytics.coffee
- src/desktop/components/split_test/running_tests.coffee
- src/lib/middleware/locals.coffee
- src/mobile/analytics/global.js
- src/mobile/analytics/personalize.js
- src/mobile/assets/mobile_analytics.coffee
- yarn.lock
This includes a little bit of cleanup I noticed around so I'll comment inline.
Addresses https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&modal=detail&selectedIssue=AR-241 and https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&modal=detail&selectedIssue=AR-255
> @xtina-starr => Onboarding analytics QA

- package.json
- src/desktop/components/split_test/running_tests.coffee
- yarn.lock
> @xtina-starr => Launch Onboarding

- package.json
- yarn.lock
Fixes issue in Onboarding redirects
> Bumps to latest Reaction

- package.json
- src/lib/setup.js
- yarn.lock
This is similar to https://github.com/artsy/metaphysics/pull/948 but to force. This PR adds gzip compression via the handy [compression](https://github.com/expressjs/compression) package. Part of @sweir27  and I's sprint to improve front-end performance.
> Compress responses

- src/desktop/apps/articles/routes.coffee
Fixes[ AR-285](https://artsyproduct.atlassian.net/browse/AR-285) by including a check for a logged in user.
> @kanaabe: expands conditional to display modal to check if user is logged in or not

- src/desktop/apps/collect/client.coffee
- src/desktop/components/commercial_filter/views/pillbox/index.styl
- src/desktop/components/main_layout/templates/index.jade
- src/desktop/components/split_test/running_tests.coffee
Just following up on the close out email.
> @mzikherman => Resolve keyword search AB test in favor of control

- package.json
- yarn.lock
Includes the fix for obfuscated errors. Read more here https://github.com/artsy/express-reloadable/pull/8
> [Dev] update @artsy/express-reloadable

- package.json
- yarn.lock
> Reaction version 0.26.3

- src/desktop/apps/auction/components/layout/Footer.js
- src/desktop/apps/auction/components/layout/__tests__/Footer.test.js
Fixes https://sentry.io/artsynet/force-production/issues/475952503/
(https://www.artsy.net/auction/phillips-20th-century-and-contemporary-art-day-sale-8)
> @sweir27 => [Bugfix] Fix path in footer template 

- src/desktop/apps/artist/client/router.coffee
- src/desktop/apps/artist/client/views/overview.coffee
- src/desktop/apps/artist/routes.coffee
- src/desktop/apps/artist/templates/index.jade
- src/desktop/apps/artist/templates/sections/overview.jade
- src/desktop/apps/artist/test/templates.coffee
- src/desktop/components/split_test/running_tests.coffee
Zeplin: https://zpl.io/aXWXPxg
> [Artist] implements A/B/C/D variants of artist page

- src/desktop/apps/artist/client/router.coffee
- src/desktop/apps/artist/client/views/overview.coffee
- src/desktop/apps/artist/routes.coffee
- src/desktop/apps/artist/templates/index.jade
- src/desktop/apps/artist/templates/sections/overview.jade
- src/desktop/apps/artist/test/templates.coffee
- src/desktop/components/split_test/running_tests.coffee
Reverts artsy/force#2239
cc @l2succes
> Revert "[Artist] implements A/B/C/D variants of artist page"

- package.json
- yarn.lock
> @kanaabe => Bump reaction 0.26.5

- src/desktop/lib/global_client_setup.coffee
> [Bugfix] See if this fixes SEO import issue

- src/desktop/components/main_layout/templates/scripts.jade
- src/desktop/lib/global_client_setup.coffee
- yarn.lock
> [SEO Bugfix] Try pushing modules to top

- scripts/assets.sh
- src/desktop/assets/main_layout.coffee
- src/desktop/components/main_layout/templates/blank.jade
- src/desktop/components/main_layout/templates/index.jade
- src/desktop/components/main_layout/templates/minimal_header.jade
- src/desktop/components/main_layout/templates/scripts.jade
- webpack.config.js
> [SEO Bugfix] More fixes 

- src/desktop/apps/auction/components/Layout.js
- src/desktop/assets/main_layout.coffee
- src/desktop/components/fair_layout/templates/index.jade
- src/desktop/components/main_layout/templates/blank.jade
- src/desktop/components/main_layout/templates/index.jade
- src/desktop/components/main_layout/templates/minimal_header.jade
- src/desktop/components/main_layout/templates/scripts.jade
- src/lib/webpack-dev-server.js
- src/mobile/components/layout/templates/scaffold.jade
> [Bugfix SEO] Defer script loading

- src/desktop/components/fair_layout/templates/index.jade
- src/desktop/components/main_layout/templates/blank.jade
- src/desktop/components/main_layout/templates/index.jade
- src/desktop/components/main_layout/templates/minimal_header.jade
- src/desktop/components/main_layout/templates/scripts.jade
- src/mobile/components/layout/templates/scaffold.jade
Since this didn't actually change anything. 
Going to explore a bit in https://github.com/artsy/reflection/pull/65 to see if this will help.
> Remove defer

- .vscode/tasks.json
- src/desktop/components/fair_layout/templates/head.jade
- src/desktop/components/main_layout/templates/head.jade
- src/desktop/components/main_layout/templates/scripts.jade
- src/desktop/components/main_layout/test/templates.coffee
- src/lib/middleware/locals.coffee
- src/test/lib/middleware/locals.coffee
Follow up to https://github.com/artsy/reflection/pull/65, in support of new Puppeteer-based Reflection scraping.
> @joeyAghion => Update Reflection UA

- src/desktop/apps/personalize/index.coffee
- src/desktop/apps/personalize/routes.js
This requires users to be logged in to display onboarding.
> @yuki24: ensure a user is logged in in order to view onboarding

- package.json
- src/desktop/apps/article/components/App.js
- src/desktop/apps/article/components/__tests__/App.test.js
- src/desktop/apps/article/components/layouts/Article.js
- src/desktop/apps/article/index.js
- src/desktop/assets/article.coffee
- yarn.lock
Pretty simple! Haven't added in NewsNav yet because that's tied to InfiniteScroll which we will handle next sprint.
> @eessex => News article

- src/desktop/apps/artwork/components/metadata/components/artwork_classification_modal/templates/attribution_class_details.jade
Small fix before this feature can go live:
- Update collector facing copy re "classification"
(  Thanks for waiting @kanaabe )
> @anyone => Artwork classification QA

- src/desktop/apps/artwork/components/metadata/components/artwork_classification_modal/templates/attribution_class_details.jade
https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=SELL&modal=detail&selectedIssue=SELL-240&sprint=49
> text update for Ephemera description

- webpack.config.js
- yarn.lock
Fixes issue with IE11 from #incidents
> Fix ie 11 minification issue

- webpack.config.js
Remove parallel minification -- unfriendly in circle ci
> No parallel during minification

- src/desktop/components/auth_modal/templates/_gdpr_signup.jade
- yarn.lock
> Revert "fixes redirect-to query string"

- src/desktop/apps/article/components/InfiniteScrollArticle.js
- src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
- src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.test.js
- src/desktop/apps/article/queries/articles.js
- src/desktop/apps/article/queries/display.js
- tslint.json
> @eessex => Display Ad after 6th News Article

- src/desktop/components/artist_page_cta/index.styl
- src/desktop/components/artist_page_cta/templates/register.jade
- src/desktop/components/artist_page_cta/view.coffee
This adds the gdpr-form to the artist page cta. I think we'd want to hold off until we close the artist page test before adding this but I wanted to get some eyes on in the event I missed something.
> [WIP] add gdpr form to artist page cta

- src/desktop/components/artist_page_cta/view.coffee
- src/desktop/components/auth_modal/view.coffee
- src/desktop/components/marketing_signup_modal/index.coffee
- src/desktop/components/split_test/running_tests.coffee
This launches the a/b test for the gdpr form. @kanaabe if everything looks good and @katarinabatina gives the go ahead I think we can launch this.
> @kanaabe: launch the gdpr compliant form a/b/c test

- src/desktop/components/hover_pulldown/index.styl
- src/desktop/components/main_layout/header/index.styl
- src/desktop/components/main_layout/header/templates/large_screen_header.jade
- src/desktop/components/main_layout/header/templates/more.jade
- src/desktop/components/main_layout/header/templates/small_screen_header.jade
- src/desktop/components/main_layout/stylesheets/body.styl
- src/desktop/components/search_bar/templates/index.jade
- src/desktop/components/search_bar/view.coffee
https://artsyproduct.atlassian.net/browse/BUY-139
https://artsyproduct.atlassian.net/browse/BUY-140
- Adjust sizing of / whitespace around search bar
- Make placeholder text size-dependent
- Update colors
> Update main nav search layout and placeholder

- package.json
- src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
- yarn.lock
Bumps reaction and uses the new positionTop prop for NewsNav to fix header position bug.
> @kanaabe => [Newsfeed QA] Fix header top position

- src/desktop/components/artist_page_cta/view.coffee
- src/desktop/components/auth_modal/view.coffee
- src/desktop/components/marketing_signup_modal/index.coffee
- src/desktop/components/split_test/running_tests.coffee
Still working on https://github.com/artsy/force/pull/2305 so disabling the test for now.
> @kanaabe: disable-gdpr-test

- src/desktop/apps/artwork_purchase/test/templates.coffee
- src/desktop/components/fair_layout/stylesheets/header.styl
- src/desktop/components/main_layout/header/index.styl
- src/desktop/components/main_layout/header/templates/user.jade
- src/desktop/components/main_layout/stylesheets/body.styl
https://artsyproduct.atlassian.net/browse/BUY-137
Main nav:
Fair microsite:
> replacing the log in / log out link styles with buttons

- package.json
- yarn.lock
> @anyone => Bump Reaction

- src/desktop/components/artist_page_cta/view.coffee
- src/desktop/components/auth_modal/view.coffee
- src/desktop/components/inquiry_questionnaire/stylesheets/desktop.styl
- src/desktop/components/marketing_signup_modal/index.coffee
- src/desktop/components/split_test/running_tests.coffee
This addresses the minor visual issue mentioned by @katarinabatina via [slack](https://artsy.slack.com/archives/C9SATFLUU/p1522765312000123) and launches the the gdpr compliance test.
> @l2succes: Launch gdpr ab test

- src/desktop/components/fair_layout/stylesheets/dark.styl
- src/desktop/components/fair_layout/stylesheets/header.styl
- src/desktop/components/fair_layout/test/templates/nav.coffee
- src/desktop/components/hover_pulldown/index.styl
- src/desktop/components/main_layout/header/index.styl
- src/desktop/components/main_layout/header/templates/large_screen_header.jade
- src/desktop/components/main_layout/header/templates/user.jade
- src/desktop/components/main_layout/stylesheets/body.styl
This is the last step in the nav updates. Includes swapping the user/notification buttons order as well.
This needs to be pretty extensively tested because has a potential of looking different on different layouts. I've tried to look at that on as many pages as I could think of - but never hurts to have more eyes on it.
> replace user name in nav with person icon

- src/desktop/apps/article/queries/articleBody.js
- src/desktop/apps/article/stylesheets/amp.styl
- src/desktop/components/article/stylesheets/content.styl
- src/desktop/components/article/templates/mixins.jade
- Adds `news_source` to articleBody query
- Adds `news_source` rendering to amp articles
> @sarahscott => Add news-source to AMP

- package.json
- yarn.lock
> Bump reaction #patch

- package.json
- src/desktop/config.coffee
- yarn.lock
Pulls in the latest Reaction and adds /news to the EDITORIAL_PATHS to make analytics available!
> @xtina-starr => Add news analytics

- src/mobile/apps/articles/client/articles.coffee
- src/mobile/apps/articles/meta/articles.jade
- src/mobile/apps/articles/routes.coffee
- src/mobile/apps/articles/stylesheets/index.styl
- src/mobile/apps/articles/templates/articles_feed.jade
- src/mobile/apps/articles/test/routes.coffee
- src/mobile/apps/articles/test/templates.coffee
- Fetches recent news articles for mobile `/articles` route
- Renders `NewsPanel` component after first article if user is admin and has News Articles
- Adds unica font family to mobile `/articles` route
> @l2succes => News Panel on mobile /articles

- package.json
- patches/pug-loader+2.4.0.patch
- yarn.lock
Just realized I had force pointed at my own fork, but this is better!
> @mzikherman => Patch pug-loader

- yarn.lock
> @starsirius => Updated yarn.lock file

- src/desktop/models/article.coffee
- src/desktop/test/models/article.coffee
This allows Editors in Parsely to use layout. Waiting on confirmation from Matt that we should do it for all articles.
> @eessex => Add layout to article json-ld

- package.json
- src/desktop/apps/article/queries/articles.js
- src/desktop/apps/article/templates/__tests__/meta.test.js
- src/desktop/apps/article/templates/meta.jade
- src/desktop/apps/articles/templates/meta/news.jade
- yarn.lock
Addresses:
https://artsyproduct.atlassian.net/browse/GROW-421
https://artsyproduct.atlassian.net/browse/GROW-527
> @l2succes => News metadata + infinite scroll fix

- src/desktop/apps/home/client/index.coffee
- src/desktop/apps/home/stylesheets/index.styl
- src/desktop/apps/home/templates/index.jade
Button to come in a following PR
https://artsyproduct.atlassian.net/browse/DISCOVER-40
> @mzhikerman => Adds centered search bar for ab test

- src/desktop/apps/home/client/index.coffee
- src/desktop/apps/home/stylesheets/index.styl
- src/desktop/components/main_layout/header/index.styl
- src/desktop/components/main_layout/header/templates/large_screen_header.jade
- src/desktop/components/main_layout/header/view.coffee
- src/desktop/components/search_bar/templates/index.jade
- src/desktop/components/search_bar/test/view.coffee
- src/desktop/components/search_bar/view.coffee
I'll keep pushing stuff to this branch, here's how it looks now:
> @sarahscott => Add scrolling/animation to search bar for AB test

- src/desktop/analytics/main_layout.js
- src/mobile/analytics/before_ready.js
This was affecting our recorded bounce rate.
> @wrgoldstein => pass noninteraction: 1 for pageload tracking

- src/desktop/apps/home/client/index.coffee
> @mzikherman => Include a max of 7 results in homepage search

- package.json
- yarn.lock
Contain errors in article display ads
> @anyone => update reaction

- src/desktop/apps/article/index.js
No idea how we missed this one 😅
> @kanaabe => Admin flag on individual news

- src/desktop/apps/article/components/App.js
> @anyone => [Trivial] Fix propType complaint

- src/desktop/apps/articles/index.js
- src/desktop/apps/articles/stylesheets/articles.styl
- src/desktop/apps/articles/templates/full_feed.jade
- src/desktop/apps/articles/test/templates.coffee
- src/desktop/collections/articles.coffee
- src/desktop/test/collections/articles.coffee
- src/mobile/apps/articles/templates/articles_feed.jade
When we're ready, removes admin flags from newsfeed features.
> Remove admin flags from news

- circle.yml
Quick revert to fix blocked deploys. Going to test this but open to suggestions
> [Sentry] Revert ENV var injection

- package.json
- scripts/sentry.sh
- yarn.lock
> [Sentry] Add @sentry/cli for `sentry-cli` binary

- src/mobile/apps/articles/client/articles.coffee
- src/mobile/apps/articles/test/templates.coffee
Forgot this one... turns on News panel on `/articles` in mobile
> @l2succes => remove admin flag from mobile /articles

- .vscode/extensions.json
- package.json
- src/desktop/apps/artwork/client/index.coffee
- src/desktop/apps/artwork/components/auction_artworks/index.jade
- src/desktop/apps/collect/client.coffee
- src/desktop/apps/collect/templates/index.jade
- src/desktop/apps/react_example/components/myJadeView.jade
- src/desktop/components/artwork_columns/stitch_template.jade
- src/desktop/components/artwork_columns/template.jade
- src/desktop/components/artwork_columns/view.coffee
- src/desktop/components/commercial_filter/queries/artwork.coffee
- src/desktop/config.coffee
- src/desktop/index.js
- src/desktop/lib/global_client_setup.coffee
- src/desktop/lib/global_react_modules.js
- src/lib/setup.js
- tsconfig.json
- yarn.lock
First replacement location for new stitch work. Note that once this is in the wild and sufficiently tested we can start removing *a lot* of code.
- `ENABLE_EXPERIMENTAL_STITCH_INJECTION` feature flag. To view new columns, update `.env` and set to `true`
- Some warning cleanup in the console
> @cavvia => Replace /collect grid with <ArtworkGrid />

- src/desktop/apps/articles/routes.js
- src/desktop/components/email/client/editorial_signup.coffee
- src/desktop/components/email/test/editorial_signup.coffee
Returns early if there is a logged in user. 
Addresses https://artsyproduct.atlassian.net/browse/GROW-404
> @eessex => Prevent modal from appearing in logged in users on /articles

- package.json
- yarn.lock
> [Dev] upgrade @artsy/stitch

- src/desktop/components/auth_modal/templates/forgot.jade
- src/desktop/components/auth_modal/templates/reset.jade
- src/desktop/components/auth_modal/test/templates.coffee
This is just some final copy changes from @mdole putting the final polish on this new set password interaction. 💪
> Some final copy changes

- package.json
- src/desktop/apps/categories/components/FeaturedGene.js
- src/desktop/apps/categories/components/GeneFamilyNav.js
- src/desktop/apps/categories/components/TAGPIntro.js
- src/desktop/apps/editorial_features/components/gucci/components/nav/header.jsx
- src/desktop/apps/editorial_features/components/gucci/components/nav/sections_nav.jsx
- src/desktop/apps/editorial_features/components/gucci/components/section/section_text.jsx
- src/desktop/apps/editorial_features/components/gucci/components/section/section_video.jsx
- src/desktop/apps/editorial_features/components/gucci/components/series/series_footer.jsx
- yarn.lock
Depends on: https://github.com/artsy/reaction/pull/629
Switches to new font system in components that were consuming font styles from reaction
> @essex => switch to new Reaction font system

- src/desktop/apps/rss/queries/news.js
- src/desktop/apps/rss/routes.js
- src/desktop/apps/rss/templates/news.jade
- src/desktop/apps/rss/test/news.coffee
- src/desktop/apps/rss/test/routes.test.js
- src/desktop/models/article.coffee
- src/desktop/test/models/article.coffee
Refactors the router to use positronql instead -- no more setTimeout as a result!
Addresses https://artsyproduct.atlassian.net/browse/GROW-516
> @eessex => RSS updates for Flipboard integration

- src/desktop/components/main_layout/header/view.coffee
- src/lib/current_user.coffee
- src/mobile/components/layout/bootstrap.coffee
- src/mobile/components/layout/test/layout.coffee
This adds a similar post-signup action you created a while back for desktop.
> @mzikherman => Post-signup action on mobile nav

- package.json
- src/desktop/apps/about/client/view.coffee
- src/desktop/components/auction_artworks/view.coffee
- src/desktop/components/auth_modal/helpers.coffee
- src/desktop/components/auth_modal/view.coffee
- src/desktop/components/marketing_signup_modal/index.coffee
- src/desktop/models/logged_out_user.coffee
- src/desktop/test/models/logged_out_user.coffee
- yarn.lock
Sorry a lot of scattered PRs to you -- this should be the last one before we can merge https://github.com/artsy/gravity/pull/11706
This bumps artsy-passport to 1.0.10 and explicitly passes in the referer just like we do with intent.
> @mzikherman => Explicitly pass referer to user signups

- CONTRIBUTING.md
Update doc format a bit to make it linkable
> [Docs] Update Force / Reaction doc format

- src/mobile/apps/feature/routes.coffee
- src/mobile/apps/feature/templates/bid_page.jade
- src/mobile/apps/feature/test/routes.coffee
- src/mobile/apps/feature/test/templates.coffee
Blocked by: https://github.com/artsy/gravity/pull/11702
This PR is the mobile web side of https://github.com/artsy/force/pull/2442
> @erikdstock => adds registration optimizations for mobile web

- src/desktop/components/main_layout/header/index.styl
We probably don't want to hide the sign up button.
> @mzikherman => Dont hide sign up on homepage

- yarn.lock
Updates the lockfile to close out https://artsyproduct.atlassian.net/browse/GROW-556
> @kanaabe => Use latest artsy-eigen-web-association

- src/desktop/analytics/gallery_partnerships.js
- src/desktop/apps/galleries_institutions/templates/main.jade
- src/desktop/components/main_layout/footer/upper.jade
- src/desktop/components/main_layout/header/templates/more.jade
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=DISCOVER&modal=detail&selectedIssue=DISCOVER-54
> @damassi => Add some analytics on /gallery-partnerships links

- package.json
- yarn.lock
> @damassi => [Lib] Stitch 1.5.2

- src/desktop/analytics/home.js
- yarn.lock
Having some trouble with the arrow navigation so I'll do that last.
> [WIP] Home Rail Instrumentation

- src/desktop/components/search_bar/index.styl
- src/desktop/components/search_bar/templates/index.jade
- src/desktop/components/search_bar/test/view.coffee
- src/desktop/components/search_bar/view.coffee
In big search bar on home:
In search bar in the header:
Based on lab feature so should be safe to merge.
> @damassi => Experimental spotlight-like autocomplete

- src/desktop/components/artwork_filter_2/stylesheets/filter.styl
- src/desktop/components/artwork_filter_2/templates/filters.jade
- src/desktop/components/artwork_filter_2/templates/index.jade
- src/desktop/components/artwork_filter_2/view.coffee
- src/desktop/components/artwork_filter_2/views/filters_view.coffee
- src/desktop/components/commercial_filter/filters/paginator/paginator_view.coffee
- src/desktop/components/commercial_filter/filters/paginator/test/view.coffee
This adds a new Paginator UI to the top right and slightly refactors the page (dropdown to the left, counts in left-hand filter bar):
> @mzikherman => [Artist Page] Add top Paginator 

- src/desktop/components/artwork_filter_2/models/filter.coffee
Bugfix for infinite scroll in `/artist/id`
> [Bugfix] Fix pagination

- .circleci/config.yml
> @mzikherman => yarn install before heroku deploy

- .circleci/config.yml
> @mzikherman => maybe this image has yarn

- .circleci/config.yml
> @mzikherman => missing env var for heroku deploys

- src/desktop/apps/artist/client/router.coffee
- src/desktop/apps/artist/templates/sections/overview.jade
- src/desktop/apps/artist/test/client/overview.coffee
- src/desktop/apps/collect/client.coffee
- src/desktop/components/artwork_filter_2/models/filter.coffee
- src/desktop/components/artwork_filter_2/templates/index.jade
- src/desktop/components/artwork_filter_2/view.coffee
- src/desktop/components/commercial_filter/filters/paginator/test/view.coffee
Completes QA issues for experimental artist pagination
- Disable animated scroll-top
- Pagination paginates
- Tests for paginator 
- Show 'Related Artists'  rail and hide shows / articles
> @mzikherman => Finish /artist/:id pagination QA 

- src/desktop/apps/artwork/components/artists/market_insights.js
- src/desktop/apps/artwork/components/artists/templates/biography.jade
Fixes https://sentry.io/artsynet/force-staging/issues/551081347/
(Noticed that this errors out if the artwork artist doesn't have a bio, not sure if that impacts original implementation)
> @xtina-starr => [Bugfix] Make market-insights-safer

- src/desktop/components/search_bar/view.coffee
Ah yes, thanks for the suggestion, this looks better!
> @cavvia => Select first result when spotlight result is available

- src/desktop/apps/fair/stylesheets/overview.styl
- src/desktop/apps/fair_organizer/stylesheets/index.styl
- src/desktop/components/artwork_filter_2/models/filter.coffee
- src/desktop/components/artwork_filter_2/test/models/filter.coffee
Fixes issue where user who has selected filter and then clears does not get back full list. 
Also fixes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=DISCOVER&modal=detail&selectedIssue=DISCOVER-43
> @mzikherman => [Bugfix] Artist filter reset does not update params

- .env.oss
- src/desktop/analytics/main_layout.js
- src/desktop/config.coffee
- src/lib/setup_sharify.js
- src/lib/volley.js
- src/mobile/analytics/before_ready.js
- src/mobile/config.coffee
- yarn.lock
Basically just adds to our existing analytics tracking.
Names of metrics and tags are open to debate!
> Send metrics to volley

- src/desktop/apps/artist/client/router.coffee
- src/desktop/components/artwork_filter_2/index.styl
- src/desktop/components/commercial_filter/stylesheets/index.styl
> @mzikherman => Remove JumpView / lower grid opacity in A/B test

- src/desktop/components/search_bar/test/view.coffee
- src/desktop/components/search_bar/view.coffee
> @cavvia => Display spotlight result for subsequent token matches as well

- package.json
- yarn.lock
Contains new quasi-relay artwork brick [save work](https://github.com/artsy/reaction/pull/683)
> [Lib] Bump reaction 1.7.0

- src/desktop/components/artwork_filter_2/models/filter.coffee
- src/desktop/components/artwork_filter_2/views/filters_view.coffee
- src/desktop/components/artwork_filter_2/views/header_sorts_view.coffee
MVC UI code is terrifying. Fixes issue with dropdown not updating:
> [Bugfix] Fix dropdown

- src/desktop/components/artwork_filter_2/models/filter.coffee
- src/desktop/components/artwork_filter_2/models/params.coffee
- src/desktop/components/artwork_filter_2/test/views/header_sorts_view.coffee
- src/desktop/components/artwork_filter_2/view.coffee
- src/desktop/components/artwork_filter_2/views/filters_view.coffee
- src/desktop/components/artwork_filter_2/views/header_sorts_view.coffee
Adds a listener to the browser history so that the back buttons work during pagination.
> @mzikherman => [Artist] Listen to pagination history
