artsy/force

src/desktop/apps/home/client/index.coffee, src/desktop/apps/home/routes.coffee, src/desktop/apps/home/stylesheets/index.styl, src/desktop/apps/home/templates/index.jade, src/desktop/components/main_layout/header/index.styl, src/desktop/components/main_layout/templates/index.jade, src/desktop/components/search_bar/templates/index.jade, src/desktop/components/split_test/running_tests.coffee
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=DISCOVER&modal=detail&selectedIssue=DISCOVER-110
=> @cavvia => Resolve homepage search test in favor of control, bringing back hero unitz

src/desktop/apps/artist/client/router.coffee, src/desktop/apps/artist/client/views/overview.coffee, src/desktop/apps/artist/templates/sections/overview.jade, src/desktop/components/artwork_filter_2/models/filter.coffee, src/desktop/components/artwork_filter_2/templates/index.jade, src/desktop/components/artwork_filter_2/view.coffee, src/desktop/components/artwork_filter_2/views/filters_view.coffee
Comments out our FF and enables the A/B test:
- https://staging.artsy.net/artist/pablo-picasso?split_test[artist_page_pagination]=experiment
- https://staging.artsy.net/artist/pablo-picasso?split_test[artist_page_pagination]=control
=> @mzikherman => [Artwork/Pagination] Enable A/B test

src/lib/__tests__/volley.jest.js, src/lib/volley.js, src/test/lib/__tests__/volley.jest.js, yarn.lock
Should fix our negative metric data issue
=> handle missing data gracefully in Volley reporter

src/desktop/components/auth_modal/helpers.coffee, src/desktop/components/auth_modal/templates/_gdpr_signup.jade, src/desktop/components/auth_modal/view.coffee, src/desktop/models/logged_out_user.coffee
=> @eessex:  adds gdpr checkbox to generic auth modal

src/desktop/apps/artwork/components/partner_stub/index.jade, src/desktop/apps/artwork/components/partner_stub/query.coffee, src/mobile/apps/artwork/components/meta_data/templates/partner.jade, src/mobile/apps/artwork/components/partner/query.coffee
@alloy - this is just commenting out the data getting part for now just to confirm that is's not somehow affecting our MP problems.
Based on the feed back about timeline for this Credit card feature we should either completely remove this code or put this call back in.
=> comment out the call to get Credit Card info completely for now

src/desktop/components/auth_modal/helpers.coffee, src/desktop/components/auth_modal/templates/_gdpr_signup.jade, src/desktop/components/auth_modal/view.coffee, src/desktop/models/logged_out_user.coffee
=> Revert "@eessex:  adds gdpr checkbox to generic auth modal"

src/desktop/analytics/artist_page.js, src/desktop/apps/artist/templates/market_data_header.jade
adress https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=39&projectKey=EV&modal=detail&selectedIssue=EV-163
cc @wrgoldstein
=> adding analytics click events to new header

src/desktop/analytics/artist_page.js
=> fixing a typo that prevented one of the analytics events to get dispatched

src/desktop/components/main_layout/templates/index.jade, src/desktop/components/search_bar/index.styl, src/desktop/components/search_bar/view.coffee, src/desktop/components/split_test/running_tests.coffee
per @katarinabatina and @anipetrov we're cool to deploy this
=> @damassi => Roll out spotlight search as an AB test

src/desktop/components/main_layout/header/index.styl
Fixes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=DISCOVER&modal=detail&selectedIssue=DISCOVER-79
=> @damassi => Remove max-width on search bar / LHS of nav

package.json, patches/graphql+0.13.2.patch, yarn.lock
Fixes double graphql issue; related: https://github.com/artsy/reaction/pull/718
=> [Lib] Bump reaction 1.10.3; graphql@0.13.2

src/desktop/apps/article/__tests__/routes.test.js, src/desktop/apps/article/components/InfiniteScrollArticle.js, src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx, src/desktop/apps/article/components/__tests__/InfiniteScrollArticle.test.js, src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.test.js, src/desktop/apps/article/components/layouts/Article.js, src/desktop/apps/article/routes.js, src/desktop/apps/articles/routes.js, yarn.lock
=> Bring back display impressions analytics

package.json, src/desktop/apps/article/components/layouts/Article.js, yarn.lock
- Updates Reaction to include tooltip QA
- Adds tracking call for splitTest 'experiment viewed'
=> @kanaabe => Add 'experiment viewed', bump reaction

src/desktop/analytics/artwork.js, src/desktop/apps/artwork/components/auction_artworks/index.jade, src/desktop/apps/artwork/components/auction_artworks/index.styl, src/desktop/apps/artwork/components/show_artworks/index.jade, src/desktop/apps/artwork/components/show_artworks/index.styl
First point in https://artsyproduct.atlassian.net/browse/EV-188
There is a lot of code repetition in those analytics events but I feel like it's actually good to be explicit here vs creating a helper functions that would be called on each event.
I'll add the rest of them first thing tomorrow.
cc @katarinabatina, @anipetrov
=> adding analytics events for artwork suggested inventory rails

src/desktop/components/main_layout/footer/index.styl, src/desktop/components/main_layout/footer/lower.jade, src/desktop/components/main_layout/footer/view.coffee, src/desktop/components/main_layout/public/icons/wechat.svg
=> Adds wechat widget and removes snapchat icon

src/desktop/apps/partnerships/stylesheets/index.styl, src/desktop/apps/partnerships/stylesheets/marketo.styl, src/desktop/apps/partnerships/templates/auction_sections.jade
- Tweak whitespace
- Remove obsolete disclaimer
Now:
=> [GDPR] Auctions partnership form QA fixes #minor

src/desktop/apps/gallery_partnerships/stylesheets/index.styl
=> [GDPR] Update Gallery partnerships form styling

src/desktop/apps/gallery_partnerships/stylesheets/index.styl, src/desktop/apps/gallery_partnerships/templates/index.jade, src/desktop/apps/page/index.coffee
- Adds a vanity url for `/data-processing-agreement`
- Deletes an obsolete terms disclaimer
=> [GDPR] Vanity url for Data Processing Agreement

src/desktop/apps/article/__tests__/routes.test.js, src/desktop/apps/article/routes.js, src/lib/middleware/locals.coffee, yarn.lock
Addresses: https://artsyproduct.atlassian.net/browse/GROW-697
This suppresses tooltips on iPad.
=> suppress tooltips for iPad

src/desktop/apps/article/__tests__/routes.test.js, src/desktop/apps/article/routes.js
Addresses [GROW-634](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-634)
Pulls UTMs from req.url and appends them to redirect if redirected.
=> @kanaabe => Don't strip UTMs from article redirects

src/desktop/apps/article/components/App.js, src/desktop/apps/article/components/__tests__/App.test.js
Was nice pairing with you on this @erikdstock!
I decided to PR what we had for now. However there are two work items that I still want to get to that will be a better path forward: 
1. Re-introducing `babel-plugin-rewire` and get rid of those FIXME's
2. Converting this test to Jest
=> @erikdstock => Fix Article Test

package.json, src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx, src/desktop/apps/auth2/client/index.tsx, src/desktop/apps/auth2/components/AuthStatic.tsx, src/desktop/apps/auth2/helpers.ts, src/desktop/apps/auth2/routes.ts, yarn.lock
- Fix static pages
- UI Changes
=> [Auth] QA items

package.json, src/desktop/apps/auth2/client/index.tsx, src/desktop/apps/auth2/components/MobileAuthStatic.tsx, src/desktop/apps/auth2/routes.ts, src/desktop/config.coffee, yarn.lock
This addresses: https://artsyproduct.atlassian.net/browse/GROW-472
This PR integrates the mobile auth forms and takes in account whether to render the Mobile or Desktop version.
=> Incorporate mobile auth modal

src/desktop/apps/auth2/client/reset_password.coffee, src/desktop/apps/auth2/index.ts, src/desktop/apps/auth2/routes.ts, src/desktop/apps/auth2/templates/reset_password.jade, src/desktop/apps/auth2/test/reset_password.coffee, src/desktop/assets/misc.coffee
Copies over the code from auth to support /reset_password
=> @xtina-starr => Restore reset_password on auth2

package.json, src/desktop/apps/artist2/client.js, src/desktop/apps/artist2/components/Meta.js, src/desktop/apps/artist2/routes.js, src/desktop/apps/artist2/server.js, src/desktop/apps/artwork2/client.js, src/desktop/apps/artwork2/components/Meta.js, src/desktop/apps/artwork2/routes.js, src/desktop/components/main_layout/templates/react_redesign.jade, src/desktop/components/main_layout/templates/redesign.jade, yarn.lock
First pass at presenting new pages in force, updating 
- `/artist2`
- `/artwork2`
Noticing a few small console errors related to rehydration but can shake those out in further passes.
=> @mzikherman => [Redesign] First pass at Force static pages

src/desktop/apps/auth2/components/__tests__/AuthStatic.jest.js
Disabling for deploy -- cc @eessex
=> [Tests] Disable AuthStatic.jest test for now

src/desktop/apps/auth2/components/__tests__/AuthStatic.jest.js, yarn.lock
I think maybe a Reaction update changed the props for this... a simple fix.
=> @damassi => fix authStatic tests

package.json, src/desktop/apps/artist2/client.js, src/desktop/apps/artist2/server.js, src/desktop/assets/artist2.js, src/desktop/assets/artwork2.js, src/desktop/assets/isomorphic-relay.js, webpack.config.js, yarn.lock
=> Send latest reaction to staging 

src/desktop/apps/auth2/__tests__/helpers.jest.js, src/desktop/apps/auth2/components/AuthStatic.tsx, src/desktop/apps/auth2/components/MobileAuthStatic.tsx, src/desktop/apps/auth2/components/ModalContainer.tsx, src/desktop/apps/auth2/helpers.ts, src/desktop/models/logged_out_user.coffee, yarn.lock
=> @xtina-starr => Authentication Analytics pt2

src/desktop/apps/artist2/components/Meta.js, src/desktop/apps/artwork2/components/Meta.js
Remove temp webfont in favor of new palette update.
=> Remove temp font

package.json, src/desktop/apps/auth2/__tests__/helpers.jest.js, src/desktop/apps/auth2/__tests__/routes.jest.js, src/desktop/apps/auth2/components/AuthStatic.tsx, src/desktop/apps/auth2/helpers.ts, src/desktop/apps/auth2/routes.ts, src/desktop/components/fair_layout/client/header.coffee, src/desktop/models/logged_out_user.coffee, yarn.lock
- Adds in the ability to send a reset password request.
- Fixes fair double modal bug
=> @eessex => Forgot Password Submit

src/desktop/apps/auth2/components/AuthStatic.tsx, yarn.lock
Adds 20px padding to top and bottom, centers form on the page
=> @l2succes => Margins for AuthStatic

.circleci/config.yml
Deploy to production k8s (as well as heroku)
=> deploy to production k8s

src/desktop/components/main_layout/templates/index.jade, src/desktop/components/main_layout/templates/redesign.jade, src/desktop/components/search_bar/index.styl, src/desktop/components/search_bar/templates/index.jade, src/desktop/components/search_bar/test/view.coffee, src/desktop/components/search_bar/view.coffee, src/desktop/components/split_test/running_tests.coffee, yarn.lock
=> @cavvia => Resolve autosuggest AB test in favor of control

package.json, src/desktop/apps/auth2/components/AuthStatic.tsx, src/desktop/apps/auth2/components/MobileAuthStatic.tsx, src/desktop/apps/auth2/components/__tests__/AuthStatic.jest.js, src/desktop/apps/auth2/components/__tests__/MobileAuthStatic.jest.js, yarn.lock
Fixes an error after moving FormSwitcher
=> [Dev] fix FormSwitcher error

package.json, yarn.lock
=> [Dev] upgrade reaction

src/desktop/apps/consign/templates/landing.jade, src/desktop/apps/consign/test/fixture.json, src/desktop/apps/consign/test/templates.js, yarn.lock
Consign page Questions 'section.description' field accepts markdown.
Addresses https://artsyproduct.atlassian.net/browse/GROW-710
=> /consign questions accept markdown

src/desktop/apps/artist2/components/Meta.js, src/desktop/apps/artist2/server.js, yarn.lock
Mostly copied from `/artist`.
I left out the 'escaped fragment' tag (cc @joey). From what I understand, that tag indicates that Google will re-request the page but with `?_escaped_fragment=` query param, which we then redirect to Reflection/our pre-rendered page.
With a fully server-side rendered page we don't need that tag anymore right?
=> @damassi => Proper title and meta tags for /artist2 page

src/desktop/apps/artist2/client.js
Related: https://github.com/artsy/reaction/pull/927
=> @mzikherman => Pass mediator to reaction

scripts/deploy.sh
=> push update asset config for k8s on deploy

package.json, yarn.lock
Fixes display canvas slideshow
=> Bump reaction version

src/desktop/components/main_layout/footer/view.coffee
Seems to be working great via `yarn link && yarn watch` flow (i'm seeing the modals working).
There's an accompanying Reaction PR but this is safe to merge in the meantime.
=> @damassi => Let the FAQ and feedback modals be triggered from a Reaction footer

src/desktop/apps/article/__tests__/routes.test.js, src/desktop/apps/article/components/InfiniteScrollArticle.js, src/desktop/apps/article/components/layouts/Article.js, src/desktop/apps/article/routes.js, src/desktop/components/split_test/running_tests.coffee, yarn.lock
Removes test config for Tooltips A/B test, and sets up to use 'bio' (default) variation. 
The related component / props are updated in Reaction here - https://github.com/artsy/reaction/pull/956
=> @xtina-starr => Close toopTip a/b test

src/desktop/apps/artwork/components/commercial/templates/index.jade
This simply removes the button so that we do not create new purchase requests. I will go back and actually kill the code some time later in the week or next week.
Happy beaching:)
=> Remove purchase flow button. Will need to clean up the actual code.

package.json, src/desktop/apps/artist2/server.js, yarn.lock
This should get the logged out page working/QA-able.
Needs a `?new_artist_page=...` to access, otherwise it next's and eventually 404s.
=> @zephraph => Bump Reaction, and drop admin-only for /artist2 in favor of a query param

package.json, src/desktop/analytics/account_creation.js, src/desktop/analytics/account_login.js, src/desktop/apps/auth2/__tests__/helpers.jest.js, src/desktop/apps/auth2/components/AuthStatic.tsx, src/desktop/apps/auth2/components/MobileAuthStatic.tsx, src/desktop/apps/auth2/components/ModalContainer.tsx, src/desktop/apps/auth2/helpers.ts, test.config.js, yarn.lock
Dependent on https://github.com/artsy/reaction/pull/964
This is the second part of https://artsyproduct.atlassian.net/browse/GROW-780 that ensures we are tracking the 'created account' and 'successfully logged in' events.
=> @l2succes: track social authentication analytics properties

package.json, src/desktop/apps/artist2/server.js, yarn.lock
=> @mzikherman => Bump Reaction for new artist page

package.json, src/desktop/apps/auth2/components/AuthStatic.tsx, src/desktop/apps/auth2/components/MobileAuthStatic.tsx, src/desktop/apps/auth2/components/ModalContainer.tsx, yarn.lock
Depends on: https://github.com/artsy/reaction/pull/973/files
=> @eessex => Fix mobile social signups & disable blur background

package.json, yarn.lock
=> @mzikherman => New Reaction version

yarn.lock
=> [Dev] update yarn.lock #trivial

package.json, yarn.lock
=> @mzikherman => bump reaction for artist page QA

README.md, src/desktop/apps/auth2/__tests__/routes.jest.js, src/desktop/apps/auth2/routes.ts, src/desktop/assets/misc.coffee
Fix couple more reset_password2 instances.
=> Fix couple more reset_password2 instances.

package.json, src/desktop/components/email/client/editorial_signup.coffee, yarn.lock
Addresses [GROW-779](https://artsyproduct.atlassian.net/browse/GROW-779), bumps reaction to 1.20.13.
=> @xtina-starr => Auth analytics QA

package.json, src/desktop/apps/artist2/server.js, yarn.lock
Along with https://github.com/artsy/reaction/pull/1002
=> @alloy => Flatten out breakpoint param for Reaction SSR booting

package.json, webpack.config.js, yarn.lock
Reverts these changes because they might be causing an issue in staging
@orta seems like being reasonably sure isn't enough 😅
=> Revert bundle changes

package.json, src/desktop/apps/artist2/client.js, yarn.lock
Force side of https://github.com/artsy/reaction/pull/1007
=> @alloy => Use mediator to update URL when filter changes on artist page

package.json, src/desktop/apps/auth2/__tests__/helpers.jest.js, src/desktop/apps/auth2/helpers.ts, yarn.lock
Addresses https://artsyproduct.atlassian.net/browse/GROW-782
Redirects to home on form completion if on static /login or /forgot routes.
=> @l2succes => Don't redirect back to static auth routes

package.json, yarn.lock
=> @mzikherman => Maybe last Reaction bump for artist page??!

package.json, yarn.lock
=> @mzikherman => Bump Reaction

package.json, yarn.lock
bump for artist page QA this afternoon
=> @mzikherman => Bump Reaction for artist page analytics

src/lib/setup_sharify.js, src/mobile/apps/auth/routes.coffee, src/mobile/apps/auth/test/routes.coffee, src/mobile/config.coffee
Creates a separate environment variable to enable the new mobile auth system from the desktop version.
=> @mzikherman => create separate env variable for mobile auth

.circleci/config.yml
fix workflow definition and dependencies.
=> fix workflow

package.json, yarn.lock
This might be the last one before we merge the incremental roll out!
=> @mzikherman => Reaction bump!

package.json, src/desktop/apps/article/components/InfiniteScrollArticle.js, src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx, src/desktop/apps/article/components/NewsArticle.tsx, src/desktop/apps/article/components/__tests__/Article.test.js, src/desktop/apps/article/components/__tests__/InfiniteScrollArticle.test.js, src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.test.js, src/desktop/apps/article/components/layouts/Article.js, src/desktop/apps/article/queries/articleBody.js, src/desktop/apps/artist/index.coffee, src/desktop/apps/artist/maybe_new_artist_page.js, src/desktop/apps/artist2/server.js, src/desktop/components/split_test/running_tests.coffee, src/desktop/config.coffee, yarn.lock
Will merge on green, Circle is having some issues with tests, so opening a new PR.
=> @damassi => Deploy new artist page to a configurable percentage of users

package.json, src/desktop/apps/artist2/client.js, yarn.lock
Depends on https://github.com/artsy/reaction/pull/1054 + new version, but safe to merge whenever.
=> @damassi => Listen for mediator events and fire pageview event for each tab

.circleci/config.yml
=> read asset manifest correctly for prod deploy

.circleci/config.yml
helps for debugging, also sets to production
=> add manifest printout for debugging

.circleci/config.yml
Manually queueing up this deploy for now.
=> Successful deploy?

package.json, yarn.lock
https://github.com/artsy/reaction/compare/v1.21.4...master
=> @sepans => [Dev] bump reaction

package.json, src/desktop/apps/artist2/server.js, src/desktop/apps/order2/server.js, yarn.lock
Deals with the breaking Reaction API change.
=> [Reaction] Update apps for newer Responsive API.

package.json, yarn.lock
=> [Lib] Bump reaction to latest

package.json, src/mobile/apps/artist/index.coffee, yarn.lock
=> @mzikherman => Bump Reaction and serve new artist page to mobile users

package.json, src/mobile/apps/artist/index.coffee, yarn.lock
little early mornin' offsite deploy!
=> Deploy artist artwork grid updates, plus serve new artist page to mobile devices

package.json, yarn.lock
=> @mzikherman => Bump Reaction to fix gene/tag grids

package.json, src/mobile/apps/artist/index.coffee, yarn.lock
=> Deploy Reaction bump

src/desktop/apps/artist2/components/Meta.js
Reverts artsy/force#2762
Whoops I meant to close not merge!
=> Revert "@cavvia => Add fragment meta tag to new artist page"

src/desktop/apps/article/components/__tests__/Article.test.js, src/desktop/apps/article/components/layouts/Article.js, src/desktop/components/split_test/running_tests.coffee
Addresses https://artsyproduct.atlassian.net/browse/GROW-834
=> @xtina-starr => Enable infinite scroll test

package.json, yarn.lock
Trying to track down why staging / prod are reporting different logs than localhost (pointed at staging / prod)
=> [DEBUG] ArtistApp SSR debugging

package.json, yarn.lock
=> [Lib] Bump reaction

src/desktop/apps/artist2/components/Meta.js
=> @cavvia => Use name instead of property for description meta tag

src/desktop/apps/artwork/components/commercial/index.styl
This is just to get it looking more like design.
=>  minor modification for shipping price style

src/desktop/apps/artist2/server.js
Thanks for noticing and logging the issue!
=> @cavvia => Dont show artist CTA when on mobile

package.json, yarn.lock
=> @mzikherman => Reaction bump

package.json, src/desktop/apps/artist2/server.js, yarn.lock
=> Deploy reaction bump, drop duplicate artist header query

src/desktop/apps/artwork/components/commercial/templates/price.jade, src/mobile/apps/artwork/components/meta_data/templates/price.jade
@mzikherman - this is a temporary solution and as was discussed in a channel we already have a lab feature for that - so I'm just guarding against new display with the sam lab feature here.
Hope that makes sense.
=> put shipping display behind BNMO flag

src/desktop/apps/article/components/__tests__/Article.test.js, src/desktop/apps/article/components/layouts/Article.js, src/desktop/apps/article/routes.js, src/desktop/components/split_test/running_tests.coffee, yarn.lock
Addresses https://artsyproduct.atlassian.net/browse/GROW-857 and simply changes the name of the test's key and global constant.
=> @l2succes: change the name of article infinite scroll test (relaunch)

package.json, src/desktop/apps/notifications/client/index.coffee, src/desktop/apps/notifications/client/react_grid.js, src/desktop/apps/notifications/client/sidebar.coffee, src/desktop/apps/notifications/stylesheets/index.styl, src/desktop/apps/notifications/templates/desktop.jade, src/desktop/assets/misc.coffee, yarn.lock
@damassi is out today so I'll self merge, I think this is pretty simple.
This 'stands up the skeleton' by replacing the contents of /works-for-you with the Reaction component if the lab feature is present.
=> @damassi => When lab feature is present, replace /works-for-you content with Reaction component

package.json, src/desktop/apps/notifications/stylesheets/index.styl, yarn.lock
for sale and artist mode, visual polish
=> @mzikherman => Bump Reaction for some works for you updates

package.json, yarn.lock
=> @mzikherman => Bump Reaction for /works-for-you badges

package.json, yarn.lock
=> @mzikherman => Bump Reaction for WorksForYou QA

package.json, src/desktop/apps/notifications/client/index.coffee, src/desktop/apps/notifications/client/react_grid.js, src/desktop/apps/notifications/stylesheets/index.styl, src/desktop/apps/notifications/templates/desktop.jade, yarn.lock
Couple of tweaks, plus new location of app.
=> @mzikherman => One more Reaction bump for WFY

package.json, src/desktop/apps/notifications/stylesheets/index.styl, yarn.lock
=> @mzikherman => Bump Reaction for some WFY QA

src/desktop/apps/artwork/helper.js, src/desktop/apps/artwork/routes.coffee, src/desktop/apps/artwork/templates/index.jade, src/desktop/apps/artwork/test/fixtures/artwork.json, src/desktop/apps/artwork/test/helper.test.js
This addresses https://artsyproduct.atlassian.net/browse/GROW-845 to add `JSONLD` that matches the Product schema.
=> @eessex: add artwork jsonLD that matches product schema

package.json, src/desktop/apps/notifications/client/react_grid.js, yarn.lock
Bump reaction for https://github.com/artsy/reaction/pull/1192
=> [Lib] Bump Reaction 3.1.2

scripts/assets.sh, scripts/start.sh
We're getting timeouts here: https://circleci.com/gh/artsy/force/8851, which I've seen in my Webpack 4 branch (which I'll look at completing today).
=> @alloy => [Toolchain] Bump Force memory during compiles / start

src/desktop/apps/order2/server.js, src/desktop/components/main_layout/templates/blank.jade, src/desktop/components/main_layout/templates/index.jade, src/desktop/components/main_layout/templates/minimal_header.jade, src/desktop/components/main_layout/templates/redesign.jade, src/desktop/components/main_layout/templates/scripts.jade, yarn.lock
This fixes an integration problem with our Reaction components that need Stripe V3, which was [discussed in Slack](https://artsy.slack.com/archives/C9YNS4X32/p1535499882000100).
=> Adds option to load Stripe v3

src/desktop/apps/notifications/stylesheets/index.styl, src/desktop/apps/notifications/templates/desktop.jade
=> @mzikherman => [WorksForYou] Update layout to match spec

package.json, yarn.lock
cc @cavvia Adds save analytics to the WFY grid/component
=> @mzikherman => Bump Reaction for WFY analytics + QA

src/desktop/apps/consign/routes.js
Related to https://github.com/artsy/metaphysics/pull/1225
=> [graphql] Name a few more quries to improve datadog representation.

src/desktop/apps/personalize/client/onboarding.js
Passes user to fix bug in onboarding
Related: https://artsyproduct.atlassian.net/browse/GROW-603
=> [Onboarding] passes user data to context provider

package.json, yarn.lock
=> Bump reaction #trivial

package.json, src/lib/setup.js, yarn.lock
* Capture user-agent
* Rename service used for upstream http requests to follow our naming convention
=> [tracer] Upgrade to include our patches and refine data sent to DD.

src/desktop/apps/show/components/flickity_zoom_sequence/view.coffee
Makes it appear in Datadog correctly
=> Update anonymous query for install shots

src/desktop/apps/gallery_partnerships/templates/index.jade, src/desktop/components/json_page/README.md
Also update the json_page README ffr
Resolves https://artsyproduct.atlassian.net/browse/SELL-721
=> Update copy on gallery partnerships page

src/desktop/apps/artwork/components/auction/test/view.coffee, src/desktop/apps/artwork/components/auction/view.coffee, src/desktop/apps/artwork/components/commercial/templates/acquire.jade, src/desktop/apps/artwork/components/commercial/test/template.coffee, src/desktop/apps/artwork/components/commercial/view.coffee, src/mobile/apps/artwork/components/bid/index.jade, src/mobile/apps/artwork/components/bid/index.styl, src/mobile/apps/artwork/components/meta_data/templates/inquiry.jade, src/mobile/apps/artwork/components/meta_data/test/template.coffee, src/mobile/apps/artwork/components/meta_data/view.coffee
=> Revert "Only show buy now behind BN lab flag or for auctions"

package.json, yarn.lock
This pulls in [necessary work](https://github.com/artsy/reaction/pull/1217) that we need for Demo Days  tomorrow.
=> Updates Reaction to 3.5.0

package.json, yarn.lock
Bumps reaction to enable the full payment flow.
=> bump reaction to enable whole bnmo flow

src/desktop/apps/artwork/components/auction/test/view.coffee, src/desktop/apps/artwork/components/auction/view.coffee, src/desktop/apps/artwork/components/commercial/bootstrap.coffee, src/desktop/apps/artwork/components/commercial/templates/acquire.jade, src/desktop/apps/artwork/components/commercial/test/template.coffee, src/desktop/apps/artwork/components/commercial/view.coffee, src/mobile/apps/artwork/components/bid/index.jade, src/mobile/apps/artwork/components/bid/index.styl, src/mobile/apps/artwork/components/meta_data/templates/inquiry.jade, src/mobile/apps/artwork/components/meta_data/test/template.coffee, src/mobile/apps/artwork/components/meta_data/view.coffee
Reverts the revert of purchase-387 as well as adds bug fixes...
=> Restore Purchase-387 + Bug Fixes

src/desktop/apps/artist2/components/Meta.js, src/desktop/apps/artist2/components/__tests__/Meta.jest.js, src/desktop/config.coffee, yarn.lock
Adds `makesOffer` object to artist JsonLD with product information for 10 for-sale artworks.
=> @l2succes => Product schema in artist JsonLD

.circleci/config.yml
=> configure hokusai before using it

scripts/test.sh, src/desktop/apps/artwork/components/auction/test/view.coffee, src/desktop/apps/artwork/components/auction/view.coffee, src/desktop/apps/artwork/components/commercial/test/view.coffee, src/desktop/apps/artwork/components/commercial/view.coffee, src/desktop/apps/notifications/client/react_grid.js, src/desktop/apps/notifications/client/sidebar.coffee, src/desktop/apps/notifications/test/client/index.coffee, src/desktop/apps/notifications/test/client/sidebar.coffee
Follow-up from https://github.com/artsy/force/pull/2871
=> [Tests] Reenable from previous pr

src/desktop/apps/order2/server.js
Depends on https://github.com/artsy/reaction/pull/1241
Addresses [PURCHASE-433](https://artsyproduct.atlassian.net/browse/PURCHASE-433).
This will require a bump in reaction once 1241 is merged. Hooks up the SSR aspect of the title rendering.
=> Wire up order app title

package.json, src/lib/components/create_order/mutation.js, yarn.lock
Following up with latest changes in https://github.com/artsy/metaphysics/pull/1276
once MP PR got merged i think we need to update MP's schema in Force too.
=> [CoordinatedMerge] Switch to latest ecommerce error format 

yarn.lock
Also fixes https://artsyproduct.atlassian.net/browse/PLATFORM-876
=> [package] Update ddtrace to include sampling priority support.

yarn.lock
=> Update reaction version

yarn.lock
Fixes: https://artsyproduct.atlassian.net/browse/GROW-887
=> [Dev] bump reaction

src/desktop/apps/artist2/components/Meta.js, src/desktop/apps/artist2/components/__tests__/Meta.jest.js, yarn.lock
QA for artist person JsonLD, adds required image field to partner object to prevent errors.
=> @l2succes => Add partner profile image to artist person metadata

package.json, yarn.lock
Includes gemini bug fixes for display, collect page updates.
=> Update reaction to 3.10.3

src/desktop/apps/artist2/components/Meta.js
Fixes: https://sentry.io/artsynet/force-production/issues/690186056/?query=is:unresolved
=> Adds check for item

package.json, yarn.lock
Follow up to https://github.com/artsy/reaction/pull/1253/
=> [BUGFIX artistPage] Make safer

package.json, yarn.lock
Corresponding PR: https://github.com/artsy/reaction/pull/1254
=> [WFY] Bump reaction

.gitignore, src/desktop/apps/consign/client/reducers.js, src/desktop/apps/consign/components/describe_work_container/index.js, src/desktop/apps/consign/components/describe_work_desktop/index.js, src/desktop/apps/consign/components/describe_work_desktop/index.styl, src/desktop/apps/consign/components/describe_work_mobile/index.js, src/desktop/apps/consign/components/select_input/index.js, yarn.lock
Ticket: https://artsyproduct.atlassian.net/browse/SELL-760
I didn't manually reformat anything, but it reformatted some files quite a bit.
=> Add minimum price for consignment submissions

src/desktop/apps/collect2/client.js, src/desktop/apps/collect2/meta.tsx, src/desktop/apps/collect2/server.js, yarn.lock
Removed custom titles from the original collect app, now uses static strings.
=> @l2succes => Add meta template for /collect2

package.json, yarn.lock
#minor - so will put it as Merge on green
=> latest reaction

src/desktop/apps/consign/client/reducers.js, src/desktop/apps/consign/components/describe_work_container/index.js, src/desktop/apps/consign/components/describe_work_desktop/index.js, src/desktop/apps/consign/components/describe_work_mobile/index.js
Sorry for the prettier changes. I just fixed one place where a select was called `dimension_metric` instead of `currency`, and made sure currency was added to the functions that manipulate submissions data. I would just search on "currency" to find the changes.
=> bug fix - wrong name on consignment submissions currency select

src/desktop/components/main_layout/footer/lower.jade, src/mobile/components/layout/templates/footer.jade
finishes https://artsyproduct.atlassian.net/browse/PURCHASE-449
=> Add Conditions of Sale link to the footer

hokusai/test.yml, webpack.config.js
=> [CI] Don’t cache build artefacts and silence progress formatter.

package.json, src/desktop/apps/artwork/components/commercial/templates/acquire.jade, src/desktop/apps/auction/components/__tests__/Layout.test.js, src/desktop/apps/auction/components/artwork_browser/PromotedSaleArtworks.js, src/desktop/apps/auction/components/artwork_browser/__tests__/PromotedSaleArtworks.test.js, src/desktop/apps/auction/components/artwork_rail/__tests__/ArtworkRail.test.js, src/desktop/components/artwork_item/templates/partials/auction_info.jade, src/desktop/components/artwork_item/templates/partials/bid_status.jade, src/desktop/components/auction_artwork_brick/templates/bid_status.jade, src/desktop/components/auction_artworks/templates/artwork/grid.jade, src/desktop/components/auction_artworks/test/template.coffee, src/desktop/models/sale.coffee, src/desktop/test/models/sale.coffee, src/mobile/apps/artwork/components/bid/index.jade, src/mobile/apps/artwork/components/meta_data/templates/inquiry.jade, src/mobile/apps/artwork/components/meta_data/test/template.coffee, src/mobile/components/auction_artwork_list/templates/artwork.jade, yarn.lock
One of the points in `Issue=DISCO-301`
=> update text of buy button to buy now

src/desktop/apps/consign/templates/landing.jade, src/desktop/apps/order2/server.js, src/desktop/components/main_layout/header/index.styl, src/desktop/components/main_layout/header/minimal_header.styl, src/desktop/components/main_layout/header/templates/minimal_header.jade, src/desktop/components/main_layout/stylesheets/body.styl, src/desktop/components/main_layout/templates/minimal_header.jade, yarn.lock
Updates the minimal header to complete [PURCHASE-426](https://artsyproduct.atlassian.net/browse/PURCHASE-426).
=> feat: update minimal header

webpack.config.js
=> [webpack] Print warning about launch time with cold cache.

package.json, yarn.lock
=> @mzikherman => Bump Reaction for last artwork brick adjustments

package.json, yarn.lock
last QA from @briansw , as well as place behind the BNMO lab (instead of its own).
=> @mzikherman => Bump Reaction for artwork brick QA and place behind BNMO lab

package.json, yarn.lock
Basically just this https://github.com/artsy/reaction/pull/1314
=> [package] Update Reaction to add artist page tracing

package.json, yarn.lock
https://github.com/artsy/reaction/pull/1325
=> Bumping Reaction to 4.8.1

src/desktop/apps/artwork/components/auction/view.coffee, src/desktop/apps/artwork/components/commercial/view.coffee, src/lib/components/create_order/mutation.js, src/mobile/apps/artwork/components/meta_data/view.coffee
Adds the ecommerce prefix to operations related to orders to support schema stitching for exchange
=> Prefix createOrder mutation with ecommerce

src/mobile/apps/browse/index.coffee, yarn.lock
Upgrades reaction and show responsive collect on mobile browsers whenever it's enabled
=> [Collect] show new collect page on mobile when enabled

src/desktop/apps/armory_week/index.js, src/desktop/apps/article/__tests__/routes.test.js, src/desktop/apps/article/routes.js, src/desktop/apps/articles/routes.js, src/desktop/apps/artist2/server.js, src/desktop/apps/artsy_in_miami/index.js, src/desktop/apps/artwork2/server.js, src/desktop/apps/auction/__tests__/routes.jest.js, src/desktop/apps/auction/routes.js, src/desktop/apps/auctions2/routes.js, src/desktop/apps/auth2/__tests__/routes.jest.js, src/desktop/apps/auth2/routes.ts, src/desktop/apps/basel_week/index.js, src/desktop/apps/categories/__tests__/routes.test.js, src/desktop/apps/categories/routes.js, src/desktop/apps/collect2/server.js, src/desktop/apps/frieze_week/index.js, src/desktop/apps/frieze_week_london/index.js, src/desktop/apps/isomorphic-relay-example/server.js, src/desktop/apps/order2/server.js, src/desktop/apps/personalize/routes.js, src/desktop/apps/personalize/test/routes.js, src/desktop/apps/react_example/routes.js
Not sure why it wasn't this way before /shrug
=> [Stitch] Update call from `renderLayout` to `stitch` 

src/desktop/apps/collect2/client.js
This will start the new collect page test against the existing page for 50% of our users.
TODO: https://artsyproduct.atlassian.net/browse/GROW-892
=> [Collect] enable A/B test

src/desktop/apps/artwork/components/commercial/bootstrap.coffee, src/desktop/apps/artwork/components/commercial/query.coffee, src/desktop/apps/artwork/helper.js, src/desktop/apps/artwork/test/fixtures/artwork.json, src/desktop/apps/artwork/test/helper.test.js
This addresses https://artsyproduct.atlassian.net/browse/GROW-878 which wraps up the artwork structured data qa items. It's labeled as WIP because I'd like to add some tests.
- Uses `sale_message` to display the price.
- Breaks up price range into `minPrice` and `maxPrice` when applicable.
- Map availability to expected offer schema.
- Add missing brand property
- Type seller as "ArtGallery"
=> @l2succes: [Structured Data] Add missing properties

package.json, yarn.lock
=> Bumps reaction to fix refresh bug

package.json, yarn.lock
https://github.com/artsy/reaction/pull/1375 and https://github.com/artsy/reaction/pull/1377
=> Update to latest reaction for BNMO changes

src/desktop/apps/artwork/components/auction/test/view.coffee, src/desktop/apps/artwork/components/auction/view.coffee, src/desktop/apps/artwork/components/commercial/test/view.coffee, src/desktop/apps/artwork/components/commercial/view.coffee, src/desktop/config.coffee, src/mobile/apps/artwork/components/meta_data/test/view.coffee, src/mobile/apps/artwork/components/meta_data/view.coffee, src/mobile/config.coffee
This PR addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-487
It requires that users log in before they are able to create an order.
=> Prompt users to log in when they click the "Buy" button

package.json, src/desktop/apps/artwork/components/auction/view.coffee, src/desktop/apps/artwork/components/commercial/test/view.coffee, src/desktop/apps/artwork/components/commercial/view.coffee, src/desktop/apps/artwork/test/fixtures/acquireable_artwork_no_edition.json, src/mobile/apps/artwork/components/meta_data/index.styl, src/mobile/apps/artwork/components/meta_data/templates/index.jade, src/mobile/apps/artwork/components/meta_data/view.coffee, yarn.lock
Fixes:
- removes loading state from "buy" button on error
- fixes how we assign edition set IDs
- adds a hook for `react-modal-container` for the mobile case, since it wasn't being mounted.
=> Fixes error states and edition set handling while creating orders

package.json, yarn.lock
=> Bump reaction@5.5.2

src/desktop/apps/artwork/components/auction/view.coffee, src/desktop/apps/artwork/components/commercial/view.coffee
Totally thought I stuck this option in the first time around 😅 . This will skip onboarding if you sign up through the flow.
Thanks for catching this @ashfurrow
=> Skip onboarding when signing up through buy now

package.json, yarn.lock
=> Bump reaction@5.6.0

README.md
=> trivial readme update

src/desktop/apps/artwork/components/commercial/templates/questions.jade, src/desktop/apps/inquiry/client/views/confirmation.coffee, src/desktop/apps/inquiry/client/views/done.coffee, src/desktop/components/contact/confirm_inquiry.coffee, src/desktop/components/contact/contact_partner.coffee, src/desktop/components/contact/inquiry.coffee, src/desktop/components/contact/show_inquiry_modal.coffee, src/desktop/components/inquiry_questionnaire/views/confirmation.coffee, src/desktop/components/inquiry_questionnaire/views/done.coffee, src/mobile/apps/artwork/components/artist/templates/index.jade, src/mobile/lib/global_react_modules.js, yarn.lock
Fixes: 
- https://artsyproduct.atlassian.net/browse/DISCO-403
- https://artsyproduct.atlassian.net/browse/DISCO-393 (new FAQ link out on BNMO works)
- https://artsyproduct.atlassian.net/browse/DISCO-396 (Update "Your Inquiry has been sent" copy)
Realized the responsive mobile side hadn't been added yet, which solves the issue that was reported since its a new design.
=> @mzikherman => [Mobile Artwork] Stitch in ArtistInfo

package.json, yarn.lock
=> Bump reaction@5.7.2

src/desktop/components/split_test/running_tests.coffee
Launches collect page (https://artsyproduct.atlassian.net/browse/GROW-932)
=> [Collect] shows new collect page to 100% of users

src/desktop/apps/order2/routes.js
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-551
=> Change header logo href source for order app

package.json, yarn.lock
=> Upgrade Reaction to 5.7.4

src/desktop/apps/artwork/components/commercial/templates/questions.jade, src/desktop/apps/artwork/components/commercial/view.coffee
https://artsyproduct.atlassian.net/browse/DISCO-393
=> Fix: properly open FAQ page on buy now works

.vscode/extensions.json, .vscode/settings.json
And updates cSpell settings to be less intrusive.
=> [VSCode] Add artsy.artsy-studio-extension-pack

package.json, yarn.lock
=> @mzikherman => Bump reaction, collect URL update

package.json, yarn.lock
=> [Lib] Bump reaction@5.7.8

src/desktop/apps/collect2/__tests__/client.jest.js, src/desktop/apps/collect2/client.js, src/desktop/apps/collect2/server.js
- hooks up /collections/:slug to collect app
- makes sure filters are serialized correctly for collect and collections
=>  [Collection] setup /collection/:slug

package.json, yarn.lock
=> Bump reaction@5.8.1

package.json, yarn.lock
possible session race condition bug fix
We should thoroughly test/QA on staging.
=> @damassi => Bump @artsy/passport for a passport.js update

package.json, yarn.lock
Don't have much hope for this.
=> @damassi => Try to upgrade cookie session lib to fix myserious missing header bug

src/desktop/apps/artwork/components/commercial/test/view.coffee, src/desktop/apps/artwork/components/commercial/view.coffee, src/lib/components/create_offer_order/index.tsx, src/lib/components/create_offer_order/mutation.js, src/mobile/apps/artwork/components/meta_data/test/view.coffee, src/mobile/apps/artwork/components/meta_data/view.coffee
This PR addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-596
When you click the "make offer" button, we should send a mutation (similar to the one for `createOrder`).
=> Actually run mutation to create an offer order when "make offer" button is clicked

src/desktop/apps/article/components/layouts/Article.tsx, src/desktop/apps/auth2/components/ModalContainer.tsx
I can no longer live without Typescript.
=> Typescriptify Article.js and add more helpful types to ModalContainer.tsx

package.json, yarn.lock
Reverts artsy/force#3054
I'll add more details later.
=> Revert "Update to latest Reaction"

package.json, yarn.lock
=> Bump reaction@6.0.4

package.json, yarn.lock
=> Bump reaction@6.0.5

package.json, yarn.lock
https://github.com/artsy/react-responsive-media/issues/19
=> [package] Bump Reaction to fix responsive bug.

package.json, yarn.lock
=> bump reaction to fix line height issue

package.json, yarn.lock
removing the language for artworks < 10 pageviews
=> @mzikherman => Bump Reaction for updated language around pageviews CTA

renovate.json
Simplifies the renovate config
=> Shared renovate

src/desktop/apps/artwork2/client.js
Follow up on https://github.com/artsy/reaction/pull/1566.
Should `just work` in the new artwork app:)
=> Add mediator events for asking auction specialist and buy now specialist for artwork2

package.json, src/desktop/apps/artist/server.js, src/desktop/apps/artwork2/server.js, src/desktop/apps/collect2/server.js, src/desktop/apps/collections/server.js, src/desktop/apps/isomorphic-relay-example/server.js, src/desktop/apps/order2/routes.js, src/desktop/components/main_layout/templates/minimal_header.jade, src/desktop/components/main_layout/templates/react_minimal_header.jade, src/desktop/components/main_layout/templates/react_redesign.jade, src/desktop/components/main_layout/templates/redesign.jade, yarn.lock
Reverts artsy/force#3108. 
Per [slack convo](https://artsy.slack.com/archives/C2TQ4PT8R/p1542840813628300) - reverting this so that we can better track down the issue in responsive. We can follow up on improving this pattern once the other issue is solved.
=> Revert "[SSR] Insert dehydrated data directly into HTML doc after main markup."

src/desktop/apps/article/queries/display.js
Finishes https://artsyproduct.atlassian.net/browse/GROW-1009
While I was QAing the cover overlay work, I realized I hadn't updated the article query. This PR does that and should be the last thing needed for the launch of the campaign for Monday.
=> @l2succes: update article query to include has_cover_overlay

src/desktop/apps/artwork2/client.tsx, src/desktop/apps/artwork2/server.tsx
We really need to get rid of these containers, but for now just need to make sure to match on the client what we render on the server.
=> [artwork2] Make client side markup match server side rendered results

renovate.json
Removing the node config change that I made because it seems to break things.
=> Fix renovate's config

package.json, src/desktop/apps/artist/server.tsx, src/desktop/apps/artwork2/server.tsx, src/desktop/apps/collect2/server.tsx, src/desktop/apps/collections/server.tsx, src/desktop/apps/isomorphic-relay-example/server.tsx, src/desktop/apps/order2/routes.tsx, yarn.lock
This pulls in Reaction v9 and updates the API usage to pass the user-agent so Reaction can detect what devices to render for.
=> Add device detection and limit amount of markup rendered.

package.json, src/desktop/apps/artwork2/client.tsx, yarn.lock
Also brings the latest reaction which passes proper artwork id for mediators so that ExtraLinks work on artwork2 page.
=> add mediator when artwork2 page loads

src/lib/intercom.ts, yarn.lock
Now that GPDR compliance is enabled and deployed to production for this (deleting Intercom data when a user requests so), we can roll this out.
=> @mzikherman => Roll out Intercom to all users

CONTRIBUTING.md
=> Update node version to 10

.circleci/config.yml, yarn.lock
=> Revert "@zephraph => Dont run tests on `release` commits"

package.json, src/desktop/apps/artwork2/client.tsx, src/desktop/assets/artwork2.styl, yarn.lock
Puts the updated PartnerAuctionInfo on the new Artwork2 page and adds mediator for triggering the buyer's premium modal.
Selfie:
=> add mediator for displaying buyer's premium on artwork page

src/mobile/apps/artwork/components/bid/index.jade, yarn.lock
Solves the  issue reported on https://artsyproduct.atlassian.net/browse/DISCO-529
Looks like:
=> hide bid action button on mobile for auction preview works

src/desktop/apps/artwork2/client.tsx
This needs a Reaction update from https://github.com/artsy/reaction/pull/1646
=> @oxaudo => Open inquiry modal when triggered by mediator on new artwork page

Dockerfile
Bumps node to pull in security updates
https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2018-11-29-version-10141-dubnium-lts-mylesborins
=> Update node to 10.14.1

.circleci/config.yml
=> @dleve123 => For now, remove schema validation step from prod deploy

package.json, yarn.lock
Urgent update, renovate hasn't updated yet.
=> Bump reaction to 9.1.20

src/desktop/apps/artwork2/server.tsx
This relaxes our admin only restriction to also include a query param for safety. Now we can QA when logged out.
=> @damassi => Allow a query param to access artwork2 page

dangerfile.ts
In #3214 Danger was raising incorrectly after we'd deployed an update to Metaphysics, this should at least make that non-blocking for the moment while I switch out to comparing using images in ECR via the AWS API.
Also moves Peril to not run the release checker, which it can't really pull-off - it doesn't have access to Force's `node_modules` available locally.
=> Convert the MP release check to be a warn for now, and don't let Peril run that check

hokusai/config.yml
- Make the dir before
- Hardcode the length of title/text
- Hardcode title/text
=> Hardcode DD deploy event

package.json, yarn.lock
=> @mzikherman => Bump Reaction for some BNMO blockers on the new artwork page

package.json, src/desktop/analytics/main_layout.js, yarn.lock
Bumps Reaction and updates the tracking exclusion.
=> @damassi => Update a bunch of analytics tracking for the new artwork page

src/desktop/config.coffee, src/mobile/config.coffee
- Needed for ENABLE_MAKE_OFFER for Make offer filter
=> Adds ENABLE_MAKE_OFFER to config.coffee

.circleci/deploy_event.sh, hokusai/config.yml
Had to give up on the one liner. Pretty much impossible to reverse engineer how a string will go through python yml and bash escaping and get it working.
=> try as a script

package.json, src/desktop/index.js, src/desktop/lib/global_client_setup.coffee, src/lib/setup.js, src/mobile/index.js, src/mobile/lib/global_client_setup.coffee, yarn.lock
Companion PR to https://github.com/artsy/stitch/pull/25.
=> Refactor stitch SSR middleware

src/lib/setup_sharify.js
This came up in Slack today, so let's cross-reference the docs and code for next time.
=> Adds link to env var docs

src/desktop/apps/artist/server.tsx, src/desktop/apps/artwork2/server.tsx
I suspect a better solution exists in Reaction but that's...going to take me a while to wade thru and figure out, so this can be a quick fix for now.
=> @joeyAghion => Make sure not found artists and artworks bubble up as 404s

src/desktop/apps/artist/server.tsx, src/desktop/components/split_test/running_tests.coffee
Add A/B test with `control` and `experiment` variations.
The value is passed through to the Artist App in artsy/reaction which will switch between the two different versions.
=> Add AB test for Artist Insights V2

src/mobile/apps/artwork/components/image/templates/image_module.jade
Fixes https://sentry.io/artsynet/force-production/issues/841841080/
=> Fix-sentry-841841080

package.json, src/desktop/components/react/stitch_components/ReactionTooltipQuestion.tsx, yarn.lock
Updates an icon path to point to palette instead of reaction
=> Update icon path

package.json, src/desktop/components/react/stitch_components/ReactionTooltipQuestion.tsx, yarn.lock
Upgrades to Palette and Reaction:
https://github.com/artsy/reaction/compare/v10.0.1...v10.0.5
https://github.com/artsy/palette/compare/v2.25.9...v2.25.10
=> Deploy: Palette & Reaction upgrades

src/desktop/apps/artist/client.tsx, src/desktop/apps/artist/server.tsx, src/desktop/apps/artwork2/client.tsx, src/desktop/apps/artwork2/server.tsx, src/desktop/apps/order2/client.js, src/desktop/apps/order2/routes.tsx
=> Revert "Remove <Container /> component used in new router apps"

src/desktop/components/main_layout/header/templates/index.jade, src/desktop/components/react/stitch_components/StagingBanner.tsx, src/desktop/components/react/stitch_components/index.tsx
- Adds a purple banner to staging to make it more obvious
- https://artsyproduct.atlassian.net/browse/PLATFORM-1066
=> PLATFORM-1066 - Adds staging banner

yarn.lock
Addresses: https://artsyproduct.atlassian.net/browse/GROW-996
This updates the artsy eigen web association module as part of https://github.com/artsy/artsy-eigen-web-association/pull/23
=> update artsy eigen web association

yarn.lock
=> Release fix

src/desktop/components/fair_week_marketing/PageScaffold.js, yarn.lock
=> Replace Grid in far_week_marketing jsonPage

src/desktop/components/main_layout/header/templates/small_screen_dropdown_menu.jade
Fix https://artsyproduct.atlassian.net/browse/BUGS-698
Make nav menu from 'Works for you' page consistent with the rest of the app.
=> Make nav menu consistent across the app

yarn.lock
related: https://github.com/artsy/artsy-eigen-web-association/pull/24
=> upgrade artsy-app-site-association

src/desktop/components/main_layout/templates/scripts.jade
If `window.Sailthru` is undefined, try again after 250ms
Fixes https://artsyproduct.atlassian.net/browse/BUGS-727
=> fix calling window.Sailthru before it is defined #BUGS-727

src/desktop/apps/auction_support/client/bid_form.coffee, src/mobile/apps/feature/client/bid_page.coffee
Update Bid processing timeout copy to match
https://artsyproduct.atlassian.net/browse/PURCHASE-142
Not sure if the format of the page is already like that zeplin page but i updated the copy.
=> Update timeout copy for bid processing

src/desktop/apps/artists/client/carousel.coffee
Fixes https://artsyproduct.atlassian.net/browse/BUGS-732
https://artsy.net/artists
=> [Bugfix] Only interact with carousel if images

src/desktop/components/react/auction_block/index.styl
Fixes https://artsyproduct.atlassian.net/browse/BUGS-566
=> [Bugfix] Constrain related auctions image size

src/desktop/apps/artists/templates/index.jade
Fixes https://artsyproduct.atlassian.net/browse/BUGS-648
=> [Bugfix] Artist page crashes if artist doesn't have a thumbnail 

src/desktop/apps/artwork2/client.tsx, src/desktop/components/view_in_room/view.coffee, yarn.lock
=> [WIP] Restore view-in-room functionality

src/desktop/components/main_layout/header/templates/large_screen_header.jade, src/desktop/components/react/stitch_components/SearchBar.tsx, src/desktop/components/react/stitch_components/index.tsx
The purpose of this PR is to give us a seam to work with the new search bar while the current one still exists.
=> Add stub for new search bar and hide behind flag

src/desktop/index.js
=> Restore order app

src/desktop/apps/artwork2/client.tsx, src/lib/components/record_artwork_view/index.js
Thanks for spotting this! I think ideally this would live in Reaction, but this should be fine for now. It's just a tiny mutation client side.
=> @damassi => [RecordArtworkView] Reenable recording an artwork view on new artwork page

src/desktop/components/article_figure/mixin.jade, src/desktop/models/article.coffee
Related: https://artsyproduct.atlassian.net/browse/GROW-568
=> [Article] fix display year in article dates

package.json, yarn.lock
Part of https://artsyproduct.atlassian.net/browse/PLATFORM-1129
=> [package] Update dd-trace client.

src/desktop/assets/artists_artworks.styl, webpack/utils/getEntrypoints.js
Forgot to remove a CSS ref here https://circleci.com/gh/artsy/force/14990
=> Remove missing collect2.css file

src/desktop/apps/auth2/client/index.tsx, src/mobile/apps/art_fairs/test/template.coffee
This test always fails randomly, gonna x it .
=> X out test that always fails CI

package.json, yarn.lock
Going to do an orchestrated deploy of this and the MP equivalent: https://github.com/artsy/metaphysics/pull/1490
=> [package] Update dd-trace client again.

src/desktop/config.coffee, src/lib/setup_sharify.js, src/mobile/config.coffee
(Will remember to remove this when it's done).
=> Adds config var for enabling make offer note

webpack/envs/production.js
=> Remove progress bar in prod

scripts/uploadToS3.js, webpack/envs/production.js, webpack/index.js
Set js and css to gzip as well as actual gzip-built assets.
=> Attempt to fix gzip

scripts/uploadToS3.js
=> Revert gzip test

hokusai/config.yml, package.json, scripts/sentry.sh, yarn.lock
See: https://docs.sentry.io/workflow/releases/
=> Re-enable Sentry sourcemap uploads

hokusai/config.yml, package.json, scripts/sentry.sh, src/desktop/config.coffee, src/lib/setup.js, src/mobile/config.coffee
Adds missing DEPLOY_ENV variable, and updates publish-assets script to call sentry.
=> Fix deploy env

package.json
Waiting for resolution in slack
=> Remove sentry uploads for now

package.json, src/desktop/apps/article/routes.js, src/desktop/components/main_layout/templates/scripts.jade, src/desktop/models/article.coffee, src/lib/setup.js, src/mobile/components/layout/templates/scaffold.jade, webpack/envs/base.js, yarn.lock
Added extra logging around fetching super articles for an article in the article model.
=> Deploy force to production

src/desktop/apps/auth2/routes.ts
Addresses: https://artsyproduct.atlassian.net/browse/GROW-1080
This PR depends on https://github.com/artsy/reaction/pull/2009
Here we pass the artist name from reaction in order to build the custom title when a logged out user attempts to follow an artist.
=> refactor custom title to account for artist name

.circleci/config.yml, hokusai/config.yml, hokusai/production.yml
Band-aid for #incident-27
Requires Hokusai v0.5.2 to deploy
=> Ddos protection

package.json, src/lib/middleware/rateLimiting.ts, src/lib/setup.js, yarn.lock
Last minute fix to make sure we're getting the ip address from the right place for rate limiting
=> Use correct IP for rate limiting

src/lib/middleware/rateLimiting.ts
Adding some logging around rate limiting to have some more visibility in staging
=> Add logging around rate limiting

patches/@artsy/reaction+13.0.6.patch, patches/@artsy/stitch+6.0.0.patch, src/desktop/apps/artist/server.tsx, src/desktop/apps/artwork2/server.tsx, src/desktop/apps/collect/server.tsx, src/desktop/apps/collections/server.tsx, src/desktop/apps/isomorphic-relay-example/server.tsx, src/desktop/apps/order2/routes.tsx
This PR is to test a possible fix for https://artsyproduct.atlassian.net/browse/PLATFORM-1184. Because it's hard to reproduce this locally, I had to rely on other indicators, which indicate this issue should be fixed. However, the proof is in the pudding, as they say, so I don’t want to call this done until we've seen it fixed in staging/production.
The fix spans a few repos, though, so rather than doing a bunch of releases that perhaps are deemed unnecessary, after testing this fix, I went with patched versions of these packages. The corresponding upstream PRs are:
* https://github.com/artsy/reaction/pull/2029
* https://github.com/artsy/stitch/pull/61
In short, this PR changes the Reaction integration to expect rendered HTML from Reaction and use that for the page’s body as-is.
=> [SC] Hot-patch Reaction and Stitch to test a fix for the CSS bloat.

hokusai/production.yml
https://artsy.slack.com/archives/C9ZJYFDNF/p1550496946082400
=> Whitelist clear cache page in Nginx DDoS mitigation rules

hokusai/production.yml
Already applied to production.
=> @ashkan18: Revert to usual scale

src/desktop/components/react/stitch_components/SearchBar.tsx
Looks super janky, but probably time we start roughing it in.
=> @jonallured => [Autosuggest] Bring in Reaction component

src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.test.js
=> @mzikherman => [Testing] Pend problematic inf scroll news article test

package.json, scripts/uploadToS3.js, src/lib/setup.js, webpack/envs/production.js, yarn.lock
Re-adds a CompressionPlugin and manually set `ContentEncoding: gzip` on upload assets.
=> Re-add CompressionPlugin for gzip assets

scripts/uploadToS3.js, webpack/envs/production.js
=> Comment out compression for now

package.json, scripts/uploadToS3.js, webpack/envs/production.js, yarn.lock
=> Cleanup commented out code

src/desktop/config.coffee, src/lib/setup_sharify.js, src/mobile/config.coffee, yarn.lock
~DO NOT MERGE~ Now ready for merging 🍏 
This is dependent on https://github.com/artsy/reaction/pull/2058 being merged and reaction being updated in force.
https://artsyproduct.atlassian.net/browse/PURCHASE-846
The ticket only mentions `ENABLE_MAKE_OFFER` but presumably `ENABLE_OFFER_NOTE` will not be required either after https://artsyproduct.atlassian.net/browse/PURCHASE-895 gets taken care of in the PR above
=> Remove make offer feature flag env vars

package.json, src/desktop/apps/article/components/__tests__/InfiniteScrollArticle.jest.tsx, yarn.lock
This fixes the search bar disappearing on staging w the missing context.
=> @mzikherman => Bump Reaction and test fix

hokusai/production.yml, hokusai/staging.yml
Relates to https://artsyproduct.atlassian.net/browse/PLATFORM-1236
These changes have been applied to staging and production.
=> Add auto-scaling to Kubernetes config

src/desktop/components/view_in_room/view.coffee
disabled background scrolling and removed existing (broken) scrollbar-disabling stuff
=> View-in-room - Page scrolling not disabled during view-in-room modal

src/desktop/components/search_bar/view.coffee
This commit reports the duration between entering a term in the existing search bar and rendering search suggestions to the user.
We plan to add a similar measurement targeting the new search bar implementation built in artsy/reaction.
=> Measure performance of search bar

src/desktop/components/main_layout/header/templates/large_screen_header.jade, src/desktop/components/main_layout/header/templates/small_screen_header.jade, src/desktop/components/split_test/running_tests.coffee, src/desktop/lib/global_client_setup.tsx, src/mobile/components/layout/bootstrap.coffee, src/mobile/components/layout/templates/main.jade
This sets up the configuration for the 50/50 AB test, and swaps out the lines that guard the feature behind a lab feature with a check that the AB test group is 'experiment'.
It also fires the 'experiment viewed' analytics tracking call.
=> @jonallured => [Autosuggest] Launch AB test

src/desktop/apps/partner2/components/hero_shows_carousel/index.jade, src/desktop/apps/partner2/components/hero_shows_carousel/index.styl, src/desktop/apps/partner2/components/hero_shows_carousel/test/view.coffee, src/desktop/apps/partner2/components/hero_shows_carousel/view.coffee
https://artsyproduct.atlassian.net/browse/GALL-1314
To simplify the requirements, we decided to bump the max number of shows to 50 and implement the [Instagram-style infinite pagination](https://github.com/chahine/pageindicator).
=> Implement infinite style for partner show carousel (GALL-1314)

src/desktop/components/view_in_room/view.coffee
fixed rendering issue related to margins added to account for classic scrollbar
=> fixed rendering issue related to margins added to account for classic scrollbar

src/test/acceptance/fixtures/metaphysics/artist.json
Update “Participated in a major biennial” to "Included in a major biennial"
branches in reaction & metaphysics
=> Artist insights 2.0 - Update biennial badge label

src/desktop/assets/artists_artworks.styl
=> @mzikherman => Remove reference to non existent old artwork CSS

package.json, yarn.lock
Follow-up from 
- https://github.com/artsy/reaction/pull/2140
- https://github.com/artsy/palette/pull/308
=> [Lib] Icon Upgrade -> Bump Reaction / Palette to latest

src/desktop/apps/partner/templates/overview.jade, src/desktop/apps/partner2/templates/overview_banner.jade, src/desktop/components/main_layout/footer/upper.jade, src/desktop/components/main_layout/header/templates/more.jade
Another minor follow up to https://github.com/artsy/reaction/pull/2159
Sorry for multiple Prs here.
=> forgot one more link to /gallery-partnerships. Updating now

package.json, yarn.lock
=> Release force

.circleci/config.yml
Reactivates the duplicates report
=> Re-enable dupe report

src/desktop/apps/fair_organizer/routes.coffee, src/desktop/apps/fair_organizer/test/routes.coffee
https://artsyproduct.atlassian.net/browse/GALL-1435
Let's check the actual profile additionally and only redirect when it's public. In the ticket we mentioned switching to use `fair.active_start_at ` instead; however, it's not always set for all fairs.
There will be a followup to [revisit the entire redirection need](https://artsyproduct.atlassian.net/browse/GALL-1460), so this PR focused on avoiding the 404 and SEO impact.
=> Fix 404 fair page redirected from fair organizer page (GALL-1435)

src/desktop/apps/article/__tests__/routes.test.js, src/desktop/apps/article/components/App.tsx, src/desktop/apps/article/routes.ts, src/desktop/apps/articles/components/App.tsx, src/desktop/apps/articles/routes.ts, src/desktop/apps/articles/test/routes.js, src/desktop/components/split_test/running_tests.coffee
Addresses: [GROW-1176](https://artsyproduct.atlassian.net/browse/GROW-1176)
=> [GROW-1176] closes editorial collections rail a/b test

.circleci/config.yml, package.json, src/desktop/components/main_layout/header/index.styl, src/desktop/components/main_layout/header/small_screen_header.styl, src/desktop/components/main_layout/header/templates/large_screen_header.jade, src/desktop/components/main_layout/header/templates/small_screen_header.jade, src/desktop/components/react/stitch_components/SearchBar.tsx, src/desktop/components/react/stitch_components/index.tsx, src/mobile/components/layout/stylesheets/main_header.styl, src/mobile/components/layout/templates/main.jade, yarn.lock
I'm bailing on #3803 for now because I just can't seem to get review apps working. Instead I'm going to get this commit in that will launch the new search bar for all admins. Once merged we can safely test on staging (and production for that matter) and when satisfied, then I can switch over to the AB approach for launching to actual users.
=> Restore new search bar for admins

src/desktop/apps/article/queries/relatedArticles.js
Last step of https://artsyproduct.atlassian.net/browse/GROW-1102
=> [Trivial] Add authors to relatedArticles query

src/desktop/apps/search/index.coffee, src/desktop/apps/search/maybe_new_search_page.ts, src/desktop/apps/search2/server.tsx
Once https://github.com/artsy/reaction/pull/2258 is released, I can remove the draft and this is mergeable (though really, all of these disparate PR's are mergeable and don't need to be synced since this isn't released yet, so it's fine to be a tad broken as things deploy).
=> @dblandin => [SearchResults] Mount new app under /search, and behind lab

scripts/validateSchemas.js
This should make it easier to go from the error message to an action
=> Changes the wording in the validate schema script

src/desktop/components/main_layout/header/templates/large_screen_header.jade, src/desktop/components/main_layout/header/templates/small_screen_header.jade, src/desktop/components/split_test/running_tests.coffee, src/desktop/components/split_test/split_test.coffee, src/desktop/lib/global_client_setup.tsx, src/mobile/assets/mobile_analytics.coffee, src/mobile/components/layout/bootstrap.coffee, src/mobile/components/layout/templates/main.jade
Woo! I'm leaving this as a draft since @cavvia still needs to approve the current setup + analytics on staging.
=> @damassi => [Autosuggest] Re-enable AB test for a second take

src/desktop/apps/artsy_primer/personalize/test/client/followable.coffee, src/desktop/apps/auctions/test/template.coffee, src/desktop/components/inquiry_questionnaire/test/map.test.coffee, src/desktop/components/related_links/test/view.test.coffee, src/desktop/components/util/test/activator.test.coffee, src/mobile/apps/shows/test/template.test.coffee
- x's sticky test that is failing in master
- Ensures that tests setting up `benv` also tear it down
Related conversation: https://artsy.slack.com/archives/C2TQ4PT8R/p1555341296004200
=> Fix sticky test, teardown Benv

package.json, src/desktop/apps/article/components/App.tsx, src/desktop/apps/article/components/__tests__/InfiniteScrollArticle.jest.tsx, src/desktop/apps/article/components/layouts/__tests__/Article.jest.tsx, src/desktop/apps/articles/components/App.tsx, src/desktop/apps/artist/client.tsx, src/desktop/apps/artist/server.tsx, src/desktop/apps/gene/client.js, src/desktop/apps/notifications/client/react_grid.js, src/desktop/apps/personalize/client/onboarding.js, src/desktop/apps/tag/client.js, src/desktop/components/react/stitch_components/StitchWrapper.tsx, yarn.lock
Depends on https://github.com/artsy/reaction/pull/2291.
Renames `ContextProvider` to `SystemContextProvider`.
=> [Refactor] Rename ContextProvider -> SystemContextProvider

src/desktop/components/main_layout/header/templates/large_screen_header.jade, src/desktop/components/main_layout/header/templates/small_screen_header.jade, src/desktop/components/split_test/running_tests.coffee, src/desktop/lib/global_client_setup.tsx, src/mobile/components/layout/bootstrap.coffee, src/mobile/components/layout/templates/main.jade
Woo!
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-943
=> @dblandin => [SearchBar] Resolve AB test in favor of new search bar from Reaction

src/desktop/apps/search2/client.tsx, src/desktop/apps/search2/server.tsx, src/desktop/apps/search2/templates/index.jade, src/desktop/components/main_layout/templates/search_results.jade
Stitch in search results skeleton within search results page.
Depends on https://github.com/artsy/reaction/pull/2305#
=> Stitch in search results page skeleton

src/desktop/apps/artist/client.tsx, src/desktop/apps/artist/server.tsx, src/desktop/components/split_test/running_tests.coffee
Addresses: [GROW-1187](https://artsyproduct.atlassian.net/browse/GROW-1187)
⚠️ Hold ⚠️
This launches the artist collections rail test but is waiting for price guidance work to be merged.
=> [ArtistCollectionsRail] launch artist collections rail test

src/desktop/apps/search/client/index.coffee, src/desktop/apps/search2/client.tsx, src/desktop/apps/search2/server.tsx, src/desktop/components/split_test/running_tests.coffee, src/mobile/apps/search/client.coffee
Leaving this as a draft since I think it's not quite ready, but almost...
=> @dblandin => [Search] Launch AB test

src/desktop/apps/artist/client.tsx, src/desktop/apps/artist/server.tsx, src/desktop/components/split_test/running_tests.coffee
=> Revert "[ArtistCollectionsRail] launch artist collections rail test"

src/desktop/apps/artist/client.tsx, src/desktop/apps/artist/server.tsx, src/desktop/components/split_test/running_tests.coffee
Reverts artsy/force#3924
We're relaunching the test
=> Revert "Revert "[ArtistCollectionsRail] launch artist collections rail test""

package.json, src/desktop/apps/artist/server.tsx, src/desktop/apps/artwork/server.tsx, src/desktop/lib/buildServerAppContext.ts, yarn.lock
cc @pepopowitz 
This is the companion to https://github.com/artsy/reaction/pull/2327
=> @mzikherman => Bump Reaction and bring back google ad snippet

src/desktop/components/artist_page_cta/view.coffee
Addresses: [GROW-1175](https://artsyproduct.atlassian.net/browse/GROW-1175)
Adds the following analytics tracking events:
**Auth Impression for scroll**
**Auth Impression for clicking the Footer CTA**
**Dismissing the CTA**
=> Add analytics events to Artist Page Signup CTA

.circleci/config.yml
Re-enable's bundle size checks in CI
=> Re-enable bundle size checks

package.json, yarn.lock
Looks like reaction is duping flickity w/ force's version. 
https://github.com/artsy/force/pull/3963
=> Remove duplicate flickity

src/desktop/apps/article/templates/__tests__/meta.jest.js, src/desktop/apps/article/templates/meta.jade
This PR inserts the script tag with the URI attr needed to inject ads hosted by Hashtag labs onto Article pages.
=> adds ad server script tag

scripts/test.sh, src/desktop/apps/auction_support/test/client/registration_form.test.coffee, src/desktop/components/auction_lots/test/client/router.test.coffee
Follow up to quiet some finicky tests exposed in https://github.com/artsy/force/pull/3930
=> Address problem tests

hokusai/config.yml
Accidentally added this, which creates unwanted tags
=> Remove git-remote

src/desktop/apps/search/client/index.coffee, src/desktop/apps/search2/client.tsx, src/desktop/apps/search2/server.tsx, src/desktop/components/split_test/running_tests.coffee, src/mobile/apps/search/client.coffee
The A/B test for the new search results page showed a positive result for the experiment variation so we're moving forward and rolling this out to 100%! :100:
ticket: https://artsyproduct.atlassian.net/browse/DISCO-988 :lock:
=> End A/B test for new search results page

src/lib/setup_sharify.js
`ARTIST_COLLECTIONS_RAIL_IDS=["ai-weiwei","alex-katz","alexander-calder","andy-warhol","ansel-adams","banksy","christo-and-jeanne-claude","chuck-close","cindy-sherman","cy-twombly","damien-hirst","david-hockney","ed-ruscha","ellsworth-kelly","fernando-botero","frank-stella","gerhard-richter","gregory-crewdson","helen-frankenthaler","henri-matisse","hiroshi-sugimoto","hunt-slonem","jasper-johns","jean-michel-basquiat","jeff-koons","jenny-holzer","jim-dine","joan-miro","josef-albers","kaws","keith-haring","louise-bourgeois","man-ray","marc-chagall","mr-brainwash","nan-goldin","pablo-picasso","paul-klee","rene-magritte","robert-indiana","robert-mapplethorpe","robert-rauschenberg","roy-lichtenstein","sally-mann","salvador-dali","shepard-fairey","slim-aarons","takashi-murakami","tracey-emin","w …
=> Adds ARTIST_COLLECTIONS_RAIL_IDS

src/desktop/components/main_layout/client.coffee
Fixes https://sentry.io/organizations/artsynet/issues/1030213561/?project=28316
=> Add missing Cookie import

src/mobile/components/layout/templates/main.jade
=> Fix whitespace in mobile nav

src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx, src/desktop/apps/article/components/NewsArticle.tsx, src/desktop/apps/articles/routes.ts
This PR adds a feature flag to the NewsArticle and InfiniteScrollNewsArticle components to enable hiding/displaying as on News landing pages.
=> Adds feature flag for new ads to news articles

src/desktop/apps/article/templates/__tests__/meta.jest.js, src/desktop/apps/article/templates/meta.jade
Follow up to https://github.com/artsy/reaction/pull/2440
=> Remove HTLads

src/desktop/components/react/stitch_components/NavBar.tsx
Ensures that the staging banner sits above the new nav
=> [NavBar] QA

src/desktop/components/react/stitch_components/StagingBanner.tsx
Small z-index fix so that staging banner is on top of new nav bar.
#trivial
=> Adjust z-index in StagingBanner

src/desktop/apps/article/helpers.tsx
This PR addresses a comment in a [previous pull request](https://github.com/artsy/force/pull/4098#discussion_r287092728)
=> uses lodash get to check for null/falsy values

src/desktop/apps/article/__tests__/helpers.jest.tsx, src/desktop/apps/article/components/InfiniteScrollArticle.tsx, src/desktop/apps/article/components/layouts/Article.tsx, src/desktop/apps/article/helpers.tsx
This PR ads props needed to determine whether or not to display ads in Series, Feature and Standard Articles.
=> Add props to render new as on Series, Featured, Standard Articles

package.json, src/desktop/apps/home/templates/index.jade, src/desktop/components/main_layout/templates/scripts.jade, src/desktop/components/main_layout/test/templates.test.coffee
For embedded web views in Eigen, we do not want to render the reCAPTCHA scripts.
=> Do not use reCAPTCHA in Eigen

src/desktop/assets/authentication.styl, src/desktop/assets/misc.styl
This was not loading correctly from `/authentication.styl` but it seems to work when loaded from here.
Follow up to https://github.com/artsy/force/pull/4140
=> Move reset_password style require

src/desktop/components/main_layout/templates/instant-page.jade, src/desktop/components/main_layout/templates/scripts.jade, src/desktop/components/split_test/running_tests.coffee, src/desktop/config.coffee, src/desktop/lib/global_client_setup.tsx, src/lib/setup_sharify.js
Removes the A/B test, re-adds `sd.ENABLE_INSTANT_PAGE` guard.
=> [A/B Instant Page] Remove A/B test in favor of Instant Page

package.json, yarn.lock
Reverts artsy/force#4193
Causing 500 errors in force staging
=> Revert "[Lib] Bump reaction"

hokusai/production.yml, hokusai/staging.yml
Updates staging/production config to use named ports.
=> Update port references in hokusai config

.circleci/config.yml
=> Bump hokusai orb

src/desktop/components/react/stitch_components/StagingBanner.tsx
Follow-up to https://github.com/artsy/reaction/pull/2559
#trivial
=> [Bugfix] Fix navBar zIndex #trivial 

src/desktop/apps/artist/client.tsx, src/desktop/apps/artist/server.tsx, src/desktop/components/split_test/running_tests.coffee
Addresses: [GROW-1270](https://artsyproduct.atlassian.net/browse/GROW-1270)
This closes the Artist Collections Rail a/b test and is follow-up to [GROW-1277](https://artsyproduct.atlassian.net/browse/GROW-1277).
=> [ArtistCollectionsRail] close artist collections rail a/b test

package.json, yarn.lock
=> Reaction and Palette updates

package.json, yarn.lock
=> Update dep @artsy/reaction from 16.18.2 to v16.18.3

src/desktop/apps/artist/client.tsx, src/desktop/apps/artist/components/__tests__/cta.jest.ts, src/desktop/apps/artist/components/cta.js, src/desktop/apps/artist/components/cta.ts, src/desktop/assets/artist.js, src/desktop/components/split_test/running_tests.coffee
Addresses: [GROW-1314](https://artsyproduct.atlassian.net/browse/GROW-1314)
This adds an auth signup modal (with an image) to the artist page and sets up the a/b tests for QA purposes. ~~This is blocked by https://github.com/artsy/reaction/pull/2590~~
=> [GROW-1314] Artist page signup modal a/b test

.circleci/config.yml
Removes step pushing redundant production image - relates to https://artsyproduct.atlassian.net/browse/PLATFORM-1596
=> Remove push-production-image step

src/desktop/apps/home/templates/meta.jade, src/desktop/apps/page/meta/default.jade
This changes the primary title and description metadata for force in keeping with ticket [GROW-1394](https://artsyproduct.atlassian.net/browse/GROW-1394).
Diff Analysis: 
```
{
"total_files_changed": 2,
"test_files_changed": 0,
"by_type": {
"jade":2
}
}
```
=> updated primary and default meta description and title tags

src/desktop/apps/artist/components/__tests__/cta.jest.ts, src/desktop/apps/artist/components/cta.ts, src/desktop/components/split_test/running_tests.coffee
Addresses: [GROW-1313](https://artsyproduct.atlassian.net/browse/GROW-1313)
This changes this key name of the Artist Signup Page A/B test and fires the experiment viewed event essentially launching the test.
=> [GROW-1313] Launch artist page signup ab test

hokusai/production.yml
Increases `maxReplicas` for production kubernetes from 12 -> 20
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-1621
=> Increase max pods to 20

src/desktop/apps/auction_reaction/client.tsx, src/desktop/apps/auction_reaction/routes.tsx, src/desktop/apps/auction_reaction/server.tsx, src/desktop/apps/auction_reaction/templates/index.jade, src/desktop/assets/auction_reaction.ts, src/desktop/index.js
Working on migrating the bidder registration flow first.
Depends upon https://github.com/artsy/reaction/pull/2605
cc/ @dleve123 @erikdstock
=> Inject new artsy/reaction auction routes

src/desktop/apps/auction/components/layout/ConfirmRegistrationModal.tsx
* Fixes divergent copy between registration and registration+bid
* Refactors out common components as they are the same from a domain perspective.
Jira: https://artsyproduct.atlassian.net/browse/AUCT-495
=> Fix registration copy

src/desktop/apps/artwork/client.tsx
Only fire test when a user is logged out, related conversation:
https://artsy.slack.com/archives/C0KEQD4B0/p1566242136006000
=> Inquiry auth test QA

src/desktop/apps/page/index.styl, src/mobile/apps/page/index.styl
- https://artsyproduct.atlassian.net/browse/PURCHASE-1415
=> PURCHASE-1415 - Fixes mobile breakpoint for injected page content

src/desktop/apps/order/client.js, src/desktop/apps/order/routes.tsx, src/desktop/components/main_layout/header/minimal_header.styl, src/desktop/components/main_layout/header/templates/minimal_header.jade, src/desktop/components/main_layout/templates/minimal_header.jade
=> PURCHASE-1406 hide order app header on eigen, not just logo

src/desktop/apps/order/client.js
👋 We just need to add this here, and then to actually show Intercom in reaction we'll send a message to the mediator when the OrderApp mounts.
https://artsyproduct.atlassian.net/browse/PURCHASE-1390
=> PURCHASE-1390 Allow intercom on order app

yarn.lock
=> Revert "Bump lodash-es from 4.17.4 to 4.17.15"

package.json, src/desktop/components/main_layout/stylesheets/body.styl, yarn.lock
Bumping reaction with new [ArtworkFilter](https://github.com/artsy/reaction/pull/2789) on `/collect` page.
=> Bump reaction@18.0.0

README.md
=> Add artsy footer

src/test/acceptance/collections.js, src/test/acceptance/fixtures/metaphysics/collections.json
- Adds a fixture for `collections` data from metaphysics
- Adds basic acceptance tests for `/collections`
=> Add acceptance tests for /collections

src/test/acceptance/collect.js, src/test/acceptance/fixtures/metaphysics/collect.json
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-1801
=> Add acceptance test for /collect

.babelrc, package.json, src/test/acceptance/fixtures/metaphysics/artist.json, yarn.lock
Bump reaction, update fixture and fix terminal warning. 
closes https://github.com/artsy/force/pull/4585
=> Bump reaction@19.0.0

src/desktop/apps/artwork/__tests__/client.jest.ts, src/desktop/apps/artwork/client.tsx, src/desktop/components/split_test/running_tests.coffee
Closes a/b test for inquiry authentication, returns to control. 
Related ticket: https://artsyproduct.atlassian.net/browse/PLATFORM-1449
=> Close inquiry auth A/B test

src/desktop/apps/auction_reaction/routes.jest.ts, src/desktop/apps/auction_reaction/routes.tsx, src/desktop/apps/auction_reaction/server.tsx
- Creates route for `/auction-faq` for new responsive Auction FAQ page. 
- DONTMERGE until https://github.com/artsy/reaction/pull/2809 is merged and released
=> Adds Auction FAQ route

CONTRIBUTING.md
Add a note to `CONTRIBUTING` regarding setup steps.
=> [Docs] Update with Review App instructions

CONTRIBUTING.md
Updates review app creation steps based on pairing session with @dleve123
=> Update CONTRIBUTING.md with more Review App info

package.json, src/index.js, yarn.lock
Here Force is being polyfilled to have access to `DOMParser`.
=> [package] Update Reaction/react-html-parser to work well on the server

package.json, yarn.lock
=> [Lib] Bump reaction@21.7.8

CONTRIBUTING.md, src/lib/environment.js, webpack/envs/productionConfig.js
=> [webpack] Ease debugging of server prod builds.

src/desktop/apps/auction/reducers/__tests__/artworkBrowser.test.js, src/desktop/apps/auction/reducers/artworkBrowser.js
Re-opening of https://github.com/artsy/force/pull/4693 (more info there) but from an upstream branch instead of a fork (I think there's some secrets not passed to forks by Circle that are now needed for Force CI).
=> @dleve123 => [Sale] Be more defensive about fetching pages > 100 during inf. scroll

src/desktop/apps/collect/client.js, src/desktop/apps/collect/server.tsx
Companion PR to https://github.com/artsy/reaction/pull/2921
This updates the collect app to properly pass A/B test across to reaction code via context.
=> [Collection] Pass COLLECT_HUBS a/b test to context

package.json, src/desktop/apps/artist/components/Meta.js, src/desktop/apps/artist/components/__tests__/Meta.jest.js, src/desktop/apps/artist/server.tsx, yarn.lock
* Reverts https://github.com/artsy/force/pull/4650
* Upgrades reaction to get this revert: https://github.com/artsy/reaction/pull/2929
To fix structured data errors. Discussion [here](https://artsy.slack.com/archives/CA8SANW3W/p1571422583451000)
=> Revert "@damassi => [Artist] Use meta tags and structured data from Reaction" and upgrade reaction

webpack/envs/baseConfig.js
This reverts commit d78859df26a127af672baf3fd2f7ea0f0ae2a538.
Now that https://github.com/artsy/reaction/pull/2926 is in, this can be re-applied.
=> [webpack] Drop graphql-js and relay network server from client bundles.

package.json, yarn.lock
Hold for https://github.com/artsy/reaction/pull/2935
=> [Lib] Remove reference to arc

src/desktop/apps/partner2/client/overview_layout_factory.coffee, src/desktop/apps/partner2/routes.coffee, src/desktop/apps/partner2/test/client/overview_layout_factory.test.coffee, src/mobile/models/partner.coffee
This PR adds a new partner layout that supports 10 shows in the hero carousel for certain partners.
=> Add a New Partner Layout

src/index.js
cc @izakp @yuki24 
This modifies the Force <-> Gravity xapp handshake to boot as normal in the event of an error, but retry every 30 seconds.
We have a bunch of pages (homepage, artist, artwork, etc.) which do not require direct requests from Force -> Gravity, so theoretically don't need an xapp token whatsoever.
Additionally, intentionally failing to boot Force is 'very bad' -> without being handled gracefully, Kubernetes will back off retries, and a cascading effect of upstream latency, Force pod deploys/kills/restarts/etc. can lead to exacerbated downtime and manually needing to bring Force pods up.
I've verified locally that partner profile pages, for example, 404 until a successful xapp token is fetched (those are older pages that rely on direct requests to Gravity). However, when an …
=> @eessex => [Xapp] If fetching an xapp token fails, retry in background but boot

src/desktop/apps/partner2/client/overview_layout_factory.coffee, src/desktop/apps/partner2/routes.coffee, src/desktop/apps/partner2/test/client/overview_layout_factory.test.coffee, src/mobile/models/partner.coffee
This PR is a follow-up to https://github.com/artsy/force/pull/4712 and adds some more layouts to the partner profile page.
=> Add New Layouts for the Partner Profile Page

hokusai/production.yml, scripts/start.sh
=> @izakp => Update mem limits for node and container

src/desktop/apps/home/client/index.coffee, src/mobile/apps/home/client/view.coffee
Addresses: [GROW-1628](https://artsyproduct.atlassian.net/browse/GROW-1628)
This PR sets up the experiment view event for both mobile and desktop. On desktop we fire the event when the user scrolls and sees the hub entry poinnts (experiment) or medium tiles (control).
=> [GROW-1628] Homepage entrypoints experiment viewed

src/desktop/analytics/main_layout.js
Adds new tracking call to auction overview pages for marketing purposes.
=> add auction pageview event for criteo

src/desktop/apps/fair/templates/sections.jade
Adjust link is currently broken, this should fix it. I'll follow up with other PRs to fix other Adjust links.
=> Updates iTunes link

src/desktop/apps/auction/__tests__/fixtures/auction.js, src/desktop/apps/auction/utils/footerItems.js, src/desktop/apps/auctions/templates/index.jade, src/mobile/components/app_banner/app_banner.coffee, src/mobile/components/artist_app_banner/index.coffee
=> Fixes remaining Adjust links

src/mobile/apps/feature/routes.coffee
addresses https://artsyproduct.atlassian.net/browse/AUCT-718
We forgot to switch the mobile view to the new confirm bid form. This PR might be easier to review with [the `w=1` trick](https://github.com/artsy/force/pull/4837/files?utf8=%E2%9C%93&diff=unified&w=1).
=> Switch to the new confirm bid view on mobile when enabled

package.json, src/desktop/components/main_layout/footer/index.styl, src/desktop/components/main_layout/footer/lower.jade, src/desktop/components/react/stitch_components/CCPARequest.tsx, src/desktop/components/react/stitch_components/index.tsx, yarn.lock
cc @joeyAghion 
This adds CCPA to the footer of the homepage only.
=> @mzikherman => [CCPA] Add CCPA link in footer

CONTRIBUTING.md, src/desktop/components/main_layout/client.coffee, src/desktop/components/main_layout/header/templates/index.jade, src/desktop/components/react/stitch_components/NavBarTest.tsx, src/desktop/components/react/stitch_components/index.tsx, src/desktop/components/split_test/running_tests.coffee
https://artsyproduct.atlassian.net/browse/GROW-1661
This sets up the A/B experiment for the desktop global nav bar.
=> [GROW-1661] Launch global nav bar experiment

package.json, src/desktop/assets/experimental-app-shell.styl, yarn.lock
- Occasional stale session info (bumped passport lib for https://github.com/artsy/artsy-passport/commit/fabd19f43cf278edd779285c22de32ada699d047)
- Include inquiry CSS in the client side routing app asset (to match the artwork app)
=> @joeyAghion => [Inquiry] Couple of fixes

README.md
[Discussed in Slack](https://artsy.slack.com/archives/C2TQ4PT8R/p1579289448007700).
=> Removes FOSSA badge. #trivial

package.json, yarn.lock
Figured I'd beat the bots, was waiting for this one :))
=> @mzikherman => [Package] Bump Reaction to 24.1.6

package.json, yarn.lock
Proper experiment viewed event name
=> @mzikherman => [Package] Bump Reaction to 24.1.7

src/desktop/apps/home/welcome.coffee
=> Updates welcome image credit

src/desktop/apps/partner2/client/overview_layout_factory.coffee, src/desktop/apps/partner2/test/client/overview_layout_factory.test.coffee
In preparation to figuring out https://artsyproduct.atlassian.net/browse/GALL-2523 - here i'm just removing redundant redirections, give sections a bit more digestible names and add `gallery_eigth` layout.
=> Refactor overview layout factory to hopefully make more sense

src/desktop/apps/purchases/server.tsx
=> I missed one line when I renamed 'purchase' to 'purchases'

package.json, src/desktop/components/inquiry_questionnaire/test/views/account.test.ts, src/desktop/components/inquiry_questionnaire/views/account.coffee, src/desktop/components/inquiry_questionnaire/views/inquiry.coffee, src/desktop/components/marketing_signup_modal/index.coffee, yarn.lock
Depends on https://github.com/artsy/reaction/pull/3113
=> Rename repcaptcha to recaptcha

src/desktop/apps/partner2/routes.coffee, src/mobile/models/partner.coffee
Can't say I understand all of that but seems like those are the places where the new layout has to be mentioned to actually take an effect.
@jonallured - tested locally. Seems to work.
=> missed several places where new layout has to be mentioned

src/desktop/components/react/stitch_components/index.tsx
Removes components that are no longer being stitched in, and adds a note about proper use and removal.
=> Remove unused stitch components

cypress/integration/artist.spec.js, package.json, src/test/acceptance/fixtures/metaphysics/artist.json, yarn.lock
Includes (mostly) the artist page facelift.
=> Bump reaction to v25.5.0

yarn.lock
This updates Force's Eigen deeplink config file, from this PR: https://github.com/artsy/artsy-eigen-web-association/pull/28
I ran `yarn upgrade artsy-eigen-web-association` and I'm not totally sure what the other changes are. Open to feedback if this is abnormal.
=> [MX-143] Updates Eigen deeplink config

package.json, yarn.lock
=> Bump reaction@25.5.3

package.json, yarn.lock
=> Bump Reaction 2

package.json, yarn.lock
=> Bump reaction@25.5.6

package.json, src/test/acceptance/collections.js, yarn.lock
Pended two `/collections` specs to get our bundle splitting out to staging. No clue how to debug error output ATM. 
@eessex - On friday I noticed that we had cypress in, and now we're back to the old acceptance tests? Looking through old PRs I don't see anything jumping out.
=> Bump reaction@25.7.0

src/desktop/components/main_layout/templates/react_blank_index.jade
=> Send to staging

.gitignore, cypress/integration/collection.spec.js, package.json, yarn.lock
Bumps palette and fixes an integration test that has changed data upstream.
=> Bump palette@7.1.0

src/desktop/lib/global_client_setup.tsx, src/lib/environment.js, src/lib/middleware/assetMiddleware.ts, webpack/envs/baseConfig.js, webpack/envs/productionConfig.js
=> [Experiment] Test fix CDN url for assets

src/desktop/lib/global_client_setup.tsx
Hard code CDN to see if ENV var is the issue, also add ability to dynamically set CDN from browser console
=> [Experiment 2]: Fix CDN Path

src/desktop/components/split_test/middleware.coffee
=> Fix A/B case

src/desktop/apps/conversations/client.tsx, src/desktop/apps/conversations/server.tsx, src/desktop/assets/conversations.tsx, src/desktop/index.js
Current way conversation app was mounted wasn't working if new app shell was turned off. 
Mount the app explicitly in force following the same pattern as what we did for `Purchases` page.
=> Add conversation app

src/desktop/components/split_test/middleware.coffee
Reading through issues I came across [this](https://github.com/skonves/express-http-context/issues/13) and thought I would give [this fix](https://github.com/skonves/express-http-context/issues/13#issuecomment-472866603) a shot to see if anything changes.
=> [Experiment 3] Bind context

src/desktop/apps/auction_support/index.coffee, src/desktop/apps/experimental-app-shell/server.tsx, src/desktop/components/split_test/middleware.coffee, src/desktop/index.js
See if the good ole `setImmediate` has any effect.
=> [Experiment 4] Check if context available next after tick

src/desktop/apps/experimental-app-shell/server.tsx
=> Remove log

package.json, src/desktop/apps/experimental-app-shell/server.tsx, src/desktop/components/split_test/middleware.coffee, src/desktop/components/split_test/skipIfClientSideRoutingEnabled.ts, yarn.lock
Ensure that if the test is false, it returns false (`??`), versus it being false and then passing to the right because of `||` operator. 
Also, backs out of previous changes that had no effect.
=> [Experiment 5] Try nullish coalescing operator 

yarn.lock
Addresses: [FX-1743](https://artsyproduct.atlassian.net/browse/FX-1743)
This updates the `artsy-eigen-web-association` app in force so that collection pages open in the iOS app for iPhone users with the app.
=> [FX-1743] update artsy-eigen-web-association app

src/mobile/components/layout/stylesheets/main_header.styl
Forgot to push the underlying content down, so the nav bar is right now covering up part of the banner! 🙈
=> Revert fix for now (covering content)

package.json, yarn.lock
=> Bump reaction@25.22.0

package.json, yarn.lock
Rolling back https://github.com/artsy/force/pull/5146. Seeing some issues with bundles on a production deploy (staging is fine).
=> Downgrade webpack

src/desktop/apps/experimental-app-shell/server.tsx, src/desktop/components/split_test/running_tests.coffee, src/desktop/components/split_test/skipIfClientSideRoutingEnabled.ts
Related: https://github.com/artsy/reaction/pull/3224
=> Update AB test name to CLIENT_NAVIGATION_V4

src/desktop/lib/global_client_setup.tsx
Adds a sentry breadcrumb for A/B test so that we can better segment issues that arise.
=> Add sentry breadcrumb

src/desktop/apps/experimental-app-shell/middleware/__tests__/userRequiredMiddleware.jest.ts
=> Remove test

src/desktop/apps/identity_verification/routes.tsx
#minor 
Completes followup comment on [[AUCT-850](https://artsyproduct.atlassian.net/browse/AUCT-850)]
=> swap minimal header on idv landing page for full header

src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.jest.tsx
Related conversation: https://artsy.slack.com/archives/C2TQ4PT8R/p1584484148006800
=> Add environment type to InfiniteScrollNewsArticle test

package.json, yarn.lock
=> Bump reaction@25.32.3

src/desktop/apps/about/client/view.coffee, src/desktop/apps/about/templates/sections/the_art_world_online.jade, src/desktop/apps/about/test/templates.test.coffee
https://artsyproduct.atlassian.net/browse/FX-1483
After:
Before:
=> Removes "Text Me a Download Link" from About page

src/desktop/apps/consign/templates/landing.jade
Drop a quick anchor so that we can link directly into faq
#trivial
=> [Consignments] Add anchor to #faq

src/desktop/apps/consign/templates/meta.jade
Fixes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=86&projectKey=CSGN&selectedIssue=CSGN-78
Updates tags per SEO recommendations:
=> CSGN-78 - Update meta tags on /consign

package.json, src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx, src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.jest.tsx, yarn.lock
Depends on https://github.com/artsy/reaction/pull/3328
Comments out news nav state updates while while we investigate why updates cause scroll position failures.
=> [HotFix] Comment out NewsNav date update

src/desktop/apps/auction_reaction/routes.tsx
=> remove contextModule from auction redirect

src/desktop/apps/art_keeps_going/client.tsx, src/desktop/apps/art_keeps_going/routes.tsx, src/desktop/apps/art_keeps_going/server.tsx, src/desktop/assets/art_keeps_going.tsx, src/desktop/index.js
Depends on https://github.com/artsy/reaction/pull/3348 (that PR also has more info on the requirements/etc.).
The force-side of this app is pretty straightforward. Note that the app is behind the `adminOnly` flag for now!
=> Adds Art Keeps Going app

src/desktop/apps/home/components/artists_to_follow/templates/index.jade, src/desktop/apps/home/components/follow_button/template.jade, src/desktop/apps/home/templates/rails.jade, src/desktop/components/artist_cell/index.jade, src/mobile/components/layout/templates/login-signup.jade
Updates for testing homepage auth entrypoints
=> #trivial - Add data-test attrs for Integrity

src/desktop/apps/art_keeps_going/server.tsx
=> Opens up art keep going page to non-admins

cypress/helpers/artworkGridRenders.js, package.json, yarn.lock
Accidentally broke integration tests with a data-attr chage, this updates references to attr and bumps reaction.
=> Fix integration tests & bump reaction

src/desktop/apps/user/pages/settings/index.jade, src/desktop/components/react/stitch_components/index.tsx
- Stitch in component from @artsy/reaction
- Guard behind admin check
=> Add user settings 2FA status/management component

src/desktop/apps/auction/components/layout/auction_info/Registration.js
follow-up for https://artsyproduct.atlassian.net/browse/AUCT-940 to fix pending registration state
=> fix registration pending case with IDV

package.json, src/desktop/analytics/inquiry_questionnaire.js, src/desktop/analytics/main_layout.js, src/desktop/apps/auction/components/layout/RegistrationModal.tsx, src/desktop/assets/analytics.coffee, yarn.lock
Related: https://github.com/artsy/reaction/pull/3407
=> [Clientside Nav] Fix referrer edgecase

src/desktop/apps/auction/__tests__/fixtures/meV1.ts, src/desktop/apps/auction/__tests__/fixtures/meV2.ts, src/desktop/apps/auction/__tests__/fixtures/saleV2.ts, src/desktop/apps/auction/__tests__/routes.jest.js, src/desktop/apps/auction/components/Layout.tsx, src/desktop/apps/auction/components/layout/ConfirmRegistrationModal.tsx, src/desktop/apps/auction/components/layout/RegistrationModal.tsx, src/desktop/apps/auction/components/layout/__tests__/ConfirmRegistrationModal.jest.tsx, src/desktop/apps/auction/components/layout/auction_info/Registration.tsx, src/desktop/apps/auction/components/layout/auction_info/__tests__/Registration.jest.js, src/desktop/apps/auction/queries/v2/me.ts, src/desktop/apps/auction/queries/v2/sale.ts, src/desktop/apps/auction/routes.js, src/lib/graphql.ts
addresses https://artsyproduct.atlassian.net/browse/AUCT-952
This PR adds a new copy for IDV sales to the registration modal.
=> Bidder sees copy in "about to register" and "registration pending" modals with information about identity verification

src/desktop/apps/consign/client/actions.js, src/desktop/apps/consign/client/reducers.js, src/desktop/apps/consign/components/upload_photo/index.js, src/desktop/apps/consign/components/upload_photo_landing/index.js, src/desktop/apps/consign/test/components.test.js
Addresses https://artsyproduct.atlassian.net/browse/CSGN-117
This PR removes the checkbox from consignment submissions that allows you to submit without uploading images. As a result, users are required to upload images for their consignment submission before they can complete it.
=> [CSGN-117] Require images for consignment submissions

src/desktop/apps/fair/components/browse/template.jade, src/desktop/apps/fair/templates/overview_top.jade, src/desktop/apps/fairs/templates/index.jade, src/desktop/apps/fairs/templates/past_fairs.jade, src/desktop/components/artwork_item/save_controls/template.jade
Related to authentication tests in integrity.
=> #trivial - Test attrs for fair/fairs integration tests

cypress/integration/home.spec.js, src/desktop/apps/home/components/artists_to_follow/templates/index.jade, src/desktop/apps/home/templates/featured_shows.jade, src/desktop/apps/home/templates/hubs_entry.jade, src/mobile/apps/home/templates/page.jade
Updates the few rails headers that live in force to use title casing to be consistent with rest
https://artsyproduct.atlassian.net/browse/MX-281
=> [MX-281] - Title casing for web home rails #trivial

src/desktop/apps/viewing-room/client.tsx, src/desktop/apps/viewing-room/server.tsx, src/desktop/assets/viewing-room.tsx, src/desktop/components/stylus_lib/index.styl, src/desktop/index.js
This is the force side of https://github.com/artsy/reaction/pull/3491.
Add new express subapp and connect the dots.
=> [ViewingRoom] Add app

src/mobile/apps/feature/routes.coffee, src/mobile/apps/feature/test/routes.test.coffee
Forgot to add this to mobile web!
Corresponding desktop PR is here: https://github.com/artsy/force/pull/5539
=> Add new feature page routing to mobile web

src/desktop/analytics/main_layout.js
Adds: 
- Campaign
- Identity Verification
cc @sweir27
=> Exclude more reaction apps from pageview tracking

src/desktop/analytics/main_layout.js
Missed the Viewing Room app from https://github.com/artsy/force/pull/5584
=> Add viewing-room to pageview exclude

package.json, yarn.lock
Addresses weird carousel bug we see occasionally around images lacking static widths: https://github.com/metafizzy/flickity/issues/691.
=> [Lib] Ensure flickity positions images correctly on load

src/desktop/apps/feature-reaction/server.tsx, src/desktop/apps/viewing-room/server.tsx
=> Removes adminOnly middleware on new feature routes

.circleci/config.yml
Updated on suspicion that the last token was revoked.
=> Update Danger GitHub API token

.circleci/config.yml, CONTRIBUTING.md, data/schema.graphql, package.json, scripts/start.sh, scripts/validateSchemas.js, src/v2/Apps/Conversation/Components/Conversation.tsx
- Updates start script to run relay
- Updates `scripts/validateSchema.js` to point at local schema vs reaction
- Updates readme
=> Some post-reaction-merge cleanup

.circleci/config.yml
Removes an unneeded workflow queue step.
=> [CI] Remove workflow queue

.storybook/webpack.config.js, webpack/envs/baseConfig.js
Attempts some webpack cleanup around our cache directories in order to reduce the chance of conflicts.
=> [Webpack] Clean up cache dirs

src/v2/Apps/ViewingRoom/Components/ViewingRoomClosed.tsx
Self merging this one once green.
=> minor: increase spacing on closed VR page

src/v2/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
Only certain browsers are compatible with our identity verification process, and right now we don't tell users what they can and cannot use. This leads users to attempting to complete the flow in an incompatible browser, resulting in a broken experience.
Add some copy explaining which browsers users can use.
Jira: https://artsyproduct.atlassian.net/browse/AUCT-1038
=> Add copy explaining which browsers are compatible for identity verification

package.json, src/desktop/apps/consign/client/__tests__/reducers.jest.ts, src/v2/Apps/Conversation/Routes/Conversation/index.tsx, yarn.lock
=> [Lib] Bump typescript to latest

src/v2/Apps/Conversation/Routes/Conversation/index.tsx
Fix ts error in conversations that slipped through master
=> Fix conversation type conflict in ts 3.9.3

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
tiny change after the discussion [here](https://artsy.slack.com/archives/C9SATFLUU/p1590685677022700).
=> use en dash

.circleci/config.yml
Tracking here: https://artsyproduct.atlassian.net/browse/PLATFORM-2395
Danger keeps failing our builds, including merge on green. Commenting out until we have a chance to look at it:
=> [CI] Comment out Danger for now

cypress/integration/partnerProfile.spec.js, src/v2/Components/Gene/__tests__/GeneRelatedLinks.jest.tsx
=> @pvinis => [Cypress] Adjust Gagosian description for profile test

docs/creating_review_app.md
=> Updates docs

src/lib/datadog.ts
This (should) fix our missing traces on wildcard routes. Pulled the solution from https://github.com/DataDog/dd-trace-js/issues/477#issuecomment-470299277.
=> [Datadog] Fix Graphql tracing on wildcard routes

src/desktop/components/main_layout/templates/blank.jade, src/desktop/components/main_layout/templates/index.jade, src/desktop/components/main_layout/templates/minimal_header.jade, src/desktop/components/main_layout/templates/redesign.jade, src/desktop/components/main_layout/templates/scripts.jade
We stopped including quantcast in [this PR](https://github.com/artsy/force/pull/3141), but we still had some references to the library.
This removes those entirely since we're no longer using the service.
=> Removes references to quantcast

src/desktop/components/react/stitch_components/NavBar.tsx, src/v2/Apps/Components/AppShell.tsx
Completes [AUCT-993](https://artsyproduct.atlassian.net/browse/AUCT-993). 
This PR adds the flash banner to the app shell, which should get it rendering on all pages.
=> add FlashBanner to AppShell

src/desktop/lib/global_client_setup.tsx
=> One more hostname fix

src/desktop/apps/auction/__tests__/routes.jest.js, src/desktop/apps/auction/__tests__/routes.jest.ts
* Specs were disabled in https://github.com/artsy/force/pull/3900
* They pass without modification now
TODO:
=> Re-enable specs in src/desktop/apps/auction/__tests__/routes.jest.js

src/desktop/apps/auctions/test/template.test.coffee
completes https://artsyproduct.atlassian.net/browse/AUCT-1080
=> enable commented out test for page without current auctions

package.json, src/v2/Apps/Conversation/Components/Details.tsx, src/v2/Components/ArtistCard.tsx, src/v2/Components/Search/Suggestions/SuggestionItem.tsx, src/v2/Components/__tests__/__snapshots__/Artwork.jest.tsx.snap, yarn.lock
=> Upgrades @artsy/palette => 11.0.x

Dockerfile
TLDR; this will significantly reduce the time spent during the `push-staging-image` step in circleci.
**Problem**
Running `chown` to reset all file permissions in a docker container is
extremely slow. At best it (certain kernels) will duplicate all file
metadata and at worse duplicate all files in a new layer.
**Solution**
Set the user earlier so files created by the container have the correct
ownership properties and use `COPY --chown` to set ownership during the
initial copy while building the image.
Previous docker build duration (local)
```
real    18m52.940s
user    0m0.590s
sys     0m0.877s
```
New docker build duration (local)
```
real    10m37.437s
user    0m0.543s
sys     0m0.900s
```
=> Remove chown from Dockerfile

src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx, src/v2/__generated__/ViewingRoomApp_UnfoundTest_Query.graphql.ts
Put up 404 page if `viewingRoom` comes back `null`. Having a hard time with the generated rawresponse in the test, any ideas/knowledge on how that works appreciated!
=> GALL-2895 Viewing room 404 when not found

data/schema.graphql, package.json, scripts/sync-schema-local.sh, scripts/sync-schema-pull.sh, src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx, src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx, src/v2/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomApp_UnfoundTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts, src/v2/__generated__/routes_ViewingRoomQuery.graphql.ts
⚠️ Connected PR on MetaPhysics https://github.com/artsy/metaphysics/pull/2477 ⚠️ 
Moving some of the copy to force from mp.
=> followup after changes on formattedEndAt on MP [GALL-2988]

cypress/integration/artist.spec.js, src/v2/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionsRail.tsx, src/v2/Apps/Artist/Components/ArtistTopWorksRail/ArtistTopWorksRail.tsx, src/v2/Apps/Artist/Components/ArtistTopWorksRail/__tests__/ArtistTopWorksRail.jest.tsx, src/v2/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx, src/v2/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx, src/v2/Apps/Artist/Routes/Overview/Components/WorksForSaleRail.tsx, src/v2/Apps/Artist/Routes/Overview/__tests__/index.jest.tsx, src/v2/Apps/Artist/Routes/Overview/index.tsx, src/v2/Apps/Artist/Routes/Works/__tests__/Works.jest.tsx, src/v2/Components/Artwork/Fillwidth.tsx, src/v2/Components/Artwork/FillwidthItem.tsx, src/v2/Components/Artwork/__tests__/Details.jest.tsx, src/v2/Components/RecentlyViewed.tsx, src/v2/Components/__stories__/Carousel.story.tsx
https://artsyproduct.atlassian.net/browse/FX-1981
https://artsyproduct.atlassian.net/browse/FX-2029
=> Make Artist Page Rails "Fully bleed" Screen on Mobile  

data/schema.graphql, package.json, scripts/sync-schema-local.sh, scripts/sync-schema-pull.sh, src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx, src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx, src/v2/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomApp_UnfoundTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts, src/v2/__generated__/routes_ViewingRoomQuery.graphql.ts
Reverts artsy/force#5810 because we will revert the one in MP
=> Revert "followup after changes on formattedEndAt on MP [GALL-2988]"

data/schema.graphql, package.json, scripts/sync-schema-local.sh, scripts/sync-schema-pull.sh, src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx, src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx, src/v2/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomApp_UnfoundTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts, src/v2/__generated__/routes_ViewingRoomQuery.graphql.ts
Exact same as #5810, but just reverting the revert because it's connected with the PR below.
⚠️ Connected PR on MetaPhysics artsy/metaphysics#2486 ⚠️
=> Revert "Revert "followup after changes on formattedEndAt on MP [GALL-2988]""

src/mobile/apps/home/routes.coffee, src/mobile/apps/home/templates/page.jade, src/mobile/apps/home/test/routes.test.coffee
=> @sweir27 => [Mobile Home] Switch to use Metaphysics V2

src/v2/Components/Authentication/Footer.tsx, src/v2/Components/Authentication/commonElements.tsx
Better target links in authentication forms for integrity. 
https://circleci.com/gh/artsy/integrity/9373#artifacts/containers/0
=> Add data attrs for integrity tests to auth form links

src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx, src/v2/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx, src/v2/__generated__/ViewingRoomCarousel_artwork.graphql.ts, src/v2/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts, src/v2/__generated__/routes_ViewingRoomWorksRouteQuery.graphql.ts
Starting a bag of minor QA items.
GALL-3016
GALL-3005
=> qa items for VR

src/v2/Apps/Conversation/Components/Conversation.tsx, src/v2/Apps/Conversation/Components/ConversationSnippet.tsx, src/v2/Apps/Conversation/Components/Message.tsx, src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx, src/v2/__generated__/Conversation_conversation.graphql.ts, src/v2/__generated__/routes_DetailQuery.graphql.ts
Fixes some of the issues reported in [PURCHASE-1977](https://artsyproduct.atlassian.net/browse/PURCHASE-1977)
There is only one thing in life worse than fixing CSS issues, and that is reviewing a CSS fix PR. Sorry 🙈 
Each fix is in a separate commit to make it easier to review. I have also added comments explaining the changes as much as I remembered it myself.
=> Conversation visual fixes - Part I

src/v2/Apps/ViewingRoom/routes.tsx
Thanks @sweir27 for the pointer:)
=> hope fixing the scroll to the bottom that happens when navigating to viewing room

src/v2/Components/NavBar/NavBar.tsx
Re: [FX-2087](https://artsyproduct.atlassian.net/browse/FX-2087)
Simple one. Didn't know there was a design for this until reviewing [FX-1821](https://artsyproduct.atlassian.net/browse/FX-1821) — so this just brings it inline with those designs.
=> [FX-2087] Styles skip to content link

package.json, src/v2/Apps/Conversation/Components/Message.tsx, src/v2/Apps/Conversation/Components/__tests__/Message.jest.tsx, yarn.lock
https://artsyproduct.atlassian.net/browse/PURCHASE-1947
https://artsyproduct.atlassian.net/browse/PURCHASE-1987
This PR implements 2 things:
The screenshot shows the message replied from my GMail, the before, and the after. More details inline.
The screenshot shows the before and after. More details inline.
=> Format conversation text and linkify links

src/lib/components/record_artwork_view/index.js
Change `record_artwork_view` to use Metaphysics v2
**Ticket/Issue Link:** https://artsyproduct.atlassian.net/browse/PLATFORM-2443
=> [P-2443] Update record_artwork_view to use Metaphysics v2

src/v2/Apps/Conversation/Components/Details.tsx
=> Add inquiry FAQ link to conversation inbox

src/v2/Apps/Conversation/Components/Reply.tsx
[PURCHASE-2003]
https://share.getcloudapp.com/OAuBNw7w
[PURCHASE-2003]: https://artsyproduct.atlassian.net/browse/PURCHASE-2003
=> Fix misspelling in error message

src/v2/Components/NavBar/Menus/NotificationsMenu.tsx, src/v2/Components/NavBar/Menus/UserMenu.tsx, src/v2/Components/NavBar/Menus/__tests__/UserMenu.jest.tsx, src/v2/Components/NavBar/NavItem.tsx, src/v2/Components/Search/SearchBar.tsx
So if you're interested [here's a little recording of navigating around the NavBar with VoiceOver](http://static.damonzucconi.com/_capture/FAKsKJ2He8kB.mov)
Also binds the `<escape>` key so that you can close out of a sub-nav if you're part of the way through without having to tab or shift+tab out of it.
=> [FX-2095]: Adds additional ARIA markup

src/v2/Apps/ArtistSeries/ArtistSeriesApp.tsx, src/v2/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx, src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesApp.jest.tsx, src/v2/Apps/ArtistSeries/routes.tsx, src/v2/Components/v2/ArtworkFilter/index.tsx, src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts, src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts, src/v2/__generated__/ArtistSeriesArtworksFilter_artistSeries.graphql.ts, src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
[FX-2009](https://artsyproduct.atlassian.net/browse/FX-2009)
---
An artist series is made up of artworks. Users want to see and interact with those artworks.
Previously, we could associate artworks with an artist series on the backend. Now, users can see artworks associated with the artist series on the artist series page and filter them.
Using our stitched `filteredArtworksConnection`, fetch all artworks associated with an artist series and display through `BaseArtworkFilter`, which gives filtering out of the box. We used the component effectively as-is.
- Unit tests test for (1) the presence of the `ArtistSeriesArtworksFilter` and (2) the presence of artworks associated with that artist series on the page.
- Tested locally. All artworks displayed and filter options and pagination work. …
=> User can see and filter artworks associated with an artist series

package.json, src/v2/Components/v2/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx, src/v2/Components/v2/ArtworkFilter/StickyContainer.tsx, src/v2/Components/v2/ArtworkFilter/index.tsx, yarn.lock
Re: [FX-1937](https://artsyproduct.atlassian.net/browse/FX-1937)
Screen recording: http://static.damonzucconi.com/_capture/SCveURgCzvGW.gif
=> [FX-1937] Implements sticky mobile filter

src/v2/Components/NavBar/Menus/DropDownMenu/DropDownMenu.tsx, src/v2/Components/NavBar/Menus/DropDownMenu/__tests__/DropDownMenu.jest.tsx
Re: [FX-2111](https://artsyproduct.atlassian.net/browse/FX-2111)
=> [FX-2111] Inserts missing href

src/v2/Apps/Conversation/Components/Conversation.tsx, src/v2/Apps/Conversation/Components/Conversations.tsx, src/v2/Apps/Conversation/Routes/Conversation/index.tsx
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-2028
Before:
=> Remove unnecessary scrollbars on inbox (especially on windows)

.circleci/config.yml
Slack: https://artsy.slack.com/archives/C02BC3HEJ/p1595522837110900
=> Temporarily remove deploy block checks

src/v2/Apps/Conversation/Components/Conversation.tsx, src/v2/Apps/Conversation/Components/Details.tsx, src/v2/Apps/Conversation/Components/InboxHeaders.tsx, src/v2/Apps/Conversation/Routes/Conversation/index.tsx
Mob paired by the purchase crew
Addresses several layout and styling issues:
- Scroll / Layout issues on small screens https://artsyproduct.atlassian.net/browse/PURCHASE-2024
- Tablet layout issues: https://artsyproduct.atlassian.net/browse/PURCHASE-2027
- and some additional layout rework!
=> Layout Adjustments for Inbox conversations

.circleci/config.yml
=> Revert "Temporarily remove deploy block checks"

src/v2/Apps/ViewingRoom/Components/ViewingRoomContentNotAccessible.tsx
=> minor spell mistake

src/v2/Apps/Conversation/ConversationApp.tsx, src/v2/Apps/Conversation/Routes/Conversation/index.tsx, src/v2/Apps/Conversation/__tests__/ConversationApp.jest.tsx, src/v2/Components/NavBar/LoggedInActions.tsx, src/v2/Components/NavBar/Menus/MobileNavMenu/LoggedInLinks.tsx, src/v2/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.jest.tsx, src/v2/Components/NavBar/NavBar.tsx, src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
[PURCHASE-1980](https://artsyproduct.atlassian.net/browse/PURCHASE-1980)
This builds off @lilyfromseattle's [PR to remove the conversations feature flag](https://github.com/artsy/force/pull/5943) and brings it up to date by resolving merge conflicts and removes tests associated with the feature flag.
DO NOT MERGE until conversations is ready for release
=> [PURCHASE-1980] Remove conversations feature flag

src/v2/Artsy/Router/RouterLink.tsx, src/v2/Components/Menu/Menu.tsx, src/v2/Components/Menu/MenuItem.tsx, src/v2/Components/NavBar/Menus/DropDownMenu/__tests__/DropDownSection.jest.tsx, src/v2/Components/NavBar/Menus/NotificationsMenu.tsx, src/v2/Components/NavBar/Menus/UserMenu.tsx, src/v2/Components/NavBar/Menus/__tests__/NotificationsMenu.jest.tsx, src/v2/Components/NavBar/__tests__/NavBar.jest.tsx, src/v2/Components/NavBar/__tests__/NavBarTracking.jest.tsx, src/v2/Components/NavBar/__tests__/NavItem.jest.tsx, src/v2/__generated__/NotificationsMenuQuery.graphql.ts, src/v2/jest.envSetup.ts
This replaces the spinner, and leans on the [new content skeleton components now available in palette](https://palette.artsy.net/elements/loaders/skeleton/)
Also improves the voiceover experience.
=> Improves loading state of notifications menu

src/v2/Components/NavBar/Menus/UserMenu.tsx, src/v2/Components/NavBar/NavBar.tsx, src/v2/Components/NavBar/NavItem.tsx, src/v2/Components/NavBar/NavItemPanel.tsx, src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
Re: [FX-1820](https://artsyproduct.atlassian.net/browse/FX-1820)
Also sneaking in an update that makes the mobile nav bar accessible to Voiceover on iOS.
=> [FX-1820] Artists/Artworks clickable, mobile nav a11y

src/desktop/analytics/consignments.js, src/desktop/apps/consign/client/__tests__/analyticsMiddleware.jest.ts, src/desktop/apps/consign/client/analytics_middleware.ts
Supports https://artsyproduct.atlassian.net/browse/PLATFORM-2688
=> Remove deprecated web triggers

src/v2/Apps/Conversation/Components/Message.tsx
Fixes [PURCHASE-2044](https://artsyproduct.atlassian.net/browse/PURCHASE-2044)
**Before:**
**After:**
=> [PURCHASE-2044] Fix collector file attachment

src/v2/Apps/Feature/Components/FeatureMeta.tsx, src/v2/Apps/Feature/__tests__/fixtures.ts, src/v2/__generated__/FeatureApp_Test_Query.graphql.ts, src/v2/__generated__/FeatureMeta_feature.graphql.ts, src/v2/__generated__/routes_FeatureQuery.graphql.ts
Re: [FX-2126](https://artsyproduct.atlassian.net/browse/FX-2126)
(https://github.com/artsy/metaphysics/pull/2570 is in production now)
=> [FX-2126] Utilizes Feature#meta fields in meta tags

src/desktop/apps/consign/client/__tests__/analyticsMiddleware.jest.ts, src/desktop/apps/consign/client/analytics_middleware.ts
Supports https://artsyproduct.atlassian.net/browse/PLATFORM-2688
=> Fix events operating under the incorrect hook naming

src/v2/Apps/Search/Components/NavigationTabs.tsx
Two fixes!
One, moves the underscore'ing 'up' a level, so only the tab name itself is modified (and not the whole URL, which includes that query term).
Second, even though search results are suppressed from Gravity without the lab feature...the aggregations (the tab name + count) might still show up. So we need to explicitly hide that tab w/ the lab feature check.
=> @sweir27 => [Search] Dont underscore query term, suppress artist series tab w/o lab feature

src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx, src/v2/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomApp_LoggedOutTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomApp_ScheduledTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomApp_UnfoundTest_Query.graphql.ts, src/v2/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts, src/v2/__generated__/routes_ViewingRoomQuery.graphql.ts
Resolves [GALL-3192]
Adding a link around the gallery name.
https://f.p0l.co/file/dropshare-public-pavlos/Screen-Recording-2020-08-11-at-19.19.00.mov
[GALL-3192]: https://artsyproduct.atlassian.net/browse/GALL-3192
=> Make gallery name clickable in VR

src/v2/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx, src/v2/Components/NavBar/Menus/MoreNavMenu.tsx, src/v2/Components/NavBar/Menus/__tests__/MoreNavMenu.jest.tsx, src/v2/Components/NavBar/NavBar.tsx, src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
=> GALL-3184 Remove references to viewing room feature flag

package.json, webpack/envs/clientProductionConfig.js, webpack/envs/serverConfig.js, webpack/utils/env.js, yarn.lock
Description
Webpack minification if significantly faster locally when parallel is
enabled and should be slightly faster when run in CI.
=> Parallel Minification

src/v2/Apps/Feature/Components/FeatureFeaturedLink.tsx, src/v2/Apps/Feature/Components/FeatureHeader/FeatureHeaderDefault.tsx, src/v2/Apps/Feature/Components/FeatureHeader/FeatureHeaderFull.tsx, src/v2/__generated__/FeatureApp_Test_Query.graphql.ts, src/v2/__generated__/FeatureFeaturedLink_featuredLink.graphql.ts, src/v2/__generated__/FeatureHeaderDefault_feature.graphql.ts, src/v2/__generated__/FeatureHeaderFull_feature.graphql.ts, src/v2/__generated__/routes_FeatureQuery.graphql.ts
Re: [FX-2158](https://artsyproduct.atlassian.net/browse/FX-2158)
The fallback isn't strictly necessary but `main` version isn't on staging, so this works.
=> [FX-2158] Prefers main, fallback to wide

src/v2/Components/NavBar/NavItem.tsx
Very minor thing — thanks @nicoleyeo
=> Adjusts NavBar NavItem focus state

src/v2/Apps/ArtistSeries/ArtistSeriesApp.tsx, src/v2/Apps/ArtistSeries/Components/ArtistSeriesMeta.tsx, src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesApp.jest.tsx, src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesMeta.jest.tsx, src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts, src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts, src/v2/__generated__/ArtistSeriesApp_artistSeries.graphql.ts, src/v2/__generated__/ArtistSeriesMeta_TestQuery.graphql.ts, src/v2/__generated__/ArtistSeriesMeta_artistSeries.graphql.ts, src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/FX-2027
Other platforms (search engines, social media, etc) need to be able to easily parse our site's content so that users can find it.
Add `meta` tags that give title and description for search and social media.
=> Add meta tags for artist series

src/v2/Apps/Fair/Components/FairHeader.tsx, src/v2/Apps/Fair/FairApp.tsx, src/v2/Apps/Fair/__tests__/FairApp.jest.tsx, src/v2/Apps/Fair/routes.tsx, src/v2/Apps/getAppRoutes.tsx, src/v2/__generated__/FairApp_Query.graphql.ts, src/v2/__generated__/FairApp_fair.graphql.ts, src/v2/__generated__/FairHeader_fair.graphql.ts, src/v2/__generated__/routes_FairQuery.graphql.ts
Addresses: https://artsyproduct.atlassian.net/browse/FX-2167
This PR adds a basic page making a simple graphQL query at the /fair2 route so we can get started adding the rest of the functionality of the page.
It's... sort of responsive, but I didn't go in-depth to match the spec as we have other tickets for that!
=> Adds /fair2 route and basic page

src/v2/Apps/Fair/Components/FairEditorial/FairEditorial.tsx, src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx, src/v2/Apps/Fair/Components/FairEditorial/index.ts, src/v2/Apps/Fair/Components/FairHeader.tsx, src/v2/Apps/Fair/Routes/FairOverview.tsx, src/v2/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx, src/v2/__generated__/FairEditorialItem_article.graphql.ts, src/v2/__generated__/FairEditorial_fair.graphql.ts, src/v2/__generated__/FairOverview_Query.graphql.ts, src/v2/__generated__/routes_FairOverviewQuery.graphql.ts
Re: [FX-2171](https://artsyproduct.atlassian.net/browse/FX-2171)
=> [FX-2171] Display fair editorial

src/v2/Apps/Fair/Components/FairHeader.tsx, src/v2/Apps/Fair/Components/__tests__/FairHeader.jest.tsx, src/v2/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx, src/v2/__generated__/FairHeader_Query.graphql.ts, src/v2/__generated__/FairHeader_fair.graphql.ts, src/v2/__generated__/FairOverview_Query.graphql.ts, src/v2/__generated__/routes_FairOverviewQuery.graphql.ts
=> @sweir27 => [Fair] Overlay profile icon onto header

src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx, src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesApp.jest.tsx, src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts, src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts, src/v2/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts, src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
Gah, I didn't notice before, but by using the `resizer` helper we'd sometimes end up resizing a low-res version of the image, so bumping it to 1200 px didn't matter.
This PR updates to use metaphysics' helpers, which I think are cleaner anyways.
=> Fixes image resolution (again)

src/desktop/analytics/artwork.js
Supports https://artsyproduct.atlassian.net/browse/PLATFORM-2691
Review App: https://artwork-js.artsy.net/
=> Remove unused events

src/v2/Apps/ViewingRoom/Components/ViewingRoomsMeta.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomsApp.jest.tsx
=> [GALL-3228] - adding description to viewingRooms page

src/v2/Apps/Artist/Components/ArtistTopWorksRail/ArtistTopWorksRail.tsx, src/v2/Apps/Artwork/Components/ArtworkArtistSeries/ArtistSeriesArtworkRail.tsx, src/v2/Components/Artwork/Details.tsx, src/v2/Components/Artwork/FillwidthItem.tsx, src/v2/Components/Artwork/Metadata.tsx, src/v2/Components/Artwork/__tests__/Details.jest.tsx, src/v2/Components/__tests__/__snapshots__/Artwork.jest.tsx.snap
=> Updates artwork details typography

src/v2/Apps/Fair/Components/FairExhibitorRail/FairExhibitorRail.tsx, src/v2/Apps/Fair/Components/FairExhibitorRail/FairExhibitorRailArtworks.tsx, src/v2/Apps/Fair/Components/FairExhibitorRail/FairExhibitorRailPlaceholder.tsx, src/v2/Apps/Fair/Components/FairExhibitorRail/index.ts, src/v2/Apps/Fair/Routes/FairExhibitors.tsx, src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx, src/v2/Apps/Fair/Routes/__tests__/FairInfo.jest.tsx, src/v2/Utils/Hooks/useLazyLoadComponent.tsx, src/v2/__generated__/FairExhibitorRailArtworksQuery.graphql.ts, src/v2/__generated__/FairExhibitorRailArtworks_show.graphql.ts, src/v2/__generated__/FairExhibitorRail_show.graphql.ts, src/v2/__generated__/FairExhibitors_Query.graphql.ts, src/v2/__generated__/FairExhibitors_fair.graphql.ts
Re: [FX-2179](https://artsyproduct.atlassian.net/browse/FX-2179)
=> [FX-2179] Fair exhibitor rails

src/v2/Apps/Artist/Routes/Works/__tests__/Works.jest.tsx, src/v2/Apps/Artist/Routes/Works/index.tsx, src/v2/Apps/Artist/routes.tsx, src/v2/Apps/ArtistSeries/ArtistSeriesApp.tsx, src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesApp.jest.tsx, src/v2/Apps/Artwork/ArtworkApp.tsx, src/v2/Apps/Artwork/Components/ArtworkArtistSeries/index.tsx, src/v2/Apps/Artwork/Components/OtherWorks/index.tsx, src/v2/Apps/Artwork/Components/__tests__/ArtworkArtistSeries.jest.tsx, src/v2/Apps/Artwork/routes.tsx, src/v2/__generated__/ArtworkApp_artwork.graphql.ts, src/v2/__generated__/ArtworkArtistSeries_Query.graphql.ts, src/v2/__generated__/ArtworkArtistSeries_artwork.graphql.ts, src/v2/__generated__/OtherWorksQuery.graphql.ts, src/v2/__generated__/OtherWorks_artwork.graphql.ts, src/v2/__generated__/Works_Test_Query.graphql.ts, src/v2/__generated__/Works_artist.graphql.ts, src/v2/__generated__/routes_ArtworkQuery.graphql.ts, src/v2/__generated__/routes_WorksQuery.graphql.ts
Tracked as: https://artsyproduct.atlassian.net/browse/FX-2153
This PR removes references to the artist series lab feature.
When it is merged and deployed... the feature will be launched!
=> FX-2153: Removes references to the Artist Series lab feature

scripts/validateSchemas.js
As discussed, it would be helpful if developer tooling didn't require introspection to be enabled in production. Luckily, the released Metaphysics schema is already available in the `release` branch's `_schema[V2].graphql` file. The script can even be simplified by not having to marshal between JSON and graphql formats.
=> Load schema from staging/release branch instead of live environment

src/mobile/apps/fair_info/test/routes.test.js, src/v2/Apps/Fair/Components/FairExhibitorRail/FairExhibitorRailArtworks.tsx, src/v2/Apps/Fair/Routes/FairExhibitors.tsx, src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx, src/v2/__generated__/FairExhibitorsQuery.graphql.ts, src/v2/__generated__/FairExhibitors_fair.graphql.ts, src/v2/__generated__/routes_FairExhibitorsQuery.graphql.ts
Re: [FX-2180](https://artsyproduct.atlassian.net/browse/FX-2180)
=> [FX-2180] Wires up exhibitor rails pagination

Dockerfile
This line no longer actually does anything w/ permissions, just removing it to clean up
=> Remove incorrect comment [skip ci]

src/desktop/apps/sitemaps/index.coffee, src/desktop/apps/sitemaps/routes.coffee, src/desktop/apps/sitemaps/test/routes.test.js
This will expose our artist series sitemap.
=> Add artist series sitemap to robots.txt

cypress.json, package.json, yarn.lock
- Major update of cypress lib to 5.1.0
- Add 3 retry attempts on failure. 
https://artsyproduct.atlassian.net/browse/PLATFORM-2794
=> Use Cypress 5

src/desktop/apps/show/client/index.coffee, src/desktop/apps/show/components/artwork_columns_metaphysics/template.jade, src/desktop/apps/show/components/artwork_columns_metaphysics/view.coffee, src/desktop/apps/show/components/flickity_zoom_sequence/view.coffee, src/desktop/apps/show/components/related_articles/view.coffee, src/desktop/apps/show/routes.coffee
Updates the `/show/:id` app to use the v2 Metaphysics schema for the following queries:
- Fetching artworks
- Paginating artworks (to do infinite scroll)
- Fetching related articles
- Fetching "install shots"
=> @ansor4 => [Desktop Show] Update to use Metaphysics V2(GALL-2974)

docs/creating_review_app.md
=> Fix bad link on review app doc.

src/v2/Apps/Fair/Components/FairCollections.tsx, src/v2/Apps/Fair/Components/FairHeader.tsx, src/v2/Apps/Fair/FairApp.tsx, src/v2/Apps/Fair/__tests__/FairApp.jest.tsx, src/v2/__generated__/FairApp_Query.graphql.ts, src/v2/__generated__/FairApp_fair.graphql.ts, src/v2/__generated__/FairCollections_fair.graphql.ts, src/v2/__generated__/routes_FairQuery.graphql.ts
Re: [FX-2174](https://artsyproduct.atlassian.net/browse/FX-2174)
There wasn't much too this and just wiring it up to the actual data was easier than not, so I just went ahead and did that.
There's some clean up in palette to do, and a bit of clean up in the header info to do (match the grids) — it'd be nice to export a maxWidth column width helper to assist with layouts such as this.
Desktop:
Mobile:
=> Implements fair "Curated highlights"

package.json, src/v2/Apps/Fair/Components/FairCollections.tsx, yarn.lock
Picking up small issue from https://github.com/artsy/force/pull/6264 and https://github.com/artsy/palette/pull/776
=> Supports retina images in card

src/desktop/apps/home/stylesheets/featured_items.styl, src/desktop/apps/home/templates/browse.jade, src/desktop/apps/home/templates/featured_articles.jade, src/desktop/apps/home/templates/featured_shows.jade, src/desktop/apps/home/templates/hubs_entry.jade, src/mobile/apps/home/stylesheets/current_shows.styl, src/mobile/apps/home/stylesheets/hero_units.styl, src/mobile/apps/home/stylesheets/index.styl, src/mobile/apps/home/templates/page.jade, src/mobile/components/artwork_columns/index.styl, src/mobile/components/layout/stylesheets/buttons.styl, src/mobile/components/layout/stylesheets/footer.styl, src/mobile/components/layout/stylesheets/headers.styl
@deliciousnachos reviewed these screenshots ✅ 
[Click here for giant scroll](https://static.damonzucconi.com/_capture/mlPEPipXluq8.png)
=> [Typography] Mobile homepage conversion

src/mobile/apps/art_fairs/index.styl, src/mobile/apps/art_fairs/templates/past-fairs.jade, src/mobile/apps/auctions/index.styl, src/mobile/apps/auctions/templates/index.jade, src/mobile/components/avant_garde_tabs/index.styl
Addresses https://www.notion.so/artsy/Web-Type-Clean-up-94cae3cc227243e2a44128b315e65046?p=ea7ef77af13b4c5ab79e1999723e6ba6
Signed off by @nicoleyeo ✅ 
Updates the Auctions mobile landing as follows:
- Updates page title, mobile tabs (globally), auction list items
- Updates zero state
- Updates logged-out state
- Converts colors and spaces to Palette helpers
And then for good measure... I do it all again for Fairs. Working on both of these allowed me to see similar conditional states and cleanup opportunities that I had missed the first time around on https://github.com/artsy/force/pull/6283, so that all gets touched up in this PR as well.
|Current|Upcoming|Past|
|---|---|---|
|<img width="200" src="https://user-images.githubusercontent.com/140521/93634178-2f3f4700-f9be-11ea-95ac-976e0b50a …
=> [Typography] Update mobile auctions landing page (and fix fairs)

src/desktop/apps/home/components/new_for_you/index.styl, src/desktop/components/fair_layout/stylesheets/dark.styl, src/desktop/components/fair_layout/stylesheets/nav.styl
Fixes two minor issues
* Converts "New for you" pop up button
* Fixes inverted color scheme for login buttons on fair pages
=> [Typography] "New for you", Fair login buttons

src/desktop/components/clock/index.styl, src/desktop/components/clock/view.coffee, src/mobile/apps/fair_info/test/routes.test.js
=> Tweaks to legibility of auction clock

CONTRIBUTING.md
I've found this helpful over the last few weeks.
=> @damassi => [Documentation] Add note about incognito browser

package.json, src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx, src/v2/Apps/Feature/Components/FeatureFeaturedLink.tsx, yarn.lock
Re: [FX-2245](https://artsyproduct.atlassian.net/browse/FX-2245)
=> [FX-2245] Artist series description truncation

src/v2/Apps/Artist/Components/ArtistHeader.tsx
Should fix the failing integrity spec.
=> Puts back data-test attr for desktop

src/v2/Apps/IdentityVerification/IdentityVerificationApp/WrongOwner.tsx, src/v2/Apps/IdentityVerification/IdentityVerificationApp/index.tsx, src/v2/Apps/IdentityVerification/__fixtures__/routes_IdentityVerificationAppQuery.ts, src/v2/Apps/IdentityVerification/__tests__/IdentityVerificationApp.jest.tsx, src/v2/__generated__/IdentityVerificationAppTestQuery.graphql.ts, src/v2/__generated__/IdentityVerificationApp_me.graphql.ts, src/v2/__generated__/routes_IdentityVerificationAppQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/AUCT-1225
=> display error message, not 404, when IDV user doesn't match logged-in user

.eslintrc.js, src/desktop/assets/analytics.ts, src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx, src/v2/Artsy/Relay/middleware/metaphysicsExtensionsLoggerMiddleware.ts, src/v2/Components/__stories__/Gene.story.tsx, src/v2/Components/__stories__/ModalDialog.story.tsx, src/v2/Components/__stories__/Tag.story.tsx, src/v2/Utils/__tests__/logger.jest.ts
Addresses: [PURCHASE-2130](https://artsyproduct.atlassian.net/browse/PURCHASE-2130)
Follow up to https://github.com/artsy/force/pull/6285/files/c37df7d74f4e60b9dc0e008761fa38793dfa47a4
=> [PURCHASE-2130] follow up on addressing eslint no-console rules

src/v2/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
https://artsyproduct.atlassian.net/browse/AUCT-1233
=> chore: update copy on ID verification landing page

src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromArtsy.tsx, src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx, src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
=> Includes HTML styling on ReadMore instances

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/FollowedArtistsFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/FollowedArtistsFilter.jest.tsx
Fixes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=FX&modal=detail&selectedIssue=FX-2311
Pretty simple!
=> @sweir27 => [Filter] Disable followedArtistsFilter if there are no results

src/v2/Apps/Order/Components/StickyFooter.tsx, src/v2/Apps/Order/Components/__tests__/StickyFooter.jest.tsx, src/v2/Apps/Order/__tests__/OrderApp.jest.tsx
Addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-2075
Updates the call to action text and links user to our help center from the orders flow
=> [PURCHASE-2075] Update FAQ to link to help center

src/v2/Apps/Fair/Components/FairHeader/FairHeader.tsx, src/v2/Apps/Fair/Components/FairHeader/FairHeaderImage.tsx, src/v2/Apps/Fair/Components/__tests__/FairHeader.jest.tsx, src/v2/Apps/Fair/__tests__/FairApp.jest.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx, src/v2/__generated__/FairApp_Query.graphql.ts, src/v2/__generated__/FairHeaderImage_fair.graphql.ts, src/v2/__generated__/FairHeader_Query.graphql.ts, src/v2/__generated__/routes_FairQuery.graphql.ts
Closes [FX-2323](https://artsyproduct.atlassian.net/browse/FX-2323)
=> [FX-2323] Improves handling of fair hero image

package.json, src/desktop/apps/article/components/App.tsx, src/desktop/apps/article/components/InfiniteScrollArticle.tsx, src/desktop/apps/article/components/layouts/Article.tsx, src/desktop/apps/article/components/layouts/Classic.tsx, src/desktop/apps/articles/components/App.tsx, yarn.lock
- Remove `openAuthModal ` prop from Articles
- Send mediator to Article with `SystemContext`
Depends on https://github.com/artsy/reaction/pull/3627
https://artsyproduct.atlassian.net/browse/PLATFORM-2775
=> Use updated Reaction follow buttons

src/v2/Apps/Fair/Components/FairCollections/FairCollection.tsx, src/v2/Apps/Fair/Components/__tests__/FairCollection.jest.tsx, src/v2/Apps/Fair/__tests__/FairApp.jest.tsx, src/v2/__generated__/FairApp_Query.graphql.ts, src/v2/__generated__/FairCollection_Query.graphql.ts, src/v2/__generated__/FairCollection_collection.graphql.ts, src/v2/__generated__/routes_FairQuery.graphql.ts
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=FX&modal=detail&selectedIssue=FX-2313
Looks like
=> @sweir27 => [Fair] Tweak display of collections to include count of works

src/desktop/apps/fairs/query.coffee, src/desktop/apps/fairs/routes.coffee
https://artsyproduct.atlassian.net/browse/FX-2329
Keeping it simple, just changing the query, and aliasing fields as necessary.
=> chore: switch fairs landing query to MP v2

src/v2/Apps/Artwork/ArtworkApp.tsx
Underlying bug was fixed in Palette [v13.7.4](https://github.com/artsy/palette/releases/tag/v13.7.4)
=> Removes hack to force re-rendering of ArtworkDetails

src/v2/Apps/IdentityVerification/Error.tsx, src/v2/Apps/IdentityVerification/__tests__/routes.jest.tsx, src/v2/Apps/IdentityVerification/routes.tsx
https://artsyproduct.atlassian.net/browse/AUCT-1238
update Jumio's Error URL to https://www.artsy.net/identity-verification/error
[Jumio settings](https://customer-portal.netverify.com/#/settings/application-settings/general)
=> feat:Add error page to IdentityVerification app #MIGRATION

src/v2/Apps/Show/ShowApp.tsx, src/v2/Apps/Show/__tests__/ShowApp.jest.tsx, src/v2/Apps/Show/__tests__/ShowInstallShots.jest.tsx, src/v2/Apps/Show/components/ShowInstallShots.tsx, src/v2/__generated__/ShowApp_show.graphql.ts, src/v2/__generated__/ShowInstallShots_show.graphql.ts, src/v2/__generated__/routes_ShowQuery.graphql.ts
Closes: [FX-2191](https://artsyproduct.atlassian.net/browse/FX-2191)
Nothing fancy (yet) for the modal view, just displays a larger version of the image, backdropped.
=> [FX-2191] Implements installation shot carousel

src/mobile/apps/art_fairs/client/art_fairs.coffee, src/mobile/apps/art_fairs/query.coffee, src/mobile/apps/art_fairs/routes.coffee
Keeping it simple by aliasing fields as necessary.
Jira :lock: : https://artsyproduct.atlassian.net/browse/FX-2330
=> chore(FX-2330): Migrate mWeb /art_fairs to Metaphysics V2

src/v2/Apps/Show/ShowApp.tsx, src/v2/Apps/Show/__tests__/ShowContextualLink.jest.tsx, src/v2/Apps/Show/components/ShowContextualLink.tsx, src/v2/__generated__/ShowApp_show.graphql.ts, src/v2/__generated__/ShowContextualLink_show.graphql.ts, src/v2/__generated__/routes_ShowQuery.graphql.ts
Will add a spec. 
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=FX&modal=detail&selectedIssue=FX-2190
=> @dzucconi => [Show] Add contextual link

src/mobile/apps/fair/test/client/exhibitors.test.js, src/v2/Apps/Fair/Components/FairHeader/FairHeader.tsx, src/v2/Apps/Show/components/ShowInstallShots.tsx, src/v2/Components/EventTiming.tsx, src/v2/Components/Links/ForwardLink.tsx, src/v2/Components/WithCurrentTime.tsx, src/v2/Utils/Hooks/__tests__/useEventTiming.jest.tsx, src/v2/Utils/Hooks/useCurrentTime.tsx, src/v2/Utils/Hooks/useEventTiming.tsx
Mostly minor refactorings I'm pulling off my working branch. The hooks remain basically the same, just extracted so that they are a bit more flexible. There's two minor bugs I fixed in the event timing hook, that I'll point out inline.
=> [FX-2192] Maintenance supporting show info header

src/mobile/apps/articles/test/client/articles.test.js
=> bugfix: Fix leaky magazine test

src/mobile/apps/fair/test/client/feed.test.js
Erroneously failing, https://app.circleci.com/pipelines/github/artsy/force/9810/workflows/59454867-7d76-4671-af60-538af7877955/jobs/67213
See context here: https://github.com/artsy/force/pull/6440
=> bugfix: cleanup flakey Fair feed test

src/v2/Apps/Show/ShowApp.tsx, src/v2/Apps/Show/__tests__/ShowApp.jest.tsx, src/v2/Apps/Show/__tests__/ShowArtworks.jest.tsx, src/v2/Apps/Show/components/ShowArtworks.tsx, src/v2/Apps/Show/routes.tsx, src/v2/Components/v2/ArtworkFilter/index.tsx, src/v2/__generated__/ShowArtworksQuery.graphql.ts, src/v2/__generated__/ShowArtworks_Query.graphql.ts, src/v2/__generated__/ShowArtworks_show.graphql.ts, src/v2/__generated__/routes_ShowQuery.graphql.ts
Pretty straightforward at this point! 😅 
Only sort of repeated/annoying thing are the GraphQL fragment arguments. Those have to be included at every fragment definition.
=> @dzucconi => [Show] Add artworks filter

src/mobile/apps/fair/test/client/for_you.test.js, src/mobile/apps/fair/test/client/main_page.test.js, src/mobile/components/article/test/view.test.js
=> bugfix: fix backbone/jquery flake in mocha tests

src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
=> Corrects casing, fixes build

src/v2/Apps/Show/Components/ShowAbout.tsx, src/v2/Apps/Show/Components/ShowArtworks.tsx, src/v2/Apps/Show/Components/ShowInfoLocation.tsx, src/v2/Apps/Show/Components/ShowInstallShots.tsx, src/v2/Apps/Show/Components/ShowPartnerEntityHeader.tsx, src/v2/Apps/Show/Routes/ShowInfo.tsx, src/v2/Apps/Show/ShowApp.tsx, src/v2/Apps/Show/ShowSubApp.tsx, src/v2/Apps/Show/__tests__/ShowApp.jest.tsx, src/v2/Apps/Show/__tests__/ShowInfo.jest.tsx, src/v2/Apps/Show/routes.tsx, src/v2/__generated__/ShowAbout_show.graphql.ts, src/v2/__generated__/ShowApp_Test_Query.graphql.ts, src/v2/__generated__/ShowApp_show.graphql.ts, src/v2/__generated__/ShowInfoLocation_show.graphql.ts, src/v2/__generated__/ShowInfo_Test_Query.graphql.ts, src/v2/__generated__/ShowInfo_show.graphql.ts, src/v2/__generated__/ShowInstallShots_show.graphql.ts, src/v2/__generated__/ShowPartnerEntityHeader_partner.graphql.ts, src/v2/__generated__/ShowSubApp_show.graphql.ts, src/v2/__generated__/routes_ShowInfoQuery.graphql.ts, src/v2/__generated__/routes_ShowQuery.graphql.ts, src/v2/__generated__/routes_ShowSubAppQuery.graphql.ts
Closes: [FX-2206](https://artsyproduct.atlassian.net/browse/FX-2206)
=> [FX-2206] Show info page

package.json, webpack/envs/clientDevelopmentConfig.js, yarn.lock
Let's see if this works on those occasional issues!
=> @damassi => [Dev] Add plug in to warn about case insensitive imports

src/mobile/apps/fair/test/client/for_you.test.js
=> bugfix: move backbone jquery declaration in flakey test

package.json, src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx, yarn.lock
Closes: [FX-2289](https://artsyproduct.atlassian.net/browse/FX-2289)
https://github.com/artsy/palette/pull/797 restores white-space in cells.
------
------
=> [FX-2289] Fixes collection rail text overflow

src/v2/Apps/Feature/__tests__/fixtures.ts
Re: https://github.com/artsy/force/pull/6475
This update to the Metaphysics schema is breaking this one spec. I'd rather update this to the mock generator but just quickly updating the field for the time being.
=> Returns string for non-nullable field

src/v2/Apps/Fair/FairApp.tsx, src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
https://artsyproduct.atlassian.net/browse/FX-2375
Trivial text updates…
=> fix: update labels for fair page sections

src/v2/Apps/Consign/ConsignApp.tsx, src/v2/Apps/Consign/consignRoutes.tsx, src/v2/Apps/getAppRoutes.tsx, src/v2/Artsy/Router/useRouter.tsx, src/v2/__generated__/ConsignApp_artist.graphql.ts, src/v2/__generated__/consignRoutes_ArtworkQuery.graphql.ts
This adds a new `/consign2` app to Force, in prep for the consign page build out that begins tomorrow.
=> feature: [Consign2] Add consign2 route

src/v2/Apps/Artist/Components/ArtistMetaCanonicalLink.tsx, src/v2/Apps/Artist/Components/__tests__/ArtistMetaCanonical.jest.tsx, src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignMeta.tsx, src/v2/Apps/Artist/Routes/Consign/Components/__tests__/ArtistConsignMeta.jest.tsx
Trying this again from a feature branch.
https://artsyproduct.atlassian.net/browse/GRO-10
=> GRO-10: Improve artist canonical link computation

src/v2/Apps/Consign/Components/ConsignMeta.tsx, src/v2/Apps/Consign/Components/ContactUs.tsx, src/v2/Apps/Consign/Components/FAQ.tsx, src/v2/Apps/Consign/Components/GetPriceEstimate.tsx, src/v2/Apps/Consign/Components/Header.tsx, src/v2/Apps/Consign/Components/HowToSell.tsx, src/v2/Apps/Consign/Components/InDemandNow/ConsignInDemandNow.tsx, src/v2/Apps/Consign/Components/InDemandNow/ConsignTopArtists.tsx, src/v2/Apps/Consign/Components/ReadMore.tsx, src/v2/Apps/Consign/Components/SellArtDifferently.tsx, src/v2/Apps/Consign/Components/SellWithArtsy.tsx, src/v2/Apps/Consign/Components/SoldRecently.tsx, src/v2/Apps/Consign/ConsignApp.tsx, src/v2/__generated__/ConsignInDemandNowQuery.graphql.ts, src/v2/__generated__/ConsignTopArtistsQuery.graphql.ts
Not the prettiest thing but this roughs in the basic structure, queries, etc. We now need to go section by section and bring it up to spec.
=> iteration: [Consign 2] Add basic structure structure to app 

scripts/start.sh
Do not start in `inspect-brk` mode, start in `inspect` mode if possible.
=> fix: Start Inspect

src/mobile/apps/fair/index.coffee
Follow-up to https://github.com/artsy/force/pull/6373
Resolves [FX-2384]
[FX-2384]: https://artsyproduct.atlassian.net/browse/FX-2384
=> fix: apply new fair redirection logic to mobile fair app

package.json, src/lib/setup.js, yarn.lock
This upgrades fresnel with some nice perf improvements from [this PR](https://github.com/artsy/fresnel/pull/158). 
@dzucconi - would you mind pulling this PR down and giving it a little spin before merging? I've clicked around and everything looks good but a second set of eyes would be nice.
=> lib: Upgrade @artsy/fresnel@1.3.0

src/v2/Apps/ViewingRoom/Components/ViewingRoomsLatestGrid.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomsApp.jest.tsx, src/v2/__generated__/ViewingRoomsApp_Test_Query.graphql.ts, src/v2/__generated__/ViewingRoomsLatestGrid_ViewingRoomsAppQuery.graphql.ts, src/v2/__generated__/ViewingRoomsLatestGrid_viewingRooms.graphql.ts, src/v2/__generated__/routes_ViewingRoomsAppQuery.graphql.ts
Meant to address this on https://github.com/artsy/force/pull/6547 so just a follow up here.
=> Uses appropriate image versions for small thumbs on viewing room cards

src/v2/Apps/Fair/FairApp.tsx, src/v2/Apps/Fair/FairSubApp.tsx, src/v2/Apps/Fair/__tests__/FairApp.jest.tsx, src/v2/Apps/Fair/__tests__/FairSubApp.jest.tsx, src/v2/__generated__/FairApp_Query.graphql.ts, src/v2/__generated__/FairApp_fair.graphql.ts, src/v2/__generated__/FairSubApp_Query.graphql.ts, src/v2/__generated__/FairSubApp_fair.graphql.ts, src/v2/__generated__/routes_FairQuery.graphql.ts, src/v2/__generated__/routes_FairSubAppQuery.graphql.ts
Re: [FX-2395](https://artsyproduct.atlassian.net/browse/FX-2395)
This is more of just a quick hack to address the symptom.
=> [FX-2395] Hide fairs with hidden profiles for non-admins

src/v2/Apps/Artist/Routes/Consign/Components/SectionContainer.tsx, src/v2/Apps/Consign/Components/ContactUs.tsx, src/v2/Apps/Consign/Components/FAQ.tsx, src/v2/Apps/Consign/Components/InDemandNow/DemandRank.tsx, src/v2/Apps/Consign/Components/ReadMore.tsx, src/v2/Apps/Consign/Components/SectionContainer.tsx, src/v2/Apps/Consign/Components/SellWithArtsy.tsx, src/v2/Apps/Consign/Components/SoldRecently.tsx, src/v2/Apps/Consign/ConsignApp.tsx
This adds the Articles, Ask a Specialist, FAQ and Sell with artsy sections.
Follow-up:
- Move new toggle to Palette 
- Confirm that we're using different / double ask specialist sections 
=> feat: [Consign2] Add remaining sections 

src/v2/Apps/Show/Components/ShowContextCard.tsx, src/v2/Apps/Show/Components/ShowViewingRoom.tsx, src/v2/Apps/Show/__tests__/ShowContextCard.jest.tsx, src/v2/Apps/Show/__tests__/ShowViewingRoom.jest.tsx
=> Adds action types to show2 tracking events

src/desktop/apps/partner2/client/shows_grid.coffee, src/desktop/apps/partner2/test/client/shows_grid.test.js
Closes: [FX-2326](https://artsyproduct.atlassian.net/browse/FX-2326)
[Screen recording of problem partner example](https://static.damonzucconi.com/_capture/WZG1IWu6BAXl.gif)
=> fix(partner/shows): fix partner show fetch for partners with >100 shows

src/v2/Apps/Consign/Components/GetPriceEstimate/ArtistInsightResult.tsx, src/v2/Apps/Consign/Components/GetPriceEstimate/ConsignArtistAutosuggest.tsx, src/v2/Apps/Consign/Components/GetPriceEstimate/ConsignPriceEstimateContext.tsx, src/v2/Apps/Consign/Components/GetPriceEstimate/EstimateResults.tsx, src/v2/Apps/Consign/Components/GetPriceEstimate/GetPriceEstimate.tsx, src/v2/Apps/Consign/Components/SoldRecently.tsx, src/v2/__generated__/ConsignPriceEstimateContext_ArtistInsights_Query.graphql.ts, src/v2/__generated__/ConsignPriceEstimateContext_SearchConnection_Query.graphql.ts
This PR:
- finishes most functionality around the price estimate UI
- tightens up all of the typescript types in our context
- adds new loading state logic, but doesn't wire in UI skeleton 
Todo: 
- Add better keyboard support 
- Touch up zerostate so that it only updates on enter, versus key change
=> feat: [Consign2] Add price estimate behavior

src/v2/Apps/Show/Routes/ShowInfo.tsx
Closes: [FX-2403](https://artsyproduct.atlassian.net/browse/FX-2403)
=> [FX-2403] Truncates press release

src/v2/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx, src/v2/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.jest.tsx
Closes: [FX-2421](https://artsyproduct.atlassian.net/browse/FX-2421)
=> [FX-2421] Matches nav item ordering with desktop

src/v2/Artsy/Router/buildClientApp.tsx
=> fix: pass correct context into buildClientApp

src/v2/Apps/Consign/Components/GetPriceEstimate/ArtistInsightResult.tsx, src/v2/Apps/Consign/Components/GetPriceEstimate/ConsignPriceEstimateContext.tsx, src/v2/__generated__/ConsignPriceEstimateContext_ArtistInsights_Query.graphql.ts
Updates the query based on this recent update from [diffusion](https://github.com/artsy/diffusion/pull/352).
=> fix: [Consign2] Update query

src/v2/Apps/Fair/Routes/FairExhibitors.tsx, src/v2/__generated__/FairExhibitorsQuery.graphql.ts, src/v2/__generated__/FairExhibitors_Query.graphql.ts, src/v2/__generated__/FairExhibitors_fair.graphql.ts, src/v2/__generated__/routes_FairExhibitorsQuery.graphql.ts
Should be descending, vs. ascending.
=> fix: use proper sort for fair exhibitors

src/desktop/apps/fairs/test/client.test.js, src/mobile/apps/art_fairs/test/template.test.js
Cleans up messy decaffeination on 2 tests that have recently failed in CI.
Related thread: https://artsy.slack.com/archives/C01ADJNCS5D/p1604526603087800
=> Cleanup flakey mocha tests

src/v2/Apps/Consign/Components/GetPriceEstimate/EstimateResults.tsx, src/v2/Apps/Consign/Components/Header.tsx, src/v2/Apps/Consign/Components/SellWithArtsy.tsx
Moves files to the [vanity-files bucket](https://s3.console.aws.amazon.com/s3/buckets/artsy-vanity-files-production?region=us-east-1&prefix=consign/).
=> fix: [Consign2] Move files to vanity-files-artsy.net

src/v2/Apps/Consign/Components/Header.tsx, src/v2/Apps/Consign/Components/SellWithArtsy.tsx, src/v2/Apps/Consign/ConsignApp.tsx
Wires up links across pages. 
(These little QA prs are trivial so just gonna self-merge)
=> fix: [Consign2] Wire up links

src/v2/Apps/Consign/Components/InDemandNow/ConsignInDemandNow.tsx, src/v2/Apps/Consign/Components/InDemandNow/ConsignTopArtists.tsx, src/v2/__generated__/ConsignInDemandNowQuery.graphql.ts
Replaces src image with srcSet
(More trivial PRs) 
@artsy/grow-devs
=> fix: [Consign2] Replace src with srcSet

src/v2/Apps/Show/Components/ShowHours.tsx, src/v2/Apps/Show/Components/ShowInfoLocation.tsx, src/v2/Apps/Show/Components/ShowLocationHours.tsx, src/v2/Apps/Show/Routes/ShowInfo.tsx, src/v2/Apps/Show/__tests__/ShowHours.jest.tsx, src/v2/__generated__/ShowHours_Test_Query.graphql.ts, src/v2/__generated__/ShowHours_show.graphql.ts, src/v2/__generated__/ShowInfoLocation_show.graphql.ts, src/v2/__generated__/ShowInfo_Test_Query.graphql.ts, src/v2/__generated__/ShowInfo_show.graphql.ts, src/v2/__generated__/ShowLocationHours_location.graphql.ts, src/v2/__generated__/routes_ShowInfoQuery.graphql.ts
Closes: [FX-2431](https://artsyproduct.atlassian.net/browse/FX-2431)
=> feat(show): display location hours if available

src/desktop/assets/analytics.ts, src/v2/Apps/Show/Components/ShowArtworks.tsx
Address [feedback in spreadsheet](https://docs.google.com/spreadsheets/d/1_VDAmRJz2K87FXDq7oh_tQSgwBv4syuZjaaR3sfetcI/edit#gid=596196548)
=> Analytics Q/A fixes

src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx, src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesApp.jest.tsx, src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts, src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts, src/v2/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts, src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
Closes: [FX-2380](https://artsyproduct.atlassian.net/browse/FX-2380)
=> [FX-2380] Uses correctly sized images

src/v2/Apps/Consign/Components/ConsignMeta.tsx
https://artsyproduct.atlassian.net/browse/GRO-77
Updates the title and description meta tags for `/consign2`.
=> feat: Update title and meta description for /consign2

tsconfig.json
Follow-up to [this slack convo](https://artsy.slack.com/archives/CC56D129X/p1604501070008700) - Adds `forceConsistentCasingInFileNames` option to ensure casing is consistent
=> toolchain: Add check for filename consistency in tsconfig

package.json, src/lib/setup.js, src/v2/Apps/Consign/Components/GetPriceEstimate/ConsignArtistAutosuggest.tsx, src/v2/Apps/Consign/Components/GetPriceEstimate/ConsignPriceEstimateContext.tsx, src/v2/Apps/Consign/Components/ReadMore.tsx, src/v2/Apps/Consign/Components/SellWithArtsy.tsx, src/v2/Apps/Consign/Components/SoldRecently.tsx, yarn.lock
Adds tracking to /consign2 page. 
Related: 
- https://github.com/artsy/cohesion/pull/129
Addresses:
- https://artsyproduct.atlassian.net/browse/GRO-72 
Tracking matrix: 
- https://docs.google.com/spreadsheets/d/12wj1rt-j5SguboPJMuaM1GqJD-5B5u5piipw8MQ5Zuk/edit#gid=0 
Cohesion PR:
- https://github.com/artsy/cohesion/pull/117
=> feat: [Consign2] Add tracking

src/v2/Apps/Consign/Components/ContactUs.tsx, src/v2/Apps/Consign/Components/InDemandNow/ConsignTopArtists.tsx, src/v2/__generated__/ConsignTopArtistsQuery.graphql.ts
Removes phone number from contact info and sums up artwork realized price data for display:
=> fix: [Consign2] More qa items 

src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
Closes: [FX-2382](https://artsyproduct.atlassian.net/browse/FX-2382)
=> [FX-2382] Adds alt tags to header images

src/v2/Apps/Consign/Components/ContactUs.tsx, src/v2/Apps/Consign/Components/FAQ.tsx, src/v2/Apps/Consign/Components/GetPriceEstimate/ArtistInsightResult.tsx, src/v2/Apps/Consign/Components/GetPriceEstimate/GetPriceEstimate.tsx
https://artsyproduct.atlassian.net/browse/GRO-84
Update copy for FAQ, GetPriceEstimate, Price Estimate flow, and ContactUs sections.
=> Feat: consign2 copy updates

src/v2/Apps/Show/Components/ShowArtworks.tsx
=> fix: readd default sort as an option on the show page

package.json, src/desktop/assets/analytics.ts, src/v2/Apps/Consign/Components/ArtworkCredits.tsx, src/v2/Apps/Consign/Components/ContactUs.tsx, src/v2/Apps/Consign/Components/GetPriceEstimate/ArtistInsightResult.tsx, src/v2/Apps/Consign/Components/Header.tsx, src/v2/Apps/Consign/Components/HowToSell.tsx, src/v2/Apps/Consign/Components/ReadMore.tsx, src/v2/Apps/Consign/Components/SellArtDifferently.tsx, src/v2/Apps/Consign/Components/SellWithArtsy.tsx, src/v2/Apps/Consign/Components/SoldRecently.tsx, src/v2/Apps/Consign/Components/TemporaryOffer.tsx, src/v2/Artsy/Router/buildClientApp.tsx, yarn.lock
Addresses most remaining items from https://www.notion.so/artsy/5e73a1a62eee465887053dae06bc15cd?v=a4e3e55e361546a5a9e26af978b4e3cd. 
(Going to merge so this can be ready for final QA tomorrow AM.)
=> fix: More consign2 QA

src/v2/Apps/Consign/Components/ContactUs.tsx
Quick QA fix in `ContactUs` to allow text to flow better at small viewports.
=> fix: Simplify text components in ContactUs to allow text to flow better

src/v2/Apps/Consign/Routes/MarketingLanding/Components/GetPriceEstimate/ConsignArtistAutosuggest.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/GetPriceEstimate/__tests__/ConsignArtistAutosuggest.jest.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/HowToSell.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/InDemandNow/ConsignInDemandNow.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/SellArtDifferently.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/TemporaryOffer.tsx, src/v2/__generated__/ConsignInDemandNowQuery.graphql.ts
=> fix: [Consign2] Launch QA

webpack/envs/clientNovoProductionConfig.js
A stashed copy of a test config was committed and needs to be removed.
=> fix: Remove Stashed Webpack Config

src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/ContactUs.jest.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/HowToSell.jest.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SellWithArtsy.jest.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SoldRecently.jest.tsx
Turns out this hypothetical tracking stuff isn't needed. Removing.
=> cleanup: [Consign] Remove unused tracking code

src/v2/Apps/Consign/Routes/MarketingLanding/Components/GetPriceEstimate/EstimateResults.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/SellWithArtsy.tsx
Addresses 
- https://artsyproduct.atlassian.net/browse/GRO-90
- https://artsyproduct.atlassian.net/browse/GRO-89
=> qa: [Consign] More QA items

src/v2/Apps/Consign/Routes/MarketingLanding/Components/GetPriceEstimate/EstimateResults.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
Quick fix for image alignment after cloudfront invalidation
=> fix: [Consign2] Fix image alignment

src/v2/Components/Modal/Modal.tsx, src/v2/Components/Modal/ModalHeader.tsx
Related to https://artsyproduct.atlassian.net/browse/PLATFORM-2915
=> Auth icons use palette

cypress/integration/collection.spec.js
This reverts commit 35facf2f9f8e42145167dbe9e378d7a0c1153edf.
=> Revert "quickfix: Disable collections cypress test for now"

src/v2/Apps/Consign/Routes/MarketingLanding/Components/GetPriceEstimate/EstimateResults.tsx
=> fix: [Consign] Add missing $

webpack/envs/clientNovoProductionConfig.js
This PR bundles luxon in the utility chunk with moment.
=> feature: Bundle Luxon in Utility Chunk

src/novo/src/index.ejs
Add preload tags for some of our initial assets.
_Forgot to add to the HTML Webpack Plugin_
=> feature: Preload

src/v2/Apps/Consign/Routes/MarketingLanding/Components/ConsignMeta.tsx
Addresses https://artsyproduct.atlassian.net/browse/GRO-124 
This is the only spot with "consign2", so assuming this is the issue.
@artsy/grow-devs
=> fix: [Consign] Fix canonical link

.prettierignore, src/novo/src/index.ejs
Noticed layouts weren't responsive in novo and noticed a missing meta tag
=> fix: [Novo] Fix responsive css

src/lib/manifest.ts, src/novo/src/index.ejs, src/novo/src/server.ts, webpack/envs/clientNovoDevelopmentConfig.js, webpack/envs/clientNovoProductionConfig.js
Wire the novo template to use the cdn. The manifest lookup names 
did not match the bundle names.
=> feature: CDN

src/v2/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Header.jest.tsx
Addresses https://artsyproduct.atlassian.net/browse/GRO-78 
Some minor spec updates from design on the header: 
=> fix: [Consign] Bring header image up to spec

src/common-middleware.ts, src/novo/src/index.ejs, src/novo/src/server.ts
Load global layout css that many novo components depend on.
=> feature: Novo Global CSS

src/v2/Apps/Artists/Routes/ArtistsByLetter.tsx, src/v2/Apps/Artists/Routes/ArtistsIndex.tsx
Closes: [FX-2542](https://artsyproduct.atlassian.net/browse/FX-2542)
Thanks @anandaroop for clearing this one up in [this thread.](https://artsy.slack.com/archives/CP9P4KR35/p1607019433330900)
=> chore(fx-2542): updates copy to reflect the more accurate figure

src/novo/src/index.ejs, src/novo/src/server.ts
Add icons to the novo web template.
=> feature: Icons

src/common-app.js, src/novo/src/routes.ts, src/novo/src/server.ts, webpack/envs/clientNovoDevelopmentConfig.js
Noticed that none of our server code was reloading after changes, requiring full server restarts, so wired up express-reloadable to novo.
=> fix: [Novo] Wire up express-reloadable

src/novo/src/client.tsx, src/novo/src/index.ejs
-  Adds segment.io and google analytics scripts
- Sets up react-tracking/track, identify, and pageview events
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-2985
=> Instrument analytics for novo routes

src/desktop/apps/artsy-v2/middleware/__tests__/userRequiredMiddleware.jest.ts, src/desktop/apps/artsy-v2/middleware/userRequiredMiddleware.tsx
Co-authored-by: The-Beez-Kneez <sutherlandanalisa@gmail.com>
=> Redirect users to login on purchase routes

scripts/pull-lock.sh
Enhance `pull-lock.sh` to support system configuration and add the execute
bit to the script.
=> feature: System Pull Lock

package.json, src/v2/Apps/Purchase/Components/PurchaseHistory.tsx, src/v2/Components/Pagination.tsx, src/v2/Components/__tests__/__snapshots__/Input.jest.tsx.snap, src/v2/Components/__tests__/__snapshots__/QuickInput.jest.tsx.snap, yarn.lock
Updating pagination typings in palette have caused conflicts with out relay typings, I've switched the types to any on the Force side. @jonallured LMK if there is a better fix for this. 
Related palette change: https://github.com/artsy/palette/pull/822
=> chore: Update palette

package.json, src/desktop/apps/artsy-v2/client.tsx, src/v2/Apps/Artist/Components/NavigationTabs.tsx, src/v2/Apps/Fair/FairApp.tsx, src/v2/Apps/Fair/Routes/FairArtworks.tsx, src/v2/Apps/Fair/__tests__/FairApp.jest.tsx, src/v2/Apps/Search/Components/NavigationTabs.tsx, src/v2/Apps/Search/Routes/Artworks/index.tsx, src/v2/Apps/Search/__tests__/SearchApp.jest.tsx, src/v2/Components/RouteTabs.tsx, src/v2/Components/UserSettings/UserSettingsTabs.tsx, src/v2/Components/v2/ArtworkFilter/index.tsx, yarn.lock
Closes: [FX-2400](https://artsyproduct.atlassian.net/browse/FX-2400)
=> fix(fx-2400): tabs spacing fixes

package.json, src/v2/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx, yarn.lock
Closes: [FX-2559](https://artsyproduct.atlassian.net/browse/FX-2559)
=> fix(fx-2559): fixes spacing on artist page related artists

src/lib/scriptLoader.ts, src/novo/src/client.tsx, src/novo/src/index.ejs
Adds the following third party scripts and a script loader in hopes that
we can dynamically load all of the third party apis in the future.
- Stripe
- Sailthru
=> feature: Third Party Scripts

src/novo/src/client.tsx, src/novo/src/index.ejs, src/novo/src/server.ts
Adds query parameters to allow disabling the novo third party trackers
so that we can better understand their performance impact.
- disableStripe=true
- disableSailthru=true
- disableSegment=true
- disableAnalytics=true
=> feature: Query Params Novo Third Party

src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx, src/v2/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetailsAdditionalInfo.jest.tsx, src/v2/Artsy/Analytics/index.ts, src/v2/__generated__/ArtworkDetailsAdditionalInfo_Test_Query.graphql.ts
Closes: [FX-2555](https://artsyproduct.atlassian.net/browse/FX-2555)
=> feat(analytics): wires up medium modal click tracking

src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
=> fix(analytics): adds click

cypress/integration/collection.spec.js
Cypress retry doesn't work in before all hooks, moving this to a
beforeEach so that it properly retries.
=> fix: Collection Test Retry

.dockerignore, Dockerfile
Forgot to add the new `packages` folder to docker.
=> fix: Docker Packages Folder

src/novo/src/index.ejs, src/novo/src/server.ts, src/typings/sharify.d.ts
Adds the current Artsy fonts to the Novo Page.
=> feature: Novo Fonts

CONTRIBUTING.md
Changes suggestion to use staging Recaptcha key to use Recaptcha key specifically for local development
=> Fix: Update local authentication guide to use correct RECAPTCHA key

src/v2/Apps/Fair/Components/FairEditorialShare.tsx, src/v2/Apps/Fair/Components/__tests__/FairEditorialShare.jest.tsx, src/v2/Apps/Fair/Routes/FairArticles.tsx, src/v2/Apps/Fair/Routes/__tests__/FairArticles.jest.tsx, src/v2/Apps/Fair/fairRoutes.tsx, src/v2/__generated__/FairArticlesQuery.graphql.ts, src/v2/__generated__/FairArticles_fair.graphql.ts, src/v2/__generated__/fairRoutes_FaiArticlesQuery.graphql.ts
Closes: [FX-2508](https://artsyproduct.atlassian.net/browse/FX-2508)
Not linked from the fairs yet. Will do that separately pending a Q/A pass.
=> feat(fx-2508): converts fair articles to new design

src/desktop/apps/user/components/auction_registrations/query.coffee, src/desktop/apps/user/components/auction_registrations/view.coffee
Part 2 of 2 for resolving [PURCHASE-2185](https://artsyproduct.atlassian.net/browse/PURCHASE-2185).
Changing auction_registrations to use mp `v2`. 
[~~This~~](https://github.com/artsy/metaphysics/pull/2894) ~~PR should be merged first for this to work.~~ Released ✅
=> chore: Switch auction_registrations to use mp v2

src/common-middleware.ts, src/lib/manifest.ts, src/lib/middleware/__tests__/locals.jest.ts, src/lib/middleware/__tests__/sharifyLocals.jest.ts, src/lib/middleware/asset.ts, src/lib/middleware/locals.ts, src/lib/middleware/sharifyLocals.ts, src/novo/src/index.ejs, src/novo/src/server.ts
This change adds the meta tags to the novo template.
=> feature: NOVO Meta Tags

src/desktop/apps/user/components/auction_registrations/query.coffee, src/desktop/apps/user/components/auction_registrations/view.coffee
Reverts artsy/force#6810
reason:
https://artsy.slack.com/archives/C9YNS4X32/p1610125536153300?thread_ts=1610121218.143400&cid=C9YNS4X32
=> Revert "chore: Switch auction_registrations to use mp v2"

src/v2/Components/Artwork/SaveButton/__tests__/SaveButton.jest.tsx
Follow up to #6862, fixes a test with an incorrect assertion 🤦
=> Fix remove save artwork test

src/v2/Apps/Fair/Components/FairEditorial/FairEditorial.tsx, src/v2/Apps/Fair/FairApp.tsx, src/v2/Apps/Fair/Routes/FairArticles.tsx, src/v2/Apps/Fair/Routes/__tests__/FairArticles.jest.tsx, src/v2/Apps/Fair/__tests__/FairApp.jest.tsx, src/v2/__generated__/FairApp_Query.graphql.ts, src/v2/__generated__/FairApp_fair.graphql.ts, src/v2/__generated__/FairArticlesQuery.graphql.ts, src/v2/__generated__/FairArticles_fair.graphql.ts, src/v2/__generated__/FairEditorial_fair.graphql.ts, src/v2/__generated__/fairRoutes_FaiArticlesQuery.graphql.ts, src/v2/__generated__/fairRoutes_FairQuery.graphql.ts
Closes: [FX-2592](https://artsyproduct.atlassian.net/browse/FX-2592)
Minor thing: wires up link to articles landing page if the total count exceeds the limit of what we show inline (which is 6)
=> feat(fx-2592): displays link to articles landing if exceeds limit

src/v2/Apps/Fair/FairApp.tsx
Will follow this up with a spec.
=> fix(fair): fixes tab hrefs

src/v2/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx, src/v2/Apps/Artwork/Components/ArtworkDetailsMediumModal.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebarClassificationsModal.tsx, src/v2/Apps/Artwork/Components/PricingContextModal.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/ContactUs.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/GetPriceEstimate/ArtistInsightResult.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/HowToSell.tsx, src/v2/Apps/IdentityVerification/IdentityVerificationApp/CompleteFailed.tsx, src/v2/Apps/IdentityVerification/IdentityVerificationApp/CompletePassed.tsx, src/v2/Apps/IdentityVerification/IdentityVerificationApp/CompleteWatchlistHit.tsx, src/v2/Apps/IdentityVerification/IdentityVerificationApp/WrongOwner.tsx, src/v2/Apps/IdentityVerification/Processing.tsx, src/v2/Apps/Order/Routes/__tests__/Respond.jest.tsx, src/v2/Components/Auction/AuctionRegistrationModal.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/Modal.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/index.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
* The `block` prop never did anything for buttons: it was true by default and is never actually referenced in code (I think the assumption was that it'd display: block/width: 100%)
* Minor fixes for the correct onClick typings
=> refactor(buttons): remove dead props; prepare for button updates

README.md
=> chore: Update README correct k8 link

package.json, yarn.lock
=> chore(deps): bumps palette

src/desktop/apps/authentication/__tests__/helpers.jest.ts, src/desktop/apps/authentication/helpers.ts, src/lib/middleware/__tests__/locals.jest.ts, src/lib/middleware/__tests__/sharifyLocals.jest.ts, src/lib/middleware/locals.ts, src/lib/middleware/sharifyLocals.ts
Move additional shared locals that are required for communicating with
backend services.
=> feature: Additional Shared Locals

src/v2/Components/ArtworkGrid/ArtworkGrid.tsx, src/v2/Components/ArtworkGrid/__tests__/ArtworkGrid.jest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid.tsx, src/v2/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
Closes: [FX-2545](https://artsyproduct.atlassian.net/browse/FX-2545)
=> feat(fx-2545): adds position/sort to artwork brick click analytics

src/v2/Apps/Auctions/AuctionsApp.tsx, src/v2/Apps/Auctions/Components/AuctionsMeta.tsx, src/v2/Apps/Auctions/Components/MyBids.tsx
=> feat: [Auctions2] Update meta

src/desktop/apps/artsy-v2/server.tsx, src/lib/middleware/__tests__/artistSeriesRedirect.jest.ts, src/lib/middleware/artistSeriesRedirect.ts, src/novo/src/server.ts
This change fixes the collection to artist series redirect and moves it
into the `lib/` directory.
=> fix: Collection to Artist Series Redirect

src/common-middleware.ts, src/novo/src/server.ts
=> fix: Collection Redirect

src/v2/Apps/Fair/Routes/FairArtworks.tsx, src/v2/Apps/Fair/fairRoutes.tsx, src/v2/__generated__/FairArtworksQuery.graphql.ts, src/v2/__generated__/FairArtworks_fair.graphql.ts, src/v2/__generated__/fairRoutes_FairArtworksQuery.graphql.ts
oops! i forgot this app uses the pattern of providing the filters (due to the 'Artist' filter which only appears here).
=> feat: add classification filter to fair page

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/AttributionClassFilter.tsx
=> feat: change Classification -> Rarity for filter heading

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
another easy one! (well, now that Crispr has the new automated genes for these, and they've been rebuilt in Gravity prod).
=> feat: add new medium types to medium filter

src/desktop/lib/webpackPublicPath.ts
Fixes artist which was misspelled.
=> fix: Misspelled Artist

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx, src/v2/Artsy/Router/Utils/shouldUpdateScroll.tsx
=> Revert "novo: Convert /orders routes"

src/v2/Apps/Fairs/Components/FairsPastFairs.tsx, src/v2/Apps/Fairs/Routes/FairsIndex.tsx
Fixes integrity failure looking for an H1 when there are no active fairs
=> fix(fairs): ensures there is always a single h1

CONTRIBUTING.md
Adds clarity around a common issue when running the tests against local force, including instructions on how to fix it.
=> chore: Describes a common issue when running locally

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx
Gut?
Requesting @icirellik's review in case there's an outsized bundle size impact.
=> Convert /fair/* to novo template

src/desktop/apps/unsubscribe/index.coffee, src/mobile/apps/unsubscribe/index.coffee
This PR just grabs the unsubscribe paths and sends them to the user edit page.
https://artsyproduct.atlassian.net/browse/GRO-181
=> feat: Redirect unsubscribe to user edit page GRO-181

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx
https://artsyproduct.atlassian.net/browse/PLATFORM-3123
=> Convert /viewing-rooms and /viewing-room/* routes to novo template (PLATFORM-3123)

src/v2/Apps/Fairs/Components/FairsFairBanner.tsx, src/v2/Apps/Fairs/Components/FairsFairRow.tsx, src/v2/Apps/Fairs/Routes/FairsIndex.tsx, src/v2/__generated__/FairsFairBanner_fair.graphql.ts, src/v2/__generated__/FairsFairRow_fair.graphql.ts, src/v2/__generated__/FairsIndex_Test_Query.graphql.ts, src/v2/__generated__/FairsIndex_viewer.graphql.ts, src/v2/__generated__/FairsPastFairsQuery.graphql.ts, src/v2/__generated__/fairsRoutes_FairsQuery.graphql.ts
=> fix(fairs): fixes dates and upcoming fair hrefs

src/v2/Apps/Fairs/Components/FairsFairRow.tsx, src/v2/Apps/Fairs/Components/__tests__/FairsFairRow.jest.tsx, src/v2/Apps/Fairs/Routes/FairsIndex.tsx, src/v2/__generated__/FairsFairRow_Test_Query.graphql.ts, src/v2/__generated__/FairsFairRow_fair.graphql.ts, src/v2/__generated__/FairsIndex_Test_Query.graphql.ts, src/v2/__generated__/FairsPastFairsQuery.graphql.ts, src/v2/__generated__/fairsRoutes_FairsQuery.graphql.ts
Piggybacking off https://github.com/artsy/force/pull/7005 — I forgot there's a separate mobile version of this.
=> fix(fairs): handles mobile view in a consistent fashion

src/v2/Apps/Fairs/Components/FairsFairRow.tsx, src/v2/Apps/Fairs/Routes/FairsIndex.tsx
=> fix(fairs): supports upcoming fairs with listings but no organizer profiles

src/desktop/apps/articles/stylesheets/articles.styl, src/desktop/apps/fair_organizer/stylesheets/index.styl, src/desktop/components/stylus_lib/index.styl, src/v2/Components/NavBar/NavBar.tsx
Quick follow up from https://github.com/artsy/force/pull/6991 to make navbar development easier in the future.
=> chore: Add comments describing what files need to change when updating the navbar

src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.jest.tsx, src/v2/Components/v2/ArtworkFilter/Utils/isDefaultFilter.tsx
Pretty simple! It's now a checkbox...
=> feat: convert major periods filter to checkbox from radio button

src/v2/Apps/Consign/Routes/MarketingLanding/Components/InDemandNow/__tests__/ConsignInDemandNow.jest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ColorFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/OptionText.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ShowMore.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/ShowMore.jest.tsx
Re: [FX-2614](https://artsyproduct.atlassian.net/browse/FX-2614)
This handles the layout; will handle the `OR` separately.
=> feat(fx-2614): colors filter design update

src/v2/Apps/Auctions/AuctionsApp.tsx, src/v2/Apps/Auctions/Routes/CurrentAuctions.tsx, src/v2/Apps/Auctions/Routes/PastAuctions.tsx, src/v2/Apps/Auctions/Routes/UpcomingAuctions.tsx, src/v2/Apps/Auctions/auctionsRoutes.tsx, src/v2/__generated__/CurrentAuctions_currentAuctions.graphql.ts, src/v2/__generated__/PastAuctions_pastAuctions.graphql.ts, src/v2/__generated__/UpcomingAuctions_upcomingAuctions.graphql.ts, src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts, src/v2/__generated__/auctionsRoutes_Current_AuctionsQuery.graphql.ts, src/v2/__generated__/auctionsRoutes_Past_AuctionsQuery.graphql.ts, src/v2/__generated__/auctionsRoutes_Upcoming_AuctionsQuery.graphql.ts
This PR stubs out routes and graphql data structure for the new auctions app, and cleans out old WIP stuff. 
Should be ready to build within now! 
(Will add relevant comments inline)
=> feat: [Auctions2] Add routing to Auctions2

src/v2/Apps/Order/Components/AddressModal.tsx, src/v2/Apps/Order/Routes/__fixtures__/MutationResults/createCreditCard.ts, src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx, src/v2/Apps/Payment/Components/PaymentSection.tsx, src/v2/Apps/Payment/Routes/Payment/PaymentApp.tsx, src/v2/Apps/Payment/__tests__/PaymentApp.jest.tsx, src/v2/Apps/Payment/__tests__/PaymentSection.jest.tsx, src/v2/Components/Payment/PaymentModal.tsx, src/v2/Components/Payment/SavedCreditCards.tsx, src/v2/Components/Payment/UserSettingsPayments.tsx, src/v2/Components/Payment/__tests__/PaymentModal.jest.tsx, src/v2/__generated__/PaymentApp_Test_Query.graphql.ts, src/v2/__generated__/PaymentApp_me.graphql.ts, src/v2/__generated__/PaymentModalCreateCreditCardMutation.graphql.ts, src/v2/__generated__/PaymentSectionCreditCard.graphql.ts, src/v2/__generated__/PaymentSection_Test_Query.graphql.ts, src/v2/__generated__/PaymentSection_me.graphql.ts, src/v2/__generated__/paymentRoutes_PaymentQuery.graphql.ts
[PURCHASE-2339]
[PURCHASE-2339]: https://artsyproduct.atlassian.net/browse/PURCHASE-2339
TODO:
=> feat: User settings cc modal

src/desktop/apps/about/templates/sections/collecting.jade, src/desktop/apps/about/templates/sections/index.jade, src/desktop/apps/about/templates/sections/the_art_world_online.jade, src/desktop/apps/about/test/templates.test.js
This PR removes a bunch of elements from the about page. All I did was delete the template code so technically there is still JSON in a bucket on S3 that would be stale and confusing to Future Us but maybe that's fine?
https://artsyproduct.atlassian.net/browse/GRO-212
=> feat: Update about page GRO-212

src/desktop/apps/artsy-v2/apps/artwork/artworkClient.tsx
Add the xapp token so that the buyers premium modal works.
=> fix: Buyers Premium Modal

src/v2/Apps/ArtistSeries/Components/ArtistSeriesMeta.tsx, src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesMeta.jest.tsx, src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts, src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts, src/v2/__generated__/ArtistSeriesMeta_TestQuery.graphql.ts, src/v2/__generated__/ArtistSeriesMeta_artistSeries.graphql.ts, src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
This is a part of the SEO Bug Bash
The /artist-series/ pages did not have a canonical tag, so we added a self referring canonical tag
https://app.deepcrawl.com/accounts/75457/projects/324980/crawls/3392865/reports/pages_without_canonical_tag_basic?page=1&filters=q%5Burl_cont%5D%3Dartist-series
=> GRO-204: Artist Series Pages Missing Canonical Tags

src/v2/Apps/Order/Components/AddressModal.tsx
=> Revert "bugfix: prevent create address mutation from firing twice"

yarn.lock
Upgrade **artsy-eigen-web-association** to include the reset-password, change and forgot password urls
=> chore: upgrade artsy-eigen-web-association

src/v2/Artsy/Router/useRouter.tsx, src/v2/Components/RouteTabs.tsx
Re: https://artsy.slack.com/archives/C01NW1YSDPF/p1615823659039800
=> fix(routetabs): passes in active prop

src/v2/Apps/Auctions/AuctionsApp.tsx
This is to update the Auctions2 Landing page with the new finalized copy scripts:
*description:*
Bid on works you love with auctions on Artsy. With live bidding opening every week, Artsy connects collectors like you to art from leading auction houses and sellers across the globe. We feature premium artworks including modern, contemporary, and street art, so you can find works by your favorite artists—and discover new ones—all in one place.
*learn more button:*
Learn more about bidding on Artsy >
=> GRO-222: Updated Copy Script for Auctions2 Landing page

src/v2/Apps/Order/Components/AddressModal.tsx, src/v2/Apps/Order/Components/SavedAddresses.tsx, src/v2/Apps/Order/Mutations/CreateUserAddress.ts, src/v2/Components/Address/AddressModalFields.tsx, src/v2/Components/Payment/PaymentModal.tsx
Fixes:
[PURCHASE-2483] [PURCHASE-2487] [PURCHASE-2488] + border fix
Each commit fixes one of 👆🏽 (also moved the common fields in `PaymentModal` and `AddressModal` to a new shared file)
required fields:
Borders:
</details>
[PURCHASE-2483]: https://artsyproduct.atlassian.net/browse/PURCHASE-2483
[PURCHASE-2487]: https://artsyproduct.atlassian.net/browse/PURCHASE-2487
[PURCHASE-2488]: https://artsyproduct.atlassian.net/browse/PURCHASE-2488
=> fix: bugs in new payment/shipping page

.storybook/preview-head.html, .storybook/preview.js, src/v2/Components/Masonry.tsx, src/v2/Components/__stories__/ExampleStory.story.tsx, src/v2/Components/__stories__/Molecules.story.tsx
This is the first page (headers) of the [molecules kitchen sink](https://www.figma.com/file/m6gDpKHEWDbYJyrwsVZDBr/Artsy-3.0-Design-System?node-id=1004%3A1354)
Will see if I can get another page (content) in before merging.
Added a few minor TODOs. One thing that occurs to me is that we probably want to improve the ergonomics of the `GridColumns` component. I propose we rename Grid/Col to LegacyGrid/LegacyCol, do a bulk find and replace in Force, then cut a breaking release and take over Grid/Col.
=> chore(design-system): molecules

src/v2/Components/__stories__/Molecules.story.tsx
Remaining patterns here.
We'll probably want to clean up and pull out all of these individual patterns into named stories (and some actual components) to allow easy copying. But this should at least verify that indeed: the v3 styles work/work together.
=> chore(design-system): molecules [part 2]

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
Closes: [FX-2735](https://artsyproduct.atlassian.net/browse/FX-2735)
=> fix(fx-2730): custom price filter q/a

src/v2/Components/FilterInput/FilterInput.story.tsx, src/v2/Components/FilterInput/FilterInput.tsx, src/v2/Components/FilterInput/__tests__/FilterInput.jest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/FacetAutosuggest.tsx
Closes: [FX-2732](https://artsyproduct.atlassian.net/browse/FX-2732)
=> feat(fx-2732): clearable filter search input

src/v2/Apps/Artist/Routes/AuctionResults/Components/SortSelect.tsx
Re: https://artsy.slack.com/archives/C9XJKPY9W/p1616618231018200
The remaining instances of this component were checked and look fine.
=> fix(sort): prevents select from filling available space

src/v2/Apps/Partner/Components/PartnerHeader/PartnerHeaderAddress.tsx, src/v2/Apps/Partner/Components/__tests__/PartnerHeader.jest.tsx
This PR fixes a possibly null value for the city field.
JIRA - https://artsyproduct.atlassian.net/browse/PX-3878
=> fix: handle null city value

src/v2/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.jest.tsx
Fixes specs for https://github.com/artsy/force/pull/7226
=> fix(specs): fixes build

data/schema.graphql, src/v2/Apps/Auctions/Components/MyBids/MyBidsBidItem.tsx, src/v2/__generated__/MyBidsBidItem_saleArtwork.graphql.ts, src/v2/__generated__/MyBidsQuery.graphql.ts
Follow-up to https://github.com/artsy/metaphysics/pull/3065 
Needed to update the field name so that the `push-schema-changes` job would work: https://app.circleci.com/pipelines/github/artsy/metaphysics/7473/workflows/0f35e3bb-62a4-4adb-a5b9-61c5df82da01/jobs/14507
=> fix: Fix schema issue

src/v2/Apps/Auctions/Components/MyBids/MyBidsBidItem.tsx
=> fix: Fix type error

src/v2/Components/Onboarding/Steps/Budget.tsx
I goofed when setting this up, thanks for catching it @abhitip!! 🙌 
=> fix: Use correct module on budget step

src/v2/Apps/Partner/Components/PartnerHeader/PartnerHeaderAddress.tsx
This PR fixes text wrapping for mobile devices.
JIRA - https://artsyproduct.atlassian.net/browse/PX-3824
Before:
Now:
=> fix: allow text wrapping for mobile 

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter2.tsx
Closes: [FX-2805](https://artsyproduct.atlassian.net/browse/FX-2805)
=> fix(filters): updates copy

src/v2/Components/Search/SearchInputContainer.tsx
Closes: [GRO-270](https://artsyproduct.atlassian.net/browse/GRO-270)
I broke it I bought it.
=> fix(searchinput): tucks the magnifying glass back under the covers
