artsy/force

- package.json
- src/desktop/apps/artwork/components/commercial/index.styl
- src/desktop/apps/artwork/components/commercial/query.coffee
- src/desktop/apps/artwork/components/commercial/templates/acquire.jade
- src/desktop/apps/artwork/components/commercial/templates/index.jade
- src/desktop/apps/artwork/components/commercial/templates/inquire.jade
- src/desktop/apps/artwork/components/commercial/test/template.coffee
- src/desktop/apps/artwork/components/commercial/view.coffee
- src/desktop/apps/artwork/test/fixtures/acquireable_artwork.json
- src/desktop/apps/artwork/test/fixtures/acquireable_artwork_single_edition.json
- src/desktop/apps/artwork/test/fixtures/acquireable_only_artwork.json
- src/desktop/apps/artwork/test/fixtures/offerable_artwork.json
- src/desktop/apps/fairs/test/template.coffee
- src/mobile/apps/artwork/components/meta_data/index.styl
- src/mobile/apps/artwork/components/meta_data/templates/inquiry.jade
- src/mobile/apps/artwork/components/meta_data/test/template.coffee
- src/mobile/apps/artwork/components/meta_data/view.coffee
- src/mobile/apps/artwork/routes.coffee
- yarn.lock
This PR addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-575
We're adding a "Make offer" button if the artwork has `is_offerable: true`.
Note that I left this out of the desktop "auction" case since we can't think of a use for it right now. If we need that UI in the future it should be easy to add.
**Desktop (Make offer + Buy now)**
**Desktop (Make offer only)**
**Mobile (Make offer + Buy now)**
**Mobile (Make offer only)**
> Adds reference to is_offerable and includes make offer button

- src/mobile/apps/user/routes.coffee
We already tried this, but I think it _might_ not have been properly deployed to staging amidst CI flakiness?
Currently, if you make a change in a console and hit https://staging.artsy.net/user/refresh in your desktop Chrome, and inspect:
This is good! We have the latest and greatest session data from Force's server, being sent to the client in the `Set-Cookie` header.
However, perform the same experiment as above ^, except open your Chrome mobile emulator:
And voila! There is _no_ `Set-Cookie` header, which is consistent with what the bug reported is...namely, that `/user/refresh` _doesnt_ actually update their session, and so, they are always stale and refreshing.
> @damassi => Make sure we send the session cookie over with /user/refresh on mobile

- src/desktop/apps/auction/__tests__/routes.jest.js
- src/desktop/apps/auction/routes.js
Closes https://artsyproduct.atlassian.net/browse/DISCO-436
~~I couldn't actually get the accompanying `routes.test.js` file to work on my computer locally, so I'll push a blind 🙈 spec.~~
EDIT- Figured out my yarn issue, added spec.
> @sweir27 => Guard against a failing server-side lot standings call

- src/mobile/components/layout/bootstrap.coffee
This seems to be one of those bugs that's possibly not going to be fully understood, and I'd like to have some benefit from the time spent on it.
So, we just suspend the auth sync for now (since I don't think it's even meaningful).
> @damassi => Dont sync user session on every page load for mobile

- src/desktop/apps/article/routes.js
This `onDailyEditorial` doesn't seem to be used anywhere in the view: https://github.com/search?q=org%3Aartsy+onDailyEditorial&type=Code
In the route where the other `onDailyEditorial` is used, we map it to `ON_DAILY_EDITORIAL` which is then used in [`src/desktop/components/email/client/editorial_signup.coffee`](https://github.com/artsy/force/blob/4a872b6e8e157c8f5b2d7507a9f85cea247b6e04/src/desktop/components/email/client/editorial_signup.coffee#L30), but in the new Article page we don't even do the same conversion, so I'm confident that we can remove this flag at least in the Article page.
> Remove unused 'onDailyEditorial' flag

- src/desktop/apps/collect2/meta.tsx
This cleans up the metadata tags for the collect and collection pages as part of https://artsyproduct.atlassian.net/browse/GROW-904 and https://artsyproduct.atlassian.net/browse/GROW-931. This PR is dependent on https://github.com/artsy/reaction/pull/1496.
> @l2succes: remove meta tags that have been moved to reaction.

- .vscode/settings.json
- yarn.lock
This will prevent results from the `.caches` directory from showing up in project-wide search in VSCode.
> Excludes .caches from VSCode project search

- src/desktop/apps/home/templates/browse.jade
finishes https://artsyproduct.atlassian.net/browse/GROW-997
Previously the Collect page was routed to `/collect?medium=#{id}` (e.g. `/collect?medium=painting`) but now it's `/collect/#{id}` (e.g. `/collect/painting`). Because of this the medium links on the homepage for non-logged-in users are broken. This PR updates the paths to fix it.
> Fixes ab issue where all medium links on homepage broken (desktop)

- src/desktop/apps/galleries_institutions/components/filter_facet/partner_filter_facet.coffee
I didn't _really_ figure out how/why this was happening to 'Hong Kong', but I think this is a good fix (+ fixes the specific issue)
Basically, since we have our own datasource of `{id: slug, name: City/Geo/Country}`, it _should_ be safe to dedupe by `id`. Not sure why HK was matching twice, but logically, we wouldn't ever want a duplicate suggestion to appear (for whatever the reason), so I'm reasonably confident in this little update.
> @anandaroop => Dedupe location matches in galleries typeahead by slug

- .circleci/config.yml
- package.json
Missed a spot where some version were out of date in circle. Also loosened the engines to only restrict to the major version.
> Fix circle-ci using wrong versions, loosen engines

- src/desktop/apps/artwork2/server.js
Along with https://github.com/artsy/reaction/pull/1567 , /artwork2 will load + work (admin-only), but there is an outstanding rehydration issue (though that's likely to be in Reaction and not here).
> @zephraph => Get a working /artwork2 page up

- src/desktop/apps/artsy_in_miami/components/MiamiFairWeekPage.js
- src/desktop/apps/artsy_in_miami/fixture.json
- src/desktop/apps/artsy_in_miami/templates/meta.jade
finishes https://artsyproduct.atlassian.net/browse/GROW-1023
* Updates the `fixture.json` to sync with the production JSON
* Adds `meta.title`, `meta.description` and `introduction.image` to the JSON file so they will be editable on https://www.artsy.net/artsy-in-miami/edit
* Replaces the hard-coded title and description in `src/desktop/apps/artsy_in_miami/templates/meta.jade` with the title and description from the JSON
* Both the production and staging JSON files have been updated and now hold `meta.title`, `meta.description` and `introduction.image`:
* https://s3.amazonaws.com/artsy-force-production/json/artsy-in-miami.json
* https://s3.amazonaws.com/artsy-force-staging/json/artsy-in-miami.json
> Add meta description field for Miami Art Week landing page by 11/28

- renovate.json
This is a bit of a test... it updates the renovate config for force to have it update the node version in the Dockerfile. I might have to play around with the configuration a little bit more, we'll see.
> Configure renovate to update node for force

- src/desktop/components/main_layout/templates/blank.jade
- src/desktop/components/main_layout/templates/index.jade
- src/desktop/components/main_layout/templates/minimal_header.jade
- src/desktop/components/main_layout/templates/redesign.jade
- src/desktop/components/main_layout/templates/scripts.jade
Now that we're using `stripev3: true`, everywhere, we don't need to reference stripe v2 anymore.
This just cleans up that option.
> Get rid of option for stripe v2, now that we no longer use it

- src/mobile/lib/global_react_modules.js
- yarn.lock
Fix mobile stitch issue so that mobile matches desktop, since everything is responsive. 
Problem arose after creating new wrapper functionality in Stitch last week so we didn’t have to wrap every stitched component in context and responsive and so on, but didn’t realize that mobile wasn’t using the same components as desktop, and had its own `global_react_modules` file, which didn’t contain that wrapper component and so there was no environment leading to the error.
> Fix mobile stitch issue

- src/desktop/apps/artwork/routes.coffee
- src/mobile/apps/artwork/components/bid/index.jade
Seems like there are several issues going on in parallel here:
- First, locally we were failing because INTERCOM_BUYER_HASH is set to null by default. I thing there is no harm in checking it before calling it. So should be fine to put the intercom behind if check I believe.
- Second for some reason stitched components are failing locally, but I think that is unrelated to the current change here.
- And finally my change is just renders the current auction item status for upcoming auctions instead of calling them closed. (same as on desktop)
> render auction details on mobile for upcoming auctions

- .circleci/config.yml
- yarn.lock
I _think_ this is correct.
What do you think? Basically, tests (+ asset compilation), is insanely slow on Force. It's tracked in a JIRA ticket: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=37&view=planning&selectedIssue=PLATFORM-599
With tests and assets, Force can take up to half an hour to actually deploy (each step can be up to 15 minutes, and they can't be parallelized since tests run first). There's also a fair amount of spuriousness in both the tests itself, as well as mysterious Docker/Circle issues, that occasionally fail a step (the more steps we have, the more prone we are to spurious CI issues).
So with a CI issue, it can take literally an entire hour to deploy Force, from the time a dev pushes the button. This is super super slow! It doesn't seem like …
> @zephraph => Dont run tests on `release` commits

- hokusai/staging.yml
We're currently running into issues with immediate 504s when accessing
staging.artsy.net, but aren't sure why. We're hoping that by ensuring
that there are more pods for us to load balance to.
> Scale force staging's pod allocation to minimic production.

- src/lib/setup.js
- src/test/acceptance/partner_profile.js
Before this change: the profile app was redirecting
all traffic of that didn’t explicitly match another route to it’s
app. This was resulting in slow health checks that were integrating with
gravity. Considering these health check requests run every 5 seconds,
we’re putting a lot of needless traffic on gravity and other potential
downstream services.
* prettify src/lib/setup.js
Co-authored-by: Christopher Pappas <damassi.pappas@gmail.com>
----
Goal is to ensure that a system healthcheck can never cascade to other systems!
https://app.datadoghq.com/apm/resource/force/express.request/5e3bbf98774abed2?end=1544824820463&env=production&paused=false&spanID=8713293955843515405&start=1544220020463&traceID=891944206827678761
> Load health check endpoints before others

- src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
- src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.test.js
- yarn.lock
Addresses: https://artsyproduct.atlassian.net/browse/GROW-632
This implements a full-user sign-up modals on /news/ pages on desktop.
> add signup modal to news articles

- .babelrc
- src/desktop/apps/unsupported_browser/template.jade
- src/lib/middleware/unsupported_browser.coffee
- webpack.config.js
Does fix support for Safari 10 however. 
Main issue blocking IE11 is that there are now libraries that ship `.mjs` files -- modern native JS modules, which conform to modern browser specs -- which Webpack reads in and does not transpile. I tried many things but couldn't get it to work, and so IE 11 would see the `class` keyword and fail.
> Update unsupported browsers list

- .circleci/config.yml
This attempts to remove the `build` workflow step that doesn't seem necessary. If it works as expected, this just simplifies the config slightly so that we can start to complicate it again by skipping tests on release builds.
No rush to merge. In fact, I may want to monitor the build closely so maybe I should just merge and monitor during a low-activity period once any feedback is addressed.
> Remove unnecessary (maybe?) workflow step

- .circleci/config.yml
I _think_ this accomplishes what we discussed, which is that release builds skip `test` and `acceptance` steps and proceed to push the docker image and publish assets, then to perform the actual deploy.
To do this I had to separate the "push" steps so that staging's depends on tests but production's doesn't. [A YAML anchor](https://blog.daemonl.com/2016/02/yaml.html) avoids duplicating the command definition. (There might also be a Circle way to do this.)
I also tried to name the steps with "staging" or "production" instead of "release" for consistency.
> @mzikherman: Skip tests on release builds

- .babelrc
- src/lib/middleware/unsupported_browser.coffee
- webpack.config.js
Move Safari 10 to unsupported browser list. Additionally fixes recent issue where compiling for an old browser was taking 12s when `yarn link`ing between Force and Reaction.
> [Supported Browsers] Move safari 10 to unsupported

- Dockerfile
- hokusai/staging.yml
Setting `server.keepAliveTimeout` in https://github.com/artsy/force/pull/3232 did not solve 504s on staging.artsy.net - fallback to reverting the Node upgrade that correlates with this behavior
> Revert to Node 10.13.0

- src/desktop/analytics/main_layout.js
Commissionable artwork pageviews require an additional analytics call to make it easier for us to do dynamic retargeting via various marketing channels. The only information explicitly sent over is the Product ID. I've tested this end to end using the segment debugger.
> add a new analytics track for marketing purposes

- src/desktop/lib/global_client_setup.coffee
The same fix that we did here https://github.com/artsy/force/pull/3048 but now in desktop (since new pages are responsive we're seeing users on mobile devices seeing this sometimes).
> @oxaudo => Dont sync current user client side to avoid endless refresh

- patches/react-relay-network-modern+2.5.0.patch
Related to https://artsyproduct.atlassian.net/browse/BUGS-685
Previously the error message would be:
```
Error Message: Relay request for `routes_CollectAppQuery` failed by the following reasons:
Server return empty response with Status Code: 200.
```
Now the error will look like:
```
Error Message: Relay request for `routes_CollectAppQuery` failed by the following reasons:
1. https://stagingapi.artsy.net/api/v1/filter/artworks?aggregations%5B%5D=total&offset=0&page=1&size=30&sort=-decayed_merch - {"type":"other_error","message":"request timed out","backtrace":[…]}
artworks: artworks_connection(first: 30, after: "") {
^^^
```
----
I'll create a PR for the upstream library. If that ends up being merged before this PR is, then it probably makes sense to replace this patch by the updated …
> [SSR] Surface remote GraphQL errors.

- src/desktop/analytics/criteo.js
- src/desktop/apps/artwork2/server.tsx
cc @cavvia this skips a couple of analytics calls that aren't possible in this style, from the new artwork page. The issue is that the calls are triggered from Force and based on bootstrapped data that is no longer present in the new page.
Generally speaking, we've been moving to triggering analytics calls from Reaction these days.
> @mzikherman => Fix analytics crashers for new artwork page

- src/desktop/analytics/main_layout.js
We need to add tracking for `offerable` artwork pageviews as we did for `inquireable` works back when BN launched. This is time sensitive as it needs to be out for MO launch.
This is another piece of metadata which the responsive artwork page needs to be able to send with the segment pageview event.
cc @anipetrov
> add offerable pageview tracking

- src/desktop/apps/sitemaps/routes.coffee
- src/desktop/apps/sitemaps/templates/news.jade
- src/desktop/apps/sitemaps/test/routes.coffee
- src/desktop/apps/sitemaps/test/templates.coffee
Partially addresses https://artsyproduct.atlassian.net/browse/GROW-818
This PR includes two changes:
* Use the correct URL scheme for news articles (`www.artsy.net/news/article-title`)
* Update the `sitemap-news.xml` endpoint to include articles that have `exclude_google_news: false`
**Note that even with this PR the `sitemap-news.xml` endpoint only generates the first 100 articles to reduce workloads for Positron since loading literally all articles may affect Positron's performance.** The main purpose of this PR is to make sure we generate the news sitemap in the correct format. Once this is confirmed we should be able to move the entire logic to Cinder so we can cover all articles with no performance penalty.
> Use the correct URL scheme for news articles

- src/desktop/apps/search/templates/search_result.jade
- src/desktop/models/search_result.coffee
- src/desktop/test/models/search_result.coffee
- src/mobile/components/search_results/result.jade
- src/mobile/models/search_result.coffee
- src/mobile/test/models/search_result.coffee
This is a pretty hack fix for https://artsyproduct.atlassian.net/browse/DISCO-537
Let me know if you think it's too smelly to do this very specific check here. The alternative is to figure out where those searchResults are generated and make sure we are assigning the proper display_model for profiles where owner is a fair but I'm not sure if that can affect anything else.
Also there is a very minimal test for this search: https://github.com/artsy/force/blob/master/src/desktop/apps/search/test/client/index.coffee
Could add something that will check that Fair is display when result is a 'Gallery' with ownerType 'Fair' but wanted to make sure this change is legit.
> Adjusting display to check for profile owner when displaying search result

- src/test/acceptance/artist.js
- src/test/acceptance/fixtures/metaphysics/artist.json
Now that we're rendering the artist insights v2 component via an A/B test, the specs need an updated artist fixture including insight data.
> Update artist acceptance fixture to include artist insights

- src/desktop/apps/artist/client.tsx
- src/desktop/apps/artist/server.tsx
- src/desktop/apps/artwork2/client.tsx
- src/desktop/apps/artwork2/server.tsx
- src/desktop/apps/order2/client.js
- src/desktop/apps/order2/routes.tsx
Once https://github.com/artsy/reaction/pull/1882 is merged and deployed this can be merged.
Moves the `<Container>` component (which constrained the width of the app) over to Reaction.
> Remove <Container /> component used in new router apps

- src/desktop/apps/sitemaps/routes.coffee
- src/desktop/apps/sitemaps/test/routes.coffee
finishes https://artsyproduct.atlassian.net/browse/GROW-1081
The `ARTSY_EDITORIAL_ID` also needs to be updated before merging this.
> Exclude partner articles and classic articles from news sitemap

- src/desktop/apps/rss/routes.js
- src/desktop/apps/rss/test/routes.test.js
finishes https://artsyproduct.atlassian.net/browse/GROW-956
This PR updates the news RSS to exclude video articles that has `media.published === false`. The GraphQL query already has `media { published }` so we don't have to update that here.
> Hide "coming soon" videos from RSS feed

- src/desktop/apps/artsy_in_miami/components/MiamiFairWeekPage.js
Removes last instance of deprecated reaction `Grid` component from Force, in favor of palette.
> Swap reaction's Grid for palette

- src/desktop/apps/order2/__tests__/routes.jest.js
- src/desktop/apps/order2/routes.tsx
In collaboration with @lilyfromseattle. Addresses [PURCHASE-787](https://artsyproduct.atlassian.net/browse/PURCHASE-787).
This is a temporary fix for serving up a 404 page when an order is not found. It's not an ideal solution - we're going to look into things a bit more and see if we can figure out a better way to emit 404's.
We're also going to talk to @mzikherman as it appears he dealt with this issue for artists/artworks recently, and see if he had any revelations.
> Serve 404 page when order is not found

- package.json
- yarn.lock
This removes the A/B test branching in Reaction to ensure that Artist Insights V2 is enabled for all artist pages.
> Deploy: Roll out Artist Insights V2 to all sessions

- .circleci/config.yml
- dangerfile.ts
- scripts/validate_schemas.js
The validate schemas check was removed in https://github.com/artsy/force/pull/3197 as it was being run via CI in the `hokusai` image which doesn't have node installed.
Generalize scripts/validate_schemas.js to check either staging or production Metaphysics and validate staging on master and production on release
Run validate schema checks on the `circleci/node:10-stretch-browsers` image
> Reinstate validate schemas

- src/mobile/models/artwork.coffee
Fixes https://artsyproduct.atlassian.net/browse/BUGS-731
Fixes  https://artsyproduct.atlassian.net/browse/BUGS-723 
This trivial change simply makes use of the Coffeescript extistential operator to safely navigate to an artwork's partner's name on mobile tag pages.
This effectively quiets the client-side JS error and the accompanying Sentry report.
But that's really secondary to the fact that the tag pages (e.g. /tag/koala) are substantially broken on mobile, which is worth a separate ticket. (I'll look for one and create if necessary).
> Use safe navigation to access partner name

- src/desktop/apps/galleries_institutions/components/primary_carousel/index.styl
- Brings in carousel arrows to 10px padding instead of 30px so the
- ( https://artsyproduct.atlassian.net/browse/BUGS-713 )
> Redefines carousel arrow offset from 30 to 10 pixels

- src/mobile/apps/galleries_institutions/templates/partner.jade
This caused a bunch of errors on the `/galleries/all` page on mobile web.
Fixes https://artsyproduct.atlassian.net/browse/BUGS-726 (https://sentry.io/artsynet/force-production/issues/856044287/?referrer=alert_email)
Note that a general weird thing about this page is that basically no location names show up. 🤷‍♀️ seems like it could use a bit of a reboot, but for a later time.
> Explicitly checks for existence of city before searching for city.name

- package.json
- src/desktop/lib/global_client_setup.coffee
- yarn.lock
Fixes https://artsyproduct.atlassian.net/browse/BUGS-736
Adds https://github.com/xpl/es7-object-polyfill as a polyfill for older browsers. Not too necessary, but just in case (just a few loc)
> Add polyfill for object.entries for older browsers

- src/mobile/components/show_more_works/index.coffee
Fixes: https://artsyproduct.atlassian.net/browse/BUGS-664
The actual height of the component necessary to show these works is ~ `18000px` so `9999` just doesn't cut it.
Updated to remove `max-height` completely (as it's set by the un-toggled version of the component). Did a quick pass through the fairs views that re-use this and they seem 👍.
> Update max-height on slider in mobile web to not cut off large shows

- src/desktop/apps/galleries_institutions/components/primary_carousel/fetch.coffee
We set this number to three back in 2016 ( https://github.com/artsy/force-private/pull/4357 ), which I think is maybe before we set the idea of premium partners having this as an key part of the selling process. So this bumps the number of premium highlighted shows from 3 -> 6.
It's a quick-fix, an ideal solution is to take the work going on with https://artsyproduct.atlassian.net/browse/GALL-1314 and to make those changes also improve this section too. It could probably do with being an infinite loop.
> Bump the number of shows from premium partners which  we highlight from 3 -> 6

- .circleci/config.yml
I _think_ this will accomplish what we discussed: pull requests should be validated against Metaphysics' staging schema _before_ being merged into `master`.
https://artsyproduct.atlassian.net/browse/PLATFORM-1142
(w/@lilyfromseattle)
> Validate Metaphysics' staging schema on pull request builds as well

- src/desktop/apps/auth2/__tests__/routes.jest.js
- src/desktop/apps/auth2/components/MobileAuthStatic.tsx
- src/desktop/apps/auth2/routes.ts
partially addresses https://artsyproduct.atlassian.net/browse/GROW-1080
This PR adds the ability to change the title of the standalone sign up page. In Reaction we've added the ability to [customize the title at the React level](MobileSignUpForm), and on Force-side we basically pass down the `title` query string to the `<MobileSignUpForm>` component. Once we merge this we'll be able to customize the title by adding `title` to the URL:
```
/sign_up?title=Sign+up+to+follow+artworks&action=follow&...
```
In terms of security, JSX sanitizes any text that goes through it (except for texts assigned to `dangerouslySetInnerHTML`, which we don't use here), so we should be good to go.
> Add ability to customize mobile sign up form using query string

- package.json
- yarn.lock
This reverts commit 1ba4b2d7f6528aba603329f349f62995d7dd6626.
Removing this update from the deploy queue so we can flush the queue, as per https://artsy.slack.com/archives/CA8SANW3W/p1549446975130500?thread_ts=1549396045.087400&cid=CA8SANW3W
> Revert "[package] Update dd-trace client."

- src/desktop/apps/article/components/layouts/Article.tsx
Fixes a small bug where the further reading was incorrectly displaying on superArticles, the `isSuper` prop was not being passed down to reaction.
> isSuper is passed down to reaction

- .circleci/config.yml
Removes a couple refs in circle to publishing assets; this now takes place in a post deploy hokusai step.
> Remove references to publishing

- Dockerfile.test
- hokusai/test.yml
- scripts/test.sh
- webpack/envs/production.js
Don't do production compiles for our assets by pointing at `Dockerfile.test`, and don't show a progress bar on CI.
> Fix compilation on CI tests

- src/lib/setup.js
Was trying to access git from a container, which was leading to a crash.
> Unassociate sentry releases

- src/desktop/apps/article/routes.js
- src/desktop/models/article.coffee
This ticket addresses [GROW-1071](https://artsyproduct.atlassian.net/browse/GROW-1071) by fixing a mysterious validation error message that was frequently appearing in Positron's logs:
```["super_article_for" needs to be a string of 12 bytes or a string of 24 hex characters]```
This error was mysterious because we knew that it involved a request for a super article, but we could not find its origin. ~After investigation, we discovered that Force was passing an article's slug instead of its ID when it requested articles for AMP.~
~The solution was to change:~
~```const article = new Article({ id: req.params.slug })```~
~to~
~```const article = new Article({ id: req.url.split("/")[2] })```~
~because the request parameters were undefined for a request like `GET /article/:slug/amp`.~
We found …
> Fixed bug in article AMP controller (GROW-1071)

- src/desktop/components/main_layout/templates/scripts.jade
- src/lib/setup.js
- src/mobile/components/layout/templates/scaffold.jade
- webpack/envs/base.js
We're getting inconsistent `gzip` encoding on our JS files, this attempts to force the header to always return `gzip`. 
Also renamed `runtimeManifest` to `runtime-manifest` so that local devs with case insensitive file systems aren't confused.
> Attempt to force gzip on assets

- package.json
- src/lib/setup.js
- yarn.lock
Since we're not using `br` compression this removes `express-static-gzip` in favor of default `compression` middleware. 
Also moves `assetMiddleware` down a bit (where bucket assets used to be) because the error 
```
asset is not a function
``` 
seems to be a redherring when artsy.net goes down. Let's see if this fixes it.
> Attempt to simplify compression

- src/desktop/apps/artist/server.tsx
- src/desktop/apps/artwork2/server.tsx
- src/desktop/apps/collect/server.tsx
- src/desktop/apps/collections/server.tsx
- src/desktop/apps/isomorphic-relay-example/server.tsx
- src/desktop/apps/order2/routes.tsx
- src/desktop/components/main_layout/header/templates/user.jade
- src/desktop/components/main_layout/templates/react_index.jade
- src/desktop/components/main_layout/templates/react_minimal_header.jade
- src/desktop/components/main_layout/templates/react_redesign.jade
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-1184
Back in https://github.com/artsy/reaction/pull/1882 I added the ability to extract styles from Reaction so that we could relay less on stitch for our Styled Components needs. This wasn't wired up at the time  because I was planning on refactoring out stitch style extraction completely from force in one go, and not just in our new SSR apps. Now that we've identified an issue with duplicate style markup this takes on more urgency as a possible solution to the problem.
> Rely on Reaction CSS extraction vs stitch

- src/desktop/apps/fair/components/capture_signup/test/index.coffee
- src/desktop/apps/user/components/password/test/view.coffee
- src/desktop/apps/user/components/password/view.coffee
- src/mobile/components/modal/test/view.coffee
This seems to have been previously working b/c of a side affect.
We used to call https://github.com/artsy/force/blob/0c16b2dd944d17143b8a6c2cd562f6ac5398791a/src/desktop/lib/global_client_setup.tsx#L64-L74 on every page, which had the 'nice' property of logging off and refreshing if _anything_ failed in that `/api/v1/me` call.
This 'change password' form would redirect to you `/log_in?redirect_uri=...`, which would actually do nothing but redirect you to `/` since you were still 'logged in'. Then, the client side check would kick in, and _actually_ log you out and reload the page, leaving you looking at a logged off homepage (and would then need to log in, and would not redirect since the page had _already_ redirected back to `/`).
This solution feels a bit better. It explicitly logs you …
> @joeyAghion => Successfully log user off when changing password

- package.json
- yarn.lock
Currently, Force's common.js bundle ends up with two versions of moment and two versions of moment-timezone due to mismatched versions in the lockfile. This PR updates both to match with other dependencies+resolutions, saving an estimated 52 KB (after GZIP) on page load.
Tests all passing with the exception of an infiniteScroll test that fails even with the previously declared versions of moment/moment-timezone.
> Optimizing moment packages

- docs/rolling_back.md
During a rollback earlier today, we saw that there was a seemingly extraneous step in there about checking CircleCI — this just removes that.
> Update rollback docs

- webpack/envs/base.js
- webpack/envs/ci.js
- webpack/envs/debug.js
- webpack/index.js
Noticed that having the webpack `DuplicationPlugin` in the base config was leading to errors when running `yarn link`:
```sh
｢wdm｣: Error: ELOOP: too many symbolic links encountered, open '/Users/cn/Sites/artsy/force/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/node_modules/@artsy/reaction/package.json'
ℹ ｢wdm｣: wait until bundle finished: /
```
This moves things into a …
> Move debug-related Webpack plugins to debugConfig

- src/index.js
- src/lib/middleware/rateLimiting.ts
- src/lib/setup.js
This resolves issues that was causing rate limiting to not work correctly in staging. 
There were several issues.
1. I can't type and writing a file in typescript doesn't help you when importing from coffeescript
2. Add the middleware was being setup before the redis cache was ready. This meant all the things that were supposed to be using the redis cache in the middleware weren't. That explains why the other rate limiting solution wasn't working. 
3. I was confusing myself on `res` and the results of the limiter. I was trying to put the response on something that wasn't a response object. 
I also made a few improvements.
1. I don't check to see if the limiter is enabled on every middleware consumption. That was just wasted cycles. 
2. I moved the `compression` middleware below rate …
> Resolve rate-limiting issues

- src/desktop/config.coffee
- src/lib/middleware/rateLimiting.ts
This update isn't strictly required, but I thought it'd be good as it'll give us more granular control without having to change code in force. I'm basically just adding a few envs. 
These are the default values too.
```diff
REQUEST_EXPIRE: 60
REQUEST_LIMIT: 300
REQUEST_PER_INSTANCE_FALLBACK: 100
+ REQUEST_PER_INSTANCE_LIMIT: 301
+ REQUEST_PER_INSTANCE_EXPIRE: 60
ENABLE_RATE_LIMITING: false
```
the `REQUEST_PER_INSTANCE_*` envs are all related to in memory limiters. `FALLBACK` is used as a limit for the in-memory limiter when redis is unavailable (or as an [insurance limiter](https://github.com/animir/node-rate-limiter-flexible/wiki/Insurance-Strategy)). The per request `LIMIT` and `EXPIRE` envs are for the [in memory block](https://github.com/animir/node-rate-limiter-flexible/wiki/In-memor …
> Add more control over rate limit settings

- hokusai/production.yml
These were applied previously. This PR brings `master` in sync.
> Bring production config up-to-date with temporary measures

- hokusai/production.yml
Create a canary deployment to test rate limiting.  This sets up a separate deployment overriding the environment variable `ENABLE_RATE_LIMITING ` in Force.  The replicas created by this deployment will serve traffic along side the force-web deployment because its labels match the services's `selector` fields.
`hokusai production update`
> canary deployment rate limiting

- hokusai/production.yml
This just applies correct syntax.
Will follow up with a PR _removing_ the deployment just so master matches prod.
> @ashkan18: Fix nginx config for canary deployment

- src/desktop/apps/article/templates/meta.jade
- src/desktop/apps/articles/templates/meta/articles.jade
- src/desktop/apps/articles/templates/meta/news.jade
- src/desktop/apps/artwork/components/meta/index.jade
- src/desktop/apps/editorial_features/components/gucci/templates/head.jade
- src/desktop/components/fair_layout/templates/index.jade
- src/desktop/components/main_layout/templates/head.jade
- src/mobile/apps/articles/meta/articles.jade
Since all of our webfonts can now be found in a single file, [all-webfonts.css](https://webfonts.artsy.net/all-webfonts.css), we can deprecate references to force-webfonts and unica-webfonts
> Consolidating fonts

- src/lib/setup.js
This moves blacklisting and rate limiting to the top of the middleware queue. If the app level rate limiting applies, we want that to happen as early as possible in the middleware chain to hopefully reduce as much load on the node instance as possible.
> Ensure blacklisting, rate limit happen first

- src/desktop/components/main_layout/header/templates/user.jade
For whatever reason this was leading to a page shell not being refreshed on click.
> Undo # from logout link

- src/desktop/apps/auctions/routes.coffee
Slack
context: https://artsy.slack.com/archives/C02BC3HEJ/p1550251913148600
Fixes https://artsyproduct.atlassian.net/browse/AUCT-224
In brief:
- Recently turned on Rate limiting in force
- Previously, caching at /auctions endpoint was broken
- Enabling rate limiting fixed this cache
+ but we don't want to cache auctions response, so remove `cache`
option in `auctions.fetch`
Some evidence of (undesired) caching going into effect:
- Data Dog trace showing queries to Gravity:
https://app.datadoghq.com/apm/trace/1497793948768870733
+ Note how all traces _in the future_ of this trace respond very quickly,
and don't integrate with Force's HTTP service or Gravity.
> Don't cache the gravity response in /auctions

- src/desktop/config.coffee
- src/lib/middleware/rateLimiting.ts
I was thinking about the rate limiter union on the way home and I decided that having `Promise.all` and the cycles that limiter introduced probably wasn't going to help things. 
I re-organized it a bit. The burst limiter is hit first. This is our first line of defense against high traffic. The in-memory limiter is very performant, so toggling that first makes sense. If it passes that, _then_ it applies to the rate limiter. I know running these serially might not be extremely ideal, but the idea is to trigger the ddos protection as fast and with as few cpu cycles as possible. Then we can get into the standard cross process rate limiting and proceed from there. 
Oh, and I added docs. Ish.
> Improve rate limiting performance, add docs

- .circleci/config.yml
- scripts/test.sh
Does (or attempts to do) a few things:
1. Generally speed up force builds (in part by having yarn cache optimization via the yarn orb)
2. Uploads a [duplicate bundle report](https://15960-22887404-gh.circle-artifacts.com/0/home/circleci/project/.artifacts/duplicates-report) from webpack to circle ci's artifact storage for later processing
3. Generally cleans up and dries out the config where it makes sense
For some reason unknown to me, the test script was running webpack in _development_ mode. I can't for the life of me see why it would do that... @damassi or @alloy if either of you happen to know why I'd love to hear more.
> Improve force CI

- src/desktop/apps/article/templates/meta.jade
- src/desktop/components/main_layout/stylesheets/index.styl
- src/desktop/components/main_layout/stylesheets/slick-css.styl
- src/desktop/components/main_layout/templates/head.jade
- src/desktop/components/main_layout/templates/redesign.jade
This PR removes requests to an [external library](https://cdnjs.com/libraries/slick-carousel/1.6.0)  that was being referenced throughout Force and adds those styles to main_layout.
This cuts two calls, those to slick.min.css and slick-theme.min.css, that were very early in the stack [screenshot](https://cl.ly/717a50673c60)
> Move slick.css and slick-theme.css in-house

- CONTRIBUTING.md
- package.json
Adds a new command `yarn start:ssr` as well as some docs that allows us to get around the `yarn link` issue + styled-components 4. This approach is pretty naive. (If anyone has any suggestions for a better approach please send them over!)
> Add yarn start:ssr command

- hokusai/production.yml
Reverts force to our pre-DDoS configuration and addresses https://artsyproduct.atlassian.net/browse/PLATFORM-1192
The Nginx config is easy enough to add back by reverting this PR but implementing L7 DDoS protection makes these Nginx rules redundant.
> Remove force-nginx and reinstate readinessProbe #PLATFORM-1192

- package.json
- yarn.lock
Updates to latest.
Note that `@types/styled-components` hasn't been updated yet since it leads to compatibility issues with our version of react. Will need to do that at the same time.
> Upgrade styled-components@4.1.3

- src/lib/middleware/rateLimiting.ts
Remove the closure around this next step, but it looks like doing so throws the middleware into an infinite loop. Not exactly sure _why_, but I was able to replicate locally. This fixed it.
> Fix middleware getting stuck in a loop

- src/desktop/apps/fair/routes.coffee
- src/desktop/collections/ordered_sets.coffee
- src/desktop/components/info_menu/index.coffee
- src/desktop/models/fair.coffee
- src/desktop/models/ordered_set.coffee
- src/desktop/test/models/ordered_set.coffee
https://artsyproduct.atlassian.net/browse/GALL-1416
The [backbone-super-sync caching](https://github.com/artsy/backbone-super-sync#built-in-request-caching) has been broken for a while and [got fixed](https://artsy.slack.com/archives/C9ZJYFDNF/p1550498674086700) last week. The default 6 hour caching delay doesn't work for fairs team's workflow when tweaking the design of the fair overview page. This PR shortens the caching time to 1 min on the fair overview page.
> GALL-1416: Shorten backbone-super-sync cache time on fair overview page

- src/desktop/components/react/stitch_components/SearchBar.tsx
This PR contains a few small styling changes for integration of our new auto-suggest search bar. It makes the search bar look like this:
(Ignore the lack of padding on the search suggestion/preview panes - those will be taken care of in reaction!)
> Style force integration with reaction/search-bar

- src/desktop/apps/search/routes.coffee
- src/desktop/apps/search/test/routes.coffee
- src/mobile/apps/search/routes.coffee
- src/mobile/apps/search/test/routes.coffee
Nice catch!
We were passing the input as `term` in the desktop XS case: https://github.com/artsy/force/blob/c2f387c62a2a10b0ff2adb99eac6881b3176e2db/src/desktop/components/main_layout/header/templates/small_screen_header.jade#L8 , which sort of makes sense b/c the mobile version of search results uses `term`.
However, that causes an issue w/ XS devices that aren't real devices (which admittedly is an edge case). With responsive pages and us resizing windows we came across it.
This just allows either ?q or ?term to work for search results, they probably should have been the same in the first place.
> @pepopowitz => [Bugfix] Honor ?q and ?term query params for mobile/desktop search results

- webpack/envs/production.js
Lets see what happens if we stick strictly to `Content-Encoding: gzip`, and omit the Compression plugin.
> Comment out compression plugin

- webpack/envs/production.js
See what happens when automatic cloudfront gzip is turned off and compressed assets are directly returned.
> Directly serve gzip .js files

- scripts/uploadToS3.js
- webpack/envs/production.js
Remove `ContentEncoding: gzip` from css since css isn't manually compressed.
> Remove ContentEncoding: gzip from css

- src/desktop/components/main_layout/header/templates/large_screen_header.jade
This lets you just hit 'Enter' after typing in the input and go to the search results page.
For now, this is just copied from: https://github.com/artsy/force/blob/9f129c2ffeb1f8a02d75269e616c9f19d5299abe/src/desktop/components/search_bar/templates/index.jade#L2
As we add this to the mobile and small desktop versions, we can consolidate into a shared layout or something. Tested locally w/ no JS- works!
> @pepopowitz => [Autosuggest] Wrap stitched Reaction component in a <form>

- .circleci/config.yml
- yarn.lock
This integrates with the library [dupe-report](https://github.com/artsy/dupe-report) that builds on top of [inspectpack](https://github.com/FormidableLabs/inspectpack). As a part of every build, force is saving the output of `inspectpack` as a circleci artifact. On a PR, `dupe-report` will download the artifacts from the PR and master and compare them. If they're the same, it bails. If they differ, it'll generate a report like the one below and send a message to the client-infra channel. If the duplicates are cleaned up and the report starts matching master then it'll auto delete itself. 
I've generally tried to put a lot of work into making this legible and useful for folks. It should save us from shipping new duplicates without realizing it. Also, we've now got a list of duplicates to …
> Add duplicate reports for force webpack builds

- src/desktop/components/view_in_room/index.jade
- src/desktop/components/view_in_room/index.styl
- src/desktop/components/view_in_room/view.coffee
When using the view-in-room feature, I want the comparable objects to have width measurements (ft) so that I can have a better sense of scale of how the artwork will look when hung up.
Some issues with the width and top margin of the bar but only when the window is resized weirdly. Spent a day trying to fix bit couldn't find a good solution but am open to suggestions.
> View-in-room 2.0 - Add measurement dimensions (width) to bench

- hokusai/production.yml
- hokusai/staging.yml
We'll get Nginx access / error logging out of the box.  If Force falls over, we will probably get 503s from Nginx rather than 504s in ELB logs.
> reinstate Nginx sidecar and proxy to Force

- src/lib/setup.js
Noticed that when an error occurs before the sharify middleware has been initialized the error-page will error out due to missing variables. This moves it near the top, yet after rate limiting.
> Fix sharify middleware order

- src/desktop/config.coffee
A small update to ensure the rate-limiting setup doesn't puke with the defaults.
> Fix rate limiting defaults so they don't error

- src/desktop/lib/global_client_setup.tsx
- src/mobile/components/layout/bootstrap.coffee
"When the only tool you have is a hammer.....everything looks like a nail"
This restores behavior that was present up until ~6 months ago, which basically calls `/api/v1/me` directly client-side _for every page load_ (this is well cached by Gravity). If there's any error, you are logged out (seems like this error check can be restricted to just 401/403).
Still to check: will this work on pages that wind up 500/404'ing , or will this have no affect on those cases? (which means they would need to navigate to a page that at least returns a 200 to get this to log them out).
> @joeyAghion => [Session] Restore checking that session is valid client-side on all pageloads

- src/desktop/components/view_in_room/test/view.coffee
- src/desktop/components/view_in_room/view.coffee
Woof. Played around with a bunch of scaling options and this one appears to work in most cases... 
The image will overlap the measurement bar if the screen size is super tiny, but I don't think that's a real use-case anyways so am 👍 ignoring.
Some screenshots:
Huge image:
> View in Room: Updates relative scaling so images don't overlap the measurement bar

- Dockerfile
- scripts/start.sh
- src/index.js
Due to an issue we were seeing with DataDog analytics not reporting server-side compilation is disabled for now. See https://artsy.slack.com/archives/CA8SANW3W/p1551397845101500 for more info.
> Disable server-side code compilation

- src/desktop/components/main_layout/header/index.styl
- src/desktop/components/main_layout/header/small_screen_header.styl
- src/desktop/components/main_layout/header/templates/large_screen_header.jade
- src/desktop/components/main_layout/header/templates/small_screen_header.jade
- src/desktop/components/react/stitch_components/SearchBar.tsx
- src/mobile/components/layout/bootstrap.coffee
- src/mobile/components/layout/stylesheets/main_header.styl
- src/mobile/components/layout/templates/main.jade
- src/mobile/components/layout/test/layout.coffee
This PR stitches the `<SearchBar>` from reaction into the mobile layout. 
The padding on the stitched `<SearchBar>` is not consistent across the three layouts (large desktop, small desktop, and mobile), so the vertical padding is also moved into the layout stylesheets.
There are still a couple of small visual issues with the search bar on mobile, and we will address those in follow-ups, but this PR gets it hooked up for mobile so that we can start QA'ing it.
> Add new search bar to mobile layout

- package.json
Ha. @joeyAghion, you get the last laugh. 
https://github.com/artsy/force/pull/3657 made a change which caused the bundle size to jump by 90 kB and added new duplicates. CI is failing now because of exceeded budget limits. This increases it until we can do the work to fix what was introduced.
> Bump bundle size

- .circleci/config.yml
Remove checks for duplicate bundles and bundle sizes.
> Disable performance checks

- Dockerfile
- scripts/start.sh
- src/desktop/config.coffee
- src/index.js
- src/lib/datadog.ts
- src/lib/setup.js
- webpack/index.js
- webpack/utils/getCSSManifest.js
When deploying server-side compilation we noticed that DataDog logging no longer worked. Reading up on [the docs](https://docs.datadoghq.com/tracing/languages/nodejs/) it states: 
> This library MUST be imported and initialized before any instrumented module. When using a transpiler, you MUST import and initialize the tracer library in an external file and then import that file as a whole when building your application. This prevents hoisting and ensures that the tracer library gets imported and initialized before importing any other instrumented module.
This PR addresses this issue, and re-enables server-side compilation.
> Fix DataDog load order; Reenabled server compilation

- src/mobile/components/layout/stylesheets/main_header.styl
This is a tiny little margin fix for the new search bar on mobile. 
Without this change, the header looks like this:
The gray line is in the wrong place, and makes things look funny.
This change bumps that line down, so it looks much better:
> Adjust bottom margin of mobile search bar

- src/desktop/components/main_layout/header/small_screen_header.styl
When I submitted #3668, I didn't realize that there were two different templates for the header on mobile. I fixed the one that is used by the home page, but the one used by other pages still looks like this:
This PR nudges that gray bar down, and makes it look like this:
> Adjust margin for new search bar on pages other than home

- src/desktop/apps/article/__tests__/routes.test.js
- src/desktop/apps/article/routes.ts
- src/desktop/components/split_test/running_tests.coffee
Disables `editorial_collections_rail` test by renaming to `editorial_collections_rail_qa`, and removing `splitTest.view()`.  Also limits displaying new rail to admins only.
> Switch editorial CollectionsRail test to admin only and dummy name

- src/desktop/apps/artwork2/client.tsx
- src/desktop/components/view_in_room/view.coffee
Addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-924
This PR makes a couple of changes to fix weird behavior we were seeing as the image transitions in/out of view in room.
- Updates the logic around whether to constrain the image based on the bounding box width or height (as the viewport changes size, the image can change which side it's "bound" on-- before we were assuming based on the dimensions of the image itself)
- Adds an extra padding to the `body` when we transition in/out to account for a little shift that occurs due to the scrollbar being removed. It appears all browsers have scrollbars that are `17px`, so I went with that.
Before:
After:
> Fixes view-in-room transition weirdness

- src/desktop/components/main_layout/templates/instant-page.jade
It looks like the `closest` api isn't available on some older browsers, though I'm not sure why it would be throwing on mobile safari. This adds a guard to make things safer, and unminifies the script (its so small and critical i think that it's better if this is readable.
> Make instant.page safer

- src/desktop/components/json_page/routes.coffee
- src/desktop/components/json_page/update.coffee
- src/desktop/config.coffee
- src/lib/middleware/error_handler.coffee
Fixes https://artsyproduct.atlassian.net/browse/BUGS-780.
There was a slight difference between how Webpack handles `require.resolve` and how node handles it, which was leading to an issue where a file lookupID !== an actual file, when running on node. By swapping it out with the more conventional form it fixed the problem.  
Also adds a `VERBOSE_LOGGING` flag that can be toggled on to display errors in our logs and error page outside of `NODE_ENV=development`, vs just posting the status code.
> Fix JSON page resolution

- .babelrc
- package.json
- src/desktop/apps/articles/components/App.tsx
- src/desktop/apps/auction/components/App.js
- src/desktop/apps/categories/components/App.js
- yarn.lock
After doing some experimenting I realized we don't need this anymore with some recent updates to webpack 4. Looking through the `react-hot-loader` repo it seems like its a bit of a fire, and it already broke our hooks support once, so going to just remove. (Compilation seem faster without it, too.)
> [Toolchain] Remove react hot loader

- src/desktop/index.js
- src/lib/setup.js
- src/mobile/index.js
While stitching in the new nav bar I noticed that changes weren't being reflected until I stopped and restarted the server. This was due to stitch's middleware being mounted with [the rest our middleware](https://github.com/artsy/force/blob/master/src/lib/setup.js), which sits just below [express-reloadable](https://github.com/artsy/express-reloadable)'s hot-swapping boundary -- [`src/desktop`](https://github.com/artsy/force/blob/master/src/lib/setup.js#L263) (and `src/mobile`). 
By mounting inside of `desktop/index` (and `mobile/index`) -- where our application-level express sub-apps are mounted -- it flips on hot-swaps so that changes are immediately reflected without a server restart.  
This  was a regression introduced in https://github.com/artsy/force/pull/3283.
> Make stitch reloadable

- src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
The main menu bar height has changed, updated the `NewsNav` position top to prevent the appearance of a gap between `NewsNav` and main nav.
> [Trivial] Update newsNav positionTop

- src/desktop/components/main_layout/footer/upper.jade
- src/desktop/components/main_layout/header/templates/more.jade
This request: https://artsyproduct.atlassian.net/browse/GALL-1479
I believe we have this same link in footer on artwork and artist pages. My guess is that it has to be changed there as well. Will double check with product but that would need to be changed in reaction  either way.
So for now - just header. Also I believe this header is now being rebuilt. Need to make sure that new version points to the correct link.
Also wondering if there is bunch of code in 'gallery-partnerships' that we can clean up. But not sure is it is used anywhere else. So not changing anything but link in this pr:)
> change gallery partnerships url to point to 'https://partners.artsy.net'

- package.json
As [discussed in Slack](https://artsy.slack.com/archives/C02BC3HEJ/p1552399118228900) - 
I am having trouble getting things running locally, and it was suspected that I need to clean my yarn cache. @damassi suggested I add it to the clean task, as well.
> Clean `.cache` as part of `clean` task

- src/desktop/apps/articles/components/App.tsx
- src/desktop/apps/articles/routes.js
- src/desktop/apps/articles/test/routes.js
This PR conditionally adds the `showCollectionsRail` prop to `/news` pages which are different then the`/news/:id` route in the article app. It also wraps the `<InfiniteScrollNewsArticle>` component with a ContextProvider which is need to make the relay query in reaction.
> Ensure collections rail displays for /news page

- src/desktop/analytics/criteo.js
- src/desktop/analytics/main_layout.js
There's an open question in Slack about the removal of this Criteo thing.
However, for now, removing it (and unblocking Force deploys) makes sense since it wasn't actually being exercised at all with the new page (so it wasn't actually being used for a while, and thus removing it here doesn't change current production behavior).
> @sweir27 => Remove unneeded analytics code referenced by old artwork page

- src/desktop/apps/article/__tests__/routes.test.js
- src/desktop/apps/article/routes.ts
- src/desktop/apps/articles/routes.js
- src/desktop/apps/articles/routes.ts
- src/desktop/apps/articles/test/routes.js
- src/desktop/components/split_test/running_tests.coffee
- Renames editorial collections rail test to launch A/B test
- Removes admin only flags to expose rail to all users
- Converts Articles routes to ts
Although the original implementation used an integer for `EDITORIAL_COLLECTIONS_RAIL`, this no longer seems to work for me locally and it has been updated to use a string.
> Rename & launch editorial collections rail test

- hokusai/production.yml
- hokusai/staging.yml
Updating DNS config for production to Force uses the internal Kubernetes DNS server (we had to work around this in an earlier version of Kubernetes but now all apps should be using this config).  With this set up we can redirect all Force backend -> Metaphysics traffic internally with https://github.com/artsy/metaphysics/pull/1581 and https://github.com/artsy/substance/pull/115 rolled out.
Also I moved the Nginx config to the shared configmap `nginx-config` like we have set up in production
`hokusai production update` 
Staging already applied
> #migration Update kubernetes yaml files for up-to-date dns config and shared nginx config

- .vscode/settings.json
- src/desktop/apps/artwork/__tests__/routes.jest.ts
- src/desktop/apps/artwork/server.tsx
Nice catch that would be lost this functionality when the old artwork app went away.
~~I'm...struggling a little bit with the tests here :(~~ (tests in!) , so this can be merged in the meantime if admins need the functionality back right away.
> @sweir27 => [Artwork] Reinstate artwork download functionality for admins

- webpack/envs/productionConfig.js
Noticed the other day that when running builds on CI it's good to run CSS compilation as well, as we have a lot of complex paths in old code that when modified could break a build on deploy. This adds a bit of time savings to prevent that from occurring.
> Compile CSS on CI

- src/desktop/apps/article/components/App.tsx
- src/desktop/apps/article/routes.ts
- src/desktop/apps/articles/components/App.tsx
- src/desktop/apps/articles/routes.ts
Addresses: [GROW-1161](https://artsyproduct.atlassian.net/browse/GROW-1161)
When we launched the editorial collections rail test we were firing the `Experiment Viewed` event from the server when we should be firing this event from the client so that we have access to the global `analytics` object. This PR move that call to the client.
> refactor to fire viewed experiment event from the client

- src/desktop/apps/search2/server.tsx
Currently if you go to https://staging.artsy.net/search2/artists?term=andy directly you get a 404, whereas navigating via tabs (which updates the URL), it's fine.
Just tweaks our matching to make sure we match all `/search2` routes.
> @dblandin => [SearchResults] Match /search2* to make sure sub-tabs are matched

- src/desktop/apps/article/__tests__/routes.test.js
- src/desktop/apps/article/routes.ts
- src/desktop/apps/articles/routes.ts
Because `sd.EDITORIAL_COLLECTIONS_RAIL` seems to be a string in the staging environment but is a integer in production we are casting it to a string to be able to consistently evaluate whether the collections rail should be visible.
See for context:
https://artsy.slack.com/archives/C2TQ4PT8R/p1552934620436400
https://artsy.slack.com/archives/C9SATFLUU/p1552934543150200?thread_ts=1552928834.148000&cid=C9SATFLUU
> ensure EDITORIAL_COLLECTIONS_RAIL is evaluated as a string

- src/desktop/apps/artist/client.tsx
- src/desktop/apps/artist/server.tsx
- src/desktop/components/split_test/running_tests.coffee
Addresses: [GROW-1139](https://artsyproduct.atlassian.net/browse/GROW-1139)
Sets up the artist collections rail test in force. This uses showCollectionsRail to determine when to show the rails on the artist page.
Related to https://github.com/artsy/reaction/pull/2172
> configure artist collections rail a/b test

- src/desktop/analytics/main_layout.js
With 02b5cc41cb149e3a46a2b830b9b80024328a2484 we got artwork page tracking duplicated so this just adds it back to the exclude list.
> DISCO-856: Exclude another route taken care of in Reaction

- src/desktop/apps/articles/templates/meta/section.jade
- src/desktop/apps/feature/index.coffee
- src/desktop/apps/feature/routes.coffee
- src/desktop/apps/feature/test/routes.coffee
https://artsyproduct.atlassian.net/browse/LD-299
We used to have a number of pages with the name "city guide" in them, unrelated to the new City Guide feature we are launching on iOS.
This PR redirects requests for any of the following deprecated urls —
```
/feature/city-guide
/feature/city-guides
/feature/city-guide-berlin
/feature/city-guide-london
/feature/city-guide-los-angeles
/feature/city-guide-los-angelespar
/feature/city-guide-miami
/feature/city-guide-new-york
/feature/city-guide-paris
/feature/city-guide-rio-de-janeiro
/feature/city-guide-sao-paulo
/feature/city-guide-stockholm
```
Users who end up requesting these urls are probably coming from  organic search results for "artsy city guide" or something similar.
We should send them to the destination on artsy.net that's most …
> Redirect requests for obsolete city guide pages

- src/desktop/apps/collect/client.js
This whole thing is sort of an anti pattern, this URL thing should just be happening in Reaction (directly using `window.history.pushState`. For now, this fixes the current issue.
> @damassi => [Collect] Correctly unset medium from URL when deselected

- src/desktop/apps/search2/server.tsx
This commit ports over the current behavior of /search without a `q=` query param.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-894 :lock:
> Redirect to home page if /search2 is missing `term=` query param

- src/desktop/apps/search2/server.tsx
The existing search bar redirects to search?q=term while the new search results page expects a `term=` query param. This commit adds a redirect to support both.
ticket: https://artsyproduct.atlassian.net/browse/DISCO-904 :lock:
> Redirect use of search `q=` query param to `term=` query param

- webpack/envs/productionConfig.js
This pulls the (potentially many) comments out of our payload files and adds them in an extra `.LICENSE` file. 
For example...
> Extract license comments from payloads

- src/desktop/analytics/bidding.js
- src/desktop/analytics/inquiry_questionnaire.js
this is needed for third party marketing channels to assign the conversion events to specific artworks.
> send product ids with key transaction events

- src/desktop/components/error_handler/index.jade
Fixes https://artsyproduct.atlassian.net/browse/PLATFORM-1316
For some reason pointing the main template at `index` fails to load JS. Not sure exactly why, but pointing at the blank page template fixes the problem sufficiently.
> Fix error page mount

- src/desktop/apps/search2/server.tsx
- src/desktop/apps/search2/templates/index.jade
As discussed, we deliberately don't want to render search results on the server. We want the experience to feel as snappy as possible to the user, and are willing to live with SEO ramifications of this change (indeed, a work item is to disallow /search on robots.txt).
So, this just removes all SSR rendering in favor of our blank 'redesign' template (which continues to load the header/NAV and other global client JS, which is essential).
We then let the normal client-side hydration take care of fetching + rendering everything client-side. There doesn't seem to be any warnings/errors doing this and the results looked very promising locally.
A next step could be to iterate on the blank template to include a nice loading state/splash screen (which will get replaced by the client-side rendered …
> @dblandin => [Search] Dont render the search results page on the server

- docs/rolling_back.md
Update docs to mention easier way for finding proper production image.
This doc seems pretty generic and applies to all `hokusai` based apps, we can potentially move this to a more common place and point to it from here and possibly other repos.
> Update docs to mention  `-f `option

- src/desktop/apps/auction/__tests__/routes.jest.js
- src/desktop/apps/auction/components/__tests__/DOM.jest.js
- src/desktop/apps/auction/components/__tests__/Layout.test.js
- src/desktop/apps/auction/components/artwork_browser/header/__tests__/FilterSort.test.js
- src/desktop/apps/auction/components/artwork_browser/header/__tests__/HeaderDesktop.jest.js
- src/desktop/apps/auction/components/artwork_browser/header/__tests__/HeaderMobile.test.js
- src/desktop/apps/auction/components/artwork_browser/main/artwork/__tests__/BidStatus.test.js
- src/desktop/apps/auction/components/artwork_browser/main/artwork/__tests__/GridArtwork.test.js
- src/desktop/apps/auction/components/artwork_browser/main/artwork/__tests__/ListArtwork.test.js
- src/desktop/apps/auction/components/artwork_browser/main/artwork/__tests__/MasonryArtwork.test.js
- src/desktop/apps/auction/components/artwork_browser/sidebar/__tests__/ArtistFilter.test.js
- src/desktop/apps/auction/components/artwork_browser/sidebar/__tests__/BasicCheckbox.jest.js
- src/desktop/apps/auction/components/artwork_browser/sidebar/__tests__/MediumFilter.test.js
- src/desktop/apps/auction/components/artwork_browser/sidebar/__tests__/Sidebar.test.js
- src/desktop/apps/auction/components/artwork_rail/__tests__/ArtworkRail.test.js
- src/desktop/apps/auction/components/layout/__tests__/Banner.jest.jsx
- src/desktop/apps/auction/components/layout/__tests__/Footer.test.js
- src/desktop/apps/auction/components/layout/active_bids/__tests__/ActiveBidItem.jest.js
- src/desktop/apps/auction/components/layout/auction_info/__tests__/AuctionInfoContainer.jest.jsx
- src/desktop/apps/auction/components/layout/auction_info/__tests__/Registration.jest.js
Disables tests from `src/desktop/auction` -- these were not run prior to changes in https://github.com/artsy/force/pull/3877, but some were enabled optimistically.  Here all tests in that directory are turned off for the moment, and we can coordinate with the auctions team to enable as priority allows. 
I ran this build 5 times without hitting a timeout, so I believe this should address the flakiness we've experienced since last night.
> x problematic tests

- src/desktop/components/main_layout/templates/head.jade
- src/mobile/components/layout/templates/head.jade
Noticed a warning reported by lighthouse that we were including criteo in our preconnect list when it wasn't on the page. 
I've just removed it for now.
> Remove criteo from our preconnects

- src/desktop/apps/search2/client.tsx
Follow up to https://github.com/artsy/force/pull/3910
The identifier was updated following review feedback, but the client-side callback which removes the loading container still referenced the old value. This commit makes that update.
> Update identifer of loading container

- src/desktop/models/search_result.coffee
- src/mobile/models/search_result.coffee
This commit backfills the fix made to Metaphysics, backing the new search results page, which always displays start/end times for auctions in Eastern Time.
> Backfill fix for auction search result item timezone display

- src/desktop/apps/search2/server.tsx
We won't hydrate this react component client-side so much of our media/responsive handling will be ineffective. I think it's simpler to disable the loading skeleton for mobile clients and let the full search results app take over once it hydrates.
> Disable search results page loading skeleton for mobile clients

- package.json
- yarn.lock
Bumps the version of moment-timezone that's now significantly smaller due to a reduced time-range set in `latest.json`. See https://github.com/moment/moment-timezone/issues/697 for more context.
> Update moment-timezone to reduce payload size

- src/desktop/apps/search2/server.tsx
This commit enables server-side rendering of loading skeleton for devices providing a mobile user-agent.
This depends on a corresponding PR (https://github.com/artsy/reaction/pull/2337) which improves styling of the loading skeleton for mobile devices.
> Enable search results page loading skeleton for mobile devices

- src/desktop/models/article.coffee
- src/desktop/test/models/article.test.coffee
https://artsyproduct.atlassian.net/browse/GROW-1186
This adds a publication date to the standard metadata block that Google considers when deciding what to show as the date next to a search result.
This field was previously identified as missing with Google's [structured data testing tool](https://search.google.com/structured-data/testing-tool/u/0/), but checks out now:
Note that there are other fields that are still considered missing, but fixing them would require a deeper dive into the Schema.org requirements for annotating these correctly (as well as probably refactoring the various implementations in Force now — `toJSONLDAmp` vs `toJSONLD`).
So we can create a follow-up ticket if need be (cc @junybrum ).
> Add datePublished to JSON-LD metadata for articles

- src/desktop/components/email/test/editorial_signup.test.coffee
- src/mobile/apps/articles/test/client/editorial_signup.test.coffee
- `EditorialSignupView` -- this component is not in use as far as I know and should be deprecated
> x Prolematic tests

- package.json
- yarn.lock
Reverts artsy/force#3964
Looks like this was leading to a break in https://www.artsy.net/galleries, where changes to the location would fail to destroy and re-create the carousel: 
```
TypeError: this.allOff is not a function
at b.f.destroy (flickity.js:887)
at r.destroyFlickity
```
Though this was a minor version change, lets follow up on the breaking change it seemed to introduce.
cc @zephraph, @starsirius
> Revert "Remove duplicate flickity"

- src/desktop/apps/home/client/setup_home_page_modules.coffee
This fix is needed to change `"undefined"` -> `undefined` (and so `if(val)` works, etc.)
> @joeyAghion => [BugFix] Drop unneeded interpolation for homepage variables

- .env.oss
- src/desktop/apps/artists/test/template.test.coffee
- src/desktop/apps/fair/test/templates.test.coffee
- src/desktop/apps/fair_organizer/test/template.test.coffee
- src/desktop/apps/home/templates/index.jade
- src/desktop/components/main_layout/templates/scripts.jade
- src/lib/setup_sharify.js
- test.config.js
Initial steps to use invisible captchas, related to https://artsyproduct.atlassian.net/browse/PLATFORM-1378
- Adds header script for google reCAPTCHA 3 to main layout
- Creates a new 'action' for loading the homepage
- Adds `RECAPTCHA_KEY` to sd 
The homepage action will start firing an invisible captcha whenever loaded, and operates in the background without affecting user experience. Once merged we should begin to see scores for users in our [reCAPTCHA admin](https://www.google.com/u/0/recaptcha/admin/site/346113690), which can help us set a baseline to determine what scores we want to accept or reject from the login/signup form.
The `RECAPTCHA_KEY` is a public key. We also have a private key that will be used once we start verifying scores on our server.
> Add reCAPTCHA 3 scripts and fire homepage event

- src/desktop/config.coffee
- src/mobile/config.coffee
Missed one step in #3993, this makes sure client can access `RECAPTCHA_KEY`.
> Add RECAPTCHA_KEY to client sd config

- src/desktop/apps/artist/server.tsx
- src/desktop/components/split_test/running_tests.coffee
- src/test/acceptance/artist.js
Artist Insights V2 launched a while ago. This PR follows-up and removes the splitTest experiment.
> Remove artist insights splitTest experiment

- src/desktop/components/main_layout/stylesheets/index.styl
Didn't see this in production before the deploy, hides a google badge for the reCAPTCHA lib.
> Hide captcha badge

- src/desktop/config.coffee
#trivial change, I forgot to include the env variable in the config file as well.
As a sidenote we should move away from `./desktop/config` and `./mobile/config`
https://github.com/artsy/force/blob/02f99c674f42a8d82b925e5716657b0a782acd6b/src/config.js#L1-L12
> Forgot default value for env var #trivial

- renovate.json
This updates renovate's config to use the new app preset. Removes assignees (other than myself) to be in line with our new limited assignee workflow, and delete the automerge config (which is already configured via the app preset).
> Use new renovate app config

- src/desktop/apps/auction_support/client/registration_form.coffee
- src/desktop/apps/auction_support/test/client/registration_form.test.coffee
- src/desktop/components/credit_card/client/error_handling_form.coffee
- src/mobile/apps/auction_support/client/registration_form.coffee
- src/mobile/apps/auction_support/test/client/registration_form.test.coffee
- src/mobile/components/credit_card/client/error_handling_form.coffee
If a user has left a required field empty after clicking "Register", they will see "invalid [telephone, city, state]" etc. On the app we currently display "This field is required" which is a much clearer message.
https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=41&view=planning&selectedIssue=PURCHASE-874
__Before:__
__After:__
> Improve copy when user submits auction registration form without a required field

- package.json
- yarn.lock
- Updates Flickity version to be the same as the version used in Reaction
- Does not introduce bug introduced in version `2.2.0` mentioned here https://github.com/artsy/force/pull/3985
> Matches flickity@2.1.2 for Force and Reaction

- patches/react-flickity-component+3.2.0.patch
- Follow up to https://github.com/artsy/reaction/pull/2388 for Force to remove Flicker from Flickity carousel
- Will also remove this patch once https://github.com/theolampert/react-flickity-component/pull/64 is merged.
> Patches flickity

- scripts/start.sh
When working with local metaphysics + force I find that they can't run at the same time with the default `yarn start` commands because they both try to start node with `--inspect-brk`. It's not possible to do that because `--inspect-brk` relies on a specific port.
So I often find myself having to alter the `start.sh` script of force, or MP's procfile just to get them both running at the same time. It's minor annoyance. Let's make it go away.
Also made the `-x` flag a production-only thing to avoid dev-time terminal noise.
Before:
After:
> improve start.sh

- src/desktop/analytics/bidding.js
- src/desktop/analytics/inquiry_questionnaire.js
Updates the schema for conversion events on bids and inquiries to allow segment to forward on data to Criteo.
> fix commercial conversion events tracking #minor

- src/desktop/config.coffee
This is now over on a WordPress blog so we're just killing this route and we've setup a vanity shortcut for it. There's more cleanup to do, but we'll get that in a separate PR once we're sure the redirection is working as expected.
> GALL-1563: Remove the gallery insights blog

- .circleci/config.yml
The last dozen or so builds have failed, most timing out after 10 minutes without output. We're not sure if the docker environment is crashing, getting killed, or getting disconnected, or just taking a long time. This doubles the wait time for staging and production deploys.
> @izakp: Try to avoid timeouts when waiting for rollouts to complete in CircleCI

- src/desktop/apps/article/__tests__/third_party_ads_enabled.jest.ts
- src/desktop/apps/article/components/InfiniteScrollArticle.tsx
- src/desktop/apps/article/components/layouts/Article.tsx
- src/desktop/apps/article/routes.ts
- src/desktop/apps/article/third_party_ads_enabled.ts
This PR is an update of https://github.com/artsy/reaction/pull/2391. Instead of checking feature flags and en/disabling externally hosted ads client side, we now handle it server side.
> Moves Enabled Ad Feature Flags to server

- src/desktop/apps/home/templates/index.jade
Missed one spot when updating reCAPTCHA events to fire only when `sd.RECAPTCHA_KEY` is present.
> Do not fire homepage reCAPTCHA event without key

- src/desktop/apps/home/client/auth_router.coffee
Related to https://artsyproduct.atlassian.net/browse/GROW-1179
Stops rendering errors passed via query params, and instead renders a default message.
> Auth errors via query render a message

- src/desktop/index.js
Missed one step when deprecating the `/auth` app here: https://github.com/artsy/force/pull/4068
Led to this error: https://circleci.com/gh/artsy/force/24744
> [TRIVIAL] Remove desktop /auth import

- mocha.config.js
- scripts/mocha.sh
- src/desktop/apps/article/client/__tests__/classic.test.js
- src/desktop/apps/article/templates/__tests__/meta.jest.js
- src/desktop/apps/auction_support/test/client/accept_conditions_of_sale_modal.test.coffee
- src/desktop/apps/consign/test/reducers.test.js
- src/desktop/apps/partner/test/client/articles.test.coffee
- src/desktop/apps/partner2/test/client/articles.test.coffee
- src/desktop/components/inquiry_questionnaire/test/map.test.coffee
- src/mobile/apps/feature/test/client/index.test.coffee
- src/mobile/components/app_banner/app_banner.coffee
- src/mobile/components/app_banner/test/app_banner.test.coffee
- src/mobile/components/layout/test/layout.test.coffee
- test.config.js
After addressing issues of uncaught promises in the Mocha run, it became apparent that our underlying problem, and a source of unpredictability was the use of `jsdom` in Mocha tests. Because all Mocha tests are using `benv` to mock the window, we were getting unpredictable conflicts in tests that require jQuery and some window functions. 
This PR separates the test environments for Jest and Mocha entirely, and removes any Mocha-specific config from `test.config.js`
Locally this is running consistently green and no failures seem to be random. 
The giant error stack that has been appearing at the top of our Mocha run is now also gone.
> Use separate test config for Mocha and Jest

- src/desktop/lib/global_client_setup.tsx
Noticed that Sentry was consuming local stack traces in dev since everything was piped through sentry's client. Guards so that it's only enabled for staging or prod deploys.
> Remove Sentry client during local development

- src/desktop/apps/sitemaps/routes.coffee
- src/desktop/apps/sitemaps/test/routes.test.coffee
Addresses https://artsyproduct.atlassian.net/browse/DISCO-927
We want to prevent bots from indexing pages like https://www.artsy.net/search?term=%EB%B3%B4%EC%A7%80%EA%B1%B8%EC%B2%9C%EC%82%AC%E2%80%BB%20omija.com%20%EC%98%A4%EB%B4%89%EB%84%B7hanging%EB%AA%A8%EC%95%84%EC%A4%98%ED%8B%B0%EB%B9%84%E3%83%A0%ED%88%B0%EC%BD%94%EC%A3%BC%EC%86%8Cnamely%20%ED%95%91%EC%9C%A0%EB%84%B7%E2%88%AA%EC%A7%88%EC%8B%B8%EB%8B%B7%EC%BB%B4h%EB%B9%A0%EA%B5%AC%EB%A6%AC%EB%84%B7%E2%94%AB%E2%92%9F%ED%92%80%EB%B9%B5%EB%8B%B7%EC%BB%B4edge (apparently a URL that is really indexed by Google).
> DISCO-927: Block /search/ from robots

- package.json
- src/desktop/apps/consign/client/actions.js
- src/desktop/components/gemini_form/view.coffee
- src/desktop/components/json_page/client/editor.coffee
- src/desktop/config.coffee
- src/desktop/lib/global_client_setup.tsx
- src/lib/setup_sharify.js
- yarn.lock
https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=64&projectKey=PLATFORM&modal=detail&selectedIssue=PLATFORM-1457
This can unset the `GEMINI_S3_ACCESS_KEY` config post-deploy in the staging and prod environments.
(I tested both editing a JSON page and consignment flow to verify things were still working).
> @joeyAghion => [Image Uploading] Drop redundant gemini config, consolidate on @artsy/gemup #migration

- src/desktop/apps/sitemaps/routes.coffee
- src/desktop/apps/sitemaps/test/routes.test.coffee
Addresses https://artsyproduct.atlassian.net/browse/DISCO-927
The disallowed search URL in #4099 was incorrect. This PR corrects it.
> Update the search URL that is disallowed in robots.txt

- src/desktop/config.coffee
- src/mobile/config.coffee
Checks if `NODE_ENV` is test before attempting to fire `window.alert`
This call to alert was causing errors when requiring `sharify` in test files.
> Exclude tests from sharify window.alert

- src/desktop/components/main_layout/templates/instant-page.jade
- src/desktop/components/split_test/running_tests.coffee
- src/desktop/config.coffee
- src/desktop/lib/global_client_setup.tsx
- src/lib/setup_sharify.js
Adds a new A/B test around https://instant.page. 
Swaps out the env var `ENABLE_INSTANT_PAGE` for `INSTANT_PAGE_AB_TEST`.
> [A/B Test] Add instant.page A/B test #migration

- src/desktop/components/prevent_right_click/index.jade
Addresses https://artsyproduct.atlassian.net/browse/DISCO-1063
We used to block users from right-clicking on any artwork images, to discourage them from downloading them. This functionality disappeared from most of the site as pieces were moved from Force to Reaction.
As apps and components have moved to Reaction, semantic CSS class names have turned into name-mangled styled-component class names, and they no longer match [the `classes.match('artwork')` line in this PR](https://github.com/artsy/force/compare/master...pepopowitz:DISCO-1063-clean-up-right-click-prevention#diff-0e9dba180220a48e988eb9df04a46e7dL8).
The `classes.match('seadragon')` line is still needed - it applies right click prevention to the large lightbox image on an artwork page. That image is handled by the OpenSeaDragon …
> Remove unused class from right-click-prevention

- src/desktop/apps/authentication/reset_password.styl
- src/desktop/assets/authentication.styl
Although the reset password component was moved to be co-located with the new `/authentication` app, the styles were not, and got removed when `desktop/apps/auth` was removed. 
This PR adds back the styles for the reset password component and addresses https://artsyproduct.atlassian.net/browse/PLATFORM-1472
A follow-up ticket to update these components is here: https://artsyproduct.atlassian.net/browse/GROW-1279
> Add reset-password styl back

- src/desktop/apps/authentication/__tests__/routes.jest.ts
- src/desktop/apps/authentication/routes.ts
Follow up to auth deprecation work, this ensures that all query params referenced in old auth flows are still valid.
> Interpret a variety of query params for redirects

- src/desktop/apps/notifications/test/client/index.test.coffee
- Removes an unnecessary mock for `window.matchMedia`
- Updates location in beforeEach of all tests
Hoping this will kill:
> NotificationView test update

- src/desktop/apps/search2/server.tsx
- src/desktop/components/main_layout/header/templates/index.jade
- src/desktop/components/react/stitch_components/NavBar.tsx
Fixes https://artsyproduct.atlassian.net/browse/DISCO-925
Blocked by companion PR https://github.com/artsy/reaction/pull/2495 
This stores the server-side search query in sharify, and passes it via our SystemContext to reaction where we then pass it into the search bar.
> [Search] Ensure search query persists across client / server

- src/desktop/components/react/stitch_components/StagingBanner.tsx
We run into issues often where the staging banner gets in the way of QA, because it pushes content down. Added a click to hide. 
Merging so that we can properly test nav bar in morning meeting tomorrow.
> Add toggle to hide staging banner

- src/desktop/components/react/stitch_components/NavBar.tsx
Blocked by companion PR: https://github.com/artsy/reaction/pull/2505
Fixes an issue where the top nav bar was consistently fixed, and wouldn't yield control to page-level configuration; e.g., 
^ Also fixed issue where login banner covered the nav: 
Dodged a bullet with this one 😅
> [NavBar] Address QA items

- src/desktop/apps/notifications/test/client/index.test.coffee
This is the last flaky test suite at the moment, and it has a known issue with mocking `window.location`. X'ing for now until I can come back to all the tests with this problem. This should ensure that master stays 🍏 on the test step.
> x NotificationsView test

- src/desktop/apps/authentication/routes.ts
- src/lib/middleware/__tests__/unsupportedBrowser.jest.ts
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-1561
On login we redirect users back to the origin of their login request, but we do not want to do this on reset password because it is confusing to users. This adds a check to the login redirect logic to always send users who reset their password home.
> Do not redirect users back to redirect password on login

- src/desktop/apps/article/__tests__/helpers.jest.tsx
- src/desktop/apps/article/helpers.tsx
This PR is the first step in deprecating the old ads--enabling the new ads on Staging for all users.
[Links to GROW-1343](https://artsyproduct.atlassian.net/browse/GROW-1343)
> Enable ads on staging for all users

- src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.jest.tsx
- src/desktop/apps/article/components/layouts/__tests__/Article.jest.tsx
This PR addresses CI failures caused by https://github.com/artsy/force/pull/4252.
> Removes unnecessary tests after deprecating ads on standard articles

- .circleci/config.yml
Follow up to #4294, makes valid schema a prerequisite of production deploys.
> Require valid schema to release to production

- src/desktop/components/artist_page_cta/view.coffee
Addresses: [GROW-1294](https://artsyproduct.atlassian.net/browse/GROW-1294)
This PR adds analytics tracking for the existing Artist Page Signup CTA. Specifically we add missing properties for the "Auth Impression Event" (`trigger`, `triggerSeconds` (when applicable), `auth_redirect`, `onboarding`). We also added the "Created Account Event". 
Examples of those analytics events:
> Artist signup modal analytics

- src/mobile/apps/feature/index.coffee
- src/mobile/apps/feature/routes.coffee
- src/mobile/apps/feature/test/routes.test.coffee
- src/mobile/assets/mobile_all.coffee
#4277 replaced a backbone modal with one coming from modern reaction components, but it missed some sneaky hidden route handlers in our mobile app. This PR removes them and makes a note to revisit some other ones that don't seem to be getting called any more.
Importantly, these are not technically modals that cover/obscure other content - they are just basic header + button web pages that link back to the real page.
thanks @xtina-starr for helping me reason about this.
Firefox dev tools showing the new modal:
Iphone simulator:
> Remove mobile auction registration confirmation routes

- src/desktop/components/artist_page_cta/view.coffee
Addresses: [GROW-1410](https://artsyproduct.atlassian.net/browse/GROW-1410)
This handles the following analytics QA items:
- Ensure trigger seconds property is consistent for old and new event by using `trigger_seconds`?
- Control, scroll modal -> `created_account`: trigger should be scroll not click. Also, we are missing trigger_seconds
- Control, footer modal -> `created_account`: Missing context_module: Footer
> [GROW-1410] persist analytics data for account creation event

- src/desktop/apps/auction/components/Layout.js
- src/desktop/apps/auction/components/layout/ConfirmRegistrationModal.tsx
- src/desktop/apps/auction/components/layout/__tests__/ConfirmRegistrationModal.jest.tsx
- src/desktop/apps/auction/routes.js
- src/desktop/apps/auction_support/client/bid_form.coffee
- src/mobile/apps/feature/client/bid_page.coffee
- src/mobile/apps/feature/index.coffee
- src/mobile/apps/feature/test/client/bid_page.test.coffee
- src/mobile/apps/feature/test/routes.test.coffee
Tracked in [AUCT-492](https://artsyproduct.atlassian.net/browse/AUCT-492)
- Fix pending registration button copy
- Redirect failed bids (due to pending registration) to
/confirm-registration?origin=bid
- Set modal type to identify modal content:
success | failed (registration) | failed (bid+registration)
- Mobile work is very similar to https://github.com/artsy/force/pull/4305 (+ redirection logic from the desktop portion of this PR)
TODO: 
Desktop selfie:
Mobile selfie:
Verifying that post bid+register works as expected on mobile:
> Render new registration failed modal when bid+register fails

- package.json
- yarn.lock
Related: 
- https://github.com/artsy/reaction/pull/2625
- https://github.com/artsy/palette/pull/543
Upgrades to latest, which fixes a false-positive warning thrown by earlier version of Styled Components: 
> It looks like you've wrapped styled() around your React component (Component), but the className prop is not being passed down to a child. No styles will be rendered unless className is composed within your React component.
> Upgrade styled-components@4.3.2

- src/desktop/components/split_test/README.md
- src/desktop/components/split_test/running_tests.coffee
https://artsyproduct.atlassian.net/browse/GROW-1417
This simply sets up a new A/B test, which we can use as a feature flag to release Collection Hubs features only to admins while they are under development.
Example use of the flag is shown in [this feature branch](https://github.com/artsy/reaction/compare/master...anandaroop:hubs-AB?expand=1).
> Set up A/B test for Collection Hubs, admin-only for now

- src/desktop/apps/article/__tests__/editorial_features.jest.ts
- src/desktop/apps/article/editorial_features.ts
- src/desktop/apps/article/queries/relatedArticles.js
Depends on https://github.com/artsy/reaction/pull/2636
- Routes Artsy Vanguard parent article to reaction's custom editorial templates
- Adds id fields for sub-articles
> Scaffold Vanguard route

- src/desktop/components/main_layout/templates/scripts.jade
I was poking around with lighthouse on the site and I noticed that the recaptcha script was being included in the critical request chain. 
(Third from the bottom)
I added the `async` and `defer` tags (which [Google recommends](https://developers.google.com/recaptcha/docs/invisible)) to push it off a bit until the critical requests have had a chance to process.
> Defer loading of the recaptcha script

- src/desktop/apps/artist/components/__tests__/cta.jest.ts
- src/desktop/apps/artist/components/cta.ts
- src/desktop/components/split_test/running_tests.coffee
Addresses: [GROW-1463](https://artsyproduct.atlassian.net/browse/GROW-1463)
The grow team is still waiting on a full analysis of the Artist Page Signup A/B Test before we can completely depreciate the Artist Page Signup CTA. This PR closes the signup test so that we can unblock the purchase team who is ready to roll out the inquiry flow test.
> [GROW-1463] closes artist page signup a/b test

- src/desktop/apps/articles/components/AuthWrapper.tsx
- src/desktop/apps/auction/components/artwork_rail/ArtworkRail.js
- src/desktop/apps/auction/components/layout/active_bids/MyActiveBids.js
- src/desktop/apps/authentication/components/ModalContainer.tsx
- src/desktop/components/react/masonry_grid/Reveal.js
Addresses some React 16.9 warnings about deprecated component lifecycle methods.
> [Refactor] Rename unsafe component methods

- src/desktop/apps/collect/server.tsx
We added a [split test named COLLECTION_HUBS](https://github.com/artsy/force/blob/e7cf3af91c20caf458581572badc76ddb5f48fd6/src/desktop/components/split_test/running_tests.coffee#L28), but we weren't passing it through to the server app. This was resulting in an SSR hydration mismatch when conditionally displaying elements in Reaction. This PR addresses that.
> [CollectionsHubsNav] Pass COLLECTION_HUBS sharify data to server app

- src/desktop/apps/authentication/__tests__/helpers.jest.js
- src/desktop/apps/authentication/helpers.ts
Jira: https://artsyproduct.atlassian.net/browse/AUCT-281
Review app: https://auct-281.artsy.net/
Monitors:
- [datadog production login monitor](https://app.datadoghq.com/monitors/6233070)
- [velocity derived counts](https://velocity.artsy.net/graphlot/?width=586&height=308&_salt=1565906540.658&from=-7days&target=summarize(stats.counters.gravity.session.login-failure.count%2C%221h%22)&target=summarize(stats.counters.gravity.session.login-success.count%2C%221h%22))
**Rebase me**
This is the 2nd pass at a solution to synchronize session state before Force and Gravity so that bidders don't need to sign in twice to access an auction.
The previous attempt involved diff to force (https://github.com/artsy/force/pull/4349, https://github.com/artsy/force/pull/4357) and artsy-passport …
> Log into Gravity after logging into Force

- src/desktop/apps/article/__tests__/editorial_features.jest.ts
- src/desktop/apps/article/__tests__/routes.jest.ts
- src/desktop/apps/article/editorial_features.ts
- src/desktop/apps/article/index.ts
- src/desktop/apps/article/routes.ts
Related to https://github.com/artsy/reaction/pull/2701
- Adds route for `/artsy-vanguard-2019`
- Overrides fetching on various vanguard routes to always grab master article data
Public slug structure:
Master article: `/artsy-vanguard-2019`
SubSeries: `/artsy-vanguard-2019/emerging`
Artist stub `/artsy-vanguard-2019/genesis-balenger`
TODO:
- We will need to redirect sub-articles to the parent from their original slugs as well (`/article/artsy-editorial-genesis-balenger` -> `/artsy-vanguard-2019/genesis-balenger`). Will cover this in a separate PR.
> [Vanguard] Routing

- scripts/build_review_app.sh
Automate the process of creating a Force review app
This is definitely a rough cut, but figured something is better than
nothing. Tried to heavily document so that the script so that when
things break, at least devs know the intent here.
* Add new build_review_app.sh script to scripts/
> Automate the process of creating a Force review app

- package.json
- yarn.lock
This library needs to be installed as a dependency in Force, otherwise, it throws an error and fails to load components using it.
We technically should not have to do this, but to move the development of Artsy Vanguard work forward, for now, this is a work-around.
Links to this PR in Reaction https://github.com/artsy/reaction/pull/2729
> Adds react-use-dimensions as dev dependency in force

- src/desktop/apps/artwork/__tests__/client.jest.ts
- src/desktop/apps/artwork/client.tsx
- src/desktop/components/split_test/running_tests.coffee
Also reenables the AB test, but when this hits staging we should QA with @cavvia 
So, this is sort of a weird one. The desire is that after a successful login/signup occurs (which happens with Reaction modals), the user is immediately brought into the inquiry flow.
However, the inquiry flow is handled via Force modals (this is a legacy component/flow that hasn't been rebuilt in Reaction). Additionally, there's implicit behavior that after a successful login, you get redirected _somewhere_. At the very least we generally reload the page so you get all the 'logged-in' state of things. This is the current behavior.
There winds up being two [reasonable, IMO] ways of proceeding to implement that desired behavior. I'll describe both, although this PR implements the first one.
Use a cookie to …
> @zephraph => [Inquiry Auth] Use cookie to immediately open contact modal

- src/desktop/apps/artist/server.tsx
- src/desktop/apps/artwork/server.tsx
- src/desktop/apps/order/routes.tsx
Now that:
- Metaphysics will propagate HTTP status codes from underlying downstream errors
- Reaction will serve the relevant error page if there is one and only one error w/ status code present
So, we can remove this special-casing. This code isn't even being hit anymore since rather than throwing an error, Reaction is rendering it's own error page anyway.
> @zephraph => [Error Handling] No need to explicitly pattern match for 404s from Reaction apps

- src/desktop/apps/galleries_institutions/queries/partner_categories_query.coffee
Was reposted in #incidents https://artsy.slack.com/archives/C9RK0BLEP/p1567172226006600
After investigation with @iskounen and @starsirius  realized recently new categories were added but the query page size was still 30. So had to increase the query page size.
> Change partner_category query page size to 50

- .gitignore
- package.json
- scripts/check-for-links.js
- scripts/quicklink.sh
- yarn.lock
For more context on this PR, see https://github.com/artsy/reaction/pull/2758. These two PRs should be merged together. 
##
This PR adds a few things:
1. A script called `quicklink` which controls the linking behavior of a package being linked to force. It is designed to cover `reaction` but likely will seamlessly handle `palette` as well. 
2. A `lint-staged` hook on `package.json` and `yarn.lock` that fails a commit if linking is still active. The process of linking actually makes a change to the package.json and yarn.lock to point the package to the published package directory.
3. A `yarn unlink-all` command to easily clean up linking
Through the whole process the tool (yalc) that handles this new linking is kind of abstracted away from the user. I don't _yet_ have a yarn command to …
> Easier linking between force/reaction

- src/desktop/apps/auction/components/layout/ConfirmRegistrationModal.tsx
- src/desktop/apps/auction/components/layout/__tests__/ConfirmRegistrationModal.jest.tsx
addresses https://artsyproduct.atlassian.net/browse/AUCT-571
This replaces the duplicate auction registration copies & modals with the one in Reaction.
> Pull inConfirmRegistrationModal from Reaction

- src/desktop/apps/auction_reaction/server.tsx
- src/desktop/apps/auction_support/index.coffee
Promotes the new bidder registration form to the primary `auction-registration/:auctionID` route.
> Promote new reaction-based registration form

- src/desktop/apps/auction_reaction/server.tsx
- src/desktop/apps/auction_support/index.coffee
Reverts artsy/force#4490
Discovered a bug causing the modal to pop up multiple times:
Originally thought this might be due to https://github.com/artsy/force/pull/4484, but I think this is more of a routing issue.
> Revert "Promote new reaction-based registration form"

- src/desktop/apps/auction_reaction/server.tsx
- src/desktop/apps/auction_support/index.coffee
Reverts a PR that switches auction registration routing rules such that non-credit card required auction registration appeared broken. Fully reverting that diff while we investigate further to ensure future deploys go through cleanly.
> Revert Production Deploy

- src/desktop/apps/partner/client/contact.coffee
- src/desktop/apps/partner/stylesheets/contact.styl
- src/desktop/apps/partner/templates/contact.jade
- src/desktop/apps/partner/test/client/contact.test.coffee
More context: this is a followup from Force #4322, which added VAT display to the newer version of the `partner` page, `partner2`. At the time, I believe we thought we didn't need to also implement it on the old version of the page (`partner`). As we were testing with a newly-created partner on staging, we discovered that at least that partner still did use `partner` instead of `partner2`. I would like to follow up by deprecating `partner`, but for now, putting up this patch.
> Add VAT number display to old version of partner page

- src/desktop/apps/auction_reaction/routes.jest.ts
- src/desktop/apps/auction_reaction/routes.tsx
- src/desktop/apps/auction_reaction/server.tsx
This PR fixes a bug encountered shortly after deploying the new registration form from reaction. It stems from the fact that our `/auction-registration/:slug` route handles multiple cases and redirects; we had QAd this change extensively while the form was sitting at `/auction-registration2/:id` but did not predict the effects of effectively blocking the current `/auction-registration` handler.
in short:
1. new route is in the force `auction_reaction` app, which loads first. It loads the new full-page registration form or redirects to (among other places `/auction/:id/registration-flow` if the user already has a credit card)
2. Old `@auctionRegistration` route lives in the old `auction_support` app. It handles essentially the same redirect logic, and *also the actual bidder creation* if …
> Fix: Auction registration modal loop

- src/desktop/apps/auction_reaction/routes.jest.ts
- src/desktop/apps/auction_reaction/routes.tsx
- src/desktop/apps/auction_reaction/server.tsx
* Defer route new auction app route handling for legacy bidder creation
add a test and consolidate routing code
* Add auction_reaction app routing tests for redirect + passthrough
* use if/else to ensure route handler halts for next/redirect
> Fix: Auction registration modal loop (#4495)

- package.json
- scripts/quicklink-to-project.sh
This is just the other direction from #4475. It does the same thing (links reaction into force), but it allows you do to so _from_ force. 
So you'd run
```
yarn integrate reaction
```
and that'd start up the linking process. I need to add some docs still.
> Allow reaction linking from force

- src/desktop/apps/show/templates/metadata/location.jade
Currently one show is online exclusive but returns true for `has_location`. Add some defense around displaying the show so that the page doesn't 500.
https://staging.artsy.net/show/tabla-rasa-gallery-confessions-and-reflections
> Display show as online exclusive if location is not available

- src/desktop/components/main_layout/stylesheets/body.styl
Related: https://github.com/artsy/palette/pull/580, https://github.com/artsy/reaction/pull/2785
When working in the `PageLoader` component we need to accommodate the height of the nav bar, while also ensuring that the loader is fixed for users that have scrolled down the page.
> [PageLoader] Set position

- src/desktop/apps/article/__tests__/editorial_features.jest.ts
- src/desktop/apps/article/__tests__/routes.jest.ts
- src/desktop/apps/article/editorial_features.ts
- src/desktop/apps/article/queries/seriesRelatedArticles.ts
- src/desktop/apps/article/routes.ts
- src/desktop/apps/article/templates/meta.jade
Updates vanguard routing to provide meta content from sub-series and artist pages when loading custom slugs i.e. `/artsy-vanguard-2019/emerging` shows meta-title for the emerging section.
> Vanguard meta

- src/desktop/apps/user/components/linked_accounts/index.jade
- src/desktop/apps/user/components/linked_accounts/test/view.test.coffee
The twitter functionality has been deprecated from Artsy passport and we are removing the env vars for twitter from force. 
This is the last remaining place I'm aware of that allows account linking to twitter.
> Remove twitter from user account linking

- src/test/acceptance/collection.js
- src/test/acceptance/fixtures/metaphysics/collection.json
Adds a basic acceptance test for `collection/:id` pages
It looks like script for scraping in the acceptance directory is not working as expected, but copied over the fixture used in Reaction for now.
> Add acceptance test for /collection/:id

- src/mobile/apps/partner_profile/templates/contact.jade
- src/mobile/apps/partner_profile/test/templates.test.coffee
[PURCHASE-1477]
__Before:__
__After:__(broken map is not related to this change)
[PURCHASE-1477]: https://artsyproduct.atlassian.net/browse/PURCHASE-1477
> PURCHASE-1477: Remove "Connecting With" from Gallery Contact page on iOS

- src/desktop/apps/home/templates/index.jade
- src/desktop/components/main_layout/templates/scripts.jade
Fixes https://sentry.io/organizations/artsynet/issues/1048199288/?project=28316&query=is%3Aunresolved&statsPeriod=14d
There seems to be some sort of race condition going on where the `onload` is being executed before the script finishes loading with the `async` tag. I believe `window.onload` should wait for those so I'm not 100% sure I can logically trace the race condition, but it seems to be happening a fair bit.
This refactors it slightly to preserve the behavior (which I was wondering- we load the lib on every page but only execute something on the homepage?), but in a way that might be more explicit and avoid a race condition.
I wasn't sure how to test locally that the reCaptcha is actually working, but I was able to verify that the callback was correctly firing after the lib loads.
> @joeyAghion => [Recaptcha] Refactor to avoid race condition

- src/test/acceptance/collection.js
@mzikherman / @anandaroop - I've disabled this integration test for now, as https://github.com/artsy/reaction/pull/2845 seemed to break it and i'm not sure how to diagnose, and it's blocking deploys. These fixture-based tests are trouble, and this system in particular is extremely hard to work with... could one of you give it a look tomorrow?
> [Test] Disable /collection test for now

- src/lib/setup.js
Part of https://artsyproduct.atlassian.net/browse/PLATFORM-1835
This flamegraph generated by clinic.js _seems_ to suggest that in a prod build of the server code a large amount of time is spent in the `express-ipfilter` middleware. I don’t really feel like I can trust this tool yet, as I'm struggling trying to get things to run without too much noise (e.g. from things like webpack), but figured it was worth a try nonetheless.
After deploying we should remove the `IP_DENYLIST` from production and restart the service.
> [config] Make IP filter disableable in an effort to reduce cost.

- src/desktop/components/frame_animator/test/index.jest.js
- src/test/acceptance/README.md
- src/test/acceptance/collection.js
- src/test/acceptance/fixtures/metaphysics/collection.json
Follow-up to https://github.com/artsy/force/pull/4614
This re-enables an integration test which was broken by https://github.com/artsy/reaction/pull/2845
There's interest in moving smoke tests like this over to https://github.com/artsy/integrity, but in the meantime I didn't want to lose coverage about the collection app being wired up correctly.
See further discussion in https://artsy.slack.com/archives/C2TQ4PT8R/p1570211335035500
> Fix /collection/:id integration test

- scripts/build_review_app.sh
Updates the review app script with two changes: 
- `hokusai review_app env set $NAME APPLICATION_NAME="$NAME"`: This sets the app name to something other than `force-staging` so that the purple staging banner UI doesn't appear, impacting the QA process
- `hokusai review_app run $NAME 'yarn publish-assets'`, which publish JS / CSS assets to S3
> [Scripts] Update create_review_app.sh script

- src/desktop/components/main_layout/templates/scripts.jade
Fixes [PURCHASE-1376](https://artsyproduct.atlassian.net/browse/PURCHASE-1376).
On pages where stripe isn't specifically required, it still loads in stripe but with the async and defer tags. 
Here's a good sort of overview of those tags: 
https://flaviocopes.com/javascript-async-defer/#performance-comparison
Essentially it'll be loaded in as a non-blocking resource. We're loading this in, because stripe uses it to enhance the data provided by stripe radar to have a better idea if something is fraud or not.
> Always load in stripe.js

- src/desktop/components/split_test/server_split_test.coffee
- src/lib/middleware/same_origin.coffee
Addresses 
- https://sentry.io/organizations/artsynet/issues/1061782931/?project=28316&query=is%3Aunresolved+headers&statsPeriod=14d
- https://sentry.io/organizations/artsynet/issues/912360189/?project=28316&query=is%3Aunresolved+headers&statsPeriod=14d
This adds a guard to check against headers being sent before performing the operation, via express [`res.headersSent`](https://expressjs.com/en/api.html#res.headersSent) property. Curious if there might be a need to check this in the next JS runloop via `setImmediate`, but we should know pretty quickly once the error is closed since it happens so often.
> [Bugfix] Check if headersSent before performing operation

- src/lib/middleware/hsts.coffee
After https://github.com/artsy/force/pull/4652/files was deployed, the big flood of errors from the split test middleware have subsided.
A much lower than that (but still pretty high) rate w/ a different stack trace has shown up: https://sentry.io/organizations/artsynet/issues/1079185890/?project=28316&query=is%3Aunresolved. This stack trace mentions `dd-trace` (not sure if that's a red herring).
This adds the `headersSent` guard in one other place in the middleware I noticed.
> @damassi => [Middleware] Guard via headersSent in HSTS

- src/desktop/apps/home/queries/initial.coffee
- src/desktop/apps/home/routes.coffee
- src/desktop/apps/home/stylesheets/hubs_entry.styl
- src/desktop/apps/home/stylesheets/index.styl
- src/desktop/apps/home/templates/hubs_entry.jade
- src/desktop/apps/home/templates/index.jade
- src/desktop/components/react/stitch_components/CollectionsHubsHomepageNav.tsx
- src/desktop/components/react/stitch_components/index.tsx
- src/mobile/apps/home/routes.coffee
- src/mobile/apps/home/stylesheets/index.styl
- src/mobile/apps/home/templates/page.jade
Addresses https://artsyproduct.atlassian.net/browse/GROW-1486.
This PR stitches the collections hubs nav into the homepage.
- It consumes real hubs data, but that real hubs data is only in staging right now. In addition, [Reaction PR 2765](https://github.com/artsy/reaction/pull/2765) needs to be released & merged into Force before this will all work.
- The hubs only show up after a user has logged in as an admin.
> Stitch collections hubs nav from Reaction into homepage

- src/desktop/apps/article/__tests__/routes.jest.ts
- src/desktop/apps/article/routes.ts
- src/desktop/apps/articles/test/routes.test.js
- src/desktop/models/article.coffee
- src/desktop/test/models/article.test.coffee
- src/test/acceptance/artist.js
Moving some code from a model that’s shared between server and client to just server-side, which is the only place it is used, and with it remove the cheerio dependency from the client-side bundles.
@eessex I didn’t make the test work (yet), because I know little about this area. Let me know if you think this test should be made to work now.
> [bundle] Drop cheerio dep from common bundle

- .circleci/config.yml
- bundle-analyzer.config.js
- package.json
- webpack/envs/ciConfig.js
- yarn.lock
This is a trial of the [bundle-analyzer](https://app.bundle-analyzer.com/) dashboard service. It's a free service that provides a dashboard to track bundle asset changes over time. 
It may and/or may not be useful. We'll remove it again if it proves not to be useful.
> Add bundle analyzer dashboard to track js assets over time

- package.json
- webpack/envs/baseConfig.js
- yarn.lock
Closes https://artsyproduct.atlassian.net/browse/PLATFORM-1890
Depends on https://github.com/artsy/reaction/pull/2920
⚒
> [webpack] Drop graphql-js and relay network server from client bundles.

- webpack/envs/ciConfig.js
Temporary fix to get us past this failing on forks. 
If the token for bundle analyzer isn't available just don't load it.
> Don't run bundle report if token isn't available

- webpack/envs/baseConfig.js
This PR reverts commit 120564b2cbc18e954a394ff04859ea7db50bd026 and partially reverts https://github.com/artsy/force/pull/4696 after seeing some client-side errors in our staging environment.
cc/ @alloy @sweir27
> Revert "[webpack] Drop graphql-js and relay network server from client bundles."

- hokusai/production.yml
Things look stable and hopefully with fewer 500s with these new parameters.  See https://artsy.slack.com/archives/CA8SANW3W/p1571307914301600 for discussion
> bump production resource requests and limits

- src/desktop/apps/auctions/stylesheets/index.styl
- src/desktop/apps/auctions/templates/index.jade
Minor SEO fix noticed while assembling integration tests, use h1 rather than h2 for page title on /auctions route.
> Use h1 for /auctions page title

- src/desktop/apps/rss/routes.js
- src/desktop/apps/rss/test/routes.test.js
**Address : [Grow - 1407](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-1407) and [Error reprot in the Sentry](https://sentry.io/organizations/artsynet/issues/1048230498/?project=28316&referrer=slack)**
This PR is going to do:
Using the guard operator to prevent us to have an undefined value, 
then there are NO errors that will be reported from the Sentry. 
(The error from Sentry`Cannot read property 'type' of undefined`)
> Grow- 1407 Editorial RSS feed broken

- src/test/acceptance/fixtures/metaphysics/collection.json
Collaboration with @xtina-starr 
We realized that a [Reaction version bump PR was failing CI](https://github.com/artsy/force/pull/4720), as a result of using incomplete fixture data. This PR adds in the necessary data to successfully run `/collection/:id` acceptance tests.
> Fix broken collection acceptance tests by adding more fixture data

- .circleci/config.yml
Problem
Right now, we can and [do][0] create deploy block records for Force,
but currently there's no systematic enforcement of preventing a
unintended deploy when there's an open unresolved deploy block.
Solution
Block a deploy using the Horizon orb. This is similar to [setup in
artsy/currents][1] that has been running production for a while.
[0]:https://releases.artsy.net/admin/deploy_blocks?utf8=%E2%9C%93&q%5Bproject_id_eq%5D=11&commit=Filter&order=id_desc
[1]:https://github.com/artsy/currents/pull/257/files
> Block a production deploy when there's a unresolved deploy block.

- src/desktop/apps/collect/client.js
- src/desktop/apps/collect/server.tsx
- src/desktop/apps/home/routes.coffee
- src/desktop/components/split_test/running_tests.coffee
- src/mobile/apps/home/routes.coffee
Addresses: [GROW-1513](https://artsyproduct.atlassian.net/browse/GROW-1513)
This renames the Collection Hubs a/b test for launch and breaks the homepage entry points into its own separate test.
Related to https://github.com/artsy/reaction/pull/2844
> [GROW-1513] setup collection hub entrypoints a/b test

- src/lib/setup.js
This is kind of messy but fixes an issue where based on an AB test, some acceptance specs are failing. Skipping this AB middleware entirely will result in those AB test values not being set, so that would generally result in the control path being used in the UI.
An alternative would be to update our acceptance specs to be able to also stub an AB test value, and then possibly update any fixtures, in order to make the tests deterministic.
I wasn't able to figure out a clean way of stubbing that though, in our existing setup. So went with this for now.
> @eessex => [Middleware] Skip AB test middleware in test

- src/lib/middleware/unsupportedBrowser.ts
This is a tiny improvement in the attempt to fix the `Cannot set headers...` issue.
Basically, in middleware you either want to `next()`, _or_ you want to `return res.render` (or `res.send`, `res.end`, etc.).
This middleware looked like it was subject to both `next()` _and_ a `res.redirect()` being called, which is generally not advised.
> @eessex => [Middleware] Add a `return` before redirecting

- package.json
- src/index.js
- yarn.lock
Confirmed locally that using `kill` executes the `shutdown` callback properly.
> @izakp => [Package] Use http-shutdown to gracefully exit

- src/desktop/apps/articles/templates/meta/articles.jade
- src/desktop/apps/articles/templates/section.jade
- src/desktop/apps/editorial_features/components/eoy/templates/index.jade
- src/desktop/apps/editorial_features/components/gucci/components/nav/__tests__/header.test.js
- src/desktop/apps/editorial_features/components/gucci/components/nav/header.tsx
- src/desktop/apps/editorial_features/components/venice_2017/templates/nav.jade
- src/desktop/apps/home/templates/featured_articles.jade
- src/desktop/components/article/templates/super_article_sticky_header.jade
- src/desktop/components/main_layout/footer/mobile_footer_menu.jade
- src/desktop/components/main_layout/header/templates/more.jade
- src/mobile/apps/articles/meta/articles.jade
- src/mobile/apps/articles/templates/section.jade
Follow up to changes in https://github.com/artsy/reaction/pull/2962 and https://github.com/artsy/reaction/pull/2955, updates all magazine references to instead refer to 'editorial'
Related to https://artsyproduct.atlassian.net/browse/PLATFORM-1916
> Update all magazine references to editorial

- src/desktop/apps/collect/client.js
- src/desktop/apps/collect/server.tsx
- src/desktop/components/split_test/running_tests.coffee
Addresses: [GROW-1639](https://artsyproduct.atlassian.net/browse/GROW-1639)
This closes the collection hubs entry points a/b test on the collect page. Related to https://github.com/artsy/reaction/pull/2970.
> [GROW-1639] close collection hubs entry points a/b test on the collect page

- src/desktop/apps/show/routes.coffee
- src/desktop/apps/show/templates/index.jade
Fixes [PURCHASE-1516](https://artsyproduct.atlassian.net/browse/PURCHASE-1516)
`Event` types now have a [required](https://developers.google.com/search/docs/data-types/event#datatypes) `location` field. For shows which don't have location we cannot provide one so removing it altogether
* Is there a problem rendering an empty tag like `<script id="json-ld" type="application/ld+json"></script>` or it needs to be removed when content is empty [here](https://github.com/sepans/force/blob/2b6be957a0127386a965faddb72c67c6cc901dad/src/desktop/components/main_layout/templates/json_ld.jade)
* Is there a change needed for `mobile`? (mobile directory didn't have the corresponding file)
> Remove `json-ld` metadata for shows without location

- patches/relay-runtime+7.1.0.patch
Was noticing this warning upon fresh `yarn install`.
> @alloy => [Patch] Update relay-runtime patch to reflect package bump

- src/desktop/apps/home/client/index.coffee
- src/mobile/apps/home/client/view.coffee
- src/mobile/apps/home/test/client_view.test.coffee
Addresses: [GROW-1628](https://artsyproduct.atlassian.net/browse/GROW-1628)
Based on [QA feedback](https://artsy.slack.com/archives/GLZRS5KMH/p1572968252088000?thread_ts=1572965424.079200&cid=GLZRS5KMH) we want to fire the experiment viewed event for the collection hubs entry points when a user see the first row of the entry points. This PR accomplishes that by adjusting the offset options.
> [GROW-1628] Ensure the experiment viewed fires when the first row of entry points

- src/desktop/apps/home/client/index.coffee
- src/desktop/apps/home/routes.coffee
- src/desktop/components/split_test/running_tests.coffee
- src/mobile/apps/home/client/view.coffee
- src/mobile/apps/home/routes.coffee
- src/mobile/apps/home/test/client_view.test.coffee
Addresses: [GROW-1640](https://artsyproduct.atlassian.net/browse/GROW-1640) & [GROW-1612](https://artsyproduct.atlassian.net/browse/GROW-1612)
**Do not merge yet**
This PR launches the hubs entry points on the homepage a/b test but is blocked by https://github.com/artsy/force/pull/4784 and pending change in reaction to remove the impression analytic event from being fired on page load.
> Launch homepage collection hubs entry points a/b test

- src/mobile/apps/home/client/view.coffee
In #4785, we were tracking experiment viewed & impression for the homepage entry hubs when a user was logged in...which is incorrect, because logged in users _never_ see the homepage entry hubs. This PR removes the tracking for logged in users.
> Don't track any impressions or experiments for homepage entry hub if user is logged in (mobile web)

- src/desktop/apps/home/client/index.coffee
This PR addresses feedback from #4785.
1. Don't attempt entry hubs tracking if user is logged in. We weren't actually *tracking* anything if the user was logged in, because neither element that we attach a waypoint to exists in that view, but the code is now more explicit that it shouldn't be attempting to track when the user is logged in.
2. Toggle the impression subject based on control vs experiment. The user is seeing different elements on the page, and the subject will better reflect what they're seeing.
> Modifications to tracking of home page hub entrypoint experiment (on desktop)

- package.json
- src/desktop/components/main_layout/templates/head.jade
- src/lib/__tests__/volley.jest.ts
- src/lib/tti-init.js
- src/lib/userPerformanceMetrics.ts
- src/lib/volley.ts
- src/mobile/components/layout/templates/head.jade
- yarn.lock
cc @eessex 
Based on https://developers.google.com/web/fundamentals/performance/user-centric-performance-metrics , this adds the described metric to volley reporting. I was curious to see the kinds of values that would be reported when playing around locally!
For artist pages, this seemed to range between 4-6 seconds locally.
For artwork pages, it ranged from 1-6 seconds.
> @zephraph => [Performance] Instrument TTI Metric

- CONTRIBUTING.md
- scripts/build_review_app.sh
This is a follow up to the discussion at https://artsy.slack.com/archives/CP9P4KR35/p1575576740223500
- This updates the **review app** instructions to describe the case where your code changes are in Reaction rather than in Force itself. The steps outlined here allow you to launch a review app for Reaction changes prior to having them merged into Reaction's master branch (which would have the potentially undesirable effect of triggering auto-updates across our various Reaction-consuming apps)
- While I'm in here I'm updating the **DNS** instructions to describe our new dashboard over at Cloudflare, and retiring the old instructions for Dyn.
cc @damassi @artsy/grow
> Update review app docs to cover Reaction canaries

- src/desktop/apps/rss/routes.js
- src/desktop/apps/rss/test/routes.test.js
https://artsy.slack.com/archives/C9SATFLUU/p1576679913100400
A deleted Kanye tweet took down our RSS feed, oh yes it did.
It was embedded in [this article](https://www.artsy.net/news/artsy-editorial-kanye-west-will-close-miamis-art-fair-week-premiering-new-opera-vanessa-beecroft), and once it was deleted, the `oembed` content that Force was fetching started 404-ing.
This change makes the RSS feed resilient to un-fetchable embeds by simply filtering out the `undefined` sections that result from them.
If you must know, this was the deleted tweet: https://web.archive.org/web/20191217061445/https://twitter.com/kanyewest/status/1202747255452602368
> Make RSS feed resilient to un-fetchable social embed content

- src/desktop/apps/home/client/index.coffee
- src/desktop/apps/home/routes.coffee
- src/desktop/components/split_test/running_tests.coffee
- src/mobile/apps/home/client/view.coffee
- src/mobile/apps/home/routes.coffee
Addresses: [GROW-1685](https://artsyproduct.atlassian.net/browse/GROW-1685)
This PR closes the homepage hubs entry point test and rolls the entry points out to 100% of logged out users.
> [GROW-1685] close homepage entry points test and rollout to 100%

- package.json
- src/desktop/analytics/main_layout.js
- src/desktop/apps/experimental-app-shell/client.tsx
- src/desktop/components/split_test/running_tests.coffee
- yarn.lock
The [Reaction PR](https://github.com/artsy/reaction/pull/3067), once merged, requires these changes to be used in Force.
I usually wind up merging the Reaction PR, and then manually closing the renovate PR that shows up in Force and manually updating the Reaction version and merging this PR.
> @joeyAghion => [Client Side Routing] Remove AB test calls that moved to Reaction

- src/mobile/components/layout/stylesheets/footer.styl
- src/mobile/components/layout/templates/footer.jade
Whoops! Since the mobile homepage is a different app and layout, it needs it's own modification to accommodate a stitched-in CCPA modal component. Luckily our modal already goes full-screen on smaller layouts, so doesn't need any further modifications.
However, the CTA text winds up spilling over:
> @joeyAghion => [CCPA] Add CCPA trigger to mobile

- src/desktop/apps/article/templates/__tests__/amp.jest.ts
- src/desktop/apps/article/templates/__tests__/classic_article.jest.ts
These publishing tests are consistently highlighted by circle as our slowest, converting to Jest in the hopes of speeding things up.
> Convert slow tests to jest

- src/desktop/apps/article/components/__tests__/InfiniteScrollArticle.jest.tsx
- src/desktop/apps/authentication/__tests__/helpers.jest.js
Minor updates to fix slow jest suites - uncaught errors were causing drag in tests that run after.
- Turn off tooltips in  InfiniteScrollArticle test to prevent connection refused errors
- Mock `window.location` to prevent JSDOM errors
> Fixup slow tests

- package.json
- src/desktop/apps/artist/client.tsx
- src/desktop/apps/experimental-app-shell/artist/client.tsx
- yarn.lock
The mediator triggers are removed in the Reaction bump, but might as well clean up these handlers.
> @mzikherman => [Analytics] Bump Reaction and remove no longer needed mediator calls

- src/desktop/apps/page/index.styl
Re: https://artsy.slack.com/archives/C9XJKPY9W/p1578064164017200
CCPA + Hackathon + typographical OCD = this PR
We have some Markdown-powered pages on the website that are administered in old admin (e.g. https://admin.artsy.net/page/privacy) 
These are rendered by the `page` sub app within Force, where a few corrections to some `ul` and `ol` styles were in order. Thanks to @jeffreytr for reviewing.
> Fix list spacing in markdown pages

- src/desktop/apps/show/templates/index.jade
- src/mobile/apps/show/helpers/view_helpers.coffee
- src/mobile/apps/show/routes.coffee
- src/mobile/apps/show/templates/index.jade
- src/mobile/apps/show/test/helpers/view_helpers.test.coffee
Fixes [PURCHASE-1647](https://artsyproduct.atlassian.net/browse/PURCHASE-1647)
The new `view_helpers.coffee` contains needed functions from the ['Desktop' app](https://github.com/artsy/force/blob/920160b8c156bae897ba0259e8cd0e25c0067f75/src/desktop/apps/show/helpers/view_helpers.coffee#L171-L211) modified to use the `show` model object instead of MP returned object (`show.location` -> `show.location()` and `location.city` -> `location.get('city')` etc.).
> [PURCHASE-1647] Adds json-ld to show mobile page

- src/desktop/assets/artwork.styl
Addresses https://artsyproduct.atlassian.net/browse/PURCHASE-1674
Require the inquiry styles on artwork page, which fixes mysterious "send anyways?" prompt and adds proper styling to forms.
> Put back inquiry styles

- src/desktop/analytics/main_layout.js
Adds an `auction_slug` property to our `Auction Pageview` tracking event at the request of marketing. This is needed for lifecycle email marketing via Sailthru... pageviews can act as triggers for marketing emails under certain conditions.
> add sale slug to Auction Pageview tracking event

- package.json
- yarn.lock
We were relying on a fork of [geoformatter](https://github.com/afeld/geo_formatter/) hosted by @dzucconi. Think he unpublished it though and it broke some builds. 
I've replaced it with an Artsy fork. There are other repos that we reference that need the same treatment.
> Replace broken dependency references

- .circleci/config.yml
Skip cypress test suite on master builds while we work on its stability.
> Skip cypress tests on master

- hokusai/staging.yml
We can stand to go down to 1 pod on staging during rollouts
cc @eessex @mzikherman
> staging doesn't need to create 2 pods before destroying the old ones

- src/desktop/apps/purchases/server.tsx
We are getting 404 for newly added `user/purchases` on staging and production.
Remove `skipIfClientSideRoutingEnabled` which would work for apps in our app shell which this purchase app is not one of those :)
https://artsy.slack.com/archives/C9YNS4X32/p1580827434305600
> Remove appShell related code that was causing 404 on staging and prod

- .babelrc
- cypress/integration/home.spec.js
- package.json
- src/desktop/apps/experimental-app-shell/client.tsx
- src/desktop/apps/experimental-app-shell/server.tsx
- src/desktop/components/main_layout/templates/experimental_app_shell.jade
- src/lib/webpack-dev-server.js
- webpack/envs/baseConfig.js
- yarn.lock
JIRA: https://artsyproduct.atlassian.net/browse/PLATFORM-2222
Companion PR to artsy/reaction#3137.
This implements the webpack side of things, as well as the client-side loading snippet required to rehydrate bundle-split packages in the SSR path.
> Bundle Splitting take 2 

- src/desktop/apps/artist/server.tsx
- src/desktop/apps/collect/server.tsx
- src/desktop/apps/experimental-app-shell/server.tsx
- src/desktop/components/split_test/running_tests.coffee
- src/desktop/config.coffee
- src/lib/middleware/pageCacheMiddleware.ts
- src/lib/setup.js
cc @damassi @zephraph 
This implements a [relatively] simple mechanism for caching the full HTML of pages.
Which 'types' of pages to cache (artist, artwork, collection, etc.), and how long to cache are all configurable via ENV (as-is this entire feature, which can be enabled with a feature flag).
Additionally, there are some cache namespace and version ENV vars which can be used to effectively bust the cache anytime (for instance, after a deploy where a change is desired to be visible right away).
It's pretty simple, and locally seems to work great. Here are some local (not particularly realistic) benchmarks:
Without cache:
```
Document Path:          /artist/andy-warhol
Document Length:        274180 bytes
Concurrency Level:      1
Time taken for tests:   4.894 seconds
Complete requests: …
```
> @joeyAghion => [Performance] Cache unauthenticated pages, configurable via ENV

- src/desktop/components/split_test/skipIfClientSideRoutingEnabled.ts
- src/lib/webpack-dev-server.js
This allows us to test client-side nav on staging without the need to be within an A/B test context.
> Untie client-side-routing from A/B test

- package.json
- src/desktop/apps/experimental-app-shell/client.tsx
- src/desktop/apps/experimental-app-shell/server.tsx
- yarn.lock
Noticed that search works great when already in the client-side routing context, but when going directly to `/search` after a hard jump the page never loads. This is a bit of fallout from bundle splitting in that we now dynamically inject all relevant scripts into the shell during SSR render, from reaction's [buildServerApp](https://github.com/artsy/reaction/blob/master/src/Artsy/Router/buildServerApp.tsx#L172-L173).  
Since we don't _fully_ render the search app on the server (we only render the flashing loading component -- and therefore don't use `buildServerApp`), we still need to inject in the new app shell JS script tag in so that the client has something to attach to once it mounts.
> [Clientside Routing] Ensure search loads main bundle when loading /search from SSR context

- src/desktop/apps/experimental-app-shell/server.tsx
Follow-up to https://github.com/artsy/force/pull/5057. We can use our `assetMiddleware` helper to return the correct script url.
> [Clientside Routing] Use assetMiddleware helper to return search script src

- src/desktop/assets/artist.styl
- src/desktop/assets/main_layout.styl
Fixes longstanding 404 issue around `artist.css`. File didn't exist in `assets` since we build our css in a new way now in reaction via styled-components; however, our legacy pages expect an asset that matches the js file. This is no longer an issue in the new client-side-routing scheme of things.
Also, fixes the unstyled inquire form on artist page in client-side routing context by importing legacy inquire form css (built with backbone) into the main layout css file. 
This is the only old .js I believe we're using in our new pages, but for reference I moved the file reference from [here](https://github.com/artsy/force/blob/master/src/desktop/assets/artwork.styl#L3) to [here](https://github.com/artsy/force/blob/master/src/desktop/assets/main_layout.styl). If we ever encounter the need to …
> Fix artist.css 404 and inquire form css

- src/desktop/assets/main_layout.styl
Realized Artwork page buyers premium modal is also old backbone-esque code. 
That brings the number of different modals on Artwork page to 4 😄
> [Clientside Routing] Fix legacy buyers premium modal css

- package.json
- src/desktop/apps/auction_reaction/server.tsx
- src/desktop/apps/auction_support/index.coffee
- src/desktop/apps/auction_support/routes.coffee
- src/desktop/apps/experimental-app-shell/auction/bidderRegistrationMiddleware.ts
- src/desktop/apps/experimental-app-shell/auction/confirmBidMiddleware.ts
- src/desktop/apps/experimental-app-shell/server.tsx
- yarn.lock
Reaction PR: https://github.com/artsy/reaction/pull/3163
Moves the auctions app into the main app shell and moves server-side redirect code into middleware that's mounted in global app shell.  No real behavior changes, but did notice two things:
1) Discovered a bug where during registration if a user doesn't have a card on file the express app hangs. Will note it inline
2) Renamed the legacy `auction-registration` route in `bid_support` to `auction-registration-modal` to a) more accurately describe what's happening; and b) to remove a conflict between the new global router and express having multiple `auction-registration` routes defined. 
- `yarn link` with reaction PR above
- Add `EXPERIMENTAL_APP_SHELL=true` to env file. If this is missing or set to false everything behaves as it did …
> [Clientside Routing] Wire in Auctions app 

- src/desktop/apps/experimental-app-shell/order/orderMiddleware.tsx
The pathname for orders app is `orders` not `order`. Integrity caught this issue.
> [Clientside Nav] Fix path to orders

- src/desktop/apps/article/__tests__/routes.jest.ts
- src/desktop/apps/article/gallery_insights_redirects.ts
- src/desktop/apps/article/routes.tsx
- src/desktop/apps/galleries_institutions/templates/main.jade
- Add specific redirects for Gallery Insights articles
Instead of redirecting all articles in the Gallery Insights channel to the partners.artsy.net homepage, if a redirect mapping exists, redirect to specific content.
- Redirect Gallery Insights link to /gallery-resources page
Instead of linking Gallery Insights on the /galleries page to the partners.artsy.net home page, link to the /gallery-resources page directly.
jira: https://artsyproduct.atlassian.net/browse/GALL-1560
> Update redirects and links for Gallery Insights content

- src/desktop/apps/article/gallery_insights_redirects.ts
Missed this extra character in https://github.com/artsy/force/pull/5082.
The redirect doesn't fire because the slug doesn't exactly match up with this character present.
One character change FTW :muscle:
> Remove trailing ? from article redirect slug

- src/lib/middleware/assetMiddleware.ts
- webpack/envs/productionConfig.js
Fixes an issue we saw on production where dynamic chunks were getting pulled from force instead of from the CDN.
> Ensure dynamic chunks get cdn url prefix

- src/desktop/lib/global_client_setup.tsx
- src/lib/environment.js
- webpack/envs/baseConfig.js
- webpack/envs/productionConfig.js
Simplify -- pass CDN directly into publicPath config since `__webpack_public_path__` is equal.
> Test 3: Set CDN public path in webpack config

- src/desktop/lib/global_client_setup.tsx
- webpack/envs/baseConfig.js
Turns out https://github.com/artsy/force/pull/5102 will prefix server-side aspects as well, going back to https://github.com/artsy/force/pull/5101
> Test 4: Only set webpack CDN public path on client

- src/desktop/lib/global_client_setup.tsx
- webpack/envs/productionConfig.js
Make sure we're not injecting `publicPath` globally in webpack config, instead only setting it at runtime on the client.
> Test 5: Ensure were not setting public path globally

- hokusai/test.yml
- src/desktop/lib/global_client_setup.tsx
- webpack/envs/baseConfig.js
Given that we only build the force image once, we need to provide both CDN url references at build time and dynamically switch between them at runtime.
> Dynamically choose CDN url at runtime

- Dockerfile
- hokusai/test.yml
So #5105 failed because the envs weren't available at build time like I expected they would be. I've moved them directly to the dockerfile because I'm _mostly_ sure that'll make them available...
cc @eessex or @izakp  If there's a better way to do this we should probably follow up w/ a cleanup
> Move cdn envs to docker image

- Dockerfile
- src/desktop/apps/experimental-app-shell/apps/search/searchMiddleware.tsx
- src/desktop/lib/global_client_setup.tsx
- webpack/envs/baseConfig.js
Noticed an `undefined` path in the search asset when deploying to prod earlier which has been observed in the past when `CDN_URL` was not found. We're still not 100% sure about the best way to encode `CDN_URL` so going to stick with hard-coding for right now. 
This has been tested locally with `EXPERIMENTAL_APP_SHELL=true` and also removed with these commands:  
- `yarn start` 
- `yarn start:prod`
See [slack convo from #dev](https://artsy.slack.com/archives/C02BC3HEJ/p1582558932007100?thread_ts=1582557643.007000&cid=C02BC3HEJ) where initial issue was reported. 
(Note the `undefined` in the asset path)
> Hard-code CDN for now

- src/desktop/apps/experimental-app-shell/server.tsx
- src/desktop/components/split_test/skipIfClientSideRoutingEnabled.ts
- src/desktop/index.js
We saw unfortunate results earlier when deploying the AB test. The experiment group seemed to 404, when the `EXPERIMENTAL_APP_SHELL` flag was not present. It was present on staging (from work _prior_ to the AB test launch), but was not present on production.
Locally, this wasn't really repro'able, which was...surprising(?) (although nothing surprises me anymore). I tested it locally, with the flag not being set, and things were...fine!
However, with `yarn start:prod`, this was fully repro'able locally. Looking at the code with fresh eyes, the reason becomes clear.
When the flag is not set, individual apps have request middleware which can skip them for the experiment group (and falls through to the app shell). However, the app shell isn't even mounted without that flag being set (and …
> @damassi => [App Shell] Move guard into middleware, and always mount

- src/desktop/apps/experimental-app-shell/server.tsx
Still seeing a small locally-unreproducible edge-case that occurs when ENV var unset, but only at top-level routes (e.g., `/collect`; nested routes are fine -- `/collect/painting`). With env set everything is all good and deployable, but this is still kinda weird. Following a hunch here, and adding a console log to get a bit more info.
> [Experiment] Update path

- src/lib/setup.js
So the log in https://github.com/artsy/force/pull/5121 revealed something interesting on the top-level routes that 404: 
```
[force] EXPERIMENTAL_APP_SHELL A/B test: getSplitTest: undefined | env var: undefined
```
A/B test is undefined, leading me to think that there might be a prod-only middleware setting (relevant only to real arty.net prod environment) that causes us to lose the request context during the first past. Moving middleware down to the lowest possible point to see if there's any impact.
> [Experiment 2] Move express context middleware down

- src/mobile/components/layout/stylesheets/main_header.styl
This feels... too easy, so let me know if I'm missing something.
For non-reaction pages (i.e. the home page), the nav bar on mobile web isn't fixed to the top of the screen. That makes general browsing different than the other pages, but also creates a weird experience when you open the nav menu:
This fixes both of those issues, but like I said let me know what I'm missing!
> Fix nav bar on mobile

- src/desktop/apps/experimental-app-shell/apps/search/searchMiddleware.tsx
Noticed this was left behind, as we now directly embed experimental app shell into the page template. 
Lets see if this might have had an impact.
> Remove unused script tag

- src/desktop/lib/global_client_setup.tsx
- webpack/envs/productionConfig.js
Yesterday we updated webpack to 4.8, which is a minor version update from 4.3. When deploying today, noticed that we were getting random errors regarding certain split chunks not loading. My working theory, which I have not been able to produce locally, is that due to consistent hash's across builds we were loading some assets from webpack 4.3 and other older assets from 4.8.
> [Webpack] Bust asset fingerprinting cache

- package.json
- yarn.lock
The resolved field here changed based on updated instructions (using `yarn add` instead of `yarn upgrade): https://github.com/artsy/artsy-eigen-web-association/pull/35 This makes the resolution consistent with `artsy-wwwify` (https://github.com/artsy/artsy-wwwify/pull/31) but if there's any reason to be concerned, let me know
> Updates Eigen deeplink config

- src/desktop/apps/consign/components/describe_work_container/index.js
What was happening was that we were never setting the mobile flag correctly, just hard-coding it to false in an initial state. So my solution here is to directly query the shared data for this check down in the container that decided whether to render the desktop or mobile version of the form.
It's possible that we have other places where this flag is not being set correctly and so a better solution would be to update that flag in the state, but I can't quite figure out where/how to do that. In my testing locally with this change, the bug is fixed so I think it's worth shipping this but open to ideas!
> CSGN-15: Directly query shared data for mobile check

- package.json
- webpack/envs/baseConfig.js
- yarn.lock
Related to other bulletproofing work around detecting [network timeouts and offline status](https://github.com/artsy/reaction/pull/3240), this adds a new [`webpack-retry-chunk-load-plugin`](https://github.com/mattlewis92/webpack-retry-chunk-load-plugin) that will check to see if there's been an error in making a fetch to a dynamic runtime split bundle and retry the request. This is particularly relevant on mobile where network connectivity can be an issue, or caching, where the bundle manifest has changed but the user is browsing a cached version of the html page. 
1) User browsing on their phone to `/collect`
1) Network goes out just before they click an artwork
1) Request to dynamically load js related to artwork bundle fails and app hangs
1) Webpack plugin sees this failure, and …
> [Webpack] Make loading dynamic bundle split chunks safer

- src/desktop/apps/auction_reaction/server.tsx
- src/desktop/apps/auction_support/index.coffee
We found a case where users in the experimental app shell `experiment` group who _didn't_ have a credit card on file were erroneously being redirected to Auction page when trying to register for a sale and not the reaction app.
Corresponding Reaction PR: https://github.com/artsy/reaction/pull/3255 
Here's the PR when the PR was introduced: https://github.com/artsy/force/pull/5064
And there was some follow-up QA from Auctions team around the time that this was released here:  https://artsy.slack.com/archives/CA3D02SDN/p1582232761065900
Somehow this slipped through the cracks.
> [Clieintside Nav] Remove Auction routes from shell 

- .circleci/config.yml
Follow up from Platform Practice meeting.
In order to create a better timeline between integrity going from green to red, alert in the #integrity channel when Force is deployed to staging.
> Alert #integrity when force is deployed to staging

- src/desktop/analytics/inquiry_questionnaire.js
While running experimental app shell A/B test we found that in the experiment subsequent inquiry events are never tracked due to the use of a `once` function, which guards against resubmitting an inquiry request. In the `control` this doesn't matter because we do hard jumps between pages, which means that we "refresh" the analytics code for the inquiry form each time a user browses, where `once` means "once per page view". 
However, the new shell is architected around a single-page-app structure, which means that once JS is loaded for pages within the app shell network, it's loaded for good; `once` in this case means "once per _session_", leading to the observed discrepancies between `experiment` and `control`. 
The events impacted are:
- `inquiry:sync` (covers events “Sent artwork …
> [Clientside Nav] Ensure we always emit events in inquiry flow

- src/desktop/apps/article/components/InfiniteScrollArticle.tsx
- src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
- src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.jest.tsx
- src/desktop/apps/article/components/layouts/Article.tsx
- src/desktop/apps/article/components/layouts/Classic.tsx
- src/desktop/apps/article/helpers.tsx
- src/desktop/apps/articles/components/AuthWrapper.tsx
- src/desktop/apps/articles/components/__tests__/AuthWrapper.jest.tsx
- src/desktop/apps/artist/components/__tests__/cta.jest.ts
- src/desktop/apps/artist/components/cta.ts
- src/desktop/apps/auction/components/DOM.js
- src/desktop/apps/auction/components/__tests__/DOM.jest.js
- src/desktop/apps/authentication/__tests__/helpers.jest.ts
- src/desktop/apps/authentication/__tests__/routes.jest.ts
- src/desktop/apps/authentication/helpers.ts
- src/desktop/components/fair_week_marketing/__tests__/BannerPopUp.jest.tsx
- src/desktop/components/marketing_signup_modal/__test__/triggerMarketingModal.jest.ts
- src/desktop/components/marketing_signup_modal/triggerMarketingModal.ts
To help us confirm that args are correct, this PR sets up/consolidates typed helpers `handleOpenAuthModal ` and `handleScrollingAuthModal` in the `authentication` app.
The idea is to use them when opening auth modals from Force, rather than the untyped `mediator` or implementing a one-off scroll triggers. 
The helpers are now in use for all `js`/`ts` files, coffee implementations are currently unchanged.
> Use typed helpers over mediator when opening auth modals

- src/desktop/apps/authentication/__tests__/routes.jest.ts
- src/desktop/apps/authentication/helpers.ts
- src/desktop/apps/authentication/routes.ts
- src/desktop/models/logged_out_user.coffee
- src/desktop/test/models/logged_out_user.test.coffee
- Updates `forgot` form text to read `Reset your password` instead of `Forgot Password`
- Overwrites `forgot` title to `Set your password` when `set_password` param provided
- Updates logic for `sd.SET_PASSWORD` to pass  all values to Gravity
> Auth forgot titles/query params

- src/desktop/components/split_test/middleware.coffee
This temporarily forces app into `control` state before we launch new test with inquiry analytics fix.
> [A/B] Temporarily force into control

- src/desktop/components/main_layout/templates/blank.jade
- src/desktop/components/main_layout/templates/experimental_app_shell.jade
- src/desktop/components/main_layout/templates/minimal_header.jade
- src/desktop/components/main_layout/templates/react_minimal_header.jade
- src/desktop/components/main_layout/templates/react_redesign.jade
- src/desktop/components/main_layout/templates/redesign.jade
cc @eessex 
Many of the flaky test failures we've been seen in integrity can be correlated with race conditions related to rehydration. An element that we're searching for may be on the page, but it may not yet be ready to be clicked. We've already added some mechanisms for waiting for an app to rehydrate. 
The biggest missing piece is knowing _if_ we should wait for an app to rehydrate. That's where this PR comes in. 
I've added the `data-test-ssr-app` to the server rendered attributes of any app that uses reaction templates. That means on server render, this attribute will be available on the body of the app and be an effective mechanism for integrity to know if it should try to wait. 
With this, we can add more hooks into global actions (like logging in) to _automatically_ wait if it's …
> Add test hook to know if app requires rehydration

- src/desktop/apps/page/index.coffee
- src/desktop/models/page.coffee
It seems like the pattern here is to create a new page in admin.artsy.net and add a new route to Force.
* The new identity verification FAQ page could be found here (and also editable): https://admin.artsy.net/page/identity-verification-faq
* The page will be on e.g. https://staging.artsy.net/identity-verification-faq
IMO the page looks a bit too different visually, and these pages need a bit upgrades in general. But let's check in with @deliciousnachos.
> Add Identity Verification FAQ page

- src/mobile/components/layout/bootstrap.coffee
- src/mobile/components/layout/stylesheets/index.styl
- src/mobile/components/layout/templates/main.jade
Addresses https://artsyproduct.atlassian.net/browse/FX-1818 (for the second time 😄)
The requirements are:
- When logged in on mobile web, don't show the login/signup banner and fix the general nav bar.
- When logged out on mobile web, show the login/signup banner and _only after scrolling to it_, fix the general nav bar.
I took a couple of approaches to achieve this:
- For the logged in case, it's easy-- we can just push the content down (I achieved this in a non-JS way by replicating the header element with `visibility: hidden` per guidance I found on stack overflow) and fix the header.
- For the logged out case, we do that ☝️ , and add a little JS to achieve the conditional fixed effect.
> Make nav bar on mobile web for "force-only" pages sticky

- CONTRIBUTING.md
- docs/creating_review_app.md
I was looking for these docs yesterday (thinking that at one point I had seen the file in the `docs` folder) but then stumbled on the script, thinking that the docs in the shell script were all there were. To make things clearer, I moved the existing docs out of `Contributing` and into its own file, discoverable from the file-tree.
> [Docs] Move Review App docs to own file

- src/desktop/apps/article/__tests__/helpers.jest.tsx
Exits 3 failing editorial tests to unblock Force deploys.
Slack conversation here: https://artsy.slack.com/archives/CP9P4KR35/p1584649786185100
For context it is unclear why these 3 failing tests were throwing an `invariant violation cannot use react hooks outside of functional components error`, but this deploy is blocking other teams, so I will make a ticket to follow up with this issue later.
> Exits tests failing bc of react hook issue

- package.json
- src/desktop/apps/collect/client.js
- src/desktop/apps/collect/server.tsx
- src/desktop/components/react/stitch_components/CCPARequest.tsx
- src/desktop/components/react/stitch_components/CollectionsHubsHomepageNav.tsx
- yarn.lock
Blocker: https://github.com/artsy/reaction/pull/3296
Been meaning to flatten the v2 folder for a while and rename Collect2 to Collect.
> [Refactor] Move v2/Components > /Components & Collect2 > Collect

- src/desktop/components/main_layout/templates/scripts.jade
- src/desktop/config.coffee
- src/lib/setup_sharify.js
- src/mobile/components/layout/templates/scaffold.jade
- src/mobile/config.coffee
Addresses: https://artsyproduct.atlassian.net/browse/FX-1812
TL;RD: In order to leverage more features in Sailthru (browse abandon, abandoned cart emails, etc.), we need to update the JS snippet that we're pulling in on our pages.
In addition... these features aren't useful unless we actually include it on all of our pages.
This PR:
- Updates desktop and mobile web to include the Sailthru JS snippet on all pages.
- Includes config options for the `SAILTHRU_CUSTOMER_ID`. Will need to add this to staging and production for the events to actually fire.
There are a couple of places where we're using this JS to explicitly `track` something, and many places where we include specific sailthru `meta` tags. It doesn't look like the API for any of this has changed in the new version, but I'll …
> Update Sailthru's JS to latest version and include it on all pages

- src/desktop/analytics/main_layout.js
We log tracking events, but not pageviews:
> Log pageviews to console

- hokusai/staging.yml
Updates staging rollout strategy to match what we recently implemented in Exchange. 
I suspect that downtime during staging deploys is a source of flake and spurious 500s in our in our Integrity tests:
> Tweak staging rollout strategy to avoid downtime

- src/desktop/components/main_layout/templates/scripts.jade
- src/mobile/components/layout/templates/scaffold.jade
Hopefully fixes [this sentry error](https://sentry.io/organizations/artsynet/issues/1579904158/events/83eaedcd9d814bcea66b3daeadffdf33/?project=28316&query=is%3Aunresolved) that popped up after we updated our Sailthru lib.
> Only call Sailthru.init if it is a function

- src/desktop/apps/consign/components/create_account/__test__/index.jest.tsx
- src/desktop/apps/consign/components/create_account/index.tsx
Addresses https://artsyproduct.atlassian.net/browse/CSGN-107
Setting the `redirectTo` property redirects the user back into the consignment flow after they've signed up, rather than the homepage/onboarding.
> [CSGN-107] Specify callback URL for consign sign-up auth flow

- src/desktop/apps/artist/components/__tests__/cta.jest.ts
- src/desktop/apps/artist/components/cta.ts
[PURCHASE-1792]
Remember user preferences when using back button
For more examples, please check: https://share.getcloudapp.com/04uKGnAL
In order to accomplish this I set a cookie when the user closes the modal, and check for that cookie when opening the modal, and don't show the modal if the cookie is present. The cookie expires after 1 hour as Guillaume suggested.
[PURCHASE-1792]: https://artsyproduct.atlassian.net/browse/PURCHASE-1792
> Stop modal when user are using back button from Artist to Artwork To Artist again

- hokusai/experimental-app-shell.yml
- package.json
- src/desktop/analytics/inquiry_questionnaire.js
- src/desktop/apps/experimental-app-shell/server.tsx
- src/desktop/components/inquiry_questionnaire/index.coffee
- src/desktop/components/inquiry_questionnaire/views/account.coffee
- src/desktop/components/split_test/middleware.coffee
- src/desktop/components/split_test/running_tests.coffee
- src/desktop/components/split_test/skipIfClientSideRoutingEnabled.ts
- src/desktop/lib/global_client_setup.tsx
- yarn.lock
Corresponding Reaction PR: https://github.com/artsy/reaction/pull/3285
1) Bumps A/B test var to `CLIENT_NAVIGATION_V5` 
2) Fixes issue where inquiry form doesn't reload after a user logins / registers
3) Fixes issue around tracking across consecutive artwork page views
> HOLD => [Clientside Nav] Bump A/B test to v5

- src/desktop/assets/art_keeps_going.styl
This is #minor but there's an extra 10-or-so pixels below the header for react layouts which use the `#main-layout-container`.
It made the big video header look suboptimal, so I'm explicitly removing it. 😬
(I noticed this is not an issue with apps that use the `experimental_app_shell` layout 😄!)
> Removes extra white space below header

- .circleci/config.yml
Noticed that there was some confusion today around type-checking and yarn linking and looking closer noticed that we're not type-checking our PRs in CI. This adds that job to our flow.
> [CI] Add type-check job to circle config

- src/desktop/apps/home/templates/hero_unit.jade
- src/desktop/apps/home/templates/hero_units.jade
- src/desktop/apps/home/welcome.coffee
Minor QA fix as follow up to Auth changes in Reaction v26.0:
- Homepage hero unit does not click through to signup (this link overwrites args passed to the modal)
- add test attrs for integrity
> Remove clickthrough from welcome hero unit, add test attrs

- src/desktop/apps/authentication/__tests__/routes.jest.ts
- src/desktop/apps/authentication/routes.ts
Minor QA follow up to Auth changes in Reaction v 26.0.0-
- Static routes such as `/login` and `/signup` use `destination` instead of `redirectTo` to forward users home. (Using `redirectTo` was preventing new signups from hitting onboarding)
- Use `copy` for modal options instead of title. These options are used for the same thing, but title is less widely used and should be deprecated.
> Do not redirect static routes, copy/title updates

- src/desktop/apps/fair/templates/footer.jade
- src/desktop/apps/fair/templates/for_you.jade
- src/desktop/apps/fair/templates/overview.jade
- src/desktop/apps/fair/templates/overview_top.jade
- src/desktop/apps/fair/templates/sections.jade
- src/desktop/apps/fair_info/templates/nav.jade
- src/desktop/apps/fair_info/templates/visitors.jade
- src/desktop/apps/fair_organizer/templates/overview.jade
- src/desktop/apps/fairs/templates/current_fairs.jade
- src/desktop/apps/fairs/templates/index.jade
- src/desktop/apps/fairs/test/template.test.coffee
- src/desktop/components/clock/view.coffee
- src/mobile/apps/art_fairs/routes.coffee
- src/mobile/apps/art_fairs/test/template.test.coffee
- src/mobile/apps/fair_info/templates/article.jade
- src/mobile/apps/fair_info/templates/index.jade
- src/mobile/apps/fair_info/test/templates/article.test.coffee
- src/mobile/apps/fair_info/test/templates/index.test.coffee
- src/mobile/components/avant_garde_tabs/README.md
I ended up updating couple of more places where fair is used than what the card asked. But those places seem to follow the same pattern of changes that are requested in the issue.
What is strange to me is that the main menu still says `Fairs` but we try not to reference `Fair` anywhere on the page. But 🤷
> [GALL-2732] - removing references to Fair on Fair pages

- src/desktop/apps/user/pages/settings/index.jade
The team role should be present for any Artsy employee so this should sufficient as we iterate on this UI.
> Guard new 2FA component behind team role (vs admin)

- src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
- src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.jest.tsx
Reverts: https://github.com/artsy/force/pull/5322/files and fixes the bug.
Depends on: https://github.com/artsy/reaction/pull/3413
We call `onDateChange`, which sets the state of the header with the new date, whenever a component enters/leaves the viewport or is appended to the bottom of the list. While playing around, I noticed that we were calling this method in bursts and it seemed to non-deterministically be called with out-of-order dates.
I'm not _exactly_ sure what the underlying cause was, but when pairing with @eessex we decided to try using `throttle` instead of `debounce`, and it appeared to make the problem go away. Conceptually, `throttle` makes more sense here anyways as we need to handle a consistent scroll behavior (vs. an event that's very bursty).
> Revert hotfix; Add back dynamic news header

- src/desktop/apps/user/pages/settings/index.coffee
Stitch is available during server-side renders but when switching between settings tabs in a browser which triggers a client-side render of the same template, any stitch components fail to render due to the missing stitch context.
I took a look at the client-side setup for the payments tab which also uses a stitched component from artsy/reaction and found what was missing. Pass in stitch explicitly to the template during the client-side template render.
h/t to @eessex for catching this!
> Expose stitch context to user settings template client-side

- src/desktop/apps/consign/__tests__/routes.jest.ts
- src/desktop/apps/consign/routes.ts
When looking at server-side [tracking results](https://numeracy.co/artsy/3laHqA5zSel#query) we noticed that some props weren't being passed over. This fixes the invocation by passing server-side props across via the `properties` key.
> Pass tracking subprops over in props key

- src/desktop/apps/consign/__tests__/routes.jest.ts
- src/desktop/apps/consign/routes.ts
Don't send server-side tracking event if we're lacking subject and contextPath
From @louislecluse via [slack](https://artsy.slack.com/archives/CS3H1K4BD/p1588103533233200?thread_ts=1587566765.121000&cid=CS3H1K4BD)
```
We know whenever the user enters the submission flow (and successfully goes through it) since we have the submission record
Since our objective is to assign each submission to its origin page, we only need to know when it comes from a page. If we can’t find a page then it means the user went directly to the submission flow.
clicked consign is very easy to understand and clearly suggests click intent. A more elaborate event such as entered submission flow would be much harder to describe and grasp for other engineers/analyts I think.
In conclusion we shouldn’t fire an event …
```
> [Consignments] Only track when subject and contextPath

- src/desktop/apps/artist/components/__tests__/cta.jest.ts
- src/desktop/apps/artist/components/cta.ts
Addresses: [FX-1892](https://artsyproduct.atlassian.net/browse/FX-1892)
Currently nudes sometimes display in the David Hockney artist signup modal and get blocked by ads. This PR uses the `marketable: true` argument to prevent nudes from displaying in the modal.
> prevent nude from showing in artist signup modal 

- .circleci/config.yml
Pin to latest released orb version vs dev tags.
Dev versions of Circle CI orbs are only valid for 90 days after publishing. So we should probably limit their inclusion to PRs.
See this Circle CI master branch build error: https://app.circleci.com/pipelines/github/artsy/force/6273/workflows/8032a1b7-0fc6-4eb3-9afc-d15ef8981ca2/jobs/45301
I see some open artsy/orbs pull requests which might be where these dev versions came from: https://github.com/artsy/orbs/pulls
A follow-up would be to see if those can be merged and reintegrated with stable version numbers.
> Update Circle CI config node+yarn orb versions

- hokusai/production.yml
https://artsyproduct.atlassian.net/browse/PLATFORM-1996
When nginx/web containers are abruptly shut down, as they are when there is a scale-in event, deployment, or update, browser clients might see 502 Bad Gateway errors. Kubernetes can run a command in the container and wait for the command to finish before killing the container. The feature is called "preStop handler". This PR is to apply preStop handlers to the 'web' and 'nginx' containers. When a pod is 'terminating', it likely has outstanding requests from clients. With the handlers, we are trying to keep the containers alive long enough so that those requests still get fulfilled.
These handlers already exist in staging.yml. This PR is to true up production.yml.
> Graceful shutdown of nginx/web containers.

- package.json
- src/desktop/models/logged_out_user.coffee
- src/desktop/test/models/logged_out_user.test.coffee
- yarn.lock
~_#dontmerge because merging this as of now would break the desktop login form, until support for OTPs in that form lands_~ This is good to go after https://github.com/artsy/reaction/pull/3496
https://artsyproduct.atlassian.net/browse/TRUST-213
This closes the loop on the work to get Force's Passport stack supporting one-time password (OTP) fields and passing them through to Gravity when required, namely when:
- the Force ClientApplication has `enforces_otp: true` (not true in production yet, but soon)
- the user has a second factor enabled
This builds on:
- https://github.com/artsy/passport-local-with-otp/pull/1
- https://github.com/artsy/artsy-passport/pull/143
> [2FA] Pass through OTP in login request to Gravity

- CONTRIBUTING.md
While investigating https://artsyproduct.atlassian.net/browse/INTGRTY-3, I learned that running Force under a `local.artsy.net` subdomain instead of `localhost` enabled authentication to function locally. This PR adds docs on how to configure Force in this way.
My long-term intention is to point the [Integrity](https://github.com/artsy/integrity) docs at this bit to inform devs how to run the Integrity test suite against a local instance of Force.
> Add a section to docs on authenticating locally

- .circleci/config.yml
- .circleci/deploy_event.sh
- docs/creating_review_app.md
- hokusai/config.yml
- scripts/build_review_app.sh
- scripts/update_review_app.sh
Problem
Review apps are great, particularly for long-running work like redesigns, major refactors and anything else that might risk causing regressions (blocking our deploy pipeline), but need further testing in a live environment.
During a platform practice meeting, it was surfaced that:
1. It's a bit too hard to create/update a review app, even with build_review_app.sh
2. It can be **super slow** to build and push a Docker image of Force (~2 GB) depending on the conditions of the developer host running build_review_app.sh and the network.
Solution
* Create a review app when pushing to a branch matching review-app-*: d0d7edf82b83230ab741296a1404f1f104d98090
* Update a review app if it already exists upon subsequent commits: 6cb75b7aeb35cf74e963337e4396ef17391c6cdc
* Remove data dog …
> Automate review app building via CircleCI

- src/desktop/apps/feature-reaction/client.tsx
- src/desktop/apps/feature-reaction/server.tsx
- src/desktop/apps/feature/routes.coffee
- src/desktop/apps/feature/test/routes.test.coffee
- src/desktop/apps/viewing-room/client.tsx
- src/desktop/assets/feature-reaction.tsx
- src/desktop/index.js
Making this a Draft until the gravity work is in and we can check for that field.
This PR:
- Adds basic route handling for a new `Feature` App in reaction (called `feature-reaction` here). I also don't love the `feature-reaction` naming... could call it `feature-version-2`?
- Demonstrates how we can short-circuit the existing feature page routing. It's not _ideal_ as it means we're making an extra request. We could try to be fancy and pass some data around but doesn't seem worth it.
> Adds routing for new feature page

- src/desktop/apps/feature-reaction/server.tsx
Since this page needs force logic to route properly, it's not yet fully part of our new app router.
Forgot this line was added! Noticed that if you're part of the experiment group, accessing this page throws a 404. This fixes it.
> Fixes issue where new feature page wouldn't show if you're part of the client nav experiment group

- src/desktop/components/inquiry_questionnaire/stylesheets/desktop.styl
- src/desktop/components/inquiry_questionnaire/templates/account/login.jade
- src/desktop/components/inquiry_questionnaire/templates/account/otp_attempt.jade
- src/desktop/components/inquiry_questionnaire/test/views/account.test.ts
- src/desktop/components/inquiry_questionnaire/views/account.coffee
https://artsyproduct.atlassian.net/browse/TRUST-220
This makes the inquiry flow login modal compatible with 2FA enforcement by intercepting the usual error handling and providing some specialized behavior if Gravity returns the `missing two-factor authentication code` or `invalid two-factor authentication code` error messages.
As noted below, this increases the number of places where we test against these specific strings, so if we do change that strategy we should add this to the list of places we'd need to change.
> [2FA] Handle OTP during inquiry auth flow

- src/desktop/apps/auction/reducers/__tests__/artworkBrowser.test.js
- src/desktop/apps/auction/reducers/artworkBrowser.js
As discussed in https://github.com/artsy/gravity/pull/13055#discussion_r423977138 , this removes aggregations (which are expensive, and don't change), during pagination.
When you 'reset' back to page 1 (clicking a filter, etc.) , we set the aggregations back to their defaults.
Jira: https://artsyproduct.atlassian.net/browse/AUCT-1015
Review app: https://sale-browser-optimization.artsy.net/
> @dleve123 => [Sale Page] Dont overfetch aggregations when paginating

- src/desktop/apps/user/pages/settings/index.jade
Having a lab feature to enable for any user account will help us QA in advance of launch milestones.
> Add lab feature to reveal 2FA enrollment UI

- package.json
- src/desktop/analytics/main_layout.js
- src/desktop/lib/global_client_setup.tsx
- yarn.lock
This makes our reaction app pageview tracking exclusion more robust, allowing us to match dynamic path names / copy paste reaction routes directly into the exclude list. Uses [path-to-regex](https://github.com/pillarjs/path-to-regexp) under the hood.
See this slack convo: https://artsy.slack.com/archives/C02BC3HEJ/p1589488137239700
And this JIRA ticket: https://artsyproduct.atlassian.net/browse/PLATFORM-2362
for more context.
See [Reaction PR](https://github.com/artsy/reaction/pull/3543) for some tests. 
Before / After:
> Make reaction app exclude tracking more robust

- src/desktop/apps/user/pages/settings/index.jade
Remove conditional for revealing 2FA enrollment UI, soft-launching 2FA for all users.
_Opening this to prepare for the 2FA soft launch_
> Expose 2FA enrollment UI to all users

- hokusai/staging.yml
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-1996
The 504s on pod termination are reported by other users in this thread https://github.com/kubernetes/kubernetes/issues/88236 and the Kubernetes authors' response is 
> Once the pod is deleted, the "upstream" load-balancers need to actually remove it from their backend sets. This is async and can take time, during which you will continue to receive requests. This is "normal". I expect that somewhere between 2 and 30 seconds later those new requests will cease.
If this is a real problem for the app, you can add a preStop lifecycle hook that exec's sleep 60 or something similar. That will be triggered BEFORE you get SIGTERM, but LBs will be able to observe the deletionTimestamp.
Since this is not a "bug", I am going to close …
> update preStop sleep hooks to 30s for Nginx and 35s for force in staging

- src/desktop/apps/about/stylesheets/index.styl
Fixes: https://artsyproduct.atlassian.net/browse/FX-1841
The /about page takes up the full height of the browser, so we actually include an additional footer (because the main one is covered up!). But it appears to be peeking through. This fixes that.
> Fix double footer on about page

- src/desktop/apps/authentication/components/ModalContainer.tsx
- src/desktop/apps/authentication/components/__tests__/ModalContainer.jest.tsx
- src/desktop/apps/authentication/helpers.ts
- src/desktop/models/logged_out_user.coffee
- src/lib/setup.js
Problem
Storing the CSRF_TOKEN in the page causes issues when doing full html
caching because many users will see the same token and that token will
only be valid for a single users session.
Solution
Move the delivery of the CSRF_TOKEN from sharify to the cookie. This
allows the page to be cached while using dynamic tokens.
> Move CSRF_TOKEN to Cookie to Allow for Page Caching

- .circleci/config.yml
Adds back `<<: *not_staging_or_release` to test steps 
This matches how it was previously: https://github.com/artsy/force/pull/5636/files#diff-1d37e48f9ceff6d8030570cd36286a61L123
> No tests on staging or release

- src/desktop/assets/analytics.coffee
- src/desktop/lib/global_client_setup.tsx
Noticed that things were double firing because we had two instances of the same event bus (reaction + publishing event emitter) being attached to the same event handler. 
Since in the end our events all attach to [`window.__reactionEvents`](https://github.com/artsy/force/blob/4dcece28d24bdc92c664d5d79db99f337ab6524b/src/v2/Utils/Events.ts#L9-L13) only need one declaration. (Need to clean up naming once things settle.)
> [Analytics] Fix double firing

- src/mobile/apps/partner_profile/client/artworks.coffee
- src/mobile/apps/partner_profile/test/client/artworks.test.coffee
https://artsyproduct.atlassian.net/browse/GALL-2867
See the screencast below for the issue and local result from the fix.
The issue was we tried to append fetched artworks to a non-existing element when scrolling. This quickly fixes it by appending to individual column.
> Fix infinite scrolling on mobile partner profile works/shop tab (GALL-2867)

- .eslintrc.js
- package.json
- yarn.lock
Noticed that eslint has been running extremely slowly. Initially i thought it was a problem with husky, but of course it was a configuration issue. See https://github.com/typescript-eslint/typescript-eslint/issues/319.
> [Toolchain] Fix eslint speed problem

- src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
- src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
- src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
- src/v2/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.jest.tsx
- src/v2/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.jest.tsx
https://artsyproduct.atlassian.net/browse/PURCHASE-1927
To make filter state track current page and cursor. So that we can really rely on filter state to determine whether any filters (including page#) has changed.
In filter state, replaced `page` property with an object containing `page` and `cursor`. The two must be updated together due to the way `Reducer` works. `cursor` is really what is used for data fetching.
`paginated` state is removed. It was a work-around because filter state didn't track page (it was always 1).
The relay fetch code block in `loadAfter()` was required to trigger refetch due to pagination. Now it isn't anymore. Now, pagination triggers filter state difference which triggers relay fetch in `useDeepCompareEffect`.
> Artist Auction Results App, make filter state track page number and cursor.

- src/v2/Apps/Conversation/Components/Conversation.tsx
- src/v2/Apps/Conversation/Components/ConversationSnippet.tsx
- src/v2/Apps/Conversation/Components/Conversations.tsx
- src/v2/Apps/Conversation/Routes/Conversation/index.tsx
- src/v2/__generated__/Conversation_me.graphql.ts
- src/v2/__generated__/routes_DetailQuery.graphql.ts
[PURCHASE-1907]
https://www.notion.so/artsy/Selected-conversation-missing-select-state-dfc1c1191eca40bb9c2a9b294be7a497
[PURCHASE-1907]: https://artsyproduct.atlassian.net/browse/PURCHASE-1907
> Selected conversation missing "select" state

- .vscode/settings.json
- docs/adding_new_app.md
- package.json
- src/v2/Apps/Collect/Routes/Collections/Components/CollectionsGrid.tsx
- yarn.lock
This adds some docs around adding a new app / route to force, via our SSR router.
> [Docs] Add docs about adding a new app to SSR router 

- Dockerfile
Problen
The yarn cache is being not being cleaned during the build causing the
docker image to be larger than needed.
Solution
Clean the yarn cache after install node modules.
> Clear Yarn Cache

- src/v2/Apps/Order/Routes/Payment/index.tsx
- src/v2/Apps/Order/Routes/Review/index.tsx
- src/v2/Apps/Order/Routes/Shipping/index.tsx
Add data-atts to order form steps, so we can better confirm what page we are on-- relates to https://github.com/artsy/integrity/blob/78eb38709ade18e4e74f68117ac00b99b6626f59/cypress/utils/ecommerceFlowHelpers.ts#L49
> #trivial add data attrs for order form steps

- src/desktop/apps/artsy-v2/client.tsx
- src/lib/webpack-dev-server.js
- webpack/envs/developmentConfig.js
Most devs aren't concerned with the full chunk output. However, if wanting to view, can use an env var:
```
WEBPACK_STATS="normal"
```
> [Webpack] Quiet the output a bit

- package.json
- src/desktop/apps/artsy-v2/client.tsx
- yarn.lock
Fixes the crazy `fsevents` / `node-gyp` output that happens on `yarn install`. See https://github.com/yarnpkg/yarn/issues/5962#issuecomment-491934806
> [Lib] Fix node-gyp yarn install error

- package.json
- yarn.lock
Now that we're pinning fsevents, this isn't needed.
> [Lib] Remove unneeded chokdar resolution

- package.json
- src/v2/Apps/Artist/ArtistApp.tsx
- src/v2/Apps/Artist/Components/ArtistHeader.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
- src/v2/Artsy/Router/RouterLink.tsx
- src/v2/Components/ArtistCard.tsx
- src/v2/Components/Artwork/FillwidthItem.tsx
- src/v2/Components/Artwork/GridItem.tsx
- src/v2/Components/Menu.tsx
- src/v2/Components/NavBar/Menus/DropDownMenu/DropDownMenu.tsx
- src/v2/Components/NavBar/Menus/DropDownMenu/DropDownSection.tsx
- src/v2/Components/NavBar/Menus/DropDownMenu/TwoColumnDropDownSection.tsx
- src/v2/Components/NavBar/Menus/DropDownMenu/__tests__/DropDownMenu.jest.tsx
- src/v2/Components/NavBar/Menus/DropDownMenu/__tests__/DropDownSection.jest.tsx
- src/v2/Components/NavBar/Menus/MoreNavMenu.tsx
- src/v2/Components/NavBar/Menus/NotificationsMenu.tsx
- src/v2/Components/NavBar/Menus/UserMenu.tsx
Now that the new appshell is in we should use `<RouterLink>` where we can for links and a tags. 
While this isn't strictly necessary thanks to our [interceptLinks](https://github.com/artsy/force/blob/master/src/v2/Artsy/Router/interceptLinks.ts) and [catchLinks](https://github.com/artsy/force/blob/master/src/v2/Artsy/Router/Utils/catchLinks.tsx) helpers which will detect `<a>` tag clicks and see if the route exists in the global router, i _did_ notice that in development, after a save / hot reload, catchLinks will no longer transition on route change which is real confusing for dev team. Couldn't figure out why, but found that if we use `RouterLink` (which is more correct anyways) it fixes the problem. 
The areas I fixed aren't exhaustive but are the most common / reused spots. 
I also …
> [Refactor] Use RouterLink where we can

- src/lib/setup.js
Noticed after the reaction merger that we don't get instant reloads for our reaction SSR code. This fixes that.
> [Toolchain] Update express-reloadable to watch v2 files

- src/v2/Components/Authentication/Desktop/LoginForm.tsx
- src/v2/Components/Authentication/Mobile/LoginForm.tsx
- src/v2/Components/Authentication/__tests__/Desktop/LoginForm.jest.tsx
- src/v2/Components/Authentication/__tests__/Desktop/SignUpForm.jest.tsx
- src/v2/Components/Authentication/__tests__/Mobile/LoginForm.jest.tsx
- src/v2/Components/Authentication/__tests__/Mobile/SignUpForm.jest.tsx
https://artsyproduct.atlassian.net/browse/MX-292
- Don't show email error on social in mobile login
- Don't show email error on social in desktop login
- Add test for email validation errors
**Co-authored with @ds300**
Adds a check that was already present for some login dialogs to prevent showing email validation errors when signing in with a 3rd party. 
**Before**
**After**
Related to this pull request, these dialogs seem to show errors pretty aggressively (onBlur events) so was wondering if it would be better to only show errors on tapping 'Login' 'Sign Up' etc. As it stands you get a validation error when clicking anywhere on screen, including for example the button to close the dialog.
> [MX-292] - Don't show email validation error for 3rd party auth

- src/v2/Apps/Conversation/Components/Reply.tsx
- src/v2/Apps/Conversation/Mutation/SendConversationMessage.ts
[PURCHASE-1904]
https://www.notion.so/artsy/Conversation-not-updated-correctly-when-new-messages-is-entered-by-collector-61d0224fe67e4d44bf8c13fe52565a4b
This PR is the result of our mob pairing session. In addition to the message order bug, we fixed an issue where the text area input wasn't clearing properly.
The changes did not make it into force master so this is a new PR to address this
[PURCHASE-1904]: https://artsyproduct.atlassian.net/browse/PURCHASE-1904
>  Conversation not updated correctly when new messages is entered by collector

- src/v2/Components/v2/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
Unexciting :) most of the nice things in the ModalBase like the focus management would apply more to desktop uses but this at least does a better job of locking the scrolling on mobile.
Also snuck in tapping on filter to scroll to top since that's expected from a UX perspective but wouldn't work due to the modal context.
-------
> Utilizes ModalBase to lock scroll on mobile filters

- src/v2/Apps/Auction/Components/BidForm.tsx
- src/v2/Apps/Auction/Components/RegistrationForm.tsx
addresses https://artsyproduct.atlassian.net/browse/AUCT-1018
This fixes a bug where user sees error message telling them to accept conditions of sale after they've already checked the checkbox. The root cause of this seems to be a racing condition in `setFieldTouched` and `setFieldValue`, and flipping the function order fixed the issue, but I don't have a definite answer as to why it fixed it or the previous order caused a bug. There might be more places that have a similar bug.
I tried to write a test for this but sadly it didn't fail in test, so just leaving it here as a reference:
```tsx
it("validates against an unchecked conditions of sale checkbox", async () => {
const env = setupTestEnv()
const page = await env.buildPage()
setupCreateTokenMock()
await page.submitForm() …
```
> Fixes a bug where user sees error message telling them to accept conditions of sale after they've already checked the checkbox

- src/lib/datadog.ts
This updates our data-dog traces to scope only to the root path segment, like `/artist`.
> Update datadog path output

- src/v2/Apps/Auction/Components/BidForm.tsx
- src/v2/Apps/Auction/Routes/__tests__/ConfirmBid.jest.tsx
addresses https://artsyproduct.atlassian.net/browse/AUCT-1024
This PR updates the bid and register form to have the country field pre-selected with United States.
> Fixes an issue where not selecting country on registration form leads to silent error when trying to register and bid

- src/desktop/lib/global_client_setup.tsx
Noticed that we were getting CDN issues when running 
```
DEBUG=true yarn start:prod
```
because we weren't accounting for the now common `local.artsy.net` hosts config setup.
cc @mzikherman
> Fix CDN url for local.artsy.net

- package.json
- src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
- src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
- src/v2/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts
- src/v2/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts
- src/v2/__generated__/ViewingRoomApp_viewingRoom.graphql.ts
- src/v2/__generated__/routes_ViewingRoomQuery.graphql.ts
- yarn.lock
This surfaced the fact that we really need to limit access to `Unpublished` VRs. Now all the drafts are visible and we do not have a separate state for either fraft/scheduled. But I think this is still a proper way to go about Closed ones.
> use state field for determining if VR is open/closed

- src/v2/Apps/Auction/Components/BidForm.tsx
- src/v2/Apps/Auction/Components/RegistrationForm.tsx
- src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/v2/Apps/Auction/Routes/__tests__/ConfirmBid.jest.tsx
- src/v2/Apps/Auction/Routes/__tests__/Register.jest.tsx
addresses https://artsyproduct.atlassian.net/browse/AUCT-857
1. The `onChange` event was not captured so the display-error-as-you-type feature wasn't working (or was it actually implemented in the first place?)
2. Client-side stripe validation errors were [converted to Javascript errors](https://github.com/artsy/force/pull/5699/files#diff-202e308e153e715988a1f211d68143beL167) and they weren't displayed to the user properly
3. On the registration form we weren't handling Javascript errors (e.g. network error)
All of these cases are now covered both in the registration and bid+register forms.
> Fix a bug where user gets unhelpful error message when encountering Stripe error on bid+register form

- src/lib/datadog.ts
There was a strange failure on deploy, so this makes path lookup a bit safer. 
See convo here: https://artsy.slack.com/archives/C02BC3HEJ/p1591231783023200?thread_ts=1591197201.008300&cid=C02BC3HEJ
> Make path lookup safer

- src/desktop/components/main_layout/footer/upper.jade
- src/desktop/components/main_layout/footer/view.coffee
- src/v2/Components/Footer.tsx
Ooops-- missed this from the ticket!
Removes the outdated `Buying from Galleries FAQ` and `Buying from Auctions FAQ` links from the footer.
Old:
New:
> Remove outdated buying links from footer

- src/desktop/lib/global_client_setup.tsx
Looking at DD stats: https://app.datadoghq.com/apm/resource/force/express.request/10c6b04c37bfce28?end=1591295052881&env=production&event=AQAAAXKAc2KIz_Fj6gAAAABBWEtBYzJpODVTSWtsUGtCNEN0ag&index=apm-search&paused=false&spanID=7154884793715102852&start=1591291452881&traceID=7154884793715102852
It seems like somehow folks are able to access artsy via `artsy.net`, without the www, even though we have https://github.com/artsy/artsy-wwwify. 
This makes things a bit safer by checking for a bare hostname.
> Fix hosthame in bundle lookup

- src/lib/datadog.ts
Enable tracing for redis now that we are caching data to it.
> Instrument Datadog Redis Tracing

- src/desktop/apps/artsy-v2/apps/artwork/artworkClient.tsx
- src/desktop/assets/main_layout.styl
With https://github.com/artsy/force/pull/5724 I accidentally broke the Auctions + Collector FAQ hooks on the artwork page.
For context, since I'd removed those FAQs from the footer, I thought it was safe to remove the mediator hooks _within_ the footer component. But turns out that was also being used to hook into the artwork page!
Since I believe the only usage of these FAQs is on the artwork page now, I stuck the hooks there for clarity.
> Fix Auction and Collector FAQ mediator hooks

- src/desktop/lib/global_client_setup.tsx
- src/desktop/lib/webpackPublicPath.ts
Noticed this issue when reading the docs: https://webpack.js.org/guides/public-path/#on-the-fly
> [Webpack] Move public path settings into own module

- src/desktop/apps/artsy-v2/server.tsx
- src/desktop/index.ts
- src/v2/Apps/Artwork/routes.tsx
- src/v2/Apps/ViewingRoom/routes.tsx
Wondering what you think of this approach? It should stop the flood of `/profile/artist` requests (something that currently happens when someone hits an artist page, due to being matched in https://github.com/artsy/force/blob/add867633daab1cb648b6eec5432bcf6158620c1/src/desktop/apps/profile/index.coffee#L14)
> @damassi => [Mount] Change mount order, and dont use wildcard for V2 apps

- src/v2/Apps/Conversation/Components/Details.tsx
- src/v2/Apps/Conversation/Components/InboxHeaders.tsx
- src/v2/Apps/Conversation/Components/Reply.tsx
- src/v2/Apps/Conversation/Routes/Conversation/index.tsx
Fixes [PURCHASE-1905](https://artsyproduct.atlassian.net/browse/PURCHASE-1905)
[A mini tour of the PR](https://github.com/artsy/force/pull/5735/files#r436007460)
There are 3 types of animation:
* **xs:** detail box fades in
* **xl:** detail box slides in while pushing the middle box content left
* **s/m/l:** detail box slides over middle box
[Designs](https://www.figma.com/proto/vtXzdPefblvRiAapA79fTh/Conversations-Inbox?node-id=1189%3A27405&viewport=1502%2C507%2C0.3293892741203308&scaling=scale-down)
**xs**
**md**
**lg**
> [PURCHASE-1905] Conversation detail animation

- .circleci/config.yml
It was noted that slack alerts for staging are no longer needed to the integrity channel. Given that this is currently causing force master to be red (but not necessarily blocking deploys) it'd be good to go ahead and remove this.
> Remove failing slack alerts

- src/desktop/apps/profile/routes.coffee
- src/desktop/apps/profile/test/routes.test.coffee
With the route order updates, we no longer get the profile requests for 'artist', 'collection', etc.
However, we still get them for the erroneous '/assets/...' ones. This just skips that check for the 'assets' profile (🙈 )
> @damassi => [Assets] Skip profile check for erroneous asset route

- src/v2/Apps/Conversation/Components/Conversation.tsx
[PURCHASE-1918]
https://www.notion.so/artsy/Conversation-not-updated-correctly-when-new-messages-is-entered-by-collector-61d0224fe67e4d44bf8c13fe52565a4b
__Before:__
__After:__
[PURCHASE-1918]: https://artsyproduct.atlassian.net/browse/PURCHASE-1918
> Date of the last message not updated in conversation

- src/v2/Apps/Conversation/Mutation/SendConversationMessage.ts
I accidentally broke our optimistic response when I renamed `messages` to `messagesConnection`. This corrects that.
> Correct conversation optimistic response to use messagesConnection

- src/v2/Apps/Artist/Components/ArtistTopWorksRail/ArtistTopWorksRail.tsx
- src/v2/Apps/Artist/Components/ArtistTopWorksRail/__tests__/ArtistTopWorksRail.jest.tsx
- src/v2/Apps/Artist/Routes/Overview/__tests__/index.jest.tsx
- src/v2/Apps/Artist/Routes/Works/__tests__/Works.jest.tsx
- src/v2/__generated__/ArtistTopWorksRail_artist.graphql.ts
- src/v2/__generated__/Works_Test_Query.graphql.ts
- src/v2/__generated__/routes_OverviewQuery.graphql.ts
- src/v2/__generated__/routes_WorksQuery.graphql.ts
Updates the sort on the Top Works rail artworks to use `-weighted_iconicity` parameter.
After, sorting on `-weighted_iconicity`:
Before, sorting on `-iconicity`:
https://artsyproduct.atlassian.net/browse/FX-1996
> Use weighted iconicity sort in Artist Top Works rail

- src/desktop/analytics/inquiry_questionnaire.js
- src/desktop/analytics/main_layout.js
- src/desktop/assets/analytics.coffee
- src/typings/global.d.ts
- src/v2/Apps/Artwork/ArtworkApp.tsx
- src/v2/Artsy/Analytics/__tests__/trackingMiddleware.jest.ts
- src/v2/Artsy/Analytics/trackingMiddleware.ts
This fixes an issue that came up from cleanup work in https://github.com/artsy/force/pull/5679
In short, we now use our `RouterLink` component more widely for routing between pages, and rely less on link interception as described in #5679. This caused things to break because we would previously
- intercept a link click to, say, `/artwork/andy-warhol` 
- store a ref to the current url as the referrer 
- _push_ the intercepted link onto the stack
- then when performing the tracking on the artist page, use the stored referrer.
See https://github.com/artsy/force/blob/master/src/v2/Artsy/Router/interceptLinks.ts#L21-L28
However, now that we use the `<Link>` component we no longer need to intercept and can simplify our referrer tracking pipeline, and consolidate everything inside of our …
> Fix artwork referrer

- src/desktop/components/main_layout/templates/artsy_v2.jade
- src/v2/Artsy/Relay/createRelaySSREnvironment.ts
Fixes: https://artsyproduct.atlassian.net/browse/PLATFORM-2476
This fixes our SSR rehydration issue around the new app shell migration.
The problem was that previously, for our SSR apps, we were rendering them in a different server side jade template than what we're using for the new app shell. When everything was consolidated into one place there was a slight misconfiguration.
> [Clientside Routing] Fix SSR rehydration

- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarExtraLinks.jest.tsx
- src/v2/Apps/Order/Components/__tests__/StickyFooter.jest.tsx
- src/v2/Artsy/Analytics/Schema/Values.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-1885
> Update NSO and inquiry FAQ link on artwork sidebar (PURCHASE-1885)

- src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
- src/v2/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.jest.tsx
- src/v2/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
- src/v2/__generated__/ArtistAuctionResultsQuery.graphql.ts
- src/v2/__generated__/ArtistAuctionResults_artist.graphql.ts
- src/v2/__generated__/AuctionResults_Test_Query.graphql.ts
- src/v2/__generated__/routes_AuctionResultsQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-1926
Trigger auth modal when user change filters/page for the 1st time. Ask for artist name in GraphQL query, and show it in modal copy.
> Trigger auth modal upon first user interaction.

- src/v2/Apps/Debug/debugRoutes.tsx
- src/v2/Apps/getAppRoutes.tsx
Adds a baseline app shell app that we can use for testing, lighthouse, Calibre, etc. 
Thanks for the suggestion @dzucconi 👍
> [AppShell] Add `debug-routes` app for baseline tests

- webpack/envs/developmentConfig.js
I noticed that force builds were hanging for a bit locally and realized it was due to source map generation. Providing `eval` as a default makes it more snappy.
> Add eval as default devtool in webpack build

- src/v2/Apps/Auction/Components/RegistrationForm.tsx
- src/v2/Apps/Auction/Components/__stories__/RegistrationForm.story.tsx
- src/v2/Apps/Auction/Routes/Register/index.tsx
- src/v2/Apps/Auction/Routes/__tests__/Register.jest.tsx
This pull request replaces the `status` message added in [the previous PR](https://github.com/artsy/force/pull/5699/files#diff-11bf8a936a98ab5a5856792a42114073R116-R120) with the error modal that was already in place.
> Use the error modal to display any error message on the registration form

- src/v2/Apps/Auction/Components/Form/__tests__/helpers.jest.tsx
- src/v2/Apps/Auction/Components/Form/helpers.tsx
- src/v2/Apps/Auction/Components/RegistrationForm.tsx
- src/v2/Apps/Auction/Operations/CreateCreditCardAndUpdatePhone.ts
- src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/v2/Apps/Auction/Routes/Register/index.tsx
- src/v2/Apps/Auction/Routes/__fixtures__/MutationResults/createCreditCardAndUpdatePhone.ts
- src/v2/Apps/Auction/Routes/__tests__/ConfirmBid.jest.tsx
- src/v2/Apps/Auction/Routes/__tests__/Register.jest.tsx
addresses: https://artsyproduct.atlassian.net/browse/AUCT-1087
~~blocked by: https://github.com/artsy/force/pull/5770~~ unblocked
This PR extracts a more detailed error message from the GraphQL response (which originally comes from Stripe) and show it to the user. See screenshot for what it looks like.
> Display error messages from Stripe as a credit card field error

- jest.config.js
While working on https://github.com/artsy/force/pull/5779, I noticed my tests are not picked up by `jest`. Looking a little deeper, it seems the `artsy-v2` app was ignored because of current jest config.
Total of 277 test suites
Total of 282 test suites
> Fix jest test path for artsy-v2 app

- src/lib/metaphysics2.coffee
- src/test/lib/metaphysics2.test.coffee
https://artsyproduct.atlassian.net/browse/FX-2042
Just a lil DX improvement here as we undertake the Metaphysics v1 → v2 migration.
Since step 1 in many cases will be to just switch from Force's MP v1 client to the MP v2 client in order to see what breaks, it would be nice to have immediately useful feedback in local Force's server console output.
> Add error logging for Metaphysics v2 requests

- src/desktop/apps/artsy-v2/middleware/__tests__/userRequiredMiddleware.jest.ts
- src/desktop/apps/artsy-v2/middleware/userRequiredMiddleware.tsx
- src/desktop/apps/artsy-v2/utils/getPageType.ts
https://artsyproduct.atlassian.net/browse/PURCHASE-1914
Depending on https://github.com/artsy/force/pull/5780.
The current conversations app does not require a logged-in user, and that causes:
- visiting /user/conversations would 500
- visiting /user/conversations/:id would 404
- logging out from conversations page would visit the same route, so 500 or 404 similarly
This PR requires a user for the conversations app, and follows the existing behavior for logging out from other pages: rendering the login page with proper redirect param (to take user back to the original page after logging in).
> Require user for collector inbox (PURCHASE-1914)

- .storybook/webpack.config.js
Storybooks started failing once we introduced a new code-path to the compile pipeline -- `src/lib` -- where previously we were only compiling `v2`. We also needed to exclude redis from webpack.
> [Toolchain] Fix storybooks

- src/desktop/analytics/editorial_features.js
- src/desktop/analytics/main_layout.js
- src/mobile/analytics/global.js
Removed additional, non 15 secs, events being fired. In progress: switching to use `timeOnPage`.
> Removed events over 15 secs (PLATFORM-2414)

- src/mobile/components/layout/bootstrap.coffee
- src/mobile/components/layout/stylesheets/index.styl
- src/mobile/components/layout/templates/main.jade
- src/mobile/components/layout/test/layout.test.coffee
https://artsyproduct.atlassian.net/browse/FX-1927
Clicking "Logout" from the navbar on old mobile web views (i.e. not Reaction) produces no result and the user is not able to log out. Users can still logout on desktop and mobile web views using Reaction.
The handler for the `auth:logout` event lives in `global_client_setup.tsx` and is set up by invoking `globalClientSetup`. Desktop views and Reaction views both use this client setup but old mobile web views do not. When the user attempts to logout, the mediator triggers the `auth:logout` event but the corresponding listener doesn't exist. The result is that the user cannot logout.
- Add new `logoutEventHandler` method  that listens for the `auth:logout` event to common mobile layout code for old mobile web routes.
- Add desktop …
> Fix mobile web logout bug

- src/mobile/components/filter2/index.coffee
As reported [on slack](https://artsy.slack.com/archives/C9ZJYFDNF/p1592312653447800), we noticed that institutional works were not showing up in a fair's `/browse/artworks` section on mobile web.
Digging into the code, I found that we are (by default) filtering by `for_sale` true in our `filter2` component on mobile web (which is also used by the gene page and a deprecated browse page).
We also don't give users the ability to add/remove a "For sale" filter on any of these views, so users are never able to see not-for-sale works.
Note that this change means that we are now displaying not-for-sale works on gene pages, but given the explanation above I think that's probably okay.
(Gene page) Before:
(Gene page) After:
(Fair page) Before-- the specific bug:
(Fair page) After-- the specific …
> [MWeb] Remove the explicit for_sale filter on mweb artworks grid

- src/desktop/apps/auction_reaction/client.tsx
addresses https://artsyproduct.atlassian.net/browse/AUCT-1093
Chris and I paired and he found that the `loadableReady` call is missing in `src/desktop/apps/auction_reaction/client.tsx`. I tried to run the integrity test against the locally running instance 10 times and they all succeeded while 1 out of 10 times with the current master failed. The statistics may not be that accurate due to, well, I might have been just lucky when running the test, but I feel pretty good about it.
Once this is staging I'm also going to revert https://github.com/artsy/integrity/pull/143.
> Possibly fix the loading issue on the auction registration form

- package.json
- src/v2/Apps/Artist/Components/ArtistTopWorksRail/ArtistTopWorksRail.tsx
- src/v2/Artsy/Analytics/Schema/index.ts
- yarn.lock
- Also bumps up cohesion version to 1.12.0
> Fix cohesion TS errors in tracking Notable Works rail content

- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
- src/v2/Components/v2/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx
I think these buckets might make more sense! Plus it lets the 40-50 range be clickable.
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=FX&modal=detail&selectedIssue=FX-2046
> @sweir27 => [PriceFilter] Adjust bucketing

- src/v2/Apps/Auction/Components/AuctionErrorModal.tsx
- src/v2/Apps/Auction/Components/BidForm.tsx
- src/v2/Apps/Auction/Components/Form/helpers.tsx
- src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/v2/Apps/Auction/Routes/Register/index.tsx
- src/v2/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
- src/v2/Apps/Auction/Routes/__tests__/ConfirmBid.jest.tsx
- src/v2/Apps/Auction/Routes/__tests__/Register.jest.tsx
- src/v2/Apps/Auction/getRedirect.ts
addresses https://artsyproduct.atlassian.net/browse/AUCT-1090
This PR replaces the general `status` message with an appropriate UI. There is another doc that hosts a list of error cases on the registration and bid+register forms and I'm going to update this PR once we are all on the same page.
> User should see an error message in the error modal on the bid+register form

- src/v2/Apps/Conversation/Components/ConversationSnippet.tsx
Truncates the title after 140px
After:
Before:
> Limit the width of gallery names to not overflow conversation snippets

- src/v2/Apps/Conversation/Components/Details.tsx
- src/v2/Apps/Conversation/Components/Reply.tsx
In [the previous PR](https://github.com/artsy/force/pull/5735), changed the `<Detail />` position to `absolute` for S/M/L screens so now the height must exclude header(s)
Also changed the reply box `z-index` to make it show up over the detail box.
I was interested to get rid of those `px` sizes as much as possible but seems it needs major restructuring of the page 😬 
Before (gap on the bottom of the page after scrolling all the way to the bottom)
After:
> Fix conversation M screen scroll

- src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
- src/v2/Apps/Auction/Routes/Register/index.tsx
Apparently the loading state is broken due to a non-blocking call passed in to `Formik`.
`Formik` internally calls `setSubmitting(true)` before execution and `setSubmitting(false)` once the entire work is done, which is supposed to be helpful. However, for some reason it assumes that the `onSubmit` call is a blocking call (which in most cases is not), and does not wait until the entire async task is done, resulting in just calling `setSubmitting(false)` right after calling `setSubmitting(true)`. This is also hard to test since we mock out async GraphQL calls with a blocking mock function in test.
For now I just added a workaround with a `setTimeout`, which is obviously a smell (and doesn't necessarily solves the problem due to a possible race condition), but it's better than nothing for …
> Fixes an issue where spinner does not show up on registration and bid+register forms

- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/GalleryFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/InstitutionFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
Related Palette PR: https://github.com/artsy/palette/pull/712
White spacing on artwork filters is too large (https://artsyproduct.atlassian.net/browse/FX-1993).
In addition to https://github.com/artsy/palette/pull/712 which removes the top margin in Palette's `Toggle` component, we need to remove the additional top/bottom margins on the top level child component to `Toggle`. This impacts the `ArtworkFilters` on both desktop and mobile web and keeps the whitespacing consistent.
> Fix whitespace on artwork filters

- src/v2/Apps/Conversation/Components/Reply.tsx
- src/v2/Apps/Conversation/Mutation/SendConversationMessage.ts
Fixes [PURCHASE-1923](https://artsyproduct.atlassian.net/browse/PURCHASE-1923)
Add SendConversationMessage mutation error handling modal
Also (temporarily) removes the `uptimisticUpdater` because relay doesn't roll it back when error?!
[Double checked](https://artsy.slack.com/archives/C9YNS4X32/p1592503222359800) with Will on design changes.
> [PURCHASE-1923] Conversation mutation error handling

- src/v2/Apps/Conversation/Components/Details.tsx
- src/v2/Apps/Conversation/Components/Message.tsx
- src/v2/__generated__/Details_conversation.graphql.ts
- src/v2/__generated__/Message_message.graphql.ts
- src/v2/__generated__/SendConversationMessageMutation.graphql.ts
- src/v2/__generated__/routes_DetailQuery.graphql.ts
In the conversation thread:
In the details panel:
Note that image attachments don't show up in the attachments details view (by design)
> Render attachments in conversation threads and details

- src/v2/Components/FlashBanner/__tests__/FlashBanner.jest.tsx
- src/v2/Components/FlashBanner/index.tsx
[Jira ticket 🔒 ](https://artsyproduct.atlassian.net/browse/AUCT-1089)
I'll merge with @damassi's + one more approving review.
This PR updates the Flash Banner's `SystemQueryRenderer` `query` prop to be null, causing the underlying relay queryrenderer to [skip querying](https://relay.dev/docs/en/query-renderer.html#props) if there is no user to query for.
As an alternative approach I spent a little while trying to make `sd.CURRENT_USER` fully replace `me` ([diff here](https://gist.github.com/erikdstock/b49cbb9349a1f2623d701fb4fc132320)), basically by adding `can_request_email_confirmation` to the allow list for current_user's properties. Unfortunately I realized this user object does not pick up changes immediately, causing the 'request email confirmation' banner to continue appearing …
> Skip pointless flashbanner query if the user is present

- src/v2/Apps/Conversation/Components/Conversation.tsx
- src/v2/Apps/Conversation/routes.tsx
https://artsyproduct.atlassian.net/browse/PURCHASE-1916
We implemented the scrolling to bottom behavior on the conversation page when
- the conversations page (`/user/conversations/:id`) first renders, and
- user replies and adds a new message to the view.
The scrolling on page render was broken (on Chrome, but Safari was fine), and it turns out to be [`<ScrollManager>`](https://github.com/artsy/force/blob/3994ddd12d85bf548256751d8da141ad59e06a5d/src/v2/Artsy/Router/buildClientApp.tsx#L91) interfering the scrolling behavior. I don't know exactly why but turning that off on conversation page fixes it.
We are using `smooth` transition animation for both use cases. _I think_ it'd be nice when the page renders it starts from the bottom as soon as possible, so I change to only apply the …
> Fix scrolling to bottom on conversation page (PURCHASE-1916)

- src/v2/Apps/Conversation/Components/Conversation.tsx
- src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx
- src/v2/__generated__/Conversation_conversation.graphql.ts
- src/v2/__generated__/routes_DetailQuery.graphql.ts
Addresses: [PURCHASE-1953](https://artsyproduct.atlassian.net/browse/PURCHASE-1953)
This styles the show inquiry item. I labelled this as WIP because I'm refactoring the `Item` component a bit and wanted to get some eyes and feedback on it.
**Artwork Item:**
**Show Inquiry:**
[PURCHASE-1953]: https://artsyproduct.atlassian.net/browse/PURCHASE-1953
> [PURCHASE-1953] style show inquiry item and refactor Item component

- src/v2/Apps/Conversation/Components/Details.tsx
The invisible detail box (with `opacity: 0`) was above the conversation box and blocking the events to get to the below level and breaking the scroll. I had a `z-index: -1` there but it was overridden by the large screen media query so I had to add it again to `xs` media query.
Before:
After:
> Fix conversation scroll bug

- src/desktop/apps/consign/components/choose_artist/index.js
- src/desktop/apps/consign/components/location_autocomplete/index.js
- src/desktop/apps/consign/components/upload_photo/index.js
Partially addresses https://artsyproduct.atlassian.net/browse/INTGRTY-38
* Adds a couple `data-test` attributes to hook into elements in integration tests
* Converts a couple "clickable div's" to buttons. (This change is not _required_ to write the integration tests, but I noticed them and if they're meant to be clicked, they should be buttons.)
No noticeable changes to the user.
> [INTGRTY-38] Add hooks for consign submission form integration tests

- src/v2/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionsRail.tsx
#minor QA followup to the Artist rails work in #5817 
Before:
After:
> Removes separator between top works and collection rail on artist page

- .env.oss
- package.json
- src/desktop/apps/about/index.coffee
- src/desktop/apps/about/routes.coffee
- src/desktop/apps/about/test/routes.test.coffee
- src/desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- src/desktop/apps/editorial_features/components/venice_2017/templates/video_description.jade
- src/desktop/apps/editorial_features/index.coffee
- src/desktop/apps/editorial_features/routes.coffee
- src/desktop/apps/editorial_features/test/routes.test.coffee
- src/desktop/config.coffee
- yarn.lock
https://artsyproduct.atlassian.net/browse/FX-1881
This is a followup to https://github.com/artsy/force/pull/5272
- Removes old SMS routes `/about/sms` and `/venice-biennale/sms`
- Removes ability for user to text themselves a link to download the Artsy app on editorial features (primarily `/venice-biennale/toward-venice`)
- Removes Twilio and associated configs
> Cleanup old SMS routes and remove Twilio

- hokusai/staging.yml
We are having a problem where staging Kubernetes not able to schedule new force-web pods. Staging deployments have been failing.
https://artsy.slack.com/archives/CA8SANW3W/p1593104547350200
Reducing force-web CPU request to make it more schedulable.
> Reduce force-web staging k8s cpu request.

- package.json
- src/v2/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
- src/v2/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.jest.tsx
- src/v2/Components/NavBar/NavBar.tsx
- src/v2/Components/__stories__/NavBar.story.tsx
Re: [FX-1861](https://artsyproduct.atlassian.net/browse/FX-1861)
This utilizes the same dependency we're using in palette for removing scroll. In addition the design changes a bit to just fully overlay content.
I'm not exactly happy with this because:
* Extra divs and a separate position fixed stacking context are required because the animated panes relies on moving z-indexes. (This is the reason we can't just use `ModalBase`)
* There's still the whole issue of scrolling panes WITHIN the menu, which is less annoying but still annoying (due to the same issue of moving around z-indexes in pre-rendered panes)
* The close button requires hardcoded values because the underlying mobile nav also requires hardcoded values
-----
A related bug due to all the hardcoded values we've got some weird …
> [FX-1861] Prevents mobile nav from scrolling

- src/desktop/apps/artists/query.coffee
- src/desktop/apps/artists/routes.coffee
- src/desktop/components/artist_cell/query2.coffee
Uses https://github.com/artsy/metaphysics/pull/2491
Utilizes field aliasing to avoid needing to modify template/other code. The `id: internalID` is an important and non-obvious one.
> @dzucconi => [Artists] Update page to use Metaphysics V2

- src/v2/Apps/ViewingRoom/ViewingRoomsApp.tsx
- src/v2/Apps/ViewingRoom/__tests__/ViewingRoomsApp.jest.tsx
- src/v2/Apps/ViewingRoom/routes.tsx
- src/v2/__generated__/ViewingRoomsApp_Test_Query.graphql.ts
- src/v2/__generated__/ViewingRoomsApp_viewingRooms.graphql.ts
- src/v2/__generated__/routes_ViewingRoomsAppQuery.graphql.ts
Thanks @damassi and @ansor4 for bearing with me here.
This is by no means a finished page but a beginning of `/viewing-rooms` page here.
@pvinis - I'm hoping in the next step here we can see how to create the VRs Grid reusing some of those cards I believe you've created for iOs view. Maybe we can pair on that at some point?
> [GALL-2979] - Starting a placeholder for ViewingRoomsApp and route

- src/desktop/apps/user/components/tabs/index.styl
Fixes FX-2055
- made the nav bar scroll horizontally at < 768px
- added a gradient block as an affordance to make it clear that it's scrollable
Questions:
- do I have to use magic number media queries like this in the stylus files, or is there a nicer way to do it?
- I made `.settings-tabs` use flexbox on all sizes - is this safe? if not, I could maybe move it into the media query?
> fix: make /user nav mobile friendly

- src/v2/Apps/Feature/Components/FeatureSet.tsx
Our internal teams are setting up their first feature with the new format and desire to up the limit here.
Pagination is a worthy follow-up but hopefully this unblocks things for now as they're planning to launch on Wednesday!
> Up the limit on number of items in a set to show in a feature (still no pagination)

- src/v2/Apps/ArtistSeries/ArtistSeriesApp.tsx
- src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
- src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesApp.jest.tsx
- src/v2/Apps/ArtistSeries/routes.tsx
- src/v2/Apps/getAppRoutes.tsx
- src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
- src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
- src/v2/__generated__/ArtistSeriesApp_artistSeries.graphql.ts
- src/v2/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts
- src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/FX-2007
---
**Goal**: Set up basic structure of the artist series page and display minimal artist series metadata on desktop and mobile web.
- Creates a basic artist series page for desktop and mobile web with a minimal header showing the title and description of an artist series.
- URL structure is `/artist-series/$slug`
- It does not show a header image for the artist series, which will come as a follow up. We currently have a gray box as a stand-in for the image.
- It also does not implement "Read more" functionality for the description.
- The page is only accessible to users who have the lab feature turned on -- otherwise, navigation to an artist series page results in a 404.
Collab: @anandaroop @ashleyjelks @mzikherman 
---
> Initial artist series page

- src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
- src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
- src/v2/__generated__/ViewingRoomApp_LoggedOutTest_Query.graphql.ts
- This checks the context for a user log-in status and does the following if the user is logged out: 
- Opens sign up modal
- Removes viewing room content or any messages related to viewing room status if user if logged out.
- Adds the `<SystemContextProvider>` in jest tests for the needed `SystemContext`. 
- Use `useEffect` to render modal in client side context since we need access to `location.href` to redirect to after sign-up/log-in.
> GALL-2880 Signup for viewing rooms

- src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
- src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
Paired with @dzucconi on this, going to merge straight away to get see if we can squeeze it out ahead of tomorrow. Basically the call to `openAuthModal` uses the mediator to fire off an event called "open:auth". In order for the sign up modal to appear, a corresponding `ModalContainer` needs to be mounted in order to ingest the "open:auth" event. So there was a race condition between the event being fired and the `ModalContainer` being mounted. Here, we hack around it by using `setImmediate` to wait for the next tick and call `openAuthModal` then.
> Use setImmediate to avoid race condition

- hokusai/staging.yml
Staging web container CPU request was originally at 700m. Last week when deployments were failing due to CPU, I drastically reduced the spec to 50m, to ensure deployments would go through. I have just now gone through every Force review app and reduced its spec to 100m. We have more CPU head room now. So I would like to raise staging spec to 100m which is probably sufficient.
> Set staging web container cpu request to 100m.

- src/desktop/apps/unsupported_browser/template.jade
- src/desktop/components/error_handler/index.jade
- src/desktop/components/main_layout/templates/index.jade
- src/desktop/components/main_layout/templates/minimal_header.jade
- src/desktop/components/main_layout/templates/redesign.jade
- src/v2/Apps/Components/AppShell.tsx
- src/v2/Apps/Debug/debugRoutes.tsx
- src/v2/Components/NavBar/NavBar.tsx
Here's what the normal tab order looks like (I added the purple outlines just so you can see what's happening, those aren't there (yet)).
Here's what the tab order looks like if you choose to engage the skip to content link
This doesn't explicitly help on it's own because *so much* of our UI is completely invisible to keyboards — that's a separate issue that still needs a ticket. But this is one of the easier things in the Lighthouse audit to knock down.
> [FX-2072] Skip link, landmarks

- src/v2/Components/Artwork/GridItem.tsx
So this is an interesting one. I had been assuming this was something weird with the lazy loading implementation but it turns out this is due to an edge case in rendering CSS columns in WebKit — best I can tell — going to try to create a minimal replication and file a bug report.
The artwork grid items utilize aspect ratio boxes, which is a pretty common and well supported hack using a `0px` `height` and a `padding-bottom` to size the container to the correct dimensions while making it responsive in width. Which is fine, but apparently in WebKit's columns implementation, the first column treats the stacked absolute element correctly but then on subsequent columns is incorrectly respecting `overflow: hidden` + the `0px` `height` and not rendering the absolutely positioned element.
So a …
> Fixes hidden images within CSS columns

- src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewWorksButton.tsx
- src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
- src/v2/Apps/ViewingRoom/Routes/Statement/ViewingRoomStatementRoute.tsx
- src/v2/Apps/ViewingRoom/Routes/Statement/__tests__/ViewingRoomStatementRoute.jest.tsx
- src/v2/__generated__/ViewingRoomStatementRoute_Test_Query.graphql.ts
- src/v2/__generated__/ViewingRoomStatementRoute_viewingRoom.graphql.ts
- src/v2/__generated__/ViewingRoomWorks_viewingRoom.graphql.ts
- src/v2/__generated__/routes_ViewingRoomStatementRouteQuery.graphql.ts
This is the counter part of the ticket. We still need to refactor to use the first 4 artworks and put them into greed.
But the counter was listed as higher priority for tomorrow's Community pages.
Generates this button:
> [GALL-3017] - view Works on Statement page should include works count

- src/desktop/apps/article/__tests__/routes.jest.ts
- src/desktop/apps/article/queries/promotedContent.js
- src/desktop/apps/article/routes.tsx
Article page/setup as I understand it:
- Article code generally hits PositronQL and is fetched from within Force. The React components still live in Reaction (not merged with Force).
- Some editorial code in Reaction though does hit Metaphysics (tooltips), and that was updated to use V2 during the migration: https://github.com/artsy/reaction/pull/2982
- There remains some minimal Metaphysics code for the article page in Force (which otherwise uses PositronQL), updated here.
> @eessex => [Article] Switch Force server-side to use MP V2

- src/v2/Apps/Conversation/Components/Conversations.tsx
- src/v2/Apps/Conversation/Components/Details.tsx
- src/v2/Apps/Conversation/Components/InboxHeaders.tsx
- src/v2/Apps/Conversation/Components/Reply.tsx
Fixes remaining from [PURCHASE-1977](https://artsyproduct.atlassian.net/browse/PURCHASE-1977) reported [here](https://www.figma.com/file/vtXzdPefblvRiAapA79fTh/Conversations-Inbox?node-id=1449%3A28359)
(first commit)
- Attachment list margins
- Remove `contact artsy ...`
- Close button for L detail screens
- Detail box icon size
- Mobile header tweaks
- Reply box should be below detail box on mobile
(2nd commit)
- Add margin bottom to conversations left panel
> [PURCHASE-1977] Conversation visual fixes - part II

- src/mobile/components/layout/test/layout.test.coffee
Re: https://artsy.slack.com/archives/CP9P4KR35/p1593543490366500
I had assumed this was something to do with the timers since it was failing in the `ClockView` spec, which is difficult to track down but had I just read the error message:
```
TypeError: Attempted to wrap reload which is already wrapped
```
There was only one other place where `reload` was being stubbed — so this was easier to track down.
> [CI] Fixes failing specs by tearing down stubs/benv

- src/v2/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
Re: https://artsy.slack.com/archives/C04KVDZU6/p1593699708206700
There's a lot that's weird about this 😅 
You'll notice in the video in that Slack thread that it's a touch device (iPad) but if you actually try to debug this in Chrome and hit the site with touch enabled you get the Microgravity homepage view, which has a stacking context for the nav in which this isn't an issue.
So how touch is detected and routed — there's almost certainly a bug there...
The desktop/non-touch homepage also renders the nav in a different container than the rest of the site which is why it's behind everything on that view. You won't see this unless you disable touch in the responsive view. (Side note: the stack on the homepage is deeply weird — which I think stems from the way that sticky hero is hacked in …
> [FX-2080] Utilizes ModalBase to break out of weird homepage stacking context

- src/desktop/apps/user/components/tabs/index.styl
- src/desktop/apps/user/stylesheets/index.styl
Fixes FX-2079
- expand the horizontally scrollable nav bar to the right edge as an affordance
- expand the Collector Profile content to 100% width in mobile
> fix: profile views layout improvements on mobile

- src/desktop/apps/about/stylesheets/index.styl
- src/v2/Components/NavBar/NavBar.tsx
- src/v2/Components/NavBar/NavItem.tsx
- src/v2/Components/NavBar/__tests__/NavBarTracking.jest.tsx
I swear I fixed the double /about footer back in [this PR](https://github.com/artsy/force/pull/5604), but I would not be surprised if some other change to the global footer/general styling caused this to come back 😅. 
This also addresses https://artsyproduct.atlassian.net/browse/FX-2055 . We want to remove hover tracking on the NavBar because the events are currently eating away at our Segment quota (and we don't actually use the events for anything).
> Removes hover tracking on nav bar + fixes double /about footer

- src/v2/Apps/Conversation/Components/Conversation.tsx
- src/v2/Apps/Conversation/Components/Message.tsx
- src/v2/Apps/Conversation/Components/Reply.tsx
- src/v2/Apps/Conversation/Routes/Conversation/index.tsx
Fixes [PURCHASE-1990](https://artsyproduct.atlassian.net/browse/PURCHASE-1990)
<details><summary>screenshots:</summary>
<p>
Note the. `send` button in the bottom of the page
</details>
**Tip:** In the first commit, I just rearranged the elements a bit so you can just check out the second commit.
In order to fix this, I had to change the `position: fixed` style to flex box. The idea is that instead of sticking the box to the bottom with `position: fixed; bottom: 0;` put the messages and reply box in a flexbox and set the height of messages box to take the entire section. Then move the scrolling to a container inside the 'messages' box.
> [PURCHASE-1990] Reply box should not extent when detail box is open

- src/desktop/apps/auctions/templates/index.jade
- src/desktop/models/sale.coffee
https://artsyproduct.atlassian.net/browse/AUCT-1124
slack thread https://artsyproduct.atlassian.net/browse/AUCT-1124
We will eventually show times in the time zone of the auction. This is a quick fix to make the pages consistent.
> Make start_at on auctions overview page use New York time

- src/v2/Apps/Conversation/Components/TimeSince.tsx
- src/v2/Apps/Conversation/Components/__tests__/TimeSince.jest.tsx
Addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-1992
Did a lot of manual testing by changing the machine time on my computer locally
Ex of changes:
If last message sent less than 1 minute ago:
Timestamp reads `Just now`
If last message sent less than 5 hours ago:
Timestamp reads `X hours ago`
If last message sent less than 24 hours ago:
Timestamp reads `1:00PM` format
If last message sent less than a week ago:
Timestamp reads `X days ago` format
If last message sent less than a month ago:
Timestamp reads `1 week/X weeks ago` format
If last message sent greater than a month ago:
Timestamp reads `MM/DD/YYYY` format
> [PURCHASE-1992] Add logic for customizing message sent timestamps

- src/v2/Apps/Conversation/Components/Reply.tsx
[PURCHASE-1984]
Text input stays in the expanded state after replying long messages and covers the last message
https://www.notion.so/artsy/Text-box-gets-stuck-open-when-long-messages-are-written-3895fcb1ae74412f9875e5adad24a66e
[PURCHASE-1984]: https://artsyproduct.atlassian.net/browse/PURCHASE-1984
> Close expanded text input on message send

- package.json
- src/desktop/components/react/stitch_components/StitchWrapper.tsx
- src/v2/Artsy/Router/Boot.tsx
- src/v2/Components/FocusVisible.tsx
- yarn.lock
Re: [FX-2076](https://artsyproduct.atlassian.net/browse/FX-2076)
So in the gif above you can get a sense of the behavior — a 1px purple focus ring outline will show up only when tabbing/shift+tabbing. What you'll notice is that big pieces of navigation and pages are not accessible via keyboard, and in other places elements have too many focus points making navigation tedious.
I think the most appropriate next steps here are [making the global nav accessible](https://artsyproduct.atlassian.net/browse/FX-1821) — (there's a ticket [to create a tech plan for this](https://artsyproduct.atlassian.net/browse/FX-1884), cc @sweir27)
I'll make tickets for some of the bigger inaccessible items as well (notably the filter sidebar is totally inaccessible for some reason). We should also install some …
> [FX-2076] Polyfills :focus-visible; adds :focus-visible outlines

- src/desktop/apps/categories/components/FeaturedGenes.js
- src/desktop/apps/categories/components/GeneFamily.js
- src/desktop/apps/categories/components/GeneFamilyNav.js
- src/desktop/apps/categories/queries/geneFamilies.js
Small follow-up to the MP v2 migration in #5881 
Some of the changes to the  ID related fields in MP v2 caused a regression in the scrolly nav. This should fix that!
This interaction is not covered by tests, so this squeaked through to staging 😅
> Fix /categories navigation

- src/desktop/apps/notifications/routes.coffee
- src/desktop/apps/notifications/test/routes.test.coffee
When linking to `artsy.net/works-for-you?artist_id=josef-albers&from_email=true`, if the user is logged out, they should be taken to the Works tab for the artist in question.
Some time in the past we changed `[artist]/works` to `[artist]/works-for-sale` and missed this redirect. This PR fixes the issue, so that logged out users clicking a link like the above will be properly taken to the `Works for sale` tab of the artist page.
Full [Slack discussion](https://artsy.slack.com/archives/C04KVDZU6/p1594307247216400) of the issue
> Redirect to artist/works-for-sale instead of artist/works

- src/desktop/apps/consign/client/actions.js
- src/desktop/apps/consign/client/reducers.js
We have a flappy integrity test against the consignment submission flow, where it occasionally fails because the suggested locations look like they're stale. Example [from this failed test run](https://app.circleci.com/pipelines/github/artsy/integrity/2287/workflows/97e7930e-2a2c-4d09-8c0d-fb8a0f275b84/jobs/10183): 
I've typed "Wauwatosa" into the box and would expect to see results that match that pretty well, but instead it looks like I'm seeing results for "W". 
My thought is: we are updating the suggestions with the last response. If they come back out of order, the last response does not correspond to the current search text.
So this PR includes the search text in the action, so that the reducer can verify that it is the "most recent" search response before updating the store.
There …
> Guard against potential race condition in consignments location search

- src/desktop/components/recently_viewed_artworks/index.coffee
Change `recently_viewed_artworks` to use Metaphysics v2
**Ticket/Issue Link:** https://artsyproduct.atlassian.net/browse/PLATFORM-2446
> [P-2446] Update recently_viewed_artworks to use Metaphysics v2

- src/v2/Apps/Conversation/Components/ConversationSnippet.tsx
- src/v2/Apps/Conversation/Components/Message.tsx
- src/v2/Apps/Conversation/Components/Reply.tsx
Paired with @xtina-starr 
__Before:__
__After:__
__Before:__
__After:__
__Before:__
__After:__
> Conversations small bug fixes

- src/v2/Apps/Conversation/Components/InboxHeaders.tsx
- src/v2/Apps/Conversation/Components/Message.tsx
Fixes some bugs reported [here](https://www.notion.so/artsy/2020-07-07-Collector-inbox-5212de7b7be0416caed0a6334ed05084)
First commit:
- Attachment icon becomes tiny when filename is long
<details><summary>screenshot</summary>
Before:
</details>
- Attachment icon goes over header when scrolling [bug report](https://www.notion.so/artsy/2020-07-07-Collector-inbox-5212de7b7be0416caed0a6334ed05084?p=9bb8c0250c5f48279bc90bb86a11d418) 
- Fix conversation detail header XL for safari. [bug report](https://www.notion.so/artsy/2020-07-07-Collector-inbox-5212de7b7be0416caed0a6334ed05084?p=3ea791d00f5e4f66a9afd14007a8d9ea) Not perfect but good for [now](https://artsy.slack.com/archives/C9YNS4X32/p1594327219238700)
Second commit:
- Large image width
<details><summary>screenshot</summary>
After: …
> Conversation QA bug fixes

- src/v2/Apps/Feature/Components/FeatureHeader.tsx
- src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
- src/v2/Artsy/Router/RouterLink.tsx
- src/v2/Components/Menu.tsx
- src/v2/Components/NavBar/LoggedInActions.tsx
- src/v2/Components/NavBar/Menus/DropDownMenu/DropDownMenu.tsx
- src/v2/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
- src/v2/Components/NavBar/Menus/MoreNavMenu.tsx
- src/v2/Components/NavBar/Menus/UserMenu.tsx
- src/v2/Components/NavBar/Menus/__tests__/UserMenu.jest.tsx
- src/v2/Components/NavBar/NavBar.tsx
- src/v2/Components/NavBar/NavBarPrimaryLogo.tsx
- src/v2/Components/NavBar/NavBarSkipLink.tsx
- src/v2/Components/NavBar/NavItem.tsx
- src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
- src/v2/Components/NavBar/__tests__/NavBarTracking.jest.tsx
- src/v2/Components/NavBar/__tests__/NavItem.jest.tsx
- src/v2/Components/NavBar/constants.ts
- src/v2/Components/NavBar/index.tsx
- src/v2/Components/Search/SearchInputContainer.tsx
Re: [FX-2088](https://artsyproduct.atlassian.net/browse/FX-2088), [FX-2088](https://artsyproduct.atlassian.net/browse/FX-2089), [FX-2090](https://artsyproduct.atlassian.net/browse/FX-2090)
On desktop — navigating with `<tab>` & `<shift+tab>` + `<enter>` or `<spacebar>` to open subnavs
The subnav stays open so long as the subnav button or anything within the subnav retains focus, once those are blurred the subnav will close.
I also made a few updates to the styling so that we aren't relying on magic numbers throughout. Notably the API for anchoring the subnav was changed to be `left | right | center | full`. Realistically we should be using a [positioning engine](https://popper.js.org/) here to handle this stuff automatically, but I think this is an improvement for the time being and …
> [FX-2088, FX-2089, FX-2090] NavBar a11y updates

- src/desktop/apps/categories/components/Gene.js
- src/desktop/apps/categories/components/__tests__/Gene.test.js
- src/desktop/apps/categories/queries/geneFamilies.js
This corrects one more instance of id/slug confusion in the /categories app MP v2 migration.
Fixes [malformed URLs](https://artsy.slack.com/archives/C9SATFLUU/p1594657044011800) in the links to gene pages.
> Use gene slug instead of id in /categories app

- src/v2/Components/NavBar/Menus/MobileNavMenu/LoggedInLinks.tsx
- src/v2/Components/NavBar/NavBar.tsx
__Issue:__
If on the Inbox page already, tapping on "Inbox" in the menu doesn't close the menu (other links do).
__Fix:__
Previously we were checking to see if we're clicking a link that lives within the new app shell and firing toggleMobileNav(false) to close the navbar. Since the check didn't include the inbox URL we weren't closing it. This PR removes that check and fires it at all times.
> Close mobile menu

- src/v2/Apps/Conversation/Routes/Conversation/index.tsx
[PURCHASE-2004]
https://www.notion.so/artsy/Layout-breaks-on-tablet-devices-18b6a33b91a3422d9a1efe80a6e52a97
__Before:__
__After:__
[PURCHASE-2004]: https://artsyproduct.atlassian.net/browse/PURCHASE-2004
> Layout breaks on tablet devices

- package.json
This is just a temporary band-aid that will allow the jest test to pass
in CI for now. Eventually the leak needs to be fixed as it will get
worse for each test suite that is added.
> Increase Jest Memory

- src/desktop/apps/consign/client/actions.js
Depends on https://github.com/artsy/gravity/pull/13258
Completes https://artsyproduct.atlassian.net/browse/CSGN-213
Updates consignment flow to only return artists where `target_supply=true`. 
Once this is merged will then un-`x` integrity specs.
> [Consignments] Only query for target_supply artists

- src/v2/Apps/Conversation/Components/Conversations.tsx
- src/v2/Apps/Conversation/Routes/Conversation/index.tsx
Addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-2016
Adjusts some breakpoints to make sure conversations list is displayed with the correct width
Hides overflow-x scroll on conversations list
Thanks Christina for the pair sesh!!
---
Inbox header and conversations list are not aligned, message view is over expanded
<br>
<br>
---
**Large screens**
1. Ensure width of conversations list aligns with header width
<br>
<br>
**Small/tablet screens**
1. Ensure width of conversations list equals width of message view
2. Ensure correct header component is displayed
<br>
<br>
**x-small screens**
1. Ensure width of conversations list equals 100% of screen
2. Ensure correct header component is displayed
<br>
<br>
> [PURCHASE-2016] Ensure Conversations list is the correct width for all screen sizes

- src/v2/Apps/Conversation/ConversationApp.tsx
- src/v2/Apps/Conversation/__tests__/ConversationApp.jest.tsx
The conversations app was failing at initial load because we still not getting the `conversationsConnection`.
Co-authored by: Sepand Ansari <sepans@sepans.com>
> fixed crash on CoversationApp on iniial load

- src/v2/Components/NavBar/NavBar.tsx
This just fixes a simple bug I noticed that prevented one from navigating the mobile subnavs. Just wanted to quickly cherry-pick this fix off my working branch.
> Fixes erroneous tap to close on MobileNav

- src/v2/Apps/Conversation/Components/Message.tsx
Addresses: [PURCHASE-2014](https://artsyproduct.atlassian.net/browse/PURCHASE-2014)
This PR addresses the issue of distorted images when multiple image attachments are sent. I initially pursued a [fix](https://github.com/artsy/force/compare/attachment-image-width?expand=1) where we fetched the image width as it was loading, but after doing a little more digging I noticed that really all we needed was to include the height as a prop to the `<Image>` component.
__Before:__
__After:__
> [PURCHASE-2014] add height value for Image component

- package.json
- src/v2/jest.envSetup.ts
Force garbage collection every ~30 seconds or so. This increases the 
runtime of the tests slightly, however, keeps the memory usage well below
the limit at which the process is OOM killed.
This is a better band-aid until we can identify the memory leak. With this change
the heap after finishing all the tests is ~1450 MB.
> Jest Force Garbage Collection

- hokusai/production.yml
Memory usage is always around 1.6GB per pod so the current value seems acceptable.
Very small tweak to CPU request to reflect that usage tends to average between 0.6 and 0.8 depending on the week.
https://artsyproduct.atlassian.net/browse/PLATFORM-2644
> Tweak CPU request to match recent usage

- src/v2/Components/NavBar/Menus/MobileNavMenu/InboxNotificationCount.tsx
- src/v2/Components/NavBar/NavBar.tsx
Addresses: [PURCHASE-2001](https://artsyproduct.atlassian.net/browse/PURCHASE-2001)
Paired with @lilyfromseattle & @zephraph 
__Context:__
When a user clicks the inbox link within the mobile nav menu, the mobile nav drop down doesn't get closed. We attempted to fix this in https://github.com/artsy/force/pull/5925 but that introduced other issues (erroneous taps closed MobileNav unintentionally). The broken inbox link was re-introduced in the fix to address the erroneous taps bug https://github.com/artsy/force/pull/5947.
__Issue:__
The current implementation doesn't account for nested elements as children in `MobileLink`. In the case of nested element passed to `MobileLink` the `parentNode` isn't an anchor element and is a flexbox div instead. As a result `toggleMobileNav(false)` doesn't …
> [PURCHASE-2001] Fix inbox nav

- src/v2/Apps/Conversation/Components/Details.tsx
- src/v2/Apps/Conversation/Routes/Conversation/index.tsx
- src/v2/Apps/Conversation/routes.tsx
This PR resolves: **[[PURCHASE-2005](https://artsyproduct.atlassian.net/browse/PURCHASE-2005)]**
- Details panel should remain open when switching between conversations
- Hide Details panel on user screen resize for small screens
> [PURCHASE-2005] Fix issue with details panel

- src/v2/Apps/Conversation/Components/Conversation.tsx
- src/v2/Apps/Conversation/Components/Conversations.tsx
- src/v2/Apps/Conversation/Components/InboxHeaders.tsx
- src/v2/Apps/Conversation/ConversationApp.tsx
- src/v2/Apps/Conversation/Routes/Conversation/index.tsx
Adjust break points for tablet experience
We want tablet to display the same experience as mobile:
> [PURCHASE-2004] Adjust breakpoints for tablet experience

- src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
- src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesApp.jest.tsx
- src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
- src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
- src/v2/__generated__/ArtistSeriesHeader_artistSeries.graphql.ts
- src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/FX-2071
---
Users should see a representative image on an artist series to ground the artist series in a work and contextualize the page.
Add header image to artist series page.
This PR also does a light refactoring of our artist series test suite to (1) break up some overly long tests into smaller, more targeted tests and (2) to test the components we've created and not the underlying implementation.
<details>
<summary>L/XL</summary>
</details>
<details>
<summary>S/MD</summary>
</details>
<details>
<summary>XS (mobile)</summary>
</details>
> Add artist series header image

- src/v2/Apps/Artist/Components/ArtistMeta.tsx
- src/v2/Apps/Artist/Components/ArtistMetaCanonicalLink.tsx
- src/v2/Apps/Artist/Components/__tests__/ArtistMeta.jest.tsx
- src/v2/Apps/Artist/Components/__tests__/ArtistMetaCanonical.jest.tsx
- src/v2/Apps/Artist/__tests__/routes.jest.tsx
- src/v2/__generated__/ArtistMetaCanonicalLink_artist.graphql.ts
- src/v2/__generated__/ArtistMeta_artist.graphql.ts
- src/v2/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Re: [FX-2102](https://artsyproduct.atlassian.net/browse/FX-2102)
So the logic for this is basically copied out of the routes file and then the fragment exists to satisfy the typings of the two functions it's leaning on. To some extent I wonder if it makes sense to extract a `canonicalUrl` field into Metaphysics, but there's quite a few UI assumptions built into that function it seems, so I'm not sure which approach feels better.
> [FX-2102] Handles canonical link tags for artists without overview pages

- data/schema.graphql
- src/v2/Apps/Artwork/ArtworkApp.tsx
- src/v2/Apps/Artwork/Components/OtherWorks/ArtistSeriesArtworkRail.tsx
- src/v2/Apps/Artwork/Components/OtherWorks/index.tsx
- src/v2/Apps/Artwork/Components/__tests__/OtherWorks.jest.tsx
- src/v2/Apps/Artwork/routes.tsx
- src/v2/__generated__/ArtistSeriesArtworkRail_artwork.graphql.ts
- src/v2/__generated__/ArtworkApp_artwork.graphql.ts
- src/v2/__generated__/OtherWorks_artwork.graphql.ts
- src/v2/__generated__/routes_ArtworkQuery.graphql.ts
Looks like:
If the lab feature is enabled, the data is fetched and an artwork carousel is rendered above the artwork grid, in the 'Other works by this artist' section. 
Depends on https://github.com/artsy/metaphysics/pull/2551
> [Artwork] Show other works from the series, if lab feature is present

- src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
Followup from some comments on https://github.com/artsy/force/pull/5979.
- Use Palette's breakpoint definitions for consistency.
- Remove styled `Col` in favor of using `Box` nested inside of `Col` with the right styling.
> Artist series header image refactor

- src/v2/Apps/Conversation/Components/Details.tsx
- src/v2/Apps/Conversation/Components/Reply.tsx
This fixes three issues:
1. The submit button was floating outside the input (putting a height on the reply component fixed that)
2. Moved the details panel to be fixed on xs to avoid weird scrolling issues on iOS
3. Changed the reply comonent to be fixed on iOS to avoid more scrolling issues.
> Attach details panel and reply on mobile

- src/v2/Apps/Conversation/Components/Conversation.tsx
- src/v2/Apps/Conversation/Components/Reply.tsx
Okay, last few issues. 
Fixes:
<details>
<summary>Input overlapping last message on mobile</summary>
</details>
-  Input incorrectly positioned on ipad
> Ensure messages have space under input, fix input on ipad

- src/v2/Apps/ArtistSeries/ArtistSeriesApp.tsx
- src/v2/Apps/ArtistSeries/Components/OtherArtistSeries/ArtistSeriesItem.tsx
- src/v2/Apps/ArtistSeries/Components/OtherArtistSeries/ArtistSeriesRail.tsx
- src/v2/Apps/ArtistSeries/Components/OtherArtistSeries/index.tsx
- src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesApp.jest.tsx
- src/v2/__generated__/ArtistSeriesApp_Query.graphql.ts
- src/v2/__generated__/ArtistSeriesApp_UnfoundTest_Query.graphql.ts
- src/v2/__generated__/ArtistSeriesApp_artistSeries.graphql.ts
- src/v2/__generated__/ArtistSeriesItem_artistSeries.graphql.ts
- src/v2/__generated__/ArtistSeriesRail_artist.graphql.ts
- src/v2/__generated__/OtherArtistSeriesQuery.graphql.ts
- src/v2/__generated__/routes_ArtistSeriesQuery.graphql.ts
Looks like:
Relatively straightforward. I added the usual fragment container, but also included a query renderer (in case we wanted to skip SSR). For the collections on the artist page, we already intentionally defer those client-side (expensive ES-backed queries).
However, for this rail, even on the artist page, we probably don't need that, but left the renderer in just in case.
> @sweir27 => [ArtistSeries] Add other series rail to page

- src/v2/Apps/Collect/Routes/Collection/Components/Header/DefaultHeader.tsx
Minor bug stemming from https://github.com/artsy/palette/pull/716
Previously the entire layout at large had an `overflow: hidden` set on it by default. Here we just set it on the relevant component.
> Prevents collection rail from overflowing

- src/v2/Apps/ViewingRoom/Components/ViewingRoomsFeaturedRail.tsx
- src/v2/Apps/ViewingRoom/Components/ViewingRoomsLatestGrid.tsx
- src/v2/Apps/ViewingRoom/__tests__/ViewingRoomsApp.jest.tsx
- src/v2/__generated__/ViewingRoomsApp_Test_Query.graphql.ts
- src/v2/__generated__/ViewingRoomsFeaturedRail_featuredViewingRooms.graphql.ts
- src/v2/__generated__/ViewingRoomsLatestGrid_ViewingRoomsAppQuery.graphql.ts
- src/v2/__generated__/ViewingRoomsLatestGrid_viewingRooms.graphql.ts
- src/v2/__generated__/routes_ViewingRoomsAppQuery.graphql.ts
I think this address the usage in `/viewing-rooms`. Still need to do the same for `viewing-room/id` but I'll do it in a separate PR. Want to verify this is working as expected first.
Thanks @dblandin, @mdole for all the work that went into making this possible.
jira: https://artsyproduct.atlassian.net/browse/GALL-3113
> Use image instead of hero_image_url for ViewingRoomsApp

- src/desktop/apps/artsy-v2/server.tsx
- src/v2/Apps/Artist/__tests__/routes.jest.tsx
- src/v2/Apps/Artist/routes.tsx
- src/v2/Artsy/Router/PermanentRedirectException.tsx
- src/v2/Artsy/Router/buildServerApp.tsx
[Re: FX-2103](https://artsyproduct.atlassian.net/browse/FX-2103)
So interestingly, while you can [tack a status code on to your error in found](https://github.com/4Catalyzer/found/blob/42b4944216654b0cad231caccd16f715dca987a6/src/server.js#L87), if that error is a redirect, [it ignores the status.](https://github.com/4Catalyzer/found/blob/42b4944216654b0cad231caccd16f715dca987a6/src/server.js#L69-L77)
I'm not familiar (at all) with found, but this seems like something worth PRing?
In any event, here we create a new exception specifically for permanent redirects and then handle it with the appropriate status code.
> [FX-2103] Supports permanent redirects for artist page

- src/desktop/apps/fair/index.coffee
- src/desktop/apps/fair/routes.coffee
- src/desktop/apps/fair/test/routes.test.coffee
- src/desktop/components/filter2/dropdown/template.jade
Fixes [PURCHASE-2019](https://artsyproduct.atlassian.net/browse/PURCHASE-2019)
Deepcrawl noticed we have incorrect URLs in the fair page affecting our SEO.
Looking at the [code](https://github.com/artsy/force/blob/85f4d423a6f966b6edd82335891b0662220559ab/src/desktop/components/filter2/dropdown/view.coffee#L35) those URLs are not being used for navigation but there is a backbone `onSelect` event that updates the filters so that URL was wrong since it was added 5 years ago.
I looked to see if there are any other usages of that filter and didn't find any to make sure this change doesn't create new malformed URLs.
Also added a redirect for `artworks/artworks` links as per Jira ticket to properly redirect search engine cached URLs
The redirect spec doesn't check the pattern matching but that's …
> Fix malformed drop down links and redirect them to correct one (for SEO)

- src/desktop/assets/analytics.ts
- src/typings/global.d.ts
Follow up to https://github.com/artsy/force/pull/6006, uses `window.analytics` over `analytics` for `identify` events, and adds identify to new logging. 
Related to https://artsyproduct.atlassian.net/browse/PLATFORM-2282
> Log identify calls

- src/desktop/apps/fair_info/templates/visitors.jade
- src/desktop/apps/fair_organizer/templates/overview.jade
- src/desktop/apps/fairs/templates/current_fairs.jade
- src/desktop/apps/how_auctions_work/test/fixture.json
- src/desktop/apps/press/test/fixtures/press_releases.json
- src/mobile/apps/how_auctions_work/fixtures/data.json
Re: [FX-1840](https://artsyproduct.atlassian.net/browse/FX-1840)
Replaces the iphone.artsy.net URLs as well as some itunes URLs (which work fine, they just redirect, but why not).
For that iphone.artsy.net app: I think we should be able to use [Cloudflare page rules](https://support.cloudflare.com/hc/en-us/articles/200172286-Configuring-URL-forwarding-or-redirects-with-Cloudflare-Page-Rules) to just 301 the whole thing? It looks like it's an app on Heroku — but the nameservers that's resolving that subdomain aren't on Cloudflare for some reason.
> [FX-1840] Bulk replaces iphone.artsy.net and old itunes URLs

- src/desktop/assets/analytics.ts
Explicitly use `window.analytics` in `assets/analytics`
Related conversation: https://artsy.slack.com/archives/C02BC3HEJ/p1596460574246500
> Always use window.analytics

- src/v2/Apps/Search/Components/NavigationTabs.tsx
- src/v2/Apps/Search/routes.tsx
If the artist series data is included in search results (which is determined wholly by the gravity feature flag), then it will correctly render:
(The description, and proper image fallback should also appear shortly once gravity is deployed and artist series re-indexed).
> @sweir27 => [Search] Show artist series in search

- package.json
- src/v2/Apps/Feature/Components/FeatureFeaturedLink.tsx
- src/v2/Apps/Feature/Components/FeatureHeader.tsx
- src/v2/Apps/Feature/Components/FeatureSet.tsx
- src/v2/Apps/Feature/FeatureApp.tsx
- yarn.lock
Addresses the breaking change in https://github.com/artsy/palette/pull/751
Worked with @nicoleyeo on the mapping over the typography changes.
> Moves to new typography on Feature pages

- src/lib/metaphysics2.coffee
Description
Is certain circumstances such as timeouts `superagent` will throw an
exception that does not contain a `response` or `text`. In these cases
`force` will crash when it attempts to `JSON.stingify` a null value.
Solution
Verify that there is a 'response' and a 'text' field before parsing them.
> Handle Superagent Errors

- src/lib/metaphysics2.coffee
Description
When testing in development the `err.response.text` was not always valid 
JSON. e.g. It could also be an HTML 404 or 500 page. 
Solution
Add an additional safety check to handle any cases where the error was 
not JSON but instead was HTML
> Text Not Guaranteed to be JSON

- src/v2/Artsy/Router/RouterLink.tsx
- src/v2/Utils/get.ts
Throwing an exception is a really expensive operation as it must walk
the call stack to generate a stack trace. This should be done with care
and only when necessary.
This minor tweak increases performance slightly by only throwing when
necessary and updating the route link matching to handle nulls instead
of relying on throwing an exception to default.
The percentages in this case are a bit misleading due to the idle time 
during the testing. The main take away is that `RouteLink.tsx` is no longer
utilizing a significant amount of time.
> Throw less Exceptions in the Router

- src/v2/Apps/Feature/Components/FeatureSet/FeatureSetMeta.tsx
Re: [FX-2148](https://artsyproduct.atlassian.net/browse/FX-2148)
Quick/easy one, adjustments to the set titles to line up with the [Figma spec](https://www.figma.com/file/3VpNrlYhYXuSvI2xzqfVZT/Campaign_Feature-Page?node-id=947%3A2353)
> [FX-2148] Adjusts title typography and spacing

- src/v2/Apps/ArtistSeries/ArtistSeriesApp.tsx
- src/v2/Apps/Artwork/Components/OtherWorks/index.tsx
- src/v2/Components/ArtistSeriesRail/ArtistSeriesRail.tsx
https://artsyproduct.atlassian.net/browse/FX-2127
The `ArtistSeriesRail` — which shows artist series associated with a given artist — currently always shows a title of "More series by this artist". But we want to be able to choose a different display title depending on the context.
- Make the display title configurable with an optional `title` prop
- Fall back to a reasonable default if `title` is not supplied. 
It seemed natural to me for the vanilla phrase "Artist Series" (spec'd in this ticket) to be the default title, and for other instances to supply a more specific title depending on the use case, so that's how this PR looks.
---
---
<details>
<summary>
<b>Other usages</b>
</summary>
**On the Artist Series page, retains the old title:**
**On the Artwork page, retains the old …
> [FX-2127] Make the display title of ArtistSeriesRail configurable

- src/typings/sharify.d.ts
- src/v2/Apps/Order/Components/PaymentPicker.tsx
- src/v2/Apps/Order/Components/__tests__/PaymentPicker.jest.tsx
- src/v2/Artsy/Router/__tests__/buildClientApp.jest.tsx
- src/v2/Artsy/Router/__tests__/buildServerApp.jest.tsx
- src/v2/Artsy/SystemContext.tsx
- src/v2/Artsy/__tests__/SystemContext.jest.tsx
- src/v2/__generated__/PaymentPickerEigenTestQuery.graphql.ts
This PR resolves **[[MX-464](https://artsyproduct.atlassian.net/browse/MX-427)]**
For the BNMO flows on iOS, the Manage cards link should be hidden when rendered within the Eigen modal.
> [MX-464] Hide manage cards on Eigen

- src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
- src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
- src/v2/Components/Authentication/Desktop/ModalManager.tsx
- src/v2/Components/Authentication/Types.ts
- src/v2/Components/Modal/Modal.tsx
- src/v2/Components/Modal/ModalWrapper.tsx
- src/v2/Components/Modal/__tests__/Modal.jest.tsx
- src/v2/Components/Modal/__tests__/ModalWrapper.jest.tsx
This PR prevents users from closing the sign-up modal that appears on a viewing room page without signing up for an account. It disables the ability for them to click outside of the modal to close it, and if a user either (1) clicks the X icon to close it, or (2) presses the Esc key, they are redirected back to the previous page.
> Prevent unauthenticated users from seeing a viewing room without signing up for an account (GALL-3186)

- src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
Small text alignment fix on VR titles reported in [GALL-3204](https://artsyproduct.atlassian.net/browse/GALL-3204):
**After:**
**Before:**
> Center Align Viewing Room Title Text

- src/v2/Components/Footer.tsx
Quick little thing — updates footer to utilize new typography & serif => sans.
Just bring it inline with [this figma spec](https://www.figma.com/file/LKKhtse11fjmdFI6AaVqGM/Palette-%5BWIP%5D?node-id=1590%3A2142). The contact forms on the right-hand side aren't in this footer so I just left them out — the intent here was just to give the type a facelift. @nicoleyeo gives the 👍
> Updates Footer typography

- src/v2/Apps/ViewingRoom/Components/ViewingRoomsLatestGrid.tsx
- src/v2/Artsy/Router/RouterLink.tsx
Addresses [GALL-3205 Landing page: Clicking "View More" loads more rooms above the button](https://artsyproduct.atlassian.net/browse/GALL-3205)
When a user clicks View More to load the next set of viewing rooms, the top of the newly loaded list of VRs should be in view so they needn't scroll up after.
> GALL-3205--Clicking "View More" Bug Fix

- webpack/plugins/bundleAnalyzer.js
Description
Changes the default settings for `webpack-bundle-analyzer` to display
the gzipped size and render a static page instead of running a
web server. The main reason for disabling the web server is that it makes 
it difficult to compare multiple branches because of port conflicts.
> Webpack Analyzer Defaults

- src/v2/Artsy/Router/RouterLink.tsx
- src/v2/Components/NavBar/NavItem.tsx
Minor: was trying out [this extension from Microsoft](https://accessibilityinsights.io/docs/en/web/overview) (recommended!) and it caught this: we're laying an unfocusable anchor tag over the dropdown items so that we can have the keypress handler open the submenu and any mouse click go to the href — since if you're using a pointing device, the submenu will open on hover.
Adding `role="presentation"` overwrites the semantics of the given element and ensures it's ignored (it wasn't focusable anyway so I don't believe this was an actual issue but dotting the i here).
> Adds role="presentation" to unfocusable anchors

- docs/creating_review_app.md
- package.json
Update docs on deleting a review app.
> [Docs] Update review app docs

- src/v2/Apps/Fair/Components/FairHeader.tsx
- src/v2/Apps/Fair/Components/__tests__/FairHeader.jest.tsx
- src/v2/Apps/Fair/FairApp.tsx
- src/v2/Apps/Fair/Routes/FairInfo.tsx
- src/v2/Apps/Fair/Routes/FairOverview.tsx
- src/v2/Apps/Fair/Routes/__tests__/FairInfo.jest.tsx
- src/v2/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx
- src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
- src/v2/Apps/Fair/routes.tsx
- src/v2/Components/Links/BackLink.tsx
- src/v2/Components/Links/ForwardLink.tsx
- src/v2/Components/Links/StyledLink.tsx
- src/v2/__generated__/FairApp_Query.graphql.ts
- src/v2/__generated__/FairApp_fair.graphql.ts
- src/v2/__generated__/FairHeader_Query.graphql.ts
- src/v2/__generated__/FairHeader_fair.graphql.ts
- src/v2/__generated__/FairInfo_Query.graphql.ts
- src/v2/__generated__/FairInfo_fair.graphql.ts
- src/v2/__generated__/FairOverview_Query.graphql.ts
- src/v2/__generated__/FairOverview_fair.graphql.ts
- src/v2/__generated__/routes_FairInfoQuery.graphql.ts
- src/v2/__generated__/routes_FairOverviewQuery.graphql.ts
- src/v2/__generated__/routes_FairQuery.graphql.ts
Addresses https://artsyproduct.atlassian.net/browse/FX-2168 and https://artsyproduct.atlassian.net/browse/FX-2170
This PR adds:
- A more filled-out `FairHeader` with the correct image.
- A "More info" link and corresponding page.
- Explicitly adds a `FairOverview` route in anticipation of needing a `FairArtworks` route in the future.
- A metaphysics PR to add `summary`, `tickets`, and `contact` to `FairType` and allow `hours` and `links` to be formatted into HTML.
- A force PR to address ☝️ .
> Adds fair header and more info page

- src/v2/Apps/Fair/Components/FairHeader.tsx
- src/v2/Apps/Fair/Components/__tests__/FairHeader.jest.tsx
- src/v2/Apps/Fair/Routes/FairInfo.tsx
- src/v2/Apps/Fair/Routes/__tests__/FairInfo.jest.tsx
- src/v2/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx
- src/v2/__generated__/FairHeader_Query.graphql.ts
- src/v2/__generated__/FairHeader_fair.graphql.ts
- src/v2/__generated__/FairInfo_Query.graphql.ts
- src/v2/__generated__/FairInfo_fair.graphql.ts
- src/v2/__generated__/FairOverview_Query.graphql.ts
- src/v2/__generated__/routes_FairInfoQuery.graphql.ts
- src/v2/__generated__/routes_FairOverviewQuery.graphql.ts
A follow-up to https://github.com/artsy/force/pull/6119 now that the necessary metaphysics changes are merged + deployed.
This addresses:
- Makes markdown-able fields render as proper HTML
- Shows the `summary` in the header and falls back to the `about` text.
> Adds missing fields to fair info page

- src/v2/Apps/ArtistSeries/ArtistSeriesApp.tsx
- src/v2/Apps/Collect/Routes/Collection/index.tsx
This is a hotfix for an issue that was identified here: https://artsy.slack.com/archives/CP9P4KR35/p1597859227496900
If a user searches for a collection or series, clicks it, and then searches or clicks another series or collection we encounter a race condition inside of our flickity carousel at the bottom of the page. 
I've seen this error in the past, and it manifests in somewhat unexpected ways, and is related to a race condition where the dom nodes managed by flickity -- which is a jquery library -- make a change to the DOM outside of the react lifecycle leadin to this error. It tends to happen on route transition, but i've seen it happen in other contexts as well (such as within tab components). 
```
reaction | Error: Failed to execute 'removeChild' on 'Node': The node to be removed …
```
> [Hotfix] Lazyload bottom carousel rails 

- .eslintrc.js
- package.json
- yarn.lock
Re: [FX-2141](https://artsyproduct.atlassian.net/browse/FX-2141)
I'd like to install a set of linting rules to pick up some basic problems which seem pretty pervasive throughout the site. Hopefully we can lean on the linting to guide developers into building more accessible components.
So we can't use [eslint-plugin-jsx-a11y](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/466) because of styled-components.  [However eslint-plugin-styled-components-a11y](https://github.com/brendanmorrell/eslint-plugin-styled-components-a11y) exists and seems to work pretty alright!
Running this against `src` comes up with 82 errors (I think only so few because of the palette components not being checked, see below) — mostly misuse of onClick handlers.
----
I might have to turn some rules to …
> [FX-2141] Installs and configures eslint-plugin-styled-components-a11y

- src/v2/Apps/ViewingRoom/Components/ViewingRoomCarousel.tsx
This is a fix to the bug reported in [GALL-3046](https://artsyproduct.atlassian.net/browse/GALL-3046) where the carousel's arrow containing div obfuscated the selected VR card and required 2 clicks to begin bringing images into the center of the carousel.
> Group images in VR featured carousel to fit 50% of viewport

- src/v2/Apps/ViewingRoom/ViewingRoomsApp.tsx
Companion PR to https://github.com/artsy/integrity/pull/176/files#diff-32758bee56d9b6d4947129eacef004bdR6, adds `h1` element for page title on `/viewing-rooms`
> [SEO] Use h1 for viewing rooms page title

- src/v2/Apps/Conversation/Components/Conversation.tsx
Quick follow-up for https://github.com/artsy/force/pull/6135
I mostly did QA on long conversations so missed this bug.
without `flex-grow` the conversation box doesn't fill the width/height
Before:
After:
> Fix conversation layout when thread is short

- src/v2/Apps/Conversation/Components/Reply.tsx
Fixes [PURCHASE-2031](https://artsyproduct.atlassian.net/browse/PURCHASE-2031)
For some reason, the `div`s enclosing `textArea`  (green and red borders in the screenshot) were not expanding with text area (blue border). Adding `flex-shrink: 0` magically fixed that.
Before:
After:
> [PURCHASE-2031] Fix Safari/Firefox reply box cutoff issue

- src/mobile/apps/partner_profile/client/articles.coffee
- src/mobile/apps/profile/client.coffee
The `src/mobile/assets/mobile_all.ts` includes a fuzzy match at the end loads up many partner client files: https://github.com/artsy/force/blob/master/src/mobile/assets/mobile_all.ts#L67. 
This match causes partner client files to be loaded in addition to expected assets on the `/art-fairs` page. However, the files were erroring because a `sharify` require was missing, and `sd.PROFILE` doesn't exist on non-profile pages. This caused the `art-fairs` client js not to execute. 
I haven't changed the matching because i'm not sure why it is there, but I've fixed the bugs so JS loads when the files are included on unrealted pages.
> Check if sd.PROFILE exists to avoid undefined error

- src/desktop/apps/artsy-v2/apps/collection/__tests__/collectionMiddleware.jest.ts
- src/desktop/apps/artsy-v2/apps/collection/collectionMiddleware.ts
- src/v2/Apps/Search/Components/NavigationTabs.tsx
Not sure how I missed these!
In any case, this removes the lab feature check from the router (so that we'll correctly route from the soon-to-be-deprecated collections) _and_ from the search results page.
> Removes last couple of instances of lab feature

- src/desktop/apps/articles/queries/editorial_articles.coffee
- src/desktop/apps/articles/routes.ts
- src/desktop/apps/articles/test/routes.test.js
- src/desktop/components/articles_feed/templates/button.jade
- src/desktop/components/articles_feed/test/view.test.js
- src/desktop/components/articles_feed/view.coffee
https://artsyproduct.atlassian.net/browse/FX-2235
Search engine crawlers may have difficulty browsing through the articles feed on `/articles` since fetching more articles requires JavaScript.
Modify the "More Articles" button to link directly to the next page of article results when JavaScript is disabled.
> Articles feed is browsable without JavaScript

- src/desktop/apps/authentication/components/meta.tsx
- src/desktop/apps/fairs/templates/promo.jade
- src/desktop/components/auction_lots/templates/_detail.jade
- src/desktop/components/auction_lots/templates/auction_lots_table.jade
- src/desktop/components/fair_layout/templates/user.jade
- src/desktop/components/inquiry_questionnaire/templates/account/login.jade
- src/desktop/components/main_layout/footer/mobile_footer_menu.jade
- src/mobile/apps/art_fairs/templates/index.jade
- src/mobile/apps/auctions/templates/index.jade
- src/mobile/apps/how_auctions_work/templates/learn_more.jade
- src/mobile/components/layout/templates/login-signup.jade
- src/v2/Components/Authentication/commonElements.tsx
Fixes [PURCHASE-2080](https://artsyproduct.atlassian.net/browse/PURCHASE-2080).
There are ultimately two parts to the above ticket that we really want to accomplish:
1. Avoid indexing `/sign_up` & `/log_in` pages, including query parameterized variations of the page
2. Reduce our crawl budget burn by ensure the pages aren't followed to by the crawler
The first one was easiest to fix codewise, but it took me a while to figure out the right thing to do. I implemented a robots meta tag with content `none`. This means that crawlers shouldn't index the page _nor_ should it try to follow any of the URLs on the page. Straight forward enough. There was a recommendation to add a self referring canonical to avoid the query parameterization indexes of the page, but given that the robots meta tag is …
> No crawl login

- src/desktop/components/article/client/super_article.coffee
`this.$(...).waypoint is not a function` on "super articles" which require the use of the jQuery Waypoints plugin.
This fixes the immediate problem but, for whatever reason, the `globalClientSetup` (which requires all the jQuery plugins) is happening after these articles get initialized. Which *is* worrying — any ideas @damassi or @zephraph or @eessex?
> Hacks around race condition in setup for "super_article"

- docs/creating_review_app.md
- hokusai/production.yml
- hokusai/staging.yml
- scripts/build_review_app.sh
Addresses:
https://artsyproduct.atlassian.net/browse/PLATFORM-2595
https://artsyproduct.atlassian.net/browse/PLATFORM-2753
- Add ingress and clusterIP resources to k8s specs.
- Update `build_review_app.sh` to work with ingress.
- Major update to review app doc.
In regards to ingress migration, please see https://www.notion.so/artsy/Nginx-Ingress-Controllers-4b5d937f0acd480f938c34ef1509d3c4 and the section `Migrating an application from an external LoadBalancer-fronted service to an Ingress-fronted service`.
DNS will be migrated under this PR: https://github.com/artsy/infrastructure/pull/245
After DNS migration, another PR will be opened to clean up sidecar nginx and loadbalancer service.
> Add ingress and update review app steps to work with Ingress.

- src/v2/Apps/Fair/Routes/FairArtworks.tsx
- src/v2/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
- src/v2/Apps/Fair/routes.tsx
- src/v2/Components/v2/ArtworkFilter/index.tsx
- src/v2/__generated__/FairArtworksQuery.graphql.ts
- src/v2/__generated__/FairArtworks_Query.graphql.ts
- src/v2/__generated__/FairArtworks_fair.graphql.ts
Pretty simple! Just our standard drop-in and component.
One follow-up:
Search results:
Notice the ugly double-separator in both? There's the separator for the tabs, but also a top separator for the filter.
That's actually tricky to remove, there's at least one place in the base filter component within Force which probably needs a prop like `hideSeparator` or something, to hide the one above the grid. Additionally, the separator on the left hand side above the medium filter actually comes from Palette (the `Toggle` component there hard-codes one. That component also needs a `hideSeparator` prop?). Minor nit- these are the kinds of little changes that are actually bothersome to make with all these shared components + Palette!
> @sweir27 => [Fair] Implement filter on artworks tab

- hokusai/staging.yml
Addresses: https://artsyproduct.atlassian.net/browse/PLATFORM-2595
Follow up to: https://github.com/artsy/force/pull/6234
Staging was migrated to ingress. This PR cleans up staging.
Normally, we submit one clean-up PR for both prod and staging. In this case, prod has yet to be migrated to ingress, and I would like to clean up staging right away, because the presence of sidecar nginx prevents review app pods from launching, and that is b/c in the previous PR, I removed nginx steps in review app build script (in anticipation of moving to ingress).
> Staging clean up after ingress migration.

- src/v2/Apps/Fair/Routes/FairArtworks.tsx
- src/v2/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
- src/v2/Apps/Fair/routes.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/FollowedArtistsFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/FollowedArtistsFilter.jest.tsx
- src/v2/Components/v2/ArtworkFilter/index.tsx
- src/v2/__generated__/FairArtworksQuery.graphql.ts
- src/v2/__generated__/FairArtworks_Query.graphql.ts
- src/v2/__generated__/FairArtworks_fair.graphql.ts
- src/v2/__generated__/routes_FairArtworksQuery.graphql.ts
Looks like:
Works as expected!
For now, I limited this to just the fair page filter. It should be pretty easy to expose it on the other places where the filter is used (need to thread all the variables through- might be some opportunity for consolidation there).
> @sweir27 => [Filter] Add artists I follow filter on fair page

- src/v2/Apps/Search/routes.tsx
- src/v2/__generated__/routes_SearchResultsArtistsQuery.graphql.ts
- src/v2/__generated__/routes_SearchResultsEntityQuery.graphql.ts
- src/v2/__generated__/routes_SearchResultsTopLevelQuery.graphql.ts
Kind of a weird one! Adds a `toString` onto the `keyword` and switches the queries to use it (over `term`, which is just included from the query params).
> @anandaroop => [Search] Use toString on search term, to avoid GraphQL type crash on term

- src/desktop/apps/artists/test/template.test.js
- src/desktop/apps/fair_organizer/test/template.test.js
- src/desktop/components/main_layout/templates/head.jade
Description
Add preload tags to download the most used fonts sooner. This approach
provides better rendering performance when used in combination with the
@font-face tags already in place.
A slightly more complex approach that I would like to trial in the future is [Critical Font with Preload](https://www.zachleat.com/web/comprehensive-webfonts/#critical-foft-with-preload)
> Preload Most Used Fonts

- src/lib/__tests__/cache.jest.ts
- src/lib/cache.js
Description
The cache clear method currently fails due to an improperly scoped
variable reference. This corrects that mistake.
> (fix) Cache Clear Method

- .eslintrc.js
- eslint/artsyPaletteCanonicalImport.js
- package.json
Description
This change adds a lint rule to detect when components are imported 
from `@artsy/palette`. The rule also has the ability to automatically fix
any import violations.
> Add lint rule to detect '@artsy/palette' usage.

- .env.oss
- src/desktop/config.coffee
- src/lib/__tests__/setup.jest.js
- src/lib/setup.js
https://artsy.slack.com/archives/CP9P4KR35/p1591794809087900
artsy-xapp and artsy-passport both respect implicit `ARTSY_ID/SECRET` from environment variables and support explicit configuration. However, Force currently maintains 2 sets of environment variables (with the same values):
- `CLIENT_ID/SECRET` for [explicitly configuring](https://github.com/artsy/force/blob/5ecb9acc1777e4a077565946783077299cacd931/src/index.js#L124) artsy-xapp, and
- `ARTSY_ID/SECRET` for [implicitly configuring](https://github.com/artsy/force/blob/b607b3b2bd9459981203c879ae3b3a3b04e9e587/src/lib/setup.js#L154-L172) artsy-passport.
This consolidates them and only uses `CLIENT_ID/SECRET` to explicitly configure both dependencies. We can then clean up the `ARTSY_ID/SECRET` from the environment variables.
I choose …
> Consolidate CLIENT_ID/SECRET and ARTSY_ID/SECRET #migration

- src/desktop/components/jump/test/view.test.js
- src/desktop/components/jump/view.coffee
- src/desktop/components/user_interests/test/view.test.js
- src/desktop/components/user_interests/view.coffee
The master builds have been [failing](https://app.circleci.com/pipelines/github/artsy/force/9045/workflows/0328659a-13d2-421b-8d8f-766d053344a9/jobs/62393) with a few errors:
```
TypeError: Cannot read property 'track' of undefined
```
It's likely due to the change in https://github.com/artsy/force/pull/6227 (https://github.com/artsy/force/pull/6249/commits/cafff1a63b61bafddf649380234ad004716f535b). This fixes it by mocking it in tests.
> Fix undefined track function in mocha tests

- src/v2/Apps/Artist/Components/ArtistHeader.tsx
- src/v2/Apps/Artist/Components/ArtistIndicator.tsx
Fixes:
I tried project searching around for some variations on this and I think this might be the only example. It might be worth looking around staging a bit though.
-----
I very much believe we should introduce aliases for the spacing scale keys that are string based: `"1x"`, `"2x"`, etc, which would be much less confusing to work with.
> Fixes pixel to spacing scale value conversion

- src/desktop/apps/home/templates/meta.jade
- src/desktop/apps/page/meta/default.jade
https://artsyproduct.atlassian.net/browse/FX-2236
Our current meta description on the homepage is too long and Google's crawlers do not read it, leading to bad SEO.
Shorten the meta description for our homepage.
> Update homepage meta description

- package.json
- src/desktop/apps/home/stylesheets/featured_items.styl
- src/desktop/lib/palette.styl
- yarn.lock
To support the [[Web] Type Clean-up](https://www.notion.so/artsy/Web-Type-Clean-up-94cae3cc227243e2a44128b315e65046) — I wanted to get this in before we started so we can hit the ground running on the legacy routes.
By importing the lib/palette.styl file you gain access to some mixins and functions.
`getFontFamily`, `getFontSize`, `getLineHeight`, `getLetterSpacing`, `getColor` all accept the token names and return back themed values. So:
```styl
color: getColor('black60') // => #666
background-color: getColor('purple100') // => #6e1eff
// etc...
``` 
The `text` mixin accepts [a variant name](https://palette.artsy.net/tokens/typography/) and mixes in the styles that comprise the treatment:
```styl
.Example
text('small')
```
Will yield:
```css
.Example {
font-family: "ll-unica77", …
```
> Stylus palette helpers to aid in typographic clean up

- src/desktop/apps/home/stylesheets/featured_items.styl
- src/lib/palette.styl
In our mob session to kick of the Web Type Cleanup project we noted that these new helpers should move up a level since they will be shared across desktop and mobile sub-apps.
cc @pepopowitz @zephraph @sweir27 @dzucconi
> refactor(type): Share palette helpers across desktop and mobile

- src/lib/palette.styl
Adds `getSpace`
It accepts any number of args so you can give it a single key:
```styl
margin-top getSpace(1) // margin-top: 10px;
```
or multiple
```styl
margin getSpace(1, 2) // margin: 10px 20px;
```
> Adds getSpace helper

- hokusai/production.yml
Follow up to: https://github.com/artsy/force/pull/6234
Clean up Prod after migration to ingress. (Staging was already cleaned.)
Have verified that sidecar nginx and `force-web` service are not getting any traffic.
Migration Steps
---
- Merge and deploy this PR.
- Delete `force-web` k8s service.
> #MIGRATION - Drop Prod loadbalancer service and sidecar nginx.

- src/desktop/apps/partner2/templates/meta.jade
- src/desktop/apps/partner2/test/templates.test.js
Addresses https://artsyproduct.atlassian.net/browse/PURCHASE-2083
This change will also adjust the canonical url for Partner Institutions as well
Eg
The collection tab for Partner Institution Madison Sq Park
https://staging.artsy.net/madisonsquarepark/collection
would have the canonical to the root slug of
https://staging.artsy.net/madisonsquarepark/
We are grabbing it from the Profile instance we have access too [here](https://github.com/artsy/force/blob/master/src/desktop/models/profile.coffee#L49)
Eg:
```
Profile {
cid: 'c92',
attributes: {
id: 'galerie-mirchandani-plus-steinruecke',
// more fields
```
Up next: edit the sitemap itself
> [PURCHASE-2083] Adjust canonical url for gallery pages to point to root gallery slug

- src/mobile/apps/art_fairs/index.styl
- src/mobile/apps/art_fairs/templates/index.jade
- src/mobile/apps/art_fairs/test/template.test.js
- src/mobile/components/layout/stylesheets/buttons.styl
Addresses: https://www.notion.so/artsy/Web-Type-Clean-up-94cae3cc227243e2a44128b315e65046?p=e07c745e0e7a453dad853dd540e1efdc
- Updates the typography on the **fairs landing page** on **mobile**
- Also makes a [global change](https://artsy.slack.com/archives/C9XJKPY9W/p1600274937047200) to Avant Garde button/tab styles
> chore(type): Update mobile fairs landing page typography

- cypress/integration/collect.spec.js
- src/test/acceptance/collect.js
- src/v2/Apps/Collect/Routes/Collect/index.tsx
- src/v2/Components/CollectionsHubsNav.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/FollowedArtistsFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/GalleryFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/InstitutionFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/OptionText.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
This started as a type conversion for the /collect page, and ballooned into several other pages. As I started converting artwork filter components, I decided I should do **all** of them instead of leaving half sans, half serif.
As a result, several pages were all affected by these changes.
All type on this page should now be using new variants. 
cc @mzikherman (because it looks like you've worked on this page pretty recently)
There are probably other places we have artwork filters, but all filters are accounted for in these three pages. 
If I'd only converted the type in radio buttons and checkboxes without making additional padding changes, text was pretty misaligned from the associated control. I added a smidge of top padding to each option to better center the option. I didn't notice …
> Type conversion: /collect page and all artwork filters

- src/desktop/apps/fairs/stylesheets/index.styl
- src/desktop/apps/fairs/templates/index.jade
- src/desktop/components/main_layout/stylesheets/buttons.styl
Addresses: https://www.notion.so/artsy/Web-Type-Clean-up-94cae3cc227243e2a44128b315e65046?p=eca675d56e3c43a3ae3c2d63b9417802
This updates the typography on the **fairs landing page** on **desktop**.
> chore(type): Update desktop fairs landing page typography

- src/desktop/apps/home/components/artists_to_follow/stylesheets/index.styl
- src/desktop/apps/home/components/followed_artists/index.styl
- src/desktop/apps/home/components/followed_artists/templates/context.jade
- src/desktop/apps/home/components/related_artists_context/annotation.jade
- src/desktop/apps/home/stylesheets/featured_items.styl
- src/desktop/apps/home/stylesheets/hero_units.styl
- src/desktop/apps/home/stylesheets/modules.styl
- src/desktop/apps/home/templates/hero_unit.jade
- src/desktop/components/artist_cell/index.styl
- src/desktop/components/artwork_brick_rail/index.styl
- src/desktop/components/artwork_brick_rail/templates/index.jade
- src/desktop/components/artwork_metadata_stub/index.styl
- src/desktop/components/featured_shows/index.styl
- src/desktop/components/follow_button/artist_suggestions.jade
- src/desktop/components/follow_button/index.styl
- src/desktop/components/main_layout/footer/index.styl
- src/desktop/components/main_layout/stylesheets/buttons.styl
- src/desktop/components/merry_go_round/index.styl
- src/desktop/components/recently_viewed_artworks/index.jade
- src/desktop/components/slider/index.jade
- src/lib/palette.styl
- src/v2/Components/CollectionsHubsHomepageNav.tsx
@deliciousnachos reviewed these screenshots ✅ 
[Click here for a giant scroll of <del>rails</del> shelves](https://static.damonzucconi.com/_capture/PSvjfwYkNSa5.png)
Logged out the only addition is this component:
----
I'm trying to replace tokens like `gray-lighter-color` and spacing with the equivalents as I come across them. They are close but slightly different. Not hugely important but it makes me *feel better*.
> [typography] Desktop homepage conversion

- cypress/integration/collect.spec.js
- src/test/acceptance/collect.js
- src/v2/Apps/Collect/Routes/Collect/index.tsx
As pointed out by @joeyAghion, the heading on the collect page likely lost some SEO strength when I updated it in #6287. This reverts the heading to what it was.
> Revert heading of collect page for SEO juiciness

- src/desktop/apps/auctions/stylesheets/index.styl
- src/desktop/apps/auctions/templates/index.jade
- src/desktop/apps/auctions/templates/placeholder.jade
- src/desktop/components/aggregate_page/index.styl
Addresses: https://www.notion.so/artsy/Web-Type-Clean-up-94cae3cc227243e2a44128b315e65046?p=a78db6c1d4e24a59b78a52b2c9f5a65a
Signed off by @deliciousnachos ✅ 
- Updates page title, auction list items, sidebar
- Updates a zero state that wasn't in the comp — see below
- Does _not_ update countdown clocks, per discussion this morning
- Converts colors and spaces to Palette helpers
See the first auction in the list for an example of the "live auction" label
When there are no current auctions, this header is displayed:
> [Typography] Update Auctions desktop landing page

- src/mobile/apps/art_fairs/templates/index.jade
- src/mobile/apps/art_fairs/test/template.test.js
https://github.com/artsy/force/pull/6283 included a copy change to the H1 on the mobile fairs landing page. It was changed to just "Fairs". 
This PR reverts to:
> Revert mobile fairs heading for SEO

- src/v2/Apps/Search/Components/SendFeedback.tsx
- src/v2/Apps/Search/Components/ZeroState.tsx
- src/v2/Apps/Search/SearchApp.tsx
Most of the type on this page was cleaned up by #6287. Included here are updates to the page heading and the "no search results" view.
> Typography cleanup: Search results page

- src/v2/Apps/Artist/Routes/Overview/__tests__/index.jest.tsx
- src/v2/Apps/Artist/Routes/Overview/index.tsx
- src/v2/Components/ArtistBio.tsx
- src/v2/Components/RecentlyViewed.tsx
Little bit out of scope but there was only a few things to convert. Any page we don't load Garamond on is 100kb of blocking data saved!
> [Typography] Converts artist page typography

- src/desktop/apps/auction/components/artwork_rail/ArtworkRail.styl
- src/desktop/apps/auction/components/layout/Banner.styl
- src/desktop/apps/auction/components/layout/active_bids/ActiveBidItem.styl
- src/desktop/apps/auction/components/layout/active_bids/MyActiveBids.styl
- src/desktop/apps/auction/components/layout/auction_info/AuctionInfo.styl
- src/desktop/apps/auction/components/layout/auction_info/Registration.styl
- src/desktop/apps/auctions/stylesheets/index.styl
- src/desktop/apps/fair/stylesheets/overview.styl
- src/desktop/apps/fair_organizer/stylesheets/index.styl
- src/desktop/components/add_to_calendar/index.coffee
- src/desktop/components/add_to_calendar/index.styl
- src/desktop/components/bid_status/index.styl
- src/desktop/components/chevron_list/index.styl
- src/desktop/components/clock/index.styl
- src/desktop/components/clock/view.coffee
- src/desktop/components/my_active_bids/index.styl
So this is primarily dealing with the desktop/mobile above the fold auction pages, but there's some bleed into a few global things.
* The add to calendar component, which was only also used on the fair events page — tested there and looks good.
* The clock component — this one I'm not 100% on all the actual active call sites. It appears that there's a different clock that's used, for instance, on artwork pages. If someone can point out other places the CoffeeScript version lives, I'd like to double check them.
* Active bids, which is used in the auctions index and shows up in settings, in addition to the actual auction pages
----
----
----
----
----
> [Typography] Converts auction pages (above the fold)

- src/v2/Apps/ViewingRoom/Components/ViewingRoomCarousel.tsx
- src/v2/Apps/ViewingRoom/Components/ViewingRoomsFeaturedRail.tsx
Introduce a new way of progressing the progress bar. Since the Featured Viewing Room rail has narrower cards, the way of incrementing the progress bar by flickity element doesn't work as well.
Do a bit of magic number math for the number of steps to progress, but it works. 🤷 
Also works with fewer Viewing Rooms in the Featured rail:
> GALL-3237 Fix VR featured rail progress bar

- src/v2/Components/NavBar/menuData.ts
Quick small fix for a faulty submenu href:
> fix: Correct a faulty href in submenu data

- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.jest.tsx
Now that artworks are re-indexed, we can expose this filter! The results are still messy, lots of free form text entry, etc.
But, maybe its fine? At the very least it's easy enough to hide, and it might serve to stimulate discussion around...possibly cleaning up or structuring the date fields and Volt inputs?
> @anandaroop => [Filter] Expose 18th Century & Earlier period filter

- src/v2/Apps/Search/Components/ZeroState.tsx
- src/v2/Apps/Search/SearchApp.tsx
- src/v2/Apps/Search/__tests__/SearchApp.jest.tsx
Based on feedback from @nicoleyeo, this PR makes a couple small changes to the search results page.
1. Change from title case to sentence case for results headline ("1001 Results" -> "1001 results")
2. Use left/right quotation marks instead of neutral ones.
This work will break integrity tests. [Here's a followup PR to fix them once this is merged](https://github.com/artsy/integrity/pull/186).
> Search results typography followup: minor changes

- src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
- src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
- src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
- src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
- src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
- src/v2/Apps/Collect/Routes/Collection/Components/Header/FeaturedArtists.tsx
- src/v2/Apps/Collect/Routes/Collection/Components/Header/index.tsx
- src/v2/Apps/Collect/Routes/Collections/Components/CollectionsGrid.tsx
- src/v2/Apps/Collect/Routes/Collections/index.tsx
Addresses: 
https://www.notion.so/artsy/Web-Type-Clean-up-94cae3cc227243e2a44128b315e65046?p=7739bd240e9f467ba4a6055ed5584245
- Collection page (desktop and mobile)
- Title
- Featured artist subheading
- Hub rails titles & cards
- Collections landing page (not really for humans, but still...)
- Title
- Section subheadings
> [Typography] Update responsive collection and collections landing pages

- .circleci/config.yml
These fail frequently for no discernible reason — if they are covered under Cypress then this is unnecessary 🤞
> Disables acceptance tests

- src/v2/Apps/Artwork/Components/ArtistInfo.tsx
- src/v2/Apps/Artwork/Components/ArtworkArtistSeries/ArtistSeriesArtworkRail.tsx
- src/v2/Apps/Artwork/Components/ArtworkBanner/Banner.tsx
- src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromArtsy.tsx
- src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
- src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
- src/v2/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
- src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkPopoutPanel.tsx
- src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
- src/v2/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarClassification.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarMetadata.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarSizeInfo.tsx
- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarTitleInfo.tsx
- src/v2/Apps/Artwork/Components/OtherWorks/Header.tsx
- src/v2/Apps/Artwork/Components/PricingContext.tsx
- src/v2/Apps/Artwork/Components/PricingContextModal.tsx
- src/v2/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
- src/v2/Apps/Artwork/Components/TrustSignals/TrustSignal.tsx
- src/v2/Apps/Artwork/Components/__tests__/OtherWorks.jest.tsx
This is _quite_ a significant change. Lots of text updates and lots of places that could possibly go wrong.
Most of this was straight conversion. I _did_ alter how h1's are rendered from the artist's name. Previously we had it where if there were multiple artists then there would be multiple h1's which is invalid from an SEO perspective.
There are also some accessibility lint rules that were failing around links that don't have hrefs but simply act as buttons. I disabled them for now, but I'd be open to fixing in this PR or a follow up. @dzucconi your thoughts would be welcome here.
Before:
After:
Before:
After:
Before:
After:
> Update artwork typography

- src/desktop/apps/press/test/util.test.js
- src/mobile/apps/fair_info/test/routes.test.js
The `fair_info` test was causing the majority of the mocha test failures
in CI, this appears to have been caused by a deferred that was not being
waited upon.
During testing, I found a second test that was flaky in rare cases where
it ran slow enough to cause a the Unix timestamp to become off by a few
ms.
This change fixes these two flaky tests and should help alleviate the
retries that have become necessary on CI.
> Fix Flaky Tests

- src/desktop/apps/partner2/test/index.test.js
During my testing, I found one additional test that was flapping. This
was caused by not properly awaiting the results from `supertest`. This
change also enables additional partner tests that were commented out
for being inconsistent in the past.
> Flapping Test

- src/mobile/components/layout/templates/head.jade
Mirrors the new behavior we just implemented for [Gallery pages on desktop](https://github.com/artsy/force/pull/6260/files). 
We want the same behavior applied on mobile screens.
Addresses https://artsyproduct.atlassian.net/browse/PURCHASE-2121
> [PURCHASE-2121] Point canonical to Gallery root url for mobile partner pages

- src/v2/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
- src/v2/Apps/Artwork/Components/ArtistInfo.tsx
- src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
- src/v2/Apps/Collect/Routes/Collection/Components/Header/index.tsx
Closes: [FX-2251](https://artsyproduct.atlassian.net/browse/FX-2251)
> [FX-2251] Utilizes `text` variant consistently across EntityHeaders

- src/desktop/apps/partner2/components/news/test/view.test.js
- src/desktop/apps/partner2/components/news/view.coffee
Currently, booths which are not yet "displayable" (have either been intentionally hidden or the fair hasn't opened yet) are visible in the "News" section on a gallery's profile page.
An example is [Goodman Gallery](https://staging.artsy.net/goodman-gallery):
This was reported in slack [here](https://artsy.slack.com/archives/C9SATFLUU/p1600787460073000).
Only fetch for shows which have `displayable: true`. This [follows the logic](https://github.com/artsy/force/blob/master/src/desktop/apps/partner2/client/overview_layout_factory.coffee#L183-L184) that we use elsewhere (such as on the "Shows" view on the same profile page).
> Only show displayable fair booths in news section on partner2 page

- package.json
- yarn.lock
Follows up https://github.com/artsy/artsy-passport/pull/149.
This seems to work locally. At least, it works as well as any local development works for me--it bumps into a Recaptcha-validation error, but that's pre-existing. (The local problem I had with xapp-loading went away when using this properly-released version of `@artsy/passport`. It must have been related to pointing to a local version of the library.)
> Upgrade @artsy/passport to pass X-Forwarded-For through from clients to API

- .circleci/config.yml
The CircleCI [workflow](https://app.circleci.com/pipelines/github/artsy/force/9366/workflows/a725eb0b-7862-4143-b04b-630009bbbe9b) for the master branch seems off. The type check step is not doing anything but consumes container. We should probably either require it for staging deployment or remove it.
> Require type check before deploying to staging

- src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
While making a change in how the auction result sale dates are rendered, I found that eslint was complaining about us using anchors with `onClick` handlers. This PR replaces them with `<Clickable>` text (which is effectively text wrapped in a `<Button>`). I also refactored the component to better separate (I think) the logical decisions from the display rendering.
There are some visual changes as a result. The fields that needed a11y help were inconsistently aligned, so I made the alignment consistent.
| Logical branch  | Before  | After |
|---|---|---|
| logged out, unfiltered | ![image](https://user-images.githubusercontent.com/1627089/94305164-62da1e00-ff36-11ea-8f0e-555a59c3a915.png) | ![image](https://user-images.githubusercontent.com/1627089/94308803-b2234d00-ff3c-11ea-931a-dfcdf0003 …
> chore [a11y]: replace auction result anchors with buttons

- src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
- src/v2/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
Addresses [(CSGN-387)](https://artsyproduct.atlassian.net/browse/CSGN-387) 
Sale dates for auction lots were showing the correct date on server-render, but once the client took over they'd flip to the previous day. 
This PR modifies (and mostly centralizes) how we parse lot sale dates so that the correct date is displayed on the client. 
Sale dates are stored in the diffusion Lot table without timezones. Metaphysics returns them to force in ISO format. For a sale that occurred on 2020-08-13, MP would return the `saleDate` field as `"2020-08-13T00:00:00.000Z"`. 
The luxon library, used in force, [assumes that we want the take the client's time zone into account when parsing dates](https://moment.github.io/luxon/docs/manual/zones.html#local-by-default). For a lot with the sale date …
> fix: display auction result sale date without considering local time zone

- src/v2/Apps/Fair/Components/FairFollowedArtists.tsx
- src/v2/Apps/Fair/FairApp.tsx
- src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
- src/v2/__generated__/FairApp_Query.graphql.ts
- src/v2/__generated__/FairApp_fair.graphql.ts
- src/v2/__generated__/FairFollowedArtists_fair.graphql.ts
- src/v2/__generated__/routes_FairQuery.graphql.ts
Re: [FX-2175](https://artsyproduct.atlassian.net/browse/FX-2175)
Not much to this. I will note that we should make a separate ticket/follow up on how we navigate to the page view the "View all" link. Apparently query strings turn off client-side routing, page anchors don't work, and the object syntax that found supports doesn't work here — so I'd rather go down that hole on its own.
> [FX-2175] Implements followed artists rail

- package.json
- yarn.lock
A couple of us have had issues with the `jwt-decode` dependency not type-checking properly, though it seems to be very inconsistently affecting people. This PR adds the types as a dev dependency with the theory that (a) it shouldn't hurt anyone, and (b) if it prevents one more person from chasing their tail on this issue it's worth it.
> chore: add types for jwt-decode

- src/desktop/apps/auction/components/layout/auction_info/Registration.tsx
- src/desktop/apps/auction/components/layout/auction_info/__tests__/Registration.jest.js
- src/desktop/apps/auction/queries/v2/me.ts
This PR creates new CTAs when a user has a pending identity verification blocking their registration in an auction. It is blocked by https://github.com/artsy/metaphysics/pull/2719.
Jira 🔒 [AUCT-1142]
Current specs for the `Registration` component, which contains logic for the button and info text on a sale:
```
auction/components/layout/auction_info/Registration.test
<Registration />
✓ doesnt render when isClosed is true (13ms)
✓ returns Approved if user has a qualified bidder registration (4ms)
✓ returns Registration Closed if if registration is ended + not registered (3ms)
sale requires identity verification
✓ returns Registration Pending when not qualified for bidding and verified (6ms)
✓ Has CTA with link for user to complete id verificaiton if that is blocking their registration …
```
> New CTAs for user with pending identity verification

- src/v2/Apps/Fair/Components/FairHeader.tsx
- src/v2/Apps/Fair/Components/FairTiming.tsx
- src/v2/Apps/Fair/Components/__tests__/FairHeader.jest.tsx
- src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
- src/v2/Components/EventTiming.tsx
- src/v2/Components/__tests__/EventTimer.jest.tsx
- src/v2/__generated__/FairApp_Query.graphql.ts
- src/v2/__generated__/FairHeader_Query.graphql.ts
- src/v2/__generated__/FairHeader_fair.graphql.ts
- src/v2/__generated__/FairTiming_fair.graphql.ts
- src/v2/__generated__/routes_FairQuery.graphql.ts
Web version of:
I made this a specific `Fair` component for now. It should be easily extracted into a more shareable `EventTiming` or something for use on the show page (it just needs the `startAt` and `endAt` basically).
For the first line of the display, I chose to use [`exhibitionPeriod`](https://github.com/artsy/metaphysics/blob/40e352176834ba79962d17dff51a94f9978dc71d/src/schema/v2/fair.ts#L157). That basically does what we want, and will include the year if it's different from the current year. The comp seems to always include the year, but the fair name (right above the timing info) will frequently include the year as well ('CHART 2020'), so this seems fine.
For the second line of the display, it's some dynamic text, but one of the dynamic possibilities is a countdown timer. I …
> @dzucconi => [Fair] Update timing display

- docs/creating_review_app.md
Part of Ingress migration change.
> Update review app doc to mention that DNS must be set to Cloudflare proxied.

- src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
- src/v2/Apps/Fair/Components/FairHeader.tsx
- src/v2/Apps/Fair/Routes/FairInfo.tsx
- src/v2/__generated__/FairApp_Query.graphql.ts
- src/v2/__generated__/FairEditorialItem_article.graphql.ts
- src/v2/__generated__/FairHeader_Query.graphql.ts
- src/v2/__generated__/FairHeader_fair.graphql.ts
- src/v2/__generated__/FairInfo_Query.graphql.ts
- src/v2/__generated__/FairInfo_fair.graphql.ts
- src/v2/__generated__/routes_FairInfoQuery.graphql.ts
- src/v2/__generated__/routes_FairQuery.graphql.ts
Couple of minor fixes to the Fair2 page:
1. Updates the "about" and "summary" to support html/markdown:
2. Same update as above, but on the info page:
3. Updates the editorial items to include the full year:
> FX-2296, FX-2309: Fix editorial byline + make descriptions proper html

- src/v2/Apps/Fair/Components/FairFollowedArtists.tsx
- src/v2/Apps/Fair/Components/FairHeader.tsx
- src/v2/Apps/Fair/Components/__tests__/FairHeader.jest.tsx
- src/v2/Apps/Fair/FairApp.tsx
- src/v2/Apps/Fair/FairSubApp.tsx
- src/v2/Apps/Fair/routes.tsx
Addresses: [FX-2300]
Following discussion on [FX-2291] and in our launch chat, we want to move the `/fair2` routing for the new Fair page over to `/fair`, which is currently unused.
[FX-2300]: https://artsyproduct.atlassian.net/browse/FX-2300
[FX-2291]: https://artsyproduct.atlassian.net/browse/FX-2291
> chore: move WIP fairs page from /fair2 to /fair

- src/v2/Apps/Order/Routes/Shipping/index.tsx
Partners can list works in any country as "domestic only" by not adding an international shipping fee when editing the artwork in CMS. However, any "domestic only" work that is not in the US or continental Europe will trigger an error that says "This work can only be shipped to the continental United States" when a user attempting to purchases submits the shipping address form.
There's actually another subtle bug this fixes - if a user were to order a work (that will ship to anywhere) and not touch the shipping dropdown, we would actually assuming it's shipping to the US. Unlikely this has happened since our auto-selected option is Afghanistan, but better to fix!
Before: 
After:
Jira ticket: https://artsyproduct.atlassian.net/browse/GALL-3293
> fix: allow domestic-only shipping for non-US works [GALL-3293]

- src/desktop/apps/categories/components/App.js
- src/desktop/apps/categories/components/FeaturedGene.js
- src/desktop/apps/categories/components/GeneFamilyNav.js
- src/desktop/apps/categories/components/__tests__/GeneFamilyNav.test.js
A small Future Friday typography conversion…
There is a generation of Force sub apps that were born after we switched to React but before we standardized on Relay/Reaction/Palette. I wanted to try updating one of those, so I went to my old friend `/categories`
The conversion was not too bad, just needed to wrap it in a Palette `<Theme />` and drop in a few `<Text>`s
I chose only to replace Avant Garde, leaving the rest as-is since that would require more substantial design input.
> style(typography): remove Avant Garde from categories page #FF

- src/v2/Apps/Fair/routes.tsx
Fixes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=FX&modal=detail&selectedIssue=FX-2177
When you click the 'View All' link in the 'Works by Artists you Follow' rail, it should stay w/in the router and link you w/o a page reload.
> @dzucconi => [Fair] Tweak route path regexp to handle linking to artworks tab w/ query params

- src/v2/Apps/Artwork/ArtworkApp.tsx
Re: https://artsy.slack.com/archives/CP9P4KR35/p1601507293104300
On client-side route changes the `ArtworkDetailsAboutTheWorkFromPartner` component doesn't re-render. I'd like to take a look in the morning see if this was introduced recently, but it appears unrelated to any of the cosmetic work that's been done on this page in the past week or so.
There's no danger in adding the key here — it's just treating the symptom and papering over the underlying issue.
> Includes artwork id in details key to force re-render

- src/v2/Apps/Order/Routes/Shipping/index.tsx
Current state: if a work can only be shipped domestically and the user selects a non-domestic country (theoretically should not be possible because the shipping dropdown should always be locked to the country/countries a work can be shipped to) and submits, they're greeted with an error that says "This work can only be shipped to the continental United States," even if the work is shipping from a different country. 
After looking into this, it seems like we'd have to add a fair amount of logic to have a truly dynamic error message that says "...can only be shipped to [Country Name]/the continental US/continental Europe", and that didn't seem worth the effort to me. @ansor4 you think this is a reasonable way to go? 
Before: 
After:
Jira ticket: …
> fix: generalize error message for domstic shipping [GALL-3297]

- src/v2/Apps/Fair/FairApp.tsx
- src/v2/Apps/Fair/Routes/FairArtworks.tsx
- src/v2/Components/v2/ArtworkFilter/index.tsx
Re: [FX-2325](https://artsyproduct.atlassian.net/browse/FX-2325)
This doesn't technically totally close out that issue. This is still an issue everywhere else that uses the artwork filter and tabs. So I suggest we merge this to deal with the immediate Q/A issue; and then resolve to fix this for real by leaving the ticket open/unresolved.
There's a few problems compounding here and preventing me from fixing this the right way:
* The artwork filter has opinions about internal — this is easy enough to resolve: I removed the hardcoded spacing and mixed in box props, then set the default props to match the existing values for `mt`. (We can remove the borders as well and do the same thing but if we want to drop the split border.)
* Re: border, that's why we're offsetting by the first `-1px`
* …
> [FX-2325] Filter border

- src/desktop/apps/auction/components/layout/ConfirmRegistrationModal.tsx
- src/desktop/apps/auction/components/layout/__tests__/ConfirmRegistrationModal.jest.tsx
- src/v2/Components/Auction/PostRegistrationModal.tsx
This PR updates the modal text for an auction registration that is blocked due to a user's pending identity verification. In the process I also updated the modal to user our preferred palette `<Text>` rather than `Serif` component.
Completes [AUCT-1142].
[AUCT-1142]: https://artsyproduct.atlassian.net/browse/AUCT-1142
> Update modal text for pending auction reservation due to IDV

- src/v2/Apps/Show/ShowApp.tsx
- src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
- src/v2/Apps/Show/components/ShowMeta.tsx
- src/v2/Apps/Show/routes.tsx
- src/v2/Apps/getAppRoutes.tsx
- src/v2/__generated__/ShowApp_show.graphql.ts
- src/v2/__generated__/ShowMeta_show.graphql.ts
- src/v2/__generated__/routes_ShowQuery.graphql.ts
Closes: [FX-2189](https://artsyproduct.atlassian.net/browse/FX-2189)
> [FX-2189] Implements bare-bones show route

- package.json
- src/v2/Apps/Artist/Components/__tests__/ArtistConsignButton.jest.tsx
- src/v2/__generated__/ArtistConsignButton_Test_Query.graphql.ts
- yarn.lock
This adds the new `relay-test-utils` package to force, and gives an example of how one would refactor an existing test (albeit without the automocking features).
> chore: Add relay-test-utils lib

- .circleci/config.yml
Review apps no longer work after the ci workflow changes. The task needs
access to the buildkit engine to succeed. This changes enables buildkit
during the review app creation.
> fix: Review App Creation

- src/v2/Apps/Fair/Routes/FairArtworks.tsx
- src/v2/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
- src/v2/Apps/Fair/routes.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
- src/v2/Components/v2/ArtworkFilter/Utils/fetchFollowedArtists.ts
- src/v2/__generated__/fetchFollowedArtistsQuery.graphql.ts
This is kind of complex/nuanced! Basically, this tweaks the functionality and behavior of the current filter based on the spec:
It feels a _bit_ odd, and I have a few questions about how it should exactly behave (is it even necessary?). But with Nicole gone, I'm not 100% sure how to clarify, or if we should revisit it.
This is nevertheless mergeable, and we can see how the behavior feels on staging/prod.
In a nutshell:
This loads artists you follow at the fair, client-side. Then, when checking on the 'Artists I follow' filter, those followed artists are checked on for you. As you select/de-select non followed artists, we maintain the `?include_artworks_by_followed_artists=true` param, and also construct the ad-hoc artists in `?artist_ids[]=...`. Once you de-select a followed artist …
> @sweir27 => [Fair] Load followed artists clientside, and enable checkbox interaction with 'Artists I Follow' filter

- src/v2/Components/Artwork/FillwidthItem.tsx
Save artwork actions on the new fair pages were not opening the modal due to missing `mediator`. 
This PR wraps the `FillwidthItem` with `SystemContext`, ensuring the `mediator` will be present in all v2 apps by default. For non-v2 apps we can manually pass the mediator as a prop to launch the modal.
> fix: Add system context to FillwidthItem

- src/mobile/apps/gene/test/view.test.js
Memory leak in tests was introduced in #6426 
Fixes test that breaks due to `this` not existing / jQuery errors.
> Remove 'this' from GeneArtistView tests

- src/mobile/apps/fair/test/client/exhibitors.test.js
- src/mobile/apps/favorites_following/test/client/following.test.js
- src/mobile/apps/home/test/client_view.test.js
- src/mobile/apps/shows/test/view.test.js
- src/mobile/apps/unsubscribe/test/client.test.js
Some changes in `mobile/bootstrap` (#6426) have introduced leak issues in mocha tests -- specifically that `Backbone.$ = $` should be defined inside the `benv.render` callback and after and view requires when used, otherwise `jQuery` will not be available.
Additionally fixed erroneously placed `return` statements and liberal use of `this`, which is not available in this context.
> chore: Address decaf/jquery issues in mocha tests

- src/desktop/apps/user/stylesheets/index.styl
- src/desktop/apps/user/templates/layout.jade
- src/desktop/components/react/stitch_components/index.tsx
- src/v2/Apps/Purchase/Components/OrderRow.tsx
- src/v2/Apps/Purchase/Components/PurchaseHistory.tsx
- src/v2/Apps/Purchase/Utils/orderHelper.tsx
- src/v2/Apps/Purchase/__tests__/PurchaseApp.jest.tsx
- src/v2/Apps/Purchase/routes.tsx
- src/v2/Components/UserSettings/UserSettingsTabs.tsx
- src/v2/Components/UserSettings/__tests__/UserSettingsTabs.jest.tsx
- src/v2/__generated__/OrderRow_order.graphql.ts
- src/v2/__generated__/PurchaseAppTestQuery.graphql.ts
- src/v2/__generated__/PurchaseHistoryQuery.graphql.ts
- src/v2/__generated__/PurchaseHistory_me.graphql.ts
- src/v2/__generated__/routes_PurchaseQuery.graphql.ts
[PURCHASE-2158]
This adds a bit on top of @lilyfromseattle's PR here: https://github.com/artsy/force/pull/6423
Missing artwork:
</details>
* Replace force `Pagination` with palette pagination components
Because force `Pagination` component is tied to `PageCursor` graphql type but since this is coming from exchange the page info is of type `CommercePageCursor 
* Move `OrderRow` to its own file
* Changed Exchange to accept `states` instead of `state` in `me->orders` query so we can pass desired states
(filtering orders by `state` on the client breaks pagination)
* Make the code more defensive around missing artworks (This is a staging problem and shouldn't happen on production but it is better to fix it to make QA easier)
[PURCHASE-2158]: …
> feat: new user setting tabs

- src/v2/Apps/Show/ShowApp.tsx
- src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
- src/v2/Apps/Show/components/ShowAbout.tsx
- src/v2/Apps/Show/components/ShowHeader.tsx
- src/v2/Apps/Show/components/ShowViewingRoom.tsx
- src/v2/__generated__/ShowAbout_show.graphql.ts
- src/v2/__generated__/ShowApp_Test_Query.graphql.ts
- src/v2/__generated__/ShowApp_show.graphql.ts
- src/v2/__generated__/ShowHeader_show.graphql.ts
This builds off the new grid component for layout in https://github.com/artsy/palette/pull/794
This is actually a weirdly complex conditional layout that becomes very easy with the new grid component.
-----
-----
-----
-----
> [FX-2192] Show header info

- src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
Adds data attributes to bid-related buttons so that we can target them in Integrity without relying on the button text.
Related to https://github.com/artsy/integrity/pull/193
Related failure: https://app.circleci.com/pipelines/github/artsy/integrity/3779/workflows/7482c733-e4f4-404d-822e-321bb242604e/jobs/17858
> trivial: Add data attrs for integrity to bid buttons

- src/v2/Apps/Show/Components/ShowContextCard.tsx
- src/v2/Apps/Show/ShowApp.tsx
- src/v2/Apps/Show/__tests__/ShowContextCard.jest.tsx
- src/v2/Components/FairCard.tsx
- src/v2/__generated__/FairCard_fair.graphql.ts
- src/v2/__generated__/ShowApp_Test_Query.graphql.ts
- src/v2/__generated__/ShowApp_show.graphql.ts
- src/v2/__generated__/ShowContextCard_Test_Query.graphql.ts
- src/v2/__generated__/ShowContextCard_show.graphql.ts
- src/v2/__generated__/routes_ShowQuery.graphql.ts
Looks like:
This only implements the 'fair booth' version (ie- display info about and link back to the fair). Will follow up in a separate PR with the relevant info for the regular show version.
> @dzucconi => [Show] Add context card for a fair

- src/mobile/assets/mobile_openseadragon.ts
- webpack/envs/clientCommonConfig.js
We don't need to load the 200KB gzip archive for `openseadragon` on each
page, it is only used on the artwork page. This change updates the Webpack
minChunk property so that single use components are not included everywhere.
Also removes one unused file.
> chore: Only Load Openseadragon if Required

- src/v2/Apps/Show/Components/ShowContextCard.tsx
- src/v2/Apps/Show/ShowApp.tsx
- src/v2/Apps/Show/__tests__/ShowContextCard.jest.tsx
- src/v2/__generated__/ShowApp_Test_Query.graphql.ts
- src/v2/__generated__/ShowApp_show.graphql.ts
- src/v2/__generated__/ShowContextCard_Test_Query.graphql.ts
- src/v2/__generated__/ShowContextCard_show.graphql.ts
- src/v2/__generated__/routes_ShowQuery.graphql.ts
Looks like:
This already displayed info for a fair booth, this completes the module by displaying the partner info (when not a fair booth).
> @dzucconi => [Show] Add context card for a partner

- src/v2/Apps/Show/Components/ShowPartnerEntityHeader.tsx
- src/v2/Apps/Show/ShowApp.tsx
- src/v2/Apps/Show/ShowSubApp.tsx
- src/v2/Components/FollowButton/FollowProfileButton.tsx
- src/v2/__generated__/ShowApp_Test_Query.graphql.ts
- src/v2/__generated__/ShowApp_show.graphql.ts
- src/v2/__generated__/ShowInfo_Test_Query.graphql.ts
- src/v2/__generated__/ShowSubApp_show.graphql.ts
- src/v2/__generated__/routes_ShowInfoQuery.graphql.ts
- src/v2/__generated__/routes_ShowQuery.graphql.ts
- src/v2/__generated__/routes_ShowSubAppQuery.graphql.ts
Follow up to #6388, update props for `ShowPartnerEntityHeader` to handle new proptypes
- remove deprecated prop `onOpenAuthModal`.
- remove extra `Clickable` (causes errors for nested buttons)
- adds analytics context to app
> ShowPartnerEntityHeader follow button uses typesafe props

- scripts/jest.sh
Jest has been stable with two workers and the memory usage is lower now
that we are running tests directly from the build container instead of
using docker in docker from the hokusai image. So let's see how three
workers goes.
This change speeds up the jest v2 build step by about 1m 10s. In other
words: from 4m 30s to 3m 20s.
> chore: Jest Three Workers

- src/v2/Apps/Fair/Routes/FairExhibitors.tsx
This doesn't seem to affect all browsers but, on some versions of Chrome, the position is lost after a visitor clicks "Load more" and content is placed above the current scroll position.
To avoid the loss of position when new content loads in, snap back to the previous position if we're below where we were due to content appearing above the current scroll position.
**Before**
**After**
> fix(FX-2324): Move scrollY to previous position after content change

- Dockerfile
Switching the electron-runner container to use a slim Debian base shaves
off ~600MiB (300MB gzip) from the image size. This will decrease push time and pull
time in CI decreasing the average execution time for the cypress steps.
```
force-test-electron-runner                           latest                                     66dcf71af3e3        27 minutes ago      2.64GB
force-test-electron-runner-slim                      latest                                     0d9ab8417dfc        37 minutes ago      2.02GB
```
> chore: Electron Runner Slim

- src/desktop/apps/fair/routes.coffee
When the response time to fair data fetch requests is high the page was
failing to load and triggering errors. The solution is to add an error
handler to the few fetch methods where they were missing.
> fix: Handle Fair Fetch Timeouts

- package.json
- yarn.lock
The async package is now missing after removing storybook and needs to
be added as a required dependency.
> fix: Missing Package Async

- src/v2/Apps/Purchase/Components/OrderRow.tsx
- src/v2/Apps/Purchase/PurchaseApp.tsx
- src/v2/Apps/Purchase/__tests__/PurchaseApp.jest.tsx
- src/v2/Apps/__tests__/Fixtures/Order.ts
- src/v2/Components/NavBar/Menus/MobileNavMenu/LoggedInLinks.tsx
- src/v2/Components/NavBar/Menus/UserMenu.tsx
- src/v2/Components/NavBar/Menus/__tests__/UserMenu.jest.tsx
- src/v2/Components/NavBar/__tests__/NavBarTracking.jest.tsx
- src/v2/__generated__/OrderRow_order.graphql.ts
- src/v2/__generated__/PurchaseAppTestQuery.graphql.ts
- src/v2/__generated__/PurchaseHistoryQuery.graphql.ts
- src/v2/__generated__/routes_PurchaseQuery.graphql.ts
Addresses [PURCHASE-2177] [PURCHASE-2178] [PURCHASE-2179]
* Add purchase history link to the mobile nav 
* Purchase history links 
* Add track order link 
* Mobile view/track button redesign
* Remove feature flag
Mobile
Desktop
</details>
[PURCHASE-2177]: https://artsyproduct.atlassian.net/browse/PURCHASE-2177
[PURCHASE-2178]: https://artsyproduct.atlassian.net/browse/PURCHASE-2178
[PURCHASE-2179]: https://artsyproduct.atlassian.net/browse/PURCHASE-2179
> enhancement: Purchase history enhancements

- src/v2/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomSubsections.tsx
https://artsyproduct.atlassian.net/browse/PX-3372
Add style `white-space: pre-wrap` to the body text of viewing room subsections
> bug: Add white space prewrap to subsection body

- src/desktop/analytics/main_layout.ts
- src/desktop/analytics/timeOnPageListener.ts
- src/v2/Artsy/Analytics/trackingMiddleware.ts
- src/v2/Artsy/Router/RouterLink.tsx
- src/v2/Components/NavBar/NavItemPanel.tsx
Fixes https://artsyproduct.atlassian.net/browse/GRO-26
Noticed that we wern't clearing the timer and executing this function twice, if clicking through pages fast. This fixes that. 
Also fixes a few glaring react console errors related to props being improperly passed to the dom. 
> bugfix: Clear timeOnPage interval

- src/v2/Artsy/Router/RouterLink.tsx
- src/v2/Components/NavBar/NavItem.tsx
Closes: [FX-2379](https://artsyproduct.atlassian.net/browse/FX-2379)
[Diff without whitespace changes](https://github.com/artsy/force/pull/6501/files?diff=unified&w=1)
This wasn't manifesting in any visible bugs, but this fixes the issue and silences the error.
The `hitAreaRef` is specifically used when a sub-menu is opened: when the escape key is pressed, the sub-menu closes and focus is returned to that hit area, which is a `Clickable`. Since `NavItems` can be plain links without sub-menus using the `as` prop, this leads to a ref on a function component `RouterLink` that can't be used (but was never actually used).
It's a fine idea to forward the ref anyway, which is what this PR does.
(Also cleaned up some erroneous props which were present in a93e15a1c217995c20553a4e1bcdbaec4d61c8ab …
> [FX-2379] Forwards ref to RouterLink

- package.json
- yarn.lock
This adds [orta/pull-lock](https://github.com/orta/pull-lock) to force which will automatically run `yarn install` after `git pull` if it detects that our lockfile has changed. (Matching how things work on Eigen.)
This is especially useful for situations where a dev has sync'd up with master, opened a branch and did some work, pushes changes, but push fails because some kind of type error, etc, related to dev forgetting to run yarn install after master sync.
> toolchain: Add pull-lock for automatically yarn installing deps on pull

- src/v2/Apps/Consign/Components/SellArtDifferently.tsx
- src/v2/Apps/Consign/ConsignApp.tsx
https://artsyproduct.atlassian.net/browse/GRO-37
Adds the "Selling Art Differently" section for the new `/consign` page. This section will have to be updated once the new icons are available.
The separator is `black10` instead of `black60` pending confirmation from design that we do in fact want `black60`.
**Desktop viewports**
**Mobile viewports** (overflow issue is unrelated)
> feat: Add Selling Art Differently section

- src/desktop/apps/fair/fairRedirection.ts
- src/desktop/apps/fair/test/fairRedirection.jest.ts
The fair slug comes in as `profileId`, not `id`, when on mobile web so the desktop-oriented redirect rules would bypass the logic intended to keep a set of fairs on the old fair experience.
This commit adds handling of the mobile request param to trigger the same exclude behavior.
> fix: do not redirect to new fair exp via mobile routes if excluded

- src/desktop/apps/fair_organizer/routes.coffee
- src/mobile/apps/fair_organizer/routes.coffee
- src/mobile/apps/fair_organizer/test/routes.test.js
This PR pulls heavily from https://github.com/artsy/force/pull/3780, doing essentially the same thing but for Force's mobile route.
The bug this fixes: when accessing a `fair_organizer` page **on mobile web**, (e.g. `artsy.net/the-armory-show`) after an iteration of that fair's autopublish date and before its start date, we redirect from fair organizer page to the individual fair page (e.g. `artsy.net/fair/the-armory-show-2020`) and the page 404s because it's not yet visible to the public.
For both mobile and desktop, I switched from checking `autopublish_at` to `start_at`. @starsirius mentions considering `active_start_at` in the last PR but opting not to because `active_start_at` is not always set.
That seems like a good choice - as we can see in `admin-fairs.artsy.net`, that field is …
> fix: stop redirecting to individual fair edition before page is available

- src/v2/Apps/Consign/Components/HowToSell.tsx
- src/v2/Apps/Consign/Components/SellArtDifferently.tsx
- src/v2/Apps/Consign/ConsignApp.tsx
https://artsyproduct.atlassian.net/browse/GRO-37
Adds the "How to Sell" section for the new consign2 page. The structure is almost identical to https://github.com/artsy/force/pull/6525.
> feat: Add "How to Sell" section to consign2

- src/mobile/collections/install_shots.coffee
- src/mobile/models/install_shot.ts
While decaffeinating files the following export needed to be updated to
prevent a mismatch between `module.exports` and es6 style exports. I'm
still investigating to see if there is a way this type of mismatch can
be identified more easily while decaffeinating files.
> fix: Decaffeination Export Error

- src/v2/Apps/Show/Components/ShowViewingRoom.tsx
- src/v2/Apps/ViewingRoom/Components/ViewingRoomsFeaturedRail.tsx
- src/v2/Apps/ViewingRoom/Components/ViewingRoomsLatestGrid.tsx
- src/v2/Utils/__tests__/resized.jest.ts
- src/v2/Utils/resized.ts
Since we don't have the same helper fields that Metaphysics has, this PR adds two new functions `cropped` and `resized` which accept the same arguments as `crop` and `resize` but return `{ src: string, srcSet: string }` with a `srcSet` filled in for the `2x` version of the desired image.
> Uses srcSet in viewing room cards

- package.json
- src/v2/Apps/Artist/Routes/Consign/Components/SectionContainer.tsx
- src/v2/Apps/Components/HorizontalPadding.tsx
- src/v2/Apps/Consign/Components/GetPriceEstimate.tsx
- src/v2/Apps/Consign/Components/Header.tsx
- src/v2/Apps/Consign/Components/HowToSell.tsx
- src/v2/Apps/Consign/Components/InDemandNow/ConsignInDemandNow.tsx
- src/v2/Apps/Consign/Components/InDemandNow/ConsignTopArtists.tsx
- src/v2/Apps/Consign/Components/InDemandNow/DemandRank.tsx
- src/v2/Apps/Consign/Components/SectionContainer.tsx
- src/v2/Apps/Consign/Components/SellArtDifferently.tsx
- src/v2/Apps/Consign/ConsignApp.tsx
- src/v2/Apps/Consign/Utils/__tests__/formatCentsToDollars.jest.tsx
- src/v2/Apps/Consign/Utils/formatCentsToDollars.ts
- src/v2/__generated__/ConsignInDemandNowQuery.graphql.ts
- yarn.lock
Addresses https://artsyproduct.atlassian.net/browse/GRO-34 
This gets a first pass of the the In Demand Now section in. 
Some follow-up items in next PR:
- Verify data (diffusion) fields are correct 
- Sum up average of all artists' artwork prices for average in top-artists section 
- Replace graph image with svg (?) 
- A little more precise design QA (margins) 
Also starts getting the overall page in shape, e.g., capping center content width for each section.
> feat: [Consign2] Add In Demand section 

- src/v2/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
- src/v2/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
- src/v2/__generated__/ArtistSearchResultsQuery.graphql.ts
- src/v2/__generated__/ArtistSearchResults_viewer.graphql.ts
- src/v2/__generated__/GeneSearchResultsQuery.graphql.ts
- src/v2/__generated__/GeneSearchResults_viewer.graphql.ts
This was such an irritating bug to track down, haha! 🤣 
I was seeing the results come back empty from MP so then I went up the stack and inspected what was going on there. I discovered that Gravity was returning 10 results but then `graphql-relay` was slicing it down to none because...well I'm not totally sure. I guess because a `page` argument was undefined where we didn't expect it, but this is right at the edge of my understanding of things.
Once I noticed that, then it occurred to me that I should try to send the `first` argument and see if that would fix things and sure enough it did. Sometimes you just have to try hard and believe in yourself!
This is the slicing code I was poking at:
https://github.com/graphql/graphql-relay-js/blob/8f4ed1ad35805ef233ad9fd1af33abb9c0cad35a/src/connec …
> Fix onboarding search results

- src/desktop/analytics/helpers.ts
- src/desktop/lib/global_client_setup.tsx
Follow up to https://github.com/artsy/force/pull/6545, checks if analytics libs are present on the window before firing events.
We are seeing issues with ad blockers on some clients selectively blocking functions from `window.analytics`.
Related sentry errors:
Cannot read property 'trackPageView' of undefined - https://sentry.io/organizations/artsynet/issues/1987311462/?project=28316
window.analytics.reset is not a function - https://sentry.io/organizations/artsynet/issues/1947334683/?project=28316
> bugfix: check for missing analytics libs before firing

- src/v2/Components/NavBar/NavItem.tsx
- src/v2/Components/NavBar/NavItemPanel.tsx
- src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
- src/v2/Components/NavBar/__tests__/NavItem.jest.tsx
Closes: [FX-2262](https://artsyproduct.atlassian.net/browse/FX-2262)
Looks identical, just instead of rendering/not rendering we thread the boolean through to `useSpring` and `display: none|block`
> [FX-2262] Renders hidden sub-menus to ensure they are crawlable

- src/desktop/apps/authentication/__tests__/helpers.jest.ts
- src/desktop/apps/authentication/helpers.ts
- src/desktop/apps/authentication/routes.ts
- src/typings/sharify.d.ts
Our auth modals use the `LoggedOutUser` model to manage authentication requests, which adds unwanted dependencies for Backbone, jQuery and Underscore. 
This PR uses `fetch` to replicate request logic from `LoggedOutUser`'s `login`, `signup`, and `forgot` methods, and makes requests directly from the modal rather than relying on the backbone model.
https://artsyproduct.atlassian.net/browse/PLATFORM-2919
Review app: https://logged-out-user.artsy.net/
Old user logic (still used for inquiry flow) - https://github.com/artsy/force/blob/master/src/desktop/models/logged_out_user.coffee#L59-L101
TODO:
> refactor: replace auth modal backbone requests with fetch

- src/v2/Apps/Show/ShowSubApp.tsx
Closes: [FX-2402](https://artsyproduct.atlassian.net/browse/FX-2402)
Initially my plan was to implement the [sticky footer pattern](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/), though this isn't as straight-forward as it seems for our case.
The situation is a rare enough thing that I don't feel too bad about adding a simple `minHeight` here.
> [FX-2402] Sets a minHeight for very short pages

- src/v2/Apps/Consign/Components/HowToSell.tsx
- src/v2/Apps/Consign/Components/SellArtDifferently.tsx
The spec for `/consign2` calls for a black60 line that divides header text from body text in certain sections. Previously we were using a `Separator` component to do this and planned to add a `color` prop to change the color of the component to black60.
Remove the `Separator` component in favor of a black60 border on the `Text` component since (1) it doesn't require updating Palette, (2) it's not clear that we should add a `color` prop to `Separator` anyway given our design system and (3) `Separator` isn't really designed for this use.
> Use border on text component instead of using a Separator on consign2

- src/v2/Apps/Consign/Components/ContactUs.tsx
- src/v2/Apps/Consign/ConsignApp.tsx
Adds a second contact block and updates `ContactUs` to have an optionally dark color scheme variant.
> feat: Add second contact block and update copy on /consign2

- src/v2/Apps/Consign/Components/GetPriceEstimate/ArtistInsightResult.tsx
- src/v2/Apps/Consign/Components/GetPriceEstimate/EstimateResults.tsx
https://artsyproduct.atlassian.net/browse/GRO-45
Adds a skeleton loading state when fetching price estimate results for an artist on `/consign2`.
> feat: Add skeleton loading state when fetching price estimates on /consign2

- src/desktop/components/prevent_right_click/index.jade
- src/desktop/models/additional_image.coffee
- src/desktop/models/artwork.coffee
- src/desktop/test/models/artwork.test.js
- src/lib/current_user.coffee
- src/typings/gravity.d.ts
- src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
- src/v2/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.jest.tsx
- src/v2/Apps/__tests__/Fixtures/Artwork/ArtworkActions.fixture.ts
- src/v2/Components/Artwork/FillwidthItem.tsx
- src/v2/Components/Artwork/GridItem.tsx
- src/v2/Components/Lightbox/Lightbox.tsx
- src/v2/Utils/__tests__/user.jest.ts
- src/v2/Utils/user.ts
- Adds utils `userIsTeam` helper
- Updates all admin checks related to images to determine access by `team` role rather than `admin`
- Adds roles  to `User` typings
Addresses https://artsyproduct.atlassian.net/browse/PLATFORM-2492
> Users with Team role can download images

- src/v2/Apps/Show/Components/ShowArtworksEmptyState.tsx
- src/v2/Apps/Show/ShowApp.tsx
- src/v2/Apps/Show/__tests__/ShowArtworksEmptyState.jest.tsx
- src/v2/Apps/Show/__tests__/ShowViewingRoom.jest.tsx
- src/v2/DevTools/setupTestWrapper.tsx
- src/v2/__generated__/ShowApp_Test_Query.graphql.ts
- src/v2/__generated__/ShowApp_show.graphql.ts
- src/v2/__generated__/ShowArtworksEmptyState_Test_Query.graphql.ts
- src/v2/__generated__/ShowArtworksEmptyState_show.graphql.ts
- src/v2/__generated__/routes_ShowQuery.graphql.ts
Closes: [FX-2412](https://artsyproduct.atlassian.net/browse/FX-2412)
-----
I tried to wrap up the boilerplate for setting up a test renderer with mocks: b98dcf3eb2b9a769c5a369d01d202423565600e0
Not super necessary but the copy-pasting was getting me down a bit. I don't *think* we can get it any shorter?
> [FX-2412] Show artwork filter empty state (and test helper)

- src/desktop/apps/artists/index.styl
- src/desktop/apps/artists/templates/index.jade
- src/desktop/apps/artists/templates/letter.jade
- src/desktop/apps/artists/templates/meta.jade
- src/mobile/apps/artists/index.styl
- src/mobile/apps/artists/routes.coffee
- src/mobile/apps/artists/templates/index.jade
This PR does a few things:
* Improve the styling of the individual letter pages for artist lists
* Improve the styling of the pagination on these pages
* Restore a pathway to the individual letter pages from the artist landing page
* Settles on 100k as the number of artists one can browse
There is a ton of great chatter here if you want more context:
https://artsy.slack.com/archives/C01ADJNCS5D/p1604507472067500
The punchline from that thread was my desire to address the glaring problem that our alpha artist pages had been orphaned on mweb. This is bad because it's that version of the site that Google crawls.
What this PR does NOT do:
* match the delightful comps @deliciousnachos made for this page
* ensure a great user experience on these alpha pages nor on the list page
Frankly this PR …
> feat: Restore path to alpha artist list pages on mweb

- src/lib/setup.js
Follow up to https://github.com/artsy/force/pull/6584, adds `roles` to artsy-passport's `userKeys` options.
> bugfix: Add 'roles' to passport's userKeys

- src/v2/Apps/Artist/__tests__/routes.jest.tsx
- src/v2/Apps/Artist/routes.tsx
- src/v2/Artsy/Router/PermanentRedirectException.tsx
- src/v2/Artsy/Router/buildServerApp.tsx
Closes: [FX-2430](https://artsyproduct.atlassian.net/browse/FX-2430)
See https://artsy.slack.com/archives/C9SATFLUU/p1604595375485200 for more context.
The thrown `PermanentRedirectException` work-around was breaking client-side routing. Since we've upgraded to found 0.5.5 we can just use the status code support that I added there a while back when this became an issue, and remove this hack.
> [FX-2430] Fixes client-side artist page redirects

- src/v2/Apps/Show/ShowApp.tsx
Closes: [FX-2428](https://artsyproduct.atlassian.net/browse/FX-2428)
I was assuming that the nullable `href` was just a mistake in the schema — but no, it is the the case that you may have a displayable show that doesn't have an `href`. This matches the behavior that's currently in production.
> [FX-2428] Guards against nullable href

- cypress/helpers/visitWithStatusRetries.js
- cypress/integration/collection.spec.js
The cypress test step has been failing somewhat regularly when a `visit` request returns a 500. Retries do not work on page visits that occur in the `before` block of a test.
Adds helper function `visitWithStatusRetries` (as we use in Integrity), to retry these requests. 
I added this to the `/collection/:id` spec for the moment, which is the one I have noticed failing. We can expand this to other tests if necessary. 
https://app.circleci.com/pipelines/github/artsy/force/10437/workflows/0e51ddb3-f580-4b73-8086-0bd6e07c7d63/jobs/72143
> chore: Add retry on status code cypress helper

- package.json
- src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
- src/v2/Apps/Show/__tests__/ShowArtworks.jest.tsx
- src/v2/Apps/Show/__tests__/ShowContextCard.jest.tsx
- src/v2/Apps/Show/__tests__/ShowContextualLink.jest.tsx
- src/v2/Apps/Show/__tests__/ShowInfo.jest.tsx
- src/v2/Apps/Show/__tests__/ShowInstallShots.jest.tsx
- src/v2/Apps/Show/__tests__/ShowViewingRoom.jest.tsx
- src/v2/DevTools/setupTestWrapper.tsx
- src/v2/__generated__/ShowArtworks_Test_Query.graphql.ts
- src/v2/__generated__/ShowContextCard_Test_Query.graphql.ts
- src/v2/__generated__/ShowContextualLink_Test_Query.graphql.ts
- src/v2/__generated__/ShowInstallShots_Test_Query.graphql.ts
- yarn.lock
Cleaned up the rest of the specs in the show app directory — I know a lot of specs involve copy pasting, so at least there's a more consistent batch of specs using the mock generator, etc.
No real changes here. I added the relay-test-utils typings so that we can type the `getWrapper` argument for mocks resolvers.
> [chore] Show2 app specs clean up

- src/v2/Apps/Fair/Routes/FairExhibitors.tsx
- src/v2/__generated__/FairExhibitorsQuery.graphql.ts
- src/v2/__generated__/FairExhibitors_Query.graphql.ts
- src/v2/__generated__/FairExhibitors_fair.graphql.ts
- src/v2/__generated__/routes_FairExhibitorsQuery.graphql.ts
This threads through the ability for the proper `endCursor` behavior to occur in Gravity (https://github.com/artsy/gravity/pull/13611)
> @mzikherman => fix: include totalCount for fair exhibitors query

- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
- src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.jest.tsx
Works from this year wouldn't be findable via the 'Time period' filtering (it only went up to '2010'). :(
Fixes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=FX&modal=detail&selectedIssue=FX-2414
> fix: allow works from 2020 to show up in that time period bucket

- src/desktop/apps/home/routes.coffee
Closes: [FX-2424](https://artsyproduct.atlassian.net/browse/FX-2424) (Maybe)
According to JSON-LD Playground, with the `http` URL, validation fails with:
> jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
So changing this to https allows it to pass validation.
That said; if you run artsy.net through https://search.google.com/test/rich-results
You get:
It's not clear to me if updating the JSON-LD markup will fix this. So, will have to deploy and re-test and go from there.
> [FX-2424] Uses https to pass validation

- src/v2/Components/FairCard.tsx
Related to [FX-2406](https://artsyproduct.atlassian.net/browse/FX-2406)
Previously was `500`ing. Now there's a missing image state:
— unsure whether or not there should be a better missing image state?
> Accommodates missing fair images

- src/v2/Apps/Consign/Components/ContactUs.tsx
- src/v2/Apps/Consign/Components/HowToSell.tsx
- src/v2/Apps/Consign/Components/SellArtDifferently.tsx
- src/v2/Apps/Consign/ConsignApp.tsx
https://artsyproduct.atlassian.net/browse/GRO-51
- Adds new icons to `/consign2` and updates copy based on current spec
- Fixes some minor layout issues at smaller viewports for "How to sell" and "Selling art differently" sections
- Fixes clickable area for some buttons to be just the button
- Moves "Sold recently on Artsy" up
> feat: Add icons to /consign2 and fix minor QA issues

- src/v2/Apps/Show/ShowApp.tsx
- src/v2/Apps/Show/__tests__/ShowApp.jest.tsx
- src/v2/__generated__/ShowApp_Test_Query.graphql.ts
- src/v2/__generated__/ShowApp_show.graphql.ts
- src/v2/__generated__/routes_ShowQuery.graphql.ts
A show can be linked to a Viewing Room but we're currently unable to fetch the Viewing Room once it has closed.
This updates the top-level query to use the connection itself to determine if we are able to render the associated Viewing Room.
Addresses [FX-2499]
[FX-2499]: https://artsyproduct.atlassian.net/browse/FX-2499
> fix: update show page hasViewingRoom determination to use connection

- .eslintrc.js
- package.json
- yarn.lock
Follow-up to cohesion PR. Updated our ESlint config with an auto-fixer for sorting object keys: 
- [object keys](https://www.npmjs.com/package/eslint-plugin-sort-keys-fix)
> toolchain: Add object keys sort lint autofixer

- src/desktop/components/search_bar/templates/index.jade
- src/v2/Components/Search/SearchBar.tsx
Closes: [FX-2424](https://artsyproduct.atlassian.net/browse/FX-2424)
While although we see the sitelinks searchbox fine:
We're still seeing this error in the search console:
I believe this is because of the duplicate and malformed microdata markup, which is now removed with this PR. Additionally we're seeing the error on every page when:
> Add this markup only to the homepage, not to any other pages
> [FX-2424] Removes older microdata sitelinks markup

- src/v2/Apps/Show/Components/ShowArtworks.tsx
- src/v2/Apps/Show/routes.tsx
Pretty straightforward, one less repo needed to be touched (MP), since we don't model possible sorts as an enum, they're just free-form strings 😅
> feat: offer a gallery curated default sort on show artwork filter

- src/v2/Apps/Consign/Components/InDemandNow/ConsignInDemandNow.tsx
Some last minute QA for /consign2 before we launch. This PR: 
- Truncates long titles for the recent auction result
- Centers the recent auction result in the large layout
- Shrinks the average price chart to fit the width
- Centers the average price chart in the small layout
> fix: Clean up margins on In Demand Now section and make layout more responsive on /consign2

- src/v2/Apps/Artist/routes.tsx
- src/v2/Apps/Consign/Components/GetPriceEstimate/ArtistInsightResult.tsx
Fixes the jump to top of page between consign -> artist/auction-results by moving behavior into artist app (which works now that we no longer have huge header)
> fix: Fix consign2 jump

- src/v2/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
So that the header images don't stretch too far on a wide screen
> fix: [Consign2] Cap header max-width

- src/v2/Apps/Consign/Routes/MarketingLanding/Components/TemporaryOffer.tsx
- src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/TemporaryOffer.jest.tsx
Quick follow up to https://github.com/artsy/force/pull/6698. Sets the expiration date to the correct date on `TemporaryOffer` so that it does not render on the right date. Also adds a few quick tests.
> fix: Update TemporaryOffer expiration date and add test

- src/lib/getContextPage.ts
We log warnings for page-type's that haven't been added to the cohesion schema, however we only need these in dev environments. Turns on the log only when `SHOW_ANALYTICS_CALLS` has been enabled.
Related conversation:
https://artsy.slack.com/archives/CA8SANW3W/p1605896540238700
> chore: Do not log warning messages about cohesion in production
