artsy/force

- analytics/partner_application.js
This track call resulted in two pageview events firing for each load of this page.
> @craigspaeth  delete extra analytics.page() call

- apps/artwork/components/auction_artworks/index.styl
- components/artwork_metadata_stub/index.styl
This does some minor style fixes on top of https://github.com/artsy/force/pull/347 Basically we are setting a height of 500px on these artwork "bricks" and that wasn't accommodating when artworks have prices that break on two lines as they do in this auction with prices in HKD (plus some other small things to tidy up the margins).
EDIT: Decided to use overflow: ellipsis instead to keep  things lining up
> @xtina-starr: Fix styling of artworks in auction 

- apps/artist/client/views/overview.coffee
- apps/artist/queries/show_fragment.coffee
cc @briansw 
Kinda weird one, we want to include reference shows in the exhibition highlights and list of shows...but that same data is _also_ used to render this rail.
So, just for purposes of rendering the show rail, we want to remove ref shows.
> @xtina-starr => Dont include reference shows in show rail

- models/article.coffee
I naively assumed that the formatting coming back from GraphQL was the same as the database, but it's actually returning a ISO date. This converts the date to a JS Date format first, which allows us to pass either format.
> @eessex => Fixes date error on articles

- apps/search/client/index.coffee
- apps/search/models/google_search_result.coffee
- apps/search/test/client/index.coffee
Closes https://github.com/artsy/force/issues/389 
(sorry, sniped your issue!)
For these search results, we can't always rely on what google returns so we fetch the artwork again and render over the image, but since we are passing in an `Artwork` model, the `imageUrl` returns something different than the `SearchResult` model. This overrides the artwork `imageUrl` method to returned a cropped version of the image.
> @xtina-starr - Adapt imageUrl for artwork to crop in the context of search results

- apps/artwork/lib/inquire.coffee
- components/inquiry_questionnaire/map/decisions.coffee
- components/inquiry_questionnaire/map/steps.coffee
- components/inquiry_questionnaire/map/test_steps.coffee
- components/inquiry_questionnaire/test/map.coffee
cc @ashkan18 @alloy @acjay 
Picks up where https://github.com/artsy/force/pull/386 left off! The basic idea is to modify the inquiry map to first check whether the work is in an auction or not. If so, just show the `specialist` view, if not, go through the inquiry flow as normal.
> @starsirius - Fix "Ask a Specialist" button on auction pages

- models/search_result.coffee
- Image urls are now returned as metadata by the Gravity Search API, so stop using the `/api/v1/:model/:id/image` endpoints to fetch these. 
- Adds article image thumbnails to our auto-suggest (as a side effect).
- Depends on [gravity#10564](https://github.com/artsy/gravity/pull/10564/), so please don't merge till that has been deployed (I will notify here).
- Depends on [positron#842](https://github.com/artsy/positron/pull/842)
>  @kanaabe : add article image thumbnails to auto-suggest #donotmerge

- apps/search/templates/search_result.jade
- models/search_result.coffee
- test/models/search_result.coffee
Since we're reusing the `SearchResult` model in both the auto-suggest and search results page context now, there was a bug where the auto-suggest was showing the extended title for Artist results - this should only be shown on the search results page.
> @starsirius : fix bug with artist display titles in auto-suggest

- models/search_result.coffee
- test/models/search_result.coffee
- Fixes fair locations returned from search to always use profile slugs.
- Depends on deployment of [Gravity#10587](https://github.com/artsy/gravity/pull/10587)
> @izakp : fix fair locations to use profile slugs in search

- lib/setup.coffee
This fixes the issue you were running into today. Basically, the rate limiting middleware Cab added uses Redis, and if you don't have that setup and running it'll choke. This conditionally adds that middleware only when a Redis url is present to keep dev dependencies smaller.
> @1aurabrown: Only add rate limiting if redis is turned on

- apps/editorial_features/index.coffee
- config.coffee
Use http-proxy to temporarily send the EOY route to a splash page. Once we are ready to go live with EOY, we can remove these lines and host @eessex's page instead. 
The "thanks" page is there because Sailthru forms need a `<form method="POST"` which requires a redirect url when submission is successful. 
cc @eessex
> @craigspaeth => EOY splash page proxy to s3

- npm-shrinkwrap.json
Not sure where the shrinkwrap went backwards, but this updated shrinkwrap (using npm 4.0.2) marks the `fsevents` dependency with an `optional: true` flag. More detail [here](https://github.com/npm/npm/issues/14042#issuecomment-262902456)
It's basically the fix for:
> @craigspaeth => Update shrinkwrap

- apps/articles/routes.coffee
- apps/editorial_features/index.coffee
- config.coffee
- lib/middleware/redirect_mobile.coffee
- lib/middleware/same_origin.coffee
Use a configurable source so that pages like `/2016-year-in-art` can post to this route as well.
> @craigspaeth => Flexible source + cors issue

- lib/middleware/redirect_mobile.coffee
No more m.artsy.net on /editorial-signup/form! Need this in asap for the teaser going out at 1pm.
> @broskoski => Prevent editorial form from being redirected to mobile

- apps/sitemaps/routes.coffee
Sitemaps right now are requesting MBs of data from fusion because we didn't limit the artist and image fields for image sitemaps. My theory is this could be partly what's causing excess memory usage and performance hit from the transfer size.
> @broskoski: Further limit fields requested for image sitemap

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/body.styl
- apps/editorial_features/components/eoy/stylesheets/index.styl
- apps/editorial_features/components/eoy/templates/body.jade
- apps/editorial_features/components/eoy/templates/index.jade
- apps/editorial_features/routes.coffee
Waypoints have mostly been taken out, and many css transitions have been replaced by pixel-by-pixel animations (for vertical lines in body) -- this is currently very laggy so today I'm going to investigate using GSAP instead of jQuery.  Let me know if you have ideas on this!
- Beginnings of responsive theming
- Support for additional writer fields
- Uses resized cloudfront images
> @kanabe => Revise animations

- components/commercial_filter/models/params.coffee
As discussed in [#metaphysics](https://artsy.slack.com/archives/metaphysics/p1480631685000539), because of the graphQL update these null defaults are no longer scrubbed in our requests to gravity. Requesting `include_artworks_by_followed_artists=` or `medium=` means something to our API, but it is not what we intend. This should fix the issues on the `/collect` page that we're seeing in staging.
We can also add some safeguards in metaphysics, but as @joeyAghion pointed out, we may not want to scrub `null` _everywhere_, especially if we intend to allow metaphysics to make PUT/POST requests.
cc @alloy does eigen staging look okay? We could potentially punt this PR and roll back metaphysics to an earlier version of graphql if there's more client fallout.
> @mzikherman => dont explicitly set null for commercial filter params

- npm-shrinkwrap.json
- package.json
This add's Cab's fix via https://github.com/artsy/artsy-error-handler/pull/15 to properly handle xhr vs. html error pages.
> @gnilekaw: Upgrade artsy-error-handler

- components/auth_modal/test/view.coffee
- components/auth_modal/view.coffee
Closes #436
The `reset` form shouldn't actually be submitted (what is causing the redirect after the notice appears) because the user `forgot` is already fired on the step before (see here: https://github.com/artsy/force/blob/master/components/auth_modal/view.coffee#L107 and here: https://github.com/artsy/force/blob/master/models/logged_out_user.coffee#L64 )
> @joeyAghion - Only submit form if the state isnt password reset

- npm-shrinkwrap.json
- package.json
I must have accidentally updated the whole shrinkwrap to include a new version of coffeescript that chokes on [this line](https://github.com/artsy/force/blob/master/lib/routers/hardcoded_redirects.coffee#L43) because `from` is a new keyword for CS loops.
> @gnilekaw: Revert my last PR

- apps/partner2/client/artists_artist.coffee
- apps/partner2/test/client/artists_artist.coffee
- models/partner_artist.coffee
Now that partner-submitted bios support Markdown, we want to display that on the front-end.
Luckily, the artist and artwork page fetch the converted HTML from Metaphysics and render it directly, so those will just work. This updates the partner profile page to render them as markdown. I think that completes making sure they're displayed consistently on the front-end!
> @ashkan18 => Support markdown on partner profile pages for partner-submitted bios

- npm-shrinkwrap.json
- package.json
Oh npm, you are a fickle beast. Running just `npm i artsy-error-handler@latest --save` wasn't updating the shrinkwrap I think b/c we were using a Github url at first. This did a full `rm -rf node_modules/ && npm i && rm npm-shrinkwrap.json && npm i artsy-error-handler@latest --save && npm shrinkwrap --dev` to try and ensure we weren't accidentally updating dependencies we didn't want to. [Yarn](https://yarnpkg.com/) anyone?
> @gnilekaw: Update error handler properly this time

- collections/bidder_positions.coffee
As a follow-up to https://github.com/artsy/gravity/pull/10612, we don't want to validate the amount you can bid against bids that have been retracted. (i.e. let's say you bid at $8,000 and $8,500 but we retract the $8,500 bid because your kid placed it while you were in the bathroom. If you bid again on that artwork, we want to allow you to place a bid at $8,500. Right now we would force you to place your next bid at $9,000).
> @mzikherman => ignore my own retracted bids when validating my price

- analytics/contact.js
- assets/analytics.coffee
- components/contact/show_inquiry_modal.coffee
- components/contact/templates/inquiry_show_form.jade
- components/inquiry_questionnaire/views/account.coffee
Closes #439 
Closes #236 
The big thing here is removing the restriction to only fire inquiry analytics when on the artwork page. 
Most of these tracking calls are namespaced so they should be fine, but the main issue is the inquiry questionnaire now gets used within the show feed, which is a little harder to single out.
> @craigspaeth - A few fixes for contact gallery buttons on the show feed.

- apps/artwork/components/commercial/index.styl
- apps/artwork/components/commercial/query.coffee
- apps/artwork/components/commercial/templates/price.jade
This PR updates price format and adds shipping info per https://github.com/artsy/collector-experience/issues/27. This is dependent on metaphysics work https://github.com/artsy/metaphysics/pull/488 which should be merged first.
Exact Price:
Range:
> @1aurabrown: update price format and add shipping info

- components/artwork_brick_rail/view.coffee
- components/merry_go_round/view.coffee
Closes #101 
See: http://flickity.metafizzy.co/options.html#accessibility
This will make it so you explicitly have to pass true to get a carousel to handle keyboard shortcuts.
> @1aurabrown - Do not handle keypress unless accessiblity is set to true

- apps/collect/client.coffee
- components/commercial_filter/views/popular_artists/popular_artists_view.coffee
- Hides 'popular artists' component on jewelry and design categories on `/collect`
- Paves way for A/B test of feature (currently a lab feature)
I had to abandon my attempt at a [parent-child mapping](https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html) between Artists and Artworks on Elasticsearch as a means of filtering artists in this component by primary media. That mapping requires that "the parent document and all of its children must live on the same shard", so it would require a complete reindexing of the Artwork index and would potentially affect ES performance more broadly in terms of traffic balancing.
The other approach would be to denormalize artist data on artwork documents in ES and I didn't consider that a worthwhile change just for an A/B …
> @mzikherman : hide popular artists on jewelry and design categories

- apps/editorial_features/routes.coffee
- models/article.coffee
This lets you preview super article drafts fully. By that I mean with its nav and sub articles. Before you were able to see the superarticle, but it would have trouble rendering the nav because its sub articles were drafts that needed to be fetched with an access token.
This makes the accessToken an option in the `fetchSuperSubArticles` method, and also fetches the super article with a token in the EOY feature.
> @craigspaeth => Allow superarticle drafts to be fully previewable

- apps/partner2/stylesheets/overview.styl
Fixes #453 
Formerly, the list of events in the New section was not correctly formatted when a bio was absent.
> Formatting for News when bio is absent

- apps/artist/queries/cv.coffee
Using the new param to make the CV tab on an artist page include those shows.
The 'exhibition highlights' section will just work, no update needed there.
> @joeyAghion => Allow artist CV to include non displayable shows

- apps/artwork/components/commercial/index.styl
- apps/artwork/components/commercial/templates/price.jade
Closes: https://github.com/artsy/force/issues/497#issuecomment-266075758
- formats text in tooltip
- uses correct label 'Price' whether the price is a range of exact price
> @kanaabe: Price label qa

- analytics/before_ready.js
- apps/editorial_features/components/eoy/stylesheets/index.styl
- apps/editorial_features/components/eoy/templates/head.jade
- apps/editorial_features/components/eoy/templates/index.jade
- apps/editorial_features/routes.coffee
- apps/editorial_features/test/components/eoy/client.coffee
- components/recently_viewed_artworks/exclude_list.coffee
- Makes sure autotrack doesn't get set to false for EOY (this is what disables Parsely tracking)
- Includes a JSONLD (what Parsely uses for metadata)
- Remove #recently-viewed-artwork: display none in favor of blacklisting
- Sets INCLUDE_SAILTHRU = true so Horizon (which tracks Sailthru pageviews) is on the page.
> @eessex => [EOY] Parsely, JSONLD, Sailthru

- models/mixins/clock.coffee
We should keep the reference to `offsetEndAtMoment` here so the clock dynamically updates when the sale closes.
> @sweir27 => fix dynamic clock state

- apps/editorial_features/components/eoy/client.coffee
- apps/editorial_features/components/eoy/stylesheets/scroller.styl
- Move video load event watcher to after body is loaded
- Intro text font size breakpoint at 900, and smaller for mobile
- Intro text margins are half size on mobile
> @kanaabe => [EOY] small bug fixes

- apps/auctions/templates/index.jade
- models/sale.coffee
- test/models/sale.coffee
For auctions with no `end_at`, we still want to show when they technically ended. This will be encapsulated by the `ended_at` field, which gets set when a sale ends.
For some reason, some past sales have a different `end_at` than `ended_at`, (or it's close to midnight so it spills over), so in the case where a sale _does_ have an `end_at`, we'll prefer that.
Here is the affected view:
> @broskoski => fix ended time for live sales

- apps/galleries_institutions/components/filter_facet/init_filter_facets.coffee
- apps/galleries_institutions/components/filter_facet/locationSynonyms.coffee
- apps/galleries_institutions/components/filter_facet/partner_filter_facet.coffee
- apps/galleries_institutions/components/filter_facet/test/partner_filter_facet.coffee
- lib/normalizeSynonyms.coffee
- test/lib/normalizeSynonyms.coffee
Fixes an issue that currently affects several of our geocoded cities, e.g…
* The geocoded name "Saint Ives" doesn't match the user input "st ives"
* The geocoded name "St. Louis" doesn't match the user input "saint louis"
Let's allow synonym-matching so that both of the above  typeahead queries will succeed:
> @gnilekaw: Allow synonyms to improve location filtering on /galleries

- apps/artwork_purchase/helpers.coffee
I didn't realized that one of the things that needed fixing in the message formatting was the fact that city, state, and zip were being displayed on different lines. This should fix!
> @craigspaeth - update city state and zip

- apps/artwork/components/commercial/index.styl
- apps/artwork/components/commercial/templates/purchase_flow_inquiry_buttons.jade
closes https://github.com/artsy/force/issues/529
gray-semibold is not a color in force, the desired color is #666 which is gray-darker-color
> @alloy make contact gallery button gray when shown with purchase button

- components/eoy_artist_list/_artist_item.jade
- components/eoy_artist_list/artist_item.styl
- components/eoy_artist_list/index.jade
- components/eoy_artist_list/index.styl
This closes the small amount of feedback @briansw had but I noticed another bigger issue came up after last night. 
https://www.dropbox.com/s/1vbef7ab19o2y5y/Screenshot%202016-12-16%2010.34.31.png?dl=0
The gravity `/artists/:id/image` endpoint is now giving an unauthorized response. @mzikherman is there a better alternative we could be using?
> @alloy - [EOY] End of year list QA (closes #569)

- apps/partner/client/artworks_filter.coffee
- apps/partner/client/filter_settings.coffee
- apps/partner/test/client/router.coffee
- apps/partner2/client/artworks_filter.coffee
- apps/partner2/client/filter_settings.coffee
- apps/partner2/test/client/router.coffee
- components/filter2/dropdown_group/view.coffee
- components/filter2/headline/view.coffee
- components/filter2/index.coffee
Previously, the `for_sale` artworks filter showed either all artworks or only ones that were for sale. 
This PR refactors it to filter:
- all artworks when `for_sale` is null,
- only for-sale artworks when it's true,
- and only not-for-sale artworks when false
> Refactors artworks for-sale filter

- components/eoy_artist_list/index.styl
> [EOY] Use the same color for anchors as text.

- apps/artwork_purchase/client/index.coffee
- apps/artwork_purchase/client/purchase_form.coffee
- apps/artwork_purchase/client/purchase_signup_form.coffee
some dumb mistakes! previously the purchase view had a user property, which i got rid of because the user object is only actually needed for a couple things in subviews, since requests automatically go to the `/me` endpoint and are associated with the user on gravity's side that way. there was one outstanding place where i didn't update the code correctly. also made a spelling mistake in an analytics event.
> @craigspaeth fix failure message typo, fix error in existing account callback

- apps/artwork/components/commercial/bootstrap.coffee
- apps/artwork/components/commercial/templates/inquire.jade
- apps/artwork/components/commercial/test/view.coffee
- apps/artwork/components/commercial/view.coffee
- apps/artwork/routes.coffee
- apps/artwork_purchase/routes.coffee
- apps/artwork_purchase/templates/main.jade
- components/embedded_inquiry/templates/attendance.jade
- components/embedded_inquiry/test/view.coffee
- components/inquiry_questionnaire/test/views/inquiry.coffee
- components/simple_contact/templates/forms/attendance.jade
fixes https://github.com/artsy/force/issues/592
I also unified the fair name in all places. in 3/4 places we were dropping the year. In one we weren't (artwork side bar mini inquiry form). @briansw let me know if that one was different for a reason.
(the fact that the icon is wrapping in an ugly way is unrelated)
> @craigspaeth change copy to past tense for closed fairs

- apps/artist/stylesheets/header.styl
Closes https://github.com/artsy/force/issues/572
We want the `<p>` tags in the blurb (except the last one) to have a space.
> @alloy => Support line-breaks for p tags in markdown for partner-submitted bios

- apps/auction_support/client/index.coffee
- apps/auction_support/templates/bid-form.jade
resolves #562 
I worked with @sweir27 on this- there are 2 buttons in this force app with the same elan class, but only one actually should be affected by the auction closed event. the other is being triggered by live auctions which trigger the same clock:is-over event when if they are live. this changes the event to only effect the artwork bid form, not the registration form.
> @craigspaeth => add more specific class for bid+registration button

- apps/editorial_features/components/eoy/stylesheets/index.styl
- Gets rid of poster styles on html5 videos
- Makes header image height auto in SA menu (was distorting aspect ratios)
> @kanaabe => [EOY] safari bugs

- analytics/artwork_purchase.js
- apps/artwork_purchase/client/index.coffee
- apps/artwork_purchase/client/purchase_form.coffee
- apps/artwork_purchase/client/purchase_signup_form.coffee
@anipetrov wants a notice sent to analytics any time that the user clicks the submit button on the purchase flow but the purchase does not submit. this may not necessarily be a request failure, it may be the modal prompting them to log in, form validation errors, etc. I also took out some promise stuff because the way they were being fulfilled was confusing and hard to debug when i was seeing uncaught errors.
> @craigspaeth better analytics messaging for purchases not completed

- apps/artwork_purchase/client/purchase_form.coffee
This adds a flag so that inquiry requests can be called out as 'purchase requests' (primarily for use in CMS Inbox UI).
> @1aurabrown => Add purchase flag to inquiry request

- analytics/artwork_purchase.js
- apps/artwork_purchase/client/index.coffee
see original pr here: https://github.com/artsy/force/pull/611
i was using the wrong name of the analytics hook, really dumb mistake. i wanted to be using this one: https://github.com/1aurabrown/force/blob/d1edc3852d0f751fa4f75392f34b88051d15b1b4/analytics/artwork_purchase.js#L25. i thought everything was working because there is a listener for all analyticsHooks events which prints whatever is sent to it (the messages in the image above prefixed `ANALYTICS HOOK`). However I wasn't using an event that had a specific handler and `analytics.track` was never being called for these events.
Also, joey maybe you have the answer to this: I took out the user from the data being passed to the analytics event in the case of a user who attempts to make an account with an email already associated with …
> @joeyAghion: fix analytics bug

- apps/fair/components/browse/view.coffee
- apps/gene/client.coffee
- apps/tag/client.coffee
When set to `false` as the default this filter was giving the wrong count. 
Fixes #615 
See https://artsy.slack.com/archives/help/p1482416501000230.
> Removes default forSale filter from gene, tag and fair filters

- npm-shrinkwrap.json
- package.json
For some reason npm decided to install this on an alpha verison with breaking changes.
> @broskoski: Move cookie-session down to stable version

- components/article/client/view.coffee
In [this commit](https://github.com/artsy/force/commit/2506fca055403408c6fc5321a3de39f781805119) I tried cleaning up a bit but ended up slightly changing the logic and introducing a bug with portrait image heights.
> @kanaabe => Restore portrait resizing logic

- Makefile
`make oss` was returning a '500 internal error' because the web server is looking for a local API server. Changed it to point to staging.
`make spd` & `make ssd` the option to specify a Procfile to `nf` is `-j` not `-f` so debugging wasn't working
> @alloy - Fixes some commands in Makefile

- components/feedback_modal/index.coffee
- components/feedback_modal/tests/index.coffee
- components/multi_page/config.coffee
- components/multi_page/index.coffee
- components/multi_page/test/view.coffee
- components/multi_page/view.coffee
- components/multi_page_modal/index.coffee
closes: https://github.com/artsy/collector-experience/issues/71
I have this as WIP because it could use a spec or two. I wanted to get feedback before investing in writing the tests though.
**Remove the “Need more immediate assistance? Please contact us” option:**
**Selects the 'Selling On Artsy' page by default when clicked launched from the 'Send us feedback':**
> @broskoski: 'Send us feedback' faq bugs

- apps/artist/client/cta.coffee
- apps/artist/queries/server.coffee
- assets/artist.styl
- components/artist_page_cta/index.styl
- components/artist_page_cta/template.jade
- components/artist_page_cta/view.coffee
PR early and often!
As discussed, we will always be showing this new functionality to any users with the lab feature. At the end, we can switch that to be the correct condition. This and future PR's (until launch) are operating in that way.
> @alloy => Display new CTA bar on artist page when lab feature is present

- components/artwork_item/templates/artwork.jade
- components/commercial_filter/queries/artwork.coffee
Closes https://github.com/artsy/force/issues/641
It looks like this might have been a bug for a while? This code (`artwork_item`) is used in several contexts, some from Metaphysics and some from not.
The Metaphysics context just coerces the GraphQL JSON into a Backbone Model. We override the `type` here: https://github.com/artsy/metaphysics/blob/b0436d6920c69ac3fde882d3096a1d2cde16762e/schema/partner.js#L52-L61
So I just added that condition below, this fixes the issue.
Really though it's just a bandaid, we should consolidate this code, switch to using `is_biddable`, etc.
> @alloy => Support alternative partner type for Bid Now label on /collect

- apps/artist/client/router.coffee
- apps/artist/queries/overview.coffee
- components/artist_page_cta/index.styl
- components/artist_page_cta/overlay.jade
- components/artist_page_cta/row.jade
- components/hover_pulldown/index.styl
This adds the pseudo feed for the artist page CTA overlay screen. You'll notice the caret just borrows the standard one for now...I was faffing around getting the CSS for that working and I was struggling a bit, will circle back!
Up next, the actual sign up form on the right hand side.
> @alloy => Include pseudo feed in artist page CTA overlay

- apps/article/client/index.coffee
- components/articles_grid/stylesheets/index.styl
- components/channel_nav/index.styl
- components/email/stylesheets/editorial_signup.styl
- components/email/stylesheets/gallery_insights.styl
Closes https://github.com/artsy/force/issues/648
- GI CTA is responsive
- GI page has responsive body class
- Update articles-grid max-width breakpoint (to allow for some l/r spacing)
> @kanaabe => Responsive Team Channels/ CTA

- apps/artwork/components/commercial/index.jade
- apps/artwork/components/commercial/templates/index.jade
fixes https://github.com/artsy/force/issues/491
each individual sub-template has its own checks for whether or not to display, so i don't think this will cause anything to be shown when it shouldn't.
> craigspaeth: display sale message for sold works

- components/artist_page_cta/index.styl
- components/artist_page_cta/templates/register.jade
- components/artist_page_cta/templates/register_footer.jade
- components/artist_page_cta/view.coffee
Because we're only showing this for logged-in users with the lab feature, it's a little funky when you click the 'Facebook' button. That basically just links your currently logged in account successfully.
However, I temporarily removed the logged-in guard, and verified that it successfully signs you up.
Up next:
- the payoff screen!
Something I'm realizing, is that successful login/signup via Facebook will redirect you, so I actually need to make the payoff screen a stand-alone server-side rendered page so that you can get successfully redirected to it.
> @alloy => Finish up facebook and login modal on signup screen of artist page CTA

- apps/artist/client/index.coffee
- apps/artist/index.coffee
- apps/artist/routes.coffee
- apps/artist/stylesheets/index.styl
- apps/artist/templates/payoff.jade
cc @alloy 
I'll self-merge, this is a start to the payoff screen. It's going to be a stand-alone page that after a successful signup/login you'll get redirected to.
It brings in the home page component directly, and so it's sort of functional(!), although it'll need to be modified.
As discussed, because this is a stand-alone new page (scaffolding set up in this PR), and its basically just using the existing component with some modifications, it could be a good task for someone else (Luc) to take on/pair.
> @mzikherman => Standalone route for artist page CTA payoff

- models/article.coffee
#minor Parse.ly, our analytics tool for Editorial recently made a change to their crawler and they want us to provide absolute urls now instead of relative ones.
> @xtina-starr => Provides Parse.ly with an absolute url

- apps/articles/stylesheets/team_channel.styl
- apps/articles/templates/team_channel.jade
- components/channel_nav/index.styl
- components/main_layout/footer/index.styl
Following up on https://github.com/artsy/force/issues/628
- Adds new max width to home pages for team-channels
- Footer menu matches width of team channels, and displays mobile menu 
It looks like the mobile footer defaults to display: none everywhere, do you know why this might be?  I enabled it for team-channel pages only.
> @kanaabe => Team channel home

- apps/fair_organizer/routes.coffee
Closes https://github.com/artsy/collector-experience/issues/79
Closes https://github.com/artsy/collector-experience/issues/78
I guess this never came up because fairs were always created in the order that they happened. Now we explicitly pass in `-start_at` to get the fair order we expect.
> @mzikherman - Explicitly sort fairs by reverse chron start_at

- Makefile
- npm-shrinkwrap.json
- package.json
Makefiles will try to run `$(shell ...)` commands in a first step ([read more](http://stackoverflow.com/questions/9081841/makefile-assign-command-output-to-variable)) before running things which causes a race condition in our deploy script. I'd like to move us off these Makefiles into package.json anyways, so I'm just going to let the script be split up in Semaphore.
> @craigspaeth: Remove deploy tasks and just let it be split up in Semaphore

- apps/artist/routes.coffee
- apps/artist/test/routes.coffee
- components/artist_page_cta/templates/register.jade
- components/artist_page_cta/view.coffee
- npm-shrinkwrap.json
- package.json
Last bit of functional work needed for the CTA!
Up next:
- address some largely visual QA in https://github.com/artsy/force/issues/688
- add analytics/AB test with @anipetrov 
This PR:
- bumps artsy-passport for a fix that didn't let you skip onboarding after social auth
- maintains the current filter state (like `?medium=works-on-paper`) through the /payoff and /follow screens
> @xtina-starr => Bump artsy-passport for redirect bug, and also maintain current filters

- lib/routers/hardcoded_redirects.coffee
We have to do this to work around not being able to create shortcuts for certain pages. I wonder if we should drop this [blacklist in Gravity](https://github.com/artsy/gravity/blob/c9d9487efb2eaf15d520afc481b905b6cf1757fd/app/models/util/handle_blacklist.rb) and replace these hard-coded redirects with shortcuts 🤔
> @mzikherman: Change /press redirect

- Dangerfile
Spotted in #700 that you got a Danger warning, but had assigned someone. This should not raise a warning.
> Improves Danger rule about assignees

- apps/show/components/artwork_columns_metaphysics/view.coffee
`is_inquireable` was missing from this metaphysics query, which caused artworks on partner show pages to not render an [inquire link](https://github.com/artsy/force/blob/master/apps/show/components/artwork_item_metaphysics/templates/artwork.jade#L23) to contact the gallery.
> Adds `is_inquireable` to graphql query

- components/fair_layout/templates/head.jade
- components/main_layout/templates/head.jade
- components/prevent_right_click/README.md
- components/prevent_right_click/index.jade
- lib/global_client_setup.coffee
One of Yulia's partners was able to do this, and the only theory I can come up with is they managed to right click before the main JS payload downloads. Yulia also pointed out that in deep zoom mode you can apparently right click save canvas to an image, so we prevent on `img` and `canvas` tags now.
> @broskoski: Load prevent right click early and prevent right clicking on canvas

- analytics/partner.js
- apps/partner2/templates/contact_info.jade
Per the conversation during sprint planning meeting, this adds analytics to the contact gallery via email link and the gallery website.
> @alloy add analytics to email gallery link and gallery website

- components/article/stylesheets/image.styl
- components/article/stylesheets/index.styl
Closes https://github.com/artsy/force/issues/707
- moves all image-component styles into their own sheet
- fixes caption margins for 'column_width' images
> @kanaabe => Article image styles

- analytics/criteo.js
A couple fixes from Criteo.
First, we intended to track viewItem event for our Auctions feed AND Artworks feed on artwork pages, but Criteo won't accept this.  So, on [L55](https://github.com/artsy/force/compare/master...OLI9292:criteo_updates?expand=1#diff-15c581b95b1b523b1ab4c35946c5a9a2R55), we send the Auctions account ID if the artwork is in an auction, otherwise we send the Artworks account ID.
Second fix is changing `inquiry:sync` to `inquiry:sent` on [L88](https://github.com/artsy/force/compare/master...OLI9292:criteo_updates?expand=1#diff-15c581b95b1b523b1ab4c35946c5a9a2R88) to properly track an inquiry.
Also added some comments to document the path splits.
> @anyone Criteo updates

- apps/artist/test/meta.coffee
- apps/collect/test/meta.coffee
- apps/feature/test/templates/meta.coffee
- apps/page/test/meta.coffee
- apps/show/test/meta.coffee
- apps/shows/test/meta.coffee
- components/auction_lots/test/templates/artist-meta.coffee
Another step towards the Force + MG merger. We were using [process.cwd()](https://nodejs.org/api/process.html#process_process_cwd) to dig into directories from the root of Force. Luckily this was an old habit we didn't repeat many places. This works okay for Force because tests are run from the root directory, but merging the apps changes directory structure slightly which breaks this, and in general it's a bad practice to have your code dependent on which  directory it's being run from.
> @kanaabe: Replace process.cwd() with relative paths #minor

- apps/editorial_features/components/eoy/client.coffee
When running the Force + MG merge I think it's pulling in a different version of jQuery and the tests are complaining here with `Uncaught Error: Syntax error, unrecognized expression: .scroller a[href*=#]:not([href=#])`. It's a simple fix to just add quotes around the attribute selector here to make it 💚
> @eessex: Update selector to make test happy #minor

- analytics/criteo.js
The analytics trigger `inquiry:sent` is not triggered on a sent inquiry.  The trigger [here](https://github.com/artsy/force/blob/master/components/contact/inquiry.coffee#L50) is what we want (and we had before), but it's hook is concatenated with `inquiry_questionnaire` to make the correct hook `inquiry_questionnaire :inquiry:sync`, whereas before we just had `inquiry:sent`.
> @anyone final change to criteo tracking code

- analytics/criteo.js
this from Jeremy: "Just checked and the conversion tag is now firing BUT it’s not passing the Transaction ID – everything else is correct, but this is the one last piece of the puzzle to be fixed."
The Transaction ID must be unique.
I think we can use the `inquiry.id`.  Inquiry seems to be passed into this trigger [here](https://github.com/artsy/force/blob/master/components/contact/inquiry.coffee#L50), although when I test on staging I get "There has been an error" and `jquery.js:8630 POST https://stagingapi.artsy.net/api/v1/me/artwork_inquiry_request/send 405 (Method Not Allowed)` so I haven't been able to confirm that `data.inquiry.id` is available.  Although, it's use [here](https://github.com/artsy/force/blob/master/analytics/inquiry_questionnaire.js#L181) makes me believe it is.
cc …
> @craigspaeth add transaction id for criteo

- apps/how_auctions_work/templates/index.jade
- apps/page/template.jade
- apps/press/templates/index.jade
- apps/search/templates/template.jade
- apps/static/templates/christies.jade
- apps/static/templates/future_of_art.jade
I must have not save all'ed correctly one some of my search + replace. I searched through the rest of the codebase for `- assetPackage = (.*)`  and diffed that against what `ls assets` returned and uncovered a couple places, such as the search results page, that were still pointing to old assets packages. 😅  my bad.
> @kanaabe: Rename remaining asset packages to their consolidated ones

- apps/article/templates/promoted_content.jade
- apps/article/test/client/index.coffee
Oops! Looks like the href was attributed to the button instead of the `<a>` 🙈
> @eessex => Promoted content link bug

- assets/auctions.coffee
Most of our client-side code is wrapped in an `init` function to defer running code for ease of testing/loading. In my refactor fury I accidentally assumed this was the same for Auctions2. This simply wraps that in a function to achieve the same thing, but I think ideally we'd thin out some of the root-level auctions2 code and wrap it in a `export default () =>` as I started to allude to in [my PR comment](https://github.com/artsy/force/pull/727#discussion_r97174703).
> @sweir27: Defer auctions2 client-side require

- apps/artwork/components/images/helpers.coffee
- apps/artwork/components/images/image_filename_map.coffee
- apps/artwork/components/images/templates/image.jade
- apps/artwork/routes.coffee
Closes #743 
The idea is to add more descriptive filenames to encourage google to index images on the artwork pages 🙏 
Filenames come from: https://docs.google.com/spreadsheets/d/1TtGEMZKEc2AjAj9JB-ri4b3WixYejgFkS9kCyDUAciE/edit#gid=0
> @mzikherman - Add manual test for custom artwork image filenames

- apps/feature/client/view.coffee
- components/artwork_columns/template.jade
- components/artwork_columns/view.coffee
- components/artwork_item/templates/artwork.jade
- components/artwork_item/templates/partials/lot_number.jade
- components/artwork_item/test/artwork.coffee
I still think we could fix some naming because this logic/name is a little odd. But apparently we do use this set on the /consign page!
Fixes it:
>  @craigspaeth => switch back to referencing the auction artwork set

- apps/artist/client/cta.coffee
- components/artist_page_cta/index.styl
- components/artist_page_cta/view.coffee
This finishes the initial animation of the bumper, leaving just that opacity overlay thing.
I'm not 100% sure if this is the 'best' way to do it. There's already transition on the CTA bar, so I added an 'initial' class that has it hidden, so removing that class causes it to animate in. Currently it's just rendered/appended, so you don't really see that transition at all.
However...I couldn't figure out a good time to remove that initial class. Even with just using `setTimeout`, it seems like sometimes the browser is still painting the artist page (images, client-side JS stuff, etc.), and so the animation is not super smooth all the time, but it's not bad.
> @1aurabrown => Animate initial CTA bumper

- package.json
@gnilekaw and I have been troubleshooting an issue where certain Artist Bios are disappearing from the Artist detail page. It's tricky to reproduce this issue, here's what I've had success with:
```
zero
one
two
three
four
```
I set one artist to have that bio and another artist to have one fewer lines. The former will have their `partner-artist-blurb` be empty and the latter works as expected. Upgrading the library fixed this bug, but there's a regression. Even though we're providing `ellipsis: ''` in our config object, an ellipsis is showing up.
So, what we're wondering, @mzikherman, is if you have any context here that we're missing and the reason for the forking of the library in the first place.
> [WIP] The Mysterious Case of Disappearing Artist Bios

- components/buyers_premium/index.coffee
- components/buyers_premium/index.styl
- components/buyers_premium/test/index.coffee
- components/my_active_bids/view.coffee
The dots get cut off in some cases, causing the buyers premium view to appear like there is no buyers premium for certain price points when this view is embedded in microgravity and eigen:
This changes the view to just have a colon and then the percentage. We can change this later, but for now this should avoid issues/bidders claiming they don't owe money.
> @broskoski => get rid of dots in buyers premium for now

- npm-shrinkwrap.json
- package.json
Fixes a problem in production where a variable is set to `param` and should be `params`
> @alloy - Update artsy passport

- package.json
Updated AP to include [passing user agent for signup/login](https://github.com/artsy/artsy-passport/pull/99).
> @broskoski: Bump Artsy Passport.

- apps/artist/client/index.coffee
- apps/home/components/followed_artists/search_artists_view.coffee
- apps/home/components/followed_artists/templates/result.jade
- apps/home/components/followed_artists/view.coffee
- components/artist_page_cta/query.coffee
This updates the follow analytics on the homepage widget to have the correct properties (and a different `context_module` for its use in the artist page CTA).
> @anipetrov => Fix follow artist analytics tracking on the homepage/artist CTA widget

- apps/home/index.coffee
- apps/home/templates/hero_unit.jade
- apps/home/test/templates.coffee
I added [randomized homepage banners](https://github.com/artsy/force/pull/768) by refactoring them to use Metaphysics. Unfortunately, this introduced a [regression to markdown support](https://artsy.slack.com/archives/help/p1485531304000831)—so this adds it back with a test.
> @xtina-starr: Support markdown in hero unit template

- apps/home/routes.coffee
- apps/home/test/routes.coffee
- lib/metaphysics.coffee
- test/lib/metaphysics.coffee
We have this `maybeFetchHomepageRails` function that tells the homepage to continue rendering in case fetching certain homepage rails didn't succeed—which seems to be more common when logged in b/c that data varies depending on the user requesting it. When I refactored hero units to MP I looped it into the same query here, which caused that behavior to continue without homepage rails _and_ hero unit data. Not clear to me why we catch failed homepage rails, but maybe @broskoski knows off hand.
This refactors it to pass through the hero unit data in the error case—fixing that `.length of undefined` bug you spotted.
> @anandaroop: Fix uncommon session based homepage bug

- models/article.coffee
Captions are appearing twice in IA's because we don't replace `<p>` with `<h1>`
> @eessex => Fix ImageCollection captions in IA

- Makefile
- apps/artwork/components/commercial/query.coffee
- apps/artwork/components/commercial/templates/inquire.jade
- apps/artwork/components/commercial/templates/price.jade
- apps/artwork/components/commercial/test/fixtures/inquireable.json
- components/contact/default_message.coffee
- components/contact/test/default_message.coffee
This is now all that's needed to display the appropriate sale messaging on the artwork page (cc @xtina-starr this may help you for the microgravity artwork page).
Still to do:
- move the pre-filled inquiry text (based on availability) up to Metaphysics (for use in multiple clients)
- update pre-filled inquiry text in Force to use that
This PR is probably mergeable w/o the above steps, but no rush- let's hold this open for those issues as well.
> @broskoski => Proper sale_message display on artwork page + inquiry update

- apps/artwork/components/commercial/templates/inquire.jade
Reported by @tayapage6 , in the case of states where there's no pre-filled inquiry text, we shouldn't show any textbox in the embedded form.
> @broskoski => Dont display blank textbox for inquiry

- components/artwork_item/test/artwork.coffee
- models/artwork.coffee
- test/models/artwork.coffee
Luckily the [artwork_item_metaphysics](https://github.com/artsy/force/blob/67cf6e19ca5848b35a65d48a184e0ad1c53cad51/apps/show/components/artwork_item_metaphysics/templates/artwork.jade#L22-L27) component in the show app already handles the 'simple' rendering.
This is what's used in the legacy 'artwork item' contexts.
> @broskoski => Update legacy sale messaging for new inquireability logic

- components/article/stylesheets/image.styl
fixes https://github.com/artsy/force/issues/799
now all images will have the same space below them that previously was only given to images with a caption
> @kanaabe margin below images instead of below caption

- components/artwork_metadata_stub/templates/didactics.jade
fixes https://github.com/artsy/force/issues/797
@broskoski I know you are working on standardizing artwork metadata components. This might just be a temporary fix that might later get incorporated into your changes, but there was an issue open for it so I wanted to fix it for now. Works that are/were part of an auction should _only_ look one of the following ways, none of which include the `sale_message`:
> @broskoski suppress sale message when auction info is displayed

- components/artist_page_cta/index.styl
it should be flex-shrink, and it should also be shrinkable. flex-shrink 0 breaks things but I didn't realize that because it was mistyped.
> @mzikherman fix typo

- apps/artwork/components/banner/helpers.coffee
- apps/artwork/components/banner/index.jade
- apps/artwork/components/banner/test/helpers.coffee
This PR addresses this issue: https://github.com/artsy/force/issues/834#issuecomment-278696349 cc @katarinabatina @briansw  
The fix was just to be clearer with the logic around whether or not the timer should be shown. Right now, it is shown in all cases _except_ once the live auction integration part has started, because at that point we don't have an `end_at` so we can't count down to anything. 
The states of the timer on the artwork/auction page are:
**Preview: Before auction opens**
**Online-only auction: After auction starts, before auction closes**
**Live auction integration: After auction starts, before live auction starts**
**Live auction integration: After live auction has begun**
> @damassi => fix timer on artwork page

- lib/middleware/redirect_mobile.coffee
Solves https://github.com/artsy/force-merge/issues/21
We inspect the routing stack of this `redirect_mobile` middleware in force-merge to see if we should route the request to the Force or MG app. Currently when MG 404s we embed the Force view in it, so these responsive about/* pages worked by falling through to that, but we should really explicitly define it here.
> @anandaroop: Add about/* to responsive pages

- models/artwork.coffee
Fusion is this little service that keeps a stale copy of Gravity's artwork data for the [sake of serving sitemaps](https://github.com/artsy/gravity/pull/9196#issuecomment-143883082). Pre-metaphysics it would help keep its data fresh by being swapped in place of /api/v1/artwork/:id requests (it also falls back to proxying Gravity). Now-a-days it just [crawls the latest artworks](https://api.artsy.net/api/v1/artworks?sort=-created_at) daily and lets the data eventually get somewhat in sync.
Ashkan noticed [an issue](https://github.com/artsy/force-merge/issues/24) in staging where it was requesting from Fusion (which doesn't have a staging version) and therefore returning a 404. So just simply removing it from the artwork model to address this.
> @broskoski: Remove Fusion url from artwork model

- components/marketing_signup_modal/index.styl
By changing the background-size from cover to `background-size: 100% 100%` in [the last PR](https://github.com/artsy/force/pull/826), the modal image loses the responsiveness and cause the image to stretch. I set the property back to cover, but this hides the photo credit on the image. I then tried to set the background-position-y property to bottom, but this causes a just a tiny bit of whitespace beneath the image. Do you have any ideas for getting this just right?
> Modal image

- models/sale.coffee
- test/models/sale.coffee
This fixes the calendar link on the auction page to set events in Eastern Time (same as how we show it on the overview page).
Someday maybe we can do better-- i.e. using the timezone of the browser or specified by user or auction, but this is at least better than UTC.
> @mzikherman => fixes calendar to be in same time zone as the sale start label

- apps/auction/stylesheets/my_active_bids.styl
- apps/auction/templates/my_active_bids.jade
- apps/auctions/stylesheets/index.styl
- apps/user/pages/auctions/index.styl
- components/my_active_bids/index.styl
- components/my_active_bids/template.jade
Fixes https://github.com/artsy/force/issues/843 
This update the my active bids module to cap the div width so it now looks like:
> @mzikherman => fix long artist name overflow in "my active bids" module

- Dangerfile
Since we're now deploying from CI (as usual), but being triggered via a GitHub PR from master -> deploy, it'd be cool if CI could run Danger, which on these PRs would post a comment listing the PR's that will be deployed.
> @orta => Post a markdown comment from Danger listing PRs on deploys

- apps/artwork/components/banner/index.jade
- apps/artwork/components/banner/query.coffee
Should fix: https://github.com/artsy/force/issues/834
Instead of "Explore Auction"
Before auction is live:
> @damassi => artwork page callout should say "Join Live Auction" if auction is live

- config.coffee
- lib/middleware/proxy_to_merged.coffee
- lib/setup.coffee
- test/lib/middleware/proxy_to_merged.coffee
Addresses https://github.com/artsy/force-merge/issues/6 without going down the rabbit hole of attempting to put a full on HAProxy/Nginx instance in front of Force and all of the DNS/session/config involved in attempting that. This simply uses [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) to achieve a similar result where we can move over traffic by tuning up the `FORCE_MERGE_WEIGHT` config. The idea here is that we can get some real traffic stress testing the merged codebase this week before flipping the switch (by no means meant to be permanent).
> @broskoski: Middleware to proxy merged.artsy.net so we can drive traffic incrementally to it for testing purpose

- .travis.yml
Since, until the consolidation, we'll have Travis running Danger and Semaphore running tests + deploys, remove the tests from Travis. Eventually, we'll just be on Travis for everything.
> @mzikherman => Dont run tests on travis for now

- lib/middleware/proxy_to_merged.coffee
- test/lib/middleware/proxy_to_merged.coffee
This took way too long to hunt down but Node Http Proxy was having a hard time when pointing to a Heroku app because the way Heroku's routing layer works with it. More explained in [this SO question](http://stackoverflow.com/questions/6444280/heroku-no-such-app-error-with-node-js-node-http-proxy-module).
> @broskoski: Set host header when proxying to Heroku for merged Force

- lib/setup.coffee
Because it avoids overhead and more importantly forces the proxied force merge to be under SSL too.
> Move SSL + WWW middleware up

- apps/partner2/components/fixed_cells_count_carousel/test/view.coffee
- apps/partner2/components/fixed_cells_count_carousel/view.coffee
fixes https://github.com/artsy/force/issues/855
The issue was, we already had code in place to allow for the rails on the gallery pages to be populated by multiple fetches (id, one fetch with parameters to return only current shows, another for upcoming). The intent was for the results from the first fetch to precede the results from the second. However there was a race condition between multiple fetches performed in parallel, and whichever results were returned first would be displayed at the beginning of the carousel. I modified things to preserve the ordering of the results _after_ all parallel fetches are complete.
> @anadaroop preserve ordering of multiple buckets in partner rails

- package.json
Otherwise we get `Uncaught Exception ReferenceError: Unknown plugin "inline-react-svg" specified in "/app/package.json" at 0, attempted to resolve relative to "/app"` taking merged.artsy.net down (not clear to me yet why staging is working—maybe NODE_ENV=staging installs dev dependencies).
And now for a philosophical rant that I encourage anyone to participate in:
We encountered a, somewhat, related issues when trying to use WebPack to import stylus files in Prediction. This caused trouble on the server-side and sent us down a whole world of pain trying to compile the server with Webpack. I think it highlights an interesting part of writing universal JS—where do you draw the line of tricking out the language itself and do you try to target a platform like "Node.js or Modern Browser …
> Move inline-react-svg to prod dependencies

- .env.oss
- desktop/models/artwork_inquiry.coffee
- desktop/test/models/artwork_inquiry.coffee
It appears as if most of our use of `inquiry.send` expects the inquiry to be saved before—which seems to happen in the more involved inquiry flows. However, in the case of the uninvolved auction lot inquiry, the inquiry appears to be new. To fix this I've implemented a `if @isNew() then @save()` check at the Backbone model layer.
> @joeyAghion: Make sure to save the inquiry first before sending

- desktop/components/article/stylesheets/content.styl
Trying this one again!
Removes background color from article's embed containers.
> @craigspaeth => Remove embed background

- circle.yml
Installing ruby 2.3.1 and the danger gem before test caused the issue below:
```
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Error loading RubyGems plugin "/opt/circleci/.rvm/gems/ruby-2.3.1/gems/gem-wrappers-1.2.7/lib/rubygems_plugin.rb": cannot load such file -- gem-wrappers (LoadError)
```
The root cause is unknown, but seems to be related to the `rvm install ...` command that runs in the dependencies phase. There is no reason why we shouldn't use the default ruby, so let's not switch the version and use the default one.
> Do not attempt to switch a ruby version

- desktop/apps/article/templates/amp_mixins.jade
- desktop/config.coffee
- desktop/lib/setup_sharify.coffee
This adds Parsely tracking to our AMP pages alongside Segment. I've checked in with Parsely support and this was their recommendation in order to bucket correctly.
> @eessex => Adds parsely analytics to amp pages

- desktop/apps/artist/client/views/cv.coffee
- desktop/apps/artist/client/views/overview.coffee
- desktop/apps/artist/templates/sections/overview.jade
Closes https://github.com/artsy/force/issues/938
Basically, we were using the `shows` part of the statuses to determine whether we should even be rendering or fetching that data.
`shows` status is correctly defined as having any shows on Artsy. The `cv` status is correctly defined as having any shows period (whether they are reference or not is immaterial). That is useful to be able to render the tabs.
However, since ref shows can show up in the overview/exhibition highlights and in the CV tab, relying on _just_ the `statuses.shows` property to determine whether to fetch/render those pieces is off for artists with just reference shows. So this updates several of those places to consider both.
> @broskoski => Render exhibition highlights and CV when only ref shows are present

- desktop/apps/shows/index.coffee
- desktop/apps/shows/routes.coffee
- desktop/apps/shows/test/routes.coffee
This adds a redirect from `/city/...` paths to `/shows/...`. This was motivated by our realization (see https://github.com/artsy/gravity/pull/10824#discussion_r102097667) that all search result types _except cities_ could be easily perma-linked like `/:type/:slug`. For cities, the search results instead link to URLs like `/shows/new-york-ny-usa`.
In #seo and #web channels, there was mild agreement that it would be good to support the more conventional `/city/...` route as well, at least as a redirect, and maybe even as a more general landing page eventually that reflects, e.g., local galleries as well as local shows. (In addition, this change helps us avoid duplicating route logic in other systems.)
I briefly experimented with also marking the new route as `isResponsive` (in …
> @craigspaeth: Redirect from /city/:slug to /shows/:slug for consistency

- desktop/apps/fairs/query.coffee
- desktop/apps/fairs/templates/current_fairs.jade
- desktop/apps/fairs/templates/fair_upcoming.jade
- desktop/apps/fairs/templates/past_fairs.jade
Address: https://github.com/artsy/waves/issues/117
The [Geocoder gem](https://github.com/artsy/gravity/blob/master/app/models/domain/location.rb#L49-L62) in gravity is returning a `nil` value for cities with Hong Kong coordinates. This is a patch to fallback to the country when the city isn't return. I think it's worth investigating why `nil` gets return for Hong Kong cities but this is a quick fix for now.
**Fair's addition in past fairs**
> @craigspaeth: fallback to country when fair city location is not available

- desktop/apps/home/stylesheets/hero_units.styl
When hovering over the `home-hero-unit` cta, the text doesn't flip when the button color is filled:
Fixed by making the button color text black:
> @craigspaeth => [Bugfix] Home hero button hover state

- desktop/apps/articles/client/magazine.coffee
- desktop/apps/articles/client/section.coffee
- desktop/apps/articles/client/team_channel.coffee
- desktop/apps/articles/routes.coffee
- desktop/apps/fair/client/articles.coffee
- desktop/apps/partner/client/articles.coffee
- desktop/apps/partner/client/view.coffee
- desktop/apps/partner/test/client/view.coffee
- desktop/apps/partner2/client/articles.coffee
- desktop/apps/partner2/client/view.coffee
- desktop/apps/partner2/test/client/view.coffee
This is a follow-up to https://github.com/artsy/positron/pull/951. For views that use `ArticleFeedView` and `ArticleGridView`, we'll need `count`. This is safe to merge regardless of if https://github.com/artsy/positron/pull/951 is deployed yet since it will ignore the field until available.
> @eessex => Adds count flag to article fetches when needed

- desktop/apps/artwork/stylesheets/index.styl
- desktop/apps/artwork/templates/index.jade
- desktop/apps/artwork/templates/metadata.jade
This fixes an issue where we were seeing the new 4-column layout extend to pages that were not related to Auctions. 
To test: 
```sh
git checkout -b damassi-artwork-auction-layout-fix master
git pull https://github.com/damassi/force.git artwork-auction-layout-fix
yarn start
```
Then navigate to: 
- Artwork that is in an Auction: http://localhost:5000/artwork/jack-tan-painting?auction_id=worlds-biggest-mauction
- Artwork that isn't, retaining side "sticky" column: 
- http://localhost:5000/artwork/pierre-jeanneret-conference-armchair
- http://localhost:5000/artwork/quayola-natures-number-3b
- http://localhost:5000/artwork/arne-jacobsen-egg-chair
@sweir27 / @erikdstock - if either of you know how to navigate into the less-known-about artwork pages for test can you let me know? I've navigated …
> Fix Artwork layout for non-sale artworks 

- desktop/apps/artwork/client/index.coffee
- desktop/apps/artwork/client/test/index.coffee
- desktop/apps/artwork/components/auction_artworks/helpers.coffee
- desktop/apps/artwork/components/auction_artworks/index.jade
- desktop/apps/artwork/components/auction_artworks/query.coffee
- desktop/apps/auction/test/templates.coffee
This PR finishes up #969 by 
- Taking associated artwork lots and sorting them first by artists that you follow and then everything else
- Returning the total number of lots and adding it to the "View All Lots" button 
```sh
git checkout -b damassi-cp-artwork-sort-auction-lots master
git pull https://github.com/damassi/force.git cp-artwork-sort-auction-lots
yarn start
```
1. Log out
1. Navigate to http://localhost:5000/auction/example-auction
1. Click into an artwork from the sale 
1. Make sure everything loads, and the associated lot artworks are coming back randomized and no page errors (fetching favorites without a favorite will throw)
1. Log in 
1. Favorite an artist from the sale 
1. Refresh and notice that that artist is always first in the queue 
1. If you have favorited multiple …
> Artwork Sale Lot Sorting 

- desktop/apps/sitemaps/routes.coffee
Looks like this one got missed in the move when we made `count` optional in positron's api.
> @dblock => Add count flag to sitemap article fetch

- desktop/apps/sitemaps/routes.coffee
- desktop/apps/sitemaps/test/routes.coffee
What if https://github.com/artsy/collector-experience/issues/62 was just a CR+LF problem?
```
curl https://www.artsy.net/robots.txt
User-agent: *
Noindex: ?sort=
Noindex: ?dimension_range=
Disallow: ?dns_source=
Disallow: ?microsite=
Disallow: ?from-show-guide=
Sitemap: https://www.artsy.net/sitemap.xml
Sitemap: https://www.artsy.net/images_sitemap.xml~/source/artsy/force/dblock (sitemap-crlf)$ 
```
> Added CR+LF to sitemaps.txt.

- desktop/apps/article/templates/amp_mixins.jade
- desktop/config.coffee
- desktop/lib/setup_sharify.coffee
We created a new Segment source that has a server type. The `SEGMENT_AMP_WRITE_KEY` points to this new source. This is required by Segment in order to send AMP analytics to GA.
> @wrgoldstein => Replace Segment Write Key with AMP-specific one

- desktop/test/models/mixins/image_sizes.coffee
Setting up an SEO experiment via https://github.com/artsy/barium-ion in which we added a "slugged" version for about 4000 artworks from a single sitemap. The goal of this PR is to make both the website and the sitemap to use that version as the preferred image version with the hope that google will like a file name such as `artist-artwork-title.jpg` more than `larger.jpg`. We don't currently have a plan of how to operationalize this if it works.
This also fixes a bug in the tests where `@model.imageUrlFor('large.jpg')` would always return `large`, that function takes a min width and height, not a JPG.
> Prefer slugged images where available.

- desktop/apps/auction2/actions.js
- desktop/apps/auction2/client.js
- desktop/apps/auction2/components/auction_artworks/index.js
- desktop/apps/auction2/components/auction_grid_artwork/index.js
- desktop/apps/auction2/components/auction_list_artwork/index.js
- desktop/apps/auction2/components/basic_checkbox/index.js
- desktop/apps/auction2/components/bid_status/index.js
- desktop/apps/auction2/components/filter_sort/index.js
- desktop/apps/auction2/components/header/index.js
- desktop/apps/auction2/components/range_slider/index.js
- desktop/apps/auction2/components/sidebar/index.js
- desktop/apps/auction2/components/sidebar/index.styl
- desktop/apps/auction2/filter_query.js
- desktop/apps/auction2/queries/sale.js
- desktop/apps/auction2/reducers.js
- desktop/apps/auction2/stylesheets/index.styl
- desktop/apps/auction2/test/reducers.js
Looks like a lot, but it's mostly just little things + cleanup:
- Updated our `filter_query` to point to the `filter_sale_artworks` endpoint instead of the `filter_artworks` endpoint. The fallout from this is that I renamed the top-level array to `saleArtworks`, and had to update a bunch of the references.
- Added a checkbox for "Artists You Follow" (which only shows up if you are a logged-in user)
- Updated the filter sort component to slide up and down depending on which item is selected.
- Updated the range slider use `sale.currency`, which is still a bandaid (albeit better). A forthcoming gravity PR will export `symbol` in a sale's JSON so we can use that.
- It now jumps to the top of the "My Active Bids" section when you select a checkbox or use the jump arrow
- Following @damassi's …
> Switch to using new sale artworks endpoint and some little cleanup

- desktop/apps/auction2/components/auction_grid_artwork/index.styl
- desktop/apps/auction2/components/auction_list_artwork/index.styl
- desktop/apps/auction2/stylesheets/index.styl
Allows it to squish under 1200 px, updates the colors on the artwork bricks to gray-darker-color.
> @sweir27 => minor auction2 style updates

- desktop/apps/auction2/client.js
`auction.get('_id')` is undefined (should be `id`), but I think we should just use the object from metaphysics here anyways.
> @sweir27 => use shared object not backbone model

- desktop/apps/article/templates/amp_mixins.jade
We need to add a custom dimension to be able to distinguish AMP content from regular search. Right now they're just bundled together. So many hoops -.-
> @eessex => Custom dimension tracking on AMP

- desktop/apps/auth/index.coffee
- desktop/apps/buy_art/index.coffee
This would allow us to deploy without exposing unfinished work.
> @kanaabe => Hide collector marketing pages for now

- mobile/analytics/criteo.js
Undefined variable `price` is causing our bid screen to fail to progress. Two questions, since I'm not very up to date on Force:
- Can we use linting to catch errors like this at build-time?
- This code runs on an event handler, but since the event mechanism is synchronous, it crashes the whole turn of the event loop, interrupting the process it's responding to. Is there a better pattern we could use to avoid this? (e.g. a variant of `on` that uses `setTimeout` or a variant of `trigger` that swallows exceptions?)
**Crash site:**
**Crash trigger:**
The `success` function at the top on line 11399 is meant to be triggered on line 11428, but `f.trigger` on the previous line throws an exception, as seen in the previous image, preventing this line from ever executing.
> fix undefined variable

- mobile/apps/auth/routes.coffee
- mobile/apps/auth/test/routes.coffee
The `redirect_uri` from a sale artwork page is sent in the query string but the mobile auth helper wasn't looking for it. 
This is a fix for https://github.com/artsy/auctions/issues/349 .
> Adds missing check for query redirect URI

- desktop/apps/collect/client.coffee
- desktop/apps/collect/templates/index.jade
- desktop/components/commercial_filter/filters/keyword/index.jade
- desktop/components/commercial_filter/filters/keyword/index.styl
- desktop/components/commercial_filter/filters/keyword/keyword_filter_view.coffee
- desktop/components/commercial_filter/models/filter.coffee
- desktop/components/commercial_filter/models/params.coffee
- desktop/components/commercial_filter/stylesheets/index.styl
This adds a new lab feature to `/collect` for keyword filtering of artworks. It's a free-form text field which searches genes, tags, auto tags and artwork titles, so you can type in anything from 'snow' to 'female portrait' to 'person on a beach' to 'furniture' and it gives pretty good results. 
Interaction is a bit clunky in that you have to hit enter for the keyword filter to execute. The filter can be combined with any other filter on collect - i've tested it with most. It can also be set via url as a `keyword=` param. 
I'd like to add artist names and medium to the list of searched fields, in order to make the search box more powerful, but i can follow up with that.
This depends on artsy/metaphysics#573.
cc @anandaroop 
cc @anandaroop
> @mzikherman : keyword filtering on collect

- desktop/apps/sitemaps/templates/artworks.jade
- desktop/apps/sitemaps/templates/images_index.jade
- desktop/apps/sitemaps/templates/index.jade
- desktop/apps/sitemaps/test/templates.coffee
We stub artwork data, but in the actual controller code it no longer exists, so https://www.artsy.net/sitemap.xml is broken but all tests pass.
> Removed leftover sitemap code.

- desktop/apps/artwork/components/commercial/templates/acquire.jade
- desktop/apps/artwork/components/commercial/templates/index.jade
- desktop/apps/artwork/components/commercial/view.coffee
- desktop/apps/artwork/routes.coffee
- desktop/apps/artwork/templates/metadata.jade
- desktop/apps/artwork_purchase/routes.coffee
- desktop/apps/artwork_purchase/test/routes.coffee
- desktop/components/split_test/running_tests.coffee
This resolves the purchase request test in favor of purchase requests!
In this case, there wasn't a ton of code to modify except removing the explicit conditionals and test code itself. Sometimes, if the resolution of an AB test results in removing functionality entirely, resolving the test can include a big code diff as well.
Since we're still going to have regular inquiries, and also purchase requests, I think these updates are sufficient. No major refactor necessary.
> @alloy => Let them buy art

- desktop/components/article/stylesheets/content.styl
Update Force list styles to match writer
Add min height to h2, empty ones used for spacing were rendering at 0px tall
> @kanaabe => List styles, h2 height

- desktop/analytics/partner_application.js
- desktop/apps/partnerships/client/view.coffee
Hey @kanaabe can you take a look and test this out. I have tested also and it seems to do what we want which is to call identify with `session_id` and `email` included. 
Two concerns are, can't figure out if this will apply for all of the partnership forms (auctions, etc) or just galleries.
Also is there enough time for the function to grab the email value before the page switches?
cc @anipetrov @eessex
> @kanaabe add identify call to application analytics stack WIP

- package.json
- yarn.lock
closes #1065
The version of `blueimp-file-upload` has been upgraded unexpectedly and it seems that the version we are currently using (9.14.0) is not compatible with our js setup. This commit downgrades the library to the latest version that is compatible.
The change that broke our feature is this: https://github.com/blueimp/jQuery-File-Upload/commit/c79a44d56867771f0d420cbe4d10bc4abb08e045, which supposedly adds support for Node/CommonJS. However, it goes into the Node/CommonJS logic when we need to load it to the browser. We were not sure what the proper fix would be for this, so we decided to downgrade for the time being.
We will submit a pull request to the upstream repository to get feedback.
> Fixed a bug where user can't upload photos from JSON page editor

- desktop/components/json_page/seed.coffee
- desktop/components/json_page/update.coffee
closes #1066
As of Inquirejs 1.0.0 (https://github.com/SBoudrias/Inquirer.js/releases/tag/v1.0.0), it no longer accepts callbacks and returns a promise object instead. This broke the command line tool we use to [upload json files](https://github.com/artsy/force/tree/master/desktop/components/json_page#development). This commit fixes the issue by changing the script to use promises.
> Fix the bug where uploading/seeding a json file stopped working

- README.md
Hi. Not sure if the docs will be added in, but noticed that the link pointed to a directory that no longer exists in the repo. Thanks.
> remove link from missing docs

- desktop/apps/auction2/actions.js
- desktop/apps/auction2/components/auction_grid_artwork/index.styl
- desktop/apps/auction2/components/basic_checkbox/index.styl
- desktop/apps/auction2/components/medium_filter/index.js
- desktop/apps/auction2/reducers.js
- desktop/apps/auction2/stylesheets/banner.styl
- desktop/apps/auction2/test/components.js
- desktop/apps/auction2/test/reducers.js
Updates the checkbox label to respect long names.
(instead of)
Late addition:
Instead of showing _all_ of the possible mediums, this PR sets the `initialMediumMap` on the first fetch, and then uses that to disable/enable them in future filters. i.e.:
> @mzikherman => fix checkbox label spacing #minor

- package.json
I think although we set the `--max_old_space_size` option, node's GC was not being aggressive enough.  See: https://blog.heroku.com/node-habits-2016#7-avoid-garbage and https://github.com/nodejs/node/issues/3370#issuecomment-148108323
cc @craigspaeth @alloy
> set node vm GC options

- package.json
We are still brushing up against the 1Gb memory limit on Heroku dynos - we need to account for memory overhead of the entire application as well as objects waiting to be GC'd, so decreasing `max_old_space_size` to 768 (Mb).
cc @craigspaeth @alloy @broskoski
> decrease --max_old_space_size to 768

- desktop/components/article/client/view.coffee
- desktop/components/article/test/view.coffee
Closes https://github.com/artsy/positron/issues/986
Stops calling the related article template unless a callout section has a related article.
> @kanaabe => exclude text-only callouts from custom template

- desktop/apps/auction2/components/header/index.js
- desktop/apps/auction2/components/range_slider/index.js
- desktop/apps/auction2/components/works_by_followed_artists/index.js
- desktop/apps/auction2/queries/sale.js
- desktop/apps/auction2/reducers.js
- desktop/apps/auction2/test/reducers.js
Here are few fixes that came out of yesterday's QA session:
- Make the "works by artists you follow" carousel loop (so you can always click the right arrow)
- Clicking the "Artists you Follow" checkbox when it is checked should _uncheck_ the box and show works by all artists
- Adds the currency symbol to the estimate slider
- Don't show "Your search returned 0 results" warning. I actually just changed this message to say "Loading", since in the current UI there's actually no way to get to 0 results, so that message was misleading. We can remove the message entirely if we want also /shrug.
> @damassi => auction2 fixes from QA session

- desktop/apps/home/client/setup_home_page_modules.coffee
- desktop/apps/home/stylesheets/modules.styl
Since: https://github.com/artsy/metaphysics/pull/579, the `active_bids` module returns actual bids and not just an empty array. This means they show up on the homepage, but I noticed that in staging, the rail looks a little odd:
Turns out the module was not displaying the title because the "my active bids" rail skips the generic `ArtworkBrickRailView` template in favor of a custom one. Since that custom template is used elsewhere on Force, I ended up manually setting the `.abrv-header` element here to the `module.title` to keep backwards compatibility. 
Fixed like so:
> @broskoski => add Your Active Bids title to home page

- desktop/apps/sitemaps/index.coffee
- desktop/apps/sitemaps/routes.coffee
- desktop/apps/sitemaps/test/routes.coffee
You can see these:
https://s3.amazonaws.com/artsy-sitemaps/sitemap-genes.xml
https://s3.amazonaws.com/artsy-sitemaps/sitemap-artists.xml
https://s3.amazonaws.com/artsy-sitemaps/sitemap-artists-2017.xml
> Replaced artist and gene sitemaps with Spark-generated ones.

- package.json
Taken from recommended settings for a 1Gb heroku dyno from here: https://github.com/damianmr/heroku-node-settings
`max_semi_space_size` and `max_executable_size` appear to be relevant.  It appears that  `max_old_space_size` should be set as the limit of the dyno.
We should also run a single 2X web dyno for force-staging (rather than a hobby dyno) so we can see memory usage over time as in production.
cc @alloy @craigspaeth @broskoski
> add max_semi_space_size and max_executable_size - bump max_old_space_size

- desktop/apps/partner2/stylesheets/index.styl
Closes #1108 
Small fix for a layout glitch reported on #help last week. Ensures that partner profile has left and right margin at smaller window widths:
> @oxaudo => Fix margins on partner2 profile page

- desktop/apps/sitemaps/index.coffee
- desktop/apps/sitemaps/routes.coffee
- desktop/apps/sitemaps/test/routes.coffee
Uses s3 proxy for articles sitemaps.
'News' specific feed is still untouched.
> @dblock => Articles use s3 sitemap

- desktop/apps/sitemaps/templates/index.jade
I was wondering why https://www.artsy.net/sitemap.xml is still showing https://www.artsy.net/sitemap-articles-0.xml, here's why,
> Removed leftover article reference.

- desktop/apps/sitemaps/index.coffee
- desktop/apps/sitemaps/routes.coffee
- desktop/apps/sitemaps/test/routes.coffee
Blocked by https://github.com/artsy/cinder/pull/127 getting merged and the data getting up onto s3.
closes: https://github.com/artsy/force/issues/1114
> Replace fair sitemaps with cinder output.

- desktop/lib/setup.coffee
Thanks for the pointer. This was an error in how we initialized [the `express-ipfilter` middleware](https://www.npmjs.com/package/express-ipfilter). I tested and confirmed that, with this update, the listed IPs are correctly blocked.
_Sort of:_ I still ran into https://github.com/artsy/force/issues/1148 which means the error page can't actually render. After removing the many `sd` references from the common layout, I was able to trigger the expected error.
However, this can still be much improved. In particular, the error is a 500 that clearly states the IP is being blocked: 
It should be a `429` or at least a `4xx` error instead of crashing the app. This requires handling the `IpDeniedError` as mentioned in [the docs](https://www.npmjs.com/package/express-ipfilter#error-handling). If you …
> @craigspaeth: Fix IP-blacklisting, at least for desktop

- lib/memory_profiler.js
Ok, flipped the script, it should now always try to upload unless `NODE_ENV` is `development`.
Going to self-merge on 💚
> [memory] Upload heap dumps in staging as well.

- lib/memory_profiler.js
- package.json
- yarn.lock
* To be able to diff heap dumps, they need to be of the same process, so adding a process specific UUID to the filenames (and logs).
* The default S3 ACL doesn’t allow us to download the heap dumps just by AWS KEY and SECRET, I think giving the ‘bucket owner’ full control should fix that (please correct me).
> [memory] Add process unique identifier and fix S3 ACL.

- desktop/apps/auction2/client/index.js
- desktop/apps/auction2/stylesheets/footer.styl
This PR fixes the styling on the auction2 page and updates the backbone `auction` object that we pass around on the client to have all of the fields that we fetch, instead of just a few as it was buggy/confusing to just `pick` them as needed.
> @craigspaeth => little auction2 fixes

- desktop/components/email/stylesheets/gallery_insights.styl
Closes https://github.com/artsy/force/issues/1134
- Removes appearance of linebreak in marketo form header
Share buttons will be addressed separately.
> @anyone => GI callout label width

- index.js
Noticed we lost the 'dont crash on nil user agents' in this version, whereas we have it in [this version](https://github.com/artsy/force/blob/137b426ea82bede31776186feb7c8f72e2213ba0/desktop/lib/middleware/redirect_mobile.coffee#L14).
Was seeing some of these in NewRelic.
Closes https://github.com/artsy/force/issues/1099
> @kanaabe => Dont crash on nil user agents

- desktop/analytics/criteo.js
- desktop/apps/auction2/client/actions.js
- desktop/assets/auctions.coffee
This fixes a few things I noticed when QAing the new auction page in staging.
- We weren't loading assets when visiting the `auction/:id/confirm-registration` page, as it no longer fit into the regex pattern. Another reason to fix this to use actual routes.
- Previously, we loaded an `sd.ARTWORKS` object server side that we could send to criteo for tracking. As we now load the artworks client-side, I instead send an explicit `analyticsHook` event when we fetch artworks from the server.
> @damassi => fix asset loading for sub pages and criteo analytics

- desktop/analytics/home.js
Adds click tracking on recommendations as it's a KPI (along with inquiries) for upcoming recs experiments.
I also need the mobile app equivalent - @alloy, any idea about click tracking on recommendations in eigen? Is that something we currently have or could add?
> @mzikherman : add click tracking to homepage recommendations

- desktop/apps/categories2/components/Content.js
- desktop/apps/categories2/components/GeneFamilies.js
- desktop/apps/categories2/components/Sidebar.js
- desktop/apps/categories2/components/__snapshots__/AppContainer.spec.js.snap
- desktop/apps/categories2/stylesheets/index.styl
This PR addresses @anandaroop's comments from https://github.com/artsy/force/pull/1171, adds proptype checking, adds genes columns and swaps in flexbox. You can also use the left navs. This is pretty rudimentary though because the header obscures the top of the scrolled-to element. The left nav also continues to scroll with the content. We can address this in a later PR. Perhaps we will also want to switch out Stylus for Styled Components.
> Refactor components to be stateless and update tests

- desktop/components/artwork_metadata_stub/queries/contact.coffee
- desktop/components/artwork_metadata_stub/templates/didactics.jade
For artworks that are in sales, we want to link to the _sale_ on the partner byline (but still show the partner name, which will be something like "Phillips Auctions" once we do the migration).
> @damassi => link to sale on artwork partner line

- desktop/lib/middleware/redirect_mobile.coffee
Visiting a page like `http://localhost:5000/consign?utm_medium=p-search&utm_source=adwords&utm_campaign=Consignments` was throwing a 404 on mobile web. I believe this should fix it.
> @craigspaeth => allow for /consign to accept utm params on mobile

- desktop/apps/article/templates/amp_mixins.jade
- desktop/components/article/stylesheets/video.styl
- desktop/components/article/templates/mixins.jade
- mobile/components/article/test/view.coffee
- mobile/test/helpers/fixtures.coffee
Companion to https://github.com/artsy/positron/pull/1007, displays video captions when available.
I am not sure how to test AMP.
> Added video captions.

- desktop/apps/auction2/components/medium_filter/index.js
Turns out the javascript `Array.find` method is [not supported in IE](http://stackoverflow.com/questions/37788536/the-find-method-is-supported-in-ie). Instead of including an explicit polyfill here, I instead grab the `find` method off of underscore, which has cross-browser support.
> @craigspaeth => make auction page IE compatible

- desktop/analytics/bidding.js
- desktop/apps/auction2/client/actions.js
- desktop/apps/auction2/templates/my_active_bids.jade
- desktop/components/my_active_bids/template.jade
Following the analytics schema here: https://docs.google.com/spreadsheets/d/17oqFli15x1SmNBu_-fPZhFifMw2BNSPJe9VdOgs1aKs/edit#gid=2024361038
This PR removes/updates the following events:
- Removed "Notify me auction form submitted" (we removed this feature)
- Only include the "Clicked Register to bid" event for the settings and auction landing page contexts (we couldn't find the other ones, I think the CTAs have been removed)
- Fixed the "Clicked Bid" events as they weren't firing anywhere, and made sure they work for the 'my active bids' modules throughout the site
- Added tracking for "Commercial filter params changed" events, which fire on the first new fetch of artworks after a param has changed.
cc @joelauerbach
> @mzikherman => Auction page analytics QA plus new events

- desktop/analytics/auction_reminder.js
- desktop/assets/analytics.coffee
- desktop/components/auction_reminders/view.coffee
closes https://github.com/artsy/auctions/issues/379
cc @sweir27 @katarinabatina @joelauerbach 
This adds analytics for auction reminder interactions, with metadata for `slug` and `auction_state`. I was able to track analyticsHooks interactions in a mocha test with a bit of mocking, but it wasn't fun and @craigspaeth recommended I leave it off (we don't currently test analytics messages anywhere else).
> reminders hooks

- mobile/components/artwork_columns/artwork.jade
- mobile/components/artwork_columns/test/template.coffee
Previously, artwork components were showing "Contact Gallery" on this page if the artwork was part of an auction. This fixes it to follow similar logic we use on desktop.
> @erikdstock => fix contact gallery showing up on mobile web

- desktop/apps/galleries_institutions/components/partner_cell/index.jade
- desktop/apps/galleries_institutions/components/primary_carousel/template.jade
- desktop/apps/galleries_institutions/components/primary_carousel/test/template.coffee
Fixes #95 
Occasionally the filter pulldown selections on /gallleries will result in an empty carousel, and a big blank space on the page, because there are no eligible profiles to display in it.
Let's selectively only render the carousel based on if we _actually_ get any profiles back for display. (Watch for Miami in the screencap below)
> @starsirius => Fix occasionally empty primary carousel

- desktop/apps/auction/queries/works_by_followed_artists.js
Turns out when I [fixed the artwork grid elements](https://github.com/artsy/force/pull/1189/files#diff-6a3cbee550d2318c7216c367fabab1b7R17) to link to a url with the artwork slug, I broke the works by artists you follow rail on this page (as the query did not include `id`).
> @damassi => fix link to works by artists you follow

- mobile/apps/fair/stylesheets/exhibitors_az.styl
- mobile/apps/fair/templates/exhibitors_subheader.jade
This is removes the exhibitor count from the fair microsite on mobile. It is the microgravity equivalent of https://github.com/artsy/force/pull/1218
> @yuki24: remove exhibitor count on mobile

- lib/setup.js
- yarn.lock
The theory is that a couple errors cascade into a bunch of [blocking](https://github.com/artsy/artsy-error-handler/blob/master/routes.coffee#L8) calls that lock up the entire server. I think this was exaggerated by the fact that I inlined stylus to avoid the need for `asset` to pull down CDNed assets for error pages—that probably eats up a bunch of CPU too. By using `res.render` I'm hoping express's view caching is enough to solve this—if not we can do some pre-compilation/further de-styling of to the error page to make rendering it less expensive.
> @sweir27: Use res.render to leverage view caching for error page

- .gitignore
- desktop/apps/auction_support/client/index.coffee
- desktop/apps/auction_support/client/registration_form.coffee
- desktop/apps/auction_support/stylesheets/index.styl
- desktop/components/credit_card/stylesheets/index.styl
closes https://github.com/artsy/auctions/issues/306
cc @craigspaeth @damassi @sweir27 @mzikherman 
This addresses an issue where, upon clicking 'Confirm Bid' on the register+bid form, the credit card form remains in place and submits again. (see the linked issue above)
From the user's perspective I'm disabling the inputs and hiding the form, but I'm doing this across 2 different backbone views `RegistrationForm` and `BidForm`.
Since there is no page reload and the BidForm is actually creating a RegistrationForm view with a callback for placing the bid, I then undelegate the events on the RegistrationForm view to prevent the data from being submitted again.
To test: 
```bash
git checkout -b erikdstock-bugfix-bid-registration master
git pull https://github.com/erikdstock/force.git …
```
> Bugfix - duplicate bidder registration on combo form

- desktop/apps/article/templates/amp_article.jade
Looks like AMP was unhappy with us using inline styles. The only place that it's being used in AMP is on the generic footer. Mobile footer doesn't have the inline styles so let's use that instead.
> @eessex => Use mobile footer without svg

- mobile/apps/auction/routes.coffee
This fixes a bug that was introduced on the switch to using `lot_label`s. It was caught for the desktop view in the following thread, but not mobile. https://github.com/artsy/force/pull/1139/files#diff-96509af377373c5b4d73eef6026785c5
relates to #1139
The fix, with proper ordering:
The broken view:
> sort auction lots by position, not lot_label

- desktop/apps/fairs/query.coffee
- desktop/apps/fairs/templates/fair_upcoming.jade
**This PR is blocked by https://github.com/artsy/metaphysics/pull/611.**
This adds a more strict conditional for displaying year-round pages for fairs. The `is_publically_visible` property ensures that a link is created for the year-round page only when a fair organizer profile is published and not private.
> @mzikherman: display fair year-round link when the profile is visible to the public

- desktop/apps/fairs/templates/fair_upcoming.jade
closes: https://github.com/artsy/collector-experience/issues/132
This is a follow up to https://github.com/artsy/force/pull/1252 and fixes the typo where `href` is meant to be called on `profile`.
> @mzikherman: fix typo

- desktop/apps/artwork/components/additional_info/templates/about_the_work.jade
- desktop/apps/auction/client/reducers.js
- desktop/apps/auction/components/auction_grid_artwork/index.js
- desktop/apps/auction/components/auction_list_artwork/index.js
- desktop/apps/auction/components/sidebar/index.js
- desktop/apps/auction/queries/sale.js
- desktop/apps/auction/test/components.js
- desktop/components/artwork_metadata_stub/queries/contact.coffee
- desktop/components/artwork_metadata_stub/templates/contact.jade
- desktop/components/artwork_metadata_stub/test/index.js
- desktop/components/my_active_bids/query.coffee
- mobile/components/artwork_columns/artwork.jade
- mobile/components/artwork_columns/auction_artwork.jade
- mobile/components/multi_page/config.coffee
Phew. Bunch of little fixes in here:
- Makes the `Signature` show up on one line
(previously)
(updated)
- Updates the auction page to show pricing information if the auction is in preview mode
- Updates the artwork brick to show pricing info if the auction is in preview mode
- fixes the "my active bids" module to use the square version of artworks so it doesn't stretch
(previously)
(updated)
- Adds `Bid now` link to artworks brick in mobile mode
(previously)
(updated)
- Updates the Auction FAQ on mobile web to link to `specialist@artsy.net` instead of `support@artsy.net`
> @damassi => little auction fixes across the board

- desktop/apps/artwork/components/auction/test/view.coffee
- desktop/apps/artwork/components/auction/view.coffee
For issue  #1229, the problem is multiple re-renders of the component containing the dropdown.
This doesn't fully fix the problem, because there will still be one re-render. Definitely a good candidate component to Reactify.
> fix bid dropdown dismissal

- desktop/apps/editorial_features/components/venice_2017/client.coffee
- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/components/venice_2017/client/video.coffee
- desktop/apps/editorial_features/components/venice_2017/stylesheets/index.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/video.styl
- desktop/apps/editorial_features/components/venice_2017/templates/index.jade
- desktop/apps/editorial_features/components/venice_2017/templates/video.jade
- desktop/apps/editorial_features/icons/vr-icon.svg
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
- desktop/assets/editorial_features.coffee
- desktop/components/auction_reminders/blacklist.coffee
Hopefully this merge will be painless on your end, but this cleans up some of the client-side code and adds video controls on the player. The scrubber is using `nouislider` which I conveniently took from the /collect page's slider. Thanks @broskoski for adding that! Was pretty fun to hack a playback scrubber on top of it.
> @eessex => Video controls

- desktop/assets/editorial_features.coffee
Before we relied on the `$` callback to evoke the init function but now that we have a little more logic and pass in our own callback, we need to explicitly evoke it.
> @eessex => Fix init on EOY page

- desktop/apps/sitemaps/index.coffee
- desktop/apps/sitemaps/routes.coffee
- desktop/apps/sitemaps/templates/cities.jade
- desktop/apps/sitemaps/test/routes.coffee
- desktop/apps/sitemaps/test/templates.coffee
- yarn.lock
This removes the previous special behavior for `sitemap-cities.xml` in favor of the standard proxy to S3 for the [new Cinder-generated sitemap](https://github.com/artsy/cinder/pull/173) located at https://s3.amazonaws.com/artsy-sitemaps/sitemap-cities.xml
> @dblock => Update city sitemap

- desktop/apps/auction_support/client/bid_form.coffee
- desktop/apps/auction_support/test/client/bid_form.coffee
- desktop/components/credit_card/client/error_handling_form.coffee
- desktop/components/credit_card/test/error_handling_form.coffee
- desktop/models/sale.coffee
relates to https://github.com/artsy/auctions/issues/372
blocked by https://github.com/artsy/gravity/pull/10972
This adds more specific messaging in the case that a user opens the timed auction biding dialogue and the auction goes live. It would currently say 'sale closed to bids'.
The message now includes a link to the sale on prediction. I think the way I'm doing this link might be wrong.
> Auctions 372 live sale bid messaging

- desktop/analytics/account_creation.js
- desktop/assets/analytics.coffee
This is the first pr in order to rethink how we handle the Marketo analytics implementation. Currently we are running out of Marketo API calls by 8am every day because of our segment integration. On every pageload we use a Segment Identify call which in turn pings Marketo's API. Additionally, while we have turned off the Marketo integration using the Segment UI for many tracking calls, we are still sending over 50k to Marketo within a few hours. 
After speaking with our consultants and looking into other options I propose three pr's make this data pipeline more efficient:
PR: 1. Remove Marketo from page load identify calls and add in new identify calls only for Marketo on Sign-Up, and Application Form submission (already done).
PR: 2. Fix identify and track calls for Gallery Insights sign …
> Rethinking Marketo Analytics Implementation PR: 1

- package.json
- scripts/acceptance-record.sh
- scripts/acceptance.sh
- scripts/deploy-assets.sh
- scripts/deploy.sh
- scripts/mocha.sh
- scripts/start.sh
- scripts/test.sh
This PR breaks out the package.json `scripts` field into separate files. I'd like to merge this initial pass before moving on to [Circle](https://github.com/artsy/force/blob/master/circle.yml#L43). Thanks to @alloy for suggesting using `set` instead of `&& \`s all over the place.
> Spin off package.json scripts into a new directory

- lib/middleware/proxy_to_reflection.coffee
- test/lib/middleware/proxy_to_reflection.coffee
There's a number of [funny errors](https://sentry.io/artsynet/force-production/issues/256014515/) reported in Sentry from the reflection middleware. This uses Node HTTP proxy instead of our own superagent implementation to do the proxying—hopefully removing that noise and leveraging a mature library to cover other edge cases.
> Use Node HTTP proxy for Reflection proxying

- desktop/apps/auction/client/reducers.js
- desktop/apps/auction/components/range_slider/index.js
- desktop/apps/auction/test/components.js
- desktop/apps/auction/test/reducers.js
We were not handling the upper bound of the estimate range filter correctly!
The initial fetch filters by `estimate_range: ''` which will return everything.
On `change`, it sets the filter to match the slider, which was immediately capping the upper bound at `50000` since that's how high the slider goes. We _should_ be querying for `*` on the upper bound, to get everything _above_ the high amount.
This PR updates the slider to query for the correct values, and also updates the display to only show the `+` after the upper bound if you have selected the max.
> @damassi => correctly handle the upper bound of the estimate range filter

- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
Fixes the route to include `/venice-biennale`
Support `video_url_medium` and `video_url_hls` videos and pick the best video for your device/browser
> @eessex => [Venice] Multi-video support and route fix

- package.json
- scripts/acceptance.sh
- scripts/mocha.sh
- yarn.lock
Eve reported [an issue](https://artsy.slack.com/archives/C0350895E/p1493034977010574) with running `yarn mocha [filename]`. 
The problem was that yarn was passing the filename or directory to `sh scripts/mocha.sh` but the script was just ignoring it. The solution is to stop ignoring and append the filenames or directories to the script's invocation of mocha.
> Fix mocha tests in package.json

- desktop/apps/auctions/test/template.coffee
- desktop/apps/editorial_features/components/venice_2017/client/video.coffee
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
- mobile/apps/auctions/test/template.coffee
- mobile/apps/how_auctions_work/test/template.coffee
- mobile/apps/shows/test/template.coffee
Looks like there was a failing test that wasn't caught in my last PR before merge. This fixes that test and addresses a bug where a dialog was being shown on the `onbeforeunload` video dropoff tracking. I still feel like this dropoff tracking needs more fine tuning (ie, should we only count dropoff if the video is playing?), but I'm getting help from #analytics with that and for now this should unblock master merges.
> @craigspaeth => [Venice] Fixes test and onbeforeunload tracking

- circle.yml
Uses `yarn deploy` instead of the `deploy-assets` script which doesn't exist anymore.
> Update circle script with new assets script

- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/components/venice_2017/client/video.coffee
- desktop/apps/editorial_features/components/venice_2017/stylesheets/index.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/video.styl
- desktop/apps/editorial_features/components/venice_2017/templates/carousel.jade
- desktop/apps/editorial_features/components/venice_2017/templates/index.jade
- desktop/apps/editorial_features/components/venice_2017/templates/video.jade
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
- Creates a loading state while the canvas/WebGL is being prepped: 
- Considers adaptive streaming for mobile browsers (except iOS which uses a medium mp4)
- Ability to close the video:
- Smooths out scrubber by pausing updates while in a "scrubbing" state:
> @eessex => [Venice] Video close, ready, adaptive streaming, smooth scrubbing

- desktop/apps/search/routes.coffee
- desktop/components/search_bar/templates/item.jade
I'd forgotten that we explicitly specify the indices we want to search in our front-end global search results query, so here I add the `Page` index to the list. 
This is preventing the consignments page from showing on the search results page right now.
> @sweir27 : search static pages in global search

- desktop/analytics/articles.js
sorry new computer and things are a little messed up. round 2
This PR fixes broken tracking around gallery insights sign up. Because we are using an embedded marketo form these calls fire on submit click rather than successful form submission.
I used beautify in atom and it changed some of your spacing @kanaabe let me know if it looks ok.
Another update on this project. We switched over to a new version of the Segment integration. It is working well, however some of the code implemented in #1291 may need to change due to new naming features. Segment Help doesn't even know themselves so waiting for them to figure it out before I do anything further.
> Rethinking Marketo Analytics PR:2 Fix Gallery Insights Tracking *round 2

- desktop/components/auth_modal/view.coffee
after the form submission (aka send me password reset instructions) is successful.
> @joeyAghion => Keep click handlers for closing the modal around

- lib/middleware/backbone_error_helper.coffee
- lib/setup.js
- package.json
- test/lib/middleware/backbone_error_helper.coffee
- yarn.lock
This removes that [artsy-error-handler](github.com/artsy/artsy-error-handler) module that has caused us so much grief lately by just pulling out the `res.backboneError` helper which we use to support our old-school `model.fetch error: res.backboneError` callback-ways.
I've been wanting to do this anyways, but it is quite confusing why this resulted in some kind of transpiling madness that required uglify to be used.
For those interested this was the stack trace that pointed me here via `at Object.<anonymous> (/Users/craigspaeth/force/lib/setup.js:7:1)`
```
Error: Cannot find module 'uglify-js'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> …
```
> @sweir27: Removed artsy error handler

- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/components/venice_2017/client/video.coffee
- desktop/apps/editorial_features/components/venice_2017/stylesheets/body.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/carousel.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/video.styl
- desktop/apps/editorial_features/components/venice_2017/templates/carousel.jade
- desktop/apps/editorial_features/components/venice_2017/templates/head.jade
- desktop/apps/editorial_features/components/venice_2017/templates/mixins.jade
- desktop/apps/editorial_features/components/venice_2017/templates/video.jade
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
Covers the following:
Error messaging (@owendodd just did my own thing here so let me know if you'd like to change this): 
Scrubber time:
> @eessex => [Venice] Scrubber time, error messaging, and other minor qa

- desktop/apps/editorial_features/components/venice_2017/stylesheets/carousel.styl
> @kanaabe => [Venice] Responsive video completion  

- desktop/apps/artwork/components/partner_stub/components/inquire_via_phone_modal.coffee
- desktop/apps/artwork/components/partner_stub/index.coffee
- desktop/apps/artwork/components/partner_stub/index.jade
- desktop/apps/artwork/components/partner_stub/index.styl
- desktop/apps/artwork/components/partner_stub/query.coffee
- desktop/apps/artwork/components/partner_stub/templates/phone_number.jade
- desktop/components/auth_modal/index.styl
- desktop/components/auth_modal/templates/login.jade
- desktop/components/auth_modal/templates/register.jade
- desktop/components/auth_modal/templates/signup.jade
- desktop/components/auth_modal/test/view.coffee
- desktop/components/auth_modal/view.coffee
finishes https://github.com/artsy/collector-experience/issues/229.
To re-use the `AuthModalView` I added the ability to specify a custom title for the modal. if a title is passed in, the modal will show the title instead of showing the Artsy logo. I'm not sure if this is even a good approach, so I'm open to suggestions.
> Update Show gallery phone number functionality

- package.json
- scripts/assets.sh
- yarn.lock
Testing `yarn assets && NODE_ENV=x yarn start` locally, removing `uglifyify` seems to fix the errors we were seeing on the auction pages and gene pages.
> @craigspaeth => removes uglifyify

- desktop/apps/artwork/components/auction/helpers.coffee
- desktop/apps/artwork/components/auction/templates/live.jade
- desktop/apps/auction/routes.js
- desktop/apps/auction/templates/banner.jade
- desktop/apps/auction/templates/my_active_bids.jade
- desktop/apps/auction/test/routes.js
- desktop/apps/auction/test/templates.js
- desktop/apps/auction_support/client/bid_form.coffee
- desktop/components/main_layout/templates/index.jade
- desktop/components/my_active_bids/helpers.coffee
- desktop/components/my_active_bids/template.jade
- desktop/components/my_active_bids/test/template.coffee
- desktop/components/my_active_bids/view.coffee
- desktop/models/sale.coffee
- desktop/test/models/sale.coffee
- desktop/test/utils/domain/auctions/urls_test.js
- desktop/utils/domain/auctions/urls.js
- mobile/apps/auction/routes.coffee
- mobile/apps/auction/test/routes.coffee
- utils/domain/auctions/urls.js
https://github.com/artsy/auctions/issues/420 tracks this.
This pr standardizes our live auction linking to use a method in a new global `/utils` folder.
The `liveAuctionUrl` method takes one argument for the saleId, appending `/login` if there is a sharify CURRENT_USER.
To test both states, we can look at:
- my active bids components (should only show /login because there is a user)
- auction pages
- artwork pages
- the banners
- loading a bid window before and placing a bid after the sale goes live
When possible, I passed helpers to templates with the locals structure `helpers: {auction: {liveAuctionUrl}}`.
the `Sale` model has many other methods that might want to live in /utils.
> Auctions#420: live links login

- desktop/apps/artwork/components/partner_stub/index.coffee
- desktop/apps/artwork/components/partner_stub/index.jade
This has been deployed to production by accident. This commit makes it impossible even for admins to QA, but right now no analytics is set up and it should be hidden as soon as possible.
/cc @briansw
> Only admins should see the 'inquire via phone' modal for now

- mobile/apps/artwork/components/bid/index.jade
- mobile/apps/artwork/components/bid/index.styl
- mobile/apps/artwork/components/bid/test/template.coffee
cc @joeyAghion @katarinabatina @damassi 
This fixes an issue we found earlier today where an artwork at auction that has been purchased through Buy Now still shows the Bid button rather than 'Sold.'
I talked through design with Katarina and @briansw. This message now shows in the same place and with the same [updated] styling as the 'Auction Closed' message, but it takes precedence if the artwork `is_sold`. The bid button section will not render unless the auction is open and the artwork is not sold.
> [mobile] Show 'Sold' instead of bid/auction closed for bought-now artwork

- desktop/apps/artwork/components/partner_stub/index.jade
- desktop/apps/artwork/routes.coffee
Right now, it's impossible for even admins to QA https://github.com/artsy/force/pull/1322. [As suggested on slack](https://artsy.slack.com/archives/C0350895E/p1493759021409652), we should be using a query param so we can toggle a feature for logged out users.
> Add ability to toggle 'inquire via phone' modal using '?inquire_via_phone=1'

- mobile/apps/artwork/components/bid/index.styl
This pr adjusts the padding in the Bidding Closed/Sold message for better vertical centering. Requested by @briansw.
> Mobile Sold artwork - adjust padding for better centering

- desktop/apps/editorial_features/routes.coffee
- desktop/apps/editorial_features/test/routes.coffee
This is a quick fix to the `email of undefined` venice issue for logged out users in case you want to hit a merge button sooner than later.
> @kanaabe: Logged out venice fix

- desktop/apps/home/client/setup_home_page_modules.coffee
- desktop/apps/home/components/followed_artists/test/view.coffee
- desktop/apps/home/components/followed_artists/view.coffee
Regarding https://github.com/artsy/force/issues/1303
This broke when your favorite model (`FeaturedLink`) got a malformed URL. This filters bad urls out and adds a spec.
> @craigspaeth - Filters out problematic URLs for FollowedArtistsRailView

- desktop/apps/artwork/components/partner_stub/index.coffee
- desktop/apps/artwork/components/partner_stub/index.jade
- desktop/apps/artwork/components/partner_stub/index.styl
- desktop/apps/artwork/components/partner_stub/templates/phone_number.jade
- desktop/components/auth_modal/index.styl
- desktop/components/auth_modal/templates/login.jade
- desktop/components/auth_modal/templates/register.jade
- desktop/components/auth_modal/templates/signup.jade
- desktop/components/auth_modal/test/view.coffee
- desktop/components/auth_modal/view.coffee
This fixes most of the QA items in https://github.com/artsy/collector-experience/issues/229#issuecomment-298762022
* Just show the normal signup modal with “Create an Artsy account to call gallery” as the header
* Inquire via phone needs to be garamond-s-body
* CALL GALLERY header should be AVANT-GARDE-BODY
* Gallery name should be bold and garamond-l-body
* Phone and location information should be garamond-l-body
* Missing space after comma between city and state
* Don't vertically center the content inside the modal
> Tweak inquire via phone modal

- desktop/apps/search/templates/search_result.jade
- desktop/models/search_result.coffee
- desktop/test/models/search_result.coffee
- test/acceptance/bidding.js
https://github.com/artsy/force/pull/1313 created a new bug, causing artist thumbnails to go missing in our search bar:
This fixes that. The issue arises from our joint use of the `SearchResult` model by both the search bar and the search results page. The model had some display logic in it relating to the latter context, which I've now moved into the relevant template where it belongs.
> @mzikherman : fix missing artist thumbnails in search bar

- desktop/analytics/account_creation.js
- mobile/analytics/auth.js
- mobile/apps/auth/client/login.coffee
These were in fact... needed.  😢 
Our `window.analytics`-wrapping analytics.js client-side code makes different calls/payloads than the server-side node Segment analytics lib we use. This makes sense since there's different information available, different contexts, etc.
So we need these client-side too.
> @craigspaeth => Revert "Remove unneeded login analytics tracks"

- desktop/apps/articles/routes.coffee
- desktop/apps/artist/routes.coffee
- desktop/apps/fairs/routes.coffee
- desktop/apps/show/routes.coffee
- desktop/components/error_handler/index.jade
- lib/setup.js
- package.json
- yarn.lock
- Bumps reaction-force
- Updates error handler to suppress output on production (since from reaction-force we do `next(err)`. This means that all lines such as https://github.com/artsy/force/blob/3f95087005fdd3c63e48183c8de96f01099d67fe/desktop/apps/artist/routes.coffee#L56 , should just also be `next(err)`.
> @craigspaeth => Bump reaction-force and only display error stack if not production

- desktop/apps/artwork/components/auction/templates/live.jade
- desktop/apps/artwork/components/auction/templates/status.jade
- desktop/apps/artwork/components/auction/view.coffee
So on the Artwork app, helpers get passed in and referenced specifically as `helpers` here: https://github.com/artsy/force/blob/master/desktop/apps/artwork/routes.coffee#L40 (and documented here: https://github.com/artsy/force/tree/master/desktop/apps/artwork#helperscoffee
We can change them to be named something else, but we would then have to change all the references in the various components across the `Artwork` app (and then I'm not sure it would accomplish what you want it to).
Please take a look and let me know if I'm misunderstanding the prior bug that you were aiming to fix!
> @erikdstock - Fix viewHelpers reference on artwork page

- desktop/assets/categories.coffee
- package.json
- scripts/assets.sh
- yarn.lock
Sigh, so after banging my head against this ( https://github.com/artsy/force/issues/1380 ) for two days, I found this issue: https://github.com/substack/factor-bundle/issues/51 . Apparently factor-bundle's de-dupe feature is incompatible with our Browserify. Someone in this thread made a browserify plugin which de-dupe's the required modules ( https://github.com/tellnes/prundupify ). 
I did a cursory comparison, and it doesn't look like file sizes are much different, but you might know whether this is a bad idea or not. It _does_ however fix the issue that I was getting with importing reaction-force client-side in production.
> @craigspaeth - Add prundupify to asset build

- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/components/venice_2017/stylesheets/body.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/guide.styl
- desktop/apps/editorial_features/components/venice_2017/templates/video_description.jade
- desktop/apps/editorial_features/index.coffee
- desktop/apps/editorial_features/routes.coffee
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/routes.coffee
- Adds twilio sms form to desktop view, shows 'open in app' link for mobile
- Fixes link color in video guide
- Adds animation to scrolling on info icon click
- Caches curation, sub-articles and video guide on fetch
> @craigspaeth => [Venice] QA + text links

- desktop/apps/artwork/components/partner_stub/index.coffee
It seems like the `#toElement`  is not implemented in FireFox or IEs and the `#target` should be used instead. I don't know I didn't use `target` in the first place...
> Fix opening a Inquire via Phone modal on FireFox and IEs

- desktop/apps/artwork/components/inquire_via_phone/templates/phone_number.jade
I should've sent this PR as part of the previous one, but [as requested](https://artsy.slack.com/archives/C03JJ2RDG/p1494596003336575) I changed the font size for the gallery name in the Inquire via Phone modal.
> Gallery name should be same size as contact info in Inquire via Phone modal

- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/components/venice_2017/client/video.coffee
- desktop/apps/editorial_features/components/venice_2017/stylesheets/video.styl
- desktop/apps/editorial_features/components/venice_2017/templates/video.jade
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
- desktop/apps/editorial_features/test/components/venice_2017/video.coffee
@owendodd there's a tradeoff in order to make this work: the video is no longer draggable on mobile and only relies on the gyroscope sensor. Reason is, there needs to be a cover on the player that listens for a touch that activates the controls again, which covers up the drag functionality. It hasn't really bothered me but just fyi.
> @eessex => [Venice] Fade out controls on mobile

- desktop/analytics/bidding.js
- desktop/apps/artwork/components/auction/bootstrap.coffee
- desktop/apps/artwork/components/auction/helpers.coffee
- desktop/apps/artwork/components/auction/query.coffee
- desktop/apps/artwork/components/auction/templates/bid.jade
- desktop/apps/artwork/components/auction/test/view.coffee
- desktop/apps/artwork/components/auction/view.coffee
- desktop/lib/global_client_setup.coffee
- package.json
- yarn.lock
This PR fixes an issue where a user who is not yet qualified to bid is able to bid via an erroneously enabled UI, leading to an error. Addresses item 1 on https://github.com/artsy/auctions/issues/442. 
**To Test:** 
```sh
git checkout -b damassi-bugfix-check-qualified-for-bidding master
git pull https://github.com/damassi/force.git bugfix-check-qualified-for-bidding
```
- Create a new account, remember the details, and sign in
- Go to http://localhost:5000/auction/chris-ohm-retraction-round-2 and click 'Register to Bid'
- Fill in fake CC info (but note that in Ohm, the sale has been set to `require bidder approval = true` to get around immediate credit card approval)
- Note that the view looks like 
- Navigate to http://localhost:5000/artwork/gerrit-engel-painting and notice 
- Sign out
- …
> @erikdstock => Fix Auction bidder registration flow 

- desktop/apps/artwork/components/partner_stub/index.coffee
* `#currentTarget` gives the element the event listener is attached to while `#target` could be something else.
* Older browsers like IE10 don't have `#dataset` implemented and `#getAttribute` should be used instead.
> Use currentTarget and getAttribute for older browsers

- desktop/components/main_layout/templates/scripts.jade
Latest master appears to be broken on this added script-- in jade templates, there needs to be a `.` after the script tag for it to be interpreted correctly cc @nicholassewitz
> @damassi => add dot for inline script tag in jade

- desktop/apps/auction/test/analytics_middleware.js
- desktop/apps/auction/test/reducers.js
- desktop/apps/consignments2/client/actions.js
- desktop/apps/consignments2/client/reducers.js
- desktop/apps/consignments2/components/choose_artist/index.js
- desktop/apps/consignments2/components/choose_artist/index.styl
- desktop/apps/consignments2/test/components.js
- package.json
- yarn.lock
This PR adds the artist autocomplete page to the consignment submission flow.
It uses `react-autosuggest` which has helpful bindings for controlling what happens when you need to fetch suggestions, clear suggestions, select a suggestion, etc. In our case, these methods all correspond to redux actions that modify our state.
Selecting a valid artist takes you to the next page in the flow. Typing in an invalid artist (that returns no results) prompts you with a warning message.
There's also just a bunch of little semicolon/unused dependencies cleanup.
> @craigspaeth => submission flow artist autocomplete

- desktop/apps/artwork/routes.coffee
- desktop/apps/auction/components/artist_filter/index.js
- desktop/apps/auction/routes.js
- desktop/apps/auction_support/client/index.coffee
- desktop/apps/auction_support/client/registration_form.coffee
- desktop/components/credit_card/client/confirm_registration.coffee
- desktop/lib/global_client_setup.coffee
- package.json
- yarn.lock
This PR cleans up a few rough edges around Auctions in Force:
**1** - After bidder registration, when clicking into an auction artwork and then hitting back `/confirm-registration` would trigger the previously dismissed registration status modal
**To Test:**
```sh
git checkout -b damassi-auctions-polish master
git pull https://github.com/damassi/force.git auctions-polish
yarn install && yarn start
```
- Log out and create a new account
- Navigate to http://localhost:5000/auction/members-only and click `Register to Bid` 
- Fill out form and submit
- Click the `x` or surrounding area and notice that the `/confirm-registration` route fragment is replaced in the URL bar
**2** - On `/artwork/:id`, an additional client-side query was necessary to update the "Bid' button so that it displays the …
> @sweir => Auction Cleanup 

- desktop/apps/auctions/routes.coffee
- desktop/apps/auctions/test/routes.coffee
`timely_at` refers to either when the sale ends or the live sale starts.
> @craigspaeth => use -timely_at to sort auctions page

- desktop/components/my_active_bids/index.styl
- desktop/components/my_active_bids/query.coffee
- desktop/components/my_active_bids/template.jade
- desktop/components/my_active_bids/test/template.coffee
This PR updates `user/auctions` to be more clear for the user:
- If live or closed, remove bid details and update button label and url
- Cleanup layout
Fixes https://github.com/artsy/auctions/issues/476
> @erikdstock => Cleanup user/auctions

- desktop/apps/consignments2/client/actions.js
- desktop/apps/consignments2/test/reducers.js
- package.json
- yarn.lock
Turns out we need to create the `Entry` in gemini first, so we have the `token` to save on the `Asset` in convection. I was mistaken in thinking we could use the `source_key` as the token to avoid the race condition.
This PR just updates the order of the convection and gemini calls. It also uses the changes in `gemup`: https://github.com/artsy/gemup/pull/3 to allow us to upload the assets with a `private` acl.
> @craigspaeth => save gemini entry before creating convection asset

- desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- desktop/apps/editorial_features/components/venice_2017/stylesheets/body.styl
- desktop/apps/editorial_features/components/venice_2017/stylesheets/index.styl
- desktop/apps/editorial_features/components/venice_2017/templates/body.jade
- desktop/apps/editorial_features/components/venice_2017/templates/index.jade
- desktop/apps/editorial_features/test/components/venice_2017/index.coffee
Since the carousel dictates routing on client-side, going to https://www.artsy.net/venice-biennale/episode-2 (Episode 2) feels a little clunky since Flickity always "shows" the first item before going to the right index. This problem is better understood visually: 
Problem: 
Solution:
> @craigspaeth => [Venice] Cleaner initial load on episodes 2+

- desktop/apps/artwork/components/partner_stub/index.jade
This will remove the `if sd.QUERY.inquire_via_phone` check and everyone will see the "Inquire via phone" link.
> Roll out the Inquire via Phone modal

- yarn.lock
Pulls in these two PRs: https://github.com/artsy/artsy-eigen-web-association/pull/11, https://github.com/artsy/artsy-eigen-web-association/pull/12 to exclude *all* Venice routes from redirecting to the app. Previously we just had the landing page.
> @xtina-starr => Update artsy-eigen-web-association

- desktop/apps/consignments2/client/index.js
- desktop/apps/consignments2/routes.js
- desktop/apps/consignments2/stylesheets/index.styl
- desktop/apps/consignments2/stylesheets/landing/desktop.styl
- desktop/apps/consignments2/stylesheets/landing/faq.styl
- desktop/apps/consignments2/stylesheets/landing/mobile.styl
- desktop/apps/consignments2/templates/faq.jade
- desktop/apps/consignments2/templates/landing.jade
- desktop/apps/consignments2/test/fixture.json
Nothing super interesting here:
- Updated the `recentlySold` artworks to be fetched via a metaphysics query 
- Added an FAQ modal-- spent a while thrashing around seeing if there was a way to reuse one of the existing modal components in force but they all seem to require some form of backbone view/fetching. In this case we explicitly want to keep the FAQ text on the DOM for seo purposes, so I did a somewhat old-school approach of basic jquery to hide/show the modal div and pure css.
- Made the layout responsive
- Updated the fixtures file to add an additional background image for mobile-only
desktop:
mobile:
> @craigspaeth => Responsive landing page for consignments + modal

- desktop/apps/partner/templates/overview.jade
This is one of the items in https://github.com/artsy/collector-experience/issues/74. There may be other pages that show non-partner information, but let me know if there is anything I missed that I should update.
> @mzikherman => Hide non-partner contact information

- desktop/apps/consignments2/client/actions.js
- desktop/apps/consignments2/components/upload_photo/index.js
- desktop/apps/consignments2/components/upload_photo_landing/index.js
- desktop/apps/consignments2/components/upload_photo_landing/index.styl
This PR fixes some issues around uploading a photo when you visit the `/consign2/submission/:submission_id/upload` path directly. I removed the `No photos at this time` checkbox since at this point we want you to upload a photo, and added a login path if you visit the page while logged out.
If you try to submit a photo for a submission that is not your own, convection will reject the request, so we don't have to worry about that here.
> @damassi => upload photo landing page + login prompt

- desktop/analytics/partner.js
The analytics itself is set up, but there are some questions around how it is set up:
* There is an existing analytics that tracks website clicks on the old `partner` page, and a context specifier should probably have to be set for the new analytics added in this PR.
* I wasn't sure what the naming conventions are for `analyticsHooks` event names. In this WIP PR, I just followed [what Matt's suggested](https://github.com/artsy/force/pull/1446#discussion_r117307589), but I'm open to other suggestions as other hook names are formatted like `event:name:for:action` rather than being `evenNameForAction`.
> @starsirius => Track website clicks on the partner2 contact page

- desktop/apps/article/templates/meta.jade
The main issue is that recent articles aren't being indexed as News in Google and sometimes they aren't appearing in regular search. I don't _think_ this PR solves it, but at the least -- it's unnecessary to have. Based on [this slack convo](https://artsy.slack.com/archives/C02BDPZPC/p1494268425535679), I can confirm that articles are rendered server-side so there's no need for Reflection to crawl.
[This page](https://www.google.com/webmasters/tools/sitemap-details?hl=en&authuser=3&siteUrl=https%3A%2F%2Fwww.artsy.net%2F&sitemapUrl=https%3A%2F%2Fwww.artsy.net%2Fsitemap-news.xml&gwtPl=L3dlYm1hc3RlcnMvdG9vbHMvc2l0ZW1hcC1saXN0P2hsPWVuJmF1dGh1c2VyPTMmc2l0ZVVybD1odHRwczovL3d3dy5hcnRzeS5uZXQvI01BSU5fVEFCPTAmQ0FSRF9UQUI9LTE%3D#CARD_TAB=-1) tells me that News articles are submitted via the …
> @joeyAghion => Remove fragment metatag on article

- desktop/apps/editorial_features/components/venice_2017/templates/index.jade
Restores modal to the Venice template. Was causing a bug when logged out users attempted to follow, which renders a login prompt using the modal.
> @kanaabe => Follow button bug

- desktop/components/main_layout/header/view.coffee
- desktop/components/main_layout/stylesheets/body_with_header_split_test.styl
closes: https://github.com/artsy/force/issues/1499
This PR moves the hover and focus border styles to its outer container to prevent the nav bar texts from jumping.
> @yuki24: Moves the hover and focus styles to the inputs container

- circle.yml
As discussed, this should be safe now that the user is removed from the org (and thus no longer has access to _our_ repos).
> @craigspaeth => Check-in ArtsyOpenSource token for Danger

- desktop/apps/search/client/index.coffee
- desktop/apps/search/templates/search_result.jade
- desktop/components/search_bar/view.coffee
Per [request](https://github.com/artsy/collector-experience/issues/251#issuecomment-306265105), we are adding the `item_id` to the search results analytics tracking.
> @mzikherman: add item_id to search result analytics

- desktop/apps/article/templates/article.jade
- desktop/apps/article/test/templates.coffee
- desktop/apps/artsy_primer/templates/article.jade
Uses article's indexable tag to add noindex meta tag, rather than tags.
This should not be merged until a backfill of the indexable field is complete. 
I did not remove the meta from the [primer template](https://github.com/artsy/force/blob/a7850384aa163c362c1b7fb1014085c682a12f60/desktop/apps/artsy_primer/templates/article.jade), do you think this should be removed as well?
> @kanaabe => Use indexable for noindex meta tag

- desktop/apps/consignments2/client/reducers.js
- desktop/apps/consignments2/client/submission.js
- desktop/apps/consignments2/components/choose_artist/index.js
- desktop/apps/consignments2/components/choose_artist/index.styl
- desktop/apps/consignments2/components/describe_work_desktop/index.js
- desktop/apps/consignments2/components/describe_work_desktop/index.styl
- desktop/apps/consignments2/components/describe_work_mobile/index.js
- desktop/apps/consignments2/components/describe_work_mobile/index.styl
- desktop/apps/consignments2/components/forgot_password/index.js
- desktop/apps/consignments2/components/forgot_password/index.styl
- desktop/apps/consignments2/components/location_autocomplete/index.styl
- desktop/apps/consignments2/components/log_in/index.js
- desktop/apps/consignments2/components/log_in/index.styl
- desktop/apps/consignments2/components/select_input/index.js
- desktop/apps/consignments2/components/select_input/index.styl
- desktop/apps/consignments2/components/sign_up/index.js
- desktop/apps/consignments2/components/sign_up/index.styl
- desktop/apps/consignments2/components/submission_flow/index.js
- desktop/apps/consignments2/components/submission_flow/index.styl
- desktop/apps/consignments2/components/text_input/index.js
- desktop/apps/consignments2/components/thank_you/index.styl
- desktop/apps/consignments2/components/upload_photo/index.js
- desktop/apps/consignments2/components/upload_photo/index.styl
- desktop/apps/consignments2/components/uploaded_image/index.styl
- desktop/apps/consignments2/stylesheets/landing/desktop.styl
- desktop/apps/consignments2/stylesheets/landing/mobile.styl
- desktop/apps/consignments2/test/components.js
Mostly little style things, but here's a list of fixes from Katarina and I's QA session today:
- Replace the hover-select box with one that you click into 👏 
- The default `authFormState` is now `'signUp'` unless you are entering from the `/upload` path
- In the responsive view, gets rid of the page-wide "Consign your work to Artsy..." title and includes the sub header on each page
- auto-focuses the first input element on each page
- Vertically stacks the elements on the `/thank_you` page
> @damassi => little visual fixes for consign2

- desktop/components/marketing_signup_modal/index.coffee
- desktop/components/marketing_signup_modal/index.jade
- desktop/components/marketing_signup_modal/index.styl
- desktop/config.coffee
- mobile/components/marketing_signup_modal/index.jade
- mobile/components/marketing_signup_modal/index.styl
- mobile/components/marketing_signup_modal/middleware.coffee
- mobile/config.coffee
closes: https://github.com/artsy/collector-experience/issues/314
This work updates the marketing modal to add a dedicated modal for the Art Basel 2017 campaign. This modal gets triggered on desktop and mobile web when a user navigates to the Art Basel 2017 Microsite or enters the `m-id=ca3` query param in the url.
*note:* updating the environment variables are pending.
**Desktop version:**
**Mobile version:**
> @craigspaeth: Marketing modals

- desktop/apps/auction/routes.js
- desktop/apps/auction/server.js
- desktop/apps/auction/templates/index.jsx
- desktop/apps/auction/utils/artwork.js
- desktop/lib/partial_renderer.js
- desktop/test/lib/partial_renderer_spec.js
- package.json
- yarn.lock
I've spent a good amount of time thinking about how we can start modernizing our server-side template flow and realized that its simpler than I thought to interpolate the two engines, due to Express providing an `html` callback to `res.render`, e.g.: 
```javascript
res.render('index.jade', { 
... 
}, (error, html) => {
res.render('index.jsx', { 
html 
})
})
```
Testing this on `/auctions/:id` it works as you'd expect. This will allow us to incrementally start moving our `jade` fragments over to React without having to throw the whole thing out and start from scratch (unless I'm missing something big).
Additionally, I've created a new helper under `/lib/partial_renderer.js` that exports two functions, `renderPartial` and `renderPartialSet`. They can be used like so in a typical Express …
> @craigspaeth => Add support for server-side React rendering

- mobile/apps/partner_profile/routes.coffee
- mobile/apps/partner_profile/templates/index.jade
- mobile/apps/partner_profile/test/routes.coffee
- mobile/apps/partner_profile/test/templates.coffee
- mobile/models/partner.coffee
- test/acceptance/helpers/index.js
- test/acceptance/partner_profile.js
This removes contact information for non-active partners on microgravity. Same work as https://github.com/artsy/force/pull/1458, this is just on mobile.
> @mzikherman => Hide contact information for non-active partners on mobile

- .babelrc
- desktop/apps/auction/client/actions.js
- desktop/apps/auction/client/test-file.coffee
- desktop/apps/auction/routes.js
- package.json
- yarn.lock
Closes https://github.com/artsy/force/issues/942.
Since I'm about to do a long stint inside of Force I wanted to sweep back through and follow up on a few things I had started thinking about a while back, with absolute module resolution being no.1 (and server-side React being no.2  😄)
What this PR does is set up [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) to take absolute paths encountered in code and remap them to their corresponding file-system location, with aliases set up in `.babelrc`. There is a similar setup in Prediction. When using ES6+, resolution works seamlessly across the server and client and tests, though CoffeeScript code, while importable, must internally resolve paths the old way. I'm sure this can be fixed (but right now is …
> @craigspaeth => Add ability to import modules via absolute paths

- desktop/apps/consignments2/client/reducers.js
- desktop/apps/consignments2/components/describe_work_desktop/index.js
- desktop/apps/consignments2/components/step_marker/index.js
- desktop/apps/consignments2/components/step_marker/index.styl
- desktop/apps/consignments2/components/text_input/index.js
- desktop/apps/consignments2/components/text_input/index.styl
- desktop/apps/consignments2/stylesheets/landing/desktop.styl
- desktop/apps/consignments2/stylesheets/landing/mobile.styl
- desktop/apps/consignments2/templates/landing.jade
- desktop/apps/consignments2/test/components.js
Just some little UI stuff here. 😄 
Finally got the horizontal step marker lines to work!
I also added in some client-side validation for the fields (`height`, `width`, `depth`, `edition_size`), that we store as number in the backend, to make sure you input a number here. Will ask for final design help from @katarinabatina on those but it should be fine for now. 😄
> @damassi => Consign2 step marker + number validations

- desktop/components/article/stylesheets/content.styl
Retains full width layout for articles list, keeps CTAs at full bleed.
https://github.com/artsy/force/issues/1538
> @xtina-starr => Fix margins on articles

- mobile/analytics/partners.js
As per the discussion [here](https://artsy.slack.com/archives/C03NF9TKR/p1496249197342826), I'm migrating old event names to new ones. This PR should update the mobile `partner` page to send a `click` event from both mobile web/iOS app (eigen just uses WebView for it).
> @xtina-starr => Migrate 'Clicked Gallery Website' event on mobile to 'Click' event

- desktop/apps/auction/client/reducers.js
- desktop/apps/auction/components/sidebar/index.js
This is a super temporary fix, just so we can launch the creative time auction in an hour or so.
The Creative Time auction is currently not showing any artworks on the auction page because none of the artworks have estimates, which is a field that we're filtering by. For _now_ we can fix this by explicitly not passing the `estimate_range` param in our query (sending `''` or `'0-*` is not sufficient). We also need to hide the price filter box.
I will follow up immediately with the "correct" fixes, which will be to either _also_ filter the price filter by the starting price cents, or to be more forgiving on gravity's side, and have a flag for hiding the price filter on the front end. I'm leaning towards the first option but have to confirm with Devang.
> @craigspaeth => Hack for creative time :(

- lib/middleware/proxy_to_reflection.coffee
- test/lib/middleware/proxy_to_reflection.coffee
Addresses https://github.com/artsy/force/issues/1460 by making a HEAD request to the Reflection url first, and if it fails for whatever reason including 403 responses, then it passes control to Force rendering instead of attempting to proxy Reflection.
This extra request is unfortunate overhead as we can't interrupt Node HTTP Proxy [barring this open PR](https://github.com/nodejitsu/node-http-proxy/pull/850), but I'm hoping this is a fine tradeoff as an extra ping to S3 shouldn't be too slow.
> @joeyAghion: Fall through to Force rendering if Reflection fails to respond

- desktop/lib/reloadable.js
This PR adds a DX utility for server-side code reloading, but without a full server restart. Greatly speeds up development time by watching all files specified by a given `appPath` (defaults to `desktop`) and, when a new request is made (page refresh), re-mounts the app, clears node's internal module cache and effectively reloads the app source-code. 
The function signature is `reloadable(app, expressCallback, appPath)`.
As suggested by @alloy, in the future we can pull this out into its own package but wanted to drop this in `/lib` for now so that others can take advantage in the interim. So much faster! 
**index.js** 
```javascript 
import express from 'express'
import reloadable, { isDevelopment } from 'desktop/lib/reloadable'
const app = module.exports = express()
app.set('view …
```
> @craigspaeth => Add lib/reloadable for server-side code reloading 

- desktop/apps/consignments2/client/actions.js
- desktop/apps/consignments2/components/checkbox_input/index.js
- desktop/apps/consignments2/components/choose_artist/index.js
- desktop/apps/consignments2/components/step_marker/index.styl
- desktop/apps/consignments2/components/submission_flow/index.js
- desktop/apps/consignments2/components/submission_flow/index.styl
- desktop/apps/consignments2/components/upload_photo/index.js
- desktop/apps/consignments2/stylesheets/index.styl
- desktop/apps/consignments2/templates/submission_flow.jade
- desktop/apps/consignments2/test/reducers.js
This PR fixes a few little UX edge cases:
- If you navigate back to the `/choose-artist` page (still client-side), we now allow you to advance using the `Next` button instead of just by clicking an autocomplete result
- On the Upload photos page, if you check the "No photos available" box while some images are partially processed, we used to enable the submit button. This fixes that.
- If you check the `edition` box on the `/describe-your-work` page and then fill in the `edition_size` and `edition_number` fields but then _uncheck_ the `edition` box (causing those fields to disappear), we now make sure to scrub them from the inputs sent to convection.
It also adds a footer (only in desktop mode).
> @damassi => little UX fixes + footer for consign2 page

- desktop/components/article/stylesheets/fullscreen_article.styl
The `.article-fullscreen_container` can either have one or two elements as children, so if there are two, we should justify with `space-between`, otherwise `flex-end`. 
Sorry for this last minute bug before your deploy!
> @sweir27 => Bug fix for fullscreen & non super article

- desktop/apps/consignments2/components/describe_work_desktop/index.js
- desktop/apps/consignments2/components/describe_work_mobile/index.js
- desktop/apps/consignments2/components/text_input/index.js
- desktop/apps/consignments2/components/text_input/index.styl
This PR adds in a little more obvious validation to the form fields-- the use-case is trying to catch a potential issue where the form doesn't register an input leaving the submit button disabled.
Note that this will only come up if you've attempted to enter a form field (and then backspace out for some reason). The button will be enabled in that case but we'll give you some messaging.
> @sweir27 => a little more obvious validation on the consign flow

- desktop/apps/consignments2/components/describe_work_desktop/index.js
- desktop/apps/consignments2/components/describe_work_mobile/index.js
The button will only be _disabled_ if there's no location. Turns out the `pristine` check is not what we want when the page is reloaded with initial values.
> @sweir27 => few more validation improvements

- desktop/analytics/partner.js
I confirmed that `'Clicked Contact Gallery Via Email'` and `'Clicked Gallery Website'` are not being sent anymore (segment stats: [email clicks](https://segment.com/artsy-engineering/sources/force-production/schema/tracks/Clicked%2520Contact%2520Gallery%2520Via%2520Email) and [website clicks](https://segment.com/artsy-engineering/sources/force-production/schema/tracks/Clicked%2520Gallery%2520Website)) and safe to remove at this point.
> Remove obsolete tracking code

- desktop/apps/article/index.coffee
- desktop/components/article/stylesheets/super_article.styl
- desktop/components/article/templates/super_article_footer.jade
- desktop/components/article/test/templates.coffee
Related to: https://github.com/artsy/positron/issues/1116 and https://github.com/artsy/positron/pull/1123
We need to add markdown support in the "Super Article" footer for an upcoming sponsorship. [Here's an example of a super article](https://www.artsy.net/article/artsy-editorial-2015-the-year-in-art).
> @yuki24 => Markdown supported SuperArticle footer

- desktop/apps/consignments2/client/reducers.js
- desktop/apps/consignments2/client/validate.js
- desktop/apps/consignments2/components/describe_work_desktop/index.js
- desktop/apps/consignments2/components/describe_work_mobile/index.js
- desktop/apps/consignments2/components/location_autocomplete/index.js
- desktop/apps/consignments2/components/location_autocomplete/index.styl
- desktop/apps/consignments2/components/step_marker/index.styl
- desktop/apps/consignments2/components/submission_flow/index.js
- desktop/apps/consignments2/components/submission_flow/index.styl
- desktop/apps/consignments2/components/text_input/index.js
- desktop/apps/consignments2/components/text_input/index.styl
- desktop/apps/consignments2/stylesheets/index.styl
- desktop/apps/consignments2/stylesheets/landing/desktop.styl
- desktop/apps/consignments2/stylesheets/landing/mobile.styl
- desktop/apps/consignments2/templates/submission_flow.jade
This PR includes a bunch of minor things:
- Adds _all_ of the fields to the mobile form. Note that the layout is still different enough that I think it warrants having two separate components, but I extracted the `validate` function.
- Updates the form to have a more "typical" UX --> the submit button is now enabled by default. Clicking it either submits the form or highlights all of the missing fields in red and scrolls you to the _first_ erroneous field.
- Removes the big `title` from the submission flow and updates the step labels to be on one line for larger breakpoints
- Updates the location input to erase when it is unfrozen (in the gif above)
> @damassi => update the validation requirements on the submission flow

- desktop/components/article/templates/super_article_footer.jade
Closes https://github.com/artsy/positron/issues/1127 (erroneously in positron)
The cta container in the superArticle footer provides the margin between the description and logo.  Added the div back, and print the link conditionally to preserve formatting.
> @kanaabe => bombay footer bug

- desktop/models/search_result.coffee
- desktop/test/models/search_result.coffee
- mobile/models/search_result.coffee
this is the follow up to https://github.com/artsy/gravity/pull/11125, which allows us to use custom destination paths for editorial/featured content in search results.
> @kanaabe : use custom href in search results if one exists

- README.md
- circle.yml
This adds a push to the staging branch on Force after the deploy to staging build finishes so that we can ensure we don't deploy anything into production that hasn't made it to staging yet. The new workflow is to simply PR from staging to release instead of master to release.
> @sweir27: Use staging > release flow instead of master > release

- desktop/components/article/client/view.coffee
- desktop/components/article/templates/mixins.jade
Closes https://github.com/artsy/positron/issues/1128
Looks like the article.related() was throwing a type error on empty superarticles, adding a conditional lets it render without timing out.
> @kanaabe => Superarticles with no subArticles

- desktop/apps/search/client/index.coffee
@yuki24 and I looked into this for a while and it was quite difficult to determine. We believe that some of the JS analytics files aren't always being loaded correctly. When that occurs the `e.preventDefault()` prohibits the link from working correctly. While removing this restores the link we should figure our why the analytics javascript isn't loading like it should which is represented in https://github.com/artsy/force/issues/1587.
> @yuki24 - restore link when js is not loaded properly

- desktop/apps/article/client/index.coffee
- desktop/apps/article/routes.coffee
- desktop/apps/article/test/routes.coffee
- desktop/components/article/stylesheets/super_article.styl
- desktop/components/article/templates/super_article_footer.jade
- desktop/components/email/client/editorial_signup.coffee
- desktop/components/email/test/editorial_signup.coffee
Switches the SA logic to rely on the existence of `sd.SUPER_ARTICLE` instead of `sd.SUPER_SUB_ARTICLES` to support the zero case.
> @eessex => SuperArticle footer & infinite scroll bugs

- desktop/apps/react_example/client.js
- desktop/apps/react_example/components/App.js
- desktop/apps/react_example/components/DOM.js
- desktop/apps/react_example/components/meta.jade
- desktop/apps/react_example/components/my_jade_view.jade
- desktop/apps/react_example/index.js
- desktop/apps/react_example/routes.js
- desktop/apps/react_example/server.js
- desktop/assets/react_example.coffee
- desktop/components/main_layout/templates/react_index.jade
- desktop/components/react/utils/build_template_component.js
- desktop/components/react/utils/render_react_layout.js
- desktop/components/react/utils/test/render_layout_test.js
- desktop/index.js
From our little workshop earlier today! I've also updated the util with some docs for clarity and fixed that bug we saw earlier related to client-side Jade templates. (Will clean up in another PR, but fine for now.)
**To view**: 
```sh
yarn start
open http://localhost:5000/react-example
```
Note that I've broken everything out in three sections so you can see how things interact:
> @kanaabe => Add isomorphic React App example 

- desktop/analytics/before_ready.js
- desktop/assets/analytics.coffee
- desktop/components/main_layout/templates/scripts.jade
One-line explanation: the contents of the before_ready.js script should run before we download any Segment analytics. Related to: https://github.com/artsy/force/issues/1587
For more detail:
We're supposed to mark pages that shouldn't be tracked with Parsely with:
```
window.PARSELY = {autotrack: false}
```
Currently, this happens in before_ready.js the analytics.coffee file. My guess is there's a race condition between Segment scripts downloading, and this above code that _should_ halt Parsely from initializing things like pInit and heartbeats. 
I can see that on pages where we have {autotrack: false}, those Parsely scripts with pInit and heartbeats are downloading which doesn't make sense.
> @yuki24 => Safeguard against possible race condition to load Parsely script

- mobile/apps/home/routes.coffee
This was just a simple oversight on my part when I refactored hero units to be randomized and use
GraphQL on mobile—whoops! Pointing to the correct platform enum now. Related to [this thread](https://artsy.slack.com/archives/C0350895E/p1498747973622367).
> @mzikherman: Point mobile hero units to MARTSY

- desktop/components/article/templates/mixins.jade
We need to ensure the video is muted + playsinline for autoplay to work in iOS.
> @craigspaeth => Autoplay videos in fullscreen headers (iOS fix)

- desktop/apps/partner2/components/fixed_cells_count_carousel/articles.jade
- desktop/apps/partner2/components/fixed_cells_count_carousel/fair_booths.jade
Slack report: https://artsy.slack.com/archives/C03JWJLLH/p1499286765372741
Back in https://github.com/artsy/force/pull/419 we fixed the problem of up-scaled cover images for **shows**.
This simply does the same for **fair booths** and **articles**, all of which appear on partner page overviews/sections.
> Fix blurry cover images

- desktop/apps/notifications/stylesheets/mobile.styl
- desktop/assets/misc.styl
This fixes that strange issue where `avant-garde-size` was conflicting when I pulled over the mobile component into a desktop app—causing certain pages to render garamond when it should have rendered avant garde. This is another unfortunate case where the global nature of CSS causes maintenance headaches. While we get `@require`s in Stylus, they don't operate like `import`s in a real programming language like JS—they essentially just smartly concatenate files, so we have to be diligent about namespacing even in mixins.
Regardless, after thinking it over I decided it's probably best to just copy-paste over the relevant styles in this case because our goal is to eventually drop ./mobile and importing into ./mobile is only going to make that more difficult to untangle down the line.
> @sweir27: Fix typography issues on settings page

- desktop/apps/article/test/client/index.coffee
- desktop/apps/article2/__tests__/routes.test.js
- desktop/apps/article2/client.js
- desktop/apps/article2/components/App.js
- desktop/apps/article2/components/__tests__/App.test.js
- desktop/apps/article2/components/meta.jade
- desktop/apps/article2/index.js
- desktop/apps/article2/queries/article.js
- desktop/apps/article2/routes.js
- desktop/apps/article2/server.js
- desktop/apps/partner/test/client/articles.coffee
- desktop/apps/partner2/test/client/articles.coffee
- desktop/assets/article2.coffee
- desktop/config.coffee
- desktop/index.js
- desktop/test/helpers/fixtures.coffee
- package.json
- yarn.lock
Screenshot is pretty rough, but it gives you the idea. Sets up SSR thanks to @damassi prior work and renders the available components from `reaction`. Right now this only renders `/article2/:id` instead of `/article2/:slug` which I'll fix next! (needs to be on the Positron side)
> @eessex => Article2 SSR w/reaction components

- desktop/apps/consign/client/actions.js
- desktop/apps/consign/components/choose_artist/index.js
- desktop/apps/consign/components/describe_work_container/index.js
- desktop/apps/consign/helpers.js
- desktop/apps/consign/test/helpers.js
This PR fixes 3 little UI bugs, and makes a slight UI adjustment.
Changes:
- Fixes the issue where the spinner would be enabled if you pressed back after uploading a photo
- Fixes the issue where you couldn't re-submit the "describe your work" page because the location would not be validated on rehydration
- **UX adjustment** we used to have it where if you click on an artist from the dropdown, it automatically advances you to the next step. A few bugs cropped up from this behavior, and I remember chatting about how it can be a bit jarring. This PR updates that flow to instead require an explicit click of the "Next" button to advance.
> @damassi => fix little UI bugs on the consign flow

- desktop/apps/artwork/components/auction/templates/bid.jade
- desktop/apps/artwork/components/auction/test/view.coffee
Fixes regression where the bid dropdown only appears after registration: 
**Before:** 
**After:**
> @sweir27 => [BUGFIX] Always show bid dropdown

- package.json
- yarn.lock
`0.1.47` has https://github.com/artsy/reaction/pull/195 and https://github.com/artsy/reaction/pull/194 that should fix the gene page.
> Fixed a bug where gene page does not show artworks

- mobile/apps/artwork/components/meta_data/templates/partner.jade
- mobile/apps/artwork/components/meta_data/test/template.coffee
This fixes the issue where partner names were linking to non-existent urls for auction lots. It seems like the template was assuming that partner slugs would be the same as sale slugs, so was constructing a url like `/auction/#{default_profile_id}`. This may have been valid in _some_ cases but it would have been a happy accident. 
Once we have partner profile pages for auction houses we will be able to link to those, but for now I'm removing the `a` tag per discussion with @devangt so they at least don't lead to a 404.
> @damassi => remove the partner link for auction artworks

- desktop/apps/artwork/components/partner_stub/index.jade
As per [the discussion here](https://github.com/artsy/collector-experience/issues/74#issuecomment-314891645), the current analytics tracking code sends extra information that is unnecessary and doesn't give us enough insights to see drop off rate for sign up from "Inquire via phone" modal. This PR makes the following changes:
* Do not send unneeded partner information
* Send `context` and `user_id` so we can track drop off rate for signup
> Update alanytics ctacking for "show phone number"

- desktop/components/main_layout/templates/head.jade
- desktop/components/main_layout/templates/index.jade
This PR update Force to point to self-hosted webfonts, as opposed to downloading via a font-face CDN. Fonts have been uploaded to S3 and a container CSS file imports them into the app. 
See: https://s3.console.aws.amazon.com/s3/buckets/artsy-webfonts and http://webfonts.artsy.net/ 
Thanks @kanaabe for your S3 help!
> @craigspaeth => Self-host webfonts via S3

- desktop/apps/article/templates/amp_mixins.jade
- desktop/apps/article2/queries/article.js
- desktop/components/article/templates/mixins.jade
- desktop/components/article/test/templates.coffee
Deprecates `background_image_url` and `background_url` in favor of the simpler, `url` field that is used across hero section types. The `url` is already backfilled.
> @eeessex => Use url field for fullscreen hero sections

- desktop/models/article.coffee
- desktop/test/models/article.coffee
Re: https://artsy.slack.com/archives/C04GGGDCM/p1501252422796212
Updates article model to return date in NY timezone if channel is editorial, otherwise returns local time.
> @craigspaeth => Use NY timezone for editorial articles

- package.json
While I was investigating the FB login issue I realized that heroku uses [a nightly version of `yarn`](https://dashboard.heroku.com/apps/force-staging/activity/builds/b6cfef18-b413-425b-9fa1-3d367454f702) (find `0.28.1`). I installed the same nightly version by [following the steps here](https://yarnpkg.com/en/docs/nightly) and was able to reproduce the same issue locally. It's possible that the nightly yarn solves or loads dependencies differently than the current stable version.
This PR adds `engines.yarn` with the latest stable version [as suggested by a heroku employee](https://github.com/heroku/heroku-buildpack-nodejs/issues/342#issuecomment-267433492).
> Always use yarn version specified in package.json

- desktop/analytics/artwork.js
- desktop/apps/artwork/components/partner_stub/index.jade
It turns out https://github.com/artsy/force/pull/1641 broke the Inquire via Phone modal. Instead of removing the partner object entirely from the template, we should just exclude the `partner` key explicitly before sending the data to analytics.
> Fix inquire via phone modal

- desktop/apps/gallery_partnerships2/client/index.coffee
- desktop/apps/gallery_partnerships2/stylesheets/index.styl
Right now, the navigation dots for testimonials on http://staging.artsy.net/gallery-partnerships2 are not working. This PR fixes it.
> Fixes an issue where nav dots for testimonials weren't working

- .babelrc
- desktop/apps/react_example/components/App.js
- desktop/components/main_layout/templates/react_index.jade
- desktop/components/react/responsive_window/test/responsive_window_spec.js
- desktop/components/react/utils/renderReactLayout.js
- desktop/components/react/utils/test/renderLayout.test.js.js
- package.json
- yarn.lock
Adds styled-components to Force and extracts the styles in `renderReactLayout.js` 
It looks like we don't need to add the babel-plugin for now -- this works without checksum errors on the react-example and the current version of article2. The checksum error we saw must have come from something I wrote in my other branch.
Thanks @damassi and @alloy for debugging/chatting about this with me!
> @damassi => Adds SSR for styled-components

- .babelrc
Fixes issue we were seeing with `NODE_ENV=production` deploys and `styled-components`.
> @kanaabe => Only add .babelrc styled-components lib in development

- desktop/components/article/templates/mixins.jade
re: https://artsy.slack.com/archives/C04GGGDCM/p1502132086251768
Video container height is set on the client to match aspect-ratio to screen width.  The caption was inside this container, meaning that it was overflowing the container height. 
This moves the caption up one level, so it is not inside the resized container.
> @kanaabe => Video caption

- desktop/apps/auction2/components/artwork_browser/ArtworkBrowser.styl
- desktop/apps/auction2/stylesheets/index.styl
- desktop/apps/order/stylesheets/mobile.styl
- desktop/apps/order/templates/checkout.jade
- desktop/apps/order/templates/shipping.jade
- desktop/components/react/responsive_window/index.js
- desktop/components/stylus_lib/index.styl
This PR accommodates a few different orientations for `/auctions2/id`, namely iPad-like dimensions (which orient as desktop mode) and iPhone portrait / landscape. 
Breakpoints for mobile start at 768px. 
Additionally 
- The route `/orders` has been modified so that its responsive css does not leak into the global scope 
- A footer has been added to the mobile `auctions/:id` view. 
---
---
---
> @craigspaeth => Add additional responsive breakpoints

- desktop/apps/gallery_partnerships/stylesheets/index.styl
[As requested here](https://github.com/artsy/collector-experience/issues/447), this PR adds a fade effect to the testimonials:
> Add a fade effect to the testimonials

- lib/middleware/error_handler.coffee
- test/acceptance/artwork.js
- test/acceptance/auth.js
- test/acceptance/bidding.js
- test/acceptance/helpers/index.js
- test/acceptance/home.js
- test/acceptance/misc.js
- test/acceptance/partner_profile.js
Related convo here: https://artsy.slack.com/archives/C0350895E/p1501103674430615
WIP because there are two tests still spitting out error messages and I'm still trying to figure out the best place to fix them.
Also, I wanted to stub `app.get('/auctions/reminders')` after [this](https://github.com/artsy/force/blob/master/test/acceptance/helpers/index.js#L110) but because of express finding routes in order, I can't override it. I could recreate the app, but that feels like going down a rabbit hole just to stub one route hence all of the `stubAuctionReminder`s.
> @damassi => Update acceptance tests to handle console errors

- desktop/apps/consign/stylesheets/landing/desktop.styl
- desktop/apps/consign/templates/landing.jade
- desktop/apps/consign/test/routes.js
- desktop/apps/consign/test/templates.js
This PR hides the "your work could be in upcoming sales!" section in the case where there are no upcoming sales (probably an edge case at this point since we run so many! but still possible).
It also fixes the spacing on the landing page re https://github.com/artsy/consignments/issues/59:
> @damassi => update width of steps and hide auctions section if there are no upcoming auctions

- desktop/apps/auction2/components/Layout.js
- desktop/apps/auction2/components/artwork_browser/__tests__/ArtworkBrowser.test.js
- desktop/apps/auction2/components/artwork_browser/main/ArtworkDisplay.js
- desktop/apps/auction2/components/artwork_browser/main/artwork/GridArtwork.js
- desktop/apps/auction2/components/artwork_browser/main/artwork/ListArtwork.js
- desktop/apps/auction2/components/artwork_browser/main/artwork/MasonryArtwork.js
- desktop/apps/auction2/components/artwork_browser/main/artwork/__tests__/GridArtwork.test.js
- desktop/apps/auction2/components/artwork_browser/main/artwork/__tests__/ListArtwork.test.js
- desktop/apps/auction2/components/artwork_browser/main/artwork/__tests__/MasonryArtwork.test.js
- desktop/apps/auction2/components/artwork_browser/sidebar/WorksByFollowedArtists.js
- desktop/apps/auction2/components/artwork_browser/sidebar/WorksByFollowedArtists.styl
- desktop/apps/auction2/utils/queries/worksByFollowedArtists.js
- desktop/components/react/utils/test/renderReactLayout.test.js
This PR fixes the 500 error stemming from Followed Artists that happen to appear in a given auction -- the module itself had never been properly implemented! 
(Note that in mobile mode it is hidden.)
> @sweir27 => Fix <WorksByFollowedArtists /> display

- desktop/components/artwork_item/templates/artwork.jade
- desktop/components/artwork_item/templates/partials/price.jade
- desktop/components/artwork_item/test/artwork.coffee
Closes #1577
In an ironic twist of fate, my last PR is fixing a bug in the artwork_item template.
Please look carefully at this, there might be something I am missing. The artwork in question: https://api.artsy.net/api/v1/artwork/pacita-abad-feel-the-beat
> @mzikherman - Allow price to be shown for institutional sellers with price info in artwork item

- desktop/apps/gallery_partnerships/stylesheets/index.styl
This PR addresses two issues:
* removes the fade effects from mobile screens on any browser
* removes the unwanted dark bars and shows proper fade effects to the testimonial section on safari
closes https://github.com/artsy/collector-experience/issues/467
> Fixes unwanted dark bars on the new gallery partnerships page

- desktop/apps/artist/stylesheets/sections.styl
- desktop/apps/artist/templates/sections/cv_item.jade
- desktop/apps/artist/templates/sections/exhibition_highlights.jade
- desktop/apps/artist/templates/sections/overview.jade
- desktop/apps/artist/templates/sections/show_groupings.jade
- desktop/apps/artwork/components/artists/index.styl
- desktop/apps/artwork/components/artists/templates/exhibition.jade
- desktop/apps/artwork/components/artists/templates/highlights.jade
and also change some show listing formatting:
Still awaiting approval, and also have an outstanding question about linking to the partner for (we only link to the show if its on Artsy/available, and not at all for ref shows), but this finishes the Force issues in https://github.com/artsy/collector-experience/issues/155
> @cavvia => Remove '... on Artsy' from some show section headers

- desktop/apps/artist/queries/show_fragment.coffee
- desktop/apps/artist/stylesheets/sections.styl
- desktop/apps/artist/templates/sections/cv_item.jade
- desktop/apps/artist/templates/sections/exhibition_highlights.jade
- desktop/apps/artist/templates/sections/show_groupings.jade
- desktop/apps/artwork/components/artists/index.styl
- desktop/apps/artwork/components/artists/query.coffee
- desktop/apps/artwork/components/artists/templates/exhibition.jade
- desktop/apps/artwork/components/artists/templates/highlights.jade
(had my mouse hovered over the first underlined partner in the pic ^)
This links to the partner (when possible), and adds an underline on hover. Refactored some of the helper code as well.
Last thing for Force in the re-formatting is to maybe hide the year's / organize by section- still waiting confirmation, can be in a later PR.
> @cavvia => Link to the partner if possible (underline on hover) in show listings

- desktop/analytics/criteo.js
- desktop/apps/artist/queries/server.coffee
We were fetching 50 `for_sale` artworks on every artist page reload (from any tab) in order to ping criteo. Since we're not using this feed feature anymore, we can improve our load time a bit by removing.
> @craigspaeth => remove excessive artworks fetch on artist page

- desktop/assets/react_example.coffee
Last couple of Force deploys generated empty assets, also saw some errors in the Circle console:
Just rewrote the file to be a bit clearer, not sure if there's any actual issue here. /shrug
> @damassi => Alternate specification for react_example asets

- scripts/assets.sh
A naive thought is that `factor-bundle` isn’t opening `stdin` immediately
and uglifyjs isn’t taking that possibility into account, whereas `cat`
does? Not sure, although this does seem to work.
> [deploy] Ensure stdin is open when invoking uglifyjs.

- lib/setup.js
To make Force a little safer, this PR only `require`'s `@artsy/express-reloadable` when `NODE_ENV=development`.
> Only import reloadable when NODE_ENV=development

- desktop/apps/partner2/stylesheets/overview.styl
Reported in https://artsy.slack.com/archives/C03JWJLLH/p1503332879000518
Upon initial load in smaller viewport, some carousels on GPP have overlapping items. Once we resized the window, it's back to normal.
We can simply call `flickity.resize()` immediately after initialization but it's more expensive. It turned out the initial template rendering had wrong width for the overflowing items in a flexbox item, and that caused flickity to calculate wrong item width in it's initialization.
I can reproduce the CSS problem [here](https://jsfiddle.net/uks3rh8b/3/).
_I think_ the issue was that overflowing children in a `flex-basis: 100%` flexbox item have trouble calculating their width based on percentage, and we have to explicitly specify `width: 100%` on the flexbox item again to make it work.
> Fix wrong item width calc in GPP flickity carousels

- desktop/apps/article2/__tests__/routes.test.js
- desktop/apps/article2/routes.js
- desktop/apps/auction/routes.js
- desktop/apps/auctions2/routes.js
- desktop/apps/categories3/routes.js
- desktop/apps/react_example/components/App.js
- desktop/apps/react_example/routes.js
- desktop/components/main_layout/templates/react_index.jade
- package.json
- yarn.lock
Now that  [@artsy/stitch](https://github.com/artsy/stitch) has been published we can start swapping out Force sub-apps that use React:
> Update React apps with @artsy/stitch

- desktop/apps/categories3/components/App.js
- desktop/apps/categories3/components/Gene.js
- desktop/apps/categories3/components/GeneFamily.js
- desktop/apps/categories3/components/GeneFamilyNav.js
- desktop/apps/categories3/components/TAGPContent.js
- desktop/apps/categories3/components/TAGPIntro.js
- desktop/apps/categories3/components/__tests__/App.test.js
- desktop/apps/categories3/components/__tests__/Gene.test.js
- desktop/apps/categories3/components/__tests__/GeneFamilies.test.js
- desktop/apps/categories3/components/__tests__/GeneFamily.test.js
- desktop/apps/categories3/components/__tests__/GeneFamilyNav.test.js
- desktop/apps/categories3/components/__tests__/TAGPContent.test.js
- desktop/apps/categories3/components/__tests__/TAGPIntro.test.js
- desktop/apps/categories3/helpers/alphabetizeGenes.js
- desktop/apps/categories3/helpers/utils.js
- desktop/apps/categories3/routes.test.js
This introduces Styled Components to /categories3 in order to specify the broad responsive layout as well as the specific component styles.
Also adds tests coverage for the React components, with a mix of shallow and static rendering via Enzyme. (The tests are mostly for rendered markup structure, and had me missing Jest snapshots 😿 )
> @kanaabe => Add styles and tests to /categories3

- desktop/apps/categories3/components/App.js
- desktop/apps/categories3/components/FeaturedGene.js
- desktop/apps/categories3/components/FeaturedGenes.js
- desktop/apps/categories3/components/GeneFamilies.js
- desktop/apps/categories3/components/GeneFamily.js
- desktop/apps/categories3/components/TAGPContent.js
- desktop/apps/categories3/components/__tests__/App.test.js
- desktop/apps/categories3/components/__tests__/FeaturedGene.test.js
- desktop/apps/categories3/components/__tests__/FeaturedGenes.test.js
- desktop/apps/categories3/components/__tests__/GeneFamilies.test.js
- desktop/apps/categories3/components/__tests__/GeneFamily.test.js
- desktop/apps/categories3/components/__tests__/TAGPContent.test.js
- desktop/apps/categories3/helpers/alphabetizeGenes.js
- desktop/apps/categories3/queries/featuredGenes.js
- desktop/apps/categories3/routes.js
- desktop/apps/categories3/utils.js
This adds the the manually curated **featured genes** for each gene family, i.e. each row of image links in the screencap below:
This relies on the old-school manual curation method in Gravity:
- Each per-family group of featured genes is an `OrderedSet`
- Each featured gene — name + image + link — is a `FeaturedSet`
> Display featured genes in new categories app

- desktop/components/artwork_masonry/index.coffee
Fixes https://github.com/artsy/collector-experience/issues/509
Basically, artworks with missing images will now be excluded from masonry grouping, vs causing a crash currently. The code was already being defensive about missing dimensions, but we should just be defensive about missing images entirely.
> @mzikherman => Be defensive about missing images in masonry grid

- desktop/components/main_layout/footer/index.styl
Closes https://github.com/artsy/force/issues/1749
.screen-reader-text positioning was not acting as expected when inside a floated container, adding position relative kills the bug.
> @kanaabe => Overflow bug

- desktop/apps/artwork/components/auction_artworks/index.jade
- desktop/apps/artwork/components/auction_artworks/query.coffee
- desktop/apps/artwork/components/auction_artworks/test/index.coffee
Noticed this small bug yesterday-- we weren't respecting the entire method signature of the `upcomingLabel` helper method (which is kinda long and accepts timestamps and then a bunch of booleans), which meant that when a LAI sale was in _preview_ mode, the label on the artwork page said `... Auction open for live bidding` instead of `... Auction opens Aug 8, 12:00 PM EDT`.
This fixes up the method call and adds a test.
Note that it is this component on the artwork page that I'm referencing:
> @damassi => Fix label for live auctions in preview mode

- desktop/components/main_layout/stylesheets/embedded.styl
https://s3.amazonaws.com/artsy-webfonts/force-webfonts.css has also been updated and 
a CloudFront invalidation initiated.
> @kanaabe => Remove Webfont Reference

- desktop/apps/article2/queries/articleBody.js
Follow up for https://github.com/artsy/positron/pull/1269: uses 'FeatureHeader' instead of 'Fullscreen' in article queries.
> @kanaabe => Use FeatureHeader in queries

- desktop/apps/consign/client/actions.js
- desktop/apps/consign/client/reducers.js
- desktop/apps/consign/components/describe_work_desktop/index.js
- desktop/apps/consign/components/describe_work_mobile/index.js
- desktop/apps/consign/components/log_in/index.js
- desktop/apps/consign/components/log_in/index.styl
- desktop/apps/consign/components/sign_up/index.js
- desktop/apps/consign/components/sign_up/index.styl
- desktop/apps/consign/components/upload_photo/index.js
- desktop/apps/consign/test/reducers.js
This PR updates the log in and sign up flows for consignments to _always_ enable the button (as opposed to before when we would only enable the button if you had entered some values for the field). I think there may be some weirdness with redux-form where it doesn't always update the `invalid` and `pristine` values when someone adds something to the form, but it's a little hard to reproduce. We heard reports of users not being able to click the button even after filling in the form, so this should fix that (or make it easier to diagnose).
Note that the form still updates to indicate which fields are `Required` after you click submit, it's just the initial disabling that I'm taking out.
New forms:
> @damassi => [consignments] always enable log in/sign up buttons

- mobile/apps/auctions/routes.coffee
- mobile/apps/auctions/test/routes.coffee
We currently have more than 20 upcoming auctions and the most recent opening auctions are actually being cut off right now. This is a quick fix to the issue [reported in Slack](https://artsy.slack.com/archives/C0C4AJ1PF/p1505657067000028) this morning. @damassi is building a new auctions2 app that will make this code irrelevant going forward.
> @acjay: Updated size limit on mobile auctions fetch

- desktop/apps/auction/routes.js
- desktop/apps/consign/client/actions.js
- desktop/apps/consign/client/reducers.js
- desktop/apps/consign/client/validate.js
- desktop/apps/consign/components/describe_work_container/index.js
- desktop/apps/consign/components/describe_work_desktop/index.js
- desktop/apps/consign/components/describe_work_mobile/index.js
- desktop/apps/consign/routes.js
- desktop/apps/consign/stylesheets/index.styl
- desktop/apps/consign/test/reducers.js
This PR addresses: https://github.com/artsy/consignments/issues/78
We now want to require that users input a `Mobile Number` when they submit a consignment. Filling out that section of the form will send a request to the `/api/v1/me` endpoint to update the phone number on the user profile (so it will be changed artsy-wide, not just on a submission-basis). 
If the user already has a phone number entered on their profile, it will show up here but they have the option to change it.
This field is required in order to submit!
Mobile:
Desktop:
> @damassi => Require a phone number when a consignment is submitted

- desktop/components/article/stylesheets/content.styl
Another bug related to accessible text -- will be sure to take a close look at the previous changes and find more instances with width problems. This bug was raised here: https://artsy.slack.com/archives/C04GGGDCM/p1505920868000296
Adding a position and overflow declaration to the parent of a block including `.screen-reader-text` prevents it from overflowing the page width.  This PR adds this to social buttons in both sticky and footer placements.
> @kanaabe => Article overflow width bug

- desktop/config.coffee
Adds 'buying-with-artsy' to the TEAM_BLOGS config setting, re: [this thread](https://artsy.slack.com/archives/C04GGGDCM/p1506088874000385).
> @kanaabe => New team-blog name

- yarn.lock
Re: https://artsy.slack.com/archives/C03JWJLLH/p1503416445000079
On the mobile shows page, we are still using the static [places](https://github.com/artsy/places) lib for the list of cities. We still need to migrate to the Gravity generated city list but we might need some design changes on mobile. In the mean time, I'd like to do our partners a favor to [update places](https://github.com/artsy/places/pull/16) and include Koloa on that page. Please don't yell at me. 🙈
> Update places and include Koloa on the mobile shows page

- desktop/apps/collect/routes.coffee
- desktop/apps/galleries_institutions/routes.coffee
- desktop/apps/shows/routes.coffee
Per discussion in #1748 
Force gets some partner city related data from static json files that are generated nightly and posted to S3. These files were ostensibly being cached, but maybe they weren't so much — `ab` benchmarking of Force, running against a local Redis instance, with and without these `cache: true` options shows negligible difference. So a few less of these instances to clean up now.
> @craigspaeth => Remove unnecessary caching for static city files

- desktop/apps/artwork/components/related_artists/index.coffee
Fixes issue where missing related artworks error out:
https://www.artsy.net/artwork/ratnasambhava-the-buddha-of-the-southern-pure-land-tibet
> @craigspaeth => [Bugfix] Make related artworks fetch safer

- desktop/components/main_layout/stylesheets/body.styl
Changes the placement and size of .screen-reader-text to no longer render it offscreen, which led to bugs in width. 
Now text is rendered at 0px height and width, and placed in the top corner of the page.  This still passes Chrome's accessibility audit.
> @kanaabe => Width bugs

- desktop/models/artwork.coffee
- desktop/test/models/artwork.coffee
Along with https://github.com/artsy/metaphysics/pull/781, this updates the `sale_message` stuff to be consistent with being suppressed as an availability of `permanent collection`, and coming thru as `On loan` in that case. It also supports being suppressed using `availability_hidden` as well.
This _should_ support all these cases, and the existing logic for `price_hidden` will control the `Contact gallery` vs `Contact for price` display (ie- when `price_hidden: true`, the CTA is `Contact for price` and the price itself is hidden, although it _is_ considered in price-based filter results).
The remaining item is to more fully support the `On loan` case thru another partner association, or come to an agreement re: `collecting_institution`, or something else entirely.
Either way, I think …
> @starsirius => Update for new availability states

- desktop/components/main_layout/stylesheets/utilities.styl
fixes https://github.com/artsy/collector-experience/issues/594
According to [this blog post](1), Chrome incorrectly respects `max-width` for elements in a container with `table-cell`. The fix is to add `table-layout: fixed`, which is a hack but at least it works fine now.
[1]: https://www.carsonshold.com/2014/07/css-display-table-cell-child-width-bug-in-firefox-and-ie/
> Fixed a style bug in the auction artwork page in IE

- desktop/components/article/stylesheets/content.styl
- desktop/components/article/templates/mixins.jade
A few small changes for Edit2 launch in Writer:
- Blockquotes are styled in Classic layouts
- H1 is styled (to match H2) in Classic layouts
- Add a conditional to contributing_authors mixin (was throwing server errors)
Closes https://github.com/artsy/publishing/issues/75
Addresses points in https://github.com/artsy/publishing/issues/84
> @kanaabe => Blockquotes in classic + tweaks

- desktop/apps/categories3/__tests__/routes.test.js
- desktop/apps/categories3/__tests__/utils.test.js
- desktop/apps/categories3/components/GeneFamilyNav.js
- desktop/apps/categories3/queries/geneFamilies.js
- desktop/apps/categories3/routes.js
- desktop/apps/categories3/routes.test.js
- desktop/apps/categories3/utils.js
This follows on from https://github.com/artsy/metaphysics/pull/784, in which we updated the `GeneFamilies` schema's pagination to a Relay-style connection
The data fetching code here is updated accordingly. This seems like it might have benefitted from some Relay boilerplate to consume the connection-shaped data properly (I'm guessing — I haven't used Relay at all), but the requirements here are very simple and I think this will do the job.
The relevant diff is just [this commit](https://github.com/anandaroop/force/commit/76479463102f1218a5e3045d1f97b8f567c2c0b6), but I also used this PR to fix a small css issue and re-organize some test files.
> Update /categories3 to consume a graphql connection

- desktop/apps/galleries_institutions/routes.coffee
Closes #1800 
Gallery A-Z pages no longer show all partners due to endpoint limitations on how deep we can page.
Complaints about this have become more frequent this week, so this is an expedient fix that simply tweaks the page _size_ in order to get a complete list fetched again.  This is not a _great_ solution, but it will give us some time to figure out if that paging limitation is necessary or not.
> Fix galleries A-Z page

- desktop/apps/gene/templates/meta.jade
As discussed (https://github.com/artsy/collector-experience/issues/533), gene pages aren't rendering effectively for Googlebot. We should probably have Reflection pre-render these pages instead. The genes sitemap has already been added to Reflection, so those pages are now being crawled and pre-rendered.
**However** when I checked that Reflection was able to render the page, I noticed apparent problems reaching Metaphysics and the main API. Similar requests work fine from other pages, so I assume there's some low-level difference in how this page functions, or maybe another error interfering. This probably shouldn't be merged until that's addressed (though the pre-rendered pages are no worse than what Googlebot is already seeing):
Blocked on: https://github.com/artsy/reflection/issues/63 …
> Prompt Googlebot to request pre-rendered page content from Reflection

- desktop/apps/auction/actions/artworkBrowser.js
- desktop/apps/auction/reducers/artworkBrowser.js
- desktop/apps/auction/routes.js
- desktop/apps/gene/client.js
- desktop/apps/gene/routes.coffee
cc @joeyAghion 
Now that metaphysics passes the `requestID` to gravity for all requests in the new data loader format (hopefully this applies to all requests soon), we can start populating the server-side requests here to give us additional insight into what requests happen on a page load.
I realized another hole is reaction-- I'm hoping there's a way to get the request ID passed to metaphysics from there, but will probably need someone with relay knowledge to help me set that up. 😄
> @craigspaeth => add request id to server-side requests for gene page and auction page

- desktop/components/article/stylesheets/content.styl
- desktop/components/article/templates/index.jade
- desktop/components/article/test/templates.coffee
Follows up https://github.com/artsy/positron/pull/1348
Related to https://github.com/artsy/positron/issues/1296
Adds support for image_collection in hero_sections for 'classic' articles, adds tests for all varieties of hero_section
> @damassi => Support image_collection in hero_section

- desktop/apps/gene/client.js
- desktop/lib/global_client_setup.coffee
Reverts artsy/force#1849
This was returning an error in staging: ```Request header field X-Request-Id is not allowed by Access-Control-Allow-Headers in preflight response.``` for some requests.
> Revert "@craigspaeth => set request id header in global ajax settings for client-side backbone fetches"

- desktop/components/article/stylesheets/content.styl
In Article1, embeds had a layout over 'overflow', where all other containers use 'overflow_fillwidth'.  This adds 'overflow_fillwidth' to css for embeds, in advance of a backfill on embed layouts.
> @kanaabe => [Minor] Add 'overflow_fillwidth' support to embeds

- desktop/apps/artwork/routes.coffee
- desktop/apps/artwork/test/routes.coffee
- desktop/apps/clear_cache/index.coffee
- desktop/apps/clear_cache/test/index.coffee
- yarn.lock
This fixes a couple of sentry errors we keep seeing for errors that should be 400-level (i.e. not reported).
I believe what's happening in this case is that we weren't setting the `status` on the error object, so it got mistakenly [interpreted as a 500](https://github.com/artsy/force/blob/master/lib/middleware/error_handler.coffee#L12).
This updates those two places to correctly send 403 errors.
Should fix https://sentry.io/artsynet/force-production/issues/275370917/ and https://sentry.io/artsynet/force-production/issues/375324373/
> @craigspaeth => throw 400-level errors for real

- mobile/apps/artist/routes.coffee
- mobile/apps/artist/templates/header.jade
- mobile/apps/artist/test/templates.coffee
Fixes: https://sentry.io/artsynet/force-production/issues/345452571/events/8359706025/
There's a more general issue, which is that we're trying to re-use this header template for an `artist` object that could be a backbone model or a graphql response. Would be great to convert everything to metaphysics-backed data, but I didn't want to jump into that for this bug-fix. Also I've vaguely heard about plans to update the artist page? So hopefully this kind of refactor would be included in that as well.
> @mzikherman => be defensive about the artist biography page

- desktop/components/add_to_calendar/index.coffee
- desktop/components/add_to_calendar/index.styl
- desktop/components/add_to_calendar/react.js
An auctions team member reported that the [CMA Benefit Auction 2017](https://www.artsy.net/auction/cma-benefit-auction-2017) partner was complaining that its link was unclickable. I looked into it and saw that the calendar wrapper was invisible but blocking the link from being clickable. In addition the hover events were not revealing the calendar bits that belonged there. This is an initial, quick fix that seems to resolve it, but I'm not 💯 on whether this is the best way to go about it or whether it will affect other areas the widget might be used.
Before: Text/link not directly under mouse when they are below the widget, widget hover function not working
Now: Both are working
> Fix display issues with add to cal widget

- desktop/apps/marketing_signup_modals/index.coffee
I just noticed https://www.artsy.net/marketing-signup-modals is publicly accessible. It doesn’t look like it hosts any private information right now, but in the future we may add sensitive data to it.
> Only admins should be able to see marketing modal edit page

- desktop/apps/marketing_signup_modals/templates/index.jade
It took me a while to figure out what the query string key should be to trigger a marketing modal, so it would be nice if the admin page had an example link.
* Show slugs as a link
* Also added "Text Opacity" to the title header
> Add example url for marketing modal

- desktop/apps/miami_fair_week/index.js
- package.json
- yarn.lock
It seems like it is ok to show the default modal when the login button in the header is clicked, but we still need to show the specialized marketing modal for Miami Fair Week for every request. In order to make sure to always show the modal, the request without the `m-id` key will be redirected to the same path but with the `m-id=ca12` pair (`ca12` is already available both in staging and production). Not sure if there's a better way to achieve this but open to suggestions.
> Alwys display the marketing modal for the Miami Fair Week on /miami-fair-week

- desktop/assets/analytics.coffee
This wires up Reaction events to Force by hooking into [that event emitter](https://github.com/artsy/reaction/pull/323) Reaction exposes.
> Send Reaction events to Segment

- desktop/apps/auction/components/layout/active_bids/ActiveBidItem.js
A partner complained that they could not access a sale while logged in. On looking into it I noticed that we assume an active bid artwork to have an artist property. I was able to recreate the problem in staging and fix it by guarding for this on our new auction page. Verified in development.
> @damassi => guard for presence of artist on artwork in auction ActiveBidItem

- desktop/components/modalize/stylesheets/index.styl
On mobile, it's a bit hard to tap the "x" close button. using `padding` will expand the tappable area and make it easier to tap it.
> Make it easier to tap/click the modal close button

- desktop/apps/auction/routes.js
We weren't passing the `symbol` data into our initial store (as the price slider is rendered server-side). This should fix the bug where Veritas (and presumably other sales) don't show the correct currency for this slider.
> @damassi => include auction symbol for server-side rendering

- desktop/apps/article/__tests__/routes.test.js
- desktop/apps/article/queries/articleBody.js
- desktop/apps/article/routes.js
- desktop/apps/article/templates/__tests__/amp.test.js
- desktop/apps/partner/test/client/articles.coffee
- desktop/apps/partner2/test/client/articles.coffee
- desktop/models/article.coffee
- desktop/test/models/article.coffee
Fixes an issue in Parsely where editorial articles aren't being attributed to the 'Editorial' section
> @eessex => Update jsonLD attribution on article pages

- desktop/apps/fairs/helpers/view_helpers.coffee
1. Go to https://admin-fairs.artsy.net
2. Find an upcoming fair that has a `fair_profile` that doesn't have an `icon` (create a new fair if there isn't any)
3. Navigate to the Handle and Visibility page by clicking the PROFILE tab and the HANDLE AND VISIBILITY tab underneath
4. Mark the fair profile as published (here `hidden` could be either)
5. Save changes
6. Go to https://www.artsy.net/art-fairs and observe
The page displays the 500 error page.
1. On step 4, the admin should not be able to mark a fair profile as published if the profile is missing an `icon`. Or,
2. The `/art-fairs` (or any page that loads fair profiles) should just work (they should be aware of the fact that a `fair_profile` may not have an `icon`)
This PR implements the 2 as a temporary fix.
> Add a guard against fair profiles without icons

- desktop/apps/article/templates/amp_mixins.jade
Fixes an issue [noted by Devang today](https://artsy.slack.com/files/U06RJAKV0/F7VUYGG91/screenshot_20171107-011114.jpg) -- AMP pages were not updated with the new WEBFONT_URL var when added a month or so ago.  This lets them access the artsy-icons font for logo and share icons.
> @craigspaeth => Use webfont URL in amp pages

- desktop/apps/article/components/EditButton.js
- desktop/apps/article/components/__tests__/EditButton.test.js
Hold over from the article2 switch -- switch link to `/edit2` back to `/edit`
> @craigspaeth => Fix edit button route

- desktop/apps/artwork/components/commercial/templates/price.jade
- desktop/apps/artwork/components/commercial/test/template.coffee
Updates a few things:
- Removes price description/tooltip from `On loan` works, and display `Permanent collection`.
Note this depends on https://github.com/artsy/gravity/pull/11392 , being able to have the artwork-level availabilities set on one-edition set works. For now, I just did a `set` in the staging console.
> @oxaudo => Some tweaks to availability display on the artwork page

- lib/setup.js
- package.json
- yarn.lock
Bumps `@artsy/express-reloadable` with new [module-watching ability](https://github.com/artsy/express-reloadable/pull/3). 
**Note:** For now, when pulling changes in via reaction `yarn compile:server` is required. Will follow up with Reaction PR that introduces a new `watch` command that will stream changes over so that dev is as rapid as storybooks.
> @damassi => Bump express-reloadable 1.1.0; watch @artsy/reaction-force

- desktop/analytics/editorial_features.js
- desktop/apps/editorial_features/components/gucci/components/nav/__tests__/header.test.js
- desktop/apps/editorial_features/components/gucci/components/nav/fixed_header.jsx
- desktop/apps/editorial_features/components/gucci/components/nav/header.jsx
- desktop/apps/editorial_features/components/gucci/components/nav/sections_nav.jsx
- desktop/apps/editorial_features/components/gucci/components/section/section.jsx
- desktop/apps/editorial_features/components/gucci/components/section/section_text.jsx
- desktop/apps/editorial_features/components/gucci/components/section/section_video.jsx
- desktop/apps/editorial_features/components/gucci/components/series/series_header.jsx
- desktop/apps/editorial_features/components/gucci/templates/__tests__/head.test.js
- desktop/apps/editorial_features/components/gucci/templates/head.jade
- Change editorial to magazine
- Change font weight on large text to medium
- Center items in dropdown menu
- Animation in header now feels good on scroll, still a pause on hover
- Prefaces meta titles for /slug with series title 'Artists for Gender Equality: III. Future'
- Menu does not hide video on mobile /slug landing
- Added tracking event for partner links in 'about the series'
> @kanaabe => Gucci QA

- desktop/apps/article/queries/relatedArticles.js
This was[ added and merged on Friday](https://github.com/artsy/force/pull/1965), however it is no longer in master (not sure if something was reverted?  Can't tell why it disappeared).
> @kanaabe => Add published_at to related query

- desktop/apps/editorial_features/components/gucci/components/App.jsx
Removes the alternative text from the Gucci tracking pixel so we don't see "Advertisement" for some ad blockers.
> @dblock => Remove alt text from tracking pixel

- desktop/apps/article/templates/__tests__/amp.test.js
- desktop/apps/article/templates/amp_fonts.jade
- desktop/apps/article/templates/amp_mixins.jade
Addresses: https://waffle.io/artsy/publishing/cards/5a05eb92eddb2a00c9174583
This moves back to using fonts.com for Garamond + Avant Garde, and pulls in`artsy-icons` as a custom font. Unica isn't used in these pages yet but when we do, it should be added in the same way as `artsy-icons`.
This is due to Google AMP whitelisting only a few domains for `<link>`-style imports. All other domains (webfonts.artsy.net) must use their `@font-face` syntax. So many rules 🙄 . [Link](https://www.ampproject.org/docs/guides/responsive/custom_fonts)
> @eessex => Fixes Google AMP errors

- yarn.lock
Bumps the version in the lock file to 1.0.7 to include the /gender-equality route!
> @alloy => Upgrade artsy-eigen-web-association

- desktop/apps/article/templates/meta.jade
- desktop/components/main_layout/stylesheets/body.styl
- desktop/components/main_layout/stylesheets/index.styl
Addresses: https://waffle.io/artsy/publishing/cards/5a062bef5304860102841aa7
Problem is that iPhone is resizing text that it thinks is too small --
https://blog.55minutes.com/2012/04/iphone-text-resizing/. This change prevents the text from growing. It also sets the viewport scale and adjust for mobile (disable zoom)
Note that this change affects `main_layout/stylesheets/index.styl`.
> @eessex => Fixes caption re-sizing on mobile

- desktop/analytics/artwork.js
- desktop/apps/auction/components/layout/Banner.js
- desktop/apps/auction/components/layout/__tests__/Banner.test.js
Spec is cases 12 + 13 of https://github.com/artsy/auctions/issues/644
This PR tracks clicks into live auctions on prediction from the artwork and auction pages. On the artwork page I used our standard method of adding handlers and did not add tests (couldn't find any others).
On the Auction page I took a different approach, implementing the tracking code as an `<a onClick={handler}` - this allowed me to quickly test the behavior in the `Button` component (maybe more complicated than the actual implementation though) *and* efficiently chop the domain portion of the url off of the link.
Spreading it around might be a bad approach anyways- we could just keep it all in one place. If folks have thoughts I'd be glad to reconsider. Thanks.
> Track clicks to enter live auction from auction + artwork page

- mobile/apps/fair_organizer/templates/fair.jade
This fixes 500 errors occurring on e.g. `/design-miami` on mobile devices, reported on Slack and also by Slack. fixes https://sentry.io/artsynet/force-production/issues/346741707/
> Fix 500 errors in fair organizers page

- desktop/analytics/artwork.js
- desktop/apps/auction/components/layout/Banner.js
This corrects an oversight in my previous PR on this analytics issue (#1992). I noticed that we were tracking the urls in segment (force-staging) with an extra leading slash . This removes it.
Currently tracked in staging:
```
analytics.track('click', {
context_module: 'auction banner',
destination_path: '//click-analytics/login',    <<<<<<<<<<<<<
flow: 'auctions',
label: 'enter live auction',
type: 'button'
});
```
> @sweir => fix double leading slash on analytics

- desktop/apps/artwork/components/commercial/query.coffee
- desktop/apps/artwork/components/commercial/templates/editions.jade
Currently on staging: 
With using the new field in https://github.com/artsy/metaphysics/pull/825
Closes https://github.com/artsy/collector-experience/issues/341
> @oxaudo => Update edition set display on artwork page for availabilities

- desktop/apps/home/routes.coffee
- desktop/apps/home/templates/featured_articles.jade
- desktop/apps/home/templates/featured_links.jade
- desktop/apps/home/templates/featured_shows.jade
- desktop/apps/home/test/routes.coffee
Uses Q's `allSettled` instead of `all` which allows us to more manually handle the states (fullfilled/rejected) of the promises instead of going straight to the `catch` block on errors.
Addresses https://github.com/artsy/force/issues/986
> @joeyAghion => Make home more resilient

- scripts/start.sh
Seen too many people get snagged on this one because the stack trace is incomprehensible when the server crashes. This adds a simple red warning if trying to start the server without an .env file.
> Warn against missing .env file

- desktop/apps/article/queries/articleBody.js
- desktop/apps/article/templates/classic_meta.jade
- desktop/apps/article/templates/meta.jade
- desktop/apps/editorial_features/components/eoy/templates/head.jade
Follows up on https://github.com/artsy/positron/pull/1477
Removes instances of article email metadata fields 'credit_line' and 'credit_url'
> @craigspaeth => Deprecate credit_line and credit_url

- desktop/apps/articles/stylesheets/articles.styl
A tiny thing that has bothered me for too long to have gotten to it just now. The magazine page ends up touching the edges of your browser on smaller desktop screens. This adds our standard side margin so it lines up with the search bar/logomark.
_after > before_
> [Minor] Fix margin on magazine page

- desktop/apps/dev/index.coffee
Requested by Mark, to verify artsy.net as our domain for Facebook
Addresses: https://github.com/artsy/publishing/issues/272
Steps for domain verification noted here: https://business.facebook.com/settings/owned-domains/2223608780998302?business_id=10153596186848407
> @craigspaeth => Adds a page for facebook domain verification

- desktop/apps/article/queries/articleBody.js
- desktop/apps/article/queries/relatedArticles.js
Adds some additional fields to the relatedArticle query to show media duration, publish date, and publish status. 
Resolves first issue in https://github.com/artsy/publishing/issues/280
> @kanaabe => Show media publish status & meta

- desktop/apps/article/__tests__/routes.test.js
- desktop/apps/article/routes.js
- package.json
- yarn.lock
If we detect a video article (currently the only one with media), then we should 404 if the media blob is not published. This ensures that the content is not reachable, even though the article itself is published. 
Also bumps reaction to the latest!
> @eessex => Bump reaction and next on unpublished media

- desktop/apps/static/index.coffee
Changes /future-of-art to /the-future-of-art. We need this change to make /future-of-art available as a Vanity url for this article: https://www.artsy.net/article/artsy-editors-future-art
> Adds new url for old future-of-art page

- desktop/models/artwork.coffee
Artwork bricks that use Metaphysics already had this fixed when we worked on the feature, and I updated a `saleMessage` method already, this seems to be a fallback the partner profile page uses /shrug
So, let's update this as well!
I've made the Gravity PR as well: https://github.com/artsy/gravity/pull/11479 , which _should_ make this redundant, but no harm in being defensive.
> @starsirius => Extra guard for hidden availabilities

- desktop/apps/artwork/components/clock/test/view.coffee
- desktop/apps/artwork/components/clock/view.coffee
- desktop/apps/partnerships/templates/auction_sections.jade
Fixes #1923, at long last.
Debugging the stubbing of reload and time to work properly was a real headache, and sent me chasing many red herrings. I believe it was importing the view dynamically, so that it would capture the stubbed globals, that finally solved the issues.
> fix ClockView reload loop

- lib/setup.js
With the last upgrade I updated the path incorrectly.
> [Toolchain] Fix path express-reloadable

- desktop/apps/article/components/App.js
- desktop/apps/article/components/EditButton.js
- desktop/apps/article/components/__tests__/App.test.js
- desktop/components/main_layout/templates/react_index.jade
Instead of changing the z-index of the EditButton to fix https://waffle.io/artsy/publishing/cards/5a4e5174c390ea0063e90860, this seemed like a good candidate to try out Portals!
Here is the button in question now visible above a Fullscreen header
> @eessex => Convert EditButton to portal to "fix zindex"

- desktop/apps/artwork/components/partner_stub/index.jade
- mobile/apps/artwork/components/meta_data/templates/index.jade
- mobile/apps/artwork/components/meta_data/templates/inquiry.jade
- mobile/apps/artwork/components/meta_data/templates/price.jade
- mobile/apps/artwork/components/meta_data/test/template.coffee
Fixes https://github.com/artsy/auctions/issues/680
This PR addresses an issue we noticed around enabling "Buy Now" on sale artworks that exist in a more general context. Currently this feature is supported _if within an auction_ but on closer inspection all that was needed was to remove the guard and instead rely on a generic `is_aquireable` flag which is returned from the request. 
Additionally, fixes an issue related to an erroneous `hr` tag in an uncommon code-path. Since there's already a top border this is unneeded: 
**Bad**
**Good**
> @sweir27 => Enable E-Commerce-like "Buy Now" on Mobile 

- desktop/analytics/main_layout.js
- desktop/apps/artwork/client/index.coffee
- desktop/apps/artwork/components/artists/helpers.coffee
- desktop/apps/artwork/components/artists/index.jade
- desktop/apps/artwork/components/artists/templates/biography.jade
- desktop/apps/artwork/components/artists/test/templates/index.coffee
- desktop/apps/artwork/components/meta/index.jade
- desktop/apps/artwork/routes.coffee
- desktop/assets/artists_artworks.coffee
- desktop/components/split_test/running_tests.coffee
~**Not for merge yet, until we're satisfied with the QA and want to release it**~
This updates the logic, which showed this for logged-in admins, to a proper AB split test, with `experiment` (seeing market insights), and `control`.
You can force a specific branch (which I did to test the tracking), via `?split_test[artist_market_data]=experiment/control` query param.
> @yuki24 => Enable AB test for market insights on artwork pages

- desktop/apps/collect/client.coffee
- desktop/apps/collect/templates/index.jade
- desktop/components/commercial_filter/filters/keyword/index.jade
- desktop/components/commercial_filter/filters/keyword/keyword_filter_view.coffee
- desktop/components/commercial_filter/stylesheets/index.styl
- desktop/components/commercial_filter/views/pillbox/index.jade
- desktop/components/commercial_filter/views/pillbox/index.styl
- desktop/components/commercial_filter/views/pillbox/pillbox_view.coffee
I thought this was admin-only, but it's actually based on an AB test. Same difference tho!
With lab:
Without lab (unchanged):
This basically gets it looking like the comp, but keeps it under lab feature.
Still to do:
- sorting. Since sorting doesn't work, I wasn't sure how we should disable/indicate that the functionality isn't supported when you have a keyword search. (cc @briansw )
- analytics. Setting up the actual AB test experiment is very straightforward, but we also should be storing all keyword searches, possible via Segment? or something else.
> @cavvia => Adjust keyword search on /collect to match comps for AB test

- desktop/components/commercial_filter/models/params.coffee
We weren't able to reproduce the other issues reported (namely, certain types of links from Sailthru weren't working/being respected). So, this fix might be the only thing needed to allow CRM team to link to /collect page filters.
This updates our client-side URL/history handling (which operates on a strict whitelist based on the available filter params), to also allow marketing UTM params (any param that begins with `utm`).
> @cavvia => Whitelist UTM marketing params for /collect

- desktop/components/artwork_metadata_stub/templates/didactics.jade
- desktop/components/artwork_metadata_stub/test/index.js
Closes https://github.com/artsy/force/issues/2017
One of the artworks returned (published), lacks a partner. Here's that artwork: www.artsy.net/artwork/mike-pratt-sleeping-moon  (this page and associated Metaphysics query has several issues with it, I'm taking a look at those).
In the meantime, this just makes the template used in the artist page filter a bit more defensive.
> @joeyAghion => Be defensive about missing partner in filter results on artist page

- desktop/analytics/article_impressions.js
- desktop/analytics/articles.js
- desktop/analytics/impressions.js
- desktop/components/split_test/split_test.coffee
- mobile/analytics/impressions.js
We no longer have a subscription to Mixpanel and do not send any events to it, so we no longer have to specifically not send experiment
> @kanaabe  => Remove unnecessary reference to Mixpanel

- desktop/apps/article/components/__tests__/Article.test.js
- desktop/apps/article/components/layouts/Article.js
- desktop/apps/article/routes.js
- desktop/components/cta_bar/view.coffee
- desktop/components/email/client/editorial_signup.coffee
- desktop/components/email/test/editorial_signup.coffee
- desktop/components/split_test/running_tests.coffee
- mobile/components/cta_bar/test/view.coffee
- mobile/components/cta_bar/view.coffee
Sets up an AB test for Editorial vs Full User signups.
TODO: 
~- [ ] Copy update~
~- [ ] Sync with email team on post-signup~
Covers:
> @xtina-starr => Editorial user signup AB modal test

- desktop/apps/personalize/client/onboarding.js
- desktop/apps/personalize/components/App.js
- desktop/apps/personalize/index.coffee
- desktop/apps/personalize/onboarding.jade
- desktop/apps/personalize/routes.coffee
- desktop/apps/personalize/routes.js
- desktop/apps/personalize/template.jade
- desktop/assets/misc.coffee
- desktop/assets/misc.styl
- desktop/assets/personalize.coffee
- desktop/assets/personalize.styl
- desktop/components/main_layout/header/view.coffee
- desktop/components/split_test/running_tests.coffee
- package.json
- yarn.lock
This PR pulls in the onboarding react root component via server-side rendering using stitch `renderLayout`. It has the initial setup for the A/B test but isn't yet fulling implemented yet. We will also probably have to refactor the tests but are PR'in early to get some eyes on this.
Paired with @xtina-starr on this!
Shows SSR on initial load, then rehydrates after JS is loaded. The SSR doesn't need to fetch any data since the first screen is hardcoded values so subsequent steps are always client-side. 
Check out the test with: `/onboarding?split_test[onboarding_test]=experiment`
> @alloy => Onboarding admin only

- desktop/apps/collect/client.coffee
- desktop/components/commercial_filter/filters/category/category_filter_view.coffee
- desktop/components/commercial_filter/filters/category/index.jade
- desktop/components/commercial_filter/filters/color/color_filter_view.coffee
- desktop/components/commercial_filter/filters/location/index.jade
- desktop/components/commercial_filter/filters/location/location.jade
- desktop/components/commercial_filter/filters/location/location_filter_view.coffee
- desktop/components/commercial_filter/filters/medium/index.jade
- desktop/components/commercial_filter/filters/medium/medium_filter_view.coffee
- desktop/components/commercial_filter/filters/period/index.jade
- desktop/components/commercial_filter/filters/period/period.jade
- desktop/components/commercial_filter/filters/period/period_filter_view.coffee
- desktop/components/commercial_filter/models/params.coffee
- desktop/components/commercial_filter/test/models/params.coffee
In a bid to improve performance on our `/collect` page, this drops medium, period, color, and partner location aggregations from the query. The UX impacts are as follows:
* No period or location counts will display.
* No disabling of period, location, medium or color filters when there are no results available under that filter. All these filters are always enabled. 
This change should only affect the `/collect` page. The hypothesis is that aggregations slow down the query significantly, particularly when multiple filters are set, combined with the assumption that there is almost always content on `/collect` under these filters, as we are filtering on our entire catalogue of for-sale content. I additionally assume the counts, as they are often very large numbers, are not meaningful to …
> @mzikherman: KSO-8 reduce filter aggregation overhead on collect

- desktop/components/commercial_filter/models/filter.coffee
Fixes a UI issue which occurs when you narrow down to zero results on `/collect`, either via keyword search or using our standard filters. The artwork grid view does not refresh in these cases, resulting in the 'no results' message appearing above stale results:
This resets the grid view (to empty) when there are no results.
> @mzikherman: reset the artwork grid view when there are no results

- desktop/components/split_test/running_tests.coffee
finishes https://artsyproduct.atlassian.net/browse/AR-68 that is part of https://artsyproduct.atlassian.net/browse/AR-5
We can't take advantage of the admin guard middleware since we are running an A/B test for users who are initially not logged in but attempt to sign up at some point in the experiment. In order to avoid exposing the new flow by accident, we should redirect any user to the existing flow, and admins should use the `?split_test[onboarding_test]=experiment` query string to force-switch to the experiment.
Also, I'm going to remove the admin guard as part of https://artsyproduct.atlassian.net/browse/AR-62 so @katarinabatina can QA as a guest user.
> All users should be redirected to the existing personalize flow after signup

- desktop/apps/personalize/index.coffee
- desktop/apps/personalize/routes.js
- desktop/assets/onboarding.coffee
- desktop/assets/personalize.coffee
- desktop/components/split_test/running_tests.coffee
- lib/middleware/locals.coffee
Christina and I have experimented with single-route onboarding A/B test to see how we could go about actually running the test.
@xtina-starr and I have confirmed that we would be able to run the A/B test with the two flows not affecting each other. However, we need to be careful about rolling this out since the user needs to be logged out in the first place and signs up at some point in the A/B test. This means we can't take advantage of the admin guard middleware. The other thing we could do is that admins should use the query string key `?split_test[onboarding_test]=experiment` for QA, but it'd also allow any user to enter the query string if it's known.
This PR is mergeable as it is, but let's discuss how we go about actually launching it.
> Put the existing and new onboarding flows into a single route for running an A/B test

- desktop/apps/auction/components/artwork_browser/PromotedSaleArtworks.js
- desktop/apps/auction/components/artwork_browser/__tests__/PromotedSaleArtworks.test.js
- desktop/apps/auction/components/artwork_browser/main/artwork/GridArtwork.js
- desktop/apps/auction/components/artwork_browser/main/artwork/ListArtwork.js
- desktop/apps/auction/components/artwork_browser/main/artwork/MasonryArtwork.js
- desktop/apps/auction/components/artwork_browser/main/artwork/MasonryArtwork.styl
- desktop/apps/auction/components/artwork_browser/main/artwork/__tests__/GridArtwork.test.js
- desktop/apps/auction/components/artwork_browser/main/artwork/__tests__/ListArtwork.test.js
- desktop/apps/auction/components/artwork_browser/main/artwork/__tests__/MasonryArtwork.test.js
- desktop/apps/auction/components/layout/Banner.js
- desktop/apps/auction/components/layout/auction_info/AuctionInfo.styl
- desktop/apps/auction/queries/filter.js
- desktop/components/clock/view.coffee
- desktop/components/react/masonry_grid/Reveal.js
**Fixes https://artsyproduct.atlassian.net/projects/BNS/issues/BNS-10 (Arrow not identical to artwork/id arrows)**
(Note that we're using Reaction's new `<Icon />` component so the font weight isn't 100%, but bolded it is very close)
**Fixes: https://artsyproduct.atlassian.net/projects/BNS/issues/BNS-7 (Missing price labels)**
**Fixes: https://artsyproduct.atlassian.net/projects/BNS/issues/BNS-6 (remove mention of bidding in timer)**:
**Fixes: https://github.com/artsy/auctions/issues/819 (Auction info full-screen popup did not have `position: fixed`**
Also, hides Buy Now rail if the sale is closed.
> @sweir27 => Buy Now bugfixes

- lib/middleware/locals.coffee
- test/lib/middleware/locals.coffee
I wasn't able to repro the exact offending UA string, but we _were_ directly inserting it into the DOM, so I believe the exploit.
So, we can just `escape` that. The way we currently use the UA in the DOM is thru CSS selectors like `html[data-useragent*="iPad"]`, which should remain unaffected by escaping. There's also some uses of it with code like `USER_AGENT.match('iphone')`, which should also remain unaffected.
> @joeyAghion => Escape user agent string to avoid XSS when inserted into DOM

- desktop/apps/auction/components/Layout.js
- desktop/apps/auction/components/__tests__/Layout.test.js
- desktop/apps/auction/reducers/app.js
- desktop/apps/auction/routes.js
Fixes 500 error that occurs when a user is logged in and attempts to visit an [ecommerce sale](https://staging.artsy.net/auction/chris-ecommerce-sale). This was due to a `me { ... }` query querying for lot standings, but e-commerce sales aren't auctions and don't contain any biddable artworks and is thus return 404.
> @sweir27 => [Auction] Fix e-commerce-sale auth issue

- desktop/components/contact/default_message.coffee
- desktop/components/contact/test/default_message.coffee
Hi force friends, it's been such a long time!!! 👋 
Per @madeleineb on #AS-7, use the sold message for on-loan works too.
> Use sold message for on loan works too

- desktop/apps/artist/client/views/overview.coffee
- desktop/apps/auction/components/layout/Banner.js
- desktop/apps/auction/components/layout/__tests__/Banner.test.js
- desktop/apps/auction/components/layout/auction_info/AuctionInfo.styl
- desktop/apps/auction/components/layout/auction_info/AuctionInfoDesktop.js
- desktop/apps/auction/components/layout/auction_info/AuctionInfoMobile.js
- desktop/apps/auction/components/layout/auction_info/__tests__/AuctionInfoDesktop.test.js
- desktop/apps/auction/components/layout/auction_info/__tests__/AuctionInfoMobile.test.js
- desktop/components/clock/react.js
- desktop/components/clock/view.coffee
- desktop/models/sale.coffee
Addresses a few more things caught in QA desktop / mobile:
- On mobile, the info window pop up needed a swapped 'Sale' title; hidden `Auctions FAQ` button; hidden time if empty or invalid
- Hidden auction time if missing / invalid
- Hidden clock if no end_at: 
- Toggle Clock text on closed
> @sweir27 => [Auction] Hide / swap fields if sale

- desktop/analytics/account_creation.js
An order_id field is required by one of our vendors.
> @xtina-starr  => Add `order_id` field to created account tracks

- desktop/apps/sitemaps/index.coffee
- desktop/apps/sitemaps/routes.coffee
- desktop/apps/sitemaps/test/routes.coffee
Adds the collect sitemap to our `robots.txt`.
The collect sitemap is now on S3:
http://artsy-sitemaps.s3-website-us-east-1.amazonaws.com/sitemap-collect.xml
For some reason, http://www.artsy.net/sitemap-collect.xml is not proxying correctly... I need to work out why. This also depends on our update for dynamic page titles, so we should wait before merging it in.
> KSO-10: add collect sitemap to robots.txt #donotmerge

- lib/middleware/proxy_to_reflection.coffee
- test/lib/middleware/proxy_to_reflection.coffee
When S3 operates as a web server, it ignores querystring parameters as you'd expect. However, S3 supports characters like `?` and `&` in object paths, so Reflection has no problem crawling sitemapped URLs with querystrings and storing the resulting HTML files at the correspondingly-named locations. It's just important that the intermediate app server escape the desired querystring parameters into the proxied path.
I.e., a googlebot request for `.../collect?gene_id=geometric-abstraction&_escaped_fragment_=` must be proxied to `.../collect%3Fgene_id%3Dgeometric-abstraction`.
This was [encountered](https://github.com/artsy/reflection/pull/25) a long time ago, it's [documented](https://github.com/artsy/reflection#proxy-configuration) and was even implemented in Force …
> @mzikherman: Once again support querystrings in Reflection proxying

- package.json
- yarn.lock
`0.19.1` includes UI fixes for the onboarding components: https://github.com/artsy/reaction/pull/508, https://github.com/artsy/reaction/pull/509
> Upgrade to latest reaction

- desktop/apps/the_armory_show/components/ArmoryShowFairWeekPage.js
- desktop/apps/the_armory_show/fixture.json
- desktop/apps/the_armory_show/index.js
- desktop/apps/the_armory_show/templates/meta.jade
- desktop/index.js
Once this is merged and deployed to staging it'll be available on https://staging.artsy.net/the-armory-show-fair-week, but this path is subject to change as it's a path we picked out and would like someone on the marketing team to provide a more SEO-friendly path.
> @kana: setup the armory show fair marketing page

- .vscode/tasks.json
This PR adds a vscode task script to launch the `yarn mocha -- --watch testFile.js` command on whatever file (hopefully a test) is currently active in the editor. It can be launched with `command + shift + B` or whatever task launching flow you prefer.
> add mocha watch task

- desktop/apps/armory_week/components/ArmoryWeekPage.js
- desktop/apps/armory_week/components/Cta.js
This current sticky footer is non-functional but has the styling that make it responsive.
> @kanaabe: Adds a sticky, non-functional CTA footer

- lib/global_modules.js
- package.json
- yarn.lock
Looks like babel-preset-env was only picking up latest IE Edge releases, and not IE 11 [("last two versions")](https://github.com/artsy/force/blob/master/.babelrc#L5) and so IE 11 was throwing on common ES6 features: 
This should make things safer for _all_ older browsers, but at some point we should make a call as this adds quite a lot of code to the overall JS that needs to be downloaded. I haven't seen any sentry errors come through so I have to 👏 MS for being rigorous / insistent with their OS update process.
> @kanaabe => Add babel-polyfill

- desktop/apps/armory_week/client/initializer.js
- desktop/apps/armory_week/components/ArmoryWeekPage.js
- desktop/apps/armory_week/components/Cta.js
- desktop/apps/armory_week/index.js
- desktop/assets/cta.js
- desktop/assets/cta.styl
This adds a sticky CTA view with an overlay modal:
Right now all the contents in the CTA view are static and hard-coded, but [we have a story for making them editable](https://artsyproduct.atlassian.net/browse/AR-113). There are also other related stories to make the page fully functional and we'll address them incrementally:
* [Change the `<FacebookButton>` to accept arbitrary button text](https://artsyproduct.atlassian.net/browse/AR-109)
* [User should be able to sign up through the modal](https://artsyproduct.atlassian.net/browse/AR-112)
* [User shouldn't be able to scroll when the overlay modal is open](https://artsyproduct.atlassian.net/browse/AR-112)
> Add overlay content to the sticky CTA

- desktop/apps/personalize/index.coffee
- mobile/apps/personalize/index.coffee
- mobile/apps/personalize/routes.coffee
- mobile/apps/personalize/routes.js
- mobile/apps/personalize/test/routes.coffee
This turned out to be pretty straightforward. When the user gets to a /personalize route on mobile and they have `res.locals.sd.ONBOARDING_TEST === 'experiment'`, we use `next()` to fall through our route handlers to desktop.
> @yuki24 => [Onboarding] Support mobile

- desktop/apps/armory_week/client/initializer.js
- desktop/apps/armory_week/components/ArmoryWeekPage.js
- desktop/apps/armory_week/components/Cta.js
- desktop/apps/armory_week/fixture.json
This PR finishes the subtasks below:
* [AR-114: User shouldn't be able to scroll when the overlay modal is open
](https://artsyproduct.atlassian.net/browse/AR-114)
* [AR-113: Admin should be able to edit the banner pop up contents](https://artsyproduct.atlassian.net/browse/AR-113)
* [AR-95: Fix Mobile Margins](https://artsyproduct.atlassian.net/browse/AR-95)
* [AR-109: Change the `<FacebookButton>` to accept arbitrary button text](https://artsyproduct.atlassian.net/browse/AR-109)
> [Armory Week] Many UI fixes for the Armory Week landing page

- webpack.config.js
This should fix the multiple react copies when running `yarn link` issue.
> @yuki24 => [Toolchain] Force react resolution

- desktop/apps/partner/client/artists.coffee
- desktop/apps/partner/client/artists_list.coffee
- desktop/apps/partner/client/overview.coffee
- desktop/apps/partner/test/client/artists_list.coffee
- desktop/apps/partner2/client/artists.coffee
- desktop/apps/partner2/components/artists_list/test/view.coffee
- desktop/apps/partner2/components/artists_list/view.coffee
- mobile/apps/partner_profile/templates/artists.jade
- mobile/apps/partner_profile/test/templates.coffee
There seem to be dozens of possible partner profile configurations, and we have 3 completely separate code paths responsible for rendering them (`desktop/apps/partner`, `.../partner2`, and `mobile/apps/partner_profile`).
@saolsen and I tried to make the sensible additions in each place to support [STI-6](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=31&projectKey=STI&modal=detail&selectedIssue=STI-6), but this looked slightly different in each location.
The end result is:
* by default, profiles are unchanged from their current appearance
* partners may opt not to display representations on their profiles, in which case artists they represent or don't will appear in a single undifferentiated list
> @saolsen: Allow partners to disable listing represented artists on their profile

- scripts/acceptance.sh
This fixes the build failure occurring on CircleCI.
Increasing the timeout seems inappropriate, but there's something weird going on in Mocha - The `-t 30000` should configure Mocha so that it'd wait up to 30s for each test, but even with `-t 60000` the `Artwork` test still finishes in around 5.6s, which doesn't explain why it was failing on CircleCI. What this means is that Mocha may be interpreting the `--timeout 30000` option as 3s or there may be something else we aren't aware of yet.
Either way, given the conversation on slack, the direction is probably to incorporate https://www.cypress.io/ at some point, so this should be fine for the time being.
> Fix CircleCI builds by increasing the mocha timeout

- desktop/apps/personalize/client/onboarding.js
- desktop/apps/personalize/components/App.js
- desktop/apps/personalize/components/RoutesWithProgressBar.js
finishes https://artsyproduct.atlassian.net/browse/AR-110
This PR replaces the <Wizard> component with [`react-router`](https://github.com/ReactTraining/react-router). In the `<Wizard>` component we have a lot of our own hacks to update the page URL. `react-router` provides a simpler way to define routes and also takes care of many edge cases we aren't aware of yet (cross-browser support, SSR, browser back/forward, etc). Instead of maintaining our own wrapper for the History API, we should take advantage of what's already out there.
> Fix the browser back/forward by replacing <Wizard> with react-router

- desktop/apps/armory_week/components/ArmoryWeekPage.js
- desktop/apps/armory_week/index.js
This PR removes the adminOnly flag and addresses [AR-128](https://artsyproduct.atlassian.net/browse/AR-128). The signup already does not display when a user is logged in. This removes the sticky footer when a user is logged in.
> @yuki24: removes adminOnly flag and hides stickyFooter for logged in users.

- circle.yml
We've run into inconvenient delays a few times because Force's `master` build immediately pushes to the `staging` branch after each successful build and deploy. This starts _another_ build of the same git SHA which occupies 4 Circle containers for ~10 minutes.
I thought we could instead whitelist the `master` and `release` branches. If you like being able to build every branch, I could change this to a blacklist of just the `staging` branch, since that's the main problem.
> @orta: Avoid re-building staging branch after master build

- desktop/apps/home/client/auth_router.coffee
- desktop/apps/home/welcome.coffee
Addresses [AR-137](https://artsyproduct.atlassian.net/browse/AR-137). This adds a `redirect-to` in the query param and pulls that off in the `signup` method to use that as the redirect url after account creation.
> Ensure signup for home banner triggers onboarding after acct creation

- package.json
- yarn.lock
minor
cc @erikdstock Tested locally, referer is being saved on staging during email/password as well as social auth for signups.
> @mzikherman => Bump artsy passport to save referer during social auth as well

- desktop/apps/show/routes.coffee
- desktop/apps/show/templates/header.jade
- desktop/apps/show/templates/metadata/location.jade
https://github.com/artsy/metaphysics/pull/927
Make sure ☝️ is merged first.
https://artsyproduct.atlassian.net/browse/STI-34
We need to show proper `Online Exclusive` label  for shows without location.
Make sure `location.jade` is always included and in there check for newly added `is_online_exculsive` flag that was added to MP in https://github.com/artsy/metaphysics/pull/927 and based on that show `Online Exclusive` or the actual location.
> [STI-34] Show Online Exclusive label on show page

- circle.yml
...since the latter appears to skip PRs.
Back in https://github.com/artsy/force/pull/2180, I white-listed the `master` and `release` branches because we were wasting Circle container time on rebuilding the `staging` branch immediately after each `master` build. [This Circle discussion](https://discuss.circleci.com/t/build-only-pull-request-to-a-specific-branch/903/2) says "any pull requests affecting those branches will trigger as well," but we observed that PRs no longer get built. Maybe the docs weren't referring to PRs from forks?
> @yuki24: Black-list staging instead of white-listing master/release

- src/desktop/components/featured_shows/metadata/location_with_dates.jade
- src/desktop/models/partner_show.coffee
- src/desktop/test/models/partner_show.coffee
We are now offering _online exclusive_ shows which are shows without any location. We need to update show component (brick?) to properly set the location to `Online Exclusive`.
Had to update `PartnerShow` model to include `isOnlineExclusive` method and in `location_with_dates.jade` using it to show proper title.
Do we have i18n support in force?
cc: @nicoleyeo 
For `show/<id>` page looks like we are using MP for getting the data, will have a separate PR for that one which would be dependent to https://github.com/artsy/metaphysics/pull/927
> [STI-33] Support online-exclusive shows

- package.json
- yarn.lock
cc @erikdstock this fixes the case you found earlier where getting to the login/signup with facebook always redirects you to `/personalize`, even with the custom redirect (the big page) set.
> @mzikherman => Bump artsy passport for redirect fix after social signup for bidding

- src/desktop/apps/artist/client/views/related_artists.coffee
- src/desktop/apps/artist/components/rail/index.coffee
- src/desktop/apps/artwork/components/related_artists/index.coffee
- src/desktop/apps/editorial_features/components/venice_2017/client/index.coffee
- src/desktop/apps/fair/components/browse/router.coffee
- src/desktop/apps/fairs/client/index.coffee
- src/desktop/apps/home/components/artists_to_follow/view.coffee
- src/desktop/apps/show/components/follow_artists/index.coffee
- src/desktop/apps/show/components/follow_profile/index.coffee
- src/desktop/apps/user/components/categories/view.coffee
- src/desktop/components/article/client/image_set.coffee
- src/desktop/components/article/client/view.coffee
- src/desktop/components/auth_modal/view.coffee
- src/desktop/components/eoy_artist_list/index.coffee
- src/desktop/components/follow_button/view.coffee
- src/desktop/components/main_layout/header/view.coffee
This adds client-side follows in the same pattern as artwork saves. I tested a bunch of different ones (artist/genes on the home page, fairs, etc.) and all seems to work locally!
The follow button-initiated sign up flow does correctly take you to onboarding (due to that `register` vs `signup` redirect fix the other day), so this removes the `destination` which was the server-side follow routes (which weren't fully implemented) in favor of the client-side follow.
So now, at least for follows, you always go thru onboarding and wind up where you started (and are following the thing).
> @erikdstock => Add ability to follow an entity after sign up

- .vscode/tasks.json
- src/desktop/apps/auction/components/DOM.js
- src/desktop/apps/home/client/hero_unit_view.coffee
- src/desktop/components/artwork_item/save_controls/view.coffee
- src/desktop/components/artwork_save/view.coffee
- src/desktop/components/auth_modal/view.coffee
- src/desktop/components/follow_button/view.coffee
- src/desktop/components/main_layout/header/view.coffee
- src/desktop/components/save_button/view.coffee
This adds intent tracking to the auth modal creation points listed below. There are a few more tricky cases, but most of the work here was finding and checking each case was called correctly. The possible `signupIntent`s are:
```
follow artist
follow profile
follow gene
save artwork
bid
register to bid
sign up
```
These have been added to:
- /artists --> Follow artist
- Artist list view - Follow artist
- Artist view - Follow artist
- Artist view - Related artists - Follow artist
- Artwork view - Follow artist
- Artwork view - Related artists - Follow artist
- Artwork view - Related works - Save work
- Artwork view - Save work
- Auction Sale - Register to bid
- Category view - Follow artist
- Category view - follow gene
- Fair booth view - Follow artist
- Fair booth view - follow profile
- …
> @mzikherman => Save intent for most contexts

- src/desktop/apps/shows/index.coffee
- src/desktop/apps/shows/routes.coffee
- src/desktop/apps/shows/templates/featured_shows.jade
- src/desktop/apps/shows/templates/location_based.jade
- src/desktop/apps/shows/templates/nav.jade
- src/desktop/apps/shows/test/routes.coffee
- src/desktop/apps/shows/test/templates.coffee
https://artsyproduct.atlassian.net/browse/STI-32
We want to add a new `Online Exclusive` tab to shows page which shows similar section as city based tabs except it only shows `Online Exclusive` shows.
Added new `online` route to shows routes which basically makes same call as city based tab except instead of passing `near` it passes `has_location` and set it to `false`.
Also renamed `city.jade` to `location_based.jade` for clarity.
Depends on coming gravity PR where we start support  `has_location` for finding shows.
https://github.com/artsy/gravity/pull/11583
> [STI-32] Add new Online Exclusive tab

- src/desktop/apps/about/client/view.coffee
- src/desktop/apps/fairs/client/index.coffee
- src/desktop/components/artist_page_cta/templates/register.jade
- src/desktop/components/artist_page_cta/view.coffee
- src/desktop/components/commercial_filter/filters/followed_artists/followed_artist_filter_view.coffee
- src/desktop/components/marketing_signup_modal/index.coffee
cc @katarinabatina @mzikherman @anipetrov 
This PR adds signup intent tracking to several CTAs throughout force. I paired with @xtina-starr on this.
_updated- per ani's requests [below]_
```
- fairs list: 'sign up to follow fairs'
- artist page cta from full page sign up modal: 'landing full page modal'
- fair popup modal (marekting_signup_modal): 'marketing modal'
- /collect sign up button cta: 'artists you follow filter'
- about sign up button: 'sign up to save works'
```
> @xtina-starr => add signupIntent to more auth points

- src/desktop/apps/home/templates/hero_unit.jade
- src/desktop/apps/home/test/templates.coffee
We noticed that the hero images on the home page are not loaded through Gemini. These images are fairly large (2000px by 672px, multi-MB) and take a lot of bandwidth. By loading these images through Gemini's resizing endpoint (with the default quality of `80`) we would be able to reduce approximately 75% of the file size.
cc @sweir27
> Load hero images through Gemini to reduce file size

- src/desktop/apps/about/templates/sections/hero_unit.jade
- src/desktop/apps/armory_week/fixture.json
- src/desktop/apps/artsy_in_miami/fixture.json
- src/desktop/apps/artwork/components/related_artists/test/artists_fixture.coffee
- src/desktop/apps/auction/__tests__/fixtures/auction.js
- src/desktop/apps/auction/components/artwork_browser/__tests__/fixtures/followedArtistSaleArtworks.js
- src/desktop/apps/partnerships/templates/hero_unit.jade
- src/desktop/components/article_figure/mixin.jade
- src/desktop/components/article_figure/parsely_figure.jade
- src/desktop/components/articles_grid/templates/figure.jade
- src/desktop/components/auction_reminders/test/view.coffee
- src/desktop/components/resizer/config.coffee
- src/desktop/components/resizer/test/index.coffee
- src/mobile/components/article_figure/index.jade
- src/mobile/components/article_figure/template.jade
- src/mobile/components/resizer/config.coffee
- src/mobile/components/resizer/test/index.coffee
- src/test/acceptance/fixtures/metaphysics/artwork.json
- src/test/acceptance/fixtures/metaphysics/bidding1.json
- src/test/acceptance/fixtures/metaphysics/bidding3.json
- src/test/acceptance/fixtures/metaphysics/bidding4.json
This PR changes the image quality of gemini-generated images as it is [suggested by Google](https://developers.google.com/web/tools/lighthouse/audits/optimize-images):
>  To pass the audit, set the compression level of each image to 85 or lower.
This may sound scary, but if you compare two images generated with `quality=95` or `quality=80` side-by-side, you would not be able to see any differences (there is an on-going Slack conversation [here](https://artsy.slack.com/archives/C02BC3HEJ/p1519765865000758) and [there](https://artsy.slack.com/archives/C02BGC5PW/p1519767409000029)).
This would dramatically reduce the file size of an image. In the example below, the size of the image with `quality=95` is 1MB while the other one with `quality=80` is 479KB. Let us know if this is an acceptable …
> Set the JPEG image quality to 80

- src/mobile/apps/artwork/components/related_artworks/queries/index.coffee
We noticed that on the artworks view in mobile web, we were requesting images of all sizes to display in the columns below the main artwork view:
We only need `tall` images (max) for these small views, so this PR updates the metaphysics query that requests the artwork image to explicitly fetch the `tall` version. (Otherwise it just seems to grab the latest image version in the list, which is anything from `large` to `tall` and mostly, `normalized` 😱 .
With this update, we're fetching much less data. (the largest image used to be 4.7 MB for an image that was way down in the related section, vs. 87.4 KB after the change).
> @mzikherman => explicitly request tall images for artwork columns on artwork page

- src/desktop/apps/show/components/artwork_item_metaphysics/save_controls/view.coffee
Good catch!
Basically this was crashing since we were trying to set the initial saved state of artworks on the page, which crashes when you're logged out (clearly they're all unsaved in that case).
> @anandaroop => Show fix re: save controls

- src/mobile/apps/home/routes.coffee
- src/mobile/apps/home/templates/page.jade
- src/mobile/apps/home/test/templates.coffee
This change is similar to #2227 but for mobile.
In addition to reducing the quality (default is now `80`), we found that in some cases even though the hero image that was uploaded is cropped correctly for mobile web, it might still be very large. This should fix that as well.
> Resize hero images on mobile

- src/desktop/components/main_layout/header/view.coffee
This address [AR-290](https://artsyproduct.atlassian.net/browse/AR-290). Sometime '/personalize/' can exist as a redirect parameter in the URL. This causes the flash message to display at unexpected times. This ensures we check for personalize in the pathname and disregard the any query string parameters.
> Display personalize flash 'thank you' message after completion of onboarding

- src/desktop/apps/home/templates/hero_unit.jade
- src/desktop/apps/home/test/templates.coffee
https://github.com/artsy/force/pull/2227 accidentally broke the "welcome" hero image, which is not loaded through metaphysics (but points to image/data directly in force). 
This PR fixes that to check for the hero unit's `mode`. When loaded through metaphysics, the `mode` will be one of `'LEFT_DARK'`, `'LEFT_LIGHT'`... (all options here: https://github.com/artsy/metaphysics/blob/master/src/schema/home/home_page_hero_units.js#L22-L39), so escaping on `'WELCOME'` seems sufficient.
cc @yuki24
> @mzikherman => don't resize the "welcome" hero unit

- src/desktop/apps/artist/client/router.coffee
- src/desktop/apps/artist/client/views/overview.coffee
- src/desktop/apps/artist/routes.coffee
- src/desktop/apps/artist/templates/index.jade
- src/desktop/apps/artist/templates/sections/overview.jade
- src/desktop/apps/artist/test/templates.coffee
- src/desktop/components/split_test/running_tests.coffee
- src/desktop/components/split_test/split_test.coffee
- src/desktop/components/split_test/test/split_test.coffee
Continuation of https://github.com/artsy/force/pull/2239
This includes a check to ensure reflection don't index one of the experimental variants. 
Here's the analytics call made for this feature when the artist page loads. @anipetrov Is there anything else we'd like to log or track for this test?
```javascript
analytics.track('Experiment Viewed', {
experiment_id: 'artist_page_variants',
experiment_name: 'artist_page_variants',
nonInteraction: 1,
variation_id: 'no_info_header', // accepted values are 'control', 'no_info', 'no_header', 'no_info_header'
variation_name: 'no_info_header'
});
```
Raw event from segment
```javascript
{
"anonymousId": "d4613e2b-4351-4b44-a0f0-5f3efb32a6a0",
"context": {
"library": {
"name": "analytics.js",
"version": "3.3.0"
},
"page": {
"path": …
```
> [Artist] ensures reflection doesn't index test variants

- src/desktop/components/buyers_premium/index.coffee
- src/desktop/components/buyers_premium/test/index.coffee
Fixes the issue below. Basically, floating point math can lead to weird rounding. I figured we'll probably never need more that 2 places after the decimal point.
> fix floating point rendering on buyer's premium

- src/lib/metaphysics.coffee
Sort of performance-related...
We use `metaphysics.debug` as a way to view a page's server-side metaphysics query in graphiql by adding `?query=true` to the end of a force url.
I noticed that when I did this on an artist page, I caused force-staging to run out of memory (and confirmed that locally as well). 😱 
Turns out that the `send` variable here can _also_ include `req` (even though it is also expected to be passed in). This was the case for the artist /index route, which meant that `qs.stringify get` was actually trying to serialize the entire `req` object (along with the query and variables) and stick it into a URL.
This fixes that by explicitly _only_ serializing `query` and `variables` before redirecting to metaphysics.
> @mzikherman => don't serialize entire req object when redirecting to graphiql

- src/desktop/apps/collect/client.coffee
- src/desktop/apps/collect/routes.coffee
- src/desktop/components/commercial_filter/models/params.coffee
- src/desktop/components/commercial_filter/test/models/params.coffee
- src/desktop/components/commercial_filter/views/sort/sort_map.coffee
- src/desktop/components/split_test/running_tests.coffee
This puts a merchandisability A/B test live on `/collect` with two groups. The experiment group gets `-decayed_merch` sort instead of the default `-partner_updated_at`. The merch sort combines our merchandisability scores with freshness and an auction boost.
The merch sort is presented as `Recently Added` in the sort dropdown - @briansw if you have any preferences for language let me know. There is a strong freshness component so I think this language works better than `Relevance` which might raise more questions.
This shouldn't be merged until:
* ~~Gravity is deployed with the latest merch query.~~ DONE
* @wrgoldstein has reviewed and is happy to run this test. One thing to note is that auction lots are boosted in the new sort, so using inquiries as a performance metric won't capture …
> merchandisability sort ab test

- src/desktop/components/main_layout/templates/scripts.jade
Fixes critical bug where https://github.com/artsy/reflection (and PhantomJS) was erroring out when indexing new pages
> [SEO] fixes rendering error for phantomJS

- src/desktop/components/main_layout/templates/scripts.jade
- src/desktop/lib/global_client_setup.coffee
- webpack.config.js
Now we're getting creative.... Takes a typical jquery import and exports it as an entrypoint, which is then referenced later as the import, circumventing the multiple jquery instance issue (possibly)
> [SEO Bugfix] Export jQuery as an entrypoint, use that as reference 

- src/desktop/apps/artist/client/views/overview.coffee
- src/desktop/apps/artist/queries/overview.coffee
- src/desktop/components/artist_page_cta/templates/overlay.jade
- src/desktop/components/artist_page_cta/test/template.coffee
Tiny optimization here-- we actually make three separate calls to the `related/artists` endpoint (client-side) on the overview artist page. This PR removes one of those by no longer fetching the `cta_artists` if the user is logged in, since in that case I believe [this variable](https://github.com/artsy/force/blob/master/src/desktop/apps/artist/routes.coffee#L49) will always be false.
> @mzikherman => Only fetch cta_artists if the user is not logged in

- src/desktop/apps/auction_support/templates/bid-form.jade
- src/desktop/apps/auction_support/templates/registration.jade
- src/desktop/apps/editorial_features/components/venice_2017/templates/index.jade
- src/desktop/apps/order/templates/checkout.jade
- src/desktop/apps/user/templates/layout.jade
- src/desktop/components/main_layout/templates/blank.jade
- src/desktop/components/main_layout/templates/index.jade
- src/desktop/components/main_layout/templates/minimal_header.jade
- src/desktop/components/main_layout/templates/scripts.jade
This PR updates the header templates to not load stripe scripts by default. We only have 3 pages that need it, but are loading it everywhere, which adds up extra page load time. Instead, we should opt-in only when necessary rather than loading it on every page.
> Do not load stripe script anywhere and opt-in when needed

- src/desktop/analytics/main_layout.js
- src/desktop/config.coffee
- src/lib/setup_sharify.js
- src/mobile/analytics/before_ready.js
- src/mobile/analytics/global.js
- src/mobile/config.coffee
This PR adds tracking for pageload time (cc @wrgoldstein @yuki24)
The main change is the addition of the `TRACK_PAGELOAD_PATHS` env var, plus the code to actually track the fields we care about _only_ on the pages we are interested in. (we configure the pages that will send this data to avoid overloading segment/costing us too much $$$)
There are also lots of changes due to `prettier` being run on these files for the first time.
> @mzikherman => adds tracking for pageload time

- src/mobile/apps/artwork/components/related_artworks/display_related_works.coffee
- src/mobile/apps/artwork/components/related_artworks/index.coffee
- src/mobile/apps/artwork/components/related_artworks/queries/auction_query.coffee
- src/mobile/apps/artwork/components/related_artworks/queries/fair_query.coffee
- src/mobile/apps/artwork/components/related_artworks/queries/show_query.coffee
- src/mobile/apps/artwork/components/related_artworks/template.jade
- src/mobile/apps/artwork/components/related_artworks/test/display_related_works.coffee
- src/mobile/apps/artwork/components/related_artworks/test/index.coffee
Related to [this discussion](https://github.com/artsy/metaphysics/pull/947#discussion_r171028196) on your previous metaphysics PR, this updates the cases on the mobile web artwork page where we are fetching _all_ artworks for a sale/partner show/fair booth to render underneath the artwork.
This updates to follow the pattern set by the `Related works`, `Artist works` and `Partner works` sections to only fetch 20 works and include a link to the relevant sale/partner show if applicable.
i.e.
cc @nicoleyeo
> @mzikherman => no longer fetch all artworks in auctions or fair booths

- src/desktop/components/commercial_filter/filters/category/category_filter_view.coffee
- src/desktop/components/commercial_filter/filters/category/index.jade
We noticed that since the a/b test ended on the collect page (and we're now always showing the gene tiles), the performance of the page took a little dip.
The gene tiles themselves are pretty large:
This updates the code to send the images through gemini's resizer, which both reduces the size and the quality... meaning we download much less data! 👏
> @mzikherman  => resize gene tiles on collect page

- src/mobile/apps/artwork/components/image/index.styl
To actually get display like that on mobile:
> properly style attribution_class on mobile

- src/desktop/components/main_layout/templates/scripts.jade
This script was written by our consultant and served from their CDN. It's is not compressed (70KB) and HTTP/2 is not enabled for
their CloudFront endpoint. By compressing and moving this script to our CDN we'll be able to speed up the page load a bit faster (smaller file, HTTP/2 connection).
I initially thought about checking this file in to git so it'll be synced across different S3 buckets automatically, but Webpack doens't like globally scoped Javascript:
So I just manually uploaded this file to S3:
* https://s3.amazonaws.com/artsy-force-production/assets/conversionpath-0.3.8.min.js
* https://s3.amazonaws.com/artsy-force-production/assets/conversionpath-0.3.8.min.js.gz
* https://s3.amazonaws.com/artsy-force-staging/assets/conversionpath-0.3.8.min.js
* …
> Move the marketo script to our CDN

- src/desktop/apps/personalize/index.coffee
addresses https://artsyproduct.atlassian.net/browse/GROWTH-367
Currently the redirection from `/personalize` to `/personalize/interests` is handled by [the `<Wizard>` component](https://github.com/artsy/reaction/blob/57547f1572226b973cf31bb21a5d8769bfe8bb29/src/Components/Onboarding/Wizard.tsx#L106-L110), but this design also allowed other Javascript to be running while the component is being mounted. The server-side redirection ensures the consistency of the path sent to Segment since it happens before the browser evaluates Javascript code.
> Redirect to user from /personalize to /personalize/interests server-side

- src/desktop/components/stylus_lib/index.styl
This groundbreaking change addresses https://artsyproduct.atlassian.net/browse/BUY-142
Seems very safe to do because the only other place this variable is used is when changing the background of nav items which is what we desire as well.
The only caveat I noticed that in this small view I don't seem to see any buttons to logIn/logOut. Only the user name and account are shown for logged in user. It is how the current view behaves but we are expanding it to bigger size.
> switch to mobile header at 767px

- package.json
- src/desktop/apps/article/components/__tests__/Article.test.js
- yarn.lock
Bumps Reaction to include new content-end strategy.
Shallow tests are to avoid looking for `document` in the Text component, should be fine here since we are only checking to see that children are rendered.
> @kanaabe => Bump reaction

- src/desktop/components/auth_modal/templates/_gdpr_signup.jade
- yarn.lock
This just fixes the redirect-to query string by adding the `=`.
> fixes redirect-to query string

- src/desktop/components/hover_pulldown/index.styl
- src/desktop/components/main_layout/footer/upper.jade
- src/desktop/components/main_layout/header/index.styl
- src/desktop/components/main_layout/header/templates/large_screen_header.jade
- src/desktop/components/main_layout/header/templates/more.jade
https://artsyproduct.atlassian.net/browse/BUY-141
https://artsyproduct.atlassian.net/browse/BUY-143
https://artsyproduct.atlassian.net/browse/BUY-151
https://artsyproduct.atlassian.net/browse/BUY-154
- Re-orders top nav menu items visually
- Re-prioritizes top nav menu items "snapping" into **More** menu
- Removes most items from **More**
- Adds Blog to footer links 
- Updates TAGP footer link to go to /categories
> Re-organize main nav on desktop

- src/mobile/models/search_result.coffee
- src/mobile/test/models/search_result.coffee
We discovered that in mobile web, search results were always linking to `/<fair-id>` when the route actually expects a `/<profile-id>`. This works in most cases because the fair slug tends to match the profile slug, but in cases where it doesn't (i.e. aipad fairs), trying to click a result from mobile web search shows a 404 page.
This fixes that and also a likely similar regression related to `page` (which we saw in desktop).
As a side note, I think the search_result models can probably get merged at this point (but this is for an urgent issue so didn't go down that path).
> @saolsen => search result href should include profile_id not fair_id for fairs in mobile web

- src/desktop/apps/article/queries/relatedArticles.js
Last step for [GROW-426](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-426)
Adds `in_editorial_feed` arg to `relatedArticlesCanvas` query on `/news` articles
> @damassi => Use in_editorial_feed in news relatedArticlesCanvas query

- package.json
- src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
- src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.test.js
- yarn.lock
For date headers and infinite scroll, adds `getDateField` method, which returns `scheduled_publish_at` if no `published_at`, and today if no date saved.
Fixes bug of date headers breaking on unpublished articles.
> @erikdstock => [Newsfeed QA] Infinite scroll handles articles without published_at 

- src/desktop/components/marketing_signup_modal/index.coffee
While @anipetrov was QA'ing analytics, she pointed out that the `experiment_viewed` was firing on every page. After looking into this I believe this is happening because of the MarketingSignupModal which gets instantiated globally in the [main_layout client](https://github.com/artsy/force/blob/master/src/desktop/components/main_layout/client.coffee). My proposed fix is to return unless there is a slug present which prevents `splitTest('gdpr_compliance_test').view()` from being executed. The assumption here is that if there is no slug we shouldn't instantiate the marketing modal. @l2succes I know you've also worked in this area so I thought you might be the one to help confirm my assumption.
> @l2succes: do not initialize marketing modal if there is no slug

- src/desktop/components/artist_page_cta/index.styl
- src/desktop/components/inquiry_questionnaire/stylesheets/desktop.styl
Fix to: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=39&projectKey=EV&view=planning&selectedIssue=EV-28
I think what happens here is that when the style was added there it mistakingly had 4 spaces indentation instead of 2. And for some reason stylus completely ignored nesting in this case.
Very strange...
> fixing error when gdpr style leaks into other pages

- src/desktop/analytics/account_creation.js
We never changed the css selector so we lost the 'Created Account' event. This restores that by passing the proper selector.
> @kanaabe: restores Created Account analytics event by passing proper selector.

- src/desktop/apps/artwork/templates/index.jade
Fixes https://artsyproduct.atlassian.net/browse/BUY-157, which hides the top "explore auction" bar for e-commerce sale artworks.
**Ecommerce sale**
**Typical Sale**
> @yuki24 => Hide top banner for ecommerce sales

- src/desktop/components/auth_modal/templates/_gdpr_signup.jade
Small tweak to make the copy consistent for opting into receiving emails on the gdpr form.
> @kanaabe: make variations of the checkbox copy consistent

- src/mobile/components/artwork_columns/view.coffee
As reported here: https://artsy.slack.com/archives/C02BAQ5K7/p1522956614000692
Looks like a subtle race condition on init.
> @mzikherman => [Bugfix] Mobile image scroller in /show/:id

- src/desktop/apps/auth/client/index.coffee
- src/desktop/apps/auth/routes.coffee
- src/desktop/apps/auth/templates/reset_password.jade
- src/desktop/apps/auth/test/routes.coffee
- src/desktop/apps/home/client/auth_router.coffee
- src/desktop/apps/home/routes.coffee
- src/desktop/components/auth_modal/templates/forgot.jade
- src/desktop/components/auth_modal/view.coffee
- src/desktop/models/logged_out_user.coffee
- src/desktop/test/models/logged_out_user.coffee
This PR is for this ticket: https://artsyproduct.atlassian.net/browse/SELL-92, which is some fallout from work done to improve security on waves. What I'm trying to do here is modify the forgot password flow so that it's suitable for fair partners that have not yet set their password. The current changes in this PR all pretty much all cosmetic, but you gotta start somewhere!
What I've done is add some additional info from the url so that I can conditionally show and hide content on the forgot password modal and reset password page. I've stopped here to ensure I'm on the right track. The next steps would be:
* take a look at the page after /forgot to ensure the copy lines up
* change the email sent to include the redirect_to param
* take a look at the page after /reset_password to ensure …
> Set password

- src/desktop/apps/collect/client.coffee
- src/desktop/components/commercial_filter/models/params.coffee
- src/desktop/components/split_test/running_tests.coffee
This closes out the merchandisability test on `/collect` in favour of the experiment, as per the recommendation from analytics. It was found to bump our conversion to artwork pageviews by around 5.5%.
> close out merch test

- scripts/acceptance.sh
- src/test/acceptance/partner_profile.js
Follow up on regression https://github.com/artsy/force/pull/2325#discussion_r179345651.
We actually have some acceptance tests for the GPP, but they are for mobile cases, which is not affected by the change. This PR re-structures the tests and adds a simple test to cover the desktop case. It should help overall coverage.
If we sorted the app mounting order (e.g. revert https://github.com/artsy/force/commit/b4af6d93412832c1245f1dfe7f9128ce8573f610), this new test will reproduce the 404 error we saw in staging.
> Add acceptance tests for desktop Gallery Profile Pages

- package.json
- src/desktop/apps/article/components/App.js
- src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
- src/desktop/apps/article/components/NewsArticle.tsx
- src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.test.js
- src/desktop/apps/article/components/__tests__/NewsArticle.test.js
- yarn.lock
Separates out NewsArticle into a subcomponent to better handle scrolling and url handling. The main change is that waypoint handling is no longer tied to the main app and each article is now responsible for its own changes. We make use of [waypoints with children](https://github.com/brigade/react-waypoint#children) to handle the top and bottom of the article. 
Addresses
https://artsyproduct.atlassian.net/browse/GROW-444
https://artsyproduct.atlassian.net/browse/GROW-177
> @eessex => Refactor Newsfeed scrolling

- src/mobile/apps/fair_organizer/routes.coffee
- src/mobile/apps/fair_organizer/templates/index.jade
- src/mobile/collections/fairs.coffee
- yarn.lock
Fixes issue where fair dates are occasionally displayed incorrectly on mobile but not on desktop. The root issue is a comparator on the mobile fairs collection that sorts fairs based on banner image size, overriding any other sort order passed to `/fairs`. Incidentally fixes a related issue where fairs in the "Previous Fairs" tab on mobile might show in a jumbled order.
- Removes comparator in mobile fairs collection that sorts 
- Explicitly sorts fairs in chronological order based on `start_at`
- Formats fair dates using `formatDates` instead of `subtitle`
- Includes update to `yarn.lock` setting CoffeeScript version
> Remove comparator on mobile fair collections

- src/desktop/analytics/inquiry_questionnaire.js
- src/desktop/apps/inquiry/client/routes/inquiry.coffee
- src/desktop/components/contact/confirm_inquiry.coffee
- src/desktop/components/contact/index.styl
- src/desktop/components/contact/templates/inquiry_form_confirm.jade
- src/desktop/components/contact/templates/inquiry_show_form.jade
- src/desktop/components/contact/view.coffee
- src/desktop/components/inquiry_questionnaire/index.coffee
- src/desktop/components/inquiry_questionnaire/stylesheets/desktop.styl
- src/desktop/components/inquiry_questionnaire/templates/account/login.jade
- src/desktop/components/inquiry_questionnaire/templates/account/register.jade
- src/desktop/components/inquiry_questionnaire/templates/affiliated.jade
- src/desktop/components/inquiry_questionnaire/templates/artists_in_collection.jade
- src/desktop/components/inquiry_questionnaire/templates/basic_info.jade
- src/desktop/components/inquiry_questionnaire/templates/commercial_interest.jade
- src/desktop/components/inquiry_questionnaire/templates/how_can_we_help.jade
- src/desktop/components/inquiry_questionnaire/templates/inquiry.jade
- src/desktop/components/inquiry_questionnaire/templates/institutional_affiliations.jade
- src/desktop/components/inquiry_questionnaire/templates/partials/nevermind.jade
- src/desktop/components/inquiry_questionnaire/templates/specialist.jade
- src/desktop/components/inquiry_questionnaire/templates/test_specialist.jade
- src/desktop/components/inquiry_questionnaire/test/index.coffee
- src/desktop/components/inquiry_questionnaire/test/views/basic_info.coffee
- src/desktop/components/inquiry_questionnaire/views/step.coffee
This code change adds 'x' button to all inquiry dialogs. And also removes 'nevermind' links from all of those dialogs since this link is now redundant.
This ended up being substantially more code kill than I anticipated. It's a bit tricky now to track who actually worked on all of those files originally since the history only includes move to `src` directory. Would appreciate if maybe @xtina-starr or maybe @damassi can take a look here and flag any potential problems they could see with all this code removals.
> [WIP] - allow inquiry_questionnaire modals to be closed via x button, click outside or escape

- src/desktop/apps/articles/index.js
- src/desktop/apps/auctions2/index.js
- src/desktop/apps/order2/index.tsx
- src/desktop/apps/order2/routes.tsx
- src/desktop/apps/react_example/index.js
- src/desktop/components/auction_reminders/blacklist.coffee
- src/desktop/lib/admin_only.coffee
- src/desktop/lib/admin_only.js
This PR addresses https://artsyproduct.atlassian.net/browse/PURCHASE-52 and https://artsyproduct.atlassian.net/browse/PURCHASE-20
- Adds `/order` and `/order2` to the auction_reminders blacklist
- Adds the `adminOnly` flag to the `/order2` page for easier QA in production 
One thing I noticed with this (it's also the case for the `onboarding` app, and potentially others) is that when you supply an `assetPackage` to be rendered in the main_layout, it automatically tries to pull in the corresponding `js` and `css` file. If we're not planning to have css files for the apps that basically just point to reaction, maybe we should create a new base template that only tries to pull in js.
> @damassi => Minor updates to order2

- src/desktop/apps/search/collections/global_search_results.coffee
- src/desktop/apps/search/routes.coffee
- src/desktop/apps/search/test/collections/global_search_results.coffee
This front-end hack for moving exact matches to the top of the list is causing partner shows named simply after an artist to rank above artist results with exact matches. eg searching for 'Donald Judd' on the site:
There is no longer any need to hack the rankings as we should let Elasticsearch deal with ranking results - it knows how to weight between entities. After the change, the results show correctly:
This issue was affecting many artists - any that had a `PartnerShow` named after them.
cc @katarinabatina
> fix search ranking hack which is causing buggy results

- src/desktop/apps/home/client/index.coffee
- src/desktop/apps/home/queries/initial.coffee
- src/desktop/apps/home/routes.coffee
- src/desktop/apps/home/stylesheets/index.styl
- src/desktop/apps/home/templates/index.jade
- src/desktop/apps/home/test/routes.coffee
- src/desktop/components/main_layout/header/index.styl
- src/desktop/components/main_layout/header/templates/large_screen_header.jade
- src/desktop/components/main_layout/header/view.coffee
- src/desktop/components/main_layout/templates/index.jade
This starts off our series of PR's with the first plumbing sorta one: hiding hero units and featured links (and not even fetching them), if the lab feature is enabled.
> @sarahscott => Hide hero units and featured section if 'Homepage Search' lab feature enabled

- src/desktop/apps/home/routes.coffee
- src/desktop/apps/home/test/routes.coffee
Hides followed_artists module; this could be further optimized by not even including `FOLLOWED_ARTISTS` in the initial metaphysics query, but I think that might be more trouble than it's worth since that initial query is quite small and the real images/data are fetched later.
> @mzikherman =>  Hide followed artists module 

- src/desktop/components/main_layout/header/templates/more.jade
Per @katarinabatina request we need to add back `Artsy for Galleries` link into top nav menu. Here it is!
> adding back Artsy for galleries link to navigation menu

- src/desktop/apps/consign/templates/faq.jade
- src/desktop/apps/consign/templates/landing.jade
We'd rather these be sent to `consign@` (`consignments@` used to be a google group but it is currently unreachable, and this is the preferred address anyways).
> @bhoggard => consignments@ --> consign@

- src/desktop/apps/react_example/components/my_jade_view.jade
- src/desktop/index.js
- src/desktop/lib/global_client_setup.coffee
- src/desktop/lib/middleware/renderArtworkBrick.js
Next step in block odyssey is Isomorphic Rendering to ensure full interactivity between reaction components and Force. Here's the flow: 
1. When a new request is made, append a new `reactionBlocks` array to `sharify`
1. Create a `new ReactionRenderer(mode = 'server')` instance and attach it as a helper to locals under `reaction`
1. Within server-side templates, when a block render is requested from jade  (`reaction.artworkGrid(props)`), serialize the `ReactionRenderer` instance and push it into `reactionBlocks` array
1. On client mount, iterate over all serialized reaction blocks and create a `new ReactionRender(mode = 'client')` instance and then run `deserialize()` which will `ReactDOM.rehydrate` all locations where reaction blocks have been mounted server-side
- Rewrite in TypeScript …
> @mzikherman => [ArtworkBrick] Implement isomorphic reaction block rendering

- package.json
- yarn.lock
Upgrade to [3.0 release](https://github.com/styled-components/styled-components/releases/tag/v3.0.1)
Matched in [Reaction](https://github.com/artsy/reaction/pull/643) so that `yarn link` doesn't complain.
Noticed rendering issues related to 3.x upgrades a few months back (`/article` pages wouldn't load) but whatever it was seems to have been fixed. Tested out all around and AOK. This gives us access to the new streaming API.
> [Lib] Bump styled-components 3.2.6

- src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
- src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.test.js
Debounces the date update and more significantly, fixes a bug where `hasNewDate` was updating no matter what since we were comparing published_at instead of the actual date.
> @eessex => Smooth scrolling /news

- src/desktop/apps/artwork/client/index.coffee
- src/desktop/apps/artwork/components/artist_artworks/index.jade
- src/desktop/apps/artwork/components/auction_artworks/index.jade
- src/desktop/apps/react_example/components/App.js
- src/desktop/apps/react_example/components/clientSideJadeView.jade
- src/desktop/apps/react_example/components/myJadeView.jade
- src/desktop/apps/react_example/routes.js
- src/desktop/index.js
- src/desktop/lib/global_client_setup.coffee
- src/desktop/lib/reactionRenderer.js
- src/lib/middleware/error_handler.coffee
Last piece: For templates that are exclusively rendered client-side we need a way to to mount at runtime. The flow:
- `ReactionRenderer` now has three modes, `server`, `client` and `runtime`
- Runtime represents post-mount `client`, when JS is already executing 
- Runtime mode has two additional requirements: 1) an `#id` to mount to, since that markup isn't available during the server-side render pass; and 2) the `reaction` renderer, which is attached globally to sharify, needs to be passed to the template being rendered client-side since there's no way to inject global helpers into client-side template code. 
Here's an example of a runtime-only page area (artwork in an auction, the "Other auction works" section); this gets mounted once the client is already ready: 
- Convert to …
> @mzikherman => [ReactionRenderer] Add runtime mode

- package.json
- src/desktop/assets/analytics.coffee
- yarn.lock
This brings back the tracking call for "Clicked read more" to be able to track a pageview, but it returns early so we don't make an event call in Segment. This is the preferred functionality for #analytics
> @xtina-starr => Return early for a Segment call and bump reaction

- src/desktop/apps/order/stylesheets/index.styl
Took me a while to figure out how to hide the nav bar _only_ when this view is embedded in the ipad, but I found this handy guide from @craigspaeth in this old PR. 😄 https://github.com/artsy/microgravity-deprecated/pull/41
The nav bar is [already hidden on the phone](https://github.com/artsy/force/blob/master/src/desktop/apps/order/stylesheets/mobile.styl#L66-L67), so I think it's okay to just use `Artsy-Mobile` here. This adds a little optimization to both cases by bumping the padding back since the header is gone in both (and there was a bunch of extra space).
> @kanaabe => hide nav for embedded ipad view

- src/desktop/apps/home/queries/initial.coffee
depends on https://github.com/artsy/metaphysics/pull/1018 and https://github.com/artsy/gravity/pull/11683 (and creating the site feature in staging).
This is what I was thinking re: https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=DISCOVER&view=planning&selectedIssue=DISCOVER-56 (surfacing the rail to the top of the homepage)
If the Metaphysics/Grav stuff is done right, this _should_ just work. I suspect Emission has a similar thing going on: https://github.com/artsy/emission/blob/7b91993ee1043fd2a78e279dec4be3f89310229a/src/lib/Scenes/Home/Components/ForYou/index.tsx#L128 (maybe some other places too)
@sarahscott can help out with it!
> @damassi => Add support for recently viewed artwork rail on homepage

- src/desktop/apps/frieze_week/index.js
- src/desktop/components/auction_reminders/blacklist.coffee
When we're ready, 
- Removes admin flags from Frieze week page
- Adds `/spring-art-fairs` to auction reminder blacklist
> @xtina-starr => Remove admin from `/spring-art-fairs`

- src/desktop/components/contact/show_inquiry_modal.coffee
- src/desktop/components/contact/view.coffee
https://artsyproduct.atlassian.net/browse/EV-94
Missed this instance when enabling 'x' on the rest of contact modals.
> contact modal can be closed with x button on contact gallery from fair page

- src/desktop/apps/artist/client/views/overview.coffee
- src/desktop/apps/artist/templates/sections/overview.jade
- src/desktop/apps/artist/test/templates.coffee
This fixes the AB test on artist pages, which is queued up on Staging, to hide the info section when a user is in the `no_header_merch_sort` group - we should be hiding both the header and info sections for this group.
After this change the experiment group now looks like this:
> hide info in artist page experiment group

- src/desktop/components/recently_viewed_artworks/index.coffee
Now that we have a 'Recently Viewed' artworks rail, this can be removed from the homepage.
Fixes https://artsyproduct.atlassian.net/browse/DISCOVER-81
> @xtina-starr => Remove recently viewed works component from home

- src/desktop/components/auth_modal/templates/_gdpr_signup.jade
- src/desktop/components/inquiry_questionnaire/templates/account/register.jade
- src/desktop/components/inquiry_questionnaire/test/views/account.coffee
Per a conversation with @katarinabatina and @junybrum on Friday we discovered that when users created an account with facebook as part of the inquiry flow those inquiries weren't going through. Seeing that we've closed the GDPR test we decided to go ahead and revert back to the old register form.
> Restore inquiry auth modal

- src/desktop/apps/artsy_primer/personalize/client/index.coffee
- src/desktop/apps/artwork/components/auction/view.coffee
- src/desktop/apps/artwork_purchase/client/index.coffee
- src/desktop/apps/auctions/client/index.coffee
- src/desktop/apps/how_auctions_work/client/index.coffee
- src/desktop/apps/inquiry/client/routes/development.coffee
- src/desktop/apps/pro_buyer/pages/landing/client/view.coffee
- src/desktop/components/artist_page_cta/view.coffee
- src/desktop/components/artwork_save/view.coffee
- src/desktop/components/auction_artwork_brick/view.coffee
- src/desktop/components/auth_modal/view.coffee
- src/desktop/components/cta_bar/view.coffee
Consolidates most of the places where we were using AuthModalView directly instead of going through the mediator. 
There are a few places remaining that will have to be refactored as we get the main modal in --
- InquireViaPhoneModalView which extends AuthModalView
- FairHeaderView which does not have the main_layout nav to trigger mediator
Addresses https://artsyproduct.atlassian.net/browse/GROW-587
> @xtina-starr => Use mediator to trigger auth modal where possible

- src/desktop/apps/artist/client/index.coffee
- src/desktop/apps/artist/client/router.coffee
- src/desktop/apps/artist/client/views/overview.coffee
- src/desktop/apps/artist/routes.coffee
- src/desktop/apps/artist/templates/index.jade
- src/desktop/apps/artist/templates/sections/overview.jade
- src/desktop/apps/home/client/index.coffee
- src/desktop/apps/home/routes.coffee
- src/desktop/apps/home/templates/index.jade
- src/desktop/components/artwork_filter_2/view.coffee
- src/desktop/components/artwork_filter_2/views/filters_view.coffee
- src/desktop/components/search_bar/templates/index.jade
- src/desktop/components/split_test/running_tests.coffee
This closes out the artist merch test in favour of the control group, and launches a homepage search test (whose key for analytics purposes is `home_search_test`) with two groups `control` and `experiment`.
To test on staging:
http://staging.artsy.net/?split_test[home_search_test]=control
http://staging.artsy.net/?split_test[home_search_test]=experiment
Also worth testing artist pages and checking that the search bar looks as it should on other artsy.net  pages.
> close out artist merch test and launch homepage search test

- src/desktop/analytics/main_layout.js
- src/desktop/apps/sitemaps/routes.coffee
- src/desktop/apps/sitemaps/test/routes.coffee
- src/desktop/config.coffee
- src/lib/memory_profiler.js
- src/mobile/analytics/global.js
- src/mobile/config.coffee
While I'm in here, I'll do a sweep for some other places that may need updating to their own flags.
On `force-production`:
Set `ENABLE_WEB_CRAWLING=true`.
On `force-staging`:
Set `SHOW_ANALYTICS_CALLS=true`.
Set `ENABLE_MEMORY_PROFILING=true`.
> @joeyAghion => Add a few granular flags to replace NODE_ENV

- src/desktop/components/search_bar/templates/index.jade
This fixes the search button not showing when in the homepage context. We only pass a `testGroup` through to the template in the home context. I was erroneously using a variable belonging to another object (`centeredHomepageSearch`).
> fix issue with search test not showing search button

- src/desktop/components/auction_lots/templates/auction_lots_table.jade
Found this while digging through old code when clicking the image from a line-item here: https://staging.artsy.net/artist/gerhard-richter/auction-result/260585. 
Restores the modal popup:
> [Bugfix] Ensure lot.id is available for modal on /artist/:id

- src/desktop/apps/rss/templates/news.jade
- src/desktop/apps/rss/test/news.coffee
Addresses [GROW-585](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-585)
In the RSS feed, uses default meta image for enclosures on 'news' articles rather than `thumbnail_img`.
> @kanaabe => News rss default meta img

- src/desktop/apps/auction_support/client/index.coffee
- src/desktop/apps/auction_support/routes.coffee
- src/desktop/apps/auction_support/templates/bid-form.jade
- src/desktop/apps/auction_support/test/client/registration_form.coffee
- src/desktop/apps/auction_support/test/routes.coffee
- src/desktop/apps/auction_support/test/templates.coffee
This PR addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-85
We now return whether or not a user has a valid credit card through the `has_valid_credit_cards` field under `me` (from metaphysics).
I updated the flow slightly to also grab whether or not a user is registered for the sale in the same metaphysics query as above. It's not really any more efficient but it's a little easier to follow this logic than to have to poke through backbone models.
For clarity, here's what the logic does:
- when you click "Bid" on the artwork page, we check to see if you are `isRegistered` and `hasValidCreditCard`.
- If `isRegistered` is true, then we show you a confirm bid page with no cc form attached
- when you click "bid" we just create a bidder position via the `me/bidder_positions` …
> @erikdstock => dont make users enter credit card again when they try to bid and already have one on file

- src/desktop/components/recently_viewed_artworks/index.coffee
- src/desktop/lib/global_client_setup.coffee
- src/lib/setup.js
when available, otherwise use the existing cookie source.
> @sarahscott => Update recently viewed artwork footer to read from cross-platform ids

- src/desktop/apps/home/client/index.coffee
- src/desktop/apps/home/queries/initial.coffee
As per @katarinabatina , since the footer (Magazine + Shows) section on the homepage is de-prioritized, and we're going to be expanding w/ more similarity rails and dropping our 'max' limit, this starts it off doing just that.
Removes cap on max rails and max gene rails (for now in effect this adds a bunch of gene rails towards the bottom of the homepage). As we add the other similarity rails, if we feel that now it's just _too_ many rails, we can cap stuff back. For instance, we could cap _just_ the gene rails w/o limiting anything else.
Currently our limit of 7 means we are actually hiding one of the 'special' rails (recently viewed, 'active bids', etc. - we have > 7 of these now).
> @damassi => Allow all the homepage rails!

- src/desktop/apps/auction_support/client/registration_form.coffee
- src/desktop/apps/auction_support/stylesheets/index.styl
- src/desktop/apps/auction_support/templates/registration-form.jade
- src/desktop/apps/auction_support/templates/registration.jade
- src/desktop/apps/auction_support/test/client/registration_form.coffee
- src/mobile/apps/auction_support/stylesheets/index.styl
This PR updates the auction registration form to be disabled until the conditions of sale have been accepted. The link to the conditions opens in a new window. See happy path through error states below:
After talking to @briansw we agreed to the following changes from the new Zeplin mocks for checkboxes and error states:
- Same checkbox as used in artsy-elan
- Red box/text on error
- No error message above the submit button because the input already shows it
> @sweir27 => Require users accept conditions of sale upon registration

- src/desktop/apps/auction_support/templates/conditions-of-sale-checkbox.jade
- src/desktop/apps/auction_support/templates/registration-form.jade
- src/mobile/apps/auction_support/client/registration_form.coffee
- src/mobile/apps/auction_support/stylesheets/index.styl
- src/mobile/apps/auction_support/templates/registration-form.jade
- src/mobile/apps/auction_support/templates/registration.jade
- src/mobile/apps/auction_support/test/client/registration_form.coffee
Tracked in https://artsyproduct.atlassian.net/browse/PURCHASE-122
This follows the same pattern as #2470 to add a checkbox for accepting conditions which disables the mobile auction registration form.
I used the same red error color that the rest of the mobile form already used.
> @sweir27 => Mobile registration - require users accept conditions of sale

- src/desktop/apps/artist/queries/articles.coffee
Addresses [GROW-573](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-573), limits articles appearing on `/artist` pages with `in_editorial_feed` query, which excludes the "news" layout.
> @xtina-starr => /artist articles limited to "in_editorial_feed"

- src/desktop/components/search_bar/view.coffee
Tweak (thanks @damassi, feels a lot better! ) - if you continue typing the spotlight'ed search, we don't need to hide it.
> @mzikherman => Dont hide spotlight search if you continue typing it

- src/desktop/components/artwork_filter_2/models/filter.coffee
(Moving defaults before instance vars in https://github.com/artsy/force/pull/2487 inherited an invalid default pagination size)
> [Bugfix] Fix pagination

- src/desktop/components/search_bar/index.styl
- src/desktop/components/search_bar/view.coffee
Chipping away at the comp, this moves the placeholder text/styling to the bottom of the list for the feature:
When selected:
As always, when you select/hit enter on that placeholder item, you go to the search results page.
> @cavvia => Move 'Search for ...' placeholder item to bottom of search results

- .circleci/heroku_deploy.sh
- scripts/deploy.sh
This should hopefully fix the staging deploys to Heroku.
Follow-up: we deploy to production using Circle (PRs to the `release` branch), does that still work with 2.0 or is there a different process?
> @saolsen => heroku deploys on circle 2.0

- .circleci/config.yml
The deploy failed since it didn't have the results of `yarn install`, etc. - I changed this to match some of the other steps (which do seem to pick up the `Dockerfile` properly).
> @saolsen => Run heroku deploy command properly on Circle 2.0

- .circleci/config.yml
- .circleci/heroku_deploy.sh
- .circleci/heroku_setup.sh
cc @saolsen 
The staging deploy worked, so this tries to generalize a tad and add a production one.
> @damassi => Add heroku prod deploys for Circle 2.0

- .circleci/config.yml
I'm not sure where this other key came from, but the fingerprint doesn't match the key(s) configured in [Circle](https://circleci.com/gh/artsy/force/edit#ssh) or [Github](https://github.com/artsy/force/settings/keys). I _think_ this is the right read/write key to use instead.
> @mzikherman: Try using correct (?) key

- src/desktop/apps/auction_support/client/registration_form.coffee
- src/desktop/apps/auction_support/stylesheets/index.styl
- src/desktop/apps/auction_support/templates/conditions-of-sale-checkbox.jade
- src/mobile/apps/auction_support/client/registration_form.coffee
- src/mobile/apps/auction_support/stylesheets/index.styl
- src/mobile/apps/auction_support/templates/registration-form.jade
This PR addresses design feedback from @briansw in PURCHASE-128, -129 AND -130:
https://artsyproduct.atlassian.net/browse/PURCHASE-106
In order to meet PURCHASE-129 (hover on link should not trigger checkbox hover state) I had to unset some of the default `.artsy-checkbox` styling and wrap the input in its text label, then align the link with the text. It appears fine for me in mobile and desktop, but it did take some nudging.
EDIT: Update with new styling that fixes the period issue pointed out by @briansw below. It adds a little extra javascript and an `a::before` pseudoelement to block the hover state when hovering on the link specifically.
> @sweir27 => Purchase 106 QA Fixes

- .circleci/config.yml
Noticed this was missing with our new deployment pipeline. This follows our [previous config](https://github.com/artsy/force/blob/9f74b2099eb42c11d80fb83caae048697ab8c1d2/circle.yml#L4) but updated to Circle 2
> @mzikherman => [CircleCI] Ignore staging branch in prod deploys

- src/desktop/collections/features.coffee
- src/desktop/models/mixins/relations/artwork.coffee
The `related/features?artwork[]=...` API hasn't been used in years and we removed it in https://github.com/artsy/gravity/pull/11694. I'm just trying to clean up the reference to it and the associated collection here.
There remain many references to the `Feature` model and routes. I think we've largely deprecated these but I can't tell what might still be used.
> @anandaroop: Try to remove references to unused related/features?artwork[]=... API

- src/desktop/components/artwork_brick/query.coffee
- src/desktop/components/artwork_filter_2/models/filter.coffee
- src/desktop/lib/global_react_modules.js
To be merged in conjunction with https://github.com/artsy/reaction/pull/683. Wraps stitch grid components in an `Artsy.ContextProvider` so that we can use saves.
- Also updates `/artist/id`
- Enable saves for `/artwork/id`, `/collect` and `/shows`
> @mzikherman => Enable saves in stitch Artwork Bricks 

- src/desktop/components/search_bar/view.coffee
> @mzikherman => Fix for pressing enter quickly on spotlight search

- src/desktop/apps/auction_support/client/bid_form.coffee
- src/mobile/apps/feature/stylesheets/bid.styl
Noticed in my QA that the combo bid/registration form would return a weird error when attempting to bid and register in the same go.
Turns out the call to `@validateAcceptConditions()` was failing because after you register, we instantiate the bid form with `@submitImmediately` set to true. Since the `@$acceptConditions` and  `@$conditionsCheckbox` elements didn't exist in that scenario, it was failing.
> @mzikherman => fix issue with validation on the combo bid form

- src/mobile/apps/artwork/components/image/templates/index.jade
- src/mobile/apps/artwork/components/meta_data/templates/index.jade
Reported on [#incidents](https://artsy.slack.com/archives/C9RK0BLEP/p1526655623001021) channel.
The file has been changed in [this](https://github.com/artsy/force/commit/0e324a1281d6ce2a07b9ba430bbdc59d51608fd4#diff-ad0338dacfbe0c2a9b1baec49bb7aecf) commit. Merged in [this PR](https://github.com/artsy/force/pull/2420). Still figuring out if it was intentional.
> Fixes missing auction artwork detail

- package.json
- src/mobile/apps/auth/client/signup.coffee
- src/mobile/apps/auth/stylesheets/index.styl
- src/mobile/apps/auth/templates/call_to_action.jade
- src/mobile/apps/auth/templates/gdpr_checkbox.jade
- src/mobile/apps/auth/templates/signup.jade
- src/mobile/apps/auth/templates/signup_buttons.jade
- src/mobile/apps/auth/test/client.coffee
- yarn.lock
FYI this needs the [update to artsy-passport](https://github.com/artsy/artsy-passport/pull/126) before this gets merged.
This adds the new gdpr checkbox for mobile signups and requires the user to click the checkbox before being able to select one of the signup options (facebook or email).
New Checkbox:
Error State:
> @l2succes: [HOLD] requires user to click gdpr checkbox before creating an account

- src/desktop/apps/artwork/client/index.coffee
- src/desktop/apps/artwork/client/test/index.coffee
- src/desktop/apps/artwork/components/fair_artworks/query.coffee
- src/desktop/apps/artwork/components/show_artworks/index.jade
- src/desktop/apps/artwork/components/show_artworks/query.coffee
Based on recent metaphysics latency/memory issues, this fix is timely.
It's the follow-up from https://github.com/artsy/force/pull/2267 and should remove the remaining cases in force where we're using `all: true` to get all objects via pagination in metaphysics.
I borrowed the logic from the mobile-web side, but we can always revisit with updated language. For now it just says "View all <num artworks> works".
> @alloy => no longer query for all: true on desktop artwork pages (for shows)

- src/mobile/apps/artist/client/view.coffee
Missed the mobile app when we made this change a few weeks ago on desktop, filters articles in `/artist` pages by `in_editorial_feed` to exclude news articles.
> @l2succes => Filter mobile artist articles by in_editorial_feed

- src/desktop/apps/home/queries/initial.coffee
Reverts artsy/force#2528
In prep for MP being rolled back: these new rails `SIMILAR_TO_RECENTLY_VIEWED`, etc. wouldn't exist and MP would throw an error on that.
> @cavvia => Revert "add support for new homepage rails and update rails order"

- src/desktop/apps/home/client/setup_home_page_modules.coffee
A recent upgrade of moment broke the home page due to a breaking API change. The fix is to import
`moment-timezone` instead of `moment` when we need access to timezone data (e.g. `moment.tz()`). The issue is described here ((https://github.com/moment/moment/issues/4313))
I missed this one import during the update.
> @kanaabe => homepage fix

- src/desktop/components/split_test/running_tests.coffee
Somehow this line got stripped out when merging changes -- puts control group back for tooltips test
> @kanaabe => Put back control group

- src/desktop/apps/search/test/client/index.coffee
- src/desktop/models/search_result.coffee
- src/desktop/test/helpers/fixtures.coffee
- src/desktop/test/models/search_result.coffee
When two items of different types but with the same slug are returned by our auto-suggest API, Force renders them as the same item, essentially eliminating the other result and displaying a dupe. For example, Code Art Fair and the Code tag share the same slug, `code`, but only the Fair is rendered (twice):
I fix this by setting the `id` attribute in our result items to the Mongo OID and moving the slug to `slug`. I assume the component is using the `id` attribute to index the items and using a slug for that is invalid since we're dealing with multiple entity types.
Fixes https://artsyproduct.atlassian.net/browse/DISCOVER-120
> fix issue with dupe search results when items share the same slug

- src/desktop/apps/artwork/components/artists/index.jade
- src/desktop/apps/artwork/components/artists/index.styl
- src/desktop/apps/artwork/components/artists/templates/biography.jade
This needs the updated MarketInsights component from https://github.com/artsy/reaction/pull/706 to look like this:
> Move the market Insights to be right below artist name on artwork page

- src/desktop/components/main_layout/templates/index.jade
- src/desktop/components/search_bar/collections/search.coffee
- src/desktop/components/search_bar/index.styl
- src/desktop/components/search_bar/templates/item.jade
- src/desktop/components/search_bar/test/search.coffee
- src/desktop/components/search_bar/view.coffee
Having this lab feature turned on supersedes the spotlight AB test, and could be safe to merge/deploy in the meantime (while the AB test is running), if we're happy with the approach and want to QA further.
The idea is that we flatten out the hash returned from Gravity, and the _first_ element in each group, gets an additional property which is the category itself. Then, the dynamic template for each item in the dropdown knows to render a top line of category when this is present, which results in quite decent scrolling/selecting behavior.
> @cavvia => Grouped search results lab feature

- package.json
- webpack.config.js
Webpack Bundle Analyzer already exists as a dependency on the project, this just wires it up to be used. 
Bundle analyzer is a tool that gives a detailed visualization of modules included in a webpack build. It can give quick insight into large areas of code duplication or focus areas for optimizations. 
Here's an example output
As a quick demonstration of its value, here we can see part of common.js that actually includes two versions of moment.js
> Implement webpack bundle analyzer

- Dockerfile
We are seeing issues with yarn install on docker images
https://circleci.com/gh/artsy/force/6484
Switched to install yarn the _recommended_ way and not use `npm` to install it, while doing that noticed these errors in our log:
```
warning Error running install script for optional dependency: "/app/node_modules/keytar: Command failed.
```
And ended up installing `libsecret-1-dev libglib2.0-dev` on the image to fix it.
> Changed how we install yarn in our image

- src/desktop/apps/partnerships/stylesheets/marketo.styl
This is a pure CSS change, in order to correctly style the new GDPR form markup that will be activated on the Marketo side. The last two rows in this screen cap represent what's new:
The actual markup is not under our control — we go through a lot of hoops to style this based on the selectors they provide.
> [GDPR] Update styling of Marketo auction partnerships form

- yarn.lock
This updates react from 16.2.0 to 16.4.0. This will put force in line with what's set in Reaction. 16.3 adds the Context API which we'll be using in Reaction for some of the upcoming work on Artist/Artwork page. There's no breaking changes, but we may start seeing some deprecation warnings for things the react team plans to phase out during the suspense work.
> Update react to 16.4.0 from 16.2.0

- src/desktop/apps/auction/components/DOM.js
- src/desktop/apps/auction/components/__tests__/DOM.jest.js
- src/desktop/apps/auction/queries/me.js
Depends on https://github.com/artsy/metaphysics/pull/1093 [merged]
Tracked here:
https://artsyproduct.atlassian.net/browse/PURCHASE-190
This PR makes removes an inconsistency in our checks for the new GDPR auction registration flow. Instead of checking whether a user `has_qualified_credit_cards` we are now just checking for `has_credit_cards` (the metaphyics PR above adds this field & is thus a blocker).
It addresses a bug due to a common issue with cards outside North America failing some checks.
> Check for any credit cards [not just qualified] at auction registration

- src/desktop/components/main_layout/footer/index.styl
- src/desktop/components/main_layout/footer/lower.jade
- src/desktop/components/main_layout/footer/view.coffee
https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-699
Previously displaying the wechat QR code wasn't taking in account resizing the screen this fixes that.
> @l2succes: fix wechat positioning

- scripts/deploy.sh
Adds a tag on a deploy to heroku/hokusai, I think. It's a little hard for me to test this.
I've added an ENV var for @artsyit to deploy it on circle, and referenced that. Whoever makes the next deploy can say whether it worked or not.
> Adds tagging to production deploys

- src/desktop/apps/auth2/index.ts
- src/desktop/apps/auth2/routes.ts
- src/desktop/apps/home/client/auth_router.coffee
- src/desktop/apps/home/index.coffee
Addresses [GROW-713](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=GROW&modal=detail&selectedIssue=GROW-713)
If `sd.NEW_AUTH_MODAL`, the `/forgot` route is served by `/auth2` app.  Otherwise, behavior is the same as existing production. 
Static route:
Existing route:
> @kanaabe => Static route for /forgot

- src/desktop/apps/rss/templates/news.jade
- src/desktop/apps/rss/test/news.coffee
Tried loading our feed in a few RSS readers, and the default image renders fine as it is-- not sure why Apple News is not able to read the correct image, but taking another stab using the meta `og:image` tag, which is included in their spec [here](https://help.apple.com/newspublisher/icloud/?lang=en#/apdc2c7520ff).
> @kanaabe => Use meta image tag for news articles

- src/desktop/apps/auction/queries/sale.js
In other tiles artwork metadata comes from [relay](https://github.com/artsy/reaction/blob/master/src/Components/Artwork/Details.tsx#L112-L116
), but in this tile it comes from `SaleQuery` which was missing artist `name` and `href`.
> Fixes missing buy-now artist name

- src/desktop/components/light_detector/index.coffee
- yarn.lock
This turned out to be a red herring in an ongoing incident but did alert us to an improper import that has probably been off for a while. The error we were getting in the console was 'BackgroundCheck is undefined' (at `BackgroundCheck.init`).  We are using a { Named } import  but the export for that BackgroundCheck looks like
```js
return {
/*
* Init and destroy
*/
init: init,
destroy: destroy,
...
```
> fix background check import

- src/desktop/components/fair_layout/client/header.coffee
- src/desktop/components/fair_layout/test/client/header.coffee
- src/desktop/components/light_detector/index.coffee
Looks like [this commit](https://github.com/kanaabe/force/commit/e42ecd52998bdf514e33aaefa513b93c2769a445#diff-05fc90c4bdb96b10a0557c46ae6d06f3) first introduced the issue, but anyway we need to do `mediator.on 'open:auth', @openAuth` in order to open the auth modal for Fair pages since those don't use `main_layout/client/header`. Went ahead and added the latest analytics fields to these mediator triggers as well, and a test 😉
> @xtina-starr => Fixes fair login/signup nav

- src/desktop/assets/misc.coffee
Delete my account button doesn't work on settings page.
there is a typo in reuqire
```
Uncaught ReferenceError: requre is not defined
at Object.<anonymous> (misc-b9700559.js.jgz:1)
at Object../src/desktop/assets/misc.coffee (misc-b9700559.js.jgz:1)
at r (common-20a6894c.js.jgz:1)
at Object.26 (misc-b9700559.js.jgz:1)
at r (common-20a6894c.js.jgz:1)
at window.webpackJsonp (common-20a6894c.js.jgz:1)
at misc-b9700559.js.jgz:1
```
> Fix typo in require

- .circleci/heroku_setup.sh
After https://github.com/artsy/force/pull/2638 and making sure `set -e` worked, the [master build](https://circleci.com/gh/artsy/force/6865) actually caught something and failed 😝. We can compare with a previous master build that had the same error but didn't fail the build.
This PR uses `mkdir -p` to not error when the folder exists.
We can actually go one step further and clean up some scripts, given CircleCI 2.0 now has an easier way to [deploy to Heroku](https://circleci.com/docs/2.0/deployment-integrations/#heroku) ([Volt](https://github.com/artsy/volt/pull/3047) and Induction switched to that). However, Force deployment is more involved and we might just move to K8s at some point, so I decided to leave it for now.
> Fix file exists error when creating .ssh folder for Heroku deployment

- scripts/start.sh
Follow up on https://github.com/artsy/force/pull/2352#discussion_r182159039.
I noticed in our [papertrail log](https://papertrailapp.com/systems/force-staging/events?focus=946681803429867523) we accidentally listed all the exported variables. I believe that was intended for local development when a .env file is present. This PR changes the default mode for running the app to development unless `NODE_ENV` is production, and hope this can simplify the checking.
More details in the commit message (copied below):
Previously we started the app by default in production mode, and only started it in dev mode when `$NODE_ENV` is set to "development". However, this requires us to grep `NODE_ENV` from .env and export it in development before being able to perform the check.
However, in production, …
> Start app in dev mode by default unless NODE_ENV is production

- .circleci/heroku_deploy.sh
After https://github.com/artsy/force/pull/2647, I noticed in the [log](https://papertrailapp.com/systems/force-staging/events?focus=946879422122909698) we `npm start` twice after deployment. Heroku will [restart dynos after deployment](https://devcenter.heroku.com/articles/dynos#restarting) so I don't think we need to manually do `heroku restart`.
> Remove unnecessary `heroku restart` after deployment

- yarn.lock
Heroku staging deployment [failed](https://circleci.com/gh/artsy/force/6977) because of outdated yarn.lockfile. This ran `yarn install` to update it.
> Yarn install

- .circleci/config.yml
Follow up on https://github.com/artsy/force/pull/2490
* Don't kick off builds for [staging branch](https://circleci.com/workflow-run/e3b35227-4ddb-4702-8a7b-1989d9030b49).
* Also require acceptance tests before deploying to Heroku.
> Skip staging branch on CI; require acceptance tests before deploying to Heroku

- src/desktop/apps/auth2/__tests__/helpers.jest.js
- src/desktop/apps/auth2/helpers.ts
- yarn.lock
This ensures the gdpr properties are passed via email signups (specifically adds `agreed_to_receive_emails`). It also bumps up the version of reaction. 
Payload:
Gravity db:
> @eessex: Verify gdpr auth

- src/desktop/apps/article/components/__tests__/Article.test.js
- src/desktop/apps/article/components/layouts/Article.js
- src/desktop/components/split_test/running_tests.coffee
- yarn.lock
It sets up the test (but puts 100% of users in the control group), conditionally removes the infinite scroll based on the test group, and adds the display panels along with the related articles canvas.
Also there is random `margin-bottom` in the [display canvas](https://artsyproduct.atlassian.net/browse/GROW-739) that causes the ad to scroll which will be addressed in a separate PR.
Signed-off-by: Eve Essex <e.essex@artsymail.com> // cc: @eessex
> @kanaabe: Implement infinite scroll a/b test

- package.json
- src/desktop/apps/auth2/components/AuthStatic.tsx
- src/desktop/apps/auth2/components/__tests__/AuthStatic.jest.js
- yarn.lock
Bumps Reaction to render auth modals using new design system component, replaces use of `DesktopHeader` (now deprecated) with `ModalHeader`.
> @l2succes => Use system Modal for Auth

- src/desktop/apps/auth2/__tests__/helpers.jest.js
- src/desktop/apps/auth2/helpers.ts
Minor: this adds the tracking label for local signup/login. This was overlooked the last bit of analytics work.
> @l2succes: add tracking label for local signup/login

- src/desktop/apps/auth2/index.ts
When we switched over to the new auth flow we didn't handle the `/reset_password` route. This came up in insidents because users that are attempting to reset their password are getting a 404 error. For  more context view the [slack conversation](https://artsy.slack.com/archives/C9RK0BLEP/p1531765572000503). 
This PR adds the `/reset_password` to the new auth flow (auth2) but we should follow up to clean up especially when we finish covering the other versions of the auth modal (i.e. marketing auth modal, artist page cta, etc.).
cc: @junybrum
> @saolsen: make sure to handle the /reset_password route in new auth flow

- package.json
- webpack.config.js
- yarn.lock
A start on bundle optimization, this removes the localization file from moment and kills cheerio in the client build. There are seemingly other dependencies that _shouldn't_ be directly included in this. 
@orta pointed out that graphql is being included in our client bundle as well which it probably shouldn't be.... lots more to do here, but I'm just kicking it off.
> Reduce JS bundle sizes

- package.json
- src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
- src/desktop/apps/article/components/NewsArticle.tsx
- src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.test.js
- yarn.lock
Removes `/news` rendering of `DisplayCanvas` and `RelatedArticlesCanvas` in favor of rendering in Reaction.  Follows up on https://github.com/artsy/reaction/pull/1008.
> @xtina-starr => Infinite scroll/Display bugs

- package.json
- src/desktop/apps/auth2/components/MobileAuthStatic.tsx
- src/mobile/apps/auth/routes.coffee
- src/mobile/apps/auth/test/routes.coffee
- tslint.json
- yarn.lock
Addresses:
- [[Mobile Auth QA] Change redirect link for back button for '/login' and '/signup' static route](https://artsyproduct.atlassian.net/browse/GROW-786)
- [Mobile modals - Redirect legacy mobile auth urls to new auth static pages](https://artsyproduct.atlassian.net/browse/GROW-496)
Tasks
Depends on: https://github.com/artsy/reaction/pull/1006
> @eessex => Mobile auth pages QA

- src/desktop/apps/artist2/server.js
We get this for free under the 'artist' page type (inferred from the URL), so this overrides it for better comparison purposes.
> @joeyAghion => Specify PAGE_TYPE (for Volley) for new artist page

- src/desktop/apps/artist2/server.js
Rather than _only_ launching when there's an external referrer, we should also launch it when there is no referrer set (navigating directly from a new browser, for instance). This matches the existing implementation, not to mention makes it easier to test (in a new signed-out incognito window, visit the artist page).
> @mzikherman => Match artist page functionality and launch CTA when there is no ref set

- package.json
- webpack.config.js
- yarn.lock
This brings back only the moment localizations exclusions from #2708. That PR had to be reverted due to the cheerio change. 
| Asset           |         Old size  |   New size     |   Diff    |  Diff % |
| --- | --- | --- | --- | --- | 
| common.js         |       2.36 MB   | 2 MB   | -366 KB  |  -15.17 % |
| article.js        |       1.6 MB    | 1.4 MB   | -204 KB  |  -12.45 % |
| articles.js       |       1.57 MB|    1.37 MB  |  -204 KB  |  -12.70 % |
| editorial_features.js  |  1.58 MB |   1.38 MB  |  -204 KB  |   -12.59 % |
| mobile_articles.js   |    811 KB  |  606 KB  |  -204 KB  |  -25.20 % |
| mobile_all.js       |     606 KB |   536 KB |   -69.2 KB   |  -11.42 % |
| Old size | New size | Diff | Diff % |
| ------- | -- | -- | -- |
| 67.6 MB | 63 MB | -4.62 MB | -6.82 % |
/cc @orta …
> Remove moment.js localizations file

- .circleci/config.yml
I added this as a final step before `hokusai staging deploy ...`.
To work, we should delete the `staging` tag via `git push artsy :refs/tags/staging`. I'll do this now.
> Once again push to staging branch (since PRs from tags don't work) #migration

- src/desktop/apps/artwork/components/commercial/view.coffee
- src/desktop/components/form/README.md
- src/lib/components/create_order/index.tsx
- src/lib/components/create_order/mutation.js
- yarn.lock
This PR updates the mutation we use to create an order to follow the new shape of `createOrderWithArtwork`.
It also makes sure to send the `editionSetId` if one is selected (by pulling out the data using `Serializer`).
> Update create order mutation (for /order2) to match new shape

- src/desktop/apps/artist2/components/Meta.js
You brought up in #seo that it seemed as if Google might be crawling some of the new artist pages. What could be happening is: the _initial_ request might be getting the new page, which doesn't include this meta tag. That prevents Google from re-requesting the page w/ the special query param which falls thru to the Reflection version. What we serve to Reflection continues to be the old page, so let's add this tag to the new artist page.
Once we're ready to deploy the new artist page fully (and want Google to index the new one), we'll need to remove this tag again.
> @cavvia => Add fragment meta tag to new artist page

- src/desktop/apps/article/components/__tests__/Article.test.js
- src/desktop/apps/article/components/layouts/Article.js
- src/desktop/apps/article/routes.js
Turned out the answer to this bug was quite simple. We render different components based on `sd.ARTICLE_INFINITE_SCROLL`, but the value was appearing differently on the server vs client.  By assigning this value at the route and passing as a prop to `renderLayout` inconsistencies are avoided.
> @l2succes => Article header/ssr bugs

- hokusai/production.yml
- hokusai/staging.yml
- set `dnsPolicy: Default` to use AWS nameservers (it appears Force is not accessing in-cluster services)
- set `nodeAffinity` so Force are scheduled on the correct node group and do not contend for resources on the `tier: api` node group
- adjust production CPU request and memory limits (our default memory limit is set to 1G [here](https://github.com/artsy/substance/blob/master/services/limits.yml#L10) and seeing Force pods getting OOMKilled
> update k8s deployments

- src/desktop/apps/order2/client.js
- src/desktop/assets/order2.styl
- src/desktop/components/inquiry_questionnaire/index.coffee
- src/desktop/components/inquiry_questionnaire/map/decisions.coffee
- src/desktop/components/inquiry_questionnaire/map/steps.coffee
- src/desktop/components/inquiry_questionnaire/test/map.coffee
- yarn.lock
This PR adds support for two mediator actions being triggered [from reaction](https://github.com/artsy/reaction/blob/master/src/Apps/Order/Components/Summary.tsx#L63-L76).
The first, an FAQ modal, is straightforward.
The second, the "Ask a specialist" modal, is not so straightforward since we previously based whether or not to show the "ask specialist" modal on the `is_auction` flag. This updates that tree/label to be more generic in both cases.
There's not _great_ test coverage for the decision tree stuff, but I can try to add some for this.
> @mzikherman => modal support for faq and inquiries on the order2 page

- src/desktop/apps/artwork/components/commercial/query.coffee
- src/desktop/apps/artwork/components/commercial/templates/price.jade
- src/mobile/apps/artwork/components/meta_data/templates/price.jade
- src/mobile/apps/artwork/routes.coffee
This assumes we can get data introduced here: https://github.com/artsy/metaphysics/pull/1205 and here: https://github.com/artsy/metaphysics/pull/1207
I don't think MP was deployed any time lately but this does seem to not change anything if the data in not available.
> adding usage for domesticShipping and internationalShipping fees for artwork

- src/desktop/apps/artist2/components/Meta.js
The new page includes `<meta property="canonical" ...` but it should be `<link rel="canonical" ...>`.
> @joeyAghion => [Artist2] Update SEO tag

- src/desktop/apps/sitemaps/routes.coffee
- src/desktop/apps/sitemaps/test/routes.coffee
Staging's `robots.txt` specifies `Noindex: /` but is still constantly getting crawled. (It also _is_ getting indexed--see bing--though perhaps that's based on previously buggy robots.txt contents.)
I think we should use the stronger `Disallow: /` instead.
> @mzikherman: Disallow crawlers on staging rather than just 'noindex'

- src/desktop/apps/auth2/__tests__/helpers.jest.js
- src/desktop/apps/auth2/helpers.ts
- src/desktop/apps/auth2/routes.ts
- src/mobile/apps/art_fairs/templates/index.jade
- src/mobile/apps/artwork/components/image/view.coffee
- src/mobile/apps/auctions/templates/index.jade
- src/mobile/apps/auth/routes.coffee
- src/mobile/apps/auth/test/routes.coffee
- src/mobile/apps/fair/templates/search_results.jade
- src/mobile/apps/fair_organizer/templates/index.jade
- src/mobile/components/follow_button/view.coffee
- src/mobile/components/layout/templates/footer.jade
- src/mobile/components/layout/templates/login-signup.jade
- src/mobile/components/layout/templates/main.jade
This addresses https://artsyproduct.atlassian.net/browse/GROW-814 by adding the missing properties for analytics to the mobile signup query params.
**Auth Impression:**
**Created Account (Save Artwork):**
**Successfully Logged In (Follow Artist):**
> @l2succes: mobile auth analytics

- src/desktop/apps/auth2/routes.ts
This fixes the auth2 routes to correctly pass these couple options for fair partners.
h/t @l2succes
> Pass correct flags for fair partners

- src/desktop/apps/order2/client.js
Other part of https://github.com/artsy/reaction/pull/1109. This configures the router to use the beforeunload hook on transitions. 
The above PR will need to be merged and reaction bumped in force before it all works though.
> Configure order router to use beforeUnload event for transitions

- src/desktop/apps/artwork/components/commercial/view.coffee
- src/lib/components/create_order/index.tsx
- src/lib/components/create_order/mutation.js
- yarn.lock
I didn't run through this with all of the other services running, but it feels like the changes I'd expect - and running `yarn jest` green'd.
> Updates the query to handle the orderOrError union type from Exchange

- src/lib/middleware/error_handler.coffee
- src/lib/setup.js
- src/test/lib/middleware/error_handler.coffee
Based on pairing + local testing, this is a required addition (based on our currently used version of this lib) for it to work the way we expect.
This possibly didn't work on Heroku, or the code was lost at some point? Or perhaps Heroku/ELBs were doing something a little differently than present/we expect?
Either way, this works the way we'd like (ie- honoring the first value in the header).
Still to do-
- ~~catch and return a 401 when a block occurs (currently this is thrown and not caught and results in a 500)~~
> @joeyAghion => Pass in option to allow express-filter to block IPs based on intermediates

- src/index.js
Just followed the example from the npm page for artsy-xapp - hopefully this'll catch 502s.
> exit app on xapp error

- src/desktop/components/clock/index.styl
- yarn.lock
Addresses: https://artsyproduct.atlassian.net/browse/PURCHASE-412
Appears this fix was pretty minor! We weren't explicitly styling `.clock-months` here.
Updated view:
> @ashfurrow => Also style clock-months

- hokusai/production.yml
- hokusai/staging.yml
As per @joeyAghion's suggestion I modeled this on the way [metaphysics does it](https://github.com/artsy/metaphysics/blob/e27355ffed06e40c4b9ec7bda8d461452647b403/hokusai/staging.yml#L46).
I'm not sure how to test this, though? Do we have some sort of Hokusai mock environment?
> add readinessProbe to hokusai config for prod and staging

- package.json
- yarn.lock
This is required for the BNMO demo meeting shortly, and includes the recent feature work of the Purchase team on the Order app, and necessary metaphysics schema upgrades.
> Upgrades Reaction to 3.1.3

- README.md
- src/index.js
- src/lib/setup.js
- yarn.lock
Removes a deprecation warning on launch in staging:
```
~/dev/projects/artsy/js/sites/force master* 1m 36s
❯ hokusai staging logs
yarn run v1.9.4
$ scripts/start.sh
+ '[' production = production ']'
+ node --max_old_space_size=1024 ./src
[Force] Started on https://staging.artsy.net.
GET / 200 806.322ms 216.218.206.66 "undefined"
Tue, 28 Aug 2018 15:14:13 GMT express deprecated res.send(status, body): Use res.status(status).send(body) instead at src/lib/setup.js:296:16
GET /system/up 200 53.863ms 66.165.229.130 "Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)"
```
> Handles a deprecation warning

- src/lib/setup.js
Well, when I run `hokusai dev start` with this, it will correctly print out the right `process.env.DD_TRACE_AGENT_HOSTNAME` - so perhaps it will do so in staging/prod
> Try adding the hostname specifically to ddTracer

- src/mobile/apps/artwork/components/related_artworks/queries/index.coffee
In [this block](https://github.com/artsy/force/blob/master/src/mobile/components/artwork_columns/artwork.jade#L28-L33), if the artwork has an auction partner, we show `Auction Closed` or `Bid Now` depending on whether or not the artwork is `forsale`. 
This wasn't working as intended because we were never querying for `is_for_sale`. Note that we probably didn't catch it because this particular brand of "related works" only appears if:
- the artwork has an auction-type partner
- the artwork is _not_ in an auction
☝️ that's not a common occurrence except in this case, where we're re-using the auction house partner for an e-commerce work that's not part of an auction.
> query for is_for_sale so we can evaluate correctly and not always show "Auction Closed"

- src/desktop/apps/article/components/__tests__/App.test.js
- src/desktop/apps/article/components/__tests__/Article.test.js
- src/desktop/apps/article/components/layouts/Article.js
- yarn.lock
Addresses https://artsyproduct.atlassian.net/browse/GROW-877
- Passes `isLoggedIn` to standard/feature articles
- Stops rendering to-be-deprecated `EditorialSignupView` in `Article` (still used on magazine page)
> @xtina-starr => Editorial auth QA

- Dockerfile
- hokusai/development.yml
- src/lib/setup.js
I was trying to get `hokusai dev start` to work to debug the dd-trace stuff, and had @bhoggard come over - he mentioned that we should consider moving off the bitnami image due to https://github.com/artsy/gravity/pull/11858 
So we moved force off, and switched to directly calling apt-get instead.
> Update the dockerfile for Force to use the official node image

- src/desktop/apps/show/routes.coffee
From [this trace](https://app.datadoghq.com/apm/resource/metaphysics.graphql/graphql.query/c1dc8c86a146ee60?env=production&paused=false&traceID=4039002158837364791&spanID=8140525992543905883&start=1535732860397&end=1535736460397)
> Updates the anonymous query for show metadata to use a named query

- hokusai/production.yml
https://artsy.slack.com/archives/C9RK0BLEP/p1535731887000100?thread_ts=1535731055.000100&cid=C9RK0BLEP
Similar to https://github.com/artsy/volt/pull/3129 , Force production deployment took about 7 mins. It's on 3 pods and using the rolling update strategy with `maxSurge` 1 and `maxUnavailable` 0. I'm not super comfortable losing any of the 3 pods during deployment, so I increase maxSurge to 2 and want to see if this speeds up the deployment.
https://circleci.com/gh/artsy/force/9118
```
hokusai production update
```
> #migration Increase K8s maxSurge for production

- src/desktop/apps/artist2/client.js
- src/desktop/apps/collect2/client.js
- src/desktop/apps/order2/client.js
I think this is the way we're supposed to pass these around now. Currently in prod the artist page isn't grabbing the mediator, so it's leading to some bugs (modals, etc.).
Locally this fixes it.
> @damassi => Pass mediator to Reaction apps properly

- package.json
- src/desktop/apps/artwork/components/additional_info/index.jade
- src/desktop/components/react/stitch_components/ReactionArtworkDetails.js
- src/desktop/components/react/stitch_components/ReactionTooltipQuestion.js
- src/desktop/lib/global_react_modules.js
- yarn.lock
This just replaces the content inside `About the work` tab on artwork page. We will decide what actually should go into the whole section and how organize this information in tabs next, but for now that should make it easier to view information side by side and make those decisions.
Example of look:
And another one:
> add ArtworkDetails reaction component and display it in About the work tab when user has BNMO feature enabled

- .circleci/config.yml
- Dockerfile
$commit_hash was not being set during the `hokusai push` step - require it in builds and set it whenever a build occurs on circleci
hotfix for https://github.com/artsy/force/pull/2851
> hotfix - require commit_hash in builds

- .circleci/config.yml
The full hash causes Force to fail to start https://github.com/artsy/bucket-assets/blob/master/index.js#L229
> hotfix - bucket-assets requires a short hash

- .circleci/config.yml
Set ASSET_MANIFEST in env var again as the app fails to boot from the COMMIT_HASH (hangs with no error log)
We should review the code in https://github.com/artsy/bucket-assets/blob/master/index.js#L43
Unblock Force deployments until we can figure this out (ASSET_MANIFEST env var is [checked before](https://github.com/artsy/bucket-assets/blob/master/index.js#L28) it attempts to fetch from the CDN + COMMIT_HASH)
> restore ASSET_MANIFEST as app fails to boot from COMMIT_HASH

- package.json
- src/lib/metaphysics.coffee
- src/test/lib/metaphysics.coffee
- yarn.lock
We're running Force behind a load balancer, [which sets](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-for) the `X-Forwarded-For` header as the IP address of the client - this change makes Force append the IP of the load balancer if the header is provided, or set the header to the client IP if not provided.  Passing it along to Metaphysics, which does the same as of  https://github.com/artsy/metaphysics/pull/1232 and https://github.com/artsy/metaphysics/pull/1264 
With the chain of proxies saved in the `X-Forwarded-For` header, Gravity will be able to resolve the real IP of clients where requests are proxied via Force or MP
> pass X-Forwarded-For headers to Metaphysics

- src/desktop/apps/artwork/components/commercial/templates/inquire.jade
- src/desktop/apps/artwork/components/commercial/test/template.coffee
- src/desktop/apps/artwork/components/partner/index.jade
- src/desktop/apps/artwork/test/fixtures/acquireable_artwork.json
- src/desktop/components/artwork_metadata_stub/queries/contact.coffee
- src/desktop/components/artwork_metadata_stub/templates/contact.jade
- src/desktop/components/artwork_metadata_stub/test/index.js
- src/mobile/apps/artwork/components/meta_data/templates/inquiry.jade
- src/mobile/apps/artwork/components/meta_data/test/template.coffee
The goal of this PR is to unblock https://github.com/artsy/metaphysics/pull/1249.
Until we launch the BNMO feature, we want (on desktop + mobile web):
- Auction-partner artworks that are `inquireable` _and_ `acquireable` should show the "Buy" button only
- Gallery-partner artworks that are `inquireable` _and_ `acquireable` should show the "Inquire" button _unless_ you have the lab feature, in which case you should see the "Buy" button
- Gallery-partner artworks that are `inquireable` and _not_ `acquireable` should show the "Inquire" button
- Works in an auction that are also `acquireable` should show the bid form + the "Buy" button
When we launch the BNMO flow, we will update this to be simpler:
- Works that are `inquireable` and `acquireable` should _just_ show the buy button (across the …
> Works that are inquireable and acquireable should behave correctly

- src/desktop/apps/auctions/routes.coffee
- src/desktop/apps/auctions/test/routes.coffee
[Mobile web](https://github.com/artsy/force/blob/master/src/mobile/apps/auctions/routes.coffee#L16) already fetches 100, as does [emission](https://github.com/artsy/emission/blob/0dd4d4cc479aa6c3c74bb73b63212f7a8bd41747/src/lib/Scenes/Home/Components/Sales/index.tsx#L96). This updates desktop to fetch 100 sales too.
> bump the number of auctions we show on artsy.net

- package.json
- src/desktop/apps/artwork/components/additional_info/index.jade
- yarn.lock
This still needs a wrap of Boot to make tabs look proper and I need to work on the designs updates that were made recently. But at least all the data should be there and we can start testing the data while I work on updating the looks:
> bring the current version of ArtworkDetails from reaction

- src/desktop/apps/artist2/components/Meta.js
- src/desktop/apps/artist2/components/__tests__/Meta.jest.js
One last item for seller info, seems to run green with the partner image URL in addition to thumbnailUrl.
> @l2succes => add partner image url

- src/desktop/apps/article/components/layouts/Article.js
Addresses https://artsyproduct.atlassian.net/browse/GROW-887
This moves the trigger to launch the editorial auth modal into force. It ensure the modal doesn't fire for logged in users and users that have dismissed the auth modal.
> fix editorial auth modal

- yarn.lock
https://github.com/DataDog/dd-trace-js/compare/27c00ff3428ae4fa76a61590de9787d5cf37fa6e...9945be573c86a5827a00b8e258cdcf88af7a0cbd
> [tracer] Update to latest version of upstream v0.6.0 branch.

- .vscode/settings.json
- scripts/start.sh
Ok, spent a bit more time trying to come up with a good pattern to automatically attach vscode’s debugger in a re-usable way across projects. I’ll comment inline.
> [script] Enable debug server if ran from vscode terminal.

- src/desktop/apps/page/index.coffee
Just using the old school pages for this. Already added (in staging and prod): https://admin-staging.artsy.net/page/buy-now-feature-faq
> @damassi => Support a standalone page for the Buy Now FAQ

- src/desktop/analytics/main_layout.js
- src/desktop/apps/artwork/routes.coffee
Adds an `ecommerce` property to our artwork pageview tracking for analytics purposes. I'm using the `is_acquireable` property on the artwork object, which I now share with the client by setting it in `sd.ARTWORK` as we do in some other places. I'm assuming that sharing the Artwork object with the client is not a security or privacy issue - I can't see any sensitive data in it (such as hidden prices).
The difference between `acquireable` and `ecommerce` is worth mentioning. I'm using the latter name in analytics for simplicity, to indicate that the artwork was available for direct purchase at the time of the pageview. If we look at the `acquireable` definition in Gravity it's a little more complicated than simply having the `ecommerce` flag set:
```ruby
def acquireable?
published? && …
```
> add ecommerce property to artwork pageview tracking

- src/desktop/apps/frieze_week_london/client/initializer.js
- src/desktop/apps/frieze_week_london/fixture.json
- src/desktop/apps/frieze_week_london/index.js
- src/desktop/index.js
This addresses https://artsyproduct.atlassian.net/browse/GROW-891 and creates the marketing landing page for Frieze Week London under the url `/london-art-fair-week`. This particular landing page should not included an event section so we simply needed to remove the events object from the json.
A few to do items before this page is ready to launch:
> @l2succes: create marketing landing page for frieze week london

- src/desktop/components/main_layout/footer/upper.jade
Removed link to "Artsy for Professional Buyers"  from Force components.
[See DISCO-289 for info.](https://artsyproduct.atlassian.net/browse/DISCO-289) 
[Related PR Reaction #1290](https://github.com/artsy/reaction/pull/1290)
> Removed defunct link from Jade footer template

- src/desktop/apps/consign/templates/landing.jade
- src/desktop/apps/order2/server.js
- src/desktop/components/main_layout/stylesheets/body.styl
Removes a `FIXME` note introduced yesterday now that other pages using the updated minimal header have been validated. Fixes a regression with the updated header not respecting the `.body-no-header` class. See below for screenshots of affected pages.
> fix: remove minimal header margin whitelisting

- src/mobile/components/layout/bootstrap.coffee
Documented in https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-295 , but this has cropped up / been reported many times, but always hard to reproduce.
This starts logging refreshes to Sentry (which should be grouped together), as well as the 'extra' data so we can see if there's a pattern:
> @sweir27 => Log out some info for the mysterious endless reload issue

- src/desktop/apps/artwork/components/commercial/bootstrap.coffee
- src/desktop/apps/artwork/components/commercial/test/view.coffee
- src/desktop/apps/artwork/components/commercial/view.coffee
- src/desktop/apps/artwork/test/fixtures/acquireable_artwork_single_edition.json
- src/mobile/apps/artwork/components/meta_data/view.coffee
- yarn.lock
Currently, if an artwork has a _single_ edition set, we're not sending an `editionSetId` along with an `artworkId` to exchange. This fixes that issue.
(Note that this functionality was overlooked because gravity [assumes the first](https://github.com/artsy/gravity/blob/master/app/api/v1/me_orders_endpoint.rb#L34-L36) in this scenario).
> If artwork has a single edition set, send that edition set ID with the createOrder mutation

- src/desktop/apps/frieze_week_london/index.js
This removes the `adminOnly` flag so the marketing landing for Frieze Week London is visible to all users.
> @eessex: remove adminOnly flag for frieze week london

- src/desktop/assets/misc.coffee
- src/desktop/components/commercial_filter/filters/period/period_map.coffee
The old version of `/works-for-you` supported either `artist` or `artist_id` query params (I believe we've used `artist` in emails, and `artist_id` from the bell dropdown).
So this just adds that here.
> @damassi => Support artist and artist_id query params to /works-for-you

- src/desktop/apps/artwork/components/commercial/templates/acquire.jade
- src/desktop/apps/artwork/components/commercial/templates/consign.jade
- src/desktop/apps/artwork/components/commercial/templates/index.jade
- src/desktop/apps/artwork/components/commercial/templates/questions.jade
- src/desktop/apps/artwork/components/commercial/test/template.coffee
- src/desktop/apps/artwork/components/commercial/view.coffee
- src/desktop/apps/artwork/lib/inquire.coffee
- src/desktop/components/inquiry_questionnaire/map/decisions.coffee
- yarn.lock
Can't figure out just yet where the email to contact a specialist is set. For now just reusing the logic that we currently have on auction page to contact a specialist. This logic seem to be using inquiry decision tree that is quite complex. Don't feel like I know enough to change any of that though...
The proposed solution seem to do what https://artsyproduct.atlassian.net/browse/DISCO-226 asks for except for not modifying any emails for now. Will try to figure that out next of maybe somebody know right away: @sweir27 or @damassi ?
> Adding contact specialist link to bnmo artwork

- package.json
- src/desktop/index.js
- src/desktop/lib/global_client_setup.coffee
- src/mobile/index.js
- src/mobile/lib/global_client_setup.coffee
- yarn.lock
Blocker: https://github.com/artsy/stitch/pull/13
Fixes import path to our `server` only reference.
> [Stitch] Update import path based on TS refactor

- patches/hard-source-webpack-plugin+0.12.0.patch
- webpack.config.js
Alright, so, I don’t have a full understanding yet of why this happens, what I know is:
* In webpack v3 this class accepted [a list of params](https://github.com/webpack/webpack/blob/v3.12.0/lib/NormalModule.js#L62), which changed in webpack v4 to be [an object of those params](https://github.com/webpack/webpack/blob/v4.0.0/lib/NormalModule.js#L68-L78). We’re still on webpack v3.
* While it’s probably related to that change in webpack, what’s weird is that one may expect then that this would apply to all modules, but the issue only arises for 2 of our modules:
- [`src/desktop/apps/editorial_features/components/gucci/components/series/series_footer.jsx`](https://github.com/artsy/force/blob/60be49cb4bde1828e7158880c85d6b2c1dcc42c3/src/desktop/apps/editorial_features/components/gucci/componen …
> [webpack] Fix bug in our hard-source caching setup.

- package.json
- yarn.lock
https://github.com/DataDog/dd-trace-js/pull/299
> [package] Update dd-trace to use our fork with connection tracing.

- src/mobile/apps/artwork/components/bid/query.coffee
- src/mobile/apps/artwork/components/image/index.styl
- src/mobile/apps/artwork/components/image/templates/index.jade
Adress https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-349
Judging that this info was not even requested on mobile I doubt it was ever displayed there. But now that is. We just have to make sure we keep it in the artwork page redesign:)
> add lot display to mobile version of artwork

- src/desktop/apps/artwork/components/additional_info/index.jade
- src/desktop/apps/artwork/components/artists/index.jade
- src/desktop/apps/artwork/components/auction/view.coffee
- src/desktop/apps/artwork/components/commercial/templates/index.jade
- src/desktop/apps/artwork/components/commercial/templates/inquire.jade
- src/desktop/apps/artwork/components/commercial/templates/price.jade
- src/desktop/apps/artwork/components/commercial/view.coffee
- src/desktop/apps/artwork/components/partner/index.jade
- src/mobile/apps/artwork/components/meta_data/templates/description.jade
- src/mobile/apps/artwork/components/meta_data/templates/inquiry.jade
- src/mobile/apps/artwork/components/meta_data/templates/partner.jade
- src/mobile/apps/artwork/components/meta_data/templates/price.jade
- src/mobile/apps/artwork/components/meta_data/test/template.coffee
- src/mobile/apps/artwork/components/meta_data/view.coffee
- src/mobile/apps/artwork/templates/index.jade
This PR follows up https://github.com/artsy/force/pull/2958 by adding a check for the `ENABLE_NEW_BUY_NOW_FLOW` feature flag everywhere we are currently checking for the lab feature.
Verified locally (desktop + mobile web) with artworks in the following states:
- Gallery artwork enabled for ecommerce
- Auction Partner artwork enabled for ecommerce
- Artwork in an auction enabled for ecommerce + bidding
Once this is merged, we should set the flag to TRUE on staging. Note that if you are logged out, you won't be able to create an order until https://artsyproduct.atlassian.net/browse/PURCHASE-487 is done.
> Use feature flag or lab feature for showing bnmo features

- package.json
- src/desktop/apps/artwork/components/auction/view.coffee
- src/desktop/apps/artwork/components/commercial/view.coffee
- src/desktop/apps/order2/__tests__/routes.jest.js
- src/desktop/apps/order2/server.js
- src/mobile/apps/artwork/components/meta_data/view.coffee
- yarn.lock
This updates force to both send new orders to the `/orders` route _and_ continue to support the existing `/order2` route until we deprecate it completely.
> Updates routing to handle /orders as well as /order2

- src/mobile/analytics/before_ready.js
This is the same analytics code I pushed for desktop [a couple of weeks back](https://github.com/artsy/force/pull/2909). Soon to be deprecated hopefully as we switch to responsive design on the Artwork page!
> add ecommerce artwork pageview tracking to mobile web

- scripts/start.sh
Context https://artsy.slack.com/archives/C2TQ4PT8R/p1539257376000100
Otherwise node will not be able to find the symlinked package’s node_modules directory.
Whoever gets to it first may merge.
> [dev] When symlinking packages, tell node to respect that.

- src/desktop/apps/artwork/components/google/index.jade
- src/desktop/apps/artwork/templates/index.jade
- src/desktop/config.coffee
- src/lib/setup_sharify.js
- src/mobile/analytics/before_ready.js
As with our FB tracking code, this sends a product ID over to Google Ads when users are visiting artwork pages. This is a requirement for retargeting Buy Now works over the Google Ads display network. This is a high priority request from marketing as we've been banned from Criteo and need to use Google as a marketing channel for Buy Now. It takes 24-48 hours for this to start populating pageviews on the Google Ads side.
No additional user data is sent in the request.
I've added the `GOOGLE_ADWORDS_ID` ENV var to staging and production.
> add google ads tracking to artwork pages

- src/desktop/components/artwork_item/templates/artwork.jade
- src/desktop/components/artwork_item/test/artwork.coffee
Kind of a weird one.
Old-school bricks (we only update the new Reaction bricks for badges, etc.) still should work, minimally speaking.
We noticed the above ^ on some of the older pages (partner profile, old collect) for acquireable works.
I think this fix makes sense, and checking a couple examples with this fix, looks good.
> @sweir27 => Fix for Contact GalleryBuy display on older artwork bricks

- Dockerfile
- package.json
- yarn.lock
Which includes https://github.com/artsy/reaction/pull/1400 for passing `oneTimeUse` flag when calling MP to set payment.
Looks like `reaction` [was updated](https://github.com/artsy/reaction/pull/1399) to use node `8.12` but Force is still on `8.11` so ended up updating docker image in `Dockerfile` to `node:8.12.0`, this locally fixes issues and seems fine but not sure how scary of a change is this.
Error in CircleCI:
```
error @artsy/reaction@5.6.3: The engine "node" is incompatible with this module. Expected version "8.12.x". Got "8.11.3"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'force' failed to build: The command '/bin/sh -c yarn install' returned a non-zero code: 1
```
> Update to reaction 5.6.3

- package.json
- src/desktop/analytics/main_layout.js
- src/desktop/apps/artwork/components/auction/test/view.coffee
- src/desktop/apps/artwork/components/auction/view.coffee
- src/desktop/apps/artwork/components/commercial/templates/questions.jade
- src/desktop/apps/artwork/components/commercial/test/view.coffee
- src/desktop/apps/artwork/components/commercial/view.coffee
- src/desktop/apps/order2/client.js
- src/mobile/apps/artwork/components/meta_data/test/view.coffee
- src/mobile/apps/artwork/components/meta_data/view.coffee
- yarn.lock
This PR adds tracking to the Buy Now checkout flow. See PURCHASE-489 for more details and https://github.com/artsy/reaction/pull/1395 for related work in Reaction.
- Added click tracking for "buy now" buttons on artwork page for both desktop and mobile
- Added click tracking for ask a specialist and read FAQ links on artwork page
- Added page view tracking for shipping, payment and review views in buy now checkout flow
- Refactored time on page tracking code into `PageTimeTracker` class
> Add tracking on buy now checkout flow

- package.json
- src/desktop/apps/home/client/setup_home_page_modules.coffee
- src/desktop/components/artwork_metadata_stub/templates/contact.jade
- yarn.lock
The old artwork brick wasn't handling the "buy now" case behind a feature flag. This fixes that.
The updated rail (with multiple brick-types) looks like this:
This also bumps reaction.
> Old artwork brick incorrectly showed "contact gallery" for bnmo works

- webpack.config.js
This reverts some changes from https://github.com/artsy/force/pull/2916, namely caching on our coffee and jade files, as it led to irregular behavior where changes to certain templates weren't being picked up even after server restarts. 
This is due, I believe, to how caching works vs how a lot of our old coffeescript template code is written: 
```coffeescript
template = -> require('path/to/template') args... 
```
Which means that when a dep is changed down the tree, the initial import site isn't invalided as its hidden behind a closure. (Not sure why template imports are written this way since a normal `template = require('path/...')` works fine and is how its commonly done.) 
(This is me speculating, but reverting to how things were fixes the issue with no observable difference in …
> [Toolchain] Revert webpack caching on certain loaders

- package.json
- src/desktop/apps/order2/client.js
- yarn.lock
Since https://github.com/artsy/reaction/pull/1419 we don't open the FAQ in a modal anymore, so there's no need to listen on this event.
> No longer listen on FAQ modal hook

- src/desktop/apps/collect2/server.js
Addresses: https://artsyproduct.atlassian.net/browse/GROW-963
This fixes the weird extra 10px top margin that appears in the mobile view of the collection page.
**Before**
**After**
> @damassi: add classes to fix margin issue

- src/desktop/apps/user/components/delete_my_account/test/view.coffee
- src/desktop/apps/user/components/delete_my_account/view.coffee
Gravity has been updated to send an error message in the client response object when a user account cannot be deleted. 
Now one of the following messages displays depending on the reason why a user cannot delete their account:
1. User recently made an order: **'Sorry, this account cannot be deleted at this time because it is associated with a recent order. Please try again after three months from the purchase date.'**
2. User recently had auction activity: **'Sorry, this account cannot be deleted at this time because it is registered to bid in an ongoing or recently closed auction. Please try again after 48 hours.'**
3. User recently contacted a gallery: **'Sorry, this account cannot be deleted at this time because it is connected to a recent inquiry conversation. Please try again after …
> Displaying error msg declared in Gravity when a user cannot delete own account

- src/test/acceptance/artist.js
- src/test/acceptance/fixtures/metaphysics/artist.json
- yarn.lock
cc @joeyAghion you were interested in this sort of a test (we have a good amount of Reaction coverage for components, and composing the components properly), so this adds a simple integration test in Force.
This was pretty sketchy running on my computer, but then again all of the existing integration tests were as well, but on CI they _seemed_ stable. This did in fact succeed _once_ on my computer, before succumbing to the same crashers that other tests on `master` had locally, so figured worth a PR and see how Circle likes it.
> @damassi => [Testing] Add a basic integration test for the artist page

- src/mobile/apps/artwork/routes.coffee
This fixes https://artsyproduct.atlassian.net/browse/DISCO-440.
During our performance analysis work we noticed that some mobile artwork pages were experiencing really large first meaningful paint times (~40 seconds) due to an image load that was taking ~30 seconds on a regular 3G network. After some investigation I discovered that artworks with multiple images were often pulling in the normalized.jpg rendition of the image which is the largest version of the image that we have stored. This was _significantly_ impacting page performance. 
This update ensures that the `large` image renditions are pulled in instead (which is how the single image setup is already configured).
> Never pull in huge normalized image into the carousel

- src/desktop/apps/sitemaps/routes.coffee
- src/desktop/apps/sitemaps/test/routes.coffee
Fixes https://artsyproduct.atlassian.net/browse/DISCO-441.
Our [robots.txt file](https://artsy.net/robots.txt) has some `Disallow` rules that start with `?`. Lighthouse dings our SEO rating check by 9 points due to this. According to [Google's official docs](https://developers.google.com/search/reference/robots_txt#format-syntax--definition), they expect disallow to start with `/` or `*`.
> Fix lighthouse SEO warnings

- src/mobile/apps/user/routes.coffee
Using https://github.com/jaredhanson/passport/issues/306#issuecomment-419334330 to work around a potential race condition inside of `req.login` and persisting the session, based on the really old version of Passport.js we are using.
Since currently this is reproable on staging, this might work/hold everything over 🤞 while the more proper task of upgrading that dependency is undertaken, since it's possible this bug was actually a real bug and fixed upstream (...years ago 😐 )
> @damassi => Explicitly save the session to avoid possibly race condition in `req.user`

- src/desktop/apps/artwork/components/commercial/view.coffee
- src/mobile/apps/artwork/components/meta_data/test/view.coffee
- src/mobile/apps/artwork/components/meta_data/view.coffee
Tracks successful creation of orders on the client. Resolves [PURCHASE-587](https://artsyproduct.atlassian.net/browse/PURCHASE-587). 
Desktop tests will require a more substantial refactor to be done in a later PR.
> Track successfully created orders

- src/mobile/apps/user/routes.coffee
- src/mobile/components/layout/bootstrap.coffee
The result of `/user/refresh` (and `req.login`, etc.) is that a new cookie is sent to the client, via a `Set-Cookie` header. This, at least within Force, is synchronous, and so shouldn't be subject to some of the race conditions people were experiencing with asynchronous session saving.
However, that got me thinking, we're expecting the result of `/user/refresh` to contain a new cookie that gets set. We're also immediately...leaving the page (by reloading).
Might that cause the browser to sometimes/race-condition not set the cookie? ie- before setting navigation away occurs and it gets flushed.
This just adds a delay of 500ms around the refresh to allow the browser to 'catch up' and set the cookie properly.
> @damassi => Grasping for straws, delay reloading to allow cookie to be set
