artsy/force

cypress/integration/collection.spec.js
Looks like something happened with ES earlier and the artwork grid is empty. 
Quickfix to unblock deploys.
=> quickfix: Disable collections cypress test for now

scripts/start.sh
Per convo the other day, this removes the `--inspect` command from default `yarn start` dev flow, which should improve perf for many on the team developing on less performant computers. 
cc @zephraph
=> toolchain: Remove --inspect from default `yarn start`

src/desktop/apps/user/components/bid_history/view.coffee, src/desktop/components/my_active_bids/query.coffee, src/desktop/components/my_active_bids/view.coffee
Fixes [PURCHASE-2188](https://artsyproduct.atlassian.net/browse/PURCHASE-2188)
The query is the same. I just changed 🐍 -> 🐫  case and `id -> internalID` conversion with aliases. 
`desktop/apps/user/components/bid_history` is also using the same query so moved that to MP V2. So it also fixes [PURCHASE-2184](https://artsyproduct.atlassian.net/browse/PURCHASE-2184)
=> chore: Move my_active_bids and bid_history to MP V2

package.json, yarn.lock
The `electron` dependency is a transitive dependency of `nightmare` we
do not need to manually include it.
=> chore: Remove electron dependency

src/desktop/apps/auction/components/Layout.tsx, src/desktop/apps/auction/components/layout/auction_info/AuctionInfoDesktop.tsx, src/v2/Components/AddToCalendar/AddToCalendar.tsx, src/v2/Components/AddToCalendar/__tests__/AddToCalendar.jest.tsx, src/v2/Components/AddToCalendar/__tests__/helpers.jest.ts, src/v2/Components/AddToCalendar/helpers.ts
Follow up to #6639, track clicks on add to calendar component.
Addresses  https://artsyproduct.atlassian.net/browse/AUCT-725
- track clicks in `AddToCalendar` component
- add tracking context to auction app
- add analytics context props to auction app
=> HACK-8: track add to calendar clicks

docs/best_practices.md
Adds some documentation around Force best practices. (h/t to Eigen's docs for providing some of the structure here.) 
I tried to keep things to point and current, but I am very likely missing stuff -- thoughts? 
Note that this is something of a launch point for adding more detail in our currently-stubbed-out [playbook](https://www.notion.so/artsy/Frontend-f7946aca868842ad8e758809826b558e). 
Tagged a few folks with extensive force experience for feedback, but if you feel someone else might have more ideas please tag them as well 🙏
=> docs: Add best practices documentation

src/v2/Apps/Artists/ArtistsApp.tsx, src/v2/Apps/Artists/Components/ArtistsArtistCard.tsx, src/v2/Apps/Artists/Components/ArtistsByLetterMeta.tsx, src/v2/Apps/Artists/Components/ArtistsCarouselCell.tsx, src/v2/Apps/Artists/Components/ArtistsIndexMeta.tsx, src/v2/Apps/Artists/Components/ArtistsLetterNav.tsx, src/v2/Apps/Artists/Components/ArtistsTopNav.tsx, src/v2/Apps/Artists/Routes/ArtistsByLetter.tsx, src/v2/Apps/Artists/Routes/ArtistsIndex.tsx, src/v2/Apps/Artists/__tests__/ArtistsArtistCard.jest.tsx, src/v2/Apps/Artists/__tests__/ArtistsByLetter.jest.tsx, src/v2/Apps/Artists/__tests__/ArtistsIndex.jest.tsx, src/v2/Apps/Artists/artistsRoutes.tsx, src/v2/Apps/getAppRoutes.tsx, src/v2/Artsy/Router/RouterLink.tsx, src/v2/Components/FollowButton/FollowArtistButton.tsx, src/v2/__generated__/ArtistsArtistCard_Test_Query.graphql.ts, src/v2/__generated__/ArtistsArtistCard_artist.graphql.ts, src/v2/__generated__/ArtistsByLetterQuery.graphql.ts, src/v2/__generated__/ArtistsByLetter_Test_Query.graphql.ts, src/v2/__generated__/ArtistsByLetter_viewer.graphql.ts, src/v2/__generated__/ArtistsCarouselCell_featuredLink.graphql.ts, src/v2/__generated__/ArtistsIndexFragmentContainer_Test_Query.graphql.ts, src/v2/__generated__/ArtistsIndex_featuredArtists.graphql.ts, src/v2/__generated__/ArtistsIndex_featuredGenes.graphql.ts, src/v2/__generated__/FollowArtistButtonQuery.graphql.ts, src/v2/__generated__/artistsRoutes_ArtistsByLetterQuery.graphql.ts, src/v2/__generated__/artistsRoutes_ArtistsQuery.graphql.ts
Closes: [FX-2513](https://artsyproduct.atlassian.net/browse/FX-2513)
This exposes the new artists index under the `/artists2` and `/artists2/artists-starting-with-:letter` routes. Once we have [pagination with real hrefs](https://artsyproduct.atlassian.net/browse/GRO-7) we'll be able to launch this under the proper path.
<del>Will move this off draft when https://github.com/artsy/metaphysics/pull/2842 is in production.</del>
=> feat(fx-2513): implements artists index

.vscode/settings.json
Follows recent change in MP: https://github.com/artsy/metaphysics/pull/2847
VSCode made a change recently where installing prettier-vscode isn't enough, one has to also set the formatter. This has caused a lot of confusion recently with @mzikherman, [see here](https://artsy.slack.com/archives/CP9P4KR35/p1606174797182000) for example, and @williardx got snagged by this too, as well as myself, which took a long time to track down. (This only recently started happening with newish vscode update.)
For those who would like to **not** autoformat their code while developing (which is rare) and instead rely on githooks when committing this can be locally disabled by updating `user` and `workspace`. cc/ @icirellik:
=> chore: Fix prettier formatter

src/novo/src/index.ejs, src/v2/Components/Authentication/Desktop/ModalManager.tsx, src/v2/Utils/ReCaptchaContainer.tsx
Only load recaptcha if the user is about to do an action that requires
it, such as authentication.
Backwards compatible with current pages.
=> feature: Lazy Load ReCaptcha

src/v2/Apps/Collect/Routes/Collect/index.tsx, src/v2/Apps/Collect/Routes/Collections/index.tsx
Addresses https://artsyproduct.atlassian.net/browse/GRO-25
Re-adds the "View collections" link to `/collect` and makes consistent with associated link on `/collections` 
=> feat: [Collect] Add collections link to header

src/v2/Apps/getAppNovoRoutes.tsx
No need to use cloneDeep, which will clone the whole tree, when we just need to assign a new path one level deep and shallowly copy other props.
=> fix: [Novo] Remove clone deep on routes

src/v2/Apps/Artists/Routes/ArtistsByLetter.tsx, src/v2/Apps/Artists/artistsRoutes.tsx
Closes: [FX-2527](https://artsyproduct.atlassian.net/browse/FX-2527)
Makes more sense to handle the 404 in the routes regardless. Handling it in the component like this was causing match to be undefined in the component, which, to me seems like a bug in the `useRouter` hook; though that's going unexamined for now (or is possibly reflected in the typings but I don't notice because of the non-strict null checking).
=> fix(fx-2527): handles 404 in routes

.eslintrc.js, package.json, yarn.lock
Closes: [FX-2515](https://artsyproduct.atlassian.net/browse/FX-2515)
Since eslint only runs on commits, it seems fine to enable this with the defaults and just fix issues as they crop up.
=> chore(fx-2515): installs/enables eslint jest plugin

package.json, yarn.lock
We use formik in many places, but rely on it via reaction's dependencies. This pr adds to force's dependencies so we can easily change the version, as well as drop the lib from reaction.
Should be merged before: https://github.com/artsy/reaction/pull/3665
=> Add formik to dependencies

CONTRIBUTING.md, package.json, scripts/pull-lock.sh
This adds a new check to our `post-merge` githook that will check to see if `DISABLE_PULL_LOCK=true` is set in `.env`, and if so, skip running the command. 
Also updates docs around using `HUSKY_SKIP_HOOKS=1` to skip git hooks.
=> toolchain: Add conditional check to run pull-lock and update docs around skipping husky

package.json, src/novo/src/index.ejs, src/novo/src/server.ts, webpack/envs/clientNovoDevelopmentConfig.js, webpack/envs/clientNovoProductionConfig.js, yarn.lock
Automatically inject all chunks using the `html-webpack-plugin`. This
will allow us to iterate on chunk heuristics without needing to update
templates.
The ejs template is compiled once by Webpack to inject chunks and a
second time during rendering to inject dynamic variables.
=> feature: EJS Inject Chunks Automatically

src/novo/src/client.tsx
This wasn't turned on before, which led to full-page reloads whenever client-side changes were made. We needed to add 
```tsx
if (module.hot) {
module.hot.accept()
}
```
to our root `client.tsx` file. Now hot reloading is enabled throughout the entire client-side tree. 
Notice that after the change is made, the console fully clears -- thats because the page has done a full reload and stuff isn't hot-reloaded.
Now, after a change, the console is appended to and things are hot-reloaded successfully. No full page restart necessary.
=> fix: enable client-side-hot-reload

src/v2/Apps/Artwork/Components/ArtworkDetails/index.tsx
Add a `white-space: pre-wrap` style certain Box elements on the artworks detail page.
**Before:**
-----------
**After:**
-----------
**CMS:**
=> bug: Add white-space: pre-wrap style to artwork details, exhitibion history, literature, and provenance

data/schema.graphql, src/v2/Apps/Artist/Components/ArtistCollectionsRail/index.tsx, src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/ArtistConsignHeaderImages.tsx, src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignMeta.tsx, src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx, src/v2/Apps/Artist/Routes/Consign/Components/__tests__/ArtistConsignMeta.jest.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/SoldRecently.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SoldRecently.jest.tsx, src/v2/Apps/__tests__/Fixtures/Artist/Routes/ConsignRouteFixture.ts, src/v2/__generated__/ArtistConsignHeaderImages_artist.graphql.ts, src/v2/__generated__/ArtistConsignMeta_artist.graphql.ts, src/v2/__generated__/ArtistConsignRecentlySold_artist.graphql.ts, src/v2/__generated__/ConsignRoute_Test_Query.graphql.ts, src/v2/__generated__/SoldRecentlyQuery.graphql.ts, src/v2/__generated__/SoldRecently_targetSupply.graphql.ts, src/v2/__generated__/SoldRecently_tests_Query.graphql.ts, src/v2/__generated__/routes_ArtistConsignQuery.graphql.ts
https://artsyproduct.atlassian.net/browse/GRO-54
Related Metaphysics PR: https://github.com/artsy/metaphysics/pull/2871
We want to show users the value of consigning on Artsy by showing positive outcomes for works sold on Artsy. To do this, we want to show the ratio of the realized price to the estimate for a work.
Add `realizedToEstimate` field on the `Artwork` type in Metaphysics and then display in Force.
As part of this work we refactored the `ArtistTargetSupplyMicrofunnel` type and related code in Metaphysics to only use `artworksConnection` instead of a separate `artworks` field. This PR continues that refactor and converts existing views that rely on `artworks` to only use `artworksConnection`.
This change is tightly coupled to changes in Metaphysics and will result in a small …
=> Refactor consign pages to use artworksConnection and add realized / estimate price multiplier to /consign recently sold artworks

.eslintrc.js, package.json, yarn.lock
This is leading to too much churn in our diffs, and attempting to fix everyting at once [here](https://github.com/artsy/force/pull/6827) mysteriously blows up our tests. Until https://github.com/artsy/force/pull/6827 can be fixed, just gonna opt to remove this plugin.
=> fix: Remove eslint object sort plugin

src/v2/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
*had to duplicate this PR because I initially made it from my fork*
The current language for COAs that appears on the artwork page defines a COA as a signed document, and while this is best practice, there are some rare exceptions where a COA is not signed, but is from an authoritative body.
We want to allow for this exception (though not encourage it) to avoid confusion on the part of collectors.
Request:
Amend the first sentence of the langue to remove "signed," so that it will read: "A certificate of authenticity (COA) is a document from an authoritative source that verifies the artwork’s authenticity."
[PURCHASE-2254]: https://artsyproduct.atlassian.net/browse/PURCHASE-2254
=> Update COA language on artwork page

src/v2/Components/NavBar/NavItem.tsx
Fixes https://github.com/artsy/force/issues/6817
This PR changes the `focus` selector to `focus-visible` for the `HitArea` in `NavItem` to make the navigation items visually consistent and prevent the black bottom border from being visible when a user clicks on an item.
=> fix: use focus visible selector in nav items

cypress/integration/partnerProfile.spec.js, src/lib/scriptLoader.ts
The Novo script loader only works for inline source.
=> fix: Novo Script Loader

src/desktop/lib/global_client_setup.tsx, src/lib/setupSentry.ts, src/v2/Artsy/Router/Boot.tsx
Use the `beforeSend` callback to filter and drop unwanted errors.  WIP.
=> #DRAFT feat: filter sentry errors

src/v2/Apps/Fair/Routes/FairArticles.tsx, src/v2/Apps/Fair/Routes/__tests__/FairArticles.jest.tsx, src/v2/Apps/Fair/fairRoutes.tsx, src/v2/__generated__/FairArticles_Test_Query.graphql.ts, src/v2/__generated__/FairArticles_fair.graphql.ts, src/v2/__generated__/fairRoutes_FaiArticlesQuery.graphql.ts
Re: [FX-2508](https://artsyproduct.atlassian.net/browse/FX-2508)
This isn't meant to close the ticket, but rather just merge something that @artsy/design can look at on staging. There's some display corner cases that I didn't handle, but will once the layout is final.
Some notes:
* The “Articles” header text size is outside of the design system. According to the initial typographic guidelines, these instances should probably be reserved for bespoke editorial content.
* We don’t store thumbnail dimensions for article thumbnails. Due to this we can only display thumbnails with a specific aspect ratio crop
* This makes the masonry weird because of how it looks with uniform content, ie: the masonry will try to lay out thumbnails in strange fashions when everything is even (like 2 even rows, …
=> feat(fx-2508): roughs in fair articles route

scripts/smoke_test.sh
We spend several seconds on each cypress test run waiting for the server
to start. Let's use this time to begin downloading an installing cypress.
=> feature: Smoke Test Order

src/v2/Apps/Collect/Routes/Collection/index.tsx
The `artworksConnection` can sometime be null. This is one of the reasons
that collection specs have been failing periodically.
=> fix: Collection Artwork Aggregations

CONTRIBUTING.md
Recaptcha key is required in local environments for authentication against staging, following https://github.com/artsy/gravity/pull/13456
Related thread: https://artsy.slack.com/archives/CP9P4KR35/p1609791118006600
=> Add recaptcha key to local auth instructions

package.json, src/v2/Apps/Artist/Routes/Articles/__tests__/Articles.jest.tsx, src/v2/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.jest.tsx, src/v2/Apps/Artist/Routes/Shows/__tests__/Shows.jest.tsx, src/v2/Apps/Artist/Routes/Works/__tests__/Works.jest.tsx, src/v2/Apps/Artists/__tests__/ArtistsByLetter.jest.tsx, src/v2/Apps/Purchase/Components/PurchaseHistory.tsx, src/v2/Apps/Purchase/__tests__/PurchaseApp.jest.tsx, src/v2/Apps/Search/Routes/Artists/__tests__/SearchResultsArtists.jest.tsx, src/v2/Apps/Search/Routes/Entity/__tests__/SearchResultsEntity.jest.tsx, src/v2/Components/Pagination.tsx, src/v2/Components/Pagination/__mocks__/useComputeHref.ts, src/v2/Components/Pagination/index.tsx, src/v2/Components/Pagination/useComputeHref.ts, src/v2/Components/v2/ArtworkFilter/Utils/urlBuilder.tsx, src/v2/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx, yarn.lock
Sibling here: artsy/force#6832
This work started as a collab with @damassi and he's graciously offered to help get it over the finish line. What we did was run force and palette locally with the latter linked to the former. That allowed us to tinker with the contract between force's pagination wrapper and the large/small components in palette.
Our approach to getting hrefs populated has been to pass a function called `getHref` that can collaborate with the url builder helper function in force. That allows us to have each pagination link set the page number but also not break any existing filtering or whatever.
This worked great for the individual page number links, but not quite for the prev/next buttons and I have not been able to get to the small breakpoint to see about how things work …
=> Improve pagination with hrefs

src/v2/Apps/Artist/Routes/Articles/ArtistArticles.tsx, src/v2/Apps/Artist/Routes/Shows/ArtistShows.tsx, src/v2/Apps/Artists/artistsRoutes.tsx, src/v2/Apps/Search/searchRoutes.tsx, src/v2/Components/Pagination/useComputeHref.ts, src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
Quick fix for https://github.com/artsy/force/pull/6832.
Noticed that we were operating on a react context that doesn't exist, when using `<Pagination>` outside of an ArtworkFilter context. 
Most of the pages this applied to are actually old / hidden, so impact of bug not that wide, but it also raises the issue of making deep link href-based pagination work on components that aren't within the artwork filter (there are a few). The only reason this worked at all initially is because we build deep-linking into the artwork filter independent of pagination -- so wiring pagination into that was pretty seamless. Same can't be said about other components, however.
=> bugfix: Fix pagination bug with non-artworkgrid components

src/desktop/apps/articles/client/magazine.coffee, src/desktop/apps/articles/routes.ts, src/desktop/apps/articles/templates/full_feed.jade, src/desktop/apps/articles/test/templates.test.js, src/mobile/apps/articles/client/articles.coffee, src/mobile/apps/articles/routes.coffee, src/mobile/apps/articles/templates/articles_feed.jade, src/mobile/apps/articles/test/routes.test.js, src/mobile/apps/articles/test/templates.test.js
We're going to be putting News on hiatus for the time being so this PR disables the news feed on the editorial landing pages.
<details>
<summary>before/after screenshots</summary>
</details>
https://artsyproduct.atlassian.net/browse/GRO-145
=> feat: Disable news on editorial landing page

src/desktop/apps/user/pages/settings/index.jade, src/desktop/components/react/stitch_components/index.tsx, src/v2/Components/UserSettings/UserEmailPreferences/UserEmailPreferencesMutation.tsx, src/v2/Components/UserSettings/UserEmailPreferences/index.tsx, src/v2/Components/UserSettings/UserInformation/index.tsx, src/v2/__generated__/UserEmailPreferencesMutation.graphql.ts, src/v2/__generated__/UserEmailPreferencesQuery.graphql.ts
This PR updates Force to use the email_frequency field on a user when updating their email preferences.
<details>
<summary>some screenshots</summary>
</details>
I worked pretty closely with @damassi on this so big thanks to him but I also brought this to a front-end practice office hours and got some great direction from @zephraph and @mdole so thanks to them as well.
Note: here's the tech plan - https://www.notion.so/Simplify-email-preferences-1cd2f7c320674032a1e3c0c73a19c54f and this is Milestone 4, the next one will see me deleting the legacy fields I cannot wait.
https://artsyproduct.atlassian.net/browse/GRO-133
=> feat: Simplify user email preferences

src/novo/src/index.ejs
This change adds preloading for the dynamically generated novo chunks
which has become necessary because the scripts must be included after
the react dom has been served to avoid visual glitches during rehydration.
=> feature: NOVO Chunk Preload

src/v2/Apps/Search/Components/NavigationTabs.tsx, src/v2/Apps/Search/searchRoutes.tsx
Fixes https://artsyproduct.atlassian.net/browse/GRO-143 
Noticed recently that the tabs were doing full page hard reloads when clicked. This fixes that, while getting around a (seeming) limitation in found around `<RouterLink to='/some-path?with=params'>`; I've got a message out to the author about it, but in the meantime. 
=> bugfix: Fix hard reload on search tabs

src/desktop/apps/page/routes.coffee, src/desktop/apps/page/test/routes.test.js
https://artsyproduct.atlassian.net/browse/GRO-123
Our `collector-faqs-selling-on-artsy` page ranks well on relevant Googles search queries but isn't a great user experience. We'd like for collectors who are searching for this information to go to `/consign` instead.
301 redirect `/page/collector-faqs-selling-on-artsy` to `/consign`.
=> feat: Redirect collector selling FAQ to /consign

src/lib/__tests__/setupSentry.jest.ts, src/lib/setupSentry.ts
Follow up to #6823, allow filtering which errors are sent to Sentry using a list of omitted errors.
=> Sentry error handling can match on multiple errors

src/lib/setupSentry.ts
Follow up to #6896, return `null` explicitly when ignoring errors.
=> bugfix: Return null when ignoring segment errors

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx
This is the first V2 app migration to the new minimal template and 
migrates: `/collections`, `/collect`, and `/collection`.
The migration is relatively straightforward and only requires a few steps
which are outlined below. There is one minor concern to be aware
of, the simplest migration (outlined below) moves all routes in a route
config for most pages I don't expect this to be an issue. However, when
migrating more complex pages would be possible to break the route
config apart to reduce the scope of the migration.
Review app ([here](https://novo.artsy.net))
* `/collections` ([here](https://novo.artsy.net/collections))
* `/collection` ([here](https://novo.artsy.net/collection/abstract-expressionism-works-on-paper))
* `/collect` ([here](https://novo.artsy.net/collect))
* …
=> feature: Convert Collection Routes

src/v2/Components/Search/SearchBar.tsx
Closes: [FX-2591](https://artsyproduct.atlassian.net/browse/FX-2591)
I noticed this bug this morning when trying to use the mobile site. The go button (which in mobile Safari simulates `<enter>`) clears the input without searching.
This was introduced here as a feature not a bug: https://github.com/artsy/reaction/pull/3217
I think it makes sense not to clear the input because frequently one wants to edit the query to refine it — this is a pretty common pattern in most searches/search engines. I couldn't find any specific accessibility guidelines on this particular point, but it makes an intuitive kind of sense. So this PR just disables the clearing of the input, rather than fixing the submission with the addition of the input clear.
We also already populate the query when linking to …
=> fix(search): removes input clear after search

src/v2/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/Modal.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Modal.tsx
This follow up https://github.com/artsy/gravity/pull/13762 🔒 to expose back-end errors in the 2FA-enabling UI.
This doesn't break existing tests but could use a new one, hence "draft." I'm diving into the tests next, but could use a little help with that.
Looks like:
=> Present API errors upon enabling second factors

src/v2/Components/UserSettings/UserInformation/index.tsx
We observed some email changes reaching the API _without_ the required password verification. This ended up being due to 2 possible conditions:
* the email mismatch is due to capitalization/normalization (fixed in https://github.com/artsy/gravity/pull/13776), and
* the email was being updated back to its original value at page-load
This change [that you suggested] mostly fixes the 2nd case. There's still a race condition somewhere that might allow form submission without a password prompt, but I couldn't reproduce it consistently.
https://artsyproduct.atlassian.net/browse/PLATFORM-3106
=> Correctly prompt for password when updating email, even to original value

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/Show/Components/ShowInstallShots.tsx, src/v2/Apps/Show/showRoutes.tsx, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx
This changed migrates the following routes: `/show/:slug`,
`/show/:slug/info`, and `/show/:slug/hours`.
Review app ([here](https://novo.artsy.net))
* `/show/:slug` ([here](https://novo.artsy.net/show/ross-sutton-gallery-black-voices-friend-of-my-mind))
* `/show/:slug/info` ([here](https://novo.artsy.net/show/ross-sutton-gallery-black-voices-friend-of-my-mind/info))
=> feature: Convert Show Routes

src/lib/middleware/__tests__/sharifyLocals.jest.ts, src/lib/middleware/locals.ts, src/lib/middleware/sharifyLocals.ts
Page performance data all arrived with the `device-type:desktop` tag once `/collect*` pages were switched to the novo template (https://github.com/artsy/force/pull/6905). It's helpful to [continue to] distinguish mobile performance data, since we're targeting mobile specifically and expect any improvements to be pronounced there.
I followed the pattern in https://github.com/artsy/force/pull/6917 and confirmed locally that the performance data is sent with either `device-type:mobile` or `...:desktop`. Added some tests while I was there.
Let me know what I'm missing!
=> Set IS_MOBILE in common middleware, so page-load tracking can use it

src/desktop/components/main_layout/footer/template.jade
Fixes issue where SSR errors were being masked by `stitch` being undefined.
=> Ensure stitch exists before attempting to use when stitching in footer

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/ArtistSeries/artistSeriesRoutes.tsx, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx
This change migrates the following routes: `/artist-series/:slug`
Review app ([here](https://novo.artsy.net))
* `/artist-series/:slug` ([here](https://novo.artsy.net/artist-series/damien-hirst-butterflies))
=> feature: Convert Artist Series

src/common-middleware.ts, src/desktop/apps/artsy-v2/apps/artwork/artworkClient.tsx, src/desktop/apps/artsy-v2/server.tsx, src/desktop/components/inquiry_questionnaire/index.coffee, src/desktop/components/view_in_room/index.jade, src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/Artwork/ArtworkApp.tsx, src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx, src/v2/Apps/Artwork/Components/legacyCSS.js, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx, src/v2/Utils/ReCaptchaContainer.tsx
This PR unblocks and migrates `/artwork` to our new novo page template. A couple things are happening:
- We lazy loading artwork page JS on client-side mount (there's a few different features here) 
- We inject legacy component css into the head on mount, and then remove it when component unmounts
We could optimize this a bit where we only load certain legacy artwork JS on button click, but will save that for a follow-up. For right now this is just getting everything working, using code as it already exists. At the worst, it won't be any slower than things were -- but it will probably be faster, because of new novo shell, and because we're lazy loading legacy js / css and webpack is splitting out a new chunk based on dynamic import, so things aren't tied to artwork bundle.
=> NOVO: Lazy load old legacy artwork page components 

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx, src/v2/Artsy/Router/Utils/shouldUpdateScroll.tsx
This was prompted by some [failures by integrity 🎉 ](https://artsy.slack.com/archives/C9YNS4X32/p1611868909222400), as well as a blind spot in our work.
We've been converting routes over to use the new novo template, which has been pretty straightforward. However, when converting the artwork page we ran into an error due to how we use 
```tsx
router.push('/orders/foo')
```
during BNMO interactions. 
Since the order app hadn't been moved yet, one can't push to a route that doesn't exist. This didn't come up before because in most places we use `<RouterLink to='/some-path'>` which has a fallback to a regular link if a route isn't found, performing a hard jump. This isn't the case with `router.push`. 
Doing a quick search around force, we don't use this function much outside of artwork / …
=> novo: Convert /orders routes

src/desktop/lib/webpackPublicPath.ts
This files was missed as part of the revert due to how git handles
modified files.
=> revert: Missed Artwork Files

src/desktop/apps/home/templates/index.jade, src/mobile/apps/home/templates/page.jade
It took a little investigation but I found the couple places where we draw the homepage and used what I think are the common practices to get something into the head of JUST the homepage.
So then I basically just copy/pasted from the Jira ticket and discovered that in Jade you have to do `|` in order to get this to work so I added that.
There's duplication here but it doesn't really offend me too much - happy to extract if there's a good pattern too. 🤷 
https://artsyproduct.atlassian.net/browse/GRO-24
=> chore: Add organizational structured data

src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx, src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.jest.tsx, src/lib/middleware/sharifyLocals.ts, src/typings/sharify.d.ts
This PR adds an `IS_GOOGLEBOT` boolean to our global data and then uses it to disable infinite scroll on news pages for Googlebot. I did some quick research and it appears `Googlebot` is the user agent to look for but wanted to ping @joeyAghion in case he has any info about this. Otherwise I think this is pretty good to go but it almost seems too easy - am I missing something? Also pretty hard to test this, I wonder how I will know if this fixes the problem? 🤔 
https://artsyproduct.atlassian.net/browse/GRO-63
=> feat: Disable infinite scroll on news page for googlebot

src/v2/Components/Footer.tsx
Quick fix to add the iOS app badge to the desktop footer since https://github.com/artsy/force/pull/6941 inadvertently did not include it.
=> fix: Add download iOS app badge to desktop footer

src/desktop/apps/page/routes.coffee
Discovered today that `Page`s at the `/page/:id` route were not rendering properly.
Turns out it's due to a recent change that removed some necessary indentation from the routes file. (CoffeeScript! :shakes_fist: 😄)
This should fix it!
=> Fix CoffeeScript issue so "Page"s will render

src/v2/Apps/Collect/Routes/Collect/Components/CollectMediumMetadata.ts
This PR addresses [FX-2486](https://artsyproduct.atlassian.net/browse/FX-2486)
**Description:**
This PR adds new options to a snippet of code on the `/collect` app that populates the `<title>` tag and a `<meta name="description">` tag with content to match the media type filter that is selected. I believe that this work will help crawlers better index the filtered pages for "Ephemera or Merchandise" and "Reproductions."
=> chore: update description meta tag for new media type filters on collect page

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx
Could it be that simple?
* `feature/:slug` [link](https://novo.artsy.net/feature/alserkal-art-week)
=> Convert /feature/* pages to novo template

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx
Like https://github.com/artsy/force/pull/6971, but for the `/art-fairs` page and the `/fairs` route that redirects to it.
This is independent from the other route conversions, and can be merged later or as part of a separate release if it helps for tracking or risk-mitigation.
I created a new [ticket](https://artsyproduct.atlassian.net/browse/PLATFORM-3126) for this since it's separate from the other fair-related routes.
=> Convert fairs routes to novo template

src/desktop/apps/authentication/__tests__/routes.jest.ts, src/desktop/apps/authentication/components/meta.tsx, src/desktop/apps/authentication/routeHelpers.ts, src/desktop/apps/authentication/routes.ts
This PR updates our auth pages to include canonical links per the recommendations from DeepCrawl. It closes that Jira ticket.
In order to do this, I followed the pattern I established in #6969 and updated each auth handler to declare the canonical path and then passed it down the stack. I found the meta component and added an optional canonical string property. That property, if present will draw the link tag and tell Google that the auth page is for real.
Looking at this `computeStitchOptions` with fresh eyes this morning I realized that I was breaking a best practice that @damassi is really good at reminding me of: positional arguments are fragile, prefer an object as a function's argument. So I started down that path first and then pushed some more stuff down. That left me with just …
=> feat: Add canonicals to auth paths

src/v2/Apps/Collect/Routes/Collect/index.tsx, src/v2/Apps/Collect/collectRoutes.tsx
Addresses: 
- https://artsyproduct.atlassian.net/browse/GRO-187 
- https://artsyproduct.atlassian.net/browse/GRO-184
This updates our URL structure for /collect to support direct url based color queries:
Example:
```
/collect/color/red
```
Once the client mounts things will convert into conventional query param for now, changing little of the underlying structure as FX is about to start a lot of work around filter architecture. 
=> feat: [SEO] Update /collect to support /color/red style url structure

src/desktop/apps/unsubscribe/index.coffee
This is a subtask of the ticket [GRO-181].
After updating the unsubscribe redirect to `user/edit` it was noted that the redirect does not point users to an area with email unsubscription. Seemed to be in best interest for us to anchor that to the `Email Preferences` section to better point the user in the area of their email preferences and the ability to unsubscribe.
[GRO-181]: https://artsyproduct.atlassian.net/browse/GRO-181
=> (GRO-188): Updated unsubscribe redirect to anchor tag to Email Preferences

src/desktop/apps/auctions/templates/meta.jade
Addresses https://artsyproduct.atlassian.net/browse/GRO-176 
Adds a meta description to /auctions pages (old, non-react section of the app).
@artsy/grow-devs
=> feat: [SEO] Add /auctions meta description text

src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
This follows up https://github.com/artsy/force/pull/6993 which switched `/viewing-room*` routes to use the novo template. [Integrity caught](https://app.circleci.com/pipelines/github/artsy/integrity/5570/workflows/ce8745f6-130b-475d-8bb6-6d99829f71e8/jobs/26893) that the registration prompt wasn't consistently appearing on viewing room pages.
The issue seems related to `ModalContainer` not being mounted when `open:auth` is triggered, as is already [mentioned in a comment](https://github.com/artsy/force/blob/dae1001ce074dbccedcc909fa82917adac2fbca1/src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx#L33-L34). Deferring the event for another second worked locally.
Apologies to future developers encountering this work-around. It may be gross, but at least it's green.
Related aborted revert: …
=> Defer openAuthModal call to avoid apparent race condition

src/lib/mediator.ts, src/v2/Apps/Artist/Components/__tests__/ArtistHeader.jest.tsx, src/v2/Apps/Artwork/Components/ArtworkDetails/__tests__/RequestConditionReport.jest.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarArtists.jest.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx, src/v2/Apps/Artwork/Components/__tests__/ArtistInfo.jest.tsx, src/v2/Apps/Collect/Routes/Collection/Components/Header/__tests__/Header.jest.tsx, src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx, src/v2/Components/Artwork/SaveButton/__tests__/SaveButton.jest.tsx, src/v2/Components/FollowButton/__tests__/FollowArtistButton.jest.tsx, src/v2/Components/FollowButton/__tests__/FollowProfileButton.jest.tsx, src/v2/Components/NavBar/__tests__/NavBar.jest.tsx, src/v2/Components/__tests__/ArtistCard.jest.tsx, src/v2/Utils/__tests__/openAuthModal.jest.ts, src/v2/Utils/openAuthModal.ts
Adds the ability to check if an event handler has been registered and
enhances the auth modal to wait for the listener if it hasn't been
attached yet.
=> feature: Registered Event Handlers

src/v2/Components/Search/SearchBar.tsx
Quick fix to force a hard reload when enter is press after typing into
the search box.
=> fix: Nagivate to Search on Enter

src/v2/Apps/Artwork/artworkRoutes.tsx, src/v2/Apps/Auction/auctionRoutes.tsx, src/v2/Apps/Consign/consignRoutes.tsx, src/v2/Apps/Debug/debugRoutes.tsx, src/v2/Apps/Feature/featureRoutes.tsx, src/v2/Apps/FeatureAKG/featureAKGRoutes.tsx, src/v2/Apps/IdentityVerification/identityVerificationRoutes.tsx, src/v2/Apps/Order/orderRoutes.tsx, src/v2/Apps/Purchase/purchaseRoutes.tsx
Removes and old lint rule ignore that is currently invalid because hte
plugin is no longer installed.
=> chore: Remove Invalid Lint Rule Ignore

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx
This change converts the `/user/purchases` routes to the NOVO template.
=> feature: Convert User Purchase Routes

src/desktop/apps/personalize/index.coffee, src/desktop/apps/personalize/routes.js, src/desktop/apps/personalize/test/routes.jest.ts
While tinkering with the onboarding code I noticed that the behavior to redirect wasn't working the way I expected. After some intense debugging in #dev-help (https://artsy.slack.com/archives/CP9P4KR35/p1613144682324000) it was discovered that artsy/passport was to blame. I opened artsy/artsy-passport#159 to remove that responsibility from that auth package.
So then this is the second part - this PR centralizes all the routing around `/personalize`. I have added some missing tests and did some extraction to make working with this part of the code a little nicer.
/cc @artsy/grow-devs @dzucconi @joeyAghion
=> fix: Improve onboarding routing

src/v2/Apps/Order/Routes/Shipping/index.tsx, src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
Problem:
When selecting a saved address the mutation was sending selected phone number along with the [shipping parameters](https://github.com/artsy/force/compare/sepans/fix-offer-checkout?expand=1#diff-1dc017ef4cac0c540b70784941eb16550eb06b8a495ad12edc5061812e14d9efR580) but not as the root `phoneNumber` param. Instead, it was trying to get it from the form which was empty.
Solution:
When not 'creating a new address', use the saved phone number
=> bugfix: send selected saved phone number to mutation

src/desktop/apps/user/index.coffee, src/desktop/components/react/stitch_components/index.tsx, src/v2/Apps/Payment/Routes/Payment/PaymentApp.tsx, src/v2/Apps/Payment/__tests__/PaymentApp.jest.tsx, src/v2/Apps/Payment/paymentRoutes.tsx, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/__generated__/PaymentApp_Test_Query.graphql.ts, src/v2/__generated__/PaymentApp_me.graphql.ts, src/v2/__generated__/paymentRoutes_PaymentQuery.graphql.ts
[PURCHASE-2434]
This new app ultimately going to replace the `/user/payments` stitched component
For now, it creates the app skeleton. After we add the saved shipping addresses to it we will remove the old route and update the route to `/user/payments`
I assume adding  it to Novo routes is how we should add apps now  cc: @icirellik 
The stitched version (old):
The app (new):
</details>
TODO:
[PURCHASE-2434]: https://artsyproduct.atlassian.net/browse/PURCHASE-2434
=> feat: Add new payment app to replace stitched user payments tab

src/v2/Apps/Order/Components/AddressModal.tsx, src/v2/Apps/Order/Mutations/CreateUserAddress.ts, src/v2/Apps/Order/Mutations/SetShipping.ts, src/v2/Apps/Order/Mutations/UpdateUserAddress.ts, src/v2/Apps/Order/Routes/Shipping/index.tsx, src/v2/Apps/Order/Routes/__fixtures__/MutationResults/saveAddress.ts, src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx, src/v2/Apps/Order/Routes/__tests__/__snapshots__/Shipping.jest.tsx.snap, src/v2/Apps/Order/Utils/shippingAddressUtils.ts, src/v2/__generated__/CreateUserAddressMutation.graphql.ts, src/v2/__generated__/SetShippingMutation.graphql.ts, src/v2/__generated__/UpdateUserAddressMutation.graphql.ts
Follow up to https://github.com/artsy/force/pull/7037 @damassi caught a problem that the module/file names are not consistent 🙌🏽 
Corrected the mutation module file names to match and make them consistent. The diff looks a bit crazy but basically, I did these changes to mutation files in `src/v2/Apps/Order/Mutations`:
```
ShippingCreateUserAddress -> CreateUserAddress
ShippingOrderAddressUpdate -> SetShipping
AddressModal -> UpdateUserAddress
```
The rest is updating references.
=> Correct mutation file/module names to match

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PartnerAutosuggest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PartnersFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/PartnerAutosuggest.jest.tsx
Uses the `react-autosuggest` lib, I figure this might be good enough to merge and iterate on the behavior. This combined galleries/institutions filter itself is behind a feature flag, so should be safe to merge.
=> feat: add galleries/institutions auto-complete for filter

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/Apps/getAppRoutes.tsx
This change converts the `/identity-verification` routes to the NOVO template.
=> feature: Convert Identity Verification Routes

src/desktop/apps/article/components/App.tsx, src/desktop/apps/articles/templates/articles.jade
This is for ticket [GRO-174]: 
We were missing a H1 Tag on artsy.net/articles. Since no additional descriptive text on this page, the H1 is the same as the title tag **Editorial | Artsy**. Jenna also requested that the visibility be hidden for this H1 tag.
New Behavior:
[GRO-174]: https://artsyproduct.atlassian.net/browse/GRO-174
=> GRO-174: Adding H1 Tag on artsy.net/articles for SEO

src/v2/Components/Onboarding/Steps/Artists/index.tsx, src/v2/Components/Onboarding/Steps/Budget.tsx, src/v2/Components/Onboarding/Steps/CollectorIntent.tsx, src/v2/Components/Onboarding/Steps/Genes/index.tsx, src/v2/Components/Onboarding/Types.ts, src/v2/Components/Onboarding/Wizard.jest.tsx, src/v2/Components/Onboarding/Wizard.tsx
This PR aims to drastically simplify the onboarding wizard component by pushing things down into its children. It was responsible for too many things and was more complicated than it had to be. Out of scope for this PR is improving the children - that's next. 😉 
The commits do a pretty good job of telling this refactoring story but I wanted to call out that prior to this work there were no tests for this onboarding code and that didn't feel great. I end up writing one sanity check test in the final commit so that's good but still not ideal. It meant that I did a lot of "refactor and then test in the browser"-type refactoring and sometimes that's just what you have to do to move something forward.
I expect to get more tests around this part of the code as I dive into the child components. …
=> refactor: Gut onboarding wizard GRO-61

src/v2/Components/CCPARequest.tsx, src/v2/Components/Footer.tsx, src/v2/Components/__tests__/Footer.jest.tsx
Our “Do Not Sell My Information” link that allows users to request their data or delete was not in the v2 footer, so when we updated web to only use the v2 footer we lost it. This PR is to add it back to be in compliance.
Previous Behavior:
New Behavior:
Desktop:
Mobile:
=> GRO-183: Adding CCPA link back to footer

src/v2/Components/NavBar/Menus/DropDownMenu/DropDownMenu.tsx, src/v2/Components/NavBar/Menus/DropDownMenu/DropDownSection.tsx, src/v2/Components/NavBar/NavBar.tsx, src/v2/Components/NavBar/NavBarPrimaryLogo.tsx, src/v2/Components/NavBar/NavBarSkipLink.tsx, src/v2/Components/NavBar/NavItemPanel.tsx
Addresses https://artsyproduct.atlassian.net/browse/GRO-215
This fixes an issue where the nav didn't stretch to the full width of the content area.
Also does a light refactor, moving the styled-components related components in a few files from the top of the file to the bottom, after the main component definition, since CSS is rarely returned to by future devs; however, main component code often is. Reduces the signal to noise ratio around contributing changes and increases readability. 
Before: 
After:
=> fix: [NavBar] Space items better at breakpoints

package.json, scripts/clean.sh
When working on old Force pages our toolchain doesn't always recompile CSS when we modify `styl` files. This results in stale CSS being served locally.
Update `yarn clean` to delete compiled CSS assets. The assets get dynamically recreated on pages that need them and allow devs to see changes they've made.
=> chore: Update yarn clean to include cleaning out compiled CSS

.gitignore, package.json, src/desktop/components/cookies/index.coffee, src/desktop/components/split_test/setup.coffee, src/desktop/components/split_test/split_test.coffee, src/lib/ip.ts, src/lib/metaphysics.ts, src/lib/metaphysics2.coffee, webpack/envs/clientNovoProductionConfig.js, yarn.lock
Strategically cleans up several `underscore`/`chalk` imports that were causing them
to be included in Novo bundles.
Pulls the one function we used from `ip` into lib, we don't need a whole
library for a single ipv6 regex.
The bundle size is reduced from 1.07 MiB to 1.02 MiB
=> feature: Reduce Novo Bundle Size

src/v2/Components/Onboarding/SelectableToggle.tsx, src/v2/Components/Onboarding/Steps/Budget.jest.tsx, src/v2/Components/Onboarding/Steps/Budget.tsx, src/v2/Components/Onboarding/Steps/CollectorIntent.jest.tsx, src/v2/Components/Onboarding/Steps/CollectorIntent.tsx, src/v2/Components/Onboarding/Steps/Layout.tsx, src/v2/Components/Onboarding/Wizard.tsx
This PR adds two new onboarding tracking events for when a user picks interests and sets a budget. I followed some advice from this thread:
https://artsy.slack.com/archives/CP9P4KR35/p1613075517312100
And moved to wrapping the Wizard component in a `track` call so that I could use hooks in the child components. This worked great! The only exception was the existing event that was triggered and has not been migrated to cohesion. After chatting with @abhitip about it, we decided to leave it alone so I just marked it as `any` and moved on. We can come back to this if/when it makes sense.
I was really happy to add a bunch of tests in this PR so that we have some confidence as we move forward working on the onboarding code - more to come on this!
This PR only addresses the first and last steps …
=> feat: Improve first and last onboarding step tracking GRO-61

src/v2/Components/Footer.tsx, src/v2/Components/NavBar/NavBar.tsx, src/v2/Components/NavBar/NavItem.tsx, src/v2/Utils/ScrollIntoView.tsx, src/v2/Utils/scrollHelpers.ts
Ticket: [GRO-213]
There were performance optimizations recommended by Damon for the footer.
The image in the footer should be lazy loaded and be a real `img` tag to increase accessibility.
New layout:
[GRO-213]: https://artsyproduct.atlassian.net/browse/GRO-213
=> chore: GRO-213: Adding LazyLoadComponent to FooterBanner

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx, src/v2/Components/v2/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx
Closes: [FX-2629](https://artsyproduct.atlassian.net/browse/FX-2629)
* The currently selected price range is always reflected in the inputs (so if selecting a radio or coming in from a link)
* You can only input positive integers into the inputs, left hand side has to be at a minimum of 0, right hand side can be empty which is `"*"`
* If the input changes to one not reflected in the radios; then no radios will be highlighted
There might be some subtleties to this interaction here that can be tweaked; so this needs some eyes on it; but this should work as a first-pass.
=> feat(fx-2629): implements custom price range filter

src/desktop/apps/about/index.coffee
While working through #7079 I failed to handle the sub-section URLs. This PR gobbles them up and redirects them to the main about page. More chatter here:
https://artsy.slack.com/archives/C9SATFLUU/p1614380046128900
https://artsyproduct.atlassian.net/browse/GRO-212
/cc @artsy/grow-devs @dblandin @joeyAghion @dzucconi
=> fix: Redirect about sub-sections GRO-212

src/v2/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
this is an odd one b/c its one of these 'how did this ever work?' bugs. the answer is that it didn't, unless something was more recently changed (but I wasn't able to find anything spelunking in force and reaction, at least until the time of the merger, so it does seem likely this hasn't worked in 1+ years?).
=> fix: allow paginating on search results tab by passing the term thru

src/desktop/lib/webpackPublicPath.ts
Just noticed that I missed adding this to the `webpackPublicPath` a while back!
=> fix: [Novo] Add /auctions2 public path

src/desktop/apps/sitemaps/index.coffee, src/desktop/apps/sitemaps/routes.coffee, src/desktop/apps/sitemaps/test/routes.test.js, src/desktop/apps/sitemaps/test/templates.test.js
We aren't publishing news like we used to so this sitemap is stale. When this is merged I'll update Google Search Console to remove the sitemap from there as well. Note that these news items ARE in the corresponding article sitemap so they were sorta dupes.
https://artsyproduct.atlassian.net/browse/GRO-226
=> feat: Remove stale news sitemap GRO-226

src/v2/Artsy/Router/RenderStatus.tsx
This adds a slight 1p white border to our top page transition loader so that we can see it in dark mode themes. This has always bothered me and just noticed this fix on another site, wanted to bring it here:
=> fix: [Router] Add white border around loader for darkmode

src/v2/Apps/Order/Components/AddressModal.tsx
Fixes a small bug that prevented a user from interacting with or scrolling the page after the `createUserAddress` mutation is submitted.
The Fix:
The Bug:
=> bugfix: prevent create address mutation from firing twice

src/v2/Apps/Order/Components/AddressModal.tsx, src/v2/Apps/Order/Components/SavedAddresses.tsx, src/v2/Apps/Order/Components/__tests__/SavedAddresses.jest.tsx, src/v2/Apps/Order/Routes/Shipping/index.tsx, src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
This PR fixes scrolling issues that happened when using the address modal. It:
- Moves visibility of the modal to state on the payment/shipping flow.
- Changes modal visibility trigger to be explicit on saved addresses. 
- Removes conditional rendering of modal in parents.
- Removes redundant click handler on modal.
=> fix: Fixes for scrolling issues related to address modal

src/desktop/apps/auction/components/layout/meta.jade
Rather than compute an href here I've opted to simply concatenate the canonical as `/auction/:id` so that we don't confuse Google with duplicate content.
More chatter here: https://artsy.slack.com/archives/C01ADJNCS5D/p1614874844237600
https://artsyproduct.atlassian.net/browse/GRO-210
=> fix: Mark all sales as auctions for seo GRO-210

src/desktop/lib/webpackPublicPath.ts
Problem: 
Getting a bunch of ChunkLoadError: Loading chunk 29 failed.  from novo routes.
Discussion:
https://artsy.slack.com/archives/CA8SANW3W/p1614893500274200
After releasing the app to the public this will be changed to `user/payement`
=> fix: Add `payments2` to converted paths

src/desktop/apps/authentication/helpers.ts, src/desktop/lib/global_client_setup.tsx, src/lib/setupSentry.ts, src/mobile/components/layout/bootstrap.coffee, src/v2/Utils/__tests__/errors.jest.ts, src/v2/Utils/errors.tsx
This cleans up the Sentry imports to better support tree shaking and
moves error reporting to a single module.
=> chore: Cleanup Sentry Imports

src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtistNationalityFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtworkLocationFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ColorFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/FacetAutosuggest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PartnersFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ShowMore.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/ArtistsFilter.jest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/FacetAutosuggest.jest.tsx
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=FX&modal=detail&selectedIssue=FX-2704
The commits tell the story. Capped 'show more' to 6, and added it to the artists filter (on fair page), and the medium and time period filters, as well as tweaking the color filter from 7 -> 6.
Also generalized the somewhat simple autosuggest widget and added it to artist nationality and artwork location (in addition to partners).
=> chore: cap show more to 6, and use for all long lists

src/v2/Apps/Order/Components/__tests__/SavedAddresses.jest.tsx, src/v2/__generated__/SavedAddressesMutation_Test_Query.graphql.ts
When compiling relay, I got the following error:
```
Duplicate definition of 'SavedAddresses_Test_Query'.
```
Will look into if CI needs this check next.
=> test: update test query to avoid relay dupliate definition error

src/desktop/lib/__tests__/buildServerAppContext.jest.ts, src/desktop/lib/buildServerAppContext.ts, src/v2/Artsy/SystemContext.tsx, src/v2/Artsy/__tests__/SystemContext.jest.tsx, src/v2/Components/NavBar/MinimalNavBar.tsx, src/v2/Components/NavBar/NavBar.tsx, src/v2/Components/NavBar/__tests__/MinimalNavBar.jest.tsx, src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
Web views in eigen have been slightly broken for some time. The root cause was that the `isEigen` system context value was not managed correctly. This PR fixes that while making sure that the main nav bars are hidden in eigen.
=> fix: eigen context

src/v2/Apps/Auctions/Components/AuctionsMeta.tsx, src/v2/Apps/Feature/Components/FeatureMeta.tsx
These tags are vestiges of the pre-rendering we needed to do for non-server-rendered pages in the past (according to [Google's deprecated AJaX crawling protocol](https://developers.google.com/search/docs/ajax-crawling/docs/specification)). Google may have deprecated it, but we've observed that other crawlers continue to respect this tag and make separate requests for the pre-rendered assets. In any case, it shouldn't be necessary for these server-rendered pages.
Once released, we can remove the [features sitemap](https://www.artsy.net/sitemap-features.xml) from the list that Reflection crawls and delete the corresponding pages:
```ruby
Sitemap.where(url: 'https://www.artsy.net/sitemap-features.xml').destroy_all
Page.where('url LIKE ?', 'https://www.artsy.net/feature/%').destroy_all
```
=> Remove unnecessary fragment meta tags

package.json
Remembered [this blog post](https://artsy.github.io/blog/2018/08/24/How-to-debug-jest-tests), and have been doing the same in Metaphysics (via VSCode). Didn't realize it wasn't in force:
=> toolchain: Add `yarn jest:debug` for debugger

src/v2/Apps/Order/Components/PaymentPicker.tsx, src/v2/Apps/Order/Components/SavedAddresses.tsx, src/v2/Apps/Order/Components/__tests__/PaymentPicker.jest.tsx
Fixes [PURCHASE-2485]
Making sure all the `null` address item values are changed to the empty string the way stripe expects them to be.
Also adds margin between saved shipping addresses in collector profile.
</details>
[PURCHASE-2485]: https://artsyproduct.atlassian.net/browse/PURCHASE-2485
=> fix: Use shipping address as billing

src/desktop/assets/analytics.ts
We have a legacy page for shows (plural!), at http://www.artsy.net/shows .
It seems like an overeager regex to not record pageviews using the legacy stack for the rebuilt show (individual) page also suppressed them for /shows. This is the fix. Worth noting that while a data team member called out the anomalous data, no product team or KPI seems to particularly relate to this somewhat lost page.
=> fix: adjust regex to not exclude analytics from /shows

src/v2/Apps/Artist/artistRoutes.tsx, src/v2/Apps/ArtistSeries/artistSeriesRoutes.tsx, src/v2/Apps/Collect/collectRoutes.tsx, src/v2/Apps/Fair/Routes/FairArtworks.tsx, src/v2/Apps/Fair/fairRoutes.tsx, src/v2/Apps/Search/searchRoutes.tsx, src/v2/Apps/Show/Components/ShowArtworks.tsx, src/v2/Apps/Show/showRoutes.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MaterialsFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/MaterialsTermFilter.jest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx, src/v2/Components/v2/ArtworkFilter/Utils/countChangedFilters.ts, src/v2/Components/v2/ArtworkFilter/Utils/isDefaultFilter.tsx, src/v2/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
https://artsyproduct.atlassian.net/browse/FX-2631
↳ https://artsyproduct.atlassian.net/browse/FX-2742
- Creates a `MaterialsFilter` facet that renders the aggregation as multiple-select checkboxes
- Adds it to the following artwork grids:
- Updates the `Apply (n)` button logic on mobile
(btw noticed while updating ⬆️ that Apply button on mobile that we don't consistently do that with all the new facets. I'll PR something, hopefully with tests that make it easier to catch.)
=> feat(materials filter): add Materials facet to artwork grids

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx, src/v2/Apps/Partner/Components/__tests__/NavigationTabs.jest.tsx, src/v2/Apps/Partner/PartnerApp.tsx, src/v2/Apps/Partner/Routes/Articles/index.tsx, src/v2/Apps/Partner/Routes/Artists/index.tsx, src/v2/Apps/Partner/Routes/Contact/index.tsx, src/v2/Apps/Partner/Routes/Overview/index.tsx, src/v2/Apps/Partner/Routes/Shows/index.tsx, src/v2/Apps/Partner/Routes/Works/index.tsx, src/v2/Apps/Partner/__tests__/PartnerApp.jest.tsx, src/v2/Apps/Partner/partnerRoutes.tsx, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/__generated__/NavigationTabs_Test_PartnerQuery.graphql.ts, src/v2/__generated__/NavigationTabs_partner.graphql.ts, src/v2/__generated__/PartnerApp_Test_Query.graphql.ts, src/v2/__generated__/PartnerApp_partner.graphql.ts, src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts
This PR adds a basic layout for the partner profile page. 
- adds new routes starts with `/partner2/:partnerId`
- adds navigation tabs
- includes 404 page handling
JIRA - https://artsyproduct.atlassian.net/browse/PX-3834
=> feat: add profile page wireframe

src/desktop/assets/analytics.ts
Because the tracking is handled by "SSR framework now via analyticsMiddleware" [[thread](https://artsy.slack.com/archives/C9YNS4X32/p1616088152046900)]
Caught by @damassi 🙏🏽 
cc: @icirellik
=> fix: Exclude `PaymentApp` route from analytics tracker

src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignMeta.tsx, src/v2/Apps/Artist/Routes/Overview/index.tsx, src/v2/Apps/Artist/Routes/Works/index.tsx, src/v2/Apps/Artist/Utils/__tests__/computeTitle.jest.tsx, src/v2/Apps/Artist/Utils/computeTitle.tsx
Fixes https://artsyproduct.atlassian.net/browse/GRO-241. 
Remove # of artworks from title tag on artist pages when 0.
=> bugfix: Fixes artist title tag for zero artworks

src/v2/Apps/Artist/Components/ArtistMetaCanonicalLink.tsx, src/v2/Apps/Artist/Components/__tests__/ArtistMetaCanonical.jest.tsx
I took this work up after our SEO bug bash and did a little cleaning up. There's a function we use to compute the canonical tag and prior to this refactoring it was taking complex objects and that made it cumbersome to test so I changed that. I moved to that function taking only primitives which made it easier to spot and fix the bug. Props to @The-Beez-Kneez for finding it first so all I had to do was the clean-up part!! 🏆 
Anyway, this should be good and I'm hoping any future changes will be easier to make.
https://artsyproduct.atlassian.net/browse/GRO-220
=> fix: Ensure self-referring canonicals on consign pages GRO-220

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MaterialsFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/MaterialsTermFilter.jest.tsx
https://artsyproduct.atlassian.net/browse/FX-2744
This update teaches the filters how to properly use the `name` _and_ `value` of the upstream aggregations:
- Use the (capitalized) `name` for user-facing display
- Use the `value` for twiddling filter state
This relies on the upstream work in Gravity (https://github.com/artsy/gravity/pull/13919), but should continue to work fine even before that lands.
=> feat(materials filter): use proper capitalization

src/v2/Apps/Artist/artistRoutes.tsx, src/v2/Apps/ArtistSeries/artistSeriesRoutes.tsx, src/v2/Apps/Collect/collectRoutes.tsx, src/v2/Apps/Fair/fairRoutes.tsx, src/v2/Apps/Search/searchRoutes.tsx, src/v2/Apps/Show/showRoutes.tsx, src/v2/Components/v2/ArtworkFilter/Utils/__tests__/allowedFilters.jest.ts, src/v2/Components/v2/ArtworkFilter/Utils/allowedFilters.ts, src/v2/Components/v2/ArtworkFilter/index.tsx
This adds an allow list on the initial request, as well as the same allow list on any refetches. So going to a filter page with `?blah=..` should just work, and the URL itself remains (as in, we're not scrubbing the URL to remove that erroneous param, as I'm sure that'll do something funky with stuff that tracks UTM params in the URL...).
=> fix: use an allowlist for filter params coming from URL

src/desktop/lib/webpackPublicPath.ts, src/v2/Apps/Partner/Components/PartnerHeader/PartnerHeaderAddress.tsx, src/v2/Apps/Partner/Components/PartnerHeader/index.tsx, src/v2/Apps/Partner/Components/__tests__/NavigationTabs.jest.tsx, src/v2/Apps/Partner/Components/__tests__/PartnerHeader.jest.tsx, src/v2/Apps/Partner/PartnerApp.tsx, src/v2/__generated__/PartnerApp_Test_Query.graphql.ts, src/v2/__generated__/PartnerApp_partner.graphql.ts, src/v2/__generated__/PartnerHeader_Test_Query.graphql.ts, src/v2/__generated__/PartnerHeader_partner.graphql.ts, src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts
This PR adds header rail for the partner profile page.
- adds partner name and locations
- adds follow partner button
- adds partner icon
JIRA - https://artsyproduct.atlassian.net/browse/PX-3824
=> feat: add header for partner profile

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
Closes [FX-2737](https://artsyproduct.atlassian.net/browse/FX-2737)
Both `*` and `0` are equivalent values for the min. Setting the price to `*` on deletion leads to a more natural UX in this case. 
-----
=> fix(filters): allows deletion of min price

.circleci/config.yml, .gitignore
Related: https://github.com/artsy/palette/pull/888
Adds a new storybook deploy step: 
https://artsy-static-sites.s3.amazonaws.com/artsy-force-storybook/index.html
=> ci: Deploy storybooks via Circle orb

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtworkLocationFilter.tsx
This PR addresses [FX-2733](https://artsyproduct.atlassian.net/browse/FX-2733) by changing the copy of the placeholder text in the artwork location filter's search field from "Enter a location" to "Enter a city" because it only filters on city name and not on state or country names.
=> fix: artwork location autosuggest placeholder copy (FX-2733)

src/v2/Apps/Partner/Components/PartnerHeader/PartnerHeaderAddress.tsx, src/v2/Apps/Partner/Components/__tests__/PartnerHeader.jest.tsx
This PR trim city name to show **only** unique values.
Discussed here - https://github.com/artsy/force/pull/7190#discussion_r598694527
JIRA - https://artsyproduct.atlassian.net/browse/PX-3824
Old:
New:
=> feat: trim city name before taking unique values for partner profile header

src/v2/Apps/Collect/Routes/Collection/index.tsx, src/v2/Apps/Collect/collectRoutes.tsx, src/v2/__generated__/CollectionAppQuery.graphql.ts, src/v2/__generated__/Collection_collection.graphql.ts, src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Looking through the fragments for the collect and collection pages, and it seems pretty clear some could be cleaned up. For instance, a bunch of requests on /collection pages are for calculating metadata, where their corresponding components don't reference any aggregation data. Some spurious `size`/`first` usage.
Also, this _re-adds_ the new aggregations back to /collect (lost in a recent refactor 🙈 ). We can keep them for QA and remove if needed.
=> chore: reason about some aggregations on /collect and collection pages

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/FacetAutosuggest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/FacetAutosuggest.jest.tsx
This PR addresses [FX-2730](https://artsyproduct.atlassian.net/browse/FX-2730) by adding style to the "No results found." text that is displayed under the filter search interface when a user's search term doesn't match any options. It also updates the copy to "No results." to match [the design spec](https://www.figma.com/file/zG9cduJdOaTQAw886QcOwn/Filters?node-id=856%3A2621).
=> fix: add missing style to filter autosuggest (FX-2730)

src/v2/Apps/Partner/Components/PartnerHeader/index.tsx, src/v2/Apps/Partner/Components/__tests__/PartnerHeader.jest.tsx, src/v2/__generated__/PartnerApp_Test_Query.graphql.ts, src/v2/__generated__/PartnerHeader_Test_Query.graphql.ts, src/v2/__generated__/PartnerHeader_partner.graphql.ts, src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts
This PR fixes the partner logo by using resized field instead of cropped.
JIRA - https://artsyproduct.atlassian.net/browse/PX-3866
Before:
Now:
=> fix: use resized logo instead of cropped

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtistNationalityFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtworkLocationFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ColorFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MaterialsFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PartnersFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ShowMore.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
Closes https://artsyproduct.atlassian.net/browse/FX-2786
This is an odd one! I wasn't sure what to account for the desired behavior in some cases: ie, interactions with the filter remain, so if you've expanded or toggled, it doesn't 're-render'. That seemed possibly larger in scope, due to how the components are structured.
So, what this does, is actually check whether there is a currently selected filter in the list of options that would be visible when 'Show More' is pressed. If so, the 'expanded' state is set there directly. This has the affect of working like we'd like: if you've expanded and selected an item, that expanded state will remain irrespective of re-renders.
=> feat: make sure to expand toggle and show more appropriately

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MaterialsFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/FacetAutosuggest.jest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/MaterialsTermFilter.jest.tsx
https://artsyproduct.atlassian.net/browse/FX-2645
This adds the autocomplete filtering of available aggregation options into the **Materials** filter:
~Tried to get a test around this, but Enzyme is not working for me — see below…~ solved
=> feat(materials filter): add autocomplete search UI

src/v2/Components/v2/ArtworkFilter/Utils/countChangedFilters.ts, src/v2/Components/v2/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx, src/v2/Components/v2/ArtworkFilter/__tests__/NewArtworkFilterMobileActionSheet.jest.tsx
This PR addresses [FX-2738](https://artsyproduct.atlassian.net/browse/FX-2738) by tracking changes that a user makes to the **artwork location**, **medium**, **rarity**, **color** and **artist nationality** filters so that the Apply button in the filter modal can show how many filters will be applied on-click.
The current behavior was that the Apply button showed 0 for any selections made on those four filters, but now the Apply button will add 1 to the count for any selections made in each filter.
**`~~~ before ~~~~~~~~~~~~~~~`**
**`~~~ after ~~~~~~~~~~~~~~~`**
=> fix: update apply button count when new filters are used (FX-2738)

src/v2/Components/v2/ArtworkFilter/__tests__/NewArtworkFilterMobileActionSheet.jest.tsx
I forgot to add an assertion to one of the tests written in #7202.
=> fix: add a missing assertion to artwork filter tests

webpack/envs/clientDevelopmentConfig.js, webpack/envs/clientProductionConfig.js
Quick fix for our `.ejs` template output. Was masked until I ran `yarn clean`, as we output the file to `public` during dev build. After folder was cleaned, realized the file wasn't outputting correctly anymore.
=> fix: Fixes path to template

src/v2/Apps/Components/AppContainer.tsx, src/v2/Apps/Gene/Components/GeneMeta.tsx, src/v2/Apps/Gene/GeneApp.tsx, src/v2/Apps/Gene/Routes/GeneShow.tsx, src/v2/Apps/Gene/Routes/__tests__/GeneShow.jest.tsx, src/v2/Apps/Gene/geneRoutes.tsx, src/v2/Apps/getAppNovoRoutes.tsx, src/v2/__generated__/GeneMeta_gene.graphql.ts, src/v2/__generated__/GeneShow_Test_Query.graphql.ts, src/v2/__generated__/GeneShow_gene.graphql.ts, src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts
Closes: [FX-2792](https://artsyproduct.atlassian.net/browse/FX-2792)
This should be fine to merge as a stub of the new app.
Some notes
* Jonathan is going to likely darken the secondaryOutline border style and tweak the rules for it's width in these 50/50 layouts
* Notice the footer: it looks like it's doing something kinda weird/complicated instead of just using the AppContainer. I'll have to update that in it's own PR.
=> feat(gene): roughs in gene route and header

.eslintrc.js, src/desktop/apps/sitemaps/routes.coffee, src/desktop/apps/sitemaps/test/routes.test.js
This PR does a little bit of double duty and I can break it out if you want.
It's primary purpose is to just add the auctions sitemap to our robots.txt. Given that I had to update a mocha test, there were some lint failures (because jest lint config options are being ran on our mocha tests). To remove those failures, I added an override to categorically ignore those errors across our mocha test files. We'd talked about how to handle this [in slack](https://artsy.slack.com/archives/C2TQ4PT8R/p1616519353015800), but this seems to be the simplest, broad solution. 
We can't merge this until our sitemap deploy job is back up and running so I'll leave it in draft, but the work is technically done.
=> feat: Add auctions to robot

src/v2/Apps/Components/AppContainer.tsx
Thanks for catching this.
In a few places [we declare a `maxWidth` then sometimes define it](https://github.com/artsy/force/blob/523e3365d7af7313055143ba1a229176d6c3316f/src/v2/Apps/Artist/ArtistApp.tsx#L39-L44) — so this just works around this.
=> fix: use props max-width unless undefined

src/v2/Apps/Order/Routes/Offer/index.tsx, src/v2/Apps/Order/Routes/Review/index.tsx
This addresses [PURCHASE-2462]
Changes copy in two screens.
**Before:**
**After:**
**Before:**
**After**
[PURCHASE-2462]: https://artsyproduct.atlassian.net/browse/PURCHASE-2462
@artsy/purchase-devs
=> chore: change copy for offer flow to include offer binding

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter2.tsx
Pretty light, tweaks the input a bit to match the spec, and also does the same "mode" thing as the price filter for the mobile case.
=> chore: tweak custom size filter to match spec

src/desktop/apps/sitemaps/index.coffee
We correctly added the reference to robots.txt and routes.coffee in #7252, but missed this other place they're configured in the index.
Unfortunate.
=> Add missing auctions sitemap reference

src/v2/Apps/Order/Components/AddressModal.tsx, src/v2/Apps/Order/Components/SavedAddresses.tsx, src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx, src/v2/Apps/Order/Mutations/CreateUserAddress.ts, src/v2/Apps/Order/Mutations/DeleteUserAddress.ts, src/v2/Apps/Order/Mutations/UpdateUserAddress.ts, src/v2/Apps/Order/Mutations/UpdateUserDefaultAddress.ts, src/v2/Apps/Order/Routes/Shipping/index.tsx, src/v2/Apps/Order/Routes/__fixtures__/MutationResults/saveAddress.ts
[PURCHASE-2484](https://artsyproduct.atlassian.net/browse/PURCHASE-2484)
Handles server errors gracefully.
Before:
When a mutation returned errors, it was being handled by `Order/Utils/commitMutation` and the errors were not properly surfaced in the UI.
After:
Now the errors are being handled and if there is a known server error, it is being displayed next to the corresponding field.
TODO:
=> fix: refactor address mutations

src/v2/Apps/Partner/PartnerApp.tsx
This PR fixes foreground on the partner profile page.
JIRA - https://artsyproduct.atlassian.net/browse/PX-3884
Before:
Now:
=> fix: partner profile page foreground

src/v2/Apps/getAppRoutes.tsx
Looks like these routes got dropped in some refactor somewhere.
=> fix(routes): re-adds gene2 routes

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MaterialsFilter.tsx
This PR addresses [FX-2802](https://artsyproduct.atlassian.net/browse/FX-2802) by changing the label on the `MediumsFilter` from "Materials" to "Material."
=> fix: change "materials" filter title to "material" (FX-2802)

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.jest.tsx
Looks like
Closes https://artsyproduct.atlassian.net/browse/FX-2800
=> fix: add a trailing `s` for numeric time period filters

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtistNationalityFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtworkLocationFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/FacetAutosuggest.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MaterialsFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PartnersFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/FacetAutosuggest.jest.tsx
Closes https://artsyproduct.atlassian.net/browse/FX-2723
This sort of winds up being relatively simple.
For each facet, we have the list of the available filter options. We also have the list of currently selected filter options for that facet. So, we create a new list of filter options, which is a reshuffle: selected items move to the front, and the rest of the options are concatenated (in their original order), with those selected items having been removed from the remaining list.
Looks like:
https://user-images.githubusercontent.com/1457859/113049099-40d58880-9171-11eb-841f-98fd416d72d8.mp4
=> feat: pin selected items to top of filters which are multi-select lists

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter2.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter2.jest.tsx
Closes https://artsyproduct.atlassian.net/browse/FX-2804
No real change, besides handling the case of coming to a page with a URL like `?height=12-*` specified (only one dimension), and also expanding the 'custom' toggle if a custom range is present.
=> chore: tweak custom size filter interaction when only one dimension is entered

webpack/envs/clientDevelopmentConfig.js, webpack/envs/legacyDevelopmentConfig.js
We were getting some confusing behavior with the new react refresh plugin which masked errors during the server-render pass. Disabling for now in favor of what was there before. 
Problem:
Solution:
=> fix: Disable react refresh overlay

src/v2/Apps/Components/AppShell.tsx
Via: https://css-tricks.com/full-width-containers-limited-width-parents/
> The viewport-percentage lengths are relative to the size of the initial containing block. When the height or width of the initial containing block is changed, they are scaled accordingly. However, any scrollbars are assumed not to exist.
- https://www.w3.org/TR/css3-values/#viewport-relative-lengths
Which is: *interesting*.
Setting `overflow-x: hidden` on our app shell fixes this.
=> fix(fullbleed): prevents persistent scrollbars from causing an overflow-x scroll on screens with fullbleed

src/desktop/lib/webpackPublicPath.ts, src/v2/routes.tsx
Add gene routes to `webpackPublicPath` so that the assets load from the
cdn properly.
=> feature: Enable Gene Routes

package.json, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx, yarn.lock
Obviously all other inputs will continue to zoom on focus (including search): which we don't really want... once we move to Palette v3 this will no longer be an issue. For now this handles this single input with a media query.
=> fix(fx-2803): prevents input zoom

src/v2/Apps/Collect/Routes/Collection/Components/Header/index.tsx
**Description:**
Passing htmlUnsafeDescription to ReadMore was causing a type error/500 for mobile browsers. Not sure if this is the correct fix please advise if there is a better way 🙏  
Affected url:
`/collection/first-look-women-artists-to-watch-2021`
Reproduce locally:
```
curl -A "Mozilla/5.0 (Linux; Android 8.0; Pixel 2 Build/OPD3.170816.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Mobile Safari/537.36" 'http://localhost:4000/collection/first-look-women-artists-to-watch-2021'
```
**Before:**
**After:**
See slack thread for more details:
https://artsy.slack.com/archives/CA8SANW3W/p1617292009246000
=> fix: fix collection type error in mobile browser

src/v2/Utils/getClientParam.tsx, src/v2/Utils/getServerParam.tsx, src/v2/client.tsx, src/v2/server.ts
Follow-up on https://github.com/artsy/force/pull/7294
Splits `getParams` function into server and client.
=> fix: Split getParams functions

src/v2/client.tsx
The client modal bundles have been merged together. Previously there were
two bundles, 22 KB and 2 KB. The 2 KB bundle was is unlikely to be beneficial
because the time to initiate a connection is similar to the time to download.
No specific speeds gains here however one less network request is always
preferable.
=> feature: Client Modal Bundle

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MaterialsFilter.tsx
This is a follow-up to #7267 because that change got overwritten.
=> fix: change materials filter title to material again

src/v2/Apps/Components/AppShell.tsx, src/v2/Apps/Partner/Components/NavigationTabs/index.tsx, src/v2/Components/StickyContainer.tsx, src/v2/Components/v2/ArtworkFilter/index.tsx
Closes: https://artsyproduct.atlassian.net/browse/FX-2809
Re: https://artsyproduct.atlassian.net/browse/FX-2796?focusedCommentId=36021
I always forget about [this issue](https://github.com/w3c/csswg-drafts/issues/865) which is a huge gotcha when using `position: sticky`. The thing that will finally fix this long-standing annoyance is `overflow: clip` but [that's not widely supported yet](https://caniuse.com/?search=overflow)
https://caniuse.com/?search=overflow
We're already tracking the intersection here so it's not much of a leap to just replicating what `position: sticky` does using `position: fixed` and a placeholder.
I've also refactored away having to pass in a `Container` prop in favor of just optionally supporting a function-as-prop. I was going to do a context + hook thing here …
=> fix(sticky): works around overflow-x: hidden sticky interference

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtistNationalityFilter.tsx
https://artsyproduct.atlassian.net/browse/FX-2820
Trivial change, to bring the placeholder text in line with the facet name:
=> fix(filters): artist nationality/ethnicity placeholder text

src/v2/Apps/Auctions/AuctionsApp.tsx
This is for JIRA ticket [GRO-277]
Since the new copy text is rather long we wanted to  use this 50/50 header layout.
New Behavior:
[GRO-277]: https://artsyproduct.atlassian.net/browse/GRO-277
=> GRO-277: Update /auctions header layout

src/desktop/apps/user/components/auction_registrations/query.coffee, src/desktop/apps/user/components/auction_registrations/view.coffee
This PR relates to [PURCHASE-2185].
Updated auction registrations onto v2. It uses the fixed `saleRegistrationsConnection` merged on [this](https://github.com/artsy/metaphysics/pull/3072) PR.
cc: @artsy/purchase-devs 
[PURCHASE-2185]: https://artsyproduct.atlassian.net/browse/PURCHASE-2185
=> chore: Update auction registrations to v2

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter2.tsx
https://artsyproduct.atlassian.net/browse/FX-2823
The ticketed is change is highlighted in red.
Based on the design [spec](https://www.figma.com/file/zG9cduJdOaTQAw886QcOwn/Filters?node-id=856%3A1600) I also smuggled in another change for consistency, highlighted in blue.
=> fix(filters): ensure consistent button styles for custom fields

src/v2/Apps/Auctions/Components/AuctionsMeta.tsx
This updates `/auctions2` with the following meta description and canonical link:
Meta Description: Bid in live and online-only sales from the world’s leading auction houses. Browse paintings, sculptures, design, prints & multiples and more.
Canonical (should be self referring): artsy.net/auctions 
New Behavior:
=> GRO-284: Added in meta description and canonical link

src/v2/Components/RouteTabs.tsx
This PR adds the use of the `exact` field value to determine the active tab.
Used `true` as a default value to support the same behavior.
=> fix: use exact value to define is active tab

src/desktop/apps/partnerships/templates/auction_sections.jade
The `/auctions-partnerships` page is giving a 500 due to this error: 
This is a fast fix to guard against that particular issue and get us back up and running.
=> Guard against quotes being empty on auctions-partnerships page

src/v2/Apps/Fair/Routes/FairArtworks.tsx, src/v2/Apps/Show/Components/ShowArtworks.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ResultsFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter2.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx, src/v2/Components/v2/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx, src/v2/Components/v2/ArtworkFilter/index.tsx
This PR addresses [FX-2830](https://artsyproduct.atlassian.net/browse/FX-2830) by:
1. Passing the filters that should appear on the fair and show artwork grids as a JSX element rather than as functional components.
1. Allowing filters that are collapsed by default to override their `expanded` prop if the user has selected one or more of their options.
**Buggy behavior**
=> fix: keep filters that are collapsed by default expanded after selection (FX-2830)

.circleci/config.yml
Added yarn relay to check to ci script as a task under `jest-v1`. Does it make sense to include it there or is there a more intuitive place to add that check? I was debating running it under the type check?
To test if this worked, I ran the suite alone and it passed and then added a duplicate definition for a test query renderer (the problem we had run into in volt when CI was passing while relay was giving the error `Duplicate definition of...`) and it [failed and exited the test suite](https://app.circleci.com/pipelines/github/artsy/force/13571/workflows/c4f30079-c7e6-4dfe-a26c-a706eff4f2b2/jobs/97445). 
[Jira ticket](https://artsyproduct.atlassian.net/browse/FP-20)
=> fix: Add yarn relay to CI script

src/v2/Apps/Auctions/AuctionsApp.tsx, src/v2/Apps/Auctions/auctionsRoutes.tsx
Noticed a few other little things with the spacing, and realized we don't need to bundle split the sub-routes as the chunk sizes are so minuscule that even with js preloading they load so fast that there's still some layout thrashing, and are basically all identical -- only pulling in a couple rails. 
Before: 
After:
=> fix: [Auctions2] More spacing QA

src/v2/Components/v2/ArtworkFilter/Utils/__tests__/countChangedFilters.jest.ts, src/v2/Components/v2/ArtworkFilter/Utils/countChangedFilters.ts
Close: [FX-2834](https://artsyproduct.atlassian.net/browse/FX-2834)
OK, this is a reprise of https://github.com/artsy/force/pull/7330 — Rather than checking each filter manually; just diff the filter states and count the changed keys.
=> fix(filters): correctly counts filter changes

src/v2/Apps/Order/Routes/Status/index.tsx
Resolves [PURCHASE-2527](https://artsyproduct.atlassian.net/browse/PURCHASE-2527) to remove the "Back to Artsy" button from the webview in Eigen after a buyer has declined a counteroffer.
Before:
After:
=> fix: Removes Back to Artsy button in Eigen's Make Offer flow

src/v2/Apps/Auctions/Routes/CurrentAuctions.tsx, src/v2/Apps/Auctions/Routes/PastAuctions.tsx, src/v2/Apps/Auctions/Routes/UpcomingAuctions.tsx, src/v2/__generated__/CurrentAuctionsQuery.graphql.ts, src/v2/__generated__/CurrentAuctions_Test_Query.graphql.ts, src/v2/__generated__/CurrentAuctions_viewer.graphql.ts, src/v2/__generated__/PastAuctionsQuery.graphql.ts, src/v2/__generated__/PastAuctions_Test_Query.graphql.ts, src/v2/__generated__/PastAuctions_viewer.graphql.ts, src/v2/__generated__/UpcomingAuctionsQuery.graphql.ts, src/v2/__generated__/UpcomingAuctions_Test_Query.graphql.ts, src/v2/__generated__/UpcomingAuctions_viewer.graphql.ts, src/v2/__generated__/auctionsRoutes_Current_AuctionsQuery.graphql.ts, src/v2/__generated__/auctionsRoutes_Past_AuctionsQuery.graphql.ts, src/v2/__generated__/auctionsRoutes_Upcoming_AuctionsQuery.graphql.ts
Fixes: https://artsyproduct.atlassian.net/browse/GRO-296🔒 
We were sorting by started_at and that seemed to be pretty unintuitive. I'd asked on [#dev-help](https://artsy.slack.com/archives/CP9P4KR35/p1618428114451400)🔒 about `timely_at` which I found in [gravity](https://github.com/artsy/gravity/blob/a1e897656e368d142f0947d473f4346d7820c0ce/app/models/domain/sale.rb#L429)🔒. 
I just updated everything to reference that. This looks like what the [old page was doing](https://github.com/artsy/force/blob/2a20ca87f57f4ffcd0af6a3902f01baefe690900/src/mobile/apps/auctions/routes.coffee#L15).
=> Fix: Use timely sorting instead of start_at

src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter2.tsx
https://artsyproduct.atlassian.net/browse/FX-2819
In the case that custom filter inputs were currently supplied for **Size** or **Price**, those inputs were not being cleared in the UI when pressing the **Clear All** button. (They were cleared in the filter state, leading to a mismatch between actual artwork grid results and filter UI state.)
This adds a side effect to check that of the filter criteria have been reset, then local UI state should be cleared as well.
=> fix(filters): ensure Clear All button clears custom inputs as well

src/v2/Apps/Artist/ArtistApp.tsx, src/v2/Apps/ArtistSeries/ArtistSeriesApp.tsx, src/v2/Apps/Artists/ArtistsApp.tsx, src/v2/Apps/Artwork/ArtworkApp.tsx, src/v2/Apps/Auctions/AuctionsApp.tsx, src/v2/Apps/Components/AppShell.tsx, src/v2/Apps/Fair/FairApp.tsx, src/v2/Apps/Fair/FairSubApp.tsx, src/v2/Apps/Fairs/FairsApp.tsx, src/v2/Apps/Feature/FeatureApp.tsx, src/v2/Apps/Gene/GeneApp.tsx, src/v2/Apps/Partner/PartnerApp.tsx, src/v2/Apps/Search/SearchApp.tsx, src/v2/Apps/Show/ShowApp.tsx, src/v2/Apps/Show/ShowSubApp.tsx, src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx, src/v2/Apps/ViewingRoom/ViewingRoomsApp.tsx, src/v2/Components/FrameWithRecentlyViewed.tsx
[GRO-252] : This is to Consolidate `<Footer>` into single location inside of `<AppShell>`.
Currently a global search through force shows that we're importing the footer within every single `v2/Apps/<AppName>`. Since all of these apps share `<AppShell>`, the footer should live there, in one location, and all of the duplication can be removed. 
Went through and removed duplicated usage of `<Footer>` component, and verified that Footer component is still seen due to its inclusion in `<AppShell>`
[GRO-252]: https://artsyproduct.atlassian.net/browse/GRO-252
=> GRO-252 : Consolidate <Footer> into single location inside of <AppShell>

package.json, src/desktop/config.coffee, src/lib/braze.ts, src/lib/setup_sharify.js, src/typings/sharify.d.ts, src/v2/client.tsx, yarn.lock
This isn't done.
Will address: https://artsyproduct.atlassian.net/browse/GRO-260
There's a few pending questions:
- Where do we ultimately set this up? I've went through a naive implementation and set it up in client. It's global, initializes after the client, imports dynamically. There are some real tradeoffs (like it only works on new pages). 
- How does marketing plan to use braze and how might that mean we need to set it up? I've got this `braze.display.automaticallyShowNewInAppMessages()` snippet that should automatically show any configured app messages, but it none of the other target types are enabled.
=> First pass for braze sdk integration

src/v2/Apps/Partner/Routes/Works/index.tsx, src/v2/Apps/Partner/partnerRoutes.tsx, src/v2/__generated__/WorksQuery.graphql.ts, src/v2/__generated__/Works_partner.graphql.ts, src/v2/__generated__/partnerRoutes_WorksQuery.graphql.ts
JIRA:
- https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-3897&quickFilter=228
- https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-3896&quickFilter=228
- https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-3898&quickFilter=228
It is turned out that there is a ready component for artwork filters I can reuse, which will cover all the cards provided above. I checked that all things needed for works tab coincide with what this component offers and applied the component into
screenshots:
=> feat: PPP Works tab

src/v2/Components/Artwork/Details.tsx
This _should_ prevent the crash we're currently seeing on the upcoming auctions tab on the `/auctions` page.
=> Fix: Add guard for when sale_artwork is null to avoid crash

src/lib/braze.ts
I'd miss a call when initializing the braze SDK. Specifically you have to _manually_ indicate that a braze session is beginning. Given that we're currently invoking braze in [client.ts](https://github.com/artsy/force/blob/master/src/v2/client.tsx), that invocation will happen once and stay valid as they navigate between new pages in our routing infrastructure. If they navigate from a new page to an old page and back to a new page it'll re-activate their session, but so long as we have sane limits on how often we send messages they shouldn't get a retriggered in app message.
=> Fix: Call openSession to register a user's braze session

src/v2/Components/Footer.tsx
This is to resolve [GRO-278] .
Added in ACA Seller’s Agreement and redirect to the universal Footer component with a redirect to https://www.artsy.net/page/artsy-curated-auctions-listing-agreement
New Behavior: 
[GRO-278]: https://artsyproduct.atlassian.net/browse/GRO-278
=> GRO-278: Add Artsy Curated Auction consignments agreement to front end.

src/v2/Components/Authentication/EmailSubscriptionCheckbox.tsx, src/v2/Components/Authentication/TermsOfServiceCheckbox.tsx, src/v2/Components/Authentication/__tests__/Desktop/SignUpForm.jest.tsx
This is to update the Copy Script for the Onboarding Sign Up form [GRO-228].
Past behavior:
New behavior:
[GRO-228]: https://artsyproduct.atlassian.net/browse/GRO-228
=> GRO-228: Updated Copy Text for ToS and Subscription checkboxes

src/v2/Apps/Partner/PartnerApp.tsx
Initially, I used `inline-block` to fix margin collapsing on the partner profile page(https://github.com/artsy/force/pull/7403), but it looks like if the inline-block contains block with  `overflow: hidden` it adds some space after inline-block element. This PR uses `flex` instead of `inline-block`
JIRA - https://artsyproduct.atlassian.net/browse/PX-3984
Before:
Now:
=> fix(PX-3984): parent child margin collapsing

src/lib/braze.ts
I'm not seeing activations in the test braze campaign I setup. As I was digging around, a comment in their [setup examples for cdn](https://github.com/Appboy/appboy-web-sdk#alternative-cdn-installation) had a note about this [changeUser](https://js.appboycdn.com/web-sdk/3.2/doc/modules/appboy.html#changeuser) method. From my understanding this is the mechanism required to de-anonymize a user. 
The one question I have is if this maps to the artsy user id or the braze user id. From their docs it sounds like the former:
> Use this method to identify a user with a unique ID
=> feat: Let braze know the current user in the session

src/v2/Components/Footer.tsx
I noticed that the footer banner displayed on each page was not being
optimized. This change runs the banner through gemini reducing the
images size from ~220 kb to ~65 kb.
=> feature: Footer Banner Optimization

src/v2/Apps/Order/Routes/Status/index.tsx
Address: [PURCHASE-2577](https://artsyproduct.atlassian.net/browse/PURCHASE-2577)
This addresses the spacing issue for by MO messaging in Eigen (inquiry checkout).
We were previously using `<br>` to create spacing in the MO messaging. This didn't translate well in eigen. This PR switches to use `<Spacer />` that provides the correct spacing.
Because this is a webview I don't think we will be able to verify this until it actually merged, but below is an example of the correct spacing we want with `<Spacer />` used in another place in eigen.
=> fix: spacing issue in BNMO messaging

webpack/envs/clientProductionConfig.js, webpack/envs/commonEnv.js, webpack/plugins/bundleAnalyzer.js
At some point, the production source maps were misconfigured causing
source maps to be inlined in our assets essentially doubling their size.
Also, ensure that the bundle report uses the correct source maps.
=> fix: Webpack Source Maps

src/v2/Apps/Gene/Components/GeneArtworkFilter.tsx, src/v2/Apps/Gene/geneRoutes.tsx
Addresses [FX-2893]
[FX-2893]: https://artsyproduct.atlassian.net/browse/FX-2893
This PR updates the address bar when the filter state changes on the Gene page and applies filters from the address bar when loading the page.
=> feat: Sync filter state with url params on gene page

src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails.tsx, src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetailsPlaceholder.tsx
This PR fixes artwork carousel for Firefox.
JIRA - https://artsyproduct.atlassian.net/browse/PX-3967
Before: 
Now:
=> fix(PX-3967): add max width to the carousel container

src/v2/Apps/Artwork/ArtworkApp.tsx, src/v2/Apps/Collect/Routes/Collection/index.tsx, src/v2/Utils/Hooks/usePathnameComplete.ts, src/v2/Utils/Hooks/usePrevious.ts, src/v2/Utils/Hooks/useRouteComplete.ts
Closes: [FX-2869](https://artsyproduct.atlassian.net/browse/FX-2869)
So this is a follow up on https://github.com/artsy/force/pull/7386
The problem with calling reset (or creating a new event for this), is that it triggers changes in the deep compare effect outside of just the reset (which is possibly a bug?). It also updates the URL, etc. I couldn't think of a way to ignore that call without altering the state since it is tracked outside of the context component itself. Just updating the key is fine to re-initialize it IMO.
=> fix(fx-2869): reset context to prevent stale filter state

src/v2/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/Modal.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactorReminder.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/Mutation/EnableSecondFactor.ts, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Modal.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/__tests__/fixtures.ts, src/v2/__generated__/EnableSecondFactorMutation.graphql.ts
Feature to automatically show 2FA backup recovery codes after successful enrollment. Discussed in PR https://github.com/artsy/gravity/pull/13099. 
**TO-DOs:** 
- Add copy/download functionality on display modal.
**Considerations for future:**
- When I removed all 2FA options and reenrolled, I received the same recovery codes as the prior enrollment. I would expect that if I removed all 2FA accounts that the previous recovery codes would be deleted automatically. @joeyAghion I saw your and @dblandin's discussion on the linked PR but I'm thinking of slightly different use case. Specifically if a user enrolled in 2FA, then at some point disables it and never reenroll's. I think it's worth considering the value of  holding onto potentially sensitive data for a feature the User has chosen not …
=> Add 2FA recovery code display on enrollment

src/v2/Apps/Fair/fairRoutes.tsx
This PR moves the `FOLLOWED_ARTISTS` aggregation to inputs in order to make the followed artists available in the artists filter on the Fair Show page
=> fix: Artwork filter not showing followed artists for fairs

package.json, src/desktop/apps/auction/utils/__tests__/analyticsMiddleware.jest.ts, src/desktop/apps/auction/utils/analyticsMiddleware.ts, src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/v2/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.jest.tsx, src/v2/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx, src/v2/Components/v2/ArtworkFilter/index.tsx, yarn.lock
https://artsyproduct.atlassian.net/browse/FX-2850
↳ https://artsyproduct.atlassian.net/browse/FX-2913
Follow-up to https://github.com/artsy/cohesion/pull/184
Filter events on all artwork grids should now send their `current` and `changed` properties as JSON blobs, rather than as nested objects, which cause problems over in Redshift.
So this bumps Cohesion to v2 and —
- Uses the updated API for Cohesion's `commercialFilterParamsChanged` helper
- Update non-Cohesion events from auction results & auction artworks grid
This is how they look in Segment —
=> refactor(analytics): send JSON in filter change events

src/v2/Components/Footer/Footer.tsx
Addresses https://artsyproduct.atlassian.net/browse/GRO-314. 
Fixes a broken footer link.
=> bugfix: Fix broken footer link

src/v2/Apps/Components/AppShell.tsx, src/v2/Utils/Hooks/useAuthIntent/__tests__/useAuthIntent.jest.ts, src/v2/Utils/Hooks/useAuthIntent/index.ts, src/v2/Utils/Hooks/useAuthIntent/mutations/AuthIntentFollowArtistMutation.ts, src/v2/Utils/Hooks/useAuthIntent/mutations/AuthIntentFollowGeneMutation.ts, src/v2/Utils/Hooks/useAuthIntent/mutations/AuthIntentFollowProfileMutation.ts, src/v2/Utils/Hooks/useAuthIntent/mutations/AuthIntentSaveArtworkMutation.ts, src/v2/Utils/Hooks/useAuthIntent/mutations/types.ts, src/v2/Utils/openAuthModal.ts, src/v2/__generated__/AuthIntentFollowArtistMutation.graphql.ts, src/v2/__generated__/AuthIntentFollowGeneMutation.graphql.ts, src/v2/__generated__/AuthIntentFollowProfileMutation.graphql.ts, src/v2/__generated__/AuthIntentSaveArtworkMutation.graphql.ts
Closes: [FX-2894](https://artsyproduct.atlassian.net/browse/FX-2894)
This is a re-implementation of [this bit of code](https://github.com/artsy/force/blob/49b6a9b180398ae5a574a14902600bcf14f617a6/src/desktop/components/main_layout/client.coffee#L15-L35), which no longer runs on new pages post-novo.
A little on the verbose side — we should really just have a single polymorphic follow mutation? — but should be straightforward.
=> fix(fx-2894): fixes after authentication intent on novo pages

src/v2/Apps/Partner/Components/Carousel/Carousel.tsx, src/v2/Apps/Partner/Components/Carousel/DesktopCarousel.tsx, src/v2/Apps/Partner/Components/Carousel/MobileCarousel.tsx, src/v2/Apps/Partner/Components/Carousel/useRailOverflow.ts, src/v2/Apps/Partner/Components/Overview/ShowsRail.tsx, src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarousel.tsx, src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarouselPlaceholder.tsx
This PR refactor carousel that we use for the partner page. 
The carousel supports:
-  showing defined items count by using the `itemsPerViewport` field
- `onRailOverflowChange` callback that indicates is carousel rail overflowed(needs to show **See all** button)
Figma - https://www.figma.com/file/x78XGXMM1LhOdQY8TxkXkR/Partner-Profile?node-id=1072%3A0
=> refactoring: partner carousel

src/v2/Apps/Tag/Components/TagArtworkFilter.tsx, src/v2/Apps/Tag/Components/TagMeta.tsx, src/v2/Apps/Tag/TagApp.tsx, src/v2/Apps/Tag/__tests__/TagApp.jest.tsx, src/v2/Apps/Tag/tagRoutes.tsx, src/v2/__generated__/TagApp_Test_Query.graphql.ts, src/v2/__generated__/TagApp_tag.graphql.ts, src/v2/__generated__/TagArtworkFilterQuery.graphql.ts, src/v2/__generated__/TagArtworkFilter_tag.graphql.ts, src/v2/__generated__/TagMeta_tag.graphql.ts, src/v2/__generated__/tagRoutes_TagQuery.graphql.ts, src/v2/routes.tsx
This moves our `/tag/id` page over to the new framework:
=> feat: Port /tag to SSR framework

src/desktop/lib/webpackPublicPath.ts
We observed that below-the-fold images failed to load, while requests for asset paths matching `.../assets/novo-*.js` were `403`-ing. Those same files _are_ available under `.../assets-novo/...`.
Similar issues have bitten us a few times now (proving that if _any_ code runs only in production, that's exactly where bugs will happen). We should eliminate this environment-sensitive path-munging somehow, as mentioned in code comments.
=> Ensure newly modernized /tag/* pages can load asset bundles in production

src/mobile/apps/galleries_institutions/templates/index.jade, src/mobile/models/cover_image.coffee
The gallery pages mobile header ranges from 1 MiB to nearly 2 MiB, now it's under 50 KiB.
=> feature: Galleries Mobile Header

src/desktop/apps/about/client/view.coffee, src/desktop/apps/about/stylesheets/the_art_world_online.styl, src/desktop/apps/about/templates/sections/the_art_world_online.jade
All I did for this was track down where we were setting up that iPhone image on the about page and then cut out all the fancy stuff, haha. Then I just dropped in a static asset. Simple enough? 🤷 
https://artsyproduct.atlassian.net/browse/GRO-249
=> feat: Update iPhone image on about GRO-249

package.json, src/v2/Apps/Auctions/AuctionsApp.tsx, src/v2/Apps/Auctions/Components/AuctionArtworksRail/AuctionArtworksRail.tsx, src/v2/Apps/Auctions/Components/AuctionArtworksRailPlaceholder.tsx, src/v2/Components/Artwork/ShelfArtwork.tsx, yarn.lock
Various little mobile fixes:
- Make titles a bit smaller 
- Cap mobile image height at 250 
- Tighten up mobile carousel area to account for really tall images offscreen 
- Update palette so that carousel arrows don't show on mobile
=> fix: [Auctions] v3 mobile updates

src/v2/Apps/Partner/Components/PartnerShows/ShowPaginatedEvents.tsx, src/v2/Apps/Partner/Routes/Articles/index.tsx, src/v2/Apps/Partner/Routes/Shows/index.tsx, src/v2/__generated__/ShowPaginatedEventsQuery.graphql.ts, src/v2/__generated__/ShowPaginatedEventsRendererQuery.graphql.ts, src/v2/__generated__/ShowPaginatedEvents_partner.graphql.ts, src/v2/__generated__/Shows_partner.graphql.ts, src/v2/__generated__/partnerRoutes_ShowsQuery.graphql.ts
JIRA:
- [PPP: Articles: empty page is opened when clicking the same page again being on the first/last page on pagination](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4047&quickFilter=228)
- [PPP: Shows: infinite loading spinner is displayed when clicking any page on pagination](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4046&quickFilter=228)
- [PPP: Shows: 24 items are displayed instead of 40 per page + "Next" button is clickable on the last page of pagination in mobile view](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4039&quickFilter=228)
- Changed shows past events count to …
=> fix: shows and articles refetch bugs

src/desktop/apps/authentication/templates/reset_password.jade, src/desktop/apps/user/components/password/index.jade, src/mobile/apps/user/models/password_edit.coffee, src/mobile/apps/user/test/models/password_edit.test.js
On the password reset page and changing password in Settings, the user could enter in the password fields a minimum of 6 characters instead of the minimum of 8 characters, as it is written in another validation message. 
I changed the validation pattern that specifies a minimum of 8 characters and validation message
=> fix: Set minimum 8 characters for password input fields

src/v2/Apps/Auctions/Components/AuctionArtworksRail/AuctionArtworksRailArtworks.tsx, src/v2/Apps/Auctions/Components/AuctionArtworksRail/__tests__/AuctionArtworksRailArtworks.jest.tsx, src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/WorksByArtistsYouFollowRail.tsx, src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/__tests__/WorksByArtistsYouFollowRail.jest.tsx, src/v2/Apps/Auctions/Routes/CurrentAuctions.tsx, src/v2/Apps/Auctions/Routes/PastAuctions.tsx, src/v2/Apps/Auctions/Routes/UpcomingAuctions.tsx, src/v2/Apps/Auctions/Routes/__tests__/CurrentAuctions.jest.tsx, src/v2/Apps/Auctions/Routes/__tests__/PastAuctions.jest.tsx, src/v2/Apps/Auctions/Routes/__tests__/UpcomingAuctions.jest.tsx
Fixes https://sentry.io/organizations/artsynet/issues/2306340388/events/ee03fe7b10c54a41b87fd9c3c8e02d01/?project=28316&query=is%3Aunresolved+url%3A%22https%3A%2F%2Fwww.artsy.net%2Fauctions%22&statsPeriod=14d
Some users were reporting 500 errors. Not sure why, but a simple guard will protect against this.
=> bugfix: Guard against null edges

src/v2/Components/Artwork/SaveButton/index.tsx
Addresses https://artsyproduct.atlassian.net/browse/GRO-326 
The save button was passing click events down to the router link; it should stop the click on the save.
=> bugfix: [Auctions] Fix save on artwork

src/v2/Components/Artwork/ShelfArtwork.tsx
Fixes the immediate page crash. This doesn't feel like the correct fix because I'm assuming this may lead to broken looking UI. Worth taking a closer look at what to do with artworks without images when they are here. (Probably filtering them out completely?)
=> fix: guards on image in shelf artwork

src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx, src/v2/__generated__/BuyerGuaranteeIndexNonAdmin_Test_Query.graphql.ts, src/v2/__generated__/BuyerGuaranteeIndex_Test_Query.graphql.ts, src/v2/__generated__/BuyerGuaranteeIndex_authenticityImage.graphql.ts, src/v2/__generated__/BuyerGuaranteeIndex_headerImage.graphql.ts, src/v2/__generated__/BuyerGuaranteeIndex_moneyBackGuaranteeImage.graphql.ts, src/v2/__generated__/BuyerGuaranteeIndex_securePaymentImage.graphql.ts, src/v2/__generated__/buyerGuaranteeRoutes_BuyerGuaranteeQuery.graphql.ts
Additional QA fixes on Buyer Guarantee page:
- uses Vanity's static urls for page images
- Fixes some text misalignment
https://artsyproduct.atlassian.net/browse/PURCHASE-2620
https://artsyproduct.atlassian.net/browse/PURCHASE-2637
cc @artsy/purchase-devs
=> chore: updates Image urls to Vanity generated ones

src/v2/Apps/Components/AppShell.tsx, src/v2/Apps/Conversation/conversationRoutes.tsx, src/v2/Apps/Order/orderRoutes.tsx, src/v2/Artsy/Router/Route.tsx, src/v2/Artsy/Router/Utils/findCurrentRoute.tsx
This addresses an issue [reported in slack](https://artsy.slack.com/archives/C9YNS4X32/p1620837973240300) around the footer appearing on the conversations screen.
Add a new `hideFooter` prop to our route config that will hide the footer and apply it to /conversations and bnmo routes.
=> feat: [Route config] Add `hideFooter` option

src/v2/Apps/Partner/PartnerApp.tsx
This PR fixes the current partner page layout. The partner profile page has special scroll behavior for the header image, the solution described here: https://github.com/artsy/force/pull/7199#discussion_r600512091. In short, we use a fixed image and foreground which scrolls over it. As far as I see this PR https://github.com/artsy/force/pull/7497 broke partner page layout. To fix it I moved back `AppContainer` and `HorizontalPadding`. 
JIRA - https://artsyproduct.atlassian.net/browse/PX-4080
Before: 
Now:
=> fix(PX-4080): partner page layout

src/desktop/apps/partner2/components/fixed_cells_count_carousel/view.coffee
OK let this be a lesson to myself to actually look into errors that crop up in the smoke tests instead of dismissing them as spurious. I think this was sometimes passing because it was in the callback after an async action. I don't know _why_ this was actually undefined because this should be OK, but I'm not motivated enough to track down the root cause of an issue in a Backbone view that's going to get replaced in a week or two anyway.
=> fix(partner): fixes _ is not a function error

src/v2/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
This PR resolves [GRO-315.](https://artsyproduct.atlassian.net/browse/GRO-315).
This PR fixes the hit area size of the backLink button in MobileNavMenu panes. Now the hit area of the button has a larger tap surface what is important for UX.
(https://user-images.githubusercontent.com/83413732/118157093-cc099580-b422-11eb-8cca-6b71a2cf0b0d.jpeg)
=> fix(GRO-315): navigation button hit area size in MobileNavMenu panes

src/v2/Apps/Fair/FairApp.tsx, src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
Addresses https://artsyproduct.atlassian.net/browse/FX-2921 
This removes the related articles header section on the page, as it was leading to strange whitespace issues.
=> fix: [fair/:id] remove related articles header to remove whitespace

src/v2/Apps/Auctions/AuctionsApp.tsx
Accidentally deleted the `h1` tag yesterday when i was doing some cleanup: 
https://app.circleci.com/pipelines/github/artsy/integrity/6937/workflows/935452c4-e6f6-4de2-80c6-7ef6ffd84e76/jobs/33784
=> fix: [Auctions] add missing h1

src/desktop/public/.well-known/assetlinks.json
This file is needed in order to make artsy.net links open in the Android app
=> feat: add assetlinks file for android deep links

src/v2/Apps/Partner/Components/Overview/SubscriberBanner.tsx, src/v2/Apps/Partner/Routes/Overview/index.tsx, src/v2/__generated__/Overview_partner.graphql.ts, src/v2/__generated__/SubscriberBanner_partner.graphql.ts, src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts
JIRA -> [Update Top Banner on Overview page for non-subscribing partners](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4022&quickFilter=228)
**Attention**
I used `hasFairPartnership ` field so far to distinguish `fair` partners from `churned`. I am not completely sure if it is the right field.
This is a link to discussion with Sarah and Oksana about that -> [Should I use `hasFairPartnership`? ](https://artsy.slack.com/archives/C01NW1YSDPF/p1620919437034500)
=> feat: create top banner for non subscriber

src/v2/Apps/Partner/Components/Overview/ShowBannersRail.tsx
This PR fixes showing progress dots for the partners with the only one available show.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4101
Before
Now
=> fix(PX-4101): hide dots for if only one show visible

src/v2/Apps/Artist/ArtistApp.tsx, src/v2/Apps/Artwork/ArtworkApp.tsx, src/v2/Apps/Auctions/AuctionsApp.tsx, src/v2/Apps/Collect/Routes/Collect/index.tsx, src/v2/Apps/Search/SearchApp.tsx, src/v2/Components/Artwork/Details.tsx, src/v2/Components/FrameWithRecentlyViewed.tsx, src/v2/Components/RecentlyViewed/RecentlyViewed.tsx, src/v2/Components/RecentlyViewed/RecentlyViewedPlaceholder.tsx, src/v2/Components/RecentlyViewed/RecentlyViewedV2.tsx, src/v2/Components/RecentlyViewed/RecentlyViewedV2Placeholder.tsx, src/v2/Components/RecentlyViewed/index.tsx, src/v2/Components/__tests__/__snapshots__/Artwork.jest.tsx.snap, src/v2/Utils/Hooks/useLazyLoadComponent.tsx, src/v2/__generated__/RecentlyViewedV2Query.graphql.ts, src/v2/__generated__/RecentlyViewedV2_me.graphql.ts, src/v2/__generated__/RecentlyViewed_me.graphql.ts
Closes: [DSWGW-58](https://artsyproduct.atlassian.net/browse/DSWGW-58)
Implements a V3 version of `RecentlyViewed` — also changes how we do the placeholder for these.
Previously we would have a weirdly placed loading spinner, then the component would pop in. Now there's an appropriately sized placeholder. One thing to note is that if you *haven't* recently viewed anything then you'll see the placeholder which will then pop _out_. Since we only show these to logged in users and a logged in viewer is pretty likely to have looked at at least one artwork, I figure that it's more appropriate to include the placeholder than not.
I also refactored the lazy-loading into the component itself since we lazy-load it in all cases that it appears.
=> feat: converts recently viewed to v3

src/desktop/apps/sitemaps/helpers.ts
Add Buyer Guarantee route to SEO sitemap.
https://artsyproduct.atlassian.net/browse/PURCHASE-2657
=> chore: add buyer guarantee route to seo sitemap

src/v2/Apps/Collect/Routes/Collection/Components/Header/index.tsx
This wraps our `collection/id` header text in a read more component:
=> feat: Wrap collection/id header text in ReadMore

src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
Fixes the width of the Learn More button in iPad sized screens and opens page in new tab instead.
Before:
After:
https://artsyproduct.atlassian.net/browse/PURCHASE-2694
https://artsyproduct.atlassian.net/browse/PURCHASE-2654
=> fix: resizes buttons on md breakpoints + open link in new tab

docs/best_practices.md, src/v2/DevTools/setupTestWrapper.tsx
Add some light docs about how we can't test `QueryRenderer`s with our Relay test tools, but rather need to extract the contents of the `QueryRenderer` into a Relay fragment-like container and then test that. 
See the `SoldRecently` [component](https://github.com/artsy/force/blob/daad34183723be649e6031859842d65f4d902c21/src/v2/Apps/Consign/Routes/MarketingLanding/Components/SoldRecently.tsx#L143) and [test](https://github.com/artsy/force/blob/daad34183723be649e6031859842d65f4d902c21/src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SoldRecently.jest.tsx) for an example of this pattern.
=> docs: Update relay test docs with note about QueryRenderer

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx, src/v2/__generated__/NavigationTabs_Test_PartnerQuery.graphql.ts, src/v2/__generated__/NavigationTabs_partner.graphql.ts, src/v2/__generated__/PartnerApp_Test_Query.graphql.ts, src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts
JIRA -> [PPP: Works tab remains visible after turning it off in CMS](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4098&quickFilter=228)
Added hidden property to Works tab route. From now the works tab won't display if it is turned off via CMS
=> fix: display works tab fix

src/v2/Apps/Order/Components/OrderStepper.tsx, src/v2/Apps/Order/OrderApp.tsx
[PURCHASE-2682]
Recently the margins have changed in the web view of checkout. The content is far more squared and would like to use as much as the width of the phone screen. Confirmed with Arvind that the order stepper margins should be the same as the page content.
Pretty sure this regression was caused by [this PR](https://github.com/artsy/force/commit/4bea40764b1a9387a5a6514c8bfa8fd76015d72b)
_Before:_
_After:_
[PURCHASE-2682]: https://artsyproduct.atlassian.net/browse/PURCHASE-2682
=> fix: Adjust margins on order flow screens

src/v2/Apps/Partner/Components/Overview/ArtworksRail.tsx, src/v2/Apps/Partner/Components/Overview/ShowBannersRail.tsx, src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetails.tsx, src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetailsList/PartnerArtistDetailsList.tsx, src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtists.tsx, src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarousel.tsx, src/v2/Apps/Partner/Components/PartnerShows/ShowPaginatedEvents.tsx
This PR replaces all QueryRenderer components with SystemQueryRenderer for the Partner Profile page. From time to time we had some render issues that I think were related to `QueryRenderer` that runs on the server side.
Pay attention to progress dots:
=> fix: use SystemQueryRenderer instead of QueryRenderer

src/desktop/components/split_test/middleware.coffee, src/desktop/components/split_test/running_tests.coffee, src/desktop/config.coffee, src/lib/middleware/__tests__/pageCache.jest.ts, src/lib/middleware/pageCache.ts, src/middleware.ts, src/v2/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx, src/v2/Apps/Artist/artistRoutes.tsx, src/v2/Artsy/Analytics/__tests__/trackingMiddleware.jest.ts, src/v2/Artsy/Analytics/trackExperimentViewed.tsx, src/v2/Artsy/Analytics/trackingMiddleware.ts, src/v2/Artsy/Router/buildClientApp.tsx, src/v2/Components/ArtworkFilter/Utils/isDefaultFilter.tsx
Reverts artsy/force#7520
We might bring some parts of this back (like the experiment viewed event stuff), but for now, we can cleanly revert to disable the AB test and 'new default sort' behavior.
=> Revert "feat: setup AB test for a new default sort on the artist page"

src/v2/Apps/Components/AppShell.tsx
This PR fixes the cover image for the partner profile page. Used `Flex` to stretch the white background for the footer.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4097
before:
now:
=> fix(PX-4097): fix cover image

src/desktop/public/.well-known/assetlinks.json
Our current assetLinks.json file is using a debug sha256 and we should instead use a release sha256. It's safe to host this publicly as this is the standard for hosting assetLinks.json files. Similar files can be seen here https://digitalassetlinks.googleapis.com/v1/statements:list?source.web.site=https://youtube.com&relation=delegate_permission/common.handle_all_urls
=> fix: use the right SHA256 on release builds

src/v2/Apps/Partner/Components/Overview/ArtworksRail.tsx, src/v2/Apps/Partner/Components/Overview/ShowBannersRail.tsx, src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetails.tsx, src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetailsList/PartnerArtistDetailsList.tsx, src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtists.tsx, src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarousel.tsx, src/v2/Artsy/Relay/SystemQueryRenderer.tsx
This PR adds a placeholder for the system query renderer. The placeholder field uses for rendering skeleton spinners at the server time to prevent some content blinking. 
Before:
Now:
=> feat: add placeholder for system query renderer

src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetails.tsx, src/v2/__generated__/PartnerArtistDetailsListQuery.graphql.ts, src/v2/__generated__/PartnerArtistDetailsListRendererQuery.graphql.ts, src/v2/__generated__/PartnerArtistDetailsQuery.graphql.ts, src/v2/__generated__/PartnerArtistDetails_partnerArtist.graphql.ts
This PR uses artworkConnection from the partnerArtist type for loading the artist's artworks in the right order.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4015
=> fix(PX-4015): use partnerArtist artwork connection for loading artist's artworks in the right order

src/v2/Apps/Artists/Components/ArtistsLetterNav.tsx, src/v2/Components/NavBar/Menus/DropDownMenu/DropDownMenu.tsx, src/v2/Components/NavBar/Menus/DropDownMenu/DropDownSection.tsx, src/v2/Components/NavBar/Menus/DropDownMenu/__tests__/DropDownMenu.jest.tsx, src/v2/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
This is a draft PR for https://artsyproduct.atlassian.net/browse/GRO-85
**Desktop**
Added letters and aligned _View all artists_ and _Browse by name_ lines
**Before**
**After**
**Mobile**
https://www.figma.com/file/an2fT6dBetfEB7FaLUbpir/Navigation?node-id=174%3A0 
**Before**
**After**
=> Added A-Z letters to artists nav bar on hover

src/v2/Apps/BuyerGuarantee/Components/Feature.tsx, src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
This PR addresses two issues from [PURCHASE-2699]:
1. It adds 20 pixels of padding on either side of the Artsy Guarantee Table so that it does not edge to the grey borders.
2. On Desktop it forces a line break for the Money-Back Guarantee passage. ‘we’ll work with you to make it right.'
[PURCHASE-2699]: https://artsyproduct.atlassian.net/browse/PURCHASE-2699
=> fix: add padding and line break to buyer guarantee page

src/v2/Apps/Partner/partnerRoutes.tsx, src/v2/__generated__/partnerRoutes_WorksQuery.graphql.ts
JIRA -> [Add redirection logic for works tab. If no artworks or CMS field for works tab display is false it should redirect to the overview page](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4098&quickFilter=228)
=> fix: add redirection logic for works page

src/v2/Apps/Partner/Components/Overview/AboutPartner.tsx, src/v2/Apps/Partner/Components/Overview/SubscriberBanner.tsx, src/v2/Apps/Partner/Components/__tests__/Overview/AboutPartner.jest.tsx
JIRA -> [Displayed only `About` title in about section of overview page](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4121&quickFilter=228)
We have a logic of displaying partners bio in about section:
- `bio` field - shorted version of partners bio for displaying on mobile version
- `full_bio` field - full version for displaying on PC
This PR adjusted the logic of displaying bio and full_bio in about section in the following way:
- display `bio` version on PC if `full_bio` is null
- display `full_bio` version on mobile if `bio` is null
=> fix: PPP overview about section

hokusai/development.yml, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/Modal.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Modal.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx, src/v2/Components/UserSettings/TwoFactorAuthentication/helpers.ts, src/v2/Utils/url.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-3340
We are going to redirect partners from CMS to Force to setup their 2FA (if they are required to but haven't yet) like so:
`https://www.artsy.net/user/edit?after_update=https%3A%2F%2Fcms.artsy.net%3A%2Fauth%2Fartsy#two-factor-authentication`
After they finish setting up 2FA, we would like them redirected to the URL encoded in `after_update` param (back to `https://cms.artsy.net/auth/artsy`).
This PR adds a 2FA setup completion modal specifically for these users. On completion, they are informed that they will be redirected to `after_update` URL.
The URL is sanitized to prevent rogue redirects (such as to www.evilsite.com, ...)
Changes to `hokusai/development.yml` are to get `hokusai dev` working.
Screenshots of new modal:
=> feat: 2FA respect after_update param.

src/v2/Components/UserSettings/TwoFactorAuthentication/__tests__/helpers.jest.ts, src/v2/Utils/__tests__/url.jest.ts
@sweir27 looked over https://github.com/artsy/force/pull/7626 and suggested testing the helper functions, and walked me through! Thanks @sweir27 !
=> feat: tests for pr#7626 (2FA respect after_update param).

src/v2/Components/Authentication/TermsOfServiceCheckbox.tsx, src/v2/Components/Footer/Footer.tsx
This is to address the bug that is being seen for Sign Up Flow in QA.
Seeing: `I agree to the Terms of Use, Privacy Policy, and Conditions of Saleand to receiving emails from Artsy.`
=> GRO-180: Fixing Spacing for Sign Up Flow

src/v2/Apps/Partner/partnerRoutes.tsx
JIRA -> [PPP: Non-subscribers: Overview: partners page is opened without scrolling to the top when clicking any gallery from "Galleries nearby" section](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4168&quickFilter=228)
before:
after:
=> fix: Overview page. Scroll to top after clicking on gallery rail card

src/desktop/components/split_test/running_tests.coffee, src/desktop/components/split_test/splitTestMiddleware.ts, src/desktop/config.coffee, src/lib/middleware/__tests__/pageCache.jest.ts, src/lib/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts, src/lib/middleware/pageCache.ts, src/middleware.ts, src/typings/sharify.d.ts, src/v2/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx, src/v2/Apps/Artist/artistRoutes.tsx, src/v2/Artsy/Analytics/__tests__/trackingMiddleware.jest.ts, src/v2/Artsy/Analytics/trackExperimentViewed.tsx, src/v2/Artsy/Analytics/trackingMiddleware.ts, src/v2/Artsy/Router/buildClientApp.tsx, src/v2/Components/ArtworkFilter/Utils/isDefaultFilter.tsx
Reverts artsy/force#7638
Queueing this up now so we can just merge it when we're ready — should be any moment now.
I think this is all there is to it, right @mzikherman? Though — if we do this via revert, we'll end up recommitting some code that we wanted to remove, correct?
=> chore(merch): end the A/B experiment [WIP]

src/desktop/components/split_test/running_tests.coffee, src/desktop/components/split_test/splitTestMiddleware.ts, src/desktop/config.coffee, src/lib/middleware/__tests__/pageCache.jest.ts, src/lib/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts, src/lib/middleware/pageCache.ts, src/middleware.ts, src/typings/sharify.d.ts, src/v2/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx, src/v2/Apps/Artist/artistRoutes.tsx, src/v2/Artsy/Analytics/__tests__/trackingMiddleware.jest.ts, src/v2/Artsy/Analytics/trackExperimentViewed.tsx, src/v2/Artsy/Analytics/trackingMiddleware.ts, src/v2/Artsy/Router/buildClientApp.tsx, src/v2/Components/ArtworkFilter/Utils/isDefaultFilter.tsx
Reverts artsy/force#7635
Properly this time 😅 — see [thread](https://artsy.slack.com/archives/CP9P4KR35/p1622580534276900)
This is a follow-up to https://github.com/artsy/force/pull/7672 which 
- inadvertently reverted the Deploy PR rather than the feature-branch PR
- thus resulted in an immediate production deploy to close the the A/B (which is ok)
- resulted in `master`+`staging` being out of sync with `release` (which is not ok)
=> chore(merch): close the A/B experiment, again

src/v2/Apps/Order/Routes/Accept/index.tsx, src/v2/Apps/Order/Routes/NewPayment/index.tsx, src/v2/Apps/Order/Routes/Offer/index.tsx, src/v2/Apps/Order/Routes/Payment/index.tsx, src/v2/Apps/Order/Routes/Shipping/index.tsx
Addresses: [https://artsyproduct.atlassian.net/browse/PURCHASE-2671](https://artsyproduct.atlassian.net/browse/PURCHASE-2671)
This ensures the margin about the "Continue" button is consistent.
**Shipping**
**Payment**
=> fix: ensure spacing is consistent above continue button

src/v2/Apps/BuyerGuarantee/Components/Feature.tsx
This PR adds a double bang in the condition render as a correction to this PR https://github.com/artsy/force/pull/7633.
=> fix: add double bang to conditional render

src/v2/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
This PR resolves [PX-3737]
Added text and link to Help Center to the modal that displays when you click on "Certificate of Authenticity" to the right of the artwork.
[PX-3737]: https://artsyproduct.atlassian.net/browse/PX-3737
=> feat(PX-3737): update COA copy in modal on Artwork Page

src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
Quick followup to #7661 to use `https` urls from Vanity instead of `http` as they caused the images to not render on Staging and Production.
Bug:
Fix:
=> fix: use https over http for static image urls

src/v2/Apps/Auctions/Routes/CurrentAuctions.tsx, src/v2/Apps/Auctions/Routes/PastAuctions.tsx, src/v2/Apps/Auctions/Routes/UpcomingAuctions.tsx, src/v2/__generated__/CurrentAuctions_Test_Query.graphql.ts, src/v2/__generated__/CurrentAuctions_viewer.graphql.ts, src/v2/__generated__/PastAuctions_Test_Query.graphql.ts, src/v2/__generated__/PastAuctions_viewer.graphql.ts, src/v2/__generated__/UpcomingAuctions_Test_Query.graphql.ts, src/v2/__generated__/UpcomingAuctions_viewer.graphql.ts, src/v2/__generated__/auctionsRoutes_Current_AuctionsQuery.graphql.ts, src/v2/__generated__/auctionsRoutes_Past_AuctionsQuery.graphql.ts, src/v2/__generated__/auctionsRoutes_Upcoming_AuctionsQuery.graphql.ts
We were noticing some performance problems around there being too many items on the dom. This lowers things to 10, and the user can click load more.
=> fix: Lower auction count on first load to 10

src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
Don't check for `user` when displaying VR content
=> hotfix: show viewing room content when logged out

Dockerfile
Remove references to `novo` from the Dockerfile.
=> chore: Dockerfile Cleanup

src/desktop/apps/auction_support/routes.coffee, src/desktop/apps/auction_support/test/routes.test.js, src/desktop/apps/authentication/client/reset_password.coffee, src/desktop/apps/authentication/index.ts, src/desktop/apps/notifications/routes.coffee, src/desktop/apps/notifications/test/routes.test.js, src/desktop/apps/user/components/password/view.coffee, src/desktop/apps/user/routes.coffee, src/desktop/apps/user/test/routes.test.js, src/desktop/components/fair_layout/templates/user.jade, src/desktop/components/fair_layout/test/templates/nav.test.js, src/desktop/components/main_layout/footer/mobile_footer_menu.jade, src/mobile/apps/favorites_following/routes.coffee, src/mobile/apps/favorites_following/test/routes.test.js, src/mobile/apps/user/routes.coffee, src/mobile/apps/user/test/routes.test.js, src/mobile/components/layout/templates/login-signup.jade, src/mobile/components/sanitize_redirect/test/index.test.js, src/v2/Apps/Auction/__tests__/routes.jest.ts, src/v2/Apps/Auction/getRedirect.ts, src/v2/Components/LoginSignUpBanner/Banner.tsx, src/v2/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.jest.tsx, src/v2/Utils/openAuthModal.ts
Back in https://github.com/artsy/force/pull/6969, the `/log_in` path started being redirected to `/login` for consistency. I believe this broke the intended behavior where logging in would redirect the user back to a specified URL.
In this PR, I try to update all the locations I could find that direct a visitor to `/log_in` to instead send them to `/login` directly, saving a redirect step. For good measure (and in case there are links to `/log_in?...` out there in our apps or the wild), I also update that internal redirect to pass the querystring through. When I updated links that used legacy querystring parameters like `redirect_uri`, I also switched them to `redirectTo` which seems to be our [current preference](https://github.com/artsy/force/blob/62646da8d4b62943566bba6e4fcc4313606a61f2 …
=> Preserve querystrings when redirecting to /login or /signup paths (PLATFORM-3341)

src/v2/Apps/Components/AppShell.tsx, src/v2/Components/AuthBanner.tsx, src/v2/Components/NavBar/NavBar.tsx, src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
So — since I moved this to the NavBar it was appearing on legacy pages too. Moved it back and will address some other issues tomorrow. This just prevents the doubling so that we can get a deploy in tonight.
One thing to note that is for sure a problem: on legacy pages we actually don't have a position fixed nav — this is fine but I'm assuming we would want to collapse this too as you scroll. The logged out view on a small phone is going to have a *tiny* screen area if we don't.
=> fix(navbar): prevents doubled auth buttons

src/v2/Apps/Order/OrderApp.tsx, src/v2/Apps/Order/__tests__/OrderApp.jest.tsx, src/v2/__generated__/OrderApp_order.graphql.ts, src/v2/__generated__/orderRoutes_OrderQuery.graphql.ts
Zendesk collector chat within Checkout flow regardless of price. Previously we only rendered the chat option when the artwork price was over $10,000 USD or its equivalent.
https://artsyproduct.atlassian.net/browse/PURCHASE-2693
=> chore: render Zendesk chat in checkout flow regardless of artwork price

src/desktop/components/clock/index.styl
The countdown on fair organizer pages looks  off. It looks like the letters/numbers are too close to each other. These pages are promoted widely by fair organizers.
https://artsyproduct.atlassian.net/browse/FX-2709
**Before**
**After**
=> fix: modified styles for countdown items

src/v2/Components/ArtistSeriesRail/ArtistSeriesItem.tsx
Reenables lazy image loading now that https://github.com/artsy/force/pull/7739 is in.
=> fix: Re-enable lazy load on Series rail

package.json, src/v2/Components/__tests__/__snapshots__/Artwork.jest.tsx.snap, src/v2/Components/__tests__/__snapshots__/Input.jest.tsx.snap, src/v2/Components/__tests__/__snapshots__/PasswordInput.jest.tsx.snap, src/v2/Components/__tests__/__snapshots__/QuickInput.jest.tsx.snap, src/v2/jest.envSetup.ts, yarn.lock
This upgrades styled-components to the latest: https://medium.com/styled-components/announcing-styled-components-v5-beast-mode-389747abd987.
Note this _does not_ update the typescript types package as that leads to a cascade of insane errors (even though styled-components 5 is backwards compatible with 4). Will take another look at this in a follow-up, as the priority in this PR is to increase performance:
- 26% smaller bundle size (16.2kB vs. 12.42kB min+gzip)
- 22% faster client-side mounting 
- 26% faster updating of dynamic styles
- 45% (!!!) faster server-side rendering
=> lib: Upgrade styled-components@5.x

src/v2/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx, src/v2/Components/ImageLink.tsx
This adds lazy loading to a few image areas that didn't have it before:
- /collect (the top collections images) 
- artwork grid: before the first 8 immediately loaded, but no reason to do that
=> fix: More lazy loading on images

src/v2/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx, src/v2/Apps/Artwork/Components/OtherWorks/index.tsx, src/v2/Apps/FeatureAKG/Components/SelectedWorks.tsx, src/v2/Apps/WorksForYou/WorksForYouFeed.tsx, src/v2/Components/ArtworkGrid/ArtworkGrid.tsx, src/v2/Components/ImageLink.tsx
Fixes a bug from https://github.com/artsy/force/pull/7751 where the lazy loaded image on /collect collapsed the height during loading. Also some light simplification.
=> bugfix: [Collect] Fix image lazy load

src/v2/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx, src/v2/Components/ArtistMarketInsights.tsx, src/v2/Components/SelectedCareerAchievements.tsx
Career highlights and auction results records are rounding up to next million making the record inaccurate, this is the quick fix which is to add an extra decimal to the display $7m -> $6.5m
=> fix: add extra decimal to fix rounding issue

cypress/integration/about.spec.ts, cypress/integration/article.spec.ts, cypress/integration/articles.spec.ts, cypress/integration/artistSeries.spec.ts, cypress/integration/artists.spec.ts, cypress/integration/auction.spec.ts, cypress/integration/auctions.spec.ts, cypress/integration/campaign.spec.ts, cypress/integration/consign.spec.ts, cypress/integration/contact.spec.ts, cypress/integration/fair.spec.ts, cypress/integration/fairs.spec.ts, cypress/integration/feature.spec.ts, cypress/integration/galleries.spec.ts, cypress/integration/gene.spec.ts, cypress/integration/institutions.spec.ts, cypress/integration/jsonPage.spec.ts, cypress/integration/search.spec.ts, cypress/integration/tag.spec.ts, cypress/integration/viewingRoom.spec.ts, cypress/integration/viewingRooms.spec.ts, cypress/tsconfig.json
1. We have a smoke test suite in [integrity](https://github.com/artsy/integrity) that is good at identifying bugs! However, the integrity suite doesn't run on force builds, so it is not effective at blocking merges that may include errors. (Someone has to explicitly check the output).
2. Force's own smoke test suite is pretty anemic and doesn't have full coverage.
3. It's a little confusing to have the same tests in both integrity and in force, especially since both instances query the same environment (staging!).
- This PR moves all of the smoke tests from integrity into force. An eventual follow up will remove the smoke tests from integrity entirely.
- See the notes below: A few are disabled.
- A few of the tests are failing (disabled via `.skip` and with corresponding `//TODO:` …
=> Adds cypress smoketests from integrity

.circleci/config.yml, dangerfile.ts, package.json, src/v2/test.tsx, yarn.lock
Addresses https://artsyproduct.atlassian.net/browse/WP-44
This adds a new Danger rule that guards against the use of the default `<QueryRenderer />`, and instead directs devs to use our `<SystemQueryRenderer />`. 
Why? 
The regular `<QueryRenderer />`, which should only fire on the client, will double fetch during our server-side render pass since the network layer is shared.
=> toolchain: [Danger] Add guard to protect against <QueryRenderer> imports 

dangerfile.ts
Addresses https://artsyproduct.atlassian.net/browse/WP-55 
In an effort to be more diligent about adding smoke tests, trigger a danger warning whenever the [`v2/routes.ts`](https://github.com/artsy/force/blob/master/src/v2/routes.tsx) file changes. (This generally only happens when new routes are being added.)
=> toolchain: Add danger rule warning about routes smoke test

src/v2/Components/FollowButton/FollowArtistButton.tsx
Minor thing I noticed looking into the integrity failure. I don't believe this is related to that failure, but 🤷
=> fix: prevents popover from showing unless you are logged in

src/v2/Apps/Fair/Routes/FairArtworks.tsx, src/v2/Apps/Fair/fairRoutes.tsx
Added location filter to fair artworks
Jira: [FX-2994]
**Before**
*filters without location filter*
**After**
[FX-2994]: https://artsyproduct.atlassian.net/browse/FX-2994
=> feat(FX-2994): location filter at fair artworks filters

src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx
Updated deps for `ConfirmArtworkModal` to use `System` instead of `Artsy` as per [this](https://github.com/artsy/force/pull/7769#discussion_r651158340) comment.
=> fix: Updated ConfirmArtworkModal deps to system instead of artsy

src/v2/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx, src/v2/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.jest.tsx
This PR updates our artwork structured data components to switch from `Product` to `CreativeWork` when we don't have price info. The ticket called for suppression of the structured data altogether, but I chatted with Jenna and we decided there was still some value to running the more generic type here.
I tried really hard to verify this fix prior to creating a PR, but for whatever reason the [Rich Results Test](https://search.google.com/test/rich-results) does not like ngrok URLs, haha. Furthermore, staging can't be tested either because we block robots:
```
jon@juggernaut:~/code/force(master)% http https://staging.artsy.net/robots.txt --body
User-agent: *
Disallow: /
```
So then I updated my local env file to allow robots but it still didn't work, probably because of whatever shenanigans …
=> feat: Suppress product artwork schema GRO-360

src/v2/Apps/Conversation/Components/Item.tsx
fixes https://artsyproduct.atlassian.net/browse/PURCHASE-2741
Change styles to limit the width of an artwork image in conversation to fit a narrow viewport
=> fix: Fix cropping artwork in narrow viewport (PURCHASE-2741)

src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
Addresses [CX-1601]
Fixes the layout issue by hiding the news article navigation and sets the top margin to `0` on Eigen.
[CX-1601]: https://artsyproduct.atlassian.net/browse/CX-1601
=> fix: news articles layout on Eigen

src/v2/Components/Authentication/Desktop/SignUpForm.tsx
After some non-zero amount of panic that maybe we leaked user passwords, we discovered that a cohort of users had entered their password into the name field. 😝 
It's understandable because so many sign up forms ask you to enter and then re-enter your password so people are probably just really used to that flow. So then all this PR does is pull that name field up to first place. Our theory is that this change will prevent users from making this mistake in the future. It's also more natural to ask for name first.
More chatter here:
https://artsy.slack.com/archives/CTZA5NBB9/p1617135285003100
https://artsyproduct.atlassian.net/browse/GRO-269
/cc @artsy/grow-devs @isakelaris
=> feat: Rearrange sign up field order GRO-269

src/v2/Components/Authentication/TermsOfServiceCheckbox.tsx
https://artsyproduct.atlassian.net/browse/GRO-359
~This change sets the Terms of Service checkbox link underline behavior to default which displays underlines under links.~
This change removes Terms of Service checkbox link `underlineBehavior` prop which defaults to links having andunderline.
:
| `underlineBehavior=default`  |  prop removed |
|---|---|
| GDPR sign up modal <img width="328" alt="Screen Shot 2021-06-15 at 1 54 15 PM" src="https://user-images.githubusercontent.com/29984068/122105479-d1be1680-cde6-11eb-90fc-5e68173ff274.png"> | GDPR sign up modal <img width="328" alt="Screen Shot 2021-06-15 at 3 43 55 PM" src="https://user-images.githubusercontent.com/29984068/122114136-f1f2d300-cdf0-11eb-9472-237588f13de3.png"> |
| US sign up modal <img width="326" alt="Screen Shot …
=> fix: TOS checkbox links (GRO-359)

docs/best_practices.md
Per [this slack discussion](https://artsy.slack.com/archives/CP9P4KR35/p1623792192103600), wanted to add some docs to our FAQ about adding global script tags.
=> docs: Add info about adding global script tags

src/v2/Apps/Order/Components/AddressModal.tsx, src/v2/Apps/Order/Components/SavedAddressItem.tsx, src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx, src/v2/Components/Address/AddressModalFields.tsx
Updated design for address form
JIRA: https://artsyproduct.atlassian.net/browse/PX-4133
While I was working on this task, I had two questions:
1) How I can set modal width like in Figma ? ("618px").  Is it necessary? Because I can only choose from the available values:
`export declare enum ModalWidth {
Narrow = "300px",
Normal = "440px",
Wide = "900px"
}`
or I can set `isWide` prop.
2) In Figma all input titles are bold. But I think I can't set bold prop into input title by using `Input` props... If needed bold font like in Figma, I can delete `title="Address Line 1"` and create `<Text variant="mediumText">Address Line 1</Text>`
But I think separating title from Input is bad practice. What should I do in the end?
=> feat(PX-4133): Collector sees updated address form styling

src/v2/Apps/Artwork/Components/ArtworkMeta.tsx, src/v2/Components/Lightbox/Lightbox.tsx, src/v2/Components/Lightbox/__tests__/Lightbox.jest.tsx
This PR adds a preload tag for the default artwork image.
I figured what you see here in this diff would be all that's required for this task, but I'm confused because the image urls don't match:
```js
$('img[data-is-default=true]').src
"https://d32dm0rphc51dk.cloudfront.net/RtSWWtWGDI11QPzBuW4dsA/large.jpg"
$('link[as=image]').href
"https://d196wkiy8qx2u5.cloudfront.net/?resize_to=fit&width=640&height=394&quality=80&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FRtSWWtWGDI11QPzBuW4dsA%2Flarge.jpg"
```
So there's something where the image url I have access to is a meta image? @dzucconi do you know what's going on here?
https://artsyproduct.atlassian.net/browse/GRO-382
=> feat: Preload default artwork image to speed up LCP GRO-382

src/lib/analytics/sentryFilters.ts, src/lib/setupSentryClient.ts
Following the guide [in the docs](https://docs.sentry.io/platforms/javascript/configuration/filtering/#decluttering-sentry), it looks like we can allow-list urls for sentry logging. 
For now, lets only look for errors from `artsy.net` and `cloudfront` (which hosts our .js assets). 
```js
const ALLOWED_URLS = [
/(.*).?artsy.net/i, 
/(.*).?cloudfront.com/i
]
```
There's the potential risk that we might be covering up an issue from our 3rd-party scripts, but in practice we would see if those scripts weren't loading just by looking in our browser inspector (which folks have open all the time) and most errors that we're seeing in Sentry originate from deeply buried stack-traces from those libs.
Some examples:
- https://sentry.io/organizations/artsynet/issues/2460352029/?project=28316&query=is%3 …
=> chore: Move sentry url filter to allow-list

src/desktop/components/main_layout/templates/scripts.jade, src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx, src/v2/Components/ZendeskWrapper.tsx
As a followup to #7780 the Zendesk scripts were being mounted twice on some auctions pages, this PR is a fix for that and should wrap up the work for https://artsyproduct.atlassian.net/browse/PURCHASE-2477.
=> fix: removes Zendesk script from auctions pages

src/v2/Components/Authentication/Desktop/SignUpForm.tsx
We were seeing noise in our Sentry logs where sometimes Force would send an empty IP address to MP so this PR ensures we have a fallback. This fallback will result in the county coming back as empty:
So that seems like it solves the problem but maybe there's a better way to not make this query at all? Open to other/better ideas here!
https://artsyproduct.atlassian.net/browse/GRO-383
=> feat: Ensure ip address is never null GRO-383

src/v2/Apps/Conversation/Components/Conversation.tsx, src/v2/Apps/Conversation/Components/ConversationHeader.tsx, src/v2/Apps/Conversation/Components/ConversationListHeader.tsx, src/v2/Apps/Conversation/Routes/Conversation/index.tsx
[PURCHASE-2748]
There are broken styles on Inbox from the new site header and sitewide margins, as well as others
- scrollbar where there shouldn't be
- extra margins pushing sidebar inward/looking weird
- breakpoint issues - header disappears at one point
- The conversation list header and the conversation header are slightly misaligned with on another
_Before:_
_After:_
[PURCHASE-2748]: https://artsyproduct.atlassian.net/browse/PURCHASE-2748
=> Style fixes for inbox

src/v2/Components/Authentication/Footer.tsx, src/v2/Components/Authentication/__tests__/Desktop/ForgotPasswordForm.jest.tsx, src/v2/Components/Authentication/__tests__/Desktop/LoginForm.jest.tsx, src/v2/Components/Authentication/__tests__/Desktop/SignUpForm.jest.tsx, src/v2/Components/Authentication/__tests__/FormSwitcher.jest.tsx
This PR contains the "_Secondary Change_" part of a reverted PR [#7821](https://github.com/artsy/force/pull/7821).
From the [description of reverted PR](https://github.com/artsy/force/pull/7811):
> When committing my changes I experienced an error during the pre-commit hook that executes yarn lint --fix:
```
error  Anchor used as a button. Anchors are primarily expected to navigate. Use the button element instead. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
```
> I reached out to [#dev-help](https://artsy.slack.com/archives/CP9P4KR35/p1623862247122500) and the recommendation was to replace the `<Link>` component with `<Clickable>`. The scope of this change affects only …
=> fix: (GRO-384) jsx-a11y/anchor-is-valid linter error in auth footer

src/v2/Apps/Artist/ArtistApp.tsx, src/v2/Apps/Artist/Routes/Overview/Utils/hasOverviewContent.ts, src/v2/Apps/Artist/__tests__/ArtistApp.jest.tsx, src/v2/Apps/Artist/artistRoutes.tsx, src/v2/__generated__/ArtistApp_Test_Query.graphql.ts, src/v2/__generated__/ArtistApp_sharedMetadata.graphql.ts, src/v2/__generated__/artistRoutes_TopLevelQuery.graphql.ts, src/v2/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
Addresses https://artsyproduct.atlassian.net/browse/GRO-392 
Fixes an issue reported here: https://artsy.slack.com/archives/C01ADJNCS5D/p1624285854225600.
When we don't have enough content to render the overview page, we redirect to works-for-sale. However, we weren't hiding the overview navigation tab, leading to confusing UX. 
Example url: https://staging.artsy.net/artist/madc/works-for-sale
=> bugfix: [Artist] Hide overview tab if no content

src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx
Addresses [CX-1412]
Aligns the columns of the market stats section to the columns of the auction result section (see comments in  [CX-1412] for more context).
[CX-1412]: https://artsyproduct.atlassian.net/browse/CX-1412
=> fix: align columns on auction results page

src/v2/Components/SelectedCareerAchievements.tsx, src/v2/Components/__tests__/SelectedCareerAchievements.jest.tsx
This is an update to fix the bug noticed on the Artist page. The career highlights portion usually includes a link to a CV for artists to view "See all past shows and fair booths" link. But artists without career highlights were not able to have this CV link.
This adds in the "See all past shows and fair booths" link for artists regardless if they have highlights or not.
Past Behavior:
New Behavior:
=> GRO-376: Artist has displayed CV even without Career Highlights

src/v2/Apps/Home/Components/HomeArtworkModuleContext.tsx, src/v2/Apps/Home/Components/HomeArtworkModuleRail.tsx, src/v2/Apps/Home/Components/HomeArtworkModules.tsx, src/v2/Apps/Home/Components/HomeFeaturedCategoriesRail.tsx, src/v2/Apps/Home/HomeApp.tsx, src/v2/Apps/Home/__tests__/HomeArtworkModuleContext.jest.tsx, src/v2/__generated__/HomeApp_Test_Query.graphql.ts, src/v2/__generated__/HomeApp_homePage.graphql.ts, src/v2/__generated__/HomeArtworkModuleContext_Test_Query.graphql.ts, src/v2/__generated__/HomeArtworkModuleContext_context.graphql.ts, src/v2/__generated__/HomeArtworkModuleRailQuery.graphql.ts, src/v2/__generated__/HomeArtworkModuleRail_artworkModule.graphql.ts, src/v2/__generated__/HomeArtworkModules_homePage.graphql.ts, src/v2/__generated__/HomeFeaturedCategoriesRailQuery.graphql.ts, src/v2/__generated__/HomeFeaturedCategoriesRail_marketingCollections.graphql.ts, src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
This PR gets a bunch of the artwork rails on the page:
https://user-images.githubusercontent.com/112297/122962707-ad68b980-d353-11eb-89f6-62dac59f150e.mov
-----
Remaining:
I think some of those modules might be artwork rails as well; I just haven't tracked them down yet.
=> feat(GRO-214): adds rails to homepage

src/v2/Components/Authentication/__tests__/FormSwitcher.jest.tsx
This removes a no longer needed feature flag reference that was removed in an [earlier PR](https://github.com/artsy/force/pull/7833).
=> chore: (GRO-384) removes left over feature flag reference in tests

src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
Addresses [CX-1618]
The label for the "Auction house" filter for "auction results" should be "Auction house" instead of "medium".
The bug was introduced in this PR: https://github.com/artsy/force/pull/7719/files
**The issue**
**The fix**
[CX-1618]: https://artsyproduct.atlassian.net/browse/CX-1618
=> fix (CX-1618): change label name for auction house filter

src/v2/Apps/BuyerGuarantee/Components/BuyerGuaranteeMeta.tsx
The Artsy guarantee page wasn't being indexed by Google due to metadata in the Buyer Guarantee .tsx file explicitly preventing this from happening. 
[This ticket](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=41&projectKey=PURCHASE&modal=detail&selectedIssue=PURCHASE-2781&sprint=613) was surfaced to remove the "noindex" and "nofollow" from the robots tag in the file. 
I have some questions about the QA process, specifically answering these questions on the jira ticket:
What's the analytics requirement, if any?
How should we QA or monitor this ticket?
Is there any performance impact?
Is there any followup (e.g. pre/post-deploy migration)?
For QA, I'm not entirely sure but it could take Google some time to scrape the artsy staging/production site once this code is …
=> fix: remove noindex from artsy metadata for Google indexing

package.json, src/lib/analytics/sentryFilters.ts, src/lib/setupSentryClient.ts, yarn.lock
Address voluminous issues around `Non-Error promise rejection captured with value: Object Not Found`, which are eating up much of our quota. See [example](https://sentry.io/organizations/artsynet/issues/2460521645/?project=28316&query=is%3Aunresolved&sort=freq&statsPeriod=90d).
Followed instructions from this [sentry thread](https://forum.sentry.io/t/unhandledrejection-non-error-promise-rejection-captured-with-value/14062/13), and added the [dedupe integration](https://docs.sentry.io/platforms/javascript/configuration/integrations/plugin/#dedupe) to help clean up logs.
=> sentry: Add dedupe lib and filter out issues

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx, src/v2/Apps/Partner/partnerRoutes.tsx, src/v2/__generated__/NavigationTabs_Test_PartnerQuery.graphql.ts, src/v2/__generated__/NavigationTabs_partner.graphql.ts, src/v2/__generated__/PartnerApp_Test_Query.graphql.ts, src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts, src/v2/__generated__/partnerRoutes_ShowsQuery.graphql.ts
This PR uses `displayableShows` filed instead of `currentDisplayableShows` to fix Shows tab for some partners.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4263
Before
Now
=> fix(PX-4263): shows tab is absent for several partners

cypress/integration/artist.spec.js, cypress/integration/collect.spec.js, src/v2/Apps/Artist/ArtistApp.tsx, src/v2/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx, src/v2/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx, src/v2/Apps/Artist/Routes/Overview/Components/ArtistNotableWorksRail.tsx, src/v2/Apps/Artist/Routes/Overview/Components/ArtistRelatedArtistsRail.tsx, src/v2/Apps/Artist/Routes/Overview/Components/__tests__/ArtistNotableWorksRail.jest.tsx, src/v2/Apps/Artist/__tests__/ArtistApp.jest.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/InDemandNow/ConsignInDemandNow.tsx, src/v2/Components/ArtistMarketInsights.tsx, src/v2/Components/ArtistSeriesRail/__tests__/ArtistSeriesItem.jest.tsx, src/v2/Components/SelectedCareerAchievements.tsx, src/v2/Components/__stories__/Headers.story.tsx, src/v2/Components/__tests__/SelectedCareerAchievements.jest.tsx
This covers the following copy script changes:
__________________________
Artwork page
CTAs should be title case (ie “Contact Gallery”)
Artist page
Cap “sale” in the part next to “Overview” → “Works for Sale”
Sentence case all “sub headers” — ie “Notable works,” “Career highlights,”  “Works for sale,” “Related artists” (“Shows/Articles featuring ____” is already sentence case)
“Followers” instead of "Following" for `ArtistHeader`
Hyphenate “blue-chip” before noun
=> GRO-378: Copy Script changes suggested for Artist and associated pages

src/v2/Apps/Artist/Routes/Overview/Components/ArtistWorksForSaleRail.tsx, src/v2/Apps/Artist/Routes/Overview/Components/__tests__/ArtistWorksForSaleRail.jest.tsx
Missed one copy update for GRO-378.
Needed to update the `Works for Sale` rail to have sentence casing. So now should be `Works for sale`.
=> GRO-378: Missed one copy update for GRO378

src/v2/Apps/Order/Routes/Offer/index.tsx, src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
PR addresses this [jira ticket](https://artsyproduct.atlassian.net/browse/PURCHASE-2717?atlOrigin=eyJpIjoiYWRkMmQ5MjVhMzhiNGZmMmJjNmQwMDFkZDBiYjJkYjYiLCJwIjoiaiJ9) on the purchase sprint board:
Updates: 
- a simple word change to denote "final offer" in checkout flow for the benefit of the user being informed as they write an offer 
- added a unit test to the test suite to confirm the changes to the UI/copy in the text box render as intended
=> [Purchase-2717] Update notice text in offer checkout flow

package.json, src/v2/Components/NavBar/NavItemPanel.tsx, src/v2/System/Router/PageLoader.tsx, yarn.lock
This change replaces `react-spring` with styled component keyframe
animations and is necessary to remove a significant memory leak caused
by `react-spring` that is crashing our production pods.
Review App:
https://novo.artsy.net/
https://user-images.githubusercontent.com/403814/123460768-210a0100-d5b6-11eb-8912-5f56c771adbb.mov
=> fix: Remove React Spring

src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx, src/v2/Apps/Conversation/Components/ConversationCTA.tsx, src/v2/Apps/Conversation/Components/EditionSelectBox.tsx, src/v2/Apps/Conversation/Components/__tests__/ConfirmArtwork.jest.tsx, src/v2/__generated__/ConfirmArtworkModalQuery.graphql.ts, src/v2/__generated__/ConfirmArtworkModal_Test_Query.graphql.ts, src/v2/__generated__/ConfirmArtworkModal_artwork.graphql.ts, src/v2/__generated__/EditionSelectBox_edition.graphql.ts
JIRA -> [Select edition in confirm artwork modal
](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=41&projectKey=PURCHASE&modal=detail&selectedIssue=PURCHASE-2708)
Added the ability to display selection boxes of artworks editions to the confirm artwork modal.
Figma design screenshot:
GIF:
=> feat(purchase-2708): add artwork editions

src/v2/Apps/Artists/artistsRoutes.tsx, src/v2/Components/ArtworkFilter/Utils/__tests__/allowedFilters.jest.ts, src/v2/Components/ArtworkFilter/Utils/allowedFilters.ts
Re: https://artsy.slack.com/archives/C2TQ4PT8R/p1624812250180200
Anytime we don't sanitize inputs like this, Force will 500. But, these are at least easy to spot: anytime there's a variable input on a route query that isn't `String` — we need to prepare the input in some way. There's probably a few more of these lurking around so feel free to point any out.
=> fix: sanitizes inputs

src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
**Jira**: [FX-2825](https://artsyproduct.atlassian.net/browse/FX-2825)
When user set custom size more then one time size filter doesn't reset
*Before*
*After*
=> fix[FX-2825]: reset size filter

src/v2/Apps/Conversation/Components/Conversation.tsx, src/v2/Apps/Conversation/Components/ConversationCTA.tsx, src/v2/Apps/Conversation/Components/Details.tsx, src/v2/Apps/Conversation/Components/OrderModal.tsx, src/v2/Apps/Conversation/Components/Reply.tsx, src/v2/Apps/Conversation/Components/ReviewOfferCTA.tsx, src/v2/Apps/Conversation/Components/__tests__/ConversationCTA.jest.tsx, src/v2/Apps/Conversation/Utils/returnOrderModalDetails.tsx, src/v2/Apps/Conversation/__tests__/Reply.jest.tsx, src/v2/Apps/Order/OrderApp.tsx, src/v2/Components/NavBar/MinimalNavBar.tsx, src/v2/__generated__/ConversationPageQuery.graphql.ts, src/v2/__generated__/ConversationPaginationQuery.graphql.ts, src/v2/__generated__/Conversation_conversation.graphql.ts, src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
As a collector I want to be presented with the contents of “respond-to/confirm offer“ page in modal form when clicking on the CTA to follow these actions.
Acceptance criteria:
- ”Respond-to/confirm offer“ page should render in modal.
- CTA should trigger modal on ”respond-to/confirm offer“ state.
I wasn't sure what tests were needed for this work, as the modal only contains an iframe, but if anyone has any suggestions I'm open!
[PURCHASE-2712]: https://artsyproduct.atlassian.net/browse/PURCHASE-2712
=> Render “respond-to/confirm offer” page in modal

src/v2/Apps/Partner/Components/PartnerShows/ShowBanner.tsx
This PR fixes the show cover image width on mobile.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4272
Before
Now
=> fix(PX-4272) show cover image on mobile

src/v2/Apps/Order/Routes/Review/index.tsx
This is a webview shared between web and app. We should display this second submit button only on the app, not on the web.
https://artsyproduct.atlassian.net/browse/PURCHASE-2688
=> feat:second button + deleted excess padding

src/lib/analytics/sentryFilters.ts
Following up recent efforts to filter out the noisiest and least-actionable error report ([1](https://github.com/artsy/force/pull/7802), [2](https://github.com/artsy/force/pull/7807), [3](https://github.com/artsy/force/pull/7809), [4](https://github.com/artsy/force/pull/7862)...), this PR filters out 2 additional groups of issues:
* https://sentry.io/organizations/artsynet/issues/2460304848
* https://sentry.io/organizations/artsynet/issues/2460304867
Together these account for ~70% of our quota. They had been "ignored," so weren't obvious in the Sentry UI but _do_ count against our quota.
=> Ignore more errors that account for ~70% of overall volume

package.json, src/lib/cache.js, src/v2/Apps/Partner/Components/Overview/NearbyGalleriesRail.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx, yarn.lock
This change removes underscore from the asset bundle decreasing it's
size by 30KB gzip.
=> fix: Remove Underscore from Asset Bundle

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx, src/v2/Apps/Partner/Components/PartnerHeader/PartnerHeaderImage.tsx, src/v2/Apps/Partner/Components/ScrollToPartnerHeader/index.tsx, src/v2/Apps/Partner/Routes/Artists/ArtistsRoute.tsx
This PR fixes empty space is displayed above the cover image on mobile. Also to fix some issues related to header height I used `useNavBarHeight`.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4291
Before 
Now
=> Kiryl zubarau/fix/px 4291 redundant empty space is displayed above the cover image

src/desktop/components/fair_week_marketing/__tests__/BannerPopUp.jest.tsx, src/v2/Apps/ArtistSeries/Components/ArtistSeriesMeta.tsx, src/v2/Apps/BuyerGuarantee/Components/BuyerGuaranteeMeta.tsx, src/v2/Apps/Fairs/Components/FairsPhonePromo.tsx, src/v2/Apps/FeatureAKG/__tests__/FeatureAKGRoute.jest.tsx, src/v2/Apps/Gene/Components/GeneMeta.tsx, src/v2/Apps/Gene/Routes/__tests__/GeneShow.jest.tsx, src/v2/Apps/Home/Components/HomeMeta.tsx, src/v2/Apps/Home/HomeApp.tsx, src/v2/Components/MetaTags.tsx, src/v2/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.jest.tsx, src/v2/Components/__tests__/MetaTags.jest.tsx
This implements a generic meta tag component and then uses it on the new homepage. I realize that these are kind of fiddly tedious to set up. Easy to forget things, image specifications, etc... so this takes the guess work out of it.
I've included usage in a couple other places. I'll have to go around and replace *all* meta tag components, which I'll do in a separate PR.
=> feat(GRO-403): fleshes out meta tags

hokusai/staging.yml
This change alters the force pod autoscaler to wait 30 minutes before
removing nodes after a scaleUp event. Looking at the graphs in Datadog
there is a significant amount of pod trashing and this will remediate
that.
This change does not alter upscale timing which will stay at
"immediate".
=> feature: Pod Stabilization (Staging)

src/v2/Apps/Order/Components/SavedAddresses.tsx, src/v2/Apps/Order/Components/__tests__/SavedAddresses.jest.tsx, src/v2/Apps/Order/Routes/Shipping/index.tsx, src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx, src/v2/Components/UserSettings/UserSettingsAddresses.tsx
In #7797 [I mentioned that I thought we could clean up a few more stateful properties](https://github.com/artsy/force/pull/7797#discussion_r660128541) in the `Shipping` route component, because they're being set but never read. This PR does that!
@Serge0n you're closer to this work, let me know if I'm missing something and these things can't be removed. 
I created the PR based on the branch for #7797, so this _could_ be merged into that branch before it's merged, if we want. Or we could merge this into master after #7797 is merged.
=> chore: Remove unused code based on #7797 

Dockerfile
Node 12 supports a command-line option to capture manual heap
snapshots. This change enables this functionality using the standard
`USR2` signal and allows profiling of pods in production.
=> feature: Manual Heap Dumps

src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilterMobileActionSheet.tsx
Jira: [FX-2806](https://artsyproduct.atlassian.net/browse/FX-2806)
The purpose of the task is replace 'Reset' button with 'Cancel' button, but I have unsolved question ([described here](https://artsy.slack.com/archives/C9SATFLUU/p1625236217017300))
**Before**
**After**
=> fix: refactor filters on artist auction results screen

hokusai/production.yml
This change alters the force pod autoscaler to wait 30 minutes before
removing nodes after a scaleUp event. Looking at the graphs in Datadog
there is a significant amount of pod trashing and this will remediate
that.
This change does not alter upscale timing which will stay at
"immediate".
=> feature: Pod Scaling Stabilization (Production)

src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
This change uses an existing local file over the same file in
`@artsy/reaction` thus eliminating it from the v2 bundle.
=> chore: Remove @artsy/reaction from v2 Bundle

src/v2/Apps/Auctions/auctionsRoutes.tsx, src/v2/Apps/Order/orderRoutes.tsx, src/v2/Apps/ViewingRoom/viewingRoomRoutes.tsx
Reduces the size of the shared `artsy-entry` bundle by encapsulating
more app logic into specific application bundles.
The entry bundle is reduced by 961 KB gzip to 794 KB gzip.
Bundles Before:
Bundles After:
=> feature: App Bundling

src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx
[PURCHASE-2807]
I was seeing the following error locally. This happens when an artwork has been deleted. `Conversation` uses a snapshot of the artwork, so its fine with deletions, but the modal has its own query renderer so it errors out when it tries to get the `editionSets` of a non existent artwork. 
I had seen this before and thought I fixed it by checking that `artwork` exists before rendering the modal query renderer, but I was only checking that the _snapshot_ existed.
[PURCHASE-2807]: https://artsyproduct.atlassian.net/browse/PURCHASE-2807
=> Fix for edition set error when artwork has been deleted

src/v2/Apps/Home/Components/HomeFeaturedArticles.tsx, src/v2/__generated__/HomeFeaturedArticlesQuery.graphql.ts
With the addition of the [`featured` option](https://github.com/artsy/metaphysics/pull/3266) — we can now display the correct articles.
=> fix(home): utilizes featured flag for articles

src/desktop/apps/auction/components/artwork_browser/__tests__/fixtures/followedArtistSaleArtworks.js, src/desktop/apps/auction/components/artwork_browser/main/artwork/BidStatus.js, src/desktop/apps/auction/queries/worksByFollowedArtists.js
Jira ticket: [FX-2356]
As a logged in user
When I visit an auction sale page that has at least 1 work by an artist I follow
I should see consistent metadata for the work in the rail and the work in the artwork grid
[FX-2356]: https://artsyproduct.atlassian.net/browse/FX-2356
=> feat: fetch bid data for auction artworks on mWeb

src/v2/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
Jira: [FX-2759](https://artsyproduct.atlassian.net/browse/FX-2759)
Aggregations is not part of context state, but only props. So they update after each receiving response from server
Description of issue:
When you search some artist series and then search another one, the aggregations don't update 
Result of fix:
Aggregations update after each search
=> fix(FX-2759): update aggregations in context

src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter.jest.tsx, src/v2/Components/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx
Jira: [FX-2826](https://artsyproduct.atlassian.net/browse/FX-2826), [FX-2827](https://artsyproduct.atlassian.net/browse/FX-2827)
Solution for issues:
- user select/unselect small/medium/large size and filter fires events for custom width/height -- if custom width/height have null value (it may be undefined or *-*) and new value is also null, they don't update, in other way width/height should reset
- user select a custom width and filter fire event for custom height -- if custom height have null value and new value is also null, it don't update (the same for width)
**Before**
Selecting size fires additional analytics events
Ex. selecting medium size fire events for custom width/height
**After**
Size events fire only by changes explicitly
**Additional**
Fix the bug with reset flag (when …
=> fix: size events fire only by changes explicitly

webpack/envs/clientCommonConfig.js, webpack/utils/env.js
This adds a flag to allow disabling size based bundle splitting, this
can help when debugging and doing bundle analysis.
=> feature: Webpack Bundle Split Flag

src/v2/Apps/Fair/Routes/FairArtworks.tsx, src/v2/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/FilterExpandable.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/PartnersFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/FilterExpandable.jest.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/PartnersFilter.jest.tsx
Jira: [FX-3062]
* As a user, I expect to see all relevant filters for each surface. 
* All filters collapsed **by default in mWeb**.
1. Exhibitors (Default Open)
2. Artists (Default Open)
3. Rarity (Default Open)
4. Medium (Default Open)
5. Price (Default Open)
6. Size (Default Open)
7. Ways to Buy (Default Open)
8. Material
9. Artist Nationality & Ethnicity
10. Artwork Location
11. Time Period
12. Color
<details>
<summary>Web</summary>
</details>
<details>
<summary>Mobile</summary>
</details>
[FX-3062]: https://artsyproduct.atlassian.net/browse/FX-3062
=> feat(FX-3062): fair artworks alignment

src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/ArtistAuctionResultsCount.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilterMobileActionSheet.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/MediumFilter.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/SizeFilter.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/KeywordFilter.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/SortSelect.tsx, src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx, src/v2/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.jest.tsx, src/v2/Apps/Artist/Routes/AuctionResults/__tests__/SizeFilter.jest.tsx
Jira: [FX-2806](https://artsyproduct.atlassian.net/browse/FX-2806)
**The purpose of the task:** refactor mobile filters on artist auction results page
Done work:
- The filters style are the same as on other mobile surfaces (ex. artist artworks)
- The filters has staged state
- Solved are most of STRICT_NULL_CHECK errors
**The filters before:**
**The filters after:**
=> fix(FX-2806): refactor auction results filters

src/desktop/apps/galleries_institutions/components/location_carousel/index.coffee, src/desktop/apps/galleries_institutions/components/location_carousel/test/index.test.js, src/desktop/apps/galleries_institutions/components/parameters/fetch_filter_partners.coffee, src/desktop/apps/galleries_institutions/components/parameters/test/fetch_filter_partners.test.js, src/desktop/apps/galleries_institutions/queries/location_carousel_query.coffee, src/desktop/apps/galleries_institutions/queries/partner_categories_query.coffee, src/desktop/apps/galleries_institutions/queries/partner_fragment.coffee, src/desktop/apps/galleries_institutions/queries/partners_filter_query.coffee, src/desktop/apps/galleries_institutions/routes.coffee
Blocked by: https://github.com/artsy/metaphysics/pull/3259
Jira ticket: https://artsyproduct.atlassian.net/browse/PX-2975
This PR updates the galleries/institutions app to use metaphysics v2 instead of v1. It relies on the schema updates in the ☝️ metaphysics PR, hence the `[Don't Merge]` 😄.
The updates are because the schemas are slightly different, but I clicked around a bit and I think we're all good! 🤞
=> [PX-2975] Updates galleries_institutions to use metaphysics v2

src/v2/Apps/Order/Routes/Review/index.tsx
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-2810
Add check for the eigen to prevent unwanted redirect to the conversation. Instead, the user stays at the order status page.
=> fix(PURCHASE-2810): unwanted redirect to conversations from eigen

src/v2/Apps/Show/Components/ShowContextCard.tsx, src/v2/Apps/Show/Components/ShowInstallShots.tsx, src/v2/Apps/Show/ShowApp.tsx
Now that we have the scrollbars we can enable them for the install shots shelf. Fixes a few other minor visual inconsistencies.
=> chore(show): adds scrollbar; minor clean up

src/v2/Components/ArtworkFilter/Utils/fetchFollowedArtists.ts, src/v2/__generated__/fetchFollowedArtistsByFairIdQuery.graphql.ts, src/v2/__generated__/fetchFollowedArtistsRawQuery.graphql.ts, src/v2/__generated__/fetchFollowedArtists_response.graphql.ts
Type: **Fix**
Jira: [FX-2859]
The initial implementation was made in PR #7441, but later an error was discovered (relay sends `null` as a default value for optional arguments – on our case this is `fairId`), which this PR corrects
[FX-2859]: https://artsyproduct.atlassian.net/browse/FX-2859
=> fix: fetch follow artists

src/v2/Components/Artwork/Details.tsx
Was scrolling down the new homepage when I encountered this beauty: 
Happened to be the exact piece of code you called out earlier. Here's a much simpler way to do this and fix the problem in one go 😬
=> fix(details): fixes artist name with multiple artists

src/v2/Apps/Order/OrderApp.tsx
solves [PURCHASE-2793](https://artsyproduct.atlassian.net/browse/PURCHASE-2793)
After the collector completes creating an order from the inquiry (using a button in conversation with the seller) user is redirected back to the conversation page. This redirect is interrupted by an "unsaved data" warning that makes no sense as the collector already completed the editing order at the moment. 
Solution: add check for "PUSH" action on the orders app to prevent "unsaved changes" warning on the application page.
=> fix[PURCHASE-2793]: remove unwanted warning on redirect from the orders page

src/lib/analytics/sentryFilters.ts
Noticing that this error keeps spamming sentry, and is coming from a 3rd party script.
=> sentry: Add `Illegal Invocation` to list

src/v2/Apps/Show/Components/ShowInstallShots.tsx
This fixes a minor issue [that was raised earlier today](https://artsy.slack.com/archives/C7LEJU1QU/p1626446421334700) regarding the install shot captions overflowing on mobile breakpoints. This also fixes the collapsing containers so as to prevent the page shift from occurring, and lazy loads images outside the viewport.
=> fix(show): improves install shots display

src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx, src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
[FX-3066]
Before
After
[FX-3066]: https://artsyproduct.atlassian.net/browse/FX-3066
=> FX-3066 feat: Auction House filter is not expanded by default

src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistNationalityFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/ArtworkLocationFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/PartnersFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ResultsFilter.jest.tsx
Jira: [FX-2789](https://artsyproduct.atlassian.net/browse/FX-2789)
Description:
The purpose of this ticket is to ensure that the filter facets (options) on web and iOS are sentence cased to match the [Artsy Copy Style Guide](https://docs.google.com/document/d/1NoBSYM-EBA4b6rdux-8CQJWneXcglISHzZNvSkKFDh0/edit#heading=h.1bm808xl0evg).
The work done:
- Updated titles for artwork filters
- Updated titles for artist auction results filters
=> feat(FX-2789): filter facet names title

src/v2/Components/NavBar/Menus/DropDownMenu/__tests__/DropDownMenu.jest.tsx, src/v2/Components/NavBar/menuData.ts
Jira: [FX-3049](https://artsyproduct.atlassian.net/browse/FX-3049)
Description:
The Curatorial team is requesting an update to the Artworks and Artists Nav Bars at the top of artsy.net. We've reviewed the performance of existing categories and collections, and removed low performing content and introduced new content that has historically performed well. We're hoping that this update can take place in early Q3.
Link to requested updates: https://docs.google.com/spreadsheets/d/1EOYineDRM9QTfNE7gUyO3pnqKUrr_pgekCHYsWsxK-U/edit#gid=0
_ARTIST_
**Artist Nav Before:**
**Artist Nav After:**
_ARTWORK_
**Artwork Nav Before**
**Artwork Nav After**
=> feat(FX-3049): nav bar update

src/v2/Apps/Conversation/Components/OpenInquiryModalButton.tsx, src/v2/Apps/Conversation/Components/OrderUpdate.tsx, src/v2/Apps/Conversation/Components/Reply.tsx
Incorrect timestamp location when submitting an offer in inquiry
Expected behavior:
The inline offer status is preceded by the time stamp
Actual behavior:
The inline offer status is followed by the time stamp
__Before:__
__After:__
Extra border shadow is still there even when MO button isn't visible
__Before:__
__After:__
[PURCHASE-2816]: https://artsyproduct.atlassian.net/browse/PURCHASE-2816
[PURCHASE-2825]: https://artsyproduct.atlassian.net/browse/PURCHASE-2825
=> moved timestamp to above order update and fixed mo button styling

src/v2/Apps/Partner/Components/PartnerHeader/PartnerHeaderAddress.tsx, src/v2/Apps/Partner/Components/__tests__/PartnerHeader.jest.tsx
This PR fixes partner profile page rendering if does not have a specified city.
=> fix: address line rendering

src/v2/Apps/Conversation/Components/ConversationList.tsx
[PURCHASE-2806]
Shoutout to @xtina-starr for finding this solution!
Conversations weren't refetching on scroll, and we realized that the `onScroll` method wasn't being hit. Moving the onScroll to a different container fixed this issue, and we were able to trace it back to this PR: https://github.com/artsy/force/pull/6135
[PURCHASE-2806]: https://artsyproduct.atlassian.net/browse/PURCHASE-2806
=> Bugfix: fix refetching on scroll in conversation list

src/v2/Apps/Fair/FairApp.tsx, src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
Jira: [FX-3079](https://artsyproduct.atlassian.net/browse/FX-3079)
Current exhibitors tab on fair page should have a new header title
See [Figma](https://www.figma.com/file/aM3b5sodn04vMTigbQXACi/Fairs-2021?node-id=2891%3A0) for reference
**Changes**
- Renamed tab title
- Updated tests for fair tabs
**Before**
**After**
=> feat(FX-3079): rename exhibitors tab to booths

src/test/fixtures/aggregations.ts, src/v2/Apps/ArtistSeries/__tests__/ArtistSeriesArtworksFilter.jest.tsx, src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx, src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx, src/v2/Components/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx, src/v2/Components/ArtworkFilter/index.tsx, src/v2/__generated__/ArtistSeriesArtworksFilter_Query.graphql.ts
Jira ticket: [FX-3064]
* As a user, I expect to see all relevant filters for each surface. 
* This ticket is to align our current filters with a consistent order and default open view
* All filters collapsed by default in mWeb.
* The order of filters **has been updated in the basic** [ArtworkFilters component](https://github.com/artsy/force/blob/c9e0748a5e21b05f33df6c73c65689ad93667c2f/src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx), which is used in all places where filters are render (except for those where the `Filters` prop [is passed](https://github.com/artsy/force/blob/4fdfd0368a2f8f2256290e6381bedefb8180de64/src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx#L27-L38)
* Initial PR #7971 
* Rarity (Default Open)
* Medium (Default Open)
* Price …
=> feat(FX-3064): base filter alignment + artist series

src/v2/Apps/Partner/Routes/Works/index.tsx, src/v2/Apps/Partner/Routes/__tests__/Works.jest.tsx, src/v2/Apps/Partner/partnerRoutes.tsx, src/v2/Components/ArtworkFilter/index.tsx, src/v2/__generated__/Works_Query.graphql.ts, src/v2/__generated__/Works_partner.graphql.ts, src/v2/__generated__/partnerRoutes_WorksQuery.graphql.ts
Jira ticket: [FX-3061], [FX-3087]
* As a user, I expect to see all relevant filters for each surface. 
* This ticket is to align our current filters with a consistent order and default open view
* All filters collapsed by default in mWeb.
* Initial PR #7971 
* Filters (Top to Bottom)
* Artists (Default Open)
* Rarity (Default Open)
* Medium (Default Open)
* Price (Default Open)
* Size (Default Open)
* Ways to Buy (Default Open)
* Material
* Artist Nationality & Ethnicity
* Time Period
* Color 
<details><summary>UI updates</summary>
</details>
[FX-3061]: https://artsyproduct.atlassian.net/browse/FX-3061
[FX-3087]: https://artsyproduct.atlassian.net/browse/FX-3087
=> feat(FX-3061, FX-3087): update filters order for partner works

src/v2/Apps/Auctions/AuctionsApp.tsx, src/v2/Apps/Auctions/Components/StandoutLots/StandoutLots.tsx, src/v2/Apps/Auctions/Components/TrendingLots/TrendingLots.tsx, src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/WorksByArtistsYouFollowRail.tsx
This PR is to address a few QA points brought up via Slack discussion for the new Curatorial Rail.
Mainly have to do with header spacings and spacing between the new rails and Auction Rails. Shown in below video:
https://user-images.githubusercontent.com/30025439/126379162-91a2e7f4-5217-4f0c-bb4a-e89efdb43223.mov
=> GRO-408: QA for Curatorial Rails

src/desktop/apps/art_keeps_going/routes.tsx, src/desktop/apps/fair_redirect/__tests__/fairRedirectionMiddleware.jest.ts, src/desktop/apps/fair_redirect/fairRedirectionMiddleware.ts, src/desktop/apps/partner_redirect/__tests__/partnerRedirectionMiddleware.jest.ts, src/desktop/apps/partner_redirect/partnerRedirectionMiddleware.ts, src/lib/middleware/artsyExpress.ts, src/lib/middleware/serverTimingHeaders.ts, src/middleware.ts, src/v2/System/Router/__tests__/buildServerApp.jest.tsx, src/v2/System/Router/buildServerApp.tsx, src/v2/server.ts
Enables server timing headers to help identify performance issues. Then
headers when enabled follow the Server Timing spec:
https://w3c.github.io/server-timing/#the-server-timing-header-field
Additionally, there is a separate commit that correctly sets the types for
Response and Request options to fix type errors.
=> feature: Server Timing Headers

src/v2/Apps/Fair/Components/ExhibitorFilterContext.tsx, src/v2/Apps/Fair/Routes/FairExhibitors.tsx, src/v2/Apps/Fair/Routes/FairExhibitorsQuery.tsx, src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx, src/v2/Apps/Fair/fairRoutes.tsx, src/v2/__generated__/FairExhibitorsQuery.graphql.ts, src/v2/__generated__/FairExhibitors_Query.graphql.ts, src/v2/__generated__/FairExhibitors_fair.graphql.ts, src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Reverts artsy/force#8037
Already rolled back in production. Reverting to unblock the deployment pipeline.
> I think I found a bug with the new page-based pagination on the fair page. Looks like the pagination component isn’t rendering correctly when you move from page to page - seems to always render as if the first page is active. It seems to work fine when I switch to A-Z sorting or when I switch back to Relevance (sort shows up in the URL).
Source: [Slack](https://artsy.slack.com/archives/C9SATFLUU/p1626863639057300).
=> Revert "FX-3071 feat: Added pagination to fair booths page"

src/v2/System/Relay/createRelaySSREnvironment.ts
When we launched force as an SPA last year we also launched the ability to tap into the relay network layer as a server-side response cache, stored in Redis. Since the launch, we've migrated dozens of pages, with each being cacheable for logged-out users during the SSR pass, and for logged-in users, on the client (unless we explicitly decide to not cache, like on artwork). 
This PR bumps up our initial launch values from 100 cache entries and a 15min expiry to 2000 entries and a 1hr expiry. We should continue playing with it, but this should account for a vastly expanded SPA page count a year in.
=> relay cache: Bump up cache expiry times

src/v2/Apps/Collect/Routes/Collect/index.tsx, src/v2/Apps/Collect/collectRoutes.tsx, src/v2/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Jira ticket: [FX-3068], [FX-3085]
* As a user, I expect to see all relevant filters for each surface. 
* This ticket is to align our current filters with a consistent order and default open view
* All filters collapsed by default in mWeb.
* Initial PR #7971 
* Artists (Default Open)
* Rarity (Default Open)
* Medium (Default Open)
* Price (Default Open)
* Size (Default Open)
* Ways to Buy (Default Open)
* Material
* Artist Nationality & Ethnicity
* Artwork Location
* Time Period
* Color
* Galleries & Institutions
<details><summary>UI updates</summary>
</details>
[FX-3068]: https://artsyproduct.atlassian.net/browse/FX-3068
[FX-3085]: https://artsyproduct.atlassian.net/browse/FX-3085
=> feat(FX-3068, FX-3085): collect filter alignment

docs/env_configuration.md, package.json, scripts/setup.sh
This is a quick followup to https://github.com/artsy/force/pull/8031 merge and also to bring us in line with similar changes being made in [this MP pr](https://github.com/artsy/metaphysics/pull/3300)
* fix typos in docs
* add `sync-env` script to provide alternative way to update `.env.shared` via `yarn`
* simplify setup script by letting commands fail organically notifying the user when `brew` is missing or `yarn` is missing.
=> minor edits following turn-key merge

src/v2/Apps/Order/OrderApp.tsx, src/v2/Apps/Order/Routes/Respond/index.tsx
Solves https://artsyproduct.atlassian.net/browse/PURCHASE-2821
Collector sends an offer in inquiry, gallery sends a counteroffer, the collector opens counteroffer respond modal and sees there "respond" step (without a header and a footer, as intended)
After accepting, declining, or sending a counteroffer the modal gets a header and a footer as on a full page. 
That happens because the "isModal" state is passing in the search string and moving to the next step is handled by the router without preserving the search string. 
This PR resolves this issue by passing the current search string to a new route on redirect. 
As a result:
=> fix(PURCHASE-2821): Forward search string in order "respond" step redirects

src/v2/Apps/Fair/Components/ExhibitorFilterContext.tsx, src/v2/Apps/Fair/Routes/FairExhibitors.tsx, src/v2/Apps/Fair/fairRoutes.tsx, src/v2/Components/ArtworkFilter/Utils/__tests__/isDefaultFilter.jest.tsx, src/v2/Components/ArtworkFilter/Utils/isDefaultFilter.tsx, src/v2/Components/ArtworkFilter/Utils/urlBuilder.tsx, src/v2/Components/Pagination/useComputeHref.ts
Initial sort value for fair exhibitors previously was set as `-decayed_merch` in order to initially hide this param in url. That caused a bug where fetching data with invalid sort value when paginating to a new page would fail.
This PR:
- adds optional parameter `defaultValues` to `updateUrl` method so that we can hide in url filter values other than initial
- fixes initial data fetching on fair booths page by changing initial sort value that is hidden in url with the help of ^ update
=> fix: Added optional parameter to updateUrl method

src/v2/Apps/Partner/partnerRoutes.tsx
This PR fixes a Sentry error that happened on the partner profile page.
Sentry error - https://sentry.io/organizations/artsynet/issues/2514889208/?project=28316&query=is%3Aunresolved+url%3A%22https%3A%2F%2Fwww.artsy.net%2Fpartner%2F%2A%22&statsPeriod=14d
=> fix: check locations is not empty before usage

package.json, webpack/index.js, webpack/plugins/datadog.js, webpack/utils/env.js, yarn.lock
Enables detailed Webpack build stats and sends them along to Datadog.
From time to time it comes up in conversation that the force build is slow
on X's computer, or that a change to the build configuration has impacted
developer experience. 
If we collect the build stats and send them to Datadog we will be able to
detect anomalies and find ways to remediate them.
An incomplete Dashboard: [link](https://app.datadoghq.com/dashboard/bt2-c8n-vpp?from_ts=1626993129102&to_ts=1627079529102&live=true)
TODO:
[ ] Add shared datadog secret
[ ] Track CI builds separately
=> WIP - feature: Webpack Build Stats

src/v2/System/Relay/createRelaySSREnvironment.ts
https://artsy.slack.com/archives/C02BC3HEJ/p1627303585123800
We started to see alerts showing up on staging about [requiring config on the clients](https://github.com/artsy/force/blob/735db9e91e1e3e46b5951987d0f693e9be9de339/src/config.ts#L12). This was an existing behavior (so likely not relevant to [this refactor](https://github.com/artsy/force/pull/8062)), and reverting 
https://github.com/artsy/force/pull/8057/commits/64f8e0a904028bf870473992e5102a2285295275 fixes it on my local.
I'm not up-to-date about how `createRelaySSREnvironment` is used on the client side or if this alert still makes sense in our current setup. We can follow up separately and revisit.
=> fix: do not require config for createRelaySSREnvironment

src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx, src/v2/Components/ArtworkFilter/index.tsx
[FX-2849]
Currently when user changes page on an artwork grid on web, we fire a `Commercial_filter_params_changed` event. We should fire a different event because a page change is not a filter change.
[FX-2849]: https://artsyproduct.atlassian.net/browse/FX-2849
=> FX-2849 feat: Artwork grids page change event

scripts/setup.sh
Do not use brew to install yarn. There is no need as the preferred
method is to install it with `npm`, this also has the benefit of being
cross platform.
=> chore: Simplify Yarn Install

src/v2/Apps/Collect/Routes/Collection/index.tsx
So turns out that in order to display a card for a tweet, Twitter demands that you add a `twitter:card` meta tag. We didn't add this tag on collection pages, so they looked terrible in tweets.
Tested using https://cards-dev.twitter.com/validator and [ngrok](https://ngrok.com/docs) for port forwarding.
One note: when I tested [this collection](https://www.artsy.net/collection/bridget-riley-black-and-white), I received the following warning:
```
WARN:  The image URL http://files.artsy.net/images/bridget-riley-black-white.png specified by the 'og:image' metatag may be restricted by the site's robots.txt file, which will prevent Twitter from fetching it.
```
So we _might_ still have problems if an image was uploaded using [Vanity](https://vanity.artsy.net/).
Before:
After:
Jira ticket: …
=> fix[FX-1758]: adds og meta tags to collection pages

src/v2/Apps/Artwork/Components/ArtworkLightbox.tsx
Embarrassed I didn't catch this sooner: When I switched this component to use a `srcSet` also required was updating the preload tag to support it. So on 2x screens we've been preloading the 1x then not using it.
=> fix(artwork): fixes preload srcset

src/v2/Apps/Collect/Routes/Collection/index.tsx
Follows up on https://github.com/artsy/force/pull/8078, uses `<MetaTags />` instead of individual `<Tag />` components. Thanks for the suggestion @damassi !
=> fix: use MetaTags for collection pages

src/v2/index.ejs
Closes: [GRO-452](https://artsyproduct.atlassian.net/browse/GRO-452)
There is an ongoing design issue with the goal of removing italics completely, but for the time being this font is used prominently on every page, so it makes sense to preload it in the meantime.
=> chore(GRO-452): preloads unica italic

src/v2/index.ejs
Being preloading the fonts before the JS assets. With the additional 
chunks created by the new chunking algorithm, fonts are being delayed
for longer than we'd like. Overall, this should help with our initial render.
=> feature: Preload Fonts ASAP

src/v2/Apps/Order/Components/PaymentPicker.tsx, src/v2/Apps/Order/Components/PhoneNumberForm.tsx, src/v2/Apps/Order/Components/__tests__/PaymentPicker.jest.tsx, src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx, src/v2/Components/AddressForm.tsx, src/v2/Components/__tests__/Utils/addressForm.ts
JIRA -> [Unexpected behavior when entering text in the shipping form](https://artsyproduct.atlassian.net/browse/PURCHASE-2817)
The bug was about weird input caret behavior of AddressForm component. It jumps to the end every re-render, so when a user wants to add a text somewhere in a middle of text, then the caret jumps to the end after first element input.
The problem was in 2 sources of truth. We have AdrdessForm state, where we store the values of inputs, and also we store the same data higher in the parent. And in the value attributes of each input in AddressForm `props.data` was passed, not `state.data`, that’s why it cause such a strange behavior. So, the fix is easy, just to replace `this.props.value` with `this.state.value`.
GIF:
=> fix: [PURCHASE-2817] AdressForm inputs caret

package.json, src/config.ts, src/lib/memoryCache.ts, src/lib/middleware/__tests__/pageCache.jest.ts, src/lib/middleware/memoryPageCache.ts, src/lib/middleware/redisPageCache.ts, src/lib/middleware/serverTimingHeaders.ts, src/middleware.ts, src/v2/routes.tsx, src/v2/server.ts, yarn.lock
A super basic in-memory full page cache for modern pages with static content.
(Dependent on final solution):
Currently caches html, utf-8 encoded, as a buffer. Long term there are more
optimized ways to cache this data. Most obviously caching the already compressed
response buffer would save CPU cycles and reduce memory load.
The goal is to leverage this in production to test the impact of full-page caching
and use the collected metrics to drive future page caching techniques. In review
apps, this eliminates up to 95%+ of the TTFB for cached pages depending on
network connection overhead: latency, bandwidth, etc.
Note: Disabled by default.
=> feature: In Memory Cache

src/v2/Apps/Order/Routes/Shipping/index.tsx
Just moved up handleError function to avoid updateAddress call, if setShipping mutation returns an error 
https://artsyproduct.atlassian.net/browse/PURCHASE-2819
https://user-images.githubusercontent.com/37010996/126953497-9772f235-2e44-40ee-8200-2bad5ffb4639.mov
=> fix:handle on setShipping error [PURCHASE-2819]

src/desktop/components/cookies/index.ts
Renames `expires` to `expire` which was incorrectly spelled during decaffeination.
=> fix: Cookie Export

.env.example, CONTRIBUTING.md
As of https://github.com/artsy/gravity/pull/14315, redirects from Gravity's staging environment to Force on `localhost` are permitted, so these special instructions should no longer be necessary.
We left [this special webpack path logic](https://github.com/artsy/force/blob/78f3308351952c9d5f8ea188ee5a9cbad9472913/src/lib/webpackPublicPath.ts#L17) in place, in case developers continue to use `local.artsy.net`.
Co-authored by: @icirellik
=> Remove special instructions for local auth now that localhost should work

src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter.jest.tsx, src/v2/Components/ArtworkFilter/Utils/__tests__/urlFragmentFromState.jest.tsx, src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
- User selects a custom size filter (custom width/height)
- User then clicks “clear all” filters
- No analytics event is fired to clear width/height
- Set initial values for custom width/height to artworks filter state
**Note**: this bug can be solved by 2 ways ([described here](https://artsy.slack.com/archives/C9SATFLUU/p1627657974044000))
When user set custom size and then clear all filters the analytics event is fired
=> fix(FX-2825): analytics event for clearing custom size

src/desktop/apps/auction/components/layout/auction_info/Registration.tsx
[PURCHASE-2851
](https://artsyproduct.atlassian.net/browse/PURCHASE-2851)
"Contact us" phone number has been changed on auction pages. 
Before: 
After:
=> chore: Contact us number change

src/v2/Apps/Collect/Components/__tests__/SeoProductsForCollections.jest.tsx, src/v2/Apps/Partner/Components/PartnerMeta/index.tsx, src/v2/Components/Seo/BreadCrumbList.tsx, src/v2/Components/Seo/CreativeWork.tsx, src/v2/Components/Seo/LocalBusiness.tsx, src/v2/Components/Seo/Person.tsx, src/v2/Components/Seo/Product.tsx, src/v2/Components/Seo/StructuredData.tsx, src/v2/Components/Seo/__tests__/BreadCrumbList.jest.tsx, src/v2/Components/Seo/__tests__/CreativeWork.jest.tsx, src/v2/Components/Seo/__tests__/LocalBusiness.jest.tsx, src/v2/Components/Seo/__tests__/Person.jest.tsx, src/v2/Components/Seo/__tests__/Product.jest.tsx, src/v2/Components/Seo/__tests__/StructuredData.jest.tsx, src/v2/__generated__/PartnerApp_Test_Query.graphql.ts, src/v2/__generated__/PartnerMeta_partner.graphql.ts, src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts
This PR adds structured data to the partner pages per the `LocalBusiness` schema.org spec:
https://schema.org/LocalBusiness
I poked around and discovered some things about the `address` and `location` attributes plus learned more about how we model partner locations so ended up pitching what you see here - we run both the `legalName` and `name` always and then conditionally run the `address` as a `PostalAddress` including phone number and conditionally run the `location` as a `Place` with lat/long in case Google will pick that up and do a map. More docs for the curious:
https://schema.org/Place
https://schema.org/PostalAddress
Note that I discovered there was no need to use the scary `dangerouslySetInnerHTML` api and instead I just ran the content right inside the `script` tag.
Looks like …
=> feat: Add structured data for partners GRO-379

src/desktop/apps/user/components/password/index.jade, src/desktop/apps/user/components/password/view.coffee
Addresses [CX-294]
Hides current password input in the settings page if the user account doesn't have a password. This case can happen if the user created the account with a 3rd party provider which doesn't require a password.
Currently, the user has to enter an arbitrary password in the "current password" field to pass the form validation when creating a password for an account without a password.
[CX-294]: https://artsyproduct.atlassian.net/browse/CX-294
=> fix: Hide current password input in settings form conditionally

src/v2/Apps/Order/OrderApp.tsx, src/v2/Apps/Order/__tests__/OrderApp.jest.tsx
[PURCHASE-2879]
*No screenshots because help chat doesn't render locally*
Current behavior:
Given a buyer has submitted an offer through an inquiry,
And they have received a counteroffer from the seller,
When they open the counteroffer modal,
Then the Help chat bubble renders at the bottom right of the modal.
Improved behavior:
Given a buyer has submitted an offer through an inquiry,
And they have received a counteroffer from the seller,
When they open the counteroffer modal,
Then the Help chat bubble does not render.
[PURCHASE-2879]: https://artsyproduct.atlassian.net/browse/PURCHASE-2879
=> Remove the Help chat bubble from Inquiry checkout modal

src/v2/Apps/Unsubscribe/UnsubscribeApp.tsx, src/v2/Apps/Unsubscribe/__tests__/UnsubscribeApp.jest.tsx, src/v2/__generated__/UnsubscribeApp_Test_Query.graphql.ts
We discovered some traffic was making it to our unsubscribe page without a token so this PR aims to improve that UX by nudging them to log in. Once they are logged in, then the page will behave as expected and they can change their email frequency. Here's how the fallback page looks:
In terms of the actual code here my approach was:
* add some specs for the three paths through this component
* extract the existing fallback component
* update that fallback component
And that's it!
https://artsyproduct.atlassian.net/browse/GRO-475
/cc @artsy/grow-devs @isakelaris
=> feat: Improve unsubscribe fallback GRO-475

src/v2/Components/DownloadAppBadge.tsx
Checks off some minor lighthouse report dings.
We can't use Palette's `Image` component to lazyLoad  because of the rounded corners on these (see: [image grievances](https://artsyproduct.atlassian.net/browse/DSWGW-79)), but we can just use a native img tag with `loading="lazy"`.
Also adds the appropriate alt text.
=> fix(footer): lazyloads app icons and adds alt text

src/v2/Utils/LegacyArtworkDllContainer.tsx
So the places the icon font is used on the artwork page are modal and once they appear on page the font will load, so there shouldn't be a need to preload this.
=> chore: removes icon fonts preload

src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/ArtistConsignHeaderImages.tsx, src/v2/Apps/Artist/Routes/Consign/__tests__/ArtistConsignRoute.jest.tsx, src/v2/Apps/Auction/Components/LotInfo.tsx, src/v2/Apps/Conversation/Components/Details.tsx, src/v2/Apps/FeatureAKG/Components/Feature.tsx, src/v2/Apps/FeatureAKG/Components/FeaturedArticles.tsx, src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
In an effort to fix an issue with Image width & height I'm removing this old `ResponsiveImage` component that shouldn't ever be used. Replaced with one-off inline styles.
=> refactor: removes remaining instances of deprecated responsive image

src/v2/Apps/Artwork/Components/ArtworkBanner/ArtworkBanner.tsx, src/v2/__generated__/ArtworkBannerQuery.graphql.ts, src/v2/__generated__/ArtworkBanner_Test_Query.graphql.ts, src/v2/__generated__/ArtworkBanner_artwork.graphql.ts, src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Fixes a few things: prevents the layout shift that was happening with images, prevents the layout shift that was happening with the svg (don't force things to center using `top`), and fixes the vertical centering (in general if you're trying to position a single line of text centered in small container: set the lineHeight to 1.
=> fix(artwork): fixes layout shift in artwork banner

src/desktop/apps/about/client/view.coffee
A previous change altered the way images were loaded (previously they were dynamically loaded off data-src attrs) and then swapped. This should have broken all the images but the slideshow code that had the `throw` in it was preventing the image loading code from executing. Once the slideshow was guarded against, this broke the images.
=> fix(about): fixes about page images

src/v2/Apps/Unsubscribe/UnsubscribeApp.tsx, src/v2/Apps/Unsubscribe/__tests__/UnsubscribeApp.jest.tsx
Isabelle caught this issue where if you were logged in AND had a token we wouldn't show anything. This PR fixes that to prefer the logged in email options.
=> fix(unsubscribe): clears up logic when presenting opt out form

package.json, webpack/envs/clientDevelopmentConfig.js, webpack/envs/clientPlugins.js, webpack/envs/clientProductionConfig.js, yarn.lock
Moment Timezone provides a webpack plugin that minimizes the timezone
data we need to include client-side, this adds the plugin and limits the
timezones to the only one that is used in v2 apps `America/New_York`
Timezone data from 32 KiB gzip -> 300 bytes gzip
Before
After
=> feature: Minimize Moment Timezone

src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx, src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/__tests__/FairOrganizerHeader.jest.tsx, src/v2/Components/Timer.tsx, src/v2/Utils/Hooks/useTimer.tsx
[FX-3189]
This PR fixes text size of timer on auction artwork page and extracts timer logic from component to hook
**Before** 
**After**
[FX-3189]: https://artsyproduct.atlassian.net/browse/FX-3189
=> fix(FX-3189): Auction timer

src/desktop/apps/partnerships/templates/auction_sections.jade, src/desktop/apps/partnerships/test/templates.test.js
[GRO-405]
Had to redo this PR due to an extra untracked repo
Changes included:
Add Consignments section below Access. Please see google doc here with text to add about Consignments and the placement
Move the Interested in Partnering with Artsy section to the top after the Experience section as a CTA.
Updated the gif under the Visibility section.
New Behavior for Visibility Section:
[GRO-405]: https://artsyproduct.atlassian.net/browse/GRO-405
=> GRO-405: Update artsy.net/auction-partnerships/ page

src/v2/Apps/Consign/Routes/MarketingLanding/Components/PromoSpace.tsx
Made a small change to the gallery promospace where before the promospace was hovering over the header image.
=> Fix: very small tweak to gallery promospace margin on consign page

src/desktop/apps/articles/templates/meta/team_channel.jade
This is a quick PR to just add a particular meta tag to a marketing page. The goal here is to signal to Google that we don't want the Buying with Artsy marketing page to show up as a site link.
https://artsyproduct.atlassian.net/browse/GRO-485
=> feat: Disable search box for marketing page GRO-485

src/v2/Apps/Order/Components/SavedAddressItem.tsx
Jira Ticket: https://artsyproduct.atlassian.net/browse/PX-4326
Discussion: https://github.com/artsy/force/pull/7869#discussion_r669827365
This PR deletes `Pill` component usage with  `!important`  in styles and add a custom "Default" label instead of `Pill` in BNMO Checkout flow. Also, I deleted deprecated `color` and put `themeGet("colors.black10")` instead.
This PR resolves this [Jira Ticket](https://artsyproduct.atlassian.net/browse/PX-4367) too, so I closed it.
https://user-images.githubusercontent.com/55637696/129696004-8590e1b1-5a09-4900-9ded-008db9c92c84.mov
=> fix(PX-4326): Don't manually override background in Pill component in SavedAddresses

package.json, src/desktop/components/split_test/setup.coffee, src/desktop/components/split_test/split_test.coffee, src/lib/cache.js, src/lib/metaphysics2.coffee, webpack/envs/clientDevelopmentConfig.js, webpack/envs/clientPlugins.js, webpack/envs/clientProductionConfig.js, webpack/envs/commonEnv.js, webpack/envs/commonLoaders.js, yarn.lock
Round 2 of slim lodash, it turns out that the lodash-webpack-plugin
is aggressive by default. An extra configuration option was
required to enable all the functionality we use.
The new change:
https://github.com/artsy/force/compare/feature-loadash-slim?expand=1#diff-fbd53dc365f51bf49b96ebd837db791e14e93411af4f3b66980a61ec563efddcR10
The previous PR:
https://github.com/artsy/force/pull/8206/files
=> feature: Slim Lodash

webpack/envs/clientPlugins.js
This PR enables Lodash currying in the `lodash-webpack-plugin`. This functionality 
is required for `.reverse()` to work.
There may be a couple of extra feature sets that will need enabling to support all of
the features we used from Ldoash. These will be enabled as needed to limit how
much scope is brought into our client bundles.
=> feature: Enable Lodash Currying

cypress/integration/home.spec.ts, src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
Marketing banners are updated in the admin tool but the sign up banner for logged out users is hardcoded in the Home app. Looking in the code, it seems to me the reason why this is hardcoded is because it renders conditionally based on the isLoggedOut user status... but I don't see why this can't also be moved into the admin app? The copy lives in something called a HeroUnit, which is just a statically-typed object. I'm not sure how admin app stuff gets into force, but I could probably figure it out.  
Waiting on new sub-header copy from the brand team and then this pr is ready to go.
=> [GRO-460] Update image/copy in homepage banner for logged out users

src/v2/Apps/Consign/Routes/MarketingLanding/Components/SoldRecently.tsx
The use of `QueryRenderer` here seemed to be causing a server/client mismatch and messing up the render. We want this to be loaded client-side anyway.
=> fix(consign): fixes render mismatch

src/v2/Apps/Auctions/Components/TrendingLots/TrendingLots.tsx, src/v2/Apps/Auctions/Components/TrendingLots/__tests__/TrendingLots.jest.tsx, src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts, src/v2/__generated__/TrendingLots_Test_Query.graphql.ts, src/v2/__generated__/TrendingLots_viewer.graphql.ts, src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
This is for [GRO-469].
We wanted to update Trending Lots to remove any closed lots from being displayed.
Note: Currently we do not have any "Trending Lots" in staging that are open. So we do not have local screen shots to show other then the empty state curatorial rail.
[GRO-469]: https://artsyproduct.atlassian.net/browse/GRO-469
=> GRO-469: Updated Trending Lots to remove closed lots

src/v2/Apps/FairOrginizer/Components/FairOrganizerPastEventsRail.tsx
This PR resolves [FX-3207]
The images in the events carousel should sit next to each other in the row. The text should sit below the images and can push the scroll bar down as needed.
[FX-3207]: https://artsyproduct.atlassian.net/browse/FX-3207
=> fix(FX-3207): align carousel items on fair organizer page

src/v2/Apps/Fair/Components/ExhibitorsLetterNav.tsx, src/v2/Apps/Fair/Components/__tests__/ExhibitorsLetterNav.jest.tsx, src/v2/Apps/Fair/Routes/FairExhibitors.tsx, src/v2/Apps/Fair/Routes/__tests__/FairBooths.jest.tsx, src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx, src/v2/__generated__/ExhibitorsLetterNav_Test_Query.graphql.ts, src/v2/__generated__/ExhibitorsLetterNav_fair.graphql.ts, src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts, src/v2/__generated__/FairExhibitors_fair.graphql.ts, src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
[FX-3158]
[FX-3158]: https://artsyproduct.atlassian.net/browse/FX-3158
**The purpose of this PR** is to add the ”A B C … X Y Z 0-9” navigator to the top of the new Exhibitors A-Z tab.
**Acceptance criteria:**  clicking on a single “letter” (A, B, C…) in the filter tab scrolls down the page
=> feat(FX-3158): Fair exhibitors A-Z navigation

src/v2/Apps/Auctions/Components/StandoutLots/StandoutLots.tsx, src/v2/Apps/Auctions/Components/StandoutLots/__tests__/StandoutLots.jest.tsx, src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts, src/v2/__generated__/StandoutLots_Test_Query.graphql.ts, src/v2/__generated__/StandoutLots_viewer.graphql.ts, src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
[GRO-469]
Continuing logic to remove `bidding closed` lots from Standout Lots and Trending Lots Rails
New Behavior:
=> GRO-469: Updated Standout Lots with logic to exclude bidding closed lots

src/v2/Apps/Auctions/Routes/CurrentAuctions.tsx, src/v2/Apps/Auctions/Routes/PastAuctions.tsx, src/v2/Apps/Auctions/Routes/UpcomingAuctions.tsx
[GRO-466]
This is to resolve the bug we are seeing that is causing spacing issues with the Current/Past/Upcoming Auction Rails.
New Behavior:
=> GRO-466: Seeing Spacing Issues with Auction Rails

src/v2/Components/Authentication/Desktop/LoginForm.tsx
This PR addresses a bug introduced in the [PR](https://github.com/artsy/force/pull/7800) that displayed the submit button spinner while the page redirect was being completed. 
Issue
The submit spinner would spin indefinitely if the same error response was received a second time (e.g., the user input the wrong username, password, or otp twice in a row). 
This was the result of the `isLoading` flag not being reset to `false` upon the second submission. This has been resolved by adding the formik `status` prop to the `useEffect` subscriptions. 
Before:
After:
=> fix: login spinner handles repeat error responses

src/v2/Apps/Fair/Components/FairOverview/FairAbout.tsx, src/v2/Apps/Fair/Components/FairOverview/FairOverview.tsx, src/v2/__generated__/FairAbout_fair.graphql.ts, src/v2/__generated__/FairOverview_Test_Query.graphql.ts, src/v2/__generated__/FairOverview_fair.graphql.ts, src/v2/__generated__/fairRoutes_FairOverviewQuery.graphql.ts
Jira: [FX-3208](https://artsyproduct.atlassian.net/browse/FX-3208)
The purpose of the ticket is hide About header if no about content present (example below)
- Added condition to render About info
- Move About content to separate component
- Refactor spaces between Overview tab sections (replace borders with `<Separator />`)
_Desktop_
_Mobile_
=> feat(FX-3208): hide empty about section

docs/best_practices.md
Adds a section on why we should avoid implicit returns in multi-line react components.
=> docs: Add section about implicit returns in FAQ

src/v2/Components/FullBleedHeader.tsx
Ensures the header has enough room for a CTA on much shorter screens.
=> fix(headers): sets a minimum height on full-bleed header

src/v2/Components/Inquiry/__tests__/views/InquiryCommercialInterest.jest.tsx, src/v2/Components/Inquiry/useUpdateMyUserProfile.tsx, src/v2/Components/Inquiry/views/InquiryCommercialInterest.tsx, src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts
Alright first step is an easy one. Thankfully the MP mutation supports `collectorLevel`, though I'm going to have to update it for the others.
https://user-images.githubusercontent.com/112297/130658630-5fabbb50-72fb-4526-bd9d-a82345470d54.mov
I'll PR `BasicInfo` next. (which is the next screen you see in that recording)
=> feat(inquiry): implements commercial interest step

src/v2/Apps/Fair/Components/ExhibitorsLetterNav.tsx, src/v2/Apps/Fair/FairApp.tsx, src/v2/Apps/Fair/Routes/FairBooths.tsx, src/v2/Apps/Fair/Routes/FairExhibitors.tsx, src/v2/Components/Sticky/Sticky.tsx
Jira: [FX-3118](https://artsyproduct.atlassian.net/browse/FX-3118)
The purpose of the ticket is make fair tabs and A-Z exhibitors navigation sticky.
- Added Sticky component where necessary
- Added Box props for <Sticky /> to custom sticky component
- mini refactor: added spacing to Booths tab (sort was very close to tabs)
_Desktop_
https://user-images.githubusercontent.com/56556580/130620242-c907a5c6-a76e-4ff8-903e-2515f83f4c5d.mov
_Mobile_
https://user-images.githubusercontent.com/56556580/130620430-5171f949-9c2a-41f8-b6d4-9054afc28ec9.mov
=> feat(FX-3118): make fair tabs sticky

src/v2/Apps/Fair/Components/ExhibitorsLetterNav.tsx, src/v2/Apps/Fair/FairApp.tsx, src/v2/Apps/Fair/Routes/FairBooths.tsx, src/v2/Apps/Fair/Routes/FairExhibitors.tsx, src/v2/Components/Sticky/Sticky.tsx
Reverts artsy/force#8258
Have to revert unfortunately due to some QA feedback from Jonathan & @thomasmeerschwam:
> The tabs should maintain the 12col structure, though there should be a drop-shadow that spans 100%
>
> https://www.figma.com/file/aM3b5sodn04vMTigbQXACi/Fairs-2021?node-id=3904%3A12987
Hoping to get this back out soon!
cc/ @tr-ann
=> Revert "feat(FX-3118): make fair tabs sticky"

hokusai/config.yml
This re-adds git deploy tags that were removed in https://github.com/artsy/force/pull/3988. (Git tags are common across hokusai repos.)
=> hokusai: Readd git deploy tags

src/v2/Apps/ViewingRoom/Components/ViewingRoomTabBar.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx, src/v2/Apps/ViewingRoom/viewingRoomRoutes.tsx
[FX-3200]
The URL structures of viewing room works tab were not consistent on Eigen and Force:
This worked in Force but not Eigen: https://www.artsy.net/viewing-room/pearl-lam-galleries-mr-doodle-the-pop-heart-collection/works
And this worked in Eigen but not Force: https://www.artsy.net/viewing-room/pearl-lam-galleries-mr-doodle-the-pop-heart-collection/artworks
This PR changes url structure for viewing room works tab in Force(`:id/works` → `:id/artworks`)  so that this page will be accessible everywhere via the same url
Demo
Redirect
=> feat(viewing room): redirect viewing room route /works to /artworks

src/v2/Apps/FairOrginizer/Routes/FairOrganizerDedicatedArticles.tsx, src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts, src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts, src/v2/__generated__/FairOrganizerDedicatedArticles_fairOrganizer.graphql.ts, src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts
[FX-3206]
Current PR supplements https://github.com/artsy/force/pull/8285 as articles should be sorted by `PUBLISHED_AT_DESC` not only on `/fair-organizer/:slug` but on `/fair-organizer/:slug/articles` as well
**Before**
**After**
=> fix(fair organizer): update articles sort order to PUBLISHED_AT_DESC rework

src/v2/Apps/Purchase/Components/OrderRow.tsx, src/v2/Apps/Purchase/Components/PurchaseHistory.tsx, src/v2/Apps/Purchase/purchaseRoutes.tsx
Migrate Purchases app on force to use Palette V3
__Before:__
__After:__
=> Convert purchases app to palette v3

src/v2/Apps/FairOrginizer/Components/DedicatedArticlesBreadcrumbs.tsx, src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx, src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx, src/v2/__generated__/DedicatedArticlesBreadcrumbs_Test_Query.graphql.ts, src/v2/__generated__/DedicatedArticlesBreadcrumbs_fairOrganizer.graphql.ts, src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts, src/v2/__generated__/FairOrganizerApp_fairOrganizer.graphql.ts, src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts, src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts, src/v2/__generated__/FairOrganizerHeader_Test_Query.graphql.ts, src/v2/__generated__/FairOrganizerHeader_fairOrganizer.graphql.ts, src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts, src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
The default fair sort in Gravity is -created_at. When looking for an upcoming fair for an organizer, we currently fetch the first fair and check if the start time is in the future. If a past fair is created after a future fair, we might be checking the wrong entity in the system.
This updates the GraphQL query to sort fair results by `-start_at` to mimic the behavior in the previous implementation [here][commit].
Related to https://github.com/artsy/metaphysics/pull/3377
Jira 🔒 : [FX-3243]
[commit]: https://github.com/artsy/force/blob/4de69dfc0d2d26cbe43b7e5ffefc0a88e44333ac/src/desktop/apps/fair_organizer/routes.coffee#L36-L41
[FX-3243]: https://artsyproduct.atlassian.net/browse/FX-3243
=> fix(fair organizer): sort fairs by -start_at to determine upcoming show

src/v2/Components/Search/SearchBar.tsx
Follows up on [CX-1761]
https://github.com/artsy/force/pull/8246 introduced a bug that prevented the `SearchBar` from clearing the search term after clicking on a suggestion item.
This fix ensures the search term gets cleared every time the user clicks on a suggestion item.
**Before:**
https://user-images.githubusercontent.com/4691889/131504182-5eec1cc6-6c6c-402d-93d6-a3413e1d4bf9.mov
**After:**
https://user-images.githubusercontent.com/4691889/131504515-13faa211-d019-4418-a7b1-e0329dad1911.mov
[CX-1761]: https://artsyproduct.atlassian.net/browse/CX-1761
=> fix: Always clear search term after navigating away from search results

src/v2/Components/Search/SearchBar.tsx, src/v2/Components/Search/Suggestions/SuggestionItem.tsx, src/v2/Components/Search/__tests__/SearchBar.jest.tsx, src/v2/__generated__/SearchBarRefetchQuery.graphql.ts, src/v2/__generated__/SearchBarSuggestQuery.graphql.ts, src/v2/__generated__/SearchBarTestQuery.graphql.ts, src/v2/__generated__/SearchBar_viewer.graphql.ts
Bug report: https://artsy.slack.com/archives/C9SATFLUU/p1630422168184900
Debugging: https://artsy.slack.com/archives/C9SATFLUU/p1630422550187900
This reverts #8309 and #8246 which may have interfered with click handling on the search results dropdown.
cc @olerichter00
=> fix: revert recent search work to fix search result dropdown bug

src/v2/Components/Search/SearchBar.tsx, src/v2/Components/Search/Suggestions/SuggestionItem.tsx, src/v2/Components/Search/__tests__/SearchBar.jest.tsx, src/v2/__generated__/SearchBarRefetchQuery.graphql.ts, src/v2/__generated__/SearchBarSuggestQuery.graphql.ts, src/v2/__generated__/SearchBarTestQuery.graphql.ts, src/v2/__generated__/SearchBar_viewer.graphql.ts
* Revert "fix: Always clear search term after navigating away from search results (#8309)"
This reverts commit ed7e907f4791589867deaba40fc0fb52cc6f60b8.
* Revert "Merge pull request #8246 from artsy/olerichter00/CX-1761/add-quick-navigation-to-search-items"
This reverts commit 74809b11f914bd013c5750977daf328b1315d803, reversing
changes made to 028f7eddd1268f57b656b3cae859b99bd87088f1.
=> Deploy (search fix)

package.json, yarn.lock
This PR bumps artsy-passport up to 3.2.0, which support the on-demand otp implementation. 
Supporting PRs:
-  [Force](https://github.com/artsy/force/pull/8274)
-  [Passport](https://github.com/artsy/artsy-passport/pull/171)
=> update artsy-passport to 3.2.0

src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx, src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorGroupPlaceholder.tsx, src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorsGroup.tsx
Jira: [FX-3077](https://artsyproduct.atlassian.net/browse/FX-3077)
Changes done after failed [QA](https://artsyproduct.atlassian.net/browse/FX-3077?focusedCommentId=40596)
- Images are lazy load
- Show 4 partner cards until the XS viewport
https://user-images.githubusercontent.com/56556580/131655061-8a415a14-bcf7-418c-8cee-0c10dd403b49.mov
=> fix(FX-3077): make images lazy load

src/config.ts, src/desktop/components/main_layout/templates/head.jade, src/lib/setup_sharify.js, src/mobile/components/layout/templates/head.jade, src/v2/index.ejs, src/v2/server.ts
https://artsyproduct.atlassian.net/browse/PLATFORM-3176
Add OneTrust javascripts and attempt to make them fire first on page load. This is to implement [Cookie Consent](https://www.notion.so/artsy/Cookie-Consent-01dace52a765476ea4e9353260ce9a7f). The tags are copied from [OneTrust's UI](https://app-eu.onetrust.com/cookies/websites).  Over there we configure consent banner, preference-center, cookie-blocking, and other things. The scripts implement those settings. Generally, changes on their UI take effect only when the scripts are re-published, here:
There  are 2 set of scripts, `Test` and `Production`. They differ only in an ID which is parameterized into the `ONETRUST_SCRIPT_ID` ENV var whose presence in config enables the scripts.
- `Test` tag ID: …
=> feat: artsy.net cookie consent.

src/dev.js, src/index.js, src/lib/loadenv.js, webpack/utils/env.js
This CL adds a condition to `lib/loadenv` and `utils/env` that prevents overwriting existing env vars that are already set. This matches the same rule that `dotenv` package adheres to: [never modify any environment variables that have already been set](https://github.com/motdotla/dotenv#what-happens-to-environment-variables-that-were-already-set). The `package.json` scripts that export `NODE_ENV=production` will now behave as expected even if a contributor has `NODE_ENV=development` in `.env`.
Additionally:
- updated `loadenv` to match the implementation in `utils/env` as I find it better
- moved the `loadenv` imports to the top of the files
=> fix(loadenv): prevent modifying already set env vars

src/v2/Apps/Search/Routes/Artists/SearchResultsArtists.tsx, src/v2/__generated__/SearchResultsArtistsQuery.graphql.ts, src/v2/__generated__/SearchResultsArtists_viewer.graphql.ts, src/v2/__generated__/searchRoutes_SearchResultsArtistsQuery.graphql.ts
[FX-3244]
Pagination on artists search results page was broken as `term` param was missing in `refetchVariables` when refetching data
This fixes broken behavior and also makes some refactoring 
**Before**
https://user-images.githubusercontent.com/44819355/131660081-f68d1044-2551-450e-afee-fc5afcab86f8.mp4
**After**
=> fix(FX-3244): Fix artists search results pagination

src/v2/Apps/FairOrginizer/Components/FairOrganizerLatestArticles.tsx, src/v2/Apps/FairOrginizer/Components/__tests__/FairOrganizerLatestArticles.jest.tsx
A newly-created Fair Organizer was failing to load on production with 500 errors. After investigating, @dblandin and I figured out that the problem was that we assumed that all fair organizers had associated articles. 
Slack thread: https://artsy.slack.com/archives/C9SATFLUU/p1630573114272300
=> fix: stop fair organizer page from crashing with no articles

src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx, src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorGroupPlaceholder.tsx, src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx, src/v2/__generated__/FairExhibitorCard_partner.graphql.ts, src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts, src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Jira: [FX-3249](https://artsyproduct.atlassian.net/browse/FX-3249)
The exhibitors listed in the A-Z tab should be formatted as per the latest 8/23 “Work in Progress” figma file. In particular we shouldn't display exhibitors image.
[Figma spec](https://www.figma.com/file/aM3b5sodn04vMTigbQXACi/Fairs-2021?node-id=3904%3A8029)
- Removed image from exhibitor card
- Wrap text when overflow
- Updated exhibitors placeholder
=> feat(FX-3249): updated exhibitors tab style

src/desktop/components/main_layout/templates/head.jade, src/mobile/components/layout/templates/head.jade, src/v2/index.ejs
We [released](https://github.com/artsy/force/pull/7841) Cookie Consent to staging, and [it's noticed](https://artsy.slack.com/archives/CA8SANW3W/p1630595596158400) that the banner is being shown in mobile app's webviews. We are not ready to implement Consent in the app, so let's disable.
=> fix: if we are in eigen, disable onetrust.

src/lib/cacheClient.tsx, src/lib/middleware/__tests__/redisPageCache.jest.ts, src/lib/middleware/memoryPageCache.ts, src/lib/middleware/pageCacheCommon.ts, src/lib/middleware/redisPageCache.ts, src/middleware.ts, src/v2/Utils/logger.ts
Updates the existing redis page cache to record responses from the new
server middleware architecture, this code previously no longer worked.
See previous PR for additional details:
https://github.com/artsy/force/pull/5047
=> feature: Redis Page Cache

src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx, src/v2/Apps/Artist/artistRoutes.tsx
Addresses [CX-1874]
Increases artist auction result's default createdBeforeYear value to fix a bug where recent auction results were filtered out on initial load.
[CX-1874]: https://artsyproduct.atlassian.net/browse/CX-1874
=> fix: Increase artist auction results default end date

src/v2/Apps/FairOrginizer/Components/DedicatedArticlesBreadcrumbs.tsx, src/v2/Apps/FairOrginizer/Components/FairOrganizerHeaderImage.tsx, src/v2/Apps/FairOrginizer/Components/__tests__/DedicatedArticlesBreadcrumbs.jest.tsx, src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx, src/v2/Apps/FairOrginizer/__tests__/FairOrganizerApp.jest.tsx, src/v2/__generated__/DedicatedArticlesBreadcrumbs_Test_Query.graphql.ts, src/v2/__generated__/DedicatedArticlesBreadcrumbs_fairOrganizer.graphql.ts, src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts, src/v2/__generated__/FairOrganizerApp_fairOrganizer.graphql.ts, src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts, src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts, src/v2/__generated__/FairOrganizerHeaderImage_fairOrganizer.graphql.ts, src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts, src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
Update the fair organizer page to use the organizer image in:
- The header hero image
- The breadcrumb link on the articles page
Jira: [FX-3276]
**Screenshots**
A few examples of the difference. Left (current / fair). Right (fair organizer).
[FX-3276]: https://artsyproduct.atlassian.net/browse/FX-3276
=> feat: update fair organizer page to use organizer profile image

src/v2/Apps/Order/Routes/Status/index.tsx
**JIRA** -> [Remove Back to Artsy link from inquiry checkout counteroffer modal](https://artsyproduct.atlassian.net/jira/software/c/projects/PURCHASE/boards/41?modal=detail&selectedIssue=PURCHASE-2895&assignee=60469b1e43eac6006f636d07)
**What I've done**:
- removed the `go back to artsy` button from the modal offer status, when buyer/seller declines a counteroffer
- refactored code
- added isModal checker due this behavior won't just be for declined statuses, the CTA opens the page modally whenever the partner takes any action
**GIF**
p.s. sorry for the fast gif... just wanted to show that we don't have a button for declined offers from now :)
=> feat(PURCHASE-2895): Remove back to artsy button

src/v2/Components/Authentication/Desktop/LoginForm.tsx, src/v2/Components/Authentication/Types.ts, src/v2/Components/Authentication/__tests__/Desktop/LoginForm.jest.tsx, src/v2/Components/Authentication/helpers.ts
This PR enables Force to handle on-demand otp related errors, which were enabled in Gravity in this [PR](https://github.com/artsy/gravity/pull/14395/files).
When we are ready to enable this functionality we will set `enforces_on_demand_otp` to `true` on the `ClientApplicaiton`. This will be tested out in staging before being set on production.
When an on-demand otp is required from the User, they will see the following prompt:
=> (PLATFORM-3537) feat: login form supports on-demand otp

src/v2/Apps/Fair/Components/FairBoothRail/FairBoothRailArtworks.tsx, src/v2/Apps/Fair/fairRoutes.tsx
Jira: [FX-3286](https://artsyproduct.atlassian.net/browse/FX-3286)
We’ve removed the Booths tab in favor of placing the booths under the overview tab.
This ticket involves adding a 301 redirect to /booths to the root fair URL. Should also be placed under the same feature flag as AZ + booths switch.
- Added redirect to booths route
- Fix warning in booth rail artworks (each component should have unique key)
https://user-images.githubusercontent.com/56556580/132510677-5b9be3c5-0511-420d-bb22-e213b2e53fbb.mov
=> feat(FX-3286): redirect to fair overview

src/v2/Apps/Conversation/Components/Conversation.tsx
paired with @copperkraft 
No status refresh after seller accepts or declines an offer
Current behaviour:
Given a seller made an offer,
And the buyer made a counteroffer,
When the seller declines or accepts the counteroffer,
Then  you close the counteroffer review modal,
And the conversation page does not refresh,
And the "counteroffer received" status persists until manual refresh.
Improved behaviour:
Given a seller made an offer,
And the buyer made a counteroffer,
When the seller declines or accepts the counteroffer,
Then you close the counteroffer review modal,
And the conversation page refreshes,
And the "counteroffer received" status changes into "Offer declined" or "Offer accepted" accordingly.
=> Fix: Refresh conversation page on modal close

src/v2/Apps/Order/Components/AddressModal.tsx, src/v2/Apps/Order/Components/SavedAddressItem.tsx, src/v2/Apps/Order/Components/SavedAddresses.tsx, src/v2/Apps/Shipping/shippingRoutes.tsx, src/v2/Components/Address/AddressModalFields.tsx, src/v2/Components/Payment/PaymentModal.tsx, src/v2/Components/UserSettings/UserSettingsAddresses.tsx
[PURCHASE-2876]
Migrate Shipping app on force to use Palette V3.
__Before:__
__After:__
[PURCHASE-2876]: https://artsyproduct.atlassian.net/browse/PURCHASE-2876
=> refactor: migrates Shipping app to use Palette V3

src/v2/server.ts
Fixes https://artsyproduct.atlassian.net/browse/PURCHASE-2924
The [previous attempt](https://github.com/artsy/force/pull/8345) to exclude cookie consents JS for Eigen didn't work. The reason was that we [used a new instance of sharify](https://github.com/artsy/force/blob/07ddb110a241bebb9e948493321d81f5fef0e1a7/src/v2/server.ts#L96), which didn't go through the [bootstrap process](https://github.com/artsy/force/blob/6045498ca44242ca0d556b67f94ac24dc00d8074/src/middleware.ts#L106) that `res.locals.sharify` did. Therefore, `sd.Eigen` wasn't present.
This updates the use of sharify in v2 server to always use the instance from `res.locals.sharify`, instead of importing a new instance again. Looks like this also fixes `CURRENT_PATH` that `apple-itunes-app` meta tag relies on.
=> fix: use sharify instance from res.locals (PURCHASE-2924)

src/v2/Apps/Home/Components/HomeFeaturedEventsRail.tsx
Minor thing; staging looks like it's missing part of the fragment for these (don't know why); which is causing the broken layout. This is an actual bug; though generally we shouldn't see this state as anything that is going to be featured is probably going to have an image. Regardless.
=> fix(homepage): fixes missing image state

src/v2/Components/Inquiry/Hooks/useArtworkInquiryRequest.ts, src/v2/Components/Inquiry/Views/InquiryInquiry.tsx, src/v2/Components/Inquiry/Views/InquiryLogin.tsx, src/v2/Components/Inquiry/Views/InquirySignUp.tsx, src/v2/Components/Inquiry/Views/InquirySpecialist.tsx, src/v2/Components/Inquiry/__tests__/Views/InquirySpecialist.jest.tsx
Allows the form to be opened in specialist-mode — for instance, for artworks that are in auctions.
<del>Draft because I realized I need to add the `contact_gallery` boolean to the Metaphysics mutation 😅 </del>
```tsx
useInquiry({ artworkID: 'example', askSpecialist: true })
```
=> feat(inquiry): implements specialist form

cypress/integration/shows.spec.ts
The reason for this error was "Presented by" string that is a bit specific for different show items(_show/daniel-cooney-fine-art-daniel-cooney-fine-art-at-art-on-paper-2021?sort=partner_show_position_). It was replaced by **Sow** because this string is common for all items!
Thanks @copperkraft for paring!
=> fix cypress test

src/v2/Apps/Fair/Components/ExhibitorsLetterNav.tsx, src/v2/Apps/Fair/Components/__tests__/ExhibitorsLetterNav.jest.tsx, src/v2/Apps/Fair/Routes/FairExhibitors.tsx, src/v2/Apps/Fair/Utils/getExhibitorSectionId.ts
This PR resolves [FX-3289]
https://user-images.githubusercontent.com/3513494/133285078-a7e68e97-19d1-4fc8-9bad-cbc33cd5a98a.mp4
* numeral, special characters sections are grouped into one
* `#` section is enabled if there are some numerals, special characters and scrolls to it
* `#` section is after letter sections
For more context: [Slack discussion](https://artsy.slack.com/archives/C9SATFLUU/p1631175036487800?thread_ts=1631117497.458800&cid=C9SATFLUU)
[FX-3289]: https://artsyproduct.atlassian.net/browse/FX-3289
=> fix(FX-3289): Group all numeral together

cypress/integration/shows.spec.ts, src/v2/Apps/Order/Components/AddressModal.tsx, src/v2/Components/Inquiry/Hooks/useArtworkInquiryRequest.ts, src/v2/__generated__/useArtworkInquiryRequestMutation.graphql.ts
I found a small bug, I don't know the reason for it. Initial values for Formik is gotten from relay and marked like readonly. So we get an error when we try to change this field.An Spread operator solved this issue. (https://artsyproduct.atlassian.net/browse/PURCHASE-2931)
=> fix(PURCHASE-2931):Editing saved address in form cause page to crash

src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
[FX-3231]
This fixes broken layout of articles on fair organizer page at large screen width 
**Before**
**After**
[FX-3231]: https://artsyproduct.atlassian.net/browse/FX-3231
=> fix(FX-3231): Removed max width of fair article

src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx, src/v2/Apps/Show/Components/ShowHeader.tsx, src/v2/Apps/Show/Components/ShowNavigationBanner.tsx, src/v2/Apps/Show/ShowApp.tsx, src/v2/Apps/Show/__tests__/ShowApp.jest.tsx, src/v2/__generated__/ShowApp_Test_Query.graphql.ts, src/v2/__generated__/ShowApp_show.graphql.ts, src/v2/__generated__/ShowHeader_show.graphql.ts, src/v2/__generated__/ShowNavigationBanner_show.graphql.ts, src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Jira: [FX-3280](https://artsyproduct.atlassian.net/browse/FX-3280)
As a collector, I should be able to go back to the Fairs 'Exhibitors A-Z' tab after clicking through to view a Fairs 'Show'. Currently, there is no navigational banner making it explicit and easy for the collector to go back to the Fair page to continue browsing exhibitors within a Fair.
[Figma](https://www.figma.com/file/aM3b5sodn04vMTigbQXACi/Fairs-2021?node-id=3474%3A17827)
- Added navigation bar with link to `/fair/:slug/exhibitors`
When redirect from fair
https://user-images.githubusercontent.com/56556580/133590538-91e5a1fd-d89c-4899-8f10-ed320385be22.mov
When redirect from shows page
https://user-images.githubusercontent.com/56556580/133590568-f2e7b15a-df3d-450d-9f38-eb0bb7e86902.mov
=> feat(FX-3280): added back link for fair shows

src/v2/Components/Search/SearchBar.tsx
=> fix(searchbar): prevents menu item hit areas from presenting over the results

src/v2/Apps/Home/Components/HomeFeaturedGalleriesRail.tsx, src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx, src/v2/Apps/Home/Components/HomeFeaturedShows.tsx, src/v2/Apps/Home/HomeApp.tsx, src/v2/Apps/Home/__tests__/HomeApp.jest.tsx, src/v2/Apps/Home/__tests__/HomeFeaturedGalleriesRail.jest.tsx, src/v2/Apps/Home/__tests__/HomeFeaturedMarketNews.jest.tsx, src/v2/Apps/Home/homeRoutes.tsx, src/v2/__generated__/HomeApp_Test_Query.graphql.ts, src/v2/__generated__/HomeApp_featuredEventsOrderedSet.graphql.ts, src/v2/__generated__/HomeFeaturedGalleriesRailQuery.graphql.ts, src/v2/__generated__/HomeFeaturedGalleriesRail_Test_Query.graphql.ts, src/v2/__generated__/HomeFeaturedGalleriesRail_orderedSet.graphql.ts, src/v2/__generated__/HomeFeaturedMarketNewsQuery.graphql.ts, src/v2/__generated__/HomeFeaturedMarketNews_Test_Query.graphql.ts, src/v2/__generated__/HomeFeaturedMarketNews_articles.graphql.ts, src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
Related https://github.com/artsy/force/pull/8398, https://github.com/artsy/metaphysics/pull/3425
Addresses https://artsyproduct.atlassian.net/browse/GRO-518 
This adds a new featured galleries rail to the home page: 
There's some weird type weirdness around `extractNodes` that I need to figure out but otherwise ready to review.
=> feat: [Home] Add new featured galleries rail 

src/v2/Components/Search/SearchBar.tsx, src/v2/Components/Search/Suggestions/SuggestionItem.tsx, src/v2/Components/Search/__tests__/SearchBar.jest.tsx, src/v2/__generated__/SearchBarRefetchQuery.graphql.ts, src/v2/__generated__/SearchBarSuggestQuery.graphql.ts, src/v2/__generated__/SearchBarTestQuery.graphql.ts, src/v2/__generated__/SearchBar_viewer.graphql.ts
Addresses [CX-1761]
Adds quick navigation items ("Artworks" & "Auction Results") to the search bar's autosuggest items for artists.
[CX-1761]: https://artsyproduct.atlassian.net/browse/CX-1761
=> feat: Add autosuggest quick navigation (second try)

src/v2/Components/Artwork/Badge.tsx, src/v2/Components/Artwork/GridItem.tsx
Closes [GRO-499](https://artsyproduct.atlassian.net/browse/GRO-499)
Simple fix; just pulls out and uses the `srcSet`, also adjusts the max-width to be the rendered size at our max breakpoint.
This PR also includes a quick fix for the tiny auction badge which no longer needs to be manually offset 🎈
=> fix(artworkgriditem): uses correct max width; supports srcset

src/v2/Apps/Search/Components/NavigationTabs.tsx, src/v2/Components/Search/SearchBar.tsx
Jira: [FX-3282](https://artsyproduct.atlassian.net/browse/FX-3282)
When you type a query into the search bar and click "Enter", you'll normally be taken to the search results page when you're not choosing one of the results shown in the dropdown menu.
In the case of `&gallery` redirecting you back to the home page, I think that is a bug that we should ticket.
When andgallery is entered, the result of `&Gallery` appears in the dropdown meny, but instead of selecting that result (by clicking on it or using your arrow keys + Enter), hitting Enter takes you to the search results page (as expected). The search results page shows artworks by default but none match the query andgallery. If you click on the Galleries tab, you'll see the one result for &Gallery listed.
It's a bit strange that …
=> fix(FX-3282): encode search query param

src/v2/Components/Authentication/Desktop/LoginForm.tsx, src/v2/Components/Authentication/__tests__/Desktop/LoginForm.jest.tsx
This PR updates the user prompt copy when an on-demand OTP is required to complete a login. 
The updated copy was suggested by the design team in the Slack thread 🔒 [here](https://artsy.slack.com/archives/C02BGC5PW/p1630601789004800).
=> refactor: improve user prompt for on-demand otp

src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx, src/v2/Apps/Home/Components/HomeFeaturedGalleriesRail.tsx, src/v2/Apps/Home/Components/HomeTrendingArtistsRail.tsx, src/v2/Apps/Home/HomeApp.tsx, src/v2/Apps/Home/__tests__/HomeAuctionLotsRail.jest.tsx, src/v2/Apps/Home/__tests__/HomeTrendingArtistsRail.jest.tsx, src/v2/__generated__/HomeAuctionLotsRailQuery.graphql.ts, src/v2/__generated__/HomeAuctionLotsRail_Test_Query.graphql.ts, src/v2/__generated__/HomeAuctionLotsRail_viewer.graphql.ts, src/v2/__generated__/HomeTrendingArtistsRailQuery.graphql.ts, src/v2/__generated__/HomeTrendingArtistsRail_Test_Query.graphql.ts, src/v2/__generated__/HomeTrendingArtistsRail_viewer.graphql.ts
Addresses 
- https://artsyproduct.atlassian.net/browse/GRO-524
- https://artsyproduct.atlassian.net/browse/GRO-520
This adds a new Trending Artists rail to the home page: 
As well as the Auction Lots rail:
=> feat: [Home] Add trending artists & auction lots rail

src/v2/Apps/Order/Routes/Respond/index.tsx
**Addresses:** [PURCHASE-2919](https://artsyproduct.atlassian.net/browse/PURCHASE-2919)
This PR fixes the styling of the "Continue" CTA button on the make offer counteroffer page on mobile web view and on the Eigen modal. 
**Before:**
**After:**
=> fix(PURCHASE-2919): "Continue" CTA styling

src/v2/Apps/Artwork/Components/ArtworkMeta.tsx, src/v2/Apps/Order/OrderApp.tsx, src/v2/Apps/__tests__/Fixtures/Order.ts, src/v2/Utils/isExceededZendeskThreshold.ts, src/v2/__generated__/ArtworkMeta_artwork.graphql.ts, src/v2/__generated__/OrderApp_order.graphql.ts, src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts, src/v2/__generated__/orderRoutes_OrderQuery.graphql.ts
Solves [PURCHASE-2909]
Makes the behaviour of the Zendesk "help" chat bubble match the acceptance criteria detailed in the ticket [https://artsyproduct.atlassian.net/browse/PURCHASE-2442] that implemented it.
* On the artwork page, the widget needs to appear if the artwork price is over $10,000 or equivalent (see below)
* On the checkout / make offer flow, the widget needs to appear if the artwork price is over $10,000 or equivalent (see below)
Threshold:
* USD: US$10000
* AUD: A$13000
* EUR: €8000
* HKD: HK$77000
* GBP: £7000
[PURCHASE-2909]: https://artsyproduct.atlassian.net/browse/PURCHASE-2909
=> fix(PURCHASE-2909): Show zendesk only for BNMO artworks exceeding price threshold

src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx, src/v2/Apps/PriceDatabase/Components/PriceDatabaseSearch.tsx, src/v2/Apps/PriceDatabase/__tests__/PriceDatabaseApp.jest.tsx
🟥 Do not merge yet, this PR might need an update.
Fixes the scrolling behavior on the artist's auction results page by waiting for `MarketStatsQueryRenderer` to load and setting the offset depending on the breakpoint.
https://user-images.githubusercontent.com/4691889/134305465-8caf6848-37ff-43b3-9e3b-e6bd12d032cc.mov
=> fix: Improve artist auction result scrolling behavior

src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx
Makes `MarketStats` `onRendered` prop optional to fix failing tests.
=> fix: Make MarketStats onRendered prop optional to fix tests

src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx, src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx, src/v2/__generated__/CreateUserAddressMutation.graphql.ts, src/v2/__generated__/UpdateUserAddressMutation.graphql.ts
Expands the `auction house` filter by default to show the filter to improve the UX when the user searches for auction results on the new price database landing page.
=> fix: Expand auction house filter by default

src/v2/Apps/Artist/ArtistApp.tsx
We access this webview from a few places in Eigen and the backlink to artist page is confusing UX for users so we are hoping to remove 🙏 
https://artsyproduct.atlassian.net/browse/CX-1972
=> fix: don't render artist back link for eigen

src/v2/Apps/Conversation/Components/Item.tsx
Correct background color is being passed in but for some reason is not showing up correctly. This was likely caused by the v3 migration
__Before:__
__After:__
=> Missing artwork image label background on conversation page

src/v2/Apps/Home/Components/HomeArtworkModules.tsx
A bit of fallout from https://github.com/artsy/force/pull/8455. 
Fixes issue where we updated module string type to a union, but didn't `toUpperCase` on the module key when making a request to MP, leading to a type error. 
Example of auth'd rails now coming through:
=> bugfix: [Home] Fix homepage module display

src/v2/Apps/BuyerGuarantee/Components/Feature.tsx, src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
Addresses visual QA issues from [PURCHASE-2918]
- CTA fill on desktop ✅
> <img width="1074" alt="Screenshot 2021-09-21 at 18 42 08" src="https://user-images.githubusercontent.com/7117670/134215735-de0a9d94-c633-4950-8fad-1da7e71ec23e.png">
- Underlined CTAs ✅
- Truncated images/copy ✅
> <img width="432" alt="Screenshot 2021-09-21 at 18 41 51" src="https://user-images.githubusercontent.com/7117670/134215804-f99851e9-321b-4635-b180-47f6c7c257b1.png">
- Missing image caption on small screens: it seems to be purposefully engineered this way from the top-level component ❌
- Mobile links not working ✅
> ![Sep-21-2021 18-47-47](https://user-images.githubusercontent.com/7117670/134215887-ceda64ca-6033-46e0-af53-ddb5afad246b.gif)
cc: @artsy/purchase-devs 
[PURCHASE-2918]: …
=> fix: Buyer guarantee refactor QA fixes

src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
**Description:**
I initially wanted to use webps for all the images in the price database landing screen and it worked properly locally but it didn't work after deployment in both staging and production.
=> fix: Use PNGs instead of webps for price database

src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx, src/v2/Apps/PriceDatabase/Components/PriceDatabaseSearch.tsx
This PR removes some `Media` wrappers in favour of Palette's responsive props.
=> cleanup: Use responsive props instead of media

src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx, src/v2/Apps/PriceDatabase/PriceDatabase.tsx, src/v2/Apps/PriceDatabase/__tests__/PriceDatabaseApp.jest.tsx
Moves price database screen tracking into `useEffect` (which should fix the flaky tests as well) and adds keys to `PopularArtistsList`.
=> fix: Adjust price database tracking

src/v2/Apps/Order/Routes/Shipping/index.tsx
Adds a spacer after the shipping options. The size aligns with the other spaces on this form.
Addresses [PX-4594]
Before:
After:
[PX-4594]: https://artsyproduct.atlassian.net/browse/PX-4594
=> fix: add some space between shipping options and button

src/v2/Apps/Components/AppShell.tsx, src/v2/DevTools/MockBoot.tsx, src/v2/System/Router/Boot.tsx, src/v2/System/Router/PageLoader.tsx, src/v2/System/Router/RenderStatus.tsx, src/v2/System/Router/Utils/findCurrentRoute.tsx, src/v2/System/Router/Utils/matchingMediaQueriesForUserAgent.ts, src/v2/System/Router/Utils/useMaybeReloadAfterInquirySignIn.tsx, src/v2/System/Router/__tests__/RouterLink.jest.tsx, src/v2/System/Router/__tests__/buildAppRoutes.jest.tsx, src/v2/System/Router/__tests__/buildServerApp.jest.tsx, src/v2/System/Router/buildAppRoutes.tsx, src/v2/System/Router/buildClientApp.tsx, src/v2/System/Router/buildServerApp.tsx
Noticed that after our React 17 upgrade we started getting "cannot set state after unmount" errors when transitioning between routes. Wrapping our state calls with `setImmediate` fixes it. 
Also cleans up all of the `// @ts-expect-error` flags in `v2/System/Router`.
=> fix: [Router] Fix cannot update state after unmount error + cleanup

.eslintrc.js, src/desktop/apps/article/__tests__/helpers.jest.tsx, src/desktop/apps/article/components/__tests__/EditButton.jest.tsx, src/desktop/apps/article/components/__tests__/InfiniteScrollArticle.jest.tsx, src/desktop/apps/article/components/__tests__/InfiniteScrollNewsArticle.jest.tsx, src/desktop/apps/article/components/__tests__/NewsArticle.jest.tsx, src/desktop/apps/article/components/layouts/__tests__/Article.jest.tsx, src/desktop/apps/articles/components/__tests__/AuthWrapper.jest.tsx, src/desktop/apps/consign/client/analytics_middleware.ts, src/desktop/components/marketing_signup_modal/__test__/triggerMarketingModal.jest.ts, src/desktop/lib/buildClientAppContext.ts, src/desktop/lib/deprecated_global_client_setup.tsx, src/typings/gravity.d.ts, src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx, src/v2/Apps/Components/AppShell.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx, src/v2/Components/FlashBanner/__tests__/FlashBanner.jest.tsx, src/v2/Components/NavBar/__tests__/NavBar.jest.tsx, src/v2/System/Analytics/__tests__/trackingMiddleware.jest.ts, src/v2/System/Relay/__tests__/createRelaySSREnvironment.jest.ts, src/v2/System/Relay/createRelaySSREnvironment.ts, src/v2/System/Relay/middleware/cache/cacheMiddleware.ts, src/v2/System/Relay/middleware/metaphysicsErrorHandlerMiddleware.ts, src/v2/System/SystemContext.tsx, src/v2/System/__tests__/SystemContext.jest.tsx, src/v2/Utils/__tests__/user.jest.ts, src/v2/Utils/user.ts
Following up on work in https://github.com/artsy/force/pull/8471, this cleans up more `// @ts-expect-error` strict null-check migration flags (this time from the entire `System` folder) and cleans up some long-standing type issues around our `User` type.
=> chore: More // @ts-expect-error cleanup

src/v2/Apps/Categories/Components/GeneFamily.tsx, src/v2/Apps/Categories/__tests__/CategoriesApp.jest.tsx
Lil Friday exercise to work those React Testing Library muscles, now that it's been [added to Force](https://artsy.slack.com/archives/C2TQ4PT8R/p1632434644096600).
- converts the basic rendering spec for the `CategoriesApp` to use RTL instead of Enzyme:
- demonstrates the basic boilerplate required by our current pattern
- demonstrates how following the grain of RTL leads to more a11y-friendly markup
=> test(categories): convert spec to RTL

src/v2/Components/Toast/ToastComponent.tsx
[PURCHASE-2923]
Added zIndex to prevent other elements from overlapping the toast component. If overlapping happens in the future, should be enough to increase the zIndex number.
Before:
After:
[PURCHASE-2923]: https://artsyproduct.atlassian.net/browse/PURCHASE-2923
=> fix(PURCHASE-2923): add zIndex to toast component

src/v2/Apps/Fair/Components/ExhibitorsLetterNav.tsx, src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx, src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorsGroup.tsx, src/v2/Apps/Fair/Components/__tests__/FairExhibitorsGroup.jest.tsx, src/v2/Apps/Fair/Routes/FairExhibitors.tsx, src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx, src/v2/Apps/Fair/Utils/useExhibitorsTabOffset.ts, src/v2/Apps/Show/Components/ShowNavigationBanner.tsx, src/v2/Apps/Show/ShowApp.tsx, src/v2/Apps/Show/__tests__/ShowApp.jest.tsx, src/v2/__generated__/ShowApp_Test_Query.graphql.ts, src/v2/__generated__/ShowApp_show.graphql.ts, src/v2/__generated__/ShowNavigationBanner_show.graphql.ts, src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
Jira: [FX-3280](https://artsyproduct.atlassian.net/browse/FX-3280)
As a collector, I should be able to go back to the Fairs 'Exhibitors A-Z' tab after clicking through to view a Fairs 'Show'. Currently, there is no navigational banner making it explicit and easy for the collector to go back to the Fair page to continue browsing exhibitors within a Fair.
[Figma](https://www.figma.com/file/aM3b5sodn04vMTigbQXACi/Fairs-2021?node-id=3474%3A17827)
- Added navigation banner
- Small refactor of fair components
https://user-images.githubusercontent.com/56556580/134356999-ce1b8cd1-9361-4b25-94d1-428fba855752.mov
https://user-images.githubusercontent.com/56556580/134358180-52d99e9a-77dd-4da2-888e-221a7d3611f1.mov
=> feat(FX-3280): navigation banner at fair show page

src/v2/Apps/Search/SearchApp.tsx
Jira: [FX-3328](https://artsyproduct.atlassian.net/browse/FX-3328)
On search results page when user click on searched item `undefined` term is displayed
- Save search term with `useMemo`
https://user-images.githubusercontent.com/56556580/134915366-358a1b3e-4c31-4ded-a5ee-48fd323854b9.mov
https://user-images.githubusercontent.com/56556580/134917282-b4f2d057-d504-4041-a6a8-a0fc10e58386.mov
=> fix(FX-3328): search term is undefined when redirect to other page

src/v2/Apps/Home/Components/HomeTrendingArtistsRail.tsx
Over on Slack our pal @admbtlr bumped into this bug and noted it here:
https://artsy.slack.com/archives/C02BC3HEJ/p1632922829278000
So then all I did here was boot force, reproduce and then remove the `partner` bit out of the link. I don't have much more context here so I'm assuming this is the fix but lmk if I'm missing something!
=> fix: Route to artist page without partner prefix

src/v2/Apps/Home/Components/HomeCurrentFairsRail.tsx, src/v2/Apps/Home/__tests__/HomeCurrentFairsRail.jest.tsx
Jira: [FX-3387](https://artsyproduct.atlassian.net/browse/FX-3387)
https://user-images.githubusercontent.com/56556580/135301257-07e50e1b-0715-4d96-be4f-a30c01551afd.mov
https://user-images.githubusercontent.com/56556580/135301339-2a927886-735f-48c7-aa9d-a6d1d2634591.mov
=> fix(FX-3387): broken links in "current fairs" section

src/v2/Components/NavBar/menuData.ts
Jira ticket: [FX-3391]
The header for the Artist Nationality and Ethnicity section has a misspelling. It should read "Artist Nationality or Ethnicity" 
[FX-3391]: https://artsyproduct.atlassian.net/browse/FX-3391
=> fix(FX-3391): Fix copy in web hover menu for Artists

docs/a-b_testing.md
Moved the A/B test docs up to the docs folder so that things are more discoverable. These docs are old, but something is better than nothing. Also removed outdated code examples as everything was simplified once we merged reaction in to force.
=> docs: Add A/B testing docs to /docs

src/v2/Apps/Order/Routes/Review/index.tsx
Partially addresses [PX-4617]
Collaboration with @annacarey, @ansor4, and @jpotts244 
@brendamanganelli the only event **from the order review page events** not included in this PR is `clickedOnSubmitOrder` -- we skipped this one because [we're already tracking something for that event](https://github.com/artsy/force/blob/5afd5f6f6e3de5d87dfa70d34058e23f3a41dd14/src/v2/Apps/Order/Routes/Review/index.tsx#L54-L66). Let us know if we need to make changes to the existing tracked event, or if it's something you can use on your end without changes.
- There is a TODO to move an OwnerType constant to cohesion, but we're hoping to launch shipping tomorrow and we plan to do that after launch.
- Tests!
[PX-4617]: https://artsyproduct.atlassian.net/browse/PX-4617
=> feat: Track user interactions in new checkout flow - order review page [PX-4617]

src/v2/Apps/Debug/DebugInquiryApp.tsx, src/v2/Components/Inquiry/Components/InquiryBackdrop.tsx, src/v2/Components/Inquiry/Hooks/useInquiryContext.tsx, src/v2/Components/Inquiry/Inquiry.tsx, src/v2/Components/Inquiry/Views/InquiryBasicInfo.tsx, src/v2/Components/Inquiry/Views/InquiryLogin.tsx, src/v2/Components/Inquiry/Views/InquirySignUp.tsx, src/v2/Components/Inquiry/__tests__/Views/InquiryLogin.jest.tsx, src/v2/Components/Inquiry/__tests__/Views/InquirySignUp.jest.tsx, src/v2/Components/Inquiry/config.ts
Re: https://github.com/artsy/integrity/pull/251
@anipetrov noticed while Q/A-ing the inquiry analytics that if she drops off the flow before reaching the end then we don't actually trigger the reload; which has caused some problems in the past.
This was a little tricky to do because the initial user fetch has to happen _inside_ of the modal; but the modal also needs to be inside of the context provider. Previously the modal was on the outside. Relay hooks would have made this _much_ easier but here we go. I had to separate out the initial context fetch into its own component where all it does is fetch, then set the context in the hook. This lets us pull it out so the provider can be moved up, and as a result so can the `onClose` function.
I _also_ happened to notice a small bug where we …
=> fix(inquiry): reload on close after authentication

src/v2/Apps/Home/Components/HomeCurrentFairsRail.tsx, src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx, src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitsLarge.tsx, src/v2/Apps/Home/HomeApp.tsx, src/v2/Components/Masonry.tsx
Fixes an issue where the columns weren't flowing correctly in Home -> CurrentFairs. 
Also adjusts some spacing per pairing Jonathan.
=> fix: [Home] Fix columns on CurrentFairs

src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx
Fixes a grid layout issue from within Masonry, where it didn't like `display: block` on a routerlink.
=> fix(home): Fix Marketing News column layout

src/v2/Components/NavBar/NavBar.tsx, src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx, src/v2/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx, src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
[GRO-552]
New Behavior:
[GRO-552]: https://artsyproduct.atlassian.net/browse/GRO-552
=> GRO-552: Updated Nav Bar for text case

src/v2/Components/Inquiry/Views/InquiryLogin.tsx, src/v2/Components/Inquiry/__tests__/Views/InquiryLogin.jest.tsx
Updates the user prompt in #8498 to match the updated copy from the design team (see: [slack thread](https://artsy.slack.com/archives/C02BGC5PW/p1630601789004800) and implementation #8430).
=> fix: update inquiry on-demand otp user prompt

src/v2/Apps/Fairs/Components/FairsFairBanner.tsx, src/v2/Apps/Fairs/Components/FairsFairRow.tsx, src/v2/Apps/Fairs/Routes/FairsIndex.tsx, src/v2/Apps/Home/Components/HomeCurrentFairs.tsx, src/v2/__generated__/FairsFairBanner_fair.graphql.ts, src/v2/__generated__/FairsFairRow_Test_Query.graphql.ts, src/v2/__generated__/FairsFairRow_fair.graphql.ts, src/v2/__generated__/FairsIndex_Test_Query.graphql.ts, src/v2/__generated__/FairsIndex_viewer.graphql.ts, src/v2/__generated__/FairsPastFairsQuery.graphql.ts, src/v2/__generated__/HomeCurrentFairsQuery.graphql.ts, src/v2/__generated__/HomeCurrentFairs_Test_Query.graphql.ts, src/v2/__generated__/HomeCurrentFairs_viewer.graphql.ts, src/v2/__generated__/RegisterButton_Test_Query.graphql.ts, src/v2/__generated__/RegisterButton_sale.graphql.ts, src/v2/__generated__/auction2Routes_TopLevelQuery.graphql.ts, src/v2/__generated__/fairsRoutes_FairsQuery.graphql.ts
Jira: [FX-3506](https://artsyproduct.atlassian.net/browse/FX-3506)
Exhibition period of fair differs at fairs list (any page with fairs) and fair page
**Example**
_Home page_
_Fair page_
Slack [discussion](https://artsy.slack.com/archives/C9SATFLUU/p1634911010101100) 
The solution: use `exhibitionPeriod` to display right date in "full months" format like `October 22 – November 5, 2021`
- use `exhibitionPeriod` to display fair period instead of `{startAt} - {endAt}`
https://user-images.githubusercontent.com/56556580/139660327-1dfba25d-38c8-48c7-bfc1-d0940c85b5b7.mov
=> fix(FX-3506): update fairs exhibition period displaying

src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
This PR resolves [CX-2114]
Change the copy in the landing page to “over 900 auction houses” replacing “from 2,400 top auction houses” as shown below
[CX-2114]: https://artsyproduct.atlassian.net/browse/CX-2114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(CX-2114): update copy on price-database

package.json, src/middleware.ts, yarn.lock
Github is removing unrestricted package authentication and this is a
great time to cleanup the last unpublished package that exists in force.
https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> chore: Github Package Authentication

src/v2/Apps/Partners/Components/PartnersFilteredCells.tsx, src/v2/Apps/Partners/Components/PartnersRail.tsx, src/v2/Apps/Partners/Components/PartnersRails.tsx, src/v2/Apps/Partners/Routes/GalleriesRoute.tsx, src/v2/Apps/Partners/Routes/InstitutionsRoute.tsx, src/v2/Apps/Partners/Routes/__tests__/GalleriesRoute.jest.tsx, src/v2/Apps/Partners/Routes/__tests__/InstitutionsRoute.jest.tsx, src/v2/Components/Cells/PartnerCell.tsx, src/v2/__generated__/GalleriesRouteFragmentContainer_Test_Query.graphql.ts, src/v2/__generated__/GalleriesRoute_viewer.graphql.ts, src/v2/__generated__/InstitutionsRouteFragmentContainer_Test_Query.graphql.ts, src/v2/__generated__/InstitutionsRoute_viewer.graphql.ts, src/v2/__generated__/PartnerCellFragmentContainer_Test_Query.graphql.ts, src/v2/__generated__/PartnerCell_partner.graphql.ts, src/v2/__generated__/PartnersFilteredCellsQuery.graphql.ts, src/v2/__generated__/PartnersFilteredCells_viewer.graphql.ts, src/v2/__generated__/PartnersRail_partnerCategory.graphql.ts, src/v2/__generated__/PartnersRailsQuery.graphql.ts, src/v2/__generated__/PartnersRails_viewer.graphql.ts, src/v2/__generated__/partnersRoutes_GalleriesRouteQuery.graphql.ts, src/v2/__generated__/partnersRoutes_InstitutionsRouteQuery.graphql.ts
Closes: [GRO-593](https://artsyproduct.atlassian.net/browse/GRO-593)
I'll need to open up a new ticket however for pagination as the `filteredPartners` field is implemented in a very unconventional manner. I'll have to re-implement it as a new field as a proper connection and restructure the schema for it.
This also winds up closing
* [GRO-603](https://artsyproduct.atlassian.net/browse/GRO-603) — Moved the set of rails to the client-side now that there's a banner up top which renders server-side.
* [GRO-590](https://artsyproduct.atlassian.net/browse/GRO-590) — Since this renders client-side now we can just use a traditional shuffle.
https://user-images.githubusercontent.com/112297/139942032-c601a6c9-7579-4f2b-b807-2a04184639d0.mov
=> feat(partners): implements filtered partners

src/v2/Apps/Home/Components/HomeFeaturedGalleriesRail.tsx, src/v2/Apps/Home/__tests__/HomeFeaturedGalleriesRail.jest.tsx, src/v2/__generated__/HomeFeaturedGalleriesRailQuery.graphql.ts, src/v2/__generated__/HomeFeaturedGalleriesRail_Test_Query.graphql.ts, src/v2/__generated__/HomeFeaturedGalleriesRail_orderedSet.graphql.ts
Closes: [GRO-637](https://artsyproduct.atlassian.net/browse/GRO-637)
Not much too this — we now expose the `Profile#owner` in Metaphysics so we can use the `PartnerCell` component. This fixes the issue with mismatched slugs. As well as adding in locations and using higher quality images.
=> fix(home): utilize partner cell on featured rail

.circleci/config.yml
[This ticket](https://artsyproduct.atlassian.net/browse/PLATFORM-3684) asks for integration tests to be incorporated into Force's release pipeline. The hope is that a _few_, _reliable_ tests can be trustworthy and informative day-to-day, despite the fact that the full Integrity suite _has not_ been.
We hoped to use regular Github "checks" for this, on the `staging` branch. That way, an engineer (or bot) considering a release would see the ❌ from an integration test failure right on the PR and be warned about (or in the case of a bot, prevented from) merging. In a pinch, a human with the necessary permission could still bypass the check and merge the PR.
This PR adds a single CI step for the `staging` branch, just to confirm how it affects release PRs. I'll probably undo it afterwards …
=> Add small check to staging branch, to confirm that status is reflected on release PRs (PLATFORM-3684)

src/desktop/apps/user/components/categories/view.coffee
An error occurred on the user page where the default export was changed
to a named export during decaffeination and the name as imported was
different.
=> fix: User Page Import

src/v2/Apps/Artwork/Server/__tests__/handleArtworkImageDownload.jest.ts, src/v2/Apps/Artwork/Server/handleArtworkImageDownload.ts, src/v2/Apps/Artwork/artworkRoutes.tsx, src/v2/System/Router/buildServerApp.tsx
Addresses https://artsyproduct.atlassian.net/browse/GRO-650 
We noticed that for logged in artsymail users sometimes the image would appear, rather than the page. This is due to the route being improperly mounted. 
Looking deeper, noticed that we weren't properly `await`ing our `onServerSideRender` calls, so this updates that.
=> fix(router): Make onServerSideRender calls async

src/v2/Apps/Unsubscribe/Components/UnsubscribeLoggedIn.tsx, src/v2/Components/UserSettings/UserEmailPreferences/index.tsx
[FX-3513]
This adds _Alert Only_ option to email frequency dropdowns on `/unsubscribe` and `/user/edit` pages
[FX-3513]: https://artsyproduct.atlassian.net/browse/FX-3513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-3513): Added alerts_only email frequency option

src/v2/Apps/Order/Routes/Offer/index.tsx, src/v2/Apps/Order/Routes/Respond/index.tsx, src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx, src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx, src/v2/Apps/__tests__/Fixtures/Order.ts, src/v2/DevTools/createTestEnv.tsx, src/v2/__generated__/OfferTestQuery.graphql.ts, src/v2/__generated__/Offer_order.graphql.ts, src/v2/__generated__/RespondCounterOfferMutation.graphql.ts, src/v2/__generated__/RespondTestQuery.graphql.ts, src/v2/__generated__/Respond_order.graphql.ts, src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts, src/v2/__generated__/orderRoutes_RespondQuery.graphql.ts
This fixes an issue where users were warned when their offer exceeded the listed (but hidden) price. Users could keep lowering the offer until the modal no longer appears, effectively guessing the listed price when the gallery intended for it to not be displayed. Now, when a price is unlisted we simply show nothing when users make an offer.
https://artsyproduct.atlassian.net/browse/PURCHASE-2965
=> fix: show no modal message when collector submits offer on unlisted price artworks

src/v2/Apps/Artwork/Components/ArtworkRelatedArtists.tsx, src/v2/Apps/Auctions/Routes/CurrentAuctions.tsx, src/v2/Apps/Auctions/Routes/PastAuctions.tsx, src/v2/Apps/Auctions/Routes/UpcomingAuctions.tsx, src/v2/Apps/Auctions/Routes/__tests__/CurrentAuctions.jest.tsx, src/v2/Apps/Auctions/Routes/__tests__/PastAuctions.jest.tsx, src/v2/Apps/Auctions/Routes/__tests__/UpcomingAuctions.jest.tsx, src/v2/Apps/Fair/Routes/FairArticles.tsx, src/v2/Apps/Fairs/Components/FairsPastFairs.tsx, src/v2/Apps/Shows/Components/ShowsCurrentShows.tsx
No ticket here; just noticed we didn't have a consistent label/variant for these and after consulting with Jonathan we are settling on `"Show More"` with the `primaryBlack` (default) button variant.
=> chore(buttons): use "Show More" / primary variant for pagination buttons

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
Jira Ticket:ticket: : [SWA-102](https://artsyproduct.atlassian.net/browse/SWA-102)
This PR adds the ability to pre-populate `ContactInformationForm` fields from `session storage`. Fields from session storage override values that had been taken from the user profile. It is really helpful for example when the user  lost connection after he clicked `Submit Artwork`
https://user-images.githubusercontent.com/55637696/140531705-4b00799f-c7b8-437e-9e33-afb37f3afec4.mov
=> feat(SWA-102): Prepopulate contact information step with information from the session storage

src/desktop/apps/galleries_institutions/components/primary_carousel/fetch.coffee
This PR resolves [FX-3559]
* As a user
* When I go to the `/galleries` page
* And specify some filter
* I see that nothing is happening
* [Slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1636452319117100)
* PR after which the problem appeared artsy/force#8707
https://user-images.githubusercontent.com/3513494/140926689-1c6efbf9-b02a-412f-a6a6-f0eb2c9547c1.mp4
https://user-images.githubusercontent.com/3513494/140926751-f5ab5e7b-ee92-45f8-974b-24fd133be92f.mp4
[FX-3559]: https://artsyproduct.atlassian.net/browse/FX-3559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FX-3559): Dropdown filters on /galleries page

Dockerfile
Tuns the way that caches are used in the Dockerfile.
The first change separates the dev and prod caches this fixes a rare
issues caused when the cache is empty and both instances of yarn attempt
to write the same files at the same time. This will increase total disk
space in CI by about 2 GB.
The second change limits a single writer to the cypress directory at a
time.
=> feature: Dockerfile Tuning

src/v2/Apps/Partner/Components/Overview/ArticlesRail.tsx, src/v2/Apps/Partner/Components/Overview/ArtistsRail.tsx, src/v2/Apps/Partner/Components/Overview/ArtworksRail.tsx, src/v2/Apps/Partner/Components/Overview/ShowsRail.tsx
This PR resolves [FX-3562]
* As a user
* When I navigate to the partner screen
* And tap on “view all” button (for example, in “all events” section)
* I navigate to “view all” screen
* [Slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1636469153134500)
* [Demo partner link](https://www.artsy.net/partner/galerie-benjamin-eck)
https://user-images.githubusercontent.com/3513494/140970840-4fe9ae6f-68ea-4c29-82be-acc755f28198.mp4
https://user-images.githubusercontent.com/3513494/140971419-409b8b86-d030-4022-b7e4-c117ab66590c.mp4
[FX-3562]: https://artsyproduct.atlassian.net/browse/FX-3562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FX-3562): Unable to click the "view all" buttons on partner page in mobile browser

src/v2/Apps/Fair/Components/FairHeader/FairHeader.tsx, src/v2/Apps/Fair/FairApp.tsx, src/v2/__generated__/FairApp_Test_Query.graphql.ts, src/v2/__generated__/FairApp_fair.graphql.ts, src/v2/__generated__/fairRoutes_FairQuery.graphql.ts
[FX-3517]
This PR adds fair logo to tabs menu on fair page when this menu becomes sticky
We have received feedback that it needs to be clearer that users are still in the Fair area once they have gone past the banner on the Fair page.
**Why this is important**
Fair branding is still of utmost importance to our partners / they want the Artsy fair experience to feel more branded. Currently once users scroll past the main fair banner it's no longer clear that they are still in the fair microsite.
https://user-images.githubusercontent.com/44819355/141301986-63cbde13-4f43-4a29-9252-89298ac669e1.mp4
https://user-images.githubusercontent.com/44819355/141301739-48ee07d9-4cc0-483d-92ec-c28b49c71473.mp4
[FX-3517]: https://artsyproduct.atlassian.net/browse/FX-3517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …
=> feat(FX-3517): Added fair logo to sticky menu

docs/best_practices.md
Still need to update the examples, but this at least sets it in stone.
=> docs(best-practices): Update with guidance to use @testing-library/react

src/v2/Components/ArtworkFilter/index.tsx
This PR resolves [FX-2928]
We should send in `commercial_filter_params_changed` only allowed filter keys
|Before|After|
|-|-|
|<img width="1748" alt="before" src="https://user-images.githubusercontent.com/3513494/141476321-d78c2fd9-fbcb-427c-aa76-72a7d5a901c9.png">|<img width="1748" alt="after" src="https://user-images.githubusercontent.com/3513494/141476371-74855de8-41d9-46e2-a4d5-58eb095b0d84.png">|
[FX-2928]: https://artsyproduct.atlassian.net/browse/FX-2928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FX-2928): Track only allowed filter keys in commercial_filter_params_changed

src/v2/Apps/Consign/Routes/MarketingLanding/Components/SellWithArtsy.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/SellWithArtsy.jest.tsx, src/v2/Components/DownloadAppBadge.tsx, src/v2/Components/__tests__/DownloadAppBadge.jest.tsx
[FX-3343]
Remove deprecated `clickedAppDownload` helper from the two components that were using it (`DownloadAppBadge` and `SellWithArtsy`), replacing it with `ClickedAppDownload` type that is [provided by cohesion](https://github.com/artsy/eigen/pull/5492/files#diff-f9f35322e1193efeb953aaf472a8d911d497795c25d0dd3ceaf6313e4ced9a8eR113).
[FX-3343]: https://artsyproduct.atlassian.net/browse/FX-3343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FX-3343] Remove clickedAppDownload helper

src/v2/Apps/Consign/Routes/MarketingLanding/Components/ReadMore.tsx
[FX-3344]
Replace clickedArticleGroup helper usage on ReadMore component with [ClickedArticleGroup type](https://github.com/artsy/cohesion/blob/01b821a0f3ea5e67eaaca9876533998b86ac8eee/src/Schema/Events/Click.ts#L88) that is provided by cohesion.
[FX-3344]: https://artsyproduct.atlassian.net/browse/FX-3344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FX-3344] Remove clickedArticleGroup helper

package.json, src/v2/Apps/Settings/Routes/EditSettings/SettingsEditSettingsInformation.tsx, src/v2/Apps/Settings/Routes/EditSettings/__tests__/SettingsEditSettingsInformation.jest.tsx, src/v2/Apps/Settings/Routes/EditSettings/useUpdateSettingsInformation.ts, src/v2/Components/Authentication/Validators.tsx, src/v2/__generated__/SettingsEditSettingsInformation_Test_Query.graphql.ts, src/v2/__generated__/SettingsEditSettingsInformation_me.graphql.ts, src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts, yarn.lock
So this PR primarily fixes the issue where we weren't sending the password through with the mutation and corrects the logic surrounding how it's displayed. 
So here you can see: as soon as you change the email the password input displays itself. If you type the correct password, it updates the email. If you type the wrong password, it prevents you from updating the email and errors.
https://user-images.githubusercontent.com/112297/142661528-4007db15-c7b6-4282-bc9f-42ec1e4ae922.mov
I'll leave a few comments below explaining what was going on and why.
=> fix(settings): submits the password with mutation; improves validation and display

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts, src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmission.ts, src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts
Jira Ticket:ticket: : [SWA-105](https://artsyproduct.atlassian.net/browse/SWA-105)
~[WIP] because we should wait until [this ticket](https://github.com/artsy/convection/pull/1163) and [this](https://github.com/artsy/force/pull/8897) been merged.~
This PR adds sessionId usage to `createConsignSubmission`
<details>
<summary>Anonymous submission</summary>
https://user-images.githubusercontent.com/55637696/142842393-c7707dd2-acac-49b8-9f0f-caed23494979.mov
</details>
<details>
<summary>Submission from logged-in user</summary>
https://user-images.githubusercontent.com/55637696/142843001-e09e5d98-f2a2-44ad-a9a5-174038087354.mov
</details>
=> feat(SWA-105): Add logic to determine whether a submission should be created anonymously

src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorCard.tsx, src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorsGroup.tsx, src/v2/Apps/Fair/Routes/FairExhibitors.tsx, src/v2/__generated__/FairExhibitorCard_exhibitor.graphql.ts, src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts, src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
Jira: [FX-3514](https://artsyproduct.atlassian.net/browse/FX-3514)
Remove the logo thumbnails from the AZ tab on the Fairs page.
Examples: https://www.artsy.net/fair/2021-art-taipei/exhibitors
Why? Too many exhibitors do not have a profile logo uploaded. When they do, it is too often getting cropped in a way that makes it illegible.
As a result, this page is looking buggy and unprofessional. We have already received complaints from fair organizers about it. Since many people view this page it also affects our brand.
It seems the easiest way around this would be to remove the thumbnails completely, just leave the gallery name and follow button.
- updated graphql query
- removed logo component
https://user-images.githubusercontent.com/56556580/141275756-94a957ee-2bbb-48f9-af18-8b7c96aec91f.m …
=> feat(FX-3514): remove exhibitors logo from list on Exhibitors A-Z tab

.circleci/config.yml
As part of our effort to make force as automated as possible it's desired that we have automated approval gates which decides if current version is safe or not to step forward in the pipeline.
We are introducing an approval gate after deploy to staging which:
- Run smoke tests using cypress definition on current running staging environment
- In case tests are failing CircleCi will mark this execution as failed
Dependencies:
- CircleCI need an environment called $SMOKE_TEST_TARGET eg: https://staging.artsy.net
=> fea: add smoke test  after deploy to staging

src/desktop/apps/user/components/password/index.jade
Existing passwords may have been created under different validation requirements. There's no need for a validation on your existing password.
=> fix(settings): removes validation for existing password input

src/desktop/apps/partnerships/templates/auction_sections.jade, src/desktop/components/article/templates/gi_signup.jade
Smoke tests (which are just the usual acceptance tests, but against staging) [fail](https://app.circleci.com/pipelines/github/artsy/force/21926/workflows/eb3679b8-cfbf-4d59-a2c7-869501cdc183/jobs/166537) surprisingly often on the `/auction-partnerships` page with `MktoForms2 is not defined`. I haven't been able to reproduce the issue myself, so I'm hoping it's limited to cypress tests. 🤞 
This PR adds a guard that prevents the Marketo reference from raising a client-side error. If there's a straightforward way to defer this call (possibly increasing its likelihood of succeeding) instead of skipping it, I'd be open to that.
=> Avoid erroring when Marketo js fails to load

src/v2/Apps/Conversation/Components/Details.tsx
[NX-3027]
Fixed an issue causing the length of the attachments to display on the conversation sidebar if there was none, and no attachments if any were present.
Also included is an ellipsis for long file names while at it, but this area's design is set to be revisited soon.
Before (displaying the actual `attachments.length`):
After (with and without attachments):
cc: @artsy/negotiate-devs 
[NX-3027]: https://artsyproduct.atlassian.net/browse/NX-3027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Attachment display on conversation sidebar

src/v2/Apps/Partners/Components/PartnersFeaturedCarousel.tsx, src/v2/__generated__/GalleriesRouteFragmentContainer_Test_Query.graphql.ts, src/v2/__generated__/InstitutionsRouteFragmentContainer_Test_Query.graphql.ts, src/v2/__generated__/PartnersFeaturedCarousel_Test_Query.graphql.ts, src/v2/__generated__/PartnersFeaturedCarousel_viewer.graphql.ts, src/v2/__generated__/partnersRoutes_GalleriesRouteQuery.graphql.ts, src/v2/__generated__/partnersRoutes_InstitutionsRouteQuery.graphql.ts
There's an `items` field — that should be deprecated — that returns a fixed amount of items with no pagination options. Updates to use the connection and fetch a max of 50 items.
=> fix(partners): updates carousel to use connection

src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx, src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx, src/v2/Components/ArtworkFilter/SavedSearch/types.ts, src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertForm.jest.tsx
Jira: [FX-3581](https://artsyproduct.atlassian.net/browse/FX-3581)
Track `ClickedCreateAlert` event when user clicks "create alert" button 
More info [here](https://docs.google.com/spreadsheets/d/1_VDAmRJz2K87FXDq7oh_tQSgwBv4syuZjaaR3sfetcI/edit#gid=121201130)
- add analytics tracking
When user click the button this event is fired
=> feat(FX-3581): analytics tracking for create alert button

src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx, src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx, src/v2/Components/ArtworkFilter/SavedSearch/types.ts, src/v2/Components/SavedSearchAlert/CreateSavedSearchAlert.tsx, src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertForm.jest.tsx
Jira: [FX-3582](https://artsyproduct.atlassian.net/browse/FX-3582)
Track analytics event toggled_saved_search when user saves an alert 
More info [here](https://docs.google.com/spreadsheets/d/1_VDAmRJz2K87FXDq7oh_tQSgwBv4syuZjaaR3sfetcI/edit#gid=121201130)
- update saved search model
- add analytics tracking
=> feat(FX-3582): add analytics tracking for alert save

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/SubmissionLayout.tsx, src/v2/Utils/recaptcha.ts
Jira Ticket:ticket: : [SWA-132](https://artsyproduct.atlassian.net/browse/SWA-132)
This PR adds `Recaptcha` usage to the `Contact Information` form submitting.
❓:
- Is it enough? Or we should use backend validation for our flow? @damassi, @mzikherman could you help, please? I noticed that in Force only `SignUpForm` has backend validation.
- Are those Recaptcha call's doing something? 
https://github.com/artsy/force/blob/0d76e5e579925c2027711ff725450001a6fc0882/src/v2/Components/Authentication/Views/ForgotPasswordForm.tsx#L23
https://github.com/artsy/force/blob/0d76e5e579925c2027711ff725450001a6fc0882/src/v2/Components/Authentication/Views/LoginForm.tsx#L46
=> feat(SWA-132): Add recaptcha for the submission creation

.circleci/config.yml
[PLATFORM-3744]
When cypress tests fail on `smoke-test-on-live-env`, we want the screenshots to be stored in the artifacts tab, so we don't need to run it again locally to detect the issue.
To test this setting, I changed it to run on this branch and changed an integration test to force it to fail. The result can be seen in [here](https://app.circleci.com/pipelines/github/artsy/force/22072/workflows/11f486a9-992e-4faf-aa8c-d36715f5a38c/jobs/167809/artifacts)
[PLATFORM-3744]: https://artsyproduct.atlassian.net/browse/PLATFORM-3744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PLATFORM-3744] Set artifacts for smoke-test-on-live-env in case of failure

package.json, src/v2/Apps/Order/Utils/__tests__/currencyUtils.jest.ts, src/v2/Apps/Order/Utils/currencyUtils.ts, src/v2/jest.envSetup.ts, yarn.lock
Currently, `price` can be any of the following formats:
`Under $1000`
`1000`
`$1000`
`"1000`
`$1000 - 2000`
`0`
`"0"`
`£150`
`€150`
`""`
`"-"`
This PR fixes a bug caused by not properly handling all the various formats that `price` is in when we pass that value to components that render an artwork's price in the BNMO flow. 
https://artsyproduct.atlassian.net/browse/NX-3029
This is a follow-up to #8884 
**The Bug:**
**The Fix:**
=> bugfix: cleans price currency before rendering

src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/Utils/isCustomValue.ts, src/v2/Components/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx, src/v2/Components/ArtworkFilter/SavedSearch/Components/FiltersPills.tsx, src/v2/Components/ArtworkFilter/Utils/allowedFilters.ts, src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx, src/v2/Components/ArtworkFilter/__tests__/FiltersPills.jest.tsx, src/v2/Components/ArtworkFilter/index.tsx, src/v2/Components/SavedSearchAlert/SavedSearchAlertForm.tsx, src/v2/Components/SavedSearchAlert/Utils/extractPills.ts, src/v2/Components/SavedSearchAlert/Utils/getNamePlaceholder.tsx
[FX-3595]
Acceptance Criteria:
-When selecting a filter, user sees pill with selected option name on top of the artworks grid
-When tapping on the 'X' of a pill it disappears and the filter related to this pill gets unselected
Changes are available with `ENABLE_SAVED_SEARCH` feature flag enabled
https://user-images.githubusercontent.com/44819355/144020160-671ea960-7770-4e67-816b-59a4a8d72b33.mp4
[FX-3595]: https://artsyproduct.atlassian.net/browse/FX-3595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-3595): Filter pills interaction

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/LocationAutocomplete.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/LocationAutocomplete.jest.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts, src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/useSubmission.jest.ts, src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts, src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
Jira Ticket:ticket: : [SWA-129](https://artsyproduct.atlassian.net/browse/SWA-129)
This PR adds the `Location` autocomplete field to the `ArtworkDetailsForm` in the `Submission flow`.
https://user-images.githubusercontent.com/55637696/144232988-f7452fa5-f544-43b1-b362-e2a9ef040b81.mov
https://user-images.githubusercontent.com/55637696/144233380-c5cb199a-e66b-45ff-b046-d9978db4b8a1.mov
https://user-images.githubusercontent.com/55637696/144233808-95f70726-de4b-4b34-baf1-9f0a821a8b53.mov
=> feat(SWA-129): As a collector, I am required to enter artwork location

src/v2/Apps/Order/Components/ShippingQuotes.tsx, src/v2/Apps/Order/Routes/Shipping/index.tsx
Ended up not adding space between the title and the description as this spacing seems fine now when things are in a table format.
Looks like:
=> refactor(PX-4712): shuffle around the shipping options display to match the design

src/desktop/apps/rss/templates/news.jade, src/desktop/apps/rss/test/news.test.js
While working on the editorial version of the widget I realized that the enclosure URL for articles in our RSS feed was not having any resizing applied to it. I only noticed this when we happened to have a massive image in the first four items and Xcode was crashing like crazy.
Anyway, with @dzucconi's help I was able to apply the `resize` mixin to the jade template that draws the RSS feed. This results in MUCH smaller image sizes:
```
jon@juggernaut:~/code/lab_notebook(main+*)% lh omg-images
total 19352
drwxr-xr-x   7 jon  staff   224B Dec  3 16:43 ./
drwxr-xr-x  28 jon  staff   896B Dec  3 15:57 ../
-rw-r--r--   1 jon  staff   211K Dec  3 15:35 first.jpg
-rw-r--r--   1 jon  staff    88K Dec  3 16:43 fourth-resized.jpg <--- nice 😎 
-rw-r--r--   1 jon  staff   8.1M Dec  3 15:37 fourth.jpg …
```
=> feat: Apply resizing logic to RSS feed items GROW-692

src/lib/middleware/redisPageCache.ts, src/v2/server.ts
Due to some limitations in how Datadog determines what route to use for a trace, the cached page data needs to be returned in the final route. This allows the trace to select the correct URL.
=> feature: Track Page Cache Metrics

src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/FAQ.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/HowToSell.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
Ticket: [SWA-80 ](https://artsyproduct.atlassian.net/browse/SWA-80)
As per legal requirements, we are not allowed to use the words 'consign' or 'consignment' in places where users have access. This PR replaces or removes some of such references to the words. The exact places where the words should be replaced/removed are discussed and determined in [this google doc](https://docs.google.com/document/d/1CyIph7Iqts-6nV9YNhV98ejQniLTQ45x9SQokFeMP3g/edit) by our product and legal teams.
=> [feat]: Replace or remove some references to the word consign

src/v2/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx, src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx, src/v2/Utils/Hooks/useScrollTo.ts
Jira ticket: [FX-3607]
* Clicking the CTA in the email alert should lead the user directly to the artworks they want to see on the Artist’s Works for Sale tab
* The effect should be that the screen “jumps” right to the artwork grid on the artist artwork tab, rather than land at the top of the mWeb page
[Demo link](https://artist-artworks-scroll.artsy.net/artist/kaws/works-for-sale?attribution_class%5B0%5D=unique&additional_gene_ids%5B0%5D=sculpture&search_criteria_id=f5c5e83b-a53c-4461-a496-bba7ddc109ca)
https://user-images.githubusercontent.com/3513494/143268199-14950fca-c7da-48b3-af4c-c797f658f7e4.mp4
https://user-images.githubusercontent.com/3513494/143268226-118f2caf-e340-46c6-aa16-e42dce1c434e.mp4
[FX-3607]: …
=> feat(FX-3607): Upon email alert click scroll down to artwork grid immediately

src/v2/Components/ArtworkFilter/SavedSearch/Utils/constants.ts
[FX-3642]
When creating saved search alert on web with one or more size checkboxes selected (Small, Medium, Large), the alert is created without sizes criteria
https://user-images.githubusercontent.com/44819355/145367146-8274e873-8068-4a6a-950d-d754f965112c.mp4
https://user-images.githubusercontent.com/44819355/145366638-e07ce5ed-c5c6-48fe-9107-128d637bc998.mp4
[FX-3642]: https://artsyproduct.atlassian.net/browse/FX-3642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FX-3642): Add sizes to the allowed filters list

src/v2/Components/ArtworkFilter/index.tsx
Add an offset to the right for the "Filter" pill (in this way, we will be safe so that the elements don’t overlap)
https://user-images.githubusercontent.com/3513494/145595850-63a8b9ba-d441-44ff-bc17-c70a76c1f473.mp4
=> chore: add offset for filter pill

src/v2/Apps/Home/Components/HomeCurrentFairs.tsx, src/v2/Apps/Home/__tests__/HomeCurrentFairs.jest.tsx
When we get null for fairs, the check for the length of fairs in HomeCurrentFairs component doesn’t work and we get an err that clashes the app. For details see the video in [GRO-618](https://artsyproduct.atlassian.net/browse/GRO-618).
=> [Fix]: GRO-618 - Check against null in addition to empty arr in HomeCurrentFairs

src/v2/Apps/Conversation/Components/Message.tsx
[NX-3028]
This PR fixes the missing border from the attachments in conversations from the collector. Also, there was a misalignment from PDF attachments that was fixed too
https://user-images.githubusercontent.com/15792853/145551887-6448820b-b695-4d86-b78e-8b39f0792608.mov
[NX-3028]: https://artsyproduct.atlassian.net/browse/NX-3028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(NX-3028): fix missing border in collector attachments

src/v2/Components/ArtworkFilter/SavedSearch/Utils/__tests__/savedSearchCriteria.jest.ts, src/v2/Components/ArtworkFilter/SavedSearch/Utils/savedSearchCriteria.tsx
[FX-3636]
We should not send default filter values in attributes for create alert mutation
See sent criteria for given alert
[FX-3636]: https://artsyproduct.atlassian.net/browse/FX-3636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FX-3636): Do not send initial values as saved search criteria

src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx, src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
Jira: [FX-3645](https://artsyproduct.atlassian.net/browse/FX-3645)
- Disable “Save Alert” button in the “Create an Alert” modal if no notification options have been selected
- Enable “Save Alert” button if selected at least one of the notification toggle options
- Added conditional disabling for button
- Added tests for it
https://user-images.githubusercontent.com/56556580/145979535-1b8bb70d-fbed-4c82-bdf4-20d7e1254e23.mov
=> feat(FX-3645): add conditional disabling for create alert button

src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/PhotoDropzone.tsx
Jira Ticket:ticket: : [SWA-152](https://artsyproduct.atlassian.net/browse/SWA-152)
This PR `adds blur call` for the "Add Photo" button after the user uploads a valid file, pushes cancel in the file dialog, or uploads an invalid file.
https://user-images.githubusercontent.com/55637696/145185117-4f09a61c-353a-4724-bc87-0eb5ba5e2d97.mov
=> fix(SWA-152): The add photo button should return to white after adding a photo

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
Jira Ticket:ticket: : [SWA-161](https://artsyproduct.atlassian.net/browse/SWA-161)
This PR adds length limits for the inputs on the Contact information step. Also, I noticed that there were a couple of inputs in ArtworkDetails step without that limit. I added it too
=> fix(SWA-161): The contact information step fields should be limited to 256 characters

src/v2/Apps/_About2/AboutApp.tsx, src/v2/Apps/_About2/aboutRoutes.tsx, src/v2/Apps/_ArtsyEducation2/ArtsyEducationApp.tsx, src/v2/Apps/_ArtsyEducation2/artsyEducationRoutes.tsx, src/v2/Apps/_AuctionPartnerships2/AuctionPartnershipsApp.tsx, src/v2/Apps/_AuctionPartnerships2/auctionPartnershipsRoutes.tsx, src/v2/Apps/_Contact2/ContactApp.tsx, src/v2/Apps/_Contact2/contactRoutes.tsx, src/v2/Apps/_HowAuctionsWork2/HowAuctionsWorkApp.tsx, src/v2/Apps/_HowAuctionsWork2/howAuctionsWorkRoutes.tsx, src/v2/Apps/_Security/SecurityApp.tsx, src/v2/Apps/_Security/securityRoutes.tsx, src/v2/Apps/_Terms2/TermsApp.tsx, src/v2/Apps/_Terms2/termsRoutes.tsx, src/v2/Apps/_WorksForYou2/WorksForYou2App.tsx, src/v2/Apps/_WorksForYou2/worksForYouRoutes.tsx, src/v2/routes.tsx
This stubs out some hackathon page-migration routes: 
- contact2
- about2
- artsy-education2
- terms-and-conditions2
- how-auctions-work2
- security2
- auction-partnerships2
- works-for-you2
Ignore the `_` in the folder name for the time being; that's for us to quickly see what's WIP. 
cc/ @artsy/grow-devs
=> feat(new-routes): Add app hackathon routes

src/v2/Apps/Artwork/Server/handleArtworkImageDownload.ts
Closes https://github.com/artsy/force/pull/9065 
Moves imports so that they're only requested server-side.
=> chore: Move server-side artwork imports

src/v2/Apps/Artwork/Server/__tests__/handleArtworkImageDownload.jest.ts, src/v2/Apps/Artwork/Server/handleArtworkImageDownload.ts
Follow-up to https://github.com/artsy/force/pull/9066 
Replaces use of superagent with fetch-api which we use all over.
=> chore: replace superagent with fetch

src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
When user unselects price filter option the `null` value is passed to filter state and it causes error in `extractFiltersPills` helper
Before
https://user-images.githubusercontent.com/56556580/146011862-6b5888b9-0ad5-4b96-a46c-5e0788d4f6a6.mov
After
https://user-images.githubusercontent.com/56556580/146012269-891afa6e-8d84-4cd4-8ef6-e0219861a69a.mov
=> fix: unselecting price filter option

src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactorBackupCodesActions.tsx, src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactorBackupCodesDialog.tsx, src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/BackupSecondFactorReminder.tsx, src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/__tests__/SettingsEditSettingsTwoFactorBackupCodesActions.jest.tsx
This PR adds functionality allowing users to download and copy their 2FA recovery codes during the 2FA setup flow, or when they are requested via the settings page. This implementation is from @lidimayra's #8930 PR, now that the component have been moved to palette v3 with #9048 .
As more partners are enrolled into 2FA, we are seeing an increase in account lockouts as users lose access to their 2FA authentication method(s). Unlocking an account requires the Trust and Safety and Platform teams to validate the ID of the requester and manually lookup and provide a code.  This functionality specifically aims to increase backup code utilization through improved UX. 
[PLATFORM-3280]
[PLATFORM-3280]: https://artsyproduct.atlassian.net/browse/PLATFORM-3280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
=> feat: add copy and download buttons to 2fa recovery modal

src/v2/Apps/Auction/Components/LotInfo.tsx, src/v2/__generated__/ConfirmBidValidTestQuery.graphql.ts, src/v2/__generated__/LotInfo_artwork.graphql.ts, src/v2/__generated__/auctionRoutes_ConfirmBidQuery.graphql.ts
Collab with @nspinazz89 on [BID-121](https://artsyproduct.atlassian.net/browse/BID-121)
Wraps the lot image and lot #/title/date/artists in a link that redirects to the artwork page.
I wanted to link the Artsy logo back to the artwork page too, but it seemed to be used in Jade templates (!?!?!?!) so I think it's OK to leave as is?
=> chore: Wrap lot image and title in a link back to the artwork page

src/v2/Components/Search/Suggestions/SuggestionItem.tsx
This PR disables the underlying `RouterLink` click behavior in favor of letting the `SearchBar` navigate:
https://github.com/artsy/force/blob/6baaeb7283df84d1fd04c852d978acf83cb1343e/src/v2/Components/Search/SearchBar.tsx#L268-L296
Steps to reproduce this bug are in the Jira ticket!
https://artsyproduct.atlassian.net/browse/GRO-653
=> fix: Prevent duplicate pageview event in search GRO-653

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
Jira Ticket:ticket: : [SWA-147](https://artsyproduct.atlassian.net/browse/SWA-147)
This PR fixes the clickable area for the Back button in the Submission flow. Also, [noticed that there are new rules for the use `sharify`](https://github.com/artsy/force/blob/e5c72b0bfb6dfca04f8273e89dbe52c8e958c6bb/.eslintrc.js#L114), so i fixed it too
https://user-images.githubusercontent.com/55637696/146342597-aa238744-01ba-48e2-93d9-e42d9c0f830d.mov
=> fix(SWA-147): Clickable area for Back button is too large

src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx, src/v2/Apps/FairOrginizer/Components/FairOrganizerFollowButton.tsx, src/v2/Apps/FairOrginizer/Components/__tests__/FairOrganizerFollowButton.jest.tsx, src/v2/Components/Artwork/SaveButton/useSaveArtwork.ts, src/v2/Components/ArtworkFilter/SavedSearch/Components/ArtworkGridFilterPills.tsx, src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx, src/v2/Components/ArtworkFilter/__tests__/CreateAlertButton.jest.tsx, src/v2/Components/ArtworkFilter/index.tsx, src/v2/Components/Authentication/Types.ts, src/v2/Components/FollowButton/FollowArtistButton.tsx, src/v2/Components/FollowButton/FollowGeneButton.tsx, src/v2/Components/FollowButton/FollowProfileButton.tsx, src/v2/Components/FollowButton/__tests__/FollowArtistButton.jest.tsx, src/v2/Components/FollowButton/__tests__/FollowGeneButton.jest.tsx, src/v2/Components/FollowButton/__tests__/FollowProfileButton.jest.tsx, src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx, src/v2/Utils/Hooks/useAuthIntent/__tests__/useAuthIntent.jest.ts, src/v2/Utils/Hooks/useAuthIntent/index.ts, src/v2/Utils/__tests__/openAuthModal.jest.ts, src/v2/Utils/openAuthModal.ts
[FX-3641]
At the moment Create an Alert button is visible on artworks grid page for logged in users and hidden for logged out users. Instead, the button should be visible for both logged in and logged out users.
- Create an Alert button is visible regardless of whether user is logged in or logged out
- If a user that is logged in clicks the button they see the Create an Alert modal
- If a user that is logged out clicks the button they see the standard login screen pop up where they are prompted to login/create account
Also, after successful auth Create Alert modal pops up without additional button click.
https://user-images.githubusercontent.com/44819355/146196258-5e4aef51-c913-4f71-997a-27453c97fdcc.mov
[FX-3641]: https://artsyproduct.atlassian.net/browse/FX-3641?atlOrigin=eyJpIjoiNWRkNTl …
=> feat(FX-3641): Show Create Alert button when user both logged in and out

src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsPassword.tsx, src/v2/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx, src/v2/__generated__/SettingsEditSettingsPassword_me.graphql.ts, src/v2/__generated__/SettingsEditSettingsRoute_me.graphql.ts, src/v2/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
A minor change here: users who sign up through social auth don't have passwords set initially. This adapts the password form to accommodate those users. This code is currently untested because we were unable to get social auth working at all locally. Though I believe this should work correctly, I'm going to just check this in staging and go from there.
=> fix(settings): accommodates users that do not have passwords setup

src/v2/Apps/Authentication/__tests__/authenticationRoutes.jest.tsx, src/v2/Apps/Components/AppShell.tsx, src/v2/System/Router/__tests__/RouterLink.jest.tsx, src/v2/Utils/Hooks/__tests__/useAuthValidation.jest.tsx, src/v2/Utils/Hooks/useAuthValidation.ts, src/v2/__generated__/useAuthValidationQuery.graphql.ts
So this replicates what https://github.com/artsy/force/blob/main/src/lib/syncAuth.ts does but for the new app shell.
I do think we should actually refresh the session without signing out the user, if possible? But I'm not entirely sure what that entails.
=> fix: validates authentication and signs out if invalid

src/desktop/models/mixins/relations/inquiry_outcome.js
Tiny fix for a `500` when trying to access the `/inquiry/:id/user_outcome` route reported by @bhoggard .
The actual error was: `TypeError: Artwork is not a constructor`, which seems to have been caused by decaffeination.
cc: @artsy/negotiate-devs
=> fix: incorrect import causing 500

src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter.jest.tsx
Jira ticket: [FX-3667]
If the user specifies the same custom size values for Force and Eigen, they will be converted to inches differently. In turn, this can add problems when working with saved search alerts (for example, a user can create an alert with the same criteria)
* width: 100 - 199 cm -> 39.37 - 78.35 in
* height: 200 - 299 cm -> 78.74 - 117.72 in
* width: 100 - 199 cm -> 39.37007874015748 - 78.34645669291338 in
* height: 200 - 299 cm -> 78.74015748031496 - 117.71653543307086 in
* Values from cm to in should be converted equally to Force and to Eigen
[FX-3667]: https://artsyproduct.atlassian.net/browse/FX-3667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Skipping rounding for custom size values

src/v2/Apps/Order/Components/OfferInput.tsx
Tiny PR to allow `OfferInput` to take and trigger an `onBlur` callback for upcoming work.
cc @artsy/negotiate-devs
=> chore: expand OfferInput to take an onBlur callback

.gitignore, package.json, webpack/index.js, webpack/plugins/bundleSize.js, webpack/utils/env.js, yarn.lock
Adds the webpack size plugin to assist with tracking large bundle size
differences. The plugin provides the ability to automatically track the
differences between branches and can easily be added to a github action
that reports bundle size differences as a PR comment.
Optionally enable by setting `WEBPACK_SIZE_PLUGIN=true`
=> feature: Webpack Size Plugin

src/v2/Apps/Partners/Components/PartnersFeaturedCarouselCell.tsx, src/v2/Components/Cells/PartnerCell.tsx
We noticed this bug after attempting to update metaphysics' `partner.href` handling to use the new `/partner/:partner_slug` structure.
Given that the current `partner.href` in metaphysics uses the `default_profile_id`, the correct link in these places should be the "naked" URL (`/partner/:default_profile_id` will not be correct in cases where the `default_profile_id` does not match the partner's `slug`). We should just use what metaphysics is giving us. 
Note that force has its own redirects in place to go from `/:default_profile_id` -> `/partner/:partner_slug`, so both styles work.
Once this is merged in, I will merge the change that was [reverted here](https://github.com/artsy/metaphysics/pull/3641), which will update metahpysics' `partner.href` to use the new-style URL.
From searching …
=> Removes /partner from links that refer to partner.href

package.json
We've run into problems with relay's cache being corrupted during a rebase. This adds a command to quickly clear it:
```
yarn clean:relay
```
=> feat(script): Add clean:relay to package.json

cypress/integration/partnerProfile.spec.js, src/desktop/apps/auction/actions/artworkBrowser.js, src/desktop/apps/auction/components/artwork_browser/main/artwork/BidStatus.js, src/desktop/apps/auction/components/artwork_browser/sidebar/ArtistFilter.js, src/desktop/apps/auction/queries/filter.js
Branched off of the [review app PR](https://github.com/artsy/force/pull/9095) though probably should have branched off of @damassi's [actual PR](https://github.com/artsy/force/pull/9087).
I think this branch can be merged into the latter, which is what this PR is doing.
Also I didn't add tests for this but it could be a good idea...
This PR:
=> fix: Finish auction/:id MPV2 support

src/v2/Components/Toast/ToastComponent.tsx
I did this:
```
$ ag -l ToastComponent | xargs sed -i '' "s/Toast/StaleToast/g"
```
And then updated the folder/filename and added that little breadcrumb comment for Future Us in case we stumble upon this again. A better solution would be to migrate that order page that uses it over to the Palette version of Toast but it's Friday I'm doing the best I can people.
=> fix: Mark deprecated component as such

package.json, yarn.lock
The PR addresses a `critical` [dependabot security alert ](https://github.com/artsy/force/security/dependabot/yarn.lock/growl/open)related to a transitive dependency of `mocha`.
=> chore: bump mocha@3.4.1 to mocha@4.1.0

.circleci/config.yml
Closes https://artsyproduct.atlassian.net/jira/software/projects/WP/boards/97?selectedIssue=WP-65 
Following the work done in https://github.com/artsy/volt/pull/4860, this adds Slack notifications to #practice-web around alerting if the MP schema is out of sync, or we get test failures on staging or release. 
=> ci(notifications): Add slack webook notifications

package.json, yarn.lock
See https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/ 
We don't import this lib directly, but it is an ephemeral dep, which still runs the risk of an automatic update.
=> security(colors.js): Lock version to 1.4 due to corruption

src/v2/Components/SavedSearchAlert/DownloadAppBanner.tsx, src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx, src/v2/Components/SavedSearchAlert/__tests__/DownloadAppBanner.jest.tsx
Jira ticket: [FX-3545]
Figma: [Link](https://www.figma.com/file/zbEFZqjKgKquZwtU8U44j9/Alerts?node-id=3565%3A7189)
Review app: [Link](https://download-app-banner.artsy.net/artist/banksy/works-for-sale)
* display the download button depending on the platform
* for iOS platform, only the "Download on the App Store" button is displayed
* for Android platform, only the "Get it on Google Play" button is displayed
* If we could not determine the platform, then we display 2 buttons at once
* when the button is clicked, the `ClickedAppDownload` event should be tracked with the values
* action = ActionType.clickedAppDownload
* `context_page_owner_type` = `artist`
* `context_page_owner_id` = `artist id`
* `context_page_owner_slug` = `artist slug`
* `context_module` = `createAlert` …
=> feat(FX-3545): Add app download buttons to create saved search alert modal

src/desktop/assets/articles.ts, src/v2/Apps/Articles/ArticlesApp.tsx, src/v2/Apps/Articles/Utils/useScrollingAuthModal.tsx
Ports over the code from [AuthWrapper.tsx](https://github.com/artsy/force/blob/main/src/desktop/apps/articles/components/AuthWrapper.tsx) (— the existing code is still used on `/news`). This should fix the failing Integrity specs (cc @joeyAghion).
=> fix(articles): ports scrolling auth modal

src/v2/Components/AuctionBuyersPremiumDialog.tsx, src/v2/Components/__tests__/AuctionBuyersPremiumDialog.jest.tsx
cc @negotiate-devs
Context:
https://artsy.slack.com/archives/CCS8TMQ0K/p1636044522073500
Example: 
https://www.artsy.net/artwork/sam-francis-blue-green-lembark-l-dot-56-sf-318
Before:
After:
[NX-3004]: https://artsyproduct.atlassian.net/browse/NX-3004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Issue with Buyer’s Premium modal display

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial2.jest.tsx
[NX-3039]
Even though the artwork is listed as `Contact Gallery` only, we still want to display Edition Sets select radio buttons (in case `Make Offer On All Eligible Artworks` lab feature is enabled)
**Before:**
**After:**
Important to have in mind that these changes are focused exclusively on **displaying** the radio buttons.
Actual usage of this data will be implemented during [NX-3051]
[NX-3039]: https://artsyproduct.atlassian.net/browse/NX-3039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NX-3051]: https://artsyproduct.atlassian.net/browse/NX-3051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NX-3039] Enable edition sets selection for inquireable artworks

src/v2/Apps/_About2/AboutApp.tsx
This ports over content from `/about` to `/about2` with **very loose** styling and without responsive layout. Leaving the latter parts to the experts.
https://user-images.githubusercontent.com/29984068/149032546-ce57008e-3e4d-446d-aa9c-f88a35e14784.mp4
=> chore: port content from /about to /about2

src/v2/Apps/_HowAuctionsWork2/HowAuctionsWorkApp.tsx
Addresses https://artsyproduct.atlassian.net/browse/GRO-737
This rebuilds the how auctions work page in Palette. 1 image is missing (needs to be created), and we should probably refresh the images in general but basically done. We can follow up.
=> feat(AboutAuctions): Rebuild How Auctions Work page 

docs/best_practices.md
Follows https://github.com/artsy/force/pull/8853 which integrated Segment/OneTrust. The integration requires us to assign cookie categories to relevant Segment Destinations. Update Best Practices doc about how to do that.
=> feat: add item for segment/onetrust integration

src/v2/Apps/Artwork/Utils/createCollectUrl.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
[PX-4828](https://artsyproduct.atlassian.net/browse/PX-4828)
This PR adds "NFT" to the artwork grid filter (I believe also used on fair page and collections page) behind an admin flag.
Also adds "NFT" to `createCollectUrl`.
I guess this needs gravity/crispr? work to actually show works marked as "NFT"? Am I missing something in Force?
Admin:
Non admin:
Checked:
=> feat: Add nft medium type to filter

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarSizeInfo.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarMetadata.jest.tsx, src/v2/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarMetadata.ts
JIRA Card: https://artsyproduct.atlassian.net/browse/GRO-710
In cases where a dimension field contains no digits ([production example](https://www.artsy.net/artwork/larva-labs-sealed-cryptopunk-number-934)), we shouldn't be rendering blank dimensions.
<details>
<summary>Broken Example - Before (local)</summary>
</details>
<details>
<summary>Broken Example - After (local)</summary>
</details>
<details>
<summary>Artwork with Dimensions and Editions - After (local)</summary>
</details>
=> fix: Render dimensions when digits are present

src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts, src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createOrUpdateConsignSubmission.ts
We started recording user agents when creating artwork submissions from Force in #9192 so that we can easily identify the source of a submission when debugging issues in Convection.
We originally added `Artsy-Force` to the front of the user agent string, but after looking through existing submissions in Convection, I realized that Eigen:
1. Adds its identifying information at the end of the user agent string, and
2. Uses the `Artsy-Mobile/[version] Eigen/[version]` convention
I would like to propose we change the user agent string that Force sends to Convection to be `... Artsy-Web Force` so that we are consistent with the existing pattern, which should make our lives a bit easier when we parse user agent strings.
=> Move client name to end of user agent string for artwork submissions

src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx, src/v2/Components/SavedSearchAlert/Utils/__tests__/getNamePlaceholder.jest.ts, src/v2/Components/SavedSearchAlert/Utils/getNamePlaceholder.tsx, src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
Jira ticket: [FX-3677]
* should **not display** "• 1 filter" in name input if no filter is selected and only the artist's name is displayed as a pill (for example, _Banksy_)
* should **display** "• 1 filter" in name input when a user adds a filter (for example, _Banksy • 1 filter_)
https://user-images.githubusercontent.com/3513494/149126899-55aba2d9-9639-49f2-b965-a84610c99df1.mp4
[FX-3677]: https://artsyproduct.atlassian.net/browse/FX-3677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-3677): update the filter counting logic for name input

src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx, src/v2/Components/ArtworkFilter/SavedSearch/Components/__tests__/CreateAlertButton.jest.tsx
Jira ticket: [FX-3678]
When logged out and I click “Create alert”, I see the `authImpression` analytics event but never see the `clickedCreateAlert` event come through - even after I'm successfully logged in and the modal pops up.
* `clickedCreateAlert` event should be tracked when an unauthorized user clicks on “Create Alert” button
[FX-3678]: https://artsyproduct.atlassian.net/browse/FX-3678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-3678): correctly track event for create alert button

src/v2/Apps/MeetTheSpecialists/MeetTheSpecialistsApp.tsx, src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx, src/v2/Apps/MeetTheSpecialists/meetTheSpecialistsRoutes.tsx, src/v2/routes.tsx
I built this page as a request from Advisory during the January 2022 Hackathon, it adds a new route and static page data for a Meet the Specialists page. Designs [here](https://www.figma.com/file/m6gDpKHEWDbYJyrwsVZDBr/Artsy-3.0-Design-System?node-id=6867%3A8040). cc @artsy/negotiate-devs 
Mobile:
https://user-images.githubusercontent.com/10385964/150017280-ee1e2493-953b-48a4-9cba-51d6a50a39b6.mov
Desktop:
https://user-images.githubusercontent.com/10385964/150017765-2c2ff0a5-a6e8-4276-b5b1-55689f2ca2cf.mov
=> feat: Add Meet the Specialists page

src/v2/Components/ArtworkFilter/SavedSearch/Components/ArtworkGridFilterPills.tsx, src/v2/Components/ArtworkFilter/SavedSearch/Components/Pills.tsx
Jira ticket: [FX-3682]
If a user clicks or hovers the mouse cursor over the artist pill, then the highlighted state is applied to it (see attached video)
* Artist pill should not apply any visual changes when clicking or hovering over it
https://user-images.githubusercontent.com/3513494/150116002-0b33f843-e8ce-440a-8e09-7a63eab8fdcd.mp4
https://user-images.githubusercontent.com/3513494/150116077-ae0b6f3b-403a-4b5b-80eb-1633dd74435c.mp4
[FX-3682]: https://artsyproduct.atlassian.net/browse/FX-3682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-3682): don't apply highlighted state for artist pill

src/v2/Apps/_Preferences2/PreferencesApp.tsx, src/v2/Apps/_Preferences2/preferencesRoutes.tsx, src/v2/routes.tsx
This is the scaffolding for the upcoming Interest-based preference center work. Set up our development route under `/preferences2`
=> feat(new-routes): Added in the Preferences2 route

src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarMetadata.jest.tsx
This PR is a follow-up to #9191. It's not directly related to the functionality, but @damassi let me know we should be trying not to use this magic comment.
In the test file, there was one instance I couldn't figure out how to remove, happy to get some help there or punt it for now!
=> chore: Remove unnecessary TS annotation

.secrets.baseline, src/config.ts, src/typings/sharify.d.ts, src/v2/Apps/Authentication/Server/__tests__/redirectPostAuth.jest.ts, src/v2/Apps/Authentication/Server/redirectPostAuth.ts, src/v2/Apps/Authentication/Utils/__tests__/helpers.jest.ts, src/v2/Apps/Authentication/Utils/helpers.ts, src/v2/Apps/Authentication/__tests__/authenticationRoutes.jest.tsx, src/v2/Apps/Authentication/authenticationRoutes.tsx
I reverted this PR originally because I realized that it didn't work well in the "default" case (when no env vars were set), which was not intentional.
This includes the original commits, with the addition of two:
1. Allow for redirecting to the `APP_URL` 
2. Allow for redirecting to the `API_URL`
This way, our `ALLOWED_REDIRECT_HOSTS` list does not need to include those, and be saved for other, less-trivial hosts.
=> (Double revert!) Allow for redirecting outside of artsy.net (within reason) after auth

src/v2/Apps/Authentication/Utils/useAuthForm.ts, src/v2/Apps/Authentication/__tests__/authenticationRoutes.jest.tsx, src/v2/Apps/Authentication/authenticationRoutes.tsx, src/v2/Components/Authentication/Types.ts
Still on the quest to allow us to use force's login form to auth into api.artsy.net! (Which will allow us to deprecate gravity's /log_in form, and we'll have one source of truth).
This PR fixes an issue that occurs when a user is logged into force, but _not_ into api.artsy.net.
Although we automatically log you into api.artsy.net after you log into force, it's possible to log out of api.artsy.net while still being logged into force. This can happen by:
- Clicking the "Sign out" button from api.artsy.net 
- If you were previously logged in but now the app you're logging into requires 2FA
- ... other pathways!
When that happens, we enter into an infinite loop:
- When you attempt to authorize, Gravity will automatically redirect you to the login form (in this scenario, force's), if you're …
=> Allow for auth-ing from the API if logged into force

src/v2/Apps/Order/Routes/Accept/index.tsx
Addresses [TX-72] Pair w/ @starsirius on this fix.
The bug originally demonstrated in this ticket was resolved by the time I got to it, but there was still a secondary bug to be addressed: after the user went through the card verification process they were redirected back to the payment screen.
The issue was solved by removing a redirect to the `/status` route and instead resubmitting the form for the user. 
[TX-72]: https://artsyproduct.atlassian.net/browse/TX-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(payment): Buyer can't accept seller's offer when payment requires authentication

src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx, src/v2/Components/ArtworkFilter/SavedSearch/Components/__tests__/CreateAlertButton.jest.tsx, src/v2/Utils/openAuthModal.ts
Jira ticket: [FX-3681]
If an unauthorized user clicks on the "Create Alert" button, a modal with sign up will open. After completing the sign up procedure, the user is redirected to the onboarding page
* After sign up procedure, a create alert modal should opened without redirecting to the onboarding screen
* All previously selected filters should be displayed in create alert modal
https://user-images.githubusercontent.com/3513494/149965636-84b09d62-7b40-40b7-8556-3fdbb86e450e.mp4
https://user-images.githubusercontent.com/3513494/149965599-f0302fe3-cbfc-4d43-80f2-623b78f4d291.mp4
[FX-3681]: https://artsyproduct.atlassian.net/browse/FX-3681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-3681): Sign up flow should skip onboarding when trying to create alert

src/v2/Components/NavBar/NavBar.tsx
In preparation for the NFT sale we are running, this PR adds a link to `NFTs` (destination: https://nft.artsy.net) to the nav bar.
In order to avoid a weird line break, this PR also hides the "Download App" link except at the two largest breakpoints.
Will wait to merge until I get the go-ahead from @GuillaumeDelg .
=> DONTMERGE: Adds NFTs link to the nav bar

src/v2/Apps/Order/Components/PriceOptions.tsx, src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
Added scroll to focus functionality when entering custom offer price.
Screenshot before toggle or text input was pressed:
Screenshot after toggle or text input was pressed:
=> feat(NX-3014): Scroll to focus functionality when entering custom offer price

CONTRIBUTING.md
Noticed some confusion around needed libraries (detect-secrets) and realized there's no link over to Potential in our setup script.
=> docs(setup): Add instructions about potential

src/v2/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryFigure.tsx, src/v2/Apps/Authentication/Routes/ResetPasswordRoute.tsx, src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx, src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsPassword.tsx, src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactorBackupCodes.tsx, src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethod.tsx, src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethods.tsx, src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddress.tsx, src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddresses.tsx, src/v2/Apps/Unsubscribe/Components/UnsubscribeLoggedIn.tsx, src/v2/Apps/Unsubscribe/Components/UnsubscribeLoggedOut.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx, src/v2/Components/Inquiry/Views/InquiryBasicInfo.tsx, src/v2/Components/Inquiry/Views/InquiryCommercialInterest.tsx, src/v2/Components/Inquiry/Views/InquiryInquiry.tsx, src/v2/Components/Inquiry/Views/InquiryInstitutionalAffiliations.tsx, src/v2/Components/Inquiry/Views/InquiryLogin.tsx, src/v2/Components/Inquiry/Views/InquiryResetPassword.tsx, src/v2/Components/Inquiry/Views/InquirySignUp.tsx, src/v2/Components/Inquiry/Views/InquirySpecialist.tsx, src/v2/Utils/Hooks/useMode.ts
We've been using the `enum Mode` pattern for a little while now and i'm always thinking we could eliminate the extra code around enums. 
What this does is gives us a new `useMode` hook which is an alias to `useState`. While its not much, it does formalize the fact that we're using the mode pattern, and instead of enums uses string unions. Enums are a weird feature of TypeScript that can lead to problems in different contexts. 
=> feat(hooks): Add useMode hook and update refs

src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
When hovering over the "save alert" button, the bell color currently doesn't change. Quick fix!
Before:
After:
=> chore: fix save search bell color

src/v2/Apps/Artist/Routes/Overview/Utils/hasOverviewContent.ts, src/v2/Apps/Artist/__tests__/ArtistApp.jest.tsx
Fixes an unreported bug I noticed on a few of these low-content artists where some overview content was appearing (and thus showing the overview page); however since we weren't checking for the condition we were hiding the overview tab. 
=> bugfix(artist-app): Fix missing overview tab

src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx
We were skipping this test because of some confusing behavior, but things should be working now.
I also wanted to include a few more unit tests around the cards we have for this feature!
=> Expand tests for the preference center

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx, src/v2/Utils/user.ts
Addresses [TX-89]
Add "Avalara Phase 2" feature flag var to `ArtworkSideBarCommercial`. Set the text display to be disabled upon activation of the phase 2 flag. 
[TX-89]: https://artsyproduct.atlassian.net/browse/TX-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Conditional removal of "Price includes tax" messaging

src/v2/Apps/Order/Components/PriceOptions.tsx, src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
Based on a request from design to change the "Offer too low" notice always to be visible until the user has entered an amount higher than 80% of the listed price.
https://user-images.githubusercontent.com/7117670/152004741-628f0c74-9c0a-4bc6-be97-34d9e28c66c6.mov
cc @artsy/negotiate-devs
=> fix: update when the price too low notice shows up

src/v2/Apps/Conversation/Components/ConversationHeader.tsx
Clean up an import that is erroneously causing `@arsty/reaction` to be
imported into v2.
=> fix: Reaction Import in V2

src/v2/Components/ArtworkFilter/SavedSearch/Utils/__tests__/savedSearchCriteria.jest.ts, src/v2/Components/ArtworkFilter/SavedSearch/Utils/savedSearchCriteria.tsx
Jira ticket: [FX-3665]
Follow up of artsy/metaphysics#3699.
Replaces `artistID` with `artistIDs` for saved searches.
https://user-images.githubusercontent.com/3513494/152139110-8e67b0e5-3938-492e-af38-0ba2c473fbde.mp4
[FX-3665]: https://artsyproduct.atlassian.net/browse/FX-3665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-3665): replace deprecated artistID with artistIDs[]

src/v2/Apps/Order/Components/PriceOptions.tsx, src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
Because of how the triggering of the "different amount" option was set up, whenever the user would interact with anything on that radio, it would cause the event to fire continuously. Corrected to only fire once on selection.
=> fix: Corrected logic which led to one event firing multiple times

src/v2/Apps/Conversation/Components/Conversation.tsx
I caused this bug as part of my sidebar PR because I removed `CANCELED` and `REFUNDED` events from the conversation query and I don't even remember why I did it - the sidebar component was already filtering those events out. Sorry everyone :(
=> Fix: old order events not showing up in conversations

src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Artsy specialists were receiving a lot of spam calls so they requested that we remove their phone numbers from `/meet-the-specialists ` as an interim step until a general support page is created.
=> [GRO-788] remove links to specialist phone numbers

src/v2/Components/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
Removing the admin flag for the NFT medium type and moving it up above the fold in the medium filter on artsy.net/collect
Thanks to @SamRozen's [ping in Slack](https://artsy.slack.com/archives/C02STV6RDT4/p1643834792432649), now noticing that we have ~15 works populated [here](https://www.artsy.net/collect/nft) that partners added themselves in the last couple weeks. This is even before we've done the migration that we're planning for next week: manually switching the medium type on ~230 works to "NFT" so they populate here too. I think that's enough to roll out to production.
How it looks above the fold:
=> feat: Remove admin flag for NFT medium filter and move above fold

src/v2/Apps/Order/Routes/Offer/index.tsx, src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx, src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx, src/v2/Apps/__tests__/Fixtures/Order.ts
[NX-3015]
This PR removes flag checks for the "New Offer Submission" page and updates tests accordingly.
[NX-3015]: https://artsyproduct.atlassian.net/browse/NX-3015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: remove new offer submission flag

src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx, src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx
Jira ticket: [FX-3686]
* Show alerts for 6 seconds
* Alerts should be displayed at the top in the middle of the screen (see [design](https://www.figma.com/file/xsnfIWE7H67ZndGoEPVtN0/Alerts-Sandbox?node-id=947%3A24402))
* Message by action:
* Create new alert action = `Your Alert has been saved.`
* Update alert action = `Your Alert has been updated.`
* Delete alert action = `Your Alert has been deleted.`
https://user-images.githubusercontent.com/3513494/151775668-db3574a0-802b-4e2a-9cd5-80e3e693ba72.mp4
https://user-images.githubusercontent.com/3513494/152174469-6f544d5f-935d-4143-ab16-e77c4635359e.mp4
https://user-images.githubusercontent.com/3513494/152176896-ca13970b-0239-40cc-b180-ef4c40ed043a.mp4
[FX-3686]: …
=> feat(FX-3686): Display alerts for saved search

src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx, src/v2/__generated__/HomeFeaturedMarketNewsQuery.graphql.ts, src/v2/__generated__/HomeFeaturedMarketNews_Test_Query.graphql.ts, src/v2/__generated__/HomeFeaturedMarketNews_articles.graphql.ts
All I did here was switch from the `article.name` to the `byline` field that was already added by @dzucconi - here's some visual proof:
I was expecting to have to deal with some test fallout but...I think it was all correctly regenerated by relay? Pretty magical! ✨ 
https://artsyproduct.atlassian.net/browse/GRO-721
=> feat: Use article byline on homepage GRO-721

src/v2/Apps/Conversation/Components/Conversation.tsx, src/v2/Apps/Conversation/Components/ConversationMessages.tsx, src/v2/Apps/Conversation/Components/OrderUpdate.tsx, src/v2/Apps/Conversation/Components/__tests__/ConversationMessages.jest.tsx, src/v2/Apps/Conversation/Components/__tests__/OrderUpdate.jest.tsx
[NX-3069](https://artsyproduct.atlassian.net/browse/NX-3069)
Because users will be pointed to the inbox after making an offer (see [NX-3041](https://artsyproduct.atlassian.net/browse/NX-3041)), we need to make it clear for them where to see the details of the offer.
Twin PR on Eigen: https://github.com/artsy/eigen/pull/6139
[Figma file](https://www.figma.com/file/PgmxHwBnoOUS4ybwpK2mTN/Make-Offer-on-all-Eligible-Artworks?node-id=525%3A3575) for reference.
=> Add a “See details.” text link that opens up the conversation sidebar

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx, src/v2/__generated__/SavedSearchAlertListItem_item.graphql.ts, src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts, src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts, src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
Jira ticket: [FX-3727]
* Open artist's artworks screen when "View All" button is clicked
* Display filters as selected that were specified in saved search alert on artist's artworks screen
https://user-images.githubusercontent.com/3513494/152999096-c45ba8dd-764b-4e4b-ab66-30658f97e584.mp4
[FX-3727]: https://artsyproduct.atlassian.net/browse/FX-3727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-3727): Open artist's artworks screen with applied filters when "View All" button is clicked

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionInfoPolling.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx, src/v2/__generated__/ArtworkSidebarAuctionInfoPolling_artwork.graphql.ts, src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts, src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
Looks like:
I'll make a couple of comments inline, but this wound up being relatively straightforward (I had thought there might be more of a refactor needed).
=> feat: pulse current bid when it updates via polling

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx, src/v2/Components/ArtworkFilter/SavedSearch/Components/CreateAlertButton.tsx, src/v2/Components/ArtworkFilter/SavedSearch/Components/__tests__/CreateAlertButton.jest.tsx, src/v2/Components/ArtworkFilter/__tests__/ArtworkGridFilterPills.jest.tsx, src/v2/Components/SavedSearchAlert/DownloadAppBanner.tsx, src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx, src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
Jira ticket: [FX-3730]
[Figma](https://www.figma.com/file/xsnfIWE7H67ZndGoEPVtN0/Alerts-Sandbox?node-id=1255%3A19002) documents the specific screens for copy edits
* Create alert modal
* title: `Create Alert`
* name field title: `Alert Name`
* download app badges: `Get alerts direct to your mobile when you download the Artsy app.`
* Create alert button label on artworks grid: `Create Alert`
* [Figma](https://www.figma.com/file/xsnfIWE7H67ZndGoEPVtN0/Alerts-Sandbox?node-id=1255%3A19002)
* [Google doc](https://docs.google.com/document/d/1QexY-xIeQS8mH8cTjfCFUZYaSMveczsJmkYcAU7bX7g/edit#)
[FX-3730]: https://artsyproduct.atlassian.net/browse/FX-3730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-3730): update alerts copy

src/v2/Apps/Order/Routes/Offer/index.tsx, src/v2/Apps/Order/Routes/Review/index.tsx, src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx, src/v2/__generated__/ReviewSubmitOfferOrderWithConversationMutation.graphql.ts
[NX-3044]
Uses submitOfferOrderWithConversation mutation in order to create conversation and like to the offer and make an offer.
Also creates a note to be used as the first message of the conversation when no note is provided.
[NX-3044]: https://artsyproduct.atlassian.net/browse/NX-3044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(offer): use submitOfferOrderWithConversation mutation

CONTRIBUTING.md
I think it might be a little more helpful to show the `--watch` flag with Jest since most folks probably won't be working on the legacy CoffeScript and Mocha code.
=> docs: Add more recent example for --watch [ci skip]

src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx, src/v2/Apps/Settings/Routes/DeleteAccount/DeleteAccountRoute.tsx, src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsEmailPreferences/SettingsEditSettingsEmailPreferences.tsx, src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx, src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethod.tsx, src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethodForm.tsx, src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertDeleteModal.tsx, src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx, src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddress.tsx, src/v2/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx, src/v2/Apps/Unsubscribe/Components/UnsubscribeLoggedIn.tsx, src/v2/Utils/Hooks/useMutation.ts
This updates the implementation of `useMutation`'s `submitMutation` fn to be a little clearer and somewhat more verbose. New API: 
```tsx
const { submitMutation } = useMutation(...)
await submitMutation({ 
variables: { foo },
rejectIf: res => res.field.hasError
})
```
=> refactor(hook): Update useMutation hook

package.json, src/v2/Components/Authentication/Components/AuthenticationFooter.tsx, src/v2/Components/Authentication/Views/LoginForm.tsx, src/v2/Components/Authentication/Views/SignUpForm.tsx, src/v2/Components/Authentication/__tests__/FormSwitcher.jest.tsx, src/v2/Components/Authentication/__tests__/Views/LoginForm.jest.tsx, src/v2/Components/Authentication/__tests__/Views/SignUpForm.jest.tsx, yarn.lock
The designs accompanying this ticket are quite a bit broader in scope than the ticket itself, and there were some changes to the legal text that we aren't totally sure about ([related Slack thread](https://artsy.slack.com/archives/C01ADJNCS5D/p1643746728541839)).
To match those designs, it seems like we'll have to rewrite most of the view logic.
We settled on leaving things in this halfway state since we'll be revisiting the modal fairly soon anyway.
Ticket: [GRO-639](https://artsyproduct.atlassian.net/browse/GRO-639)
<details>
<summary>Log in modal (after)</summary>
</details>
<details>
<summary>Sign up modal (after)</summary>
</details>
=> feat (GRO-639): User sees updated visuals for auth options

docs/authentication.md
Leaving behind some context from my work on adding Google Auth to Force.
Most of my notes are actually made useless by the move in #9263, which is great because they were notes on things that went wrong in local development. 🎉
=> docs: Add authentication doc [ci skip]

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
[NX-3077]
We had a conditional to hide the Contact Gallery button on the artwork page in case the artwork is offerable/acquireable.
This condition doesn't seem to make sense as an artwork can't be selected as `offerable` **and** `inquireable` at the same time in CMS. However, it wouldn't also make any difference in the flow either.
Given we're changing the `offerable` scenario in MOOAEA, artworks that are `inquireable` are also `offerable`, therefore, we do not want to hide the button in these cases.
Besides this, we're handling these conditionals in Gravity at this point (see https://github.com/artsy/gravity/pull/14971). Gravity is ensuring Contact Gallery button is hidden in case `offer` field is `true` (and not if `offerable?` method is `true` as it was happening here).
Force shouldn't …
=> [NX-3057] Remove unneeded conditionals to hide Contact Gallery button

src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx, src/v2/Apps/Settings/Routes/EditSettings/Components/__tests__/SettingsEditSettingsLinkedAccounts.jest.tsx
I noticed that the Apple logo had an underline beneath it, I fixed that
by using the AppleIcon from palette.
While in this file, I went ahead and changed things over to the
IconButton component too, just to be consistent.
📹 [Loom Video](loom.com/share/58ac7c9d1bc646ccb26b2110d1e338b7)
=> bug: Fix underline inconsistency

src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/PhotoThumbnail.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/PhotoThumbnail.jest.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx, src/v2/__generated__/UploadPhotos_ImageRefetch_Query.graphql.ts
When I upload an image and navigate away from the photo upload step, if I return to the photo upload step before Gemini has finished processing a thumbnail for the image, then I see an empty grey box. Now instead text "Processing" will be shown atop of the grey box in > xs version, and in xs version we show Spinner instead
Jira - https://artsyproduct.atlassian.net/browse/SWA-185
https://user-images.githubusercontent.com/79979820/152970059-cb189aa4-f1a1-4345-a63c-9c40e864fb6c.mov
Image refeching:
https://user-images.githubusercontent.com/79979820/153593567-8338bfa1-ce4b-4f33-87aa-69f8b89b7f64.mov
=> [SWA-185]: Display "Processing" label on an image preview if still processing

data/schema.graphql, src/v2/Apps/Article/ArticleApp.tsx, src/v2/Apps/Article/Components/ArticleHeader.tsx, src/v2/Apps/Components/AppToasts.tsx, src/v2/__generated__/ArticleApp_article.graphql.ts, src/v2/__generated__/ArticleBody_test_Query.graphql.ts, src/v2/__generated__/ArticleHeader_article.graphql.ts, src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
Closes [GRO-818](https://artsyproduct.atlassian.net/browse/GRO-818)
As mentioned here: https://github.com/artsy/metaphysics/pull/3777 — Positron hero units have a `url` associated with them, but the function of that URL changes depending on the specific layout. In the case of a "basic" layout we use it as an embed. 🤷
=> feat(GRO-818): hero unit video layout

src/v2/Apps/Order/Components/ShippingQuotes.tsx, src/v2/Apps/Order/Components/__tests__/ShippingQuotes.jest.tsx
Addresses: https://artsyproduct.atlassian.net/browse/PX-4794
Radio button for first shipping option is selected on initial load
If user selects a shipping quote for purchase and comes back to the page, the user's selection takes precedence. 
https://user-images.githubusercontent.com/12748344/154365103-01f325a2-3e60-459d-8873-94956fa3b0f4.mov
=> [chore: PX-4794] Default to first shipping quote on initial page load

src/v2/Apps/_About2/AboutApp.tsx
I replaced the app store image in the App section to one without a caption and replaced the transparent app store buttons with ones with color. The big image is still low res, but this can get shipped without it for now.
=> [GRO-734](feat): small design fixes for /about2

.secrets.baseline, src/config.ts, src/lib/__tests__/current_user.jest.ts, src/mobile/components/layout/stylesheets/embedded.styl, src/typings/sharify.d.ts, src/v2/Apps/Authentication/Components/ModalContainer.tsx, src/v2/Components/Authentication/FormSwitcher.tsx, src/v2/Components/Authentication/ModalManager.tsx, test.mocha.js
Twitter and LinkedIn authentication support [was previously removed](https://github.com/artsy/artsy-passport/pull/131), so I think we should delete these references to that code too.
=> Remove references to removed auth providers

src/v2/Apps/Artists/Components/ArtistsCarouselCell.tsx, src/v2/Apps/Artists/Routes/ArtistsIndex.tsx
This page was done prior to strict-mode being enabled which would have dealt with these errors. This page being down is causing a smoke test to fail as well.
=> fix(artists): prevents 500s when missing data

src/v2/Components/NavBar/NavBar.tsx, src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx, src/v2/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
This commit updates the NFTs nav link to a relative `/nft` href. This will match a currently [registered vanity shortcut](https://artsy.net/nft) to `/gene/nft`.
The gene is currently unpublished so the page a user is redirected to throws a Forbidden 403 error.
We can either:
- Publish the gene, which will make the gene page visible
- Update the vanity shortcut to another visible page. The collect page filtered
to artworks of the NFT medium type, for example.
Either way, changing the nav link to not point directly to a specific subdomain gives us more flexibility and a UI to change where this link redirects a user to.
Link to a related [Slack thread](https://artsy.slack.com/archives/CHVFQ06DV/p1645020706482189) 🔒
=> feat: update NFTs nav link to /nft

src/desktop/apps/auction/components/layout/auction_info/Registration.tsx, src/v2/Apps/Auction2/Components/AuctionDetails/AuctionInfoSidebar.tsx
[GRO-826]
Replaced the old `Contact Us:` phone number with the newest number +1-845-582-3967
New Behavior:
[GRO-826]: https://artsyproduct.atlassian.net/browse/GRO-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated: Changed the phone number on artsy.net/auction sale pages

src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
[GRO-787]
[GRO-789]
Added additional copy to the Meet The Specialist page, including links to help center and support emails. Also included an update to the SEO elements, added in a title tag and meta description.
FIGMA DESIGN: https://www.figma.com/file/m6gDpKHEWDbYJyrwsVZDBr/Artsy-3.0-Design-System
New Displays!
Desktop
Mobile
[GRO-787]: https://artsyproduct.atlassian.net/browse/GRO-787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
SEO Title Tag and Meta Added:
[GRO-789]: https://artsyproduct.atlassian.net/browse/GRO-789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-787 & GRO-789: User sees general support CTAs on /meet-the-specialists and updated copy/design on page

src/v2/Apps/Auction2/Auction2App.tsx, src/v2/Apps/Auction2/Components/AuctionActiveBids.tsx, src/v2/Apps/Auction2/Components/AuctionPromotedSaleRail.tsx, src/v2/Components/Artwork/ShelfArtwork.tsx, src/v2/__generated__/Auction2App_sale.graphql.ts, src/v2/__generated__/AuctionPromotedSaleRail_sale.graphql.ts, src/v2/__generated__/auction2Routes_TopLevelQuery.graphql.ts, src/v2/__generated__/useCreateBidderMutation.graphql.ts
This adds the promoted sale "Buy Now" rail to the page:
=> feat(auction2): Add promoted sale rail

src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
Small change to remove unneeded `Private Sales` header and update a specialists email
New Behavior:
=> GRO-787: Updated: Specialist page with new email for a specialist

src/v2/Apps/Order/Routes/Offer/index.tsx, src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx, src/v2/Apps/Order/Routes/__tests__/Offer2.jest.tsx
[NX-3074]
- Removes high-speed bump modal when an offer is higher than the list price
- Fixes an issue when the price was hidden we showed the low-speed bump modal informing the offer was X% under the list price
[NX-3074]: https://artsyproduct.atlassian.net/browse/NX-3074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: remove high speed bump modal from offer

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial2.jest.tsx, src/v2/Apps/Conversation/Components/OpenInquiryModalCTA.tsx, src/v2/Apps/Conversation/Components/__tests__/OpenInquiryModalCTA.jest.tsx, src/v2/Components/Artwork/Details.tsx, src/v2/Components/Artwork/__tests__/Details.jest.tsx
[NX-3082]
We're changing the copies around `Buy now`, `Make offer` and `Contact for Price` but only the copies, we are not touching in any `saleMessage` coming from Gravity or other services, nor the language elsewhere, example we still call Buy now and everything related to it, only the copy has changed to Purchase.
Artwork page (Price on Request)
Search screen (Price on Request)
Artwork page (Purchase & Make an Offer)
Conversation (Make an Offer)
[NX-3082]: https://artsyproduct.atlassian.net/browse/NX-3082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(NX-3082): change CTA copies

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx, src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx, src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx, src/v2/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
Type: **Enhancement**
Jira ticket: [FX-3768]
* Add `editedSavedSearch` event when the saved search alert was updated
* Track `deletedSavedSearch` event when the saved search alert was deleted
* [Find and Explore Analytics Tracking](https://docs.google.com/spreadsheets/d/1_VDAmRJz2K87FXDq7oh_tQSgwBv4syuZjaaR3sfetcI/edit#gid=121201130)
* [Notion card](https://www.notion.so/artsy/We-d-need-2-additional-event-tracking-179d8c06383e4a9eafe86f6c7eb8b466)
https://user-images.githubusercontent.com/3513494/155741736-4785f666-d52e-43b7-9740-d76e25ed8ef5.mp4
https://user-images.githubusercontent.com/3513494/155741788-3bfd2df2-e903-485c-9d98-f1df2f1d5387.mp4
[FX-3768]: https://artsyproduct.atlassian.net/browse/FX-3768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
=> feat(FX-3768): Add additional event tracking

package.json, src/config.ts, src/lib/__tests__/featureFlagProvider.jest.ts, src/lib/featureFlags/FeatureFlagProvider.tsx, src/lib/featureFlags/featureFlagService.ts, src/lib/featureFlags/unleashService.ts, src/lib/middleware/featureFlagMiddleware.ts, src/middleware.ts, src/typings/sharify.d.ts, src/v2/Apps/ViewingRoom/ViewingRoomsApp.tsx, src/v2/DevTools/MockBoot.tsx, src/v2/System/Router/Boot.tsx, src/v2/System/Router/buildClientApp.tsx, src/v2/System/Router/buildServerApp.tsx, src/v2/System/Router/index.ts, src/v2/System/Server/sharifyHelpers.ts, src/v2/client.tsx, src/v2/server.ts, yarn.lock
This PR is a follow-up to the initial implementation of Unleash in Force, which led to an incident due to incorrect logic in `featureFlagMiddleware`. 
In `featureflagMiddleware`, we checked [here](https://github.com/artsy/force/blob/2706f4a2edd6b55ebd06ca9c765e8f68fccbbea1/src/lib/middleware/featureFlagMiddleware.ts#L12-L20) if there is an existing unleash client, and create one if there isn’t. We had the logic wrong and were creating a new instance of the unleash client on every request here, which caused the huge [spike of requests, leading to high latency and timeouts](https://app.datadoghq.com/apm/service/force/express.request?env=production&panel_end=1645656270957&panel_paused=true&panel_start=1645652670957&topGraphs=latency%3Alatency%2CbreakdownAs%3Apercentage%2Cerrors%3Acount%2Chits …
=> mc-jones/fix unleash implementation

src/v2/Apps/Partner/PartnerApp.tsx
This is a quick PR to make the banner static for the Cultural Attributes banner.
Uploading Screen Recording 2022-02-28 at 7.15.32 AM.mov…
New Behavior:
=> Make Marquee static with Cultural Attributes

src/v2/Apps/_Preferences2/PreferencesApp.tsx, src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx
This is something I noticed that will definitely come up in the Preference Center QA!
<details>
<a href="https://www.loom.com/share/28cb6f902ecc43f2951b0872dda0f75b">Video</a>
</details>
=> fix: Reset form on submission or cancel

src/lib/featureFlags/FeatureFlagProvider.tsx, src/lib/middleware/featureFlagMiddleware.ts, src/v2/System/Router/Boot.tsx, src/v2/System/Router/__tests__/buildClientApp.jest.tsx, src/v2/System/Router/__tests__/buildServerApp.jest.tsx, src/v2/System/Router/buildClientApp.tsx, src/v2/System/Router/buildServerApp.tsx, src/v2/System/Server/sharifyHelpers.ts, src/v2/System/SystemContext.tsx, src/v2/System/__tests__/useFeatureFlag.jest.tsx, src/v2/System/useFeatureFlag.tsx, src/v2/client.tsx, src/v2/server.ts
This PR simplifies the Unleash implementation by removing the previously used custom React `Context.Provider` in favor of `Force`'s `SystemContext`. 
- https://github.com/artsy/force/pull/9498
- https://github.com/artsy/force/pull/9393
- Allow for experimentation by implementing `useVariant` and analytics tracking. [PLATFORM-3922]
[PLATFORM-3922]: https://artsyproduct.atlassian.net/browse/PLATFORM-3922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: add featureFlags to SystemContext

src/v2/Apps/Collect/Routes/Collect/Utils/__tests__/getMetadata.jest.ts, src/v2/Apps/Collect/Routes/Collect/Utils/getMetadata.ts, src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx
Updates Force's color filter palette to reflect the changes from https://github.com/artsy/gravity/pull/15040 and https://github.com/artsy/gravity/pull/15051/files.
This should not be merged until all the Gravity PRs have been merged and artworks are reindexed to have the new color values!
Jira ticket: https://artsyproduct.atlassian.net/browse/FX-3718
=> feat[FX-3718]: update color palette

src/v2/Apps/Order/Routes/Offer/index.tsx, src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
[NX-3075]
Changes the modal message when the offer is under 20% list price; before was popping up when the offer was 25% under list price.
[NX-3075]: https://artsyproduct.atlassian.net/browse/NX-3075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: change low offer modal in offer submission page

src/v2/Apps/Conversation/Components/ConversationList.tsx
[NX-3076]
The conversation list was cut off at the bottom making the last element not become fully visible causing issues when trying to load more conversations on the desktop breakpoint.
This PR fixes the issue mentioned and one re-rendering issue causing some weird rendering of the loading spinner.
https://user-images.githubusercontent.com/15792853/155956354-00191426-2861-4cf3-bf32-f90503cb532b.mov
[NX-3076]: https://artsyproduct.atlassian.net/browse/NX-3076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: conversation list cut off

src/v2/Apps/Order/Components/TransactionDetailsSummaryItem.tsx, src/v2/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx
[TX-217](https://artsyproduct.atlassian.net/browse/TX-217)
This PR adds a conditional to display "Waiting for final costs" for the "Total" transaction detail line item when the total has not yet been calculated. Nothing was displayed previously.
=> feat(TX-217): update buyer total messaging

src/v2/Apps/_Preferences2/PreferencesApp.tsx, src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx
This branch contains a few fixes for the preference center form. After talking with @damassi and some of the other GROW engineers we decided this cancel button is a bit confusing and not worth the complexity.
=> fix(GRO-584): Remove interest based preference center cancel button

src/lib/middleware/errorHandler.tsx
https://artsyproduct.atlassian.net/browse/PLATFORM-4003
This change is an action item following [#inc-141](https://artsy.app.opsgenie.com/incident/detail/0f3fd6e1-9e57-40a5-a41b-92bc54a86356). During investigations responders noticed that the observed 504 errors were _not_ recorded in papertrail, making troubleshooting more difficult.
This adds server error logging to force middleware _errorHandler_ when in production mode.
=> feat: add server error logging in middleware

docs/best_practices.md
Adds an entry to our best practices doc around tracking. 
Example:
```tsx
import { useTracking } from "react-tracking"
import { ContextModule } from "@artsy/cohesion"
const MyApp = () => {
const { trackEvent } = useTracking()
return (
<Button onClick={() => {
trackEvent({
contextModule: ContextModule.myApp,
})
}}>
)
}
```
=> docs(best-practices): Add entry on tracking

src/lib/analytics/sentryFilters.ts
A followup to #[inc-141](https://artsy.app.opsgenie.com/incident/detail/0f3fd6e1-9e57-40a5-a41b-92bc54a86356) (_Force 504 errors and unleash request spike_) this removes _Response Timeout_ error type from ignored sentry errors.
Additionally, following [a suggestion](https://github.com/artsy/force/pull/9546#issuecomment-1059311495) this adds a new type of error (for the time being) to the ignored list as it is deemed harmless.
=> PLATFORM-4004 sentry(errors): edit sentry filters

src/v2/Apps/Shows/Components/ShowsHeader.tsx
https://artsyproduct.atlassian.net/browse/FX-3763
Just a lil `data-test` attribute for Cypress to grab onto.
This is a pre-requisite for https://github.com/artsy/integrity/pull/299, which establishes coverage for the list of geocoded cities.
=> test(geocoding): add test selector for Integrity

docs/creating_review_app.md
=> docs(review-app): Add notes on adding / updating ENV vars in the review app instance 

.circleci/config.yml
The `codecov` orb has been unused for a long time. And yet, renovate keeps bumping the version and rebasing the open PR (https://github.com/artsy/force/pull/9169), wasting CI time.
Next challenge: how to get renovate to stop rebasing all of these bump PRs constantly.
=> Remove unused codecov orb

src/v2/Apps/Order/Components/ArtworkSummaryItem.tsx, src/v2/Apps/Order/OrderApp.tsx, src/v2/Apps/Order/Utils/offerItemExtractor.tsx, src/v2/Apps/__tests__/Fixtures/Order.ts, src/v2/__generated__/AcceptTestQuery.graphql.ts, src/v2/__generated__/ArtworkSummaryItem_order.graphql.ts, src/v2/__generated__/CounterTestQuery.graphql.ts, src/v2/__generated__/NewPaymentTestQuery.graphql.ts, src/v2/__generated__/Offer2TestQuery.graphql.ts, src/v2/__generated__/OfferTestQuery.graphql.ts, src/v2/__generated__/PaymentTestQuery.graphql.ts, src/v2/__generated__/RejectTestQuery.graphql.ts, src/v2/__generated__/RespondCounterOfferMutation.graphql.ts, src/v2/__generated__/RespondTestQuery.graphql.ts, src/v2/__generated__/ReviewTestQuery.graphql.ts, src/v2/__generated__/ShippingTestQuery.graphql.ts, src/v2/__generated__/StatusQuery.graphql.ts, src/v2/__generated__/orderRoutes_AcceptQuery.graphql.ts, src/v2/__generated__/orderRoutes_CounterQuery.graphql.ts, src/v2/__generated__/orderRoutes_NewPaymentQuery.graphql.ts, src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts, src/v2/__generated__/orderRoutes_PaymentQuery.graphql.ts, src/v2/__generated__/orderRoutes_RejectQuery.graphql.ts, src/v2/__generated__/orderRoutes_RespondQuery.graphql.ts, src/v2/__generated__/orderRoutes_ReviewQuery.graphql.ts, src/v2/__generated__/orderRoutes_ShippingQuery.graphql.ts, src/v2/__generated__/orderRoutes_StatusQuery.graphql.ts
This PR updates our graphql queries and adds some type safety to avoid 500 errors when trying to load an order for an artwork that has become unpublished. 
Fixes [TX-66]
TODO: 
[TX-66]: https://artsyproduct.atlassian.net/browse/TX-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: TX-66 - gracefully handle orders with unpublished artworks.

src/v2/Apps/Collect/Routes/Collect/Utils/__tests__/getMetadata.jest.ts, src/v2/Apps/Collect/Routes/Collect/Utils/getMetadata.ts, src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx
In order to un-break Eigen's color filtering we'd like to revert all artworks to index the old color palette _only_, and thus we'd need to  also roll back Force's color filtering UI, i.e. revert https://github.com/artsy/force/pull/9497
(This should get merged and deployed before https://github.com/artsy/gravity/pull/15099)
See the following Slack threads:
- Diagnosis: https://artsy.slack.com/archives/C9SATFLUU/p1646667810727089 
- Fix: https://artsy.slack.com/archives/C9SATFLUU/p1646683881730749
=> fix(colors): revert recent changes to artwork color filtering

src/v2/Apps/_Preferences2/PreferencesApp.tsx, src/v2/Apps/_Preferences2/preferencesRoutes.tsx, src/v2/Apps/_Preferences2/useEditNotificationPreferences.tsx, src/v2/__generated__/PreferencesApp_viewer.graphql.ts, src/v2/__generated__/preferencesRoutes_PreferencesQuery.graphql.ts, src/v2/__generated__/useEditNotificationPreferencesMutation.graphql.ts
[GRO-862]
Added: Resolving authentication token not being passed properly for Preference Center updated. Being updated in Braze, but throwing an error that is citing a lack of user.
Need to see why toast is throwing us this error, even though Braze is successfully updating.
[GRO-862]: https://artsyproduct.atlassian.net/browse/GRO-862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-862: Signed out user flow error for preference center

src/v2/Apps/_Preferences2/PreferencesApp.tsx, src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx
Updated: addressed all blocking changes from the Preference Center QA doc
Notion Doc: https://www.notion.so/artsy/74fbad8d69bf465fb325db743a86b894?v=55c457b9b9ef4c6ba8fc08121342bb38 
Before:
After:
=> GRO-865: Copy updates from Preference Center QA session

src/v2/Apps/Home/Components/HomeTroveArtworksRail.tsx, src/v2/Apps/Home/HomeApp.tsx, src/v2/Apps/Home/__tests__/HomeTroveArtworksRail.jest.tsx, src/v2/__generated__/HomeTroveArtworksRailQuery.graphql.ts, src/v2/__generated__/HomeTroveArtworksRail_Test_Query.graphql.ts, src/v2/__generated__/HomeTroveArtworksRail_viewer.graphql.ts
This PR solves: [GRO-834]
To get more artwork on the homepage and available for users to check out!
Note: We're gonna want to remove Trove as an item on the carousel for `logged in` / `logged out` states which is something an admin does. 
Gotta coordinate with Jenna before pushing this live. 
[GRO-834]: https://artsyproduct.atlassian.net/browse/GRO-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [GRO-834] add Trove Rail to the Artsy homepage

src/v2/Apps/Home/Components/HomeTroveArtworksRail.tsx, src/v2/Apps/Home/__tests__/HomeTroveArtworksRail.jest.tsx, src/v2/__generated__/HomeTroveArtworksRailQuery.graphql.ts, src/v2/__generated__/HomeTroveArtworksRail_Test_Query.graphql.ts, src/v2/__generated__/HomeTroveArtworksRail_viewer.graphql.ts
Oops! While smoke testing this we realized that we were using the SALE artwork connection rather than the more general one. All this PR does is switch that over. Visual proof:
hashtag free britney
https://artsyproduct.atlassian.net/browse/GRO-834
=> fix: Use artwork connection for trove GRO-834

src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx, src/v2/jest.envSetup.ts
Spent a long while trying to figure out why my relay tests weren't passing when I knew they were correct and realized that we've been silently suppressing runtime errors in our relay tests! Somehow this has been missed for years.
This restores logging if there's a runtime error by capturing the common second argument for such failures.
=> fix(jest): Properly log out runtime JS errors

src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.jest.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/index.tsx
⚠️ This feature is behind a feature flag ⚠️
This ticket resolves [FX-3786](https://artsyproduct.atlassian.net/browse/FX-3786)
- introduced `artwork-page-create-alert` feature flag in [unleash](https://unleash.artsy.net/projects/default/features2/artwork-page-create-alert) 
- added `CreateArtworkAlertSection` to be displayed in all artwork screens when ff is enabled
- button is currently not doing anything follow up work will be addressed in another pr.
|Desktop| mobile small | mobile |
|--|--|--|
|![Screenshot 2022-03-09 at 17 15 14](https://user-images.githubusercontent.com/21178754/157483137-b18ec1f3-8382-4ff5-950a-b3a60d75cb9a.png)|![Screenshot 2022-03-09 at 17 15 04](https://user-images.githubusercontent.com/21178754/157483143-072f95fa-b899-492b-a014-2e406ada14da.png)|![Screenshot …
=> feat(FX-3786): add create alert button in artwork screen

hokusai/staging.yml
Inconsistent Integrity failures alerted us to this problem of cached review apps' pages polluting staging's responses. It frequently manifests as CORS violations (attempting to submit data from staging to a different subdomain) when logging in or signing up, but could theoretically affect any functionality since the included javascript assets might be incorrectly based on a review app's code.
Steps to reproduce:
* as an admin, clear Force's staging cache (`/clear-cache`)
* incognito and unauthenticated, visit the home page of a review app
* visit staging's home page
* note references to review app's subdomain in the HTML source
This kubernetes declaration appears to be all that's needed to isolate review apps' cached pages from staging's. (Review apps' cache keys will be prefixed with the …
=> Isolate review apps' cached pages from staging's (PLATFORM-3779 and PLATFORM-4034)

src/v2/System/__tests__/useFeatureFlag.jest.tsx, src/v2/System/useFeatureFlag.tsx
This PR adds analytics to the `useVariant` hook by sending an `Experiment Viewed` event to segment on the first instance the user is shown the flag's variation. 
To track if a user has seen the experiment before we are simply storing an array on `localStorage` with the name of the feature flag and the variant e.g., `${featureName}+${variantName}`.  On each `useFeatureVariant` we check the array to see if the experiment has been viewed before, and push it onto the array if not. This is a simple approach, but has the disadvantage of potentially sending multiple events for a single user in cases where they have cleared application storage from their browser. I'm not sure we can get around this issue by sticking with client-side tracking of repeat views. 
- #9513
- #9498
- #9393
- #9547
- …
=> Feat: analytics support for useVariant

src/v2/Apps/Order/Routes/Offer/index.tsx, src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx, src/v2/Apps/__tests__/Fixtures/Order.ts
[NX-3075]
Doesn't show the modal in the New Offer Submission step given a price under 80% of the list price.
[NX-3075]: https://artsyproduct.atlassian.net/browse/NX-3075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: doesn't display modal when price options are visible

src/lib/featureFlags/unleashService.ts
This PR passes in the environment to the Unleash client upon initialization. This will enable us to check for the environment in `context` from a [custom strategy.](https://docs.getunleash.io/advanced/custom_activation_strategy). Or, if we upgrade to a paid version, we can use [strategy constraints](https://docs.getunleash.io/advanced/strategy_constraints).
=> feat: pass in node env to unleash

package.json, yarn.lock
artsy/force#8620 was automatically merged, despite the fact that not all checks were started/passed
=> Revert "chore(deps): update dep typescript from 4.3.5 to v4.6.2"

src/v2/Apps/Auction/Routes/Bid/Components/PricingTransparency.tsx
Just caught this when changing max bids in the auction/id/bid form.
=> fix(auction): Fix caps case in loader

src/lib/passport/lib/passport/index.js
Based on the documentation, I think we should be doing this anyway. I'm hoping it will resolve https://artsyproduct.atlassian.net/browse/GRO-879 as well.
=> fix: Add scope parameter to Google strategy

docs/unleash_a-b_testing.md, src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx, src/v2/Components/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx, src/v2/System/useFeatureFlag.tsx
- Created `filters-expanded-experiment` flag in Unleash dashboard
- Activation strategy:
- gradual rollout 100%
- stickiness: `userID`
- Variants:
- we created the [variants](https://docs.getunleash.io/advanced/toggle_variants) that contain the actual experiment. Here we define a new variant as well as a control variant. It is worth noticing that all the variants will be weighted equally. You are able to define many variants – in this example, we have created 2. “control” is the control variant, while “experiment” is the alternative we want to test.
- add tracking `ExperimentViewed` event
- updated types and imports for analytics.
Noticed that there is no way of having two levels of `stickiness` 🤔 
- If we pick `sessionID` stickiness we result in having a consistent result during a …
=> feat: add simple unleash experiment in artist filters

src/v2/Apps/Auction/Components/AuctionDetails/__tests__/AuctionDetails.jest.tsx, src/v2/__generated__/CreateConsignSubmissionMutation.graphql.ts
I'm pretty surprised this is never come up since any SSR rendered page that relies on the X-TIMEZONE header is going to display UTC.
I suppose one way to fix this would be to set a cookie and defer to that on subsequent requests but the first request will always be UTC.
=> fix(auction): corrects display of tz in production

src/v2/Apps/Auction/Routes/AuctionRegistrationRoute.tsx, src/v2/Apps/Auction/Routes/__tests__/AuctionRegistrationRoute.jest.tsx, src/v2/Apps/Auction/auctionRoutes.tsx, src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx, src/v2/__generated__/AuctionRegistrationRouteTestQuery.graphql.ts, src/v2/__generated__/AuctionRegistrationRoute_me.graphql.ts, src/v2/__generated__/auctionRoutes_RegisterRouteQuery.graphql.ts
- [Link to register requiring credit card for returning bidders](https://www.notion.so/artsy/3b2ab528673e4b5892db9d7081466166?v=80f170f7972e4a20b9bad42a3650cb9a&p=9af839a5e6b24658a23b06fc768eb6e8)
- Other misc sort + pagination issue on initial load, where it wouldn't sort properly on page 2
Found an issue where when the user clicks page 2, the default sort is no longer applied. (However, if the user selected a sort, then its in the url bar, and it works fine.) 
Also fixes an issue where if a user already had a credit card on file /register would still show the registration form. Normally a user can't get to this URL from the UI, but didn't realize that ops folks were pasting it into emails. Now we'll check that condition and then redirect to …
=> fix(auction): misc bugs

src/v2/Apps/Partners/Routes/GalleriesRoute.tsx, src/v2/Apps/Partners/Routes/InstitutionsRoute.tsx
This PR solves [GRO-853] & [GRO-854]
Making these pages canonical to the homepage rather than a self-referring canonical so they can be properly crawled. 
[GRO-853]: https://artsyproduct.atlassian.net/browse/GRO-853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-854]: https://artsyproduct.atlassian.net/browse/GRO-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [GRO-853 & 854]: update metatags for /galleries and /institutions for SEO

src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/CreateArtworkAlertSection.jest.tsx, src/v2/Components/SavedSearchAlert/Components/SavedSearchAlertArtworkGridFilterPills.tsx, src/v2/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButton.tsx, src/v2/Components/SavedSearchAlert/Components/__tests__/CreateAlertButton.jest.tsx, src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx, src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
Type: **Refactor** & **Enhancement**
These changes will allow us to reuse [SavedSearchCreateAlertButton](https://github.com/artsy/force/blob/dimatretyak/refactor/reuse-create-alert-button/src/v2/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButton.tsx) component and its logic (this will be useful for the [FX-3788](https://artsyproduct.atlassian.net/browse/FX-3788) task)
=> refactor: Ability to reuse SavedSearchCreateAlertButton component on different grids

src/v2/Apps/Auction/auctionRoutes.tsx
The type of this PR is: **Bugfix** (kinda)
This PR solves [GRO-892]
I'm not 100% certain this is the preferred way to accomplish this with our router, but it does seem to work! 😆 
cc @damon is this fine to do?
[GRO-892]: https://artsyproduct.atlassian.net/browse/GRO-892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(GRO-892): Redirect from the old /sale path to /auction
