src/v2/Apps/Auctions/Components/__tests__/AuctionArtworksRail.jest.tsx
src/v2/__generated__/AuctionArtworksRail_Test_Query.graphql.ts
src/v2/__generated__/CurrentAuctions_Test_Query.graphql.ts
src/v2/__generated__/PastAuctions_Test_Query.graphql.ts

These specs are failing with `TypeError: Cannot read property 'trackEvent' of undefined` — adding the analytics provider isn't helping so pending for now.

fix: fixes build

---

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/AttributionClassFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/GalleryFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/InstitutionFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ResultOption.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ShowMore.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter2.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx

chore(filters): prepare filters for v3

---

package.json
src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
yarn.lock

See incident https://artsy.slack.com/archives/C01T7AA1QD9
Related: 
- https://github.com/artsy/palette/pull/903
- https://github.com/artsy/palette/pull/901

bugfix: Bump palette to ensure that ReadMore works

---

src/v2/Utils/getParam.tsx
src/v2/client.tsx
src/v2/server.ts

This speeds up our v2 client init by parallelizing the fetch of our async client imports.

feature: Parallelize client init imports

---

src/v2/Apps/Auctions/AuctionsApp.tsx
src/v2/Apps/Auctions/Routes/CurrentAuctions.tsx
src/v2/Apps/Auctions/__tests__/AuctionsApp.jest.tsx
src/v2/__generated__/CurrentAuctionsQuery.graphql.ts
src/v2/__generated__/CurrentAuctions_Test_Query.graphql.ts
src/v2/__generated__/CurrentAuctions_viewer.graphql.ts
src/v2/__generated__/auctionsRoutes_Current_AuctionsQuery.graphql.ts

This addresses the following tickets:
- https://artsyproduct.atlassian.net/browse/GRO-267
- https://artsyproduct.atlassian.net/browse/GRO-264
- https://artsyproduct.atlassian.net/browse/GRO-266
This is for Auctions2 QA fixes. I have updated the "Learn more about bidding on Artsy" to direct to Zendesk help center.  Updated the introduction copy text on artsy.net/auctions2. And put in a filter sort for Current Auctions so user sees auctions in chronological order.

Auctions2 QA Fixes

---

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ResultOption.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.jest.tsx

Closes https://artsyproduct.atlassian.net/browse/FX-2799

chore: last filter QA

---

src/v2/Apps/Partner/Components/Overview/ArticlesRail.tsx
src/v2/Apps/Partner/Routes/Overview/index.tsx
src/v2/Apps/Partner/partnerRoutes.tsx
src/v2/__generated__/ArticlesRail_articles.graphql.ts
src/v2/__generated__/Overview_partner.graphql.ts
src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts

Created articles rail on overview page
JIRA - https://artsyproduct.atlassian.net/browse/PX-3839
screenshot:

feat: add articles rail overview

---

src/v2/Apps/Fair/Routes/FairArtworks.tsx
src/v2/Apps/Gene/Components/GeneArtworkFilter.tsx
src/v2/Apps/Gene/Routes/GeneShow.tsx
src/v2/Apps/Gene/Routes/__tests__/GeneShow.jest.tsx
src/v2/Apps/Gene/geneRoutes.tsx
src/v2/Apps/Show/Components/ShowArtworks.tsx
src/v2/Components/Artwork/Details.tsx
src/v2/Components/Artwork/SaveButton/index.tsx
src/v2/Components/ArtworkGrid/ArtworkGridEmptyState.tsx
src/v2/Components/__tests__/__snapshots__/Artwork.jest.tsx.snap
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/AttributionClassFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/FilterExpandable.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/GalleryFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/InstitutionFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/ResultsFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter2.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx
src/v2/Components/v2/ArtworkFilter/index.tsx
src/v2/__generated__/GeneArtworkFilterQuery.graphql.ts
src/v2/__generated__/GeneArtworkFilter_gene.graphql.ts
src/v2/__generated__/GeneShow_Test_Query.graphql.ts
src/v2/__generated__/GeneShow_gene.graphql.ts

Notably here, I wound up refactoring `Details` into a functional component so as to be able to use the `useThemeConfig` hook. The specs for that pass without changes and *seem* comprehensive enough.

Adds artwork filter to gene2

---

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter2.tsx

Fixes https://artsyproduct.atlassian.net/browse/FX-2818
tweaks size entry parsing to use `*` instead of 0

fix: tweak logic foor setting/deleting custom size oon input change

---

src/v2/Apps/Auctions/Components/MyBids/MyBidsBidItem.tsx

Tiny lil `whitespace` fix. #trivial

fix: [Auctions2] Fix css line-break in watched lot

---

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/FacetFilter.tsx

Closes: [FX-2824](https://artsyproduct.atlassian.net/browse/FX-2824)

fix(filter): fixes input zoom on ios

---

src/v2/Apps/Partner/Components/PartnerArticles/ArticleCard.tsx
src/v2/__generated__/ArticleCard_article.graphql.ts
src/v2/__generated__/ArticlesQuery.graphql.ts
src/v2/__generated__/partnerRoutes_ArticlesQuery.graphql.ts
src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts

Changed article card title on thumbnailTitle
JIRA -> https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-3935&quickFilter=228

fix: Article card title

---

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter2.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx

Closes: [FX-2828](https://artsyproduct.atlassian.net/browse/FX-2828)

fix(filters): allows numeric inputs to be optionally empty

---

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
src/v2/Apps/Partner/Routes/Articles/index.tsx
src/v2/__generated__/ArticlesQuery.graphql.ts
src/v2/__generated__/Articles_partner.graphql.ts
src/v2/__generated__/partnerRoutes_ArticlesQuery.graphql.ts

JIRA - https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-3924&quickFilter=228
- removed useless Col, Row wrappers
- removed scrollTo (Pagination container has its scrollTo under the hood)
- added query params support
- fixed pagination functionality

fix: articles pagination fix

---

src/v2/Apps/Auctions/AuctionsApp.tsx

Quick fix to make integrity happy!

fix: [Auctions] Add h1 tag for integrity

---

src/v2/Apps/Consign/Routes/MarketingLanding/Components/InDemandNow/ConsignInDemandNow.tsx

fix: [Consign] Make sellThroughRate displayable

---

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
src/v2/Apps/Partner/Components/__tests__/NavigationTabs.jest.tsx
src/v2/Apps/Partner/partnerRoutes.tsx
src/v2/__generated__/NavigationTabs_Test_PartnerQuery.graphql.ts
src/v2/__generated__/NavigationTabs_partner.graphql.ts
src/v2/__generated__/PartnerApp_Test_Query.graphql.ts
src/v2/__generated__/partnerRoutes_ArtistsQuery.graphql.ts
src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts

This PR uses `displayArtistsSection` field from partner entity instead of partner profile.

fix: use fields from partner entity instead of profile

---

src/v2/Components/v2/ArtworkFilter/ArtworkFilters/SizeFilter2.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter2.jest.tsx

This PR addresses [FX-2817](https://artsyproduct.atlassian.net/browse/FX-2817) by changing the custom size filter fields from inches to centimeters.

fix: change custom size filter to centimeters [FX-2817]

---

src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx

Closes: [FX-2821](https://artsyproduct.atlassian.net/browse/FX-2821)

fix(fx-2821): force re-render when pathname changes

---

package.json
src/v2/Apps/Artist/Routes/Articles/__tests__/Articles.jest.tsx
src/v2/Apps/Artist/Routes/Shows/__tests__/Shows.jest.tsx
src/v2/Components/Pagination/index.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
yarn.lock

feat(pagination): supports v3

---

src/v2/Apps/Partner/Routes/Articles/index.tsx
src/v2/Apps/Partner/partnerRoutes.tsx
src/v2/Components/Pagination/index.tsx

JIRA - https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-3976&quickFilter=228
- Expanded Pagination component. Added the ability to specify offset attr with scrollTo

Fix: pagination scrolling to top

---

src/v2/Apps/Fair/Routes/FairArtworks.tsx
src/v2/__generated__/WorksQuery.graphql.ts
src/v2/__generated__/partnerRoutes_WorksQuery.graphql.ts

whoops! These additional variables (unneeded) were preventing the aggregation prop from flowing thru on a refetch.

fix: restore proper refetching behavior on fair artworks grid

---

src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails.tsx

fix: fix nationality ant birthday text color for artist details item

---

src/v2/Apps/Components/AppShell.tsx

This PR adds white background to the footer to fix the partner profile page. Also adds `AppContainer` to set to the footer the same width as for the page (please let me know if this is unnecessary).
JIRA - https://artsyproduct.atlassian.net/browse/PX-3984
Before:
Now:

fix(PX-3984): add background for the footer 

---

src/v2/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx

Reverts artsy/force#7370
Re: https://artsy.slack.com/archives/C9SATFLUU/p1618949962304400

Revert "fix(fx-2821): force re-render when pathname changes"

---

src/lib/braze.ts

I goofed. I had my logic wrong and it was trying to initialize on the server.

Fix: Correct logic causing braze to fail to initialize on the client

---

src/v2/Apps/Partner/Components/PartnerShows/ShowCard.tsx
src/v2/Apps/Partner/Components/__tests__/PartnerShows/ShowCard.jest.tsx
src/v2/Apps/Partner/Routes/Shows/index.tsx
src/v2/Apps/Partner/partnerRoutes.tsx
src/v2/__generated__/ShowCard_Test_Query.graphql.ts
src/v2/__generated__/ShowCard_show.graphql.ts
src/v2/__generated__/Shows_partner.graphql.ts
src/v2/__generated__/partnerRoutes_ShowsQuery.graphql.ts

JIRA -> https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-3969&quickFilter=228
- ShowCard implemented
- Tests for ShowCard implemented
- Added ShowCard on shows tab page (shows page is still in progress)
screenshot:

feat: show card implementation

---

src/v2/Apps/Gene/Routes/GeneShow.tsx
src/v2/Components/FollowButton/FollowGeneButton.tsx
src/v2/Components/FollowButton/__tests__/FollowGeneButton.jest.tsx
src/v2/Utils/openAuthModal.ts
src/v2/__generated__/FollowGeneButtonMutation.graphql.ts
src/v2/__generated__/FollowGeneButton_Test_Query.graphql.ts
src/v2/__generated__/FollowGeneButton_gene.graphql.ts
src/v2/__generated__/GeneShow_Test_Query.graphql.ts
src/v2/__generated__/GeneShow_gene.graphql.ts
src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts

Closes: [FX-2858](https://artsyproduct.atlassian.net/browse/FX-2858)
I'm going to have to make two more issues
* one in Metaphysics for supporting unfollows in this mutation (apparently you can *only* follow genes right now)
* and another for following up here with the ability to unfollow (which should just be a one or two line change)

feat(gene): adds gene follow button

---

src/v2/Apps/Partner/PartnerApp.tsx

This PR fixes parent child margin collapsing on the partner profile page.
JIRA - https://artsyproduct.atlassian.net/browse/PX-3984
Before: 
Now:

fix(PX-3984): parent child margin collapsing

---

src/lib/middleware/sharifyLocals.ts

This change ensures that all sharify variables including dynamic ones
are properly reflected in the serer side sharify state.

feature: Enable Sharify Locals Server Side

---

src/typings/sharify.d.ts
src/v2/Apps/Partner/Components/PartnerMeta/index.tsx
src/v2/Apps/Partner/PartnerApp.tsx
src/v2/Apps/Partner/__tests__/PartnerApp.jest.tsx
src/v2/__generated__/PartnerApp_Test_Query.graphql.ts
src/v2/__generated__/PartnerApp_partner.graphql.ts
src/v2/__generated__/PartnerMeta_partner.graphql.ts
src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts

This PR adds meta information for the partner profile page.
JIRA - https://artsyproduct.atlassian.net/browse/PX-3910

feat(PX-3910): add meta information for partner profile page

---

src/v2/Components/FollowButton/FollowGeneButton.tsx
src/v2/Components/FollowButton/__tests__/FollowGeneButton.jest.tsx

Addresses [FX-2877]
Depends on https://github.com/artsy/metaphysics/pull/3110
[FX-2877]: https://artsyproduct.atlassian.net/browse/FX-2877

feature: Support unfollows in follow gene button

---

src/v2/Apps/Order/OrderApp.tsx
src/v2/Apps/Order/__tests__/OrderApp.jest.tsx

Addresses [PURCHASE-2175]
[PURCHASE-2175]: https://artsyproduct.atlassian.net/browse/PURCHASE-2175

fix: bring back ask a question modal to BNMO checkout flow

---

src/v2/Utils/__tests__/resized.jest.ts
src/v2/Utils/__tests__/resizer.jest.ts
src/v2/Utils/resizer.ts

Use the cloudfront url from the application configuration.

feature: Cloudfront URL

---

src/v2/Apps/Partner/Routes/Works/index.tsx
src/v2/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
src/v2/Components/v2/ArtworkFilter/index.tsx

JIRA
[fix the scrolling after pagination click](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-3991&quickFilter=228)

fix: add offset props to set an offset

---

src/v2/Apps/Components/AppShell.tsx

@damassi — thanks for pointing me in the right direction with this one.

fix(theme): waits for route to complete before changing out theme

---

src/v2/Apps/Partner/Routes/Overview/index.tsx
src/v2/Apps/Partner/partnerRoutes.tsx
src/v2/__generated__/partnerRoutes_ArticlesQuery.graphql.ts

JIRA
- [hide the articles rail on the overview tab if there are no articles. Redirect form the articles tab to overview if no articles.](https://artsyproduct.atlassian.net/browse/PX-4000)

fix: no articles redirect; no articles hide rail

---

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
src/v2/Apps/Partner/Components/PartnerShows/ShowPaginatedEvents.tsx
src/v2/Apps/Partner/Routes/Articles/index.tsx
src/v2/Apps/Partner/Routes/Shows/index.tsx
src/v2/Apps/Partner/Routes/Works/index.tsx
src/v2/Apps/Partner/partnerRoutes.tsx
src/v2/__generated__/Articles_partner.graphql.ts
src/v2/__generated__/NavigationTabs_Test_PartnerQuery.graphql.ts
src/v2/__generated__/NavigationTabs_partner.graphql.ts
src/v2/__generated__/PartnerApp_Test_Query.graphql.ts
src/v2/__generated__/ShowPaginatedEventsRendererQuery.graphql.ts
src/v2/__generated__/ShowPaginatedEvents_partner.graphql.ts
src/v2/__generated__/partnerRoutes_ArticlesQuery.graphql.ts
src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts

-JIRA [fix pagination on reload](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4035&quickFilter=228)
added property page for articles/shows connection
added functionality for artwork filter for url params filter and page work

fix:save pagination on reload

---

src/v2/Apps/Partner/Components/Overview/ArticlesRail.tsx
src/v2/Apps/Partner/Components/Overview/ArtistsRail.tsx
src/v2/Apps/Partner/Components/Overview/ArtworkRailPlaceholder.tsx
src/v2/Apps/Partner/Components/Overview/ArtworksRail.tsx
src/v2/Apps/Partner/Components/Overview/ShowsRail.tsx
src/v2/Apps/Partner/Components/Overview/ViewAllButton.tsx
src/v2/Apps/Partner/Routes/Overview/index.tsx
src/v2/Components/Artwork/Details.tsx
src/v2/Components/__tests__/__snapshots__/Artwork.jest.tsx.snap
src/v2/__generated__/ArtworksRailRendererQuery.graphql.ts
src/v2/__generated__/ArtworksRail_partner.graphql.ts
src/v2/__generated__/Overview_partner.graphql.ts
src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts

This PR adds a banner with the last updated artworks. 
JIRA - https://artsyproduct.atlassian.net/browse/PX-4017, https://artsyproduct.atlassian.net/browse/PX-4018

feat(PX-4017): banner with last updated artworks

---

src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx

First round of QA Fixes:
1. Adds links to the Zendesk support page 
2. Fixes mis-alignment in artwork images
https://artsyproduct.atlassian.net/browse/PURCHASE-2623

fix: Buyer guarantee qa fixes #1

---

package.json
src/v2/Apps/Auctions/AuctionsApp.tsx
src/v2/Apps/Auctions/Components/AuctionArtworksRail/AuctionArtworksRail.tsx
src/v2/Apps/Auctions/Components/AuctionArtworksRail/AuctionArtworksRailArtworks.tsx
src/v2/Apps/Auctions/Components/AuctionArtworksRail/__tests__/AuctionArtworksRailArtworks.jest.tsx
src/v2/Apps/Auctions/Components/AuctionArtworksRailPlaceholder.tsx
src/v2/Apps/Auctions/Components/MyBids/MyBids.tsx
src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/WorksByArtistsYouFollowRail.tsx
src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/__tests__/WorksByArtistsYouFollowRail.jest.tsx
src/v2/Apps/Auctions/Routes/CurrentAuctions.tsx
src/v2/Apps/Auctions/Routes/PastAuctions.tsx
src/v2/Apps/Auctions/Routes/UpcomingAuctions.tsx
src/v2/Apps/Auctions/Utils/auctionsHelpers.tsx
src/v2/Apps/Auctions/auctionsRoutes.tsx
src/v2/Components/Artwork/Details.tsx
src/v2/Components/Artwork/Metadata.tsx
src/v2/Components/Artwork/ShelfArtwork.tsx
src/v2/Components/ChevronButton.tsx
src/v2/Components/__tests__/__snapshots__/Artwork.jest.tsx.snap
src/v2/Utils/Hooks/useLazyLoadComponent.tsx
src/v2/Utils/logger.ts
src/v2/__generated__/AuctionArtworksRailArtworksQuery.graphql.ts
src/v2/__generated__/AuctionArtworksRailArtworks_Test_Query.graphql.ts
src/v2/__generated__/AuctionArtworksRailArtworks_sale.graphql.ts
src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
src/v2/__generated__/ShelfArtwork_artwork.graphql.ts
src/v2/__generated__/WorksByArtistsYouFollowRail_Test_Query.graphql.ts
src/v2/__generated__/WorksByArtistsYouFollowRail_viewer.graphql.ts
src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
yarn.lock

Addresses https://artsyproduct.atlassian.net/browse/DSWGW-41 
This migrates our new v2 /auctions page to Palette v3.

feat: Migrate /auctions app to Palette v3 

---

src/v2/Apps/Partner/Components/Overview/ArticlesRail.tsx
src/v2/Apps/Partner/Components/PartnerArticles/ArticleCard.tsx
src/v2/Apps/Partner/Routes/Overview/index.tsx
src/v2/__generated__/ArticleCard_article.graphql.ts
src/v2/__generated__/ArticlesQuery.graphql.ts
src/v2/__generated__/Overview_partner.graphql.ts
src/v2/__generated__/partnerRoutes_ArticlesQuery.graphql.ts
src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts

JIRA - > [Add 'See all articles' card to the Articles carousel](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4045&quickFilter=228)

fix: change articles carousel

---

src/v2/Apps/Gene/Components/GeneMeta.tsx
src/v2/__generated__/GeneMeta_gene.graphql.ts
src/v2/__generated__/GeneShow_Test_Query.graphql.ts
src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts

Minor thing — this field will strip out the Markdown formatting.

fix(gene): uses meta#description

---

src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
src/v2/Apps/BuyerGuarantee/Routes/__tests__/BuyerGuaranteeIndex.jest.tsx

More QA fixes for the Buyer Guarantee page
https://artsyproduct.atlassian.net/browse/PURCHASE-2659
https://artsyproduct.atlassian.net/browse/PURCHASE-2660

chore: updates page's icon styling

---

src/v2/Apps/Collect/Routes/Collect/index.tsx
src/v2/Apps/Collect/collectRoutes.tsx

Addresses https://artsyproduct.atlassian.net/browse/DSWGW-50 
Migrates /collect to Palette v3

refactor: [Collect] Migrate /collect

---

src/v2/Apps/Partner/Components/Overview/ShowBannersRail.tsx
src/v2/Apps/Partner/Components/Overview/ShowBannersRailPlaceholder.tsx
src/v2/Apps/Partner/Components/PartnerShows/ShowBanner.tsx
src/v2/Apps/Partner/Components/__tests__/PartnerShows/ShowBanner.jest.tsx
src/v2/Apps/Partner/Routes/Overview/index.tsx
src/v2/__generated__/ShowBannersRailRendererQuery.graphql.ts
src/v2/__generated__/ShowBannersRail_partner.graphql.ts

This PR adds a banner with shows for the overview page.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4016
Desktop:
Mobile:

feat (PX-4016): banner with shows

---

src/v2/Apps/Auctions/AuctionsApp.tsx
src/v2/Apps/Auctions/Components/AuctionArtworksRail/AuctionArtworksRailArtworks.tsx
src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail/WorksByArtistsYouFollowRail.tsx
src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
src/v2/Apps/Fair/Components/FairExhibitorRail/FairExhibitorRail.tsx
src/v2/Apps/Fair/Components/FairExhibitorRail/FairExhibitorRailArtworks.tsx
src/v2/Apps/Fair/Components/FairExhibitorRail/FairExhibitorRailPlaceholder.tsx
src/v2/Apps/Fair/Components/FairFollowedArtists.tsx
src/v2/Apps/Fair/Components/FairHeader/FairHeader.tsx
src/v2/Apps/Fair/Components/FairHeader/FairTiming.tsx
src/v2/Apps/Fair/FairApp.tsx
src/v2/Apps/Fair/FairSubApp.tsx
src/v2/Apps/Fair/Routes/FairArticles.tsx
src/v2/Apps/Fair/Routes/FairArtworks.tsx
src/v2/Apps/Fair/Routes/FairExhibitors.tsx
src/v2/Apps/Fair/Routes/FairInfo.tsx
src/v2/Apps/Fair/fairRoutes.tsx
src/v2/Components/Artwork/ShelfArtwork.tsx
src/v2/__generated__/FairExhibitorRailArtworksQuery.graphql.ts
src/v2/__generated__/FairExhibitorRailArtworks_show.graphql.ts

Addresses https://artsyproduct.atlassian.net/browse/DSWGW-52 
Migrates fair pages to Palette v3.

refactor: [Fair] migrate to Palette v3

---

src/v2/Apps/Order/OrderApp.tsx

Fixes a max-width issue on the order app. We'll revisit when we convert OrderApp to palette v3.

fix: Fix max-width on OrderApp

---

src/v2/Apps/Gene/Routes/GeneShow.tsx
src/v2/Apps/Show/Components/ShowAbout.tsx
src/v2/Apps/Show/Components/ShowArtworks.tsx
src/v2/Apps/Show/Components/ShowContextCard.tsx
src/v2/Apps/Show/Components/ShowContextualLink.tsx
src/v2/Apps/Show/Components/ShowHeader.tsx
src/v2/Apps/Show/Components/ShowInstallShots.tsx
src/v2/Apps/Show/Routes/ShowInfo.tsx
src/v2/Apps/Show/ShowApp.tsx
src/v2/Apps/Show/ShowSubApp.tsx
src/v2/Apps/Show/__tests__/ShowContextualLink.jest.tsx
src/v2/Apps/Show/__tests__/ShowInstallShots.jest.tsx
src/v2/Apps/Show/showRoutes.tsx
src/v2/__generated__/ShowApp_Test_Query.graphql.ts
src/v2/__generated__/ShowApp_show.graphql.ts
src/v2/__generated__/ShowHeader_show.graphql.ts
src/v2/__generated__/ShowInstallShots_Test_Query.graphql.ts
src/v2/__generated__/ShowInstallShots_show.graphql.ts
src/v2/__generated__/showRoutes_ShowQuery.graphql.ts
tsconfig.json

Addresses https://artsyproduct.atlassian.net/browse/DSWGW-53 
This migrates the show page from palette 2 to palette 3:

refactor: [Show] migrate to Palette 3

---

cypress.json

We're already on 5, so lets bump retries up a bit.

smoke-tests: Bump retries to 5

---

src/v2/Apps/Artists/Components/ArtistsArtistCard.tsx
src/v2/Apps/Artists/Components/ArtistsCarouselCell.tsx
src/v2/Apps/Artists/Components/ArtistsLetterNav.tsx
src/v2/Apps/Artists/Components/ArtistsTopNav.tsx
src/v2/Apps/Artists/Routes/ArtistsByLetter.tsx
src/v2/Apps/Artists/Routes/ArtistsIndex.tsx
src/v2/Apps/Artists/__tests__/ArtistsByLetter.jest.tsx
src/v2/Apps/Artists/artistsRoutes.tsx
src/v2/__generated__/ArtistsArtistCard_Test_Query.graphql.ts
src/v2/__generated__/ArtistsArtistCard_artist.graphql.ts
src/v2/__generated__/ArtistsCarouselCell_featuredLink.graphql.ts
src/v2/__generated__/ArtistsIndexFragmentContainer_Test_Query.graphql.ts
src/v2/__generated__/ArtistsIndex_featuredGenes.graphql.ts
src/v2/__generated__/artistsRoutes_ArtistsQuery.graphql.ts

https://user-images.githubusercontent.com/112297/118045179-993d9f80-b345-11eb-8570-21da118f5740.mov

feat: converts /artists & /artists/:letter to v3

---

src/v2/Apps/Fair/Components/FairEditorial/FairEditorial.tsx
src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
src/v2/Apps/Fair/Components/FairExhibitorRail/FairExhibitorRail.tsx
src/v2/Apps/Fair/Components/FairFollowedArtists.tsx
src/v2/Apps/Fair/Components/FairHeader/FairHeaderImage.tsx
src/v2/Apps/Fair/FairApp.tsx
src/v2/Apps/Partner/Components/PartnerHeader/PartnerHeaderImage.tsx
src/v2/Components/FullBleedHeader.tsx
src/v2/__generated__/FairApp_Test_Query.graphql.ts
src/v2/__generated__/FairHeaderImage_fair.graphql.ts
src/v2/__generated__/FairHeader_Test_Query.graphql.ts
src/v2/__generated__/PartnerApp_Test_Query.graphql.ts
src/v2/__generated__/PartnerHeaderImage_profile.graphql.ts
src/v2/__generated__/fairRoutes_FairQuery.graphql.ts
src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts

Closes [DSWGW-57](https://artsyproduct.atlassian.net/browse/DSWGW-57)

Replaces full bleed headers with common implementation

---

src/v2/Apps/Partner/PartnerApp.tsx
src/v2/Apps/Partner/Routes/Overview/index.tsx
src/v2/Apps/Partner/__tests__/PartnerApp.jest.tsx
src/v2/Apps/Partner/partnerRoutes.tsx
src/v2/__generated__/Overview_partner.graphql.ts
src/v2/__generated__/PartnerApp_Test_Query.graphql.ts
src/v2/__generated__/PartnerApp_partner.graphql.ts
src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts
src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts

**Do not merge this PR until graphQL schema will be updated.**
This PR adds support of non-subscriber partners. 
JIRA - https://artsyproduct.atlassian.net/browse/PX-4044

feat(PX-4044): non subscribers page

---

src/v2/Apps/Partner/PartnerApp.tsx

Removed AppContainer and HorizontalPadding from the partner app component.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4080

fix(PX-4080): remove AppContainer and HorizontalPadding from partner app component

---

src/v2/Apps/Fair/Components/FairHeader/FairHeaderIcon.tsx
src/v2/Apps/Show/Components/ShowContextualLink.tsx
src/v2/Apps/Show/Components/ShowHeader.tsx
src/v2/Apps/Show/ShowApp.tsx
src/v2/__generated__/FairApp_Test_Query.graphql.ts
src/v2/__generated__/FairHeaderIcon_fair.graphql.ts
src/v2/__generated__/FairHeader_Test_Query.graphql.ts
src/v2/__generated__/fairRoutes_FairQuery.graphql.ts

This addresses a few qa items caught during page roll outs: 
- [Show - Mobile] Reduce margin-bottom on carousel to 40px - https://artsyproduct.atlassian.net/browse/DSWGW-60
- [Show - Mobile] "Presented by _____" text should be left-aligned not centered - https://artsyproduct.atlassian.net/browse/DSWGW-61
- [Show - Mobile] Add 10px margin-top to "Presented by _____" text - https://artsyproduct.atlassian.net/browse/DSWGW-62
- [Show - Mobile] Reduce 'spacer' above artwork grid to 60px (from 120px) - https://artsyproduct.atlassian.net/browse/DSWGW-63
- [Fair - Mobile] Reduce profile image from 100x100px to 60x60px - https://artsyproduct.atlassian.net/browse/DSWGW-64

qa: [Palette v3 Migration] Address misc qa

---

src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx

This PR introduces UI fixes from the QA of the Buyer Guarantee Page:
- [Copy updates](https://artsyproduct.atlassian.net/browse/PURCHASE-2666)
- [Increase chevron size](https://artsyproduct.atlassian.net/browse/PURCHASE-2644)
- [Reduce spacing between icons on mWeb](https://artsyproduct.atlassian.net/browse/PURCHASE-2647)
- [Add chevrons to icons on mWeb](https://artsyproduct.atlassian.net/browse/PURCHASE-2648)
- [Fully extend grey background on table on mWeb](https://artsyproduct.atlassian.net/browse/PURCHASE-2650)
- [Add header title to mWeb table](https://artsyproduct.atlassian.net/browse/PURCHASE-2655)
- [Add meta for SEO](https://artsyproduct.atlassian.net/browse/PURCHASE-2656)
- [Fix image resizing via aspect ratio](https://artsyproduct.atlassian.net/browse/PURCHASE-2640) *Thank you …

More Buyer guarantee page QA fixes

---

src/v2/Apps/Auctions/AuctionsApp.tsx

Palette 3 qa: Noticed the size was a bit off compared to other pages.

fix: [Auctions] Fix header size -> xxl to xl

---

src/v2/Apps/Collect/Routes/Collection/Components/Header/DefaultHeader.tsx
src/v2/Apps/Collect/Routes/Collection/Components/Header/DefaultHeaderArtwork.tsx
src/v2/Apps/Collect/Routes/Collection/Components/Header/index.tsx
src/v2/Apps/Collect/Routes/Collection/index.tsx

Minor alignment update and removal of ts-ignores for good measure.

fix(collection): vertically aligns follow buttons; null check removals

---

src/v2/Apps/Components/AppContainer.tsx
src/v2/Apps/Components/AppShell.tsx
src/v2/Apps/Components/HorizontalPadding.tsx

I think there was a ticket associated with this but I can't find it now.

fix: implements sticky footer

---

src/v2/Components/FollowButton/FollowArtistButton.tsx

This fixes a few errors that integrity has been seeing.

fix: Fix integrity tests 

---

src/v2/Apps/Auctions/Routes/UpcomingAuctions.tsx
src/v2/__generated__/UpcomingAuctionsQuery.graphql.ts
src/v2/__generated__/UpcomingAuctions_Test_Query.graphql.ts
src/v2/__generated__/UpcomingAuctions_viewer.graphql.ts
src/v2/__generated__/auctionsRoutes_Upcoming_AuctionsQuery.graphql.ts

Creating a draft PR as there is no upcoming auctions to test the change.

fix: Changed sorting from timely_at_name to start_at

---

src/v2/Apps/Artist/Components/__tests__/ArtistHeader.jest.tsx
src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarArtists.jest.tsx
src/v2/Apps/Artwork/Components/__tests__/ArtistInfo.jest.tsx
src/v2/Components/__tests__/ArtistCard.jest.tsx

fix: fixes spec

---

src/v2/Apps/Gene/Components/GeneMeta.tsx

This fixes https://artsyproduct.atlassian.net/browse/GRO-332

fix: Deleted extra slash in href string

---

src/v2/Apps/Auctions/Components/AuctionsMeta.tsx

https://artsyproduct.atlassian.net/browse/GRO-322
**Before**
**After**

feat: Updated auctions page title

---

docs/migrating_app_palette_v3.md

Addresses https://artsyproduct.atlassian.net/browse/WP-42
This adds some documentation around how to use our new Palette v3 interfaces.

docs: Add Palette v3 use docs

---

src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx

Links to the following tickets:
https://artsyproduct.atlassian.net/browse/PURCHASE-2674
https://artsyproduct.atlassian.net/browse/PURCHASE-2641
https://artsyproduct.atlassian.net/browse/PURCHASE-2641
https://artsyproduct.atlassian.net/browse/PURCHASE-2677
After:
Before:

fix: fixes table spacing and layout on buyer guarantee page

---

src/v2/Apps/Auctions/Components/AuctionsMeta.tsx

Looks like we were missing an s

fix: Fix /auctions title plural

---

src/v2/Apps/ViewingRoom/Components/ViewingRoomMeta.tsx
src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx
src/v2/__generated__/ViewingRoomApp_ClosedTest_Query.graphql.ts
src/v2/__generated__/ViewingRoomApp_DraftTest_Query.graphql.ts
src/v2/__generated__/ViewingRoomApp_LoggedOutTest_Query.graphql.ts
src/v2/__generated__/ViewingRoomApp_OpenTest_Query.graphql.ts
src/v2/__generated__/ViewingRoomApp_ScheduledTest_Query.graphql.ts
src/v2/__generated__/ViewingRoomApp_UnfoundTest_Query.graphql.ts
src/v2/__generated__/ViewingRoomMeta_viewingRoom.graphql.ts
src/v2/__generated__/viewingRoomRoutes_ViewingRoomQuery.graphql.ts

Adds image/description/etc meta tags for social sharing.

fix(viewing-room): fleshes out meta tags for social share

---

Dockerfile
package.json
src/lib/asyncLocalWrapper/browser.ts
src/lib/asyncLocalWrapper/index.ts
src/lib/asyncLocalWrapper/server.ts
src/lib/middleware/__tests__/bootstrapSharifyAndContextLocalsMiddleware.jest.ts
src/lib/middleware/asyncLocalMiddleware.ts
src/lib/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts
src/middleware.ts
src/v2/Components/Authentication/FormSwitcher.tsx
src/v2/Utils/getENV.tsx
src/v2/Utils/resized.ts
webpack/envs/commonEnv.js
yarn.lock

Leverages the node api `AsyncLocalStorage` to provide safe access to
shared context across async requests.
https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage

feature: Async Locals

---

src/v2/Components/Sticky/Sticky.tsx
src/v2/Components/Sticky/StickyProvider.tsx

Closes: [PX-3991](https://artsyproduct.atlassian.net/browse/PX-3991)

fix(stickies): remove stickies from context on teardown

---

src/v2/Apps/Partner/Components/Overview/NearbyGalleriesRail.tsx
src/v2/Apps/Partner/Components/Overview/NearbyGalleriesRailPlaceholder.tsx
src/v2/Apps/Partner/Components/Overview/NearbyGalleryCard.tsx
src/v2/Apps/Partner/Components/__tests__/Overview/NearbyGalleryCard.jest.tsx
src/v2/Apps/Partner/Routes/Overview/index.tsx
src/v2/__generated__/NearbyGalleriesRailRendererQuery.graphql.ts
src/v2/__generated__/NearbyGalleriesRail_partners.graphql.ts
src/v2/__generated__/NearbyGalleryCard_Test_Query.graphql.ts
src/v2/__generated__/NearbyGalleryCard_partner.graphql.ts
src/v2/__generated__/Overview_partner.graphql.ts
src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts

This PR adds nearby galleries rail.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4027, https://artsyproduct.atlassian.net/browse/PX-4026

feat(PX-4027): add nearby galleries rail

---

src/desktop/apps/about/stylesheets/index.styl

https://artsyproduct.atlassian.net/browse/GRO-330
**Before**
**After**

fix: width made dynamic

---

src/desktop/apps/consign/components/create_account/__tests__/CreateAccount.jest.tsx
src/lib/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts
src/typings/sharify.d.ts
src/v2/Components/Authentication/Desktop/SignUpForm.tsx
src/v2/Components/Authentication/EmailSubscriptionCheckbox.tsx
src/v2/Components/Authentication/FormSwitcher.tsx
src/v2/Components/Authentication/TermsOfServiceCheckbox.tsx
src/v2/Components/Authentication/__tests__/Desktop/SignUpForm.jest.tsx
src/v2/Components/Authentication/__tests__/FormSwitcher.jest.tsx
src/v2/__generated__/SignUpFormLocationQuery.graphql.ts
src/v2/__generated__/SignUpFormLocation_tests_Query.graphql.ts
src/v2/__generated__/SignUpForm_requestLocation.graphql.ts

This is to complete the work associated with the ask from Legal that required an auto-enrollment in Email Subscriptions during onboarding sign up for US users only.
We updated Metaphysics to supply us with country code based on IP address of the users during sign up, and altered the `SignUpForm` to display these conditional checkboxes.
GDPR Country Experience:
USA Experience:

GRO-336: Implement IP address tracking solution in Force 

---

src/v2/Apps/BuyerGuarantee/Components/BuyerGuaranteeMeta.tsx
src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx

https://artsyproduct.atlassian.net/browse/PURCHASE-2656

chore: adds Buyer Guarantee seo meta tags 

---

.storybook/main.js

Addresses https://artsyproduct.atlassian.net/browse/WP-45 
See [this issue](https://github.com/styleguidist/react-docgen-typescript/issues/356) for more info.

fix: [Storybooks] Fix deploy issue due to ts 4.3.x incompatibility 

---

src/desktop/apps/about/stylesheets/index.styl

https://artsyproduct.atlassian.net/browse/GRO-330
Before
After

Fixed CSS selector to more specific

---

src/v2/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
src/v2/Apps/Consign/Routes/MarketingLanding/__tests__/ConsignApp.jest.tsx

Addresses https://artsyproduct.atlassian.net/browse/GRO-358
Removes duplicate footer on /consign app.

fix: Remove duplicate footer on /consign

---

src/v2/Apps/Partner/Components/PartnerHeader/index.tsx
src/v2/Apps/Partner/Components/__tests__/PartnerHeader.jest.tsx
src/v2/__generated__/PartnerApp_Test_Query.graphql.ts
src/v2/__generated__/PartnerHeader_Test_Query.graphql.ts
src/v2/__generated__/PartnerHeader_partner.graphql.ts
src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts

This PR fixes overview tab selection when the user clicks on the partner name.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4142
Before 
Now

fix(PX-4142): overview tab is not selected

---

src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistList.tsx

JIRA - https://artsyproduct.atlassian.net/browse/PX-4171
Before
Now

fix(PX-417): show part of 3rd column for the artist list on mobile

---

src/v2/Components/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
src/v2/Components/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx

https://artsyproduct.atlassian.net/browse/FX-2840

feat: Disabled 'Apply' button when there is no selected filters

---

src/v2/Apps/Partner/Components/Overview/ArtistsRail.tsx
src/v2/Apps/Partner/Components/__tests__/Overview/ArtistsRail.jest.tsx
src/v2/Apps/Partner/Routes/Overview/index.tsx
src/v2/__generated__/ArtistsRail_Test_Query.graphql.ts
src/v2/__generated__/ArtistsRail_partner.graphql.ts
src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts

This PR fixes artist rail without artists.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4144
Before 
Now

fix(PX-4144): Remove artist rail if no artists

---

src/v2/Apps/Partner/PartnerApp.tsx
src/v2/Apps/Partner/Routes/Artists/ArtistsRoute.tsx
src/v2/Apps/Partner/Utils/PartnerArtistsLoadingContext.tsx

This PR fixes scroll to the artist on mobile devices.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4167
Before
Now

fix(PX-4167): scroll to artist on mobile

---

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
src/v2/Apps/Partner/Components/Overview/ArticlesRail.tsx
src/v2/Apps/Partner/Components/Overview/ArtistsRail.tsx
src/v2/Apps/Partner/Components/Overview/ArtworksRail.tsx
src/v2/Apps/Partner/Components/Overview/NearbyGalleryCard.tsx
src/v2/Apps/Partner/Components/Overview/ShowsRail.tsx
src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistItem.tsx
src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarousel.tsx
src/v2/Apps/Partner/Components/PartnerHeader/index.tsx
src/v2/Apps/Partner/Components/PartnerMeta/index.tsx
src/v2/Apps/Partner/Components/__tests__/PartnerHeader.jest.tsx
src/v2/Apps/Partner/partnerRoutes.tsx

We split the partner2 -> partner into 6 steps to make a migration smoothly.
You can see these steps in [the PR with our routes migration plan](https://github.com/artsy/force/pull/7611)
This PR is a first step of migration

feat: partner2 -> partner transition (replace partner2 with partner)

---

src/desktop/lib/webpackPublicPath.ts

This PR should fix CDN problem that we have on the partner page at staging now.

fix: partner profile page CDN problems

---

src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx

Remove  auth modal window in the Viewing room

fix:Remove login/signup gate on viewing rooms

---

src/v2/Components/DownloadAppBadge.tsx
src/v2/Components/Footer/Footer.tsx
src/v2/Components/Footer/FooterDownloadAppBanner.tsx
src/v2/Components/Footer/__tests__/Footer.jest.tsx
src/v2/Utils/getRandom.ts

https://artsyproduct.atlassian.net/browse/GRO-342
**_Desktop_**
**Before**
**After**
**_Mobile_**
**Before**
**After**

feat: App download banner

---

src/v2/Apps/Artist2/Routes/Overview/ArtistOverviewRoute.tsx
src/v2/Apps/Artist2/Routes/Overview/Components/Artist2CareerHighlights.tsx
src/v2/Apps/Artist2/Routes/Overview/Components/IconicCollectionsRail/Artist2IconicCollectionsRail.tsx
src/v2/Apps/Artist2/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
src/v2/Components/ArtistSeriesRail/ArtistSeriesRail.tsx

Fixes up a couple spacing issues seen before we QA

fix: [Artist2] Light qa

---

src/desktop/lib/webpackPublicPath.ts
src/v2/routes.tsx
src/v2/server.ts
webpack/envs/clientDevelopmentConfig.js
webpack/envs/clientProductionConfig.js
webpack/envs/legacyCommonConfig.js
webpack/envs/legacyProductionConfig.js

Remove the temporary directory for storing `novo` assets.

feature: Remove `assets-novo`

---

src/v2/Apps/Order/Routes/Offer/index.tsx

Tiny copy change to offer page as requested by legal. The force portion of this [ticket](https://artsyproduct.atlassian.net/browse/PURCHASE-2663)

Make offer copy addition

---

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
src/v2/Apps/Partner/Routes/Shows/index.tsx
src/v2/Apps/Partner/partnerRoutes.tsx
src/v2/__generated__/NavigationTabs_Test_PartnerQuery.graphql.ts
src/v2/__generated__/NavigationTabs_partner.graphql.ts
src/v2/__generated__/PartnerApp_Test_Query.graphql.ts
src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts
src/v2/__generated__/partnerRoutes_ShowsQuery.graphql.ts

JIRA -> [PPP: redundant "Shows" tab is displayed and leads to 500 error for some partners](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=PX&modal=detail&selectedIssue=PX-4190&quickFilter=228)
-removed shows tab from PPP if no shows

fix: remove shows tab when no shows

---

src/v2/Components/RouteTabs.tsx
src/v2/Components/UserSettings/UserSettingsTabs.tsx

fix(settings): temporarily disables tracking on route tabs

---

src/desktop/components/fair_layout/templates/index.jade
src/desktop/components/main_layout/templates/blank.jade
src/desktop/components/main_layout/templates/index.jade
src/desktop/components/main_layout/templates/minimal_header.jade
src/desktop/components/main_layout/templates/redesign.jade
src/desktop/components/main_layout/templates/scripts.jade
src/desktop/components/main_layout/test/templates.test.js
src/mobile/components/layout/templates/scaffold.jade
webpack/envs/legacyCommonConfig.js
webpack/envs/legacyProductionConfig.js
webpack/utils/getEntrypoints.js

During the recent asset renaming logacy development mode broke due to
how asset lookup is configured.

fix: Legacy Dev Mode

---

src/v2/Apps/Artist/artistRoutes.tsx
src/v2/Apps/Example/exampleRoutes.tsx
src/v2/Apps/Show/showRoutes.tsx
src/v2/Apps/Tag/tagRoutes.tsx
webpack/envs/clientCommonConfig.js

This change increases the minimum size required for a new chunk to be
created thus reducing the overall number of chunks that are generated.
The main benefit of this change will be a reduction of time spent waiting to
establish connections with CloudFront.
125 chunks -> 75 chunks

feature: Reduce Chunk Count

---

src/v2/Apps/Artist/ArtistApp.tsx
src/v2/Apps/Artist/Components/ArtistHeader.tsx
src/v2/Apps/Artist/Components/FollowArtist2Button.tsx
src/v2/Apps/Artist/Routes/Overview/Components/ArtistRelatedArtistsRail.tsx
src/v2/Apps/Artist/Routes/Overview/Components/ArtistWorksForSaleRail.tsx

This PR fixes some test failures over in integrity post artist page rebuild.

fix: Update tests for new Artist page

---

src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
src/v2/Apps/Artist/Routes/AuctionResults/__tests__/SizeFilter.jest.tsx
src/v2/Apps/Fair/Routes/__tests__/FairArtworks.jest.tsx
src/v2/Apps/Show/__tests__/ShowArtworks.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/FilterExpandable.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtistNationalityFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtistsFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ArtworkLocationFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/AttributionClassFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/FilterExpandable.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/MaterialsTermFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/MediumFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/PartnersFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ResultsFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/SizeFilter2.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/WaysToBuyFilter.jest.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/helpers.ts
src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/useScrollContext.tsx
src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
src/v2/Components/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.jest.tsx
src/v2/Components/ArtworkFilter/__tests__/NewArtworkFilterMobileActionSheet.jest.tsx
src/v2/Components/ArtworkFilter/index.tsx

…k height for calculating scrolling offset
https://artsyproduct.atlassian.net/browse/FX-2832
**Before**
**After**

feat(mWeb): scroll filters into view when expanded

---

src/desktop/apps/article/__tests__/helpers.jest.tsx
src/desktop/apps/article/__tests__/routes.jest.ts
src/desktop/apps/article/components/App.tsx
src/desktop/apps/article/components/InfiniteScrollArticle.tsx
src/desktop/apps/article/components/InfiniteScrollNewsArticle.tsx
src/desktop/apps/article/components/NewsArticle.tsx
src/desktop/apps/article/components/layouts/Article.tsx
src/desktop/apps/article/components/layouts/Classic.tsx
src/desktop/apps/article/helpers.tsx
src/desktop/apps/article/routes.tsx

Addresses [CX-1568](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=77&modal=detail&selectedIssue=CX-1568) and [CX-1585](https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=77&modal=detail&selectedIssue=CX-1585) and depends on https://github.com/artsy/reaction/pull/3687

feat: Remove ads and signup banner in articles for eigen

---

src/v2/Apps/Show/ShowApp.tsx
src/v2/__generated__/ShowApp_Test_Query.graphql.ts
src/v2/__generated__/ShowApp_show.graphql.ts
src/v2/__generated__/showRoutes_ShowQuery.graphql.ts

https://artsyproduct.atlassian.net/browse/FX-2535
**Before**
**After**

fix: Show fair booth when it's full featured only

---

src/v2/Components/RouteTabs.tsx
src/v2/Components/UserSettings/UserSettingsTabs.tsx

Closes [GRO-372](https://artsyproduct.atlassian.net/browse/GRO-372)

fix: restores tracking to route tabs

---

HACKS.md
README.md

Addresses RFC proposal here: https://github.com/artsy/README/issues/390

feat: Add HACKS.md file

---

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
src/v2/Apps/Partner/Components/Overview/AboutPartner.tsx
src/v2/Apps/Partner/Components/Overview/ArtistsRail.tsx
src/v2/Apps/Partner/Components/Overview/ShowsRail.tsx
src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistItem.tsx
src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistList.tsx
src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtists.tsx
src/v2/Apps/Partner/Components/__tests__/NavigationTabs.jest.tsx
src/v2/Apps/Partner/Components/__tests__/Overview/ArtistsRail.jest.tsx
src/v2/Apps/Partner/PartnerApp.tsx
src/v2/Apps/Partner/Routes/Overview/index.tsx
src/v2/Apps/Partner/__tests__/PartnerApp.jest.tsx
src/v2/Apps/Partner/partnerRoutes.tsx
src/v2/__generated__/AboutPartner_Test_Query.graphql.ts
src/v2/__generated__/AboutPartner_partner.graphql.ts
src/v2/__generated__/ArtistsRail_Test_Query.graphql.ts
src/v2/__generated__/ArtistsRail_partner.graphql.ts
src/v2/__generated__/NavigationTabs_Test_PartnerQuery.graphql.ts
src/v2/__generated__/NavigationTabs_partner.graphql.ts
src/v2/__generated__/Overview_partner.graphql.ts
src/v2/__generated__/PartnerApp_Test_Query.graphql.ts
src/v2/__generated__/PartnerApp_partner.graphql.ts
src/v2/__generated__/PartnerArtistsQuery.graphql.ts
src/v2/__generated__/PartnerArtists_partner.graphql.ts
src/v2/__generated__/ShowsRail_partner.graphql.ts
src/v2/__generated__/partnerRoutes_ArtistsQuery.graphql.ts
src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts
src/v2/__generated__/partnerRoutes_PartnerQuery.graphql.ts

This PR adds logic to display the correct partner page layout according to partner type and contract type.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4079
Gallery: Custom
Gallery: Fair
Gallery: Churned
Brand

feat(PX-4079): partner profile page states

---

src/v2/Apps/Order/Components/SavedAddressItem.tsx
src/v2/Apps/Order/Components/SavedAddresses.tsx
src/v2/Apps/Order/Components/__tests__/SavedAddresses.jest.tsx
src/v2/Apps/Order/Routes/Shipping/index.tsx
src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
src/v2/__generated__/SavedAddressesInCollectorProfile_Test_Query.graphql.ts
src/v2/__generated__/SavedAddressesOutsiseCollectorProfile_Test_Query.graphql.ts

Updated design for shipping step
JIRA: https://artsyproduct.atlassian.net/browse/PX-4132
https://user-images.githubusercontent.com/55637696/121357059-20c50100-c93a-11eb-9334-714e1f9f318e.mov

feat(PX-4132): Collector sees updated design for shipping step

---

cypress/integration/home2.spec.ts
src/v2/Apps/Home/Components/HomeHeroUnit.tsx
src/v2/Apps/Home/Components/HomeInfoBlurb.tsx
src/v2/Apps/Home/HomeApp.tsx
src/v2/Apps/Home/__tests__/HomeApp.jest.tsx
src/v2/Apps/Home/homeRoutes.tsx
src/v2/System/Router/__tests__/buildClientApp.jest.tsx
src/v2/System/Router/__tests__/buildServerApp.jest.tsx
src/v2/System/SystemContext.tsx
src/v2/System/__tests__/SystemContext.jest.tsx
src/v2/__generated__/HomeApp_Test_Query.graphql.ts
src/v2/__generated__/HomeApp_homePage.graphql.ts
src/v2/__generated__/HomeHeroUnit_heroUnit.graphql.ts
src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts
src/v2/routes.tsx

Sets up the above the fold content. I figure the remainder will be all loaded client-side.

feat(GRO-214): sets up HomeApp

---

src/lib/analytics/sentryFilters.ts

Makes our sentry url filtering more expansive by matching all subdomains.

chore: More sentry filtering

---

src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx

Updated artists filter options style to v3
Jira: [FX-3028](https://artsyproduct.atlassian.net/browse/FX-3028)
**Before**
**After**

fix: spacing between artist filter options

---

src/v2/Components/Authentication/Desktop/LoginForm.tsx

[FX-1846](https://artsyproduct.atlassian.net/browse/FX-1846)
Before
After

fix: Show spinning during redirect

---

docs/best_practices.md

chore: docs edit

---

src/v2/Components/Lightbox/Lightbox.tsx

Lazy load `openseadragon` when the image modal opened.

feature: Lazy Load Sea Dragon

---

src/v2/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
src/v2/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx

Fixes issue seen here https://artsy.slack.com/archives/C9XJKPY9W/p1623693785160500

bugfix: [Artist] Fix falsy bug in header follower count

---

package.json
src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStatsPlaceholder.tsx
src/v2/Apps/Auctions/Components/AuctionArtworksRail/__tests__/AuctionArtworksRailPlaceholder.jest.tsx
src/v2/Apps/Auctions/Components/AuctionArtworksRailPlaceholder.tsx
src/v2/Apps/Fair/Components/FairExhibitorRail/FairExhibitorRailPlaceholder.tsx
src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetailsPlaceholder.tsx
src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistListPlaceholder.tsx
yarn.lock

fix(skeleton): removes done usage

---

renovate.json

@damassi, I'm not sure that this should be you (or just be you). Force can be a little noisy sometimes. I'll leave that up to you? Feel free to update it as you like.

Remove me as renovate assignee

---

src/v2/Apps/Home/Components/HomeFeaturedCategoriesRail.tsx
src/v2/Apps/Home/Components/HomeFeaturedShows.tsx
src/v2/Apps/Home/HomeApp.tsx
src/v2/Apps/Home/__tests__/HomeFeaturedShows.jest.tsx
src/v2/__generated__/HomeFeaturedShowsQuery.graphql.ts
src/v2/__generated__/HomeFeaturedShows_Test_Query.graphql.ts
src/v2/__generated__/HomeFeaturedShows_orderedSet.graphql.ts

Simple enough. Next up featured articles.

feat(GRO-214): adds featured shows grid

---

src/v2/Apps/Home/Components/HomeFeaturedArticles.tsx
src/v2/Apps/Home/Components/HomeFeaturedCategoriesRail.tsx
src/v2/Apps/Home/HomeApp.tsx
src/v2/Apps/Home/__tests__/HomeFeaturedArticles.jest.tsx
src/v2/__generated__/HomeFeaturedArticlesQuery.graphql.ts
src/v2/__generated__/HomeFeaturedArticles_Test_Query.graphql.ts
src/v2/__generated__/HomeFeaturedArticles_articles.graphql.ts

Simple enough, however we don't yet expose the `featured` flag on the articles field in Metaphysics — we'll have to follow up with that.

feat(GRO-214): adds featured articles rail

---

src/v2/Apps/Home/Components/HomeArtworkModuleContext.tsx
src/v2/Apps/Home/Components/HomeArtworkModuleRail.tsx
src/v2/Apps/Home/Components/HomeFeaturedEventsRail.tsx
src/v2/Apps/Home/HomeApp.tsx
src/v2/Apps/Home/__tests__/HomeApp.jest.tsx
src/v2/Apps/Home/homeRoutes.tsx
src/v2/Components/Artwork/ShelfArtwork.tsx
src/v2/__generated__/HomeApp_Test_Query.graphql.ts
src/v2/__generated__/HomeApp_orderedSet.graphql.ts
src/v2/__generated__/HomeArtworkModuleContext_Test_Query.graphql.ts
src/v2/__generated__/HomeArtworkModuleContext_context.graphql.ts
src/v2/__generated__/HomeArtworkModuleRailQuery.graphql.ts
src/v2/__generated__/HomeFeaturedEventsRail_orderedSet.graphql.ts
src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts

Gets the rest of the rails in. I had some faulty assumptions about them, the only weird one is active bids, which we'll replace with the MyBids implementation next.

feat(GRO-214): remaining rails

---

src/lib/analytics/sentryFilters.ts

Adds `gpt/pubads_impl` to sentry ignore errors array.

sentry: Add to ignoreErrors

---

src/v2/Apps/Fair/Components/FairEditorial/FairEditorial.tsx
src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
src/v2/Apps/Fair/Components/__tests__/FairEditorialItem.jest.tsx
src/v2/Apps/Fair/FairApp.tsx
src/v2/__generated__/FairApp_Test_Query.graphql.ts
src/v2/__generated__/FairEditorialItem_Test_Query.graphql.ts
src/v2/__generated__/FairEditorialItem_article.graphql.ts
src/v2/__generated__/fairRoutes_FairQuery.graphql.ts

[FX-2939]
**Before**
**After**
[FX-2939]: https://artsyproduct.atlassian.net/browse/FX-2939

feat: Rearrange modules on fairs page

---

src/v2/Apps/Home/Components/HomeFeaturedShow.tsx
src/v2/Apps/Home/Components/HomeFeaturedShows.tsx
src/v2/Apps/Home/__tests__/HomeFeaturedShows.jest.tsx
src/v2/__generated__/HomeFeaturedShow_show.graphql.ts
src/v2/__generated__/HomeFeaturedShowsQuery.graphql.ts
src/v2/__generated__/HomeFeaturedShows_Test_Query.graphql.ts
src/v2/__generated__/HomeFeaturedShows_orderedSet.graphql.ts

Closes [GRO-401](https://artsyproduct.atlassian.net/browse/GRO-401)

feat(home): improves show event time display

---

src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx

Closes: [GRO-402](https://artsyproduct.atlassian.net/browse/GRO-402)

feat(home): preloads initial hero unit image

---

src/v2/Apps/Partner/partnerRoutes.tsx
src/v2/System/Router/Route.tsx
src/v2/System/Router/Utils/shouldUpdateScroll.tsx

This PR fixes scroll behavior on the partner profile page
JIRA - https://artsyproduct.atlassian.net/browse/PX-4273
Before
Now

fix(PX-4273): partner profile page scrollbar position

---

src/v2/Apps/Home/Components/HomeArtworkModuleContext.tsx

fix(GRO-398): fixes header variant

---

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
src/v2/Apps/Partner/Components/__tests__/NavigationTabs.jest.tsx

This PR renames **Shows** tab to **Events**
JIRA - https://artsyproduct.atlassian.net/browse/PX-4293

feat(PX-4293): rename Shows tab to Events

---

src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionFilterMobileActionSheet.tsx

Revert "fix: refactor filters on artist auction results screen"

---

src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx

feat(home): adds credit line to desktop heroes

---

src/desktop/apps/partner/test/client/artists_list.test.js
src/desktop/apps/partner2/components/artists_list/test/view.test.js
src/desktop/components/article/templates/mixins.jade
src/desktop/models/artwork.coffee
src/desktop/models/partner.coffee
src/desktop/models/partner_artist.coffee
src/desktop/test/models/artwork.jest.ts
src/desktop/test/models/partner.jest.ts
src/desktop/test/models/partner_artist.jest.ts
src/mobile/apps/articles/routes.coffee
src/mobile/apps/articles/test/routes.test.js
src/mobile/apps/home/templates/current_shows.jade
src/mobile/components/article/templates/sections/images.jade
src/mobile/components/artist_list/template.jade
src/mobile/models/artwork.coffee
src/mobile/models/partner.coffee
src/mobile/models/show.coffee
src/mobile/test/models/artwork.test.js
src/v2/Apps/Purchase/Components/OrderRow.tsx
src/v2/Apps/__tests__/Fixtures/Order.ts
src/v2/__generated__/OrderRow_order.graphql.ts
src/v2/__generated__/PurchaseAppTestQuery.graphql.ts
src/v2/__generated__/PurchaseHistoryQuery.graphql.ts
src/v2/__generated__/purchaseRoutes_PurchaseQuery.graphql.ts

We split the partner2 -> partner into 6 steps to make a migration smoothly.
You can see these steps [the PR with our routes migration plan](https://github.com/artsy/force/pull/7611)
This PR is a 4th step of migration.
This PR should be merged after the [2nd part](https://github.com/artsy/force/pull/7677)

feat: partner transition part 4

---

src/v2/Apps/Conversation/Components/OpenInquiryModalButton.tsx

https://artsyproduct.atlassian.net/browse/PURCHASE-2791
The Artsy guarantee link opens in new window

Fix:target _blank for The Artsy guarantee link

---

src/v2/Apps/Conversation/Components/BuyerGuaranteeMessage.tsx

This box is placed on full conversation width. Set maxWidth as Figma required 
https://artsyproduct.atlassian.net/browse/PURCHASE-2792

fix:right width for protectedBy block

---

package.json
src/desktop/apps/article/templates/classic_meta.jade
src/desktop/apps/articles/components/AuthWrapper.tsx
src/desktop/apps/articles/components/__tests__/AuthWrapper.jest.tsx
src/desktop/apps/articles/test/routes.test.js
src/desktop/apps/editorial_features/components/eoy/templates/head.jade
src/desktop/apps/editorial_features/components/gucci/templates/__tests__/head.test.js
src/desktop/apps/editorial_features/components/gucci/templates/head.jade
src/desktop/apps/editorial_features/components/venice_2017/templates/head.jade
src/desktop/apps/editorial_features/routes.coffee
src/desktop/apps/editorial_features/test/routes.test.js
src/desktop/components/fair_layout/templates/head.jade
src/desktop/components/main_layout/templates/blank.jade
src/desktop/components/main_layout/templates/index.jade
src/desktop/components/main_layout/templates/minimal_header.jade
src/desktop/components/main_layout/templates/redesign.jade
src/desktop/components/main_layout/templates/scripts.jade
src/desktop/config.coffee
src/lib/analytics/helpers.ts
src/lib/setup_sharify.js
src/mobile/apps/articles/index.coffee
src/mobile/apps/articles/routes.coffee
src/mobile/apps/articles/test/routes.test.js
src/mobile/components/layout/templates/scaffold.jade
src/mobile/config.coffee
src/typings/global.d.ts
src/v2/Apps/Artwork/Components/ArtworkMeta.tsx
src/v2/index.ejs
src/v2/server.ts
yarn.lock

Closes: [GRO-394](https://artsyproduct.atlassian.net/browse/GRO-394)

chore(sailthru): removes sailthru

---

cypress/integration/article.spec.ts
src/desktop/apps/partner/templates/index.jade
src/desktop/apps/partner2/templates/index.jade

**Do not merge this PR until the second part will be merged** 
The 5th step of the partner profile page transition. #7611
JIRA - https://artsyproduct.atlassian.net/browse/PX-4058

feat(PX-4058): partner transition part 5

---

cypress/integration/shows.spec.ts
src/v2/Apps/Shows/Components/ShowsFeaturedShow.tsx
src/v2/Apps/Shows/Components/ShowsHeader.tsx
src/v2/Apps/Shows/Components/ShowsMeta.tsx
src/v2/Apps/Shows/Components/ShowsShowDates.tsx
src/v2/Apps/Shows/Routes/ShowsCity.tsx
src/v2/Apps/Shows/Routes/ShowsIndex.tsx
src/v2/Apps/Shows/Routes/__tests__/ShowsCity.jest.tsx
src/v2/Apps/Shows/Routes/__tests__/ShowsIndex.jest.tsx
src/v2/Apps/Shows/ShowsApp.tsx
src/v2/Apps/Shows/showsRoutes.tsx
src/v2/__generated__/ShowsCity_Test_Query.graphql.ts
src/v2/__generated__/ShowsCity_city.graphql.ts
src/v2/__generated__/ShowsCity_viewer.graphql.ts
src/v2/__generated__/ShowsFeaturedShow_show.graphql.ts
src/v2/__generated__/ShowsHeader_viewer.graphql.ts
src/v2/__generated__/ShowsIndex_Test_Query.graphql.ts
src/v2/__generated__/ShowsIndex_featuredShows.graphql.ts
src/v2/__generated__/ShowsIndex_viewer.graphql.ts
src/v2/__generated__/ShowsShowDates_show.graphql.ts
src/v2/__generated__/showsRoutes_ShowsCityQuery.graphql.ts
src/v2/__generated__/showsRoutes_ShowsIndexQuery.graphql.ts
src/v2/routes.tsx

feat(shows): roughs in shows2

---

src/v2/Apps/Gene/Components/GeneArtworkFilter.tsx
src/v2/Apps/Gene/Components/__tests__/GeneArtworkFilter.jest.tsx
src/v2/Apps/Gene/Routes/GeneShow.tsx
src/v2/Apps/Gene/geneRoutes.tsx
src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
src/v2/Components/ArtworkFilter/Utils/fetchFollowedArtists.ts
src/v2/Components/ArtworkFilter/index.tsx
src/v2/__generated__/GeneArtworkFilterQuery.graphql.ts
src/v2/__generated__/GeneArtworkFilter_Query.graphql.ts
src/v2/__generated__/GeneArtworkFilter_gene.graphql.ts
src/v2/__generated__/GeneShow_Test_Query.graphql.ts
src/v2/__generated__/GeneShow_gene.graphql.ts
src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts

Resolves [FX-2859]
[FX-2859]: https://artsyproduct.atlassian.net/browse/FX-2859

feature: Add artists filter to gene page

---

src/v2/Apps/Artist/Routes/Articles/ArtistArticlesRoute.tsx
src/v2/__generated__/ArtistArticlesRouteQuery.graphql.ts
src/v2/__generated__/ArtistArticlesRoute_Test_Query.graphql.ts
src/v2/__generated__/ArtistArticlesRoute_artist.graphql.ts
src/v2/__generated__/artistRoutes_ArticlesQuery.graphql.ts

Closes: [GRO-423](https://artsyproduct.atlassian.net/browse/GRO-423)

fix(artist): makes artist articles clickable

---

cypress/integration/partnerProfile.spec.js
package.json
yarn.lock

Update's Cohesion version to 2.9.0.

chore: bump Cohesion to 2.9.0

---

src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/v2/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
src/v2/Apps/Artist/Routes/AuctionResults/Components/AuctionResultsControls.tsx
src/v2/Apps/Artist/Routes/AuctionResults/Components/KeywordFilter.tsx
src/v2/Apps/Artist/Routes/AuctionResults/Components/SortSelect.tsx
src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
src/v2/__generated__/ArtistAuctionResultsQuery.graphql.ts
src/v2/__generated__/ArtistAuctionResults_artist.graphql.ts

Addresses [CX-1591]
Allows users to filter artist auction results by keyword.
|<img width="494" alt="Screenshot 2021-07-09 at 13 13 50" src="https://user-images.githubusercontent.com/4691889/125070058-e2953b80-e0b7-11eb-9338-e239bd0159ae.png">|<img width="488" alt="Screenshot 2021-07-09 at 13 15 52" src="https://user-images.githubusercontent.com/4691889/125070069-e5902c00-e0b7-11eb-8433-6257be3b5e27.png">|
|---|---|
|<img width="1060" alt="Screenshot 2021-07-09 at 13 15 26" src="https://user-images.githubusercontent.com/4691889/125070103-f2ad1b00-e0b7-11eb-95fb-1da89f985b65.png">|
|---|
[CX-1591]: https://artsyproduct.atlassian.net/browse/CX-1591

feat: User can keyword filter within artist auction results

---

src/v2/Apps/Conversation/Components/ConfirmArtworkButton.tsx
src/v2/Apps/Conversation/Components/ConversationCTA.tsx
src/v2/Apps/Conversation/Components/OpenInquiryModalButton.tsx

Adds tracking to Make Offer Inquiries when user taps Make Offer and when user confirms artwork before entering checkout flow.
https://artsyproduct.atlassian.net/browse/PURCHASE-2801

chore: add inq checkout tracking analytics

---

src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistArtworksRail.tsx
src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetails.tsx
src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetailsPlaceholder.tsx
src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistDetailsList/PartnerArtistDetailsList.tsx
src/v2/Components/Carousel/Carousel.tsx
src/v2/__generated__/PartnerArtistArtworksRailQuery.graphql.ts
src/v2/__generated__/PartnerArtistArtworksRail_partnerArtist.graphql.ts
src/v2/__generated__/PartnerArtistDetailsListQuery.graphql.ts
src/v2/__generated__/PartnerArtistDetailsListRendererQuery.graphql.ts
src/v2/__generated__/PartnerArtistDetails_partnerArtist.graphql.ts

This PR fixes limited artwork loading and adds batch loading for the artwork carousel.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4310
<details>
<summary>Desktop</summary>
https://user-images.githubusercontent.com/79979820/125110145-e2636300-e0ec-11eb-9769-dee05fdd1732.mov
</details>
<details>
<summary>Mobile</summary>
https://user-images.githubusercontent.com/79979820/125110534-5b62ba80-e0ed-11eb-941a-6ddcac76f1f4.mov
</details>

fix(PX-4310): artwork loading limit

---

src/v2/Apps/Home/HomeApp.tsx
src/v2/Components/FlashBanner/EmailConfirmationCTA.tsx
src/v2/Components/FlashBanner/EmailConfirmationLinkExpired.tsx
src/v2/Components/FlashBanner/__tests__/FlashBanner.jest.tsx
src/v2/Components/FlashBanner/index.tsx

Simple enough. Some minor clean up to the styling (these changes are valid/fine in v2 as well).

feat(home): adds flash banner to homepage

---

src/v2/Apps/Home/Components/HomeArtworkModuleRail.tsx
src/v2/Apps/Home/Components/HomeArtworkModules.tsx
src/v2/Apps/Home/HomeApp.tsx

chore(home): moves shows module up

---

src/v2/Apps/Order/Components/AddressModal.tsx
src/v2/Apps/Order/Components/SavedAddressItem.tsx
src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx
src/v2/Apps/Order/Mutations/CreateUserAddress.ts
src/v2/Apps/Order/Mutations/UpdateUserAddress.ts

The collector can set an address as default
Jira: https://artsyproduct.atlassian.net/browse/PX-4135
<details>
<summary>Edit modal when isDefault true</summary>
https://user-images.githubusercontent.com/55637696/125309131-2b5c2700-e33a-11eb-93ea-8fb0e158f126.mov
</details>
<details>
<summary>Edit modal when isDefault false</summary>
https://user-images.githubusercontent.com/55637696/125309297-50e93080-e33a-11eb-891e-920d9408d39d.mov
</details>
<details>
<summary>Add modal(checkbox is always shown)</summary>
https://user-images.githubusercontent.com/55637696/125309822-ba693f00-e33a-11eb-98c4-0654d9a12cb7.mov
</details>
<details>
<summary>Correct state when uncheck</summary>
https://user-images.githubusercontent.com/55637696/125309372-6199a680-e33a-11eb-86f5-16da6a34f9a4.mov
</details> …

feat(PX-4135): Collector can set an address as default

---

src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx

Left off this handler in the refactor.

fix: fixes watch lot button

---

src/v2/Components/NavBar/NavBar.tsx

fix(nav): prevents hamburger click from reloading the page

---

src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
src/v2/Components/Address/AddressModalFields.tsx

https://artsyproduct.atlassian.net/browse/PURCHASE-2772
the correct order of fields (the same for mobile and desktop view)

fix: correct fields order for add new adress modal [PURCHASE-2772]

---

src/v2/Components/ArtworkFilter/index.tsx

Fixes overflowing container in Firefox

fix: fixes overflowing artwork grid in firefox

---

src/v2/Apps/Partner/Components/Overview/SubscriberBanner.tsx

JIRA - https://artsyproduct.atlassian.net/browse/PX-4170
Before
Now

feat(PX-4170): update non-subscriber PPP banner

---

src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarousel.tsx
src/v2/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarouselItem.tsx
src/v2/__generated__/PartnerArtistsCarouselItem_artist.graphql.ts
src/v2/__generated__/PartnerArtistsCarouselRendererQuery.graphql.ts
src/v2/__generated__/PartnerArtistsCarousel_partner.graphql.ts

This PR fixes artwork image for the artists carousel. Used first image according to CMS artworks order. 
JIRA - https://artsyproduct.atlassian.net/browse/PX-4292

fix(PX-4292): fix artwork image for the artists carousel

---

src/v2/Apps/Fair/Components/ExhibitorFilterContext.tsx
src/v2/Apps/Fair/Routes/FairExhibitors.tsx
src/v2/Apps/Fair/Routes/FairExhibitorsQuery.tsx
src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
src/v2/Apps/Fair/fairRoutes.tsx
src/v2/__generated__/FairExhibitorsQuery.graphql.ts
src/v2/__generated__/FairExhibitors_Query.graphql.ts
src/v2/__generated__/FairExhibitors_fair.graphql.ts
src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts

[FX-3071]
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
[FX-3071]: https://artsyproduct.atlassian.net/browse/FX-3071

FX-3071 feat: Added pagination to fair booths page

---

src/v2/Apps/Order/Routes/Shipping/index.tsx
src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx
src/v2/Apps/Order/Utils/shippingUtils.ts

This PR adds new error messages for Arta shipping.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4228

feat(PX-4228): error messages for Arta shipping

---

package.json
src/v2/Apps/Conversation/Components/CollapsibleArtworkDetails.tsx
yarn.lock

Fixes a few type errors that slipped into master

fix: type errors

---

data/schema.graphql
src/v2/Apps/Conversation/Components/Conversation.tsx
src/v2/__generated__/ConversationPageQuery.graphql.ts
src/v2/__generated__/ConversationPaginationQuery.graphql.ts
src/v2/__generated__/Conversation_conversation.graphql.ts
src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts

Addresses: [PURCHASE-2826](https://artsyproduct.atlassian.net/browse/PURCHASE-2826)
This PR is follow up work to https://github.com/artsy/metaphysics/pull/3249 and uses the new `liveArtwork` field to get the up-to-date `isOfferableFromInquiry` property. This allows us to more accurately display the 'Make Offer' button and 'Buyer Guarantee' message.

feat: use liveArtwork to determine isOfferable

---

src/v2/Apps/Artwork/ArtworkApp.tsx
src/v2/Apps/Order/OrderApp.tsx
src/v2/Utils/LegacyArtworkDllContainer.tsx

Creates a reusable component that loads both the legacy JS and CSS
assets for modern pages.

fix: Legacy Asset Loading

---

cypress/integration/userPayments.spec.js
cypress/integration/userShipping.spec.js
src/lib/middleware/userRequiredMiddleware.ts
src/v2/Apps/Payment/Routes/Payment/PaymentApp.tsx
src/v2/Apps/Payment/__tests__/PaymentApp.jest.tsx
src/v2/Apps/Purchase/Components/PurchaseHistory.tsx
src/v2/Apps/Shipping/Routes/Shipping/ShippingApp.tsx
src/v2/Apps/Shipping/__tests__/ShippingApp.jest.tsx
src/v2/Apps/Shipping/shippingRoutes.tsx
src/v2/Components/UserSettings/UserSettingsTabs.tsx
src/v2/Components/UserSettings/__tests__/UserSettingsTabs.jest.tsx
src/v2/__generated__/PaymentApp_Test_Query.graphql.ts
src/v2/__generated__/ShippingApp_Test_Query.graphql.ts
src/v2/__generated__/ShippingApp_me.graphql.ts
src/v2/__generated__/shippingRoutes_ShippingQuery.graphql.ts
src/v2/routes.tsx

Saved addresses used to be on the same tab in the uses settings tab: **Payment & Shipping** (`/user/payments`): 
Now they are separated into two tabs: **Payment** and **Shipping**.
**Payments** page stays on the same URL, but addresses are removed: 
Adresses are on the new page, **Shipping** (`/user/shipping`)

feat(PURCHASE-2767): Split Payments and Shipping tabs

---

src/v2/Components/NavBar/Menus/MobileNavMenu/LoggedInLinks.tsx

Solves https://artsyproduct.atlassian.net/browse/PURCHASE-2767
Add shipping link to the menu on mWeb.

feature (PURCHASE-2767): Add shipping nav item to the menu

---

cypress/integration/fairOrganizer.spec.ts
src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
src/v2/Apps/FairOrginizer/fairOrganizerRoutes.tsx
src/v2/routes.tsx

[FX-3129]
[FX-3129]: https://artsyproduct.atlassian.net/browse/FX-3129

FX-3129 feat: Added /fair-organizer/:slug route

---

src/v2/System/Router/RouterLink.tsx

https://styled-components.com/docs/api#shouldforwardprop
We just don't have updated typings yet.

chore: silences "react does not recognize..." warnings

---

src/v2/Apps/Fair/Components/ExhibitorFilterContext.tsx
src/v2/Apps/Fair/Routes/FairExhibitors.tsx
src/v2/Apps/Fair/Routes/FairExhibitorsQuery.tsx
src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
src/v2/Apps/Fair/fairRoutes.tsx
src/v2/__generated__/FairExhibitorsQuery.graphql.ts
src/v2/__generated__/FairExhibitors_Query.graphql.ts
src/v2/__generated__/FairExhibitors_fair.graphql.ts
src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts

[FX-3071]
Re-opening [#8037](https://github.com/artsy/force/pull/8037) as it was reverted
[FX-3071]: https://artsyproduct.atlassian.net/browse/FX-3071

FX-3071 Re-open #8037(feat: Add pagination to fair booths new)

---

src/v2/Apps/Artist/Routes/Overview/Components/ArtistRelatedArtistsRail.tsx
src/v2/__generated__/ArtistOverviewRoute_Test_Query.graphql.ts
src/v2/__generated__/ArtistRelatedArtistsRail_artist.graphql.ts
src/v2/__generated__/artistRoutes_OverviewQuery.graphql.ts

Just a minor thing I noticed when I was auditing the images. Also un-nests the nested anchor tags.

fix(artistrelatedartists): uses cropped image versions; cleans up

---

src/middleware.ts

Only provided `@artsy/passport` with values that it uses.

chore: Passport Configuration

---

webpack/plugins/datadog.js
webpack/utils/env.js

Add support for loading the webpack datadog configuration from the
shared environment file and log some basic machine stats.

feature: Webpack Stats from Environment

---

src/v2/Apps/Conversation/Components/Conversation.tsx
src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx
src/v2/Apps/Conversation/Components/__tests__/Item.jest.tsx
src/v2/Apps/__tests__/Fixtures/Conversation.ts
src/v2/__generated__/ConversationPaginationTestQuery.graphql.ts

Partially solves https://artsyproduct.atlassian.net/browse/PURCHASE-2814
Move Item tests to a separate file, add tests to the Conversation component

chore (PURCHASE-2814): add test to the conversation component

---

src/v2/Components/NavBar/NavBar.tsx

OK — one more minor thing — logged out button alignment.

fix(navbar): tweaks desktop logged out button vertical alignment

---

src/v2/Components/ArtworkFilter/ArtworkFilters/SizeFilter.tsx

This PR is not associated with Jira ticket
The purpose of the PR is to remove unnecessary code and improve code style

refactor: update size filter code style

---

src/v2/Apps/Conversation/Components/Conversation.tsx
src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx
src/v2/__generated__/ConversationPagination_Test_Query.graphql.ts

Not entirely sure how these became failing; I think a fixture changed out from under the specs. Re-wrote them to just use the auto-generated relay mocks.

fix(conversation): corrects failing specs

---

src/v2/Apps/Order/Components/AddressModal.tsx

This PR adds on mount validation for the address modal.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4360
Before
https://user-images.githubusercontent.com/79979820/127998040-6009206c-d625-48f8-b84a-2dd8470800a7.mov
Now
https://user-images.githubusercontent.com/79979820/127997883-9330ef76-74b6-48f1-9669-5147f6afd264.mov

fix(PX-4360): fix add address validation

---

src/v2/Apps/Order/Components/SavedAddresses.tsx
src/v2/Apps/Order/Routes/Shipping/index.tsx

This PR selects a newly added address.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4368
https://user-images.githubusercontent.com/79979820/128002014-8f9f3ca5-2460-47a4-864c-d81c7df12553.mov

feat(PX-4368): select newly added address

---

src/v2/Apps/Order/Routes/Shipping/index.tsx

This PR removes shipping quotes information on address and delivery change to fix animation.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4363
Before
https://user-images.githubusercontent.com/79979820/127999250-ec8d6d6d-2828-4a39-ad5a-4f623b79e097.mov
Now
https://user-images.githubusercontent.com/79979820/127999793-f8ae48f8-075a-4752-8453-e06c6e01a3fc.mov

fix(PX-4363): fix animation on address change

---

src/v2/Apps/Consign/Routes/MarketingLanding/Components/ArtsyMissionStatement.tsx
src/v2/Apps/Consign/Routes/MarketingLanding/Components/FAQ.tsx
src/v2/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx
src/v2/Apps/Consign/Routes/MarketingLanding/Components/PromoSpace.tsx
src/v2/Apps/Consign/Routes/MarketingLanding/Components/SellArtDifferently.tsx
src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Header.jest.tsx
src/v2/Apps/Consign/Routes/MarketingLanding/MarketingLandingApp.tsx
src/v2/Components/FullBleedHeader.tsx

This PR solves [GRO-462]
This PR is to create a new consign Sell with Artsy landing page based on updated value props, creative, and copy written by the design team. The intention is for the user to see the new landing page UI and FAQ info. 
[GRO-462]: https://artsyproduct.atlassian.net/browse/GRO-462

GRO-462: Update sell with artsy landing page

---

src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuItem.tsx
src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuTransition.tsx

Fixes a touch scrolling issue that would sometimes manifest if the download app banner was stacked on top of the nav.

fix(navbar): improves overflow scrolling

---

src/v2/Apps/Conversation/Components/Conversation.tsx
src/v2/Apps/Conversation/Components/ConversationCTA.tsx
src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx
src/v2/Apps/Conversation/Components/__tests__/ConversationCTA.jest.tsx

Removes feature flag checkers for Web Inquiry Checkout functionality.
cc: @artsy/purchase-devs

chore: Remove feature flag checkers for web inquiry checkout

---

src/v2/Apps/Order/Components/SavedAddresses.tsx

JIRA - https://artsyproduct.atlassian.net/browse/PX-4368
Before
https://user-images.githubusercontent.com/79979820/128732317-6f401fdc-6d86-4fdf-a4af-ea85f8e98886.mov
Now
https://user-images.githubusercontent.com/79979820/128732218-fcd3a471-fb6a-4a8a-b937-0b3dc510edef.mov

fix(PX-4368): wait for address reloading before select newly added address

---

src/v2/Apps/Conversation/Components/OpenInquiryModalButton.tsx
src/v2/Apps/Conversation/Components/OrderUpdate.tsx
src/v2/Apps/Conversation/Components/Reply.tsx

Re-implementing changes from [this PR](https://github.com/artsy/force/pull/8007)

revert: Adjust MO button style and move order update timestamp

---

src/desktop/apps/about/client/view.coffee

fix(about): avoids initializing slideshow if selector is missing

---

src/v2/Apps/ArtistSeries/Components/ArtistSeriesHeader.tsx
src/v2/Apps/Artwork/Components/ArtworkBanner/ArtworkBanner.tsx
src/v2/Components/TopContextBar.tsx

[Figma spec](https://www.figma.com/file/m6gDpKHEWDbYJyrwsVZDBr/Artsy-3.0-Design-System?node-id=1007%3A1392)

fix: uses a consistent height for artwork context bar

---

.eslintrc.js
cypress/integration/artist.spec.js

Any others? Sad we didn't think of doing this sooner!

chore: adds restricted imports eslint config

---

src/v2/Apps/Auction/Routes/__tests__/ConfirmBid.jest.tsx
src/v2/Apps/Auction/Routes/__tests__/Register.jest.tsx
src/v2/Apps/Order/Components/CreditCardDetails.tsx
src/v2/Apps/Order/Components/CreditCardInput.tsx
src/v2/Apps/Order/Components/__tests__/CreditCardInput.jest.tsx
src/v2/Apps/Payment/Components/PaymentSection.tsx
src/v2/Apps/Payment/paymentRoutes.tsx
src/v2/Components/Address/AddressModalFields.tsx
src/v2/Components/Mixins.tsx
src/v2/Components/Payment/PaymentModal.tsx
src/v2/Components/Payment/SavedCreditCards.tsx
src/v2/Components/UserSettings/UserSettingsTabs.tsx

[PURCHASE-2878]
__Before:__
__After:__
__V2 styles preserved for other uses of the shared credit card field:__
[PURCHASE-2878]: https://artsyproduct.atlassian.net/browse/PURCHASE-2878

Migrate payments app to palette v3

---

package.json
yarn.lock

Bump for https://github.com/artsy/reaction/pull/3697

lib: Bump reaction

---

yarn.lock

The lockfile wanted a minor tweak.

chore: Lodash Lockfile

---

cypress/integration/partnerProfile.spec.js
src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx
src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/__tests__/FairOrganizerHeader.jest.tsx
src/v2/Apps/FairOrginizer/fairOrganizerRoutes.tsx
src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
src/v2/__generated__/FairOrganizerHeader_Test_Query.graphql.ts
src/v2/__generated__/FairOrganizerHeader_fairOrganizer.graphql.ts
src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts

[FX-3132]
**Demo**
_moving-image-istanbul_ organizer hasn't profile hence its page is not available
[FX-3132]: https://artsyproduct.atlassian.net/browse/FX-3132

feat(FX-3132): Added link to the fair page on fair organizer page, show 404 when there is no profile

---

src/desktop/components/inquiry_questionnaire/test/views/inquiry.test.ts
src/desktop/components/inquiry_questionnaire/views/account.coffee
src/desktop/components/inquiry_questionnaire/views/inquiry.coffee
src/desktop/components/inquiry_questionnaire/views/loadRecaptcha.ts
src/v2/Apps/Artwork/ArtworkApp.tsx

Addresses https://artsyproduct.atlassian.net/browse/GRO-443 
This is a temporary fix for loading recaptcha only when the (old) Inquiry form loads. The new one loads things dynamically so this will quickly be phased out.

feat: Temporarily load recaptcha in form

---

src/v2/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlights.tsx
src/v2/Apps/Artist/Routes/Overview/Components/ArtistConsignButton.tsx
src/v2/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
src/v2/__generated__/ArtistConsignButton_Test_Query.graphql.ts
src/v2/__generated__/ArtistConsignButton_artist.graphql.ts
src/v2/__generated__/ArtistOverviewRoute_Test_Query.graphql.ts
src/v2/__generated__/artistRoutes_OverviewQuery.graphql.ts

This PR fixes a few pieces of the artist page that weren't converted to V3. In particular the gallery submitted bio lacked correct line-spacing which is what prompted this discovery.

fix(artist): corrects v3 styling

---

src/v2/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx

Minor fix to viewing room header images.

fix(viewing-room): fixes mobile image header

---

package.json
webpack/envs/clientPlugins.js
yarn.lock

fix(types): adds types for lodash-webpack-plugin

---

src/v2/Apps/Partner/Components/PartnerHeader/PartnerHeaderImage.tsx
src/v2/Components/FullBleedHeader.tsx

Closes [DSWGW-88](https://artsyproduct.atlassian.net/browse/DSWGW-88)

fix(headers): limits full-bleed headers to 50vh (sans nav)

---

packages/publish/package.json

Updates a missed configuration to support node 14

feature: Node 14

---

src/v2/Apps/ViewingRoom/Components/ViewingRoomsFeaturedRail.tsx

This PR comes as a try to fix #incident-122
Co-authored-by: Matt Dole <mdole7@gmail.com>
Co-authored-by: Andre Rocha <devel.andrerocha@gmail.com>

fix: undefined featured viewing rooms

---

webpack/envs/clientPlugins.js

We also need to include lodash `flattening` functionality.

fix: Lodash Flattening

---

src/v2/Apps/Partner/Components/PartnerShows/ShowBanner.tsx

This PR fixes image position for hidden shows. 
JIRA - https://artsyproduct.atlassian.net/browse/PX-4456
Before
https://user-images.githubusercontent.com/79979820/130789920-4df44882-4c29-457c-81a0-d0b26ff6b39d.mov
Now
https://user-images.githubusercontent.com/79979820/130790262-07d9b3a9-c8c9-454d-95ad-142206cdb9bb.mov

fix(PX-4456): show links on partner overview page

---

src/v2/Apps/Order/Components/PaymentPicker.tsx

fix checkbox name in PaymentPicker

fix:fix checkbox name in PaymentPicker

---

package.json
src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/ResultsFilter.tsx
src/v2/Components/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
yarn.lock

[FX-3197]
This PR makes options for `Material`, `Price`, `Color`, and `Ways to Buy` filters title cased
<details>
<summary>Price</summary>
**Before**
**After**
</details>
<details>
<summary>Ways to Buy</summary>
**Before**
**After**
</details>
<details>
<summary>Material</summary>
**Before**
**After**
</details>
<details>
<summary>Color</summary>
**Before**
**After**
</details>

feat(FX-3197): make all filter options Title Cased

---

src/v2/Apps/Order/Components/AddressModal.tsx

hide banner if error is null
https://artsyproduct.atlassian.net/browse/PX-4486

FIX:error banner if error is null [PX-4486]

---

src/v2/Apps/ViewingRoom/viewingRoomRoutes.tsx

Jira Ticket:ticket: : [PX-4489](https://artsyproduct.atlassian.net/browse/PX-4489)
Discussion:scroll: : https://artsy.slack.com/archives/C9ZJYFDNF/p1630397677128800
This PR fixing the 404 error when clicking on the `View Works` button.
https://user-images.githubusercontent.com/55637696/131490371-c8528fa0-0346-4b37-a8d9-44aa960f716a.mov

fix(PX-4489): Viewing rooms: View works: 404 error page is opened

---

src/v2/Apps/Partner/Components/NavigationTabs/index.tsx
src/v2/Apps/Partner/Components/__tests__/NavigationTabs.jest.tsx

Reverts artsy/force#8293 and releases VR in PPP to all users

Revert "chore: add admin flag to show VR in PPP"

---

src/v2/Apps/Artist/Routes/Overview/Components/ArtistConsignButton.tsx
src/v2/Apps/Artist/Routes/Overview/Components/__tests__/ArtistConsignButton.jest.tsx

Looks like this got un-nested in the v3 conversion.

fix(artist): fixes consign button link

---

src/lib/cacheClient.tsx
src/lib/middleware/__tests__/redisPageCache.jest.ts
src/lib/middleware/memoryPageCache.ts
src/lib/middleware/pageCacheCommon.ts
src/lib/middleware/redisPageCache.ts
src/middleware.ts
src/v2/Utils/logger.ts

This reverts commit d3936d06e57533f781550eda4f82d3cc5ebf7e21.

Revert "Revert "feature: Redis Page Cache""

---

src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorGroupPlaceholder.tsx
src/v2/Apps/Fair/Components/FairExhibitors/FairExhibitorsGroup.tsx

Slack discussion: [here](https://artsy.slack.com/archives/C9SATFLUU/p1630675754335900?thread_ts=1630675379.334600&cid=C9SATFLUU)
https://user-images.githubusercontent.com/56556580/132017702-477c551d-b671-4ce3-8a4e-8d8fb46362cf.mov

chore: updated exhibitors layout

---

src/v2/Apps/Artist/ArtistApp.tsx
src/v2/Apps/Artist/__tests__/ArtistApp.jest.tsx

Title cases the artist's Auction Results tab title ("Auction results" --> "Auction Results").

fix: Titlecase Artist Auction Results tab title

---

src/lib/cacheClient.tsx
src/lib/middleware/__tests__/redisPageCache.jest.ts
src/lib/middleware/memoryPageCache.ts
src/lib/middleware/redisPageCache.ts
src/lib/middleware/requestRecorder.ts
src/middleware.ts
src/v2/Utils/logger.ts

This reverts commit b0a2d33bac91b8c4514184185ee0e03679e620d2.

Revert "Revert "Revert "Revert "feature: Redis Page Cache""""

---

src/v2/Components/Inquiry/Hooks/useCreateUserInterest.ts
src/v2/Components/Inquiry/Hooks/useInquiryAffiliated.ts
src/v2/Components/Inquiry/Views/InquiryArtistsInCollection.tsx
src/v2/Components/Inquiry/Views/InquiryAuctionHousesYouWorkWith.tsx
src/v2/Components/Inquiry/Views/InquiryFairsYouAttend.tsx
src/v2/Components/Inquiry/Views/InquiryGalleriesYouWorkWith.tsx
src/v2/Components/Inquiry/__tests__/Hooks/useInquiryAffiliated.jest.tsx
src/v2/Components/Inquiry/config.ts
src/v2/__generated__/InquiryArtistsInCollectionQuery.graphql.ts
src/v2/__generated__/useCreateUserInterestMutation.graphql.ts

Implements artists in collection step; which relies on the user interests API.
https://user-images.githubusercontent.com/112297/132402516-cbe1bba5-a983-4394-ba01-256234bf903f.mov

feat(inquiry): implements artists in collection step

---

src/v2/Apps/BuyerGuarantee/Components/Feature.tsx
src/v2/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
src/v2/Apps/Fairs/Routes/FairsIndex.tsx

[PURCHASE-2918]
https://www.figma.com/file/6h9u666iRyHPC1rvZafZjl/2021-Artsy-Pay-Protection?node-id=2010%3A3
- Excess code was deleted
- some refactoring
- keeping v3 flow
**Desktop:**
**Mobile:**
[PURCHASE-2918]: https://artsyproduct.atlassian.net/browse/PURCHASE-2918

refactor(PURCHASE-2918):BuyerGuarantee page refactoring

---

src/v2/Apps/Order/Routes/Shipping/index.tsx
src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx

JIRA - https://artsyproduct.atlassian.net/browse/PX-4495
Before
Now

fix(PX-4495): make continue button disabled if shipping quote not selected

---

src/v2/Components/Sticky/Sticky.tsx

FWIW it does look like we'll have to add these features soon!

chore(sticky): adds faq

---

src/v2/Apps/Home/Components/HomeFeaturedEventsRail.tsx
src/v2/__generated__/HomeApp_Test_Query.graphql.ts
src/v2/__generated__/HomeFeaturedEventsRail_orderedSet.graphql.ts
src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts

Closes: [GRO-514](https://artsyproduct.atlassian.net/browse/GRO-514)

fix(gro-514): homepage featured rail typography/layout updates

---

src/v2/Apps/Home/Components/HomeFeaturedArticles.tsx
src/v2/Apps/Home/__tests__/HomeFeaturedArticles.jest.tsx
src/v2/__generated__/HomeFeaturedArticlesQuery.graphql.ts
src/v2/__generated__/HomeFeaturedArticles_Test_Query.graphql.ts
src/v2/__generated__/HomeFeaturedArticles_articles.graphql.ts

Addresses https://artsyproduct.atlassian.net/browse/GRO-516 
This updates the homepage articles section to the new design.

feat: Update homepage article layout

---

src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
src/v2/Apps/FairOrginizer/__tests__/FairOrganizerApp.jest.tsx
src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
src/v2/__generated__/FairOrganizerApp_fairOrganizer.graphql.ts
src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts

Description
Add the missing MetaTags of the Fair Organizer app.
[Ticket](https://artsyproduct.atlassian.net/browse/FX-3291)
Screenshot
Validated with the Twitter URL checked and used [ngrok](https://ngrok.com/) as the helper tool.

feat[FX-3291]: add MetaTags to the FairOrganizerApp

---

src/v2/Apps/Fair/Components/FairOverview/FairAbout.tsx
src/v2/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx
src/v2/__generated__/FairAbout_fair.graphql.ts
src/v2/__generated__/FairOverview_Test_Query.graphql.ts
src/v2/__generated__/fairRoutes_FairOverviewQuery.graphql.ts

[FX-3303]
Before
After
[FX-3303]: https://artsyproduct.atlassian.net/browse/FX-3303

feat(FX-3303): Added Read More functionality

---

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarExtraLinks.jest.tsx
src/v2/Components/AuctionFAQsDialog.tsx
src/v2/Components/__tests__/AuctionFAQsDialog.jest.tsx
src/v2/Utils/legacyAssetDll.tsx
src/v2/__generated__/AuctionFAQsDialogQuery.graphql.ts
src/v2/__generated__/AuctionFAQsDialog_Test_Query.graphql.ts
src/v2/__generated__/AuctionFAQsDialog_viewer.graphql.ts

And that's it for these modals.

refactor: replaces old auction faq dialog; enables

---

src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx

Revert "fix(FX-3231): Removed max width of fair article"

---

src/v2/Apps/FairOrginizer/FairOrganizerApp.tsx
src/v2/Apps/FairOrginizer/__tests__/FairOrganizerApp.jest.tsx
src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
src/v2/__generated__/FairOrganizerApp_fairOrganizer.graphql.ts
src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts

Related to #8410 
- Adjust the description to use truncated text from `about` in the `MetaTags`.
- Clean up test
- Remove Title not necessary anymore
Now the description makes more sense to me, but would like to hear about it 👍 
PS: followed the Twitter recommendation to not go over 200 characters on the description.

fix(FX-3291): adjust meta description on FairOrganizerApp

---

src/v2/Apps/Home/Components/HomeCurrentFairsRail.tsx
src/v2/Apps/Home/Components/HomeFeaturedGalleriesRail.tsx
src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx
src/v2/Apps/Home/Components/HomeFeaturedShow.tsx
src/v2/Apps/Home/HomeApp.tsx
src/v2/Apps/Home/__tests__/HomeCurrentFairsRail.jest.tsx
src/v2/__generated__/HomeCurrentFairsRailQuery.graphql.ts
src/v2/__generated__/HomeCurrentFairsRail_Test_Query.graphql.ts
src/v2/__generated__/HomeCurrentFairsRail_viewer.graphql.ts

Addresses 
- https://artsyproduct.atlassian.net/browse/GRO-523
- https://artsyproduct.atlassian.net/browse/GRO-533
- https://artsyproduct.atlassian.net/browse/GRO-534
This adds a new Current Fairs rail to the home page:

feat: [Home] Add current fairs rail

---

src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItem.tsx
src/v2/Apps/Fair/Components/FairEditorial/FairEditorialItemLink.tsx
src/v2/Apps/Fair/Components/FairEditorial/FairEditorialRailArticles.tsx
src/v2/Apps/FairOrginizer/Routes/FairOrganizerDedicatedArticles.tsx
src/v2/__generated__/FairEditorialItemLink_article.graphql.ts
src/v2/__generated__/FairEditorialItem_Test_Query.graphql.ts
src/v2/__generated__/FairEditorialItem_article.graphql.ts
src/v2/__generated__/FairEditorialRailArticles_Test_Query.graphql.ts
src/v2/__generated__/FairEditorial_Test_Query.graphql.ts
src/v2/__generated__/FairOrganizerApp_Test_Query.graphql.ts
src/v2/__generated__/FairOrganizerDedicatedArticlesQuery.graphql.ts
src/v2/__generated__/FairOrganizerDedicatedArticles_Test_Query.graphql.ts
src/v2/__generated__/FairOrganizerLatestArticles_Test_Query.graphql.ts
src/v2/__generated__/FairOverview_Test_Query.graphql.ts
src/v2/__generated__/fairOrganizerRoutes_FairOrganizerDedicatedArticles_Query.graphql.ts
src/v2/__generated__/fairOrganizerRoutes_FairOrganizerQuery.graphql.ts
src/v2/__generated__/fairRoutes_FairOverviewQuery.graphql.ts

[FX-3231]
**Before**
**After**
[FX-3231]: https://artsyproduct.atlassian.net/browse/FX-3231

fix(FX-3231): Aligned articles layout

---

src/v2/Apps/Order/Components/AddressModal.tsx
src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx
src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx

This PR moves the phone validation work behind a feature flag per https://artsyproduct.atlassian.net/browse/PURCHASE-2944.
Without:
With:

chore: adds feat flag to show/hide country code dropdown menu

---

src/v2/Apps/Order/Components/__tests__/PaymentPicker.jest.tsx

Adds page updates to fix failing payment picker tests.

fix: Add page updates to fix payment picker tests

---

data/schema.graphql
src/v2/Apps/Home/Components/HomeArtworkModuleRail.tsx
src/v2/Apps/Home/Components/HomeArtworkModules.tsx
src/v2/__generated__/HomeArtworkModuleRailQuery.graphql.ts

chore: Sync mp schema & Update HomeArtworkModule types

---

src/v2/Apps/PriceDatabase/Components/PriceDatabaseSearch.tsx
src/v2/Apps/PriceDatabase/PriceDatabase.tsx
src/v2/Apps/PriceDatabase/__tests__/PriceDatabaseApp.jest.tsx
src/v2/System/Analytics/Schema/Values.ts

Jira: [CX-1836](https://artsyproduct.atlassian.net/browse/CX-1836)
This PR adds 2 tracking events at `/price-database`
- adds a screen track to price database landing
- adds tracking for filter changes
- adds tracking for Search click
Fired events look as below: 
Screen track 
```
{
action: "screen"
context_module: "priceDatabaseLanding"
context_screen_owner_type: "priceDatabase"
}
```
Filter Change
```
{
action_type: "priceDatabaseFilterParamsChanged"
changed: "{sizes: MEDIUM}"
context_module: "priceDatabaseLanding"
context_owner_type: "priceDatabase"
current: "{\"organizations\":[],\"categories\":[\"Painting\"],\"sizes\":[]}"
}
```
Click on Search
```
{
action: "searchedPriceDatabase"
context_module: "priceDatabaseLanding"
context_owner_type: "priceDatabase"
destination_owner_slug: …
```

Enhancement:[CX-1836] Add tracking to price db page 

---

src/v2/Apps/Order/Routes/Shipping/index.tsx
src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx

This PR fixes an error message that we show if something went wrong on the Arta side.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4574

fix(PX-4574): fix Arta error message

---

src/v2/Apps/PriceDatabase/PriceDatabase.tsx

This PR adds new lines between price database sections and primarily exists to create a new Deploy PR.

chore: Add new lines between price database sections

---

package.json
yarn.lock

Revert "chore(deps): update dep typescript from 4.3.5 to v4.4.3"

---

src/v2/Components/Inquiry/Hooks/useArtworkInquiryRequest.ts
src/v2/Components/Inquiry/Views/InquiryLogin.tsx
src/v2/Components/Inquiry/Views/InquiryResetPassword.tsx
src/v2/Components/Inquiry/Views/InquirySignUp.tsx
src/v2/Components/Inquiry/__tests__/Views/InquiryLogin.jest.tsx
src/v2/Components/Inquiry/__tests__/Views/InquiryResetPassword.jest.tsx
src/v2/Components/Inquiry/__tests__/Views/InquirySignUp.jest.tsx
src/v2/__generated__/useArtworkInquiryRequestMutation.graphql.ts

I'll add specs on Monday. Waiting on https://github.com/artsy/cohesion/pull/238 as well as some updates to the auth event types.

fix(inquiry): adds preliminary inquiry analytics tracking

---

src/v2/Components/Inquiry/Views/InquiryLogin.tsx
src/v2/Components/Inquiry/__tests__/Views/InquiryLogin.jest.tsx
src/v2/Utils/__tests__/auth.jest.ts
src/v2/Utils/auth.ts

Implements the same as in https://github.com/artsy/force/pull/8355

fix(inquiry): adds support for on-demand auth

---

src/v2/Apps/Order/Routes/Shipping/index.tsx

[PX-4590](https://artsyproduct.atlassian.net/browse/PX-4590)
Copy change: "Shipping options" --> "Artsy Shipping options"

fix(PX4590): Change shipping options to artsy shipping options

---

src/v2/Components/Inquiry/Components/InquiryAffiliatedAutocomplete.tsx
src/v2/Components/Inquiry/Views/InquiryInquiry.tsx
src/v2/Components/Inquiry/config.ts
src/v2/Components/LocationAutocompleteInput.tsx

Some minor tweaks to support https://github.com/artsy/integrity/pull/250

fix(inquiry): integrity tweaks

---

src/v2/Apps/Home/Components/HomeCurrentFairsRail.tsx
src/v2/Apps/Home/Components/HomeFeaturedShow.tsx
src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitsLarge.tsx
src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnitsSmall.tsx

Addresses QA feedback on new home page refactor. 
Addresses:

chore: [Home] Address QA 

---

src/v2/Apps/Order/Routes/Shipping/index.tsx

This PR adds dot to the end of the error message.
JIRA - https://artsyproduct.atlassian.net/browse/PX-4574

fix(PX-4574): add dot

---

src/v2/Apps/Shows/Components/ShowsCurrentShows.tsx
src/v2/Apps/Shows/Routes/ShowsCity.tsx
src/v2/Apps/Shows/Routes/__tests__/ShowsCity.jest.tsx
src/v2/Apps/Shows/showsRoutes.tsx
src/v2/Utils/Hooks/useScrollTo.ts
src/v2/Utils/scrollHelpers.ts
src/v2/__generated__/ShowsCityQuery.graphql.ts
src/v2/__generated__/ShowsCity_city.graphql.ts
src/v2/__generated__/ShowsCurrentShowsQuery.graphql.ts
src/v2/__generated__/showsRoutes_ShowsCityQuery.graphql.ts

Also takes care of [DSWGW-92](https://artsyproduct.atlassian.net/browse/DSWGW-92) cc @tr-ann
I need to follow this up with another PR where we support `?page=n` URL params, but need to make another change in Metaphysics to support.

feat(shows2): adds pagination

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/SubmissionLayout.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/v2/Apps/Consign/consignRoutes.tsx

Jira Ticket:ticket: : [SWA-7](https://artsyproduct.atlassian.net/browse/SWA-7)
This PR creates new routes for new submission flow:
https://user-images.githubusercontent.com/55637696/135835036-c09a70a7-53a8-4bd3-b5e0-14bd94fd8b26.mov

feat(SWA-7): Create initial routes for the submission flow [WIP]

---

package.json
src/v2/Utils/Hooks/__tests__/useDialog.jest.tsx
src/v2/Utils/Hooks/__tests__/useLazyLoadComponent.jest.tsx
yarn.lock

- Adds React Testing Library Hooks dev dependency
- Provides 2 test examples using the library
Related to #8484

test(hooks): Add RTL hooks

---

src/v2/Apps/Shows/Routes/ShowsCity.tsx
src/v2/Apps/Shows/showsRoutes.tsx
src/v2/__generated__/ShowsCityQuery.graphql.ts
src/v2/__generated__/ShowsCity_city.graphql.ts
src/v2/__generated__/showsRoutes_ShowsCityQuery.graphql.ts

This PR adds support to current shows pagination such that the page param updates on click and full page reloads point to the correct page.

feat(shows2): supports page param

---

package.json
src/v2/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionsRail.jest.tsx
src/v2/Apps/Show/__tests__/ShowInstallShots.jest.tsx
src/v2/Apps/Shows/Components/ShowsHeader.tsx
src/v2/Apps/Shows/Routes/ShowsCity.tsx
src/v2/Apps/Shows/Routes/ShowsIndex.tsx
src/v2/System/Router/RouterLink.tsx
src/v2/__generated__/ShowsCityQuery.graphql.ts
src/v2/__generated__/ShowsCity_Test_Query.graphql.ts
src/v2/__generated__/ShowsCity_city.graphql.ts
src/v2/__generated__/showsRoutes_ShowsCityQuery.graphql.ts
yarn.lock

This PR adds support for the "Online Exclusive" shows

feat(shows2): supports online shows

---

src/v2/Apps/Home/Components/HomeCurrentFairs.tsx
src/v2/Apps/Home/Components/HomeTrendingArtistsRail.tsx
src/v2/Apps/Home/HomeApp.tsx
src/v2/Apps/Home/__tests__/HomeCurrentFairs.jest.tsx
src/v2/Components/Rail/Rail.tsx
src/v2/Components/Rail/RailHeader.tsx
src/v2/Components/Rail/__tests__/Rail.jest.tsx
src/v2/Components/Rail/index.tsx
src/v2/__generated__/HomeCurrentFairsQuery.graphql.ts
src/v2/__generated__/HomeCurrentFairs_Test_Query.graphql.ts
src/v2/__generated__/HomeCurrentFairs_viewer.graphql.ts

Adds a new component that wraps common items in our carousels that have seen much duplication across our pages. 
**API**: 
```tsx
<Rail
title="Trending Artists on Artsy"
countLabel={20} 
viewAllLabel="View All Artists"
viewAllHref="/artists"
viewAllOnClick={() => { ... }}
getItems={() => { ... }}
/>
```

feat(Rail): Add new <Rail /> component 

---

src/v2/Components/Rail/RailHeader.tsx
src/v2/Components/Rail/__stories__/Rail.story.tsx

Adds missing storybook file for `<Rail>`

feat(Rail): Add Rail storybook entry

---

src/v2/Apps/Consign/Components/SubmissionStepper.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/v2/Apps/Consign/consignRoutes.tsx

Jira Ticket:ticket: : [SWA-11](https://artsyproduct.atlassian.net/browse/SWA-11)
This PR adds  `SubmissionStepper` for the new submission flow. Also added redirect from `/consign/submission2` to `/consign/submission2/artwork-details`
https://user-images.githubusercontent.com/55637696/135874371-0beada1f-2849-4e01-847a-a50673410bbb.mov

feat(SWA-11): Add stepper for the submission flow

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutosuggest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutosuggest.jest.tsx

Jira Ticket:ticket: : [SWA-44](https://artsyproduct.atlassian.net/browse/SWA-44)
This PR adds the tests for the Artist field.

feat(SWA-44): Write unit tests for artist field on artwork step

---

src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/PhotoDropzone.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/PhotoDropzone.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/fileUtils.jest.ts

This PR adds unit tests for the upload photos step.
JIRA - https://artsyproduct.atlassian.net/browse/SWA-30

feat(SWA-30) add unit tests for the upload photos step

---

yarn.lock

Update Artsy-eigen-web-association to ignore price-database
Follow-up on https://github.com/artsy/artsy-eigen-web-association/pull/40

chore(CX-2113): update artsy-eigen-web-association to ignore price-database

---

src/v2/Apps/Order/Routes/Status/index.tsx

Super minor PR using the refactor that we did in Exchange.

chore(PX-4677): small refactor to account for displayState being capitalized on Exchange side now

---

src/v2/Apps/Consign/Components/SubmissionStepper.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmission.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts
src/v2/Utils/Hooks/useAuthIntent/index.ts

Jira Ticket:ticket: : [SWA-78](https://artsyproduct.atlassian.net/browse/SWA-78)
This PR returns the `Contact Information` step in the `Submission flow`

feat(SWA-78): Reintroduce contact information step to submission flow

---

src/v2/Apps/Partners/Components/PartnersLocationAutocomplete.tsx
src/v2/__generated__/PartnersLocationAutocompleteQuery.graphql.ts
src/v2/__generated__/PartnersLocationAutocomplete_Test_Query.graphql.ts
src/v2/__generated__/PartnersLocationAutocomplete_viewer.graphql.ts

Closes [GRO-647](https://artsyproduct.atlassian.net/browse/GRO-647)

fix(partners): location autocomplete serves all locations

---

src/v2/Apps/Artwork/Server/handleArtworkImageDownload.ts

Oops, we want an original image here!

fix(artwork): normalized image -> original

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx

Jira Ticket:ticket: : [SWA-66](https://artsyproduct.atlassian.net/browse/SWA-66)
This PR deletes input errors from the `Contact Information` step in the `Submission flow` 
https://user-images.githubusercontent.com/55637696/140101323-d27214fc-63ae-401e-a1d8-7143aa8a41c5.mov

feat(SWA-66): "Contact Information" error messages need to be consistent

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

Ticket: [SWA-51](https://artsyproduct.atlassian.net/browse/SWA-51)
This PR handles the case where user types spaces in contact information step's email input. The spaces are simply trimmed before pushed to formik's event handler. 
https://user-images.githubusercontent.com/42584148/140296986-81d23465-7c45-4b91-b0dd-2c5cabe9c1af.mov

[Feat]: SWA-51/Trim email address

---

src/v2/Apps/Order/Routes/Offer/index.tsx
src/v2/Apps/Order/Routes/Respond/index.tsx
src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
src/v2/Apps/__tests__/Fixtures/Order.ts
src/v2/DevTools/createTestEnv.tsx
src/v2/__generated__/OfferTestQuery.graphql.ts
src/v2/__generated__/Offer_order.graphql.ts
src/v2/__generated__/RespondCounterOfferMutation.graphql.ts
src/v2/__generated__/RespondTestQuery.graphql.ts
src/v2/__generated__/Respond_order.graphql.ts
src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
src/v2/__generated__/orderRoutes_RespondQuery.graphql.ts

Revert "fix: show no modal message when collector submits offer on unlisted price artworks"

---

src/v2/Apps/Home/Components/HomeFeaturedEventsRail.tsx
src/v2/__generated__/HomeApp_Test_Query.graphql.ts
src/v2/__generated__/HomeFeaturedEventsRail_orderedSet.graphql.ts
src/v2/__generated__/homeRoutes_HomeQuery.graphql.ts

Minor thing — other day noticed a very poor quality image on this rail. We weren't using the largest possible source versions so this changes that to prefer them.

chore(home): use higher resolution image versions

---

cypress/integration/artist.spec.js
src/v2/Apps/Artist/Routes/WorksForSale/ArtistWorksForSaleRoute.tsx
src/v2/Apps/Artist/Utils/__tests__/computeTitle.jest.tsx
src/v2/Apps/Artist/Utils/computeTitle.ts

Solves: https://artsyproduct.atlassian.net/browse/GRO-635
I wasn't sure if it was overkill to add a Cypress test here, so I just left things at a unit test.

feat(GRO-635): Add unique title on for sale page

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/v2/__generated__/ContactInformationTestQuery.graphql.ts

Jira Ticket:ticket: : [SWA-42](https://artsyproduct.atlassian.net/browse/SWA-42)
This PR adds the tests for the `Contact information` step.

feat(SWA-42): Write unit tests for contact information form

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutosuggest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutosuggest.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/UploadPhotosForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/fileUtils.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/fileUtils.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/uploadFileToS3.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

Tickets: [SWA-49](https://artsyproduct.atlassian.net/browse/SWA-49) & [SWA-79](https://artsyproduct.atlassian.net/browse/SWA-79)
This PR handles with api errors in consignment flow, namely the cases of: 
- autosuggest api call failure, when artist name type in the 1st step
- image upload failure in the 2nd step 
- submission failure (on network or application)
https://user-images.githubusercontent.com/42584148/140051559-a6d7e3ba-0013-46a1-9f77-64b7262c803c.mov
https://user-images.githubusercontent.com/42584148/140051613-7dbb02ea-02a6-49b2-b347-9d7b54d2f85b.mov
https://user-images.githubusercontent.com/42584148/140051647-53f61b10-5236-4415-bee6-684227e0afdb.mov

[Feat]: Swa-79 / handle consignment api errs

---

src/v2/Apps/Partners/Components/PartnersFilteredCells.tsx
src/v2/Apps/Partners/Components/PartnersLocationAutocomplete.tsx
src/v2/Apps/Partners/Components/PartnersSpecialtyAutocomplete.tsx
src/v2/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
src/v2/__generated__/CreateCreditCardAndUpdatePhoneMutation.graphql.ts
src/v2/__generated__/PartnersFilteredCellsQuery.graphql.ts
src/v2/__generated__/PartnersFilteredCells_viewer.graphql.ts
src/v2/__generated__/PartnersSpecialtyAutocompleteQuery.graphql.ts
src/v2/__generated__/PartnersSpecialtyAutocomplete_Test_Query.graphql.ts
src/v2/__generated__/PartnersSpecialtyAutocomplete_viewer.graphql.ts
src/v2/__generated__/UpdateUserInformationMutation.graphql.ts
src/v2/__generated__/UserEmailPreferencesMutation.graphql.ts
src/v2/__generated__/useUpdateMyUserProfileMutation.graphql.ts

Closes: [GRO-651](https://artsyproduct.atlassian.net/browse/GRO-651)
https://user-images.githubusercontent.com/112297/140542924-241f6efc-a89c-477c-ab0d-16ad2b0e8bf3.mov

feat(partners): implements pagination on filtered results

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/PhotoDropzone.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/UploadPhotosForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

This PR removes errors on the uploading photos step after new uploading started.
JIRA - https://artsyproduct.atlassian.net/browse/SWA-95
https://user-images.githubusercontent.com/79979820/140738859-4cbb944a-67e6-4a3f-a878-15725c42a43f.mov

feat(SWA-95): remove errors after new uploading

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/useSubmission.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

Jira Ticket:ticket: : [SWA-97](https://artsyproduct.atlassian.net/browse/SWA-97)
[WIP] because of question about placeholder
This PR adds a new field `Provenance` to the `ArtworkDetailsForm`
https://user-images.githubusercontent.com/55637696/140756675-e5e7c746-3dc3-499d-912b-eb62ab940e95.mov

feat(SWA-97): Provenance field on the Artwork Details page

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutosuggest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutosuggest.jest.tsx

This PR adds debounce function for the artist autosuggest to prevent unnecessary API calls.
JIRA - https://artsyproduct.atlassian.net/browse/SWA-83
https://user-images.githubusercontent.com/79979820/140496881-370637a4-ad5a-4672-b15f-74ecebb6e3f2.mov

feat(SWA-83): add debounce for the artist autosuggest

---

src/v2/Apps/Purchase/Components/OrderRow.tsx
src/v2/Apps/Purchase/Utils/orderHelper.tsx
src/v2/Apps/Purchase/__tests__/PurchaseApp.jest.tsx
src/v2/Apps/Purchase/__tests__/orderHelper.jest.tsx
src/v2/Apps/__tests__/Fixtures/Order.ts
src/v2/__generated__/OrderRow_order.graphql.ts
src/v2/__generated__/PurchaseAppTestQuery.graphql.ts
src/v2/__generated__/PurchaseHistoryQuery.graphql.ts
src/v2/__generated__/purchaseRoutes_PurchaseQuery.graphql.ts

This should have no changes on user front but does shuffles code around. Tagging couple of initial developers here for a review.

refactor(PX-4655) - use displayState for calculating statuses on Purchase app

---

src/v2/Components/NavBar/NavBar.tsx
src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
src/v2/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
src/v2/Components/NavBar/__tests__/NavBar.jest.tsx

Jira: [CX-1919](https://artsyproduct.atlassian.net/browse/CX-1919)
This tasks involves adding a new navbar item (Price Database) pointing at `/price-database`
- adds `Price Database` to both navbar and navbar mobile menu
- hides navbar items `Buy` and `Editorial` from the navbar between 900px & 768px
<div>
</div>

[DO NOT MERGE] feat(CX-1919): add Price Database link to navbar

---

src/v2/Apps/Artist/Routes/CV/ArtistCVRoute.tsx

Closes [GRO-662](https://artsyproduct.atlassian.net/browse/GRO-662)

fix(artist): corrects copy

---

src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
src/v2/Apps/PriceDatabase/Components/PriceDatabaseSearch.tsx

Updates some marketing copy on the price database page.

chore: marketing copy updates #trivial

---

src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/SettingsEditProfileArtistsYouCollect.tsx
src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/SettingsEditProfileArtistsYouCollectRemoveButton.tsx
src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/useAddArtistYouCollect.ts
src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/useRemoveArtistYouCollect.tsx
src/v2/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileYourGalleryIntro.tsx
src/v2/Apps/Settings/Routes/EditProfile/Components/__tests__/SettingsEditProfileYourGalleryIntro.jest.tsx
src/v2/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
src/v2/__generated__/SettingsEditProfileArtistsYouCollectAutocompleteQuery.graphql.ts
src/v2/__generated__/SettingsEditProfileArtistsYouCollect_me.graphql.ts
src/v2/__generated__/SettingsEditProfileRoute_me.graphql.ts
src/v2/__generated__/SettingsEditProfileYourGalleryIntro_Test_Query.graphql.ts
src/v2/__generated__/SettingsEditProfileYourGalleryIntro_me.graphql.ts
src/v2/__generated__/settingsRoutes_EditProfileRouteQuery.graphql.ts
src/v2/__generated__/useAddArtistYouCollectMutation.graphql.ts
src/v2/__generated__/useRemoveArtistYouCollectMutation.graphql.ts

Closes [GRO-596](https://artsyproduct.atlassian.net/browse/GRO-596)
This PR finishes off the edit profile settings page by implementing the "Artists You Collect" & "Your Gallery Intro"
https://user-images.githubusercontent.com/112297/141371339-47e54523-0652-4c0c-ad1a-ca2b75643c91.mov

feat(settings): implements artists you collect/gallery intro

---

src/v2/Apps/PriceDatabase/Components/PriceDatabaseMeta.tsx

Updating some metadata values for this page!
https://artsyproduct.atlassian.net/browse/GRO-660

chore(GRO-660): Change metadata for Price Database

---

src/v2/Apps/Partners/Components/PartnersRail.tsx
src/v2/Apps/Partners/Components/PartnersRails.tsx
src/v2/System/Relay/SystemQueryRenderer.tsx
src/v2/__generated__/PartnersRailQuery.graphql.ts
src/v2/__generated__/PartnersRail_partnerCategory.graphql.ts
src/v2/__generated__/PartnersRailsQuery.graphql.ts
src/v2/__generated__/PartnersRails_viewer.graphql.ts

This PR further optimizes the lazily loaded rails by lazily loading each individual rail instead of in just a big block.

feat(partners): lazily load individual rails

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx

Jira Ticket:ticket: : [SWA-121](https://artsyproduct.atlassian.net/browse/SWA-121)
[WIP] because of copy question in Jira.
This PR adds the `Provenance modal` to  the `ArtworkDetailsForm` in the `Submission flow`
https://user-images.githubusercontent.com/55637696/141800038-8d8d8014-ad7d-473b-97c4-697f26b37be2.mov

feat(SWA-121): Provenance modal

---

src/v2/Apps/Home/Components/HomeFeaturedGalleriesRail.tsx
src/v2/__generated__/HomeFeaturedGalleriesRailQuery.graphql.ts

Closes: [GRO-670](https://artsyproduct.atlassian.net/browse/GRO-670)

feat(home): updates set id for homepage featured galleries rail

---

src/v2/Apps/Order/Routes/Review/index.tsx

Resolves NX-3020 
Removes "Please note that all offers are binding."

fix: NX-3020 remove text

---

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
src/v2/Apps/Settings/Routes/Saves/Components/SettingsSavesArtists.tsx
src/v2/Apps/Settings/Routes/Saves/Components/SettingsSavesArtworks.tsx
src/v2/Apps/Settings/Routes/Saves/Components/__tests__/SettingsSavesArtists.jest.tsx
src/v2/Apps/Settings/Routes/Saves/Components/__tests__/SettingsSavesArtworks.jest.tsx
src/v2/Apps/Settings/Routes/Saves/SettingsSavesRoute.tsx
src/v2/Apps/Settings/settingsRoutes.tsx
src/v2/Components/ArtistRail.tsx
src/v2/Components/Artwork/GridItem.tsx
src/v2/__generated__/ArtistRailQuery.graphql.ts
src/v2/__generated__/ArtistRail_artist.graphql.ts
src/v2/__generated__/SettingsSavesArtistsQuery.graphql.ts
src/v2/__generated__/SettingsSavesArtists_me.graphql.ts
src/v2/__generated__/SettingsSavesArtworksQuery.graphql.ts
src/v2/__generated__/SettingsSavesArtworks_me.graphql.ts
src/v2/__generated__/settingsRoutes_SettingsQuery.graphql.ts

This implements the top half of the page.
Remaining are followed categories and partners. Will switch to the Metaphysics work for both before continuing.
https://user-images.githubusercontent.com/112297/142468998-99117981-5ced-4b5e-b283-1616156ffed5.mov

feat(GRO- 595): /settings2/saves

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/v2/Components/Authentication/Types.ts
src/v2/Utils/Hooks/useAuthIntent/index.ts

Jira Ticket:ticket: : [SWA-128](https://artsyproduct.atlassian.net/browse/SWA-128)
~[WIP] because we should wait until [this ticket](https://github.com/artsy/convection/pull/1163) been merged~
This PR removes the login modal from the submission flow.

feat(SWA-128): Remove login modal from the contact information step

---

src/v2/Components/Footer/FooterDownloadAppBanner.tsx

Closes [GRO-655](https://artsyproduct.atlassian.net/browse/GRO-655)

feat(footer): updates to new image

---

packages/publish/uploadToS3.js

Add the progress status and time taken to the upload to S3 task to
enabled a better understanding of which file take the longest.

feature: Upload Progress

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/SubmissionLayout.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/useErrorModal.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/useErrorModal.tsx

Ticket: [SWA-118](https://artsyproduct.atlassian.net/browse/SWA-118) 
This PR creates a custom hook for rendering an error modal, to be used across all sections of consign app. Currently the hook is used in 2 steps where we have API calls. 
When we implement draft submissions after each step, we'll be able to utilise this hook on each step.

[Feat]: AlicanAkyuz/swa-118/create error modal hook

---

src/v2/Apps/Settings/Routes/Saves/Components/SettingsSavesArtists.tsx
src/v2/Apps/Settings/Routes/Saves/Components/SettingsSavesArtworks.tsx
src/v2/Apps/Settings/Routes/Saves/Components/SettingsSavesCategories.tsx
src/v2/Apps/Settings/Routes/Saves/Components/__tests__/SettingsSavesCategories.jest.tsx
src/v2/Apps/Settings/Routes/Saves/SettingsSavesRoute.tsx
src/v2/Components/CategoryRail.tsx
src/v2/__generated__/CategoryRailQuery.graphql.ts
src/v2/__generated__/CategoryRail_category.graphql.ts
src/v2/__generated__/SettingsSavesCategoriesQuery.graphql.ts
src/v2/__generated__/SettingsSavesCategories_me.graphql.ts

Adds the followed categories (genes) rails.
https://user-images.githubusercontent.com/112297/143098035-41f54c93-3fa8-48fb-8d6a-b5502ce05c71.mov

feat(GRO-595): followed categories

---

src/v2/Apps/Consign/Components/SubmissionStepper.tsx

Jira Ticket:ticket: : [SWA-127](https://artsyproduct.atlassian.net/browse/SWA-127)
This PR updates Stepper headings for SWA mobile flow

feat(SWA-127): Update Stepper headings for SWA mobile flow

---

package.json
webpack/envs/clientDevelopmentConfig.js
webpack/envs/clientProductionConfig.js
webpack/envs/legacyDevelopmentConfig.js
webpack/envs/legacyProductionConfig.js
webpack/envs/legacySharedConfig.js
webpack/envs/serverConfig.js
webpack/envs/sharedPlugins.js
webpack/index.js
webpack/utils/env.js
webpack/utils/getCSSManifest.js
webpack/utils/log.js
yarn.lock

Adds commands that generate clean webpack statistics for all assets.
Additionally, cleaning up webpack plugin instantiation as constructing a
plugin may have unintended side effects.

feature: Webpack Stats

---

src/v2/Apps/Unsubscribe/Components/UnsubscribeLoggedIn.tsx

Jira ticket: [FX-3576]
|Large|Medium|Small|
|-|-|-|
|![image](https://user-images.githubusercontent.com/3513494/143622997-e741dedb-11cf-4224-b416-d4b4069f8e70.png)|![image](https://user-images.githubusercontent.com/3513494/143623024-fe21172e-1633-48e8-8611-fe8b63488fb5.png)|![image](https://user-images.githubusercontent.com/3513494/143623049-5110c086-0200-47fc-81fe-f7c82b928e54.png)|
[FX-3576]: https://artsyproduct.atlassian.net/browse/FX-3576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-3576): full width for "unsubscribe" button on small devices

---

src/v2/Apps/Partners/Components/PartnersFeaturedCarouselCell.tsx
src/v2/Components/ArtworkFilter/__tests__/FiltersPills.jest.tsx
src/v2/__generated__/GalleriesRouteFragmentContainer_Test_Query.graphql.ts
src/v2/__generated__/InstitutionsRouteFragmentContainer_Test_Query.graphql.ts
src/v2/__generated__/PartnersFeaturedCarouselCell_profile.graphql.ts
src/v2/__generated__/PartnersFeaturedCarousel_Test_Query.graphql.ts
src/v2/__generated__/partnersRoutes_GalleriesRouteQuery.graphql.ts
src/v2/__generated__/partnersRoutes_InstitutionsRouteQuery.graphql.ts

Embarrassingly, this shipped without being clickable.

fix(partners): adds links to hero units

---

src/v2/Apps/Settings/Routes/Saves/Components/SettingsSavesProfiles.tsx
src/v2/Apps/Settings/Routes/Saves/Components/__tests__/SettingsSavesProfiles.jest.tsx
src/v2/Apps/Settings/Routes/Saves/SettingsSavesRoute.tsx
src/v2/Components/EntityHeaders/FairEntityHeader.tsx
src/v2/Components/EntityHeaders/FairOrganizerEntityHeader.tsx
src/v2/Components/EntityHeaders/PartnerEntityHeader.tsx
src/v2/Components/EntityHeaders/PlaceholderEntityHeader.tsx
src/v2/__generated__/FairEntityHeader_fair.graphql.ts
src/v2/__generated__/FairOrganizerEntityHeader_fairOrganizer.graphql.ts
src/v2/__generated__/PartnerEntityHeader_partner.graphql.ts
src/v2/__generated__/SettingsSavesProfilesQuery.graphql.ts
src/v2/__generated__/SettingsSavesProfiles_me.graphql.ts

Closes [GRO-595](https://artsyproduct.atlassian.net/browse/GRO-595)
This finally closes out the ticket, adding the last piece to the page.

feat(GRO-595): adds followed profiles

---

src/mobile/components/layout/bootstrap.js

https://artsy.slack.com/archives/CA8SANW3W/p1638375400188200
In an un-related [PR](https://github.com/artsy/force/pull/8853), I have an update to this file and notice that `git commit` converts the file to typescript (?). The conversion has no relationship to the work in that PR, so I thought it best to PR the conversion here without any actual code changes.

feat: linter convert mobile bootstrap

---

src/v2/Apps/Settings/Routes/Purchases/Components/SettingsPurchases.tsx
src/v2/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
src/v2/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx
src/v2/Apps/Settings/Routes/Purchases/SettingsPurchasesRoute.tsx
src/v2/Apps/Settings/SettingsApp.tsx
src/v2/Components/Pagination/CommercePagination.tsx
src/v2/Components/Pagination/index.tsx
src/v2/__generated__/CommercePagination_pageCursors.graphql.ts
src/v2/__generated__/SettingsPurchasesQuery.graphql.ts
src/v2/__generated__/SettingsPurchasesRoute_me.graphql.ts
src/v2/__generated__/SettingsPurchasesRow_order.graphql.ts
src/v2/__generated__/SettingsPurchases_Test_Query.graphql.ts
src/v2/__generated__/SettingsPurchases_me.graphql.ts

Closes [GRO-597](https://artsyproduct.atlassian.net/browse/GRO-597)

feat(GRO-597): Order history

---

src/typings/sharify.d.ts
src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsPassword.tsx
src/v2/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
src/v2/Apps/Settings/Routes/EditSettings/useUpdateSettingsPassword.ts
src/v2/Utils/__tests__/auth.jest.ts
src/v2/Utils/auth.ts
src/v2/__generated__/useUpdateSettingsPasswordMutation.graphql.ts

Quickly implements the UI for password update module. I need to implement the mutation in Metaphysics to wire this up. Will wait on https://github.com/artsy/force/pull/8990 to merge because there will likely be some conflicts.

feat(GRO-683): implements password module

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/PhoneNumberInput.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/PhoneNumberInput.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/phoneNumberUtils.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
src/v2/__generated__/ContactInformationTestQuery.graphql.ts
src/v2/__generated__/ContactInformation_me.graphql.ts
src/v2/__generated__/consignRoutes_ContactInformationQuery.graphql.ts
src/v2/__generated__/phoneNumberUtils_PhoneNumber_Query.graphql.ts

This PR adds phone number validation for the contact information step.
JIRA - https://artsyproduct.atlassian.net/browse/SWA-60

fix(SWA-60): add phone number validation

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx

Add log for the error that happen on the contact information step

feat: show error for submission creation

---

src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactor.tsx
src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactorBackupCodes.tsx
src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactorBackupCodesDialog.tsx
src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/index.ts
src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/useCreateSettingsBackupSecondFactorsMutation.ts
src/v2/Apps/Settings/Routes/EditSettings/Components/__tests__/SettingsEditSettingsTwoFactor.jest.tsx
src/v2/__generated__/SettingsEditSettingsTwoFactorBackupCodesDialogQuery.graphql.ts
src/v2/__generated__/SettingsEditSettingsTwoFactorBackupCodesDialog_me.graphql.ts
src/v2/__generated__/SettingsEditSettingsTwoFactorBackupCodes_me.graphql.ts
src/v2/__generated__/SettingsEditSettingsTwoFactor_Test_Query.graphql.ts
src/v2/__generated__/SettingsEditSettingsTwoFactor_me.graphql.ts
src/v2/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
src/v2/__generated__/useCreateSettingsBackupSecondFactorsMutation.graphql.ts

Closes [GRO-690](https://artsyproduct.atlassian.net/browse/GRO-690)
Ports over the simplest of these modules.

fix(GRO-690): ports over backup codes module

---

src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx
src/v2/Components/ArtworkFilter/Utils/__tests__/getSelectedFiltersCounts.jest.ts
src/v2/Components/ArtworkFilter/Utils/getSelectedFIltersCounts.ts
src/v2/Components/ArtworkFilter/index.tsx

Jira: [FX-3617](https://artsyproduct.atlassian.net/browse/FX-3617)
Display total count of filters at top of artwork grid in line with the current app experience
- add helper to count filters
- add tests for that
https://user-images.githubusercontent.com/56556580/144445982-b7583d05-29e0-42c9-bc06-b6221c9eddce.mov

(FX-3617): total count of filters

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/LocationAutocomplete.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/LocationAutocomplete.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/useSubmission.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

This PR  temporarily switches off the `Location field` in submission flow in Force

fix: (SWA) Temporarily switch-off Location field

---

src/v2/Apps/Consign/Components/SubmissionStepper.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/PhoneNumberInput.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/PhoneNumberInput.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/SubmissionLayout.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/PhotoDropzone.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/UploadPhotosForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/useErrorModal.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmission.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/phoneNumberUtils.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/useErrorModal.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
src/v2/Components/Authentication/Types.ts
src/v2/Utils/Hooks/useAuthIntent/index.ts
src/v2/Utils/recaptcha.ts
src/v2/__generated__/ContactInformationTestQuery.graphql.ts
src/v2/__generated__/ContactInformation_me.graphql.ts
src/v2/__generated__/consignRoutes_ContactInformationQuery.graphql.ts
src/v2/__generated__/phoneNumberUtils_PhoneNumber_Query.graphql.ts

JIRA - https://artsyproduct.atlassian.net/browse/SWA-99
Test env - https://submission-flow.artsy.net/

[WIP]feat(SWA-99): Anonymous submissions

---

src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx

New behavior:
https://user-images.githubusercontent.com/30025439/144517193-e14dd232-6805-430f-9cbb-1a4fb55578b4.mov

GRO-544: Hover state added for Home Page Article Cards

---

src/v2/Utils/countries.ts

This PR fixes the wrong text for some countries.
JIRA - https://artsyproduct.atlassian.net/browse/SWA-163

fix(SWA-163): fix country codes

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createConsignSubmissionInput.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

This PR adds location input to the submission flow.

feat(SWA): add location input

---

src/v2/Apps/Home/Components/HomeCurrentFairs.tsx
src/v2/Apps/Home/Components/HomeFeaturedMarketNews.tsx
src/v2/Apps/Home/Components/HomeTrendingArtistsRail.tsx
src/v2/Components/Rail/RailHeader.tsx

New Behavior:
https://user-images.githubusercontent.com/30025439/145096403-cea9fa79-f3bf-456a-80a9-866d00eda3f3.mov

GRO-548: [Mobile] Trending Artists on Artsy - CTA link is wrapping

---

src/v2/Apps/Consign/Components/SubmissionStepper.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx

Jira Ticket:ticket: : [SWA-153](https://artsyproduct.atlassian.net/browse/SWA-153)
Jira Ticket:ticket: : [SWA-154](https://artsyproduct.atlassian.net/browse/SWA-154)
This PR updates copy for Rarity and Provenance fields in the `Submission flow`,  deletes forgotten TODO comment.

fix(SWA-153, SWA-154): Copy updates

---

src/v2/Apps/Auction/Components/BidForm.tsx
src/v2/Apps/Auction/Components/CreditCardInstructions.tsx
src/v2/Apps/Auction/Components/LotInfo.tsx
src/v2/Apps/Auction/Components/PricingTransparency.tsx
src/v2/Apps/Auction/Routes/ConfirmBid/index.tsx
src/v2/Apps/Auction/Routes/__tests__/ConfirmBid.jest.tsx
src/v2/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
src/v2/Components/Auction/ConditionsOfSaleCheckbox.tsx
src/v2/Components/CountrySelect.tsx

This updates the bid form to Palette V3:

chore(palette-v3): Migrate BidForm to v3

---

.eslintrc.js
src/v2/Components/ConfirmPasswordModal/index.tsx
src/v2/Components/PasswordInput.tsx
src/v2/Utils/Hooks/useMutation.ts

Just pulling off some of the useful SHAs from my working branch. Going to start over with a much lighter touch (I think our options are minimally invasive surgery vs rewrite from original spec). Opting for minimally invasive surgery.

fix(GRO-688): 2fa progress

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

Jira Ticket:ticket: : [SWA-151](https://artsyproduct.atlassian.net/browse/SWA-151)
This PR makes the `Provenance` field required and deletes an unnecessary Optional label.
https://user-images.githubusercontent.com/55637696/145821741-17e4c393-0281-41b1-8903-4837f0fbf094.mov

fix(SWA-151): The provenance field should be a required field

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx

Jira Ticket:ticket: : [SWA-171](https://artsyproduct.atlassian.net/browse/SWA-171)
Design 🎨  : [Figma](https://www.figma.com/file/mcQv2yvaXiacFKZbC74BE0/SWA-Submissions-Flow?node-id=2973%3A22947)
This PR fixes the spaces between fields in the mobile web view on the Artwork details step in the Submission flow
https://user-images.githubusercontent.com/55637696/145983501-3deee85f-7782-4403-8a20-2964ba537884.mov

fix(SWA-171): [MWeb] Artwork details: different spaces between input fields in form

---

src/v2/Apps/Partner/Components/PartnerShows/ShowBanner.tsx
src/v2/__generated__/ShowBanner_Test_Query.graphql.ts
src/v2/__generated__/ShowBanner_show.graphql.ts
src/v2/__generated__/ShowBannersRailRendererQuery.graphql.ts
src/v2/__generated__/partnerRoutes_ShowsQuery.graphql.ts

We recently added a `normalized` version to these images; but for whatever reason these were mostly favoring `large`. I should make an update in Force to do this by default but for now this fixes the quality issues for these.
(Also really need to prioritize the V3 migration of this app)

fix(partner): improves image quality

---

src/v2/Apps/Auction/Components/Form/helpers.tsx

The force component of per: https://artsyproduct.atlassian.net/jira/software/c/projects/BID/boards/106?modal=detail&selectedIssue=BID-119&search=119

chore:update copy on reserve not met error to improve clarity

---

.eslintrc.js
src/lib/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts
src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx
src/v2/Apps/Settings/Routes/EditSettings/Components/__tests__/SettingsEditSettingsLinkedAccounts.jest.tsx
src/v2/Apps/Settings/Routes/EditSettings/Components/useUnlinkSettingsLinkedAccount.ts
src/v2/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx
src/v2/__generated__/SettingsEditSettingsLinkedAccounts_Test_Query.graphql.ts
src/v2/__generated__/SettingsEditSettingsLinkedAccounts_me.graphql.ts
src/v2/__generated__/SettingsEditSettingsRoute_me.graphql.ts
src/v2/__generated__/settingsRoutes_SettingsEditSettingsRouteQuery.graphql.ts
src/v2/__generated__/useUnlinkSettingsLinkedAccountMutation.graphql.ts

Closes [GRO-684](https://artsyproduct.atlassian.net/browse/GRO-684)

feat(GRO-684): settings linked accounts module

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/__generated__/ContactInformation_submission.graphql.ts
src/v2/__generated__/consignRoutes_submissionQuery.graphql.ts

Jira Ticket:ticket: : [SWA-113](https://artsyproduct.atlassian.net/browse/SWA-113)

[WIP] feat(SWA-113): Add an update-submission mutation request to the contact information step

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/PhotoThumbnail.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/UploadPhotosForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/fileUtils.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/fileUtils.ts
src/v2/Apps/Consign/consignRoutes.tsx

This PR makes sure that in the consignment flow, the photos for the submission is added in the 2nd step directly instead of the last step. 
https://user-images.githubusercontent.com/42584148/146934100-f98edee4-743f-42d0-b9dd-2e2c3c5fbab5.mov

[feat]: [SWA-111] - AlicanAkyuz/Upload photos step

---

src/v2/Components/OneTrustConsentStyles.ts

Not sure what happened to this PR https://github.com/artsy/force/pull/9068 — I guess I accidentally force pushed an empty PR and then somehow merged it... Either way. Here's the code for the styles. They've been copied into the staging template and I've included some instructions here.

feat: set up for developing one trust styling

---

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx

per: https://artsyproduct.atlassian.net/jira/software/c/projects/BID/boards/106?modal=detail&selectedIssue=BID-137

fix:update alt text for bidding icons

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx

Jira Ticket:ticket: : [SWA-159](https://artsyproduct.atlassian.net/browse/SWA-159)
Jira Ticket:ticket: : [SWA-156](https://artsyproduct.atlassian.net/browse/SWA-156)
This PR updates copy for Upload Photos and Contact information steps in the Submission flow.

fix(SWA-159, SWA-156): Copy updates

---

src/v2/Apps/_About2/aboutRoutes.tsx
src/v2/Apps/_ArtsyEducation2/artsyEducationRoutes.tsx
src/v2/Apps/_AuctionPartnerships2/auctionPartnershipsRoutes.tsx
src/v2/Apps/_Contact2/contactRoutes.tsx
src/v2/Apps/_HowAuctionsWork2/howAuctionsWorkRoutes.tsx
src/v2/Apps/_Security/securityRoutes.tsx
src/v2/Apps/_Terms2/termsRoutes.tsx
src/v2/Apps/_WorksForYou2/worksForYouRoutes.tsx

fix: Fix hackathon routes

---

src/v2/Apps/Fair/Components/FairHeader/FairHeader.tsx
src/v2/Apps/Fair/FairApp.tsx
src/v2/Apps/Fair/Routes/FairExhibitors.tsx
src/v2/Apps/Fair/Routes/__tests__/FairExhibitors.jest.tsx
src/v2/Apps/Fair/Utils/useExhibitorsTabOffset.ts
src/v2/Apps/Fair/__tests__/FairApp.jest.tsx
src/v2/__generated__/FairApp_Test_Query.graphql.ts
src/v2/__generated__/FairApp_fair.graphql.ts
src/v2/__generated__/FairExhibitors_Test_Query.graphql.ts
src/v2/__generated__/FairExhibitors_fair.graphql.ts
src/v2/__generated__/fairRoutes_FairExhibitorsQuery.graphql.ts
src/v2/__generated__/fairRoutes_FairQuery.graphql.ts

Type: **Fix**
Jira ticket: [FX-3603]
https://user-images.githubusercontent.com/3513494/146403988-61d45df9-f969-4602-989c-91a4b880537b.mp4
https://user-images.githubusercontent.com/3513494/146404016-4e17ad07-2556-42f7-9e2f-2934acc0d241.mp4
https://user-images.githubusercontent.com/3513494/146404395-7d7724f0-bcf0-4e56-adb1-ff32d95ff59a.mp4
https://user-images.githubusercontent.com/3513494/146404423-14f7de89-ed3f-4890-a146-be49d6af702b.mp4
[FX-3603]: https://artsyproduct.atlassian.net/browse/FX-3603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FX-3603): remove extra offset for exhibitors nav

---

src/v2/Apps/Articles/ArticlesApp.tsx
src/v2/Apps/Articles/Components/ArticlesIndexArticle.tsx
src/v2/Apps/Articles/Components/ArticlesIndexArticleShare.tsx
src/v2/Apps/Articles/Components/ArticlesIndexArticles.tsx
src/v2/Apps/Articles/Components/__tests__/ArticlesIndexArticles.jest.tsx
src/v2/Apps/Articles/articlesRoutes.tsx
src/v2/__generated__/ArticlesApp_viewer.graphql.ts
src/v2/__generated__/ArticlesIndexArticle_article.graphql.ts
src/v2/__generated__/ArticlesIndexArticlesQuery.graphql.ts
src/v2/__generated__/ArticlesIndexArticles_test_Query.graphql.ts
src/v2/__generated__/ArticlesIndexArticles_viewer.graphql.ts
src/v2/__generated__/articlesRoutes_ArticlesQuery.graphql.ts
src/v2/routes.tsx

Sitting under /articles2 for now.

feat(articles): implements articles index page

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/fileUtils.ts

This PR adds logs for some network requests.

feat(SWA): add error logs for some network requests

---

cypress/integration/userPayments.spec.js
cypress/integration/userShipping.spec.js
src/v2/Apps/Authentication/Routes/LoginRoute.tsx
src/v2/Apps/Authentication/Routes/SignupRoute.tsx
src/v2/Apps/Authentication/__tests__/authenticationRoutes.jest.tsx

Sometimes you just need a quick win - here are some pretty pictures:
<details>
</details>
https://artsyproduct.atlassian.net/browse/GRO-731

feat: Update copy on auth pages GRO-731

---

src/v2/Apps/_Contact2/ContactApp.tsx

feat(contact2): Style page

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createOrUpdateConsignSubmission.ts

This PR updates the default value for the location field and saves user-agent on submission creating.

feat(SWA): submission flow improvements

---

src/v2/Apps/Articles/Components/ArticlesIndexArticle.tsx
src/v2/__generated__/ArticlesIndexArticle_article.graphql.ts
src/v2/__generated__/ArticlesIndexArticlesQuery.graphql.ts
src/v2/__generated__/ArticlesIndexArticles_test_Query.graphql.ts
src/v2/__generated__/articlesRoutes_ArticlesQuery.graphql.ts

Re: https://artsy.slack.com/archives/C01ADJNCS5D/p1642201185143100

fix(articles): adjusts thumbnail aspect ratio

---

src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

Removes admin check from #9217

remove admin block

---

src/v2/Components/OneTrustConsentStyles.ts

This just updates the development styles for OneTrust. Changes have been added to the dashboard and published on staging. Will merge once published to production.

fix(onetrust): updates styles

---

src/v2/Apps/Purchase/Components/OrderRow.tsx
src/v2/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx

Changed title from "Fulfillment" to "Delivery method"

fix(NX-3055): change order history "Fulfillment" copy to "Delivery method"

---

src/v2/Apps/MeetTheSpecialists/MeetTheSpecialistsApp.tsx
src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
src/v2/Apps/MeetTheSpecialists/meetTheSpecialistsRoutes.tsx

Followup to: #9217. 
Resizes/fixes images and replaces flexbox with grid-column for layout.

Meet the specialists page fixes

---

src/v2/Components/ArtworkFilter/SavedSearch/Components/ArtworkGridFilterPills.tsx
src/v2/Components/ArtworkFilter/SavedSearch/Components/Pills.tsx

Type: **Fix**
After yesterday's [PR](https://github.com/artsy/force/pull/9212), there was a small problem with padding for pills

chore: set offset for pills

---

src/v2/Apps/Auction/Components/LotInfo.tsx
src/v2/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
src/v2/__generated__/ConfirmBidValidTestQuery.graphql.ts
src/v2/__generated__/LotInfo_saleArtwork.graphql.ts
src/v2/__generated__/auctionRoutes_ConfirmBidQuery.graphql.ts

Updates bid form to ensure use current bid rather than minimum next bid per: https://artsyproduct.atlassian.net/jira/software/c/projects/BID/boards/106?modal=detail&selectedIssue=BID-150

bug:update value in bid form to match the label

---

src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

Add minor edits to the Meet the Specialist page content as requested by the Advisory team: https://artsy.slack.com/archives/C08U9TB2Q/p1641848725009400

chore: edit advisory page content

---

src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
src/v2/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx

Forgot to add this to mobile web!

Adds NFTs link to mobile web nav

---

src/v2/Apps/Order/Components/CreditCardInput.tsx
src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethod.tsx
src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethodForm.tsx
src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethods.tsx
src/v2/Apps/Settings/Routes/Payments/SettingsPaymentsRoute.tsx
src/v2/Apps/Settings/Routes/Payments/useAddCreditCard.ts
src/v2/Apps/Settings/Routes/Payments/useDeleteCreditCard.ts
src/v2/Apps/Settings/Routes/__tests__/SettingsPaymentsRoute.jest.tsx
src/v2/Components/CreditCardInput/CreditCardInput.tsx
src/v2/Components/CreditCardInput/CreditCardInputProvider.tsx
src/v2/Components/CreditCardInput/index.ts
src/v2/__generated__/SettingsPaymentsMethod_method.graphql.ts
src/v2/__generated__/SettingsPaymentsMethods_me.graphql.ts
src/v2/__generated__/SettingsPaymentsRoute_Test_Query.graphql.ts
src/v2/__generated__/SettingsPaymentsRoute_me.graphql.ts
src/v2/__generated__/settingsRoutes_PaymentsRouteQuery.graphql.ts
src/v2/__generated__/useAddCreditCardMutation.graphql.ts
src/v2/__generated__/useDeleteCreditCardMutation.graphql.ts

Same deal as the shipping tab. Just easier to a quick and clean rebuild. Will take this off draft when the MP schema updates in main.
https://user-images.githubusercontent.com/112297/151063400-fb8886a9-2424-4885-82b1-bb28194b047a.mov

feat(settings2): rebuilds payments tab

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/PhoneNumberInput.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

This PR updates the Contact Information step of the consignment submission flow in order to display an errror message under the email input when user types in an invalid email address. 
https://user-images.githubusercontent.com/42584148/150965202-a119daee-ff98-4dce-a12c-f1da67bfa7d4.mov

[Feat]: Display error msg when email is not valid in cons submissions

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx

This PR updates the Contact Information step of the consignment submission flow in order to update Submit button's disabled/enabled status when user removes the typed number altogether. 
https://user-images.githubusercontent.com/42584148/151013389-4e69c7dc-e1a6-42de-a7e6-2419f823d8b7.mov

[feat]: AlicanAkyuz/swa-201/update phone number validation

---

src/v2/Components/Footer/Footer.tsx
src/v2/Components/Footer/__tests__/Footer.jest.tsx
src/v2/System/Router/__tests__/RouterLink.jest.tsx

chore: adding small changes to the footer

---

src/v2/Components/OneTrustConsentStyles.ts

Closes: [GRO-759](https://artsyproduct.atlassian.net/browse/GRO-759)

fix(onetrust): aligns container to match page

---

src/lib/passport/example/client.js
src/lib/passport/example/index.js
src/lib/passport/example/public/client.js
src/lib/passport/index.js
src/lib/passport/lib/app/analytics.js
src/lib/passport/lib/app/forwarded_for.js
src/lib/passport/lib/app/index.js
src/lib/passport/lib/app/lifecycle.js
src/lib/passport/lib/app/locals.js
src/lib/passport/lib/app/logout.js
src/lib/passport/lib/app/redirectback.js
src/lib/passport/lib/app/sanitize_redirect.js
src/lib/passport/lib/app/token_login.js
src/lib/passport/lib/index.js
src/lib/passport/lib/options.js
src/lib/passport/lib/passport/callbacks.js
src/lib/passport/lib/passport/index.js
src/lib/passport/lib/passport/serializers.js
src/lib/passport/sanitize-redirect.js
src/lib/passport/test/app/analytics.js
src/lib/passport/test/app/lifecycle.js
src/lib/passport/test/app/locals.js
src/lib/passport/test/app/logout.js
src/lib/passport/test/app/sanitize_redirect.js
src/lib/passport/test/app/token_login.js
src/lib/passport/test/passport/callbacks.js
src/lib/passport/test/passport/serializers.js

chore(prettier): Run over passport

---

src/v2/Apps/Authentication/Routes/ResetPasswordRoute.tsx
src/v2/Apps/Authentication/Routes/__tests__/ResetPasswordRoute.jest.tsx
src/v2/Apps/Authentication/authenticationRoutes.tsx
src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsPassword.tsx
src/v2/System/Server/sharifyHelpers.ts
src/v2/Utils/getENV.tsx

Closes [GRO-725](https://artsyproduct.atlassian.net/browse/GRO-725)
Main change in https://github.com/artsy/force/commit/451c3b9c47184da80e6dcd54e72c9dd2b0891e8b
Included a minor refactor to use Formik & improve client-side validation.

fix(GRO-725): prevents exposure of token to 3rd parties

---

src/v2/Components/Authentication/Components/AuthenticationFooter.tsx
src/v2/Components/Authentication/Views/LoginForm.tsx

This took like 10 minutes, I'm PRing it just so users can log in with Google while I'm working [on the updated visuals](https://artsyproduct.atlassian.net/browse/GRO-639?atlOrigin=eyJpIjoiYjRkMWI4NDIwMzAyNGVmOTkzZDViNGY1Zjk2YjI5ZmYiLCJwIjoiaiJ9).
Before:
After:

fix: Allow users to sign in via Google

---

docs/env_configuration.md

- As of #8062, the desktop/mobile-specific config files have been consolidated
into the src/config.ts file
- Add note to type a new sharify addition
cc/ @sonecabr @dzucconi

docs: update docs to add an ENV var

---

src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsPassword.tsx

Minor change in the phone validator and adds some data-test attrs for Integrity to target.

fix(settings): fixes phone validation; integrity changes

---

src/v2/Apps/Article/ArticleApp.tsx
src/v2/Apps/Article/Components/ArticleHeader.tsx
src/v2/__generated__/ArticleBody_test_Query.graphql.ts
src/v2/__generated__/ArticleHeader_article.graphql.ts
src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts

Closes [GRO-756](https://artsyproduct.atlassian.net/browse/GRO-756)

feat(article): implements remaining hero types

---

src/v2/Components/SavedSearchAlert/DownloadAppBanner.tsx

Jira ticket: [FX-3728]
[FX-3728]: https://artsyproduct.atlassian.net/browse/FX-3728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-3728): Update Apple and Google Play Store Badges in create alert modal

---

src/v2/Apps/Article/Components/ArticleBody.tsx
src/v2/Apps/Article/Components/Sections/ArticleSectionVideo.tsx
src/v2/Apps/Article/Components/__tests__/ArticleBody.jest.tsx
src/v2/__generated__/ArticleBody_article.graphql.ts
src/v2/__generated__/ArticleBody_test_Query.graphql.ts
src/v2/__generated__/ArticleSectionVideo_section.graphql.ts
src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts

Closes [GRO-752](https://artsyproduct.atlassian.net/browse/GRO-752)
Will rebase this once the Metaphysics schema makes it into `main`.

feat(article): implements video embeds

---

src/v2/Apps/Article/Components/ArticleBody.tsx
src/v2/Apps/Article/Components/Sections/ArticleSectionSocialEmbed.tsx
src/v2/Apps/Article/Components/Sections/ArticleSectionVideo.tsx
src/v2/Apps/Article/Components/__tests__/ArticleBody.jest.tsx
src/v2/__generated__/ArticleBody_article.graphql.ts
src/v2/__generated__/ArticleBody_test_Query.graphql.ts
src/v2/__generated__/ArticleSectionSocialEmbed_section.graphql.ts
src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts

Closes [GRO-751](https://artsyproduct.atlassian.net/browse/GRO-751)
Will rebase once schema changes are in main before merging.

feat(article): implements social embeds

---

src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethod.tsx

bugfix(settings): Return error value

---

src/v2/Apps/Settings/SettingsApp.tsx

FWIW I like exuberance!
https://artsyproduct.atlassian.net/browse/GRO-800

feat: Remove exuberant greeting GRO-800

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts

https://artsyproduct.atlassian.net/browse/SWA-181
_before_
_after_

chore(SWA-181): update consign submission no artist error msg

---

src/v2/Apps/Article/Components/ArticleBody.tsx
src/v2/Apps/Article/Components/Sections/ArticleSectionEmbed.tsx
src/v2/Apps/Article/Components/__tests__/ArticleBody.jest.tsx
src/v2/__generated__/ArticleBody_article.graphql.ts
src/v2/__generated__/ArticleBody_test_Query.graphql.ts
src/v2/__generated__/ArticleSectionEmbed_section.graphql.ts
src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts

Closes [GRO-753](https://artsyproduct.atlassian.net/browse/GRO-753)

feat(article): implements generic embeds

---

src/v2/Apps/Articles/Components/ArticlesIndexArticle.tsx
src/v2/Apps/Articles/Components/__tests__/ArticlesIndexArticles.jest.tsx
src/v2/__generated__/ArticlesIndexArticle_article.graphql.ts
src/v2/__generated__/ArticlesIndexArticlesQuery.graphql.ts
src/v2/__generated__/ArticlesIndexArticles_test_Query.graphql.ts
src/v2/__generated__/articlesRoutes_ArticlesQuery.graphql.ts

Closes [GRO-805](https://artsyproduct.atlassian.net/browse/GRO-805)

fix(articles): uses thumbnail title

---

src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
src/v2/__generated__/SavedSearchAlertsApp_me.graphql.ts
src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts

Jira ticket: [FX-3723]
Review app: [link](https://your-alerts-pagination.artsy.net/user/alerts)
* Display "Show More" button at the bottom
* When the button is clicked, the next alerts should be loaded
* If all alerts are displayed, then the button should be hidden
* “Show More” button should be displayed under the list of all alerts if the edit panel is open
https://user-images.githubusercontent.com/3513494/152768325-c02ef48a-946c-4119-8675-6f8c8bfd47d6.mp4
[FX-3723]: https://artsyproduct.atlassian.net/browse/FX-3723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-3723): add pagination for edit alerts screen

---

src/v2/Apps/Article/ArticleApp.tsx
src/v2/Apps/Article/Components/ArticleBody.tsx
src/v2/Apps/Article/Components/ArticleSeries.tsx
src/v2/Apps/Article/Components/ArticleSponsor.tsx
src/v2/Apps/Article/Components/ArticleVideo.tsx
src/v2/Apps/Article/Components/__tests__/ArticleVideo.jest.tsx
src/v2/Apps/Articles/Components/ArticlesIndexArticle.tsx
src/v2/Components/ArticleShare.tsx
src/v2/__generated__/ArticleApp_article.graphql.ts
src/v2/__generated__/ArticleSeries_article.graphql.ts
src/v2/__generated__/ArticleSeries_test_Query.graphql.ts
src/v2/__generated__/ArticleSponsor_sponsor.graphql.ts
src/v2/__generated__/ArticleVideo_article.graphql.ts
src/v2/__generated__/ArticleVideo_test_Query.graphql.ts
src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts

Closes [GRO-807](https://artsyproduct.atlassian.net/browse/GRO-807)
https://user-images.githubusercontent.com/112297/153670781-7f40a870-c8a1-4a8a-bf32-42d9dbaa5b71.mov

feat(GRO-807): implements article video layout

---

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormDesktop.tsx
src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormMobile.tsx
src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
src/v2/Apps/Settings/Routes/SavedSearchAlerts/types.ts

Type: Enhancement
Jira ticket: [FX-3738]
Review app: https://full-screen-edit-panel.artsy.net/user/alerts
Add full screen modal for edit alert panel on mobile devices
https://user-images.githubusercontent.com/3513494/153862900-947ba5a6-4e65-464e-8811-55a4453450b1.mp4
[FX-3738]: https://artsyproduct.atlassian.net/browse/FX-3738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-3738): Full screen modal for edit alert panel

---

src/v2/Apps/Artist/ArtistApp.tsx
src/v2/Apps/Artist/__tests__/ArtistApp.jest.tsx
src/v2/Apps/Components/AppShell.tsx
src/v2/Apps/Order/OrderApp.tsx
src/v2/System/Router/Utils/__tests__/findCurrentRoute.jest.ts
src/v2/System/Router/Utils/findCurrentRoute.tsx
src/v2/System/Router/useCurrentRoute.ts
src/v2/Typings/global.d.ts

This is just an idiomatic React proxy to `getCurrentRoute` (which we use in some class components).

feat(router): Add useCurrentRoute

---

src/v2/Apps/Artist/ArtistApp.tsx
src/v2/Apps/Artist/__tests__/ArtistApp.jest.tsx
src/v2/Apps/Components/AppShell.tsx
src/v2/Apps/Order/OrderApp.tsx
src/v2/System/Router/Utils/__tests__/findCurrentRoute.jest.ts
src/v2/System/Router/Utils/findCurrentRoute.tsx
src/v2/System/Router/useCurrentRoute.ts
src/v2/Typings/global.d.ts

Reverting this as i'm seeing some unexpected issues with route transitions. 
Reverts artsy/force#9416

Revert "feat(router): Add useCurrentRoute"

---

data/schema.graphql
src/v2/Apps/Article/Components/ArticleBody.tsx
src/v2/Apps/Article/Components/ArticleByline.tsx
src/v2/Apps/Article/Components/__tests__/ArticleBody.jest.tsx
src/v2/__generated__/ArticleBody_article.graphql.ts
src/v2/__generated__/ArticleBody_test_Query.graphql.ts
src/v2/__generated__/ArticleByline_article.graphql.ts
src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts

Closes [GRO-803](https://artsyproduct.atlassian.net/browse/GRO-803)
Picking up on https://github.com/artsy/metaphysics/pull/3772

feat(article): loads image/bio for byline

---

src/v2/Components/Cells/PartnerCell.tsx
src/v2/__generated__/HomeFeaturedGalleriesRailQuery.graphql.ts
src/v2/__generated__/HomeFeaturedGalleriesRail_Test_Query.graphql.ts
src/v2/__generated__/PartnerCellFragmentContainer_Test_Query.graphql.ts
src/v2/__generated__/PartnerCell_partner.graphql.ts
src/v2/__generated__/PartnersFilteredCellsQuery.graphql.ts
src/v2/__generated__/PartnersRailQuery.graphql.ts

Ended up having revert issues, so I closed and reopened. This is to support the newly created "Black Owned" gallery badges.
New Functionality:

GRO-770: Reverted and Added: EntityHeader and Badging to PartnerCell

---

src/v2/Apps/_About2/AboutApp.tsx
src/v2/Apps/_About2/AboutArtworksRail.tsx
src/v2/__generated__/AboutArtworksRailQuery.graphql.ts
src/v2/__generated__/AboutArtworksRail_viewer.graphql.ts

PR is still a WIP, but also I need to clean up the commit history because its pulling commits from my other PR in. Still figuring out how to split PRs from branches that are created from another branch with separate code from the same file. Thanks for being so confusing, git! 
Update: PR is no longer a draft and ready to be merged

[GRO-734] use graphql query for artwork to render artwork rail 

---

src/lib/passport/lib/passport/callbacks.js

This reverts commit 08deb0214b9e798dfd0e01fdaf926f74fa6bc46c.
I'm suggesting this based on this [conversation in Slack](https://artsy.slack.com/archives/C01PBEBRB0V/p1645038350679579). Debugging this code is really time-consuming, I'm totally okay with reverting this and then revisiting the idea of refactoring later.

Revert "chore: DRY up passport callbacks"

---

package.json
src/v2/Apps/Article/Components/ArticleHTML.tsx
src/v2/Apps/Article/Components/ArticleTooltip.tsx
src/v2/Components/EntityTooltip/EntityTooltip.tsx
src/v2/Components/EntityTooltip/EntityTooltipArtist.tsx
src/v2/Components/EntityTooltip/EntityTooltipGene.tsx
src/v2/Components/EntityTooltip/EntityTooltipPartner.tsx
src/v2/Components/EntityTooltip/index.ts
src/v2/__generated__/EntityTooltipArtistQuery.graphql.ts
src/v2/__generated__/EntityTooltipArtist_artist.graphql.ts
src/v2/__generated__/EntityTooltipGeneQuery.graphql.ts
src/v2/__generated__/EntityTooltipGene_gene.graphql.ts
src/v2/__generated__/EntityTooltipPartnerQuery.graphql.ts
src/v2/__generated__/EntityTooltipPartner_partner.graphql.ts

Closes: [GRO-749](https://artsyproduct.atlassian.net/browse/GRO-749)
https://user-images.githubusercontent.com/112297/154770922-9f9ba7c7-4bf7-4339-818e-15beb1be3982.mov

feat(article): implements entity tooltips

---

.secrets.baseline
src/config.ts
src/lib/setup_sharify.js
src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
src/v2/Apps/Auction2/Auction2App.tsx
src/v2/Apps/Auction2/Components/AuctionActiveBids.tsx
src/v2/Apps/Auction2/Components/AuctionDetails/RegisterButton.tsx
src/v2/Apps/Auction2/Components/Form/ConditionsOfSaleCheckbox.tsx
src/v2/Apps/Auction2/Routes/Auction2RegistrationRoute.tsx
src/v2/Apps/Auction2/Routes/Bid/Components/AuctionLotInfo.tsx
src/v2/Apps/Auction2/Routes/Bid/useSubmitBid.ts
src/v2/Apps/Auction2/auction2Routes.tsx
src/v2/Components/ArtworkFilter/index.tsx
src/v2/System/Router/RouterLink.tsx
src/v2/__generated__/Auction2App_me.graphql.ts
src/v2/__generated__/AuctionActiveBidsRefetchQuery.graphql.ts
src/v2/__generated__/AuctionActiveBids_me.graphql.ts
src/v2/__generated__/AuctionLotInfo_saleArtwork.graphql.ts
src/v2/__generated__/auction2Routes_TopLevelQuery.graphql.ts

This adds an active bids component for when a user has bid on a sale and starts work on other minor issues as I see them. 

feat(auction2): Add ActiveBids component 

---

src/v2/Apps/Artists/Components/ArtistsArtistCard.tsx
src/v2/Apps/Artists/Components/ArtistsCarouselCell.tsx
src/v2/Components/FollowButton/FollowArtistButton.tsx
src/v2/__generated__/ArtistsArtistCard_Test_Query.graphql.ts
src/v2/__generated__/ArtistsArtistCard_artist.graphql.ts
src/v2/__generated__/ArtistsCarouselCell_featuredLink.graphql.ts
src/v2/__generated__/ArtistsIndexFragmentContainer_Test_Query.graphql.ts
src/v2/__generated__/artistsRoutes_ArtistsQuery.graphql.ts

Some minor things:
* Fixes SSR for follow buttons by including placeholder
* Adds a second line for the featured artists
* Simplifies getting artist id by actually getting the underlying entity
* Fixes TS expect errors

fix(artists): cleans up artist cards

---

src/v2/Apps/Auction2/Auction2App.tsx
src/v2/Apps/Auction2/Components/AuctionDetails/AuctionDetails.tsx
src/v2/Apps/Auction2/Components/AuctionDetails/RegisterButton.tsx
src/v2/Apps/Auction2/Components/Form/IdentityVerificationWarning.tsx
src/v2/__generated__/Auction2App_me.graphql.ts
src/v2/__generated__/AuctionDetails_sale.graphql.ts
src/v2/__generated__/RegisterButton_Test_Query.graphql.ts
src/v2/__generated__/RegisterButton_sale.graphql.ts
src/v2/__generated__/auction2Routes_TopLevelQuery.graphql.ts
src/v2/__generated__/useCreateBidderMutation.graphql.ts

qa(auction2): Minor auction2 QA

---

src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx

Type: **Enhancement**
Jira ticket: [FX-3769]
Review app: https://max-width-alert.artsy.net/user/alerts
[FX-3769]: https://artsyproduct.atlassian.net/browse/FX-3769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-3769): Set max width for "Your Alerts" screen

---

src/v2/Apps/Article/ArticleApp.tsx
src/v2/Apps/Article/Components/ArticleInfiniteScroll.tsx
src/v2/Apps/Article/Components/ArticleVisibilityMetadata.tsx
src/v2/Utils/Hooks/useIntersectionObserver.ts
src/v2/__generated__/ArticleApp_article.graphql.ts
src/v2/__generated__/ArticleInfiniteScrollQuery.graphql.ts
src/v2/__generated__/ArticleInfiniteScroll_viewer.graphql.ts
src/v2/__generated__/ArticleVisibilityMetadata_article.graphql.ts
src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts

Closes: [GRO-757](https://artsyproduct.atlassian.net/browse/GRO-757)
https://user-images.githubusercontent.com/112297/155785043-fc994a9c-0e1e-489a-a750-c3056dbf675c.mov

feat(GRO-757): article infinite scroll

---

src/v2/Apps/_Preferences2/PreferencesApp.tsx
src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx
src/v2/Apps/_Preferences2/preferencesRoutes.tsx
src/v2/Apps/_Preferences2/useEditNotificationPreferences.tsx
src/v2/__generated__/PreferencesApp_viewer.graphql.ts
src/v2/__generated__/preferencesRoutes_PreferencesQuery.graphql.ts
src/v2/__generated__/useEditNotificationPreferencesMutation.graphql.ts

This PR finishes up most of the work for the Preference Center and is a prerequisite for https://github.com/artsy/force/pull/9246.
<details>
<a href="https://www.loom.com/share/c988a130bda24c1b91d02b6d928a4102">Video</a>
</details>

GRO-584 Interest-based preference center

---

src/v2/Apps/Auction2/Routes/Auction2RegistrationRoute.tsx

qa(auction2): fix register modal width 

---

src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
src/v2/Apps/PriceDatabase/Components/PriceDatabaseMeta.tsx
src/v2/Apps/PriceDatabase/Components/PriceDatabaseSearch.tsx

This PR resolves [CX-2346](https://artsyproduct.atlassian.net/browse/CX-2346) 
|Before|
|---|
|![image](https://user-images.githubusercontent.com/17421923/155750486-87d95894-6ad6-4d1a-88c3-f9d185f8b157.png)|
|After|
|![image](https://user-images.githubusercontent.com/17421923/155750324-526853e6-f56a-481b-b8d0-f4523a678112.png)|

chore: Price DB copy update

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx

This PR resolves [[SWA-237](https://artsyproduct.atlassian.net/browse/SWA-237)]
This PR updates the text copies in the artwork details step of the submission flow.

[feat]: update text copy in Artwork details step of submission flow

---

src/v2/Apps/Auctions/Components/CuritorialRailsTabBar.tsx
src/v2/Apps/Auctions/Components/StandoutLotsRail.tsx
src/v2/Apps/Auctions/__tests__/AuctionsApp.jest.tsx

Just a quick PR to update some copy.
https://artsyproduct.atlassian.net/browse/GRO-832

chore: Update copy on auctions page GRO-832

---

src/v2/Components/FocusVisible.tsx

fix: changes focus visible outline color to blue

---

.circleci/config.yml

This updates our #practice-web slack notification to be a bit more clear, and provide a path forward to fix.

ci(notifications): Update slack message to be more clear

---

docs/feature_flagging.md

This PR adds a quick initial doc on how to use feature flagging, implemented in this  PR #9498.

feature: feature flagging docs

---

src/v2/Apps/Articles/ArticlesApp.tsx
src/v2/Apps/PriceDatabase/Components/PriceDatabaseMeta.tsx

[GRO-852]
[GRO-857]
Updated SEO tags for Artsy Price Database and updated canonical tag on artsy.net/articles
[GRO-852]: https://artsyproduct.atlassian.net/browse/GRO-852?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-857]: https://artsyproduct.atlassian.net/browse/GRO-857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GRO-852 & GRO-857: SEO Updates for Articles and Price Database

---

src/v2/Apps/Conversation/Components/ReviewOfferCTA.tsx

https://artsyproduct.atlassian.net/browse/FX-3355

feat: remove helper

---

src/v2/Apps/Conversation/__tests__/DetailsSidebar.jest.tsx
src/v2/Apps/Order/Components/ArtworkSummaryItem.tsx
src/v2/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
src/v2/Apps/Order/Components/__tests__/TransactionDetailsSummary.jest.tsx
src/v2/Apps/Order/Routes/Review/index.tsx
src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx

[TX-231](https://artsyproduct.atlassian.net/browse/TX-231)
This PR releases the [new order breakdown](https://artsyproduct.atlassian.net/browse/TX-90) by taking it out from behind the Avalara Phase 2 feature flag.

feat(TX-231): release new order breakdown

---

src/v2/Apps/_Preferences2/PreferencesApp.tsx
src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx

Single character PR please applaud 👏 
https://artsyproduct.atlassian.net/browse/GRO-865

fix: Use singular form in page title GRO-865

---

src/v2/Apps/Order/Routes/Review/index.tsx

Fixes a merge issue that caused an unused dep to remain.

fix: Remove unused dep

---

src/v2/Apps/_Preferences2/PreferencesApp.tsx

Old Copy Script:
Benefit from Artsy by receiving all our emails, with recommendations for you, Artsy Editorial, guidance on collecting, and updates on your favorite artists.”
New Copy Script:
Get all of Artsy’s emails, including recommendations for you, Artsy Editorial, guidance on collecting, and updates on your favorite artists.

Updated: Preference Center copy 

---

src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.jest.tsx

This pr addresses roop's comments from [here](https://github.com/artsy/force/pull/9576#pullrequestreview-906021241)
- corrected description of test 
- removed redundant feature flag variant mock

test: ArtworkSidebar test improvements

---

docs/adding_a_segment_destination.md
docs/best_practices.md

This updates our docs with a note on the differences between enzyme and `@testing-library/react`, and adds a note about testing react hooks.

docs(best-practices): Update testing section

---

src/v2/Apps/Auction2/Hooks/useAuctionTracking.ts

Adds a few missing analytics events from the old page

chore(auction2): Add missing events

---

src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx

This PR resolves [CX-2431](https://artsyproduct.atlassian.net/browse/CX-2431)
Before
After

feat: Update Price DB proposition

---

src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/__tests__/createConsignSubmission.jest.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createOrUpdateConsignSubmission.ts

The PR adds source field to identify the source of the submission.
JIRA - https://artsyproduct.atlassian.net/browse/SWA-233

feat(SWA-233): add submission source

---

src/v2/Apps/Article/Components/ArticleAd/ArticleAd.tsx
src/v2/Apps/Article/Components/ArticleSectionAd.tsx
src/v2/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGallery.tsx
src/v2/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryFigure.tsx
src/v2/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryResponsiveBox.tsx
src/v2/Utils/Hooks/useSizeAndPosition.ts
src/v2/__generated__/ArticleBody_test_Query.graphql.ts
src/v2/__generated__/ArticleInfiniteScrollQuery.graphql.ts
src/v2/__generated__/ArticleSectionAd_article.graphql.ts
src/v2/__generated__/NewsIndexArticlesQuery.graphql.ts
src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
src/v2/__generated__/articlesRoutes_NewsQuery.graphql.ts

Closes: [GRO-863](https://artsyproduct.atlassian.net/browse/GRO-863)
Remaining Q/A items.

fix(GRO-863) Article Q/A (Part 2)

---

package.json
src/v2/Apps/Auction2/Components/AuctionActiveBids.tsx
src/v2/Apps/Auction2/Components/AuctionDetails/AddToCalendar.tsx
src/v2/Apps/Auction2/Components/AuctionDetails/__tests__/AddToCalendar.jest.tsx
src/v2/Apps/Auction2/Components/AuctionDetails/__tests__/AuctionDetails.jest.tsx
src/v2/Apps/Auction2/Components/RegisterButton.tsx
src/v2/Apps/Auction2/Components/__tests__/AuctionActiveBids.jest.tsx
src/v2/Apps/Auction2/Components/__tests__/RegisterButton.jest.tsx
src/v2/Apps/Auction2/Hooks/__tests__/useAuctionTracking.jest.tsx
src/v2/Apps/Auction2/Hooks/useAuctionTracking.ts
src/v2/Apps/Auction2/Hooks/useCreateTokenAndSubmit.ts
src/v2/Apps/Auction2/Routes/Bid/Auction2BidRoute.tsx
src/v2/Apps/Auction2/Routes/Bid/__tests__/Auction2BidRoute.jest.tsx
src/v2/Apps/Auction2/Routes/Bid/__tests__/useSubmitBid.jest.tsx
src/v2/Apps/Auction2/Routes/Bid/useSubmitBid.ts
src/v2/__generated__/Auction2AppTestQuery.graphql.ts
src/v2/__generated__/AuctionActiveBidsRefetchQuery.graphql.ts
src/v2/__generated__/AuctionActiveBidsTestQuery.graphql.ts
src/v2/__generated__/AuctionActiveBids_me.graphql.ts
src/v2/__generated__/RegisterButton_Test_Query.graphql.ts
src/v2/__generated__/RegisterButton_me.graphql.ts
src/v2/__generated__/auction2Routes_TopLevelQuery.graphql.ts
src/v2/__generated__/useBidderPositionQuery.graphql.ts
yarn.lock

This wires up /auction2 tracking and adds some test around the code. 
Next pr will contain last little bit of qa, then a launch PR. 

chore(auction2): Wire up and test auction tracking

---

package.json
yarn.lock

Bumps cohesion from 4.36.0 to 4.37.0

chore(deps): bump cohesion from 4.36.0 to 4.37.0

---

src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx

This PR resolves [CX-2413](https://artsyproduct.atlassian.net/browse/CX-2413)
Before
After

feat: Hide unknown medium text

---

src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
src/v2/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButton.tsx
src/v2/Components/SavedSearchAlert/Components/__tests__/CreateAlertButton.jest.tsx
src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchAlertArtworkGridFilterPills.jest.tsx
src/v2/Components/SavedSearchAlert/Utils/__tests__/savedSearchCriteria.jest.ts
src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
src/v2/Components/SavedSearchAlert/types.ts

Type: **Enhancement**
* Rename `type` to `ownerType`
* Add `analytics` field

chore: pass OwnerType to SavedSearchEntity

---

docs/unleash_a-b_testing.md

Adds some docs for forcing an unleash variant for a specific userId.

docs: force an unleash variant for userId 

---

src/v2/Apps/_Preferences2/PreferencesApp.tsx
src/v2/Apps/_Preferences2/__tests__/PreferencesApp.jest.tsx

I didn't realize I needed to add this component! Oops :)
Note that we'll need to update this in https://github.com/artsy/force/pull/9246

chore: Add MetaTags to preferences app

---

src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

This PR solves: [GRO-850]
Collector Specialists team asked to be added to `/meet-the-specialists`
[GRO-850]: https://artsyproduct.atlassian.net/browse/GRO-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GRO-850] add collector specialists team to meet-the-specialists

---

pull_request_template.md

I was inspired by Cohesion to create a simple PR review template to remove some of the redundancy around including/linking jira tickets etc. 
Let me know if there's anything that would be worth it to add? A header for screenshots maybe?

add basic pull request template to force

---

src/v2/Apps/Auction/Components/AuctionArtworkFilter.tsx

Closes: [GRO-893](https://artsyproduct.atlassian.net/browse/GRO-893)

fix(auction): adjusts pagination count

---

src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
src/v2/Components/Range.tsx

* slider handle size increased from `16` to `24`
* reduced box shadow

chore: update slider handle

---

src/v2/Apps/Auction/Components/__tests__/AuctionArtworkFilter.jest.tsx

Interestingly the Github downtime threw away change in my previous branch despite the push being successful.

fix(auction): updates spec

---

src/v2/Apps/Auction/auctionRoutes.tsx
src/v2/__generated__/ArtistSeriesApp_artistSeries.graphql.ts
src/v2/__generated__/ArtistSeriesArtworksFilterQuery.graphql.ts
src/v2/__generated__/ArtistWorksForSaleRoute_artist.graphql.ts
src/v2/__generated__/AuctionAppTestQuery.graphql.ts
src/v2/__generated__/AuctionArtworkFilterQuery.graphql.ts
src/v2/__generated__/AuctionArtworkFilter_viewer.graphql.ts
src/v2/__generated__/CollectionArtworksFilter_Query.graphql.ts
src/v2/__generated__/Collection_collection.graphql.ts
src/v2/__generated__/FairArtworksQuery.graphql.ts
src/v2/__generated__/FairArtworks_fair.graphql.ts
src/v2/__generated__/GeneArtworkFilterQuery.graphql.ts
src/v2/__generated__/GeneArtworkFilter_Query.graphql.ts
src/v2/__generated__/SearchResultsArtworks_viewer.graphql.ts
src/v2/__generated__/ShowApp_show.graphql.ts
src/v2/__generated__/TagArtworkFilterQuery.graphql.ts
src/v2/__generated__/TagArtworkFilter_tag.graphql.ts
src/v2/__generated__/Works_Query.graphql.ts
src/v2/__generated__/Works_partner.graphql.ts
src/v2/__generated__/artistRoutes_WorksForSaleQuery.graphql.ts
src/v2/__generated__/artistSeriesRoutes_ArtistSeriesQuery.graphql.ts
src/v2/__generated__/geneRoutes_GeneShowQuery.graphql.ts
src/v2/__generated__/showRoutes_ShowQuery.graphql.ts

Unknown as to why this fixes the issue.

fix(auction): fixes logged out, ssr display of sale lots

---

src/v2/Components/LotTimer.tsx
src/v2/Components/__tests__/LotTimer.jest.tsx

[BX-279](https://artsyproduct.atlassian.net/browse/BID-279)
Before:
After
:

fix: Fix timer to only turn red at 2 mins or less

---

.secrets.baseline

The type of this PR is: Bugfix
Generates a new PR to resolve CI failing [detect-secrets](https://app.circleci.com/pipelines/github/artsy/force) tests. Seems like the baseline file got out of sync.

fix: update detect-secrets baseline

---

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
src/v2/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
src/v2/Components/Artwork/Details.tsx
src/v2/Components/Artwork/__tests__/Details.jest.tsx

This PR solves [NX-3091]
Change "Price on Request" to "Price on request" on the artwork page and in the search results. Only CTA texts should use title case.
[NX-3091]: https://artsyproduct.atlassian.net/browse/NX-3091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3091): Make "Price on Request" text sentence case

---

src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx

This PR solves [CX-2421]
[CX-2421]: https://artsyproduct.atlassian.net/browse/CX-2421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Price DB 4th copy update

---

src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
src/v2/Apps/Settings/Routes/EditSettings/Components/useUpdateSettingsInformation.ts

Closes [GRO-877](https://artsyproduct.atlassian.net/browse/GRO-877)
Picking up from https://github.com/artsy/metaphysics/pull/3894 since it's now returning the error in the schema rather than the errors array we need to pick it up and reject it.

fix(settings): reject on error

---

src/v2/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx

This PR solves [CX-2462]
[CX-2462]: https://artsyproduct.atlassian.net/browse/CX-2462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Price DB 4th copy update

---

src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
src/v2/Apps/Settings/Routes/EditSettings/Components/useUpdateSettingsInformation.ts
src/v2/__generated__/useUpdateSettingsInformationMutation.graphql.ts

This PR solves [GRO-878]
Reset the form after success to clear out the password and update the email that the field compares against.
[GRO-878]: https://artsyproduct.atlassian.net/browse/GRO-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(settings): resets form after updates

---

src/lib/middleware/hardcodedRedirects.ts
src/lib/middleware/userRequiredMiddleware.ts
src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
src/v2/Apps/Settings/SettingsApp.tsx
src/v2/Apps/Settings/settingsRoutes.tsx
src/v2/Components/NavBar/Menus/NavBarUserMenu.tsx
src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
src/v2/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts

The type of this PR is: Enhancement 
This PR addresses [GRO-654]
The wording in the ticket specifies that the code should be migrated, but this seems to have already been addressed. Here I added a tab to the settings app for easier navigation.
[GRO-654]: https://artsyproduct.atlassian.net/browse/GRO-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: add 'your alerts' to settings app

---

data/schema.graphql
src/v2/Apps/Preferences/PreferencesApp.tsx
src/v2/__generated__/PreferencesApp_viewer.graphql.ts
src/v2/__generated__/preferencesRoutes_PreferencesQuery.graphql.ts
src/v2/__generated__/useEditNotificationPreferencesMutation.graphql.ts

This PR solves [GRO-844]
We don't need to mess with this since Gravity doesn't really need these fields.
Depends on https://github.com/artsy/metaphysics/pull/3903
[GRO-844]: https://artsyproduct.atlassian.net/browse/GRO-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(GRO-844): Don't send values that aren't used by Gravity

---

src/lib/middleware/bootstrapSharifyAndContextLocalsMiddleware.ts
src/v2/Apps/Partners/Components/PartnersFeaturedCarousel.tsx
src/v2/Apps/Partners/Components/__tests__/PartnersFeaturedCarousel.jest.tsx
src/v2/Apps/Partners/Routes/__tests__/GalleriesRoute.jest.tsx
src/v2/Apps/Partners/Routes/__tests__/InstitutionsRoute.jest.tsx
src/v2/Utils/Hooks/__tests__/useStableShuffle.jest.tsx
src/v2/Utils/Hooks/useStableShuffle.ts

This PR solves [GRO-856]
Implements a seeded shuffle using the Express request ID as a seed.
[GRO-856]: https://artsyproduct.atlassian.net/browse/GRO-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(GRO-856): shuffled featured partners carousel

---

src/v2/Apps/Auction/Components/AuctionActiveBids.tsx
src/v2/Apps/Auction/Components/__tests__/AuctionActiveBids.jest.tsx
src/v2/Apps/Auction/Routes/Bid/Components/AuctionLotInfo.tsx
src/v2/__generated__/AuctionActiveBidsRefetchQuery.graphql.ts
src/v2/__generated__/AuctionActiveBidsTestQuery.graphql.ts
src/v2/__generated__/AuctionAppTestQuery.graphql.ts
src/v2/__generated__/AuctionBidRouteQuery.graphql.ts
src/v2/__generated__/AuctionBidRouteTestQuery.graphql.ts
src/v2/__generated__/AuctionLotInfo_saleArtwork.graphql.ts
src/v2/__generated__/auctionRoutes_BidRouteQuery.graphql.ts
src/v2/__generated__/auctionRoutes_TopLevelQuery.graphql.ts
src/v2/__generated__/useBidderPositionQuery.graphql.ts

This PR solves [BID-256]
Add formatted closing time to Active Bids cards, plus display "Bidding Closed" based on design input.
[Figma link](https://www.figma.com/file/PD7gXzuexzbi4Zz1tZLssx/Popcorn-and-cascading-bidding?node-id=1543%3A9164)
Screenshot
[BID-256]: https://artsyproduct.atlassian.net/browse/BID-256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore:update copy for active bids

---

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
src/v2/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx
src/v2/__generated__/SavedSearchAlertListItem_item.graphql.ts
src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
src/v2/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts

* Revert #9731
* Add changes for artsy/metaphysics#3880

chore: use displayValue instead of value for filter criteria

---

src/v2/Apps/Article/Components/ArticleBody.tsx
src/v2/Apps/Article/Components/ArticleHTML.tsx
src/v2/Apps/Article/Components/ArticleHeader.tsx
src/v2/Apps/Article/Components/ArticleSection.tsx
src/v2/Apps/Article/Components/ArticleSeriesItem.tsx
src/v2/Apps/Article/Components/ArticleVideo.tsx
src/v2/Apps/Article/Components/Sections/ArticleSectionText.tsx
src/v2/Components/ArticleShare.tsx
src/v2/__generated__/ArticleSeriesItem_article.graphql.ts
src/v2/__generated__/ArticleSeries_test_Query.graphql.ts
src/v2/__generated__/ArticleVideo_test_Query.graphql.ts
src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts

fix(article): typographic updates

---

src/v2/Apps/Partner/PartnerApp.tsx
src/v2/Components/EntityHeaders/EntityHeaderPartner.tsx
src/v2/__generated__/PartnerCell_partner.graphql.ts

Enhancement:
This PR solves [GRO-767]
This is to add in implementation that supports the Gallery Attributes, in particular, the newest addition of `Women Owned` galleries.
[GRO-767]: https://artsyproduct.atlassian.net/browse/GRO-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GRO-767: Supporting the Creation of "Women Owned" Gallery Attribute

---

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/v2/Components/SavedSearchAlert/Components/SavedSearchAlertArtworkGridFilterPills.tsx
src/v2/Components/SavedSearchAlert/Components/SavedSearchAlertPills.tsx
src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchAlertPills.jest.tsx
src/v2/Components/SavedSearchAlert/SavedSearchAlertModal.tsx
src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
src/v2/Components/SavedSearchAlert/__tests__/extractPills.jest.ts
src/v2/Components/SavedSearchAlert/types.ts

```javascript
DefaultFilterPill {
isDefault: true
name: string
displayName: string
}
NonDefaultFilterPill {
isDefault?: false
name: string
displayName: string
filterName: string
}
```
```javascript
FilterPill = {
isDefault?: boolean
value: string
displayValue: string
field: string
}
```

refactor: pill entity

---

src/v2/Components/Artwork/SaveButton/NewSaveButton.tsx

This PR solves [FX-3862]
Changing the data-test with the one of the old button to stop integrity tests from breaking.
[slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1649089235436909)
[FX-3862]: https://artsyproduct.atlassian.net/browse/FX-3862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: replace data-test tag with the old one

---

src/v2/Apps/Partner/Components/__tests__/PartnerViewingRooms/ViewingRoomCard.jest.tsx
src/v2/Components/__stories__/Image.story.tsx
src/v2/Components/__tests__/MetaTags.jest.tsx
src/v2/Utils/resizer.ts

I'm going to do some informal polling on determining appropriate compression levels. Re: [GRO-822](https://artsyproduct.atlassian.net/browse/GRO-822). So this adds a story that runs through some images applying compression and allowing to you compare easily.

chore(images): adds compression taste-test story

---

src/v2/Apps/Preferences/PreferencesApp.tsx

The type of this PR is: **Enchancement?**
This PR solves [GRO-902]
Removed a period!
[GRO-902]: https://artsyproduct.atlassian.net/browse/GRO-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(GRO-902): Copy tweak [ci skip]

---

src/v2/Apps/MeetTheSpecialists/MeetTheSpecialistsApp.tsx
src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
src/v2/Components/CCPARequest.tsx
src/v2/Components/Footer/Footer.tsx
src/v2/Components/Footer/__tests__/Footer.jest.tsx
src/v2/__generated__/CCPARequestMutation.graphql.ts

Just some minor things noticed when clicking around the footer looking for pages.
* Cleans up "Meet the Specialists" page
* Rebuilds the CCPA data request form
https://user-images.githubusercontent.com/112297/161833997-1e72c8f4-19f2-41ad-b10c-7aa492093be5.mov

chore: page consistency

---

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
src/v2/Apps/Settings/Routes/SavedSearchAlerts/SavedSearchAlertsApp.tsx
src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts
src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts
src/v2/__generated__/SavedSearchAlertsApp_me.graphql.ts
src/v2/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts
src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts

This PR solves [FX-3832]
Review app: [LINK](https://sort-for-alerts.artsy.net/settings/alerts)
* Two sort options:
* Recently Added
* Name (A-Z) (Alphabetical)
* Default option - Recently added 
https://user-images.githubusercontent.com/3513494/160845960-377ac682-a2ea-4361-b318-f6ee6d5c9417.mp4
[FX-3832]: https://artsyproduct.atlassian.net/browse/FX-3832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-3832): add sort control to alert management UI

---

package.json
yarn.lock

Revert "chore(deps): update dep typescript from 4.3.5 to v4.6.3"

---

src/v2/Apps/_AuctionPartnerships2/AuctionPartnershipsApp.tsx

This PR solves: [GRO-739]
[GRO-739]: https://artsyproduct.atlassian.net/browse/GRO-739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GRO-739] Auction-partnerships2 palette v3 migration 

---

.github/dependabot.yml
renovate.json

This PR solves https://artsyproduct.atlassian.net/browse/PLATFORM-4066
Updates dependabot and renovate assignee to @mc-jones 

chore: update dependabot and renovate assignee

---

src/v2/Apps/Settings/Routes/Saves/Components/__tests__/SettingsSavesArtworks.jest.tsx
src/v2/Apps/Shows/Routes/__tests__/ShowsCity.jest.tsx

fix: fixes mocks

---

src/v2/Apps/Home/Components/HomeFeaturedShowsRail.tsx
src/v2/Apps/Home/__tests__/HomeFeaturedShowsRail.jest.tsx

chore: update "Featured shows" capitalization

---

docs/unleash_a-b_testing.md

This PR solves [PLATFORM-4084]
This PR updates the unleash a/b test documentation to include changes made, and learnings, from the first experiment: PR #9679
[PLATFORM-4084]: https://artsyproduct.atlassian.net/browse/PLATFORM-4084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: unleash a/b test

---

src/v2/Components/__stories__/ResponsiveImages.story.tsx

Working through creating a doc on image handling. Needed some example code and figured they should live as stories.

chore(stories): adds some image handling examples

---

src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/ConsignMeta.tsx
src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/PromoSpace.tsx
src/v2/Apps/Consign/Routes/NewMarketingLanding/MarketingLandingApp.tsx
src/v2/Apps/Consign/consignRoutes.tsx

This PR solves [SWA-331]
This PR adds a new route `/sell2` with a new landing page.
[SWA-331]: https://artsyproduct.atlassian.net/browse/SWA-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(SWA-331): SWA landing page redesign

---

src/lib/passport/lib/app/lifecycle.js

@araujobarret and I paired on this yesterday. It fixes the issue new Google sign-ups have with missing display names. Addressing the already impacted users will follow, but this will help us avoid creating more users with bad data.

fix: Add scope to Google strategy to fix nil name sign ups

---

src/v2/Apps/Components/AppShell.tsx
src/v2/Components/Authentication/Views/SignUpForm.tsx
src/v2/Components/Inquiry/useInquiry.tsx
src/v2/Components/MNTNPixels.tsx
src/v2/index.ejs

This PR solves [GRO-949]
consolidate both the tracking & conversion pixels into a single file for intuitive refactor or removal. 
add the conversion pixel to contact gallery modal (a conversion point missed in the previous PR).
[GRO-949]: https://artsyproduct.atlassian.net/browse/GRO-949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(mntn pixel): add pixel to gallery inquiry modal

---

src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

Points to updated image assets

fix(meet-the-specialists): fixes images

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetailsForm.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
src/v2/Components/LocationAutocompleteInput.tsx
src/v2/Components/__tests__/LocationAutocompleteInput.jest.tsx
src/v2/__generated__/ArtworkDetails_SubmissionFlowTest_Query.graphql.ts
src/v2/__generated__/ArtworkDetails_submission.graphql.ts
src/v2/__generated__/consignRoutes_artworkDetailsQuery.graphql.ts
src/v2/__generated__/consignRoutes_contactInformationQuery.graphql.ts
src/v2/__generated__/consignRoutes_uploadPhotosQuery.graphql.ts
src/v2/__generated__/redirects_submission.graphql.ts

This PR solves [SWA-303]
Review app - https://postal-code.artsy.net/consign
This PR adds the postal code field for the submission flow.
[SWA-303]: https://artsyproduct.atlassian.net/browse/SWA-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(SWA-303): postal code

---

docs/handling_images.md

docs: adds link to notion doc

---

docs/unleash_a-b_testing.md
src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx

This PR solves [FX-3900]
Clean up of the filters expanded experiment.
- turned the experiment off in production/development
- clean up of the experiment here
- will archive the [feature-flag](https://unleash.artsy.net/projects/default/features2/filters-expanded-experiment) once this gets merged
- enhance unleash docs
[FX-3900]: https://artsyproduct.atlassian.net/browse/FX-3900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: cleanup unleash filters experiment

---

src/v2/Components/OneTrustConsentStyles.ts

These changes have already been published as draft template changes within OneTrust.

chore: adjusts cookie consent styles

---

src/v2/Apps/Jobs/Components/JobLink.tsx
src/v2/Apps/Jobs/Components/JobsFilter.tsx
src/v2/Apps/Jobs/JobApp.tsx
src/v2/Apps/Jobs/JobsApp.tsx
src/v2/Apps/Jobs/jobsRoutes.tsx
src/v2/Apps/Page/Components/PageHTML.tsx
src/v2/__generated__/JobApp_job.graphql.ts
src/v2/__generated__/JobLink_job.graphql.ts
src/v2/__generated__/JobsApp_viewer.graphql.ts
src/v2/__generated__/JobsFilter_viewer.graphql.ts
src/v2/__generated__/addUserToSubmissionMutation.graphql.ts
src/v2/__generated__/jobsRoutes_JobQuery.graphql.ts
src/v2/__generated__/jobsRoutes_JobsQuery.graphql.ts

Depends on https://github.com/artsy/metaphysics/pull/3990
Obviously, ignore the `schema.graphql` updates here. Will convert off draft once https://github.com/artsy/metaphysics/pull/3990 is on staging.
https://user-images.githubusercontent.com/112297/164311482-57e5f7c9-00c0-4d1b-aa03-618573a5d7db.mov

feat: converts jobs2 to use greenhouse data

---

src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

This PR solves [GRO-979]
Added in 2 new Auction Specialists, for /meet-the-specialists route.
[GRO-979]: https://artsyproduct.atlassian.net/browse/GRO-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://user-images.githubusercontent.com/30025439/165333570-0cb0a551-48d6-410f-b892-23b666a72c97.mov

GRO-979: Add new specialists to /meet-the-specialists

---

src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

This PR solves [GRO-979]
Updating specialist's last name to exclude second last name.
[GRO-979]: https://artsyproduct.atlassian.net/browse/GRO-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating to remove second name of a specialist

---

src/v2/Apps/Consign/Hooks/__tests__/useConnectUserToSubmission.jest.ts
src/v2/Apps/Consign/Hooks/useConnectUserToSubmission.ts
src/v2/Components/__tests__/LotTimer.jest.tsx

The type of this PR is: Bugfix
This PR fixes that we were making an API calls to add a user to a submission before the component mounted.

feat: prevent call before mounting

---

src/v2/Apps/Consign/Hooks/__tests__/useConnectUserToSubmission.jest.ts
src/v2/Apps/Consign/Hooks/useConnectUserToSubmission.ts
src/v2/Components/__tests__/LotTimer.jest.tsx

The type of this PR is: Bugfix
The test file fails when run in a PR, but it succeeds when run on main. I am creating this PR to merge into main to get the green there with the correct test.

Alican akyuz/fix lot timer test

---

src/v2/Components/__tests__/LotTimer.jest.tsx

The type of this PR is: Bug fix
This PR solves: issue with [spec failing in CI ](https://app.circleci.com/pipelines/github/artsy/force/30664/workflows/c3b09060-4b03-4554-9943-993b0af99150/jobs/239245) where the spec is expecting 2m 0s and it gets 1m 59s
Paired with @jacobherrington on this

bug:fixes flakey test that fails in CI off by 1 sec

---

docs/best_practices.md

docs: Add subsection linking to example test [ci skip]

---

src/lib/passport-local-with-otp/lib/index.js
src/v2/Apps/Auction/Components/Form/AddressForm.tsx
src/v2/Apps/Auction/Components/Form/Utils/initialValues.ts
src/v2/Apps/Auction/Components/Form/Utils/validationSchemas.ts
src/v2/Apps/Auction/Hooks/__tests__/useCreateTokenAndSubmit.jest.tsx
src/v2/Apps/Auction/Hooks/useCreateTokenAndSubmit.ts
src/v2/Apps/Auction/Routes/AuctionConfirmRegistrationRoute.tsx
src/v2/Apps/Auction/Routes/__tests__/AuctionConfirmRegistrationRoute.jest.tsx
src/v2/Apps/Order/Components/__tests__/AddressModal.jest.tsx
src/v2/Components/AddressForm.tsx
src/v2/Components/__tests__/Utils/addressForm.ts
src/v2/__generated__/AuctionConfirmRegistrationRouteTestQuery.graphql.ts
src/v2/__generated__/AuctionConfirmRegistrationRoute_me.graphql.ts
src/v2/__generated__/auctionRoutes_ConfirmRegistrationRouteQuery.graphql.ts
tsconfig.json

(Paired with @erikdstock on this)
This PR solves [TX-266]
This PR adds a new phone number requirement (if the user is missing a phone number) to the auction/id/confirm-registration route. 
[TX-266]: https://artsyproduct.atlassian.net/browse/TX-266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(Auction): Add phone number into to /confirm-registration if no phone number on file

---

cypress/integration/consign.spec.ts
src/desktop/apps/sitemaps/helpers.ts
src/lib/middleware/hardcodedRedirects.ts
src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/CtaBanner.tsx
src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/Header.tsx
src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/SellMeta.tsx
src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/__tests__/Header.jest.tsx
src/v2/Apps/Consign/Routes/NewMarketingLanding/Components/index.ts
src/v2/Apps/Consign/Routes/NewMarketingLanding/MarketingLandingApp.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/SubmissionLayout.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/redirects.ts
src/v2/Apps/Consign/consignRoutes.tsx
src/v2/Components/NavBar/NavBar.tsx
src/v2/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx
src/v2/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx

This PR solves [SWA-348]
This PR turns on the new SWA landing page on the `/sell` route. Also, replaces `/consign` route to `/sell`.
[SWA-348]: https://artsyproduct.atlassian.net/browse/SWA-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(SWA-348): turn on new landing page

---

src/v2/Apps/NewForYou/NewForYouApp.tsx
src/v2/Apps/NewForYou/__tests__/NewForYouApp.jest.tsx
src/v2/Apps/NewForYou/newForYouRoutes.tsx
src/v2/routes.tsx

This PR solves [GRO-976]
this pr creates: 
- "/new-for-you" route 
- stub app component
- stub test suite 
- associated feature flag
[GRO-976]: https://artsyproduct.atlassian.net/browse/GRO-976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(new for you): create /new-for-you

---

package.json
yarn.lock

Reverts artsy/force#10006
related [slack thread](https://artsy.slack.com/archives/C02BC3HEJ/p1651742054123479) for context

Revert "chore(deps): update dep typescript from 4.3.5 to v4.6.4"

---

src/v2/Apps/Auctions/Components/CuritorialRailsTabBar.tsx
src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts
src/v2/__generated__/CuritorialRailsTabBar_viewer.graphql.ts
src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts

The type of this PR is: feat
This PR solves [GRO-196]
Logged in (artist follows)
Logged in (no artist follows)
[GRO-196]: https://artsyproduct.atlassian.net/browse/GRO-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GRO-196] user sees empty state at auction

---

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx

This PR enhances [NX-3130]
Before:
After:
[NX-3130]: https://artsyproduct.atlassian.net/browse/NX-3130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(NX-3130): update button border color to match palette definition

---

src/v2/Apps/Jobs/JobApp.tsx

chore(jobs): updates copy

---

docs/adding_new_app.md
src/v2/Apps/Example/ExampleApp.tsx
src/v2/Apps/Example/README.md
src/v2/Apps/Example/Routes/Welcome/WelcomeRoute.tsx
src/v2/Apps/Example/__tests__/ExampleApp.jest.tsx
src/v2/Apps/Example/exampleRoutes.tsx
src/v2/__generated__/ExampleApp_Test_Query.graphql.ts

This PR solves [WP-67]
This PR adds example test setup for the ExampleApp using RTL and improves the visibility of the app in our docs. Additionally, it aims to use palette v3 fully within the app. 
[WP-67]: https://artsyproduct.atlassian.net/browse/WP-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Documentation]: ExampleApp improvements

---

src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Mutations/CreateConsignSubmissionMutation.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Mutations/UpdateConsignSubmissionMutation.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/createOrUpdateConsignSubmission.ts
src/v2/Apps/Consign/Routes/SubmissionFlow/Utils/redirects.ts
src/v2/Apps/Consign/consignRoutes.tsx
src/v2/__generated__/ArtworkDetails_SubmissionFlowTest_Query.graphql.ts
src/v2/__generated__/ArtworkDetails_submission.graphql.ts
src/v2/__generated__/ContactInformation_SubmissionFlowTest_Query.graphql.ts
src/v2/__generated__/ContactInformation_submission.graphql.ts
src/v2/__generated__/CreateConsignSubmissionMutation.graphql.ts
src/v2/__generated__/UpdateConsignSubmissionMutation.graphql.ts
src/v2/__generated__/UploadPhotos_ImageRefetch_Query.graphql.ts
src/v2/__generated__/UploadPhotos_SubmissionFlowTest_Query.graphql.ts
src/v2/__generated__/UploadPhotos_submission.graphql.ts
src/v2/__generated__/consignRoutes_artworkDetailsQuery.graphql.ts
src/v2/__generated__/consignRoutes_contactInformationQuery.graphql.ts
src/v2/__generated__/consignRoutes_uploadPhotosQuery.graphql.ts
src/v2/__generated__/redirects_submission.graphql.ts

Jira card - https://artsyproduct.atlassian.net/jira/software/c/projects/SWA/boards/113?modal=detail&selectedIssue=SWA-210
Changes how submissions IDs are presented to collectors (for security reasons). Instead of sequential IDs collectors will see UUIDs

feat[SWA-210]: Consign Submission Flow uses external id for submissions

---

src/desktop/models/artwork.js

See https://github.com/artsy/gravity/pull/15329 for details

chore: remove has_limited_fair_partnership

---

src/v2/__generated__/NewForYouApp_test_Query.graphql.ts
src/v2/__generated__/NewForYouApp_viewer.graphql.ts
src/v2/__generated__/NewForYouArtworksGridQuery.graphql.ts
src/v2/__generated__/NewForYouArtworksGrid_viewer.graphql.ts
src/v2/__generated__/newForYouRoutes_TopLevelQuery.graphql.ts

These files showed up recently, I think they may have been left out by mistake or by some broken automation?

chore: Check in graphql diff

---

src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx

This PR adds icons for payment methods of bank transfer and credit card in the checkout flow.

(Enhancement): Add icons for payment methods

---

src/v2/Apps/Article/Components/ArticleAd/ArticleAd.tsx
src/v2/Apps/Article/Components/ArticleBody.tsx
src/v2/Apps/Article/Components/ArticleNewsSource.tsx
src/v2/Apps/Article/Components/ArticleSponsor.tsx
src/v2/Apps/Article/Components/ArticleVideo.tsx
src/v2/Apps/Article/Components/Sections/ArticleSectionVideo.tsx
src/v2/Apps/Article/Components/__tests__/ArticleBody.jest.tsx
src/v2/Apps/Article/Components/__tests__/ArticleSeries.jest.tsx
src/v2/Apps/Article/Components/__tests__/ArticleVideo.jest.tsx
src/v2/Apps/Article/useArticleTracking.ts
src/v2/Apps/Articles/Components/__tests__/ArticlesIndexArticles.jest.tsx
src/v2/Components/ArticleShare.tsx
src/v2/Components/EntityTooltip/EntityTooltipArtist.tsx
src/v2/Components/EntityTooltip/EntityTooltipGene.tsx
src/v2/Components/EntityTooltip/EntityTooltipPartner.tsx
src/v2/__generated__/ArticleBody_article.graphql.ts
src/v2/__generated__/ArticleBody_test_Query.graphql.ts
src/v2/__generated__/ArticleInfiniteScrollQuery.graphql.ts
src/v2/__generated__/ArticleNewsSource_article.graphql.ts
src/v2/__generated__/NewsIndexArticlesQuery.graphql.ts
src/v2/__generated__/articleRoutes_ArticleQuery.graphql.ts
src/v2/__generated__/articlesRoutes_NewsQuery.graphql.ts

Closes [GRO-758](https://artsyproduct.atlassian.net/browse/GRO-758)

feat(GRO-758): Wires up article analytics

---

src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx
src/v2/Apps/Home/__tests__/HomeAuctionLotsRail.jest.tsx
src/v2/__generated__/HomeAuctionLotsRailQuery.graphql.ts
src/v2/__generated__/HomeAuctionLotsRail_Test_Query.graphql.ts
src/v2/__generated__/HomeAuctionLotsRail_viewer.graphql.ts

This PR solves [GRO-1015]
Replace highlights-at-auction with our-top-auction-lots
[GRO-1015]: https://artsyproduct.atlassian.net/browse/GRO-1015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore (GRO-1015): Change gene for HomeAuctionLotsRail

---

data/schema.graphql
src/v2/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx
src/v2/__generated__/NewForYouApp_test_Query.graphql.ts
src/v2/__generated__/NewForYouArtworksGridQuery.graphql.ts
src/v2/__generated__/NewForYouArtworksGrid_viewer.graphql.ts
src/v2/__generated__/newForYouRoutes_TopLevelQuery.graphql.ts

Through an unfortunate series of events the MP schema drifted and this PR gets us back in sync.
/cc @tam-kis @starsirius @joeyAghion @laurabeth

Fix schema drift

---

src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
src/v2/Apps/Artist/Routes/WorksForSale/Components/ZeroState.tsx
src/v2/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
src/v2/Components/ArtworkGrid/ArtworkGridEmptyState.tsx

This PR solves [FX-3927]
Addressed the post merge comments from https://github.com/artsy/force/pull/10062
[FX-3927]: https://artsyproduct.atlassian.net/browse/FX-3927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-3927): Address post-merge comments

---

src/desktop/components/main_layout/templates/scripts.jade
src/v2/System/Router/renderServerApp.tsx
src/v2/index.ejs

This PR solves [GRO-1036]
This removes our 3rd party marketing lib Postie from force. 
[GRO-1036]: https://artsyproduct.atlassian.net/browse/GRO-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(postie): remove postie 3rd party lib

---

src/v2/Apps/Auctions/Components/__tests__/StandoutLotsRail.jest.tsx
src/v2/Apps/Auctions/Components/__tests__/TrendingLotsRail.jest.tsx
src/v2/Apps/Auctions/Components/__tests__/WorksByArtistsYouFollowRail.jest.tsx
src/v2/Components/Artwork/ShelfArtwork.tsx

These tests were pretty easy to swap to React Testing Library and I think they fit that mental model pretty well.

chore: Convert Rail tests to RTL

---

src/v2/Apps/Auctions/Components/__tests__/AuctionArtworksRail.jest.tsx

One more test that I could quickly convert to React Testing Library.

chore: Convert test to RTL

---

src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx

Re: https://artsy.slack.com/archives/C02BC3HEJ/p1653428106310039 & https://sentry.io/organizations/artsynet/issues/2340820754/?project=159064&query=is%3Aunresolved

fix(artwork): there may not be any images

---

src/v2/Apps/Conversation/Components/MakeOfferOnInquiryButton.tsx
src/v2/Apps/Conversation/Components/PurchaseOnInquiryButton.tsx
src/v2/Apps/Order/Routes/Review/index.tsx
src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx
src/v2/__generated__/ReviewTestQuery.graphql.ts
src/v2/__generated__/Review_order.graphql.ts
src/v2/__generated__/orderRoutes_ReviewQuery.graphql.ts

This PR solves [NX-3138]
- Implements redirect for purchase for inquiry
- Tidies `if` statements on the Review component
[NX-3138]: https://artsyproduct.atlassian.net/browse/NX-3138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(NX-3138): Adjust checkout redirect behavior for Purchase from inquiry

---

src/v2/Apps/Example/ExampleApp.tsx
src/v2/Apps/Example/Routes/AddToCollection/AddToCollectionRoute.tsx
src/v2/Apps/Example/Routes/AddToCollection/Components/ArtworkItem.tsx
src/v2/Apps/Example/exampleRoutes.tsx
src/v2/__generated__/AddToCollectionRoute_viewer.graphql.ts
src/v2/__generated__/exampleRoutes_AddToCollectionRouteQuery.graphql.ts

This adds a new example app route to force for review.

feat(example-app): add new example route

---

src/v2/Apps/Article/Components/ArticleBody.tsx
src/v2/Apps/Article/Components/ArticleHero.tsx
src/v2/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollection.tsx
src/v2/Apps/Article/Components/Sections/ArticleSectionText.tsx

Fixes remaining design Q/A from Peter.

fix(article): remaining design q/a

---

src/v2/Apps/Components/__tests__/AppShell.jest.tsx
src/v2/Components/Footer/FooterDownloadAppBanner.tsx

This PR solves [GRO-994]
Replace footer copy.
Get More from Artsy—on the App > Get the Artsy app
[GRO-994]: https://artsyproduct.atlassian.net/browse/GRO-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(footer): replace copy

---

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionInfoPolling.tsx
src/v2/Apps/AuctionPartnerships/AuctionPartnershipsApp.tsx
src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx

This PR solves [GRO-986] [GRO-1016] [GRO-1017]
A few very small tickets in one PR.
[GRO-986]: https://artsyproduct.atlassian.net/browse/GRO-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1016]: https://artsyproduct.atlassian.net/browse/GRO-1016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1017]: https://artsyproduct.atlassian.net/browse/GRO-1017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove personnel, margin fix

---

cypress/integration/artAppraisals.spec.ts
src/v2/Apps/ArtAppraisals/ArtAppraisalsApp.tsx
src/v2/Apps/ArtAppraisals/artAppraisalsRoutes.tsx
src/v2/routes.tsx

This PR solves [GRO-1044]
This stubs out the new Art Appraisals app routes. 
[GRO-1044]: https://artsyproduct.atlassian.net/browse/GRO-1044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(art-appraisals): Stub out app

---

src/v2/Apps/Article/Components/ArticleHTML.tsx
src/v2/Apps/Article/Components/Sections/ArticleSectionText.tsx

Just opening a draft to queue up some minor refinements throughout the day.

fix(article): article refinements

---

src/v2/index.ejs

Fixes the error pages attempting to load the layout.
Not entirely sure what this diff does but, this is the source of the issue:
https://github.com/artsy/force/commit/c14a320fa33e9eae665283963f7cea05ae45b053#diff-8527786fa5a1865c6babd7d10de914560a326cbe092000ed5e5e447eb8a4cf03R26

fix: respects disable scripts flag

---

src/desktop/apps/sitemaps/helpers.ts
src/v2/Apps/ArtAppraisals/ArtAppraisalsApp.tsx

This PR solves [GRO-1040]
This PR finishes up the Art Appraisals page and adds in remaining content. 
[GRO-1040]: https://artsyproduct.atlassian.net/browse/GRO-1040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(art-appraisals): Add page content

---

src/v2/Apps/ArtAppraisals/ArtAppraisalsApp.tsx

The type of this PR is: **Cleanup**
Some light cleanup around the new `art-appraisals` page to better support mobile.

chore(art-appraisals): Cleanup

---

src/v2/Apps/Artist/Routes/Overview/Components/ArtistNotableWorksRail.tsx
src/v2/Apps/Artist/Routes/Overview/Components/ArtistWorksForSaleRail.tsx
src/v2/Apps/Auctions/Components/AuctionArtworksRail.tsx
src/v2/Apps/Auctions/Components/StandoutLotsRail.tsx
src/v2/Apps/Auctions/Components/TrendingLotsRail.tsx
src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx
src/v2/Apps/Consign/Routes/MarketingLanding/Components/SoldRecentlyOnArtsy.tsx
src/v2/Apps/Fair/Components/FairBoothRail/FairBoothRailArtworks.tsx
src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx
src/v2/Apps/Home/Components/HomeRecentlyViewedRail.tsx
src/v2/Apps/Home/Components/HomeWorksByArtistsYouFollowRail.tsx
src/v2/Components/Artwork/ShelfArtwork.tsx

Reverts artsy/force#10234
A problem was found with the display of updated pills

Revert "enhancement(FX-4016): Add new hover behavior to artwork cards in ArtworkShelf"

---

src/v2/Apps/Order/Components/PaymentPicker.tsx
src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx

This PR solves [TX-382]
This PR adds attributes for the integration tests
[TX-382]: https://artsyproduct.atlassian.net/browse/TX-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add test attributes

---

src/v2/Apps/IdentityVerification/Error.tsx
src/v2/Apps/IdentityVerification/IdentityVerificationApp/CompleteFailed.tsx
src/v2/Apps/IdentityVerification/IdentityVerificationApp/CompletePassed.tsx
src/v2/Apps/IdentityVerification/IdentityVerificationApp/CompleteWatchlistHit.tsx
src/v2/Apps/IdentityVerification/IdentityVerificationApp/WrongOwner.tsx
src/v2/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
src/v2/Apps/IdentityVerification/Processing.tsx
src/v2/Apps/IdentityVerification/__tests__/IdentityVerificationApp.jest.tsx
src/v2/Apps/IdentityVerification/__tests__/Utils/IdentityVerificationAppTestPage.tsx
src/v2/Apps/IdentityVerification/identityVerificationRoutes.tsx

Moving right along. Just a visual update here, again.

refactor: updates indentity verification to v3

---

src/v2/Apps/ArtAppraisals/ArtAppraisalsApp.tsx

This updates the /art-appraisals route with more suitable images (darker header, higher res main). 🙏 for the image export @dzucconi.  

chore(art-appraisals): Update images

---

src/v2/Apps/ArtAppraisals/ArtAppraisalsApp.tsx

chore(art-appraisals): Fix image size

---

cypress/integration/campaign.spec.ts

Fixes build. No clue why this wouldn't have failed earlier.

fix: removes dead spec

---

src/v2/Apps/Fair/Routes/FairOverview.tsx
src/v2/Apps/Fair/Routes/__tests__/FairOverview.jest.tsx

Small improvement that fixes the problem with scrolling to the "Booths" section

fix: scroll to booths container

---

yarn.lock

This PR bumps jsprim to `1.4.2` from `1.4.1`

chore: bump jsprim

---

src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlertButton.tsx
src/v2/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx
src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx
src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchAlertArtworkGridFilterPills.jest.tsx
src/v2/Components/SavedSearchAlert/Components/__tests__/SavedSearchCreateAlertButtonContainer.jest.tsx
src/v2/Components/SavedSearchAlert/Utils/__tests__/savedSearchCriteria.jest.ts
src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
src/v2/Components/SavedSearchAlert/Utils/savedSearchCriteria.tsx
src/v2/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx
src/v2/Components/SavedSearchAlert/__tests__/extractPills.jest.ts
src/v2/Components/SavedSearchAlert/types.ts

chore: rename `artists` to `defaultArtists` for saved search alerts

---

package.json
src/v2/Apps/Artwork/Components/ArtworkMeta.tsx
src/v2/Apps/Artwork/Components/ArtworkZendesk.tsx
src/v2/Apps/Auction/AuctionApp.tsx
src/v2/Apps/Order/OrderApp.tsx
src/v2/Components/ZendeskWrapper.tsx
src/v2/Utils/Hooks/useLoadScript.ts
src/v2/Utils/isExceededZendeskThreshold.ts
src/v2/__generated__/ArtworkApp_Test_Query.graphql.ts
src/v2/__generated__/ArtworkMeta_artwork.graphql.ts
src/v2/__generated__/ArtworkZendesk_artwork.graphql.ts
src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
yarn.lock

This PR removes `react-zendesk` and better encapsulates its initialization.

fix: safely loads zendesk

---

src/v2/Components/Footer/Footer.tsx

https://artsyproduct.atlassian.net/browse/GRO-1084

feat: Add appraisals page to footer GRO-1084

---

src/v2/Apps/About/AboutApp.tsx

https://artsyproduct.atlassian.net/browse/GRO-1064

feat: Remove specialists section from about GRO-1064

---

src/v2/Apps/Partner/Components/Overview/AboutPartner.tsx
src/v2/Apps/Partner/Components/__tests__/Overview/AboutPartner.jest.tsx
src/v2/__generated__/AboutPartner_Test_Query.graphql.ts
src/v2/__generated__/AboutPartner_partner.graphql.ts
src/v2/__generated__/partnerRoutes_OverviewQuery.graphql.ts

This PR adds tracking to clicks from Artsy to external partner pages.
[Slack context](https://artsy.slack.com/archives/C9SATFLUU/p1652904245355049)

feat: add tracking to partner page website clicks

---

src/v2/Apps/Order/Routes/Review/index.tsx
src/v2/Apps/Order/Routes/__tests__/Review.jest.tsx

Reverts artsy/force#10376
Issue was found here: [slack thread](https://artsy.slack.com/archives/C9YNS4X32/p1655975838228519)

Revert "[Coordinated merge] Disable submit button on review step until Stripe is ready"

---

yarn.lock

This PR solves [PLATFORM-4249]
This PR bumps several `ansi-regex` versions by one patch version. 
[PLATFORM-4249]: https://artsyproduct.atlassian.net/browse/PLATFORM-4249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: bump-ansi-regex

---

src/v2/Apps/Artist/Components/ArtistInsights/ArtistInsightBadges.tsx
src/v2/Apps/Artist/Components/ArtistInsights/ArtistInsightPills.tsx

Fixing styling bugs on the Artist that were introduced when the new artist insights work was shipped.

fix(artist-insights): styling bug fixes on artist overview

---

src/v2/Apps/Onboarding/Components/OnboardingLoadingCollection.tsx
src/v2/Apps/Onboarding/Components/OnboardingSteps.tsx
src/v2/Apps/Onboarding/Views/OnboardingArtistsOnTheRise.tsx
src/v2/Apps/Onboarding/Views/OnboardingCuratedArtworks.tsx
src/v2/Apps/Onboarding/Views/OnboardingFollowArtists.tsx
src/v2/Apps/Onboarding/Views/OnboardingFollowGalleries.tsx
src/v2/Apps/Onboarding/Views/OnboardingTopAuctionLots.tsx
src/v2/Apps/Onboarding/__tests__/config.jest.ts
src/v2/Apps/Onboarding/config.ts
src/v2/Apps/Onboarding/useOnboardingContext.tsx

Sets up the remaining views to be filled in. + Some minor simplification.

feat(onboarding): adds stub views for remaining steps

---

src/v2/Apps/Onboarding/Views/OnboardingQuestionThree.tsx

Minor thing noticed when reviewing the code with @TMcMeans

fix(onboarding): handles options for remaining answer

---

src/v2/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
src/v2/__generated__/SettingsPurchasesQuery.graphql.ts
src/v2/__generated__/SettingsPurchasesRow_order.graphql.ts
src/v2/__generated__/SettingsPurchases_Test_Query.graphql.ts
src/v2/__generated__/settingsRoutes_PurchasesRouteQuery.graphql.ts

This PR solves [TX-304]
[TX-304]: https://artsyproduct.atlassian.net/browse/TX-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add new payment methods to the order history page.

---

src/v2/Apps/Artist/Components/ArtistInsights/ArtistInsightAchievements.tsx
src/v2/Apps/Artist/Components/ArtistInsights/ArtistInsightBadges.tsx
src/v2/Apps/Artist/Components/ArtistInsights/ArtistInsightPills.tsx
src/v2/Apps/Artist/Components/ArtistInsights/__tests__/ArtistInsightBadges.jest.tsx
src/v2/Apps/Artist/Components/ArtistInsights/__tests__/ArtistInsightPills.jest.tsx
src/v2/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlights.tsx
src/v2/__generated__/ArtistApp_Test_Query.graphql.ts
src/v2/__generated__/ArtistCareerHighlightsQuery.graphql.ts
src/v2/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
src/v2/__generated__/ArtistHeader_Test_Query.graphql.ts
src/v2/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
src/v2/__generated__/ArtistInsightBadges_artist.graphql.ts
src/v2/__generated__/ArtistInsightPills_Test_Query.graphql.ts
src/v2/__generated__/ArtistInsightPills_artist.graphql.ts
src/v2/__generated__/artistRoutes_TopLevelQuery.graphql.ts

The type of this PR is: *fix*
This PR solves problems surfaced during artist insights metadata QA
https://www.notion.so/artsy/Artist-At-a-Glance-Data-QA-6b5bd62ae7c842fc8f80ed599d1f463c?v=b4dcffb5be39480ea31bc55e9e5c907b
This code addresses: 
- Remove blue chip badge/pill
- Address copy for headers and badges descriptions
- Remove icons from badges
- Make pills clickable with a scrollTo function that navigates to badges 

fix(artist-insights): Remove blue chip representation & design cleanup

---

src/desktop/apps/eoy_2016/fixtures/data.json
src/desktop/components/main_layout/footer/index.styl
src/v2/Apps/About/AboutApp.tsx
src/v2/Apps/AuctionPartnerships/AuctionPartnershipsApp.tsx
src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnit.tsx
src/v2/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx
src/v2/Apps/__tests__/Fixtures/Collections.ts
src/v2/Components/ViewInRoom/ViewInRoomRoom.tsx

Closes #GRO-1128
Also fixes some minor CSS bugs on the about page.

fix(GRO-1128): fixes mixed content warnings

---

src/v2/Apps/Settings/Routes/Payments/Components/SettingsBankAccount.tsx
src/v2/Apps/Settings/Routes/Payments/Components/SettingsCreditCard.tsx
src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethod.tsx
src/v2/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethods.tsx
src/v2/Apps/Settings/Routes/Payments/useAddCreditCard.ts
src/v2/Apps/Settings/Routes/Payments/useDeleteBankAccount.ts
src/v2/Apps/Settings/Routes/Payments/useDeleteCreditCard.ts
src/v2/Apps/Settings/Routes/__tests__/SettingsPaymentsRoute.jest.tsx
src/v2/__generated__/SettingsBankAccount_bankAccount.graphql.ts
src/v2/__generated__/SettingsCreditCard_creditCard.graphql.ts
src/v2/__generated__/SettingsPaymentsMethods_me.graphql.ts
src/v2/__generated__/SettingsPaymentsRoute_Test_Query.graphql.ts
src/v2/__generated__/settingsRoutes_PaymentsRouteQuery.graphql.ts
src/v2/__generated__/useDeleteBankAccountMutation.graphql.ts
src/v2/__generated__/useDeleteCreditCardMutation.graphql.ts

This PR solves [TX-350]
This PR add new section with the bank accounts on settings page.
[TX-350]: https://artsyproduct.atlassian.net/browse/TX-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add bank accounts to the settings page

---

package.json
yarn.lock

This should be most of the low hanging fruit within `devDependencies`

chore: removes unused code; dependencies

---

src/desktop/apps/editorial_features/components/gucci/components/App.tsx
src/desktop/apps/editorial_features/components/gucci/components/nav/sections_nav.tsx
src/desktop/apps/editorial_features/components/gucci/components/series/series_header.tsx
src/desktop/assets/analytics.ts
src/desktop/lib/__tests__/global_client_setup.jest.ts
src/desktop/lib/buildClientAppContext.ts
src/desktop/lib/deprecated_global_client_setup.tsx
src/lib/analytics/__tests__/helpers.jest.ts
src/lib/analytics/helpers.ts
src/lib/analytics/setAnalyticsClientReferrerOptions.ts
src/lib/analytics/timeOnPageListener.ts
src/lib/analytics/trackPageView.ts
src/lib/getContextPage.ts
src/lib/userPerformanceMetrics.ts
src/v2/DevTools/MockBoot.tsx
src/v2/System/Router/buildClientApp.tsx
src/v2/client.tsx

This PR solves: https://www.notion.so/artsy/92189f632add4fc3abf177c8ead3279d?v=a888de39a73c4f0ea0af683953932d7f&p=b56a6ca90a2745daabcffd6ef00f1937
This PR removes as many // @ts-expect-error PLEASE_FIX_ME_STRICT_NULL_CHECK_MIGRATION as possible as a refinathon project.

[Refinathon]: AlicanAkyuz/Fix-TS-errors-from-strict-null-check-migration

---

src/v2/Apps/Artist/Components/ArtistMeta.tsx
src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignMeta.tsx
src/v2/Apps/Artist/Routes/Consign/Components/ArtistConsignPageViews.tsx
src/v2/Apps/Artist/Routes/Overview/Components/ArtistWorksForSaleRail.tsx
src/v2/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx
src/v2/Apps/ArtistSeries/Components/ArtistSeriesMeta.tsx
src/v2/Apps/Artists/Routes/ArtistsByLetter.tsx
src/v2/Apps/Artists/__tests__/ArtistsByLetter.jest.tsx
src/v2/Apps/Artwork/ArtworkApp.tsx
src/v2/Apps/Artwork/Components/ArtistInfo.tsx
src/v2/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromArtsy.tsx
src/v2/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
src/v2/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
src/v2/Apps/Artwork/Components/PricingContext.tsx
src/v2/Apps/Artwork/Components/__tests__/ArtistInfo.jest.tsx
src/v2/Apps/Artwork/Components/__tests__/PricingContext.jest.tsx
src/v2/Components/Pagination/index.tsx
src/v2/Utils/identityVerificationRequirements.ts

This PR solves: https://www.notion.so/artsy/92189f632add4fc3abf177c8ead3279d?v=a888de39a73c4f0ea0af683953932d7f&p=b56a6ca90a2745daabcffd6ef00f1937
This PR focuses on Artist and Artwork apps to remove comments remaining from strict null check migration.

[Refinathon]: AlicanAkyuz/Fix-TS-errors-from-strict-null-check-migration-in-v2Apps

---

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx
src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
src/v2/__generated__/SavedSearchAlertEditFormQuery.graphql.ts
src/v2/__generated__/SavedSearchAlertEditForm_Test_Query.graphql.ts

Remove `ARTIST` aggregation from query

chore: don't query ARTIST aggregation for edit alert flow

---

.secrets.baseline
src/v2/Apps/ArtAppraisals/ArtAppraisalsApp.tsx

This PR solves [GRO-1133]
Replace email of Simon with the general appraisals@artsymail.com address. I also update the email address for the "Request an Appraisal" button at the top of the page.
[GRO-1133]: https://artsyproduct.atlassian.net/browse/GRO-1133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore:update email for appraisals page to appraisals@artsymail.com

---

src/v2/Apps/Onboarding/Components/OnboardingFigure.tsx
src/v2/Apps/Onboarding/Components/OnboardingGene.tsx
src/v2/Apps/Onboarding/Components/OnboardingLoadingCollection.tsx
src/v2/Apps/Onboarding/Components/OnboardingModal.tsx
src/v2/Apps/Onboarding/Components/OnboardingWelcomeAnimatedPanel.tsx
src/v2/Apps/Onboarding/Views/OnboardingArtistsOnTheRise.tsx
src/v2/Apps/Onboarding/Views/OnboardingCuratedArtworks.tsx
src/v2/Apps/Onboarding/Views/OnboardingQuestionOne.tsx
src/v2/Apps/Onboarding/Views/OnboardingQuestionThree.tsx
src/v2/Apps/Onboarding/Views/OnboardingQuestionTwo.tsx
src/v2/Apps/Onboarding/Views/OnboardingTopAuctionLots.tsx
src/v2/Apps/Onboarding/Views/OnboardingWelcome.tsx

https://user-images.githubusercontent.com/112297/177420164-d9b0a3e3-9136-4225-8023-d2666911c85e.mov
The animated columns will be updated with crops that I don't have yet.

feat(onboarding): blocks in initial img assets

---

src/v2/Apps/Onboarding/Components/OnboardingGene.tsx
src/v2/Apps/Onboarding/Components/OnboardingLoadingCollection.tsx
src/v2/Apps/Onboarding/Components/OnboardingQuestionPanel.tsx
src/v2/Apps/Onboarding/Components/OnboardingSplitLayout.tsx
src/v2/Apps/Onboarding/Views/OnboardingQuestionOne.tsx
src/v2/Apps/Onboarding/Views/OnboardingQuestionThree.tsx
src/v2/Apps/Onboarding/Views/OnboardingQuestionTwo.tsx
src/v2/Apps/Onboarding/Views/OnboardingWelcome.tsx
src/v2/Components/Artwork/Badge.tsx

Working through: [GRO-1138](https://artsyproduct.atlassian.net/browse/GRO-1138)
I need to get my FollowButton refactor merged to make some minor changes to the Gene header. Up next.

chore(onboarding): mobile pass

---

src/v2/Apps/Onboarding/Components/OnboardingGene.tsx
src/v2/Apps/Onboarding/Components/OnboardingModal.tsx
src/v2/Apps/Onboarding/Views/OnboardingCuratedArtworks.tsx
src/v2/Apps/Onboarding/Views/OnboardingTopAuctionLots.tsx

Closes: [GRO-1138](https://artsyproduct.atlassian.net/browse/GRO-1138)

fix(onboarding): remaining mobile layout tweaks

---

src/v2/Apps/Onboarding/Views/OnboardingQuestionOne.tsx
src/v2/__generated__/OnboardingQuestionOneMutation.graphql.ts

Re: [GRO-1140](https://artsyproduct.atlassian.net/browse/GRO-1140)
No analytics yet; this just persists the corresponding collector level to the user model.

feat(onboarding): saves collector level

---

src/v2/Apps/Onboarding/Components/OnboardingWelcomeAnimatedPanel.tsx
src/v2/Apps/Onboarding/Views/OnboardingWelcome.tsx

Updates the crop images on the animated columns; closes [GRO-1087](https://artsyproduct.atlassian.net/browse/GRO-1087)

fix(onboarding): updates crops; adds name

---

src/v2/Apps/Onboarding/Components/OnboardingOrderedSet.tsx
src/v2/Apps/Onboarding/Components/__tests__/OnboardingFollowArtists.jest.tsx
src/v2/Apps/Onboarding/Components/__tests__/OnboardingOrderedSet.jest.tsx
src/v2/Apps/Onboarding/Components/__tests__/OnboardingSearchResults.jest.tsx
src/v2/Apps/Onboarding/Views/OnboardingFollowArtists.tsx
src/v2/__generated__/OnboardingOrderedSet_Test_Query.graphql.ts
src/v2/__generated__/OnboardingSearchResults_Test_Query.graphql.ts

The type of this PR is: _test_
This PR solves [GRO-1100] & [GRO-1096]
This is a simple follow-up test PR to compliment the work done on building the 'Follow Artists' & 'Follow Galleries' views that the user sees at the end of Onboarding flow. 
[GRO-1100]: https://artsyproduct.atlassian.net/browse/GRO-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1096]: https://artsyproduct.atlassian.net/browse/GRO-1096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(onboarding): render testing for follow artists and galleries view

---

src/v2/Apps/Home/HomeApp.tsx
src/v2/Apps/Home/Hooks/useOnboarding.tsx
src/v2/Apps/Onboarding/OnboardingApp.tsx
src/v2/Components/Onboarding/Components/OnboardingDebug.tsx
src/v2/Components/Onboarding/Components/OnboardingFollows.tsx
src/v2/Components/Onboarding/Components/OnboardingOrderedSet.tsx
src/v2/Components/Onboarding/Components/OnboardingProgress.tsx
src/v2/Components/Onboarding/Components/OnboardingSearchResults.tsx
src/v2/Components/Onboarding/Components/OnboardingSteps.tsx
src/v2/Components/Onboarding/Components/__tests__/OnboardingFollowArtists.jest.tsx
src/v2/Components/Onboarding/Hooks/useOnboarding.tsx
src/v2/Components/Onboarding/Hooks/useOnboardingContext.tsx
src/v2/Components/Onboarding/Views/OnboardingQuestionOne.tsx
src/v2/Components/Onboarding/Views/OnboardingQuestionThree.tsx
src/v2/Components/Onboarding/Views/OnboardingQuestionTwo.tsx
src/v2/Components/Onboarding/Views/OnboardingWelcome.tsx
src/v2/Components/Onboarding/__tests__/config.jest.ts
src/v2/Components/Onboarding/config.ts
src/v2/Components/Onboarding/index.ts

This PR allows the onboarding modal to be triggered from the homepage with the existence of a query param: `?onboarding=true`

feat(onboarding): adds query param trigger

---

src/v2/Apps/Article/Components/ArticleAd/ArticleAd.story.tsx
src/v2/Apps/Home/Components/HomePersonalizeMore/HomePersonalizeMore.story.tsx
src/v2/Apps/Home/Components/HomePersonalizeMore/HomePersonalizeMore.tsx
src/v2/Apps/Home/Components/HomePersonalizeMore/HomePersonalizeMoreCard.tsx

Adds the components. Open question for the conditions under which they are displayed and dismissed though.

feat(GRO-1101): personalize more cards/rail

---

cypress/integration/home.spec.ts
src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnits.tsx

This reverses https://github.com/artsy/force/pull/10071 putting the world back the way it was.
https://artsyproduct.atlassian.net/browse/GRO-1025

feat: Stop suppressing logged out hero GRO-1025

---

scripts/uploadToS3.js

This fixes the upload path for our files as the script has moved.

fix(ci): Fix s3 upload path

---

src/v2/Apps/Feature/Components/FeatureFeaturedLink.tsx
src/v2/Apps/ViewingRoom/ViewingRoomApp.tsx
src/v2/System/Router/Boot.tsx
src/v2/System/Router/__tests__/Boot.jest.tsx

We can get rid of this component + dependency entirely now.

chore: removes deprecated grid component

---

docs/troubleshooting.md

removed empty bullet point from docs

docs: Removed empty bulletpoint

---

src/v2/Apps/Order/Components/BankAccountPicker.tsx
src/v2/Apps/Order/Components/InsufficientFundsError.tsx
src/v2/Apps/Order/Components/PollAccountBalance.tsx
src/v2/Apps/Order/Components/__tests__/BankAccountPicker.jest.tsx
src/v2/Apps/Order/Components/__tests__/InsufficientFundsError.jest.tsx
src/v2/Apps/Order/Components/__tests__/PollAccountBalance.jest.tsx
src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
src/v2/Apps/Order/Routes/Payment/index.tsx
src/v2/Apps/__tests__/Fixtures/Order.ts
src/v2/Components/BankDebitForm/BankDebitForm.tsx
src/v2/Components/BankDebitForm/BankDebitProvider.tsx
src/v2/Components/BankDebitForm/__tests__/BankDebitForm.jest.tsx
src/v2/Components/BankDebitForm/__tests__/BankDebitProvider.jest.tsx
src/v2/__generated__/PaymentTestQuery.graphql.ts
src/v2/__generated__/Payment_order.graphql.ts
src/v2/__generated__/PollAccountBalanceQuery.graphql.ts
src/v2/__generated__/PollAccountBalanceQuery_Test_Query.graphql.ts
src/v2/__generated__/PollAccountBalance_commerceBankAccountBalance.graphql.ts
src/v2/__generated__/orderRoutes_PaymentQuery.graphql.ts

This PR solves [TX-348]
This PR adds the feature of checking user's stripe-linked bank account balance before progressing to the review step from the payment step. 
[TX-348]: https://artsyproduct.atlassian.net/browse/TX-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://user-images.githubusercontent.com/42584148/177786836-e4b00992-67ce-4fb4-bea6-13fcc4ec7976.mov
https://user-images.githubusercontent.com/42584148/177786929-3d08dd5f-1570-418d-b8c5-c2ac636b2cad.mov

[feat]: AlicanAkyuz/TX-348/Poll bank account balance

---

src/v2/Apps/Order/Routes/Accept/index.tsx
src/v2/Apps/Order/Routes/NewPayment/index.tsx
src/v2/Apps/Order/Routes/__tests__/NewPayment.jest.tsx
src/v2/Apps/Order/redirects.tsx

This PR solves [TX-376]
This PR allows to change payment method to credit card for bank transfer orders.
[TX-376]: https://artsyproduct.atlassian.net/browse/TX-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WIP]feat: update fix failed payment to support the bank transfers.

---

src/Apps/Order/OrderApp.tsx
src/Apps/Order/__tests__/OrderApp.jest.tsx
src/Apps/Order/orderRoutes.tsx
src/__generated__/orderRoutes_OrderQuery.graphql.ts

This PR refactors OrderApp into a functional component and had some clean up along the way.

[enc]: AlicanAkyuz/FF/Refactor Order App

---

src/Components/BankDebitForm/BankDebitForm.tsx
src/Components/BankDebitForm/BankDebitProvider.tsx
src/__generated__/EnableSecondFactorMutation.graphql.ts
src/__generated__/useCreateSettingsBackupSecondFactorsMutation.graphql.ts

This PR solves [TX-281]
This PR adds two new test attributes for the new Bank transfer tests.
[TX-281]: https://artsyproduct.atlassian.net/browse/TX-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Kiryl zubarau/tx 281 add test attributes

---

src/Components/Onboarding/Components/OnboardingGene.tsx
src/Components/Onboarding/Components/OnboardingOrderedSet.tsx
src/Components/Onboarding/Views/OnboardingWelcome.tsx

This PR solves
- [GRO-1154]
- [GRO-1155]
Fixes 
- User who clicks "skip" closes the modal and does not reload
- When user clicks artist name on follow screen, do not go to artist page
[GRO-1154]: https://artsyproduct.atlassian.net/browse/GRO-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1155]: https://artsyproduct.atlassian.net/browse/GRO-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(onboarding): Address a few QA tickets 

---

src/Apps/Order/Components/BankAccountPicker.tsx

This PR solves [TX-281]
This PR adds a test attribute for the bank account list
[TX-281]: https://artsyproduct.atlassian.net/browse/TX-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add test attribute

---

src/Apps/Order/Components/BankAccountPicker.tsx
src/Components/BankDebitForm/BankDebitForm.tsx

This PR solves [TX-281]
This PR updates test attributes for the save and continue buttons
[TX-281]: https://artsyproduct.atlassian.net/browse/TX-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update test attributes

---

src/Apps/Order/Components/BankAccountPicker.tsx
src/Components/BankDebitForm/BankDebitForm.tsx
src/Components/BankDebitForm/BankDebitProvider.tsx
src/Components/CreditCardInput/CreditCardInput.tsx

This PR updates some test attributes.

chore: update test attributes

---

src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx

Adds "My Collection" entry to the mobile menu (behind the `my-collection-web` feature flag).

feat: Add My Collection to mobile menu (behind feature flag)

---

src/Components/Onboarding/Components/OnboardingFollows.tsx
src/Components/Onboarding/Components/OnboardingSearchResults.tsx
src/Components/Onboarding/Components/__tests__/OnboardingSearchResults.jest.tsx

The type of this PR is: _fix_
This PR solves these jira tickets:
[GRO-1173]
[GRO-1174]
[GRO-1175]
The intention of this PR is to handle tickets that resulted from onboarding QA feedback happening in various slack threads. All of these tickets are related to the follow artist/gallery views so I bundled a bunch of these small bug fixes & copy changes into one PR. 
- changed the zero state copy from "no results found" to an interpolated string that includes the search query for the user to see and updated the test for this
- fixed a bug that caused the zero state copy to pop up when the user inputs less than 2 chars
- changed the button on the follow views to say "next" instead of "done" w/ the intention of a follow up PR to include the "thank you" screen that follows
[GRO-434]: …

fix(onboarding): onboarding follow screens fixes

---

src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx
src/Components/NavBar/menuData.ts

This PR solves [FX-4114]
Review app: https://update-nav-links.artsy.net/
| <img width="634" alt="before-1" src="https://user-images.githubusercontent.com/3513494/182102086-4809f541-f277-4e9b-8050-a25d7d044dca.png"> | <img width="551" alt="after-1" src="https://user-images.githubusercontent.com/3513494/182102121-f9dfc270-1f32-432a-b46a-7f40e35215c5.png"> |
| <img width="741" alt="before-2" src="https://user-images.githubusercontent.com/3513494/182102348-db6fb8c5-34ee-4695-b808-68c028a51422.png"> | <img width="741" alt="after-2" src="https://user-images.githubusercontent.com/3513494/182104089-5646e8e1-6819-47a0-96cf-59be8aaf610b.png"> |
[FX-4114]: …

chore(FX-4114): update nav links

---

src/Components/Onboarding/Components/OnboardingDebug.tsx
src/Components/Onboarding/Components/OnboardingModal.tsx
src/Components/Onboarding/Components/OnboardingSplitLayout.tsx
src/Components/Onboarding/Hooks/useOnboarding.tsx
src/Components/Onboarding/Views/OnboardingWelcome.tsx

This PR adjusts the layout slightly to be slightly more responsive. 

fix(onboarding): Make slightly more responsive

---

src/Components/NavBar/menuData.ts

Request from Merch team to update the text on this link!

chore: update nav text for collection

---

src/Apps/Settings/Routes/MyCollection/Components/HowMyCollectionWorks.tsx
src/Apps/Settings/Routes/MyCollection/Components/MyCollectionAppDownload.tsx
src/Apps/Settings/Routes/MyCollection/Components/MyCollectionBenefits.tsx
src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
src/Components/Artwork/Details.tsx
src/Components/Artwork/GridItem.tsx
src/Components/Artwork/Metadata.tsx
src/Components/Artwork/__tests__/Details.jest.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx

This PR solves [CX-2680]
- Fixes all outstanding issues as outlined in the attached Jira ticket
[CX-2680]: https://artsyproduct.atlassian.net/browse/CX-2680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2680): fix my collection web phase 1 issues

---

src/Components/Onboarding/Components/OnboardingModal.tsx

Fixes issue where dialog was shifting in height due to props being overwritten with a spread.

fix(onboarding): Fix responsive shift

---

src/Apps/Order/Routes/Review/index.tsx
src/Apps/Order/Routes/__tests__/Review.jest.tsx

This PR solves [TX-421]
This is a take II of https://github.com/artsy/force/pull/10376. It's almost identical and I'll comment inline the difference.
Since the previous attempt caused an issue, I assign this to myself and plan to merge and monitor in the morning ET.
[TX-421]: https://artsyproduct.atlassian.net/browse/TX-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: disable submit button on review step until stripe is loaded (take II)

---

src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx

Addresses [CX-2692]
Move "My Collection" entry down in the mobile menu.
[CX-2692]: https://artsyproduct.atlassian.net/browse/CX-2692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Move My Collection down in mobile menu

---

src/Apps/Settings/Routes/MyCollection/Components/MyCollectionAppDownload.tsx

Addresses [CX-2691]
Change My Collection landing page subtitle copy.
[CX-2691]: https://artsyproduct.atlassian.net/browse/CX-2691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Change My Collection landing page subtitle copy

---

src/Apps/Order/Components/TwoColumnLayout.tsx

This PR solves [TX-405]
This PR fixes lost connected account on screen size change.
https://user-images.githubusercontent.com/79979820/182350210-0f9e65e3-1d56-475a-b516-020ba1f428c2.mp4
[TX-405]: https://artsyproduct.atlassian.net/browse/TX-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove media components for the two column layout

---

src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx

This PR solves [CX-2690]
Updates My Collection banner style
[CX-2690]: https://artsyproduct.atlassian.net/browse/CX-2690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix [CX-2690]: Update My Collection banner style

---

src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx

This PR solves [CX-2694]
This PR updates the interaction with the Download Artsy App banner in My Collection 
https://user-images.githubusercontent.com/20655703/182677455-f67349dc-18b4-4387-b34c-41dba86d1cfe.mp4
[CX-2694]: https://artsyproduct.atlassian.net/browse/CX-2694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix [CX-2694]: Update my collection banner interaction

---

src/Apps/About2/AboutApp2.tsx
src/Components/NavBar/NavBar.tsx

Finishes up some UI stuff around /about2, including adding nav buttons to the links. 

chore(about2): Updates UI

---

src/Components/Links/StyledLink.tsx
src/Components/Onboarding/Components/OnboardingProgress.tsx
src/Components/Onboarding/Hooks/useOnboardingContext.tsx
src/Components/Onboarding/config.ts
src/Utils/WorkflowEngine.tsx
src/Utils/__tests__/WorkflowEngine.jest.ts

This PR solves [GRO-1152]
This adds back button support to the modal so the user can go back and change their answers: 
[GRO-1152]: https://artsyproduct.atlassian.net/browse/GRO-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onboarding): Add back button

---

src/Components/Links/BackLink.tsx
src/Components/Onboarding/Components/OnboardingProgress.tsx

Fixes small issue with font weight and position to match close

fix(onboarding): Link position

---

src/Apps/Settings/Routes/MyCollection/Components/DownloadAppBadgesDark.tsx
src/Apps/Settings/Routes/MyCollection/Components/EmptyMyCollectionPage.tsx
src/Apps/Settings/Routes/MyCollection/Components/MyCollectionAppDownload.tsx
src/Apps/Settings/Routes/MyCollection/Components/MyCollectionBenefits.tsx

This PR solves [CX-2715]
This PR updates the spacing and the font sizes in My Collection empty state
| Mobile| Desktop|
|--|--|
| ![image](https://user-images.githubusercontent.com/20655703/183065437-16ec50a7-05fe-423b-aca5-6e085aa1f3a9.png) | ![image](https://user-images.githubusercontent.com/20655703/183065980-3d0f3ce5-d4c1-498f-88f2-d8e602553f3a.png) |
| ![image](https://user-images.githubusercontent.com/20655703/183065540-f3568521-d1e2-4a40-aaca-84dd952c2bd2.png) | ![image](https://user-images.githubusercontent.com/20655703/183066073-7876d0c1-3a9e-4f39-a03e-e2cfac6293b3.png) |
[CX-2715]: …

fix[CX-2715]: Update My Collection empty state spacing and font sizes

---

src/Components/NavBar/NavBarPrimaryLogo.tsx

Adds `.focus-visible` to the logo for accessibility.

fix(logo): Add focus-visible class

---

src/Components/Onboarding/config.ts

This PR solves [GRO-1178]
[GRO-1178]: https://artsyproduct.atlassian.net/browse/GRO-1178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(onboarding): change follow artist & galleries buttons copy

---

src/Apps/Artist/Routes/CV/ArtistCVRoute.tsx
src/Apps/Artist/Routes/CV/Components/ArtistCVGroup.tsx
src/System/i18n/locales/en-US/translation.json

I goofed a rebase over on https://github.com/artsy/force/pull/10639 and it ended up getting merged due to a `merge-on-green` label so this PR fixes what I had messed up.

Fix: clean up artist cv mess

---

src/Apps/About/AboutApp.tsx

Fixes captions and sizing on credits. 

chore(about): Update captions

---

src/Apps/Settings/SettingsApp.tsx

This PR solves [CX-2715]
This PR updates the greeting statement in the Settings app to add an apostrophe to it according to the design
[CX-2715]: https://artsyproduct.atlassian.net/browse/CX-2715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat[CX-2715]: Update Settings page greeting statement

---

src/__generated__/SettingsPurchases_Test_Query.graphql.ts
src/__generated__/SettingsPurchases_me.graphql.ts
src/__generated__/settingsRoutes_PurchasesRouteQuery.graphql.ts

#10726 didn't include the generated files, this fixes that.

chore(TX-562): include missing generated files

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.jest.tsx
src/Apps/Auction/Components/RegisterButton.tsx
src/Apps/Auction/Components/__tests__/RegisterButton.jest.tsx
src/Apps/Authentication/Components/AuthStatic.tsx
src/Components/Inquiry/Views/InquirySignUp.tsx
src/Components/Inquiry/__tests__/Views/InquirySignUp.jest.tsx
src/Components/Modal/ModalHeader.tsx
src/Components/NavBar/NavBar.tsx
src/Components/NavBar/__tests__/NavBar.jest.tsx
src/Components/SavedSearchAlert/Components/ActiveFilterPillsAndCreateAlert.tsx
src/Components/SavedSearchAlert/Components/__tests__/SavedSearchCreateAlertButtonContainer.jest.tsx
src/Utils/Hooks/useScrollToOpenArtistAuthModal.ts

This PR solves [GRO-1141]
**Full /signup page**
--
**Any page—log in/sign up buttons on the top of the nav bar**
--
**User scrolls on an artist page**
--
**User scrolls for a while in an article**
--
**User attempts to `Buy Now`**
--
**User attempts to `Make Offer`**
--
**User attempts to inquire**
--
**User attempts to bid on an auction page or register to bid**
--
**User attempts to create an alert from the artwork page or an artist page**
--
Will merge on approval
[GRO-1141]: https://artsyproduct.atlassian.net/browse/GRO-1141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Chore(copy): auth static form & modal copy changes

---

src/Apps/Order/Routes/Offer/index.tsx

This PR solves [TX-514]
This PR translates order app's offer route to a functional component. 
[TX-514]: https://artsyproduct.atlassian.net/browse/TX-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TX-514): AlicanAkyuz/Translate offer route to FC

---

.gitignore

Somehow our .swc compiler artifacts got checked in! Not sure.

fix(compiler): Remove compiler artifacts

---

src/Apps/About/AboutApp.tsx

This PR solves [GRO-1204]
Updates the images to include a bit of fade so that captions show up. 
[GRO-1204]: https://artsyproduct.atlassian.net/browse/GRO-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(about): Update images

---

src/Apps/About/AboutApp.tsx

Minor updates to fix images and credits.
<details>
<summary>full page screenshot</summary>
</details>
https://artsyproduct.atlassian.net/browse/GRO-1209
/cc @artsy/grow-devs @jpoczik

fix: Update about images and credits GRO-1209

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx

This PR solves layout issues inside my collection
**Before**
**After**

fix: layout issue on my collection artwork page

---

src/Apps/Settings/SettingsApp.tsx
src/Components/NavBar/Menus/NavBarUserMenu.tsx
src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx

This PR solves [CX-2717]
This PR removes the `my-collection-web` feature flag and the code related to it
[CX-2717]: https://artsyproduct.atlassian.net/browse/CX-2717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2717): Remove My Collection feature flag

---

src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
src/Apps/MyCollection/Routes/EditArtwork/Utils/useCreateOrUpdateArtwork.ts

This PR fixes a few things I've missed in https://github.com/artsy/force/pull/10732.

fix: make MyC artwork upload flow work again

---

src/Apps/MyCollection/myCollectionRoutes.tsx

- force update my collection artworks to make sure deleted artworks do not show up immediately

fix: force update my collection artworks

---

src/Components/Onboarding/Views/OnboardingWelcome.tsx

This PR is part of the work that fixes the integration tests failing in integrity. Adding a `data-test-id` helps select the skip button in cypress tests. 

fix(onboarding): add data-test id for integration testing

---

.circleci/config.yml

Seeing what happens if we bump parallelism to 6 on circle

ci(circle): test parallelism of 6

---

src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Routes/__tests__/Shipping.jest.tsx

This PR solves [TX-517]
This PR refactors /shipping route in Order App to a functional component. 
[TX-517]: https://artsyproduct.atlassian.net/browse/TX-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TX-517): Alican/Order shipping route to FC

---

.secrets.baseline
cypress/integration/myCollection.spec.ts
src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/ArtworkForm.jest.tsx
src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
src/DevTools/setupTestWrapper.tsx
src/__generated__/ArtworkFormTest_Query.graphql.ts

This PR adds the missing tests for the My Collection artwork form.

chore: Add My Collection artwork form test

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkComparables.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
src/__generated__/MyCollectionArtworkComparables_artwork.graphql.ts
src/__generated__/MyCollectionArtwork_artwork.graphql.ts
src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts

This PR solves [CX-2739]
Add "Comparable works" section to the artwork page
Hidden behind a FF
[CX-2739]: https://artsyproduct.atlassian.net/browse/CX-2739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat:  Add "Comparable works" section 

---

src/Apps/Order/Routes/Payment/PaymentContent.tsx
src/Apps/Order/Routes/__tests__/Payment.jest.tsx

This PR solves [TX-597]
This PR updates the description body that is rendered below the payment option on the payment route of the checkout flow. 
[TX-597]: https://artsyproduct.atlassian.net/browse/TX-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(TX-597): Alican/Update copy for ACH explanation on checkout flow

---

src/Apps/Order/Routes/Payment/PaymentContent.tsx
src/Apps/Order/Routes/__tests__/Payment.jest.tsx

This PR solves [TX-608]
This PR updates the description body for the SEPA payment method on the checkout flow. 
[TX-608]: https://artsyproduct.atlassian.net/browse/TX-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(TX-608): Update copy for SEPA payment method

---

src/Server/analytics/segmentOneTrustIntegration/setTrackingPreferences.ts
src/server.ts

Quick PR to move some of our cookie setting code out of the main server file.

refactor(one-trust): Move cookie setting code

---

src/Apps/Artwork/Components/ArtworkSidebarClassificationsModal.tsx

Addresses [CX-2771]
Change rarity modal copy from "Artwork classifications" to "Rarity classifications".
[CX-2771]: https://artsyproduct.atlassian.net/browse/CX-2771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Change rarity modal copy

---

src/Apps/About/AboutApp.tsx
src/Apps/Auctions/Components/CuritorialRailsTabBar.tsx
src/Apps/Auctions/Components/__tests__/CuritorialRailsTabBar.jest.tsx
src/Apps/Home/Components/HomeMeta.tsx
src/Components/NavBar/NavBar.tsx
src/System/Router/interceptLinks.ts
src/__generated__/AuctionsApp_Test_Query.graphql.ts
src/__generated__/CuritorialRailsTabBar_Test_Query.graphql.ts
src/__generated__/CuritorialRailsTabBar_viewer.graphql.ts

This PR solves
- SEO OpenGraph images on home and about https://artsyproduct.atlassian.net/browse/GRO-1207
- Update NavBar with new NFT link: https://artsyproduct.atlassian.net/browse/GRO-1186 
- Persist Editorial in NavBar: https://artsyproduct.atlassian.net/browse/GRO-1233 
- Only show /auctions WFY tab if following artist from auction: https://artsyproduct.atlassian.net/browse/GRO-1192

chore(grow): Address misc tickets

---

src/Components/StepSummaryItem.tsx

This PR solves [TX-583]
This PR fixes wrong icon position of the payment section on sidebar
Before
Now
[TX-583]: https://artsyproduct.atlassian.net/browse/TX-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: review offer side panel

---

hokusai/staging.yml

This PR solves PLATFORM-4514
Part of spike on using AWS Spot instances.
[Had created spot tier](https://github.com/artsy/substance/pull/283) in staging Kubernetes cluster.

feat: run some staging pods in kubernetes spot tier.

---

src/Apps/Order/Components/BankAccountPicker.tsx
src/Components/BankDebitForm/BankDebitForm.tsx
src/Components/BankDebitForm/BankDebitProvider.tsx
src/Components/BankDebitForm/__tests__/BankDebitForm.jest.tsx
src/Components/BankDebitForm/__tests__/BankDebitProvider.jest.tsx

The type of this PR is: **Refactor/fix**
This PR solves [TX-578]
This PR prevents unnecessary transaction creation by calling `CreateBankDebitSetupForOrderMutation`. 
[TX-578]: https://artsyproduct.atlassian.net/browse/TX-578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TX-578) - Unnecessary setup intent creation

---

docs/feature_flagging.md

Updates feature flag docs to using https://tools.artsy.net/feature-flags over unleash

docs: Update feature flag docs

---

src/Apps/NewForYou/newForYouRoutes.tsx

We had some emails go out with this param as lower so this PR just defends against that case by converting it to upper.
/cc @artsy/grow-devs @isakelaris @SamRozen

fix: Coerce version to uppercase

---

src/Components/Notifications/NotificationsList.tsx
src/__generated__/NotificationsListNextQuery.graphql.ts
src/__generated__/NotificationsListQuery.graphql.ts
src/__generated__/NotificationsList_viewer.graphql.ts

This PR solves [FX-4175]
Review app: https://pagination-for-activity-panel.artsy.net/notifications
Implement pagination using the "show more" button on an Activity Panel standalone page.
[FX-4175]: https://artsyproduct.atlassian.net/browse/FX-4175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4175): add pagination for activity panel page

---

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx
src/Apps/MyCollection/myCollectionRoutes.tsx

- Improves MyC photo upload error handling.
- Adds missing functionality to abort the photo upload.

fix: Improve MyC photo upload error handling

---

src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx

Add MyC Save button loading state when processing images.

feat: Add MyC Save button loading state when processing images

---

src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/MyCollectionArtworkNoImageComponent.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/__tests__/MyCollectionArtworkImageBrowser.jest.tsx
src/Apps/MyCollection/myCollectionRoutes.tsx

Addresses [CX-2745]
Add upload photos step.
[CX-2745]: https://artsyproduct.atlassian.net/browse/CX-2745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add upload photos step

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx

This PR solves [CX-2863]
This PR updates the tabs to match the design
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/20655703/187477478-e9201195-969d-414a-98e4-974abe1c4db0.png) | ![image](https://user-images.githubusercontent.com/20655703/187477501-a9d3cb0d-4a13-4ef9-9ecc-71fed65a9cd5.png)|
[CX-2863]: https://artsyproduct.atlassian.net/browse/CX-2863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CX-2863): Update tabs design

---

src/Apps/Notifications/NotificationsApp.tsx
src/Components/Notifications/Notifications.tsx
src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/__tests__/Notifications.jest.tsx
src/__generated__/NotificationsListNextQuery.graphql.ts
src/__generated__/NotificationsListQuery.graphql.ts
src/__generated__/NotificationsList_test_Query.graphql.ts
src/__generated__/NotificationsList_viewer.graphql.ts

This PR solves [FX-4176]
Review app: https://tabs-for-activity-panel.artsy.net/notifications
* Implement All / Alerts  tabs on the Activity Panel standalone page.
* Use `notificationTypes` field exposed in [this ticket](https://artsyproduct.atlassian.net/browse/FX-4153).
[FX-4176]: https://artsyproduct.atlassian.net/browse/FX-4176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4176): Implement All / Alerts  tabs on the Activity Panel standalone page.

---

src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx

This PR solves [CX-2775]
Change the Current confirmation page to the new design 
| Desktop | mWeb |
| --- | --- |
| <img width="1451" alt="image" src="https://user-images.githubusercontent.com/36167539/187491571-72f45733-76f3-495a-a091-8ebebe8704a3.png"> | <img width="510" alt="image" src="https://user-images.githubusercontent.com/36167539/187491610-839d652c-8359-48a0-bf42-639c6e82d892.png"> |
[CX-2775]: https://artsyproduct.atlassian.net/browse/CX-2775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: change confirmation page

---

src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx

This PR updates the content (button) for the Thank You page in the SWA flow
| Authenticated | Anonymous |
| -- | -- |
| <img width="985" alt="image" src="https://user-images.githubusercontent.com/20655703/187881272-29a03965-b6ff-4d0d-a3e1-cf8ecc7a660b.png"> | ![image](https://user-images.githubusercontent.com/20655703/187881311-023c46e7-1931-41b0-a6e4-f127471867b7.png) |

fix: update SWA content for non-logged-in users

---

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ShippingInformation.tsx
src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2Artists.jest.tsx
src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2ArtworkTitle.jest.tsx
src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2ShippingInformation.jest.tsx
src/__generated__/ArtworkSidebar2Artists_Test_Query.graphql.ts
src/__generated__/ArtworkSidebar2ArtworkTitle_Test_Query.graphql.ts
src/__generated__/ArtworkSidebar2ShippingInformation_Test_Query.graphql.ts

Adds some tests for artworkSidebar2 components.
Paired with @mdole 

test: artwork sidebar2 tests

---

src/Apps/Order/Routes/Payment/PaymentContent.tsx
src/Apps/Order/Routes/__tests__/Payment.jest.tsx

Fulfills [TX-634]
This PR Contains minor copy updates for the sepa payment content.
Compare to [figma](https://www.figma.com/file/rhcgsn0cMrogxN0TXu5l6T/TX-ACH-Bank-Transfer%2F-Wire-transfer?node-id=8540%3A62912) (note: countries listed in tooltip are unchanged)
[TX-634]: https://artsyproduct.atlassian.net/browse/TX-634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update sepa payment description copy

---

src/Apps/Order/Components/BankAccountPicker.tsx
src/Components/BankDebitForm/__tests__/BankDebitProvider.jest.tsx
src/__generated__/BankAccountPickerTestQuery.graphql.ts
src/__generated__/BankAccountPicker_order.graphql.ts
src/__generated__/PaymentTestQuery.graphql.ts
src/__generated__/orderRoutes_PaymentQuery.graphql.ts

This PR solves [TX-420]
This PR allows that when a buyer changes payment method in the review step and goes back to the payment step, they see their unsaved bank account pre-selected. 
https://user-images.githubusercontent.com/42584148/188600027-20554121-3e8e-4d9e-ab60-9cc063e54fcc.mov
[TX-420]: https://artsyproduct.atlassian.net/browse/TX-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(tx-420): alican/payment method change from review step

---

src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2Details.jest.tsx

Fix failed test for artsy/force#10914

fix: failed test for `ArtworkSidebar2Details`

---

src/Apps/Notifications/NotificationsApp.tsx
src/Components/NavBar/Menus/NavBarNewNotifications.tsx
src/Components/Notifications/NotificationItem.tsx
src/Components/Notifications/Notifications.tsx
src/Components/Notifications/NotificationsList.tsx
src/Components/Notifications/NotificationsTabs.tsx
src/Components/Notifications/__tests__/Notifications.jest.tsx

This PR solves [FX-4197], [FX-4195]
Review app: https://activity-panel-improvements.artsy.net/
* Added hover states
* Made tabs sticky to the top
https://user-images.githubusercontent.com/3513494/188157628-960242ef-2ed4-4225-b695-550d43573944.mp4
https://user-images.githubusercontent.com/3513494/188157720-91737225-35bd-410d-b4c8-e371ae1ba351.mp4
[FX-4197]: https://artsyproduct.atlassian.net/browse/FX-4197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FX-4195]: https://artsyproduct.atlassian.net/browse/FX-4195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-4197, FX-4195): activity panel improvements

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarTitleInfo.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebar.jest.tsx
src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
src/__generated__/MyCollectionArtworkSidebarMetadataTestQuery.graphql.ts
src/__generated__/MyCollectionArtworkSidebarTestQuery.graphql.ts
src/__generated__/MyCollectionArtworkSidebarTitleInfo_artwork.graphql.ts
src/__generated__/MyCollectionArtworkTestQuery.graphql.ts
src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts

This PR solves [CX-2845]
This PR updates MyC artwork details page to include the artist link
[CX-2845]: https://artsyproduct.atlassian.net/browse/CX-2845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-2845): Add artist link to MyC artwork details page

---

docs/unleash_a-b_testing.md

Updates A/B test docs with steps for using tools.artsy.net/feature-flags.

docs(a-b-testing): Update unleash docs to mention at tools.artsy.net

---

docs/unleash_a-b_testing.md

Oops opened a pr from a pr! This merges the `Update unleash A/B test docs` PR into main

docs(unleash): Update a/b testing docs to mention tools.artsy.net/feature-flags 

---

src/Components/Notifications/NotificationsListScrollSentinel.tsx

a quick solution that fixes the infinity pagination problem for the activity panel dropdown menu

fix: infinite pagination for activity panel dropdown menu

---

src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx

The type of this PR is: **Style**
This PR solves [CX-2917] [CX-2861] 
| Web Edit | Web Upload | mWeb Edit | mWeb Upload |
| --- | --- | --- | --- |
| <img width="1742" alt="image" src="https://user-images.githubusercontent.com/36167539/189643660-602e339a-d32e-43bf-ad97-85232992cf08.png"> | <img width="1564" alt="image" src="https://user-images.githubusercontent.com/36167539/189644187-e5422912-1b73-449a-918c-722d59befc72.png"> | <img width="355" alt="image" src="https://user-images.githubusercontent.com/36167539/189643600-1e2a956c-a5b4-4fe7-a08d-6bf6307228b3.png"> | <img width="467" alt="image" src="https://user-images.githubusercontent.com/36167539/189644010-c71b73d0-4537-443a-aa5a-6d81018e7bf9.png">|
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNz …

Style: adjust title and buttons of the upload/edit form

---

src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx
src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx
src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx

This PR solves [CX-2905]
Change email consign@ to sell@ for the service message on SWA flow
[CX-2905]: https://artsyproduct.atlassian.net/browse/CX-2905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: change email consign@ to sell@

---

src/Components/Notifications/NotificationsList.tsx

https://user-images.githubusercontent.com/3513494/190414079-6e2ba32f-384f-4fdd-97ae-2b8967ea9fdb.mp4
https://user-images.githubusercontent.com/3513494/190414118-163282b1-9e1f-498b-b542-e02708a653ce.mp4

fix: pass empty types for all tab

---

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx

This PR solves [CX-2906]
[CX-2906]: https://artsyproduct.atlassian.net/browse/CX-2906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: swap fields order for mWeb, year and medium

---

hokusai/production.yml

This PR solves [PLATFORM-5471]
Missed this config in https://github.com/artsy/force/pull/10982

fix: for prod, add toleration for spot node taint

---

src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkValidation.ts

This PR solves [CX-2904]
[CX-2904]: https://artsyproduct.atlassian.net/browse/CX-2904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: change error message

---

src/Apps/Consign/Routes/SubmissionFlow/ThankYou/Components/DownloadApp.tsx
src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx
src/System/i18n/locales/en-US/translation.json

chore(copy):  navbar menu item "Download apps" -> "Download app"

---

src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx

Addresses [CX-2842]
Redirect to my collection page after editing an artwork.
[CX-2842]: https://artsyproduct.atlassian.net/browse/CX-2842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Redirect to my collection page after editing an artwork

---

src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx

Reverts artsy/force#11014
Related ticket [CX-2842](https://artsyproduct.atlassian.net/browse/CX-2842)
This change was actually meant to be for the app and not web...

Revert "fix: Redirect to my collection page after editing an artwork"

---

src/Apps/Artwork/Components/ArtworkSidebar/LotTimer.tsx
src/Apps/Artwork/Components/ArtworkSidebar/__tests__/LotTimer.jest.tsx
src/Apps/Auction/__tests__/AuctionApp.jest.tsx
src/Components/CascadingEndTimesBanner.tsx
src/Components/__tests__/CascadingEndTimesBanner.jest.tsx

This PR solves [NX-3299]
Just a simple copy change from "last minute", to "last-minute".
[NX-3299]: https://artsyproduct.atlassian.net/browse/NX-3299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Hyphenate 'last-minute'

---

src/Apps/Settings/Routes/Insights/Components/InsightsLandingPage.tsx
src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
src/__generated__/InsightsRoute_me.graphql.ts
src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts

This PR solves [CX-2882]
This PR adds the landing page to the Insights tab
| Mobile | Tablet | Desktop |
|--|--|--|
| ![image](https://user-images.githubusercontent.com/20655703/192344793-96db40e1-800b-4919-8956-02d9bc0b28c8.png) | ![image](https://user-images.githubusercontent.com/20655703/192344837-0874ce18-cba9-4f19-988f-abcb3761f879.png) | ![image](https://user-images.githubusercontent.com/20655703/192344855-e4edf3c3-c80a-46fe-8f13-48f24b3d76a4.png) | 
[CX-2882]: https://artsyproduct.atlassian.net/browse/CX-2882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

feat(CX-2882): add Insights landing page

---

src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx

This PR solves [DO-475]
Added Bohnams to PriceDB filters
[DO-475]: https://artsyproduct.atlassian.net/browse/DO-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add bonhams to PriceDB filters

---

src/Components/NavBar/Menus/NavBarNewNotifications.tsx
src/Components/Notifications/NotificationsTabs.tsx

Review app: [decrease-dropdown-height](https://decrease-dropdown-height.artsy.net/)
https://user-images.githubusercontent.com/3513494/192488855-276c3836-a2f2-4b32-9dcf-fadf2652d5f7.mp4
https://user-images.githubusercontent.com/3513494/192488887-961d493a-5876-4e2e-83ee-d29ac97ad2c4.mp4

chore: decrease max height for dropdown activity panel

---

src/Components/Footer/FooterDownloadAppBanner.tsx

This PR solves [GRO-1298]
This adds a new footer tag line to the image: 
[GRO-1298]: https://artsyproduct.atlassian.net/browse/GRO-1298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(footer): Add caption to footer

---

src/Components/Footer/FooterDownloadAppBanner.tsx

Looks like the copy was incorrect for the footer images! Updating.

chore(footer): update copy

---

src/Apps/Order/Components/OfferInput.tsx
src/Apps/Order/Components/PhoneNumberForm.tsx
src/Apps/Order/Components/RevealButton.tsx
src/Apps/Order/Components/StickyFooter.tsx
src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
src/Apps/Order/Components/__tests__/StickyFooter.jest.tsx

This PR solves [TX-685]
This PR identifies and refactors remaining class components in the OrderApp into functional components. 
[TX-685]: https://artsyproduct.atlassian.net/browse/TX-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(TX-685): Class components to FC in OrderApp

---

src/Apps/Jobs/Components/JobsFilter.tsx

Closes [GRO-1319](https://artsyproduct.atlassian.net/browse/GRO-1319)
Removes the lead gen location from the locations menu and pushes the department to the end of the page.

feat(jobs): special case handling of lead gen dept/location

---

src/Components/Notifications/NotificationsList.tsx

https://user-images.githubusercontent.com/3513494/192843015-94d43a08-408d-4d40-a7a1-8666415120a4.mp4

feat: add dynamic pagination mode for standalone activity screen

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx

This PR solves [CX-2982]
| --- | --- |
| <img width="449" alt="image" src="https://user-images.githubusercontent.com/36167539/193286467-9060d82e-55c6-45a2-b25b-4551e59fa748.png"> | <img width="448" alt="image" src="https://user-images.githubusercontent.com/36167539/193286386-f3bcafb2-2aa3-4e1c-b4b2-91d6f3f19af9.png"> |
[CX-2982]: https://artsyproduct.atlassian.net/browse/CX-2982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: adjust spasing, MyCollectionArtworkSWASectionMobileLayout component

---

src/Components/Notifications/__tests__/NotificationItem.jest.tsx
src/Components/Notifications/__tests__/util.jest.ts
src/Components/Notifications/util.ts

* Add "Yesterday" label
* Sync changes with Eigen

chore: update date labels for activities

---

.eslintrc.js
.vscode/settings.json

Update eslint & .vscode configs.

chore(tooling): add configs for eslint-plugin-no-relative-paths

---

src/Apps/Artist/Components/ArtistInsights/ArtistInsightBadges.tsx
src/Apps/Artist/Components/ArtistInsights/ArtistInsightPills.tsx
src/Apps/Artist/Components/ArtistInsights/__tests__/ArtistInsightBadges.jest.tsx
src/Apps/Artist/Components/ArtistInsights/__tests__/ArtistInsightPills.jest.tsx
src/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlights.tsx
src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistCareerHighlights.jest.tsx
src/__generated__/ArtistApp_Test_Query.graphql.ts
src/__generated__/ArtistCareerHighlightsQuery.graphql.ts
src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts
src/__generated__/ArtistCareerHighlights_artist.graphql.ts
src/__generated__/ArtistHeader_Test_Query.graphql.ts
src/__generated__/ArtistInsightBadges_Test_Query.graphql.ts
src/__generated__/ArtistInsightBadges_artist.graphql.ts
src/__generated__/ArtistInsightPills_Test_Query.graphql.ts
src/__generated__/ArtistInsightPills_artist.graphql.ts
src/__generated__/artistRoutes_TopLevelQuery.graphql.ts

And finally we arrive at the punchline of this work - BEHOLD:
<details>
<summary>some screenshots</summary>
</details>
What I did here was go to the `kind` arrays and add the new ones and then it was a matter of deleting stuff we no longer needed. Feels good to delete a TODO I am just saying. 💃 
https://artsyproduct.atlassian.net/browse/GRO-841
https://artsyproduct.atlassian.net/browse/GRO-916

feat: Add critically acclaimed and vanguard artist insights GRO-841

---

src/Components/BankDebitForm/BankDebitProvider.tsx

This PR solves [TX-654]
This PR Updates legal text styles for Stripe payment element.
Before
Now
[TX-654]: https://artsyproduct.atlassian.net/browse/TX-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update stripe legal text styles

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworRequestPriceEstimateSection.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASection.tsx
src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx

This PR solves [CX-2736, CX-2783]
| Web | Web sent | mWeb | mWeb sent |
| --- | --- | --- | --- |
| <img width="705" alt="image" src="https://user-images.githubusercontent.com/36167539/193986938-98e38071-e709-4c00-bd75-d8696371e7cf.png"> | <img width="560" alt="image" src="https://user-images.githubusercontent.com/36167539/193988976-ac9e7668-c872-4948-9577-3ce84edb1706.png"> |  <img width="609" alt="image" src="https://user-images.githubusercontent.com/36167539/193989008-8b65a678-8eb2-4dcd-b936-3324c4c570c5.png"> | <img width="614" alt="image" src="https://user-images.githubusercontent.com/36167539/193989040-3eb19832-55bb-41b1-b1cc-0bfcf08ae92e.png"> |
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

feat: create request price estimate block cta UI only

---

src/Apps/Order/Routes/__tests__/Shipping.jest.tsx

Some tests after Relay upgrade became broken because the `commitMutation` wasn't mocked in all children/different components related to Shipping route.
This PR basic changes these broken tests instead of observing the `commitMutation` to observe if the `updateUserAddress` and `deleteUserAddress` are called with the expected params.

fix: broken shipping tests 

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionInfoPolling.tsx
src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2AuctionTimer.tsx
src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2BiddingClosedMessage.tsx
src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CommercialButtons.tsx
src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2CommercialButtons.jest.tsx
src/Apps/Order/Routes/Payment/PaymentContent.tsx
src/Apps/Order/Routes/Payment/index.tsx
src/Apps/Settings/Routes/Auctions/SettingsAuctionsRoute.tsx
src/Apps/Settings/Routes/EditProfile/SettingsEditProfileRoute.tsx
src/Apps/Settings/Routes/EditSettings/SettingsEditSettingsRoute.tsx

remove @ts-ignore RELAY UPGRADE 13 leftovers

refactor: remove @ts-ignore RELAY UPGRADE 13 leftovers

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkInsights.tsx

This PR solves [CX-2736]
Added missing Media tag to avoid displaying the section twice
[CX-2736]: https://artsyproduct.atlassian.net/browse/CX-2736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add missing media tag

---

src/Apps/Order/Routes/Shipping/index.tsx

This PR solves [TX-765]
This PR updates the shipping page to use the actual address list to fix saving a new shipping address if the last saved address was removed.
Before
https://user-images.githubusercontent.com/79979820/193578972-ca5c468f-eca4-4fcf-8796-2df2a7b5e0e0.mp4
Now
https://user-images.githubusercontent.com/79979820/193578988-4bca263b-faa6-4032-8bd3-5c265b1a08e7.mp4
[TX-765]: https://artsyproduct.atlassian.net/browse/TX-765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: cannot save a new shipping address if last saved address removed on shipping page

---

.secrets.baseline
src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx

This PR solves [FX-4316]
move separator to be above estimated value
|before|after|
|---|---|
|<img width="1280" alt="Screenshot 2022-10-05 at 18 27 47" src="https://user-images.githubusercontent.com/21178754/194112544-5065de97-7adb-4ddc-87ff-1312eb6b6709.png">|<img width="1281" alt="Screenshot 2022-10-05 at 18 21 39" src="https://user-images.githubusercontent.com/21178754/194112381-6f6256da-ca97-4058-8d3f-fa28f7418f33.png">|
|<img width="1281" alt="Screenshot 2022-10-05 at 18 28 44" src="https://user-images.githubusercontent.com/21178754/194112770-ab4dc7cf-118e-47c9-a29f-63eea75edffa.png">|<img width="1281" alt="Screenshot 2022-10-05 at 18 21 26" src="https://user-images.githubusercontent.com/21178754/194112407-7f3c2b25-4df6-4fd6-8097-969f7c80c9c8.png">| …

fix: separator fix in auctions

---

.secrets.baseline

chore: updates version of detect secrets

---

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
src/Apps/Partner/Components/PartnerArtists/PartnerArtistDetails/PartnerArtistDetailsPlaceholder.tsx
src/Components/Artwork/Details.tsx

This PR solves [FX-4321]
Changed in gravity the string `Contact For Price` to be `Contact for price`, and as a result, we should also change the checks that we had in place.
this is the related gravity pr.
https://github.com/artsy/gravity/pull/15726
[FX-4321]: https://artsyproduct.atlassian.net/browse/FX-4321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(FX-4321): change Contact For Price checks

---

src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
src/Apps/MyCollection/Routes/PriceEstimate/__tests__/PriceEstimateContactInformation.jest.tsx

Addresses [CX-2781]
[Slack thread with more context](https://artsy.slack.com/archives/C01B2P6LJUU/p1665503904238489?thread_ts=1665475292.748669&cid=C01B2P6LJUU)
Update Price Estimate contact information page copy.
[CX-2781]: https://artsyproduct.atlassian.net/browse/CX-2781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update Price Estimate page copy

---

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CommercialButtons.tsx

This PR solves [FX-4314]
Adds missing test ids for cypress tests
[FX-4314]: https://artsyproduct.atlassian.net/browse/FX-4314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add test ids for cypress

---

src/Apps/MyCollection/Routes/EditArtwork/Utils/rarityOptions.ts

Add "Select a classification" placeholder to the My Collection form rarity options.

fix: Add placeholder to My Collection form rarity options

---

src/Apps/ArtQuiz/ArtQuizWelcome.tsx
src/System/i18n/locales/en-US/translation.json

This PR solves [GRO-1317]
Adds useTranslation and t function to Welcome Screen and copy text to translation.json file. 
[GRO-1317]: https://artsyproduct.atlassian.net/browse/GRO-1317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(art taste quiz): Add INTL to Welcome Screen

---

src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/ContactInformationForm.tsx
src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/Components/PhoneNumberInput.tsx
src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx
src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
src/Apps/MyCollection/Routes/PriceEstimate/Utils/validation.ts
src/Apps/MyCollection/Routes/PriceEstimate/__tests__/PriceEstimateContactInformation.jest.tsx

Make phone number optional in Price Estimate flow.

fix: Make phone number optional in Price Estimate flow

---

src/Apps/Auction/Components/Form/AddressFormWithCreditCard.tsx

This PR solves [TX-764] by updating the copy above the credit card form:
[TX-764]: https://artsyproduct.atlassian.net/browse/TX-764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update auction registration credit card note

---

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx

Context: [slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1666081573326719)

fix: change artsy guarantee logic to be either of isOfferable/isOfferableFromInquiry

---

src/Apps/Settings/Routes/Insights/InsightsRoute.tsx

This PR updates the insights page structure regarding the feature flags

fix: Update Insights page

---

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ArtworkTitle.tsx

After releasing sidebar2 smoke tests started failing, @MrSltun reported it and this pr fixes this issue (will also unblock failing deploy)

fix: add as-h1 to make smoke tests pass

---

src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateConfirmation.jest.tsx
src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateConfirmation.tsx

This PR solves [CX-2782]
| --- | --- |
| <img width="984" alt="image" src="https://user-images.githubusercontent.com/36167539/196427401-28de9b24-a648-45b0-8c73-3966ad51746f.png"> | <img width="817" alt="image" src="https://user-images.githubusercontent.com/36167539/196427317-ebebef16-4a27-445d-bee5-099135ba1ee0.png"> |
[CX-2782]: https://artsyproduct.atlassian.net/browse/CX-2782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove back button

---

src/Apps/Gene/Utils/geneToCollectionMap.ts

Following up on https://github.com/artsy/force/pull/10970, one redirect was wrong!

fix: correct redirect for collection

---

src/Apps/Settings/Routes/Insights/InsightsRoute.tsx

This PR adds My Collection Insights meta title to be displayed in the browser

feat: Add MyC Insights meta title

---

src/Components/NavBar/NavBarLoggedInActions.tsx
src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx
src/Components/Notifications/NotificationItem.tsx
src/Components/Notifications/NotificationsTabs.tsx
src/__generated__/NavBarLoggedInActionsQuery.graphql.ts

This PR solves [FX-4381]
Tracking for Activity Panel
[FX-4381]: https://artsyproduct.atlassian.net/browse/FX-4381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(FX-4381): Activity Panel tracking

---

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CommercialButtons.tsx

🍼 👶 Small refactor that removes sidebar inlined render functions from `ArtworkSidebar2CommercialButtons.tsx` and also removes stray commented out console.log #:1st_place_medal: 

refactor: remove sidebar inlined render functions

---

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Details.tsx

bug was reported [here](https://artsy.slack.com/archives/C9SATFLUU/p1666278653343459) incorrect lineheight according to [designs](https://www.figma.com/file/9DMfKOi5RuuBD2f49eB9nV/Artwork-page?node-id=1820%3A38846)

fix: fixed variant in artwork details

---

src/Components/Notifications/NotificationItem.tsx
src/Components/Notifications/__tests__/NotificationItem.jest.tsx
src/Components/Notifications/__tests__/util.jest.ts
src/Components/Notifications/util.ts
src/__generated__/NotificationItem_item.graphql.ts
src/__generated__/NotificationItem_test_Query.graphql.ts
src/__generated__/NotificationsListNextQuery.graphql.ts
src/__generated__/NotificationsListQuery.graphql.ts
src/__generated__/NotificationsList_test_Query.graphql.ts

Related Metaphysics Jira ticket: [FX-4313]
Related Metaphysics PR: artsy/metaphysics#4452
Review app: https://formatted-notification-date.artsy.net/
https://user-images.githubusercontent.com/3513494/196991607-1a4b568e-323c-4a6d-afa5-aaa1a74f1869.mp4
[FX-4313]: https://artsyproduct.atlassian.net/browse/FX-4313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: query formatted notification date from Metaphysics

---

src/Apps/Order/Components/SavingPaymentSpinner.tsx

This PR solves [TX-665]
Adds spacing to saving payment spinner 
[TX-665]: https://artsyproduct.atlassian.net/browse/TX-665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TX-665): add spacing to saving payment spinner

---

src/Components/Onboarding/Components/OnboardingFollows.tsx
src/System/i18n/locales/en-US/translation.json

Closes [GRO-1325](https://artsyproduct.atlassian.net/browse/GRO-1325)

feat(GRO-1325): additional follow description copy

---

src/Apps/Feature/Components/FeatureFeaturedLink.tsx
src/Apps/Feature/Components/FeatureHeader/FeatureHeaderDefault.tsx
src/Apps/Feature/Components/FeatureHeader/FeatureHeaderFull.tsx
src/Apps/Feature/Components/FeatureMeta.tsx
src/Apps/Feature/Components/FeatureSet/FeatureSet.tsx
src/Apps/Feature/Components/FeatureSet/FeatureSetContainer.tsx
src/Apps/Feature/Components/FeatureSet/FeatureSetItem.tsx
src/Apps/Feature/Components/FeatureSet/FeatureSetMeta.tsx
src/Apps/Feature/FeatureApp.tsx
src/__generated__/FeatureApp_Test_Query.graphql.ts
src/__generated__/FeatureHeaderDefault_feature.graphql.ts
src/__generated__/FeatureHeaderFull_feature.graphql.ts
src/__generated__/featureRoutes_FeatureQuery.graphql.ts

Closes [GRO-1361](https://artsyproduct.atlassian.net/browse/GRO-1361)
Fixes the padding but also just overhauls the spacing and general layout to better reflect the current state of layouts throughout the site.

fix(GRO-1361): feature layout updates

---

src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx

Review app: [register-to-bid-improvements](https://register-to-bid-improvements.artsy.net/)
Small improvements after [internal QA](https://artsy.slack.com/archives/C9SATFLUU/p1666785127449729?thread_ts=1666710678.447889&cid=C9SATFLUU)

chore: register to bid popover improvements

---

src/Utils/Hooks/useImagePerformanceObserver.ts

Closes [GRO-1388](https://artsyproduct.atlassian.net/browse/GRO-1388)
Bit of an obscure one. This is a very rarely used version of Safari according to Google Analytics and other versions work fine.
https://bugs.webkit.org/show_bug.cgi?id=209216
Simply wraps init in a try/catch — We'll just ignore this version.

fix: wraps performance observer initialization in a try/catch

---

src/Apps/Order/Routes/Payment/index.tsx
src/Utils/__tests__/logger.jest.ts

This PR solves [TX-853]
This PR adds a simple test suite for logging extended error objects to Sentry. 
[TX-853]: https://artsyproduct.atlassian.net/browse/TX-853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(TX-853): testing logger

---

src/Apps/Order/Routes/Payment/index.tsx

A simple fix introduced in a previous PR that hasn't been deployed yet.

fix: error type

---

src/Apps/NewForYou/newForYouRoutes.tsx

After some surprising results and some scratching of heads, we have decided to double the number of artwork recs on the new for you page.
Investigation here:
https://www.notion.so/artsy/Investigate-artwork-rec-differences-eb461849f7d149518497a0ba98c491c5
Chatter here:
https://artsy.slack.com/archives/C033E79AQG4/p1667232723970619
https://artsyproduct.atlassian.net/browse/GRO-1386
/cc @artsy/grow-devs @isakelaris

feat: Double new for you recs GRO-1386

---

src/Components/NavBar/NavBar.tsx
src/Components/NavBar/NavBarItem.tsx

Fixes [GRO-1405](https://artsyproduct.atlassian.net/browse/GRO-1405)

fix(navbar): prevents viewing room from breaking at md breakpoint

---

src/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx
src/Apps/Artwork/Components/ArtworkLightbox.tsx
src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorksArtwork.tsx

This just pre-empts some changes here: https://github.com/artsy/metaphysics/pull/4492

fix(image): use || for geometry fallback values

---

src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowserLarge.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowserSmall.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowserLarge.jest.tsx
src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowserSmall.jest.tsx

Just some renaming for clarity.

refactor(artwork): improves naming

---

package.json
src/Components/ArticleShare.tsx
src/Components/Footer/Footer.tsx
yarn.lock

Close: [GRO-1148](https://artsyproduct.atlassian.net/browse/GRO-1148)
Long time coming. Thank you deeply @damassi for getting the Icons repo publishing correctly.
----
I'm going to ticket replace/delete of the old icons.

feat(GRO-1148): updated social icons

---

src/Apps/Conversation/Components/OrderModal.tsx
src/Apps/Order/Components/AddressModal.tsx
src/Apps/Order/Components/__tests__/AddressModal.jest.tsx

This PR solves [TX-836]
This PR updates deprecated components in Order App
1. AddressModal `Modal` --> `ModalDialog`
2. Order Modal `Modal` --> `ModalDialog`
3. AddressModal Delete Dialog `Dialog` --> `ModalDialog`
[TX-836]: https://artsyproduct.atlassian.net/browse/TX-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(TX-836): update deprecated components in order app 

---

src/Apps/Order/Routes/Shipping/index.tsx
src/Apps/Order/Utils/getStatusCopy.tsx

This PR solves [TX-863] and [TX-865]
This PR updates the CTA copy for the shipping page and removes the Covid message from the status page. 
[TX-863]: https://artsyproduct.atlassian.net/browse/TX-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TX-865]: https://artsyproduct.atlassian.net/browse/TX-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update CTA copy and remove Covid message 

---

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkDemandIndex/HighDemandIcon.tsx
src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
src/Components/Artwork/Details.tsx

Addresses [CX-3077]
Decrease MyC artwork high demand icon size.
| --- | --- |
|<img width="481" alt="Screenshot 2022-11-08 at 11 55 34" src="https://user-images.githubusercontent.com/4691889/200546630-8c7f2edd-47f6-440e-920e-3bf51075e5fc.png"> |<img width="481" alt="Screenshot 2022-11-08 at 11 52 17" src="https://user-images.githubusercontent.com/4691889/200546735-aa19e246-f73d-49c5-bb22-41bce33ca6d9.png"> |
[CX-3077]: https://artsyproduct.atlassian.net/browse/CX-3077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Decrease MyC artwork high demand icon size

---

src/Apps/Order/Components/SavedAddressItem.tsx

This is a fix to my [previous PR](https://github.com/artsy/force/pull/11306) as the Clickable component was causing unexpected behavior during QA. This is an alternative approach. 

fix: edit button accessibility 

---

src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx

Addresses [CX-2981]
Remove My Collection screen top banner.
[CX-2981]: https://artsyproduct.atlassian.net/browse/CX-2981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Remove My Collection screen top banner

---

src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx

This PR fixes a copy issue at the request price estimate screen.

fix: request price estimate CTA copy
