artsy/force

.circleci/config.yml
Action item from incident review (#141). Notify engineering when a force deploy fails.
Looking at #practice-web channel, I do not see any post-steps logging, only the slack notifications from the [validate_production_schema](https://github.com/artsy/force/blob/main/.circleci/config.yml#L33). I wonder if using channel IDs would help as the configuration seems correct to me.
The slack app _should_ be able to send notifications to #dev as it is authorized to do so:
=> notify #dev on failed prod deploys

src/v2/Apps/Home/Components/HomeTroveArtworksRail.tsx
This PR solves [GRO-834]
The `View All Artworks` tab was missing from the Trove Rail. It now links to `/gene/trove` collection page. 
[GRO-834]: https://artsyproduct.atlassian.net/browse/GRO-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (Fix): add view all artworks CTA to trove rail

src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
This PR solves [CX-2409]
Updated copy on SWA confirmation page to mention that submission is in MyC
When FF "swa_my_collection" is disabled   | When FF "swa_my_collection" is enabled
------------- | -------------
Updated copy on SWA confirmation page to mention that submission is in MyC -daria
[CX-2408]: https://artsyproduct.atlassian.net/browse/CX-2408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CX-2409]: https://artsyproduct.atlassian.net/browse/CX-2409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-2409): When the user has the SWA<>MYCollection feature enabled - show updated copy

src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
This PR solves [CX-2450]
Added check isLoggedIn to the implementation
[CX-2450]: https://artsyproduct.atlassian.net/browse/CX-2450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-2450): check if the user is logged in or not when showing updated copy after artwork submission | Force

src/v2/Apps/FairOrginizer/Components/FairOrganizerHeader/FairOrganizerHeader.tsx, src/v2/Components/Timer.tsx, src/v2/Components/__tests__/Timer.jest.tsx, src/v2/Utils/Hooks/useTimer.tsx
When working on the lot page timer, I forgot to conditionally show the time until the sale ends vs. the time until the sale starts based on whether or not the sale has started. This PR fixes that.
https://artsyproduct.atlassian.net/browse/BID-272
**Uses of `useTimer` and `<Timer/>**
_Fair Timer_
Currently live fair:
Past fair:
Upcoming fair:
_Lot Timer:_
Sale start date is in the future:
Before (date corresponding with end of sale):
After (date corresponding with beginning of sale):
_Auction Timer:_
In progress live sale:
Upcoming live sale:
Upcoming OO sale:
=> fix: Fix timer showing time to end when sale has not yet started

src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
Add horizontal offsets (`12px`) for histogram
=> chore: add horizontal offsets for histogram

src/v2/Apps/Conversation/Components/Conversation.tsx, src/v2/Apps/Conversation/Components/__tests__/Conversation.jest.tsx, src/v2/__generated__/ConversationPageQuery.graphql.ts, src/v2/__generated__/ConversationPaginationQuery.graphql.ts, src/v2/__generated__/ConversationPagination_Test_Query.graphql.ts, src/v2/__generated__/Conversation_conversation.graphql.ts, src/v2/__generated__/conversationRoutes_DetailQuery.graphql.ts
This PR solves [NX-3114]
The type of this PR is: Bugfix.
Since we moved all offers to go through conversations, we switched the check for the counteroffer modal from `isOfferableFromInquiry` to `isOfferable`.
Co-authored-by: Carlos Barreto <araujobarret@gmail.com>
Co-authored-by: Lidiane Taquehara <lidiane.taquehara@artsymail.com>
[NX-3114]: https://artsyproduct.atlassian.net/browse/NX-3114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Switched isOfferableFromInquiry check to isOfferable

.circleci/config.yml, .secrets.baseline, package.json, scripts/detect-secrets.sh
Following a [recent issue](https://artsy.slack.com/archives/CP9P4KR35/p1647897472182919) when `.secrets.baseline` became out of sync, (_as requested_) this adds yarn support to rebuild the _baseline_ when is necessary.
Modified the existing script to include functions and updated the calling code, references to use the new form.
=> enh: add rebuild to detect-secrets

src/v2/Apps/Order/Components/MinPriceWarning.tsx, src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
This PR solves [NX-3111]
Changes the copies from the low amount warning in the Offer. Slightly adjust the design removing underline decoration and not breaking the line anymore/
Price
Price Range
[NX-3111]: https://artsyproduct.atlassian.net/browse/NX-3111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: change copies from input field in Offer

src/v2/Apps/Order/Components/PriceOptions.tsx, src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
This PR solves [NX-3110](https://artsyproduct.atlassian.net/browse/NX-3110)
Reversed order for options with range price, from high to low price.
=> feat(NOSF2): reverse order of options for range price

src/lib/middleware/featureFlagMiddleware.ts
If you don't have Unleash set up locally or if there's an error, anything using a feature flag is going to error:
=> fix(featureflags): return empty object regardless when setting up feature flags

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionTimer.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/index.tsx, src/v2/Apps/Artwork/Utils/lotIsClosed.ts, src/v2/__generated__/ArtworkSidebarAuctionTimer_artwork.graphql.ts, src/v2/__generated__/ArtworkSidebar_Test_Query.graphql.ts, src/v2/__generated__/ArtworkSidebar_artwork.graphql.ts, src/v2/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
This uses the same `useTimer` hook to detect when the lot has ended (if we have the lot end time details), and immediately hides/updates the sidebar components as needed.
=> feat: when a lot is closed, suppress bidding UI immediately

src/v2/Apps/Auction/Components/Form/ErrorStatus.tsx, src/v2/Apps/Auction/Components/Form/Utils/errorMessages.ts, src/v2/Apps/Auction/Components/Form/__tests__/ErrorStatus.jest.tsx
Do not merge until [MP work](https://github.com/artsy/metaphysics/pull/3893) is merged.
[BID-257](https://artsyproduct.atlassian.net/browse/BID-257)
Show a different error to handle cascading end times when the lot is closed but the sale is still open.
Screenshot:
=> feat: Handle error case for bid when the bid was placed when a lot is closed but sale is still open

src/v2/Apps/Order/Components/MinPriceWarning.tsx, src/v2/Apps/Order/Components/PriceOptions.tsx, src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
This PR solves [NX-3112]
Removes clickable from low offer warning text
Going to inform the data team we don't have anymore the event "We recommend changing your offer" being dispatched
[NX-3112]: https://artsyproduct.atlassian.net/browse/NX-3112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: remove clickable from low offer notice text

src/v2/Apps/Order/Components/PriceOptions.tsx, src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx, src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx
This PR solves: [NX-3109](https://artsyproduct.atlassian.net/browse/NX-3109)
Reversed order of price options for exact price. First option is now replaced with the exact price.
=> feat(NOSF2): change order of options starting with the exact price

src/v2/Components/Artwork/FlatGridItem.tsx
Per discussion, this bottom aligns our artwork grid on Auctions page to better support legibility as well as cascading end times.
=> chore(auctions): Make grid bottom aligned

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx, src/v2/Apps/Settings/Routes/SavedSearchAlerts/__tests__/SavedSearchAlertsApp.jest.tsx, src/v2/__generated__/SavedSearchAlertListItem_item.graphql.ts, src/v2/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts, src/v2/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts, src/v2/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
as part of [the task](https://github.com/artsy/metaphysics/pull/3880), it is necessary to temporarily disable the display of filter criteria to avoid incorrect behavior (the raw value will be displayed, not human-readable for pills)
=> chore: temporarily disabling filter criteria

src/v2/Apps/Order/Components/MinPriceWarning.tsx, src/v2/Apps/Order/Components/PriceOptions.tsx, src/v2/Apps/Order/Components/__tests__/PriceOptions.jest.tsx
This PR solves: [NX-3116](https://artsyproduct.atlassian.net/browse/NX-3116)
Copy changes for Exact price and Warning message.
Exact price is now changed to: List price
Added margin top for Warning message.
=> fix(NOSF2): updated copy for exact price and warning message

src/v2/Components/ArtworkGrid/ArtworkGrid.tsx
Some interaction between `white-space: nowrap` and CSS grid: https://bugzilla.mozilla.org/show_bug.cgi?id=1528030
=> fix(auction): prevents overflowing text from breaking out of column in Firefox

src/v2/Apps/ArtistSeries/artistSeriesRoutes.tsx
This PR solves [FX-3835]
This PR adds the price histogram on to the artist series page. This is controlled by the `new_price_filter` unleash feature toggle which can be found [here](https://unleash.artsy.net/projects/default/features2/new_price_filter)
This is how it looks on my local machine
[FX-3835]: https://artsyproduct.atlassian.net/browse/FX-3835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: added price histogram to the artist series page

.circleci/config.yml
Specify slack channels in the `validate_production_schema` job instead of _post-steps_ to deliver notifications to both channels.
In my [testing](https://github.com/artsy/force/commit/5fa8cd717dd8e9e9d04215c635429d5002f13377), the post-step would not trigger a slack/notify if one of the required jobs fails and sends a slack notification.
=> slack notify dev when validate_production_schema fails

.circleci/config.yml
We're already using the [slack/notify orb](https://github.com/CircleCI-Public/slack-orb) which supports custom templates written for Slack's [Block Kit](https://api.slack.com/block-kit) UI framework.
This commit takes further advantage of the framework to format links and break up the notification content into a few sections.
You can view an example notification in Slack's Block Kit Builder [here][example].
[example]: https://app.slack.com/block-kit-builder/T02531TU5#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22:warning:%20*Deployment%20Failed*%20:warning:%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Hey%20there!%20:wave:%22%7D%7D,%7B%22type%22:%22sectio …
=> ci: spruce up "Validate Production Schema" CI job failure Slack notification

src/v2/Components/Artwork/ArtworkImage.tsx, src/v2/Components/Artwork/GridItem.tsx, src/v2/Components/MagnifyImage.tsx
This PR solves [FX-3849]
Slack thread with discussion: [Link](https://artsy.slack.com/archives/C9SATFLUU/p1648554470666829)
Review app: [Link](https://zoom-scroll-when-hovering.artsy.net/artist/banksy/works-for-sale)
As a collector, I’d like to zoom in into the primary image so I can see more detail.
* Given I am on the artwork grid
* And I am hovering on an artwork grid item
* And the artwork does not have an alternate image available
* Then I should see a zoomed in view of the image
* Alternative metadata is displayed when hovering only for `GridItem` component
* Changes are hidden under [Unleash flag](https://unleash.artsy.net/projects/default/features2/force-enable-hover-effect-for-artwork-item) and will be available only for staging environment …
=> feat: zoom in on image when hovering on artwork grid item

src/v2/Components/ArtworkFilter/ArtworkFilters/index.tsx, src/v2/System/__tests__/useFeatureFlag.jest.tsx, src/v2/System/useFeatureFlag.tsx
This PR solves [PLATFORM-4059]
This PR aims to make s number of improvements to the `useFeatureVariant` function and address tracking-related issues [discovered while QA'ing the first implementation](https://github.com/artsy/force/pull/9679). 
1. Reduce `useFeatureVariant`'s parameters to `experimentName`,  `variantName`,  and `payload` (optional). Analytics data no longer is being passed in and is handled within the function itself using  `useRouter` to get the pathname and parse out the `PageType` and `PageSlug`. 
2. Return out a callback, `trackVariantView` instead of passing in a `boolean` to the `shouldTrackExperiment`, enabling developers to conditionally make a tracking call in the component being tested.
3. Improved test coverage
Done with …
=> refactor: useFeatureVariant

src/v2/Apps/Conversation/Components/CollapsibleArtworkDetails.tsx, src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx, src/v2/Apps/Conversation/Components/EditionSelectBox.tsx, src/v2/Apps/Conversation/Components/__tests__/ConfirmArtwork.jest.tsx
This PR solves [NX-3052]
Remove some texts, fix elements alignment, upgrade deprecated Palette components, update tests to wait for DialogModal to open.
Before:
After:
[NX-3052]: https://artsyproduct.atlassian.net/browse/NX-3052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(NX-3052): Modify the UI of the edition selection modal

src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
This PR solves [PLATFORM-3979]
Due to Authy being no longer [actively developed](https://www.twilio.com/docs/verify/authy-vs-verify) we would prefer to recommend Google Authenticator to collectors instead.
~~Currently, this also removes a hyperlink as there doesn't appear to be a "nice" hyperlink for Google Authenticator for all users. There are links, but they are to the Apple or Google play stores, which doesn't cover all users.~~
A [hyperlink](https://support.google.com/accounts/answer/1066447?hl=en&co=GENIE.Platform%3DAndroid&oco=0) has been added to help collectors know exactly where to download Google Authenticator for both Android and iOS.
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
=> fix: remove Authy reference in favour of Google Authenticator

src/v2/Apps/Jobs/JobsApp.tsx, src/v2/Apps/Jobs/jobsRoutes.tsx, src/v2/Apps/Page/pageRoutes.tsx, src/v2/Components/Cells/CellArticle.tsx, src/v2/__generated__/JobsApp_viewer.graphql.ts, src/v2/__generated__/jobsRoutes_JobsQuery.graphql.ts, src/v2/routes.tsx
This PR (potentially) solves [GRO-943]
This just sets up a new jobs page under /jobs2. We should run this by the relevant stakeholders since we're dropping the grouping. We _could_ also display this as a flat list with descriptions etc like it is currently. Here I'm just using the article cell components since they are articles and it was quick/easy/consistent.
[GRO-943]: https://artsyproduct.atlassian.net/browse/GRO-943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(GRO-943): /jobs2

src/v2/Apps/Auction/Routes/Bid/AuctionBidRoute.tsx, src/v2/Apps/Auction/Routes/Bid/__tests__/AuctionBidRoute.jest.tsx
This PR solves [BID-292]
The following scenario was observed:
- user is not registered for an auction, and enters the bid flow
- they are asked to register ('agree to conditions of sale', placing the bid will create the bidder)
- they are asked to input a CC always, even if they already had one on file
The desired behavior:
- if a CC is on file, the registration inlined during bidding should just be the conditions of sale checkbox
- if there is no CC on file, preserve current behavior (CC form)
After taking a careful look, it seems like a logic bug with `&&` vs `||`.
With these changes, here's how it now looks if you are not registered to bid, but have a CC on file:
[BID-292]: https://artsyproduct.atlassian.net/browse/BID-292?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> fix: dont reask for credit card info during bidding

src/v2/Apps/Authentication/Server/checkForRedirect.ts, src/v2/Components/Authentication/FormSwitcher.tsx
This PR solves [PLATFORM-4011]
This closes a potentially malicious loophole where an Artsy URL could be used to redirect a collector off the website as the untrusted input for the `redirect-to` param was not sanitised.
OWASP [suggests](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html) a number of ways to deal with this issue, however it appears that we already have this code [implemented in Artsy](https://github.com/artsy/force/blob/a5702128800ff5dfd4b2f2ea55708a98ef27d2ab/src/lib/passport/lib/app/sanitize_redirect.js#L29), but we were not using it in this instance. In addition to this, we also have a great test suite setup, even including a URL which [does not contain a …
=> fix: sanitising untrusted redirect url

src/v2/Apps/Auctions/Components/TrendingLotsRail.tsx, src/v2/Apps/Auctions/Components/__tests__/TrendingLotsRail.jest.tsx, src/v2/__generated__/AuctionsApp_Test_Query.graphql.ts, src/v2/__generated__/TrendingLotsRail_Test_Query.graphql.ts, src/v2/__generated__/TrendingLotsRail_viewer.graphql.ts, src/v2/__generated__/auctionsRoutes_AuctionsQuery.graphql.ts
I expect this PR will fail on CI because I can't get one of the jest specs to behave. I did a quick call with @dzucconi and it was not clear to us what was happening so I'm going to assign you @damassi and maybe you can see something we did not?
Either way the actual point of this PR is to remove closed lots from this rail:
I assumed there was some problem with the way we were making the query to MP and ultimately Gravity but after some chatting with @mzikherman I think this is actually something else, likely a missed indexing opportunity when a sale closes. More chatter here:
https://artsy.slack.com/archives/C01ADJNCS5D/p1649262707508329
It's worth noting his advice towards the end of that thread:
> in general tho, i think its known and accepted that you may see elasticsearch staleness, …
=> fix: Suppress lots that are closed from trending rail GRO-891

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx
Jira ticket: [FX-3880]
* “Your Alerts” header should have `lg` variant
* “Your Alerts” should match the rest of the headers on settings page
[FX-3880]: https://artsyproduct.atlassian.net/browse/FX-3880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update title size for "Your Alerts" page

.circleci/config.yml
This PR reverts the renovate bump of cypress's docker base image from `16.4.0` to `16.4.2`. This appears to be causing `smoke-test-on-live-env` to failed with a `error Couldn't find the binary git`. Failure in CI [here](https://app.circleci.com/pipelines/github/artsy/force/29307/workflows/9ac6ed93-196c-4851-bb86-f41ba2e22699/jobs/228659?invite=true#step-102-56).
Slack discussion [here](https://artsy.slack.com/archives/CA8SANW3W/p1649428139745399).
This PR aims to get CI green again while we look into the other related issues: the root cause of the error, and why Horizon merged the PR with failing checks.
=> fix: drop cypress base image to last working version

src/v2/Components/ArtworkFilter/ArtworkFilters/PriceRangeFilterNew.tsx
This PR solves [FX-3882]
Review app [link](https://update-offsets-for-price-filter.artsy.net/artist/banksy/works-for-sale)
* Spacing between min and max boxes is `20px`
* Spacing between graph and max/min is `20px`
* Spacing between bar and graph is `20px`
* Spacing between slider and price points is `10px`
| Before        | After           |
| ------------- |:-------------:|
| <img width="472" alt="price-before" src="https://user-images.githubusercontent.com/3513494/162427340-1e95f0e7-fc73-4442-9c86-7b14ccd2ac2a.png"> | <img width="472" alt="price-after" src="https://user-images.githubusercontent.com/3513494/162427350-a3cb8fa3-4355-404d-9500-ed8a231c93ef.png"> |
[FX-3882]: https://artsyproduct.atlassian.net/browse/FX-3882?atlOrigin=eyJpIjoiNWRkNTljN …
=> chore(FX-3882): update offsets for updated price filter (with histogram)

src/v2/Components/Rail/RailHeader.tsx
The type of this PR is: feat
This PR solves [GRO-944]
Design noticed that the Home Trove Rail mweb cuts off the text at the ellipsis when viewing on mobile screens so I added this to all Rails for consistency.
[GRO-944]: https://artsyproduct.atlassian.net/browse/GRO-944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [GRO-944] universally remove subtitles from Rails at smaller screen widths

src/v2/Apps/Auction/auctionRoutes.tsx
Following the thread [here](https://artsy.slack.com/archives/C01ADJNCS5D/p1649788140435499) it turns out some old Eigen versions are relying on urls that no longer exist after the /auction/id rebuild. This restores those URLs:
- /auction-registration/<sale-slug>: redirects to /sale/id/register
- /auction-faq: promotes /auction-faq2 to /auction-faq
- /auction/<sale-slug>/buyers-premium: redirects to /auction-faq (since that page contains buyer premium information
=> fix(auction): Restore old urls for older versions of Eigen

package.json, yarn.lock
The type of this PR is: Security Update
This PR solves [PLATFORM-4079]
This PR bumps `mocha` to `6.2.3` the minimum bump that allows us to also bump the transitive dependency `minimist` to `1.2.6`: the earliest version with the patch. This resolves this dependabot [alert](https://github.com/artsy/force/security/dependabot/68). 
[PLATFORM-4079]: https://artsyproduct.atlassian.net/browse/PLATFORM-4079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump minimist

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
This PR solves [NX-3106]
It Fixes one issue given price on request, we were displaying shipping info when we don't want in this case.
Before
After
[NX-3106]: https://artsyproduct.atlassian.net/browse/NX-3106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: no shipping info when price on request

src/v2/Apps/Auction/Components/AuctionDetails/SaleDetailTimer.tsx, src/v2/Apps/Auction/Components/AuctionDetails/__tests__/SaleDetailTimer.jest.tsx
This PR solves [BID-313]
Changes copy from 'Until Bidding Ends' -> 'Until Lots Start Closing' , which is more accurate. This component is sort of generically named (`SaleDetailTimer`), so I was afraid that perhaps I was inadvertently changing copy for other use cases, but it looks like the fragment container is only used for cascading (https://github.com/artsy/force/blob/40606892068e96bda00397f5f5426ee32c45d142/src/v2/Apps/Auction/Components/AuctionDetails/AuctionDetails.tsx#L51-L53)
[BID-313]: https://artsyproduct.atlassian.net/browse/BID-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update copy for timing banner for cascading auction

.circleci/config.yml
This removes practice-web from out-of-sync MP slack pings since we now have that notification going directly to #dev
=> ci(slack-notifications): remove practice-web

src/v2/System/__tests__/useFeatureFlag.jest.tsx, src/v2/System/useFeatureFlag.tsx
This PR adds a guard against sending segment events when the `variantName` equals `disabled`. This prevents us from sending useless data to segment, as all we care about are `control` or `experiment` views. 
co-authored with: @ovasdi
=> feat: do not send segment event for disabled variant views

src/v2/Components/MagnifyImage.tsx
=> fix: fill width/height for MagnifyImage container

src/v2/Components/MagnifyImage.tsx
[Notion card](https://www.notion.so/artsy/Mobile-web-When-I-tap-an-image-it-zooms-before-navigating-b0f4b0821b3f45b6a20acedf1f7b505c)
When user tap an image (MagnifyImage component), it zooms before navigating
https://user-images.githubusercontent.com/3513494/164474100-430de80b-8e86-4443-8280-b36e49344703.mp4
https://user-images.githubusercontent.com/3513494/164473964-1b72a850-f4fa-4dca-9cfb-8e233e972d5a.mp4
=> fix: ignore touch devices for MagnifyImage component

docs/authentication.md
I thought this was being done in another place while adding Google auth to Force, but later realized it wasn't working how I thought, so I am leaving a note for the next person 😄
=> docs: Document setting scope params [ci skip]

src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx
The type of this PR is: **Bugfix/Enhancement**
This PR solves [FX-3804]
Review app: [artists-filter](https://artists-filter.artsy.net/collect)
* Go to [Collect page](https://www.artsy.net/collect)
* Select the artist you follow in Artists filter (e.g. if you follow Banksy, you need to check Banksy)
* Unselect this artist
* **_current outcome_**: All the artists you follow will be selected.
* **_expected outcome_**: Previously selected artist will be unselected
* Fixes for the problem described above
* Some improvements for `Artists I follow` (you can find more context in [this slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1649779628853899))
https://user-images.githubusercontent.com/3513494/162975587-198733ad-7e85-4b4b-932a-740e8e352829.mp4 …
=> fix(FX-3804): Incorrect behavior for Artists filter

src/v2/Apps/Conversation/Components/ConversationList.tsx
This PR solves [NX-3092]
The calculations and scroll event were fine. The problem was that the layout of the conversation list wasn't limited to the height of the viewport, as it is limited on the main layout.
[NX-3092]: https://artsyproduct.atlassian.net/browse/NX-3092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(NX-3092): constraint the height of the conversation list container

src/v2/Apps/Order/OrderApp.tsx
The type of this PR is: **bugfix**
Currently, if a user has not accepted cookies and views an order page, they will be unable to see the "continue" button at the bottom of the screen and are unable to scroll it into view.
While we figure out a better long-term solution, this PR adds more margin to the container so that users can at least scroll the button into view and not get stuck.
Before:
After:
After + user has accepted cookies:
=> fix[cookie-consent]: add bottom margin to checkout flow

src/v2/Apps/Page/Components/PageHTML.tsx, src/v2/Apps/Page/PageApp.tsx, src/v2/Apps/Press/PressApp.tsx, src/v2/Apps/Press/pressRoutes.tsx, src/v2/__generated__/PressApp_page.graphql.ts, src/v2/__generated__/pressRoutes_InTheMediaQuery.graphql.ts, src/v2/__generated__/pressRoutes_PressReleasesQuery.graphql.ts, src/v2/routes.tsx
Adds the press2 app. These pages are backed by two Markdown pages managed in Torque:
https://admin.artsy.net/page/in-the-media
https://admin.artsy.net/page/news-and-press-releases
Which I made by converting the JSON blobs from the JSON pages into Markdown.
https://artsy-force-production.s3.amazonaws.com/json/in-the-media.json
https://artsy-force-production.s3.amazonaws.com/json/press-releases.json
https://user-images.githubusercontent.com/112297/164546873-7fa75ba6-78f5-42ee-9194-68c2d0843e37.mov
=> feat(press): adds press2 app

src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx, src/v2/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx
This PR solves [SWA-349]
Removes the `swa_my_collection` Unleash feature flag from logic that displays different confirmation screens at the end of the SWA flow.
[SWA-349]: https://artsyproduct.atlassian.net/browse/SWA-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: removed swa unleash flag (SWA-349)

.circleci/config.yml
Every Hokusai release is preceded by a [beta release](https://github.com/artsy/hokusai#distributing-hokusai) which has to be tested against a representative project. We had [designated Gravity](https://github.com/artsy/gravity/pull/15211) as such a project, but it [appears](https://artsy.slack.com/archives/CP9P4KR35/p1650901922885489) that Force is a better candiate!
So how about we put Force on hokusai beta (and relieve Gravity)?
=> feat: let CI always use hokusai beta

src/v2/Apps/Components/AppShell.tsx
The type of this PR is: **hotfix**
This fixes the issue where modals appear below the one-trust banner by forcing the z-index of the banner on mount. Also updates things so that we can make on the fly updates without having to jump through template hoops in one trust admin. Consider this a hotfix.
=> fix(one-trust): ensure that modal appears above one-trust

src/v2/Components/MagnifyImage.tsx
We’ve lost the fade in of the lazy loading of our images with the deep-zoom work. So this PR will fix it
https://user-images.githubusercontent.com/3513494/165492204-65103a96-dcf8-436d-a25b-42c3786f3821.mp4
https://user-images.githubusercontent.com/3513494/165492226-0d0c9b87-b79d-4e23-bb9d-84ec80cd36b8.mp4
=> chore: add fade in effect for image

src/v2/Components/NavBar/NavBar.tsx, src/v2/Components/NavBar/__tests__/NavBar.jest.tsx
This PR solves [GRO-1002]
This fixes an issue where the user isn't redirected back to the existing page on sign up, and instead is redirected to home. Now the user is redirected to the current url.
[GRO-1002]: https://artsyproduct.atlassian.net/browse/GRO-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(auth): Fix redirect to existing page on signup

src/v2/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
This PR solves [NX-3130]
Small improvement to the tertiary button "Contact Gallery" clashing with the partner title.
Before:
After:
[NX-3130]: https://artsyproduct.atlassian.net/browse/NX-3130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(NX-3130): add a margin to the tertiary button to avoid clashing

docs/best_practices.md
Following up on Chris' feedback!
=> docs: Add a link to time example [ci skip]

src/v2/Apps/Artwork/Components/__tests__/ArtistInfo.jest.tsx, src/v2/Components/FollowButton/__tests__/FollowArtistButton.jest.tsx, src/v2/Components/__tests__/ArtistCard.jest.tsx, src/v2/Utils/__tests__/openAuthModal.jest.ts, src/v2/Utils/openAuthModal.ts
This PR solves [GRO-1002]
Fixes a few more redirects that fell off during onboarding removal. Unfortunately we can't fix the article redirect stuff since we can't update old reaction code. Once new article launches we can fix. 
[GRO-1002]: https://artsyproduct.atlassian.net/browse/GRO-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(auth): More redirects

src/v2/Components/FollowButton/__tests__/FollowArtistButton.jest.tsx, src/v2/Components/FollowButton/__tests__/FollowProfileButton.jest.tsx
I have no clue what's correct, this just updates the specs to match https://github.com/artsy/force/pull/10020 (which seemed to be hastily merged by Peril 'merge on green' before Circle ran).
=> test: update some signup redirect specs

src/v2/Apps/Auction/Components/Form/ConditionsOfSaleCheckbox.tsx, src/v2/Apps/Auction/Components/Form/__tests__/ConditionsOfSaleCheckbox.jest.tsx, src/v2/Apps/Auction/Routes/AuctionConfirmRegistrationRoute.tsx
Fixes missing conditions of sale link on register page (it only appeared on register screen for users with a CC on file).
=> fix(auction): Link conditions of sale

src/v2/Apps/Consign/Routes/MarketingLanding/Components/ContactUs.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/FAQ.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/__tests__/ContactUs.jest.tsx, src/v2/Apps/Consign/Routes/Offer/Components/StickyFooter.tsx
This PR solves [GRO-1003]
This is in support of the need to update any use of the old consignments email addresses, so that the team can use the new email address, [sell@artsy.net](mailto:sell@artsy.net) across all surfaces.
[GRO-1003]: https://artsyproduct.atlassian.net/browse/GRO-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GRO-1003: Update general secondary market seller support email to sell@artsy.net

src/v2/Apps/Artwork/ArtworkApp.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/LotTimer.tsx, src/v2/Apps/Artwork/Components/ArtworkSidebar/index.tsx, src/v2/System/WebsocketContext.tsx
Rather than the naive approach of each component initializing their own `actioncable` object _and_ subscription , we really should be using one (per tree).
Artwork app - should have one place that sets up a subscription to the sale channel (if an extended bidding auction work), and injects the received data into the context.
We'd like to use this in the auction app, and so the same applies as above.
Seems to work well w/ mocktioning locally but ofc want to test on staging.
=> feat: move websockets into a proper context, and use in the ArtworkApp

docs/unleash_a-b_testing.md
Noticed that the Unleash docs lacked a section on how to access on the server, so added it!
=> docs(unleash): Add section on accessing flags on server

src/v2/Apps/NewForYou/NewForYouApp.tsx, src/v2/Apps/NewForYou/__tests__/NewForYouApp.jest.tsx
The type of this PR is: Feature development
This PR solves [GRO-919]
Figma Designs: https://www.figma.com/file/HwAhS7iZKrvZLs6lNx5g4z/New-for-You?node-id=53%3A11944
We need to create a new page, /new-for-you so that users can find affinity recommendations all in one place on web.  This puts in the New Works For You page title and header copy.
New Layout:
[GRO-919]: https://artsyproduct.atlassian.net/browse/GRO-919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GROW-919: Added New for You page title and header copy

src/v2/Apps/Collect/Routes/Collections/Components/CollectionsCategory.tsx, src/v2/Apps/Collect/Routes/Collections/index.tsx
This PR solves [FX-3907]
In FX we decided to add two test cases in integrity for collections.
You can see the Integrity PR [here](https://github.com/artsy/integrity/pull/333)
This PR adds:
- added `data-test` properties in order to be able to select the elements that we want to test.
- refactored `sd` -> to use `getENV` in one file due to eslint errors.
- removed redundant react import
[FX-3907]: https://artsyproduct.atlassian.net/browse/FX-3907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add data-test props for collections page

package.json, yarn.lock
Updates eigen-web-association dependency which now includes google auth callback in denylist to prevent artsy app from opening when trying to sign in with google on mobile web.
=> fix: update deeplink denylist to include google auth callback

cypress/integration/home.spec.ts, src/v2/Apps/Home/Components/HomeHeroUnits/HomeHeroUnits.tsx
We have a contract with a partner about how the carousel on the homepage behaves - it was supposed to always show an ad for a particular auction but we forgot about the signed out user. This PR does the absolutely bare minimum to suppress that item because I believe once that sale ends we'll want to revert. Looks like this:
https://artsyproduct.atlassian.net/browse/GRO-1025
=> feat: Temporarily suppress logged out hero GRO-1025

src/v2/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx, src/v2/Components/ArtworkGrid/ArtworkGridEmptyState.tsx, src/v2/Components/ArtworkGrid/__tests__/ArtworkGrid.jest.tsx
This updates our artwork filter so that the zero state / loading indicator is sticky, preserving the position in the users viewport even if they've scrolled down. (It was confusing to click a filter and to see nothing happen, especially if there are no results and on mobile.)
=> feat(artwork-filter): Making loading/zero states sticky

package.json, yarn.lock
Updates eigen-web-association to latest version which has additional auth related endpoints to prevent deep linking during auth flows.
=> fix: update web association, add missing auth endpoints

src/v2/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
This PR solves [GRO-925]
This bundle splits all of the lazy loaded queryrenderers on /artist/id/overview, which reduces the size of the main artist page chunk: 
[GRO-925]: https://artsyproduct.atlassian.net/browse/GRO-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(artist): bundle split artist/overview page

src/v2/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx, src/v2/Components/NavBar/menuData.ts
This PR solves [FX-3965]
Adds `Finds Under ＄1000` -> `/gene/finds-under-1000` to Artworks Navigation tab
|Screenshots||
|---|---|
|<img width="400" alt="Screenshot 2022-05-16 at 19 27 10" src="https://user-images.githubusercontent.com/21178754/168649789-75f51407-d05c-41fc-a0a3-424afd578e9e.png">|<img width="500" alt="Screenshot 2022-05-16 at 19 26 57" src="https://user-images.githubusercontent.com/21178754/168649795-bec90506-024d-4fb7-84d0-02a4d5f9bd5a.png">|
[FX-3965]: https://artsyproduct.atlassian.net/browse/FX-3965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …
=> feat(FX-3965): add finds under 1000 in artwork links tab

src/v2/Components/Footer/Footer.tsx, src/v2/Components/Footer/__tests__/Footer.jest.tsx
Closes https://artsyproduct.atlassian.net/browse/GRO-735 
Education link is very old, so we're going to remove. See [this convo](https://artsy.slack.com/archives/C04KVDZU6/p1641933064003300) for more context.
=> remove(education): Remove link in footer

data/schema.graphql, src/v2/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx, src/v2/Apps/NewForYou/NewForYouApp.tsx, src/v2/Apps/NewForYou/__tests__/NewForYouApp.jest.tsx, src/v2/Apps/NewForYou/newForYouRoutes.tsx, src/v2/__generated__/NewForYouApp_test_Query.graphql.ts, src/v2/__generated__/NewForYouApp_viewer.graphql.ts, src/v2/__generated__/NewForYouArtworksGridQuery.graphql.ts, src/v2/__generated__/NewForYouArtworksGrid_viewer.graphql.ts, src/v2/__generated__/newForYouRoutes_TopLevelQuery.graphql.ts
This PR solves [GRO-918] & [GRO-920]
Add the new for you grid structure & associated query (which will fetch backfill artworks if the user has none). 
Backfill work is in flight, per @jonallured.
[GRO-918]: https://artsyproduct.atlassian.net/browse/GRO-918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-920]: https://artsyproduct.atlassian.net/browse/GRO-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature(NewForYou): implement artwork grid w/ artworksForUser query

src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx, src/v2/Apps/Artist/Routes/WorksForSale/Components/ZeroState.tsx, src/v2/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx, src/v2/Components/ArtworkGrid/ArtworkGrid.tsx, src/v2/Components/ArtworkGrid/ArtworkGridEmptyState.tsx
This PR solves [FX-3927]
[Review app](https://empty-artist-artworks.artsy.net/)
We want to display the same messages on mWeb and Desktop.  More specifically:
- No filters applied: [this copy](https://www.figma.com/file/zG9cduJdOaTQAw886QcOwn/Filters?node-id=3914%3A33534) on desktop / mWeb
- Filters applied: the already existing copy on mWeb but on both desktop/mWeb:
`There aren't any works available that meet the following criteria at this time. Change your filter criteria to view more works. Clear all filters.` 
where the clear all filters will be a clickable underlined text that clears the applied filters.
|No filters applied|Filters applied|
|---|---|
|Before||
|<img width="1792" alt="Screenshot 2022-05-19 at 11 58 36" …
=> chore(FX-3927): update copy when no artworks available by an artist

src/v2/Apps/Order/Routes/Accept/index.tsx, src/v2/Apps/Order/Routes/__tests__/Accept.jest.tsx, src/v2/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx, src/v2/DevTools/RootTestPage.tsx
This PR enhances the morale
Removes the old createTestEnv which works but is a high-level abstraction not needed thanks to the Relay testing tools we have. This is also one attempt to unblock the Relay 13 upgrade which has failing tests in special with `createTestEnv` and they're very hard to debug and find the issue.
=> test: remove old relay test tools part I

src/v2/System/WebsocketContext.tsx, src/v2/__generated__/AcceptTestQuery.graphql.ts
Now that https://github.com/artsy/gravity/pull/15349 is in, we can start passing along the xapp token.
Once a mocktion verifies this all works on staging, I can follow up with the final update in gravity:
- dropping the 'allowlist' of domains in place of strictly requiring an xapp token
=> chore: pass xapp_token along in websocket request

src/v2/Apps/Settings/Routes/DeleteAccount/DeleteAccountRoute.tsx, src/v2/Apps/Settings/settingsRoutes.tsx, src/v2/__generated__/DeleteAccountRoute_me.graphql.ts, src/v2/__generated__/settingsRoutes_DeleteAccountRouteQuery.graphql.ts
This PR solves [PLATFORM-4147]
Thanks to @damassi , @ovasdi , @jacobherrington for their help with this task.
Update `/settings/delete` page so it presents two alternative views:
- When `hasPassword` is true (the case of non-social accounts), display a `PASSWORD` field required for form submission. Password must be correct for deletion to succeed.
- When `hasPassword` is false (Google/Facebook/Apple accounts), no `PASSWORD` field.
Related PRs and Slack threads:
https://github.com/artsy/metaphysics/pull/4057 (MP accept password)
https://github.com/artsy/gravity/pull/15289 (Gravity accept password)
https://github.com/artsy/integrity/pull/337 (Update test for non-social account deletion)
https://artsy.slack.com/archives/C9XJKPY9W/p1652992094634549 …
=> feat: require password for account deletion, if account has password

src/v2/Components/Artwork/Badge.tsx
Not sure what would have changed for this to be the case. The styles in the `styled` tag were losing out to the text variant styling. This PR fixes the issue for the time being, but this warrants a closer look as to why this happened.
=> fix: corrects sizing of badge

docs/authentication.md
The type of this PR is: Documentation
This PR solves [PLATFORM-4182]
From [time to time](https://github.com/artsy/force/pull/10132) we have to test 3rd party auth on local Force. So far we know how to do it for Google auth. The steps are quite involved so documenting them.
[PLATFORM-4182]: https://artsyproduct.atlassian.net/browse/PLATFORM-4182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add instructions about Google auth during local development

src/v2/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx
This PR solves [PLATFORM-4179]
This PR adds an alert message after a user updates their email instructing them to verify their email address. It supports the backend changes being made as part of this [ticket](https://artsyproduct.atlassian.net/browse/PLATFORM-4178), and will not be merged until that work is complete. 
I don't love the two toasts, but I felt it made the action require more clear to the user. If people feel strongly, I'm happy to revert to the alternative approach shown below, with the action required message being part of the success toast message. 
Current Approach:
Alternative Approach:
Update [related integrity test.](https://github.com/artsy/integrity/blob/5dac98724c8500498156d8f491fceea16a5fbd53/cypress/integration/velocity/auth …
=> refactor: add alert to verify email after update

src/v2/Apps/Artwork/Components/ArtworkLightbox.tsx, src/v2/Apps/Artwork/Components/__tests__/ArtworkLightbox.jest.tsx, src/v2/__generated__/ArtworkLightboxTestQuery.graphql.ts
This makes the ArtworkLightbox a bit safer with a guard, and adds a test. 
Repo steps:
- on staging, log out
- visit https://staging.artsy.net/artwork/628e9618880cda000d5fb82e
- should get 500 error, due to server-side render pass failing [around here](https://github.com/artsy/force/blob/main/src/v2/Apps/Artwork/Components/ArtworkLightbox.tsx#L29)
- Does _not_ fail on localhost
@laurabeth / @dzucconi - when y'all get a sec please investigate why `activeIndex` might be null as that's what seems to be leading to this error. Nothing jumps immediately out. 
See [this thread](https://artsy.slack.com/archives/C02BC3HEJ/p1653428106310039) for more info.
=> bugfix(artwork-lightbox): make lightbox safer

package.json
I can never remember the URL to test the cookie consent banner, so dropped it into package.json as a script.
=> chore(one-trust): add open link with query params in package.json

src/v2/Components/Range.tsx
This PR solves [FX-3995]
Fixes a minor issue where a user may inadvertently highlight a selection which includes the range slider UI, which is visually noisy and not really meaningful
https://user-images.githubusercontent.com/140521/171226922-f381deb8-4072-4fb6-956c-21f6f96e4fc9.MP4
Note that some text remains selectable, consistent with other parts of the filter UI.
https://user-images.githubusercontent.com/140521/171226924-cb42ffe9-269e-48fe-ad4e-40b040345cdb.MP4
[FX-3995]: https://artsyproduct.atlassian.net/browse/FX-3995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: disable text highlighting within range slider UI

package.json, src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx, src/v2/System/Router/RenderStatus.tsx, src/v2/Utils/Hooks/useRouteComplete.ts, yarn.lock
This PR solves multiple 500s on staging (presumably after webpack update)
=> resolves setImmediate is not defined problem

.secrets.baseline, package.json, src/v2/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/v2/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx, src/v2/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx, src/v2/Apps/ViewingRoom/__tests__/ViewingRoomApp.jest.tsx, src/v2/DevTools/__tests__/renderUntil.jest.tsx, src/v2/DevTools/enzyme+renderUntil.d.ts, src/v2/DevTools/renderUntil.tsx, src/v2/System/Router/RenderStatus.tsx, src/v2/System/__tests__/SystemContext.jest.tsx, src/v2/Utils/Hooks/useRouteComplete.ts, yarn.lock
This replaces our non-standard use of `setImmediate` with `setTimeout`. It turns out that `setImmediate` is a [non-standard browser function](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) and `setTimeout, 0` does the exact same thing. 
Related: 
- https://github.com/artsy/force/pull/10203
- https://github.com/artsy/force/pull/10198
=> fix(standards): replace setImmediate with setTimeout

src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx, src/v2/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx
This PR solves [FX-4005]
Review app: https://saved-label-on-artwork-page.artsy.net/artwork/banksy-flower-thrower-13
* Given a collector
* And I am on an artwork page
* And the artwork is not yet saved
* When I click the save control
* The control text changes to “Saved”
* And "Saved" label should not shift other buttons to the right
https://user-images.githubusercontent.com/3513494/171868173-d3d666dd-2250-4c55-be65-6c5faf8e570e.mp4
https://user-images.githubusercontent.com/3513494/171868236-6ebf6433-4eba-4fcb-a55b-f7812eac700b.mp4
[FX-4005]: …
=> chore(FX-4005): display "Saved" label when artwork is saved

src/v2/Apps/Collect/Routes/Collect/Utils/__tests__/getMetadata.jest.ts, src/v2/Apps/Collect/Routes/Collect/Utils/getMetadata.ts, src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx
~Blocked by https://github.com/artsy/gravity/pull/15407 + a full artwork reindex, but otherwise ready for review~ all good now 👍🏽 
This PR solves [FX-4001]
This reverts the revert in 2b25e68979007aa2698e4e43e08dae82f34e1128, in order to re-enable the updated color filtering UIs, with an updated palette of color swatches to choose from.
(Eventually we'll PR a change to _drop_ support for the _old_ colors).
[FX-4001]: https://artsyproduct.atlassian.net/browse/FX-4001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: re-enable new color filtering palette

src/v2/Components/Artwork/ShelfArtwork.tsx
Co-authored-by: Dima Tretyak (Dzmitry Tratsiak) <itretyak@ya.ru>
This PR solves [FX-3997](https://artsyproduct.atlassian.net/browse/FX-3997)
Review app: https://shelf-artwork-save-button.artsy.net/
Updates the pages which do not have the quick-view functionality to have the new Save button.
https://user-images.githubusercontent.com/3934579/172379667-91c3b3c5-f479-4681-9991-ad13f7a59d89.mp4
https://user-images.githubusercontent.com/3934579/172379684-74d499b1-5bf7-48a1-9bef-870d7108c424.mp4
=> feat(FX-3997): Expand New 'Save' Styling to ShelfArtwork component

src/v2/Apps/ArtAppraisals/ArtAppraisalsApp.tsx
This is actually centered. I think you were trying to offset for the line-height of the headline text. Which I don't think we should do.
Also minor fix: don't wrap buttons in links. It creates a double tabstop and an empty button.
=> fix: removes offset; removes double focus

src/v2/Apps/Auction/Routes/Bid/AuctionBidRoute.tsx, src/v2/Apps/Auction/Routes/Bid/__tests__/AuctionBidRoute.jest.tsx, src/v2/__generated__/AuctionBidRouteQuery.graphql.ts, src/v2/__generated__/AuctionBidRouteTestQuery.graphql.ts, src/v2/__generated__/AuctionBidRoute_artwork.graphql.ts, src/v2/__generated__/auctionRoutes_BidRouteQuery.graphql.ts
This PR solves [BID-388]
This re-uses the artwork page countdown and progress bar in the bid modal. It's a bit rough, but works as expected!
Looks like:
The footnote about closure times adjusting is popcorn-bidding specific.
I have an open question to design about fitting this data in a bit more smoothly but in the meantime, we decided to roll with it.
[BID-388]: https://artsyproduct.atlassian.net/browse/BID-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add lot countdown timer + progress bar in bid modal

src/v2/Apps/Artist/Routes/Overview/Components/ArtistNotableWorksRail.tsx, src/v2/Apps/Artist/Routes/Overview/Components/ArtistWorksForSaleRail.tsx, src/v2/Apps/Auctions/Components/AuctionArtworksRail.tsx, src/v2/Apps/Auctions/Components/StandoutLotsRail.tsx, src/v2/Apps/Auctions/Components/TrendingLotsRail.tsx, src/v2/Apps/Auctions/Components/WorksByArtistsYouFollowRail.tsx, src/v2/Apps/Consign/Routes/MarketingLanding/Components/SoldRecentlyOnArtsy.tsx, src/v2/Apps/Fair/Components/FairBoothRail/FairBoothRailArtworks.tsx, src/v2/Apps/Home/Components/HomeAuctionLotsRail.tsx, src/v2/Apps/Home/Components/HomeRecentlyViewedRail.tsx, src/v2/Apps/Home/Components/HomeWorksByArtistsYouFollowRail.tsx, src/v2/Components/Artwork/ShelfArtwork.tsx
This PR solves [FX-4016]
Related PR for `GridItem` component #9741
We added new hover behavior to swap in information on Rarity and Medium Type on artwork cards in the artwork grid. This ticket covers adding the same hover behavior to the artworks cards found on the ArtworkShelf component, supporting most artwork rails on [artsy.net](http://artsy.net/)
> **Note**
> We also want to start rendering the gallery name on these cards as well. This will give us the same vertical space to render the pills within.
* Always display artist name, artwork title, gallery name/partner, price
* Display the rarity and medium type pills when hovering over an artwork card in an artwork rail
* No changes to existing behaviour on artwork grid artwork item (default …
=> enhancement(FX-4016): Add new hover behavior to artwork cards in ArtworkShelf

src/v2/Apps/Artist/Routes/Overview/Components/ArtistNotableWorksRail.tsx
This PR solves [FX-4020]
https://user-images.githubusercontent.com/3513494/172820004-bd4dcfa0-a70e-4c8b-a360-5f84b21e0400.mp4
https://user-images.githubusercontent.com/3513494/172820189-3cca0c8c-2d0b-45c8-a8bd-c42c637f2c3e.mp4
cc: @dzucconi 
[FX-4020]: https://artsyproduct.atlassian.net/browse/FX-4020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FX-4020): Jumping state for "Notable Works" rail on artwork page

package.json, yarn.lock
The type of this PR is: **Lib**
Updates eigen-web-associations lib which excludes `/art-appraisals` route. See https://github.com/artsy/artsy-eigen-web-association/pull/51. 
=> lib(update): Update eigen-www

src/v2/Apps/WorksForYou/WorksForYouApp.tsx
This PR solves [FX-4017]
Similar PR #8004
Review app: https://works-for-you-page.artsy.net/works-for-you
Artworks break out of container and overlap the footer if you open the ["Works For You"](https://www.artsy.net/works-for-you) page in Firefox
https://user-images.githubusercontent.com/3513494/172888470-73a4a6ca-91f5-4a75-a8bb-a79be474aaa3.mp4
https://user-images.githubusercontent.com/3513494/172888583-34267262-583f-4453-9989-a1ccbc4af9ca.mp4
[FX-4017]: https://artsyproduct.atlassian.net/browse/FX-4017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: "Works for You" page does not display correctly in Firefox

src/v2/Apps/Order/Components/BankDebitDetails.tsx, src/v2/Apps/Order/Components/PaymentMethodSummaryItem.tsx, src/v2/Apps/Order/Components/WireTransferDetails.tsx, src/v2/Apps/Order/Components/__tests__/WireTransferDetails.jest.tsx, src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx, src/v2/Apps/Order/Routes/Review/index.tsx, src/v2/Apps/Order/Routes/Status/index.tsx
This PR solves [TX-403]
This PR improves the checkout flow UI, namely: 
- The copy for wire transfer payment method is updated to "To pay by wire transfer, complete checkout and a member of the Artsy team will contact you with next steps by email." in Payment and Review steps. 
- The copy is removed from the confirmation step.
- The icon colours for wire and bank transfer orders are updated to _green100_
- The copy "Payment" is updated to "Payment method' in Review and Confirmation steps. 
Note: to make the CreditCardIcon darker, we'll need to update it on Palette as there seems to be no type or color that we can pass to it to make it darker.
https://user-images.githubusercontent.com/42584148/173025150-02633b95-5241-4cdd-8022-a79e1277f451.mov …
=> [ENHANCEMENT]: AlicanAkyuz/TX-403/UI-improvements-checkout-flow

src/v2/Apps/Order/Routes/Payment/index.tsx, src/v2/Apps/Order/Routes/__fixtures__/MutationResults/setOrderPayment.ts, src/v2/__generated__/PaymentRouteSetOrderPaymentMutation.graphql.ts
This PR fixes the problem that users choosing credit card had to click Continue 2 times in orders to move to the review step. Luckily, this bug did not affect users on productions, since it's caused by new payment method integration, which is behind a feature flag. 
We solved the problem by pulling the paymentMethod on Order when payment is set, so that the redirecting logic could safely check if creditCard info exists in an order when paymentMethod is CreditCard.
=> [fix]: AlicanRachelKiril/pull-paymentMethod-upon-setting-payment

src/v2/Apps/IdentityVerification/IdentityVerificationApp/index.tsx, src/v2/Apps/IdentityVerification/__tests__/IdentityVerificationApp.jest.tsx
This PR solves [PLATFORM-4165](https://artsyproduct.atlassian.net/browse/PLATFORM-4165)
This is a followup to https://github.com/artsy/force/pull/10263. After removing [this logic](https://github.com/artsy/force/pull/10263/files#diff-5e4ebdf40b75b0a9dac5f65a77a5e245dff68b03561e90c7259fefecc403bd2dL39) and the [wrong-owner component](https://github.com/artsy/force/pull/10263/files#diff-5e8cbe37fe55c565db5dfb15eaa537c04376af52e84c62af9370006930c54bf6L11) I introduced a regression and so now when requesting an identity verification that does not exist the client throws a _500 internal server error_ whereas before we rendered a _wrong-owner_ component. 
To address this regression I thought it would be good to return a _404_ when an identity verification …
=> enhancement: return 404 when identity verification does not exist

src/v2/Components/ArtworkFilter/ArtworkFilters/ColorFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.jest.tsx
This PR solves [FX-3779]
Simply adds a new color filtering option for **brown**.
This will begin to appear in the filtering UI as soon as this PR is deployed, so this should probably wait until we've actually indexed brown for all artworks (see: https://github.com/artsy/gravity/pull/15433)
|Desktop|mWeb|
|---|---|
|<img alt="brown desktop" src="https://user-images.githubusercontent.com/140521/172861191-4f2485f2-422a-4950-a247-7aad4dabeced.png">|<img alt="brown mweb" src="https://user-images.githubusercontent.com/140521/172861653-ca530677-c260-4ca5-9e61-3d798b88a7a3.png">|
[FX-3779]: …
=> feat(colors): add brown color filter option

src/v2/Components/NavBar/NavBarLoggedInActions.tsx, src/v2/Components/NavBar/__tests__/NavBarTracking.jest.tsx
This PR solves [FX-4007]
Related Palette PR: artsy/palette#1180
Review app: https://replace-hover-on-click.artsy.net/
Right now you can hover over the activity bell or the profile icon to see menus appear. We’d like to remove the hover effect and instead show/hide the menus on click
* Menu should be opened/hided by click instead of hover
* Clicking outside of the menu should cause the menu to hide
[FX-4007]: https://artsyproduct.atlassian.net/browse/FX-4007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-4007): replace hover to click on rightmost navigation bar elements

src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx
Related PR #10186
This PR solves [FX-3972]
Unleash flag: [trending-sort-for-artist-artwork-grids](https://unleash.artsy.net/projects/default/features/trending-sort-for-artist-artwork-grids)
* Experiment name: `trending-sort-for-artist-artwork-grids`
* Variant names: `control` and `experiment`
[FX-3972]: https://artsyproduct.atlassian.net/browse/FX-3972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-3972): track analytics for Trending Sort A/B test

src/lib/analytics/segmentOneTrustIntegration/__tests__/getOneTrustConsent.jest.ts, src/lib/analytics/segmentOneTrustIntegration/getOneTrustConsent.ts, src/lib/analytics/segmentOneTrustIntegration/setServerSideCookie.ts, src/v2/server.ts
This updates our OneTrust cookie consent flow by syncing the client-side cookie on the server via `secure: true`, which should satisfy Apple's requirements around ITP and get around resetting after 7 days. 
Note the checkmarks in the rows highlighted below; that means `secure: true`, set from the server and overwriting the client cookie set by OneTrust.
Opening for discussion.
=> feat(cookie-consent): Sync OneTrust cookie on server

src/v2/Apps/Auction/Routes/Bid/AuctionBidRoute.tsx, src/v2/Apps/Auction/Routes/Bid/__tests__/AuctionBidRoute.jest.tsx
So this looks suspicious to me. Theoretically this _shouldn't_ be an issue because of: https://github.com/artsy/palette/blob/bbea96cd7e4ecd74b5f60fb12c1de9792b6795a7/packages/palette/src/utils/usePortal.ts#L24 — but it's worth a shot.
=> fix(auction): wait for mount on bid route

src/v2/Components/__tests__/SelectedCareerAchievements.jest.tsx, src/v2/System/Router/RenderStatus.tsx
The theory here is that some race condition has been exposed and a state set is happening on an unmounted component. `useEffect` runs only on the initial mount (server rehydration), and since the set states happen in the render body directly; here I've just stuck the timeouts in refs then clear them in the opposing conditional branches.
=> fix: render status

src/v2/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
One slightly suspicious thing here was a component that used a modal which was being defined inside of a render body. Not a good thing to do, so this is a harmless refactoring but I don't really believe it to be the cause of the render bug we're encountering.
=> refactor(artwork): moves component definitions outside of render body

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx
This PR solves [FX-4043]
After the upgrade of palette to v3.1 the pill design in the alert management page broke, this pr addresses that.
> ⚠️ ⚠️ This PR doesn't address the other layout issues. I will follow up with design to create tickets and sync for the rest of the layout issues ⚠️ ⚠️ 
|Before|After|
|---|---|
|<img width="1792" alt="Screenshot 2022-06-16 at 12 28 10" src="https://user-images.githubusercontent.com/21178754/174040173-2d1dafe2-7813-48c0-aa33-4d3ed949a4f0.png">|<img width="1792" alt="Screenshot 2022-06-16 at 12 29 32" src="https://user-images.githubusercontent.com/21178754/174040160-1a0f2248-f632-4d92-aaf7-71184e186070.png">|
|Before|After|
|---|---|
|<img width="420" alt="Screenshot 2022-06-16 at 12 30 50" …
=> fix(FX-4043): Alert Management page pills styling after palette upgrade

src/v2/Apps/Artwork/Components/ArtworkMeta.tsx
Temporarily removes ZenDesk; which appears to be crashing some artwork pages, only in production.
Will follow up with a re-enable; sans the 3rd party integration library.
cc https://github.com/artsy/force/pull/10318
=> fix: temporarily removes zendesk

src/v2/Apps/Artwork/Components/ArtworkMeta.tsx
Whether it's with how this script is loaded, or something in the content of this script — something about this include is causing the DOM to be manipulated outside of React, which is causing an error on route changes.
Removing it completely for now. Will re-add using our `useLoadScript` hook.
=> fix: removes google retargeting script

src/v2/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx, src/v2/__generated__/NewForYouApp_test_Query.graphql.ts, src/v2/__generated__/NewForYouArtworksGrid_viewer.graphql.ts, src/v2/__generated__/newForYouRoutes_TopLevelQuery.graphql.ts
NFY was displaying empty state despite data being available. After doing a sanity check w/ @jonallured & @dzucconi we realized that there was a typo in the props passed to the `ArtworkGrid` component. Corrected the prop name and all is right with the world.
Gotcha: 
- The `ArtworkGrid` can take a singular `artwork` prop without throwing a type error.
=> bugfix(NewForYou): artwork grid empty state

yarn.lock
This PR solves [TX-421]
Roughly since https://github.com/artsy/force/pull/10320, we started to see flaky Integrity failures on the[ SCA scenarios](https://artsy.slack.com/archives/C02JHHHKP5K/p1655809767938599). It's hard but I managed to [reproduce](https://artsy.slack.com/archives/C02JHHHKP5K/p1655824170423609?thread_ts=1655809767.938599&cid=C02JHHHKP5K) it by simulating a slower network connection when submitting an order with SCA card.
Still not sure the root cause but trying to roll forward and upgrade the libs and see if this fixes it.
[TX-421]: https://artsyproduct.atlassian.net/browse/TX-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: upgrade stripe libs

src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx, src/v2/Components/ArtworkFilter/Utils/fetchFollowedArtists.ts
These changes are necessary for the [FX-4041](https://artsyproduct.atlassian.net/browse/FX-4041) task so that artist pills can be displayed correctly when the "Artists I Follow" option has been selected (now the followed artists are stored [inside the component](https://github.com/artsy/force/blob/main/src/v2/Components/ArtworkFilter/ArtworkFilters/ArtistsFilter.tsx#L94) and for this reason we do not have access to them)
https://user-images.githubusercontent.com/3513494/173886558-4a3d74dc-cbff-4da0-8a6b-74f3b54ed851.mp4
=> chore: keep followed artists inside `ArtworkFilterContext`

src/v2/Apps/Components/AppShell.tsx, src/v2/Utils/Hooks/__tests__/useBrazeInAppMessage.jest.ts, src/v2/Utils/Hooks/useBrazeInAppMessage.ts
This PR adds a new trick to our app shell: conditionally showing Braze In App Messages! I got some advice from @dzucconi here:
https://artsy.slack.com/archives/C01ADJNCS5D/p1655829978286369
And the approach we sorta settled on was: add a hook to the app shell and adapt the code that Segment suggests with an allow list of routes. Here's that code from the Segment docs:
https://segment.com/docs/connections/destinations/catalog/braze/#other-features
Overall the flow is:
* add a ready handler to window.analytics
* add a subscription to window.appboy with a handler
* when that handler fires, decide if the IAM should be shown
In terms of testing what we have here is I extracted a function that wraps the regex checks and that's what I'm testing. The async nature of this code resisted any further …
=> feat: Manually trigger Braze IAM GRO-895

yarn.lock
This PR solves [PLATFORM-4245]
This PR bumps `prismjs` from `1.21.0` to `1.28.0`
[PLATFORM-4245]: https://artsyproduct.atlassian.net/browse/PLATFORM-4245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump prismjs

yarn.lock
This PR solves [PLATFORM-4245](https://artsyproduct.atlassian.net/browse/PLATFORM-4245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
Description
This PR follows up on #10372 to bump prisms from `1.21.0` to `1.28.0`. I missed the transitive dep from `refactor` in the previous PR.
=> chore: bump prismjs part two

src/v2/Apps/Onboarding/Components/OnboardingSplitLayout.tsx, src/v2/Apps/Onboarding/Components/OnboardingWelcomeAnimatedPanel.tsx, src/v2/Apps/Onboarding/Views/OnboardingWelcome.tsx
This blocks in the animation on the opening welcome panel. We won't have assets until they are approved on Monday — so some placeholders.
https://user-images.githubusercontent.com/112297/175394154-034c1613-72f7-4e84-9572-d3c2c9312b17.mov
=> feat(onboarding): adds animated welcome panel

src/v2/Components/DownloadAppBadges/DownloadAppBadge.tsx, src/v2/Components/Footer/FooterDownloadAppBanner.tsx
This PR solves [GRO-994]
- Upload assets through tools.artsy.net
- Swap out asset addresses in both `FooterDownloadAppBanner` and `DownloadAppBadge`
[GRO-994]: https://artsyproduct.atlassian.net/browse/GRO-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(footer): swap out assets

src/v2/Apps/Onboarding/Components/OnboardingWelcomeAnimatedPanel.tsx, src/v2/Apps/Onboarding/Hooks/useOnboardingFadeTransition.tsx, src/v2/Apps/Onboarding/Views/OnboardingQuestionOne.tsx, src/v2/Apps/Onboarding/Views/OnboardingQuestionThree.tsx, src/v2/Apps/Onboarding/Views/OnboardingQuestionTwo.tsx, src/v2/Apps/Onboarding/Views/OnboardingWelcome.tsx, src/v2/Utils/Hooks/__tests__/useFadeTransition.jest.tsx, src/v2/Utils/Hooks/useFadeTransition.story.tsx, src/v2/Utils/Hooks/useFadeTransition.tsx
The goal with this PR was to implement a method for doing the staggered fade transitions without having to muddy up the components with complex and repetitive styling.
The solution I arrived at with cda564a26bc3013d67e094d6314480eb58b5653f is a very simple hook that allows one to `register` elements in a specific order. Then returns a function to `transition` them in that order. We could make this hook much more generic to support different types of transitions; like transforms — not necessary at this time.
https://user-images.githubusercontent.com/112297/175652649-823d2968-10e9-454f-a7e1-5e29006377e5.mov
=> feat(onboarding): adds staggered fade transition between views

src/v2/Apps/Conversation/Components/ConfirmArtworkButton.tsx, src/v2/Apps/Conversation/Components/ConfirmArtworkModal.tsx, src/v2/Apps/Conversation/Components/Conversation.tsx, src/v2/Apps/Conversation/Components/ConversationCTA.tsx, src/v2/Apps/Conversation/Components/OrderModal.tsx, src/v2/Apps/Conversation/Components/Reply.tsx
This PR solves [NX-3190]
This fix is needed because otherwise Conversational Buy Now Flow for artworks containing more than 1 edition set would lead to "Make Offer" flow instead of "Buy Now".
The solution here consists of passing the param between different components so we can control if an order is an offer or purchase. We understand this is not the ideal solution, this is a quick fix so we can release the feature tomorrow. We'll work separately on a proper refactor to avoid the prop drilling ([NX-3208]).
[NX-3190]: https://artsyproduct.atlassian.net/browse/NX-3190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> fix(NX-3190): fix bug on CBN flow for edition sets

src/v2/Apps/Order/Routes/Offer/index.tsx, src/v2/Apps/Order/Routes/__tests__/Offer.jest.tsx, src/v2/Apps/__tests__/Fixtures/Order.ts, src/v2/__generated__/OfferTestQuery.graphql.ts, src/v2/__generated__/Offer_order.graphql.ts, src/v2/__generated__/orderRoutes_OfferQuery.graphql.ts
This PR solves [NX-3064]
This PR enables the New Offer Submission Flow on single editioned artworks with a listed price.
We can continue enhancing the scope of NSFW with future work, after a clearer path forward with editions.
Based on work done by @tam-kis 
[NX-3064]: https://artsyproduct.atlassian.net/browse/NX-3064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Enable NOSF for single editions with listed price

package.json, src/v2/Apps/Order/Routes/Shipping/index.tsx, src/v2/Apps/Order/Routes/__tests__/Shipping.jest.tsx, src/v2/Apps/__tests__/Fixtures/Order.ts, yarn.lock
Expands force side logic to include more countries into artsy shipping
pairing with @oxaudo 
TO DOs:
Addressing: https://artsyproduct.atlassian.net/browse/PX-5031
This PR solves [PX-5031]
Expands force logic to allow for EU/UK/CH/NO domestic and international artsy shipping
[PX-5031]: https://artsyproduct.atlassian.net/browse/PX-5031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(PX-5031): Support EU/NO/GB/CH checkout out flows with artsy shipping

src/v2/Apps/Onboarding/Components/OnboardingProgress.tsx, src/v2/Apps/Onboarding/Views/OnboardingQuestionOne.tsx, src/v2/Apps/Onboarding/Views/OnboardingQuestionThree.tsx, src/v2/Apps/Onboarding/Views/OnboardingQuestionTwo.tsx, src/v2/Utils/Hooks/useDebounce.ts
Closes [GRO-1093](https://artsyproduct.atlassian.net/browse/GRO-1093)
A little tricky: we need to either relocate the progress bar to the parent `OnboardingSteps` so that it transitions smoothly — this is non-ideal, structurally. Or: we can transition to the next state _before_ the step renders, as the old one is transitioning out. This works but is slightly weird since there's a spare render that happens inside the step that picks up the previous progress; since this is a computed value coming from the workflow engine. A bit of a hacky solution then: just debounce the progress value so that we loose that spare render.
=> feat(onboarding): animates progress bar

src/v2/Apps/Home/Components/HomeNewWorksForYouRail.tsx, src/v2/Apps/Home/Components/HomeWorksForYouTabBar.tsx, src/v2/Apps/Home/__tests__/HomeNewWorksForYouRail.jest.tsx, src/v2/Apps/Home/__tests__/HomeWorksForYouTabBar.jest.tsx, src/v2/__generated__/HomeNewWorksForYouRailQuery.graphql.ts, src/v2/__generated__/HomeNewWorksForYouRail_Test_Query.graphql.ts, src/v2/__generated__/HomeNewWorksForYouRail_artworksForUser.graphql.ts
This PR updates the homepage app to default to a rail powered by the `artworksForUser` query that ends up populating the rail with the newest affinity based artwork recs. Looks like this:
https://artsyproduct.atlassian.net/browse/GRO-1103
=> Add new for you rail to homepage

src/v2/Apps/Onboarding/Components/OnboardingGene.tsx, src/v2/Apps/Onboarding/Components/__tests__/OnboardingGene.jest.tsx, src/v2/Apps/Onboarding/Views/OnboardingArtistsOnTheRise.tsx, src/v2/Apps/Onboarding/Views/OnboardingCuratedArtworks.tsx, src/v2/Apps/Onboarding/Views/OnboardingTopAuctionLots.tsx, src/v2/Apps/Onboarding/config.ts, src/v2/__generated__/OnboardingGeneQuery.graphql.ts, src/v2/__generated__/OnboardingGene_Test_Query.graphql.ts, src/v2/__generated__/OnboardingGene_gene.graphql.ts
The type of this PR is: *feat*
This PR solves [GRO-1097]
The intention of this code is to build out the Top Auction Lots rewards screen that occurs at the end of the Onboarding workflow. By writing the component to be re-usable based on gene name and sub-header description as a prop, the config for Trove and Artists on the Rise reward screens are also included in this pr. 
Acceptance criteria: 
Top Auction Lots
Artists on the Rise
Trove
[GRO-1097]: https://artsyproduct.atlassian.net/browse/GRO-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(GRO-1097)(onboarding): Build top auction lots screen

src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx, src/v2/Apps/Order/Routes/__tests__/Payment.jest.tsx
This adds the correct action type for clicked payment method. 
[Slack thread](https://artsy.slack.com/archives/C02JHHHKP5K/p1656518383285269)
=> fix(tracking): add correct action type for clicked payment method

src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
This PR solves [TX-411]
This PR adds the "US bank account only" label to the ACH payment method selection.
[Figma](https://www.figma.com/file/rhcgsn0cMrogxN0TXu5l6T/TX-ACH-Bank-Transfer%2F-Wire-transfer?node-id=4261%3A56669)
[TX-411]: https://artsyproduct.atlassian.net/browse/TX-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-411): add US bank account only label 

src/v2/Apps/Order/Components/WireTransferDetails.tsx, src/v2/Apps/Order/Components/__tests__/WireTransferDetails.jest.tsx, src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx
This PR solves [TX-418]
In the wire order checkout flow, we tell users that their bank may charge a fee for the wire transfer. This is incorrect because their bank is expected to charge the buyer a fee for the wire transfer.
This PR changes the message from “Your bank may charge a fee for the transaction.” to “Please inform your bank that you will be responsible for all wire transfer fees.”
[TX-418]: https://artsyproduct.atlassian.net/browse/TX-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [chore][TX-418]: AlicanAkyuz/Inform users about wire transfer fees

src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx, src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx, src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/KeywordFilter.tsx, src/v2/Components/ArtworkFilter/ArtworkFilters/__tests__/KeywordFilter.jest.tsx, src/v2/Components/ArtworkFilter/Utils/isDefaultFilter.tsx, src/v2/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx, src/v2/Components/ArtworkFilter/index.tsx
This PR solves [FX-4027]
As a collector
When I visit the artist page’s artwork grid
I see a new keyword filter
And when I enter a keyword
the grid is filtered down to match that query
I've created a feature toggle in Unleash, it's called `artist-artwork-grid-keyword-search` and currently enabled for development and staging
* [Demo app](https://artwork-grid-keyword-filter.artsy.net)
* [Banksy grid](https://artwork-grid-keyword-filter.artsy.net/artist/banksy/works-for-sale?sort=-default_trending_score)
https://user-images.githubusercontent.com/3934579/175893281-c8b0e340-644b-4087-9d80-0496e926e4dd.mp4
[FX-4027]: https://artsyproduct.atlassian.net/browse/FX-4027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4027): Add keyword filter to artist page's artwork grid

src/v2/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx
Small markup fix. Fixes paddings between filter components on Artist Works for sale grid
This PR solves [FX-4027]
[FX-4027]: https://artsyproduct.atlassian.net/browse/FX-4027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FX-4027): fixes Artist Works For Sale filters markup

src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx, src/v2/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx, src/v2/__generated__/SavedSearchAlertEditFormQuery.graphql.ts, src/v2/__generated__/SavedSearchAlertEditForm_Test_Query.graphql.ts, src/v2/__generated__/SavedSearchAlertEditForm_viewer.graphql.ts
This PR solves [FX-4059]
Review app: https://warning-message.artsy.net/
Display a warning message on edit alert screen if the "Email Alerts" toggle is enabled, but the "Custom Alerts" setting is disabled in the [Email Preference Center](https://artsy.net/unsubscribe) on Force (this is already [implemented for Eigen](https://github.com/artsy/eigen/pull/6070))
There may be a situation when the user previously created a saved search alert and enabled "Email Alerts" toggle, but later set "Email Preferences" to "None". And it would be useful to warn the user about this on edit alert screen
https://user-images.githubusercontent.com/3513494/177386719-e13a89eb-97bb-47d2-acd2-8edd32094aec.mp4
[FX-4059]: …
=> feat(FX-4059): display warning message on edit alert screen

src/v2/Apps/Partner/Routes/Works/index.tsx, src/v2/Apps/Partner/Routes/__tests__/Works.jest.tsx, src/v2/Components/ArtworkFilter/Utils/__tests__/filterArtistSlugsByAggregation.jest.ts, src/v2/Components/ArtworkFilter/Utils/filterArtistSlugsByAggregation.ts, src/v2/Components/ArtworkFilter/Utils/usePrepareFiltersForPills.ts, src/v2/Components/SavedSearchAlert/Components/ActiveFilterPills.tsx, src/v2/Components/SavedSearchAlert/Components/ArtworkGridFilterPills.tsx, src/v2/Components/SavedSearchAlert/Components/DefaultCreateAlertButton.tsx, src/v2/Components/SavedSearchAlert/Components/__tests__/ArtworkGridFilterPills.jest.tsx, src/v2/Components/SavedSearchAlert/constants.ts, src/v2/__generated__/WorksTL_Query.graphql.ts
This PR solves [FX-4041]
Review app: https://selected-filters-for-partner.artsy.net
We’ve added active filter pills to the artist page’s artworks grid a while ago, which is also where the “Create alert” control lives. We’d like to first expand these active filter pills to other grids before we also support alert creation on those surfaces.
* As a collector
* When I visit a partner’s artwork grid
* And I enable at least one filter
* Then I should see my active filters represented as pills above the artwork grid
* And "Create Alert" button should **NOT** be displayed
* [Aicon Gallery](https://selected-filters-for-partner.artsy.net/partner/aicon-gallery/works)
* [Paragon](https://selected-filters-for-partner.artsy.net/partner/paragon/works)
* [Galerie …
=> feat(FX-4041): Add active filter pills to partner page's artwork grid

src/v2/Apps/Home/Components/HomeFeaturedShowsRail.tsx
This PR solves [GRO-1034]
Previously the FeaturedShows component used to be a grid and so was limited to 6. It’s now a rail so the limit can be removed.
[GRO-1034]: https://artsyproduct.atlassian.net/browse/GRO-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: removing feature shows limit

src/v2/Apps/Conversation/Components/Conversation.tsx
The type of this PR is: FIX
This PR solves [NX-3189](https://artsyproduct.atlassian.net/browse/NX-3189)
Refactored Banner as a separate functional component in order to avoid it affecting the Edition Set modal.
https://user-images.githubusercontent.com/17580625/177367870-5c4a1180-4948-4d09-aaa1-58fbf9633f6d.mov
=> fix(NX-3189): refactor banner so the state doesn't affect Edition set modal

src/v2/Apps/Onboarding/Components/OnboardingOrderedSet.tsx, src/v2/Apps/Onboarding/Components/OnboardingSearchResults.tsx, src/v2/Apps/Onboarding/Views/OnboardingFollowArtists.tsx, src/v2/Apps/Onboarding/__tests__/config.jest.ts, src/v2/Apps/Onboarding/config.ts, src/v2/Apps/Onboarding/useOnboardingContext.tsx, src/v2/__generated__/OnboardingOrderedSetQuery.graphql.ts, src/v2/__generated__/OnboardingOrderedSet_orderedSet.graphql.ts, src/v2/__generated__/OnboardingSearchResultsQuery.graphql.ts, src/v2/__generated__/OnboardingSearchResults_viewer.graphql.ts
The type of this PR is: _feat_
This PR solves [GRO-1096]
The intention of this code is to build out the Follow Artists rewards screen that occurs at the end of the Onboarding workflow. Currently, an `orderedSet` is being used to backfill featured artists and a search filter will be implemented. 
Acceptance criteria:
[GRO-1096]: https://artsyproduct.atlassian.net/browse/GRO-1096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(onboarding)[WIP]: build screen for follow artists reward path

src/v2/Components/Artwork/Details.tsx, src/v2/Components/Artwork/__tests__/Details.jest.tsx, src/v2/Utils/__tests__/getSaleOrLotTimerInfo.jest.ts, src/v2/Utils/getSaleOrLotTimerInfo.ts
This PR solves [FX-4068]
This pr updates the copy of the popcorn bidding timers that we show on lots for the close time.
Note that when the lots close in > 24hrs we get the whole string value from metaphysics from [here](https://github.com/artsy/metaphysics/blob/main/src/lib/date.ts#L305)
When the lots close in < 24hrs we format the date on the clients.
Metaphysics PR for > 24hrs https://github.com/artsy/metaphysics/pull/4220
|>24hrs|<24hrs|
|---|---|
|![Screenshot 2022-07-08 at 11 02 53](https://user-images.githubusercontent.com/21178754/177959507-f8c761ff-51c6-4339-b94a-1d746d7ce844.png)|![Screenshot 2022-07-08 at 11 02 21](https://user-images.githubusercontent.com/21178754/177959527-9b7cc1f8-c173-4ce5-96d6-a2bdee7bf930.png)|
[FX-4068]: …
=> fix: timer copy changes auctions

src/v2/Components/NavBar/menuData.ts
This PR solves [FX-4083]
Just a [small copy change](https://artsy.slack.com/archives/C9SATFLUU/p1657209665949729) for the **Artist** dropdown menu: `Our Top Auction Lots` → `Top Auction Lots`
|Desktop|Mobile|
|---|---|
|<img width="1195" alt="Screen Shot 2022-07-11 at 3 49 00 AM" src="https://user-images.githubusercontent.com/140521/178215111-08232b24-67ec-485b-b8d7-73fce4ad376b.png">|<img width="443" alt="Screen Shot 2022-07-11 at 3 49 28 AM" src="https://user-images.githubusercontent.com/140521/178215120-35c764a2-3dca-4549-92c8-dc6b88e61d06.png">|
[FX-4083]: https://artsyproduct.atlassian.net/browse/FX-4083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update copy in Artist dropdown

src/v2/Apps/Order/Components/TwoColumnLayout.tsx, src/v2/Apps/Order/Routes/Status/index.tsx
This PR removes a small gap between sections on the mobile
Before
After
=> fix: mobile layout on the order status page

src/v2/Apps/Onboarding/Components/OnboardingOrderedSet.tsx, src/v2/Apps/Onboarding/Components/OnboardingSearchResults.tsx, src/v2/Apps/Onboarding/Components/OnboardingSplitLayout.tsx, src/v2/Apps/Onboarding/Views/OnboardingFollowArtists.tsx, src/v2/Apps/Onboarding/Views/OnboardingFollowGalleries.tsx, src/v2/__generated__/OnboardingOrderedSetQuery.graphql.ts, src/v2/__generated__/OnboardingOrderedSet_orderedSet.graphql.ts, src/v2/__generated__/OnboardingSearchResultsQuery.graphql.ts, src/v2/__generated__/OnboardingSearchResults_viewer.graphql.ts
The type of this PR is: _feat_
This PR solves [GRO-1100]
The intention of this code is to build out the Follow Galleries rewards screen that occurs at the end of the Onboarding workflow. Currently, an `orderedSet` is being used to backfill featured partner profiles and a search filter will be implemented. 
Acceptance criteria:
[GRO-1100]: https://artsyproduct.atlassian.net/browse/GRO-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(onboarding): build screen for follow galleries path

src/v2/Apps/ArtistSeries/Components/ArtistSeriesArtworksFilter.tsx, src/v2/Apps/Auction/Components/AuctionArtworkFilter.tsx, src/v2/Apps/Collect/Routes/Collect/index.tsx, src/v2/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx, src/v2/Apps/Fair/Routes/FairArtworks.tsx, src/v2/Apps/Gene/Components/GeneArtworkFilter.tsx, src/v2/Apps/Search/Routes/SearchResultsArtworks.tsx, src/v2/Apps/Show/Components/ShowArtworks.tsx, src/v2/Apps/Tag/Components/TagArtworkFilter.tsx, src/v2/Components/SavedSearchAlert/Utils/__tests__/extractPills.jest.ts, src/v2/Components/SavedSearchAlert/Utils/extractPills.ts
This PR solves [FX-4025]
Review app: https://pills-for-other-grids.artsy.net/
Investigation and faced problems: [Spike Document](https://www.notion.so/artsy/Spike-Add-saved-search-alerts-to-other-artwork-grids-a57a04ac02654861915f6f7d3f2edb4a)
* [Auctions](https://pills-for-other-grids.artsy.net/auction/artsy-x-seoul-auction-contemporary-icons)
* [Show](https://pills-for-other-grids.artsy.net/show/charlie-smith-london-papyrophilia)
* [Tag](https://pills-for-other-grids.artsy.net/tag/cowboy)
* [Artist Series](https://pills-for-other-grids.artsy.net/artist-series/hiroshi-sugimoto-seascapes)
* [Gene](https://pills-for-other-grids.artsy.net/gene/ukiyo-e)
* [Fair](https://pills-for-other-grids.artsy.net/fair/art-cologne-2020/artworks)
* …
=> feat(FX-4025): Add active filter pills to other (non-artist) artwork grids

src/v2/Apps/NewForYou/NewForYouApp.tsx, src/v2/Apps/NewForYou/__tests__/NewForYouApp.jest.tsx
The type of this PR is: **BUG**
This PR solves [GRO-1129]
Add query param to url so user is redirected back to `/new-for-you` after logging in.
[GRO-1129]: https://artsyproduct.atlassian.net/browse/GRO-1129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bug(NewForYou): add redirect after login

src/v2/Apps/Order/Components/SetPaymentByStripeIntent.tsx, src/v2/Apps/Order/Routes/Payment/index.tsx, src/v2/Components/BankDebitForm/BankDebitForm.tsx
This PR solves [TX-241]
This PR provides the ability to save/not save a stripe-linked bank account during the checkout flow via a checkbox and explanation tooltip. 
https://user-images.githubusercontent.com/42584148/178008582-b53c30d5-874e-4a0d-9acb-a721f0967c73.mov
[TX-241]: https://artsyproduct.atlassian.net/browse/TX-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feat]: AlicanAkyuz/TX-241/Buyer can save bank account during checkout

src/v2/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx, src/v2/Apps/NewForYou/NewForYouApp.tsx, src/v2/Apps/NewForYou/__tests__/NewForYouApp.jest.tsx, src/v2/Apps/NewForYou/newForYouRoutes.tsx, src/v2/__generated__/NewForYouApp_test_Query.graphql.ts, src/v2/__generated__/NewForYouApp_viewer.graphql.ts, src/v2/__generated__/NewForYouArtworksGrid_viewer.graphql.ts, src/v2/__generated__/newForYouRoutes_TopLevelQuery.graphql.ts
This PR is well described over on https://github.com/artsy/force/pull/10482 but the tl;dr is that I've updated the `/new-for-you` page so that you can pass `first`, `includeBackfill` and `version` to override defaults.
/cc @artsy/grow-devs @joeyAghion @kathytafel
=> Support URL params on New For You page

src/v2/Components/Onboarding/Components/OnboardingGene.tsx, src/v2/Components/Onboarding/Components/__tests__/OnboardingGene.jest.tsx
The type of this PR is: _fix_
The intention of this PR is to add a zero state to the artwork grid views at the end of the Onboarding flow.
=> fix(onboarding): add zero state to artwork gene masonry grid 

src/lib/passport/lib/app/analytics.js, src/lib/passport/lib/app/index.js, src/lib/passport/test/app/analytics.jest.js
Reverts artsy/force#10525. 
It looks like the options object gets mutated on init; see [this convo](https://artsy.slack.com/archives/C01ADJNCS5D/p1657904394813909) for more info.
=> Revert "chore(passport): Delete unused passport analytics code"

src/v2/Components/ArtworkFilter/ArtworkFilterContext.tsx, src/v2/Components/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx, src/v2/Components/ArtworkFilter/Utils/__tests__/getSelectedFiltersCounts.jest.ts
* [Show Artworks](https://custom-default-sort.artsy.net/show/ko-austere-imaginary)
* [Auction artworks](https://custom-default-sort.artsy.net/auction/artsy-x-thurgood-marshall-college-fund-spring-selections)
For example, when A/B test is launched and the default sort value should be different from `-decayed_merch` ([FX-3972](https://artsyproduct.atlassian.net/browse/FX-3972))
| Before  | After |
| <img width="344" alt="before-1" src="https://user-images.githubusercontent.com/3513494/176003002-71622180-163e-4e8a-94f3-ecc42bce9abf.png"> | <img width="344" alt="after-1" src="https://user-images.githubusercontent.com/3513494/176003120-c572818a-230b-43ad-837e-bd3f9442edd5.png"> |
Correctly reset sort value, when custom …
=> chore: skip counting custom default sort value

src/v2/Components/Search/SearchBar.tsx, src/v2/System/i18n/ClassI18n.tsx
Simplifying the way we use i18n-next on class components.
=> simplifying

src/v2/Apps/RSS/queries/RssArticlesQuery.ts, src/v2/Apps/RSS/rssServerApp.tsx, src/v2/Apps/RSS/templates/news.ejs, src/v2/__generated__/RssArticlesQuery.graphql.ts, src/v2/__generated__/RssArticlesQuery_artwork.graphql.ts, src/v2/__generated__/RssArticlesQuery_image.graphql.ts
Over on https://github.com/artsy/force/pull/10491/ we migrated the RSS code but dropped the feed at `/rss/news` - this was a mistake. It's true that we no longer publish news but this is the official editorial RSS feed that powers all sorts of things including the iOS widget's editorial version. Apple News is another customer. It's poorly named but I'm not touching that here - just trying to restore what was broken.
Anyway, all I did here was copy what I saw for the partner updates feed but then change the channel id over to the editorial one. Then I created a new feed template and copy/pasted from that other PR so that the title/description/etc looked as it did before the deletion.
https://artsyproduct.atlassian.net/browse/GRO-1145
=> fix: Restore the news rss feed GRO-1145

src/v2/Apps/Components/AppShell.tsx, src/v2/Apps/Components/constants.ts
The type of this PR is: **BUG**
This PR solves [GRO-1037]
This bug likely effected only very small screens.
Upon scrolling to the very bottom of the page sticky messages currently overlap the app footer, which is not the desired behavior. This change forces message banners to instead slide beneath the footer. 
- Add footer value to `Z` constant
- Apply constant value to `Footer` wrapper in `AppShell`
- Magic
[GRO-1037]: https://artsyproduct.atlassian.net/browse/GRO-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bug(Footer): add z-index to footer

src/v2/Components/NavBar/Menus/NavBarUserMenu.tsx
This PR solves [CX-2662]
- This PR adds `My Collection` item to NavBarUserMenu
- Hidden behind `my-collection-web` user flag
https://user-images.githubusercontent.com/18648835/179798863-8bdb36ed-3802-4e10-ac04-cab4edd8348e.mov
[CX-2662]: https://artsyproduct.atlassian.net/browse/CX-2662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-2662): Add my collection menu item to NavBarUserMenu

src/v2/Apps/Order/Routes/Payment/PaymentContent.tsx, src/v2/Apps/Order/Routes/__tests__/Payment.jest.tsx, src/v2/Components/BankDebitForm/BankDebitForm.tsx, src/v2/Components/BankDebitForm/__tests__/BankDebitForm.jest.tsx
This PR solves [TX-443](https://artsyproduct.atlassian.net/browse/TX-443)
This PR logs the selected payment method when the payment component mounts. It logs it the same as any time a user selects a payment method.
It also removes some events that were never fully defined. These were intended to be a part of [TX-227] but we need to invest more time to fully understand our options there. My intent is that we can revert or re-implement parts of what we remove in 750255d79a815f0d7e664bd1ebca7bdb46dfaed8 to complete this.
[TX-227]: https://artsyproduct.atlassian.net/browse/TX-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: track first payment selected as we track others

src/v2/Apps/RSS/queries/RssArticlesQuery.ts, src/v2/Apps/RSS/templates/article.ejs, src/v2/__generated__/RssArticlesQuery.graphql.ts
It took me a bit to figure out but we missed the enclosure tag for thumbnail images:
https://github.com/artsy/force/pull/10491/files?show-deleted-files=true&show-viewed-files=true&file-filters%5B%5D=#diff-3d2a4663bd9f40b2dc26e533d8c9fab2ead98a14f0b5cf4de401c563ede934aaL30
So this PR adds that back. Once that's fixed then the iOS widget should go back to working.
https://artsyproduct.atlassian.net/browse/GRO-1145
=> fix: Add back the enclosure for thumbnail images GRO-1145

src/Components/Onboarding/Components/OnboardingGene.tsx, src/__generated__/OnboardingGeneQuery.graphql.ts, src/__generated__/OnboardingGene_Test_Query.graphql.ts, src/__generated__/OnboardingGene_gene.graphql.ts
The type of this PR is: _fix_
This PR solves [GRO-1163]
The goal of this PR is to address the concerns surfaced during Onboarding QA here: https://www.notion.so/artsy/for-curated-collections-the-modal-doesn-t-match-the-collection-632acc9da57f4eb5983dbaa5e4611462
The intention rather than to just pull the first 100 artworks from gene collections for the artwork collection reward screen at the end of the onboarding flow, to instead filter the query to match the artworks presented on the gene's page. This code solves for the `trove`, `artists on the rise` and `top auction lots` gene collections. 
An example (artists on the rise):  …
=> (fix)(onboarding): edit query filter to match gene artwork on gene page

src/Apps/Settings/SettingsApp.tsx
This PR solves [CX-2658]
This PR adds My Collection tab inside SettingsApp when `my-collection-web` feature flag is enabled.
Original PR: [my-collection-web](https://github.com/artsy/force/pull/10580)
[CX-2658]: https://artsyproduct.atlassian.net/browse/CX-2658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add My Collection to Settings tabs

.secrets.baseline
detect-secrets [v1.3.0](https://github.com/Yelp/detect-secrets/releases/tag/v1.3.0) has been released last Friday. CI has automatically picked up the new version and [is currently failing](https://app.circleci.com/pipelines/github/artsy/force/34427/workflows/fa9e10a7-1851-493c-aec0-733c6e7040ae/jobs/265361). The failure seems to be a result of some changes in the new version, specifically around "_Base64 High Entropy String_" plugin. The new version seems to be picking up a lot of new secret like strings that match that _Type_.
To resolve this, I've regenerated the _baseline_ from scratch using the latest version of the tool. The [one notable change](https://github.com/artsy/force/pull/10597/files#diff-d8447df0cd384602c76086081f13f27ad0b45902297c42da35a6fc …
=> chore: regenerate secrets baseline for version 1.3.0

src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/useCreateSettingsBackupSecondFactorsMutation.ts
This PR solves: [PLATFORM-4340](https://artsyproduct.atlassian.net/browse/PLATFORM-4340)
This updates `useCreateSettingsBackupSecondFactorsMutation.ts` to no longer default to an empty object as a password is now required by the schema. [MP pr here](https://github.com/artsy/metaphysics/pull/4247).
This would resolve the _type-error_ observed in https://github.com/artsy/force/pull/10590. Failed job run [here](https://app.circleci.com/pipelines/github/artsy/force/34427/workflows/fa9e10a7-1851-493c-aec0-733c6e7040ae/jobs/265378).
=> fix: password required in CreateBackupSecondFactorsInput

src/Apps/RSS/templates/article.ejs
I swear I tested this folks but clearly something went wrong - without proper quotes this is not valid XML and that's been breaking the Editorial version of the iOS widget. 
=> Fix malformed RSS tag

src/Apps/Conversation/Components/OrderUpdate.tsx
The type of this PR is: **bugfix**
#10565  contained an incorrect v2 color (causing yellow100 to render as copper100) and the wrong icon for an order processing approval event in a conversation. This is a #minor pr to fix that.
[slack conversation where we discovered this 🔒](https://artsy.slack.com/archives/C02JHHHKP5K/p1658329405084939?thread_ts=1658270238.787909&cid=C02JHHHKP5K)
=> fix: correct order processing approval event color and icon type

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx, src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/SizeFilter.tsx, src/Apps/Artist/Utils/allowedAuctionResultFilters.ts
This PR solves [FX-4039]
Related PRs: artsy/force#10593, artsy/force#10572
Review app: https://auction-results-metric.artsy.net
Demo link: https://auction-results-metric.artsy.net/artist/salman-toor/auction-results
https://user-images.githubusercontent.com/3513494/180767621-b04e69f6-ad99-407b-862e-ddc9822963bc.mp4
[FX-4039]: https://artsyproduct.atlassian.net/browse/FX-4039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4039): expand auto-selection of user's preferred measurement system for size filter on auction results grid

src/Components/Onboarding/Components/OnboardingProgress.tsx
This PR solves [GRO-1160]
This is a small fix to the margins between the close button and the progress bar. 
[GRO-1160]: https://artsyproduct.atlassian.net/browse/GRO-1160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (onboarding): increase padding between progress bar and close button

src/Components/Onboarding/Components/OnboardingSteps.tsx, src/Components/Onboarding/Views/OnboardingThankYou.tsx, src/Components/Onboarding/config.ts
The type of this PR is: _feat_
This PR solves [GRO-1162]
This PR is a result of the tickets that address Onboarding Phase 1 QA. There was discussion about adding closure to the onboarding flow, right now I'm unsure of where exactly the `OnboardingThankYou` screen is supposed to go tbh. There was chatter about it going after the `Follow` screens so I included a boilerplate component there for now. Moving it around in the flow is simple because all views and decision views exist in an array.
Also, this PR is a WIP until design provides mocks.
To do:
[GRO-1162]: https://artsyproduct.atlassian.net/browse/GRO-1162?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> feat(onboarding): include thank you screen after follow view

src/Apps/Home/Hooks/useOnboarding.tsx, src/Apps/Onboarding/OnboardingApp.tsx, src/Components/Onboarding/Components/OnboardingGene.tsx, src/Components/Onboarding/Hooks/useOnboarding.tsx, src/Components/Onboarding/Hooks/useOnboardingContext.tsx, src/Components/Onboarding/Views/OnboardingWelcome.tsx, src/Components/Onboarding/__tests__/config.jest.ts, src/Components/Onboarding/config.ts
This PR solves [GRO-1168]
Part 1 of a two PR body of work. This PR updates the onboarding flow's context with a new `onComplete` function that can be called when we're certain onboarding has completed. When invoked, it calls the `updateUserProfile` with a `completedOnboarding: true` value. 
Also renames `onDone` to `onClose`.  
Follow-up PR will wire up to the final thank you screen, to be invoked. 
[GRO-1168]: https://artsyproduct.atlassian.net/browse/GRO-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(onboarding): Add new onComplete handler to context, invoking the updateUserProfile mutation

src/Components/Onboarding/Components/OnboardingGene.tsx, src/Components/Onboarding/Views/OnboardingThankYou.tsx
This dispatches the `onboarding_complete` event to the user model in gravity, called when a user hits the thank you page. 
=> feat(onboarding): Call onComplete on complete

src/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx, src/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx, src/Apps/Artist/Components/ArtistInsights/ArtistInsightPills.tsx, src/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlights.tsx, src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistCareerHighlights.jest.tsx, src/__generated__/ArtistCareerHighlightsQuery.graphql.ts, src/__generated__/ArtistCareerHighlights_Test_Query.graphql.ts, src/__generated__/ArtistCareerHighlights_artist.graphql.ts
This PR restores the CV link using the follow logic:
* if the artist has an editorial bio, then run the link under that text
* if the artist has a partner supplied bio, then run the link under that text
* if the artist has no bio at all then run the link where the editorial bio would normally go
Here's some pictures of those various states:
I'm going to get some missing tests around this - hang tight @TMcMeans!! 🙏 
https://artsyproduct.atlassian.net/browse/1150
=> fix: Restore artist CV link 1150

docs/i18n.md
Google drive presentation link was incorrect
=> docs: Fix presentation link

src/Apps/MeetTheSpecialists/Routes/MeetTheSpecialistsIndex.tsx, src/System/i18n/locales/en-US/translation.json
~You know me, I just really like a good `quick win` PR on a Friday before vacay.~ 😎 🌴 🍹 
I realized that this PR would be a good chance to try out the i18n work that @lidimayra and friends have put so much time into and I think it worked pretty well! I first made the changes to the page that the ticket called for and then I took a step back and extracted certain strings to the en-EU file. Here's how I thought about the page:
<details>
<summary>meet the specialists: i18n pass</summary>
</details>
In that screenshot I have labels various bits of text with the i18n keys I used to populate the page. I skipped the sections in black with the following reasoning:
* those questions at the top seem pretty static and ripe for extraction but they contain HTML - how should i handle that?
* the …
=> feat: Update staff info on advisory page 1164

src/Apps/Redirects/__tests__/redirectsServerRoutes.jest.ts, src/Apps/Redirects/redirectsServerRoutes.tsx
This PR solves [PX-5140]
It seems that the redirection was broken with the latest changes. The reason for this (and why the tests did not pick this up) is that the tests were passing in the valid `req.route.path` which doesn't actually happen in the real world. When passed an array like is done [here](https://github.com/artsy/force/blob/c9b7c872408e743614419fd0703874b4cee56357/src/Apps/Redirects/redirectsServerRoutes.tsx#L162-L176), the specific path which triggers the function from being run is lost and instead the entire array of routes are passed through to the function, e.g.
```
/:id,/:id/overview,/:id/about,/:id/shows,/:id/works,/:id/collection,/:id/shop,/:id/artists,/:id/artist/:artistId,/:id/articles,/:id/contact
```
This breaks all logic that …
=> fix: PX-5140 - artist url redirect

src/Apps/Artist/Components/ArtistInsights/ArtistInsightAchievements.tsx, src/Apps/Artist/Components/ArtistInsights/__tests__/ArtistInsightAchievements.jest.tsx
This PR solves [GRO-1179]
This reinstates tracking on the "see more" button on the artist insights module which was accidentally removed when it was rebuilt. 
[GRO-1179]: https://artsyproduct.atlassian.net/browse/GRO-1179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(artist-insights): Add missing analytics calls

src/Apps/Auction/Components/AuctionWorksByFollowedArtistsRail.tsx, src/Apps/Auction/Components/__tests__/AuctionWorksByFollowedArtistsRail.jest.tsx, src/Components/Artwork/Details.tsx, src/Components/ArtworkGrid/ArtworkGridContext.tsx
This PR solves [FX-4067]
Review app: https://countdown-timer.artsy.net/
| <img width="470" alt="before" src="https://user-images.githubusercontent.com/3513494/181456297-67b77800-6c0f-4f7d-9b0f-f7d7fa3865f1.png"> | <img width="470" alt="after" src="https://user-images.githubusercontent.com/3513494/181456334-915794ad-8549-46a7-a696-04da021cf7d7.png"> |
| Closes on | Closes in | Closed |
| ------------- | ------------- | ------------- |
| <img width="470" alt="after" src="https://user-images.githubusercontent.com/3513494/181457796-eb9eaf15-b4c6-40aa-9670-965ce4d5d0cc.png"> | <img width="458" alt="after-2" src="https://user-images.githubusercontent.com/3513494/181457738-98a70c73-4b63-46bd-a468-800c7224b4d7 …
=> feat(FX-4067): add countdown timer to lot card in "Works By Artists You Follow" rail on Sail/Auction page

src/Apps/Conversation/Components/OrderUpdate.tsx, src/Apps/Conversation/Components/__tests__/OrderUpdate.jest.tsx
resolves [TX-479]
This PR updates the order update for a `processing_approval` state change to the latest figma copy, changing "Payment pending" for "Payment processing"
[TX-479]: https://artsyproduct.atlassian.net/browse/TX-479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update copy per spec

.circleci/config.yml, scripts/jest.sh
Related https://github.com/artsy/force/pull/10668 
Jest 28 comes with [a new `--shard` argument](https://jestjs.io/docs/next/cli#--shard) which allows one to split the tests across processes all run in parallel. 
Test speeds went from 6+ minutes per run [down to ~2m](https://app.circleci.com/pipelines/github/artsy/force/34836/workflows/ba6af729-8d73-4696-ae37-b00a0445ff4b/jobs/267865/parallel-runs/0?filterBy=ALL), so a 2/3rds reduction in time. If we wanted to decrease it further we could increase the `parallelism` value in our circle config.
The only question here is: Will this in any way constrain other jobs being executed on CircleCI outside of Force?
=> ci(test): Speed up tests on CI via parallelism 

src/Components/Artwork/GridItem.tsx
This PR solves [CX-2693]
- Prevents My Collection artwork click scrolling by not passing any URL.
- Removes `cursor: not-allowed;` artwork link.
[CX-2693]: https://artsyproduct.atlassian.net/browse/CX-2693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Prevent My Collection artwork click scrolling and remove cursor: not-allowed style

src/Apps/Settings/Routes/MyCollection/Components/MyCollectionAppDownload.tsx
This PR solves [CX-2689]
This PR updates the aspect ratio of the image in My Collection empty state to fix it being stretched
| - | Before | After |
| -- | -- | -- |
| Mobile view | ![image](https://user-images.githubusercontent.com/20655703/182670419-f2e5fb78-04e9-4293-b45d-16601e13b96e.png) | ![image](https://user-images.githubusercontent.com/20655703/182670453-33ed002d-2b8b-4eab-81a2-4b8b3485eafa.png) |
| Desktop view | ![image](https://user-images.githubusercontent.com/20655703/182671031-326f958c-6961-4227-b500-f037607cfbe9.png) | ![image](https://user-images.githubusercontent.com/20655703/182670966-2be19ed3-b672-411d-85c4-245777c307b4.png) | 
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> fix [CX-2689]: Fix My Collection empty state stretched image

src/Apps/About2/AboutApp2.tsx, src/Apps/About2/AboutArtworksRail2.tsx, src/Apps/About2/aboutRoutes2.tsx, src/__generated__/AboutArtworksRail2Query.graphql.ts, src/__generated__/AboutArtworksRail2_viewer.graphql.ts, src/routes.tsx
This PR solves [GRO-1154]
This creates a new /about2 route, with the first pass of the new layout. Note there are no links on the subsections yet; we're still working out the designs. 
Figma: https://www.figma.com/file/nVRxXK7ChPHqMJ0NAQsDQA/CVP?node-id=138%3A1968
[GRO-1154]: https://artsyproduct.atlassian.net/browse/GRO-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(about2): Add first pass /about2

src/Components/Artwork/Metadata.tsx, src/System/Router/RouterLink.tsx
- When a RouterLink's `to` prop is passed a `null`, onClick automatically jumps to top of page. This PR fixes that.
=> fix(RouterLink): Prevent Disabled RouterLink from routing to top of page

src/Apps/Settings/Routes/MyCollection/Components/DownloadAppBadgesDark.tsx, src/Apps/Settings/Routes/MyCollection/Components/MyCollectionAppDownload.tsx
This PR solves [CX-2714]
This PR updates the download badges logic inside My Collection empty state to show the badge according to the device (Play Store for Androids and App Store for iPhones)
| iPhone | Android |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/20655703/182819860-361921f4-5402-4951-b15d-5d4f576c3f69.png) | ![image](https://user-images.githubusercontent.com/20655703/182819893-af4f85d5-be23-41b7-b7ae-1b41f3a0f981.png) |
[CX-2714]: https://artsyproduct.atlassian.net/browse/CX-2714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> fix [CX-2714]: Update My Collection download app badges logic

src/Apps/Home/Components/HomeWorksForYouTabBar.tsx, src/Apps/Home/__tests__/HomeWorksForYouTabBar.jest.tsx, src/Apps/NewForYou/NewForYouApp.tsx, src/Apps/NewForYou/__tests__/NewForYouApp.jest.tsx
This PR solves [GRO-1190]
Just a tiny copy change
`New Works For You` -> `New Works for You`
[GRO-1190]: https://artsyproduct.atlassian.net/browse/GRO-1190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(GRO-1190): change copy of new works for you

src/Components/NavBar/NavBarPrimaryLogo.tsx
This PR solves [GRO-1194]
As a number of people have flagged this as (seemingly) a bug, this removes the blue focus state on the logo in the navbar. If we can figure out a way to make the behavior feel a little more solid then lets give it a shot (as I assume this was done for a specific reason). 
[GRO-1194]: https://artsyproduct.atlassian.net/browse/GRO-1194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(navbar): Remove focus state on logo in navbar

.gitignore, pull_request_template.md
This adds the `.swc` output folder to `.gitignore` and also updates our PR template to include all of the categories from Semantic Commit
=> chore(compiler): Add .swc to .gitignore

src/Apps/Artist/Routes/CV/Components/ArtistCVGroup.tsx, src/Apps/Artist/Routes/CV/__tests__/ArtistCVRoute.jest.tsx
Another nice and easy one - I just updated the CV page so that rather than returning `null` when no shows are returned it runs a message. Note that the test I found was not actually testing anything. 😬 I made it better and will go red if the message is not there. 👍 
https://artsyproduct.atlassian.net/browse/GRO-1177
=> feat: Add empty state CV page GRO-1177

package.json, src/Components/Onboarding/Hooks/useOnboardingTracking.tsx, yarn.lock
This PR solves [GRO-1153]
The goal of this PR is to bundle up all the analytics tracking events defined in this spreadsheet here: https://docs.google.com/spreadsheets/d/12wj1rt-j5SguboPJMuaM1GqJD-5B5u5piipw8MQ5Zuk/edit?pli=1#gid=275928850 
All analytics events are defined in a hook file and ready to be fired whenever the user completes specific tasks in the onboarding flow (as noted by the comments).
Will add a separate PR for wiring up the analytics calls in the Onboarding app and tests. 
[GRO-1153]: https://artsyproduct.atlassian.net/browse/GRO-1153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
=> feat(onboarding): define analytics tracking for onboarding user events

.circleci/config.yml, scripts/clean.sh, webpack/webpackEnv.js
Due to a strange issue that was spotted by @pam-, this updates our SWC compiler settings to be opt-in via the `EXPERIMENTAL_SWC_COMPILER_ENABLED` env var, versus on by default. We need to test this out a bit more before launching it more widely to the team.  
To repo issue: 
- set `EXPERIMENTAL_SWC_COMPILER_ENABLED=true` in `.env` 
- `yarn clean && yarn start`
- Navigate to `/artist/andy-warhol` and see something along the lines of:  
```sh
Invariant Violation: loadable: cannot find Components-ArtistNotableWorksRail in stats
```
Perhaps it's not properly compiling our  [dynamic import statements](https://github.com/artsy/force/blob/main/src/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx#L16-L22)? Note that this only happens when visiting a page with …
=> chore(webpack): Opt-in to SWC compiler, vs on by default

src/Apps/Order/Components/BankAccountPicker.tsx, src/Apps/Order/Components/SaveAndContinueButton.tsx, src/Components/BankDebitForm/BankDebitForm.tsx
Currently our Integrity tests are [failing](https://app.circleci.com/pipelines/github/artsy/integrity/13620/workflows/884ea3e4-d687-4d16-845d-68bfd3a0890b/jobs/67584) because it looks for specific test Ids on button elements. This PR attempts to fix this issue by moving test IDs from the wrapper component `SaveAndCotinuebutton` to `Button` element directly.
=> fix(): Alican/Provide data-test id to button element directly instead of wrapper

docs/i18n.md, src/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx, src/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx, src/Apps/Artist/Routes/Overview/Components/ArtistCareerHighlights.tsx, src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistCareerHighlights.jest.tsx, src/System/i18n/locales/en-US/translation.json
Returning to the topic of artist CV links and https://github.com/artsy/force/pull/10631. After that PR was merged I realized that this would have been a good time to extract a string into the locale file so I'm opening a PR to do this.
I extracted the string and used the hook/helper to update the two call sites in the implementation code. Then I went back to the testing code and replaced the const with the actual string itself.
What do folks think about this - is this the right way to do this?
=> chore: Extract string for cv link text

src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx, src/Components/Artwork/GridItem.tsx, src/Components/Artwork/__tests__/GridItem.jest.js, src/Components/Artwork/__tests__/GridItem.jest.tsx, src/DevTools/setupTestWrapper.tsx, src/__generated__/GridItem_Test_Query.graphql.ts
This PR solves [CX-2713]
- Navigate the user to my collection artwork screen when clicking on a my collection artwork with phase 2 of MyC ff enabled.
- Add support for props injection inside `renderWithRelay`. I only have the prop set as an object now since I didn't manage to get typescript React.ComponentProps to work, it would be great to visit that in the future. 
| For MyC artworks | For standard artworks |
| --- | --- |
| https://user-images.githubusercontent.com/11945712/184091970-353703b7-a115-432d-8a84-ec8a4e7e45e9.mov  | https://user-images.githubusercontent.com/11945712/184091920-a62805a5-2ec1-4376-9b55-9db28b0fe61e.mov |
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> feat(CX-2713): navigate to my collection artworks on artwork press

scripts/setup.sh
The type of this PR is: **enhancement**
I noticed when setting up Artsy services on a loaner recently that Force didn't include Redis in its setup script despite requiring it. Adding it here to make that explicit!
=> chore: add redis to installed services

.circleci/config.yml
Reverts artsy/force#10729
Possible that this is breaking our builds? https://artsy.slack.com/archives/C2TQ4PT8R/p1660222140815259
=> Revert "chore(deps): update cypress/base docker tag to v16.14.2"

cypress/integration/myCollection.spec.ts, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkMeta.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebarMetadata.jest.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/index.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx, src/Apps/MyCollection/myCollectionRoutes.tsx, src/__generated__/MyCollectionArtworkMeta_artwork.graphql.ts, src/__generated__/MyCollectionArtworkSidebarMetadataTestQuery.graphql.ts, src/__generated__/MyCollectionArtworkSidebarMetadata_artwork.graphql.ts, src/__generated__/MyCollectionArtworkSidebar_artwork.graphql.ts, src/__generated__/MyCollectionArtwork_artwork.graphql.ts, src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
This PR solves [CX-2708]
This PR adds the overview section (sidebar) in My Collection artwork details page
|Mobile| Desktop|
|--|--|
| ![image](https://user-images.githubusercontent.com/20655703/184369414-9a3d42d7-8704-4fb2-8678-f2e92255e454.png) |  ![image](https://user-images.githubusercontent.com/20655703/184369451-fd49d43c-6eed-41f2-a2f8-da9a290db457.png) |
[CX-2708]: https://artsyproduct.atlassian.net/browse/CX-2708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-2708): Add My Collection Artwork details overview  

src/Components/Onboarding/Components/OnboardingGene.tsx, src/Components/Onboarding/Views/OnboardingThankYou.tsx
The type of this PR is:  fix
This PR solves issues surfaced from the most recent Onboarding QA here: https://www.notion.so/artsy/Onboarding-Web-QA-c5f83b5a7b004cce9694ae4c4fb97771
This PR adds more time delay for users to read the thank you page copy text as well as removing an unnecessary onMouseUp handler on the artworkgrid items that cause the onboarding modal to close when liking an artwork. 
=> fix(onboarding): thank you page fix & small changes

src/Components/Onboarding/Components/OnboardingFigure.tsx, src/Components/Onboarding/Components/OnboardingQuestionPanel.tsx
This fixes the issue where the next button and the image would be squished depending on the responsive size: 
=> fix(onboarding): Fix image and next button size

src/Apps/Partners/Components/PartnersLocationAutocomplete.tsx, src/Apps/Partners/Utils/__tests__/filterUtils.jest.ts, src/Apps/Partners/Utils/filterUtils.ts
Jira: [FX-4161](https://artsyproduct.atlassian.net/browse/FX-4161)
The /galleries page currently has a location filter to narrow down displayed galleries.
The filter is backed by lists of cities generated by Gravity and exposed via Metaphysics. The filtering currently takes place client-side using a simple string lowercase / include mechanism.
This is not inclusive of cities whose names contain accented characters. When searching for Bogotá or Périgueux, if you replace accented characters when unaccented variation, the expected results do not show up. Short of switching to a completely different back-end implementation, I've opted for simpler client-side patch here by further normalizing the characters.
The use of `String.normalize` seems widely supported in browsers today: …
=> feat: further normalize to improve gallery location filter matches 

src/Apps/Article/ArticleApp.tsx, src/Apps/Authentication/Utils/__tests__/helpers.jest.ts, src/Apps/Authentication/Utils/helpers.ts, src/Apps/Authentication/Utils/useAuthForm.ts, src/Apps/Components/AppShell.tsx, src/Apps/Home/HomeApp.tsx, src/Components/Authentication/Types.ts, src/Components/Onboarding/Components/OnboardingGene.tsx, src/System/Router/__tests__/buildClientApp.jest.tsx, src/Utils/Hooks/useOnboardingModal.ts, src/Utils/Hooks/useScrollToOpenArtistAuthModal.ts
This PR solves [GRO-1191]
(Merging this PR will launch the new onboarding flow!) 
This PR fully integrates onboarding globally into the app by checking against the users intent before showing. Note that we exclude all commercial intents in this onboarding behavior, including: 
```tsx
const COMMERCIAL_AUTH_INTENTS = [
Intent.bid,
Intent.buyNow,
Intent.createAlert,
Intent.inquire,
Intent.makeOffer,
Intent.registerToBid,
]
```
Leveraged the `useOnboarding` code that @dzucconi added to the HomeApp by moving the hook to `Utils/Hooks`, adding it to the `AppShell` and then listening for a `?onboarding=true` queryParam. 
[GRO-1191]: https://artsyproduct.atlassian.net/browse/GRO-1191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> [Do Not Merge] => feat(onboarding): Update auth flow to trigger onboarding

.circleci/config.yml, scripts/smoke_test.sh
This PR solves [WP-111]
Following the work done in https://github.com/artsy/integrity/pull/368, this parallelizes our smoke tests in Force in an effort to bring the smoke test runner down by 3min. 
[WP-111]: https://artsyproduct.atlassian.net/browse/WP-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci(smoke-tests): parallelize smoke tests on CI

.circleci/config.yml
Missed the `smoke-test-on-live-env` job
=> ci(smoke-tests): parallelize smoke tests on live env

src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
This PR solves [CX-2770]
If screen size is >= "md" - maxImageWidth is 600 (took this number from `ResponsiveImageWithMaxWidth`)
if screen size is < "md" - maxImageWidth is "100%"
https://user-images.githubusercontent.com/36167539/185410497-00a0ada5-2e70-4455-8b0f-539054f5fc92.mov
[CX-2770]: https://artsyproduct.atlassian.net/browse/CX-2770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: adjust no-image image container

.circleci/config.yml
Switch over to Artsy managed docker image for executing detect-secrets in CI.
Two reasons for this change:
1. we have control over detect-secrets releases
2. I want to remove [this workaround](https://github.com/artsy/force/blob/main/.circleci/config.yml#L217-L236) in another PR  to see if it is still necessary.
i. In case I have to revert the change ☝️. This PR change will stay in place.
=> chore: CI uses Artsy managed docker image to execute detect-secrets

.circleci/config.yml
Back in the fall of 2021, we [expanded the run command](https://github.com/artsy/force/pull/8648) to recover from '_random_' baseline mutations. This was necessary (at the time) as it was causing developer friction and failed builds in CI.
Seeing as the tool has had a couple of releases since then and some projects ([eigen](https://github.com/artsy/eigen/blob/main/scripts/secrets-check-all)) do not experience the same issue, I wanted to remove the conditional recovery logic and verify if the extra logic is still necessary.
I picked Force to try this out on because:
1. Force was one of the projects that had this issue in the past.
2. Force has a lot of daily builds so if the recovery logic is still necessary, the problem should surface (hopefully) …
=> chore: run detect-secrets in CI without recovery logic

.circleci/config.yml
Fixes parallelization on the `smoke-test-on-live-env` job
=> ci(acceptance): parallelize live acceptance tests

src/Apps/Authentication/Utils/__tests__/helpers.jest.ts, src/Apps/Authentication/Utils/helpers.ts, src/Apps/Authentication/Utils/useAuthForm.ts
This updates how we handle onboarding redirects from the static `artsy.net/signup` page, instead relying on internal auth form logic rather than setting a fallback on `AUTHENTICATION_REDIRECT_TO` (which broke a few integrity tests). 
Something that we very much need to follow up on once things have settled is refactoring the onboarding auth flow logic to have a formalized onboarding launch mechanism, versus us piggy-backing on `redirectTo` which is brittle and opaque. It works well enough right now, but the case in this PR illustrates why it won't scale: as soon as we have a signup example that _doesn't_ use `redirectTo` things break; a future dev will certainly not know why. (Filed a ticket [here](https://artsyproduct.atlassian.net/browse/GRO-1239).)
cc …
=> fix(onboarding): handle /signup case slightly better

src/Components/Onboarding/Views/OnboardingWelcome.tsx
A quick PR to remove the bit that was sending users to the homepage when they skip onboarding. This should fix some integrity failures and is a better user experience!
https://artsyproduct.atlassian.net/browse/GRO-1241
=> fix: Just dismiss modal when skipping onboarding GRO-1241

data/schema.graphql, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkArtistMarket.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkComparables.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkArtistMarket.jest.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx, src/DevTools/setupTestWrapper.tsx, src/__generated__/MyCollectionArtworkArtistMarket_Test_Query.graphql.ts, src/__generated__/MyCollectionArtworkArtistMarket_marketPriceInsights.graphql.ts, src/__generated__/MyCollectionArtwork_artwork.graphql.ts, src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
This PR solves [CX-2738]
This PR adds market insights to my collection artwork page.
[CX-2738]: https://artsyproduct.atlassian.net/browse/CX-2738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-2738): add artist market insights

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkComparables.tsx
This PR solves [CX-2802]
Return null when results (comparables) are not available
[CX-2802]: https://artsyproduct.atlassian.net/browse/CX-2802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: return null when results (comparables) are not available

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkAuctionResults.tsx
Addresses [CX-2740]
Scroll to Market Signals when opening MyC auction results.
See https://artsyproduct.atlassian.net/browse/CX-2740?focusedCommentId=50540 for more context.
[CX-2740]: https://artsyproduct.atlassian.net/browse/CX-2740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Scroll to Market Signals when opening MyC auction results

data/schema.graphql, src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx, src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilter.jest.tsx, src/Apps/Artist/Routes/WorksForSale/Utils/getWorksForSaleRouteVariables.ts
This PR solves [FX-4178]
[FX-4178]: https://artsyproduct.atlassian.net/browse/FX-4178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-4178): cleanup trending sort AB test

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkAuctionResults.tsx
This PR solves [CX-2823]
Hide auction results section title when results are not available
[CX-2823]: https://artsyproduct.atlassian.net/browse/CX-2823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Hide auction results section title when results are not available

.circleci/config.yml
This PR solves [PLATFORM-4375](https://artsyproduct.atlassian.net/browse/PLATFORM-4375)
- using a dedicated tag makes rolling out new versions of this tool easier across multiple projects
- adds inline exclusion as the new pattern is a false positive
=> chore: switch to CI specific tag for detect-secrets

.secrets.baseline, src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx, src/Apps/MyCollection/Routes/EditArtwork/__tests__/ArtworkForm.jest.tsx
This PR solves [CX-2755]
On back button press opens the confirmation modal.
| Upload web | Upload Mobile | Edit Web | Edit Mobile |
| --- | --- | --- | --- |
| <img width="1784" alt="image" src="https://user-images.githubusercontent.com/36167539/186168368-aa75ecf1-ff82-4123-ab6e-a60cac6a733a.png"> | <img width="431" alt="image" src="https://user-images.githubusercontent.com/36167539/186168483-5b171f08-b4f7-43a2-870b-943981a03f74.png"> | <img width="1792" alt="image" src="https://user-images.githubusercontent.com/36167539/186168808-9e77948a-c3fc-485e-aae0-9930d3460ce6.png"> | <img width="386" alt="image" src="https://user-images.githubusercontent.com/36167539/186168928-95cd1eda-a82b-4355-afad-9d7d1bfb1cf5.png"> |
[GRO-434]: …
=> feat: abandoned flow confirmation | uploading flow & edit flow

src/Components/Onboarding/Components/OnboardingFollows.tsx, src/Components/Onboarding/Components/OnboardingGene.tsx, src/Components/Onboarding/Hooks/useOnboardingContext.tsx
This PR solves [GRO-1242]
The goal of this PR is a bug fix to deal with the `userCompletedOnboarding()` tracking function being called multiple times at the end of the flow. My solution is to remove the tracking function call from the async user mutation and into a more stable place like a button click for artist/gallery follow views and whenever the user closes the modal for the gene views. 
artist/gallery follow view
gene view
[GRO-1242]: https://artsyproduct.atlassian.net/browse/GRO-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(onboarding): move completed onboarding tracking call to end of flow

src/Apps/About/AboutApp.tsx, src/Components/Onboarding/Components/OnboardingFigure.tsx
This italicizes the captions on about/onboarding.
=> fix(onboarding/about): Italics on captions

hokusai/staging.yml
This PR solves the issue discussed in this [thread](https://artsy.slack.com/archives/CA8SANW3W/p1661368748053139).
Reduce Staging web deployment's `preStop` sleep interval. It's currently 35 seconds, longer than Kubernetes' default termination grace period of 30 seconds, such that k8s [kills the pods before their preStop runs to completion](https://app.datadoghq.com/event/explorer?query=failedprestophook%20force-web%20env%3Astaging&cols=&messageDisplay=expanded-lg&options=&sort=DESC&from_ts=1661281020625&to_ts=1661367420625&live=true).
We observe that for Prod it is just 10 seconds which seems fine. So let's make Staging agree with Prod. There will be less noise in k8s events, and Staging k8s rollout will be faster, since k8s will wait 25 seconds less between …
=> fix: make staging preStop sleep interval agree with prod

src/Apps/Order/Components/PollAccountBalance.tsx
This PR solves [TX-619]
This PR fixes the problem that when account balance check polling receives null initially and then the actual balance value, it still allows users to proceed to the review step, even though the received value is less than the order value. 
The fix is to send bankAccountId as a string explicitly instead of defaulting to null, even when we are using setupIntentId for a newly added bank account. 
Note that this problem is surfaced only since yesterday, when we added bankAccountId to the query for already saved bank account. 
https://user-images.githubusercontent.com/42584148/186608637-45dc30d6-9809-4fca-ada7-06e60dc1423c.mov
[TX-619]: https://artsyproduct.atlassian.net/browse/TX-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …
=> fix(TX-619)- Do not send bankAccountId as null

src/Apps/Order/Routes/Payment/index.tsx, src/Components/BankDebitForm/BankDebitForm.tsx, src/Components/BankDebitForm/__tests__/BankDebitForm.jest.tsx
This PR solves [TX-618]
This PR fixes the error seen in console when 2 events are tracked: 'unknown analytics schema is used'. The reason for the problem was that the correct `ActionType` property was missing in the event bodies. 
[TX-618]: https://artsyproduct.atlassian.net/browse/TX-618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(TX-618) - analytics unknown schema errors

src/Apps/Redirects/redirectsServerRoutes.tsx
I think it's more optimal to have this shortcut redirect handler at the bottom of our middleware stack - it'll save looking up a shortcut for all the legacy partner, fair, other root-level pages.
Additionally, with https://github.com/artsy/metaphysics/pull/4342 , `shortcut` could be `null` so deserves a guard (although the `try/catch` would have swallowed that anyway). Prior to the MP PR, `shortcut` could not be `null` and MP would actually return a 500 for shortcuts that aren't found, which gets caught by the `try/catch`.
=> chore: move shortcut redirect middleware to last, and also account for new MP behavior when shortcut doesn't exist

.secrets.baseline, src/Apps/MyCollection/Routes/EditArtwork/ConfirmationModalBack.tsx, src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx, src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx
Same logic as https://github.com/artsy/force/pull/10835, just resolves the merge conflicts.
Adjust MyC artwork form "Leave Without Saving" behavior. Before it wasn't possible to navigate back from the artwork detail page once the user clicked on  "Leave Without Saving" because this would cause the browser to navigate back to the edit page again.
=> fix: Adjust My Collection artwork form Leave Without Saving behaviour

src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx
Addresses [CX-2840]
Decrease Upload Work button size on mWeb.
| --- | --- |
|<img width="407" alt="Screenshot 2022-08-26 at 12 51 58" src="https://user-images.githubusercontent.com/4691889/186888406-af55fadc-4eca-4689-84cf-7b354ba9f1fb.png"> | <img width="410" alt="Screenshot 2022-08-26 at 12 51 17" src="https://user-images.githubusercontent.com/4691889/186888358-c7a6b87b-3f79-4b77-9066-ab787aa0c897.png"> |
[CX-2840]: https://artsyproduct.atlassian.net/browse/CX-2840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Decrease "Upload Work" button size on mWeb

src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx, src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtworkDetailsForm.tsx, src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtistAutocomplete.jest.tsx, src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx
This PR solves [CX-2836]
This PR fixes the validation for the artist autocomplete by adding a `onSelect` callback. Before this change selecting an artist or clearing the input didn't revalidate the form. 
[CX-2836]: https://artsyproduct.atlassian.net/browse/CX-2836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Artist autocomplete validation

src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx, src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx
Resolves [CX-2843](https://artsyproduct.atlassian.net/browse/CX-2843) & [2844](https://artsyproduct.atlassian.net/browse/CX-2844)
This PR changes the copy of and removes the `Stepper` component from the artwork form header. This solves the following problems:
- Text was overlapping the sticky header
- Chevron Icon was visible at the end of the stepper.
=> fix: My Collection artwork form header 

src/routes.tsx
Updates our `routes.ts` file with a 404 redirect for `/oembed`
=> fix(404): `/oembed` route now 404s 

src/Apps/Authentication/Components/AuthStatic.tsx, src/Apps/Authentication/Components/__tests__/AuthStatic.jest.js, src/Apps/Authentication/Routes/SignupRoute.tsx, src/Apps/Authentication/Utils/useAuthForm.ts
This PR solves [GRO-1238]
This updates our static auth pages to only include a description when called for:
la
[GRO-1238]: https://artsyproduct.atlassian.net/browse/GRO-1238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(auth): Update description copy on login

src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx, src/Apps/Partner/PartnerApp.tsx, src/Components/ArtworkFilter/ArtworkFilters/__tests__/KeywordFilter.jest.tsx, src/Components/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilterNew.jest.tsx, src/System/Analytics/trackingMiddleware.ts, src/tests.ts
This PR solves
- https://artsyproduct.atlassian.net/browse/GRO-1242 (onboarding events firing more than once)
- https://artsyproduct.atlassian.net/browse/GRO-1210 (hyphenate gallery ownership badges) 
Fixes the first ticket by adding a debounce to our analytics middleware. This is good protection (just in general) but more specific to the ticket, we were getting three page view calls because we 
- create account and then
- redirect back to page where user was (page view)
- and trigger onboarding by updating url bar with query param (page view)
- then replace url by stripping `onboarding=true` query param (page view)
which is three routing events (push, push, replace), which all tap into our analytics middleware. So this adds some protection against that by …
=> fix(misc-tickets): Debounce pageview tracking and hypenate partner badges 

src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx, src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
This PR solves [FX-4174]
Unleash flag: [force-enable-new-activity-panel](https://unleash.artsy.net/projects/default/features/force-enable-new-activity-panel)
Review app: [activity-menu-item](https://activity-menu-item.artsy.net/)
* Add the "Activity" link to the menu below "Account"
* Render the "Activity" link only for mWeb
* Render the "Activity" link only for logged in users
* Render the "Activity" link only when feature flag is enabled
| NOT logged in user | Feature Flag is disabled | Feature Flag is enabled and logged in user |
| ------------- | ------------- | ------------- |
| <img width="344" alt="1" src="https://user-images.githubusercontent.com/3513494/186404140-8b15aaa0-3bcc-4e0b-8f92-29f221faf2a6.png"> | <img width="344" alt="2" …
=> feat(FX-4174): add Activity link to navbar menu

src/Apps/Settings/Routes/Auctions/Components/SectionContainer.tsx, src/Apps/Settings/Routes/DeleteAccount/DeleteAccountRoute.tsx, src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileAboutYou.tsx, src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileArtistsYouCollect/SettingsEditProfileArtistsYouCollect.tsx, src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileYourGalleryIntro.tsx, src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsEmailPreferences/SettingsEditSettingsEmailPreferences.tsx, src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsInformation.tsx, src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx, src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsPassword.tsx, src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactor.tsx, src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactorBackupCodes.tsx, src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/SettingsEditSettingsTwoFactorBackupCodesDialog.tsx, src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx, src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/BackupSecondFactorReminder.tsx, src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsTwoFactor/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx, src/Apps/Settings/Routes/MyCollection/MyCollectionRoute.tsx, src/Apps/Settings/Routes/Payments/Components/SettingsPaymentsMethods.tsx, src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormDesktop.tsx, src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertHeader.tsx, src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx, src/Apps/Settings/Routes/Saves/Components/SettingsSavesArtists.tsx, src/Apps/Settings/Routes/Saves/Components/SettingsSavesArtworks.tsx, src/Apps/Settings/Routes/Saves/Components/SettingsSavesCategories.tsx, src/Apps/Settings/Routes/Saves/Components/SettingsSavesProfiles.tsx, src/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddresses.tsx, src/Apps/Settings/SettingsApp.tsx
As discussed with Design, this PR changes the titles font size in the settings app from `lg` to `md` on mWeb and adjusts the vertical tabs spacing on mWeb.
**Note for reviewers:**
I've commented on the two relevant changes. Everything else is just import sorting and repeating the font size change.
| --- | --- |
| <img width="407" alt="Screenshot 2022-08-29 at 12 47 21" src="https://user-images.githubusercontent.com/4691889/187184574-ba4c4f5b-7fc1-4ccb-b1f6-b6d7d6e23685.png">| <img width="409" alt="Screenshot 2022-08-29 at 12 46 34" src="https://user-images.githubusercontent.com/4691889/187184494-1de2e012-3004-4e5c-9523-bfe8ae535e63.png">|
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
=> fix: Adjust Settings app title font size on mWeb and tab spacing

src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx, src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx
Replacing `/my-collection` with `/settings/my-collection` in redirects to avoid 404s. This is probably related to the redirect.
=> fix: Replacing my-collection routes in redirects to avoid 404s

hokusai/staging.yml
This PR solves PLATFORM-4514
Part of spike on using AWS Spot instances.
Follows https://github.com/artsy/force/pull/10846
Spot tiers were [tainted](https://github.com/artsy/substance/pull/285) with `reserved=spot:NoSchedule`. Now for any deployment we want to run on Spot, we must add a [toleration](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/). Adding that for `web` deployment.
=> feat: staging to tolerate spot instance taint

src/Components/EntityHeaders/EntityHeaderPartner.tsx, src/Components/EntityHeaders/__tests__/EntityHeaderPartner.jest.tsx
We covered the partner badge hyphenation on the /partner/id page, but never handled it on the main partners page. Fixing that here: 
=> fix(partners): Hyphenate categories on /partners page

src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
This PR solves [TX-600]
This PR shows `PROCESSING_APPROVAL` order status on the order history page 
[TX-600]: https://artsyproduct.atlassian.net/browse/TX-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: show order status on the order history page

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkArtistMarket.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkArtistMarket.jest.tsx
This PR solves [CX-2855]
This PR updates the Sell Through Rate value in the artist market in My Collection artwork details page
|before|after
|--|--|
|<img width="1301" alt="image" src="https://user-images.githubusercontent.com/20655703/187442127-2d72de9a-eca5-442f-8667-9d0293f9ad18.png"> | <img width="1323" alt="image" src="https://user-images.githubusercontent.com/20655703/187442140-12a28662-e9c1-4ac4-8ac1-acadc86c24d5.png"> |
[CX-2855]: https://artsyproduct.atlassian.net/browse/CX-2855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-2855): Update sell through rate in MyC Artist Market

src/System/Analytics/trackingMiddleware.ts
@abhitip discovered that page-to-page tracking in the SPA broke from this change, so going to revert it for now and investigate things further. 
=> fix(pageview-tracking): Revert debounce on analytics middleware

src/Apps/ArtQuiz/ArtQuizApp.tsx, src/Apps/ArtQuiz/artQuizRoutes.ts, src/routes.tsx
This PR solves [GRO-1282]
This code is to create the routing for the new Art Quiz app. @laurabeth and I have added a feature flag to prevent the app from rendering in production as well. 
[GRO-1282]: https://artsyproduct.atlassian.net/browse/GRO-1282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(art-quiz) add art quiz app routes

src/Apps/Order/Routes/Payment/PaymentContent.tsx, src/Components/BankDebitForm/BankDebitProvider.tsx
We started to see Integrity failure roughly after https://github.com/artsy/force/pull/10859. There seems to be 2 reasons:
- Stripe seemed to change their iframe implementation again, and our [iframe selector in Integrity](https://github.com/artsy/integrity/blob/0cdd676c94025bb0dd40d988031d0da71ec68e0a/cypress/utils/checkAndAddBankAccount.ts#L12) will find 2 matches.
- After https://github.com/artsy/force/pull/10859, we'll render 2 sections with `[data-test="bankTransferSection"]` (one for ACH one for SEPA). The selection then becomes ambiguous.
This PR updates the `data-test` attribute to be payment method specific so our selector in Integrity can be more reliable.
=> fix: specify payment method for each Payment Element

src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/__tests__/MyCollectionArtwork.jest.tsx
This PR hides the Insights title and tabs behind the phase4 feature flags
=> fix: hide the insights title/tab behind the feature flags

src/Apps/Order/Routes/Review/index.tsx
This PR is part of [MOPLAT-311]
We need to get a callback so that we know the order was successful. That way we can do some work after that.
https://user-images.githubusercontent.com/100233/187646529-d92b7988-ab9a-4847-b668-ad7f6c3650ac.mov
[MOPLAT-311]: https://artsyproduct.atlassian.net/browse/MOPLAT-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: sending a message to eigen on successful order

src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx, src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx, src/Components/Artwork/GridItem.tsx
Addresses [CX-2854]
This PR adds a delay to the artwork form before navigating the user to the My Collection overview. This should add enough time to make sure all new images have started being processed and can be displayed.
The reason is that when immediately navigating to the artwork detail page or the My Collection overview, images are either not present on the artwork or have not been processed and can't be displayed correctly.
The only issue that is left is `GridItem` not correctly rendering the image when getting the `square`-version, which is the first version of the image that gets processed.
[CX-2854]: https://artsyproduct.atlassian.net/browse/CX-2854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Add delay to artwork form for image processing

src/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx, src/Apps/NewForYou/NewForYouApp.tsx, src/Apps/NewForYou/newForYouRoutes.tsx, src/__generated__/NewForYouApp_viewer.graphql.ts, src/__generated__/NewForYouArtworksGrid_viewer.graphql.ts, src/__generated__/newForYouRoutes_TopLevelQuery.graphql.ts
We already support a number of params for easy testing on the /new-for-you surface including `first`, `version`, and `includeBackfill`. This adds an additional `maxWorksPerArtist` param which is threaded to the underlying Metaphysics and Vortex GraphQL query fields.
=> feat: support maxWorksPerArtist param on /new-for-you page

src/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx, src/Apps/Artwork/Utils/insightHelpers.ts, src/Apps/Artwork/Utils/insightUtils.ts, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkArtistMarket.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkArtistMarket.jest.tsx
Addresses https://github.com/artsy/force/pull/10880#pullrequestreview-1093488341
Adjust MyC insights sell-through rate formatting.
| --- | --- |
| <img width="288" alt="Screenshot 2022-09-01 at 16 28 06" src="https://user-images.githubusercontent.com/4691889/187939216-b4d6f33a-9fc1-456f-87b6-a48bc0fd7b05.png">|<img width="322" alt="Screenshot 2022-09-01 at 16 33 02" src="https://user-images.githubusercontent.com/4691889/187940412-5b88a9dd-f721-4daa-95cf-d21e6d8cac85.png"> |
=> fix: Adjust MyC insights sell-through rate formatting

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Artists.tsx, src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx
Currently, when saving an artwork after editing it, the user will be navigated to the artwork detail page. At this point it's not easy to navigate back to the My Collection overview because pressing the back button would navigate the user again back to the edit page. 
This PR fixes this by replacing the route with the `/my-collection` route after saving the artwork. 
=> fix: Add my-collection route to history when saving an artwork

.secrets.baseline, src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Artists.tsx, src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx, src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx, src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx
This PR solves [CX-2870]
Don't show confirmation dialog when the user has not made any changes | edit/create artwork flow
[CX-2870]: https://artsyproduct.atlassian.net/browse/CX-2870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: don't show confirmation dialog

src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYou.tsx, src/Apps/Consign/Routes/SubmissionFlow/ThankYou/ThankYouWhenFromMyCollection.tsx, src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYou.jest.tsx, src/Apps/Consign/Routes/SubmissionFlow/ThankYou/__tests__/ThankYouWhenFromMyCollection.jest.tsx
This PR solves [CX-2883]
Reverted changes made to the Thank you page that is shown after successful submission to sell (ThankYou.tsx)
Renamed the file with the component that will be used for the same purposes, but when the artwork is submitted from My Collection (ThankYouWhenFromMyCollection.tsx)
To test the standard SWA ThankYou screen you can use the link: http://localhost:5000/sell/submission/ed0c7181-ceb3-47c0-96cb-cea66f28b608/thank-you
[CX-2883]: https://artsyproduct.atlassian.net/browse/CX-2883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: reverted changes made to SWA ThankYou screen

src/Apps/Admin/adminRoutes.tsx, src/Apps/Admin/adminServerRoutes.tsx
While [investigating](https://artsy.slack.com/archives/CCS8TMQ0K/p1662478073254789) a shortcut that had been updated and is seemingly very cached, discovered that the `/admin/clear-cache` route & functionality was broken. 
This fixed it when running locally, though I will freely admit that I'm not sure if it's the "correct" way to fetch a user in Force nowadays. LMK if I goofed!
=> fix: fix admin/clear-cache route

src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx, src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx
This PR solves [FX-4152]
[FX-4152]: https://artsyproduct.atlassian.net/browse/FX-4152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4152): position account above inbox in mweb nav

src/Components/NavBar/NavBar.tsx, src/Components/NavBar/NavBarLoggedInActions.tsx, src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuAuthentication.tsx, src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotificationsIndicator.tsx, src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenuNotificationsIndicator.jest.tsx, src/Components/NavBar/NavBarNotificationIndicator.tsx, src/Components/NavBar/helpers.ts, src/__generated__/NavBarMobileMenuNotificationsIndicatorQuery.graphql.ts, src/__generated__/NavBarMobileMenuNotificationsIndicator_me.graphql.ts, src/__generated__/NavBarMobileMenuNotificationsIndicator_test_Query.graphql.ts
This PR solves [FX-4201]
[Figma link](https://www.figma.com/file/SlzmAJV6zqJDmAO8GoSjiC/Activity-%2F-Save-%2F-Follow-%2F-Create?node-id=1336%3A81444)
Review app: https://add-blue-dot-indicator.artsy.net/
* Add a blue dot on the hamburger menu icon if user has unread notifications (ignore Inbox for now)
* Add blue dot on Activity link if user has unread notifications
* Use the same query which is used on Desktop
| Menu | Activity item |
| <img width="344" alt="demo-1" src="https://user-images.githubusercontent.com/3513494/188670728-89e753fe-b794-4ece-ab3d-f6eacfab7e0e.png"> | <img width="344" alt="demo-2" src="https://user-images.githubusercontent.com/3513494/188670765-a5b95941-9680-4043-9a19-3528ad71d023.png"> |
[FX-4201]: …
=> feat(FX-4201): display indicator for hamburger menu icon and Activity link when user has unread notifications

src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx, src/Server/passport/lib/app/lifecycle.js
This PR adds a layer of text injection protection that we were lacking. It updates two sides of a handshake so that a bad actor can't populate our error toast via the URL. Here's an example of the intended usage:
Examples of abuses:
```
http://localhost:4000/settings/edit-settings?error=Please%20contact%20support%20at%20bad-actor@example.com
http://localhost:4000/settings/edit-settings?error=already-linked&provider=Please%20contact%20bad-actor@example.com
http://localhost:4000/settings/edit-settings?error=already-linked&provider=Google%20Please%20contact%20bad-actor@example.com
```
I have verified each of these does nothing with this new blocking approach. 👍 
Shout out to @joeyAghion for helping me see that this was an easy way to solve the problem! 🤗 …
=> fix: Block text injection on settings page GRO-1172

src/Apps/Order/Routes/Review/index.tsx
This PR removes the first of two COVID-19 messages that is displayed to collectors when they place a BNMO order. This message informs users that response times may be impacted by COVID-19, and is displayed on both the review step and the confirmation page.
We are removing this message from the review step to free up real estate for the submit button that can be hidden below the fold for some collectors.
Review step:
Confirmation page:
=> chore: remove COVID-19 message from review step of checkout flow

src/DevTools/setupTestWrapper.tsx
@MounirDhahri @MrSltun and I have added an `ErrorBoundary` class that prints an error message telling what went wrong if a test fails
**Before** logs:
**After** logs:
=> chore: add ErrorBoundary to the setupTestWrapper

src/Apps/Order/Components/BankAccountPicker.tsx, src/Apps/Order/Routes/Payment/PaymentContent.tsx, src/Apps/Order/Routes/Payment/index.tsx, src/Apps/Order/Routes/__tests__/Payment.jest.tsx
This PR solves [TX-611]
This PR allows buyers in EUR to re-use their unsaved SEPA bank account when they come back to the payment step in the checkout flow. 
https://user-images.githubusercontent.com/42584148/189081572-ee8b1e86-fca6-42de-a1d9-87cd82343d86.mov
[TX-611]: https://artsyproduct.atlassian.net/browse/TX-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-611): Allow unsaved SEPA account to be re-used during checkout 

src/Components/Notifications/Notifications.tsx, src/Components/Notifications/NotificationsEmptyStateByType.tsx, src/Components/Notifications/NotificationsList.tsx, src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx, src/Components/Notifications/__tests__/NotificationsList.jest.tsx, src/Components/Notifications/types.ts
This PR solves [FX-4196]
Review app: [activity-panel-empty-states](https://activity-panel-empty-states.artsy.net/)
| All tab | Alerts tab |
| <img width="513" alt="demo-1" src="https://user-images.githubusercontent.com/3513494/188926318-774b5d4d-184f-4c7e-a0de-a5313df4d2ce.png"> | <img width="513" alt="demo-2" src="https://user-images.githubusercontent.com/3513494/188926352-4256ab7f-65e5-42dd-82e8-a01a119aae2a.png"> |
https://user-images.githubusercontent.com/3513494/188931252-91d3ea16-1438-458a-ba67-bda9e287033a.mp4
| All tab | Alerts tab |
| <img width="342" alt="demo-3" src="https://user-images.githubusercontent.com/3513494/188926609-a8005557-ef4c-439c-9cd4-c2bcb73d5ba9.png"> | <img …
=> feat(FX-4196): render empty states for activity panel

src/Components/NavBar/Menus/NavBarNewNotifications.tsx
Review app: [unlock-parent-scroll](https://unlock-parent-scroll.artsy.net/)
https://user-images.githubusercontent.com/3513494/189310246-bc34a271-2ccd-4cd2-a397-202e20b6a39c.mp4
https://user-images.githubusercontent.com/3513494/189310338-1582b373-72f2-4a23-be64-c021f495c6bc.mp4
=> feat: unlock parent scroll when activity panel menu is closed

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx, src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ArtsyGuarantee.tsx, src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2ArtsyGuarantee.jest.tsx, src/DevTools/setupTestWrapper.tsx, src/System/i18n/locales/en-US/translation.json
This PR solves [FX-4151]
- adds artsy guarantee section
- hidden behind a featureflag
- exports render with i18n provider from setuptestwrapper file
> :warning: Note that the icons are not the latest updated figma icons, need to resolve the questions/feedback on [this palette pr](https://github.com/artsy/palette/pull/1206) in order to use the newer ones
|Desktop expanded|Desktop collapsed|
|---|---|
|<img width="1018" alt="Screenshot 2022-09-09 at 12 52 15" src="https://user-images.githubusercontent.com/21178754/189335398-6fe251f0-1bb7-4ba5-8258-0bf519febb9e.png">|<img width="894" alt="Screenshot 2022-09-09 at 12 53 06" src="https://user-images.githubusercontent.com/21178754/189335386-e9d30727-7a0d-416c-9b56-e77246223f50.png">|
|**mweb expanded**|**mweb …
=> feat(FX-4151): Artsy Guarantee section

src/Apps/Show/ShowApp.tsx, src/Apps/Show/__tests__/ShowApp.jest.tsx
The criteria to suppress a link back to the fair wasn't strict enough - this PR updates the logic to include a check on the `hasFullFeature` property.
<details>
<summary>Here's some screenshots</summary>
</details>
https://artsyproduct.atlassian.net/browse/GRO-1171
=> fix: Suppress fair banner when not full featured fair GRO-1171

src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx
This PR solves [TX-637]
This PR updates the styles of the order statuses on the order history page.
[TX-637]: https://artsyproduct.atlassian.net/browse/TX-637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update styles of order statuses

src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx, src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx, src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
This PR solves [CX-2885]
This PR adds the insights header to the insights page
| | Mobile | Desktop |
| --- | --- | --- |
| normal | <img width="389" alt="image" src="https://user-images.githubusercontent.com/20655703/189614351-51656f99-e077-4254-b68b-55fdc16fd525.png"> | <img width="1739" alt="image" src="https://user-images.githubusercontent.com/20655703/189614333-f83323a6-0dec-4887-930e-32419f90b954.png"> |
| sticky | <img width="389" alt="image" src="https://user-images.githubusercontent.com/20655703/189585091-a5766f38-8d33-4537-a630-976cbe5a2a1d.png"> | <img width="1744" alt="image" src="https://user-images.githubusercontent.com/20655703/189585017-2ab01175-fbf3-4266-b4c0-b6715d12096d.png"> |
[GRO-434]: …
=> feat(CX-2885): Add Insights header

src/Components/NavBar/NavBarLoggedInActions.tsx
Jira ticket: [FX-4201]
Render new notifications indicator for navbar menu when feature flag is enabled
| <img width="448" alt="before" src="https://user-images.githubusercontent.com/3513494/189870132-788a7506-4b6d-449d-8171-8d6d9532433c.png"> | <img width="448" alt="after" src="https://user-images.githubusercontent.com/3513494/189870175-217d2b9b-93bf-4774-8214-e35cc14f4750.png"> |
[FX-4201]: https://artsyproduct.atlassian.net/browse/FX-4201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-4201): render new notifications indicator for navbar menu

src/Components/Notifications/NotificationsTabs.tsx
Review app: [close-icon-for-activity-panel](https://close-icon-for-activity-panel.artsy.net/)
Figma: [link](https://www.figma.com/file/SlzmAJV6zqJDmAO8GoSjiC/Activity-%2F-Save-%2F-Follow-%2F-Create?node-id=1336%3A57605)
* Add close icon for activity panel dropdown menu
* Small improvements for tabs
=> feat: add close icon for activity panel

src/Components/SavedSearchAlert/Components/SavedSearchAlertPills.tsx
This PR solves [FX-4108]
https://user-images.githubusercontent.com/3513494/189921609-d33c9fa7-1c71-44f1-ab19-9c6c021ea984.mp4
https://user-images.githubusercontent.com/3513494/189921771-6e0bded0-5a3b-4061-aa3c-76cb7db70da1.mp4
[FX-4108]: https://artsyproduct.atlassian.net/browse/FX-4108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FX-4108): Switching between metrics (cm/in) produces duplicate filter pills when custom size is selected

src/Apps/Authentication/Routes/__tests__/ResetPasswordRoute.jest.tsx, src/Components/Authentication/Validators.tsx, src/Components/Authentication/Views/SignUpForm.tsx, src/Components/Authentication/__tests__/helpers.jest.ts
This PR started with a simply copy change so that users see all the rules for a valid password. Then I also update the Yup schema for the password field to throw errors when those rules are violated and provide better error messages to the user. This happens client-side so the user doesn't have to wait for the server to tell them something was wrong.
I then wrote unit tests that use this Yup schema to demonstrates the various ways a password can be invalid and finally a case for a password that follows the rules.
<details>
<summary>Here's some screenshots</summary>
</details>
https://artsyproduct.atlassian.net/browse/GRO-1277
=> feat: User sees complete rules for password and better validations GRO-1277

hokusai/production.yml, hokusai/staging.yml
This PR supports [PLATFORM-4571]
Staging [has been partly run on Spot nodes](https://github.com/artsy/force/pull/10846) for a while. I haven't heard of any problems. This PR spikes Prod on Spot.
- Allow pods in Prod to run on Spot nodes.
And (as [done for Gravity](https://github.com/artsy/gravity/pull/15646)):
- Remove topologySpreadConstraints in Staging.
[PLATFORM-4571]: https://artsyproduct.atlassian.net/browse/PLATFORM-4571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: allow prod to run on spot

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx, src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2EditionSets.tsx, src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2SizeInfo.tsx, src/__generated__/ArtworkSidebar2EditionSets_artwork.graphql.ts, src/__generated__/ArtworkSidebar2SizeInfo_piece.graphql.ts, src/__generated__/ArtworkSidebar2_Test_Query.graphql.ts, src/__generated__/ArtworkSidebar2_artwork.graphql.ts, src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
This PR solves [FX-4219]
> ⚠️ Feature is behind a feature flag
Adds Edition selection in artwork screen, functionality and tests will be added on next ticket ([FX-4149](https://artsyproduct.atlassian.net/browse/FX-4149))
|Desktop| mWeb|
|---|---|
|<img width="1512" alt="Screenshot 2022-09-14 at 17 22 48" src="https://user-images.githubusercontent.com/21178754/190196608-0d80ef91-e5fd-404f-8d0f-3ffc0777c13e.png">|<img width="378" alt="Screenshot 2022-09-14 at 17 23 26" src="https://user-images.githubusercontent.com/21178754/190196604-4312597b-4deb-4d63-82b5-f4881459b901.png">|
[FX-4219]: …
=> feat:(FX-4219): edition selection artwork screen

src/Apps/Search/Components/ZeroState.tsx, src/Apps/Search/SearchApp.tsx, src/System/i18n/locales/en-US/translation.json
Remove the logic responsible for defining if the sentence that's displayed on the search results should use singular or plural form and replace it with i18n keys.
=> chore: Let react-i18next handle pluralization on Search results

src/Apps/Conversation/Components/Conversation.tsx
This PR solves [NX-3277](https://artsyproduct.atlassian.net/browse/NX-3277)
Update fraud prevention banner copy to `To be covered by the Artsy Guarantee, always communicate and pay through the Artsy platform.`
=> fix(NX-3277): update copy for fraud prevention banner

src/Apps/Consign/Routes/MarketingLanding/Components/Header.tsx, src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/Header.jest.tsx
Addresses [CX-2937]
Adding the "Get in Touch" CTA on **Sell** page behind feature flag.
| mWeb | Web |
| --- | --- |
|![Screenshot 2022-09-19 at 11 40 11](https://user-images.githubusercontent.com/4691889/190994705-5e74f498-d1d1-4862-9dc3-38c702a9ae0c.png) |![Screenshot 2022-09-19 at 12 02 21](https://user-images.githubusercontent.com/4691889/190994716-0447b316-157c-4a6b-82e5-ad45f18f4c85.png) |
[CX-2937]: https://artsyproduct.atlassian.net/browse/CX-2937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add Get in Touch CTA

src/Apps/Home/Components/HomeNewWorksForYouRail.tsx, src/Apps/NewForYou/newForYouRoutes.tsx
This PR updates both the rail on the homepage and the actual /new-for-you page so that they will show more works per artist. I considered extracting a constant for this but then changed my mind. 🤷 
https://artsyproduct.atlassian.net/browse/GRO-1297
/cc @artsy/grow-devs @shaq31415926 @isakelaris
=> feat: Increase the max number of works per artist for new for you GRO-1297

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx, src/Apps/Auction/Components/RegisterButton.tsx, src/Apps/Auction/Components/__tests__/RegisterButton.jest.tsx
Some Login modals are wrongly showing a prompt to "Sign up" in their copy. This PR fixes it.
Thanks @joeyAghion for flagging!
=> chore: fix copy for log in modal

src/Apps/Consign/Routes/MarketingLanding/FAQApp.tsx, src/Apps/Consign/consignRoutes.tsx
Addresses [CX-2950]
This PR adds the new Sell with Artsy FAQ page to be displayed in a web view in the app.
| with Eigen's user agent |normal | 
| --- | --- |
|<img width="375" alt="Screenshot 2022-09-20 at 10 21 35" src="https://user-images.githubusercontent.com/4691889/191213717-ede5c96a-354e-4716-96d5-95b3bd69ca1f.png"> |<img width="375" alt="Screenshot 2022-09-20 at 10 21 51" src="https://user-images.githubusercontent.com/4691889/191213740-029b3cc2-7c5c-495f-8a66-4e65ebdb71ca.png"> |
[CX-2950]: https://artsyproduct.atlassian.net/browse/CX-2950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add Sell with Artsy FAQ page

src/Apps/About/AboutApp.tsx
This PR updates the company mission that is included in the `/about` page (as a meta-tag), so that our previous mission no longer appears in Google search results when I search for "artsy mission".
=> chore: update company mission

src/Apps/Show/Routes/ShowInfo.tsx, src/Apps/Show/__tests__/ShowInfo.jest.tsx, src/__generated__/ShowInfo_Test_Query.graphql.ts, src/__generated__/ShowInfo_show.graphql.ts, src/__generated__/showRoutes_ShowInfoQuery.graphql.ts
This PR adds back something that was removed when we re-built the more info page for shows: `PartnerShowEvent` records. Here's the Figma I was following:
https://www.figma.com/file/k465puwy6YQOcEESEkppni/Smaller-Tasks-2022?node-id=24%3A952
What I did here was update the GQL to include the `events` array and then I broke out an `EventList` component. I didn't start with that component extracted but then when it came time to test it was handy to have a way to filter down to that part of the page.
<details>
<summary>Heres some screenshots</summary>
</details>
https://artsyproduct.atlassian.net/browse/GRO-1024
/cc @artsy/grow-devs @starsirius
=> feat: User sees show events on the info page GRO-1024

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/__tests__/MyCollectionArtworkSidebar.jest.tsx
This PR solves [CX-2913]
This PR updates the label from "Size" to "Dimensions" in My Collection artwork page
|--|--|
| ![image](https://user-images.githubusercontent.com/20655703/191809566-ba840e91-0a08-4483-80f2-f078b337f832.png) | ![image](https://user-images.githubusercontent.com/20655703/191809574-23682d2d-fce4-48c3-933b-6b2ea8730016.png) |
[CX-2913]: https://artsyproduct.atlassian.net/browse/CX-2913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-2913): rename Size to Dimensions in MyC artwork page

src/Apps/Notifications/NotificationsApp.tsx, src/Apps/Notifications/notificationsRoutes.ts, src/Components/NavBar/Menus/NavBarNewNotifications.tsx, src/Components/NavBar/NavBarLoggedInActions.tsx, src/Components/Notifications/MarkAllAsReadPanel.tsx, src/Components/Notifications/Mutations/markAllNotificationsAsRead.ts, src/Components/Notifications/NotificationsList.tsx, src/Components/Notifications/NotificationsTabs.tsx, src/Components/Notifications/__tests__/MarkAllAsReadPanel.jest.tsx, src/Components/Notifications/__tests__/Notifications.jest.tsx, src/System/i18n/locales/en-US/translation.json, src/__generated__/NotificationsApp_me.graphql.ts, src/__generated__/NotificationsListNextQuery.graphql.ts, src/__generated__/NotificationsListQuery.graphql.ts, src/__generated__/NotificationsList_test_Query.graphql.ts, src/__generated__/NotificationsList_viewer.graphql.ts, src/__generated__/markAllNotificationsAsReadMutation.graphql.ts, src/__generated__/notificationsRoutesQuery.graphql.ts
This PR solves [FX-4182]
Review app: [mark-all-notifications-as-read](https://mark-all-notifications-as-read.artsy.net/)
> **Warning**
> Please note that there are some problems on the backend side (e.g. [FX-4271](https://artsyproduct.atlassian.net/browse/FX-4271), [FX-4205](https://artsyproduct.atlassian.net/browse/FX-4205)) and for this reason not all notifications can be marked as read
https://user-images.githubusercontent.com/3513494/191791689-840d36b0-a52b-494a-b525-a46fa008aa46.mp4
https://user-images.githubusercontent.com/3513494/191791752-bdae2b20-428b-47da-a13e-3aa869ba9bc9.mp4
[FX-4182]: https://artsyproduct.atlassian.net/browse/FX-4182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4182): mark all notifications as read

src/Apps/Order/Routes/Payment/index.tsx
This PR solves [TX-753]
This PR prevents the initialization of `bankAccountSelection` field when `selectedPaymentMethod` empty. 
[TX-753]: https://artsyproduct.atlassian.net/browse/TX-753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: cannot create SEPA bank account if collector already has saved US bank account

src/Components/Onboarding/Hooks/useOnboarding.tsx
This fixes the issue where the modal was always expanding to fill 90% of the height on desktop: 
=> fix(onboarding): Cap max height

src/Apps/ArtQuiz/ArtQuizApp.tsx, src/Apps/ArtQuiz/ArtQuizContext/ArtQuizContext.tsx, src/Components/ArtQuiz/Views/ArtQuizWelcome.tsx
The type of this PR is: **feat w/ a lil refactor** 
This PR solves [GRO-1284]
The intent of this PR is to hook up the welcome page to the interface after `onClick()` to start the quiz. 
[GRO-1284]: https://artsyproduct.atlassian.net/browse/GRO-1284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(art-quiz) hook welcome screen to art quiz interface

src/Apps/Consign/Routes/MarketingLanding/FAQApp.tsx
Decrease Consign FAQ page top spacing for Eigen only.
[Slack Thread for context](https://artsy.slack.com/archives/C01B2P6LJUU/p1664353989135969?thread_ts=1664268146.882799&cid=C01B2P6LJUU)
=> fix: Decrease Consign FAQ page top spacing for mobile

src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx, src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
This PR removes the subtitle from the Insights header to match the design
Also updates the padding for the sticky header in the mobile view
|Before|After|
|--|--|
| ![image](https://user-images.githubusercontent.com/20655703/192752434-8661bbee-a570-4813-b0f1-a8bdddee8073.png) | ![image](https://user-images.githubusercontent.com/20655703/192752456-6c2674a7-dd48-4c8e-bdd5-99889186cf63.png) |
| ![image](https://user-images.githubusercontent.com/20655703/192754107-944a7c4d-4d41-4d60-8f45-6b1deecf2283.png) | ![image](https://user-images.githubusercontent.com/20655703/192754124-1cb907e2-50e7-48d9-89b1-3fe5f47cf40a.png) |
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> fix: Remove subtitle from Insights Header

src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkBackButton.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
This PR solves [CX-2780]
This PR adds the back button to My Collection inside MyC Artwork Details page
| Viewport | Before | After |
|--|--|--|
| Desktop | <img width="1280" alt="image" src="https://user-images.githubusercontent.com/20655703/192596885-800b731f-30ba-45c4-93d7-7cee04b91650.png"> | <img width="1280" alt="image" src="https://user-images.githubusercontent.com/20655703/192596958-6ce898dc-8d18-4bd1-a9c7-6212d42f4ef6.png"> |
| Mobile | <img width="390" alt="image" src="https://user-images.githubusercontent.com/20655703/192596999-bbb41aac-3087-486d-b8fa-2ccb6efeaec5.png"> | <img width="390" alt="image" src="https://user-images.githubusercontent.com/20655703/192597025-3743f730-cbad-4c85-b5d0-1a5906122b32.png"> |
[GRO-434]: …
=> feat(CX-2780): add back button to MyC Artwork details page

src/Components/Notifications/NotificationsList.tsx
| <img width="342" alt="before" src="https://user-images.githubusercontent.com/3513494/192834619-a904d2a1-d4a0-491c-9108-1f6fd43ad930.png"> | <img width="342" alt="after" src="https://user-images.githubusercontent.com/3513494/192834666-887e413a-cb29-4020-9e9b-cacce680b030.png"> |
=> chore: use `secondaryBlack` variant for "show more" button

src/html.ejs
A minor thing but in my [non-scientific] testing this removed webfonts from being a factor in holding up the LCP.
The domain preconnect is incase we're on a page that has another font (mainly medium-italic, though it's rare). And preload the CSS because that's an obvious critical one we need.
=> feat: preconnect webfonts and preload font css

src/Apps/Order/Routes/Shipping/index.tsx
This PR solves [PX-5256](PX-5256)
Seeing the following error on checkout plus the "something went wrong" modal if:
- Order is Artsy Shipping
- on any address changes (addition of new address or selecting between multiple saved addresses)
The error in console reads as:
```
instrument.js:109 Order/Routes/Shipping/index.tsx | Error: Mutliple simulataneous mutations is not currently supported
```
Looks like this started with the new use of `useEffect` [that calls setShipping mutation](https://github.com/artsy/force/blob/main/src/Apps/Order/Routes/Shipping/index.tsx#L165-L170)
=> fix (PX-5256): Remove duplicated call to setShipping mutation on address changes

src/System/Analytics/trackingMiddleware.ts, src/System/Router/buildClientApp.tsx, src/Utils/Hooks/useOnboardingModal.ts
Closes: [GRO-1242](https://artsyproduct.atlassian.net/browse/GRO-1242)
Initially: https://github.com/artsy/force/pull/11058
Read that description; which is still valid. The problem with that approach is that manipulating the history state directly does not update anything in the routing store. The data in the routing store is used in triggering the modal in the first place.
Here I've just added an additional argument to exclude referrers from tracking 😵‍💫 — sorry.
=> fix(GRO-1242): prevents triggering analytics on route change

.eslintrc.js, package.json, yarn.lock
Addresses https://artsyproduct.atlassian.net/browse/WP-116
Add eslint plugin & rule to disallow the use of relative paths, with an exception for same folder.
=> chore(tooling): add no-relative-path-imports

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ArtsyGuarantee.tsx
This PR resolves [FX-4335]
Remove blue highlight from Artsy Guarantee section
[slack thread](https://artsy.slack.com/archives/C9SATFLUU/p1664963285885169) where this was surfaced
|Desktop|mWeb|
|---|---|
|<img width="1510" alt="Screenshot 2022-10-05 at 13 46 27" src="https://user-images.githubusercontent.com/21178754/194053718-5a392ea2-198d-4bd2-9bab-2dce3074ef2d.png">|<img width="385" alt="Screenshot 2022-10-05 at 13 46 53" src="https://user-images.githubusercontent.com/21178754/194053705-eb8e174d-cffa-44dd-9cd3-f95b3aa7b0aa.png">|
[FX-4335]: https://artsyproduct.atlassian.net/browse/FX-4335?atlOrigin=eyJp …
=> fix: remove blue highlight from guarantee icons

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ArtsyGuarantee.tsx
This PR solves [FX-4317]
When pressing artsy guarantee learn more link a new tab opens
[FX-4317]: https://artsyproduct.atlassian.net/browse/FX-4317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FX-4317): artsy guarantee learn more link opens new tab

src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGallery.tsx, src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryCaption.tsx, src/Apps/Article/Components/ArticleZoomGallery/ArticleZoomGalleryFigure.tsx, src/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionCaption.tsx, src/Apps/Article/Components/Sections/ArticleSectionImageCollection/ArticleSectionImageCollectionImage.tsx, src/__generated__/ArticleBody_test_Query.graphql.ts, src/__generated__/ArticleInfiniteScrollQuery.graphql.ts, src/__generated__/ArticleSectionImageCollectionCaption_figure.graphql.ts, src/__generated__/ArticleSectionImageCollectionImage_figure.graphql.ts, src/__generated__/ArticleZoomGalleryCaption_figure.graphql.ts, src/__generated__/ArticleZoomGalleryFigure_figure.graphql.ts, src/__generated__/ArticleZoomGalleryQuery.graphql.ts, src/__generated__/ArticleZoomGallery_article.graphql.ts, src/__generated__/ArticleZoomGallery_test_Query.graphql.ts, src/__generated__/NewsIndexArticlesQuery.graphql.ts, src/__generated__/articleRoutes_ArticleQuery.graphql.ts, src/__generated__/articlesRoutes_NewsQuery.graphql.ts
Closes: [GRO-1299](https://artsyproduct.atlassian.net/browse/GRO-1299)
<del>Will draft until I open and merge the Metaphysics PR wherein I add a new `ArticleUnpublishedArtwork` type.</del>
https://github.com/artsy/metaphysics/pull/4431 adds an `ArticleUnpublishedArtwork` type.
This uses that type to display the missing works. Basically looks the same but there's no link to the artwork, just a normal zoom.
=> feat(article): allows unpublished artworks to be viewed within articles

src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/UploadPhotosForm.tsx
Removes `callback` to avoid removed photos to appear again in the SWA form when adding a new photo.
1. Submit an artwork
2. Add artwork details
3. Add some photos
4. Remove some photos
5. Add a new photo
6. **Removed photos shouldn't appear again**
=> fix: Remove callback to avoid removed photos to appear again in the SWA form

src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
This PR hides the Career Highlights carousel behind the `my-collection-web-phase-7-career-highlights` feature flag
=> fix: Hide Career Highlights carousel behind feature flag

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CommercialButtons.tsx
This PR solves [FX-4319]
Review app: [commercial-buttons](http://commercial-buttons.artsy.net/)
Quick artwork example: [Link](https://commercial-buttons.artsy.net/artwork/damon-zucconi-editioned-cg-price-range-arta-us-2)
* Commercial buttons starts overflowing the sidebar when screen width < 1075
* iPhone SE (first generation) does the same when contact gallery is secondary
We discussed with Kseniya and decided that the buttons will be placed under each other by default (column view). When the screen width is `1192px` or more (`xl` breakpoint according to the list of [supported breakpoints](https://palette.artsy.net/guides/responsive/#all-breakpoints)), then place the buttons in a row
| <img width="981" …
=> fix(FX-4319): commercial buttons section overflow

src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/UploadPhotosForm.tsx, src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx, src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx, src/Components/PhotoUpload/Components/PhotoThumbnail.tsx, src/Components/PhotoUpload/Utils/fileUtils.ts, src/Components/PhotoUpload/Utils/uploadFileToS3.tsx, src/__generated__/UploadPhotos_SubmissionMyCollectionFlowTest_Query.graphql.ts, src/__generated__/UploadPhotos_myCollectionArtwork.graphql.ts, src/__generated__/consignFromMyCollectionRoutes_uploadArtworkPhotosQuery.graphql.ts
This PR solves [CX-2952](https://artsyproduct.atlassian.net/browse/CX-2952)
This PR implements the initialization of images in the Sell With Artsy form when submitting an artwork from My Collection.
All images from the My Collection artwork will be automatically reuploaded and processed and added as assets to the submission.
=> feat: Initialize SWA form images when submitting an artwork from My Collection

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2Classification.tsx
This PR solves [FX-4320]
Made artworksidebar2classification more defensive, there were some cases where the `shortArrayDescription` was in a weird state and it resulted in a 500 error, after debugging it the stacktrace led us to [this line](https://github.com/artsy/force/compare/gkartalis/FX-4320?expand=1#diff-939cb6b50bc43cdd9bad7d07f9b299588080dea5bf44017432b427d87ec2bf87L46)
> (also updated an import path)
How to test:
Spawn an online auction, go to a lot that doesn't have an attribution class to gravity staging, add an attributionClass and reload, the page in force should not break (make sure that you wait some seconds after adding the attributionClass)
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
=> fix(FX-4320): make artworksidebar2classification more defensive

src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/Components/UploadPhotosForm.tsx, src/Components/PhotoUpload/Components/PhotoThumbnail.tsx, src/Components/PhotoUpload/Utils/uploadFileToS3.tsx, src/Components/PhotoUpload/__tests__/PhotoThumbnail.jest.tsx
Addresses [CX-2952]
Adjust error message when initial artwork image loading (from My Collection) fails in SWA flow.
[Slack Thread with more context](https://artsy.slack.com/archives/C01B2P6LJUU/p1665492951106379)
[CX-2952]: https://artsyproduct.atlassian.net/browse/CX-2952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Adjust error message when initial artwork image loading fails in SWA flow

docs/best_practices.md
Updates FAQ best practices with note about avoiding inner margins
=> docs(best-practices): Add docs around avoiding inner margins

src/Components/Notifications/NotificationItem.tsx, src/Components/Notifications/__tests__/NotificationItem.jest.tsx, src/__generated__/NotificationItem_item.graphql.ts, src/__generated__/NotificationItem_test_Query.graphql.ts, src/__generated__/NotificationsListNextQuery.graphql.ts, src/__generated__/NotificationsListQuery.graphql.ts, src/__generated__/NotificationsList_test_Query.graphql.ts
This PR solves [FX-4363]
Removes counters from individual notifications since backend returns not complete data which makes it impossible to display a correct number. This is a temporary solution until the issue is resolved on BE side.
[FX-4363]: https://artsyproduct.atlassian.net/browse/FX-4363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4363): Activity panel: Remove artworks counter

src/Apps/Auction/Components/AuctionAssociatedSale.tsx, src/Apps/Auction/Components/__tests__/AuctionAssociatedSale.jest.tsx
This PR solves [GRO-1354]
Force should not be doing its own formatting for `sale. displayTimelyAt`, as Metaphysics already does it for clients.
Related Metaphysics [deploy](https://github.com/artsy/metaphysics/pull/4444). 
[GRO-1354]: https://artsyproduct.atlassian.net/browse/GRO-1354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: remove timely formatting

hokusai/production.yml, hokusai/staging.yml
This PR solves [PLATFORM-4614]
Follows https://github.com/artsy/force/pull/10995
Make web  deployment prefer Spot tier, to maximize Spot usage. [Dashboard](https://app.datadoghq.com/dashboard/2n5-6tr-ypp/kubernetes-deployments?tpl_var_deployment%5B0%5D=force-web&tpl_var_hpa%5B0%5D=force-web&from_ts=1665066560349&to_ts=1665671360349&live=true) shows spot/on-demand distribution.
[PLATFORM-4614]: https://artsyproduct.atlassian.net/browse/PLATFORM-4614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: web deployment to prefer spot tier

src/Components/Notifications/NotificationsEmptyStateByType.tsx, src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
This PR solves [FX-4365]
[FX-4365]: https://artsyproduct.atlassian.net/browse/FX-4365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4365): Change copy of Alert's tab empty state

src/Apps/Settings/Routes/Insights/Components/InsightsMedianSalePrice.tsx, src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsMedianSalePrice.jest.tsx, src/Apps/Settings/Routes/Insights/InsightsRoute.tsx, src/__generated__/InsightsMedianSalePriceTestQuery.graphql.ts, src/__generated__/InsightsMedianSalePrice_me.graphql.ts, src/__generated__/InsightsRoute_me.graphql.ts, src/__generated__/settingsRoutes_InsightsRouteQuery.graphql.ts
This PR solves [CX-2879]
This PR adds the Median Sale Price to My Collection insights tab. this work is hidden behind a feature flag:
`my-collection-web-phase-7-median-sale-price`
| Desktop | Mobile | 
| -- | -- |
| ![image](https://user-images.githubusercontent.com/20655703/195318087-561ed9ed-4df4-4316-8770-e287df32397f.png) | ![image](https://user-images.githubusercontent.com/20655703/195318043-82d5100c-064d-4b11-87b8-25a8c91f52b6.png) |
[CX-2879]: https://artsyproduct.atlassian.net/browse/CX-2879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-2879): Add Median Sale Price to MyC Insights

src/Apps/RSS/templates/article.ejs
I'm having a hard time seeing _why_ this is happening so I'll do some more poking around but I wanted to fix this so that RSS clients aren't stuck.
https://artsyproduct.atlassian.net/browse/GRO-1358
=> fix: Guard against undefined images in RSS feed GRO-1358

src/Apps/Auctions/Components/MyBids/MyBids.tsx, src/Apps/Home/Components/HomeFeaturedMarketNews.tsx, src/Components/Cells/CellArticle.tsx
Minor thing; going around trying to improve some of the placeholders to reduce layout shift.
In a separate PR I'm going to extract some work from https://github.com/artsy/force/pull/11126 which included a bunch of placeholder improvements (— not sure when we'll get to a point where we can start breaking the image caches).
=> fix(home): tightens up homepage placeholders

src/Apps/Components/AppShell.tsx, src/Server/__tests__/volley.jest.ts, src/Server/analytics/helpers.ts, src/Server/volley.ts, src/Utils/Hooks/__tests__/useImagePerformanceObserver.jest.ts, src/Utils/Hooks/useImagePerformanceObserver.ts, src/Utils/resizer.ts
Sets up a `PerformanceObserver` in the `AppShell` and listens for image loads.
The Volley payload looks like:
```json
{
"serviceName": "force",
"metrics": [
{
"type": "timing",
"name": "image.load-time",
"timing": 21.799999952316284,
"tags": [
"transfer-size:sm",
"device-type:desktop"
]
},
{
"type": "timing",
"name": "image.load-time",
"timing": 27.30000001192093,
"tags": [
"transfer-size:md",
"device-type:desktop"
]
},
{
"type": "timing",
"name": "image.load-time",
"timing": 42.69999998807907,
"tags": [
"transfer-size:sm",
"device-type:desktop"
]
},
{
"type": "timing",
"name": "image.load-time",
"timing": 61.5,
"tags": [
"transfer-size:sm",
"device-type:desktop"
]
},
{
"type": "timing",
"name": "image.load-time",
"timing": 69.5,
"tags": [
"transfer-size:sm",
"device-type:desktop"
]
},
{ …
```
=> chore: instrument client-side image loading

src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateConfirmation.tsx, src/Apps/MyCollection/Routes/PriceEstimate/PriceEstimateContactInformation.tsx
Adjust Price estimate page header.
| --- | --- |
| <img width="1157" alt="Screenshot 2022-10-17 at 11 14 02" src="https://user-images.githubusercontent.com/4691889/196138823-cf0adf3c-e240-4511-86ef-ce259eb33b1a.png">| <img width="1246" alt="Screenshot 2022-10-17 at 11 13 31" src="https://user-images.githubusercontent.com/4691889/196138741-9f3c4077-8386-4e4f-ba72-687d6ae28ea2.png">|
=> fix: Adjust Price estimate page header

src/Apps/About/AboutArtworksRail.tsx, src/Apps/Artist/Routes/Overview/Components/ArtistNotableWorksRail.tsx, src/Apps/Artist/Routes/Overview/Components/ArtistWorksForSaleRail.tsx, src/Apps/Artwork/Components/OtherWorks/Header.tsx, src/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx, src/Apps/Artwork/Components/OtherWorks/index.tsx, src/Apps/Artwork/Components/__tests__/OtherWorks.jest.tsx, src/Apps/Consign/Routes/MarketingLanding/Components/SoldRecentlyOnArtsy.tsx, src/Apps/Home/Components/HomeAuctionLotsRail.tsx, src/Apps/Home/Components/HomeNewWorksForYouRail.tsx, src/Apps/Home/Components/HomeRecentlyViewedRail.tsx, src/Apps/Home/Components/HomeTroveArtworksRail.tsx, src/Apps/Home/Components/HomeWorksByArtistsYouFollowRail.tsx, src/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx, src/Apps/Settings/Routes/Saves/Components/SettingsSavesArtworks.tsx, src/Components/ArtistRail.tsx, src/Components/Artwork/ShelfArtwork.tsx, src/Components/ArtworkGrid/ArtworkGrid.tsx, src/Components/ArtworkGrid/ArtworkGridContext.tsx, src/Components/CategoryRail.tsx, src/Components/Masonry.tsx
Closes [GRO-1351](https://artsyproduct.atlassian.net/browse/GRO-1351)
This ensures we're using consistent placeholders for the artwork rails; adds a placeholder for the grids and uses it.
Ultimately this doesn't have a huge effect on layout shift for two reasons:
* We need to set a specific height for rails (which I do in the area based scaling PR)
* In a few places we don't know what modules we're actually loading, notably the artwork page might have up to 4 grids on it.
That said, this does get us closer, reduces the amount of duplicate work when building new rails and grids, looks better.
=> fix: shelf placeholders

src/Components/Notifications/NotificationsEmptyStateByType.tsx
This PR solves [FX-4367]
| <img width="451" alt="before" src="https://user-images.githubusercontent.com/3513494/196239083-6ab65180-4732-4e6f-99d6-5ef5c1450945.png"> | <img width="451" alt="after" src="https://user-images.githubusercontent.com/3513494/196239123-6b6ac2e1-58bc-4a73-874b-1486f604ddee.png"> |
[FX-4367]: https://artsyproduct.atlassian.net/browse/FX-4367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-4367): Empty state version should have 40px padding between tabs and copy

src/Apps/Gene/Server/__tests__ /redirectGeneToCollection.jest.ts, src/Apps/Gene/Server/redirectGeneToCollection.ts, src/Apps/Gene/Utils/geneToCollectionMap.ts, src/Apps/Gene/geneRoutes.tsx, src/Apps/Home/Components/HomeTroveArtworksRail.tsx, src/Apps/Home/__tests__/HomeTroveArtworksRail.jest.tsx, src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx, src/Components/NavBar/menuData.ts, src/Components/Onboarding/Components/OnboardingMarketingCollection.tsx, src/Components/Onboarding/Components/__tests__/OnboardingMarketingCollection.jest.tsx, src/Components/Onboarding/Views/OnboardingArtistsOnTheRise.tsx, src/Components/Onboarding/Views/OnboardingCuratedArtworks.tsx, src/Components/Onboarding/Views/OnboardingTopAuctionLots.tsx, src/Server/analytics/__tests__/brazeMessagingIntegration.jest.ts, src/__generated__/HomeTroveArtworksRailQuery.graphql.ts, src/__generated__/HomeTroveArtworksRail_Test_Query.graphql.ts, src/__generated__/HomeTroveArtworksRail_viewer.graphql.ts, src/__generated__/OnboardingMarketingCollectionQuery.graphql.ts, src/__generated__/OnboardingMarketingCollection_Test_Query.graphql.ts, src/__generated__/OnboardingMarketingCollection_marketingCollection.graphql.ts
This PR solves [FX-4095]
This PR accomplishes a few things:
- Update navigation links to point to collections instead of gene pages (e.g. `/collection/trove-editors-picks` instead of `/gene/trove`)
- Update "curated genes" to redirect to curated collections (e.g. navigating to `/gene/trove` will redirect you to `/collection/trove-editors-picks`)
- Replace genes in onboarding with collections (Paired with Eigen version [here](https://github.com/artsy/eigen/pull/7396))
- Update homepage Trove rail to pull works from a collection and direct clicks to the collection instead of to the gene
[FX-4095]: https://artsyproduct.atlassian.net/browse/FX-4095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
For the full plan …
=> feat[FX-4095]: use curated collection pages instead of genes

src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx, src/Components/PhotoUpload/Components/PhotoThumbnail.tsx, src/Components/PhotoUpload/__tests__/PhotoThumbnail.jest.tsx
Addresses [CX-2952]
Only show last error message in SWA photo upload form.
| --- | --- |
|<img width="1767" alt="Screenshot 2022-10-13 at 15 43 09" src="https://user-images.githubusercontent.com/4691889/195613590-7c0de1f6-5c65-4ef5-8023-0ed2875a5536.png"> |<img width="1770" alt="Screenshot 2022-10-13 at 15 37 37" src="https://user-images.githubusercontent.com/4691889/195613612-6c65c4f0-ab89-4b15-aff6-4ae698cfac7b.png"> |
[CX-2952]: https://artsyproduct.atlassian.net/browse/CX-2952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Only show last error message in SWA photo upload form

.secrets.baseline, src/Apps/MyCollection/Routes/EditArtwork/MyCollectionArtworkForm.tsx, src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionArtworkForm.jest.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkArtistMarket.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkAuctionResults.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkComparables.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkDemandIndex/index.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSidebar/MyCollectionArtworkSidebarMetadata.tsx
This PR solves [CX-3065]
Checklist: 
1. Save changes - disable the button if no changes are made on the form
2. Demand Index - make padding 40
3. Titles in Insights - make title 20, subtitle (if exists) 13 (sm-display)
4. Demand Index - make number 40 (xl) and text 20 (medium)
5. Market insights - make the titles small-display
6. My collection Artwork - make “---” black60
| fix | before | after |
| --- | --- | --- |
| 1. Save changes button, disable when form is dirty | <img width="1214" alt="image" src="https://user-images.githubusercontent.com/36167539/196445737-57ce8829-0a36-4e63-94d6-69eca2774692.png"> | <img width="1218" alt="image" src="https://user-images.githubusercontent.com/36167539/196445635-6f45e995-b0d7-4b3b-a667-141d6f6d95d1.png"> |
| 2. …
=> fix: my collection UI updates

src/Apps/Order/Components/__tests__/CreditCardPicker.jest.tsx, src/Apps/Order/Routes/__tests__/Shipping.jest.tsx, src/Apps/Order/Utils/__tests__/formValidators.jest.tsx, src/Apps/Order/Utils/formValidators.tsx, src/Components/__tests__/Utils/addressForm.ts
This PR solves [TX-828]
Currently the address validation util used for the address form in the shipping step of the checkout flow does not capture wrong postal code submissions by the user. As a result of that, we go ahead and make a request to our API to set the (invalid) address on the order, which results in an error as illustrated below: 
This PR adds a validator function for postal code for addresses in the US and CA, so that: 
- user is informed about the wrong information they submitted 
- we avoid trying to set an invalid address on the order
[TX-828]: https://artsyproduct.atlassian.net/browse/TX-828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(TX-828): Postal code validation in shipping step address form

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2CommercialButtons.tsx
This PR solves [FX-4382]
Add separator with margin when artwork is sold
screenshots
[FX-4382]: https://artsyproduct.atlassian.net/browse/FX-4382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add spacer when artwork is Sold

src/Apps/MyCollectionInsights/Routes/MyCollectionInsightsMedianSalePriceAtAuction/MyCollectionInsightsMedianSalePriceAtAuction.tsx, src/Apps/MyCollectionInsights/myCollectionInsightsRoutes.tsx, src/Apps/Settings/Routes/Insights/Components/InsightsMedianSalePrice.tsx, src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsMedianSalePrice.jest.tsx, src/routes.tsx
This PR solves [CX-2942]
- This PR adds the median sale price at auction screen wrapper.
**Note:**
- It's still not yet clear if we will hide or show the navigation and footer.
- The medium type will be sent as a query param, this is in order to support deep linking to the same page if needed later in App. When none is specified or a wrong one is specified, the fallback should be ideally `All`, as we do in App.
https://user-images.githubusercontent.com/11945712/196888467-a6e0c66e-9ffe-4bed-88f9-d958a12fab72.mov
[CX-2942]: https://artsyproduct.atlassian.net/browse/CX-2942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-2942): create median sale price screen wrapper

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
I can't be sure but I believe the intention here was to set the page title but rather than using the react-head approach we were using the MetaTags approach. This didn't work well because it caused us to render _all_ the meta tags again (incorrectly) so this PR just gets us back on track.
https://artsyproduct.atlassian.net/browse/GRO-1357
=> fix: Remove bogus canonical tag from auction results GRO-1357

src/Apps/Feature/Components/FeatureFeaturedLink.tsx
Working on removing the old typography from Palette completely. This just wouldn't have worked, but good to remove the reference regardless.
=> fix: removes serif reference

src/Apps/PriceDatabase/Components/PriceDatabaseBenefits.tsx
Over in #image-processing we noticed that [this page](https://www.artsy.net/price-database) was serving up PNGs up to 3mb in size, rather than compressed images.
This changes those 3 large images to
- use the optimized/resized urls generated in Forque ([example](https://tools.artsy.net/uploads/images%2Fkehinde_wiley_portrait_of_nelly_moudime_ii.png))
- specify a `src` as well as a `srcSet` for high-dpi screens
- add an `alt` tag for a11y
|Before|After|
|---|---|
|![before](https://user-images.githubusercontent.com/140521/197033729-ab086329-0ae1-49a5-a4aa-474f89177ae8.jpg)|![after](https://user-images.githubusercontent.com/140521/197033730-4bb97299-ff8d-4edb-bd02-cdedce81f3da.jpg)|
=> perf: right-size image sources for /price-database

src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2.jest.tsx, src/Components/Artwork/SidebarExpandable.tsx
This PR solves [FX-4386]
Adds analytics to sidebarExpandable component for `shipping and taxes` & `Artsy Guarantee` sections
[FX-4386]: https://artsyproduct.atlassian.net/browse/FX-4386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4386): add analytics to expandable sidebar sections

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2PartnerInfo.tsx
This PR solves [FX-4326]
Removes underline from partner link in sidebar
|Before|After|
|---|---|
|<img width="1911" alt="Screenshot 2022-10-21 at 11 53 23" src="https://user-images.githubusercontent.com/21178754/197168995-9488c014-85d7-4a1f-8735-7240eee6818f.png">|<img width="2560" alt="Screenshot 2022-10-21 at 11 52 44" src="https://user-images.githubusercontent.com/21178754/197169039-f3c01536-41ca-42e0-a0a3-0d3f80c4014e.png">|
|<img width="417" alt="Screenshot 2022-10-21 at 11 53 11" src="https://user-images.githubusercontent.com/21178754/197169031-0615c359-ce42-42d8-8946-36a9964d179d.png">|<img width="387" alt="Screenshot 2022-10-21 at 11 52 55" src="https://user-images.githubusercontent.com/21178754/197169036-73383703-9028-46a3-bd95-aab632ee69b7.png">| …
=> fix(FX-4326): artworksidebar > partner link should not be underlined

src/Components/FollowButton/FollowArtistButton.tsx, src/Components/FollowButton/FollowGeneButton.tsx, src/Components/FollowButton/FollowProfileButton.tsx, src/Components/FollowButton/__tests__/useFollowButtonTracking.jest.ts, src/Components/FollowButton/useFollowButtonTracking.ts
This PR solves [FX-4390]
It appears that ever since the refactor in https://github.com/artsy/force/pull/10434 the follow buttons for artist/gene/profile have been _always_ sending `followedPartner` / `unfollowedPartner` payloads instead of the ones appropriate to their owner type.
This PR 
- introduces a new `ownerType` arg for `useFollowButtonTracking` to solve that
- updates follow button call sites accordingly
- adds test coverage 
Selected examples for…
|Before|After|
|---|---|
|<img width="100%" alt="follow before" src="https://user-images.githubusercontent.com/140521/197247043-e28b9c65-d284-4efd-b72d-59533e5de537.png">|<img width="100%" alt="follow after" src="https://user-images.githubusercontent.com/140521/197247045-83644232-c6cf-4a0a-b106-d3a780078b …
=> fix: follow buttons’ tracking payloads

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx, src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2.jest.tsx
Realized on https://github.com/artsy/eigen/pull/7526#discussion_r1001632469 that we don't need to check for isSold in order to display the Artsy Guarantee section since `isEligibleForArtsyGuarantee` field will return `false` if the artwork `isSold = true`
=> fix: remove is sold from artsy guarantee check

src/Apps/Order/Components/BankAccountPicker.tsx, src/Apps/Order/Components/PollAccountBalance.tsx, src/Apps/Order/Components/__tests__/BankAccountPicker.jest.tsx, src/Apps/Order/Routes/Payment/PaymentContent.tsx, src/Apps/Order/Routes/Payment/index.tsx, src/Components/BankDebitForm/BankDebitForm.tsx, src/Components/BankDebitForm/BankDebitProvider.tsx, src/Components/BankDebitForm/__tests__/BankDebitForm.jest.tsx, src/Components/BankDebitForm/__tests__/BankDebitProvider.jest.tsx, src/Utils/logger.ts
This PR solves [TX-689]
This PR extends error logging to Sentry in the payment route of the checkout flow. With these changes, we will be able to spot error by orderId and payment method in Sentry. 
Note that I could not find a way to log mock errors that I threw locally to Sentry in order to test the shape of the logged objects. I am intending to do the QA after this work is on staging. If anyone has a way to accomplish this locally, please let me know 🙏 
[TX-689]: https://artsyproduct.atlassian.net/browse/TX-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> perf(TX-689): Extend error logging in payment route

src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx, src/Utils/Hooks/useAuthIntent/index.ts
Related Force PR: artsy/force#11171
This PR solves [FX-4388]
Review app: [show-register-to-bid-popup-after-auth](https://show-register-to-bid-popup-after-auth.artsy.net/)
Artwork example: https://show-register-to-bid-popup-after-auth.artsy.net/artwork/henri-van-noordenburg-untitled-1
https://user-images.githubusercontent.com/3513494/197199913-824e6591-d82e-413f-8255-d5a92cc2d18b.mp4
[FX-4388]: https://artsyproduct.atlassian.net/browse/FX-4388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4388): display register to bid popover after auth flow

src/Apps/MyCollectionInsights/Routes/MyCollectionInsightsMedianSalePriceAtAuction/Components/MyCollectionInsightsSelectArtistModal.tsx, src/Apps/MyCollectionInsights/Routes/MyCollectionInsightsMedianSalePriceAtAuction/MyCollectionInsightsMedianSalePriceAtAuction.tsx, src/Apps/MyCollectionInsights/myCollectionInsightsRoutes.tsx, src/__generated__/MyCollectionInsightsMedianSalePriceAtAuction_artist.graphql.ts, src/__generated__/myCollectionInsightsRoutesQuery.graphql.ts
This PR solves [CX-2943]
This PR adds the select artist screen as a **modal**. The reason behind that is as discussed with Pierluca and Dascha the ease of the implementation and to use the existing `ModalDialog`.
https://user-images.githubusercontent.com/11945712/197208057-c47fb121-db30-4c83-8cfa-f8942eddca35.mov
[CX-2943]: https://artsyproduct.atlassian.net/browse/CX-2943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-2943): add select artist modal to median sale price

jest.config.js, src/Apps/ArtQuiz/__tests__/ArtQuizResultsLoader.jest.tsx, src/Apps/Artist/Routes/CV/Components/ArtistCVGroup.tsx, src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2ArtsyGuarantee.jest.tsx, src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx, src/Components/NavBar/__tests__/NavBar.jest.tsx, src/Components/Notifications/__tests__/MarkAllAsReadPanel.jest.tsx, src/Components/Notifications/__tests__/Notifications.jest.tsx, src/DevTools/mockReactI18n.tsx, src/DevTools/setupTestWrapper.tsx, src/System/i18n/config.ts, src/System/i18n/i18n.ts
This fixes the mock so that you don't have to use a monkey patched render etc.
=> fix(i18n): globally mocks translation function

src/Apps/Components/AppShell.tsx, src/Components/NavBar/NavBar.tsx, src/Components/Onboarding/Components/OnboardingFollows.tsx, src/Components/Onboarding/Components/OnboardingProgress.tsx, src/Components/Onboarding/Views/OnboardingFollowArtists.tsx, src/System/Router/Boot.tsx
Noticed that components weren't adhering to the design system in onboarding. Turns out it was sitting inside of the v2 theme context. This PR removes that possibility from happening in the future.
=> fix(theme): uses a single theme provider

src/Utils/logger.ts
Adding a type guard for `shouldLogErrorToSentry` property in error logger.
=> fix: Type guard in logger

src/Apps/ArtQuiz/ArtQuizResults.tsx, src/Apps/ArtQuiz/ArtQuizWelcome.tsx, src/Apps/ArtQuiz/__tests__/ArtQuizResults.jest.tsx, src/Apps/ArtQuiz/__tests__/ArtQuizResultsLoader.jest.tsx, src/Apps/ArtQuiz/artQuizRoutes.ts, src/System/i18n/locales/en-US/translation.json
This PR solves [GRO-1258]
This PR creates a basic structure for the user's art quiz results.
🚧Still to-do🚧
[GRO-1258]: https://artsyproduct.atlassian.net/browse/GRO-1258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(art-quiz): create results page structure

src/Apps/Artist/Components/ArtistHeader/ArtistHeader.tsx
Those `none` values were causing the follow count to be suppressed so this just restores them. Looks like this:
https://artsyproduct.atlassian.net/browse/GRO-1382
=> fix: Restore artist follow count to all breakpoints GRO-1382

src/Apps/Artwork/ArtworkApp.tsx, src/Apps/Artwork/Components/UnlistedBannerModal.tsx, src/Components/UnlistedArtworkBanner.tsx, src/Components/__tests__/UnlistedArtworkBanner.jest.tsx, src/__generated__/ArtworkApp_artwork.graphql.ts, src/__generated__/UnlistedArtworkBanner_Test_Query.graphql.ts, src/__generated__/UnlistedArtworkBanner_partner.graphql.ts, src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
This PR solves: [PX-5250]
This PR adds a non-scrollable full width banner to the Artwork page when it's been `unlisted`. This lets the collector know what that this artwork is not findable to the general public on Artsy. The banner contains a link that pops open a modal that further explains the value proposition.
[PX-5250]: https://artsyproduct.atlassian.net/browse/PX-5250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat:PX-5250 unlisted artwork banner

src/Apps/Order/Routes/NewPayment/index.tsx
This PR solves [TX-824]
This PR attempts to fix the problem that buyers cannot fix a failed payment with credit card initially and have to try a second time to succeed. 
The detected problem was that by the time the buyer is prompted to authenticate their purchase through 3D Security, our credit card picker has already presented the creditCardId. When the buyer re-lands on the page after authorising the purchase through the Stripe modal, we lose the creditCardId initially acquired and make an API call to MP's newPayment mutation with creditCardId missing in the payload. 
This PR makes sure that we have the creditCardId after the 3D security modal has been closed. 
https://user-images.githubusercontent.com/42584148/199185863-f74c74f0-c93c-4e89-b45c-fa395a4a11 …
=> fix(TX-824): Type guard for credit card picker in new payment

src/Utils/Hooks/__tests__/useImagePerformanceObserver.jest.ts, src/Utils/Hooks/useImagePerformanceObserver.ts
Closes [GRO-1406](https://artsyproduct.atlassian.net/browse/GRO-1406)
* I can't use the `pageType` tagging that the page load metrics use. Those rely on something server-side and aren't updated as the client-side route changes. Instead I went with just pulling off the first path dir, tagged with `root-path`. Now that we no longer have top-level vanity routes, this should be sufficent: `artwork`, `article`, `collect`... etc.
* I added a tag for device pixel ratio. Not sure if this is necessary but would be nice to have to better determine where large images are coming from.
* I didn't add a cap to the transfer size because I just don't know where that top is. It'd be good to get some insight here.
=> chore(volley): updates image metrics

src/Utils/Hooks/__tests__/useImagePerformanceObserver.jest.ts, src/Utils/Hooks/useImagePerformanceObserver.ts
Rounds the device pixel ratio to 1 or 2 since we only serve 1x or 2x images.
=> fix(useimageperformanceobserver): rounds to 1x or 2x

src/Apps/Artwork/Components/ArtworkVideoPlayer/ArtworkVideoPlayer.tsx
This temporarily removes the background frame color on the video while we investigate other issues with vimeo possibly returning wrong dimensions. For now this fixes the issue seen:
before: 
after:
=> fix(video): Temporarily remove bg color for now

src/Components/Notifications/NotificationsEmptyStateByType.tsx, src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
This PR solves [FX-4425]
- change "Set alerts for artworks you're hunting for." -> "Set alerts for artworks you're seeking”
- "tap" should be "select" when on web.
- the quote marks around "Create Alert." in the body text should be curly quotes, with the period inside the quote marks.
=> fix(FX-4425): copy changes on empty activity panel

src/Apps/Artwork/Components/OtherWorks/index.tsx
This PR solves [FX-4422]
Recent investigations into the flapping Elasticsearch monitors revealed that the `OtherWorksQuery` on the artwork page was firing well before its associated content was scrolled into view. 
While this might be fine for most queries, the `more_like_this` Elasticsearch queries that back the `OtherWorksQuery` are known to be slower since the ES upgrade, so this seems like a worthwhile optimization.
https://user-images.githubusercontent.com/140521/200079411-0336b544-1a35-4d96-a9b0-3fc9ea6f1a64.mov
[FX-4422]: https://artsyproduct.atlassian.net/browse/FX-4422?atlOrigin=eyJpIjoiNWRkNTljNz …
=> perf: make OtherWorksQuery even lazier

src/Apps/Order/Components/SavedAddressItem.tsx
This PR solves [TX-861]
This PR improves the accessibility of the order app by making sure all buttons / radios / inputs are able to be tab navigated and keypress clickable. 
So far I've only discovered one failing button --> the edit button. 
I've also noticed that the modal close buttons are also failing, but I will complete this in a separate Palette PR. Please let me know if you see anything else!
[TX-861]: https://artsyproduct.atlassian.net/browse/TX-861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-861): improve accessibility tabbing on order app 

src/Apps/Artist/Routes/WorksForSale/Components/ZeroState.tsx, src/Components/ArtworkGrid/ArtworkGridEmptyState.tsx
Re: [GRO-1424](https://artsyproduct.atlassian.net/browse/GRO-1424)
Temporarily removing the `Sticky` surrounding the empty states here while investigating. This bug is almost certainly caused by my work with the `Jump` component but it's hard to pinpoint because the filter has such a convoluted component architecture.
Disabling sticky here while I try to set up a clean room repro of the problem in Storybook.
=> fix(artist): temporarily removes sticky zero state while investigating infinite loop render bug

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilter.tsx, src/Apps/Artist/Routes/WorksForSale/Components/ZeroState.tsx, src/Apps/Example/Routes/ArtworkFilter/ExampleArtworkFilterRoute.tsx, src/Components/ArtworkGrid/ArtworkGridEmptyState.tsx
Closes: [GRO-1424](https://artsyproduct.atlassian.net/browse/GRO-1424)
I wasn't actually able to recreate this bug in Storybook, but my thinking is that it has to do with the Sticky being declared in one component render body, then passed through context down which is then nested inside of another Sticky. Very confusing and hopefully a rare happening.
But: please, *please*, if you see components declared in a render body: please call it out in review. This is a very common problem and always leads to bugs. There is *never* a good reason to do it.
=> fix(filter): fixes infinite render bug

src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx, src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowserLarge.tsx, src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowserSmall.tsx, src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowserLarge.jest.tsx, src/Apps/Artwork/Components/ArtworkVideoPlayer/ArtworkVideoPlayer.tsx, src/Components/DeepZoom/DeepZoom.tsx, src/Utils/Hooks/useDetectActivity.ts
OK — there's no ticket here; so we can take or leave this. Just wanting to make it so that videos fill the space more optimally, as if they were sized like the images.
Previously we had `70px` of horizontal padding on either side to accommodate the next/previous arrows. This PR does a few things:
* Removes that padding so that the arrows overlay the video directly, just like they currently do on images.
* Changes the blend mode to difference so that they are always visible.
* Extracts the idle detection hook that I used in the deep zoom viewer to hide the nav after a few seconds of inactivity and to redisplay it when you move the cursor.
* Reduced the click area of the arrows so as to not interfere with the video UI.
* Added index support to the progress dashes at the bottom so those go …
=> feat(artwork): hide next/prev nav when idle

src/Apps/Order/Routes/Payment/PaymentContent.tsx, src/Apps/Order/Routes/__tests__/Payment.jest.tsx
This PR solves [TX-875]
This PR implements the new design for how we display "Us bank accounts only" copy for ACH payment method. 
[TX-875]: https://artsyproduct.atlassian.net/browse/TX-875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-875): Implement new 'us accounts only' design

src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
This PR solves [CX-3146]
- Without this, updating a submission as a logged out user will fail with `Submission Not Found`
[CX-3146]: https://artsyproduct.atlassian.net/browse/CX-3146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix(CX-3146): Add session_id property in UploadPhotos step

src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/CareerHighlightModalPromoStep.tsx, src/Apps/Settings/Routes/Insights/Components/CareerHighlights/CareerHighlightsModal/Components/CareerHighlightsModal.tsx, src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightCard.tsx, src/Apps/Settings/Routes/Insights/Components/CareerHighlights/InsightsCareerHighlightPromoCard.tsx, src/Apps/Settings/Routes/Insights/Components/CareerHighlights/__tests__/InsightsCareerHighlightRail.jest.tsx
This PR solves [CX-3149]
This PR updates the copy of the last step in the Career Highlights Modal, and adds keyboard accessibility
|--|--|
| ![image](https://user-images.githubusercontent.com/20655703/201944115-46552180-eb4e-4a58-b087-a06274851aef.png) | ![image](https://user-images.githubusercontent.com/20655703/201943988-828a164b-56c4-49a9-9af0-c9d873d916df.png) |
[CX-3149]: https://artsyproduct.atlassian.net/browse/CX-3149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix(CX-3149): Update Career Highlights modal copy

src/Apps/Home/Components/HomeContentCards.tsx
This PR uses our Skeleton components to draw a placeholder for the content cards so that we avoid layout shifting. For the text I used an example of content from a card that's running today. I'll play with this on production to see if it's jarring and we can adjust that content as needed.
<details>
<summary>Here's some screenshots</summary>
</details>
https://artsyproduct.atlassian.net/browse/GRO-1324
=> chore: Add placeholder content cards GRO-1324

src/client.tsx
This cleans up our `client.tsx` entrypoint to remove unnecessary bundle-splitting and complexity. Should fix the error noticed [in Slack here](https://artsy.slack.com/archives/C04BPTCCZ9N/p1668545403212579?thread_ts=1668544247.837469&cid=C04BPTCCZ9N).
=> chore(client): Cleanup client entrypoint

.eslintrc.js
Simply ignoring the warnings leads to very difficult to refactor components and hooks. There's very little effort involved with actually addressing the errors. Ignoring them tends to paper over actual bugs that will when the component is extended or altered. If we're to ignore errors then you should be forced to include a comment explaining why you are doing so (there's valid reasons but they tend to be rare in practice.)
=> chore: errors on exhaustive-deps

src/Apps/Consign/Components/SubmissionStepper.tsx, src/Apps/Consign/Hooks/useSubmissionFlowSteps.ts, src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx, src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx, src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx, src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx, src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx
This PR solves [CX-3151]
- Fixes the duplication of MyCollection Artwork after submission. 
- Fixes submission_id not being updated on MyCollection Artwork submission because the source is forced to `web_inbound` instead of `my_collection`
[CX-3151]: https://artsyproduct.atlassian.net/browse/CX-3151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-3151): fix duplication of MyCollection after submission

src/Apps/NewForYou/NewForYouApp.tsx, src/Apps/NewForYou/__tests__/NewForYouApp.jest.tsx
This PR solves [GRO-1372]
When a user lands on `/new-for-you` from email, we know the user has an account, but we’re unable to display their recommendations without being logged in. This PR updates the copy to reflect the fact that we know the user already has an Artsy account.
[GRO-1372]: https://artsyproduct.atlassian.net/browse/GRO-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(GRO-1372): Update logged out copy

src/Components/NavBar/__tests__/NavBarSubMenu.jest.tsx, src/Components/NavBar/menuData.ts
This PR solves [FX-4449]
| <img width="1000" alt="before" src="https://user-images.githubusercontent.com/3513494/202426496-7725e5fc-2a04-4f59-8f25-998d5e3260ec.png"> | <img width="1000" alt="after" src="https://user-images.githubusercontent.com/3513494/202426532-2fc01ff5-036f-48bf-bda1-8e4d77226398.png"> | 
[FX-4449]: https://artsyproduct.atlassian.net/browse/FX-4449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(FX-4449): change navigation link copy

src/Components/NavBar/NavBarLoggedInActions.tsx, src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotificationsIndicator.tsx, src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenuNotificationsIndicator.jest.tsx, src/Components/NavBar/NavBarNotificationIndicator.tsx
This just ensures we use a consistent notification indicator style on both notifications and conversations.
I don't *think* there should be any merge conflicts with https://github.com/artsy/force/pull/11375 but we should get that merged too!
=> fix(navbar): uses consistent notifications style

src/Apps/Home/Components/HomeContentCard.tsx, src/Apps/Home/Components/HomeContentCards.tsx, src/Components/HeroCarousel/HeroCarousel.tsx, src/Components/HeroCarousel/HeroCarouselLarge.tsx, src/Components/HeroCarousel/HeroCarouselSmall.tsx
This PR updates the Braze content card code to use their SDK to send events. Because we're loading these things ourselves, we are responsible for sending clicks and impressions so that's what this PR does.
Note that I started by duplicating the `HomeHeroUnit` and then spent about a dozen commits pruning it down to just what I needed in this case. Ultimately we'll end up removing that component once we fully ship Braze content cards but not yet. We still use a query param to load the Braze ones so this acts as a feature flag for now. Hopefully we can remove all that stuff next week!
While this project was meant to focus only on replicating how the existing cards behave we had an opportunity to chat about the images and improve things there - more here: …
=> feat: Send content card events to braze GRO-1324

src/Apps/Artwork/Components/ArtworkDetails/index.tsx
This is a lazily-loaded component, which when properly fetched renders some data (which we'd like to target via Integrity). I _think_ (based on looking at a couple of analogous examples), that this may aid in that, it's a proper div which can be scrolled to (kicking off the query instead of more arbitrary scrolling), and then data found as normal.
=> chore: add box around artwork details query renderer for cypress targeting

src/Components/NavBar/NavBar.tsx, src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenu.tsx, src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenu.jest.tsx, src/Components/NavBar/menuData.ts
This PR solves [GRO-1409]
The goal of this PR is to clean up the nav bar a bit as part of the fix it sprint. NFTs now live under artwork mediums where they belong :)
Desktop
https://user-images.githubusercontent.com/23108927/203132713-f8d7cae2-4cc5-4ff6-af5b-cae4bb7bb376.mp4
MWEB
https://user-images.githubusercontent.com/23108927/203132974-ad27c625-f9cd-489f-a2f9-e77fbf4b525e.mp4
[GRO-1409]: https://artsyproduct.atlassian.net/browse/GRO-1409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (fix)[GRO-1409] move NFTs from home nav to artwork medium

src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx, src/Apps/Auction/Components/AuctionArtworkFilter.tsx, src/Apps/Collect/Routes/Collection/Components/CollectionArtworksFilter.tsx, src/Apps/Fair/Routes/FairArtworks.tsx, src/Apps/Search/Components/SearchResultsArtworksFilters.tsx, src/Apps/Search/Routes/SearchResultsArtworks.tsx, src/Components/ArtworkFilter/ArtworkFilters/index.tsx
This PR solves [FX-4072]
* [Artist](https://keyword-filter.artsy.net/artist/jean-michel-basquiat/works-for-sale)
* [Artist Series](https://keyword-filter.artsy.net/artist-series/zao-wou-ki-zhao-wu-ji-abstractions)
* [Collect](https://keyword-filter.artsy.net/collect)
* [Collection](https://keyword-filter.artsy.net/collection/takashi-murakami-pillows)
* [Fair](https://keyword-filter.artsy.net/fair/1-54-paris-2021/artworks)
* [Gene](https://keyword-filter.artsy.net/gene/color-field-painting)
* [Show](https://keyword-filter.artsy.net/show/dab-art-art-in-the-time-of-corona)
* [Tag](https://keyword-filter.artsy.net/tag/horse)
* [Auctions](https://keyword-filter.artsy.net/auction/artsy-x-seoul-auction-contemporary-icons)
* [Auction …
=> feat(FX-4072): add Keyword filter for other grids

src/Components/Inquiry/Views/InquiryBasicInfo.tsx, src/Components/Inquiry/__tests__/Views/InquiryBasicInfo.jest.tsx
This PR solves [CX-3130]
This PR removes the "Share followed artists, categories, and galleries" from the inquiry flow
| -- | -- |
| ![image](https://user-images.githubusercontent.com/20655703/203355248-709cb446-90e9-467a-9b0f-9af75e17dfa9.png) | ![image](https://user-images.githubusercontent.com/20655703/203355088-be106142-f3ef-4554-b988-d5ef64192051.png) |
[CX-3130]: https://artsyproduct.atlassian.net/browse/CX-3130
=> fix(CX-3130): Remove "share followed artists..." from Inquiry Flow

src/Apps/Article/ArticleApp.tsx, src/Apps/Articles/ArticlesApp.tsx, src/Apps/Articles/NewsApp.tsx, src/Apps/Authentication/Components/ModalContainer.tsx, src/Apps/Authentication/Components/__tests__/ModalContainer.jest.tsx, src/Apps/Authentication/Utils/__tests__/helpers.jest.ts, src/Apps/Authentication/Utils/__tests__/useAuthForm.jest.ts, src/Apps/Authentication/Utils/helpers.ts, src/Apps/Authentication/Utils/useAuthForm.ts, src/Apps/Authentication/__tests__/authenticationRoutes.jest.tsx, src/Components/Authentication/Types.ts, src/Components/Authentication/__tests__/FormSwitcher.jest.tsx, src/Utils/Hooks/useScrollToOpenArtistAuthModal.ts
I guess at some point this must have done something, but no longer. Previously whatever was passed as `destination` was set as a cookie named `"destination"`. This cookie is never actually checked anywhere.
=> refactor(auth): removes destination

src/Components/Inquiry/Components/InquiryBackdrop.tsx, src/Components/Inquiry/Inquiry.tsx
This PR solves [CX-3139]
This PR updates the inquiry flow to prevent users from closing the modal by clicking the background, it also updates the width of the Confirmation view
[CX-3139]: https://artsyproduct.atlassian.net/browse/CX-3139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-3139): Update Inquiry flow user experience

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2ArtsyGuarantee.tsx, src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2.jest.tsx, src/Apps/Artwork/Components/ArtworkSidebar2/__tests__/ArtworkSidebar2ArtsyGuarantee.jest.tsx, src/Apps/Artwork/Components/TrustSignals/SecurePayment.tsx, src/System/i18n/locales/en-US/translation.json
Old copy: Be covered by the Artsy Guarantee
New copy: Be covered by the Artsy Guarantee when you checkout with Artsy
Old copy: Secure Payment
New copy: Secure Checkout
Jira: [FX-4455](https://artsyproduct.atlassian.net/browse/FX-4455)
**Before**
**After**
=> chore(artwork): update secure payment copy in artsy guarantee section

src/Apps/Artwork/Components/RelatedWorks/index.tsx
Follow-up to #11432
A small tweak to address the [observed lag](https://artsy.slack.com/archives/C9SATFLUU/p1669835022592399) in rendering the new Related Works rail, as you scroll down the page.
=> chore: tune RelatedWorks laziness

src/Apps/CollectorProfile/Routes/SavesAndFollows/CollectorProfileSavesAndFollowsRoute.tsx, src/Apps/CollectorProfile/collectorProfileRoutes.tsx, src/__generated__/CollectorProfileSavesAndFollowsRoute_me.graphql.ts, src/__generated__/collectorProfileRoutes_SavesAndFollowsRouteQuery.graphql.ts
This PR solves [CX-3177]
- Add saved and follows to the collector profile
**Note:**
Follow up work once this is released
[CX-3177]: https://artsyproduct.atlassian.net/browse/CX-3177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-3177): add saved and follows to collector profile

cypress/e2e/home.cy.ts, src/Apps/Home/Components/HomeContentCards/HomeContentCards.tsx, src/Apps/Home/Components/HomeContentCards/PlaceholderCards.tsx, src/Apps/Home/Components/HomeContentCards/__tests__/HomeContentCards.jest.tsx, src/Apps/Home/HomeApp.tsx
This PR will launch the Braze content cards on web! 🎉 
It also fixes (at least) two things:
1. A race condition where Braze cards aren't rendered
2. A bug where client-side routing breaks the call to Braze for cards
So yeah, let's merge this tomorrow morning and behold the glory.
ALSO
Over on https://github.com/artsy/force/pull/11456 I thought I was a real hotshot and knew it was fine to pend that spec but it turns out it was revealing that race condition bug. 😬 This fixes the bug and also makes the test pass IMAGINE THAT.
Finally I wanted to mention that in a follow up to this PR I will be deleting the `HomeHeroUnit` code. I could have done that here but for my sanity I want it to be easy to rollback in case something goes wrong.
https://artsyproduct.atlassian.net/browse/GRO-1324
/cc …
=> feat: Launch Braze Content Cards GRO-1324

src/Apps/Partner/Components/PartnerArtists/PartnerArtistsCarousel/PartnerArtistsCarousel.tsx, src/Components/Cells/CellPartnerArtist.tsx, src/Components/Cells/__tests__/CellPartnerArtist.jest.tsx, src/__generated__/CellPartnerArtistFragmentContainer_Test_Query.graphql.ts, src/__generated__/CellPartnerArtist_partnerArtist.graphql.ts, src/__generated__/PartnerArtistsCarouselRendererQuery.graphql.ts, src/__generated__/PartnerArtistsCarousel_partner.graphql.ts
This PR solves [PX-5309]
This PR addresses an issue where the artwork image on an artist rail is associated with an Artsy wide Artist instead of the PartnerArtist as it should be. 
Current incorrect image: 
After update Correct Image:
[PX-5309]: https://artsyproduct.atlassian.net/browse/PX-5309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix:ensure artist carousel image is scoped to partner artist

src/Components/Notifications/NotificationItem.tsx, src/Components/Notifications/__tests__/NotificationItem.jest.tsx, src/__generated__/NotificationItem_item.graphql.ts, src/__generated__/NotificationItem_test_Query.graphql.ts, src/__generated__/NotificationsListNextQuery.graphql.ts, src/__generated__/NotificationsListQuery.graphql.ts, src/__generated__/NotificationsList_test_Query.graphql.ts
This PR solves [FX-4476]
Re-introduces counts but using a new `objectsCount` field
[FX-4476]: https://artsyproduct.atlassian.net/browse/FX-4476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4476): activity panel notifications counts

src/Apps/Debug/DebugAuth.tsx, src/Apps/Debug/debugRoutes.tsx, src/Components/AuthDialog/AuthDialog.tsx, src/Components/AuthDialog/AuthDialogContext.tsx, src/Components/AuthDialog/Components/AuthDialogSocial.tsx, src/Components/AuthDialog/Components/AuthTermsCheckboxes.tsx, src/Components/AuthDialog/Hooks/__tests__/useAfterAuthenticationRedirect.jest.ts, src/Components/AuthDialog/Hooks/useAfterAuthentication.ts, src/Components/AuthDialog/Hooks/useAfterAuthenticationRedirect.ts, src/Components/AuthDialog/Hooks/useElligibleForOnboarding.ts, src/Components/AuthDialog/README.md, src/Components/AuthDialog/Views/AuthDialogForgotPassword.tsx, src/Components/AuthDialog/Views/AuthDialogLogin.tsx, src/Components/AuthDialog/Views/AuthDialogSignUp.tsx, src/Components/AuthDialog/Views/__tests__/AuthDialogForgotPassword.jest.tsx, src/Components/AuthDialog/Views/__tests__/AuthDialogLogin.jest.tsx, src/Components/AuthDialog/Views/__tests__/AuthDialogSignUp.jest.tsx, src/Components/AuthDialog/index.ts, src/Components/AuthDialog/useAuthDialog.tsx, src/Utils/EnableRecaptcha.tsx, src/Utils/Hooks/useAuthIntent/index.tsx, src/Utils/__tests__/auth.jest.ts, src/Utils/__tests__/sanitizeRedirect.jest.ts, src/Utils/auth.ts, src/Utils/recaptcha.ts, src/Utils/sanitizeRedirect.ts, src/__generated__/AuthDialogSignUpQuery.graphql.ts, src/__generated__/AuthDialogSignUp_requestLocation.graphql.ts
I'm just going to open a draft here to update progress.
This is what's left on my TODO:
-------
https://user-images.githubusercontent.com/112297/202306804-2693b7a0-acf1-4c3b-bef2-19ce4ae4650d.mov
=> feat(GRO-1437): rebuilds auth dialog

src/Apps/Home/Components/HomeContentCards/HomeContentCards.tsx, src/Apps/Home/Components/HomeContentCards/HomeErrorBoundary.tsx, src/Apps/Home/HomeApp.tsx
This PR adds an [Error Boundary](https://reactjs.org/docs/error-boundaries.html) to the rendering of the Braze content cards on the homepage. When an error is thrown, it'll catch it, log it and then render the fallback cards.
This doesn't really solve the problem but it's a better user experience. What I hope to see is for these errors to show up in Sentry so my next step after this lands is to figure out why we aren't seeing that.
/cc @artsy/grow-devs @isakelaris
=> Catch more content card errors

src/Server/middleware/userRequiredMiddleware.ts
This PR solves [CX-322]
Added "/my-collection/artworks(.*)", to the USER_REQUIRED_ROUTES in the userRequirediddleWare
https://user-images.githubusercontent.com/36167539/206203347-dacefd92-dbd0-4407-8d62-45e09113b475.mov
[CX-322]: https://artsyproduct.atlassian.net/browse/CX-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-322): /my-collection/artworks/new  is opening for logged out user

package.json, src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx, src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx, src/Apps/Partner/Components/__tests__/PartnerViewingRooms/ViewingRoomCard.jest.tsx, src/Components/__tests__/MetaTags.jest.tsx, src/Utils/__tests__/resized.jest.ts, src/Utils/__tests__/resizer.jest.ts, src/Utils/resized.ts, src/Utils/resizer.ts, yarn.lock
This switches our image proxy URL generation to use the new [@artsy/img](https://github.com/artsy/img) package.
I'm not expecting any differences or real errors though we'll probably see some spec failures as it now alphabetizes the query params. Let's see.
=> refactor: utilizes @artsy/img package to mint gemini urls

src/Apps/Artwork/Components/ArtworkSidebar2/ArtworkSidebar2.tsx
This PR solves [FX-4492]
Adds lot label even when bidding is closed to match eigen's behavior.
Screenshots:
|BiddingClosed||
|---|---|
|<img width="422" alt="Screenshot 2022-12-12 at 10 19 21" src="https://user-images.githubusercontent.com/21178754/207013955-01bcf93f-8af4-407e-9fff-27e3cefceff3.png">|<img width="1000" alt="Screenshot 2022-12-12 at 10 19 05" src="https://user-images.githubusercontent.com/21178754/207013965-ead70a1c-b8f4-4b52-ae58-895b838164fc.png">|
[FX-4492]: https://artsyproduct.atlassian.net/browse/FX-4492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
=> feat(FX-4492): add lot label even when lot is closed

src/Apps/Settings/SettingsApp.tsx, src/Components/TopContextBar.tsx
This PR solves [CX-3224]
This PR removes the Back to Collector Profile button in the Settings App header
[CX-3224]: https://artsyproduct.atlassian.net/browse/CX-3224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-3224): Remove "Back to Collector Profile" button

src/public/.well-known/assetlinks.json
This PR solves [MOPLAT-521]
Adds the signing cert sha for our playstore app to fix android app links. Play store console was complaining that our site was failing verification due to this missing. 
[MOPLAT-521]: https://artsyproduct.atlassian.net/browse/MOPLAT-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add play store signing sha to assetlinks.json

src/Apps/CollectorProfile/Routes/Insights/CollectorProfileInsightsRoute.tsx, src/Apps/CollectorProfile/collectorProfileRoutes.tsx, src/Apps/Settings/Routes/Insights/InsightsRoute.tsx, src/__generated__/collectorProfileRoutes_InsightsRouteQuery.graphql.ts
This PR solves [CX-3247]
I reused InsightsRouteFragmentContainer
I didn't hide the changes behind a FF, I think if it's off, the user won't be able to reach this page anyway. I would test the experience with FF off during the QA session when all work is done.
| Web | mWeb |
| --- | --- |
| <img width="672" alt="image" src="https://user-images.githubusercontent.com/36167539/207601707-2c8d0ca2-172b-4f67-93f4-65b54fcb9c1a.png"> | <img width="390" alt="image" src="https://user-images.githubusercontent.com/36167539/207601786-72a0d67a-a49f-47bc-986a-c9010cde5a79.png"> |
[CX-3247]: …
=> feat: add Insights to the my collection tab on collector profile

src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx, src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
Removed title from insights header
=> fix: remove title from insights page

src/Apps/ArtQuiz/Components/ArtQuizButton.tsx, src/Apps/ArtQuiz/Components/ArtQuizCard.tsx, src/Apps/ArtQuiz/Components/ArtQuizMain.tsx, src/Apps/ArtQuiz/Components/ArtQuizResultsLoader.tsx, src/Apps/ArtQuiz/Hooks/useSwipe.ts
I thought I'd open this early as draft and update it as I approach the problem, since we don't do animation that often.
I'm approaching this in 3 steps:
I'll be using the Web Animations API (edit: used simple transitions for the swipes for now), which is quite nice and well supported with our user base. I'll leave comments on these individual steps.
=> feat(artquiz): implements animation

src/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistList.tsx
Reverts artsy/force#11498
The original fix breaks the column arrangement in Chrome:
While not covering all cases in Firefox:
Reverting the fix so we can return the proper display in Chrome while we figure out a cross-browser solution
=> Revert "fix:prevent overlapping text on firefox"

src/Apps/ArtQuiz/Components/ArtQuizLikedArtworks.tsx, src/Apps/ArtQuiz/Components/ArtQuizResultsTabs.tsx, src/__generated__/ArtQuizLikedArtworksQuery.graphql.ts, src/__generated__/ArtQuizLikedArtworks_me.graphql.ts
Closes [GRO-1259](https://artsyproduct.atlassian.net/browse/GRO-1259)
-----
Outside chance I'll be forced to rewrite our Masonry grid component to handle the sort order correctly because the legacy ArtworkGrid isn't compatible with this connection type and is a mess. But we'll see how that plays out.
=> feat(art-quiz): renders saved artworks

src/Apps/Components/AppShell.tsx
Minor thing I noticed: with `hideFooter: true` the `HorizontalPadding` div would collapse a bit and create an overlapping scrollable div.
=> fix(appshell): fixes double scroll area on footer-less pages

src/Apps/Home/Components/HomeContentCards/HomeContentCards.tsx, src/Apps/Home/Components/HomeContentCards/__tests__/HomeContentCards.jest.tsx
We were able to reproduce this situation by returning an empty array of destinations and then supplying the Segment load function with an invalid write key. This sorta simulates getting Segment to be truthy but for the actual ready function to never fire. Ad blockers gonna block?
When I was pairing with @dzucconi we discussed whether that `brazeTimeout` is actually required and his feeling was that it would never do anything. I'm hesitant to remove it and I don't believe it will hurt anything so I'm leaving it but it's possible we could simplify things here by only having a single timeout. Seems like we should make incremental changes here on a Friday in the hopes of improving things and not introducing any regressions but maybe I'm being too cautious! 😝 …
=> fix: Use fallback cards when segment is never ready GRO-1474

src/Apps/Settings/Routes/Shipping/Components/SettingsShippingAddressForm.tsx
This PR solves [TX-962]
This PR adds a simple validation case for the phone number input in user settings' saved addresses. 
When a user is trying to edit their previously saved address and they have a single string with country code saved on that address, the phone number input looks like +1 +1XXXX, like so: 
Although this is not a severe problem, it's not ideal – especially considering the fact that the address might be used to make a purchase and the phone number might be passed to 3rd parties like ARTA. 
This PR adds a validation that if the national number includes + sign, we are prompting the user to remove it and select it from the countries dropdown. 
[TX-962]: https://artsyproduct.atlassian.net/browse/TX-962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> feat(TX-962): Prompt users to fix their number while editing an address

src/Apps/Home/Components/HomeContentCards/BrazeCards.tsx, src/Apps/Home/Components/HomeContentCards/HomeContentCards.tsx, src/Apps/Home/Components/HomeContentCards/__tests__/HomeContentCards.jest.tsx, src/Server/analytics/brazeMessagingIntegration.ts, src/Server/analytics/segmentOneTrustIntegration/setSegmentDestinationPref.ts, src/Typings/global.d.ts
This PR gets Force ready to use the latest Braze web sdk. The biggest change is that they renamed from `window.appboy` to `window.braze` but there were also a few breaking changes that this PR fixes. I have verified that the names of the cookies have NOT changed so nothing is needed to be done to add new cookies to our safelist.
Note: this will break things on production for some non-zero amount of time. Once this lands on production, then I will:
1. Sign into Segment's dashboard
2. Disable the old Braze integration for force-production
3. Enable the new Braze integration for force-production
Once the destinations have been updated then `window.braze` will be populated and we will have successfully migrated and Jon can go lay down. 😅 I'm assigning to myself and will usher this through …
=> chore: Migrate to latest Braze sdk GRO-1327

src/Apps/Conversation/Components/ConversationHeader.tsx, src/Apps/Conversation/Components/DetailsHeader.tsx
This PR solves [NX-3342]
- There was a mismatch between:
- when we showed the sidebar positioned as absolute, and
- when we showed the sidebar header to make it closable.
- The reason seems to be that using different values on the attributes (i.e.: `display={["none", "none", "flex", "flex"]`) wasn't applying the changes at the same widths as `breakpoints`. We use breakpoints to change the `position` of the sidebar ([see here](https://github.com/artsy/force/blob/main/src/Apps/Conversation/Components/DetailsSidebar.tsx#L34-L68))
- I made sure either DetailsHeader or DetailIcon is always visible (both allow you to close the sidebar)
- For that, I rewrote those attributes' media queries with useMatchMedia (still client-side queries), to match:
- when the …
=> fix(NX-3342): artwork detail wasn't closable on medium-size screens

src/Apps/Components/AppShell.tsx
Removing this temporarily as it's effecting the `clip` usage in the `FullBleedHeader` (interesting). I'm going to do a bit more of a comprehensive overhaul of the way the `AppShell` is structured along with some test routes and stories. This was only added to support the art-quiz; which isn't in production yet. So I'll just get that back to normal tomorrow morning.
=> fix(app-shell): temporarily removes height/overflow

src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx, src/__generated__/ArtQuizArtworks_me.graphql.ts, src/__generated__/artQuizRoutes_ArtworksQuery.graphql.ts
This PR does two things.
* The `/art-quiz/artworks` was erroring due to the fragment name property not being updated
* Added the `FullscreenBox` usage and updated the images to work with it.
=> fix(art-quiz): fixes fragment access; uses fullscreen box

src/Apps/ArtQuiz/ArtQuizApp.tsx, src/Apps/ArtQuiz/Components/ArtQuizButton.tsx, src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
Just remembered this little missing piece. Turns out to be the first time I've ever had a need for the [`useImperitiveHandle`](https://beta.reactjs.org/apis/react/useImperativeHandle) hook... so that's semi-interesting.
https://user-images.githubusercontent.com/112297/208749448-99808ab4-9747-431b-8579-5b5d6c5627d3.mov
-----
@laurabeth I'll just wait for https://github.com/artsy/force/pull/11599 to be merged and will rebase and fix the conflicts.
=> feat(art-quiz): trigger button animations on swipe

src/Apps/Artist/Routes/CV/ArtistCVRoute.tsx, src/Apps/Artist/Routes/CV/Components/ArtistCVGroup.tsx, src/__generated__/ArtistCVGroup_artist.graphql.ts, src/__generated__/ArtistCVRoute_Test_Query.graphql.ts, src/__generated__/ArtistCVRoute_viewer.graphql.ts, src/__generated__/artistRoutes_CVQuery.graphql.ts
@joeyAghion points out that
`solo_show=true` returns only solo shows
`solo_show=false` returns only group shows
Sending no `solo_show` parameter includes all results of either type
So this just restructures these arguments a bit to correctly return all fair booths, which may be classified as solo shows.
=> fix(artist): corrects logic for querying for fair booths

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx
Hide the collected artists section when the user hasn't collected any artists yet in the artwork upload flow (according to the Figma design).
=> fix: Hide collected artists when not existing in upload flow

src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx, src/Apps/Consign/Routes/SubmissionFlow/Utils/validation.ts
Addresses [CX-3270]
Simplify SWA phone number validation to only check if the phone number is a valid number.
```
"123" -> valid
"123abc" -> not valid
"123.4" -> not valid
```
[CX-3270]: https://artsyproduct.atlassian.net/browse/CX-3270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Simplify SWA phone number validation

src/Components/NavBar/useNavBarHeight.ts, src/Components/Sticky/Sticky.tsx
Review app: [ignore-header-offset](https://ignore-header-offset.artsy.net/)
Ignore header offset in sticky when `isEigen` is true, since the nav bar menu [will not be rendered](https://github.com/artsy/force/blob/aa217617287577dff6e9c2b2710df63fdcd195f0/src/Components/NavBar/NavBar.tsx#L58-L60)
https://user-images.githubusercontent.com/3513494/209139712-b7888df4-5338-4897-a807-46c0422d4e69.mp4
https://user-images.githubusercontent.com/3513494/209139795-d34d6a14-da3e-44e3-afaf-a7f91514f1be.mp4
=> feat: ignore header offset when `isEigen` is true

src/Apps/Conversation/Components/Conversation.tsx
This PR solves [NX-3209]
Remove check that prevents order modal from being rendered proper inside a conversation.
* We rely on `isActionable` in order to determine whether the order modal should be displayed - [ref](https://github.com/artsy/force/blob/9413fd9f88ba360bed598d70391c0e1d07098d3d/src/Apps/Conversation/Components/Conversation.tsx#L287-L298)
* `isActionable` only returns `true` in case an Artwork fits into one of the following scenarios: MO, MOI, MOOAEA, CBN - [ref](https://github.com/artsy/force/blob/9413fd9f88ba360bed598d70391c0e1d07098d3d/src/Apps/Conversation/Components/Conversation.tsx#L80-L83)
* An artwork can only fit into any of the conditions above if its availability is listed as `for sale` - …
=> fix(NX-3209): Remove isActionable check from OrderModal

src/Apps/Conversation/Components/OrderModal.tsx
This PR solves [NX-3408]
After updating the deprecated `Modal` component to `ModalDialog` (#11301), the iframe being rendered inside the modal had its width affected.
Changes here ensure the iframe will use 100% of the available width when the modal is triggered (this seemed to be the usual behaviour when we were using the `Modal` component).
Is this the best way to go here? As I understand we don't use this component today in any other spot besides the conversation.
[NX-3408]: https://artsyproduct.atlassian.net/browse/NX-3408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(NX-3408): Set the iframe to use the total width

src/Apps/MyCollectionInsights/myCollectionInsightsCollectorProfileRoutes.tsx, src/Apps/Settings/Routes/Insights/Components/InsightsMedianSalePrice.tsx, src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsMedianSalePrice.jest.tsx, src/__generated__/myCollectionInsightsCollectorProfileRoutesQuery.graphql.ts, src/routes.tsx
The type of this PR is: **Feat/Fix**
This PR solves [CX-3276]
Add a new route for median sale price
When assessing the page from collector profile, the URL should start with /collector-profile
[CX-3276]: https://artsyproduct.atlassian.net/browse/CX-3276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-3276): add new route for mediam sale price

src/Apps/ArtQuiz/ArtQuizApp.tsx, src/Apps/ArtQuiz/Components/ArtQuizFullscreen.tsx, src/Apps/ArtQuiz/Components/ArtQuizResultsLoader.tsx, src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx, src/Apps/ArtQuiz/Routes/ArtQuizWelcome.tsx, src/Apps/ArtQuiz/artQuizRoutes.tsx, src/Components/NavBar/useNavBarHeight.ts
OK, so this was a funny journey.
While although we can get the layout to naturally fill out the parent container now, it turns out we actually want to do something slightly different because of how `100vh` works on Mobile Safari. Basically: `top bar + document + bottom bar = 100vh`. Which means there would be a bit of overflow scrolling. So, where we need these fullscreen layouts we can use `ArtQuizFullscreen.tsx` which just — you guessed it — measures out the available viewport.
There actually _is_ a way to do this using the value `fill-available` but we'd need to patch this up to the `html` and `body` elements — which, I actually think we should. But for now this is going to work fine.
=> refactor(art-quiz): compromise on the layout

src/Apps/CollectorProfile/Components/CollectorProfileHeader/CollectorProfileHeader.tsx
This PR solves [CX-3284]
This PR updates the Settings icon size on the Collector Profile
|--|--|
| ![image](https://user-images.githubusercontent.com/20655703/209391162-5fd94b94-e268-4aa6-8506-9b9174dee2ed.png) | ![image](https://user-images.githubusercontent.com/20655703/209391149-ae126fb5-174e-41ab-b221-65a22de0052a.png) |
[CX-3284]: https://artsyproduct.atlassian.net/browse/CX-3284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-3284): Update Setting icon size in Collector Profile

src/Apps/Settings/Routes/EditProfile/Components/SettingsEditProfileFields.tsx
This PR solves [CX-3278]
This PR updates the Bio field to TextArea
| before | after |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/20655703/209381574-b2aa09d6-927f-4661-96da-87f83a3548f0.png) | ![image](https://user-images.githubusercontent.com/20655703/209381532-3a8bb15e-4d90-412e-ac49-e73b28c8cc0d.png) |
| ![image](https://user-images.githubusercontent.com/20655703/209381654-58afc1b7-175e-4599-9843-a7cb0f0eeafe.png) | ![image](https://user-images.githubusercontent.com/20655703/209381703-f88fc74a-0116-4bd3-9775-c2cc2fe95342.png) |
[CX-3278]: …
=> fix(CX-3278): Add Text area for bio in Collector Profile

src/Components/NavBar/Menus/NavBarUserMenu.tsx, src/Components/NavBar/Menus/__tests__/NavBarUserMenu.jest.tsx, src/Components/NavBar/NavBar.tsx, src/Components/Search/SearchInputContainer.tsx
This PR solves [CX-3225]
1. Remove “order history”, show it only for Admins
2. increase icon size to 22px - Collector Profile, Activity, Search
3. On the mweb "bell icon" should navigate the user to the activity panel
[CX-3225]: https://artsyproduct.atlassian.net/browse/CX-3225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-3225): navigation menu, address comments

src/Apps/Settings/Routes/Insights/Components/InsightsHeader.tsx, src/Apps/Settings/Routes/Insights/Components/__tests__/InsightsHeader.jest.tsx
This PR solves [CX-3287]
Show the Upload Artwork button only of the header is sticky
https://user-images.githubusercontent.com/36167539/209970666-e0bfb852-a100-48e1-a992-e3c5efe3ee5c.MOV
[CX-3287]: https://artsyproduct.atlassian.net/browse/CX-3287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-3287): Show the Upload Artwork button only if the header is sticky

src/Components/Artwork/Details.tsx
Add space to High Demand icon on artwork grid.
| --- | --- |
|<img width="499" alt="Screenshot 2022-12-29 at 15 12 04" src="https://user-images.githubusercontent.com/4691889/209965597-303f4e23-1a11-47a0-9d75-6fe3a9d4855a.png"> |<img width="508" alt="Screenshot 2022-12-29 at 15 11 21" src="https://user-images.githubusercontent.com/4691889/209965630-f8456c74-d8e0-422a-8f82-360facae79f0.png"> |
=> fix: Add space to High Demand icon on artwork grid

src/Apps/ArtQuiz/Hooks/useDislikeArtwork.ts, src/Apps/ArtQuiz/Hooks/useSaveArtwork.ts, src/Apps/ArtQuiz/Hooks/useUpdateQuiz.ts, src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx, src/__generated__/ArtQuizArtworks_me.graphql.ts, src/__generated__/artQuizRoutes_ArtworksQuery.graphql.ts, src/__generated__/useSaveArtworkMutation.graphql.ts, src/__generated__/useUpdateQuizMutation.graphql.ts
This PR solves [PROJECT-1487]
Adds necessary mutations: 
- Custom version of save artwork that doesn't allow for unsave on a second click. 
- updateQuiz 
- dislikeArtwork
Attached to save / dislike & close button.
=> feat(art-quiz): add mutation hooks

package.json, src/Apps/Debug/DebugAuth.tsx, src/Components/AuthDialog/AuthDialog.tsx, src/Components/AuthDialog/AuthDialogContext.tsx, src/Components/AuthDialog/Components/AuthDialogSocial.tsx, src/Components/AuthDialog/Hooks/useElligibleForOnboarding.ts, yarn.lock
This PR adds `AuthImpression` tracking and makes a change to the API to accept an `analytics` configuration field for clarity.
=> feat(authdialog): adds analytics tracking

src/Apps/Consign/Hooks/useSubmissionFlowSteps.ts, src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx, src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/__tests__/ContactInformation.jest.tsx, src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/__tests__/UploadPhotos.jest.tsx, src/Apps/Consign/consignFromCollectorProfileMyCollectionRoutes.tsx, src/Apps/Consign/consignFromMyCollectionRoutes.tsx, src/Apps/Consign/consignRoutes.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkImageBrowser/MyCollectionArtworkImageBrowser.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/MyCollectionArtwork.tsx
This PR redirects the old traffic from `/sell/submission/artwork-details` to the main sell page now `sell/submission`. It also removes the feature flag.
**Before**
https://user-images.githubusercontent.com/11945712/210546100-df38ff42-6605-4dd2-9a3d-d1c12aca52df.mov
**After**
https://user-images.githubusercontent.com/11945712/210546122-b9e3d45d-4193-4825-bf7e-3f68581a4eaf.mov
=> chore: redirect artwork-details nav request to main sell tab

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArworkSearch.tsx
This PR solves [CX-3308]
This PR increases the number of artworks in My Collection upload flow "Select Artwork" step. Later we might implement pagination or infinite scrolling. 
[CX-3308]: https://artsyproduct.atlassian.net/browse/CX-3308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Increase number of artworks in My Collection upload flow

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx, src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormMain.tsx
This PR resolves [CX-3296]
https://user-images.githubusercontent.com/11945712/210832556-fd7a38a7-bb65-46e3-9680-7b35888afff0.mov
Images take a while to be first in queue in Gemini and it's why they take a while to be fully ready
[CX-3296]: https://artsyproduct.atlassian.net/browse/CX-3296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: show existing artwork images from local store

src/Components/Authentication/Components/AuthenticationFooter.tsx, src/Components/Authentication/FormSwitcher.tsx, src/Components/Authentication/Views/SignUpForm.tsx, src/Components/Authentication/__tests__/Views/SignUpForm.jest.tsx
This removes the terms checkbox as it's no longer explicitly needed. Will open an Integrity pull request before merging.
| GDPR | Non-GDPR |
| ---- | ---- |
| ![](https://static.damonzucconi.com/_capture/GJWmbIg4.png) | ![](https://static.damonzucconi.com/_capture/6BGaEBGN.png)
=> feat(authentication): removes explicit terms checkbox

.circleci/config.yml
This job has been failing for a while with invalid credentials so I'm just cleaning it up by deleting it altogether.
=> Remove deepcrawl ci job

src/Apps/Order/Routes/Shipping/index.tsx, src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
This PR solves [TX-988]
This PR fixes the problem reported by Applause in the new app release. the problem is that when users select pick-up shipping option, type in their phone number, and they have a saved address, we are storing the phone number from the saved address instead of the typed-in number. 
https://user-images.githubusercontent.com/42584148/210779467-d95a41cf-e954-4ed9-8974-df3c51cb449f.mov
[TX-988]: https://artsyproduct.atlassian.net/browse/TX-988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(TX-988): correct phone number is committed for pickup orders

.secrets.baseline, src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx, src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionCreateArtwork.jest.tsx
We need to hide the artist selection **skip** button behind when the feature flag `"cx-my-collection-personal-artists-for-web"` is disabled. This is needed in case we want to enable the new uploading flow without allowing users to create artists (just in case 😄 )
=> fix: Hide artist selection skip button behind feature flag in MyC upload flow

src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiry.tsx, src/__generated__/ConsignmentInquiry_Test_Query.graphql.ts, src/__generated__/ConsignmentInquiry_me.graphql.ts, src/__generated__/consignRoutes_ConsignmentInquiryAppQuery.graphql.ts
This PR solves [CX-3275]
- When populating the form with the user's already saved phone number, we rely on the international and national formatted numbers gotten from Metaphysics. However these formats - national and international - when used to populate the form, we can end up with unintended final phone number values sent to the BE and we cannot handle this case by case (or country by country)
- This PR uses the raw phone number as is in gravity and replaces the country code in order to get the phone number we actually want to save as the phone value. 
More Context: https://artsy.slack.com/archives/C01B2P6LJUU/p1671712313793239
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
=> fix(CX-3275): Fix Phone Input Populated with wrong values in Consignment Inquiry Form

src/Apps/CollectorProfile/CollectorProfileApp.tsx
This PR solves [CX-3180]
This PR updates the logged-out experience of the Collector Profile
| Desktop | mWeb |
|--|--|
| <img width="1731" alt="image" src="https://user-images.githubusercontent.com/20655703/211595161-bb0d0586-bdc3-4ff1-8b90-459a9a124e1f.png"> | <img width="579" alt="image" src="https://user-images.githubusercontent.com/20655703/211595176-8bc189a5-b948-4c5f-8fbf-3d34f6019f1b.png"> |
https://user-images.githubusercontent.com/20655703/211595077-a7a6b43d-b08c-490d-8a82-e1f77865c87d.mov
[CX-3180]: https://artsyproduct.atlassian.net/browse/CX-3180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
=> fix(CX-3180): Update Collector Profile logged-out experience

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateAlertButton.tsx, src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCreateArtworkAlert.tsx, src/Apps/Artwork/Components/ArtworkSidebar/CreateArtworkAlertSection.tsx, src/Apps/FairOrginizer/Components/FairOrganizerFollowButton.tsx, src/Apps/FairOrginizer/Components/__tests__/FairOrganizerFollowButton.jest.tsx, src/Components/Artwork/SaveButton/__tests__/SaveButton.jest.tsx, src/Components/Artwork/SaveButton/useSaveArtwork.ts, src/Components/Artwork/__tests__/Details.jest.tsx, src/Components/FollowButton/FollowArtistButton.tsx, src/Components/FollowButton/FollowGeneButton.tsx, src/Components/FollowButton/FollowProfileButton.tsx, src/Components/FollowButton/__tests__/FollowArtistButton.jest.tsx, src/Components/FollowButton/__tests__/FollowGeneButton.jest.tsx, src/Components/FollowButton/__tests__/FollowProfileButton.jest.tsx, src/Components/SavedSearchAlert/Components/ActiveFilterPillsAndCreateAlert.tsx, src/Components/SavedSearchAlert/Components/SavedSearchCreateAlertButtonContainer.tsx, src/Components/SavedSearchAlert/Components/__tests__/SavedSearchCreateAlertButtonContainer.jest.tsx, src/Utils/__tests__/openAuthModal.jest.ts, src/Utils/openAuthModal.ts
Continuing the auth dialog rollout (currently at 25% in just the top-right auth links), this PR expands the surface to auth dialogs that open when you click actions that have after authentication intents (save, follow, etc).
=> chore(authdialog): enables auth dialog wrapper for intentful buttons

src/Apps/ArtQuiz/Components/ArtQuizResultsRecommendedArtworks.tsx, src/Apps/ArtQuiz/Components/ArtQuizResultsTabs.tsx, src/Apps/ArtQuiz/Routes/ArtQuizResults.tsx, src/__generated__/ArtQuizResultsRecommendedArtworksQuery.graphql.ts, src/__generated__/ArtQuizResultsRecommendedArtworks_me.graphql.ts
This PR solves [GRO-1482]
After a user takes the art quiz we want to show them works related to the ones they saved. Acceptance criteria for this task were explained as follows:
- If user likes only 1 artwork, show ALL related
- If user likes less than 3 artworks, show [8] per liked
- If user likes more than 3 artworks, show [4] per liked
This set of criteria for the related works results, however, does not apply to the quiz results email, which will have a smaller subset of related works. That being said, it didn't feel too out of line to simply pass a size argument to the pre-existing query.
Maybe worth revisiting a `results` query that encapsulates all results data at some point in the future.
[GRO-434]: …
=> feat(art-quiz): limit results related works

src/Apps/Home/Components/HomeFeaturedMarketNews.tsx, src/Apps/Home/__tests__/HomeFeaturedMarketNews.jest.tsx
This PR solves [FX-4542]
| <img width="1920" alt="before" src="https://user-images.githubusercontent.com/3513494/212068538-f2692d8b-4a97-4339-8f13-6b6efdd80935.png"> | <img width="1920" alt="after" src="https://user-images.githubusercontent.com/3513494/212068607-77701c0c-f123-417e-a666-97f2a5543e1f.png"> | 
[FX-4542]: https://artsyproduct.atlassian.net/browse/FX-4542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Change "Market News" title on home page to "Artsy Editorial"

src/Apps/Order/Components/BuyerGuarantee.tsx, src/Apps/Order/Components/StickyFooter.tsx, src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx, src/Apps/Order/Components/__tests__/BuyerGuarantee.jest.tsx, src/Apps/Order/Components/__tests__/StickyFooter.jest.tsx, src/Apps/Order/OrderApp.tsx, src/Apps/Order/Routes/Payment/PaymentContent.tsx, src/Apps/Order/Routes/Payment/index.tsx, src/Apps/Order/Routes/__tests__/Payment.jest.tsx, src/__generated__/OrderApp_order.graphql.ts, src/__generated__/orderRoutes_OrderQuery.graphql.ts
This PR solves [TX-991]
This PR updates the payment step for private sale orders. 
- Email at the footer is updated 
- Explanation texts updated for wire_transfer 
- Private conditions of sale link UI added 
- Extra conditions of sale is added 
Notes
1- We need to update the link for Private conditions of sale 
2- When Exchange offers, we need to pull the extra conditions of sale  from there 
https://user-images.githubusercontent.com/42584148/212628364-9d0f53f8-4eff-498e-b42b-d4f0f26f8a23.mov
[TX-991]: https://artsyproduct.atlassian.net/browse/TX-991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-991): payment step for private sale orders

src/Components/Notifications/NotificationItem.tsx, src/Components/Notifications/__tests__/NotificationItem.jest.tsx
Prefixes Artsy Editorial notifications. [Figma specs](https://www.figma.com/file/SlzmAJV6zqJDmAO8GoSjiC/Activity-%2F-Save-%2F-Follow-%2F-Create?node-id=2611%3A142945&t=4JqzzeUmmWVbyuWT-0)
Artist's name is missing on the screenshot because of the bug on gravity side. The fix is being deployed at the moment
=> Activity Panel: prefix artsy editorial notifications

src/Components/ZendeskWrapper.tsx
The type of this PR is: **Fix/Style**
[GRO-1511]
This PR moves the Zendesk widget to the right place, ie behind the cookie consent banner and above the rest of the site content.
[GRO-1511]: https://artsyproduct.atlassian.net/browse/GRO-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix: bump zindex to 1 to fix zendesk widget placement

src/Components/AuthDialog/Views/AuthDialogSignUp.tsx, src/Components/AuthDialog/Views/__tests__/AuthDialogSignUp.jest.tsx, src/Utils/__tests__/auth.jest.ts, src/Utils/auth.ts
I had made the assumption that the `signUp` function was just passing along the data it was given. As it happens it was selecting specific values, but the object I passed it still satisfied the type. So while the test was running we weren't including `agreed_to_receive_emails` in the registration payload.
=> fix(authdialog): corrects how email sign up is passed

src/Apps/Order/OrderApp.tsx, src/Apps/Order/__tests__/OrderApp.jest.tsx
This PR solves [TX-995]
This PR updates the redirect URL for the logo click when a user is on the checkout flow. For PS orders, users are redirected to the home page instead of the artwork page. 
[TX-995]: https://artsyproduct.atlassian.net/browse/TX-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-995): redirect users to home page upon logo click

src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx, src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx, src/__generated__/SettingsPurchasesQuery.graphql.ts, src/__generated__/SettingsPurchasesRow_order.graphql.ts, src/__generated__/SettingsPurchases_Test_Query.graphql.ts, src/__generated__/settingsRoutes_PurchasesRouteQuery.graphql.ts
This PR solves [TX-994]
This PR updates the help email displayed per order in user order history. For private sale orders, we are providing users with a different help email address. 
[TX-994]: https://artsyproduct.atlassian.net/browse/TX-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-994): Update email in order history for private sale orders

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormContext.tsx, src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormImages.tsx, src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormMain.tsx, src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx, src/Apps/MyCollection/Routes/EditArtwork/MyCollectionEditArtwork.tsx, src/Utils/localImagesHelpers.ts
Addresses [CX-3336]
This PR simplifies the My Collection local image optimization by moving the state where the images are stored into the context and removing the ref that was needed before. It's only a preparation for the next steps and needed to later store the images by image ID (which is returned from the create/update mutation).
[CX-3336]: https://artsyproduct.atlassian.net/browse/CX-3336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Simplify MyC local image optimization

src/Components/Notifications/Mutations/markNotificationAsRead.ts, src/Components/Notifications/NotificationItem.tsx, src/__generated__/NotificationItem_item.graphql.ts, src/__generated__/NotificationItem_test_Query.graphql.ts, src/__generated__/NotificationsListNextQuery.graphql.ts, src/__generated__/NotificationsListQuery.graphql.ts, src/__generated__/NotificationsList_test_Query.graphql.ts, src/__generated__/markNotificationAsReadMutation.graphql.ts
This PR solves [FX-4535]
Review app: [mark-notification-as-read](https://mark-notification-as-read.artsy.net/)
https://user-images.githubusercontent.com/3513494/213193037-3bdd51be-1f56-4058-a9d6-64c7c6d3cfe9.mp4
[FX-4535]: https://artsyproduct.atlassian.net/browse/FX-4535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4535): mark specific notification as read when clicking on an entry in the activity panel

src/Components/NavBar/NavBar.tsx
https://user-images.githubusercontent.com/3513494/213499077-712bfb23-9806-46d8-8a37-a0b14facc62b.mp4
https://user-images.githubusercontent.com/3513494/213499163-aab3d8cf-1e15-46c2-8a5b-90f349fd008c.mp4
=> fix: track `clickedNotificationsBell` event when activity panel icon is tapped

src/Apps/ArtQuiz/artQuizRoutes.tsx
This PR solves [GRO-1506]
The goal of this PR is to remove the Artsy app download footer from the results page, so that users can focus on their artwork/artist recs and choices made during the quiz w/o distractions. 
https://user-images.githubusercontent.com/23108927/213530192-50a0d6f0-fb9b-4593-a740-118fdd189e13.mp4
[GRO-1506]: https://artsyproduct.atlassian.net/browse/GRO-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(art-quiz): remove footer from results page

src/Apps/Home/Components/HomeContentCards/FallbackCards.tsx
This is one of the last pieces of the Trove rebrand and it just updates the fallback cards. These should rarely be seen by users but it's still nice to call a job complete ya know?
=> Update fallback content card for Trove

src/Apps/Order/Routes/Status/index.tsx, src/Apps/Order/Routes/__tests__/Status.jest.tsx, src/Apps/Order/Utils/getStatusCopy.tsx
This PR solves [TX-993]
This Pr updates the status page with the relevant copies for Private Sale orders. 
Credit Card 
ACH 
Wire 
[TX-993]: https://artsyproduct.atlassian.net/browse/TX-993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-993): Checkout status page updates for private sale orders

src/Apps/Order/Components/ItemReview.tsx
This PR solves [TX-1009]
This PR makes it so when the artwork version image "resized" is null on the review page, the UI will not error out. 
[TX-1009]: https://artsyproduct.atlassian.net/browse/TX-1009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(TX-1009): review page will not error out if no image

.circleci/config.yml, package.json, src/Apps/Auction/Components/AuctionDetails/__tests__/helpers.jest.ts, yarn.lock
This adds some nice PR status reporting on test failures, courtesy of https://github.com/jest-community/jest-junit. 
Looks like this, once you click into the `Tests` tab:
=> feat(ci): Add CI test reporting on failures

src/Components/Authentication/Components/AuthenticationSignUpPlaceholder.tsx, src/Components/Authentication/Views/SignUpForm.tsx
The bug was/is that the form was rendering initially with an empty `requestLocation`, this caused `isAutomaticallySubscribed` to be `false`, which set the initial value of `agreed_to_receive_emails` to `false`. Later on the `requestLocation` comes back with, say, `"US"` as the value; causing the form to render without the checkbox, but since the initial value is already set within Formik, it's not updated. So the form submits with the erroneous initial value.
I'm not entirely sure what caused this problem to manifest or how it was working previously but https://github.com/artsy/metaphysics/pull/4692 fixed cases in which this query would sometimes error, and we were previously always rendering the fragment container, with or without the `requestLocation`.
This PR sets it up so that we see …
=> fix(signup): uses a placeholder to only render form once we are ready

src/System/useFeatureFlag.tsx
The noise in the specs can be misleading when looking at the CI logs. It seems to me that: these aren't errors but are warnings, and are only really useful to developers in development mode. This is open to debate, of course.
=> chore(feature-flags): switch to warn and only warn during development

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx, src/Apps/Artist/Routes/AuctionResults/Components/MarketStatsInfoButton.tsx
Currently going through great pains to remove our remaining legacy Force modal usage. This appears to be the last usage of the deprecated Palette Modal. After this is merged I'll release a canary with that removed to see.
=> refactor(auction-results): removes usage of modal; clean up

src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx, src/Apps/ArtQuiz/Routes/ArtQuizResults.tsx, src/Apps/ArtQuiz/__tests__/ArtQuizResults.jest.tsx
Co-authored-by: Laura Bhayani <laurabeth@users.noreply.github.com>
This PR solves [GRO-1522]
The goal of this PR is to hide the loader from users who revisit their art quiz results, and makes for a better UI experience. Currently a WIP while another bug centralized around the `ArtQuizArtworks` is being investigated and is causing really strange behavior. 
[GRO-1522]: https://artsyproduct.atlassian.net/browse/GRO-1522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(art-quiz): hide loader from results after user revisits 

src/Apps/Artwork/ArtworkApp.tsx
This PR solves [FX-4554]
Review app: [fixes-for-artwork-screen](https://fixes-for-artwork-screen.artsy.net/)
Layout is broken when you open artwork screen in firefox and change the window width from `~750px` to `~1250px`
https://user-images.githubusercontent.com/3513494/213516640-ab652720-d255-4235-983c-eae0dcaf97ff.mp4
https://user-images.githubusercontent.com/3513494/213516747-a9f0a972-c052-4f1c-ab3d-17def352100b.mp4
[FX-4554]: https://artsyproduct.atlassian.net/browse/FX-4554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FX-4554): fixes overflowing artwork screen in firefox

src/Apps/Article/ArticleApp.tsx, src/Apps/Articles/ArticlesApp.tsx, src/Apps/Articles/NewsApp.tsx, src/Components/AuthDialog/AuthDialog.tsx, src/Components/AuthDialog/AuthDialogContext.tsx, src/Components/AuthDialog/Views/AuthDialogForgotPassword.tsx, src/Components/AuthDialog/Views/AuthDialogLogin.tsx, src/Components/AuthDialog/Views/AuthDialogSignUp.tsx, src/Utils/Hooks/useScrollToOpenArtistAuthModal.ts, src/Utils/Hooks/useScrollToOpenAuthModal.ts, src/Utils/Hooks/useScrollToOpenEditorialAuthModal.ts
With this PR 100% of the calls to open auth dialog are now wrapped in the rollout flag.
=> chore(auth-dialog): migrates remaining triggers

src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
This PR solves [GRO-1516]
This PR adds a standard "Saved Artwork" tracker to the `/art-quiz/artworks` page. 
The second event mentioned in @abhitip's spreadsheet will have to be implemented during completion of [GRO-1252]. I've linked the tickets so this doesn't get lost. 
[GRO-1516]: https://artsyproduct.atlassian.net/browse/GRO-1516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1252]: https://artsyproduct.atlassian.net/browse/GRO-1252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(art quiz): add save analytics to quiz save button

src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2ByIdRoute.tsx, src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx, src/Apps/CollectorProfile/collectorProfileRoutes.tsx, src/Server/middleware/userRequiredMiddleware.ts
This PR solves [FX-4555]
Review app: [collector-profile-saves2-routes](https://collector-profile-saves2-routes.artsy.net/)
* [/collector-profile/saves2](https://collector-profile-saves2-routes.artsy.net/collector-profile/saves2)
* [/collector-profile/saves2/:id](https://collector-profile-saves2-routes.artsy.net/collector-profile/saves2/hello)
[FX-4555]: https://artsyproduct.atlassian.net/browse/FX-4555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4555): add `/collector-profile/saves2/*` routes

src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
The type of this PR is: **style**
This PR is a quick fix to the offset of the info tooltip on `art-quiz/artworks`. Adjusts the tooltip to be closer to the CTAs and overlay the edge of the artwork. 
(Merging even though the build is timing out, secure in the knowledge that @dzucconi is following up w/ a fix to the issue.)
=> style(art-quiz): adjust tooltip height

src/Apps/ArtQuiz/Components/ArtQuizTrendingCollection.tsx
Just a quick PR to support collection descriptions that include HTML.
https://artsyproduct.atlassian.net/browse/GRO-1536
=> fix: Allow HTML in collection description GRO-1536

src/Apps/Order/Routes/Payment/PaymentContent.tsx, src/Apps/Order/Routes/__tests__/Payment.jest.tsx, src/Apps/Order/Utils/__tests__/orderUtils.jest.ts, src/Apps/Order/Utils/orderUtils.ts
This PR solves [TX-992]
This PR updates the payment step to stop using credit cart as a default payment method.  
[TX-992]: https://artsyproduct.atlassian.net/browse/TX-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update available payment methods for private sale orders

src/Apps/NewForYou/NewForYouApp.tsx
Closes [GRO-1373](https://artsyproduct.atlassian.net/browse/GRO-1373)
This actually is fixed in the new auth page which will handled encoded paths correctly. This was previously failing because the existing auth page was unable to handle the encoded slash in the pathname. However what we really want to do is just open a modal here since it's lower friction than the full page load and more consistent with what we do around the site.
[GRO-1373]: https://artsyproduct.atlassian.net/browse/GRO-1373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(new-for-you): redirects back to correct page upon authentication

src/Apps/Settings/SettingsApp.tsx, src/Server/passport/lib/app/lifecycle.js
Surfaced this via Sentry: https://sentry.io/organizations/artsynet/issues/3588012322/?project=28316&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h
I guess the original passport code wasn't in strict mode so this started to error once it was moved over. Converting our passport implementation to TypeScript would be well worth the effort.
=> fix(passport): fixes linked account redirect

data/schema.graphql, src/Components/NavBar/NavBarLoggedInActions.tsx, src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotifications.tsx, src/Components/NavBar/NavBarMobileMenu/NavBarMobileMenuNotificationsIndicator.tsx, src/Components/NavBar/NavBarMobileMenu/__tests__/NavBarMobileMenuNotificationsIndicator.jest.tsx, src/Components/Notifications/Mutations/markNotificationsAsSeen.ts, src/Components/Notifications/Notifications.tsx, src/__generated__/NavBarLoggedInActionsQuery.graphql.ts, src/__generated__/NavBarMobileMenuNotificationsIndicatorQuery.graphql.ts, src/__generated__/NavBarMobileMenuNotificationsIndicator_me.graphql.ts, src/__generated__/NavBarMobileMenuNotificationsIndicator_test_Query.graphql.ts, src/__generated__/NavBarMobileMenuNotificationsQuery.graphql.ts, src/__generated__/NavBarMobileMenuNotifications_me.graphql.ts, src/__generated__/markNotificationsAsSeenMutation.graphql.ts
Co-authored-by: Dima Tretyak <itretyak@ya.ru>
This PR solves [FX-4538]
As a user
Given I have unseen notifications
When I visit the activity panel
The top-level indicator goes away
And I continue to see unread indicators to individual notifications.
- [Review app](https://notifications-bell.artsy.net/) - will work only after https://github.com/artsy/metaphysics/pull/4731 is merged
Might be convenient to use this mutation to imitative opening notifications feed in past:
```graphql
mutation {
markNotificationsAsSeen(input: { until: "2023-01-28T11:05:19Z"}) {
responseOrError {
... on MarkNotificationsAsSeenSuccess {
success
}
... on MarkNotificationsAsSeenFailure {
mutationError {
message
}
}
}
}
}
``` …
=> feat(FX-4538): Hide AP blue dot indicator if there are no new notifications

src/Apps/Order/Components/ItemReview.tsx
There is an issue with the artwork classification "Limited Edition Set" as when it changed to just "Limited Edition" we are no longer able to get the short description, erroring out the review page. This makes the "short description" optional on the review page. 
=> fix: make short description optional

scripts/smoke_test.sh, src/Apps/Authentication/__tests__/authenticationRoutes.jest.tsx, src/Apps/Components/AppShell.tsx, src/Apps/Components/__tests__/AppShell.jest.tsx, src/Apps/Settings/Routes/EditSettings/Components/SettingsEditSettingsLinkedAccounts.tsx, src/Components/AuthDialog/Components/AuthDialogSocial.tsx, src/Components/AuthDialog/Hooks/__tests__/useSocialAuthTracking.jest.ts, src/Components/AuthDialog/Hooks/useAfterAuthenticationRedirectUrl.ts, src/Components/AuthDialog/Hooks/useAuthDialogTracking.ts, src/Components/AuthDialog/Hooks/useSocialAuthTracking.ts, src/Components/AuthDialog/Views/__tests__/AuthDialogForgotPassword.jest.tsx, src/System/Router/__tests__/buildServerApp.jest.tsx, src/Utils/Hooks/useAuthIntent/__tests__/useAuthIntent.jest.ts, src/Utils/Hooks/useAuthIntent/index.tsx
Closes: [GRO-1543](https://artsyproduct.atlassian.net/browse/GRO-1543)
Now when clicking on the social auth links, we set a cookie that then gets picked up by this hook when you land back in the app. It correctly checks to make sure the auth didn't error by ensuring you're not on the login or sign up paths.
[GRO-1543]: https://artsyproduct.atlassian.net/browse/GRO-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(auth): tracks social logins

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormContext.tsx, src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx, src/Utils/localImageHelpers.ts
Addresses [CX-3391]
Clear local images when navigating back in artwork form.
[CX-3391]: https://artsyproduct.atlassian.net/browse/CX-3391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Clear local images when navigating back in artwork form

src/Components/AuthDialog/Hooks/__tests__/useAfterAuthenticationRedirect.jest.ts, src/Components/AuthDialog/Hooks/__tests__/useAfterAuthenticationRedirectUrl.jest.ts, src/Components/AuthDialog/Hooks/useAfterAuthenticationRedirectUrl.ts
So apparently the `AP` environment variable is pointing to old paths, which is the reason why this was redirecting back to /login, technically. We don't really need to be using them though so I'm just removing this.
The reason the Integrity spec failed is because, typically, if you're logged in, you're gonna get redirected to the homepage if you hit that route. It didn't because as far as the state of the browser is concerned, you are not logged in.
I'm confident that login is actually succeeding because [there's this assertion](https://github.com/artsy/integrity/blob/8b81f9f288c8d305c97855a4766dc3b849719391/cypress/utils/loginToArtsyAsUser.ts#L34-L36) — and we can eliminate one redirect anyway by fixing this so specs should pass once this is on staging.
-----
We did uncover this very …
=> fix(auth): uses our actual auth paths

src/Apps/CollectorProfile/Routes/Saves2/Components/FourUpImageLayout.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/StackedImageLayout.tsx
| <img width="497" alt="before" src="https://user-images.githubusercontent.com/3513494/217311783-e809e61a-3f46-47b7-a8be-ad4b630994ce.png"> | <img width="497" alt="after" src="https://user-images.githubusercontent.com/3513494/217311829-d40c31c2-47c1-4aea-b667-e1adbb0284fd.png"> | 
=> chore: correctly display image placeholders for saves/wishlist

src/Components/Footer/Footer.tsx
This PR solves [CX-3363]
Don't show the Talk to Specialists page link when cx-swa-landing-page-redesign-2023 ff is enabled
[CX-3363]: https://artsyproduct.atlassian.net/browse/CX-3363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-3363): remove the Talk to Specialists page link from the footer

src/Apps/Settings/SettingsApp.tsx
This PR solves [CX-3373]
- Replaces the Settings Heading with a collector profile breadcrumb.
- 
[CX-3373]: https://artsyproduct.atlassian.net/browse/CX-3373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feat(CX-3373): Collector Profile breadcrumb in Settings

src/Components/Notifications/NotificationItem.tsx, src/Components/Notifications/__tests__/NotificationItem.jest.tsx, src/Components/Notifications/util.ts
This PR solves [FX-4601]
[FX-4601]: https://artsyproduct.atlassian.net/browse/FX-4601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(FX-4601): Do not display +n text in activity panel for non-artwork-based notifications

src/Apps/Partner/Components/PartnerArtists/PartnerArtistList/PartnerArtistList.tsx
Closes [GRO-1535](https://artsyproduct.atlassian.net/browse/GRO-1535)
So interestingly there's a bug in Firefox where `break-before` is broken in multi-column layouts. That means that removing the hack gives us this as a possibility at some widths in Firefox:
Instead we can just break this into two sets of columns:
[GRO-1535]: https://artsyproduct.atlassian.net/browse/GRO-1535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(GRO-1535): removes column headers hack

src/Components/Onboarding/Components/OnboardingDebug.tsx, src/Components/Onboarding/Components/OnboardingSteps.tsx, src/Components/Onboarding/Hooks/useOnboardingContext.tsx, src/Components/Onboarding/Views/OnboardingQuestionOne.tsx, src/Components/Onboarding/Views/OnboardingQuestionThree.tsx, src/Components/Onboarding/Views/OnboardingThankYou.tsx, src/Components/Onboarding/config.ts
This PR solves [GRO-1252]
This PR contains the logic that conditionally adds the Art Quiz as an option to the user onboarding flow. The logic is outlined [here](https://www.figma.com/file/F12JFyxE0DR0qCGX2nap5E/Art-Quiz%3A-Onboarding-Phase-2?node-id=36%3A32&t=RXDUidcrzrM8Ffxb-0).
Tracking is implemented and follows the same patterns as previous onboarding reward screen options.
[GRO-1252]: https://artsyproduct.atlassian.net/browse/GRO-1252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add art quiz as an onboarding reward screen

src/Apps/ArtQuiz/Components/ArtQuizFullscreen.tsx, src/Apps/ArtQuiz/Routes/ArtQuizWelcome.tsx
Just a little polish on the welcome screen.
This fixes the shrunken buttons when the height is short. Also fixes the flash of content where the container isn't the correct height while the JS loads.
https://user-images.githubusercontent.com/112297/217666954-99ae9b43-cc7a-499d-a481-ec0575cef859.mov
=> fix(art-quiz): prevents squashed buttons and short screen overflows

src/Apps/ArtQuiz/Components/ArtQuizResultsRecommendedArtworks.tsx, src/Apps/Consign/Routes/SubmissionFlow/UploadPhotos/UploadPhotos.tsx, src/Components/PhotoUpload/Components/PhotoThumbnail.tsx, src/Components/PhotoUpload/Utils/fileUtils.ts
This PR solves [GRO-1453]
The intention of this code is to add a fallback state for users who take the art quiz and receive no artwork recs. After some chatter about this, was suggested to use a message in place of a collection because this issue seems to occur mostly on staging and will very rarely happen on prod. However, keeping this a draft PR until design approves messaging or asks for a collection to be included instead. Will hit merge on this once I know for sure. 
[GRO-1453]: https://artsyproduct.atlassian.net/browse/GRO-1453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
=> fix(art quiz): add messaging to empty state on artwork recs in results 

src/Apps/Settings/SettingsApp.tsx
This PR solves [CX-3373]
Removes extra spacing in the Collector Profile Breadcrumb
[CX-3373]: https://artsyproduct.atlassian.net/browse/CX-3373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-3373): Rm extra spacing

src/Apps/Settings/Routes/Purchases/Components/SettingsPurchasesRow.tsx, src/Apps/Settings/Routes/Purchases/Components/__tests__/SettingsPurchases.jest.tsx, src/__generated__/SettingsPurchasesQuery.graphql.ts, src/__generated__/SettingsPurchasesRow_order.graphql.ts, src/__generated__/SettingsPurchases_Test_Query.graphql.ts, src/__generated__/settingsRoutes_PurchasesRouteQuery.graphql.ts
This PR solves [TX-1053]
This PR gets the artwork image, displayed in the order row in user purchases, from the artwork version, since this section can now include private sale orders.
Additionally, I made the artwork's name un-clickable for private sale orders, since users cannot go to the artwork page. 
[TX-1053]: https://artsyproduct.atlassian.net/browse/TX-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-1053): Get versioned artwork image

src/Apps/Order/OrderApp.tsx, src/Apps/Order/__tests__/OrderApp.jest.tsx
This PR solves [TX-1058]
This PR updates the order app Artsy logo to always redirect to the homepage. 
[TX-1058]: https://artsyproduct.atlassian.net/browse/TX-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-1058): order app logo redirects to home page

src/Apps/Artists/Routes/ArtistsIndex.tsx
While although these should never be `null` — it is apparently possible. So this just guards against one or both of these sets being missing.
=> fix(artists): guards against potentially null data

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx, src/Apps/Artist/Routes/AuctionResults/Components/TableSidebar.tsx
This PR solves [CX-3390]
before: 
after:
[CX-3390]: https://artsyproduct.atlassian.net/browse/CX-3390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-3390):hide upcoming auctions when there are no upcoming auctions in auction results

src/Apps/Order/Routes/Review/index.tsx, src/Apps/Order/Routes/__tests__/Review.jest.tsx
When an offer-order is initiated from an ongoing conversation, we want the buyer to be redirected to that conversation when the offer-order is submitted. This behavior changed for offer-orders initiated from an artwork page in #11914, and this PR updates that to consider the conversation-initiated offer-orders as well.
=> fix: route inquiry wire offers to conversations

src/Apps/ArtQuiz/Components/ArtQuizResultsRecommendedArtworks.tsx, src/Apps/ArtQuiz/Components/ArtQuizResultsTabs.tsx, src/Apps/ArtQuiz/Routes/ArtQuizResults.tsx, src/__generated__/ArtQuizResultsRecommendedArtworksQuery.graphql.ts, src/__generated__/ArtQuizResultsRecommendedArtworks_me.graphql.ts
Co-authored with @TMcMeans 
This switches the recommended artworks to use the 24 hour cached `recommendedArtworks` field.
=> fix(quiz): switches artworks tab to use recommended artworks field

src/Apps/Order/Routes/Shipping/index.tsx, src/Apps/Order/Utils/formValidators.tsx
This PR solves [TX-1016]
This PR ensures that the CTA button in the shipping step of the checkout flow is disabled if user does not provide: a phone number that does include only 0-9 and +-. 
[TX-1016]: https://artsyproduct.atlassian.net/browse/TX-1016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-1016): Primitive phone number validation 

src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/DeleteSavesModal.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/SavesContextualMenu.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/DeleteSavesModal.jest.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/SavesContextualMenu.jest.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SavesArtworks.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/SavesArtworks.jest.tsx, src/Components/ContextualMenu/ContextualMenu.tsx, src/Components/ContextualMenu/ContextualMenuItem.tsx, src/Components/ContextualMenu/__stories__/ContextualMenu.story.tsx, src/Components/ContextualMenu/__tests__/ContextualMenu.jest.tsx, src/Components/ContextualMenu/index.ts, src/System/i18n/locales/en-US/translation.json, src/__generated__/DeleteSavesModalMutation.graphql.ts, src/__generated__/SavesArtworksQuery.graphql.ts, src/__generated__/SavesArtworks_Test_Query.graphql.ts, src/__generated__/SavesArtworks_collection.graphql.ts
This PR solves [FX-4553]
This adds the ability to delete an Artwork List.
In order to get there I needed a new kind of [contextual menu](https://www.nngroup.com/articles/contextual-menus/) that is triggered from a ⋯ icon. 
I extracted this into what is now the first commit. (If desired I can further extract this new component into a separate PR.)
I was going for a simple API that can be used like this:
```jsx
const SomeContextualMenu = () => (
<ContextualMenu>
<ContextualMenuItem onClick={doSomething}>Item one</ContextualMenuItem>
<ContextualMenuDivider />
<ContextualMenuItem onClick={doSomething}>Item two</ContextualMenuItem>
<ContextualMenuDivider />
<ContextualMenuItem onClick={doSomething}>Item three</ContextualMenuItem>
</ContextualMenu>
);
```
This …
=> feat(artwork lists): contextual action menu + delete action

src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
The goal of this PR is to remove a sorting function that maintained the correct position on the quiz artwork cards on the art quiz. @jonallured pushed a PR in gravity that tackles this on the backend now so this code is no longer needed: https://github.com/artsy/gravity/pull/16112
=> chore(art-quiz): remove sorting function

src/Apps/CollectorProfile/Routes/Saves2/Components/FourUpImageLayout.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SavesArtworkSaveButton.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SavesNoImage.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListItem.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListItemImage.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkFooter.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkHeader.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkImage.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkModal.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/SelectListsForArtworkPlaceholders.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SelectListsForArtworkModal/__tests__/SelectListsForArtworkModal.jest.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/StackedImageLayout.tsx, src/Apps/CollectorProfile/Routes/Saves2/Utils/__tests__/getSelectedCollectionIds.jest.ts, src/Apps/CollectorProfile/Routes/Saves2/Utils/getSelectedCollectionIds.ts, src/System/i18n/locales/en-US/translation.json, src/__generated__/SelectListItem_item.graphql.ts, src/__generated__/SelectListsForArtworkHeader_artwork.graphql.ts, src/__generated__/SelectListsForArtworkModalQuery.graphql.ts, src/__generated__/SelectListsForArtworkModal_Test_Query.graphql.ts, src/__generated__/SelectListsForArtworkModal_artwork.graphql.ts, src/__generated__/SelectListsForArtworkModal_me.graphql.ts
This PR solves [FX-4590]
Review app: [select-lists-for-artwork](https://select-lists-for-artwork.artsy.net/collector-profile/saves2)
https://user-images.githubusercontent.com/3513494/220416936-1500e1b4-f68f-4298-8458-78f8b30a57e1.mp4
https://user-images.githubusercontent.com/3513494/220654855-fc0de29b-2f17-4a8f-9451-befb4a2279c0.mp4
[FX-4590]: https://artsyproduct.atlassian.net/browse/FX-4590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4590): Select lists for this artwork modal - connect backend

src/Server/middleware/errorHandler.tsx
Minor update. Noticed this while talking to Viviana about our layouts — This page wasn't using the `LogoOnly` layout despite looking nearly identical. (There was some unintentional whitespace under the logo, which was the tell)
=> fix(errors): uses logo only layout on error pages

src/Apps/Artwork/ArtworkApp.tsx
This PR solves [PLATFORM-4980]
Temporarily suppresses the artwork page's `RelatedWorks` rail, which appears to be implicated in the increasing frequency of ES alerts. 
See Slack threads [here](https://artsy.slack.com/archives/CA8SANW3W/p1676999056487519) and [here](https://artsy.slack.com/archives/C9SATFLUU/p1677253352997539).
Effects can be monitored [here](https://artsy.slack.com/archives/C9SATFLUU/p1677533281286779?thread_ts=1677253352.997539&cid=C9SATFLUU).
[PLATFORM-4980]: https://artsyproduct.atlassian.net/browse/PLATFORM-4980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> perf: temporarily disable RelatedWorks rail

src/Apps/ArtQuiz/Components/ArtQuizResultsEmpty.tsx, src/Apps/ArtQuiz/Components/ArtQuizResultsTabs.tsx
A small issue I noticed is that on pages that had `Shelf` components in the quiz there would be a doubling up of the scroll area of exactly `10px`. This is because these pages don't have a footer and the `Shelf`'s scrollbar reaches past it's container `-10px` in order to have a larger hit area for it's scrollbar. This is usually fine but since there was no footer and _no_ extra whitespace at all, it was causing there to be 2 nested scroll areas, which was not good. It also just looks natural for there to be a bit of breathing room down there.
=> fix(art-quiz): adds footer space to help visually and fix double scroll

src/Apps/ArtQuiz/Routes/ArtQuizArtworks.tsx
Adding a data-test id to the artwork cards count for testing in Cypress. 
=> chore(quiz): add data test id for integration testing

src/Apps/Settings/Routes/Saves/Components/SettingsSavesProfiles.tsx, src/Apps/Settings/Routes/Saves/Components/__tests__/SettingsSavesProfiles.jest.tsx
This PR solves [GRO-1581]
The goal of this PR is to update the copy on https://www.artsy.net/collector-profile/follows for gallery follows to prevent confusion for users as my collection grows. 
[GRO-1581]: https://artsyproduct.atlassian.net/browse/GRO-1581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(collector profile): change follow profiles copy

src/Components/ErrorPage.tsx, src/System/Router/ErrorBoundary.tsx
Just wanting to make error reports a bit less ambiguous; this makes it such that we'll only see error codes on actual server errors (or client-side "404s").
=> feat(error): improves messages for client-side errors

src/Apps/Order/Components/PriceOptions.tsx, src/Apps/Order/Routes/__tests__/Offer.jest.tsx
This PR solves [TX-1073]
This PR updates the offer step in the checkout flow, by selecting artwork list price as the default option among the readio buttons. 
https://user-images.githubusercontent.com/42584148/222149148-748e0f7f-6564-401e-9e86-dfcc9e30d46a.mov
[TX-1073]: https://artsyproduct.atlassian.net/browse/TX-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-1073): Select list price as default offer option

src/Components/Search/Suggestions/SuggestionItem.tsx
This PR solves [FX-4631]
Adding analytics on the quick action `Artwork` and `Auction Results` buttons on the Artist autosuggest element.
[FX-4631]: https://artsyproduct.atlassian.net/browse/FX-4631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add analytics on search artist quickaction btns

docs/i18n.md, package.json, scripts/list-translations.js
Adds a little devx feature that I was missing while reviewing a PR just now.
We are seeing increasing adoption of the i18n pattern in Force. That adds some indirection/friction to the process of identifying a component by its user-facing labels, and then locating its source code.
This PR aims to make things easier by adding a `yarn translations` command that exposes the fully qualified path names for each i18n string, so that you can search for e.g. `collectorSaves.savesHeader.listCreated` and find the component in question.
Output is designed to be very skimmable by default:
And also grep-friendly:
I skimmed https://www.i18next.com and didn't see anything like this included by default, but correct me if I'm wrong.
=> feat(devx): add package script to pretty-print i18n translations

src/Utils/Hooks/useAuthValidation.ts
Closes [GRO-1588](https://artsyproduct.atlassian.net/browse/GRO-1588)
If you log out in one tab you'll remain logged in in other open tabs. Further navigation in those tabs will lead to sporadic errors. So here I just am adding an additional check when a tab regains focus.
[GRO-1588]: https://artsyproduct.atlassian.net/browse/GRO-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(GRO-1588): re-check auth on tab focus

src/Apps/Order/Components/CreditCardPicker.tsx, src/Apps/Order/Components/PhoneNumberForm.tsx, src/Apps/Order/Components/SaveAndContinueButton.tsx, src/Apps/Order/Routes/Payment/PaymentContent.tsx, src/Apps/Order/Routes/Shipping/index.tsx, src/Components/AddressForm.tsx, src/Components/CountrySelect.tsx
This PR solves [TX-1071]
This PR fixes the tab selection for the checkout flow as the selectable fields inside the `Collapse` components can be selected even when they are hidden. 
This set a conditional `tabIndex` for input and buttons inside relevant Collapses. For Stripe components that don't support `tabIndex`, I set `display: "none"` when they are hidden, disabling the tab selection. 
More discussion on this issue[ here](https://artsy.slack.com/archives/C2TQ4PT8R/p1676472354876629). 
[TX-1071]: https://artsyproduct.atlassian.net/browse/TX-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
=> fix(TX-1071): improve checkout flow tab accessibility

data/schema.graphql, src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiry.tsx, src/Apps/Consign/Routes/ConsignmentInquiry/__tests__/ConsignmentInquiry.jest.tsx, src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx, src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/MeetTheSpecialists.jest.tsx, src/Apps/Consign/consignRoutes.tsx, src/__generated__/consignRoutes_ConsignmentInquiryWithRecipientEmailAppQuery.graphql.ts, src/__generated__/useCreateConsignmentInquiryMutation.graphql.ts
This PR solves [CX-3496]
If the user visits the get in touch flow via the "contact _NAME_" button, the specialist's name will be displayed in the title and the email will be sent to this specialist
Test here: https://swa-lp-redesign.artsy.net/
[CX-3496]: https://artsyproduct.atlassian.net/browse/CX-3496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-3496): use recipientEmail in get in touch flow

src/Components/RecentlyViewed/RecentlyViewed.tsx
Unknown what the cause of this is but some nodes in this response are `null`. This fixes the front-end for now.
=> fix: compacts artworks displayed in shelf

src/Apps/Order/Routes/Status/index.tsx, src/Apps/Order/Routes/__tests__/Status.jest.tsx, src/Apps/Order/__tests__/OrderApp.jest.tsx, src/Apps/Order/redirects.tsx, src/__generated__/orderRoutes_OrderQuery.graphql.ts, src/__generated__/redirects_order.graphql.ts
Companion PR to https://github.com/artsy/eigen/pull/8275. Pretty sure this should cover all of the places we're using order `state` to determine what to display/how to route users where having state be `in_review` might cause things to break.
=> feat: use order displayState instead of state

src/Apps/Settings/Routes/EditProfile/helpers/verifyID.ts
This PR solves : N/A
This adds a comment to clarify that when `verifyID` helper is called, no inputs are passed with the mutation and the user is pulled from authenticated context, ultimately ending up [in this block of code](https://github.com/artsy/gravity/blob/b14ea0276391db2d3a4547b8175f1210251fb8c4/app/api/v1/identity_verifications_endpoint.rb#L72-L76) in gravity.
=> refactor: add comment to clarify usage of inputs in verifyID helper

src/Apps/Settings/Routes/Insights/Components/InsightsAuctionResults.tsx
This PR solves [CX-3430]
Show only past auction results inside insights
[CX-3430]: https://artsyproduct.atlassian.net/browse/CX-3430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: show only past auction results inside insights

src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx, src/Components/Artwork/Details.tsx
This PR solves: [PX-5444]
This PR refactors the conditional link used in the Details.tsx file so we no longer need to pass in the underlineOnHover argument. 
[PX-5444]: https://artsyproduct.atlassian.net/browse/PX-5444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore:slight style refactor of conditional link

src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditSavesModal.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/EditSavesModal.jest.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx
The type of this PR is: **Chore**, **Refactor**
Review app: [modal-buttons](https://modal-buttons.artsy.net/collector-profile/saves2)
* Added improvements/changes to edit list modal based on [this comment](https://artsy.slack.com/archives/C9SATFLUU/p1678099239933699?thread_ts=1677803388.476209&cid=C9SATFLUU)
* Small refactor and improvements for edit/create list modals
| <img width="952" alt="before-edit-desktop" src="https://user-images.githubusercontent.com/3513494/224754274-148d6ec4-f72c-490f-a571-6076ef46a242.png"> | <img width="952" alt="after-edit-desktop" src="https://user-images.githubusercontent.com/3513494/224754344-33a0acee-e5dc-45d5-9556-ed414d1aee3e.png"> | 
| ------------- | …
=> chore: improvements for edit list and create new list modals

src/Components/Search/SearchBar.tsx, src/Components/Search/Suggestions/SuggestionItem.tsx, src/Components/Search/__tests__/SearchBar.jest.tsx
The type of this PR is: Style
This PR solves [FX-4650]
|Before|After|
|---|---|
|<img width="552" alt="image" src="https://user-images.githubusercontent.com/17421923/225265522-8b91d1ba-ff1c-4d1b-ba25-1ea02c56b10f.png">|<img width="598" alt="image" src="https://user-images.githubusercontent.com/17421923/225265278-617ace72-1d01-46dc-a3af-ed818309076a.png">|
[FX-4650]: https://artsyproduct.atlassian.net/browse/FX-4650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> style: move the see full results to the bottom

scripts/setup.sh, src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx, src/__generated__/HomeEmergingPicksArtworksRailQuery.graphql.ts, src/__generated__/HomeEmergingPicksArtworksRail_Test_Query.graphql.ts, src/__generated__/HomeEmergingPicksArtworksRail_viewer.graphql.ts
This PR solves [CX-3493]
Sort "Curator's Picks: Emerging" home rail by decayed merch to use the same sorting as on the collection page.
| | |
| --- | --- |
| <img width="1020" alt="Screenshot 2023-03-14 at 14 57 26" src="https://user-images.githubusercontent.com/4691889/225024386-6c8b21c3-bdb6-4d18-a783-7f16ab705c6c.png"> | <img width="1025" alt="Screenshot 2023-03-14 at 14 57 34" src="https://user-images.githubusercontent.com/4691889/225024408-54408839-77cb-4269-8ef5-85de657593f1.png"> |
[CX-3493]: https://artsyproduct.atlassian.net/browse/CX-3493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
=> CX-3493: Sort "Curator's Picks: Emerging" home rail by decayed merch

src/Apps/Artist/Routes/WorksForSale/Components/ArtistArtworkFilters.tsx, src/Apps/ArtistSeries/__tests__/ArtistSeriesArtworksFilter.jest.tsx, src/Apps/Auction/Components/AuctionArtworkFilter.tsx, src/Apps/Fair/Routes/FairArtworks.tsx, src/Apps/Gene/Components/__tests__/GeneArtworkFilter.jest.tsx, src/Apps/Partner/Routes/__tests__/Works.jest.tsx, src/Apps/Show/__tests__/ShowArtworks.jest.tsx, src/Apps/Tag/Components/__tests__/TagArtworkFilter.jest.tsx, src/Components/ArtworkFilter/ArtworkFilters/index.tsx
This PR solves [FX-4668]
Clean up `artist-artwork-grid-keyword-search` flag
We need to archive the flag after this is deployed
[FX-4668]: https://artsyproduct.atlassian.net/browse/FX-4668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(cleanup): remove artist-artwork-grid-keyword-search

src/Apps/Artist/Routes/WorksForSale/Components/__tests__/ArtistArtworkFilter.jest.tsx
This PR solves [FX-4669]
[FX-4669]: https://artsyproduct.atlassian.net/browse/FX-4669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: cleanup trending-sort-for-artist-artwork-grids feature flag

src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/AddArtworksModal.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/ArtworksList.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModalForManageArtwork.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModalWizard.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/__tests__/AddArtworksModal.jest.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/useAddArtworksToCollection.ts, src/Apps/CollectorProfile/Routes/Saves2/Components/SavesHeader.tsx, src/Components/Artwork/ManageArtworkForSaves.tsx, src/System/i18n/locales/en-US/translation.json, src/__generated__/useAddArtworksToCollectionMutation.graphql.ts
This PR solves [FX-4639]
- Pressing Save commits the mutation
- A confirmation toast is displayed
- [Review app](https://create-list-mutation.artsy.net/)
| Desktop | Mobile Web |
|---|---|
| <video src="https://user-images.githubusercontent.com/3934579/225592240-6b48fe89-2a8a-4aa9-a830-8abdd2eed5b3.mp4" /> | <video src="https://user-images.githubusercontent.com/3934579/225592260-165456b3-de5b-4e40-aed4-d157b757e1a8.mp4" /> |
[FX-4639]: https://artsyproduct.atlassian.net/browse/FX-4639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4639): User adds artworks to new list — mutation and toast

data/schema.graphql, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkRequestPriceEstimateSection.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/__tests__/MyCollectionArtwork.jest.tsx, src/__generated__/MyCollectionArtworkRequestPriceEstimateSection_artwork.graphql.ts, src/__generated__/MyCollectionArtworkTestQuery.graphql.ts, src/__generated__/collectorProfileRoutes_ArtworkQuery.graphql.ts, src/__generated__/myCollectionRoutes_ArtworkQuery.graphql.ts
This PR solves [CX-3524]
This PR is a follow-up on artsy/metaphysics#4888
This PR updates the logic of the request price estimate section to use the new field `isPriceEstimateRequestable` from metaphysics
[CX-3524]: https://artsyproduct.atlassian.net/browse/CX-3524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(CX-3524): Refactor Request Price Estimate section logic

src/Apps/Artist/ArtistApp.tsx, src/Apps/Artist/Routes/Overview/Utils/renderOrRedirect.tsx, src/__generated__/ArtistApp_Test_Query.graphql.ts, src/__generated__/ArtistApp_artist.graphql.ts, src/__generated__/ArtistApp_sharedMetadata.graphql.ts, src/__generated__/artistRoutes_TopLevelQuery.graphql.ts
Closes [GRO-1624](https://artsyproduct.atlassian.net/browse/GRO-1624)
So; in investigating this it looks like we have a lot to address when making the design updates for the tabs. I started to unravel that thread but it's a bit large. For now I've just changed the auction lots check to use the status flag instead of checking the count.
We _will_ want to circle back to how we conditionally render tabs/pages and handle redirects before we make any real changes to the tab layout — so calling that out as a dependency for some of the redesign work.
[GRO-1624]: https://artsyproduct.atlassian.net/browse/GRO-1624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(artist): uses status field to determine auction lots rendering

src/Apps/Artwork/ArtworkApp.tsx, src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercialButtons.tsx, src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercialButtons.jest.tsx, src/Utils/Hooks/useAuthIntent/index.tsx, src/Utils/Hooks/useAuthIntent/mutations/AuthIntentCreateOfferOrderMutation.ts, src/Utils/Hooks/useAuthIntent/mutations/AuthIntentCreateOrderMutation.ts, src/__generated__/AuthIntentCreateOfferOrderMutation.graphql.ts, src/__generated__/AuthIntentCreateOrderMutation.graphql.ts
This PR solves [TX-1015]
This PR creates two new after auth action for BNMO clicks, so that an order/offer-order is created and users redirected to the shipping/offer step of the checkout flow after auth. 
[TX-1015]: https://artsyproduct.atlassian.net/browse/TX-1015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://user-images.githubusercontent.com/42584148/225321040-b8fb2e26-481d-4e5c-8bad-bef3432a379b.mov
=> feat(TX-1015): order creation after auth

src/Apps/Home/Components/HomeEmergingPicksArtworksRail.tsx, src/__generated__/HomeEmergingPicksArtworksRailQuery.graphql.ts, src/__generated__/HomeEmergingPicksArtworksRail_Test_Query.graphql.ts, src/__generated__/HomeEmergingPicksArtworksRail_viewer.graphql.ts
This PR solves [CX-3493]
This PR updates the number of artworks in the Curator's picks rail to 20 artworks
[CX-3493]: https://artsyproduct.atlassian.net/browse/CX-3493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(CX-3493): Increase number of artworks in Curator's picks rail to 20

src/Utils/__tests__/getSaleOrLotTimerInfo.jest.ts, src/Utils/getSaleOrLotTimerInfo.ts
This PR solves [TX-1102]
In some cases, because of timezone issues, the copy would show "Bidding Starts Today" for starting tomorrow lots.
The intent here is to have the same logic we use in Eigen (src/app/utils/saleTime.ts).
**_Before_**
**_After_**
[TX-1102]: https://artsyproduct.atlassian.net/browse/TX-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update bidding starts copy

src/Components/Artwork/ShelfArtwork.tsx, src/Components/Artwork/__stories__/ShelfArtwork.story.tsx, src/Utils/__tests__/resized.jest.ts, src/Utils/resized.ts
This PR picks up off of https://github.com/artsy/force/pull/11126 — we wound up pulling over all the placeholder work from that initial PR so this winds up being pretty easy to drop in.
| ---- | ---- |
| ![www artsy net_artist_lee-krasner](https://user-images.githubusercontent.com/112297/228333934-8feead30-9b5b-417f-bb32-4963616b0eb1.png) |  ![localhost_5050_artist_lee-krasner](https://user-images.githubusercontent.com/112297/228333976-2433db81-a4e7-4b1f-9cd3-82d1edbb53b5.png) |
| ![staging artsy net_artist_jackson-pollock](https://user-images.githubusercontent.com/112297/228334190-24e53bfe-90b1-484b-a7a2-0e6bbeb571ca.png) | ![localhost_5050_artist_jackson-pollock](https://user-images.githubusercontent.com/112297/228334237-f212906a-d388-4b76-9583-f1af87e5653e.png) |
| …
=> feat: area-based image resizing for artwork shelf

src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListItem.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListsHeader.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Images/ArtworkListNoImage.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Images/FourUpImageLayout.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Images/StackedImageLayout.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Images/__tests__/FourUpImageLayout.jest.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Images/__tests__/StackedImageLayout.jest.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SavesEntityImage.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/ArtworkListsHeader.jest.tsx, src/System/i18n/locales/en-US/translation.json
Notion: [Card](https://www.notion.so/artsy/Artworks-list-I-think-we-ve-got-a-confusing-mix-of-terms-in-our-codebase-for-Artwork-Lists-collec-03de616986ab4cd4a839ec6aed989d3d)
=> refactor(phase 4): standardise and use `ArtworkList` terminology

src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditArtworkListModal.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/EditArtworkListModal.jest.tsx
This PR solves [FX-4707]
```javascript
{
action: ActionType.editedArtworkList,
context_owner_type: OwnerType.saves,
owner_id: string // id of the list
}
```
https://user-images.githubusercontent.com/3513494/229127899-1df98088-06aa-43eb-82ae-250c36f6c2ca.mp4
[FX-4707]: https://artsyproduct.atlassian.net/browse/FX-4707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4707): Track `editedArtworkList` event when a user edits an artwork list

.circleci/config.yml, README.md
Today we experienced yet another [Review App Update failure](https://app.circleci.com/pipelines/github/artsy/force/46718/workflows/e4fc64f0-ed84-43df-8a2c-66611c942c13/jobs/351539), where the [inline script in CircleCI config](https://github.com/artsy/force/blob/8d92b46e732815e2d1864479def64146a08ece0b/.circleci/config.yml#L114) failed to realize that the Review App already exists - it ran `build_review_app.sh` instead of `update_review_app.sh`.
Similar to in the past, the problem goes away upon [re-running the job](https://artsy.slack.com/archives/CP9P4KR35/p1680290046440389?thread_ts=1680280549.503849&cid=CP9P4KR35). So far we have not been able to repro the problem manually from within CircleCI container.
So for now, let's refactor the inline script to …
=> feat: add verbosity to inline review app create/update script

src/Apps/Settings/Routes/Insights/Components/InsightsAuctionResults.tsx
This PR updates the title of the auction results title in My Collection Insights page
=> fix: Update Insights's Auction Result title

src/Apps/Auction/Components/Form/ConditionsOfSaleCheckbox.tsx, src/Apps/Auction/Components/Form/__tests__/ConditionsOfSaleCheckbox.jest.tsx
Minor hackathon project to add additional text stating that all bids are binding in the auction registration flows. I tried this with the checkbox top-aligned when text breaks into multiple lines (which it always does now). I think it looks better centered on a single line.
Let's wait to merge this until we have signoff from the auctions team.
<details><summary>New COS checkbox text</summary>
Ignore the blue color, i took the screenshot while in the hover state.
</details>
<details><summary>With the checkbox bumped up to stay aligned with the first line of text</summary>
</details>
=> chore: add some copy to the COS checkbox note

src/Apps/CollectorProfile/Routes/Saves2/Components/Images/ArtworkListImageBorder.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Images/ArtworkListNoImage.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Images/FourUpImageLayout.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Images/StackedImageLayout.tsx
This PR solves [FX-4713]
Notion card: [link](https://www.notion.so/artsy/UX-suggestion-Display-border-for-artwork-image-as-we-did-it-for-placeholder-image-in-artwork-lis-3291ab26ee9e43e397957e2362d97f75?pvs=4)
Review app: [display-border-for-all-images](https://display-border-for-all-images.artsy.net/collector-profile/saves2)
| ![before](https://user-images.githubusercontent.com/3513494/229854712-50b911cd-7b48-4766-bb70-328ab7d30aef.png) | ![after](https://user-images.githubusercontent.com/3513494/229854751-fc639d42-33a8-4950-a9c2-233402b6164b.png) | …
=> feat(FX-4713): display border for all artwork images in artwork lists rail

src/Apps/CollectorProfile/Routes/Saves2/Components/Images/FourUpImageLayout.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/Images/StackedImageLayout.tsx
This PR solves [FX-4713]
| <img width="731" alt="before-1" src="https://user-images.githubusercontent.com/3513494/230066297-f606e411-fbac-4988-9663-c8653dffaaab.png"> | <img width="731" alt="after-1" src="https://user-images.githubusercontent.com/3513494/230066337-95c97dcf-0f10-4259-9463-94b09985ed38.png"> |
| <img width="377" alt="before-2" src="https://user-images.githubusercontent.com/3513494/230066427-4624259a-c437-49bd-ae7b-737b814cf9a3.png"> | <img width="377" alt="after-2" src="https://user-images.githubusercontent.com/3513494/230066453-d3d05f97-fd20-4b40-b31c-3a5101ecad60.png"> |
[GRO-434]: …
=> fix(FX-4713): specify size for image containers, specify size for images

src/Apps/Marketing/Components/MarketingAlternatingStack.tsx, src/Apps/Marketing/Components/MarketingHeader.tsx, src/Apps/Marketing/Components/MarketingQuizCTA.tsx, src/Apps/Marketing/Routes/MarketingFindArtYouWantRoute.tsx, src/Apps/Marketing/Routes/MarketingMeetArtAdvisorRoute.tsx, src/Apps/Marketing/Utils/brandPalette.ts
Re: [GRO-1639](https://artsyproduct.atlassian.net/browse/GRO-1639), [GRO-1640](https://artsyproduct.atlassian.net/browse/GRO-1640)
Gets these to a Q/A-able state. I'm going to tackle the footer updates separately then circle back to introduce a footer-less layout for the one route.
[GRO-1639]: https://artsyproduct.atlassian.net/browse/GRO-1639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GRO-1640]: https://artsyproduct.atlassian.net/browse/GRO-1640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(GRO-1637): refines brand campaign routes

src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx, src/Apps/CollectorProfile/Routes/Saves2/__tests__/CollectorProfileSaves2Route.jest.tsx
This PR solves [FX-4717]
Notion card: [link](https://www.notion.so/artsy/Internal-Server-Error-when-trying-to-load-custom-list-that-doesn-t-exist-Should-404-488676f9749e42f28e322002f46cf74b?pvs=4)
Review app: [artwork-list-404](https://artwork-list-404.artsy.net/collector-profile/saves2/unknown-artwork-list)
https://user-images.githubusercontent.com/3513494/230105690-153cc163-a174-4fee-9177-c7a90243f8ea.mp4
[FX-4717]: https://artsyproduct.atlassian.net/browse/FX-4717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4717): Respond with a 404 when navigating to a non-existent list

src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditArtworkListModal.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListForm/ArtworkListForm.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx, src/System/i18n/locales/en-US/translation.json
This PR solves [FX-4676]
Review app: [artwork-list-form-refactor.artsy.net](https://artwork-list-form-refactor.artsy.net/collector-profile/saves2)
This refactors the **Create Artwork List** and **Edit Artwork List**  modals by extracting a common `ArtworkListForm` that they both can use.
This reduces duplication and divergence between the two forms by allowing us to standardize on:
- Validation via a common Yup schema
- Use of common i18n strings
- Enforcing common desirable behavior, such as [implicit form submission](https://www.notion.so/artsy/Intuitively-tried-to-submit-the-Create-new-list-form-by-pressing-the-Enter-key-and-couldn-t-do-w-5c26ca3a1a424970995b822f9470e3d8)
- Enforcing common responsive behavior on desktop vs mobile
Because of the …
=> refactor(artwork lists): use a common ArtworkListForm in create and edit flows

src/Apps/CollectorProfile/Routes/Follows/CollectorProfileFollowsRoute.tsx, src/Apps/CollectorProfile/Routes/Saves/CollectorProfileSavesRoute.tsx, src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx, src/Apps/CollectorProfile/Routes/Saves2/__tests__/CollectorProfileSaves2Route.jest.tsx, src/Apps/Settings/Routes/Insights/InsightsRoute.tsx
This PR solves [FX-4719]
Notion card: [link](https://www.notion.so/Should-the-browser-tab-page-title-reflect-the-selected-Saves-tab-Currently-it-s-Collector-Profil-e6ebf577fd49409dabc80493f3e9f256)
| <img width="1919" alt="before" src="https://user-images.githubusercontent.com/3513494/230133713-32b2c6ad-2022-4ee4-a73b-2c83354a8470.png"> | <img width="1919" alt="after" src="https://user-images.githubusercontent.com/3513494/230133758-1cc5cdf5-f12a-462d-9024-abdc2dd29ef3.png"> | 
| <img width="1915" alt="before-3" src="https://user-images.githubusercontent.com/3513494/230140973-d06fdd8c-bc79-4a36-9633-12998f4a9411.png"> | <img width="1915" alt="after-3" …
=> chore(FX-4719): set correct page title for the new "Saves" tab

src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListContent.tsx
This PR solves [FX-4721]
Notion card: [link](https://www.notion.so/artsy/The-name-of-Oldest-first-sort-is-potentially-confusing-Probably-fine-with-Recently-Added-as-the-008440e1d8744e7fa00e463cc7a6e98e?pvs=4)
* Rename `Recently Saved` to `Recently Added`
* Rename `Oldest First` to `First Added`
| <img width="208" alt="image" src="https://user-images.githubusercontent.com/3513494/230457007-16c930f2-1226-46fc-aecb-83f38b7d5155.png"> | <img width="220" alt="image" src="https://user-images.githubusercontent.com/3513494/230456440-0082e09b-eda6-4cc4-8972-39504adc5b2f.png"> | 
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
=> chore(FX-4721): rename sort options

src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/DeleteArtworkListModal.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/AddArtworksModal.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/SelectArtworkListsModal/SelectArtworkListsModal.tsx
This PR solves [FX-4667]
[FX-4667]: https://artsyproduct.atlassian.net/browse/FX-4667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4667): Align modal width across different artwork list-related modals

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultsRoute.tsx, src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx, src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx, src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.jest.tsx, src/Apps/Artist/Utils/allowedAuctionResultFilters.ts, src/Apps/Artist/artistRoutes.tsx, src/__generated__/ArtistAuctionResultsQuery.graphql.ts, src/__generated__/ArtistAuctionResultsRoute_artist.graphql.ts, src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts, src/__generated__/ArtistAuctionResults_artist.graphql.ts, src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
This PR solves [DO-675]
This PR updates auction results tab.
- Updated page size to 50 per page
- Pagination uses pages instead of cursor
- Filter values `allowEmptyCreatedDates` and `page` are stored in the URL
[DO-675]: https://artsyproduct.atlassian.net/browse/DO-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: update auction results pagination

src/Apps/Order/Components/AddressModal.tsx, src/Apps/Order/Components/__tests__/AddressModal.jest.tsx, src/Apps/Order/Mutations/CreateUserAddress.ts
This PR solves [TX-1019]
This PR fixes the problem that when a user is adding a new address through "Add Address" modal in the shipping step, and their submitted address is not valid because of phone number, we are displaying a general error response (as opposed to a specific error when editing an address through the same modal). 
Since the error messages are different for phone number error when adding and editing an address, this PR adds the absent error message to our look-up hash.
Note that the changes in createUserAddress mutation file are seemingly necessary in order to mock the response of that mutation in our test setup. If you know they are not necessary, do let me know! 
[TX-1019]: https://artsyproduct.atlassian.net/browse/TX-1019?atlOrigin=eyJpIjo …
=> fix(TX-1019): Error display for invalid phone number submission via Add Address modal

src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertCreate.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertFind.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertReady.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingAlertSelectFilter.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowFind.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowHighlight.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveArtwork.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveFind.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingSaveHighlight.tsx, src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingContext.jest.tsx, src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingFollows.jest.tsx, src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingSaves.jest.tsx
Closes [GRO-1668](https://artsyproduct.atlassian.net/browse/GRO-1668)
This is a confusing one to explain and this PR solves a few different bugs which were related.
* The specific bug that came up during the demo was that state wasn't being synced between tabs correctly. `localStorage` is automatically in sync but the context store is not. So 4cb5806e3d67beca7787da19f480dead5ccef47e solves that.
Then thinking about the doubling problem a bit more some other edge cases came to mind.
* What if you follow someone in one tab, then follow someone in another tab? Now, on the first step of an onboarding chain we check to ensure that if you've started any other chain, we dismiss them all.
* What if you start a chain, see the 'find' tip for that thing but then ignore it by clicking somewhere else. …
=> fix(GRO-1668): Prevent multiple secondary tips from appearing simultaneously

src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButtonV2.tsx, src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsWatchLotButton.tsx, src/Apps/Artwork/Components/ArtworkImageBrowser/UtilButton.tsx, src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActionsSaveButtonV2.jest.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/__tests__/ArtworkListsHeader.jest.tsx, src/Apps/CollectorProfile/Routes/Saves2/__tests__/CollectorProfileSaves2Route.jest.tsx, src/Components/Artwork/SaveButton/useSaveArtworkToLists.ts, src/Components/Artwork/useArtworkLists.ts, src/System/i18n/locales/en-US/translation.json
This PR solves [FX-4737], [FX-4738]
* [Review app](https://artwork-list-copy-changes.artsy.net/)
* [Figma file](https://www.figma.com/file/wSV2KNz97Tyj8HkH2ZYAkB/Save-%2B-Lists?node-id=1961-232743&t=GnSm3kVwUDGayQux-0)
Change `Watch lot` to `Watching lot` when artwork lot becomes watched
| <video src="https://user-images.githubusercontent.com/3513494/232109629-a84d05df-83e1-47bc-a28a-053c252822d8.mp4" />  | <video src="https://user-images.githubusercontent.com/3513494/232087919-3c9fcbfe-3cc2-4bfc-9deb-9ff097ec0cf5.mp4" />  | 
Display **Artwork saved** toast message instead of **Watch lot saved** for auction artworks
| <video …
=> chore(FX-4737, FX-4738): artwork list copy changes (phase 2)

.secrets.baseline, src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/Components/ArtistAutocomplete.tsx, src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtistStep.tsx, src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormDetails.tsx, src/Apps/MyCollection/Routes/EditArtwork/MyCollectionCreateArtwork.tsx, src/Apps/MyCollection/Routes/EditArtwork/MyCollectionEditArtwork.tsx, src/Apps/MyCollection/Routes/EditArtwork/Utils/artworkModel.ts, src/Apps/MyCollection/Routes/EditArtwork/__tests__/MyCollectionEditArtwork.jest.tsx, src/Apps/MyCollection/Routes/Hooks/__tests__/useMyCollectionTracking.jest.tsx, src/Apps/MyCollection/Routes/Hooks/useMyCollectionTracking.tsx, src/__generated__/ArtistAutocomplete_SearchConnection_Query.graphql.ts, src/__generated__/MyCollectionArtworkFormArtistStep_me.graphql.ts, src/__generated__/MyCollectionCreateArtworkTest_Query.graphql.ts, src/__generated__/MyCollectionEditArtworkTest_Query.graphql.ts, src/__generated__/MyCollectionEditArtwork_artwork.graphql.ts, src/__generated__/collectorProfileRoutes_MyCollectionArtworkFormQuery.graphql.ts, src/__generated__/collectorProfileRoutes_MyCollectionArtworkUploadQuery.graphql.ts, src/__generated__/myCollectionRoutes_MyCollectionArtworkFormQuery.graphql.ts, src/__generated__/myCollectionRoutes_MyCollectionArtworkUploadQuery.graphql.ts
This PR solves [CX-3611]
Adding and setting the `isP1Artist` field on the `saveCollectedArtwork` tracking event.
[CX-3611]: https://artsyproduct.atlassian.net/browse/CX-3611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Add isP1Artist to saveCollectedArtwork tracking event

src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuthenticityCertificate.tsx, src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarShippingInformation.tsx, src/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx, src/Apps/Auctions/AuctionsApp.tsx, src/Apps/Auctions/__tests__/AuctionsApp.jest.tsx, src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FAQSWA.tsx, src/Apps/Consign/Routes/MarketingLanding/Components/__tests__/FAQSWA.jest.tsx, src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/ArtworkDetails.tsx, src/Apps/Consign/Routes/SubmissionFlow/ArtworkDetails/__tests__/ArtworkDetails.jest.tsx, src/Apps/Conversation/Components/DetailsSidebar.tsx, src/Apps/IdentityVerification/IdentityVerificationApp/index.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWAHowItWorksModal.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/MyCollectionArtworkSWASectionSubmitted.tsx, src/Apps/MyCollection/Routes/MyCollectionArtwork/Components/__tests__/MyCollectionArtworkSWAHowItWorksModal.jest.tsx, src/Apps/Order/Components/BuyerGuarantee.tsx, src/Apps/Order/Components/StickyFooter.tsx, src/Apps/Order/Components/__tests__/StickyFooter.jest.tsx, src/Components/Footer/Footer.tsx, src/Server/middleware/hardcodedRedirects.ts
This PR solves [NX-3492]
Changes Support links from Zendesk to Salesforce.
[NX-3492]: https://artsyproduct.atlassian.net/browse/NX-3492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(NX-3492): change support links from ZD to Salesforce

src/Components/NavBar/NavBarLoggedInActions.tsx
In general it's preferable to use `aria-label` on the actual trigger.
=> fix(nav): adds aria-label to your account; removes redundant titles

.circleci/config.yml
Reverts artsy/force#11050. 
Reverting this because it looks like something changed in the underlying `s3` lib, since the docs still show [this being used](https://circleci.com/developer/orbs/orb/circleci/aws-s3).
=> Revert "chore(deps): update aws-s3 orb from 2.0.0 to v3"

Dockerfile, hokusai/production.yml, hokusai/staging.yml
This PR solves [PLATFORM-5131]
Force pods memory [usage since June 2022](https://app.datadoghq.com/dashboard/2n5-6tr-ypp/kubernetes-deployments?fullscreen_end_ts=1656915540000&fullscreen_paused=true&fullscreen_section=overview&fullscreen_start_ts=1649406000000&fullscreen_widget=5114866942402968&tpl_var_deployment%5B0%5D=force-web&tpl_var_hpa%5B0%5D=force-web&from_ts=1649406000000&to_ts=1656915540000&live=false) has been much lower than before. Reduce their memory request/limit to reflect actual usage.
- Reduce Staging memory request/limit from 1G/1.5G to 500M/1G
- Reduce Prod memory request/limit from 1.5G/3.5G to 1G/2G
[Prod actual usage](https://app.datadoghq.com/dashboard/2n5-6tr-ypp/kubernetes-deployments?fullscreen_end_ts=1682019962714&fullscreen_pause …
=> feat: reduce memory request/limit to reflect actual usage

src/Apps/Order/Routes/Payment/PaymentContent.tsx, src/Apps/Order/Routes/__tests__/Payment.jest.tsx
This PR solves [TX-1134]
Now that bank transfers have the ability to be the only payment method at checkout via private sales, we have added a title to clarify the payment method being used. 
[TX-1134]: https://artsyproduct.atlassian.net/browse/TX-1134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-1134): add title when bank transfer is the only payment method

src/Apps/Home/Components/HomeContentCards/HomeContentCards.tsx
After some back-and-forth with Braze support and looking at their reproduction logs I'm thinking we were too aggressive in our rendering of fallback cards. I don't fully understand when/why this happens but it's possible for `renderFallback` to be true AND for us to have more than 0 `cards`. When that's true we should render the cards, not the fallback!
So that's what this PR aims to do - it shuffles the conditional rendering logic so that when both things are true we render `BrazeCards` rather than `FallbackCards`. My plan is to deploy this on Monday and call for eyes on this over the next few days. If we don't see issues then we can call this another win on the improvements to our content card code.
/cc @artsy/grow-devs @isakelaris @kathytafel
=> fix: Skip fallback when Braze cards exist

cypress/e2e/settings.cy.ts
This PR disables a sporadically failing cypress test.
More [context here](https://artsy.slack.com/archives/C2TQ4PT8R/p1682430821427279) but the short of it is that following [runtime upgrade](https://github.com/artsy/force/pull/12243) a cypress [test](https://github.com/artsy/force/blob/main/cypress/e2e/settings.cy.ts) has been sporadically failing. This PR skips the test to remedy CI failures. Hoping to remove this sometime this week but will depend on how soon the issue can be resolved.
=> test: skip cypress settings redirect

scripts/smoke_test.sh
This PR is a follow-up to https://github.com/artsy/force/pull/12311
The earlier added `timeout` [stops the script on error](https://app.circleci.com/pipelines/github/artsy/force/47846/workflows/084e8b05-2758-4f38-888b-cea2f7bb2e7f/jobs/359559?invite=true#step-101-17) because `set -e` is set at the top. This fixes that problem and improves the intention disabling the exit on error flag during cypress install to allow the script to continue in case of timeout.
If the install command succeeds the script will continue, if any other error is thrown that's not timeout `124`, the script will exit with that error.
=> fix: disable exit on error during cypress install

src/Apps/Artist/artistRoutes.tsx, src/__generated__/artistRoutes_AuctionResultQuery.graphql.ts
This PR solves: [thread](https://artsy.slack.com/archives/C03D5MXDAN7/p1682517072960289)
Make the auction result screen main query principal using the `@principalField` directive.
**Before**
**After**
=> fix: make auction result main query principal

src/Apps/Home/Components/HomeContentCards/FallbackCards.tsx
Data update here that adds another content card no biggie. Looks like this:
I believe they want to time this to go out later today so I'll assign myself and merge/usher this along when the time is right.
https://artsyproduct.atlassian.net/browse/GRO-1648
=> feat: Add fallback card for brand campaign GRO-1648

src/Apps/Home/Components/HomeContentCards/FallbackCards.tsx
I mean come on Jon get your life together:
```
hyphen: -
en dash: – (option + hyphen)
em dash: — (option + shift + hyphen)
```
h/t @isakelaris 
https://artsyproduct.atlassian.net/browse/GRO-1648
=> fix: Use an emdash like a gentleman GRO-1648

src/Components/SalesforceWrapper.tsx
This PR solves [NX-3530]
SF persisted after navigating to a different page. The component needs to be hidden when unmounting.
[NX-3530]: https://artsyproduct.atlassian.net/browse/NX-3530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(NX-3530): hide SF chat after unmounting. Same as the zendesk component

src/Apps/Auction/Components/AuctionArtworkFilter.tsx, src/Apps/Auction/Components/__tests__/AuctionArtworkFilter.jest.tsx, src/Apps/Auction/auctionRoutes.tsx
This PR solves [FX-4744]
We found that auction artwork grids were not respecting an incoming `sort` param in the URL querystring, and instead always sorting by lot number (`sort: sale_position`) —
```
https://www.artsy.net/auction/artsy-auction-street-art-2?sort=-prices
↑↑↑↑↑↑↑↑↑↑↑↑ ignored
```
This is because the default value of `sale_position` for the `sort` param was being set later in the request lifecycle, and was thus clobbering the value coming in from the querystring.
This PR hoists that default out of the later location (`AuctionArtworkFilter.tsx`) up into an earlier location (`auctionRoutes.tsx`) so that it can be correctly overriden by the URL param.
The grid is now sorted correctly…
✓ when there is no `sort` param in the URL _(defaults to …
=> fix: set auction artwork initial sort from querystring

src/Apps/Order/Routes/Review/index.tsx, src/Apps/Order/Routes/__fixtures__/MutationResults/submitOfferOrder.ts, src/Apps/Order/Routes/__tests__/Review.jest.tsx
This PR solves [PRO-85](https://artsyproduct.atlassian.net/browse/PRO-85)
Followup from https://github.com/artsy/exchange/pull/1637, see there for more context.
Draft until https://github.com/artsy/metaphysics/pull/4983 is merged & deployed.
[PRO-84]: https://artsyproduct.atlassian.net/browse/PRO-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PRO-85]: https://artsyproduct.atlassian.net/browse/PRO-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(PRO-85): use order state when routing after offer

package.json, src/Server/datadog.ts, yarn.lock
This PR solves [PLATFORM-5144](https://artsyproduct.atlassian.net/browse/PLATFORM-5144) and is a follow-up to https://github.com/artsy/force/pull/12328
This upgrades dd-trace library to v2.31.0, the latest "Maintenance" version ([version table](https://github.com/DataDog/dd-trace-js/tree/master#version-release-lines-and-maintenance)).
Looking at [v1 -> v2 migration doc](https://github.com/DataDog/dd-trace-js/blob/master/MIGRATING.md#10-to-20) it looks to me like none of the migration changes apply to Force:
- Force does not use the removed Configuration options: `enabled`, `debug`
- Force does not appear to set `DD_TRACE_ENABLED` env var however when instrumenting the library, tracer is [enabled by …
=> chore: upgrade dd-trace to maintenance version

src/Apps/Collect/Server/__tests__/redirectCollectionToArtistSeries.jest.ts, src/Apps/Collect/Server/redirectCollectionToArtistSeries.ts
Slack thread: [Link](https://artsy.slack.com/archives/C9SATFLUU/p1683048414783759)
Review app: [collection-redirect](https://collection-redirect.artsy.net/)
Some redirects from [here](https://github.com/artsy/force/blob/e70881afd24e42de7f9756b9f412cdbdbf65fd5d/src/Apps/Collect/Utils/collectionToArtistSeriesSlugMap.tsx#L1) 
| [banksy-girl-with-balloon](https://www.artsy.net/collection/banksy-girl-with-balloon) | [banksy-girl-with-balloon](https://collection-redirect.artsy.net/collection/banksy-girl-with-balloon) | 
| [alec-monopoly-monopoly-man](https://www.artsy.net/collection/alec-monopoly-monopoly-man) | [alec-monopoly-monopoly-man](https://collection-redirect.artsy.net/collec …
=> fix: use correct param for redirect from `/collection/id:` to `/artist-series/:id`

src/Apps/Home/Components/HomeContentCards/FallbackCards.tsx
Removing this card per marketing!
https://artsyproduct.atlassian.net/browse/GRO-1690
=> chore: Remove stale fallback card GRO-1690

src/Apps/Auctions/Routes/EndingSoonAuctionsGrid.tsx, src/Apps/NewForYou/Components/NewForYouArtworksGrid.tsx
This PR solves [CX-3670]
Display artworks in 2/3/4 columns depending on the screen size
https://user-images.githubusercontent.com/36167539/235716901-58fc53bf-4fd2-402d-88d1-7e713509d571.mov
[CX-3670]: https://artsyproduct.atlassian.net/browse/CX-3670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix(CX-3670): display artworks in 2/3/4 columns

src/Apps/Artist/Server/__tests__/redirect.jest.ts, src/Apps/Artist/Server/redirect.ts, src/Apps/Artist/artistRoutes.tsx
This PR solves [FX-4778]
The [cleanup work](https://github.com/artsy/gravity/pull/16308) for the trending score experiment uncovered the fact that the URLs we generated in the course of that experiment, e.g...
```
https://www.artsy.net/artist/sam-king/works-for-sale?sort=-default_trending_score&metric=in
^^^^^^^^^^^^^^^^^^^^^^^
soon-to-be invalid!
```
...got [shared](https://artsy.slack.com/archives/C9SATFLUU/p1683131630609639?thread_ts=1683131226.200629&cid=C9SATFLUU) and ultimately [indexed](https://artsy.slack.com/archives/C9SATFLUU/p1683131966269079?thread_ts=1683131226.200629&cid=C9SATFLUU) by search engines.
Before we proceed with the cleanup we want to make sure we redirect these experimental URLs back to their canonical counterparts, e.g…
``` …
```
=> fix: 301 redirect invalid artist urls from trending score a/b

src/Components/AddressForm.tsx, src/Components/CountrySelect.tsx
I would like to write an Integrity test to place an order that is shipped or billed to a country other than the United States, but there is no ID available on the address form's country select component to make that easy.
~I made the ID prop optional so that different forms can give it an ID that is consistent with other form elements (ie. `AddressForm_name`, `AddressForm_country`, etc.). I'd love to hear about whether that's a weird thing to do in React or not.~
I added a `data-test` attribute to the country selection element so that it can be easily selected. I also added `data-test` attributes to the rest of the elements on this form to be able to standardize this behavior.
=> add data- attributes to address form elements for tests

src/Components/NavBar/NavBar.tsx, src/Components/Search/NewSearch/Mobile/Overlay.tsx, src/Components/Search/NewSearch/Mobile/OverlayBase.tsx, src/Components/Search/NewSearch/Mobile/SearchBar.tsx, src/Components/Search/NewSearch/NewSearchBar.tsx, src/Components/Search/NewSearch/NewSearchBarInput.tsx
This PR solves [FX-4657]
- create a new full screen overlay/modal 
- if feature flag is enabled, when user presses the search input (on mWeb only) they see the new overlay
- overlay should have an x button to dismiss
- overlay should include search input as specified in design
https://github.com/artsy/force/assets/3934579/1d11f0c4-7982-4c95-ac08-b01677ac36a1
[FX-4657]: https://artsyproduct.atlassian.net/browse/FX-4657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FX-4657): mobile web search overlay

docs/developing_local_palette.md, package.json, scripts/yalc-link-local-palette, scripts/yalc-unlink-local-palette
Related:
- https://github.com/artsy/palette/pull/1294
Similar to Eigen and Energy, this adds yalc for developing packages locally. To run:
```bash
cd packages/palette
yarn local-palette-dev
cd force 
yarn local-palette-dev
```
=> feat(dev): add yalc for local package dev

src/Apps/Order/Routes/Review/index.tsx, src/Apps/Order/Routes/__tests__/Review.jest.tsx
This PR solves PRO-130
Turns out we were routing based on the _pending_ offer and not the response from the mutation.
=> fix(PRO-130): correct routing after in_review offer

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/FooterBanner.tsx
Add space after & before "Become a partner" on SWA landing page.
=> fix: Add space after & before "Become a partner" on SWA landing page.

src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/MeetTheSpecialists.tsx, src/Apps/Consign/Routes/MarketingLanding/Components/LandingPage/SpecialistsData.tsx
This PR updates the SWA specialist key to match the key in [Eigen](https://github.com/artsy/eigen/blob/main/src/app/Scenes/SellWithArtsy/utils/useSWALandingPageData.tsx#L35). There is a typo in the key but it will be difficult to fix because Eigen fetches the data from S3 and old versions expect the key with the typo :/
=> fix: Update SWA specialist key to match key in eigen

src/Apps/Artist/artistRoutes.tsx
Closes [GRO-1718](https://artsyproduct.atlassian.net/browse/GRO-1718)
[GRO-1718]: https://artsyproduct.atlassian.net/browse/GRO-1718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
We were unintentionally stripping out the query params on these redirects. This posed a particular problem for links that exist in emails, which would link to `/works-for-sale` routes with filters selected.
=> fix(artist): preserves query string

src/Components/CascadingEndTimesBanner.tsx
This PR solves [TX-1196](https://artsyproduct.atlassian.net/browse/TX-1196?atlOrigin=eyJpIjoiYTAxNjUzNDU5ZDBiNDQ0ZGJlNTA0Y2JmMDc2NzBmNDYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
Broken:
Fixed:
[TX-1196]: https://artsyproduct.atlassian.net/browse/TX-1196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: cascading bids banner link has :visited state making it invisible

src/Apps/Order/Components/SavedAddresses.tsx, src/Apps/Order/Components/__tests__/SavedAddresses.jest.tsx, src/Apps/Order/Routes/Shipping/index.tsx
The type of this PR is: **Feature/Refactor**
This PR solves [TX-1168]
This PR changes the "add a new address" button on the shipping page to a clickable text button from a standard button. 
I also went ahead and removed the `inCollectorProfile` logic and components from `SavedAddresses.tsx` as it is no longer used. 
[TX-1168]: https://artsyproduct.atlassian.net/browse/TX-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-1168): update add new address button + collector profile cleanup

src/Apps/Order/Routes/Shipping/index.tsx, src/Apps/Order/Routes/__tests__/Shipping.jest.tsx, src/Components/Address/AddressModalFields.tsx, src/Components/AddressForm.tsx
This PR solves [TX-1151]
This PR updates the layout for address forms in the checkout flow, in order to provide better UX after the input styles are updated in Palette. 
[TX-1151]: https://artsyproduct.atlassian.net/browse/TX-1151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-1151): Update address form layouts in the checkout flow

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/Apps/Artist/Routes/AuctionResults/Components/ArtistAuctionResultsEmptyState.tsx, src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx, src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx, src/__generated__/ArtistAuctionResultsQuery.graphql.ts, src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts, src/__generated__/ArtistAuctionResults_artist.graphql.ts, src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
Closes [GRO-1725](https://artsyproduct.atlassian.net/browse/GRO-1725)
We can check the `counts.auctionResults` to display the full empty component; when there's 0 results we can just leverage the existing filter empty component.
A slight rough patch here is that it doesn't handle resetting the keyword correctly:
https://github.com/artsy/force/assets/112297/b703816e-83cb-4fa5-ab13-fbbce55e63a6
The main reason this is an issue is because we're debouncing the query by debouncing setting the keyword. This is a bit backwards: we want to actually debounce the query execution for all filters. The filter context state should be a true representation. I'm not going to fix that in this PR however.
[GRO-1725]: https://artsyproduct.atlassian.net/browse/GRO-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> fix(artist): fixes empty state for filters on auction-results

src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/__tests__/EditArtworkListModal.jest.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListForm/ArtworkListForm.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/CreateNewListModal.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/CreateNewListModal/__tests__/CreateNewListModal.jest.tsx, src/System/i18n/locales/en-US/translation.json
This PR solves [FX-4704] and [FX-4740]
This introduces two further client-side behaviors to the Artwork List name field:
- leading and trailing whitespaces are trimmed before submitting, on create (this behavior [already existed](https://github.com/artsy/force/blob/e4e9939edf84ce200774a9fa4cee4347eab20a66/src/Apps/CollectorProfile/Routes/Saves2/Components/Actions/EditArtworkListModal.tsx#L57) on edit) — [89e2446](https://github.com/artsy/force/pull/12435/commits/89e2446ffc4fde78525d22935ff939c1b169bbfc)
- the name field is validated to be non-empty — [456e05b](https://github.com/artsy/force/pull/12435/commits/456e05bcbaced399a9ee054f095ae504c31f39f4)
The screencap below demonstrates an empty name being rejected, and then a name with  whitespace being …
=> feat(artwork lists): improve name handling

src/Components/Search/NewSearch/NewSearchBarFooter.tsx, src/Components/Search/NewSearch/NewSearchBarInput.tsx, src/Components/Search/NewSearch/SuggestionItem/SuggestionItemLink.ts
This PR solves [FX-4789]
In this PR `background-color:white` has been removed to  give focus to the search bar elements while navigating using the keyboard arrow up and down buttons
https://github.com/artsy/force/assets/17421923/88fdda54-a06c-475a-bf45-9ce7862e784f
[FX-4789]: https://artsyproduct.atlassian.net/browse/FX-4789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: keyboard arrow navigation

package.json, src/Apps/Order/Routes/Payment/index.tsx, yarn.lock
Paired with @iskounen 
This PR adds the new `errorMessageViewed` [event](https://github.com/artsy/cohesion/pull/431) to the payments order route whenever a user views an error dialog. 
=> chore: add error message event tracking for payment step

src/Apps/Order/Routes/Shipping/index.tsx
This is a follow-up to #12447 that adds event tracking to the shipping route of the checkout flow. This will allow us to know which error messages are displayed to users in this step. Knowing when the generic "An error occurred" error message gets displayed to users is the most interesting, since we suspect those to be dead-ends in the checkout flow.
=> chore: add dead-end event to shipping step

src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListItem.tsx
This PR solves [FX-4722]
Review app: https://fx-4722-a11y.artsy.net/
Restores the focus styles that were missing when you navigated the Artwork Lists rail via keyboard.
This required moving the styling from the `Flex` to the containing `RouterLink`, and giving it `display: block` to fix the collapsed focus outline problem.
Both of the screencaps below show the results of keyboard navigation: navigating with `Tab` and selecting with `Enter`.
|Before|After|
|---|---|
| <video src="https://github.com/artsy/force/assets/140521/90cceef1-2b85-4ae2-bdb5-1fa1b5eeaebc" /> | <video src="https://github.com/artsy/force/assets/140521/fef166a7-7134-4744-bb03-5e17e86a60a9" /> |
The Artwork List cards _were_ in fact already focusable and tabbable, as you can see in the …
=> fix(artwork lists): improve a11y by making focus visible

cypress/e2e/artist.cy.js
https://github.com/artsy/metaphysics/pull/5024 changed the format of the description `<meta>` tag on that artist page. 
That needs to be reflected in the smoke test that sits inside of Force (this is currently causing all Force builds to fail in CI).
=> fix(artist): update smoke test to match latest meta description format

Dockerfile, scripts/jest.sh, scripts/start.sh
This PR solves [PLATFORM-5149](https://artsyproduct.atlassian.net/browse/PLATFORM-5149)
To fix [distributed downstream tracing in datadog](https://github.com/DataDog/dd-trace-js/issues/2388) we are going to disable the [experimental fetch API](https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental) that is enabled by default in node v18+.
Force uses [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) and so disabling this experimental feature should have no bearing on the application except that it will fix distributed tracing that has been not working since the runtime upgrade.
[Review app](https://disable-experimental-fetch.artsy.net/)
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJp …
=> feat: disable experimental fetch

src/Utils/Hooks/useSizeAndPosition.ts
Cherry-picking off https://github.com/artsy/force/pull/12280 so that the PR is clean in case of revert.
=> fix(usesizeandposition): ensures that if node is added after hook is set up; we still get geometry

src/Apps/BuyerGuarantee/Routes/BuyerGuaranteeIndex.tsx
See slack thread:
https://artsy.slack.com/archives/C04U9SJ5A0K/p1685979530945009
=> chore: replace zendesk link in buyer guarantee page with SF one

package.json, src/Components/CookieConsentManager/CookieConsentBanner.tsx, src/Components/CookieConsentManager/CookieConsentManager.tsx, src/Components/CookieConsentManager/CookieConsentManagerContext.tsx, src/Components/CookieConsentManager/CookieConsentManagerDialog.tsx, src/Components/CookieConsentManager/CookieConsentManagerSetter.tsx, src/Components/CookieConsentManager/README.md, src/Components/CookieConsentManager/__tests__/categories.jest.ts, src/Components/CookieConsentManager/categories.ts, src/Components/CookieConsentManager/cookieConsentManagerServerRoutes.ts, src/Components/CookieConsentManager/useConsentRequired.ts, src/Components/CookieConsentManager/utils.ts, yarn.lock
Alright, take two. 🎬
Original PR: https://github.com/artsy/force/pull/12280
To summarize: the problem I ran into, and why this was reverted, was that, previously, we were conditionally returning out a "different" set of children, sans context. This somehow broke routing: links would work fine but it was pressing browser back would change the URL without actually navigating the page. Here I just thread children through unconditionally and then conditionally render only the banner/dialog.
This PR _only_ adds the code, and does not yet enable it. So it's safe to merge. I'll make a separate PR with a review app again to enable it. (Review app because I'll be adding some specs covering basic back/forward navigation to ensure routing is OK and won't merge until everything is green, flaky or …
=> feat(cookie-consent): implements cookie consent manager

src/Apps/Order/Routes/Review/index.tsx
This PR solves [TX-1229]
This PR adds the new `errorMessageViewed` [event](https://github.com/artsy/cohesion/pull/431) to the review order route whenever a user views an error dialog.
[TX-1229]: https://artsyproduct.atlassian.net/browse/TX-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(TX-1229): add error message tracking for review route

src/Apps/Home/homeRoutes.tsx, src/__generated__/homeRoutes_HomeQuery.graphql.ts
This PR sits on top of https://github.com/artsy/metaphysics/pull/5072 and changes the default behavior of the homepage to show only active hero units by default. This should ease confusion around why inactive hero units are showing up for admins.
Then I also added support for a query param called `show_all` and when this is set to true, then a signed in admin can preview any inactive hero units that they are working on.
https://artsyproduct.atlassian.net/browse/GRO-1755
=> feat: Show only active hero units by default GRO-1755

src/Apps/Order/Routes/Payment/PaymentContent.tsx, src/Apps/Order/Routes/__tests__/Payment.jest.tsx
This PR solves [TX-1213]
This PR adds "UK bank accounts will be charged in GBP once the gallery accepts the order" to the SEPA payment method selection copy. 
[TX-1213]: https://artsyproduct.atlassian.net/browse/TX-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TX-1213): update SEPA copy

src/Apps/CollectorProfile/Routes/Saves2/CollectorProfileSaves2Route.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListArtworksGrid.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListContent.tsx, src/Apps/CollectorProfile/Routes/Saves2/Components/ArtworkListItem.tsx, src/Apps/CollectorProfile/Routes/Saves2/Utils/useArtworkListVisibility.tsx
This PR solves [FX-4802]  & [FX-4803]
Review app: https://fx-artwork-list-scroll.artsy.net/collector-profile/saves
Based on internal beta feedback we want to address the usability of the Artwork Lists area on small screens.
This PR introduces some selective auto-scroll behavior, and aims to be as helpful and unobtrusive as possible.
Therefore an artwork list's artwork grid content will be scrolled into view when and only when:
- the artwork list content is **out of view** (i.e. below the bottom edge of the viewport https://github.com/artsy/force/pull/12502/commits/90f6ee13f7b0c49127e8c88c8ebecd5616166be8)
- the user is **expecting** to see new content (i.e. they have interacted with the Artwork Lists rail …
=> feat(artwork lists): improve visibility of artwork list content on smaller screens

src/Apps/Components/AppToasts.tsx
Review app: [improvement-for-toast](https://improvement-for-toast.artsy.net/)
This PR solves [FX-4718]
There may be situations when it will be difficult to click on the buttons if the toast message is displayed. The problem is due to the fact that toast messages have paddings that block clicks. If the button is in this zone, the click will not be processed
| <video src="https://github.com/artsy/force/assets/3513494/77463d51-8d10-48f7-817f-a465faaabb03" /> | <video src="https://github.com/artsy/force/assets/3513494/f81ad660-125d-4ee2-9488-9b2f82ca526c" /> | 
[GRO-434]: https://artsyproduct.atlassian.net/browse/GRO-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> chore(FX-4718): it's hard to click on the buttons if the toast message is displayed

src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArtworkFormArtworkStep.tsx, src/Apps/MyCollection/Routes/EditArtwork/Components/MyCollectionArworkSearch.tsx, src/__generated__/MyCollectionArworkSearchQuery.graphql.ts
This PR solves [CX-3780]
We are currently saving the large version of the image as image url assuming the latter always exists. This is not the case though when Gemini fails. We are updating the logic now to parse the available image versions and use the first biggest image available.
**Next step:** Introduce the same fix to **Eigen**
| Before                                                                              | After                                                                               |
|-------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|
| https://github.com/artsy/force/assets/11945712/4941487c-c6b6-4883-8ca8-aa391f52f7 …
=> fix(CX-3780): show artwork image inside my collection when gemini processing fails

cypress/e2e/artist.cy.js
This adds a 10s timeout (not ideal) to the artist acceptance test.
This test uses Pablo Picasso and must load quite a lot of artworks hence the longer timeout.
=> chore(e2e): adding timeout to artist cypress run

src/Apps/Artist/Routes/AuctionResults/Components/ArtistAuctionResultsEmptyState.tsx
Very minor update to the copy on the auctions tab when there are no results.
https://artsyproduct.atlassian.net/browse/GRO-1747
=> chore: Update empty message for no auction results GRO-1747

src/Apps/Order/Routes/Shipping/index.tsx, src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
This PR intends to solve 2 issues:
- Requesting new quotes whenever the price changes if the collector decides to go back to the offer step and make a lower or higher value offer.
Before:
https://github.com/artsy/force/assets/7518671/49a3baef-d346-4a55-8aaf-1f091bf2016e
After:
https://github.com/artsy/force/assets/7518671/2ab6e424-16d6-4be6-8eef-2bf4dc3b40bf
- The broken behaviour when toggling between pickup and shipping, caused by a faulty check on `onSelectShippingOption` where the code assumed that the shipping option would be changed after the [setShippingOption](https://github.com/artsy/force/compare/leamotta/artsy-shipping-effect?expand=1#diff-e0afcd1142a7fdd8a803a66f3f2490eb8db1d25fe9d66bd889fefd4852937ec6R553) line. However this is not the case and …
=> fix: artsy shipping quote selection

src/Apps/Order/Routes/Review/index.tsx, src/Apps/Order/Routes/__tests__/Review.jest.tsx
This PR adds error handling in the Review step of the checkout flow for a new error code that will be sent from Exchange when the seller's Stripe Connect account is inactive. (See: artsy/exchange#1700)
When this error code is encountered, the buyer will be shown the following error message:
> **An error occurred**
> Your payment could not be processed. Please contact orders@artsy.net for assistance.
=> feat: handle stripe account inactive error in checkout

src/Apps/Shows/Routes/ShowsCity.tsx, src/__generated__/ShowsCityQuery.graphql.ts, src/__generated__/ShowsCity_Test_Query.graphql.ts, src/__generated__/ShowsCity_city.graphql.ts, src/__generated__/showsRoutes_ShowsCityQuery.graphql.ts
This PR comes off the back of a complaint where the past shows rail is showing only a single gallery even though there are multiple galleries in the specific city. As the results are paginated and sorted by gallery name, they are very one sided when a gallery has a large number of closed events.
The fix means we now sort by end date and should mean that galleries are more varied, especially when certain galleries are no longer with Artsy, yet still have a large amount of past shows and a name which was favoured for sorting.
=> fix: sort past shows by end date

src/Components/Notifications/NotificationsEmptyStateByType.tsx, src/Components/Notifications/__tests__/NotificationsEmptyStateByType.jest.tsx
Update copy for Activity Panel empty states (both All and Alerts tabs) based on feedback from Content Design team.
Jira: [FX-4677](https://artsyproduct.atlassian.net/browse/FX-4677)
| <img width="475" alt="Screenshot 2023-06-27 at 12 09 03" src="https://github.com/artsy/force/assets/123595/bf2877ba-4c35-4e52-a801-c59781c1847f"> | <img width="469" alt="Screenshot 2023-06-27 at 12 07 55" src="https://github.com/artsy/force/assets/123595/53364afa-6548-4a4a-bfdb-386787e9f077"> |
| <img width="480" alt="Screenshot 2023-06-27 at 12 09 08" src="https://github.com/artsy/force/assets/123595/704197af-1b39-4a17-b75b-7c8e649c7ec8"> | <img width="476" alt="Screenshot 2023-06-27 at 12 08 06" …
=> feat: update activity panel empty state copy

src/Apps/Artwork/Components/ArtworkChatBubble.tsx
[NX-3562]
We're calling SalesforceWrapper twice inside ArtworkChatBubble (mistakenly done during #12559). This commit removes one of them.
[NX-3562]: https://artsyproduct.atlassian.net/browse/NX-3562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
cc @artsy/negotiate-devs
=> fix(NX-3562): Remove duplicated component

cypress/e2e/artist.cy.ts, cypress/helpers/visitWithStatusRetries.ts, src/Apps/Example/ExampleApp.tsx, src/Apps/Example/Routes/Search/SearchRoute.tsx, src/Apps/Example/Routes/Search/SearchRouteOption.tsx, src/Apps/Example/exampleRoutes.tsx, src/__generated__/SearchRouteOption_artist.graphql.ts, src/__generated__/SearchRouteQuery.graphql.ts
@nickskalkin was wondering how to use a fragment container with the `AutocompleteInput` — the answer is: it just works. Use the `matchConnection` instead of the `searchConnection` (to be deprecated), however.
https://github.com/artsy/force/assets/112297/f1de9123-5c1e-4069-8907-dc799421e47b
=> chore: adds search example using autocomplete input

src/Components/Search/NewSearch/NewSearchBarFooter.tsx, src/Components/Search/NewSearch/NewSearchBarInput.tsx
This PR solves [FX-4827]
Currently search bar is broken on small devices: if search dropdown is bigger than display area - dropdown is "flipped" (displayed above the search input). This is something we want to avoid, and it became possible to enforce "un-flippable" behaviour after https://github.com/artsy/palette/pull/1303 was merged.
Apart from that, I've changed the "See full results..." item from being a regular option to a footer. Now if dropdown area doesn't fit into the screen, footer is still visible (options area becomes scrollable).
|---|---|
| <video src="https://github.com/artsy/force/assets/3934579/4036fb6a-1b4c-4b34-93c3-003f6fe70c33" /> | <video src="https://github.com/artsy/force/assets/3934579/2abcf8a5-2734-4ca8-bc8c-689c2a …
=> fix(FX-4827): fixes new search bar for small screens

src/Apps/Order/Components/BankAccountPicker.tsx, src/Apps/Order/Routes/Payment/index.tsx, src/Apps/Order/Utils/orderUtils.ts
This PR is an attempt to understand how the payment route works by refactoring the hook that is responsible for picking a bank account to be selected when either `US_BANK_ACCOUNT` or `SEPA_DEBIT` is the selected payment method.
I want to refactor it for the following reasons:
1. I don't think that this hook should do anything when `CREDIT_CARD` or `WIRE_TRANSFER` is selected. (It currently updates the `bankAccountSelection` state property to `{ type: "new" }`)
1. I think that this logic would be easier to read if it were in simple if-else statements.
1. I think that the `BankAccountPicker` component should house this logic.
I would also like to see if I can remove the `// eslint-disable-next-line` by resolving the warning that it otherwise generates.
=> [#FF] refactor: bank account auto-selection hook

src/Apps/Order/Components/BankAccountPicker.tsx, src/Apps/Order/Routes/Payment/index.tsx, src/Apps/Order/Utils/orderUtils.ts
Reverts artsy/force#12590 because I noticed two issues while testing with "closed account" and "insufficient funds" accounts on staging:
1. After connecting the bank accounts and continuing to the Review step, I was correctly returned to the Payment step and shown an error message. However, the bank account that I had just connected was not visible in the list of bank accounts.
2. When I select another bank account from the list after recovering from the error in (1) the form is automatically re-submitted. The submission process takes several seconds, and when it is complete I see the Review step with the bank account from (1) selected.
I would like to test this again without these changes to confirm whether this is a regression or not.
=> Revert "[#FF] refactor: bank account auto-selection hook"

src/Apps/Order/Components/BankAccountPicker.tsx, src/Apps/Order/Routes/Payment/index.tsx, src/Apps/Order/Utils/orderUtils.ts
Reverts artsy/force#12597, which itself reverted #12590 to test some issues found while manually testing. It turns out that those issues existed before those changes were introduced, so I am re-merging them.
=> Revert "Revert "[#FF] refactor: bank account auto-selection hook""

src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButton.tsx, src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActionsSaveButtonV2.tsx, src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActionsSaveButtonV2.jest.tsx
This PR solves [ONYX-114]
Do not dispatch new artwork lists behavior when clicking on 'Watch lot' on artwork page. Demo below:
https://github.com/artsy/force/assets/3934579/a77bbc3f-4e46-4463-aeee-6e1ea2b6b425
[ONYX-114]: https://artsyproduct.atlassian.net/browse/ONYX-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(onyx-114): Do not dispatch new artwork lists behavior when clicking on 'Watch lot' on artwork page

src/Apps/Page/PageApp.tsx, src/Apps/Page/__tests__/PageApp.jest.tsx, src/__generated__/PageApp_Test_Query.graphql.ts, src/__generated__/PageApp_page.graphql.ts, src/__generated__/pageRoutes_PageQuery.graphql.ts
While working with the Auctions team to create a new page to store the conditions of sale of closed auctions, I noticed we are not respecting the [published field](https://github.com/artsy/gravity/blob/93c9a0374724525580f50f615b83b484df8feebc/app/models/domain/page.rb#L52) on the `Page` model. For example, this draft page is [unpublished](https://tools.artsy.net/pages/conditions-of-sale-archive-draft), but [publicly available](https://www.artsy.net/page/conditions-of-sale-archive-draft). 
This PR adds a guard that throws a `404` if the page is `unpublished: true` and the `user` is _not_ an admin user.
=> fix: only expose unpublished pages to admins

hokusai/staging.yml
This PR solves [PHIRE-102]
Prevent staging pods from running on Spot instances.
[PHIRE-102]: https://artsyproduct.atlassian.net/browse/PHIRE-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: do not use spot in staging

src/Components/SavedSearchAlert/Components/__tests__/ConfirmationModalHeader.jest.tsx, src/Components/SavedSearchAlert/ConfirmationArtworksGrid.tsx, src/Components/SavedSearchAlert/__tests__/ConfirmationArtworksGrid.jest.tsx, src/System/i18n/locales/en-US/translation.json
This PR solves [ONYX-148]
Per the discussion on ONYX-15 this updates the copy for the various cases that might be encountered in the Alert confirmation modal: many matches, few matches, one match, no matches.
|Many|Few|One|None|
|---|---|---|---|
|<img width="679" alt="many" src="https://github.com/artsy/force/assets/140521/5b8d5259-dc4a-4e2f-b7e2-5d2d55f40301">|<img width="683" alt="few" src="https://github.com/artsy/force/assets/140521/7b1e53dc-73d2-4936-8ad4-34472bb4836d">|<img width="683" alt="one" src="https://github.com/artsy/force/assets/140521/5d383a0a-0f50-4db2-a58c-74ba7c5e1082">|<img width="684" alt="0" src="https://github.com/artsy/force/assets/140521/ad2d374a-6050-42d3-8f96-d7d7a3a8b61c">|
[ONYX-148]: …
=> feat(alerts): update confirmation messages for various cases

src/Apps/Order/Routes/Shipping/index.tsx
This PR solves [EMI-1302]
This PR updates the address verification flow to only happen once. Previously, users could close the address verification modal and try again with a modified address. However, that creates a lot of noise and racks up additional usage charges from Smarty, so we are limiting it to 1 address verification per visit to the Shipping step of the checkout flow.
**Note:** If the user proceeds to the Payment step and returns to the Shipping step to edit their address, verification will be performed again.
[EMI-1302]: https://artsyproduct.atlassian.net/browse/EMI-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: only perform address verification once

hokusai/production.yml, hokusai/staging.yml
[PHIRE-111]
[We noticed](https://artsy.slack.com/archives/CA8SANW3W/p1689785076024629?thread_ts=1689359985.499589&cid=CA8SANW3W) a situation where 9 Spot instances were interrupted together, taking down most of prod `force-web` pods, causing elevated latency for ~5 minutes. This is not acceptable.
This PR is to try the idea of using two deployments: `force-web1`, `force-web2`.
`web1` runs on on-demand EC2 instances only, so its pods are guaranteed to exist.
`web2`, as the current single-deployment, can run on on-demand or Spot but prefers Spot. Its pods can be all on Spot and therefore can all go away.
With this setup, a baseline of pods (`web1`) is guaranteed, so the service may be degraded by Spot interruptions but it will never completely go down. …
=> feat: use two k8s deployments

src/Apps/Components/constants.ts
This PR solves [ONYX-161]
Since `Toasts` are now bottom-aligned in Force there is an edge case interaction between the `Toast` and `CookieConsentBanner` components.
Note that in the right-hand window, the cookie banner prevents the toasts from being visible.
https://github.com/artsy/force/assets/140521/68eecfd0-1ef7-4c87-b81c-c21be00d434f
Change to the toasts’ z-index ensures they are above the banner.
[ONYX-141]: https://artsyproduct.atlassian.net/browse/ONYX-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ONYX-161]: https://artsyproduct.atlassian.net/browse/ONYX-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(toasts): adjust position when cookie consent banner is displayed

src/Components/Search/NewSearch/NewSearchInputPills.tsx
This PR solves [ONYX-162]
|---|---|
| <video src="https://github.com/artsy/force/assets/3934579/b46987fb-0e40-4b3a-bb38-3ad2b6514b3d" /> | <video src="https://github.com/artsy/force/assets/3934579/4a5c9ad9-fd1a-4a74-bc0d-62496189cba3" /> |
[ONYX-162]: https://artsyproduct.atlassian.net/browse/ONYX-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(onyx-162): Fix pill navigation when it doesn’t remove the arrow button when scrolled all the way over to the right

src/Apps/Artist/Components/ArtistHeader/__tests__/ArtistHeader.jest.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingContext.tsx, src/Components/ProgressiveOnboarding/ProgressiveOnboardingFollowArtist.tsx, src/Components/ProgressiveOnboarding/__tests__/ProgressiveOnboardingContext.jest.tsx, src/Components/ProgressiveOnboarding/withProgressiveOnboardingCounts.tsx, src/Utils/Hooks/useAuthIntent/index.tsx
Closes [DIA-7](https://artsyproduct.atlassian.net/browse/DIA-7)
[DIA-7]: https://artsyproduct.atlassian.net/browse/DIA-7?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This PR displays the follow artist progressive onboarding tip to logged out users. Once the user is logged in it will also sync up the dismissal status with the logged out statuses and reset those. (Statuses are keyed to user IDs)
=> feat(progressive-onboarding): displays follow tip to logged out users

src/Apps/Order/Routes/Shipping/index.tsx, src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
This PR solves [EMI-1312](https://artsyproduct.atlassian.net/browse/EMI-1312)
We want to release address verification for US address only in the first iteration. This checks the country entered in the address form against the corresponding feature flag to determine enabling address verification or not.
I've created 2 feature flags [address_verification_us](https://unleash.artsy.net/projects/default/features/address_verification_us) and [address_verification_intl](https://unleash.artsy.net/projects/default/features/address_verification_intl), and will archive [the old one](https://unleash.artsy.net/projects/default/features/address_verification) after this.
[EMI-1312]: https://artsyproduct.atlassian.net/browse/EMI-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
=> Use different feature flags for US and international address verification

src/Components/ProgressiveOnboarding/withProgressiveOnboardingCounts.tsx
Currently Integrity is failing due to errors in onboarding which are strange, to say the least. As you're moving through the onboarding flow, it 'resets'. Sometimes there's what appear to be CSS errors indicative of an SSR mismatch. A little tricky to debug.
I'm not entirely sure how this would be causing the behavior we're seeing in staging. But this is 'correct' now and does appear to fix. Will continue to investigate/come up with a spec.
=> fix(progressive-onboarding): ensures we return correct ready states

src/Apps/CollectorProfile/Routes/Saves2/useCheckIfArtworkListsEnabled.ts, src/Apps/CollectorProfile/collectorProfileRoutes.tsx
This PR solves [FX-4809]
Currently the Artwork Lists feature is restricted to Artsy users and the Integrity user.
This PR removes that restriction, so that the enablement is governed _only_ by the Unleash feature flag.
Since that flag is set to true in staging and prod already, merging & deploying this PR will **release the feature to all users** in production.
(After that the Unleash flag can still be used for rollback, if at all necessary. Otherwise we will proceed eventually with the remaining [post launch steps](https://www.notion.so/artsy/Launch-Plan-a0d1f5a0bc814f439a4237a79965156a))
[FX-4809]: …
=> feat: remove user checks from artwork lists feature toggle

src/Apps/Order/Routes/Shipping/index.tsx, src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
This PR solves [EMI-1311](https://artsyproduct.atlassian.net/browse/EMI-1311)
The address verification modal gets triggered again after user choosing an address from it. Setting states is async. Checking if the verification needs to run right after the async set states will get the old value of the states, which triggers the address verification again.
Since on choosing an address we are ready to proceed to the next step, this directly move on to finalizing fulfillment, instead of checking again if address verification needs to run.
[EMI-1311]: https://artsyproduct.atlassian.net/browse/EMI-1311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: avoid double triggering address verification modal

src/Apps/Order/Routes/Shipping/index.tsx, src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
This PR solves [EMI-1316](https://artsyproduct.atlassian.net/browse/EMI-1316)
Basic form validation (e.g. required fields) should be performed before the address verification (e.g. calling Smarty API for suggestions). This changes the order to perform basic form validation first.
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details> 
[EMI-1316]: https://artsyproduct.atlassian.net/browse/EMI-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: perform basic form validation before address verification

src/Apps/Order/Components/AddressVerificationFlow.tsx, src/Apps/Order/Routes/Shipping/index.tsx
https://artsyproduct.atlassian.net/browse/EMI-1358
In [this PR](https://github.com/artsy/force/pull/12673), we removed the logic of automatically proceeding with a verified address due to a persistence bug. However, we _should_ continue when there are no changes being suggested, otherwise the user is forced to click again on the "Save and Continue" button after getting no feedback from the site (we don't show anything in the case of the user entering a perfect address)
In an ideal world, we should find a way of overcoming the persistence bug and refactoring the shipping index file.
Before (2 clicks):
https://github.com/artsy/force/assets/7518671/ee5931a2-5bd9-4682-9275-0d2fcbbce730
After (1 click): …
=> fix: auto-continue when no address change is suggested

src/Components/Onboarding/Components/OnboardingModal.tsx
Uses the existing modal close component which prevents the auto-focus ring styling.
=> fix(onboarding): uses default modal close component

src/Components/SavedSearchAlert/Components/ConfirmationStepFooter.tsx, src/Components/SavedSearchAlert/Components/__tests__/ConfirmationStepFooter.jest.tsx, src/Components/SavedSearchAlert/ConfirmationArtworksGrid.tsx, src/Components/SavedSearchAlert/ConfirmationStepModal.tsx
This PR solves [ONYX-158]
There is a little sense to display "See all matching works" button when all works are already on the screen. This PR hides this button when there are <= artworks that match criteria.
- [Review app](https://onyx-158.artsy.net/)
| No matches | Few matches | Many matches |
|---|---|---|
| ![No matches](https://github.com/artsy/force/assets/3934579/b7edbad9-45f7-43e0-b89b-d05e50748aee) | ![Few matches](https://github.com/artsy/force/assets/3934579/e324ae00-b6f3-4251-b885-2f65510810f3) | ![Many matches](https://github.com/artsy/force/assets/3934579/93753f75-a752-41e4-9038-ea219ac3066f) |
[ONYX-158]: https://artsyproduct.atlassian.net/browse/ONYX-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
=> fix(onyx-158): Hide See all matching works button on alerts confirmation step when <= 10 artworks match criteria

jest.config.js, package.json, yarn.lock
This PR adds jest-watch-typeahead which gives previews for what files will run when using pattern or test name matching with `jest. --watch`. It's a nicety but not necessary and may have been considered and rejected in the past. This is what it looks like:
=> chore: add jest-watch-typeahead

src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx, src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx
This PR reverts back display the price filter for all users.
=> fix: display the price filter for all users

src/Apps/Conversation/Components/Reply.tsx
The `Modal` component in Palette still has a story, to my horror. Let's remove it completely by deleting the last remaining Force reference.
=> refactor(conversations): replace old modal with new dialog component

src/Apps/Order/Components/AddressVerificationFlow.tsx, src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx, src/Apps/Order/Routes/Shipping/index.tsx, src/__generated__/AddressVerificationFlow_Test_Query.graphql.ts, src/__generated__/AddressVerificationFlow_verifyAddress.graphql.ts
This PR solves [EM-1295] and mostly completes  [EM-1355]. It includes an update of the changes in https://github.com/artsy/force/pull/12636
With this change the `address_verified_by` argument is sent to [exchange's `setShipping` mutation](https://github.com/artsy/exchange/blob/b9079eb9d9bb5b157fb55f8d67b950e9f3ab2a73/app/graphql/mutations/set_shipping.rb#L30), triggering the backend address verification job.
It also fixes some types and cleans up some development code.
To accomplish this I updated our boolean `addressHasBeenVerified` state variable to be a `null | "ARTSY" | "USER"` `addressVerifiedBy` variable - its presence means that it has been verified, and editing the form after saving sets the address as verified by the user …
=> chore: EM-1355 - send address verified by

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx, src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormDesktop.tsx, src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditFormMobile.tsx, src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertListItem.tsx, src/Apps/Settings/Routes/SavedSearchAlerts/types.ts, src/Components/SavedSearchAlert/Mutations/createSavedSearchAlert.ts, src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx, src/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx, src/Components/SavedSearchAlert/types.ts, src/__generated__/SavedSearchAlertListItem_item.graphql.ts, src/__generated__/SavedSearchAlertsAppRefetchQuery.graphql.ts, src/__generated__/SavedSearchAlertsApp_Test_Query.graphql.ts, src/__generated__/settingsRoutes_SavedSearchAlertsAppQuery.graphql.ts, src/__generated__/settingsRoutes_SavedSearchAlertsQuery.graphql.ts
Jira: [ONYX-227](https://artsyproduct.atlassian.net/browse/ONYX-227)
Allow collectors to create an alert without specifying a custom name and fallback to our generated display name which automatically displays the most relevant criteria at a glance.
With the feature flag enabled, the "Alert Name" input placeholder will be empty, and creating/updating an alert with no custom name will trigger the new generated default/fallback name.
**Next Steps**
- Open a similar PR for the app/eigen
- Update the create/edit flows to utilize the previewSavedSearch query field in Metaphysics so we can preview the generated name and formatted pills without formatting client-side.
https://www.loom.com/share/6ccad310d13248e5a66e9b0aff289eb9?sid=aa946cc3-ac57-490c-91b0-af74962d6 …
=> feat: use generated displayName for alerts without a custom name 

data/schema.graphql, src/Apps/Order/Components/AddressVerificationFlow.tsx, src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx, src/__generated__/AddressVerificationFlowQuery.graphql.ts, src/__generated__/AddressVerificationFlow_Test_Query.graphql.ts, src/__generated__/AddressVerificationFlow_verifyAddress.graphql.ts
Must be merged with https://github.com/artsy/metaphysics/pull/5179
Completes [EMI-1286]
This is a rebase of #12703. I put it in a separate PR for comparison in case i missed anything in the rebase to avoid force pushing over that work. The functionality is to handle an error from our address verification service and fall back to our confirmation modal without suggestions. Must be tested against https://github.com/artsy/metaphysics/pull/5179 locally and merged together, as it includes a major schema change used only by this component.
<details><summary>Summary of changes from #12703 </summary>
- rebased the @fladson's branch off of `main`, doing my best to fix merge conflicts
- added tests for the new behavior
- removed a `...loading...` message used in development
- added functionality to …
=> feat: handle gravity errors in metaphysics verify address query resolver

src/Apps/Show/Components/ShowArtworks.tsx
This PR solves [ONYX-137]
| --- | --- |
| <img width="988" alt="image" src="https://github.com/artsy/force/assets/36167539/95acec73-22c8-4db0-9f20-e7df9c4cbf93"> | <img width="979" alt="image" src="https://github.com/artsy/force/assets/36167539/1010caa3-3eb4-44ef-bac2-bb6a571c278d"> |
[ONYX-137]: https://artsyproduct.atlassian.net/browse/ONYX-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(ONYX-137): Remove "Recommended" artwork grid sort on show/booth pages

src/Components/ArtworkFilter/ArtworkFilterCreateAlert.tsx, src/Components/ArtworkFilter/ArtworkFilterDrawer.tsx, src/Components/ArtworkFilter/ArtworkFilters/ArtworkSortFilter2.tsx, src/Components/ArtworkFilter/__tests__/ArtworkFilter.jest.tsx, src/Components/ArtworkFilter/index.tsx
Closes [DIA-15](https://artsyproduct.atlassian.net/browse/DIA-15)
This enables the new filter grid via the `diamond_revised-artwork-filters`. (You can enable `diamond_revised-artwork-filters`) for the full experience.
This winds up being easy once we got rid of [the props drilled alerts stuff](https://github.com/artsy/force/pull/12714).
[DIA-15]: https://artsyproduct.atlassian.net/browse/DIA-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(artist): feature flags new artwork filter layout

src/Apps/Search/Routes/SearchResultsArtworks.tsx
This seems like a reasonable/correct fix, and does accomplish the intended result: without this the `context_page_owner_type` being set to Segment was `home`, and is now `search`.
Only thing I haven't fully traced (yet) is how this _was_ working before and if this or something analogous to it was inadvertently removed, or some other unrelated change had a side-effect, etc. If you're more familiar w/ any recent search work you might recall.
=> fix: use correct contextPageOwnerType on search results

yarn.lock
Lets bump `loader-utils` patch version!
=> chore: bump loader-utils

src/Apps/Order/Components/AddressVerificationFlow.tsx
This PR solves [EMI-1383]
The goal of this pr is to make a quick fix to the generic error modal in the address verification flow to have a light grey background, to make it look less editable based on feedback from QA. Here's the figma design for reference: https://www.figma.com/file/TainZ4UB7crFHJuYzhhx7d/Address-Verification?type=design&node-id=1-12&mode=design&t=emanoboiinbjD2Cn-0
[EMI-1383]: https://artsyproduct.atlassian.net/browse/EMI-1383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(EMI-1383): style error modal background color

src/Components/AddressForm.tsx, src/Components/__tests__/AddressForm.jest.tsx
This PR solves [EMI-1388](https://artsyproduct.atlassian.net/browse/EMI-1388)
Editing address after accepting suggested address resets form with original user inputs. This was due to the `initialState` in `useState` is only used in the initial render and ignored in re-render. This PR also adds a test to cover this scenario. More details in thread.
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details> 
[EMI-1388]: https://artsyproduct.atlassian.net/browse/EMI-1388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: preserve suggested address after editing

src/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx
Closes [DIA-60](https://artsyproduct.atlassian.net/browse/DIA-60)
At some breakpoints the figures would get truncated. We simply move to a layout that gives them more space, at a wider breakpoint.
[DIA-60]: https://artsyproduct.atlassian.net/browse/DIA-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(artist): triggers 2x2 layout at a wider breakpoint

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/Apps/Artist/Routes/AuctionResults/Components/MarketStats.tsx, src/Apps/Artist/Routes/Overview/ArtistOverviewRoute.tsx
I noticed Market Stats needs a bit spacing for mobile view
=> fix: add spacing for Market Stats for mobile view

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx, src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx, src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/SuggestedArtworksShelf.jest.tsx, src/__generated__/SuggestedArtworksShelfQuery.graphql.ts, src/__generated__/SuggestedArtworksShelf_Test_Query.graphql.ts
This PR solves [ONYX-130](https://artsyproduct.atlassian.net/browse/ONYX-130)
Adds Shelf for suggested artworks based on criteria.
[ONYX-130]: https://artsyproduct.atlassian.net/browse/ONYX-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ONYX-130): add shelf for suggested artworks

src/Apps/Order/Components/AddressVerificationFlow.tsx, src/Apps/Order/Components/__tests__/AddressVerificationFlow.jest.tsx, src/Apps/Order/Routes/Shipping/index.tsx, src/Apps/Order/Routes/__tests__/Shipping.jest.tsx
Resolves [EMI-1410] and _I think _ [EMI-1397] as well.
This PR solves a bug we currently hack around, creating a negative user experience. Paired with @damassi and @iskounen on it.
In https://github.com/artsy/force/pull/12684 and #12673 we changed the behavior of our address verification and submission flow to require an additional button click. Initially the thought was that we had a race condition with numerous `useState` variable settings, causing an old address to be sent immediately after confirmation.
While that fix solved the problem, we think the problem was actually that the `onChosenAddress` prop, an anonymous arrow function, was closuring the `finalizeFulfillment()` function, which itself was closuring the `setShipping()` …
=> fix: Extra save & continue click investigation fix

src/Apps/Order/Dialogs.tsx, src/Apps/Order/Hooks/__tests__/useStripePaymentBySetupIntentId.jest.tsx, src/Apps/Order/Hooks/useStripePaymentBySetupIntentId.tsx, src/Apps/Order/Routes/Payment/index.tsx
This PR solves [EMI-1284]
This is a companion PR to artsy/exchange#1733 that displays an error message to users if it doesn't pass backend validation in Exchange. (See the companion PR in Exchange for more context.)
[EMI-1284]: https://artsyproduct.atlassian.net/browse/EMI-1284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: show error message when setting payment by setup intent fails (EMI-1284)

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx, src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertTooltip.tsx, src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/SuggestedArtworksShelf.tsx, src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/ArtworkAuctionCreateAlertTooltip.jest.tsx, src/System/i18n/locales/en-US/translation.json
Update placeholder and copy for `ArtworkAuctionsCreateAlertHeader` feature.
=> fix(onyx): update copy and placeholder for Auction create alert header

src/Apps/Auction/Components/RegisterButton.tsx, src/System/Router/RouterLink.tsx, src/System/Router/__tests__/RouterLink.jest.tsx, src/Utils/__tests__/sanitizeURL.jest.ts, src/Utils/sanitizeURL.ts
Closes [DIA-102](https://artsyproduct.atlassian.net/browse/DIA-102)
Round Two
Here we return empty string if the function is passed empty string. Which — makes fine sense.
[DIA-102]: https://artsyproduct.atlassian.net/browse/DIA-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DIA-102): sanitize back hrefs

src/Apps/Artist/Components/ArtistBackLink.tsx, src/Apps/Show/Components/BackToFairBanner.tsx, src/Utils/__tests__/sanitizeURL.jest.ts, src/Utils/sanitizeURL.ts
Closes [DIA-102](https://artsyproduct.atlassian.net/browse/DIA-102) — for real this time.
No more global changes from me this week. However we now need to remain aware that this may sneak in as a problem again whenever we are utilizing query params. 
[DIA-102]: https://artsyproduct.atlassian.net/browse/DIA-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: prevents non url back links

src/Apps/Auction/AuctionApp.tsx, src/Apps/Auction/__tests__/AuctionApp.jest.tsx
See [Slack thread](https://artsy.slack.com/archives/C02JHHHKP5K/p1692814936087279) for more details.
The auction support chat was not ready to launch and it's currently broken in production. This quickly removes it for now until it's properly implemented.
=> fix: remove broken auction support chat until it's properly implemented

src/Apps/Artist/Components/ArtistHeader/ArtistHeader2.tsx, src/__generated__/ArtistApp_Test_Query.graphql.ts, src/__generated__/ArtistHeader2_artist.graphql.ts, src/__generated__/artistRoutes_ArtistAppQuery.graphql.ts
After much pain I'm back with a PR that reinstates the temporary verified rep line that we were using to QA this data on the new Artist page header. Looks like this:
=> Chore: Reinstate temporary verified rep line

src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/ArtworkAuctionCreateAlertHeader.tsx, src/Apps/Artwork/Components/ArtworkAuctionCreateAlertHeader/__tests__/ArtworkAuctionCreateAlertHeader.jest.tsx, src/__generated__/ArtworkAuctionCreateAlertHeader_Test_Query.graphql.ts, src/__generated__/ArtworkAuctionCreateAlertHeader_artwork.graphql.ts, src/__generated__/artworkRoutes_ArtworkQuery.graphql.ts
This PR solves [ONYX-267]
If an artwork doesn’t have suggested artworks (there are no such artworks based on pre-set criteria like artist, medium, attribution class, for sale) we should hide tooltip, shelf and “see more” button.
| with suggested artworks | without |
|---|---|
| ![Screenshot 2023-08-25 at 12 41 50](https://github.com/artsy/force/assets/3934579/a7bc242b-5c07-43c0-923a-44d5eac05278) | ![Screenshot 2023-08-25 at 12 41 41](https://github.com/artsy/force/assets/3934579/52ab084d-5ebb-449b-aa2c-34ede775293c) |
[ONYX-267]: https://artsyproduct.atlassian.net/browse/ONYX-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(onyx-267): Hide suggested artworks section if there are no suggested artworks

src/Components/ArtworkFilter/index.tsx
- Addresses [ONYX-240]
- [Slack Thread](https://artsy.slack.com/archives/C2TQ4PT8R/p1693219904639299)
This PR ensures that the Partners filter is updated correctly when there is a route change. This is done by adding a key to `BaseArtworkFilter` which will make sure all filters are reloaded when the artist changes.
https://github.com/artsy/force/assets/4691889/749a320e-2fd6-463e-9d93-de1ef1c5cdc4
[ONYX-240]: https://artsyproduct.atlassian.net/browse/ONYX-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Update Partners filter correctly on route change

src/Components/AuthDialog/AuthDialogContext.tsx, src/Components/AuthDialog/Components/AuthDialogSocial.tsx, src/Components/AuthDialog/Hooks/__tests__/useSocialAuthTracking.jest.ts, src/Components/AuthDialog/Hooks/useAuthDialogTracking.ts, src/Components/AuthDialog/Hooks/useSocialAuthTracking.ts
Closes [DIA-45](https://artsyproduct.atlassian.net/browse/DIA-45)
We lose the auth context once there's a full page load so we need to store the analytics options in the cookie that the social tracking picks up on then just pass those through to the tracking call.
[DIA-45]: https://artsyproduct.atlassian.net/browse/DIA-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(auth): threads through analytics options after social login/sign up

src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx, src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultsRoute.tsx, src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx, src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/SaleEndYearFilter.tsx, src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx, src/Apps/Artist/Routes/AuctionResults/__tests__/ArtistAuctionResults.jest.tsx, src/Apps/Artist/Utils/allowedAuctionResultFilters.ts, src/__generated__/ArtistAuctionResultsQuery.graphql.ts, src/__generated__/ArtistAuctionResultsRoute_artist.graphql.ts, src/__generated__/ArtistAuctionResults_Test_Query.graphql.ts, src/__generated__/ArtistAuctionResults_artist.graphql.ts, src/__generated__/artistRoutes_AuctionResultsQuery.graphql.ts
This PR solves [DIA-99]
Adds Sale Year filter for Auction Results page.
[DIA-99]: https://artsyproduct.atlassian.net/browse/DIA-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add sale end year filter

.vscode/settings.json, src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCreateArtworkAlert.jest.tsx, src/Apps/Artwork/Components/ArtworkSidebar/__tests__/CreateArtworkAlertSection.jest.tsx, src/Components/SavedSearchAlert/Components/SavedSearchAlertNameInput.tsx, src/Components/SavedSearchAlert/Components/__tests__/SavedSearchAlertNameInput.jest.tsx, src/Components/SavedSearchAlert/SavedSearchAlertModal.tsx, src/Components/SavedSearchAlert/__tests__/SavedSearchAlertModal.jest.tsx, src/__generated__/SavedSearchAlertNameInputQuery.graphql.ts, src/__generated__/SavedSearchAlertNameInput_Test_Query.graphql.ts, src/__generated__/SavedSearchAlertNameInput_previewSavedSearch.graphql.ts
This PR solves [ONYX-241]
Co-authored-by: @dblandin 
Wires up the new `previewSavedSearch.displayName` field from https://github.com/artsy/metaphysics/pull/5186 into the Alert creating and editing flows.
This feature is guarded by the [`onyx_force-fallback-to-generated-alert-names`](https://unleash.artsy.net/projects/default/features/onyx_force-fallback-to-generated-alert-names) feature flag, which is based on a user id strategy, so you might have to opt in to see these changes.
---
The MP-backed display name is shown (and updated realtime) as the placeholder in the alert form:
|Artist|Artwork|
|---|---|
|<video src="https://github.com/artsy/force/assets/140521/64c43a1c-c1f8-4cb2-abb7-cecd0a252602" />|<video …
=> feat(alerts): use generated displayName in create and edit forms

package.json, yarn.lock
This reverts commit 173de9d7d21b41a61f0c95bf83e87110afd51695.
This got merged automatically but before CI happened to run (momentarily 🍏 ?), and did indeed break something.
=> Revert "chore(deps): update dep typescript from 4.7.4 to v4.9.5"

src/Apps/Settings/Routes/SavedSearchAlerts/Components/SavedSearchAlertEditForm.tsx, src/Apps/Settings/Routes/SavedSearchAlerts/Components/__tests__/SavedSearchAlertEditForm.jest.tsx
The type of this PR is: **Featuer**
This PR solves [[ONYX-241](https://artsyproduct.atlassian.net/browse/ONYX-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)]
This PR enables the new generated default naming in the Alert edit form. https://github.com/artsy/force/pull/12751 only adds it to the create form.
I've disabled some tests because I couldn't fix them
- Fix tests.
[ONYX-241]: https://artsyproduct.atlassian.net/browse/ONYX-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Use new generated default name in alert edit form

src/Apps/Order/Dialogs.tsx, src/Apps/Order/Routes/Review/index.tsx, src/Apps/Order/Routes/__fixtures__/MutationResults/submitOrder.ts, src/Apps/Order/Routes/__tests__/Review.jest.tsx, src/Apps/Order/Utils/__tests__/getErrorDialogCopy.jest.tsx, src/Apps/Order/Utils/getErrorDialogCopy.tsx
The type of this PR is: feat
This PR solves [EMI-1328] by adding a special error handler for `currency_not_supported` decline codes when a hold fails on order submission so that we can show a better error message. Previously we were showing users the following error message in this scenario:
> **Charge failed** Payment has been declined. Please contact your card provider or bank institution, then press “Submit” again. Alternatively, use another payment method.
Now we will show:
> **Payment declined** This card is not compatible with the currency for this artwork. Please confirm with your card issuer if this currency can be supported, try a different payment method or contact [orders@artsy.net](mailto:orders@artsy.net).
---
This PR also adds a new utility method `getErrorDialogCopy` that …
=> feat: report currency not supported (EMI-1328)

src/Apps/Consign/Routes/ConsignmentInquiry/ConsignmentInquiry.tsx, src/Apps/Consign/Routes/ConsignmentInquiry/__tests__/ConsignmentInquiry.jest.tsx, src/Apps/Consign/Routes/SubmissionFlow/ContactInformation/ContactInformation.tsx, src/Components/TopContextBar.tsx, src/Utils/__tests__/sanitizeURL.jest.ts, src/Utils/sanitizeURL.ts
Closes [DIA-103](https://artsyproduct.atlassian.net/browse/DIA-103)
This is just a minor clean up related to the ticket wherein one could alter the query string to execute a script on click. This also now prevents someone from linking to an external site.
In the process I noticed some code that didn't actually work and uncovered some bugs in the consignment flow.
[DIA-103]: https://artsyproduct.atlassian.net/browse/DIA-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(dia-103): ensures top context bar only links to internal routes

src/Apps/Order/Routes/Shipping/index.tsx, src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts, src/Apps/Order/Routes/__tests__/Shipping.jest.tsx, src/Apps/Order/Utils/getErrorDialogCopy.tsx
This PR solves [EMI-1332]
This PR is a follow-up to artsy/exchange#1763 that displays an error message for the error that is newly being returned from Exchange when a user submits a non-existing shipping address.
It also makes use of the new `getErrorDialogCopy` function created in #12803 to house the new copy. That function is still being tested out as I work on checkout dead-ends so any feedback on it is appreciated.
[EMI-1332]: https://artsyproduct.atlassian.net/browse/EMI-1332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: report destination_could_not_be_geocoded error (EMI-1332)
